### ISSUE TITLE
Application metrics are not scraped when mTLS is enabled

### ISSUE THREAD

**Issue by meteatamel** [istio/istio#10544] opened 2018-12-18 07:58 UTC
**Describe the bug**
When mTLS is enabled, application/custom metrics from my pods are not scraped by Istio Prometheus. Instead I get a certificate issue, see screenshot. Restarting Prometheus pod is the workaround.

**Expected behavior**
Application/custom metrics should be scraped with or without mTLS enabled.

**Steps to reproduce the bug**
Enable mTLS, send custom metrics from a pod and check /metrics endpoint in Prometheus to see the error.

**Version**
Istio: 1.0.5

**Installation**
Using istio-demo-auth.yaml

**Environment**
GKE

**Comment by bianpengyuan** [comment] 2018-12-18 08:04
Root cause is that secret volume is not ready when prom starts and prom does not retry after initialization. Fix is tracked in #10528. @meteatamel Are you ok to close this one as a dup?

**Comment by meteatamel** [comment] 2018-12-18 08:06
Sure, thanks!

**Closed** 2018-12-18 08:12 UTC
