### ISSUE TITLE
Mixer needs to report changing url path.

### ISSUE THREAD

**Issue by JacksChoco** [istio/istio#20982] opened 2020-02-10 05:15 UTC
**Describe the feature request**
mixer collect request count. if this metric include request.url_path. url_path has a large variety. mixer make too many metric. As a result, my prometheus used large memory. so mixer need to replace uri path. 
for example 
`/api/v1/user/123` -> `/api/v1/user/{}`
`/api/v1/account/user/1234` -> `api/v1/account/user/{}`

**Describe alternatives you've considered**
I made function at mixer/pkg/lang/externs.go (https://github.com/JacksChoco/istio/commit/bd71c9eabfc6919e79334461650a92cbbd4a34f9#diff-6c02b536e62d7221593ad595c4e9479a) but I don't know if this is the right way.

**Additional context**

**Comment by douglas-reid** [comment] 2020-02-11 00:55
I don't believe that this feature will make it into Mixer, so we probably want to rename / collapse this FR with others around supporting operation extractions, and start planning for v2 support.

FWIW, this functionality was intended to come via OpenAPI support, which was abandoned (no real progress made). There is obvious utility in providing such functionality.

/cc @mandarjog

**Comment by JacksChoco** [comment] 2020-02-11 03:07
Do you think this feature is made at envoy?

**Comment by douglas-reid** [comment] 2020-02-11 18:51
@JacksChoco given that Mixer will be deprecated with the 1.5 release, I think any changes to support additional reporting ultimately need to be handled in a proxy extension. What remains is how we want to approach providing this functionality in a generic and extensible manner.

**Comment by douglas-reid** [comment] 2020-05-05 01:51
@mandarjog has been working on adding this feature to the v2 extensions. it should be available in 1.6 releases. that work is being tracked elsewhere. i'm gonna close this for now.

**Closed by douglas-reid** 2020-05-05 01:51 UTC
Labels: area/policies and telemetry, kind/enhancement
