### ISSUE TITLE
istioctl manifest apply/generate should be able to use in-cluster CR

### ISSUE THREAD

**Issue by ostromart** [istio/istio#19155] opened 2019-11-23 01:08 UTC
Add a flag to use in-cluster CR. This is useful for cases where user is migrating from controller to (or back to) istioctl.

**Comment by esnible** [comment] 2020-03-02 15:09
@elfinhe are you working on this?

@ostromart is there a design for this?  is the proposal to add a `--use-kube` flag, and if supplied we would use that as the CR?  I like this idea a lot.

This Issue may be affected when we go to multiple control planes.  (There will be >1 CR, and we must identify the correct one that works with the other options for choosing which CR to upgrade.)

Related: https://github.com/istio/istio/issues/20000 , which tracks my desire to have istioctl ALWAYS write the cluster to the CR, so that the users who are not using the controller can have good defaults performing additional updates.

**Comment by elfinhe** [comment] 2020-03-02 18:56
Thanks Ed for the heads up. I didn't get a chance to work on it (and probably not in the following month, sorry). Please feel free to assign someone else.

**Comment by esnible** [comment] 2020-04-28 15:54
https://github.com/istio/istio/issues/23183 may be a duplicate of this.  Closing this in favor of the newer one.

**Closed by esnible** 2020-04-28 15:54 UTC
Labels: area/environments/operator, area/user experience, kind/enhancement
