### ISSUE TITLE
Apache Spark issue with istio

### ISSUE THREAD

**Issue by gothicfann** [istio/istio#27900] opened 2020-10-12 23:47 UTC
**Bug description**
I tried to install Spark using bitnami chart with default values in istio enabled namespace:
https://github.com/bitnami/charts/tree/master/bitnami/spark
spark workers cannot communicate with master using spark rpc protocol. 
**workers envoy access logs:**
```
2020-10-12T23:19:46.484430533Z 2020-10-12T23:19:46.484180Z	info	Envoy proxy is ready
2020-10-12T23:19:49.597606234Z [2020-10-12T23:19:49.589Z] "- - -" 0 UH "-" "-" 0 0 7 - "-" "-" "-" "-" "-" - - 10.106.150.225:7077 172.17.0.5:45878 - -
2020-10-12T23:19:59.60201629Z [2020-10-12T23:19:55.583Z] "- - -" 0 UF,URX "-" "-" 0 0 18 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:45938 - -
2020-10-12T23:20:09.601992159Z [2020-10-12T23:20:01.564Z] "- - -" 0 UF,URX "-" "-" 0 0 2 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:45992 - -
2020-10-12T23:20:09.602059689Z [2020-10-12T23:20:07.581Z] "- - -" 0 UF,URX "-" "-" 0 0 4 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:46048 - -
2020-10-12T23:20:19.602430225Z [2020-10-12T23:20:13.564Z] "- - -" 0 UF,URX "-" "-" 0 0 3 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:46102 - -
2020-10-12T23:20:19.602460947Z [2020-10-12T23:20:19.580Z] "- - -" 0 UF,URX "-" "-" 0 0 10 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:46160 - -
2020-10-12T23:20:59.604970891Z [2020-10-12T23:20:52.589Z] "- - -" 0 UF,URX "-" "-" 0 0 4 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:46532 - -
2020-10-12T23:21:29.606355696Z [2020-10-12T23:21:25.572Z] "- - -" 0 UF,URX "-" "-" 0 0 3 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:46898 - -
2020-10-12T23:21:59.60615571Z [2020-10-12T23:21:58.593Z] "- - -" 0 UF,URX "-" "-" 0 0 9 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:47242 - -
2020-10-12T23:22:39.607634311Z [2020-10-12T23:22:31.589Z] "- - -" 0 UF,URX "-" "-" 0 0 6 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:47594 - -
2020-10-12T23:23:09.608354321Z [2020-10-12T23:23:04.591Z] "- - -" 0 UF,URX "-" "-" 0 0 6 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:47936 - -
2020-10-12T23:23:39.607643696Z [2020-10-12T23:23:37.589Z] "- - -" 0 UF,URX "-" "-" 0 0 5 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:48308 - -
2020-10-12T23:24:19.607935687Z [2020-10-12T23:24:10.584Z] "- - -" 0 UF,URX "-" "-" 0 0 11 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:48668 - -
2020-10-12T23:24:49.609418102Z [2020-10-12T23:24:43.587Z] "- - -" 0 UF,URX "-" "-" 0 0 8 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:49034 - -
2020-10-12T23:25:19.610426859Z [2020-10-12T23:25:16.590Z] "- - -" 0 UF,URX "-" "-" 0 0 5 - "-" "-" "-" "-" "172.17.0.6:7077" outbound|7077||spark-master-svc.default.svc.cluster.local - 10.106.150.225:7077 172.17.0.5:49408 - -
```
**workers app logs:**
```
2020-10-12T23:26:23.515216868Z [38;5;6m [38;5;5m23:26:23.51 [0m
2020-10-12T23:26:23.51614386Z [38;5;6m [38;5;5m23:26:23.51 [0m[1mWelcome to the Bitnami spark container[0m
2020-10-12T23:26:23.517086864Z [38;5;6m [38;5;5m23:26:23.51 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-spark[0m
2020-10-12T23:26:23.517997868Z [38;5;6m [38;5;5m23:26:23.51 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-spark/issues[0m
2020-10-12T23:26:23.519027225Z [38;5;6m [38;5;5m23:26:23.51 [0m
2020-10-12T23:26:23.524658485Z [38;5;6m [38;5;5m23:26:23.52 [0m[38;5;2mINFO [0m ==> ** Starting Spark setup **
2020-10-12T23:26:23.536920006Z [38;5;6m [38;5;5m23:26:23.53 [0m[38;5;2mINFO [0m ==> Generating Spark configuration file...
2020-10-12T23:26:23.540673381Z [38;5;6m [38;5;5m23:26:23.54 [0m[38;5;2mINFO [0m ==> ** Spark setup finished! **
2020-10-12T23:26:23.540689587Z 
2020-10-12T23:26:23.548148905Z [38;5;6m [38;5;5m23:26:23.54 [0m[38;5;2mINFO [0m ==> ** Starting Spark in worker mode **
2020-10-12T23:26:23.558059753Z starting org.apache.spark.deploy.worker.Worker, logging to /opt/bitnami/spark/logs/spark--org.apache.spark.deploy.worker.Worker-1-spark-worker-0.out
2020-10-12T23:26:23.639031571Z Spark Command: /opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1g org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark-master-svc:7077
2020-10-12T23:26:23.639052558Z ========================================
2020-10-12T23:26:24.174937694Z Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2020-10-12T23:26:24.184237867Z 20/10/12 23:26:24 INFO Worker: Started daemon with process name: 36@spark-worker-0.spark-headless.default.svc.cluster.local
2020-10-12T23:26:24.201074938Z 20/10/12 23:26:24 INFO SignalUtils: Registered signal handler for TERM
2020-10-12T23:26:24.201824717Z 20/10/12 23:26:24 INFO SignalUtils: Registered signal handler for HUP
2020-10-12T23:26:24.201995203Z 20/10/12 23:26:24 INFO SignalUtils: Registered signal handler for INT
2020-10-12T23:26:24.529713443Z 20/10/12 23:26:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-10-12T23:26:24.580617888Z 20/10/12 23:26:24 INFO SecurityManager: Changing view acls to: spark
2020-10-12T23:26:24.581465592Z 20/10/12 23:26:24 INFO SecurityManager: Changing modify acls to: spark
2020-10-12T23:26:24.583364011Z 20/10/12 23:26:24 INFO SecurityManager: Changing view acls groups to: 
2020-10-12T23:26:24.583837749Z 20/10/12 23:26:24 INFO SecurityManager: Changing modify acls groups to: 
2020-10-12T23:26:24.584703005Z 20/10/12 23:26:24 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
2020-10-12T23:26:24.913880578Z 20/10/12 23:26:24 INFO Utils: Successfully started service 'sparkWorker' on port 40001.
2020-10-12T23:26:25.084691474Z 20/10/12 23:26:25 INFO Worker: Starting Spark worker 172.17.0.5:40001 with 1 cores, 6.6 GiB RAM
2020-10-12T23:26:25.089845121Z 20/10/12 23:26:25 INFO Worker: Running Spark version 3.0.1
2020-10-12T23:26:25.090382436Z 20/10/12 23:26:25 INFO Worker: Spark home: /opt/bitnami/spark
2020-10-12T23:26:25.107156574Z 20/10/12 23:26:25 INFO ResourceUtils: ==============================================================
2020-10-12T23:26:25.108372044Z 20/10/12 23:26:25 INFO ResourceUtils: Resources for spark.worker:
2020-10-12T23:26:25.108420995Z 
2020-10-12T23:26:25.108773081Z 20/10/12 23:26:25 INFO ResourceUtils: ==============================================================
2020-10-12T23:26:25.233558835Z 20/10/12 23:26:25 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
2020-10-12T23:26:25.268689284Z 20/10/12 23:26:25 INFO WorkerWebUI: Bound WorkerWebUI to 0.0.0.0, and started at http://spark-worker-0.spark-headless.default.svc.cluster.local:8081
2020-10-12T23:26:25.274713863Z 20/10/12 23:26:25 INFO Worker: Connecting to master spark-master-svc:7077...
2020-10-12T23:26:25.37374162Z 20/10/12 23:26:25 INFO TransportClientFactory: Successfully created connection to spark-master-svc/10.106.150.225:7077 after 50 ms (0 ms spent in bootstraps)
2020-10-12T23:26:25.409149141Z 20/10/12 23:26:25 WARN TransportChannelHandler: Exception in connection from spark-master-svc/10.106.150.225:7077
2020-10-12T23:26:25.409174852Z java.io.IOException: Connection reset by peer
2020-10-12T23:26:25.409180555Z 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2020-10-12T23:26:25.409185388Z 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
2020-10-12T23:26:25.409189732Z 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
2020-10-12T23:26:25.40919409Z 	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
2020-10-12T23:26:25.409198553Z 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
2020-10-12T23:26:25.409203093Z 	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
2020-10-12T23:26:25.409207467Z 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
2020-10-12T23:26:25.40921176Z 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
2020-10-12T23:26:25.409216114Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
2020-10-12T23:26:25.409220621Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
2020-10-12T23:26:25.409225304Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2020-10-12T23:26:25.409229816Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2020-10-12T23:26:25.409234265Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2020-10-12T23:26:25.409249603Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2020-10-12T23:26:25.409254598Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2020-10-12T23:26:25.409259072Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2020-10-12T23:26:25.409263625Z 	at java.lang.Thread.run(Thread.java:748)
2020-10-12T23:26:25.4102625Z 20/10/12 23:26:25 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from spark-master-svc/10.106.150.225:7077 is closed
2020-10-12T23:26:25.41756288Z 20/10/12 23:26:25 WARN Worker: Failed to connect to master spark-master-svc:7077
2020-10-12T23:26:25.417584108Z org.apache.spark.SparkException: Exception thrown in awaitResult: 
2020-10-12T23:26:25.417588372Z 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:302)
2020-10-12T23:26:25.41759168Z 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
2020-10-12T23:26:25.417594879Z 	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
2020-10-12T23:26:25.417597975Z 	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
2020-10-12T23:26:25.417601004Z 	at org.apache.spark.deploy.worker.Worker$$anon$1.run(Worker.scala:277)
2020-10-12T23:26:25.417604091Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-10-12T23:26:25.417619978Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-10-12T23:26:25.417624191Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-10-12T23:26:25.417627353Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-10-12T23:26:25.417630457Z 	at java.lang.Thread.run(Thread.java:748)
2020-10-12T23:26:25.4176334Z Caused by: java.io.IOException: Connection reset by peer
2020-10-12T23:26:25.41763646Z 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2020-10-12T23:26:25.417639532Z 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
2020-10-12T23:26:25.417642551Z 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
2020-10-12T23:26:25.417645525Z 	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
2020-10-12T23:26:25.417648478Z 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
2020-10-12T23:26:25.417651484Z 	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
2020-10-12T23:26:25.417654509Z 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
2020-10-12T23:26:25.417666034Z 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
2020-10-12T23:26:25.417669745Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
2020-10-12T23:26:25.417680601Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
2020-10-12T23:26:25.417695032Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2020-10-12T23:26:25.417698886Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2020-10-12T23:26:25.417702075Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2020-10-12T23:26:25.417705177Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2020-10-12T23:26:25.417708344Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2020-10-12T23:26:25.417712263Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2020-10-12T23:26:25.417715465Z 	... 1 more
2020-10-12T23:26:33.28301265Z 20/10/12 23:26:33 INFO Worker: Retrying connection to master (attempt # 1)
2020-10-12T23:26:33.283675082Z 20/10/12 23:26:33 INFO Worker: Connecting to master spark-master-svc:7077...
2020-10-12T23:26:33.285029889Z 20/10/12 23:26:33 INFO TransportClientFactory: Found inactive connection to spark-master-svc/10.106.150.225:7077, creating a new one.
2020-10-12T23:26:33.287335156Z 20/10/12 23:26:33 INFO TransportClientFactory: Successfully created connection to spark-master-svc/10.106.150.225:7077 after 2 ms (0 ms spent in bootstraps)
2020-10-12T23:26:33.290964099Z 20/10/12 23:26:33 WARN TransportChannelHandler: Exception in connection from spark-master-svc/10.106.150.225:7077
2020-10-12T23:26:33.290989631Z java.io.IOException: Connection reset by peer
```
**master envoy access logs:**
```
2020-10-12T23:28:45.635604665Z [2020-10-12T23:28:40.007Z] "- - -" 0 UF,URX "-" "-" 0 0 7 - "-" "-" "-" "-" "127.0.0.1:7077" inbound|7077|cluster|spark-master-svc.default.svc.cluster.local - 172.17.0.6:7077 172.17.0.7:40782 - -
2020-10-12T23:28:45.635677332Z [2020-10-12T23:28:45.289Z] "- - -" 0 UF,URX "-" "-" 0 0 1 - "-" "-" "-" "-" "127.0.0.1:7077" inbound|7077|cluster|spark-master-svc.default.svc.cluster.local - 172.17.0.6:7077 172.17.0.5:34914 - -
2020-10-12T23:28:55.636260462Z [2020-10-12T23:28:45.989Z] "- - -" 0 UF,URX "-" "-" 0 0 1 - "-" "-" "-" "-" "127.0.0.1:7077" inbound|7077|cluster|spark-master-svc.default.svc.cluster.local - 172.17.0.6:7077 172.17.0.7:40860 - -
2020-10-12T23:28:55.636330126Z [2020-10-12T23:28:52.000Z] "- - -" 0 UF,URX "-" "-" 0 0 1 - "-" "-" "-" "-" "127.0.0.1:7077" inbound|7077|cluster|spark-master-svc.default.svc.cluster.local - 172.17.0.6:7077 172.17.0.7:40924 - -
2020-10-12T23:29:05.636224878Z [2020-10-12T23:28:57.980Z] "- - -" 0 UF,URX "-" "-" 0 0 0 - "-" "-" "-" "-" "127.0.0.1:7077" inbound|7077|cluster|spark-master-svc.default.svc.cluster.local - 172.17.0.6:7077 172.17.0.7:40992 - -
2020-10-12T23:29:35.637224934Z [2020-10-12T23:29:31.302Z] "- - -" 0 UF,URX "-" "-" 0 0 1 - "-" "-" "-" "-" "127.0.0.1:7077" inbound|7077|cluster|spark-master-svc.default.svc.cluster.local - 172.17.0.6:7077 172.17.0.5:35422 - -
2020-10-12T23:29:35.637295762Z [2020-10-12T23:29:33.001Z] "- - -" 0 UF,URX "-" "-" 0 0 1 - "-" "-" "-" "-" "127.0.0.1:7077" inbound|7077|cluster|spark-master-svc.default.svc.cluster.local - 172.17.0.6:7077 172.17.0.7:41372 - -
```
**master app logs:**
```
2020-10-12T23:19:22.133670797Z [38;5;6m [38;5;5m23:19:22.13 [0m
2020-10-12T23:19:22.134625845Z [38;5;6m [38;5;5m23:19:22.13 [0m[1mWelcome to the Bitnami spark container[0m
2020-10-12T23:19:22.135525431Z [38;5;6m [38;5;5m23:19:22.13 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-spark[0m
2020-10-12T23:19:22.136876464Z [38;5;6m [38;5;5m23:19:22.13 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-spark/issues[0m
2020-10-12T23:19:22.140935814Z [38;5;6m [38;5;5m23:19:22.13 [0m
2020-10-12T23:19:22.144890379Z [38;5;6m [38;5;5m23:19:22.14 [0m[38;5;2mINFO [0m ==> ** Starting Spark setup **
2020-10-12T23:19:22.156922639Z [38;5;6m [38;5;5m23:19:22.15 [0m[38;5;2mINFO [0m ==> Generating Spark configuration file...
2020-10-12T23:19:22.160977024Z [38;5;6m [38;5;5m23:19:22.16 [0m[38;5;2mINFO [0m ==> ** Spark setup finished! **
2020-10-12T23:19:22.160992687Z 
2020-10-12T23:19:22.168267251Z [38;5;6m [38;5;5m23:19:22.16 [0m[38;5;2mINFO [0m ==> ** Starting Spark in master mode **
2020-10-12T23:19:22.181434131Z starting org.apache.spark.deploy.master.Master, logging to /opt/bitnami/spark/logs/spark--org.apache.spark.deploy.master.Master-1-spark-master-0.out
2020-10-12T23:19:22.249463647Z Spark Command: /opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1g org.apache.spark.deploy.master.Master --host spark-master-0.spark-headless.default.svc.cluster.local --port 7077 --webui-port 8080
2020-10-12T23:19:22.249484593Z ========================================
2020-10-12T23:19:22.843147562Z Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2020-10-12T23:19:22.853526449Z 20/10/12 23:19:22 INFO Master: Started daemon with process name: 40@spark-master-0.spark-headless.default.svc.cluster.local
2020-10-12T23:19:22.868808815Z 20/10/12 23:19:22 INFO SignalUtils: Registered signal handler for TERM
2020-10-12T23:19:22.869902188Z 20/10/12 23:19:22 INFO SignalUtils: Registered signal handler for HUP
2020-10-12T23:19:22.870005644Z 20/10/12 23:19:22 INFO SignalUtils: Registered signal handler for INT
2020-10-12T23:19:23.159750646Z 20/10/12 23:19:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-10-12T23:19:23.207397422Z 20/10/12 23:19:23 INFO SecurityManager: Changing view acls to: spark
2020-10-12T23:19:23.20777644Z 20/10/12 23:19:23 INFO SecurityManager: Changing modify acls to: spark
2020-10-12T23:19:23.208152724Z 20/10/12 23:19:23 INFO SecurityManager: Changing view acls groups to: 
2020-10-12T23:19:23.20855362Z 20/10/12 23:19:23 INFO SecurityManager: Changing modify acls groups to: 
2020-10-12T23:19:23.208993032Z 20/10/12 23:19:23 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
2020-10-12T23:19:23.513487975Z 20/10/12 23:19:23 INFO Utils: Successfully started service 'sparkMaster' on port 7077.
2020-10-12T23:19:23.53576886Z 20/10/12 23:19:23 INFO Master: Starting Spark master at spark://spark-master-0.spark-headless.default.svc.cluster.local:7077
2020-10-12T23:19:23.540343238Z 20/10/12 23:19:23 INFO Master: Running Spark version 3.0.1
2020-10-12T23:19:23.672044996Z 20/10/12 23:19:23 INFO Utils: Successfully started service 'MasterUI' on port 8080.
2020-10-12T23:19:23.719952202Z 20/10/12 23:19:23 INFO MasterWebUI: Bound MasterWebUI to 0.0.0.0, and started at http://spark-master-0.spark-headless.default.svc.cluster.local:8080
2020-10-12T23:19:23.869948708Z 20/10/12 23:19:23 INFO Master: I have been elected leader! New state: ALIVE
```

**Steps tested:**
1. tried to change port name on spark-master-svc (http, http2, grpc, tcp...) nothing worked.
2. disabled mTLS on namespace and created DestinationRule to service not to use mTLS (did not work)
3. Without sidecar injection everything works fine.

**Note**: I am running this helm chart with default values.

Please help to solve this issue, or suggest any workaround for it. I need it ASAP

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Workers should communicate and register with master.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**\

```
istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (4 proxies)
```
```
kubectl version --short
Client Version: v1.19.2
Server Version: v1.18.3
```
```
helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

**How was Istio installed?**
default profile

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE, minikube

[cluster_state_archive.zip](https://github.com/istio/istio/files/5368112/cluster_state_archive.zip)

**Comment by gothicfann** [comment] 2020-10-13 09:47
Any help or response please

**Comment by abhiramkolli** [comment] 2020-10-14 04:25
I have the same issue. Any comments on the above?

**Comment by auswells** [comment] 2020-10-14 12:16
I ran into the same issue and for now I have bypassed redirection by adding the following annotation to the master
```
traffic.sidecar.istio.io/excludeInboundPorts: "7077"
```
And the following annotation to the workers
```
traffic.sidecar.istio.io/excludeOutboundPorts: "7077"
```

**Comment by gothicfann** [comment] 2020-10-14 15:54
@auswells Yes but in that case we cant get telemetry data in kiali because the traffic is never logged. :(

**Comment by Secretions** [comment] 2020-11-18 20:27
I'm trying to figure out this same thing. I honestly don't grok why setting it to tcp wouldn't fix it--shouldn't it then be just passing the traffic verbatim and be pretty much compatible with any tcp protocol?

**Comment by Secretions** [comment] 2020-11-24 03:12
After looking into this further, it seems it's related to the fact that the spark master doesn't listen on localhost, but Istio requires it. There was recently a PR (#28178) that makes the sidecar configurable in such a way that this can work, though it wasn't included in either of the most recent releases (1.7.5 or 1.8.0) that were released after the commit.

Is there a rough timeline for when this fix will make into a released version of Istio (or expected version)?

**Comment by bleggett** [comment] 2021-01-06 19:04
> After looking into this further, it seems it's related to the fact that the spark master doesn't listen on localhost, but Istio requires it. There was recently a PR (#28178) that makes the sidecar configurable in such a way that this can work, though it wasn't included in either of the most recent releases (1.7.5 or 1.8.0) that were released after the commit.
> 
> Is there a rough timeline for when this fix will make into a released version of Istio (or expected version)?

Can Spark masters be configured to listen on localhost? That might be simpler.

**Comment by bleggett** [comment] 2021-01-08 00:06
Confirmed that the Bitnami Spark installation (or any Spark standalone setup) will work in Istio 1.8.1 just fine if you set SPARK_MASTER_HOST to localhost. Workers are able to register and jobs are distributed.

```
master:
    extraEnvVars:
     - name: SPARK_MASTER_HOST
       value: "127.0.0.1"
```

**Comment by howardjohn** [comment] 2021-02-16 20:30
If the issue is just the bind, this will work out of the box in a future Istio version. See https://docs.google.com/document/d/1j-5_XpeMTnT9mV_8dbSOeU7rfH-5YNtN_JJFZ2mmQ_w/edit# for info

**Comment by howardjohn** [comment] 2021-03-03 18:57
This should be fixed by #30226. If you still see issues on master (https://github.com/istio/istio/wiki/Dev%20Builds) please reopen!

**Closed by howardjohn** 2021-03-03 18:57 UTC
Labels: area/networking, feature/Virtual-machine, kind/enhancement

**Comment by kirandeshpande1990** [comment] 2021-05-19 14:08
Thanks I've followed above comments and added the env variable. Post that, the spark streaming job submitted in cluster/client mode fails exactly after an hour of running. The application is getting into "Finished" status. I have the latest istio 1.9 installed with spark 2.4.6


Logs:
2021-05-19 06:09:06,975 [dispatcher-event-loop-1] WARN  (Logging.scala:66) - Connection to 127.0.0.1:7077 failed; waiting for master to reconnect...
   2021-05-19 06:09:06,977 [dispatcher-event-loop-1] WARN  (Logging.scala:66) - Disconnected from Spark cluster! Waiting for reconnection...
   2021-05-19 06:09:06,984 [SIGTERM handler] ERROR (SignalUtils.scala:43) - RECEIVED SIGNAL TERM
   2021-05-19 06:09:07,618 [dispatcher-event-loop-0] ERROR (Logging.scala:70) - Lost executor 2 on spark-worker-1.spark-headless.nuance-preprod-neap.svc.cluster.local: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
   2021-05-19 06:09:07,623 [dispatcher-event-loop-0] ERROR (Logging.scala:70) - Lost executor 1 on spark-worker-2.spark-headless.nuance-preprod-neap.svc.cluster.local: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
   2021-05-19 06:09:07,623 [dispatcher-event-loop-0] ERROR (Logging.scala:70) - Lost executor 0 on spark-worker-0.spark-headless.nuance-preprod-neap.svc.cluster.local: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
   2021-05-19 06:09:07,636 [dispatcher-event-loop-0] WARN  (Logging.scala:66) - No more replicas available for rdd_41_30 !

Any suggestions would be greatly appreciated.

**Comment by puneetloya** [comment] 2021-05-19 14:31
> 2021-05-19 06:09:06,977 [dispatcher-event-loop-1] WARN (Logging.scala:66) - Disconnected from Spark cluster! Waiting for reconnection...

These suggestions are guesses but may be worth a try:
- Increase `spark.network.timeout` or other timeouts. Also have more retries. If you are using the default Dockerfile provided in spark distribution, you can add something like this(in `entrypoint.sh`):
    ```sh
          # Execute the container CMD under tini for better hygiene
          retries=5
          if [ -n "$SPARK_ENVOY_RETRIES" ]; then
              retries=$SPARK_ENVOY_RETRIES
          fi
          while [[ ${retries} -ge 0 ]]
          do
            /usr/bin/tini -s -- "${CMD[@]}" && break
            ((retries-=1))
            echo "Failed to start ${SPARK_K8S_CMD}. ${retries} reties left"
            sleep 15
          done
    ```
- Destination rules that can be tweaked.
https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings

**Comment by aodj** [comment] 2021-05-28 15:37
> Thanks I've followed above comments and added the env variable. Post that, the spark streaming job submitted in cluster/client mode fails exactly after an hour of running. The application is getting into "Finished" status. I have the latest istio 1.9 installed with spark 2.4.6
>  ...
> Any suggestions would be greatly appreciated.

I encountered something similar to do with Istio terminating long running connections after an hour. I found [this StackOverflow question](https://stackoverflow.com/questions/63843610/istio-proxy-closing-long-running-tcp-connection-after-1-hour) helpful in that it directed me to [this answer](https://stackoverflow.com/a/65285867/438017) about adding an EnvoyFilters for the inbound and outbound connections.
