### ISSUE TITLE
Upgrade istio from 1.4.7 to 1.5.10 using kubectl missing istiod

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#29755] opened 2020-12-23 11:56 UTC
Hi,
We are trying to upgrade istio from 1.4.7v to 1.5.10 (in order to be able to go over newset version later)
As i know the main changes in 1.5.10 is the refactoring of the control plan and moving part of it to istiod,
When we upgrade istio using `helm template` & `kubectl` we notice that there is no `istiod` component, and instead of it we have the regular components ( pilot, citadel,...),
i know that the old multi-components control plan model is still there, but how can I switch to the new one using helm and kubectl ? without causing to any downtime?

Thanks

**Comment by howardjohn** [comment] 2020-12-24 02:44
Istiod is added only in the istioctl install, the helm install was deprecated and thus not updated for Istiod

**Comment by howardjohn** [comment] 2020-12-28 15:36
Closing this as working as intended. Thanks

**Closed by howardjohn** 2020-12-28 15:36 UTC
Labels: area/environments
