### ISSUE TITLE
Incorrect service grafana dashboard with traffic split

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#13626] opened 2019-04-25 19:20 UTC
With traffic splitting enabled during canary deployment, service dashboard show incorrect success percentages.
Success rate varies from 50% to 150%. 

https://snapshot.raintank.io/dashboard/snapshot/mimQl4yS42oWPWpaW0na0rDozt5jRYLf

**Comment by douglas-reid** [comment] 2019-04-25 19:36
This appears to be caused by, at least in part, the difference in use of `irate` and `rate` in the numerator and denominator.

**Comment by douglas-reid** [comment] 2019-05-13 18:49
Closing, based on istio/installer/pull/166.

Please re-open if that does not resolve issue.

**Closed by douglas-reid** 2019-05-13 18:49 UTC
Labels: area/policies and telemetry
