### ISSUE TITLE
initconainer cannot access network

### ISSUE THREAD

**Issue by ghaering** [istio/istio#27382] opened 2020-09-17 07:17 UTC
**Bug description**

My own init container has no access to Kubernetes API, and probably network in general. My init container lists secrets, but access to the Kubernetes API server is not possible:

The connection to the server 10.14.0.1:443 was refused - did you specify the right host or port?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The init container should be able to access the Kubernetes API.

**Steps to reproduce the bug**

Will attach Kubernetes manifest with testcase.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.4
control plane version: 1.7.0
data plane version: 1.7.0 (43 proxies)
$ kubectl version --short
Client Version: v1.18.2
Server Version: v1.17.9
```

**How was Istio installed?**

Via the istio operator.

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service.
[testcase.txt](https://github.com/istio/istio/files/5237021/testcase.txt)

**Comment by howardjohn** [comment] 2020-09-17 19:20
Are you using Istio CNI?

**Comment by howardjohn** [comment] 2020-09-17 19:20
https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers

**Comment by hzxuzhonghu** [comment] 2020-09-18 08:41
Init container have set iptables that captured the traffic, but as the envoy is not up. This is the cause.

>Set the traffic.sidecar.istio.io/excludeOutboundIPRanges annotation to disable redirecting traffic to any CIDRs the init containers communicate with.

**Comment by howardjohn** [comment] 2020-10-22 02:13
Closing as this is a known and documented limitation

**Closed by howardjohn** 2020-10-22 02:13 UTC
Labels: area/networking
