### ISSUE TITLE
Resurrect RDS

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#5934] opened 2018-05-30 23:26 UTC
Current pilot has regressed to not using RDS, which has the unfortunate effect of flushing envoy caches in mixerfiler on any config change. We should either resurrect RDS to preserve the caches, or share the caches between workers in envoy. The second option is more technically challenging since that requires locking discipline and can cause contention. The simpler option is to simply use RDS just like it was before the v2 change.

cc @louiscryan @rshriram

**Comment by lizan** [comment] 2018-06-02 00:04
@kyessenov +1 to resurrect RDS rather than share caches between envoy threads. What was the particular issue of the regression?

**Comment by kyessenov** [comment] 2018-06-02 00:07
I don't think there was a good reason for regression rather than lack of time, per @rshriram .

**Comment by costinm** [comment] 2018-06-05 16:46
RDS is implemented - we chose to not use it to explore the impact of RDS on 503.

If we enable it - it should be with a flag and with testing evaluating 503 with and without. 

Config change is not a frequent event ( Envoy is supposed to detect diffs ) - and flushing the cache
on config changes seems like a good feature, not a bug.  If mixer wants to keep the caches after 
reconfig - it can implement it as well.

I have no issues with using RDS if it is confirmed it has no negative impact.

**Comment by costinm** [comment] 2018-06-05 16:48
And I don't think it's a 'regression' - it was an explicit choice, and so far I haven't seen a 503 on config changes  when using v2.

**Comment by kyessenov** [comment] 2018-06-05 19:07
Per @rshriram , he chose not to implement RDS. Unfortunately, config change is a frequent event in k8s world (any pod coming up seems to potentially trigger reconfiguration and cache flush). This is the theory behind why the rate limit suddenly became flake. The pre-allocated quotas are constantly flushed.

**Comment by kyessenov** [comment] 2018-06-05 21:17
https://groups.google.com/forum/#!topic/istio-users/tqMx_BvfidQ

**Comment by andraxylia** [comment] 2018-06-05 21:19
@kyessenov is this about having routes inside ADS but not inlined in the listeners, or completely separate RDS?

**Comment by kyessenov** [comment] 2018-06-05 21:21
This is about RDS protocol, which may or may not be encapsulated as part of ADS. Basically, inlining HTTP routes into LDS configs forces envoy to perform an internal restart for that particular HTTP listener.

**Comment by mandarjog** [comment] 2018-06-05 21:33
Mixer client started using per route config so as to not trash the entire listener when something changed. 

This could be addressed in pilot or envoy,

1. If envoy is smarter about diffing old and new listener, inlined routes are fine 
2. Rds seems easy enough as well.

**Comment by lizan** [comment] 2018-06-05 21:40
1. won't work well if you have large number of inlined routes, any routes change would cause draining listeners. 2. is the right way to do.

**Comment by kyessenov** [comment] 2018-06-05 21:42
Smart LDS diff == RDS :)

**Comment by andraxylia** [comment] 2018-06-05 22:32
Sounds like a good plan, will need to test impact on 503s.

**Comment by markns** [comment] 2018-06-06 06:43
I noticed https://github.com/istio/istio/issues/5934#issuecomment-394863304 referenced my thread on istio-users. I'd really appreciate it if anyone could share any kind of workaround for the dropped connections on reconfiguration. Thanks!

**Comment by rshriram** [comment] 2018-06-14 17:44
Please note that while RDS fixes grpc streaming, it does not fix the flakes in the mixer test. There is more to do to fix those flakes.

**Comment by rshriram** [comment] 2018-06-21 18:41
fixed by #6081

**Closed by rshriram** 2018-06-21 18:41 UTC
Labels: area/networking
