### ISSUE TITLE
Incorrect version on istioctl proxy-status 

### ISSUE THREAD

**Issue by deadc** [istio/istio#13950] opened 2019-05-09 16:45 UTC
**Bug description**

The istioctl proxy-status returns me a different version of what is actually installed.

```bash
nasty//deadcow istio/istio-1.1.5/bin (master) % ./istioctl proxy-status                                     
NAME                                                           CDS        LDS        EDS               RDS          PILOT                           VERSION
httpbin-v1-78d9ff557d-n7dw2.cb-tests                           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
httpbin-v2-558f7d7fd5-7h54q.cb-tests                           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
istio-egressgateway-676f5d9b65-ppnzg.istio-system              SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-8447cfb59-w2ddb     1.1.3
istio-ingressgateway-private-787b749875-8hhpz.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
istio-ingressgateway-public-5c7bcd867-jwzfr.istio-system       SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-8447cfb59-w2ddb     1.1.3
productpage-v1-5cb458d74f-f5q45.bookinfo                       SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
ratings-v1-76f4c9765f-5pkls.bookinfo                           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
reviews-v1-56f6855586-lqcm9.bookinfo                           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
reviews-v2-65c9df47f8-9zv82.bookinfo                           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
reviews-v3-6cf47594fd-2q5ch.bookinfo                           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
sleep-7ffd5cc988-rdjw6.cb-tests                                SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-8447cfb59-w2ddb     1.1.3
nasty//deadcow istio/istio-1.1.5/bin (master) % 
```

**Expected behavior**

The correct return of the installed version

**Steps to reproduce the bug**

Install version 1.1.5 of the istio and run the command `istioctl proxy-status`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```bash
nasty//deadcow istio/istio-1.1.5/bin (master) % ./istioctl version --remote
client version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
citadel version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
egressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
galley version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
ingressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
ingressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
pilot version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
policy version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
sidecar-injector version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
nasty//deadcow istio/istio-1.1.5/bin (master) % kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:39:52Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
nasty//deadcow istio/istio-1.1.5/bin (master) % 
```

**How was Istio installed?**

Installed generating templates with helm and applied some customization with kustomize.

**Environment where bug was observed (cloud vendor, OS, etc)**

Using AWS with CoreOS stable (1967.6.0)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment] 2019-05-09 17:48
This is because we read ISTIO_PROXY_VERSION not ISTIO_VERSION. The latter refers to the istio installation version (ie release-1.1-20190509-09-1, or 1.1.5, etc), where as ISTIO_PROXY_VERSION is the compatibility version -- which is only incremented when backwards incompatible changes are made.

It probably makes sense to use ISTIO_VERSION for istioctl

@esnible thoughts?

**Comment by esnible** [comment] 2019-05-09 18:22
I added `kind/docs` because https://preliminary.istio.io/docs/reference/commands/istioctl/#istioctl-proxy-status doesn't document the output of `istioctl proxy-status` specifically the meaning of the columns.

As @howardjohn pointed out, there are two versions, and you can see the both by doing `istioctl proxy-config bootstrap <pod> | grep VERSION`.  I agree with Howard's suggestion, to show the `ISTIO_VERSION` instead of the `ISTIO_PROXY_VERSION`.  If we keep the proxy version, we should change the column headers.

@frankbu how should we document the columns the user can expect?  Should we document them in the .go source using Cobra?  The `istioctl proxy-status` column names are not intuitive.

**Comment by frankbu** [comment] 2019-05-09 20:35
Documenting the columns in `istioctl config proxy-status -h` would seem good, but I notice that the help doc of no other `istioctl` or `kubectl` command gets into that kind of detail (e.g., `kubectl config get-contexts -h`).

Maybe this doc could use a little more elaboration? https://preliminary.istio.io/docs/ops/traffic-management/proxy-cmd/#get-an-overview-of-your-mesh

**Comment by adityats2020** [comment] 2019-05-09 20:43
Why are several pods not 100% synced? This wasn't the case with Istio-1.0. Is this expected behavior?

**Comment by esnible** [comment] 2019-05-09 21:08
This work item seems to be a duplicate of https://github.com/istio/istio/issues/9597

@frankbu All I want is for the Cobra text to be amended with something like

```
See https://preliminary.istio.io/docs/ops/traffic-management/proxy-cmd/#get-an-overview-of-your-mesh for details of the output format
```

@adityats2020 The percentage is the "scope of visibility".  It does not need to be 100% and we may remove that information because it is confusing.  For discussion see https://github.com/istio/istio.io/issues/3853

**Closed** 2019-05-21 16:01 UTC
Labels: area/user experience, kind/docs
