### ISSUE TITLE
Onboarding statefulset to istio mesh disrupts the corresponding k8s service's load balancing

### ISSUE THREAD

**Issue by RaiAnandKr** [istio/istio#44351] opened 2023-04-12 12:13 UTC
### Bug Description

So we have two statefulSets: `loglake-alpha` and `loglake-prod` being controlled by one regular (and not headless) k8s service: `loglake-svc`.
The `loglake-alpha` statefulSet has 1 replica and `loglake-prod` statefulSet has 3 replicas.
In general and as expected, the k8s service routes 25% traffic to each of the replica. All of the traffic is coming from outside the k8s cluster and is being sent through `ambassador` gateway at the edge.

When I onboard `loglake-alpha` statefulset to istio mesh (by adding the `sidecar.istio.io/inject: "true"` label), all of a sudden we see 90-95% traffic of overall traffic being served by `loglake-alpha` statefulset (i.e. by just on replica). The `loglake-prod` statefulSet serves only ~10% of the overall traffic despite having 3 replicas.
Here are couple of graphs to indicate the pattern:
![Screenshot 2023-04-12 at 5 37 18 PM](https://user-images.githubusercontent.com/21973868/231452618-362025e5-98b5-4f86-a451-0a6ff34bd8a8.png)
![Screenshot 2023-04-12 at 5 37 56 PM](https://user-images.githubusercontent.com/21973868/231452631-5e0aeff1-976c-43a1-b940-e866783bc217.png)

After this even if we onboard `loglake-prod` to istio too later, the stickiness to alpha continues and the situation doesn't improve.

If we flip it from scratch, i.e. onboard only the `loglake-prod` statefulSet to istio mesh, we see it serving 90-95% of the overall traffic this time and `loglake-alpha` serving only ~10% of the traffic. So there is some stickiness to the pods with the envoy proxy.

What could be causing this disruption in RR load balancing and stickiness to the statefulset / pods with sidecar proxy?

We can consistently reproduce this scenario.
Also we tried the same thing with k8s `deployments` where we have 2 deployments and 1 service and onboarding one of the deployment to istio mesh doesn't cause any stickiness. So this is a problem we are seeing exclusively with StatefulSets.

### Version

```prose
$ istioctl version
client version: 1.16.3
control plane version: 1.16.3
data plane version: 1.16.3 (10 proxies)

kubectl version --short
Client Version: v1.21.1
Server Version: v1.22.17
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment] 2023-04-12 17:27
It would help to understand the traffic flow (`a -> b -> c -> d`) and the protocol (http? tcp?)

**Comment by howardjohn** [comment] 2023-04-13 14:35
My hypothesis right now would be that ambassador is doing a poor job load balancing, which shows up only when you introduce a sidecar on the loglake-svc due to connection reuse.

Before:

Ambassador opens a connection-per-request, which is balanced across loglake pods (by kube-proxy or ambassador itself, not sure). May not be one connection per request, but its multiple connections. When new pods come up, connections establish to them

After:

Sidecar efficiently maintain connections persistently. When new pod comes up, ambassador already has enough open connections for incoming requests so it doesn't open new connections, so connections don't go to the new pods.


LMK if that aligns with what you know about your setup

**Comment by howardjohn** [comment] 2023-04-13 17:35
ideally you have a smarter client (ambassador) and the problem is resolved no matter what. Looks like they have a mode for that: https://www.getambassador.io/docs/edge-stack/latest/topics/running/resolvers#kubernetes-endpoint-level-discovery which is probably your best bet.

you could also use Istio Gateway but that is a bigger shift I would imagine.

I don't think onboardin both at the same time helps much. Both will still have sticky connections. So if you scale up for example, or restart, I don't think they will balance

**Comment by howardjohn** [comment] 2023-04-14 13:09
If ambassador is closing the connections or opening new ones nothing sidecar can do about that. My assumption was loglake was closing connections more than the envoy sidecar though, which in turn leads to the stickiness. Obviously I don't know much about loglake so that's mostly a guess.

**Closed as completed** 2023-05-24 13:19 UTC
Labels: area/networking, area/user experience
