### ISSUE TITLE
Multicluster remote profile broken for CA

### ISSUE THREAD

**Issue by nmittler** [istio/istio#26325] opened 2020-08-10 14:31 UTC
**Bug description**

From @tbarrella:

```
istiod has a lot of logs like
2020-08-07T18:46:48.514682Z	warn	serverca	Authentication failed for 10.4.2.7:42220: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT: tokenreviews.authentication.k8s.io is forbidden: User "system:serviceaccount:istio-system:istio-reader-service-account" cannot create resource "tokenreviews" in API group "authentication.k8s.io" at the cluster scope. Authenticator ClientCertAuthenticator at index 2 got error: no verified chain is found.

I found that adding this for the remote cluster spec fixed it:
      caAddress: istiod.istio-system.svc:15012
```

The "legacy" (i.e. non-central) remote profile used to only require setting `remotePilotAddress` to function properly. I suspect that something was broken by the recent changes for central istiod.

The following *should* work:

Set up the first primary cluster: https://gist.github.com/nmittler/177017e7f16600f47caca0493b01d9d2

Add a remote cluster: https://gist.github.com/nmittler/bdb42cc5ff8a694851c61e24ee7ed046

Verify everything works: https://gist.github.com/nmittler/cdca9db77cfef663f79569de0213ae2f

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by stevenctl** [comment] 2020-08-10 14:55
If you check out https://github.com/istio/istio.io/pull/7888, I think we also need this in values.global:
```
          # Use the cluster-local istiod for CA
          caAddress: istiod.istio-system.svc:15012
```

**Comment by stevenctl** [comment] 2020-08-10 14:57
This may be a dupe of https://github.com/istio/istio/issues/26017; there is also an issue with the cert generation make commands.

**Comment by nmittler** [comment] 2020-08-10 16:16
@stevenctl 

>  ```caAddress: istiod.istio-system.svc:15012```

Just to be clear, this is still using the local istiod in the remote cluster as the CA, correct?

**Comment by nmittler** [comment] 2020-08-10 18:36
It looks like this was initially set by https://github.com/istio/istio/pull/23731

@howardjohn is there a way that `caAddress` could be provided a sensible default?

**Closed** 2020-08-11 21:53 UTC
Labels: area/networking, feature/Multi-cluster
