### ISSUE TITLE
Fix build issue requiring a file be touched in pilot before builds work

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#1849] opened 2017-11-23 04:35 UTC
Pulling down a clean source tree and trying to build the pilot directory fails due to a missing file
(istio/pilot/platform/kube/config). Just creating the file allows the build to complete.

This should be fixed.

**Comment by kyessenov** [comment] 2017-11-23 18:04
`make build` creates the file automatically (see https://github.com/istio/istio/blob/master/Makefile#L116). 
The recommendation is to use `make` instead of `bazel`, which it calls under the hood.

**Comment by geeknoid** [comment] 2017-11-23 18:05
Bazel is our official build system. Whatever hack make does should be done in the bazel world instead.

Thanks.

**Comment by kyessenov** [comment] 2017-11-23 18:10
@geeknoid - let me explain why it's needed and you tell me how we can bend bazel to our will :)

Some pilot tests run against a real kubernetes cluster (not a mock environment due to lack of controller mocks in k8s tests, they heavily rely on e2e for testing). When run inside bazel sandbox, the home file system is inaccessible. To get around that, the file with credentials needs to be placed into bazel workspace. This file is this config file. The file then needs to be declared as a test dependency. Now if you remove that file, bazel in theory should still build, but it doesn't since test and build dependency are treated equivalently (incorrectly).

The only workaround I can come up with is to disable linux sandbox entirely. That may cause strange irreproducible test failures since tests are no longer isolated from one another.

**Comment by geeknoid** [comment] 2017-11-23 18:16
Why can't the file be checked into Git?

**Comment by geeknoid** [comment] 2017-11-23 18:17
@douglas-reid

**Comment by kyessenov** [comment] 2017-11-23 18:18
The file contains authentication information for GKE clusters. It's different for everyone.

**Comment by geeknoid** [comment] 2017-11-23 18:22
But to get things to build, I just needed to create an empty file. Can't
that empty file be checked in?

**Comment by kyessenov** [comment] 2017-11-23 18:23
It builds but will not pass tests. You need an actual `.kube/config` to pass the tests. If we check-in the empty file, then putting the actual file will make the tree dirty.

**Comment by geeknoid** [comment] 2017-11-23 19:42
​We can do this:

- Check in a blank file, this will let builds work.
- Add the file to .gitignore which will prevent future edits of the file
from dirtying the tree.

How's that?​

**Comment by ozevren** [comment] 2017-11-25 19:39
Can we simply get a better explanation of what to do when Bazel build
fails? Or have that empty file checked in to enable the build, but have a
big red warning during test run?

Asking to use make when Bazel is the defacto build system is confusing.

**Comment by kyessenov** [comment] 2017-11-29 01:55
@geeknoid that _may_ work, but I feel that untracked committed files are bound to confuse most git users.

bazel is not make, and make is not bazel. I don't see a problem with automating bazel with make.

**Comment by geeknoid** [comment] 2017-11-29 01:58
If make is our build system, no problem. Bazel is our current build system
and people are expected to type "bazel build" to compile stuff.

How would this work in a go-only world BTW?

**Comment by kyessenov** [comment] 2017-11-29 02:03
Bazel has made certain extremely-opinionated design decisions that we can either easily bypass by calling it make first, or try to convince bazel team to be less opinionated.  That doesn't mean make is our build system, it's just an entry point to a world of scripts. Everyone knows `make build`, `make lint`, `make vet`. We use them everyday, and not complain that some of these don't call bazel under the hood.

In a go-only world, some tests would fail unless kubeconfig is linked first. The failed tests should probably print a warning about linking the file. That doesn't prevent me from building or running tests (unlike in bazel world).

**Comment by douglas-reid** [comment] 2017-11-29 03:02
@kyessenov what about a `genrule` with `local = 1` for exec'ing the `ln -s` bit (only disable the sandbox for that one rule)?  shouldn't that work? it should be straightforward to then declare dependencies within BUILD files on that file. disclaimer: i have not tried this.

**Comment by mattdelco** [comment] 2017-12-07 06:23
> Bazel is our official build system. Whatever hack make does should be done in the
> bazel world instead.

I sympathize with the desire, but various istio docs (e.g., https://goo.gl/v5jv1o and misc readme docs) are basically prescribing that people do a "make setup" followed by "make build".  I presume that the desire for the top-level Makefile is to make things more turnkey for users, though setting up some aliases or rules in the top-level BUILD[.bazel] would probably help with usability (right now it seems like people have to either determine a subdirectory path & target for a specific component, or hope that "//..." builds everything [though currently it doesn't, hence things like "make artifacts" and other scripts run in a release build] ).

**Comment by geeknoid** [comment] 2017-12-07 14:17
I originally setup this makefile pattern when we first created the Mixer
build processes. The reason for make was really as a convenience. The real
build system has always been Bazel, with make just kicking things off and
having no logic of its own. This has evolved however over time sadly.

**Comment by kyessenov** [comment] 2017-12-13 20:13
Without bazel, this is no longer an issue.

**Closed by kyessenov** 2017-12-13 20:13 UTC
Labels: bug, build, pilot
