### ISSUE TITLE
error: a container name must be specified for pod productpage-v1-6987489c74-bv8xz, choose one of: [productpage istio-proxy] or one of the init containers: [istio-init]

### ISSUE THREAD

**Issue by zzguang520** [istio/istio#26764] opened 2020-08-24 07:53 UTC
* Enviroment:
```
[root@master istio-1.7.0]# istioctl version
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (1 proxies)

[root@master istio-1.7.0]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
[root@master istio-1.7.0]#
```

* Install istio:
1.curl -L https://istio.io/downloadIstio | sh -
2.cd istio-1.7.0/
3.export PATH=$PWD/bin:$PATH
4.istioctl install

```
[root@master istio-1.7.0]# kubectl get po -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-658c5c4489-dtxbb   1/1     Running   0          86m
istiod-6f5fd7cb8f-slth8                 1/1     Running   0          86m
[root@master istio-1.7.0]# kubectl get po -n kube-system
NAME                                               READY   STATUS    RESTARTS   AGE
coredns-66bff467f8-6nk6r                           1/1     Running   10         96d
coredns-66bff467f8-zn25r                           1/1     Running   10         96d
etcd-master.test.com                                   1/1     Running   11         96d
kube-apiserver-master.test.com                  1/1     Running   14         96d
kube-controller-manager-master.test.com   1/1     Running   12         96d
kube-flannel-ds-amd64-24pqx                        1/1     Running   0          53d
kube-flannel-ds-amd64-6nf5v                        1/1     Running   12         96d
kube-flannel-ds-amd64-qr26n                        1/1     Running   7          96d
kube-flannel-ds-amd64-x9668                        1/1     Running   6          96d
kube-proxy-5qwgb                                   1/1     Running   3          65d
kube-proxy-k7gqd                                   1/1     Running   4          65d
kube-proxy-mqfb7                                   1/1     Running   0          53d
kube-proxy-t75bp                                   1/1     Running   4          65d
kube-scheduler-master.test.com            1/1     Running   12         96d
tiller-deploy-5d58456765-mftpc                     1/1     Running   1          53d
[root@master istio-1.7.0]# kubectl get endpoints -n istio-system
NAME                   ENDPOINTS                                                              AGE
istio-ingressgateway   10.244.3.98:8443,10.244.3.98:15021,10.244.3.98:15443 + 1 more...       87m
istiod                 10.244.2.213:15053,10.244.2.213:15010,10.244.2.213:15012 + 2 more...   87m
[root@master istio-1.7.0]# kubectl describe ns istio-demo
Name:         istio-demo
Labels:       istio-injection=enabled
Annotations:  <none>
Status:       Active

No resource quota.

No LimitRange resource.
[root@master istio-1.7.0]# kubectl get po -n istio-demo
NAME                              READY   STATUS             RESTARTS   AGE
details-v1-558b8b4b76-fc99h       1/2     CrashLoopBackOff   15         61m
productpage-v1-6987489c74-bv8xz   1/2     CrashLoopBackOff   15         61m
ratings-v1-7dc98c7588-kq75g       1/2     CrashLoopBackOff   16         61m
reviews-v1-7f99cc4496-k8sjv       1/2     CrashLoopBackOff   16         61m
reviews-v2-7d79d5bd5d-28rrw       1/2     CrashLoopBackOff   15         61m
reviews-v3-7dbcdcbc56-7lvvr       1/2     CrashLoopBackOff   15         61m
[root@master istio-1.7.0]# kubectl logs details-v1-558b8b4b76-fc99h -n istio-demo
error: a container name must be specified for pod details-v1-558b8b4b76-fc99h, choose one of: [details istio-proxy] or one of the init containers: [istio-init]
[root@master istio-1.7.0]#
```

**Comment by zzguang520** [comment] 2020-08-24 08:05
```
[root@master istio-1.7.0]# kubectl get po -n istio-demo
NAME                              READY   STATUS             RESTARTS   AGE
details-v1-558b8b4b76-fc99h       1/2     CrashLoopBackOff   18         73m
productpage-v1-6987489c74-bv8xz   1/2     CrashLoopBackOff   18         73m
ratings-v1-7dc98c7588-kq75g       1/2     CrashLoopBackOff   18         73m
reviews-v1-7f99cc4496-k8sjv       1/2     CrashLoopBackOff   18         73m
reviews-v2-7d79d5bd5d-28rrw       1/2     CrashLoopBackOff   18         73m
reviews-v3-7dbcdcbc56-7lvvr       1/2     CrashLoopBackOff   18         73m
[root@master istio-1.7.0]# kubectl logs details-v1-558b8b4b76-fc99h istio-init -n istio-demo
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

Writing following contents to rules file:  /tmp/iptables-rules-1598251937036614039.txt366204973
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1598251937036614039.txt366204973
Writing following contents to rules file:  /tmp/ip6tables-rules-1598251937104352373.txt077070760

ip6tables-restore --noflush /tmp/ip6tables-rules-1598251937104352373.txt077070760
iptables-save
# Generated by iptables-save v1.6.1 on Mon Aug 24 06:52:17 2020
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Mon Aug 24 06:52:17 2020
# Generated by iptables-save v1.6.1 on Mon Aug 24 06:52:17 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Mon Aug 24 06:52:17 2020
# Generated by iptables-save v1.6.1 on Mon Aug 24 06:52:17 2020
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Mon Aug 24 06:52:17 2020
[root@master istio-1.7.0]#
```

**Comment by zzguang520** [comment] 2020-08-24 08:09
Bookinfo Application deploy reference link: https://istio.io/latest/docs/examples/bookinfo/
```
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
```

**Comment by zzguang520** [comment] 2020-08-24 08:13
```
[root@master istio-1.7.0]# kubectl describe pod details-v1-558b8b4b76-fc99h -n istio-demo
Name:         details-v1-558b8b4b76-fc99h
Namespace:    istio-demo
Priority:     0
Node:         node1.iocc-test.ibm.com/9.112.160.75
Start Time:   Mon, 24 Aug 2020 14:51:36 +0800
Labels:       app=details
              istio.io/rev=default
              pod-template-hash=558b8b4b76
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=details
              service.istio.io/canonical-revision=v1
              version=v1
Annotations:  prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/status:
                {"version":"8e6e902b765af607513b28d284940ee1421e9a0d07698741693b2663c7161c11","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:       Running
IP:           10.244.1.223
IPs:
  IP:           10.244.1.223
Controlled By:  ReplicaSet/details-v1-558b8b4b76
Init Containers:
  istio-init:
    Container ID:  docker://67c95e8b886871d1696c7cfaeae6d2052fed4264afab71d238a687936ff9ab44
    Image:         docker.io/istio/proxyv2:1.7.0
    Image ID:      docker-pullable://istio/proxyv2@sha256:c1f1b45a4162509f86aa82d0148aef55824454e7204f27f23dddc9d7f4ae7cd1
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x

      -b
      *
      -d
      15090,15021,15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 24 Aug 2020 14:52:16 +0800
      Finished:     Mon, 24 Aug 2020 14:52:17 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     10m
      memory:  10Mi
    Environment:
      DNS_AGENT:
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from bookinfo-details-token-ws874 (ro)
Containers:
  details:
    Container ID:   docker://aab25c396e5d475a5a48283cc847ecca8001afd02d0c5b012abe8b531fd3ac7a
    Image:          docker.io/istio/examples-bookinfo-details-v1:1.16.2
    Image ID:       docker-pullable://istio/examples-bookinfo-details-v1@sha256:18e54f81689035019e1ac78f6d2e6483fcf1d94072d047315ab193cb2ab89ae5
    Port:           9080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 24 Aug 2020 14:52:36 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from bookinfo-details-token-ws874 (ro)
  istio-proxy:
    Container ID:  docker://b023215c914535b8a49590724eae486d076a1b7f2433b714bb7dfa8a5d27c814
    Image:         docker.io/istio/proxyv2:1.7.0
    Image ID:      docker-pullable://istio/proxyv2@sha256:c1f1b45a4162509f86aa82d0148aef55824454e7204f27f23dddc9d7f4ae7cd1
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      details.$(POD_NAMESPACE)
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --trust-domain=cluster.local
      --concurrency
      2
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 24 Aug 2020 16:09:24 +0800
      Finished:     Mon, 24 Aug 2020 16:09:29 +0800
    Ready:          False
    Restart Count:  19
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    first-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      details-v1-558b8b4b76-fc99h (v1:metadata.name)
      POD_NAMESPACE:                 istio-demo (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"proxyMetadata":{"DNS_AGENT":""}}

      ISTIO_META_POD_PORTS:          [
                                         {"containerPort":9080,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     details
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_META_WORKLOAD_NAME:      details-v1
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/istio-demo/deployments/details-v1
      ISTIO_META_MESH_ID:            cluster.local
      DNS_AGENT:
      ISTIO_KUBE_APP_PROBERS:        {}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from bookinfo-details-token-ws874 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  bookinfo-details-token-ws874:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  bookinfo-details-token-ws874
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istiod-ca-cert:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        istio-ca-root-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                  From                              Message
  ----     ------   ----                 ----                              -------
  Normal   Pulling  51m (x11 over 80m)   kubelet, node1.iocc-test.ibm.com  Pulling image "docker.io/istio/proxyv2:1.7.0"
  Warning  BackOff  88s (x359 over 79m)  kubelet, node1.iocc-test.ibm.com  Back-off restarting failed container
[root@master istio-1.7.0]#
```

**Comment by tanjunchen** [comment] 2020-08-24 10:18
It seems that  you need to choose a certain container. 
Any questions? 
For example, kubectl logs  details-v1-558b8b4b76-fc99h details -n istio-demo -c containerName

**Comment by esnible** [comment] 2020-08-24 14:23
Duplicate of https://github.com/istio/istio/issues/5056

Istio adds "sidecar containers" to a pods.  If your pod previously had one container, `kubectl logs` did not require a `-c` argument.

See the rationale in https://github.com/kubernetes/kubernetes/issues/82339 .  Someone on that Issue asked for a way to indicate which pod container is the default (the original).  The Issue was closed without a feature like that.  (If Kubernetes had a way to indicate the "original" container then Istio would apply that flag during sidecar injection.)

Close this issue unless someone is working on a way to tell _kubectl_ which pod is the original.

**Comment by howardjohn** [comment] 2020-08-24 17:42
You can also do `--all-containers`.

**Comment by esnible** [comment] 2020-09-05 00:43
Reopening this issue because I found an undocumented solution reading the _kubectl_ source at https://github.com/kubernetes/kubectl/blob/master/pkg/polymorphichelpers/logsforobject.go#L39 has provided a solution.

To see this working,

```
$ kubectl logs httpbin-6674f664d-fw2hd
error: a container name must be specified for pod httpbin-6674f664d-fw2hd, choose one of: [istio-proxy httpbin] or one of the init containers: [istio-init]
$ kubectl annotate pod httpbin-6674f664d-fw2hd kubectl.kubernetes.io/default-logs-container=httpbin
pod/httpbin-6674f664d-fw2hd annotated
$ kubectl logs httpbin-6674f664d-fw2hd
[2020-09-03 17:35:34 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-09-03 17:35:34 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
...
```

@howardjohn Does it seem reasonable to have Istio injection set kubectl.kubernetes.io/default-logs-container if
- it doesn't already exist
- the original pod had only one container?

**Comment by howardjohn** [comment] 2020-09-08 02:10
@esnible that is pretty neat find! I think it makes sense. However, it will still be broken on `kubectl exec`... seems like they should have included that. Maybe we can file a kubernetes issue for it. I would recommend they make `kubectl.kubernetes.io/default-container` apply to logs/exec/anything else. But for now just logs is useful

**Comment by esnible** [comment] 2020-09-08 15:04
Adding `area/environments` for it shall need to be done in the injector.

**Comment by esnible** [comment] 2020-09-09 17:16
@tanjunchen You have assigned this issue to yourself.  Do you concur that it makes sense for Istio's injector to add `kubectl.kubernetes.io/default-container={.spec.container[0].name}` when injecting a pod with a single container?

Do you want to keep this issue or have it re-assigned?

**Closed** 2020-12-01 19:41 UTC
Labels: area/environments, area/user experience

**Comment by Stono** [comment] 2021-03-02 11:29
Hi, 
This is in the 1.9.1 change log (https://istio.io/latest/news/releases/1.9.x/announcing-1.9.1) but doesn't seem to work, we don't get any annotation.

**Comment by Stono** [comment] 2021-03-02 11:53
Apologies it is working, but FYI it's been deprecated and replaced with `default-container` https://github.com/kubernetes/kubectl/blob/6bd2b56331dd685ec433b23aec38b5261c1b114b/pkg/polymorphichelpers/logsforobject.go#L84

**Comment by howardjohn** [comment] 2021-03-02 17:10
Opened https://github.com/kubernetes/kubernetes/pull/99649 for ^. Are you running `kubectl` master? I think it was just merged a few days ago
