### ISSUE TITLE
Egress Gateways - Apply Kubernetes network policies failure

### ISSUE THREAD

**Issue by jkbschmid** [istio/istio#14736] opened 2019-06-12 08:49 UTC
**Bug description**

The scenario described in [Apply Kubernetes network policies](https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-gateway/#apply-kubernetes-network-policies) cannot be successfully followed.

Step 9: 
```
$ kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -v https://edition.cnn.com/politics
* Could not resolve host: edition.cnn.com
* Closing connection 0
curl: (6) Could not resolve host: edition.cnn.com
command terminated with exit code 6
```
shows a different error message. Probably not relevant, since hostname can't be resolved as well.

Step 13 (curling cnn via egress) fails:
```
$ kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -s -o /dev/null -w "%{http_code}\n" https://edition.cnn.com/politics
000
command terminated with exit code 6
```
Envoy's readiness probe fails:
```
$ kubectl get pods -n test-egress
NAME                     READY   STATUS    RESTARTS   AGE
sleep-5fb55468cb-68hg9   1/2     Running   0          14s
```
Envoy logs show the following:
```
[2019-06-12 08:30:45.574][16][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 14, no healthy upstream
[2019-06-12 08:30:45.574][16][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:49] Unable to establish new stream
[2019-06-12 08:30:45.953][16][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 14, no healthy upstream
[2019-06-12 08:30:45.953][16][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:49] Unable to establish new stream
2019-06-12T08:30:46.270973Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2019-06-12T08:30:48.271003Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
[2019-06-12 08:30:49.570][16][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 14, no healthy upstream
[2019-06-12 08:30:49.570][16][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:49] Unable to establish new stream
2019-06-12T08:30:50.270592Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
Curl should succeed.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.2.0-rc.0
Kubectl: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Installed via [installation guide]
(https://preliminary.istio.io/docs/setup/kubernetes/install/kubernetes/).
Note: For the demo to have an effect, I set passthrough mode to `REGISTRY_ONLY` via:
```
kubectl get configmap istio -n istio-system -o yaml | sed 's/mode: REGISTRY_ONLY/mode: ALLOW_ANY/g' | kubectl replace -n istio-system -f -
```
**Environment where bug was observed (cloud vendor, OS, etc)**
GKE.

**Comment by howardjohn** [comment] 2019-06-12 14:33
```
    - namespaceSelector:
        matchLabels:
          istio: system
```

This looks wrong.. `istio-system` doesnt have a label `istio`. So it blocks pilot

**Comment by jkbschmid** [comment] 2019-06-12 14:47
@howardjohn 
In step 6 of [Apply Kubernetes Network Policies](https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-gateway/#apply-kubernetes-network-policies) the label is manually added:
```
kubectl label namespace istio-system istio=system
```

**Comment by howardjohn** [comment] 2019-06-12 14:50
Oh good point.

Well I suspect that it still can't talk to pilot. Maybe try `curl istio-pilot.istio-system:8080/ready` or `curl istio-pilot.istio-system:8080/debug/adsz` (I think /ready is an endpoint on pilot but I forget. adsz definitely is though)

**Comment by jkbschmid** [comment] 2019-06-12 15:03
You're right:
```
kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -v istio-pilot.istio-system:8080/debug/adsz
* Could not resolve host: istio-pilot.istio-system
* Closing connection 0
curl: (6) Could not resolve host: istio-pilot.istio-system
command terminated with exit code 6
```
Seems like the DNS server (which is running) cannot be reached.
The /etc/resolv.conf on the pod points to the correct DNS-server service IP.

**Comment by howardjohn** [comment] 2019-06-12 15:07
Interesting, did you label the kube-system (step 7)

`$ kubectl label ns kube-system kube-system=true`

Is your DNS stuff running in kube-system?

**Comment by jkbschmid** [comment] 2019-06-12 15:09
Yup, to both question.
```
$ kubectl get namespaces --show-labels -l kube-system
NAME          STATUS   AGE   LABELS
kube-system   Active   22d   kube-system=true
```

```
$ kubectl get pods --namespace=kube-system -l k8s-app=kube-dns
NAME                     READY   STATUS    RESTARTS   AGE
coredns-6fdb7894-26s4f   1/1     Running   0          22h
coredns-6fdb7894-78s2g   1/1     Running   0          22h
```

**Comment by duderino** [comment] 2019-06-13 04:26
I'm worried this will get lost in the noise if we leave it as a P1

**Comment by duderino** [comment] 2019-06-13 18:00
@rlenglet could you take a look?

It may not be a regression from 1.1, in which case this could be demoted to P1

But I think it would be very nice to support a network policy that forces egress traffic through egress gateways

**Comment by howardjohn** [comment] 2019-06-13 18:04
My guess is this is 100% just an error in our docs, not any bug in Istio

**Comment by jkbschmid** [comment] 2019-06-14 07:53
Changing the port for DNS in the NetworkPolicy from 53 to 8053 solves the problem with the readiness probe. 
The NetworkPolicy contains targets port 53 (which is the service port), but the actual targetPort on the container was 8053. Will dig a little further and see if the rest can also be fixed.
I noticed that if you
> Follow the steps in the Egress gateway for HTTPS traffic section.

the DestinationRule, Gateway and VirtualService will all be applied in the default namespace instead of in the newly-created test-egress. Maybe this is also another source of errors.

**Comment by jkbschmid** [comment] 2019-06-14 08:18
Ok, applying the configuration to the 'test-egress'-namespace solves it.
In conclusion:
1) Mention that `REGISTRY_ONLY` should be configured for the Istio installation. Otherwise 
  `Verify that your ServiceEntry was applied correctly by sending an HTTP request to http://edition.cnn.com/politics.` is pointless.
2) Use the DNS-service's target port in the NetworkPolicy, not sure if k8s always uses 8053, maybe someone else can verify or we can add an explanation to the docs.
3) Deploy traffic configuration to `test-egress` instead of the default namespace.

**Comment by rlenglet** [comment] 2019-06-14 16:59
We shouldn't have to change the port to 8053. The port is not even configurable in resolv.conf, so clients always use port 53.

**Comment by jkbschmid** [comment] 2019-06-14 21:17
> The port is not even configurable in resolv.conf, so clients always use port 53.

Interesting, didn't know that yet. 
The problem is NetworkPolicies reference container ports, not service ports (if my understanding is correct). In my cluster, for some reason service port 53 is mapped to container port 8053. Thus, even if clients target port 53, the port is mapped to the prohibited port 8053 and DNS requests from sidecars will fail.
IMO, adding a warning or troubleshooting section would be a good solution for a corner case like this.

**Comment by rlenglet** [comment] 2019-06-14 22:00
I'm currently trying to reproduce, and will comment afterwards.

**Comment by rlenglet** [comment] 2019-06-14 23:24
I can't reproduce this on a GKE `v1.12.8-gke.6` cluster:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.6", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-05-18T01:21:01Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

The `sleep` pod in namespace `test-egress` can resolve `edition.cnn.com` but can't access `https://edition.cnn.com/politics` as expected:
```
$ kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -v https://edition.cnn.com/politics
*   Trying 151.101.65.67...
* TCP_NODELAY set
*   Trying 2a04:4e42::323...
* TCP_NODELAY set
* Immediate connect fail for 2a04:4e42::323: Network unreachable
*   Trying 2a04:4e42:400::323...
* TCP_NODELAY set
* Immediate connect fail for 2a04:4e42:400::323: Network unreachable
*   Trying 2a04:4e42:600::323...
* TCP_NODELAY set
* Immediate connect fail for 2a04:4e42:600::323: Network unreachable
*   Trying 2a04:4e42:200::323...
* TCP_NODELAY set
* Immediate connect fail for 2a04:4e42:200::323: Network unreachable
*   Trying 2a04:4e42::323...
* TCP_NODELAY set
* Immediate connect fail for 2a04:4e42::323: Network unreachable
*   Trying 2a04:4e42:400::323...
* TCP_NODELAY set
```

I restarted the pod before running this command, to be sure the DNS cache was empty in the pod.

Note that the IP addresses here are correct, e.g. when resolving from my laptop I get the same IP addresses:
```
$ dig edition.cnn.com a +all | grep '^edition'
edition.cnn.com.	172	IN	A	151.101.129.67
edition.cnn.com.	172	IN	A	151.101.193.67
edition.cnn.com.	172	IN	A	151.101.1.67
edition.cnn.com.	172	IN	A	151.101.65.67
```

```
$ dig edition.cnn.com aaaa +all | grep '^edition'
edition.cnn.com.	120	IN	AAAA	2a04:4e42:200::323
edition.cnn.com.	120	IN	AAAA	2a04:4e42:400::323
edition.cnn.com.	120	IN	AAAA	2a04:4e42:600::323
edition.cnn.com.	120	IN	AAAA	2a04:4e42::323
```

I deleted the pod and retried several times, and the results were consistent: DNS resolves, and curl fails, as expected.

**Comment by rlenglet** [comment] 2019-06-14 23:35
Even after injecting with a sidecar, the pod can still resolve `edition.cnn.com`:

**At step 13:**

```
$ kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- ping edition.cnn.com -c 4
PING edition.cnn.com (151.101.65.67): 56 data bytes
...
$ kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- ping edition.cnn.com -c 4
PING edition.cnn.com (151.101.193.67): 56 data bytes
...
```

So DNS traffic is allowed.

However, the curl fails, and that is not OK:
```
$ kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -sL -o /dev/null -D - https://edition.cnn.com/politics
command terminated with exit code 35
```

**Comment by rlenglet** [comment] 2019-06-14 23:56
The proxy's config seems fine from Pilot's viewpoint:
```
$ istioctl proxy-status
NAME                                                   CDS        LDS        EDS              RDS          PILOT                            VERSION
istio-egressgateway-785888df6f-c5bmm.istio-system      SYNCED     SYNCED     SYNCED (96%)     NOT SENT     istio-pilot-84c4845958-ckjns     1.2.0-rc.1
istio-ingressgateway-68dc54f87f-cxzwb.istio-system     SYNCED     SYNCED     SYNCED (96%)     NOT SENT     istio-pilot-84c4845958-ckjns     1.2.0-rc.1
sleep-ff7f5c94f-6pfq8.default                          SYNCED     SYNCED     SYNCED (51%)     SYNCED       istio-pilot-84c4845958-ckjns     1.2.0-rc.1
sleep-ff7f5c94f-zwckm.test-egress                      SYNCED     SYNCED     SYNCED (48%)     SYNCED       istio-pilot-84c4845958-ckjns     1.2.0-rc.1
rlenglet@b7160dc7572d:~/istio-1.2.0-rc.1
```
```
$ istioctl proxy-status sleep-ff7f5c94f-zwckm.test-egress
Clusters Match
Listeners Match
Routes Match (RDS last loaded at Fri, 14 Jun 2019 23:28:58 UTC)
```

**Comment by rlenglet** [comment] 2019-06-15 00:03
The `sleep` pods in the `default` and the `test-egress` namespaces have exactly the same listener configurations for the `edition.cnn.com` virtual host.

**Comment by rlenglet** [comment] 2019-06-15 00:13
Even with connection logging at trace level, the sidecar doesn't log anything useful.

**Comment by rlenglet** [comment] 2019-06-15 00:22
Even with the NetworkPolicy deleted, the pod in `test-egress` can't curl.

**Comment by rlenglet** [comment] 2019-06-15 00:35
Adding the same ServiceEntry, Gateway, VirtualService, and DestinationRule as the `default` namespace into the `test-egress` namespace, and re-installing the NetworkPolicy, the pod can now curl edition.cnn.com via the egress gateway:
```
$ kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -s -o /dev/null -w "%{http_code}\n" https://edition.cnn.com/politics
200
```

I checked in the egress gateway that it's accessing through the gateway.

**Comment by rlenglet** [comment] 2019-06-15 00:38
So, to conclude my research:

1) **The DNS issue is not reproducible on a GKE v1.12.8-gke.6 cluster. This is most likely a bug in the Calico CNI on v1.14.0 clusters, not an Istio bug.**

2) **The instructions are missing the creation of the same ServiceEntry, Gateway, VirtualService, and DestinationRule resources in the `test-egress` namespace as in the `default` namespace, which makes steps 13 and 14 fail.**

**Comment by rlenglet** [comment] 2019-06-15 00:40
@jkbschmid Please report the DNS thing as a bug in GKE v1.14.0. I will fix the docs to create the proper resources in the `test-egress` namespace.

**Comment by rlenglet** [comment] 2019-06-15 01:13
Actually, the only resource missing from namespace `test-egress` is the DestinationRule. The other resources are not required.

**Comment by jkbschmid** [comment] 2019-06-17 07:12
@rlenglet 
>Please report the DNS thing as a bug in GKE v1.14.0.

I don't think this is a bug in GKE, rather a misconfiguration of the NetworkPolicy for my setup, since container port and service port are not equal:
```
$ kubectl get service -n kube-system kube-dns -o=jsonpath='{.spec.ports[?(.name == "dns")]}'
map[name:dns port:53 protocol:UDP targetPort:8053]
```

Out of curiosity, would you mind posting the output of
```bash
kubectl get service -n kube-system kube-dns -o=jsonpath='{.spec.ports[?(.name == "dns")]}'
```
to see if this can explain why you could not reproduce the issue?

**Comment by rlenglet** [comment] 2019-06-18 14:36
Keeping this issue open to investigate the remaining network policy problem in k8s 1.14. removed the Istio 1.2 target for that.

**Closed** 2019-11-06 06:56 UTC
Labels: area/networking, bug bashed, kind/docs, lifecycle/needs-escalation
