### ISSUE TITLE
Address does not show up for kubectl get ingress on Bluemix Container Service.

### ISSUE THREAD

**Issue by craigyam** [istio/istio#317] opened 2017-05-24 03:29 UTC
Running Istio on Bluemix Container Service with the Bookinfo demo.  If I do `kubectl get svc` I can see that istio-ingress is assigned an external IP, but when I do `kubectl get ingress` the Address field is left blank.  If I check the istio-ingress logs, I see:

> I0523 19:48:25.146704       1 status.go:302] updating Ingress default/gateway status to [{169.47.245.10 }]
> W0523 19:48:25.149243       1 status.go:306] error updating ingress rule: Forbidden: "/apis/extensions/v1beta1/namespaces/default/ingresses/gateway/status" (put ingresses.extensions gateway)

I updated the install/kubernetes/istio-rbac-alpha.yaml to add "ingresses/status" resource to the istio-manager cluster role and the address starts being populated.

**Comment by andraxylia** [comment] 2017-05-24 03:54
Ingresses is already in istio-manager, did you add it to istio-sidecar?

**Comment by andraxylia** [comment] 2017-05-24 04:04
Could you please check the fix in  #318 ?

**Comment by frankbu** [comment] 2017-05-24 04:35
This is a duplicate of https://github.com/istio/issues/issues/10

**Comment by andraxylia** [comment] 2017-05-24 05:32
Fixed in  #318.

**Closed by andraxylia** 2017-05-24 05:32 UTC
