### ISSUE TITLE
Configuring an external TCP endpoint (Microsoft SQL Server, TCP: 1433)

### ISSUE THREAD

**Issue by HXK123** [istio/istio#12390] opened 2019-03-10 21:50 UTC
**Description of issue**
Hi,

I am having a little trouble adapting the examples for configuring external TCP endpoints in Istio.  I wish to create a consistent service name that points to varying external IP address endpoints (e.g., external database server on port 1433) so that applications in Kubernetes do not have to update the hostname between environments (e.g., Test vs. Staging vs. Production).

These are the two examples I have tried (with and without a `VirtualService`):

* https://preliminary.istio.io/blog/2018/egress-mongo/#control-tcp-egress-traffic-without-a-gateway
* https://preliminary.istio.io/blog/2018/egress-mongo/#control-tls-egress-traffic-without-a-gateway

Here is the latest attempt:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mssql
spec:
  hosts:
  - mssql.testdomain
  ports:
  - number: 1433
    name: tcp-mssql
    protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mssql
spec:
  hosts:
  - mssql.testdomain
  tls:
  - match:
    - port: 1433
      sni_hosts:
      - mssql.testdomain
    route:
    - destination:
        host: 10.10.5.5
        port:
          number: 1433
```

However, when I try to ping `mssql.testdomain` from within the application container or use `sqlcmd` to connect via port 1433, I get a connection timeout.  If I use `sqlcmd` to connect to the IP address directly, I am able to query the schema.

Am I doing something wrong?  I also tried with `resolution: STATIC` with similar results:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mssql
spec:
  hosts:
  - mssql.testdomain
  addresses:
  - 10.10.5.5/32
  ports:
  - number: 1433
    name: tcp-mssql
    protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
  - address: 10.10.5.5
    ports:
      tcp-mssql: 1433
```

If I use native Kubernetes `Service` and `Endpoint` objects, I am able to connect without any issues:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "app.name" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: tcp-{{ include "app.name" . }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ include "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "app.name" . }}
subsets:
  - addresses:
      - ip: 10.10.5.5
    ports:
      - port: {{ .Values.service.port }}
```

Any help is greatly appreciated.

Thanks!

**Version**
```
$ istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

**Installation**
Installed via Helm Chart.

**Environment**
IBM Cloud Kubernetes Service:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8+IKS", GitCommit:"105f9aeb766a38f33dcd5f632bff307be45722ab", GitTreeState:"clean", BuildDate:"2019-03-01T14:51:51Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by wangye1123356056** [comment] 2019-05-28 03:04
I also have the same problem.
If I use native Kubernetes Service and Endpoint objects, I am able to connect without any issues.
Is your problem solved?

**Comment by spam8321** [comment] 2019-05-28 03:12
Nope, not solved.  I just ended up using `Service` and `Endpoint` objects instead.  Even if egress traffic is blocked by the Envoy sidecar, egress traffic is allowed to the defined `Service` automatically as per https://github.com/istio/istio/issues/12410#issuecomment-481442615.

**Comment by wangye1123356056** [comment] 2019-05-28 10:03
Thanks, but I use the native Kubernetes service and the endpoint object to use istio as a proxy. I will have sporadic connection failures. I don't know if this is related to my failure to establish ServiceEntry, but I can't create ServiceEntry now.

**Comment by HXK123** [comment] 2019-05-28 11:58
Wasn't solved for me either.  We did the same workaround with `Service` and `Endpoint` as you and spam8321 did, which is sufficient for our needs.

It would be nice if there was a concrete example out there we can use though.

**Comment by vadimeisenbergibm** [comment] 2019-08-26 08:02
@HXK123 @spam8321 @tuantuan11233 cc @howardjohn 

Please note that the issue is probably with DNS. A service entry in Istio does not define a DNS record. So before your app tries to open a connection to `mssql.testdomain`, it sends a DNS query for `mssql.testdomain` and it does not get an IP for `mssql.testdomain` from the Kubernetes DNS since Kubernetes DNS is not aware of this domain name. So the app fails before even opening a connection to the destination and before Envoy is able to intercept the connection. To handle DNS, you have to define a Kubernetes selector-less service. For that Kubernetes service, you define either Kubernetes Endpoints, or you use a VirtualService to define routing.

**Comment by vadimeisenbergibm** [comment] 2019-08-26 08:36
@HXK123 @spam8321 @tuantuan11233 I have a PR to istio.io regarding the Kubernetes services for egress traffic https://github.com/istio/istio.io/pull/4710. A compiled version is here. Let me know if it helps https://deploy-preview-4710--preliminary-istio.netlify.com/docs/tasks/traffic-management/egress/egress-kubernetes-services/, any comments are welcome.

**Comment by vadimeisenbergibm** [comment] 2019-09-05 16:31
@HXK123 @spam8321 @tuantuan11233 are your issues with the external service solved?

**Comment by HXK123** [comment] 2019-09-06 23:59
> @HXK123 @spam8321 @tuantuan11233 are your issues with the external service solved?

Hi @vadimeisenbergibm,

For me personally, we ended up using `Service` and `Endpoint` resources instead as `ServiceEntry` was still giving us trouble.  In that respect, we were able to work around the issue so it is not as important for us any more.

Thanks!

**Comment by vadimeisenbergibm** [comment] 2019-09-08 06:48
Hi @HXK123, thank you for letting me know, you are welcome. Could you please close this issue?

**Closed** 2019-09-09 14:22 UTC
Labels: area/networking, kind/customer issue
