### ISSUE TITLE
Operator install with sds profile does not work

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#18675] opened 2019-11-06 00:50 UTC
Use operator to install sds profile, then istio-proxy seems to not work properly. See abnormal frequent xds connection close message from the proxy logs.

**Comment by howardjohn** [comment] 2019-11-06 01:44
trying this out as well, will add some details shortly

**Comment by howardjohn** [comment] 2019-11-06 01:48
My config:
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: istio
  namespace: istio-operator
spec:
  values:
    grafana:
      enabled: true

    global:
      controlPlaneSecurityEnabled: true
      mtls:
        enabled: true
      sds:
        enabled: true
        udsPath: "unix:/var/run/sds/uds_path"
        useNormalJwt: true


    nodeagent:
      enabled: true
      image: node-agent-k8s
      env:
        CA_PROVIDER: "Citadel"
        CA_ADDR: "istio-citadel:8060"
        VALID_TOKEN: true
        SECRET_GRACE_DURATION: "1m"
        SECRET_JOB_RUN_INTERVAL: "30s"
        SECRET_TTL: "2m"
```

Pilot istio-proxy logs:

```
2019-11-06T01:46:13.018195Z     info    waiting for file
2019-11-06T01:46:13.118368Z     info    waiting for file
2019-11-06T01:46:13.218548Z     info    waiting for file
2019-11-06T01:46:13.318738Z     info    waiting for file
2019-11-06T01:46:13.418907Z     info    waiting for file
2019-11-06T01:46:13.519076Z     info    waiting for file
2019-11-06T01:46:13.619345Z     info    waiting for file
2019-11-06T01:46:13.719504Z     info    waiting for file
2019-11-06T01:46:13.819666Z     info    waiting for file
2019-11-06T01:46:13.919875Z     info    waiting for file
2019-11-06T01:46:14.020047Z     info    waiting for file
2019-11-06T01:46:14.120214Z     info    waiting for file
2019-11-06T01:46:14.220423Z     info    waiting for file
2019-11-06T01:46:14.320627Z     info    waiting for file
2019-11-06T01:46:14.420869Z     info    waiting for file
2019-11-06T01:46:14.521043Z     info    waiting for file
2019-11-06T01:46:14.621203Z     info    waiting for file
2019-11-06T01:46:14.721459Z     info    waiting for file
2019-11-06T01:46:14.821720Z     info    waiting for file
2019-11-06T01:46:14.922240Z     info    waiting for file
2019-11-06T01:46:15.022381Z     info    waiting for file
2019-11-06T01:46:15.122753Z     info    waiting for file
2019-11-06T01:46:15.222998Z     info    waiting for file
2019-11-06T01:46:15.323154Z     warn    file still not available after1m0s
2019-11-06T01:46:15.323230Z     info    Monitored certs: []string{"/etc/certs/cert-chain.pem", "/etc/certs/key.pem", "/etc/certs/root-cert.pem"}
2019-11-06T01:46:15.323236Z     info    waiting 2m0s for /etc/certs/cert-chain.pem
2019-11-06T01:46:15.323253Z     info    waiting 2m0s for /etc/certs/key.pem
2019-11-06T01:46:15.323261Z     info    waiting 2m0s for /etc/certs/root-cert.pem
```

but eventually comes up

Ingress logs are similar


Pretty sure the problem is nodeagent is never created though

**Comment by howardjohn** [comment] 2019-11-06 01:50
`mesh generate` shows `# NodeAgent component is disabled.` and `"nodeagent":{"enabled":false, ....` (in the injector template .values config)

This is an operator/installer bug, not SDS issue @richardwxn

**Comment by richardwxn** [comment] 2019-11-06 01:54
@howardjohn yep I believe so, I am trying to see whether can I find a fix.

**Comment by pitlv2109** [comment] 2019-11-06 02:47
We don't use `useNormalJwt` and `useTrustworthyJwt` anymore in the old installer, this needs to be updated in the operator as well.

**Comment by richardwxn** [comment] 2019-11-06 03:55
@pitlv2109 yep I noticed that change but that doesn't seem to be the reason?

**Comment by howardjohn** [comment] 2019-11-06 04:06
My issue was a misconfiguration btw -- will try with the correct config
tomorrow

**Comment by richardwxn** [comment] 2019-11-08 09:06
@howardjohn any findings for the node agent issue?

**Comment by howardjohn** [comment] 2019-11-08 16:29
@richardwxn I merged some PRs the other day that seem to get it running, I will give a more thorough testing today

**Comment by pitlv2109** [comment] 2019-11-08 17:08
I found some issue about workloads not sending any jwts yesterday. Will
look into it.

**Comment by ostromart** [comment] 2019-11-22 23:07
Any update on this @pitlv2109 @myidpt ? Currently sds profile is present but omitted in the documentation. Once we get the green light we will update the docs to restore it.

**Comment by pitlv2109** [comment] 2019-11-22 23:08
I created a separate issue with more details on the problem and a fix https://github.com/istio/istio/issues/19109

**Closed** 2020-01-17 21:55 UTC
Labels: area/environments/installer, area/environments/operator, cherrypick/release-1.4
