### ISSUE TITLE
Validation Error on gateways missing server

### ISSUE THREAD

**Issue by m4ver1k** [istio/istio#42788] opened 2023-01-12 14:38 UTC
### Bug Description

i'm seeing the following validation failure post upgrading to `1.16.1` on `istiod` logs,

```
istiod-5f9d7487d8-2c9fv discovery {"level":"info","time":"2023-01-12T13:52:51.118094Z","scope":"validationServer","msg":"configuration is invalid: gateway must have at least one server"}
istiod-5f9d7487d8-2c9fv discovery {"level":"info","time":"2023-01-12T13:52:53.079627Z","scope":"validationServer","msg":"configuration is invalid: gateway must have at least one server"}
istiod-5f9d7487d8-2c9fv discovery {"level":"info","time":"2023-01-12T13:52:55.481093Z","scope":"validationServer","msg":"configuration is invalid: gateway must have at least one server"}
istiod-5f9d7487d8-2c9fv discovery {"level":"info","time":"2023-01-12T13:52:56.019442Z","scope":"validationServer","msg":"configuration is invalid: gateway must have at least one server"}
istiod-5f9d7487d8-2c9fv discovery {"level":"info","time":"2023-01-12T13:52:59.605484Z","scope":"validationServer","msg":"configuration is invalid: gateway must have at least one server"}
istiod-5f9d7487d8-2c9fv discovery {"level":"info","time":"2023-01-12T13:53:02.256907Z","scope":"validationServer","msg":"configuration is invalid: gateway must have at least one server"}
```

But when I check my gateway object I can see the server is configured, is this a false positive or am I missing something.

```apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: internal-ingress-gateway
    meta.helm.sh/release-namespace: istio-system
  creationTimestamp: "2023-01-11T20:58:14Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: istio-internal-gateway
  namespace: istio-system
  resourceVersion: "2857919763"
  uid: 36e3ded2-72bb-468d-acf6-912b54bd998d
spec:
  selector:
    operator.istio.io/component: IngressGateways
  servers:
  - hosts:
    - '*.domain.com'
    port:
      name: istio-ingressgateway
      number: 80
      protocol: HTTP
```

### Version

```prose
❯ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (1865 proxies)

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.21.14-gke.4300
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1
```

**Comment by howardjohn** [comment] 2023-01-12 14:57
This is a dupe of https://github.com/istio/istio/issues/28372. PTAL there. Thanks!

**Closed by howardjohn** 2023-01-12 14:57 UTC
