### ISSUE TITLE
Isto ingressgateway cannot get the real IP address of the client

### ISSUE THREAD

**Issue by yuanyiran** [istio/istio#28266] opened 2020-10-26 05:54 UTC
**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Networking

**Affected features (please put an X in all that apply)**

[ ] Physical machine

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

istio 1.2.2
kubernetes 1.14.2
helm 2.16.0

**How was Istio installed?**

helm install istio 1.2.2

**Environment where bug was observed (cloud vendor, OS, etc)**

Local physical machine kubernetes cluster istio no cluster deployment

**error describe**

At present, I use k8s + isto architecture, and I do not use the inress configuration of k8s. Instead, I use isto inress gateway. Nginx service directly accesses the front-end and back-end pages through the inress gateway. However, I can't get the real IP of the client in my service. How do I need to modify the relevant configuration of isto to obtain it successfully?

**nginx config**
`
server {
    listen  80;
    location / {
      root   /web;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
      proxy_set_header    X-Real-IP        $remote_addr;
      proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
      proxy_set_header    HTTP_X_FORWARDED_FOR $remote_addr;
    }
    
    location /nginxstatus {
      stub_status on;
      access_log on;
    }
  }

  log_format  main  '$http_x_forwarded_for | $http_x_real_ip | $remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

`

**nginx logs**
`
10.244.0.0 | - | 127.0.0.1 - - [23/Oct/2020:17:59:08 +0800] "GET /umi.js HTTP/1.1" 200 1414283 "http://192.168.0.109/monitor/services/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "10.244.0.0"
10.244.0.0 | - | 127.0.0.1 - - [23/Oct/2020:17:59:09 +0800] "GET /vendors.chunk.css HTTP/1.1" 200 352929 "http://192.168.0.109/monitor/services/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "10.244.0.0"
10.244.0.0 | - | 127.0.0.1 - - [23/Oct/2020:17:59:09 +0800] "GET /vendors.async.js HTTP/1.1" 200 1555426 "http://192.168.0.109/monitor/services/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "10.244.0.0"
10.244.0.0 | - | 127.0.0.1 - - [23/Oct/2020:17:59:09 +0800] "GET /layouts__BasicLayout.chunk.css HTTP/1.1" 200 32170 "http://192.168.0.109/monitor/services/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "10.244.0.0"
`

**Comment by howardjohn** [comment] 2020-10-26 23:33
Hi @yuanyiran . This is a duplicate of https://github.com/istio/istio/issues/27520, lets keep discussion there.Thanks.

See also https://istio.io/news/support/announcing-1.2-eol/

**Closed by howardjohn** 2020-10-26 23:33 UTC
