### ISSUE TITLE
Possibly CRD regression 1.7 to master

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26964] opened 2020-09-01 15:09 UTC
@costinm reports that the `patch.value` is pruned in Envoyfilter after upgrading from 1.7 to master

cc @jasonwzm

**Comment by jasonwzm** [comment] 2020-09-01 17:50
@costinm How did you do the upgrade? Using `istioctl upgrade`?

**Comment by howardjohn** [comment] 2020-10-16 17:16
Possibly related to https://github.com/istio/istio/issues/28020

**Comment by jasonwzm** [comment] 2020-10-18 05:13
@costinm Can you provide more details on the upgrade. I tried to reproduce by in-place upgrade from 1.7.3 to master and I could not reproduce missing patch value. Also I don't believe k8s prunes fields after stored.

**Comment by jasonwzm** [comment] 2020-10-20 17:17
closing this as I could not reproduce. Feel free to reopen if needed.

**Closed by jasonwzm** 2020-10-20 17:17 UTC
Labels: area/config
