### ISSUE TITLE
Forwarding client certificate info in header

### ISSUE THREAD

**Issue by Szymongib** [istio/istio#8263] opened 2018-08-27 09:07 UTC
**Describe the feature request**
Provide ability to configure Envoy's [`forward_client_cert`](https://www.envoyproxy.io/docs/envoy/latest/api-v1/network_filters/http_conn_man#config-http-conn-man-forward-client-cert) option.

**Describe alternatives you've considered**
Provide some other way to pass client certificate's Subject to services.

**Additional context**
We use Istio Gateway to validate client certificates, we would like to pass client certificate subject to services. Envoy provides the following configuration option `forward_client_cert`, which make it possible to pass the certificate's info in header `x-forwarded-client-cert`.

I have not found a way to configure this in Istio.

**Comment by rshriram** [comment] 2018-08-29 17:14
would it work if we set it to always forward, for the gateways?

**Comment by yangminzhu** [comment] 2018-08-29 19:17
This sounds like an interesting use case, do you only use gateways in your cluster?
If the consumer of the forwarded cert is behind Envoy, I guess we'll need to set `forward_client_cert` in sidecar Envoy as well, otherwise the default behavior is to sanitize it from the headers?

/cc @diemtvu

**Comment by Szymongib** [comment] 2018-08-30 06:16
For our use case it would be fine to always forward, but we do use sidecar injection so consumers are indeed behind the Envoy. Would it be possible to pass the header further with use of `EnvoyFilter` either be overriding default behaviour or passing it as a custom header? If so the only requirement would be forwarding from the gateway.

**Comment by yangminzhu** [comment] 2018-08-30 21:09
I'm not entirely sure when the sanitation happens but feel it's happening before any other filters have the chance to access the headers. (I can double check later)

**Comment by diemtvu** [comment] 2018-08-30 22:42
One thing we need to be careful is to make sure this header is trusted.  If the mesh use mTLS, we can probably set Ingress-gateway to `forward_only` and sidecar (inbound) to `append_forward`, so that `x-forwarded-client-cert` from ingress (if any) won't be dropped. We may also want to set sidecar (outbound) to `sanitize` to prevent adversary app to put malicious value in that header.

If the mesh doesn't use mTLS, I guess we cannot do much anyway.

**Comment by diemtvu** [comment] 2018-09-04 17:36
I've just drafted this [PR](https://github.com/istio/istio/pull/8468). Let me know if it make sense. I'll verify behavior and adding tests later.

**Comment by Szymongib** [comment] 2018-09-11 12:08
Described feature should be sufficient, so yes, for our case it makes sense.

**Comment by Disper** [comment] 2018-09-17 09:12
@diemtvu any updates on this topic?

**Comment by diemtvu** [comment] 2018-09-21 22:34
PR was merged. It should be available in 1.1, or you can try from HEAD. Thanks.

**Comment by lszymik** [comment] 2018-09-22 07:38
@diemtvu Thank you very much.

**Comment by sslavic** [comment] 2018-10-05 12:56
@diemtvu please correct me if wrong, it seems the PR https://github.com/istio/istio/pull/8468 was included in 1.1.0.snapshot.1 pre-release.

I've:
- installed that Istio pre-release on k8s 1.10 minikube with
  - `NodePort` instead of `LoadBalancer`
  - globally enabled mutual TLS in the mesh (`MeshPolicy` and `DestinationRule` as by https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls ) 
- deployed httpbin with VirtualService and Gateway, configured ingress to do mutual TLS following https://istio.io/docs/tasks/traffic-management/secure-ingress/

Then I deployed a simple `EnvoyFilter` which just logs all request headers. When issuing the request using curl and generated client certificates, I can see in the httpbin sidecar logs the `x-forwarded-client-cert` header is there. Problem is that it only has `By=spiffe://cluster.local/ns/default/sa/default` while I was expecting it would include initial hop, so information about client (certificate) that initiated the request to the ingress gateway. Are my assumptions/expectations correct?

PR comment mentions `FORWARD_ONLY` to be configured for the gateway but I don't see that being used in the actual PR changes, only `APPEND_FORWARD` and `SANITIZE_SET` are configured.

**Comment by yangminzhu** [comment] 2018-10-05 22:58
@sslavic Thank you for this detail feedback, I could reproduce this in GKE as well.

I'm not sure about your XFCC header's entire content, but I see the following when I reproduced this:
```
"X-Forwarded-Client-Cert": "Hash=67dcd33c192b8ba33ac94ba51b68ecdaa02a9084446974350454532934611e94,By=spiffe://cluster.local/ns/testcert/sa/default;Hash=5067c65e6752be8aac43b379f4c8812bb3ca692489a4684217821c8d4a492d3c",
```

Note carefully there are actually 2 values in the XFCC header separated by comma (`,`). 
The first element is `Hash=...` which I believe it's added by the ingress gateway.
The second element is `By=spiffe...;Hash=...` which I believe is appended in the sidecar inbound listener.

This means the Envoy is adding the XFCC header correctly but just doesn't include the necessary fields from the cert. I think this is due to PR #8468 doesn't set the [SetCurrentClientCertDetails](https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#L278) which by default sets all fields to `false`. This resulted that only `Hash=...` is added to the header.

I created a PR https://github.com/istio/istio/pull/9178 to fix this and I can confirm it solves my problem. I can find the client cert fields correctly in the header after this patch:
```
"X-Forwarded-Client-Cert": "Hash=67dcd33c192b8ba33ac94ba51b68ecdaa02a9084446974350454532934611e94;Subject=\"CN=4_client,O=Dis,L=Springfield,ST=Denial,C=US\";URI=http://my.url.test/,By=spiffe://cluster.local/ns/testcert/sa/default;Hash=5067c65e6752be8aac43b379f4c8812bb3ca692489a4684217821c8d4a492d3c"
```

**Comment by sslavic** [comment] 2018-10-07 18:18
@yangminzhu true, two hashes were there already. I will test tomorrow, from head. Thanks a lot for quick fix!

**Comment by somcsel** [comment] 2018-12-05 20:40
The code added in PR #9178 has been removed - mistakenly, I believe - by #9016.

[Here](https://github.com/istio/istio/pull/9016/files#diff-86fb73d7dd150e47328ead76ceca0992L276
) is the diff.

I have verified that this is the case using 1.11.0-snapshot.3 and logging the incoming HTTP headers at the sidecar with an EnvoyFilter.  As seen below, the sidecar appends the client certificate `Hash` to `X-Forwarded-Client-Cert` but not the `Subject`, `DNS` or `URI` fields.
```
"X-Forwarded-Client-Cert": "Hash=aefe3f9f8006d07bb5fb273ee2e63994ad6dabeba4810034ca129abc6ffe527f;Subject=\"CN=httpbin.example.com,O=Dis,L=Springfield,ST=Denial,C=US\";URI=,By=spiffe://cluster.local/ns/default/sa/default;Hash=755b83bdde9a0bde0152213cfcba9d210a5883823570ddec62db5927c68c678b"
```

@yangminzhu - shall I create a new issue for this or would you like to re-open this one?

**Comment by yangminzhu** [comment] 2018-12-06 09:01
@somcsel Thank you so much for catching this! I have just created a PR to add this back. I included a unit test to catch and prevent this in the future.

**Comment by eoftedal** [comment] 2019-01-21 20:20
Just referencing this for history/linking: https://github.com/istio/old_issues_repo/issues/165

**Comment by chadlwilson** [comment] 2019-03-05 03:52
@yangminzhu - are you able to clarify for the community if there is a reason this ticket was re-opened and is still open? If I read your PR correctly it looks like this has been fixed/merged into Istio 1.1 - but perhaps I am missing something. Is it that it's still missing some of the info or there is some remaining work to do?

**Comment by lszymik** [comment] 2019-03-05 11:15
I am also interested in knowing it.

**Comment by yangminzhu** [comment] 2019-04-12 01:02
@chadlwilson @lszymik I think this is fixed and could be closed.

**Closed by yangminzhu** 2019-04-12 01:02 UTC

**Comment by chadlwilson** [comment] 2019-04-12 01:29
Thanks @yangminzhu - I agree, we have recently moved to 1.1 and I've seen the info coming through. Forgot to update this ticket. Thanks for all the work!
