### ISSUE TITLE
Consider installing Istio Machinery in the istio namespace

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#254] opened 2017-05-11 16:26 UTC
From Hackathon feedback
```
It would be classy to put all the Istio machinery in a single namespace, such as "istio", rather than the default namespace.  This can be done by specifying e.g.
Kubectl create -f istio.yaml --namespace istio
But this is not critical and may be trickier to get right along with the RBAC stuff.
 
```

**Comment by andraxylia** [comment] 2017-06-06 21:05
Closing: duplicate of istio/istio#338

**Closed by andraxylia** 2017-06-06 21:05 UTC
Labels: hackathon
