### ISSUE TITLE
Kubernetes Services for Egress Traffic fails on 1.4.0-alpha.0

### ISSUE THREAD

**Issue by ericvn** [istio/istio#18208] opened 2019-10-23 01:47 UTC
**Bug description**

Working through the Kubernetes Services for Egress Traffic example at https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-kubernetes-services/

Under the `Use a Kubernetes service with endpoints to access an external service` section, step #6 shows accessing the wikipedia service from the Istio sidecar pod with Istio's mTLS disables. This step should get a valid response, but end up getting a `exit code 35`

**Expected behavior**

Example should pass

**Steps to reproduce the bug**

Follow the instructions for the task at https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-kubernetes-services/

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.4.0-alpha.0

**How was Istio installed?**

Since the installation specified in the example is broken, I used:
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \                                                                          
    --values install/kubernetes/helm/istio/values-istio-demo.yaml \
    --set global.controlPlaneSecurityEnabled=true \
    --set global.mtls.enabled=true | kubectl apply -f -
```

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS, but problem was replicated elsewhere (though not sure where)

**Comment by ericvn** [comment] 2019-10-24 14:37
I did try the same example on 1.3.3 using the 1.3 docs (*demo* profile) and it fails with the same error code.

**Comment by linsun** [comment] 2019-10-24 14:55
@vadimeisenbergibm could you help check this out when you have some time?

**Comment by vadimeisenbergibm** [comment] 2019-10-24 15:10
@linsun Sure, will do.

**Comment by vadimeisenbergibm** [comment] 2019-10-24 15:10
@linsun @ericvn The issue is probably related to https://github.com/istio/istio/issues/17112, that bug should be fixed first.

**Comment by ericvn** [comment] 2019-10-24 15:40
As an FYI, this was merged into preliminary.istio.io with https://github.com/istio/istio.io/pull/4710 and cherry-picked back to istio.io (default 1.3 branch) with https://github.com/istio/istio.io/pull/5157

**Comment by ericvn** [comment] 2019-10-24 18:15
As an FYI, this was merged into preliminary.istio.io with https://github.com/istio/istio.io/pull/4710 and cherry-picked back to istio.io (default 1.3 branch) with https://github.com/istio/istio.io/pull/5157. Per discussion, reverted in 1.3 for now with https://github.com/istio/istio.io/pull/5254.

**Comment by ericvn** [comment] 2019-10-24 18:17
I think we will need #17112 fixed and cherry-picked back into 1.4 (how big is that effort), or we want to revert it out of the 1.4 documentation as well (unless we can fix it so that it works (with the mentioned workaround?)).

**Comment by vadimeisenbergibm** [comment] 2019-10-24 18:24
@ericvn let me check https://github.com/istio/istio/issues/17112, will update you.

**Comment by howardjohn** [comment] 2019-10-26 18:37
17112 is not a bug as far as I can tell, so please revert/fix the docs

**Comment by vadimeisenbergibm** [comment] 2019-10-27 18:32
@ericvn https://github.com/istio/istio.io/pull/5261 should fix this issue.

**Comment by ericvn** [comment] 2019-10-28 18:17
@vadimeisenbergibm I did verify the new page instructions work. Thank you.

**Closed** 2019-10-29 15:00 UTC
Labels: area/networking
