### ISSUE TITLE
istioctl validate does not parse namespace from input files

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#13408] opened 2019-04-17 23:58 UTC
Running istioctl validate on YAMLs with namespaces shows that the namespace field is ignored.

**Comment by kyessenov** [comment] 2019-04-22 18:04
@ozevren @esnible I'd like to prioritize this for Code Mauve. It's frustrating to use the tool when it does not properly parse namespaces, and hence, makes fully-qualified names invalid.

**Comment by ozevren** [comment] 2019-04-22 22:33
Sounds great.

When can we expect a fix? ;)

**Comment by kyessenov** [comment] 2019-04-22 22:37
I need a permission to work on this. Put it into Code Mauve :)

**Comment by kyessenov** [comment] 2019-04-24 04:02
The root cause is that the internal k8s REST mapper considers istio APIs as non-namespaced, which makes the client erase the namespaces from the input files.

To what extent are we committed to using kubectl for parsing istio APIs? There is a simple fix of using YAML parser directly, or a complex fix of packaging istio CRDs with istioctl to educate the mapper about namespace scoping.

**Comment by ozevren** [comment] 2019-04-24 15:05
I am not sure about the historical context here, as it predates me. It maybe a simple artifact of kubectl being the starting point/source of library methods for istioctl. In either case, using the K8s Yaml parser directly seems like a reasonable approach.

**Comment by esnible** [comment] 2019-04-29 11:55
This may be a duplicate of https://github.com/istio/istio/issues/12407 .  I researched this, see my comment at https://github.com/istio/istio/issues/12407#issuecomment-472174065

**Closed** 2019-04-29 19:47 UTC
Labels: area/user experience, code mauve
