### ISSUE TITLE
Istio injector pod being rescheduled results in apps deployed without a sidecar

### ISSUE THREAD

**Issue by Stono** [istio/istio#3716] opened 2018-02-23 08:34 UTC
Hey, 
As we run only a single istio-injector pod to handle the webhook requests, we've noticed that if that pod is being rescheduled for whatever reason (we make use of pre-emptible instances on GCP in preprod environments to save costs), or kubernetes is upgrading the node for example, and an application is deployed, or scaled, or the istio-injector is being rescheduled itself, it does not get injected.

Notice the ones which are `1/1`
```
❯ k get pods
NAME                                        READY     STATUS    RESTARTS   AGE
at-consumer-platform-589dcc9f69-ddk49       1/1       Running   0          13h
at-consumer-platform-589dcc9f69-mqclj       2/2       Running   0          1d
at-sauron-service-search-75845cdbff-smbkx   2/2       Running   0          5m
at-sauron-web-5f867d7dcb-h8hkg              2/2       Running   0          2m
at-sauron-web-5f867d7dcb-s5hq9              2/2       Running   0          2m
at-sauron-web-mobile-5f45bcfb7b-cb6nt       2/2       Running   0          6m
at-search-one-647755f899-2w847              1/1       Running   0          13h
at-search-one-647755f899-kpfln              2/2       Running   0          14h
at-urs-66fcccd5f8-5ptkz                     2/2       Running   0          1d
platform-helm-builder-d45677445-5c2g2       1/1       Running   0          13h
platform-helm-deployer-d6df8bb76-twjlr      2/2       Running   0          1d
platform-image-builder-68575d785-dsjzr      3/3       Running   0          14h
```

This results in service outages for us, until it's noticed and someone does a `kubectl delete pod` to recreate the pod

Question: this could be resolved by running multiple injector pods with a PodDisruptionBudget of 1; are they horizontally scalable?

**Comment by nmittler** [comment] 2018-02-23 16:36
@ayj would you be able to take a look?

**Comment by ayj** [comment] 2018-02-23 17:20
The webhook is horizontal scalable. We could also change the `failurePolicy` to fail closed. The default is fail open (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#webhook-v1beta1-admissionregistration)

**Comment by nmittler** [comment] 2018-02-23 17:34
@ayj that sounds right to me.

@costinm any thoughts?

**Comment by ayj** [comment] 2018-02-23 17:54
See https://groups.google.com/d/msg/istio-users/mlAlO49UOW4/a20Z6i9fAgAJ for what seems to be another instance of this problem.

**Comment by alexkoturanov** [comment] 2018-02-23 19:45
I think there might be and issue with this approach, consider the following scenario:
* *istio-sidecar-injector* pod is not available (being re-scheduled or simply scaled down to 0)
* an application pod is rescheduled (i.e. deleted manually)

In this scenario a new application pod is not created until *istio-sidecar-injector* is available. What if it is not available due to misconfiguration or other reason?

I think injection into deployment object would more consistent.

**Comment by Stono** [comment] 2018-02-23 20:18
Hey, 
Injection into a deployment would be optimal, providing people use deployments (I know most of us do).  This would ensure the same version and configuration of istio across each deployment, which I think it actually important.

I suppose the question comes down to if you want to support people who use replicasets or pods directly?

As there is more discussion around this, and I'm guessing it's also a more involved changed, personally (and somewhat selfishly) I'd like to see #3724 merged as a "temporary hotfix", as where we are now is particularly troublesome.

**Comment by ayj** [comment] 2018-02-23 21:24
> What if it is not available due to misconfiguration or other reason?

A similar problem exists if someone accidentally scale down Pilot replicas to zero. Any newly created pod with a sidecar would not receive any traffic and routing would be broken. The injection webhook should be configured to be HA in such scenarios to avoid the problem your described. Fortunately the webhook is fairly lightweight (~1.5us per injected pod), stateless, and is easily horizontally scalable, i.e. k8s api-server will load balance injection requests across all webhook pod instances.

Misconfiguration could be addressed through canarying in a more isolated environment, e.g. run a canary version of the webook+configuration that is scoped to canary namespace. 

> This would ensure the same version and configuration of istio across each pod in a deployment, which I think is actually very important, scaling up a deployment or rescheduled a pod should not introduce any change in configuration, it should be as it was, when it was deployed.

Manual injection might be a better tool for this use case. You can commit the injected deployment to SCM, version it, etc.

> I suppose the question comes down to if you want to support people who use replicasets or pods directly? 

Yes, we want to support automatic injection into all workloads. Injecting into the controller level resource (e.g. deployment) doesn't work well for other custom controllers that create pods.

**Comment by ayj** [comment] 2018-02-23 21:44
cc @yusuoh, who is working on Istio upgrade process and was interested in pod-level injection for incremental sidecar upgrades.

**Comment by yusuoh** [comment] 2018-02-24 03:54
I think the root issue is about the availability of injector. Even if we switch to deployment-level injection, we still cannot exclude the case when deployment is created while injector is down (although the chance is less). And we have to capture more workload types like daemonset, job, singleton pod, etc.

So I think we can try what @ayj suggested: (1) Forcefully fail pod creation when injector is not available (2) Increase the number of webhook replicas with anti-affinity option enabled so that restarting a single node won't cause the injection service to fail. If the problem still happens, we can revisit the design later.

**Comment by Stono** [comment] 2018-02-26 11:02
I definitely agree with the solution of fail pod creation, and HA setup of the injector as an immediate solution to this issue.  We've implemented this on our cluster for now.

I do think there is potentially a wider discussion however around the fact that deployment pod spec templates are generally considered immutable, ie a change to a deployment is applied to all of the pods running in that deployment (lets say I change the resource limits for example; that pod template is then applied to, in a rolling update fashion, everything underneath) and by injecting at the pod level we do potentially introduce a situation where some pods are configured differently to other pods (lets say an update to the injection template happens and then a deployment is scaled up), effectively breaking that immutability and whilst I don't have a tangible example of the problems this would cause, my gut tells me it doesn't feel right.

> Manual injection might be a better tool for this use case. You can commit the injected deployment to SCM, version it, etc.

I don't feel this is a solution, taking our use case of (potentially) 200+ helm charts, if we manually committed the injected deployment into git, whenever we wanted to upgrade istio we would have a mammoth task on our hands, and it doesn't feel very "service mesh" if we're having to effectively get product teams to update applications whenever we update the mesh.

It gets more complex when some of the helm charts we have are deployed to both istio, and non-istio enabled clusters.  The only way to get such helm charts working in the above model would be to have conditional "if values.istio=true" logic in the templates.  This also doesn't feel right.

I am speaking as someone who has very limited experience of your code base & mutatingwebhooks but it does feel like we should be trying to auto-inject at the highest possible level in descending order (deployment first, then rs, then pod).

**Comment by alexkoturanov** [comment] 2018-02-26 17:02
I think I also agree with failing pod creation when injector is not available but still I would like to have an option to configure injection at the deployment level. In our use case only deployments are used and I would prefer them to be immutable so I can easily reason about 20+ pods created by a deployment.

Is there any option to configure injection to use deployments first (inject sidecar and annotation that injection is not required) and then fallback to pod creation injection for all other use cases?

**Comment by andraxylia** [comment] 2018-02-27 17:01
@nmittler Automatic injection is area/environments.

**Comment by costinm** [comment] 2018-02-27 23:24
Not sure what you mean by 'configure injection to use deployments first ' - is it using kube-inject 
before ? If yes: +1

**Comment by ayj** [comment] 2018-02-28 01:21
> by injecting at the pod level we do potentially introduce a situation where some pods are configured differently to other pods 

This was by design to enable incremental upgrade of sidecar proxies without needing to touch the user's original deployment/statefulset/job/etc.The argument could be made for (re)introducing controller-level injection again (i.e. deployment), but it should probably be mutually exclusive with pod-level injection. Trying to support both at the same time would require additional annotations/heuristics to figure out the desired behavior. This all seems to be outside the scope of the original issue of missing injected sidecars which should be fixed by https://github.com/istio/istio/pull/3724.

@alexeykazakov @Stono - would you be willing to open a feature request for deployment-level injection option. We can continue discussion, assign priority, etc. in that context?

**Comment by Stono** [comment] 2018-02-28 08:32
@ayj done, this issue can be closed off when we resolve https://github.com/istio/istio/pull/3724

**Comment by nmittler** [comment] 2018-03-01 00:31
Awesome! Thanks, @ayj!

**Closed** 2018-03-01 00:30 UTC
Labels: area/environments, kind/customer issue, kind/needed for 1.0
