### ISSUE TITLE
Version downgrade from 1.5 to 1.3, produces error of istiod not found.

### ISSUE THREAD

**Issue by adrafiq** [istio/istio#25745] opened 2020-07-22 13:40 UTC
**Bug description**
We have an istio-deployment in out cluster. Version is 1.3. The version was installed using helm chart. 
Now for observability project I updated the istio version. The update was'nt via an upgrade process. Rather delete the helm release and install istio via `istioctl install --set profile=demo`. After that I deleted the version 1.5 using `istioctl manifest generate  | kubectl delete -f -` as described in docs and went back to creating release for version 1.3 from helm. 
The release was created with following errors: 
`Error: release istio failed: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service "istiod" not found`
Or creating any istio object like a service entry creates error
`Error from server (InternalError): error when creating "service_entries/stage-webveloper/customer-example-posts-helper-api.yaml": Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service "istiod" not found`

Since istiod was released in a recent release i.e version 1.5. Istiod combines the complete istio control plane into one binary process. Why is the system calling webhook to istiod when the release was created for version 1.3. Which had multi process control plane. (Citadel, pilot, galley, policy)
Why the kubectl api is referencing the version 1.5 ? 

`**Affected product area (please put an X in all that apply)**

[x ] Configuration Infrastructure
[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Succesful helm release. and creation of istio config objects i.e virtualservices, gateways.
**Steps to reproduce the bug**
1) Install version 1.3 via helm. `helm install istio.io/istio --name istio --namespace istio-system -f values.yaml `
2) Delete the helm release. `helm delete --purge istio`
3) Install istio version 1.5 via istioctl.  `istioctl install --set profile=demo` 
4) Delete the istio version 1.5 `istioctl manifest generate  | kubectl delete -f -` 
5) Install version 1.3 from helm again. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
***istioctl version***:
client version: 1.4.5
control plane version: 1.3.3
***kubectl version***
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T14:19:25Z", GoVersion:"go1.13.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
***Helm Version***
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

**How was Istio installed?**
Helm
**Environment where bug was observed (cloud vendor, OS, etc)**
GCP
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment] 2020-07-31 21:31
Sounds like the webhook was not properly cleaned up, can you check `kubectl get validatingwebhookconfigurations`

**Comment by adrafiq** [comment] 2020-08-17 21:30
> Sounds like the webhook was not properly cleaned up, can you check `kubectl get validatingwebhookconfigurations`

Hey I can confirm this was the issue.  And deleting the existing webhooks, made the install proceed like normal. 
Now how can we fix that for everyone. I was trying the documented method for cleanup `istioctl manifest generate -f file | kubectl delete -f - `. Why did'nt the hooks were in the manifest. I would ask.

**Comment by howardjohn** [comment] 2020-08-24 23:00
The two webhooks should be in the `istioctl manifest generate` output from my testing. The problem is 1.3 behaved differently (the webhook was dynamically created by the deployment), is probably root cause. We only support upgrade from 1.5 to 1.6, not older versions, so I am not sure there are any current docs to update

**Comment by howardjohn** [comment] 2020-11-03 16:54
Closing as this is fixed and not supported

**Closed by howardjohn** 2020-11-03 16:54 UTC
Labels: area/environments, kind/need more info
