### ISSUE TITLE
The application in the pod could not call envoy in the pod.

### ISSUE THREAD

**Issue by kinash000** [istio/istio#15861] opened 2019-07-26 10:02 UTC
During the execution there were about 8 calls, in one of them
when trying to call another service, error 503 occurred, but the envoy did not display it in the access logs.
I can not repeat this case.
The application in the pod could not call envoy in the pod???

Log envoy:
[2019-07-25T13:03:51.144Z] "POST /com.sbt.synapse.mq.protobuf.MessageChannel/processMessage HTTP/2" 200 - "-" 2515 12 13 12 "-" "grpc-java-netty/1.18.0" "ae5c639d-1956-9ca9-939d-4c6cb7e9b50f" "mq-gateway-pprbim:6565" "10.129.10.37:6565" outbound|6565||mq-gateway-pprbim.synapse-esbmdm-prom.svc.cluster.local - 172.30.143.192:6565 10.128.5.117:58202 -
[2019-07-25T12:53:51.494Z] "- - -" 0 - "-" 517 6874 600151 - "-" "-" "-" "-" "10.112.128.100:9093" outbound|9093||alertmanager-operated.openshift-monitoring.svc.cluster.local 10.128.5.117:33714 10.112.128.100:9093 10.128.5.117:33712 -
[2019-07-25T13:03:56.544Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:56412 10.128.5.117:8081 10.128.4.1:32774 -
[2019-07-25T13:04:06.544Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:56696 10.128.5.117:8081 10.128.4.1:33058 -
[2019-07-25T13:04:13.423Z] "POST /com.sbt.synapse.mq.protobuf.MessageChannel/processMessage HTTP/2" 200 - "-" 48727 11 2 1 "-" "grpc-java-netty/1.18.0" "fbeb5946-ecc2-9b94-b412-abfac7eefdf5" "service-router-pprbim-transform-services:6565" "127.0.0.1:6565" inbound|6565|grpc|snp-createprivateclient-skm.synapse-esbmdm-prom.svc.cluster.local - 10.128.5.117:6565 10.129.5.42:33972 outbound_.6565_._.snp-createprivateclient-skm.synapse-esbmdm-prom.svc.cluster.local
[2019-07-25T13:04:13.429Z] "POST /personServices/person/ HTTP/1.1" 200 - "-" 2176 272 147 146 "-" "Java/1.8.0_191" "9ca8fee9-1ea8-9706-a54d-3175bf01f3d3" "usv.ingress.apps.prom-istio.****.ru" "10.128.5.109:80" outbound|80||istio-egressgateway-synapse-esbmdm-prom.synapse-esbmdm-prom.svc.cluster.local - 10.112.122.198:80 10.128.5.117:35028 -
[2019-07-25T13:04:13.578Z] "POST /com.sbt.synapse.mq.protobuf.MessageChannel/processMessage HTTP/2" 200 - "-" 2516 12 5 4 "-" "grpc-java-netty/1.18.0" "0890ed4c-2575-949b-a2a2-58ffcf406c19" "mq-gateway-pprbim:6565" "10.129.5.42:6565" outbound|6565||mq-gateway-pprbim.synapse-esbmdm-prom.svc.cluster.local - 172.30.143.192:6565 10.128.5.117:58202 -
[2019-07-25T13:04:15.672Z] "POST /com.sbt.synapse.mq.protobuf.MessageChannel/processMessage HTTP/2" 200 - "-" 67731 11 2 1 "-" "grpc-java-netty/1.18.0" "3cc9dd9c-01d5-9cc6-8ca9-68a9f0bec238" "service-router-pprbim-transform-services:6565" "127.0.0.1:6565" inbound|6565|grpc|snp-createprivateclient-skm.synapse-esbmdm-prom.svc.cluster.local - 10.128.5.117:6565 10.130.4.163:33204 outbound_.6565_._.snp-createprivateclient-skm.synapse-esbmdm-prom.svc.cluster.local
[2019-07-25T13:04:15.677Z] "POST /com.sbt.decode.DecodeApi/getDecodeValueStream HTTP/2" 200 - "-" 16 20 2 1 "-" "grpc-java-netty/1.18.0" "8ada0cec-3ef9-93fc-9906-2ad2eeada5b4" "snp-decode-module:6565" "10.128.5.118:6565" outbound|6565||snp-decode-module.synapse-esbmdm-prom.svc.cluster.local - 172.30.72.126:6565 10.128.5.117:43472 -
[2019-07-25T13:04:15.683Z] "POST /personServices/person/ HTTP/1.1" 200 - "-" 2227 272 411 409 "-" "Java/1.8.0_191" "358ffe7e-3db6-9750-995b-b2a51b990295" "usv.ingress.apps.prom-istio.****.ru" "10.128.8.17:80" outbound|80||istio-egressgateway-synapse-esbmdm-prom.synapse-esbmdm-prom.svc.cluster.local - 10.112.122.198:80 10.128.5.117:35028 -
[2019-07-25T13:04:16.094Z] "POST /com.sbt.synapse.mq.protobuf.MessageChannel/processMessage HTTP/2" 200 - "-" 2516 12 4 4 "-" "grpc-java-netty/1.18.0" "e9ffa673-b111-9585-825d-15a5a529a78c" "mq-gateway-pprbim:6565" "10.129.5.44:6565" outbound|6565||mq-gateway-pprbim.synapse-esbmdm-prom.svc.cluster.local - 172.30.143.192:6565 10.128.5.117:58202 -
[2019-07-25T13:04:16.544Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:56964 10.128.5.117:8081 10.128.4.1:33326 -
[2019-07-25T13:04:18.071Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:57010 10.128.5.117:8081 10.128.4.1:33372 -
[2019-07-25T13:04:26.544Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:57222 10.128.5.117:8081 10.128.4.1:33584 -
[2019-07-25T13:04:36.544Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:57462 10.128.5.117:8081 10.128.4.1:33824 -
[2019-07-25T13:04:36.936Z] "POST /com.sbt.synapse.mq.protobuf.MessageChannel/processMessage HTTP/2" 200 - "-" 70585 11 4 3 "-" "grpc-java-netty/1.18.0" "a1cca135-0df1-9c21-8638-29efbcd89854" "service-router-pprbim-transform-services:6565" "127.0.0.1:6565" inbound|6565|grpc|snp-createprivateclient-skm.synapse-esbmdm-prom.svc.cluster.local - 10.128.5.117:6565 10.128.5.110:45010 outbound_.6565_._.snp-createprivateclient-skm.synapse-esbmdm-prom.svc.cluster.local
[2019-07-25T13:04:36.965Z] "POST /com.sbt.synapse.mq.protobuf.MessageChannel/processMessage HTTP/2" 200 - "-" 4672 12 214 213 "-" "grpc-java-netty/1.18.0" "ab983d57-7833-9cbc-8f11-bbf1b6f3b186" "mq-gateway-pprbim:6565" "10.129.8.21:6565" outbound|6565||mq-gateway-pprbim.synapse-esbmdm-prom.svc.cluster.local - 172.30.143.192:6565 10.128.5.117:58202 -
[2019-07-25T13:04:46.544Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:57724 10.128.5.117:8081 10.128.4.1:34086 -
[2019-07-25T13:04:56.544Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:57994 10.128.5.117:8081 10.128.4.1:34356 -
[2019-07-25T13:05:06.544Z] "- - -" 0 - "-" 130 164 1 - "-" "-" "-" "-" "127.0.0.1:8081" inbound|8081|mgmt-8081|mgmtCluster 127.0.0.1:58248 10.128.5.117:8081 10.128.4.1:34610 -

Log Application:
2019-07-25 16:04:36.942 [INFO ] [pool-2-thread-3] [c.s.s.i.IntegrationScenarioService] [T:] - [ID:414d51204d39392e4553422e4d444d2ed329235dd6ade02b] Sending transformed request body to provider...
2019-07-25 16:04:36.959 [ERROR] [pool-2-thread-3] [c.s.s.i.IntegrationScenarioService] [T:] - [ID:414d51204d39392e4553422e4d444d2ed329235dd6ade02b] Got exception. Create error answer
feign.FeignException: status 503 reading USVService#createPrivateClient(CreatePrivateClientRq)
        at feign.FeignException.errorStatus(FeignException.java:78)
        at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:93)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:149)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy110.createPrivateClient(Unknown Source)
        at transform.component.PPRBUCPUtilsUnit.requestForProvider(PPRBUCPUtilsUnit.java:32)
        at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sbt.synapse.integrationscenario.adapter.IntegrationScenarioAdapterImpl.execute(IntegrationScenarioAdapterImpl.java:36)
        at com.sbt.synapse.integrationscenario.IntegrationScenarioService.runScenarioLogic(IntegrationScenarioService.java:134)
        at com.sbt.synapse.integrationscenario.IntegrationScenarioService.processMessage(IntegrationScenarioService.java:72)
        at com.sbt.synapse.mq.protobuf.MessageChannelGrpc$MethodHandlers.invoke(MessageChannelGrpc.java:209)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.opentracing.contrib.grpc.ServerTracingInterceptor$2.onHalfClose(ServerTracingInterceptor.java:190)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:711)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

P.S: the application time and the time of the envo is different by 3 hours

Istio use OS installation.
$ istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

Version OS
OpenShift Master:
v3.11.98
Kubernetes Master:
v1.11.0+d4cacc0
OpenShift Web Console:
v3.11.98

**Comment by esnible** [comment] 2019-08-01 14:32
Can you confirm that the TCP port used on the failed call is the same as the port used on the successful calls?

If a Service exposes multiple ports, but Envoy isn't logging traffic for all of them, the pod Deployment may lack a `containerPort`.  See https://istio.io/docs/setup/kubernetes/additional-setup/requirements/

I have also seen this on rare occasions when Envoy crashes and restarts.  During the restart traffic may not be logged.

**Comment by kinash000** [comment] 2019-08-24 13:57
@ensible Thanks for the answer 
_Can you confirm that the TCP port used on the failed call is the same as the port used on the successful calls?_
Yes

_If a Service exposes multiple ports, but Envoy isn't logging traffic for all of them, the pod Deployment may lack a containerPort. See https://istio.io/docs/setup/kubernetes/additional-setup/requirements/_
This requirement is done. Port name set.

_I have also seen this on rare occasions when Envoy crashes and restarts. During the restart traffic may not be logged._
In istio-proxy logs all is well. 
But I noticed in the monitoring of the openshift the entry about the start of the container istio-init:
![63500225-2685f400-c4d2-11e9-99f0-6cd5809d38a9](https://user-images.githubusercontent.com/22095634/63638393-e8ceca00-c68f-11e9-9a1f-51b699bb8b92.jpg)

Сan starting an istio-init container cause an error?
And judging by the log, the istio-init container starts periodically. This is normal?

**Comment by vadimeisenbergibm** [comment] 2019-10-03 16:41
@kinash000 So can this issue be closed, since it looks like a duplicate of https://github.com/istio/istio/issues/16473 ? The problem is related to the init container restarted on OpenShift, it is not Istio's fault.

We are going to make Istio resilient to the init container restarts, there is another issue for it https://github.com/istio/istio/issues/16768.

**Closed** 2019-10-07 00:01 UTC
Labels: area/networking, bug bashed
