### ISSUE TITLE
Istio 1.5.0 can not find istiod installation from Helm chart install

### ISSUE THREAD

**Issue by fm9282** [istio/istio#22148] opened 2020-03-13 03:08 UTC
**Bug description**
Using helm chart to install demo(install/kubernetes/helm/istio/values-istio-demo.yaml), but can not find istiod installation,  does Isito1.5.0 support installation from Helm and Tiller?

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
helm chart
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by tariq1890** [comment] 2020-03-30 23:15
Some inputs on this would be great. @howardjohn ?

**Comment by howardjohn** [comment] 2020-03-30 23:56
Please follow https://istio.io/docs/setup/install/istioctl/, the helm approach is deprecated and doesn't have the new istiod/telemetry v2 features

**Comment by tariq1890** [comment] 2020-03-31 05:46
I am not sure if the helm approach works. The latest docker images seem to reference some configmaps containing envoy config which isn't even present in the helm charts.

While I understand that it's deprecated, it should definitely work, correct?

**Comment by howardjohn** [comment] 2020-03-31 13:33
It should work with 1.5 images, if you are really using "latest" images
(master) then it is not expected to work

**Comment by kylebevans** [comment] 2020-03-31 17:41
@howardjohn To move from an installation via helm to one via istioctl, is there an upgrade path or must istio be uninstalled via helm and then installed via istioctl?

**Comment by howardjohn** [comment] 2020-03-31 18:25
@kylebevans this is an area we unfortunately did poorly in and didn't provide a proper migration path. We had retrospective about this and agreed this was a mistake and will not do similar things in the future (as much as possible). In 1.6, we are introducing a new feature allowing proper transition from helm to istioctl (and upgrades in general). Proper documentation is still pending, but the design doc can be found https://docs.google.com/document/d/1d1z5PC8wvh9QiR3NesAaPm6w2HnE4-KIfjB7GB-_Wf8.

In terms of today, you can either uninstall and reinstall, or just try to run the istioctl command over the existing installation, but do note that this is not tested/support so I wouldn't do this in a real production environment.

**Comment by cbron** [comment] 2020-04-02 23:34
@howardjohn doc is restricted, can you open up link or elaborate on design ? We are trying to determine correct approach on migration. Is design primarily around enhancing istioctl and/or operator to handle helm-migration and upgrades via a sub-command like upgrade or manifest ?

**Comment by howardjohn** [comment] 2020-04-02 23:35
@cbron you can join the google group, its the only way I can share https://istio.io/about/community/join/. should be auto approved.

**Comment by howardjohn** [comment] 2020-05-15 04:23
Closing as this is working as intended. Take a look at the upgrade notes which give a safe migration path from Helm to istioctl as well in 1.6. Thanks!

**Closed by howardjohn** 2020-05-15 04:23 UTC
Labels: area/environments, kind/docs, lifecycle/needs-triage
