### ISSUE TITLE
`istioctl manifest` does not work with CNI

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18561] opened 2019-11-01 19:21 UTC
```
$ istioctl manifest generate --set profile=demo --set cni.enabled=true --set cni.components.cni.enabled=true --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/var/run/multus/cni/net.d

bad path=value (values.cni.cniBinDir=/var/lib/cni/bin): unknown field "cni" in v1alpha1.Values
```

This is istioctl from 1.4:
```
$ istioctl version --short=false --remote=false
version.BuildInfo{Version:"69dffe00dec378e2a9a24e42bc36746f26f3c9a6", GitRevision:"69dffe00dec378e2a9a24e42bc36746f26f3c9a6", GolangVersion:"go1.13.3", BuildStatus:"Clean", GitTag:"1.4.0-beta.1-19-g69dffe00d"}
```

**Comment by jmazzitelli** [comment] 2019-11-01 19:23
I just wrote up a dup of this issue. I'll close it - here's what my description said with replication procedures:

---

As per docs: https://preliminary.istio.io/docs/setup/additional-setup/cni#installation I want to install CNI because I'm using OpenShift 4. But istioctl fails:

```
Failed to generate and apply manifests, error: failed to generate tree from the set overlay, error: bad path=value (values.cni.cniBinDir=/var/lib/cni/bin): unknown field "cni" in v1alpha1.Values
```

Replication: run this script

```
# download latest build from 11/1/2019:
wget https://storage.googleapis.com/istio-build/dev/1.4-alpha.5a79dedda6d383eef412088b3bc331a236fe3fcd/istio-1.4-alpha.5a79dedda6d383eef412088b3bc331a236fe3fcd-linux.tar.gz

# untar
tar xvf istio-1.4-alpha*

# go to bin where istioctl is
cd istio-1.4*/bin
pwd

# try to install with CNI options
./istioctl manifest apply --set profile=demo --set cni.enabled=true --set cni.components.cni.enabled=true --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/var/run/multus/cni/net.d
```

**Comment by sdake** [comment] 2019-11-01 19:53
@ostromart can you offer some advice on how to solve this problem.  I am super overloaded atm but I might be able to find someone to fix if you can provide some idea on resolution.

Cheers
-steve

**Comment by sdake** [comment] 2019-11-01 20:47
trimming the input a bit seems to work:

```
sdake@beast-01:~/istio-1.4-alpha.5a79dedda6d383eef412088b3bc331a236fe3fcd/bin$ ./istioctl manifest apply --set profile=demo --set cni.enabled=true --set cni.components.cni.enabled=true
```
...

**Comment by jmazzitelli** [comment] 2019-11-01 20:50
> trimming the input a bit seems to work:
> 
> ```
> sdake@beast-01:~/istio-1.4-alpha.5a79dedda6d383eef412088b3bc331a236fe3fcd/bin$ ./istioctl manifest apply --set profile=demo --set cni.enabled=true --set cni.components.cni.enabled=true
> ```
> 
> ...

@sdake right, that is what I first did too :) The problem is that doesn't apply CNI completely. How I found this out is because if you look at the telemetry in Prometheus, you don't see any telemetry coming from any pods other than istio-ingressgateway.

See: https://istio.slack.com/archives/C382V8Q92/p1572613433131600

**Comment by jmazzitelli** [comment] 2019-11-01 20:55
In case that slack URL doesn't work, here's what I said - this is how you know CNI isn't working:

----

is anyone seeing telemetry not getting generated from non-ingress pods on 1.4.0.beta-1? I see istio-proxy containers on all my bookinfo pods, but all the telemetry I get is:

![image](https://user-images.githubusercontent.com/2029470/68055900-240cfb00-fcc8-11e9-8904-ba1a7028727d.png)

`istio_request_bytes_count{destination_workload_namespace="bookinfo"}` results in a single row of data which jives with what Kiali is showing.

```
istio_request_bytes_count{destination_app="productpage",destination_version="v1",destination_workload="productpage-v1",destination_workload_namespace="bookinfo", source_app="istio-ingressgateway",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"  ...// }
```

so for some reason, only the data coming in from ingress gateway is in telemetry - none of the internal bookinfo pods has any telemetry

and I confirmed all my sidecar proxys are running:

```
$ for p in $(oc get pods -n bookinfo -o name); do echo -n "$p = "; oc get $p -n bookinfo -o jsonpath='{.status.containerStatuses[?(@.name=="istio-proxy")].ready}'; echo; done
pod/details-v1-c5b5f496d-hk2wd = true
pod/productpage-v1-c7765c886-wn6gk = true
pod/ratings-v1-f745cf57b-5nmdj = true
pod/reviews-v1-75b979578c-x2hrd = true
pod/reviews-v2-597bf96c8f-txthc = true
pod/reviews-v3-54c6c64795-2cj6d = true
```

**Comment by richardwxn** [comment] 2019-11-01 20:59
not familiar how CNI works, but the reason why you get the bad path error is because it doesn't exist in the values pass through proto defined here for CNI: "https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha1/values_types.pb.go#L298"

**Comment by jmazzitelli** [comment] 2019-11-01 21:02
@richardwxn right - I think the issue is the wrong version is being used.. I think @sdake said istioctl should be using v1alpha2

**Comment by sdake** [comment] 2019-11-01 21:05
@jmazzitelli I was mistaken - the values pass-through only has one version atm.

**Comment by richardwxn** [comment] 2019-11-01 21:11
yep the values pass through proto defined in v1alpha1 is used internally for validation only, which should not be used in this case that cause the overrides error. Let me take a deeper look to check.

**Comment by sdake** [comment] 2019-11-02 15:54
Thanks a bunch, @richardwxn - super appreciate your effort in this area.  I would also like the operator controller loop to be able to take these configuration values.  Is that viable or possible?

Cheers
-steve

**Closed** 2019-11-02 23:31 UTC
Labels: area/environments/installer

**Comment by richardwxn** [comment] 2019-11-04 00:23
@sdake What configuration values you are referring to? The manifests generation logic is shared between CLI and controller including the validation part. Or are you talking about the force flag from CLI?
