### ISSUE TITLE
Ambient : WebAssembly filter configuration with imagePullSecret for specific service not functioning as expected

### ISSUE THREAD

**Issue by adilmp1** [istio/istio#51288] opened 2024-05-29 18:17 UTC
While attempting to write integration tests for wasm for ambient mode, https://github.com/istio/istio/pull/51286, as per https://github.com/istio/istio/issues/42337, configuration of a WebAssembly filter for a specific service encounters an issue. Upon running the test, it gets stuck during the execution of the curl command. 

```
root@debian-s-4vcpu-8gb-blr1-01:~# k get pods -n echo-1-52029
NAME                                                        READY   STATUS    RESTARTS   AGE
captured-v1-5cfbd668c9-2dtnk                                1/1     Running   0          3m20s
captured-v2-87cb7478f-thgcv                                 1/1     Running   0          3m20s
service-addressed-waypoint-gateway-istio-6555498bbf-4g4h7   1/1     Running   0          2m51s
service-addressed-waypoint-v1-6cc56b764-z2w9r               1/1     Running   0          3m20s
service-addressed-waypoint-v2-85bc887ccd-62xg5              1/1     Running   0          3m20s
sidecar-uncaptured-v1-6c678c444d-xddpv                      2/2     Running   0          3m20s
sidecar-uncaptured-v2-5c7985bf58-45v2q                      2/2     Running   0          3m19s
uncaptured-v1-7d4bc7669-jwwns                               1/1     Running   0          3m20s
uncaptured-v2-5c87d4f59f-nz9mh                              1/1     Running   0          3m19s
waypoint-7676984697-hl278                                   1/1     Running   0          3m2s
workload-addressed-waypoint-v1-f6b867985-khlc4              1/1     Running   0          3m20s
workload-addressed-waypoint-v2-6d49bf8459-xvk8p             1/1     Running   0          3m20s
root@debian-s-4vcpu-8gb-blr1-01:~# 
```

Upon inspecting the logs of the istiod pod, the following warning was found: 
```2024-05-29T18:09:17.836778Z warn delta ADS:ECDS: ACK ERROR waypoint-7676984697-hl278.echo-1-52029-6 Internal fetch Wasm module echo-1-52029.service-wasm-test: missing image pulling secret```

The WasmPlugin configuration I applied is 

```
root@debian-s-4vcpu-8gb-blr1-01:~# k get wasmplugin -n echo-1-52029 wasm-test-module-waypoint-service -o yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  annotations:
    wasmPluginVersion: g-0
  creationTimestamp: "2024-05-29T19:50:13Z"
  generation: 1
  name: wasm-test-module-waypoint-service
  namespace: echo-1-52029
  resourceVersion: "167202"
  uid: 5c98c927-4595-49e7-b7e4-eaf1245f1e8a
spec:
  imagePullSecret: reg-cred
  phase: STATS
  targetRefs:
  - group: ""
    kind: Service
    name: service-addressed-waypoint
  url: oci://10.96.137.136:1338/istio-testing/wasm/header-injector:latest

root@debian-s-4vcpu-8gb-blr1-01:~# k get secret -n echo-1-52029
NAME       TYPE                             DATA   AGE
reg-cred   kubernetes.io/dockerconfigjson   1      3m38s

# When the traffic test is manually run, it can be observed that the header injection wasm module is not applied
root@debian-s-4vcpu-8gb-blr1-01:~# kubectl -n echo-1-52029 exec deploy/captured-v1 -- curl -i "http://service-addressed-waypoint.echo-1-52029.svc.cluster.local:80/path"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408  100   408    0     0  91974      0 --:--:-- --:--:-- --:--:--   99k
HTTP/1.1 200 OK
date: Wed, 29 May 2024 19:55:29 GMT
content-length: 408
content-type: text/plain; charset=utf-8
x-envoy-upstream-service-time: 0
server: istio-envoy
x-envoy-decorator-operation: :80/*

ServiceVersion=v2
ServicePort=18080
Host=service-addressed-waypoint.echo-1-52029.svc.cluster.local
URL=/path
Cluster=cluster-0
IstioVersion=
Method=GET
Proto=HTTP/1.1
IP=10.244.0.219
Alpn=
RequestHeader=Accept:*/*
RequestHeader=User-Agent:curl/7.81.0
RequestHeader=X-Forwarded-Proto:http
RequestHeader=X-Request-Id:f0313113-68ef-4d98-8d18-6dc6b6cf8907
Hostname=service-addressed-waypoint-v2-69c97c5f7f-zpkjs
root@debian-s-4vcpu-8gb-blr1-01:~#
```

**Comment by hzxuzhonghu** [comment] 2024-05-30 06:34
You can see some logs showing this in istiod

**Comment by adilmp1** [comment] 2024-05-30 09:01
> imagePullSecret: reg-cred seems not a right format
> 
> Try test with `imagePullSecret: kubernetes://reg-cred`

The same imagePullSecret (reg-cred) works correctly when the WasmPlugin is applied at the waypoint.

```
--- PASS: TestGatewaySelection (7.94s)
    --- PASS: TestGatewaySelection/OCI_initial_creation_with_latest_for_a_gateway (4.29s)
    --- PASS: TestGatewaySelection/OCI_Configure_WebAssembly_filter_for_waypoint_gateway (1.62s)
PASS
2024-05-30T08:54:52.498951Z     info    tf      === DONE: Test Run: 'ambient' ===
2024-05-30T08:54:52.498957Z     info    tf      === Suite "ambient" run time: 52.650140107s ===
2024-05-30T08:54:52.498968Z     info    tf      Wrote trace to /tmp/trace.yaml
2024-05-30T08:54:52.499185Z     debug   tf      Begin cleaning up scope: [suite(ambient)]
2024-05-30T08:54:52.499203Z     debug   tf      Done cleaning up scope: [suite(ambient)]
ok      istio.io/istio/tests/integration/ambient        52.717s

root@debian-s-4vcpu-8gb-blr1-01:~/go/src/projects/istio# k get wasmplugin waypoint-wasm-test -n echo-1-40158 -o yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  annotations:
    wasmPluginVersion: g-1
  creationTimestamp: "2024-05-30T08:54:50Z"
  generation: 1
  name: waypoint-wasm-test
  namespace: echo-1-40158
  resourceVersion: "319609"
  uid: 7cbeef8a-89a4-48ff-a3ee-17d4f9dd3eac
spec:
  imagePullSecret: reg-cred
  phase: STATS
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: waypoint
  url: oci://10.96.134.93:1338/istio-testing/wasm/header-injector:latest
root@debian-s-4vcpu-8gb-blr1-01:~/go/src/projects/istio# 
```

**Comment by kfaseela** [comment] 2024-05-30 09:05
@hzxuzhonghu i think the format is correct as per @adilmp1 's finding above. The same format works fine when the wasmplugin is applied at waypoint instead of service.

**Comment by hzxuzhonghu** [comment] 2024-05-30 11:18
This is where the error reported
```
func rewriteVMConfig(resourceName string, vm *wasmextensions.VmConfig, status *string, cache Cache, configName string) error {
	envs := vm.GetEnvironmentVariables()
	var pullSecret []byte
	pullPolicy := Unspecified
	resourceVersion := ""
	if envs != nil {
		if sec, found := envs.KeyValues[model.WasmSecretEnv]; found {
			if sec == "" {
				*status = fetchFailure
				return fmt.Errorf("cannot fetch Wasm module %v: missing image pulling secret", configName)
			}
			pullSecret = []byte(sec)
		}

```


And this is where we set empty when secret name is not well formated `imagePullSecret: kubernetes://{namespace}/reg-cred`
```
func updatePluginConfig(pluginConfig *wasmextensions.PluginConfig, pullSecrets map[string][]byte) {
	// Find the pull secret resource name from wasm vm env variables.
	// The Wasm extension config should already have a `WASM_IMAGE_PULL_SECRET` env variable
	// at in the VM env variables, with value being the secret resource name. We try to find the actual
	// secret, and replace the env variable value with it. When ECDS config update reaches the proxy,
	// agent will extract out the secret from env variable, use it for image pulling, and strip the
	// env variable from VM config before forwarding it to envoy.
	envs := pluginConfig.GetVmConfig().GetEnvironmentVariables().GetKeyValues()
	secretName := envs[model.WasmSecretEnv]
	if secretName != "" {
		if sec, found := pullSecrets[secretName]; found {
			envs[model.WasmSecretEnv] = string(sec)
		} else {
			envs[model.WasmSecretEnv] = ""
		}
	}
}
```

**Comment by hzxuzhonghu** [comment] 2024-05-30 11:21
And take a look at how we parse imagePullSecret 

```
func parseSecretName(resourceName string, proxyCluster cluster.ID) (SecretResource, error) {
	// The secret resource name must be formatted as kubernetes://secret-namespace/secret-name.
	if !strings.HasPrefix(resourceName, credentials.KubernetesSecretTypeURI) {
		return SecretResource{}, fmt.Errorf("misformed Wasm pull secret resource name %v", resourceName)
	}
	res := strings.TrimPrefix(resourceName, credentials.KubernetesSecretTypeURI)
	sep := "/"
	split := strings.Split(res, sep)
	if len(split) != 2 {
		return SecretResource{}, fmt.Errorf("misformed Wasm pull secret resource name %v", resourceName)
	}
	return SecretResource{
		SecretResource: credentials.SecretResource{
			ResourceType: credentials.KubernetesSecretType,
			Name:         split[1],
			Namespace:    split[0],
			ResourceName: resourceName,
			Cluster:      proxyCluster,
		},
	}, nil
}
```

**Comment by hzxuzhonghu** [comment] 2024-05-30 11:35
nvm, i see where we convert the name format to `imagePullSecret: regcred`. It is in `initWasmPlugins`, before generating ECDS

**Comment by kfaseela** [comment] 2024-05-30 11:48
@adilmp1 may be you can try fixing the bug yourself with the inputs what Zhonghu has given. Will be a new experience for you 🙂

**Comment by hzxuzhonghu** [comment] 2024-05-30 11:48
Figurred out the root cause: for wasmplugin with targetRef set to  `service`, the ecds generator cannot find the wasmPlugin during secret pull.

```
func (e *EcdsGenerator) Generate(proxy *model.Proxy, w *model.WatchedResource, req *model.PushRequest) (model.Resources, model.XdsLogDetails, error) {
	if !ecdsNeedsPush(req) {
		return nil, model.DefaultXdsLogDetails, nil
	}

	wasmSecrets := referencedSecrets(proxy, req.Push, w.ResourceNames)
```

**Comment by hzxuzhonghu** [comment] 2024-05-30 11:51
I am happy to guide more. 

I think the most simple fix is to change https://github.com/istio/istio/blob/7974cb96c411a4751a643c9d180b06178d5a28bb/pilot/pkg/xds/ecds.go#L170

with `wasmPlugins := push.WasmPluginsByName(proxy, parseExtensionName(extensionConfigNames))`

**Comment by hzxuzhonghu** [comment] 2024-05-30 11:52
Then #51018 fix is complete

**Comment by adilmp1** [comment] 2024-05-30 16:09
Ok, I will try to fix it

**Comment by adilmp1** [comment] 2024-05-31 10:40
@hzxuzhonghu  I have made the suggested changes to ```ecds.go``` . Could you please review it

**Comment by kfaseela** [comment] 2024-05-31 10:46
@hzxuzhonghu @howardjohn the fix pointed out  has been added to https://github.com/istio/istio/pull/51286 by @adilmp1

**Comment by kfaseela** [comment] 2024-10-31 13:54
@MaYuan-02 : Will you be interested in taking a look at this issue?

**Comment by MaYuan-02** [comment] 2024-11-01 03:46
@kfaseela Sorry, I'm not quite clear on what this issue needs me to do. It seems that the problem with imagePullSecret for
 the Service scope wasmplugin has already been fixed.

**Comment by kfaseela** [comment] 2024-11-01 20:44
> @kfaseela Sorry, I'm not quite clear on what this issue needs me to do. It seems that the problem with imagePullSecret for the Service scope wasmplugin has already been fixed.

https://github.com/istio/istio/blob/master/tests/integration/ambient/wasm_test.go#L231 should give you some idea

**Comment by MaYuan-02** [comment] 2024-11-04 02:06
OK, I will try to reproduce and fix it. If there is any progress, I will discuss it with you here.

**Comment by kfaseela** [comment] 2024-11-04 13:25
> OK, I will try to reproduce and fix it. If there is any progress, I will discuss it with you here.

If you intend to fix it, let me know, I will reopen this issue and assign to you..

**Comment by MaYuan-02** [comment] 2024-11-05 08:46
@kfaseela you can assign this issue to me. I will fix this as soon as possible.

**Comment by MaYuan-02** [comment] 2024-12-18 03:33
@kfaseela This PR #54232 has been merged, can we close the current issue now?

**Closed** 2024-12-18 05:23 UTC
Labels: area/networking, lifecycle/automatically-closed, help wanted

**Comment by PranavBhatSF** [comment] 2025-01-22 11:35
@MaYuan-02 Is there any workaround for this issue? I don't see the fix in 1.24.2.

**Comment by MaYuan-02** [comment] 2025-01-22 12:16
@PranavBhatSF This fix is included in version 1.25, which has not yet been released.

As a workaround, you might consider applying a gateway-scope WasmPlugin and performing some matching within your plugin. Unfortunately, I haven't been able to identify a better method for applying a service-scope WasmPlugin in an ambient environment.

Using a service-scope WasmPlugin without specifying an imagePullSecret is also a viable option.

**Comment by PranavBhatSF** [comment] 2025-01-22 13:09
@MaYuan-02 We are using gateway scoped WasmPlugin.
```
spec:
  imagePullPolicy: IfNotPresent
  imagePullSecret: <secret>
  pluginConfig:
    active_active: "false"
    cache_ttl: 3600
    forward_services:
    - name: service1
       paths:
       - ""
    forward_target: ""
    fqdn: <FQDN>
  selector:
    matchLabels:
      istio: ingressgateway
```
We need to use imagePullSecret to pull the wasm charts from registry during runtime.

**Comment by MaYuan-02** [comment] 2025-01-23 02:03
@PranavBhatSF 
The current issue primarily focuses on the service-scope WasmPlugin in ambient mode. The problem you're encountering with the gateway-scope might be due to other reasons.
You can try searching for related errors or warnings in the istiod or gateway. Istio includes integration tests for gateway-scope WasmPlugins, so this feature should be functioning correctly.
If you still suspect it's a bug, you can open a new issue and tag me.
