### ISSUE TITLE
can envoy support multipart/form-data upload?

### ISSUE THREAD

**Issue by huanghuangzym** [istio/istio#14133] opened 2019-05-16 09:54 UTC
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
when use multipart/form-data post file ,envoy proxy return 502,and not connect to upstream

**Expected behavior**
can use multipart upload

**Steps to reproduce the bug**
upload file use http multipart/form-data  to envoy

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
k8s v1.13.4
istio 1.0.5
**How was Istio installed?**
by helm

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS Linux release 7.5.1804 (Core)
Linux staging-master1 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by rshriram** [comment] 2019-05-17 18:32
This is a question for Envoy repo. I would suggest you post the question there.

**Comment by tariq1890** [comment] 2020-09-22 19:57
@huanghuangzym Did you happen to open an issue in envoy for this? I am trying to track down related issues.

Envoy seems to be creating problems with multipart form data upload

**Comment by tariq1890** [comment] 2020-09-23 22:25
Reopening this issue, since this is a blocker for us when using Istio

I've also posted this issue in Envoy: https://github.com/envoyproxy/envoy/issues/13240

**Comment by huanghuangzym** [comment] 2020-09-27 09:53
> Reopening this issue, since this is a blocker for us when using Istio
> 
> I've also posted this issue in Envoy: [envoyproxy/envoy#13240](https://github.com/envoyproxy/envoy/issues/13240)

we find it is a used bug  by application
the application used nodejs ,it is nodejs bug

**Comment by howardjohn** [comment] 2020-10-23 16:12
Duplicate of https://github.com/istio/istio/issues/27423#issuecomment-696363395 and envoyproxy/envoy#13240 and probably others. Lets try to keep this in one place to avoid split conversations.

**Closed by howardjohn** 2020-10-23 16:12 UTC
Labels: area/networking
