### ISSUE TITLE
Mixer start fails on Kubernetes restart

### ISSUE THREAD

**Issue by theganyo** [istio/istio#7026] opened 2018-07-11 21:22 UTC
Since moving to the 1.0 builds, the Mixer process is no longer able to properly restart if the Kubernetes environment it is running in is stopped/started or restarted. Instead, I see the following error in the both the istio-policy and istio-telemetry logs when Kubernetes is started:

    Unable to initialize Mixer: unable to listen: listen unix /sock/mixer.socket: bind: address already in use

All other Istio services still seem to restart fine.

My Kube env is Docker for Mac.

$istioctl version
Version: release-1.0-20180711-09-15
GitRevision: 8af1366b7603401585de5915b79e4b9282cc59a5
User: root@c77611bb72fa
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kyessenov** [comment] 2018-07-11 21:36
That sounds like a general problem with minikube and UDS sockets. My guess is that minkube is just dropping the sockets during restart.

**Comment by theganyo** [comment] 2018-07-11 23:22
It's Docker, not Minikube, FWIW. But this used to work fine until the recent Istio builds. My guess is that something changed in how Istio Mixer is managing its connections.

**Comment by mandarjog** [comment] 2018-07-13 23:47
duplicate of #7050

**Comment by mandarjog** [comment] 2018-08-02 22:46
@theganyo this is resolved in 1.0

**Closed by mandarjog** 2018-08-02 22:46 UTC
