### ISSUE TITLE
Sidecar injector cert rotation

### ISSUE THREAD

**Issue by costinm** [istio/istio#5947] opened 2018-05-31 13:46 UTC
On a long running cluster (installed 2 weeks ago), running continuously ever since:

"test           2018-05-30 20:29:05 -0700 PDT   2018-05-30 20:28:24 -0700 PDT   14        fortio-noistio1-b66b8c5b4.15339cfbd4983ce4                 ReplicaSet                                                            Warning   FailedCreate                   replicaset-controller                            Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: x509: certificate signed by unknown authority"

It is likely to be a cert rotation issue - may be other issue. Filed separate bug to add metrics, but 
need to investigate the code as well. 

This is critical for 1.0

**Comment by ayj** [comment] 2018-06-05 00:13
I've verified that the webhook is detecting local configuration and cert changes and reloading accordingly. I did observe a delay between updating the k8s secret and local volume updates in the injector pod (e.g. tens of seconds to minutes). 

Re-applying the mutating webhook configuration will clear the patched caBundle. If the sidecar injector deployment itself didn't change then the pods won't re-run and re-patch the bundle.

**Comment by costinm** [comment] 2018-06-05 03:46
So we'll need to watch the secrets directly instead of relying on volume ?
Sounds good, pilot already does that.
Requiring user to update or wait doesn't work.

**Comment by jhrv** [comment] 2018-06-12 11:51
We are hitting the same issue.

When we are setting up our clusters, we do a kubectl apply -f on all yaml for the cluster, assuming it to be idempotent. Whenever we reapply istio.yaml now, the caBundle is set to "" or null. 

Is this intended?

**Comment by ostromart** [comment] 2018-06-12 21:45
Duplicate of https://github.com/istio/istio/issues/6069

**Closed by ostromart** 2018-06-12 21:45 UTC
Labels: area/environments, kind/needed for 1.0
