### ISSUE TITLE
[Istio 1.5.0-beta.1] Request to bookinfo productpage via ingressgw fails

### ISSUE THREAD

**Issue by objectiser** [istio/istio#21104] opened 2020-02-13 14:22 UTC
**Bug description**
Curl request to product page, via Ingress Gateway, results in `UNAVAILABLE:upstream connect error or disconnect/reset before headers. reset reason: connection failure`

**Expected behavior**
A valid response from the productpage service.

**Steps to reproduce the bug**
Running on minikube:
```
istioctl verify-install 
istioctl manifest apply --set profile=demo
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
export INGRESS_HOST=$(minikube ip)
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
curl -s http://${GATEWAY_URL}/productpage
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.0-beta.1
control plane version: 1.5.0-beta.1
data plane version: 1.5.0-beta.1 (8 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
From: https://github.com/istio/istio/releases/download/untagged-e927792f03470f745667/istio-1.5.0-beta.1-linux.tar.gz

**Environment where bug was observed (cloud vendor, OS, etc)**
Fedora-30

**Comment by esnible** [comment] 2020-02-13 18:34
Does `istioctl analyze` or `istioctl x describe service productpage` report any problems with your configuration?

**Comment by objectiser** [comment] 2020-02-17 16:59
@esnible Sorry for delay in responding:
```
$ istioctl analyze
✔ No validation issues found when analyzing namespace: default.
```
```
$ istioctl x describe service productpage
Service: productpage
   Port: http 9080/HTTP targets pod port 9080
Pod is PERMISSIVE, clients configured automatically


Exposed on Ingress Gateway http://192.168.39.5:8080

VirtualService: bookinfo
   /productpage, /static*, /login, /logout, /api/v1/products*
```

**Comment by esnible** [comment] 2020-02-21 21:49
The configuration looks good.

The Ingress Gateway is on 192.168.39.5.  You `curl http://192.168.39.5:8080/productpage` from somewhere that can reach your 192.168.0.0 network and you get a 503?

I have seen this when there are problems with the ingress or the sidecar.  Check using `kubectl get pods` that your pods are all `2/2` ready.  Use `kubectl logs` on your ingress gateway and productpage pod to see if there are any errors such as being unable to mount a secret.

**Comment by dgn** [comment] 2020-03-03 13:37
Assuming this to be a duplicate of #21556

**Comment by howardjohn** [comment] 2020-04-15 15:00
Fixed, see https://github.com/istio/istio/issues/21556. Thanks for the report!

**Closed by howardjohn** 2020-04-15 15:00 UTC
Labels: area/networking, community/testing days, lifecycle/needs-escalation
