### ISSUE TITLE
Destination Rule is not applied to traffic from all namespaces it's exported to

### ISSUE THREAD

**Issue by Lysholm** [istio/istio#15556] opened 2019-07-16 09:41 UTC
**I misidentified this to begin with see: https://github.com/istio/istio/issues/15556#issuecomment-511989768 for a correct description of what's going on** Below is the original bug report.

**Bug description**
When trying out the https via egress gateway tasks i notice they only work from the namespace the virtual service is applied to. From what i can tell this happens because the keyword "mesh" now expects a namespace prefix or it is only applied to sidecars in the local namespace. IE: "anything/mesh" is all sidecars "mesh" is current namespace sidecars.

The following VirtualService works from all namespaces:
```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-cnn
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - anything/mesh
  - istio-system/egress
  tls:
  - match:
    - gateways:
      - anything/mesh
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: 
        subset: cnn
        port:
          number: 443
  - match:
    - gateways:
      -  istio-system/egress
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
```

This one only works from the namespace the VirtualService is deployed to:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-cnn
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - istio-system/egress
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: 
        subset: cnn
        port:
          number: 443
  - match:
    - gateways:
      -  istio-system/egress
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
```

The only difference between the two is prefix for the "mesh" keyword.

**Affected product area (please put an X in all that apply)**

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expect the keyword "mesh" not to require a namespace prefix

**Steps to reproduce the bug**
Follow the steps on:
https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic 
But try the sleep example from a different namespace.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl:
```
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
egressgateway version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
nodeagent version: 
nodeagent version: 
nodeagent version: 
pilot version: 1.2.2
policy version: 1.2.2
policy version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
telemetry version: 1.2.2
telemetry version: 1.2.2
```
kubectl:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"archive", BuildDate:"2019-06-20T22:55:20Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by frankbu** [comment] 2019-07-16 19:02
@Lysholm Adding the `anything/mesh` prefix, as you describe, does not work. Instead of the VirtualService working in all namespaces, it is NOT working in all namespaces. The reason the `curl` command appears to work in all namespaces is because the VirtualService is being ignored (as expected) and the sidecars are then successfully calling the external service directly, i.e., not via the gateway as intended.

That said,  there does seem to be a bug in the documented example. The `curl` should work from a different namespace, but it does not. It seems the problem is that the DestinationRule is not being found when the the `curl` is from a different namespace. You can confirm this by adding a copy of just the DestinationRule in the second namespace.

The DestinationRule lookup algorithm is supposed to be:

1. client namespace
2. service namespace
3. istio-system

Given what's happening in this example, it seems the second one isn't being searched.

**Comment by frankbu** [comment] 2019-07-16 21:13
After further investigation, the code is working as expected. Here's what happens.

The DestinationRule is created in the first namespace, so `curl` from that namespace works according to check 1, described above. 

The `curl` requests from a second namespace fails because it doesn't find the DestinationRule according to check 1, but it also doesn't find it according to check 2 because the DestinationRule is for the service `host: istio-egressgateway.istio-system.svc.cluster.local`. This service is defined in the `istio-system` namespace, not the namespace that the DestinationRule was created in.

So, it seems that if we want this example to work from any namespace, we need to move the DestinationRule to the `istio-system` namespace. Or, maybe we should change the example, and/or explain this better in the docs. It's kind of subtle.

^^^ @rshiram @vadimeisenbergibm WDYT?

**Comment by Lysholm** [comment] 2019-07-17 13:21
@frankbu: Thanks for clearing up my misunderstanding. From what i understand the bug is rather that destination rules do not get exported currently?

From the docs on destination rule `exportTo`:
```
exportTo | string[]: A list of namespaces to which this destination rule is exported. The resolution of a destination rule to apply to a service occurs in the context of a hierarchy of namespaces. Exporting a destination rule allows it to be included in the resolution hierarchy for services in other namespaces. This feature provides a mechanism for service owners and mesh administrators to control the visibility of destination rules across namespace boundaries.If no namespaces are specified then the destination rule is exported to all namespaces by default.
```

**Comment by frankbu** [comment] 2019-07-17 14:03
@Lysholm There is actually no bug, just subtle behavior. `exportTo` is working as expected. The DestinationRule is exported to all namespaces, allowing it to be used in other namespaces, but to be used it ALSO needs to be on the lookup path (i.e., in the service's namespace or `istio-system`) as I described above.

**Comment by Lysholm** [comment] 2019-07-17 14:27
@frankbu: Ok so it works as intended. Do you know what the reasoning behind that intent is? Is there a use case that requires the "visible but not applied" logic for destination rules? Or is it a limitation?

My expectation is that it gets applied to traffic from all namespaces given the wording in the documentation and seemingly this must have been the case before as i was going through the tasks again after upgrading from 1.0 to 1.2 broke egress in my cluster.

It would at least be good to have documentation on how the lookup path works and if it can be configured.

**Comment by frankbu** [comment] 2019-07-17 14:46
@Lysholm, I agree this needs to be documented better, or the design improved, or both.

The problem is because `exportTo` defaults to all namespaces, which we are stuck with for backward compatibility. Exporting to all namespaces is very dangerous, because it allows anyone to create a DestinationRule in any namespace that can override the behavior of services in completely unrelated namespaces. There's also an issue with lookup order, if there is more than one DestinationRule for the same host.

This was a serious problem in early releases of Istio, which was fixed by limiting the lookup path to the the 3 namespaces described above.

I wonder if we can improve this by adding a mesh-wide "strict export" configuration parameter, which if set, would default `exportTo` to `.`. In that mode, resources that are not explicitly exported would not be visible in other namespaces. Then, we could add other namespaces to the lookup path for DestinationRules, although we would still need to figure out how to specify the order, if there is more than one namespace exporting a rule for the same host.

I suppose it's getting clear why this is a pretty complicated issue :-)

**Comment by rshriram** [comment] 2019-07-17 18:44
fwiw, we already have a mesh wide setting.. in the mesh config, there is a defaultDestinationRuleExportTo setting which you can set to '.' .. 

However, today, exportTo does not support anything other than . and *. The reason is because the use of specific namespaces in destination rule, creates a whole ton of issues when doing the three checks.

**Comment by frankbu** [comment] 2019-07-17 19:28
I suppose another way to solve this problem is by adding a stand-in ServiceEntry or no-op VirtualService in the same namespace as the DestinationRule, so that the DR will be found in the service namespace. For the egressgateway example, we could add this to the config:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: serviceentry-for-egressgateway
spec:
  hosts:
  - istio-egressgateway.istio-system.svc.cluster.local
```
I'll take a pass at a PR to add some documentation about DR exposure and update the egress gateway example.

**Closed** 2019-07-23 17:48 UTC
Labels: area/config, area/networking
