### ISSUE TITLE
Zone Aware Routing

### ISSUE THREAD

**Issue by Stono** [istio/istio#4702] opened 2018-04-03 07:52 UTC
Hey, 
I know someone was looking at this around a month ago in slack, but I can't find the message thread.  I'm really interested in Zone Aware Routing but at the moment (and I believe it was a problem with mtls?) it doesn't work:

```
2018-04-03T07:23:51.382022Z     info    Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/at-conference-application/sidecar~10.202.3.108~at-conference-application-89dd474c6-xgvrj.default~default.svc.cluster.local: read tcp 10.202.3.108:50694->10.192.65.162:15005: read: connection reset by peer
2018-04-03T07:24:21.385071Z     info    Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/at-conference-application/sidecar~10.202.3.108~at-conference-application-89dd474c6-xgvrj.default~default.svc.cluster.local: read tcp 10.202.3.108:50792->10.192.65.162:15005: read: connection reset by peer
2018-04-03T07:24:51.388113Z     info    Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/at-conference-application/sidecar~10.202.3.108~at-conference-application-89dd474c6-xgvrj.default~default.svc.cluster.local: read tcp 10.202.3.108:50866->10.192.65.162:15005: read: connection reset by peer
2018-04-03T07:25:21.391097Z     info    Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/at-conference-application/sidecar~10.202.3.108~at-conference-application-89dd474c6-xgvrj.default~default.svc.cluster.local: read tcp 10.202.3.108:50938->10.192.65.162:15005: read: connection reset by peer
2018-04-03T07:25:51.394193Z     info    Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/at-conference-application/sidecar~10.202.3.108~at-conference-application-89dd474c6-xgvrj.default~default.svc.cluster.local: read tcp 10.202.3.108:51012->10.192.65.162:15005: read: connection reset by peer
2018-04-03T07:26:21.397230Z     info    Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/at-conference-application/sidecar~10.202.3.108~at-conference-application-89dd474c6-xgvrj.default~default.svc.cluster.local: read tcp 10.202.3.108:51086->10.192.65.162:15005: read: connection reset by peer
2018-04-03T07:26:51.400568Z     info    Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/at-conference-application/sidecar~10.202.3.108~at-conference-application-89dd474c6-xgvrj.default~default.svc.cluster.local: read tcp 10.202.3.108:51182->10.192.65.162:15005: read: connection reset by peer
2018-04-03T07:27:21.403533Z     info    Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/at-conference-application/sidecar~10.202.3.108~at-conference-application-89dd474c6-xgvrj.default~default.svc.cluster.local: read tcp 10.202.3.108:51258->10.192.65.162:15005: read: connection reset by peer
2018-04-03T07:27:21.403577Z     info    Availability zone not set, proxy will default to not using zone aware routing.
```

Just wondering where this is on the roadmap, or if it should be working now and if this is a bug?

**Comment by nmittler** [comment] 2018-04-03 16:42
@rshriram @ZackButcher do you know the right person to look at this?

**Comment by linsun** [comment] 2018-04-03 16:58
waiting for this to get in:  https://github.com/istio/istio/pull/3913. cc @liamawhite

**Comment by liamawhite** [comment] 2018-04-03 17:24
We will also need some changes to envoy. I'll assign this to myself and keep this issue updated with any progress.

**Comment by nmittler** [comment] 2018-04-03 17:30
Sounds good! Thanks @liamawhite

**Comment by Stono** [comment] 2018-04-30 12:43
Hey @liamawhite - was there any update with this?

**Comment by liamawhite** [comment] 2018-04-30 12:50
Not yet, will be focusing on this after KubeCon.

**Comment by Stono** [comment] 2018-04-30 12:56
See you there. 👌

**Comment by liamawhite** [comment] 2018-05-07 10:36
As soon as 0.8 is released I'll be getting this fully operational.

**Comment by oreasono** [comment] 2018-05-07 10:40
@liamawhite thanks for your quick repliy. Any idea how I can work around this(getting the sidecar work again)?

**Comment by Stono** [comment] 2018-05-07 10:54
You might have a different problem than this issue because zone aware
routing with mtls disabled doesn't work (at all), however you're describing
intermittent behaviour.

I'm guessing you're not using mTLS?

PS.  Zone aware routing not working shouldn't break your sidecar either,
it's warning rather than error.

**Comment by oreasono** [comment] 2018-05-07 11:01
@Stono yes i'm not using mTLS
But with this info log showed, my sidecar no longer proxy *ANY* traffic fire from the target pod.
Therefore some of my pods in istio can send http request to *ANY* website address, meanwhile some pods can only send request to websites described in EgressRule.

**Comment by Stono** [comment] 2018-05-07 11:05
Yeah,
That is definitely a different issue then.
I suggest raising a new issue with as much log + context as possible.

Karl

**Comment by oreasono** [comment] 2018-05-07 11:09
@Stono on a second thought, that log can be irrelevant. My main issue is some  of my sidecars no longer proxy traffic. Will raise an issue. Thanks for your reply.

**Comment by liamawhite** [comment] 2018-05-07 11:10
Yes, this is a separate issue. The zone aware stuff at the moment is just setting config that envoy ignores.

**Comment by wangybgit** [comment] 2018-05-11 04:06
hello,I have the same problem:when I use the command"kubectl apply -f <(istioctl kube-inject -f bookinfo.yaml)",it is correct.
but when I use this command to apply my own application,error
 `[2018-05-11T03:11:49.516Z] "GET /istio_service1 HTTP/1.1" 302 - 0 0 14 5 "172.17.0.1" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36" "41839fbf-94c8-9b5c-99fa-065bd85940a2" "10.37.218.11:30448" "127.0.0.1:8080"
2018-05-11T03:12:12.023104Z	info	Unable to retrieve availability zone from pilot: Get http://istio-pilot.istio-system:15005/v1/az/test-istio/sidecar~172.17.0.16~test-istio-v1-d488787bc-97jm8.default~default.svc.cluster.local: read tcp 172.17.0.16:41684->10.254.71.33:15005: read: connection reset by peer
`
if I use the command"kubectl apply -f istio-service.yaml" to apply the application,the application is OK.
Curious to know what the pilot done when use "kube-inject".

**Comment by wangybgit** [comment] 2018-05-11 06:51
@oreasono hi,I have the same problem. the application helloworld and bookinfo are success,，but my own application using the sidecar hava the problem “Unable to retrieve availability zone from pilot”.How did you solve it?

**Comment by Stono** [comment] 2018-06-02 16:55
Hey @liamawhite 
Just trawling through my issues, is this something on the roadmap now 0.8 is out?

**Comment by liamawhite** [comment] 2018-06-04 05:42
Yes, I have started a discussion in #networking if you want to chime in with your reqs. We have two options: zone aware or endpoint locality load balancing and these are mutually exclusive.

**Comment by sakshigoel12** [comment] 2018-06-05 00:13
@liamawhite do you have a target for when this would be available ?

**Comment by liamawhite** [comment] 2018-06-05 02:18
Pending our discussion in the networking meeting this week... We're aiming for just zone aware in alpha for 1.0.

**Comment by costinm** [comment] 2018-06-05 03:40
What does 'mutually exclusive' mean ? Not even sure what is the difference
between 'endpoint locality' and 'zone aware', can you define the 2 ?

Pilot knows where the endpoint is. It does pass this info to envoy. Envoy
can already select local clusters first.

What is missing ?

**Comment by liamawhite** [comment] 2018-06-05 06:09
From Envoy [docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing#zone-aware-routing):

```The purpose of zone aware routing is to send as much traffic to the local zone in the upstream cluster as possible while roughly maintaining the same number of requests per second across all upstream hosts (depending on load balancing policy).```

```Another approach to determining how to weight assignments across different zones and geographical locations is by using explicit weights supplied via EDS in the LocalityLbEndpoints message. This approach is mutually exclusive with the above zone aware routing, since in the case of locality aware LB, we rely on the management server to provide the locality weighting, rather than the Envoy-side heuristics used in zone aware routing.```

So with zone aware we just have to tell envoy which zone it is in and it does best effort to keep all traffic between hosts in that zone, we do most of this already it will just require a few tweaks.

Endpoint locality picks the locality using a weighted round-robin schedule, where the locality weight is used for weighting the requests. So with a weighting of 2 66% would go to the same region and 33% would go to other regions (assuming all endpoints in the regions are healthy).

Zone aware is a binary on/off whereas locality weighting is more configurable.

**Comment by liamawhite** [comment] 2018-06-05 07:44
I believe this can be configured on a per Envoy basis, but would need to confirm. Zone aware is not completely implemented yet in v2 because the configuration of it changed.

> Also my understanding was that we use weights on clusters - i.e. cluster v1
will get 10% and cluster v2 will get 90%. And within
each cluster, zone aware is used.

This will be correct when we finish up the zone aware v2 work. Weighted EDS is different, it effectively allows you to configure how much of the traffic is kept in the same zone (locality) as opposed to the best effort as much as possible that zone aware does.

**Comment by liamawhite** [comment] 2018-06-21 17:56
Design Doc is [here](https://docs.google.com/document/d/17TVN-GUWLAuM-YHPd561qMQOXCaSMQ51wcQEkxvvW9U/edit). Discussions ongoing.

**Comment by m1093782566** [comment] 2018-06-22 05:52
Based on what I see in production deployment, topology is arbitrary. It would be great that Istio can have topology-aware routing support - including zone, rack, region, host etc.

**Comment by m1093782566** [comment] 2018-06-22 05:56
@liamawhite Is the design doc public now? I am unable to open it - it requires some permissions.

**Comment by liamawhite** [comment] 2018-06-22 06:16
updated the link so it should now work

**Comment by m1093782566** [comment] 2018-06-22 06:43
hmmm, I still can not open the link :(

**Comment by costinm** [comment] 2018-06-25 23:03
I think this should be in 1.0 - it's very important for any user with multiple zones, and a regression that it no longer works.

**Comment by liamawhite** [comment] 2018-07-23 06:56
As discussed in the design doc and on slack this is not achievable due to the way Kubernetes services map to Envoy clusters. Envoy requires that a proxy <-> cluster is a 1-1 relationship for zone aware. In Kubernetes a pod can be part of multiple services, therefore, proxy <-> cluster is a 1-many relationship.

See https://github.com/istio/istio/issues/4481 for ongoing discussions about Locality Weighted Load Balancing (LWLB) and how this could achieve something close to zone aware.

**Closed by liamawhite** 2018-07-23 06:56 UTC
Labels: area/networking, kind/customer issue
