### ISSUE TITLE
Crash on wasm

### ISSUE THREAD

**Issue by costinm** [istio/istio#21732] opened 2020-03-02 22:59 UTC
- Installed Istio 1.5 ( using 1.5-dev tag )
- fortio deployed

I see one of the pods crashing, captured a log from the pod.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by costinm** [comment] 2020-03-02 23:01
[envoy_crash.log](https://github.com/istio/istio/files/4278336/envoy_crash.log)

**Comment by costinm** [comment] 2020-03-02 23:01
[Envoy (Epoch 0)] [2020-03-02 22:57:21.160][23][trace][http2] [external/envoy/source/common/http/http2/codec_impl.cc:424] [C1] dispatched 129 bytes
[Envoy (Epoch 0)] [2020-03-02 22:57:21.160][35][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[Envoy (Epoch 0)] [2020-03-02 22:57:21.160][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2020-03-02 22:57:21.160][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 9acf3a066a37a835bafd767ba13a762687fd6763/1.13.1-dev/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2020-03-02 22:57:21.161][34][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[Envoy (Epoch 0)] [2020-03-02 22:57:21.161][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2020-03-02 22:57:21.161][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 9acf3a066a37a835bafd767ba13a762687fd6763/1.13.1-dev/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2020-03-02 22:57:21.170][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: Envoy::TerminateHandler::logOnTerminate()::$_0::operator()() [0x563903953cae]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.171][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: Envoy::TerminateHandler::logOnTerminate()::$_0::operator()() [0x563903953cae]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.180][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #1: [0x563903953bb9]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.181][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #1: [0x563903953bb9]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.189][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: std::__terminate() [0x563903eb6973]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.190][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: std::__terminate() [0x563903eb6973]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.199][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: std::__1::__function::__func<>::operator()() [0x563902063b2f]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.200][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: std::__1::__function::__func<>::operator()() [0x563902063b2f]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.208][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Extensions::Common::Wasm::Context::onConfigure() [0x563902754c1e]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.210][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Extensions::Common::Wasm::Context::onConfigure() [0x563902754c1e]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.220][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: Envoy::Extensions::Common::Wasm::getOrCreateThreadLocalWasm() [0x563902778ab4]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.227][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: Envoy::Extensions::Common::Wasm::getOrCreateThreadLocalWasm() [0x563902778ab4]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.232][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: std::__1::__function::__func<>::operator()() [0x563902392957]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.237][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: std::__1::__function::__func<>::operator()() [0x563902392957]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.241][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: std::__1::__function::__func<>::operator()() [0x563903421d08]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.246][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: std::__1::__function::__func<>::operator()() [0x563903421d08]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.251][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: std::__1::__function::__func<>::operator()() [0x563903422f38]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.256][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: std::__1::__function::__func<>::operator()() [0x563903422f38]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.260][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: Envoy::Event::DispatcherImpl::runPostCallbacks() [0x56390348cad6]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.265][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: Envoy::Event::DispatcherImpl::runPostCallbacks() [0x56390348cad6]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.270][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: Envoy::Event::DispatcherImpl::run() [0x56390348c96c]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.275][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: Envoy::Event::DispatcherImpl::run() [0x56390348c96c]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.279][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: Envoy::Server::WorkerImpl::threadRoutine() [0x563903483868]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.284][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: Envoy::Server::WorkerImpl::threadRoutine() [0x563903483868]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.289][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #12: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x563903989853]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.289][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #13: start_thread [0x7f71069496db]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.289][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Aborted, suspect faulting address 0x53900000017
[Envoy (Epoch 0)] [2020-03-02 22:57:21.289][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2020-03-02 22:57:21.289][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 9acf3a066a37a835bafd767ba13a762687fd6763/1.13.1-dev/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2020-03-02 22:57:21.289][35][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7f7106954890]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.294][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #12: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x563903989853]
[Envoy (Epoch 0)] [2020-03-02 22:57:21.294][34][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #13: start_thread [0x7f71069496db]
2020-03-02T22:57:21.357919Z	info	sds	node:sidecar~10.12.4.22~fortio-77b675c89b-d5qmm.fortio~fortio.svc.cluster.local-2 resource:ROOTCA connection is terminated: rpc error: code = Canceled desc = context canceled

**Comment by PiotrSikora** [comment] 2020-03-02 23:10
Seeing as this crashes in `onConfigure`, is it possible that this is a duplicate of https://github.com/envoyproxy/envoy-wasm/issues/439?

**Comment by mandarjog** [comment] 2020-03-03 03:20
sounds like bad config?

**Comment by mandarjog** [comment] 2020-03-03 16:23
@costinm how had you configured the wasm extension?

**Closed** 2020-09-12 05:03 UTC
Labels: area/extensions and telemetry, lifecycle/needs-triage
