### ISSUE TITLE
IP whitelist does not work

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#13326] opened 2019-04-15 08:57 UTC
**Describe the bug**
IP whitelist does not work

**Expected behavior**
Only IP addresses in the whitelist should be allowed

**Steps to reproduce the bug**
```yml
apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  name: whitelistip
  namespace: istio-system
spec:
  overrides: ['ip1', 'ip2', 'ip3']
  entryType: IP_ADDRESSES
  blacklist: false

---
apiVersion: config.istio.io/v1alpha2
kind: listentry
metadata:
  name: sourceip
  namespace: istio-system
spec:
  value: request.headers["x-forwarded-for"][0]

---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkip
  namespace: istio-system
spec:
  match: source.labels["istio"] == "ingressgateway"
  actions:
    - handler: whitelistip.listchecker
      instances:
        - sourceip.listentry
```

**Version**
```
➜  ~ istioctl version
Version: 1.0.5
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
one key installation from the menu of an alibaba cloud k8s cluster

**Environment**
alibaba cloud

**Comment by xiaozhongliu** [comment] 2019-04-15 09:00
If I use , the following error is returned:
> INVALID_ARGUMENT:whitelistip.listchecker.istio-system:180.154.17.14, 172.16.206.219 is not a valid IP address

**Comment by gargnupur** [comment] 2019-04-15 20:40
The problem is 2 fold:
First, listentry template accepts a single value and you are trying to provide 2 valid values. Secondly, request.headers["x-forwarded-for"] is parsed as a string and not an array by the language generation parser. 
To support your scenario, we would have to extend listentry template to accept a list of valid values and parse request.headers as an ip list.
@kyessenov , @douglas-reid : what do you guys think?

**Comment by kyessenov** [comment] 2019-04-15 20:52
I'm curious how `request.headers["x-forwarded-for"][0]` got accepted at all, since the parser should not be accepting array accesses.

We've put the work to add string arrays on hold for awhile. Not sure if it fits the code mauve motive. You can use CEL runtime to work with arrays once in 1.2.

**Comment by xiaozhongliu** [comment] 2019-04-16 01:27
Thanks for all ur replies.
@kyessenov What's CEL runtime? is there a link to share?
So we can take another way to get it work in istio 1.2 right? Is there any workaround now in 1.0.5 or 1.1.2?

**Comment by kyessenov** [comment] 2019-04-16 19:15
CEL is a common expression language https://github.com/google/cel-spec/blob/master/doc/langdef.md. It supports arbitrary protobufs. It's included in master as an opt-in option using `policy.istio.io/lang: CEL` annotation on rules, instances, and handlers. 

However, we still need string processing functions to handle headers. I think we want an expression of the form: `split(request.headers["x-forward-for"], ",")[0]`.

**Comment by gargnupur** [comment] 2019-04-23 20:46
@kyessenov : should we use this bug to track adding a split function for headers?
Otherwise problem in the issue can be closed as "working as intended behavior"...

**Comment by douglas-reid** [comment] 2019-06-03 23:32
I think once #14481 merges, we should close this issue. https://github.com/istio/istio/issues/2802 can be used to track any features around strings and handling them.

**Closed** 2019-06-05 17:36 UTC
Labels: area/policies and telemetry, kind/enhancement

**Comment by xiaozhongliu** [comment] 2019-09-18 15:23
I see 1.3 is already released, now how should I do to get the first ip from request.headers["x-forwarded-for"] ?

**Comment by gargnupur** [comment] 2019-09-18 17:27
I don't think it's ready yet. https://github.com/istio/istio/issues/2802 was supposed to track that feature request but stale bot closed that issue. @kyessenov does that sound right?

**Comment by xiaozhongliu** [comment] 2019-09-19 01:31
Ok now let's forget all of that, could you help to answer this:
What's the right way to realize client ip whitelist, other than source.ip indicated in the official sample?

**Comment by gargnupur** [comment] 2019-09-23 21:00
how about using x-real-ip?

**Comment by x15zhang** [comment] 2019-10-22 00:29
Any update? How to get the first ip from request.headers["x-forwarded-for"] ?

**Comment by roksaksida** [comment] 2020-02-11 16:14
Any update? How to get the first ip from x-forwarded-for?

**Comment by roooxvee** [comment] 2020-02-11 16:20
Is there any update?
How to get the first ip from request.headers["x-forwarded-for"]?

**Comment by courcelm** [comment] 2020-02-28 20:30
I'm also interested in this answer.

**Comment by kyessenov** [comment] 2020-02-28 20:54
Hi,
Mixer has been deprecated, and the IP white listing feature has been superseded by the [authorization policy](https://istio.io/docs/reference/config/security/authorization-policy/). Please re-direct your questions to the @istio/wg-security-maintainers .

**Comment by Arpeet-gupta** [comment] 2020-05-22 14:59
https://blog.opstree.com/2020/04/07/preserve-source-ip-in-aws-classic-load-balancer-and-istios-envoy-using-proxy-protocol/
