### ISSUE TITLE
Istio 1.1 GKE setup too small

### ISSUE THREAD

**Issue by qfel** [istio/istio#12051] opened 2019-02-26 01:39 UTC
**Describe the bug**
GKE setup instructions create a cluster that's too small to run istio-system namespace: istio-policy and istio-telemetry don't get scheduled due to insufficient CPU and memory

**Expected behavior**
All deployments get scheduled

**Steps to reproduce the bug**
- follow [platform-setup/gke/](https://preliminary.istio.io/docs/setup/kubernetes/platform-setup/gke/)
- follow [helm-install](https://preliminary.istio.io/docs/setup/kubernetes/helm-install/)
- run `kubectl get deployment -n istio-system`

**Version**
```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.6", GitCommit:"144b681e3870074abfdaaf176e48b1b13360d7e5", GitTreeState:"clean", BuildDate:"2019-02-09T00:08:19Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
https://preliminary.istio.io/docs/setup/kubernetes/helm-install/

**Environment**
GKE

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2903372/istio-dump.tar.gz)

**Comment by duderino** [comment] 2019-03-05 17:40
Most likely a duplicate of https://github.com/istio/istio/issues/11964

**Closed by duderino** 2019-03-05 17:40 UTC
