### ISSUE TITLE
TestManifestGenerateOrdered is flaky

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17390] opened 2019-09-25 21:28 UTC
This test checks that the output of manifest generate is deterministic. It was supposed to verify that the manifest items are not being reordered. 
The problem I am seeing is that the sidecar config injector ConfigMap has different values for prometheus.enabled on the two runs of runManifestGenerate (true/false).
This is really weird. The value is defined both in the default values in the chart and in the global values we are generating. I just don't see where prometheus.enabled could be set to false. 
Further, I cannot repro this issue by running mesh manifest generate -f cmd/mesh/testdata/all_on.yaml which is supposedly exactly what the test is running. The output is always correct.
Any clues would be highly appreciated! I'm attaching the outputs from got1 and got2.
```bash
diff got1.json got2.json 
516c516
<     "enabled": true,
---
>     "enabled": false,
```
got1 

{
  "certmanager": {
    "enabled": false,
    "hub": "quay.io/jetstack",
    "image": "cert-manager-controller",
    "namespace": "istio-system",
    "tag": "v0.6.2"
  },
  "citadel": {
    "dnsCerts": {
      "istio-pilot-service-account.istio-system": "istio-pilot.istio-system"
    },
    "enableNamespacesByDefault": true,
    "image": "citadel",
    "selfSigned": true,
    "trustDomain": "cluster.local"
  },
  "clusterResources": true,
  "galley": {
    "enabled": true,
    "namespace": "istio-system"
  },
  "gateways": {
    "istio-egressgateway": {
      "autoscaleEnabled": true,
      "connectTimeout": "10s",
      "drainDuration": "45s",
      "enabled": false,
      "env": {
        "ISTIO_META_ROUTER_MODE": "sni-dnat"
      },
      "namespace": "istio-system",
      "ports": [
        {
          "name": "http2",
          "port": 80
        },
        {
          "name": "https",
          "port": 443
        },
        {
          "name": "tls",
          "port": 15443,
          "targetPort": 15443
        }
      ],
      "secretVolumes": [
        {
          "mountPath": "/etc/istio/egressgateway-certs",
          "name": "egressgateway-certs",
          "secretName": "istio-egressgateway-certs"
        },
        {
          "mountPath": "/etc/istio/egressgateway-ca-certs",
          "name": "egressgateway-ca-certs",
          "secretName": "istio-egressgateway-ca-certs"
        }
      ],
      "zvpn": {
        "enabled": true,
        "suffix": "global"
      }
    },
    "istio-ingressgateway": {
      "applicationPorts": "",
      "autoscaleEnabled": true,
      "debug": "info",
      "domain": "",
      "enabled": true,
      "env": {
        "ISTIO_META_ROUTER_MODE": "sni-dnat"
      },
      "meshExpansionPorts": [
        {
          "name": "tcp-pilot-grpc-tls",
          "port": 15011,
          "targetPort": 15011
        },
        {
          "name": "tcp-citadel-grpc-tls",
          "port": 8060,
          "targetPort": 8060
        },
        {
          "name": "tcp-dns-tls",
          "port": 853,
          "targetPort": 853
        }
      ],
      "namespace": "istio-system",
      "ports": [
        {
          "name": "status-port",
          "port": 15020,
          "targetPort": 15020
        },
        {
          "name": "http2",
          "port": 80,
          "targetPort": 80
        },
        {
          "name": "https",
          "port": 443
        },
        {
          "name": "kiali",
          "port": 15029,
          "targetPort": 15029
        },
        {
          "name": "prometheus",
          "port": 15030,
          "targetPort": 15030
        },
        {
          "name": "grafana",
          "port": 15031,
          "targetPort": 15031
        },
        {
          "name": "tracing",
          "port": 15032,
          "targetPort": 15032
        },
        {
          "name": "tls",
          "port": 15443,
          "targetPort": 15443
        }
      ],
      "secretVolumes": [
        {
          "mountPath": "/etc/istio/ingressgateway-certs",
          "name": "ingressgateway-certs",
          "secretName": "istio-ingressgateway-certs"
        },
        {
          "mountPath": "/etc/istio/ingressgateway-ca-certs",
          "name": "ingressgateway-ca-certs",
          "secretName": "istio-ingressgateway-ca-certs"
        }
      ],
      "telemetry_addon_gateways": {
        "grafana_gateway": {
          "desPort": 3000,
          "enabled": false,
          "name": "grafana",
          "port": 15031,
          "tls": false
        },
        "kiali_gateway": {
          "desPort": 20001,
          "enabled": false,
          "name": "kiali",
          "port": 15029,
          "tls": false
        },
        "prometheus_gateway": {
          "desPort": 9090,
          "enabled": false,
          "name": "prometheus",
          "port": 15030,
          "tls": false
        },
        "tracing_gateway": {
          "desPort": 80,
          "enabled": false,
          "name": "tracing",
          "port": 15032,
          "tls": false
        }
      },
      "telemetry_domain_name": "",
      "zvpn": {
        "enabled": true,
        "suffix": "global"
      }
    }
  },
  "global": {
    "arch": {
      "amd64": 2,
      "ppc64le": 2,
      "s390x": 2
    },
    "configNamespace": "istio-system",
    "configValidation": true,
    "controlPlaneSecurityEnabled": true,
    "defaultNodeSelector": {},
    "defaultPodDisruptionBudget": {
      "enabled": true
    },
    "defaultResources": {
      "requests": {
        "cpu": "10m"
      }
    },
    "disablePolicyChecks": true,
    "enableHelmTest": false,
    "enableTracing": true,
    "enabled": true,
    "hub": "gcr.io/istio-release",
    "imagePullPolicy": "Always",
    "imagePullSecrets": [],
    "istioNamespace": "istio-system",
    "k8sIngress": {
      "enableHttps": false,
      "enabled": false,
      "gatewayName": "ingressgateway"
    },
    "localityLbSetting": {
      "enabled": true
    },
    "logAsJson": false,
    "logging": {
      "level": "default:info"
    },
    "meshExpansion": {
      "enabled": false,
      "useILB": false
    },
    "meshNetworks": {},
    "mtls": {
      "enabled": false
    },
    "multiCluster": {
      "enabled": false
    },
    "namespace": "istio-system",
    "oneNamespace": false,
    "outboundTrafficPolicy": {
      "mode": "ALLOW_ANY"
    },
    "policyCheckFailOpen": false,
    "policyNamespace": "istio-system",
    "priorityClassName": "",
    "prometheusNamespace": "istio-system",
    "proxy": {
      "accessLogEncoding": "TEXT",
      "accessLogFile": "",
      "accessLogFormat": "",
      "autoInject": "enabled",
      "clusterDomain": "cluster.local",
      "componentLogLevel": "misc:error",
      "concurrency": 2,
      "dnsRefreshRate": "300s",
      "enableCoreDump": false,
      "envoyAccessLogService": {
        "enabled": false
      },
      "envoyMetricsService": {
        "enabled": false
      },
      "envoyStatsd": {
        "enabled": false
      },
      "excludeIPRanges": "",
      "excludeInboundPorts": "",
      "excludeOutboundPorts": "",
      "image": "proxyv2",
      "includeIPRanges": "*",
      "includeInboundPorts": "*",
      "kubevirtInterfaces": "",
      "logLevel": "warning",
      "privileged": false,
      "protocolDetectionTimeout": "1s",
      "readinessFailureThreshold": 30,
      "readinessInitialDelaySeconds": 1,
      "readinessPeriodSeconds": 2,
      "resources": {
        "limits": {
          "cpu": "2000m",
          "memory": "1024Mi"
        },
        "requests": {
          "cpu": "100m",
          "memory": "128Mi"
        }
      },
      "statusPort": 15020,
      "tracer": "zipkin"
    },
    "proxy_init": {
      "image": "proxy_init",
      "resources": {
        "limits": {
          "cpu": "100m",
          "memory": "50Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "10Mi"
        }
      }
    },
    "sds": {
      "enabled": false,
      "udsPath": ""
    },
    "securityNamespace": "istio-system",
    "tag": "master-latest-daily",
    "telemetryNamespace": "istio-system",
    "tracer": {
      "datadog": {
        "address": "$(HOST_IP):8126"
      },
      "lightstep": {
        "accessToken": "",
        "address": "",
        "cacertPath": "",
        "secure": true
      },
      "zipkin": {
        "address": ""
      }
    },
    "trustDomain": "",
    "useMCP": true
  },
  "grafana": {
    "accessMode": "ReadWriteMany",
    "contextPath": "/grafana",
    "dashboardProviders": {
      "dashboardproviders.yaml": {
        "apiVersion": 1,
        "providers": [
          {
            "disableDeletion": false,
            "folder": "istio",
            "name": "istio",
            "options": {
              "path": "/var/lib/grafana/dashboards/istio"
            },
            "orgId": 1,
            "type": "file"
          }
        ]
      }
    },
    "datasources": {
      "datasources.yaml": {
        "apiVersion": 1
      }
    },
    "enabled": false,
    "env": {},
    "envSecrets": {},
    "image": {
      "repository": "grafana/grafana",
      "tag": "6.1.6"
    },
    "ingress": {
      "enabled": false,
      "hosts": [
        "grafana.local"
      ]
    },
    "namespace": "istio-system",
    "nodeSelector": {},
    "persist": false,
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "replicaCount": 1,
    "security": {
      "enabled": false,
      "passphraseKey": "passphrase",
      "secretName": "grafana",
      "usernameKey": "username"
    },
    "service": {
      "annotations": {},
      "externalPort": 3000,
      "name": "http",
      "type": "ClusterIP"
    },
    "storageClassName": "",
    "tolerations": []
  },
  "istio_cni": {
    "enabled": false
  },
  "kiali": {
    "contextPath": "/kiali",
    "createDemoSecret": true,
    "dashboard": {
      "passphraseKey": "passphrase",
      "secretName": "kiali",
      "usernameKey": "username",
      "viewOnlyMode": false
    },
    "enabled": false,
    "hub": "docker.io/kiali",
    "ingress": {
      "enabled": false,
      "hosts": [
        "kiali.local"
      ]
    },
    "namespace": "istio-system",
    "nodeSelector": {},
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "replicaCount": 1,
    "security": {
      "cert_file": "/kiali-cert/cert-chain.pem",
      "enabled": true,
      "private_key_file": "/kiali-cert/key.pem"
    },
    "tag": "v1.1.0"
  },
  "mixer": {
    "adapters": {
      "kubernetesenv": {
        "enabled": true
      },
      "prometheus": {
        "enabled": true,
        "metricsExpiryDuration": "10m"
      },
      "stackdriver": {
        "auth": {
          "apiKey": "",
          "appCredentials": false,
          "serviceAccountPath": ""
        },
        "enabled": false,
        "tracer": {
          "enabled": false,
          "sampleProbability": 1
        }
      },
      "stdio": {
        "enabled": false,
        "outputAsJson": false
      },
      "useAdapterCRDs": false
    },
    "policy": {
      "adapters": {
        "kubernetesenv": {
          "enabled": true
        }
      },
      "enabled": true,
      "image": "mixer",
      "namespace": "istio-system"
    },
    "telemetry": {
      "autoscaleEnabled": true,
      "enabled": true,
      "image": "mixer",
      "loadshedding": {
        "latencyThreshold": "100ms",
        "mode": "enforce"
      },
      "namespace": "istio-system",
      "nodeSelector": {},
      "podAntiAffinityLabelSelector": [],
      "podAntiAffinityTermLabelSelector": [],
      "replicaCount": 1,
      "reportBatchMaxEntries": 100,
      "reportBatchMaxTime": "1s",
      "sessionAffinityEnabled": false,
      "tolerations": [],
      "useMCP": true
    }
  },
  "nodeagent": {
    "enabled": false,
    "image": "node-agent-k8s",
    "namespace": "istio-system"
  },
  "pilot": {
    "appNamespaces": [],
    "autoscaleEnabled": true,
    "autoscaleMax": 5,
    "autoscaleMin": 1,
    "configMap": true,
    "configNamespace": "istio-config",
    "cpu": {
      "targetAverageUtilization": 80
    },
    "enabled": true,
    "env": {
      "GODEBUG": "gctrace=1"
    },
    "image": "pilot",
    "ingress": {
      "ingressClass": "istio",
      "ingressControllerMode": "OFF",
      "ingressService": "istio-ingressgateway"
    },
    "keepaliveMaxServerConnectionAge": "30m",
    "meshNetworks": {
      "networks": {}
    },
    "namespace": "istio-system",
    "nodeSelector": {},
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "policy": {
      "enabled": false
    },
    "replicaCount": 1,
    "telemetry": {
      "enabled": true
    },
    "tolerations": [],
    "traceSampling": 1,
    "useMCP": true
  },
  "prometheus": {
    "contextPath": "/prometheus",
    "enabled": true,
    "hub": "docker.io/prom",
    "ingress": {
      "enabled": false,
      "hosts": [
        "prometheus.local"
      ]
    },
    "namespace": "istio-system",
    "nodeSelector": {},
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "replicaCount": 1,
    "retention": "6h",
    "scrapeInterval": "15s",
    "security": {
      "enabled": true
    },
    "tag": "v2.8.0",
    "tolerations": []
  },
  "security": {
    "enabled": true,
    "namespace": "istio-system"
  },
  "sidecarInjectorWebhook": {
    "alwaysInjectSelector": [],
    "enableNamespacesByDefault": false,
    "enabled": true,
    "image": "sidecar_injector",
    "injectLabel": "istio-injection",
    "namespace": "istio-system",
    "neverInjectSelector": [],
    "nodeSelector": {},
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "replicaCount": 1,
    "rewriteAppHTTPProbe": false,
    "rollingMaxSurge": "100%",
    "rollingMaxUnavailable": "25%",
    "selfSigned": false,
    "tolerations": []
  },
  "tracing": {
    "enabled": false,
    "ingress": {
      "enabled": false
    },
    "jaeger": {
      "accessMode": "ReadWriteMany",
      "enabled": false,
      "hub": "docker.io/jaegertracing",
      "memory": {
        "max_traces": 50000
      },
      "namespace": "istio-system",
      "persist": false,
      "spanStorageType": "badger",
      "storageClassName": "",
      "tag": 1.12
    },
    "nodeSelector": {},
    "opencensus": {
      "exporters": {
        "stackdriver": {
          "enable_tracing": true
        }
      },
      "hub": "docker.io/omnition",
      "resources": {
        "limits": {
          "cpu": 1,
          "memory": "2Gi"
        },
        "requests": {
          "cpu": "200m",
          "memory": "400Mi"
        }
      },
      "tag": "0.1.9"
    },
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "provider": "jaeger",
    "service": {
      "annotations": {},
      "externalPort": 9411,
      "name": "http",
      "type": "ClusterIP"
    },
    "zipkin": {
      "hub": "docker.io/openzipkin",
      "javaOptsHeap": 700,
      "maxSpans": 500000,
      "node": {
        "cpus": 2
      },
      "probeStartupDelay": 200,
      "queryPort": 9411,
      "resources": {
        "limits": {
          "cpu": "300m",
          "memory": "900Mi"
        },
        "requests": {
          "cpu": "150m",
          "memory": "900Mi"
        }
      },
      "tag": "2.14.2"
    }
  },
  "version": ""
}

got2

{
  "certmanager": {
    "enabled": false,
    "hub": "quay.io/jetstack",
    "image": "cert-manager-controller",
    "namespace": "istio-system",
    "tag": "v0.6.2"
  },
  "citadel": {
    "dnsCerts": {
      "istio-pilot-service-account.istio-system": "istio-pilot.istio-system"
    },
    "enableNamespacesByDefault": true,
    "image": "citadel",
    "selfSigned": true,
    "trustDomain": "cluster.local"
  },
  "clusterResources": true,
  "galley": {
    "enabled": true,
    "namespace": "istio-system"
  },
  "gateways": {
    "istio-egressgateway": {
      "autoscaleEnabled": true,
      "connectTimeout": "10s",
      "drainDuration": "45s",
      "enabled": false,
      "env": {
        "ISTIO_META_ROUTER_MODE": "sni-dnat"
      },
      "namespace": "istio-system",
      "ports": [
        {
          "name": "http2",
          "port": 80
        },
        {
          "name": "https",
          "port": 443
        },
        {
          "name": "tls",
          "port": 15443,
          "targetPort": 15443
        }
      ],
      "secretVolumes": [
        {
          "mountPath": "/etc/istio/egressgateway-certs",
          "name": "egressgateway-certs",
          "secretName": "istio-egressgateway-certs"
        },
        {
          "mountPath": "/etc/istio/egressgateway-ca-certs",
          "name": "egressgateway-ca-certs",
          "secretName": "istio-egressgateway-ca-certs"
        }
      ],
      "zvpn": {
        "enabled": true,
        "suffix": "global"
      }
    },
    "istio-ingressgateway": {
      "applicationPorts": "",
      "autoscaleEnabled": true,
      "debug": "info",
      "domain": "",
      "enabled": true,
      "env": {
        "ISTIO_META_ROUTER_MODE": "sni-dnat"
      },
      "meshExpansionPorts": [
        {
          "name": "tcp-pilot-grpc-tls",
          "port": 15011,
          "targetPort": 15011
        },
        {
          "name": "tcp-citadel-grpc-tls",
          "port": 8060,
          "targetPort": 8060
        },
        {
          "name": "tcp-dns-tls",
          "port": 853,
          "targetPort": 853
        }
      ],
      "namespace": "istio-system",
      "ports": [
        {
          "name": "status-port",
          "port": 15020,
          "targetPort": 15020
        },
        {
          "name": "http2",
          "port": 80,
          "targetPort": 80
        },
        {
          "name": "https",
          "port": 443
        },
        {
          "name": "kiali",
          "port": 15029,
          "targetPort": 15029
        },
        {
          "name": "prometheus",
          "port": 15030,
          "targetPort": 15030
        },
        {
          "name": "grafana",
          "port": 15031,
          "targetPort": 15031
        },
        {
          "name": "tracing",
          "port": 15032,
          "targetPort": 15032
        },
        {
          "name": "tls",
          "port": 15443,
          "targetPort": 15443
        }
      ],
      "secretVolumes": [
        {
          "mountPath": "/etc/istio/ingressgateway-certs",
          "name": "ingressgateway-certs",
          "secretName": "istio-ingressgateway-certs"
        },
        {
          "mountPath": "/etc/istio/ingressgateway-ca-certs",
          "name": "ingressgateway-ca-certs",
          "secretName": "istio-ingressgateway-ca-certs"
        }
      ],
      "telemetry_addon_gateways": {
        "grafana_gateway": {
          "desPort": 3000,
          "enabled": false,
          "name": "grafana",
          "port": 15031,
          "tls": false
        },
        "kiali_gateway": {
          "desPort": 20001,
          "enabled": false,
          "name": "kiali",
          "port": 15029,
          "tls": false
        },
        "prometheus_gateway": {
          "desPort": 9090,
          "enabled": false,
          "name": "prometheus",
          "port": 15030,
          "tls": false
        },
        "tracing_gateway": {
          "desPort": 80,
          "enabled": false,
          "name": "tracing",
          "port": 15032,
          "tls": false
        }
      },
      "telemetry_domain_name": "",
      "zvpn": {
        "enabled": true,
        "suffix": "global"
      }
    }
  },
  "global": {
    "arch": {
      "amd64": 2,
      "ppc64le": 2,
      "s390x": 2
    },
    "configNamespace": "istio-system",
    "configValidation": true,
    "controlPlaneSecurityEnabled": true,
    "defaultNodeSelector": {},
    "defaultPodDisruptionBudget": {
      "enabled": true
    },
    "defaultResources": {
      "requests": {
        "cpu": "10m"
      }
    },
    "disablePolicyChecks": true,
    "enableHelmTest": false,
    "enableTracing": true,
    "enabled": true,
    "hub": "gcr.io/istio-release",
    "imagePullPolicy": "Always",
    "imagePullSecrets": [],
    "istioNamespace": "istio-system",
    "k8sIngress": {
      "enableHttps": false,
      "enabled": false,
      "gatewayName": "ingressgateway"
    },
    "localityLbSetting": {
      "enabled": true
    },
    "logAsJson": false,
    "logging": {
      "level": "default:info"
    },
    "meshExpansion": {
      "enabled": false,
      "useILB": false
    },
    "meshNetworks": {},
    "mtls": {
      "enabled": false
    },
    "multiCluster": {
      "enabled": false
    },
    "namespace": "istio-system",
    "oneNamespace": false,
    "outboundTrafficPolicy": {
      "mode": "ALLOW_ANY"
    },
    "policyCheckFailOpen": false,
    "policyNamespace": "istio-system",
    "priorityClassName": "",
    "prometheusNamespace": "istio-system",
    "proxy": {
      "accessLogEncoding": "TEXT",
      "accessLogFile": "",
      "accessLogFormat": "",
      "autoInject": "enabled",
      "clusterDomain": "cluster.local",
      "componentLogLevel": "misc:error",
      "concurrency": 2,
      "dnsRefreshRate": "300s",
      "enableCoreDump": false,
      "envoyAccessLogService": {
        "enabled": false
      },
      "envoyMetricsService": {
        "enabled": false
      },
      "envoyStatsd": {
        "enabled": false
      },
      "excludeIPRanges": "",
      "excludeInboundPorts": "",
      "excludeOutboundPorts": "",
      "image": "proxyv2",
      "includeIPRanges": "*",
      "includeInboundPorts": "*",
      "kubevirtInterfaces": "",
      "logLevel": "warning",
      "privileged": false,
      "protocolDetectionTimeout": "1s",
      "readinessFailureThreshold": 30,
      "readinessInitialDelaySeconds": 1,
      "readinessPeriodSeconds": 2,
      "resources": {
        "limits": {
          "cpu": "2000m",
          "memory": "1024Mi"
        },
        "requests": {
          "cpu": "100m",
          "memory": "128Mi"
        }
      },
      "statusPort": 15020,
      "tracer": "zipkin"
    },
    "proxy_init": {
      "image": "proxy_init",
      "resources": {
        "limits": {
          "cpu": "100m",
          "memory": "50Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "10Mi"
        }
      }
    },
    "sds": {
      "enabled": false,
      "udsPath": ""
    },
    "securityNamespace": "istio-system",
    "tag": "master-latest-daily",
    "telemetryNamespace": "istio-system",
    "tracer": {
      "datadog": {
        "address": "$(HOST_IP):8126"
      },
      "lightstep": {
        "accessToken": "",
        "address": "",
        "cacertPath": "",
        "secure": true
      },
      "zipkin": {
        "address": ""
      }
    },
    "trustDomain": "",
    "useMCP": true
  },
  "grafana": {
    "accessMode": "ReadWriteMany",
    "contextPath": "/grafana",
    "dashboardProviders": {
      "dashboardproviders.yaml": {
        "apiVersion": 1,
        "providers": [
          {
            "disableDeletion": false,
            "folder": "istio",
            "name": "istio",
            "options": {
              "path": "/var/lib/grafana/dashboards/istio"
            },
            "orgId": 1,
            "type": "file"
          }
        ]
      }
    },
    "datasources": {
      "datasources.yaml": {
        "apiVersion": 1
      }
    },
    "enabled": false,
    "env": {},
    "envSecrets": {},
    "image": {
      "repository": "grafana/grafana",
      "tag": "6.1.6"
    },
    "ingress": {
      "enabled": false,
      "hosts": [
        "grafana.local"
      ]
    },
    "namespace": "istio-system",
    "nodeSelector": {},
    "persist": false,
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "replicaCount": 1,
    "security": {
      "enabled": false,
      "passphraseKey": "passphrase",
      "secretName": "grafana",
      "usernameKey": "username"
    },
    "service": {
      "annotations": {},
      "externalPort": 3000,
      "name": "http",
      "type": "ClusterIP"
    },
    "storageClassName": "",
    "tolerations": []
  },
  "istio_cni": {
    "enabled": false
  },
  "kiali": {
    "contextPath": "/kiali",
    "createDemoSecret": true,
    "dashboard": {
      "passphraseKey": "passphrase",
      "secretName": "kiali",
      "usernameKey": "username",
      "viewOnlyMode": false
    },
    "enabled": false,
    "hub": "docker.io/kiali",
    "ingress": {
      "enabled": false,
      "hosts": [
        "kiali.local"
      ]
    },
    "namespace": "istio-system",
    "nodeSelector": {},
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "replicaCount": 1,
    "security": {
      "cert_file": "/kiali-cert/cert-chain.pem",
      "enabled": true,
      "private_key_file": "/kiali-cert/key.pem"
    },
    "tag": "v1.1.0"
  },
  "mixer": {
    "adapters": {
      "kubernetesenv": {
        "enabled": true
      },
      "prometheus": {
        "enabled": true,
        "metricsExpiryDuration": "10m"
      },
      "stackdriver": {
        "auth": {
          "apiKey": "",
          "appCredentials": false,
          "serviceAccountPath": ""
        },
        "enabled": false,
        "tracer": {
          "enabled": false,
          "sampleProbability": 1
        }
      },
      "stdio": {
        "enabled": false,
        "outputAsJson": false
      },
      "useAdapterCRDs": false
    },
    "policy": {
      "adapters": {
        "kubernetesenv": {
          "enabled": true
        }
      },
      "enabled": true,
      "image": "mixer",
      "namespace": "istio-system"
    },
    "telemetry": {
      "autoscaleEnabled": true,
      "enabled": true,
      "image": "mixer",
      "loadshedding": {
        "latencyThreshold": "100ms",
        "mode": "enforce"
      },
      "namespace": "istio-system",
      "nodeSelector": {},
      "podAntiAffinityLabelSelector": [],
      "podAntiAffinityTermLabelSelector": [],
      "replicaCount": 1,
      "reportBatchMaxEntries": 100,
      "reportBatchMaxTime": "1s",
      "sessionAffinityEnabled": false,
      "tolerations": [],
      "useMCP": true
    }
  },
  "nodeagent": {
    "enabled": false,
    "image": "node-agent-k8s",
    "namespace": "istio-system"
  },
  "pilot": {
    "appNamespaces": [],
    "autoscaleEnabled": true,
    "autoscaleMax": 5,
    "autoscaleMin": 1,
    "configMap": true,
    "configNamespace": "istio-config",
    "cpu": {
      "targetAverageUtilization": 80
    },
    "enabled": true,
    "env": {
      "GODEBUG": "gctrace=1"
    },
    "image": "pilot",
    "ingress": {
      "ingressClass": "istio",
      "ingressControllerMode": "OFF",
      "ingressService": "istio-ingressgateway"
    },
    "keepaliveMaxServerConnectionAge": "30m",
    "meshNetworks": {
      "networks": {}
    },
    "namespace": "istio-system",
    "nodeSelector": {},
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "policy": {
      "enabled": false
    },
    "replicaCount": 1,
    "telemetry": {
      "enabled": true
    },
    "tolerations": [],
    "traceSampling": 1,
    "useMCP": true
  },
  "prometheus": {
    "contextPath": "/prometheus",
    "enabled": false,
    "hub": "docker.io/prom",
    "ingress": {
      "enabled": false,
      "hosts": [
        "prometheus.local"
      ]
    },
    "namespace": "istio-system",
    "nodeSelector": {},
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "replicaCount": 1,
    "retention": "6h",
    "scrapeInterval": "15s",
    "security": {
      "enabled": true
    },
    "tag": "v2.8.0",
    "tolerations": []
  },
  "security": {
    "enabled": true,
    "namespace": "istio-system"
  },
  "sidecarInjectorWebhook": {
    "alwaysInjectSelector": [],
    "enableNamespacesByDefault": false,
    "enabled": true,
    "image": "sidecar_injector",
    "injectLabel": "istio-injection",
    "namespace": "istio-system",
    "neverInjectSelector": [],
    "nodeSelector": {},
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "replicaCount": 1,
    "rewriteAppHTTPProbe": false,
    "rollingMaxSurge": "100%",
    "rollingMaxUnavailable": "25%",
    "selfSigned": false,
    "tolerations": []
  },
  "tracing": {
    "enabled": false,
    "ingress": {
      "enabled": false
    },
    "jaeger": {
      "accessMode": "ReadWriteMany",
      "enabled": false,
      "hub": "docker.io/jaegertracing",
      "memory": {
        "max_traces": 50000
      },
      "namespace": "istio-system",
      "persist": false,
      "spanStorageType": "badger",
      "storageClassName": "",
      "tag": 1.12
    },
    "nodeSelector": {},
    "opencensus": {
      "exporters": {
        "stackdriver": {
          "enable_tracing": true
        }
      },
      "hub": "docker.io/omnition",
      "resources": {
        "limits": {
          "cpu": 1,
          "memory": "2Gi"
        },
        "requests": {
          "cpu": "200m",
          "memory": "400Mi"
        }
      },
      "tag": "0.1.9"
    },
    "podAntiAffinityLabelSelector": [],
    "podAntiAffinityTermLabelSelector": [],
    "provider": "jaeger",
    "service": {
      "annotations": {},
      "externalPort": 9411,
      "name": "http",
      "type": "ClusterIP"
    },
    "zipkin": {
      "hub": "docker.io/openzipkin",
      "javaOptsHeap": 700,
      "maxSpans": 500000,
      "node": {
        "cpus": 2
      },
      "probeStartupDelay": 200,
      "queryPort": 9411,
      "resources": {
        "limits": {
          "cpu": "300m",
          "memory": "900Mi"
        },
        "requests": {
          "cpu": "150m",
          "memory": "900Mi"
        }
      },
      "tag": "2.14.2"
    }
  },
  "version": ""
}

**Comment by irisdingbj** [comment] 2019-09-26 01:22
@ostromart The should be fixed in https://github.com/istio/operator/pull/300.

I also listed the root cause there. Please check and comment. Thanks.

**Closed** 2019-10-18 04:09 UTC
Labels: area/environments/operator, kind/test failure
