### ISSUE TITLE
Pilot fails to update ingress gateway about new gateways and virtual services

### ISSUE THREAD

**Issue by harpratap** [istio/istio#11039] opened 2019-01-17 01:25 UTC
**Describe the bug**
When I create new gateway and virtual service they aren't being reflected in istio's ingress gateway. When I curl hostname:31380/ it fails to connect and returns connection refused. However, on restarting all the ingress gateway pods the rules are updated and I can access my deployment on port 31380 successfully. 
Sometimes if I wait for few minutes the new changes are reflected (#8093)
And sometimes only some of the new ingress gateways recreated after deletion get the updated changes. Resulting in a lot of failed requests randomly (#11001 )

**Expected behavior**
Changes to be reflected immediately and my service to be accessible on hostname:31380/

**Steps to reproduce the bug**
Deploy a simple webserver and expose it using a service. Create a simple gateway and virtualservice to access it on the ingress nodeport. 
`apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ngin-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginvirtservice
spec:
  hosts:
  - "*"
  gateways:
  - ngin-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /hello9
    - uri:
        exact: /status
    route:
    - destination:
        host: ngin
        port:
          number: 80`

**Version**
1.1 Snapshot 4

**Installation**
Used helm 2.11 to install on bare metal nodes

**Environment**
Kubernetes version - 1.13.2
CoreOS 1855.4.0
Kernel 4.14 using IPVS
Bare Metal nodes

**Cluster state**
https://ufile.io/dras4
Dump too big to be uploadable on github

**Comment by esnible** [comment] 2019-02-01 16:21
This may be a duplicate of https://github.com/istio/istio/issues/10933 and fixed by https://github.com/istio/istio/pull/11177 .  Can you check again with a more recent 1.1 build?

**Comment by GregHanson** [comment] 2019-03-01 15:06
the issue with newly recreated ingress gateway instances not receiving their configs should be resolved by #11905, marking as resolved until issue can be recreated with 1.1 release candidate

**Closed by GregHanson** 2019-03-01 15:06 UTC
