### ISSUE TITLE
Default retry policy or not?

### ISSUE THREAD

**Issue by cabrinoob** [istio/istio#20547] opened 2020-01-27 11:05 UTC
Hello,
I'am using Istio v1.3.5 and I wonder if there is a default retry policy ?

If I read the doc, I can find this : 

_"By default, the Envoy proxy doesn’t attempt to reconnect to services after a first failure."_

So, if I understand, there is no default retry policy. But it's not exactly what I observe. Because, when I call a service on which I have not defined a virtualService (so, no retry policy), when this service return a 503, I can see 2 retries.

Using istioctl proxy-config I have this config on every routes of every pods : 

```
...
"routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|80||sa-test.dev.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
... 
```
As you can see, **numRetries: 2** on 503 statusCode. 
So, what is the truth ? 

Thank you.

**Comment by seeruk** [comment] 2020-01-29 15:16
Istio 1.4.3 is also exhibiting this behaviour. If there is some kind of global default retry policy, I'd really like to be able to override it globally, but I can't find any way to do that. I just don't want to have to make a VirtualService for everything to get around this.

**Comment by Luffy110** [comment] 2020-02-25 02:43
I have this issue too. and i tried update retry policy , but seems it didn't work. https://istio.io/docs/reference/config/networking/virtual-service/#HTTPRetry

**Comment by davinkevin** [comment] 2020-05-10 12:39
Since 1.1, you have this merged: https://github.com/istio/istio/pull/10566

This seems to indicate there is a default retry policy. But the doc is saying the opposite which is hard to understand.

**Comment by howardjohn** [comment] 2020-05-14 17:32
There is a default policy, so the docs are wrong.

Easy to reproduce:

`curl httpbin/status/503`

access logs will show

```
[2020-05-14T17:30:30.369Z] "GET /status/503 HTTP/1.1" 503 - "-" "-" 0 0 1 1 "-" "curl/7.58.0" "7518ac98-b71f-4de6-9a9c-3787dd6f055a" "httpbin" "127.0.0.1:80" inbound|80|http|httpbin.default.svc.cluster.local 127.0.0.1:44760 10.28.0.191:80 10.28.0.190:50182 outbound_.80_._.httpbin.default.svc.cluster.local default
[2020-05-14T17:30:30.375Z] "GET /status/503 HTTP/1.1" 503 - "-" "-" 0 0 1 0 "-" "curl/7.58.0" "7518ac98-b71f-4de6-9a9c-3787dd6f055a" "httpbin" "127.0.0.1:80" inbound|80|http|httpbin.default.svc.cluster.local 127.0.0.1:44760 10.28.0.191:80 10.28.0.190:50182 outbound_.80_._.httpbin.default.svc.cluster.local default
[2020-05-14T17:30:30.390Z] "GET /status/503 HTTP/1.1" 503 - "-" "-" 0 0 1 0 "-" "curl/7.58.0" "7518ac98-b71f-4de6-9a9c-3787dd6f055a" "httpbin" "127.0.0.1:80" inbound|80|http|httpbin.default.svc.cluster.local 127.0.0.1:44760 10.28.0.191:80 10.28.0.190:50182 outbound_.80_._.httpbin.default.svc.cluster.local default
```
matching the 2 retry policy

**Closed** 2020-05-15 15:02 UTC
Labels: area/networking, community/help wanted, kind/docs
