### ISSUE TITLE
istioctl kube-inject -f httpbin.yaml gives a blank output on s390x system

### ISSUE THREAD

**Issue by kadamvandita** [istio/istio#2338] opened 2017-12-27 11:09 UTC
istioctl kube-inject -f httpbin.yaml gives blank file on s390x system

**Comment by Bo0mer** [comment] 2017-12-28 12:18
Hello,

I'm experiencing similar problems on darwin.

# Environment
I'm using minikube.

```text
$ istioctl version
Version: 0.3.0
GitRevision: 24ec6a3ac3a1d592d1873d2d8198278a849b8301
GitBranch: ad6c09778ae6218b51c91ed53aafc7f9e13796b3
User: root@24c944bda24b
GolangVersion: go1.8
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ uname -a
Darwin Ivans-Mac-mini-2.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

# What I did

I executed the following command:
```bash
$ istioctl kube-inject -f samples/sleep/sleep.yaml
```

# What I expected to see

The content of `sleep.yaml` file decorated with the Istio sidecar.

# What I saw instead

Nothing. No output was present on stdout/stderr. The `istioctl` exits with exit code `0`.

Thanks for your awesome work!

**Comment by ayj** [comment] 2018-01-02 21:40
This is likely due to `istio` ConfigMap not being found in `istio-system` namespace, but it's hard to say for certain since `istioctl` is swallowing the error. 

The hidden error issue should be resolved by https://github.com/istio/istio/pull/2334.

The `kube-inject` runtime dependency on k8s and ConfigMap specifically should be removed as part of https://github.com/istio/istio/pull/1895.

**Comment by christian-posta** [comment] 2018-01-10 19:25
I can reproduce this with istioctl 0.3.0 when no `istio` configmap. @Bo0mer do you have istio installed in your k8s cluster?

**Comment by Bo0mer** [comment] 2018-01-10 19:43
Hello,

I did not have istio installed and this was causing the issue. After installing istio the issue was resolved. Nevertheless printing an error message when istio is not installed seems like a good idea to me - in my case it would have saved this issue and some time of mine.

Thanks,
Ivan.

**Comment by christian-posta** [comment] 2018-01-10 20:58
Great @Bo0mer 
Sounds like #2334 takes care of making errors more visible. 
Guess we can close this one?

**Comment by ayj** [comment] 2018-01-11 17:19
Thanks for reporting @Bo0mer. I'm closing this for now assuming #2334 fixed this problem, We can re-open if that is not the case.

**Closed by ayj** 2018-01-11 17:19 UTC
