### ISSUE TITLE
Analysis framework does not invoke analysis if some inputs types have no exemplars

### ISSUE THREAD

**Issue by esnible** [istio/istio#17686] opened 2019-10-08 16:09 UTC
To reproduce:

Add `metadata.K8SCoreV1Namespaces` to the list of Inputs in the `Metadata()` method of any `analyzer.Analyzer`.

`make istioctl`, use the new build on a file known to have analysis errors, without `--use-kube`.  These errors will no longer be reported.  The `Analyze()` method is not called if the input includes `metadata.K8SCoreV1Namespaces` (and sometimes if the input includes `K8SCoreV1Services`, or `K8SCoreV1Pods`)  The analyzer `Analyze()` is called if `--use-kube` is specified.

**Comment by sushicw** [comment] 2019-10-08 19:02
I believe what you're running into is the "service discovery" switch, which I'm realizing is sort of poorly named.

There's a flag that controls whether we look at the k8s resources used for service discovery or not, that mirrors the behavior of enableServiceDiscovery in galley. If service discovery is disabled, we're not looking at k8s resources, and any analyzers that depend on them get skipped.

In addition, the default value of this flag is true if you're running with --use-kube and false otherwise.

So right now, if you want to run analyzers that pay attention to namespaces, pods, & services, you need to either run with `--use-kube` or with `-d true`. 

The reasoning behind this is that for the majority of file-based cases, there won't be namespace or service resources included and we don't want false positives. I was also trying to keep the behavior of `istioctl x analyze` and galley validation status update to be consistent where possible. 

Would it be helpful to rename the --discovery flag to something like --include-kube-resources? It would still default to true if you're hitting a live cluster as part of analysis, but would be less confusingly named.

**Comment by esnible** [comment] 2019-10-09 00:45
To test my misplaced/misspelled annotation analyzer I created a Service default.httpbin with invalid annotation, then tested it without `--discovery`.

`--discovery` is perhaps great for disabling messages about missing things, but perhaps we should pass in to Analyze() that we are being run in `--discovery=false` mode and let the Analyze() method itself choose if it is appropriate to be skipped?

**Comment by sushicw** [comment] 2019-11-20 22:43
@esnible Can we close the loop on this? This seems like a case of "working as intended, but the behavior isn't obvious / the design could be improved." If there are actions to take from here, let's see if we can figure out what they are, otherwise we can close this issue out. 

The current behavior is close to what you describe in the last comment, except that the analysis framework is using the availability of resources to decide what to skip instead of needing Analyzers to handle that logic themselves. 

The `--verbose` flag helps a bit, since we can at least see exactly which analyzers get skipped over. We do log the reason for the skip but that's going to be harder for most users to get to... should we bubble that detail up to the `--verbose` output as well?

**Comment by esnible** [comment] 2019-12-05 20:08
I propose we close this.  I haven't been bitten in a long time by this problem.  Let's see if any users have trouble with it.

**Closed** 2019-12-05 21:08 UTC
Labels: area/config, area/user experience
