### ISSUE TITLE
1.1 Mixer telemetry memory and cpu regression

### ISSUE THREAD

**Issue by ayj** [istio/istio#9964] opened 2018-11-14 19:30 UTC
Mixer telemetry pods are consuming significantly more resources (CPU/memory/goroutines) compared to 1.0. 

https://snapshot.raintank.io/dashboard/snapshot/WmdWry4GLEUffhZzbrPEERArkcU9Jyks

![screenshot from 2018-11-14 11-22-17](https://user-images.githubusercontent.com/116378/48507000-98246980-e7ff-11e8-832a-a81195ac52b2.png)
![screenshot from 2018-11-14 11-22-23](https://user-images.githubusercontent.com/116378/48507002-98246980-e7ff-11e8-9c10-d99b875b59a7.png)
![screenshot from 2018-11-14 11-22-29](https://user-images.githubusercontent.com/116378/48507004-98246980-e7ff-11e8-87e3-7dd677cb1d5e.png)

- build: release-1.1-20181112-21-12
- k8s server: v1.10.7-gke.9
- services/pods: ~800
- pilots: 4
- telemetry pods: 5

**Comment by bianpengyuan** [comment] 2018-11-14 19:32
This is a known bug and has been fixed by https://github.com/istio/istio/pull/9946.

**Comment by mandarjog** [comment] 2018-11-14 19:49
Lets see what we find after the upgrade. I think this issue is different. #9946 fixes the tight loop. Tight loop is seen as purely more cpu. It is *not* associated with increasing memory and go routine use.

**Comment by mandarjog** [comment] 2018-11-15 01:36
The issue here is open census libraries we are using. Under the same load direct use of prometheus client libraries did not have this issue.  Mixer uses open census library to export self monitoring metrics.

The metrics code uses a buffered channel of 1024 capacity to record metrics. Mixer records ~15 metrics per telemetry request. Mixer is receiving 50% more requests than in 1.0.x, and requests are waiting  to do a blocking write into the internal metrics channel.

The fix will involve sending a PR to the dependency that does a non-blocking write.
@songy23  One thread is doing work as expected and 

About 2000 goroutines are blocked on `chan send`
```
goroutine 243829 [chan send]: [50 times] 
istio.io/istio/vendor/go.opencensus.io/stats/view.record(0xcc0fc03b98, 0x1a7df00, 0xcd665563c0)
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/stats/view/worker.go:115 +0xd8
istio.io/istio/vendor/go.opencensus.io/stats.Record(0x2086a80, 0xce9c046990, 0xcdc812f180, 0x5, 0x5)
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/stats/record.go:50 +0x15a
istio.io/istio/vendor/go.opencensus.io/plugin/ocgrpc.handleRPCEnd(0x2086a80, 0xce9c046990, 0xcc120504b0)
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/plugin/ocgrpc/stats_common.go:156 +0x8fb
```
One goroutine is doing work ...
```
goroutine 83 [runnable]: 1 times: [[83]
istio.io/istio/vendor/go.opencensus.io/tag.(*Map).Value(...)
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/tag/map.go:42
istio.io/istio/vendor/go.opencensus.io/stats/view.encodeWithKeys(0xcc0e4824e8, 0xc420019580, 0x4, 0x4, 0xc4212dce58, 0xc420334aa0, 0xc42028d9e0)
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/stats/view/collector.go:65 +0x2e3
istio.io/istio/vendor/go.opencensus.io/stats/view.(*viewInternal).addSample(0xc4202faa20, 0xcc0e4824e8, 0x3f0a4d4cfea525d9)
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/stats/view/view.go:134 +0x5e
istio.io/istio/vendor/go.opencensus.io/stats/view.(*recordReq).handleCommand(0xcd64779a60, 0xc42012a140)
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/stats/view/worker_commands.go:154 +0x70
istio.io/istio/vendor/go.opencensus.io/stats/view.(*worker).start(0xc42012a140)
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/stats/view/worker.go:148 +0x1ef
created by istio.io/istio/vendor/go.opencensus.io/stats/view.init.0
        /workspace/go/src/istio.io/istio/vendor/go.opencensus.io/stats/view/worker.go:29 +0x58
```

**Comment by douglas-reid** [comment] 2018-11-15 19:38
Without knowing the full context here, I feel like it would be nice to avoid refactoring the client code to deal with the internals of a specific library. Obviously, there is a need for some pragmatism for a solution here, but batching only delays the issue and could lead to brittle code (depending on how it is refactored, etc.).

**Comment by mandarjog** [comment] 2018-11-15 20:19
@songy23 We have a two fold plan, I will submit a PR to opencensus for non-blocking write.
Doug is working on a PR to do some batching, both are independently needed.

**Comment by odeke-em** [comment] 2018-11-16 17:21
@mandarjog would you mind sharing with me what your fix for "non-blocking write" would look like? If private, my email is in my Github profile. Thanks!

**Comment by mandarjog** [comment] 2018-11-16 18:50
@douglas-reid please hold off on the batching work. The root cause appears to be something different.

**Comment by odeke-em** [comment] 2018-11-17 00:01
@mandarjog @douglas-reid  interestingly I've spun a rough profiler
```go
package main

import (
	"context"
	"fmt"
	"log"
	"sync"
	"time"

	"go.opencensus.io/stats"
	"go.opencensus.io/stats/view"
	"go.opencensus.io/tag"
)

func main() {
	keyName, _ := tag.NewKey("key")
	keyMethod, _ := tag.NewKey("method")
	m := stats.Int64("m", "the measurement", "By")

	v := &view.View{
		Name:        "V",
		Description: "The view",
		Measure:     m,
		TagKeys:     []tag.Key{keyName, keyMethod},
		Aggregation: view.Distribution(0, 1<<10, 1<<20, 1<<40, 1<<60, 1<<62),
	}
	if err := view.Register(v); err != nil {
		log.Fatalf("Failed to register view: %v", err)
	}

	ctx, _ := tag.New(context.Background(), tag.Upsert(keyMethod, "Foo"), tag.Upsert(keyName, "Bar"))

	for {
		nl := []int{1, 10, 100, 200, 400, 800, 1024, 1200, 1600, 2000, 4000, 6000, 10000}

		for _, n := range nl {
			navg := 10

			var maxNs time.Duration
			var minNs time.Duration = 1<<63 - 1
			var qpsTotal float64
			var durTotal float64
			for i := 0; i < navg; i++ {
				ts := doMeasure(ctx, m, n)
				qps := float64(n) / ts.Seconds()
				qpsTotal += qps
				durTotal += ts.Seconds()
				if ts > maxNs {
					maxNs = ts
				}
				if ts < minNs {
					minNs = ts
				}
			}
                        fmt.Printf("%-8d: MinNs: %-11s MaxNs: %-11s RollingAvgQPS: %-20.4f AvgQPS: %-20.4f\n", n, minNs, maxNs, qpsTotal/float64(navg), float64(n*navg)/durTotal)
			<-time.After(500 * time.Millisecond)
		}
		fmt.Println("\n")
		<-time.After(1 * time.Second)
	}
}

func doMeasure(ctx context.Context, m *stats.Int64Measure, n int) (td time.Duration) {
	startTime := time.Now()
	defer func() {
		td = time.Since(startTime)
	}()

	var wg sync.WaitGroup
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func() {
			stats.Record(ctx, m.M(1e8))
			wg.Done()
		}()
	}
	wg.Wait()

	return
}
```

which when run gives values such as
```shell
1       : MinNs: 2.953µs     MaxNs: 32.539µs    RollingAvgQPS: 251411.6904          AvgQPS: 147084.7797         
10      : MinNs: 17.382µs    MaxNs: 67.612µs    RollingAvgQPS: 389401.5245          AvgQPS: 335758.6298         
100     : MinNs: 90.269µs    MaxNs: 392.83µs    RollingAvgQPS: 759837.7330          AvgQPS: 613919.1432         
200     : MinNs: 148.156µs   MaxNs: 339.841µs   RollingAvgQPS: 1027258.1452         AvgQPS: 977938.2031         
400     : MinNs: 277.196µs   MaxNs: 748.124µs   RollingAvgQPS: 843147.2690          AvgQPS: 778161.3681         
800     : MinNs: 628.682µs   MaxNs: 2.174351ms  RollingAvgQPS: 747452.4563          AvgQPS: 677752.7245         
1024    : MinNs: 1.085032ms  MaxNs: 2.087372ms  RollingAvgQPS: 725058.8659          AvgQPS: 705889.9763         
1200    : MinNs: 1.109202ms  MaxNs: 3.108164ms  RollingAvgQPS: 733633.3900          AvgQPS: 687243.0677         
1600    : MinNs: 1.914818ms  MaxNs: 3.162023ms  RollingAvgQPS: 711347.1439          AvgQPS: 693647.8032         
2000    : MinNs: 2.401493ms  MaxNs: 4.473802ms  RollingAvgQPS: 659295.7092          AvgQPS: 628404.8546         
4000    : MinNs: 5.566742ms  MaxNs: 9.418366ms  RollingAvgQPS: 586229.1843          AvgQPS: 561196.2875         
6000    : MinNs: 7.320768ms  MaxNs: 13.843318ms RollingAvgQPS: 601240.3980          AvgQPS: 576061.5105         
10000   : MinNs: 12.971585ms MaxNs: 21.45374ms  RollingAvgQPS: 561263.3827          AvgQPS: 546493.0193         


1       : MinNs: 2.956µs     MaxNs: 42.714µs    RollingAvgQPS: 201979.7597          AvgQPS: 100859.3214         
10      : MinNs: 25.635µs    MaxNs: 106.444µs   RollingAvgQPS: 241008.9410          AvgQPS: 209350.4275         
100     : MinNs: 97.843µs    MaxNs: 239.733µs   RollingAvgQPS: 717820.8546          AvgQPS: 660271.7150         
200     : MinNs: 177.069µs   MaxNs: 384.03µs    RollingAvgQPS: 936909.0577          AvgQPS: 880578.1876         
400     : MinNs: 266.978µs   MaxNs: 716.751µs   RollingAvgQPS: 961848.3253          AvgQPS: 891092.6600         
800     : MinNs: 729.533µs   MaxNs: 2.609441ms  RollingAvgQPS: 770895.3491          AvgQPS: 686219.0488         
1024    : MinNs: 1.032006ms  MaxNs: 2.730231ms  RollingAvgQPS: 789499.9863          AvgQPS: 732834.2522         
1200    : MinNs: 930.167µs   MaxNs: 3.744389ms  RollingAvgQPS: 705157.4731          AvgQPS: 625176.3844         
1600    : MinNs: 1.363028ms  MaxNs: 3.880073ms  RollingAvgQPS: 826065.6980          AvgQPS: 762345.9424         
2000    : MinNs: 2.494629ms  MaxNs: 4.493105ms  RollingAvgQPS: 649251.4286          AvgQPS: 620173.0959         
4000    : MinNs: 4.684919ms  MaxNs: 8.202363ms  RollingAvgQPS: 686579.5374          AvgQPS: 664785.5010         
6000    : MinNs: 7.341815ms  MaxNs: 14.64125ms  RollingAvgQPS: 560736.8621          AvgQPS: 534797.1039         
10000   : MinNs: 12.244631ms MaxNs: 22.523656ms RollingAvgQPS: 602695.2226          AvgQPS: 573405.2139         


1       : MinNs: 4.545µs     MaxNs: 36.608µs    RollingAvgQPS: 118647.2413          AvgQPS: 83498.9396          
10      : MinNs: 28.316µs    MaxNs: 122.259µs   RollingAvgQPS: 180170.7493          AvgQPS: 154229.1166         
100     : MinNs: 73.685µs    MaxNs: 139.663µs   RollingAvgQPS: 1002951.2862         AvgQPS: 967791.8860         
200     : MinNs: 115.646µs   MaxNs: 2.296029ms  RollingAvgQPS: 954980.9850          AvgQPS: 437171.8479         
400     : MinNs: 279.557µs   MaxNs: 715.949µs   RollingAvgQPS: 814271.2819          AvgQPS: 759289.6238         
800     : MinNs: 847.16µs    MaxNs: 2.31624ms   RollingAvgQPS: 788313.3854          AvgQPS: 717799.6641         
1024    : MinNs: 1.061804ms  MaxNs: 3.041955ms  RollingAvgQPS: 800832.8509          AvgQPS: 729219.6609         
1200    : MinNs: 1.171951ms  MaxNs: 2.468705ms  RollingAvgQPS: 799675.2600          AvgQPS: 750276.6176         
1600    : MinNs: 1.61515ms   MaxNs: 3.490994ms  RollingAvgQPS: 815173.7715          AvgQPS: 755427.7603         
2000    : MinNs: 2.020368ms  MaxNs: 5.076004ms  RollingAvgQPS: 805290.4967          AvgQPS: 732918.9214         
4000    : MinNs: 4.530765ms  MaxNs: 7.942242ms  RollingAvgQPS: 707805.4108          AvgQPS: 680506.6638         
6000    : MinNs: 7.179455ms  MaxNs: 12.246159ms RollingAvgQPS: 624953.0918          AvgQPS: 604413.5243         
10000   : MinNs: 12.312888ms MaxNs: 22.869093ms RollingAvgQPS: 614382.2871          AvgQPS: 580744.3682  
```
where the first column is the number of concurrent goroutines for a `stats.Record(context, stats.Measure)` call and so far with ~10K goroutines concurrently invoking that function, the worst time am getting is about ~23ms

**Comment by mandarjog** [comment] 2018-11-17 00:46
Thanks for that info. It appears that so many go routines blocked on open-census go may be a symptom of the problem and not the cause. I will update this issue as I know more.

**Comment by mandarjog** [comment] 2018-11-20 19:44
Some more info here
v104 sawtooth https://snapshot.raintank.io/dashboard/snapshot/4IQrG35rzYhxwCy30xVgExMmsCAcPGMi
This shows the problem occurring in v104-pre at high load. As seen from the chart, the issue associated with large spikes of incoming requests to the istio telemetry pod.

**Comment by douglas-reid** [comment] 2018-11-26 19:43
Any updates here (or newer action items)?

**Comment by mandarjog** [comment] 2018-11-29 01:48
It appears that once mixer enters this situation we have unbounded number of grpc goroutines in the front end contending for the same pool of mutable bags that the bounded back end go routines do

front end:
```
goroutine 180854 [semacquire]: 68 times: 
sync.runtime_SemacquireMutex(0xc51b54682c, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc51b546828)
        /usr/local/go/src/sync/mutex.go:134 +0xff
sync.(*Pool).getSlow(0x2d28db0, 0xc51b546200, 0x1)
        /usr/local/go/src/sync/pool.go:165 +0xbe
sync.(*Pool).Get(0x2d28db0, 0x1a448c0, 0xc327c33320)
        /usr/local/go/src/sync/pool.go:141 +0x12b
istio.io/istio/mixer/pkg/attribute.GetMutableBag(0x1d53600, 0xc327c33320, 0xc001586d80)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/pkg/attribute/mutableBag.go:59 +0x31
istio.io/istio/mixer/pkg/api.(*grpcServer).Report(0xc000ead770, 0x1d51d80, 0xc499e8d7d0, 0xc1e38ef140, 0xc000ead770, 0x1b0d0d0, 0x6)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/pkg/api/grpcServer.go:245 +0x1be
istio.io/istio/vendor/istio.io/api/mixer/v1._Mixer_Report_Handler.func1(0x1d51d80, 0xc499e8d7d0, 0x19b2ec0, 0xc1e38ef140, 0xc258990f50, 0x1882c80, 0x2d74df0, 0xc49b14faa0)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/vendor/istio.io/api/mixer/v1/service.pb.go:113 +0x86
istio.io/istio/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.UnaryServerInterceptor(0x1d51d80, 0xc499e8d7d0, 0x19b2ec0, 0xc1e38ef140, 0xc3dd73ab20, 0xc3dd73ab40, 0x1882c80, 0x2d74df0, 0x1a6ef60, 0xc43cc473b0)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:29 +0xa4
istio.io/istio/vendor/istio.io/api/mixer/v1._Mixer_Report_Handler(0x18bccc0, 0xc000ead770, 0x1d51d80, 0xc499e8d7d0, 0xc1c76516c0, 0x1ba0520, 0x0, 0x0, 0x0, 0x0)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/vendor/istio.io/api/mixer/v1/service.pb.go:115 +0x158
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc002045500, 0x1d63f80, 0xc002e62000, 0xc43cc473b0, 0xc000d1cf90, 0x2d375f8, 0x0, 0x0, 0x0)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1011 +0x4cd
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc002045500, 0x1d63f80, 0xc002e62000, 0xc43cc473b0, 0x0)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1249 +0x1308
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0021f6790, 0xc002045500, 0x1d63f80, 0xc002e62000, 0xc43cc473b0)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:678 +0xa1
```
Back end thru goroutine pool
```
goroutine 114 [semacquire]: 948 times:
sync.runtime_SemacquireMutex(0xc51b54682c, 0xc000d95b00)
        /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc51b546828)
        /usr/local/go/src/sync/mutex.go:134 +0xff
sync.(*Pool).getSlow(0x2d28db0, 0xc51b546600, 0x1207db4)
        /usr/local/go/src/sync/pool.go:165 +0xbe
sync.(*Pool).Get(0x2d28db0, 0xf, 0xc35cd4c5a0)
        /usr/local/go/src/sync/pool.go:141 +0x12b
istio.io/istio/mixer/pkg/attribute.GetMutableBag(0x0, 0x0, 0x8)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/pkg/attribute/mutableBag.go:59 +0x31
istio.io/istio/mixer/pkg/template.NewOutputMapperFn.func1(0x1d536c0, 0xc450476520, 0xc138728690, 0xc401605030, 0xc488c8eb60)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/pkg/template/template.go:243 +0x4a
istio.io/istio/mixer/template.glob..func4(0x1d51d80, 0xc138728690, 0x1d272c0, 0xc0016c3050, 0x175c540, 0xc401605030, 0x1d535c0, 0xc543e28880, 0xc000c514e0, 0x2d56440, ...)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/template/template.gen.go:455 +0x24d
istio.io/istio/mixer/pkg/runtime/dispatcher.(*dispatchState).invokeHandler(0xc53b0b5680, 0x0, 0x0)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/pkg/runtime/dispatcher/dispatchstate.go:111 +0x771
istio.io/istio/mixer/pkg/runtime/dispatcher.(*dispatchState).invokeHandler-fm(0x0, 0x0)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/pkg/runtime/dispatcher/session.go:231 +0x3e
istio.io/istio/mixer/pkg/pool.(*GoroutinePool).AddWorkers.func1(0xc0002cd720)
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/pkg/pool/goroutine.go:82 +0x6f
created by istio.io/istio/mixer/pkg/pool.(*GoroutinePool).AddWorkers
        /Volumes/Untitled/mjog/GOHOME/src/istio.io/istio/mixer/pkg/pool/goroutine.go:80 +0x6f
```

This causes a snowball effect. The back end cannot make progress and more and more goroutines from front end get thru this lock, but get stuck later because it needs the back end to make progress.

**Comment by jasminejaksic** [comment] 2019-01-15 00:41
PRs for overload protection is merged, need to set-up parameter tuning for overload protection. Mandar is working on it and is likely to submit before EoW.

**Comment by mandarjog** [comment] 2019-01-15 17:56
Next steps are 
1. Configure overload protection
2. Update istio-telemetry hpa to a much higher level "max" and put cpu and memory limits on the POD. We will use 5 CPU and 6 GB limits with 20 instances max. Max should be scaled by the actual size of deployment.  @therealmitchconnors

**Comment by duderino** [comment] 2019-02-11 18:12
@mandarjog update please

**Comment by duderino** [comment] 2019-02-26 19:22
dropping to P1 to cover residual

**Comment by jnativio** [comment] 2019-04-04 19:56
@ayj Should this issue be closed or you are still seeing the problem?

**Comment by ayj** [comment] 2019-04-04 20:32
cc @therealmitchconnors who may be able to answer if the problem still exists (or not).

**Comment by therealmitchconnors** [comment] 2019-04-04 20:59
1.1 has effectively mitigated this issue by: 

1. Enabling Load Shedding for telemetry by default
2. Applying a relatively tight CPU and memory limit for mixer telemetry
3. Expanding the upper level of scaling in the telemetry HPA to compensate for the reduced resources.

These mitigations do not fix the underlying issue, and under certain circumstances have a side-effect of compromising telemetry fidelity.  I consider this to be a temporary mitigation, though an ETA for a fix to the underlying issue is not available at this time.  Certainly Mixer V2 will resolve this, but it isn't entirely clear if we can live with this mitigation until then...

**Comment by douglas-reid** [comment] 2019-04-18 19:02
@mandarjog what is the next step here?

**Comment by douglas-reid** [comment] 2019-05-31 20:04
Given that we have a mitigation in 1.1 and a longer-term fix in development, I'm going to close this issue for now. Work is continually being done to improve the efficiency of the telemetry pipeline within Istio, and that work is tracked in other issues, etc.

**Closed by douglas-reid** 2019-05-31 20:04 UTC
Labels: area/perf and scalability, area/policies and telemetry
