### ISSUE TITLE
RBAC e2e test is consistently failing

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#606] opened 2017-08-27 20:20 UTC
The current rbac-no-auth e2e test is currently failing % of the time.

After looking at the logs, the failure seems to be consistenly the mixer test and that the metrics are not being propagated
mixer_test.go:212: Could not find value: value not found for map[string]string{}
mixer_test.go:216: Bad metric value: got 0.000000, want at least 1.000000

**Comment by sebastienvas** [comment] 2017-08-29 18:06
@Brian-Xincheng-Zhang, please find someone to work on this.

**Comment by wattli** [comment] 2017-08-30 21:52
I don't think it is not auth related. assign back to @Brian-Xincheng-Zhang , please try mixer guys.

**Comment by Brian-Xincheng-Zhang** [comment] 2017-08-30 22:07
I had a chat with Mandar.
1. mixer config server will be gone next week. so let's wait until next week to see whether the problem persists. 
2. the issue happens when a config is being pushed to mixer, and it happens to two PRs. the flakiness could be caused by both code and test-infra. therefore, if the problem persists next week, Mandar and engprod oncall will work together to debug the issue. 
I will reassign the bug to Mandar and EngProd oncall.

**Comment by yutongz** [comment] 2017-08-31 04:24
We have a EngProd oncall now? @sebastienvas

**Comment by Brian-Xincheng-Zhang** [comment] 2017-08-31 04:29
Yutong, you are the engprod oncall  next week:
https://docs.google.com/spreadsheets/d/1FaHwPpad3F3hva2suJweNeTnocjKtLnbgLkyMRPzgUY/edit#gid=0



-- Brian

**Comment by sebastienvas** [comment] 2017-08-31 19:48
This impacts release 0.2.1

**Comment by ldemailly** [comment] 2017-09-04 01:52
it's failing all the time, we need to make it pass again and then make it mandatory so it stays passing

ps: right now though nothing seems to pass, even non rbac see #653 for one of the causes

**Comment by yutongz** [comment] 2017-09-12 18:51
Fixed

**Closed by yutongz** 2017-09-12 18:51 UTC
Labels: flaky-test, oncall

**Comment by ldemailly** [comment] 2017-09-13 08:17
fixed in #711
