### ISSUE TITLE
proto: tag has too few fields: "-"  when doing `istio-1.6.7/bin/istioctl profile dump`

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#26184] opened 2020-08-05 22:40 UTC
**Bug description**
Following the install instructions which prompt to check the default profile:
```
$ istio-1.6.7/bin/istioctl profile dump > /dev/null
2020-08-05T22:34:27.599807Z	info	proto: tag has too few fields: "-"
```
ideally the output should be clean (and only the config) instead of that logging (maybe downgrade that log to verbose/debug if it's expected; or fix the "too few fields"?)

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
no log output

**Steps to reproduce the bug**
see above

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.7

**How was Istio installed?**
before installation

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS istioctl 1.6.7

**Comment by ericvn** [comment] 2020-08-06 00:25
Similar to https://github.com/istio/istio/issues/26010

**Comment by esnible** [comment] 2020-08-07 13:58
Closing as a duplicate of https://github.com/istio/istio/issues/26010

**Closed by esnible** 2020-08-07 13:58 UTC
Labels: area/environments
