### ISSUE TITLE
Failed calling admission webhook "sidecar-injector.istio.io":certificate signed by unknown authority

### ISSUE THREAD

**Issue by wattli** [istio/istio#5828] opened 2018-05-24 18:29 UTC
istio-release-0.8-20180520-18-17

website: https://preliminary.istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection

message: 'Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io":
      Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s:

      x509: certificate signed by unknown authority (possibly because of "crypto/rsa:
      verification error" while trying to verify candidate authority certificate "k8s.cluster.local")'

**Comment by ayj** [comment] 2018-06-05 22:30
The `caBundle` is initially empty based on the default value in istio-demo.yaml. Citadel is responsible for provisioning certs via k8s secret which are mounted into the sidecar injector pod. The sidecar-injector pod(s) should patch the `caBundle` on startup. Re-applying istio-demo.yaml would overwrite the `caBundle`.

**Comment by buddyledungarees** [comment] 2018-06-05 22:34
Ah, thanks for the clarification. Bounced the sidecar-injector pod and now the auto injection is working.

**Comment by ostromart** [comment] 2018-06-12 21:54
Duplicate of https://github.com/istio/istio/issues/6069

**Closed by ostromart** 2018-06-12 21:54 UTC
Labels: area/networking

**Comment by sdake** [comment] 2018-06-25 12:37
@wattli another possibility with this bug is your servers are not running NTP.  Can you verify NTP was running in this scenario?

Cheers
-steve

**Comment by AloisReitbauer** [comment] 2018-07-29 11:52
I had the same issue. After playing around a bit I realized that the example does not set the proper labels for automated sidecar injection. Use

kubectl label namespace default istio-injection=enabled

and it should work.

**Comment by Cryson** [comment] 2018-08-30 14:15
I ran into this issue as well, turned out to be the kube-apiserver manifest and not the injector container as the error stated. I did not have `.svc` in my no_proxy ENV variable for the kube-apiserver. Once I added `.svc` to that ENV variable, everything started working as usual.

**Comment by ayj** [comment] 2018-08-30 16:27
@Cryson, you're not the first to have problems with no_proxy and kube-apiserver. Would you be willing to contribute your findings to either the [k8s webhooks ops guide](https://github.com/istio/istio.github.io/blob/master/content/help/ops/setup/webhook/index.md) or  [quick start guide](https://github.com/istio/istio.github.io/blob/master/content/docs/setup/kubernetes/quick-start/index.md) for your particular k8s distribution / install method?

**Comment by multipathmaster** [comment] 2018-08-30 17:32
put the no_proxy settings in /etc/kubernetes/manifests .  specifically the api manifest/config.  Then systemctl restart kubelet.  Might have to whack the pods too (EXCEPT DNS!!!) to get it to roll.  @ayj feel free to update that.

```
i.e. no_proxy = subdomain.domain.com, localhost, .svc
```

**Comment by Cryson** [comment] 2018-08-30 17:54
@ayj https://github.com/istio/istio.github.io/pull/2477

Let me know if that's acceptable, I saw a lot of people talking about that issue so I believe it'd be good to at least have some information on where to begin troubleshooting. This was an on-premise cluster, therefore proxies become an issue when inside a corporate network.
