### ISSUE TITLE
istioctl replace an existing rule causes a 404 reponse

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1437] opened 2017-11-03 22:50 UTC
@maruina commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926)

Hello, I noticed that when I'm updating the istio pilot rules while serving traffic, sometimes I get back a 404 from envoy.

I have a service with 3 different backends (`istioctl kube-inject` omitted)
```
apiVersion: v1
kind: Service
metadata:
  name: version
  labels:
    app: version
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: version
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: version-one
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: version
        version: v1
        env: production
    spec:
      containers:
      - name: app
        image: <PRIVATE_IMAGE>
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "v1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: version-two
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: version
        version: v2
        env: sandbox
    spec:
      containers:
      - name: app
        image: <PRIVATE_IMAGE>
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "v2"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: version-three
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: version
        version: v3
        env: sandbox
    spec:
      containers:
      - name: app
        image: <PRIVATE_IMAGE>
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "v3"
```
an ingress 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: version-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: <PRIVATE_DNS>
    http:
      paths:
      - backend:
          serviceName: version
          servicePort: 5000
```
and a default istio traffic rule
```
# As default rule, route all traffic to the specifig tag (line 10)
type: route-rule
name: version-default
namespace: default
spec:
  destination: version.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: v1
    weight: 100
```

I have a Python script that opens a request to the endpoint to read the environment variable `VERSION`
```
$ python tester.py counter 10000 <PRIVATE_DNS>/envvar/VERSION
2017-07-12 12:04:26,729 - __main__ - INFO - Version: v1
2017-07-12 12:04:26,767 - __main__ - INFO - Version: v1
2017-07-12 12:04:26,816 - __main__ - INFO - Version: v1
2017-07-12 12:04:26,889 - __main__ - INFO - Version: v1
2017-07-12 12:04:26,928 - __main__ - INFO - Version: v1
2017-07-12 12:04:26,967 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,013 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,048 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,084 - __main__ - INFO - Version: v1
[ ....]
2017-07-12 12:04:27,268 - __main__ - INFO - Version: v1
```
If I change the routing rule to include the other backends
```
type: route-rule
name: version-default
namespace: default
spec:
  destination: version.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: v1
    weight: 30
  - tags:
      version: v2
    weight: 20
  - tags:
      version: v3
    weight: 50
```
and then I apply it with istioctl replace -f istio-default-route.yaml, this is what happens
```
2017-07-12 12:04:27,233 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,268 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,301 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,331 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,363 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,400 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,433 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,466 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,502 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,535 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,567 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,596 - __main__ - INFO - Status code: 404
2017-07-12 12:04:27,634 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,671 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,712 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,760 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,801 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,838 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,878 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,914 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,951 - __main__ - INFO - Version: v1
2017-07-12 12:04:27,987 - __main__ - INFO - Version: v1
2017-07-12 12:04:28,027 - __main__ - INFO - Version: v1
2017-07-12 12:04:28,061 - __main__ - INFO - Version: v1
2017-07-12 12:04:28,104 - __main__ - INFO - Version: v1
2017-07-12 12:04:28,139 - __main__ - INFO - Version: v1
2017-07-12 12:04:28,181 - __main__ - INFO - Version: v1
2017-07-12 12:04:28,222 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,278 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,318 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,377 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,412 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,449 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,498 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,535 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,570 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,605 - __main__ - INFO - Version: v2
2017-07-12 12:04:28,641 - __main__ - INFO - Version: v3
2017-07-12 12:04:28,679 - __main__ - INFO - Version: v3
2017-07-12 12:04:28,715 - __main__ - INFO - Version: v3
2017-07-12 12:04:28,751 - __main__ - INFO - Version: v3
2017-07-12 12:04:28,788 - __main__ - INFO - Version: v3
2017-07-12 12:04:28,822 - __main__ - INFO - Version: v3
2017-07-12 12:04:28,859 - __main__ - INFO - Version: v3
2017-07-12 12:04:28,896 - __main__ - INFO - Version: v3
```
Is that 404 expected? This is what a header looks like
```
Headers: {'date': 'Wed, 12 Jul 2017 11:04:27 GMT', 'server': 'envoy', 'content-length': '0'}
```

---

@rshriram commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-314807980)

This is interesting. Thanks for reporting this and the steps to reproduce this. Can you try the python client from a pod in the cluster, and try to access that service via the local envoy in the pod?
i.e. package this client as another istio app, and do the same route change stuff. And see if the 300ms downtime happens internally as well.  This would help us narrow down the issue to either our ingress implementation or across ingress and internal envoys.

Alternatively, it would be good to take a snapshot of RDS/CDS outputs from istio-pilot, as it would help us understand if this is a problem in Envoy or a problem with the way we are switching to a new config.

---

@rshriram commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-314808998)

cc @mattklein123 @htuch @dnoe - in case you happen to know off the top of your head, whether this downtime is expected. I pretty much think that this should not happen unless RDS update is going ahead of CDS update. 

---

@mattklein123 commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-314813647)

If RDS is received before CDS, yes, this is expected. This is related to the conversation in https://github.com/lyft/envoy-api/issues/102. However, it's difficult to say exactly what is happening here without further debugging.

---

@kyessenov commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-314876588)

Yes, a route rule can introduce a new cluster (for special version, for example), and it's hard to coordinate CDS/RDS. I guess with ADS we can do atomic update and solve the issue. Another way could be to use metadata on network endpoints, to avoid creating multiple clusters in the first place (for v1,v2,v3 routes, route rule should point to a cluster + version selector).

---

@htuch commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-314877012)

@kyessenov Do you need atomicity or jsut single stream semantics with ADS? It's evolving as we speak, let me share my draft with you offline.

---

@kyessenov commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-314877945)

Sequencing of updates (CDS prior to RDS) is sufficient. I think that should be a requirement on ADS to process updates bottom-up.

---

@htuch commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-314878670)

ADS is free to allow the management server to drop traffic if it wants. ADS is really just a mux of the existing xDS. 

---

@rshriram commented on [Wed Jul 12 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-314878770)

I wouldn't want to go down the dynamic cluster stuff (using endpoint metadata). Either way, that would still have the same issue, until SDS info with metadata is propagated.

I think ADS with the ability to sequence updates is sufficient (I would potentially extend it to SDS as well if possible).

---

@maruina commented on [Thu Jul 13 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-315047338)

Hi all, I was able to reproduce the same behavior from a pod inside the cluster running the python script.

Unfortunately, the error seems quite random: sometimes I do an `istioctl replace` and I don't lose any requests, sometimes I have the 404.

---

@rshriram commented on [Thu Jul 13 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-315094060)

@maruina I think we have narrowed the issue. Its an issue/feature of the way we update the route tables and upstream clusters in the Envoy proxy. Today we have two independent updates which is causing the random 404s during updates. But rest assured that this is fixable :)

---

@maruina commented on [Thu Jul 13 2017](https://github.com/istio/old_pilot_repo/issues/926#issuecomment-315112504)

Ok, thanks!
Let me know if I can help!

**Comment by kdillane** [comment] 2017-11-20 17:34
Is this expected to be fixed in 0.3?  Also, can this issue be worked around?  We expect near 100% uptime for the routes in our cluster.

**Comment by ostromart** [comment] 2018-06-13 20:38
@ijsnellf could you close this if no longer applicable?

**Comment by andraxylia** [comment] 2018-06-14 01:57
We need to test this with 0.8, we cannot close it yet.

**Comment by rshriram** [comment] 2018-06-21 19:35
this is a duplicate of #1038 . Please follow that issue for updates..

**Closed** 2018-06-21 19:38 UTC
Labels: area/networking
