### ISSUE TITLE
 Insufficient cpu when running e2e-pilot-auth-v1alpha3-v2-non-mcp in circli CI

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#11887] opened 2019-02-20 09:54 UTC
Most recent run for e2e-pilot-auth-v1alpha3-v2-non-mcp fails in circleci due to:

```sh
FailedScheduling               default-scheduler                                       0/1 nodes are available: 1 Insufficient cpu.
```

```sh
          Normal    ScalingReplicaSet              deployment-controller                                   Scaled up replica set istio-sidecar-injector-b98c6586c to 1
4m          39m          125       istio-telemetry-79c9d9db5c-jcfxq.158506be45fb2586                               Pod                                                                        Warning   FailedScheduling               default-scheduler                                       0/1 nodes are available: 1 Insufficient cpu.
39m         39m          1         istio-telemetry-79c9d9db5c.158506be457b0dc7                                     ReplicaSet                                                                 Normal    SuccessfulCreate               replicaset-controller                                   Created pod: istio-telemetry-79c9d9db5c-jcfxq
39m         39m          1         istio-telemetry.158506be42c46e90                                                Deployment                                                                 Normal    ScalingReplicaSet              deployment-controller                                   Scaled up replica set istio-telemetry-79c9d9db5c to 1
3m          38m          71        istio-telemetry.158506c56148532d                                                HorizontalPodAutoscaler                                                    Warning   FailedGetResourceMetric        horizontal-pod-autoscaler                               unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
32m         38m          13        istio-telemetry.158506c561766ab7                                                HorizontalPodAutoscaler                                                    Warning   FailedComputeMetricsReplicas   horizontal-pod-autoscaler                               failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

https://circleci.com/gh/istio/istio/331194

**Comment by irisdingbj** [comment] 2019-02-20 09:55
https://circleci.com/gh/istio/istio/331195

**Comment by irisdingbj** [comment] 2019-02-20 09:58
Looking at the recent PR: https://github.com/istio/istio/pull/11476 seems we have increased the resource req. We should increase the cricle CI resource as well to fix this.

@mandarjog @linsun any comments for fixing?

**Comment by esnible** [comment] 2019-02-21 16:50
https://circleci.com/gh/istio/istio/333460?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link failed.  This is a PR that adds more logging of test flakes so I have more information about the failure.  When e2e-pilot-auth-v1alpha3-v2-non-mcp failed due to "Deployment rollout ends after [16m0.000143144s] with err [context deadline exceeded]" I the pods were in this status:

```
NAME                                      READY     STATUS              RESTARTS   AGE
istio-citadel-8674d746b6-kmkpt            0/1       Pending             0          16m
istio-egressgateway-8645645bb4-vc6pz      0/1       Running             4          16m
istio-galley-6d5fb455cd-rl8wd             0/1       ContainerCreating   0          16m
istio-ingressgateway-5b5d7b4669-hs8bh     0/1       Running             4          16m
istio-pilot-7f55bb48dd-8bk5r              1/2       Running             4          16m
istio-policy-7c6d7cdff5-22f2h             1/2       CrashLoopBackOff    13         16m
istio-sidecar-injector-77665d5f79-5gc7r   0/1       Pending             0          16m
istio-telemetry-7874b9f48f-rhq8z          0/2       Pending             0          16m
prometheus-646dbcbbbf-hs62k               0/1       Pending             0          16m
```

Very frightening that the pods are still pending after 16 minutes!

The Policy CrashLoopBackOff was caused by

```
  Warning  Unhealthy              15m (x7 over 15m)   kubelet, default-21780827-9d1f-4f11-b56a-53b06fd462a8  Liveness probe failed: Get http://172.17.0.6:15014/version: dial tcp 172.17.0.6:15014: getsockopt: connection refused
  Normal   Killing                15m (x3 over 15m)   kubelet, default-21780827-9d1f-4f11-b56a-53b06fd462a8  Killing container with id docker://mixer:Container failed liveness probe.. Container will be killed and recreated.
```

If the liveness probe is failing this suggests the pod is starved for CPU at startup.

**Comment by howardjohn** [comment] 2019-02-21 18:01
> Looking at the recent PR: #11476 seems we have increased the resource req. We should increase the cricle CI resource as well to fix this.

The change also introduced a new `values-e2e.yaml` file that is used by these tests, so the requests shouldn't have changed. I looked through this file and it looks like the total cpu requests are around 700m, which should be low enough - looks like minikube is started up with defaults, which uses 2 cpus.

What is odd though is in https://circleci.com/gh/istio/istio/333460?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link mixer is requesting 1 cpu. This should be overriden by values-e2e.yaml. I am looking into why this doesn't happen

**Comment by howardjohn** [comment] 2019-02-21 18:13
The test generates `istio-auth.yaml` then ignores it and uses `istio-auth-mcp.yaml` instead which isn't generated with the values-e2e.yaml file. I think this is the cause.

**Comment by douglas-reid** [comment] 2019-03-05 18:30
Can we close this now?

**Comment by howardjohn** [comment] 2019-03-05 18:36
Yes, this should be fixed now. If anyone gets similar errors (pods in pending during e2e test) please open another issue.

**Closed by howardjohn** 2019-03-05 18:36 UTC
Labels: area/perf and scalability, area/test and release
