### ISSUE TITLE
Publish Helm 3 Chart on a Chart repository.

### ISSUE THREAD

**Issue by koalalorenzo** [istio/istio#29222] opened 2020-11-26 16:02 UTC
**Describe the feature request**
It would be nice to have the helm chart published in a public repository accessible by everybody.
I can't figure out why I am forced to use `istioctl` when it looks like under the hood a helm chart/ Go Template is being used. It is way more complex to set up a custom pipeline on Spinnaker or GitLab CI/CD just for istio rather than use a more adopted tool like helm. All other tools/services that I use are installed easily via helm, but **why is Istio being a special one**? 😅 

Note also that [this guide](https://istio.io/v1.8/docs/setup/install/helm/) seems written quickly without telling where the actual manifests are! 😭 (I know where they are but it is not clear to somebody reading it)

**Describe alternatives you've considered**
The alternative is to generate files manually from `istio manifests generate`. 

[x] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure

[x] Multi-Cluster
[x] Virtual Machine
[x] Multi Control Plane

**Additional context**

**Comment by shamsher31** [comment] 2020-11-27 06:32
Similar issue https://github.com/istio/istio/issues/25467

**Comment by desaintmartin** [comment] 2021-03-04 16:47
This would actually allow to automatically deploy the istio-operator WITHOUT having to hack around the huge git repository. It would become as simple (and fast) as:
```
helm repo add istio https://something.istio.io
helm install istio/istio-operator --namespace istio-operator --version 1.9.1
```

**Comment by desaintmartin** [comment] 2021-03-04 16:51
Somehow also related to https://github.com/istio/istio/issues/30471

**Comment by desaintmartin** [comment] 2021-03-04 19:08
In the meantime, I've published the istio-operator helm chart v1.9.1 at https://artifacthub.io/packages/helm/wiremind/istio-operator. For other charts, you can easily do it as well on your own repo with testing and so on.

**Comment by koalalorenzo** [comment] 2021-06-10 10:31
We should re-open this issue! :D

**Comment by koalalorenzo** [comment] 2021-06-10 11:12
@howardjohn @desaintmartin do we know how to re-open this issue? :) Can anybody help?

**Comment by koalalorenzo** [comment] 2021-06-11 07:49
Thank you :)

**Comment by bsord** [comment] 2021-07-16 20:19
This is the only project i've used for kubernetes that does not host their own helm repository for the chart. PLEASE do this. I can't use istio without it (unless i manually publish charts to my own repositories but this will quickly fall out of date). I am grateful this issue is re-opened. You can even use a github action and github pages repo to automatically publish these and host for free with github.

**Comment by howardjohn** [comment] 2021-09-10 03:22
This is a duplicate of https://github.com/istio/istio/issues/31275. Which will be fixed very soon.

**Closed by howardjohn** 2021-09-10 03:22 UTC
Labels: kind/enhancement, area/environments, area/user experience, lifecycle/automatically-closed
