### ISSUE TITLE
[Test Framework] Support TLS is Native Echo component

### ISSUE THREAD

**Issue by nmittler** [istio/istio#13778] opened 2019-05-02 14:02 UTC

**Comment by howardjohn** [comment] 2019-08-12 01:30
@nmittler is this done now that we have docker?

**Comment by nmittler** [comment] 2019-08-12 14:20
@howardjohn echo *should* support it now, but I think there may still be some pieces missing (native citidel?) before we can make sure it works.

**Comment by howardjohn** [comment] 2019-10-03 17:21
Effectively duplicate of https://github.com/istio/istio/issues/9177

**Closed by howardjohn** 2019-10-03 17:21 UTC
Labels: area/test and release, kind/enhancement
