### ISSUE TITLE
prow/e2e-smoke.sh failure:recipe for target 'istioctl' failed

### ISSUE THREAD

**Issue by mangchiandjjoe** [istio/istio#3320] opened 2018-02-08 19:25 UTC
Multiple PR encounter the same issue.

@yutongz @mattdelco Could you please take a look or reassign the issue to the the right person?

https://storage.googleapis.com/istio-prow/pull/istio_istio/3169/e2e-smoke/2613/build-log.txt

```
W0208 18:45:12.065] + make e2e_bookinfo
W0208 18:45:12.220] pilot/cmd/istioctl/inject.go:24:2: cannot find package "github.com/ghodss/yaml" in any of:
W0208 18:45:12.220] 	/usr/local/go/src/github.com/ghodss/yaml (from $GOROOT)
W0208 18:45:12.220] 	/home/bootstrap/go/src/github.com/ghodss/yaml (from $GOPATH)
W0208 18:45:12.221] pilot/pkg/model/conversion.go:24:2: cannot find package "github.com/gogo/protobuf/jsonpb" in any of:
W0208 18:45:12.221] 	/usr/local/go/src/github.com/gogo/protobuf/jsonpb (from $GOROOT)
W0208 18:45:12.221] 	/home/bootstrap/go/src/github.com/gogo/protobuf/jsonpb (from $GOPATH)
W0208 18:45:12.221] pilot/pkg/model/conversion.go:25:2: cannot find package "github.com/gogo/protobuf/proto" in any of:
W0208 18:45:12.221] 	/usr/local/go/src/github.com/gogo/protobuf/proto (from $GOROOT)
W0208 18:45:12.222] 	/home/bootstrap/go/src/github.com/gogo/protobuf/proto (from $GOPATH)
W0208 18:45:12.222] pilot/pkg/model/validation.go:29:2: cannot find package "github.com/gogo/protobuf/types" in any of:
W0208 18:45:12.222] 	/usr/local/go/src/github.com/gogo/protobuf/types (from $GOROOT)
W0208 18:45:12.222] 	/home/bootstrap/go/src/github.com/gogo/protobuf/types (from $GOPATH)
W0208 18:45:12.222] pilot/cmd/istioctl/main.go:29:2: cannot find package "github.com/golang/glog" in any of:
W0208 18:45:12.223] 	/usr/local/go/src/github.com/golang/glog (from $GOROOT)
W0208 18:45:12.223] 	/home/bootstrap/go/src/github.com/golang/glog (from $GOPATH)
W0208 18:45:12.223] pilot/pkg/model/conversion.go:26:2: cannot find package "github.com/golang/protobuf/jsonpb" in any of:
W0208 18:45:12.223] 	/usr/local/go/src/github.com/golang/protobuf/jsonpb (from $GOROOT)
W0208 18:45:12.223] 	/home/bootstrap/go/src/github.com/golang/protobuf/jsonpb (from $GOPATH)
W0208 18:45:12.224] pilot/pkg/model/config.go:23:2: cannot find package "github.com/golang/protobuf/proto" in any of:
W0208 18:45:12.224] 	/usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
W0208 18:45:12.224] 	/home/bootstrap/go/src/github.com/golang/protobuf/proto (from $GOPATH)
W0208 18:45:12.224] pilot/pkg/model/context.go:25:2: cannot find package "github.com/golang/protobuf/ptypes" in any of:
W0208 18:45:12.224] 	/usr/local/go/src/github.com/golang/protobuf/ptypes (from $GOROOT)
W0208 18:45:12.224] 	/home/bootstrap/go/src/github.com/golang/protobuf/ptypes (from $GOPATH)
W0208 18:45:12.225] pilot/pkg/model/validation.go:32:2: cannot find package "github.com/golang/protobuf/ptypes/duration" in any of:
W0208 18:45:12.225] 	/usr/local/go/src/github.com/golang/protobuf/ptypes/duration (from $GOROOT)
W0208 18:45:12.225] 	/home/bootstrap/go/src/github.com/golang/protobuf/ptypes/duration (from $GOPATH)
W0208 18:45:12.225] pilot/cmd/istioctl/main.go:30:2: cannot find package "github.com/hashicorp/go-multierror" in any of:
W0208 18:45:12.225] 	/usr/local/go/src/github.com/hashicorp/go-multierror (from $GOROOT)
W0208 18:45:12.225] 	/home/bootstrap/go/src/github.com/hashicorp/go-multierror (from $GOPATH)
W0208 18:45:12.226] pilot/pkg/kube/inject/webhook.go:30:2: cannot find package "github.com/howeyc/fsnotify" in any of:
W0208 18:45:12.226] 	/usr/local/go/src/github.com/howeyc/fsnotify (from $GOROOT)
W0208 18:45:12.226] 	/home/bootstrap/go/src/github.com/howeyc/fsnotify (from $GOPATH)
W0208 18:45:12.226] pkg/log/config.go:55:2: cannot find package "github.com/natefinch/lumberjack" in any of:
W0208 18:45:12.226] 	/usr/local/go/src/github.com/natefinch/lumberjack (from $GOROOT)
W0208 18:45:12.226] 	/home/bootstrap/go/src/github.com/natefinch/lumberjack (from $GOPATH)
W0208 18:45:12.227] pilot/pkg/kube/inject/initializer.go:18:2: cannot find package "github.com/openshift/api/apps/v1" in any of:
W0208 18:45:12.227] 	/usr/local/go/src/github.com/openshift/api/apps/v1 (from $GOROOT)
W0208 18:45:12.227] 	/home/bootstrap/go/src/github.com/openshift/api/apps/v1 (from $GOPATH)
W0208 18:45:12.227] pilot/cmd/istioctl/config.go:22:2: cannot find package "github.com/spf13/cobra" in any of:
W0208 18:45:12.227] 	/usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
W0208 18:45:12.227] 	/home/bootstrap/go/src/github.com/spf13/cobra (from $GOPATH)
W0208 18:45:12.228] pilot/cmd/istioctl/main.go:42:2: cannot find package "github.com/spf13/cobra/doc" in any of:
W0208 18:45:12.228] 	/usr/local/go/src/github.com/spf13/cobra/doc (from $GOROOT)
W0208 18:45:12.228] 	/home/bootstrap/go/src/github.com/spf13/cobra/doc (from $GOPATH)
W0208 18:45:12.228] pkg/collateral/control.go:28:2: cannot find package "github.com/spf13/pflag" in any of:
W0208 18:45:12.228] 	/usr/local/go/src/github.com/spf13/pflag (from $GOROOT)
W0208 18:45:12.229] 	/home/bootstrap/go/src/github.com/spf13/pflag (from $GOPATH)
W0208 18:45:12.229] pkg/log/config.go:56:2: cannot find package "go.uber.org/zap" in any of:
W0208 18:45:12.229] 	/usr/local/go/src/go.uber.org/zap (from $GOROOT)
W0208 18:45:12.229] 	/home/bootstrap/go/src/go.uber.org/zap (from $GOPATH)
W0208 18:45:12.229] pkg/log/config.go:57:2: cannot find package "go.uber.org/zap/zapcore" in any of:
W0208 18:45:12.229] 	/usr/local/go/src/go.uber.org/zap/zapcore (from $GOROOT)
W0208 18:45:12.229] 	/home/bootstrap/go/src/go.uber.org/zap/zapcore (from $GOPATH)
W0208 18:45:12.230] pkg/log/config.go:58:2: cannot find package "go.uber.org/zap/zapgrpc" in any of:
W0208 18:45:12.230] 	/usr/local/go/src/go.uber.org/zap/zapgrpc (from $GOROOT)
W0208 18:45:12.230] 	/home/bootstrap/go/src/go.uber.org/zap/zapgrpc (from $GOPATH)
W0208 18:45:12.230] pkg/log/config.go:59:2: cannot find package "google.golang.org/grpc/grpclog" in any of:
W0208 18:45:12.230] 	/usr/local/go/src/google.golang.org/grpc/grpclog (from $GOROOT)
W0208 18:45:12.230] 	/home/bootstrap/go/src/google.golang.org/grpc/grpclog (from $GOPATH)
W0208 18:45:12.231] pilot/pkg/model/conversion.go:29:2: cannot find package "gopkg.in/yaml.v2" in any of:
W0208 18:45:12.231] 	/usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
W0208 18:45:12.231] 	/home/bootstrap/go/src/gopkg.in/yaml.v2 (from $GOPATH)
W0208 18:45:12.231] pilot/cmd/istioctl/inject.go:28:2: cannot find package "istio.io/api/mesh/v1alpha1" in any of:
W0208 18:45:12.231] 	/usr/local/go/src/istio.io/api/mesh/v1alpha1 (from $GOROOT)
W0208 18:45:12.231] 	/home/bootstrap/go/src/istio.io/api/mesh/v1alpha1 (from $GOPATH)
W0208 18:45:12.232] pilot/pkg/model/validation.go:36:2: cannot find package "istio.io/api/mixer/v1" in any of:
W0208 18:45:12.232] 	/usr/local/go/src/istio.io/api/mixer/v1 (from $GOROOT)
W0208 18:45:12.232] 	/home/bootstrap/go/src/istio.io/api/mixer/v1 (from $GOPATH)
W0208 18:45:12.232] pilot/pkg/model/config.go:25:2: cannot find package "istio.io/api/mixer/v1/config/client" in any of:
W0208 18:45:12.232] 	/usr/local/go/src/istio.io/api/mixer/v1/config/client (from $GOROOT)
W0208 18:45:12.232] 	/home/bootstrap/go/src/istio.io/api/mixer/v1/config/client (from $GOPATH)
W0208 18:45:12.233] pilot/pkg/model/config.go:26:2: cannot find package "istio.io/api/routing/v1alpha1" in any of:
W0208 18:45:12.233] 	/usr/local/go/src/istio.io/api/routing/v1alpha1 (from $GOROOT)
W0208 18:45:12.233] 	/home/bootstrap/go/src/istio.io/api/routing/v1alpha1 (from $GOPATH)
W0208 18:45:12.233] pilot/pkg/model/config.go:27:2: cannot find package "istio.io/api/routing/v1alpha2" in any of:
W0208 18:45:12.233] 	/usr/local/go/src/istio.io/api/routing/v1alpha2 (from $GOROOT)
W0208 18:45:12.233] 	/home/bootstrap/go/src/istio.io/api/routing/v1alpha2 (from $GOPATH)
W0208 18:45:12.234] pilot/pkg/kube/inject/webhook.go:31:2: cannot find package "k8s.io/api/admission/v1beta1" in any of:
W0208 18:45:12.234] 	/usr/local/go/src/k8s.io/api/admission/v1beta1 (from $GOROOT)
W0208 18:45:12.234] 	/home/bootstrap/go/src/k8s.io/api/admission/v1beta1 (from $GOPATH)
W0208 18:45:12.234] pilot/pkg/kube/inject/webhook.go:32:2: cannot find package "k8s.io/api/admissionregistration/v1beta1" in any of:
W0208 18:45:12.234] 	/usr/local/go/src/k8s.io/api/admissionregistration/v1beta1 (from $GOROOT)
W0208 18:45:12.234] 	/home/bootstrap/go/src/k8s.io/api/admissionregistration/v1beta1 (from $GOPATH)
W0208 18:45:12.235] pilot/pkg/kube/inject/initializer.go:19:2: cannot find package "k8s.io/api/apps/v1beta1" in any of:
W0208 18:45:12.235] 	/usr/local/go/src/k8s.io/api/apps/v1beta1 (from $GOROOT)
W0208 18:45:12.235] 	/home/bootstrap/go/src/k8s.io/api/apps/v1beta1 (from $GOPATH)
W0208 18:45:12.235] pilot/pkg/kube/inject/initializer.go:20:2: cannot find package "k8s.io/api/batch/v1" in any of:
W0208 18:45:12.235] 	/usr/local/go/src/k8s.io/api/batch/v1 (from $GOROOT)
W0208 18:45:12.235] 	/home/bootstrap/go/src/k8s.io/api/batch/v1 (from $GOPATH)
W0208 18:45:12.235] pilot/pkg/kube/inject/initializer.go:21:2: cannot find package "k8s.io/api/batch/v2alpha1" in any of:
W0208 18:45:12.236] 	/usr/local/go/src/k8s.io/api/batch/v2alpha1 (from $GOROOT)
W0208 18:45:12.236] 	/home/bootstrap/go/src/k8s.io/api/batch/v2alpha1 (from $GOPATH)
W0208 18:45:12.236] pilot/pkg/serviceregistry/kube/cache.go:20:2: cannot find package "k8s.io/api/core/v1" in any of:
W0208 18:45:12.236] 	/usr/local/go/src/k8s.io/api/core/v1 (from $GOROOT)
W0208 18:45:12.236] 	/home/bootstrap/go/src/k8s.io/api/core/v1 (from $GOPATH)
W0208 18:45:12.236] pilot/pkg/kube/inject/initializer.go:23:2: cannot find package "k8s.io/api/extensions/v1beta1" in any of:
W0208 18:45:12.236] 	/usr/local/go/src/k8s.io/api/extensions/v1beta1 (from $GOROOT)
W0208 18:45:12.236] 	/home/bootstrap/go/src/k8s.io/api/extensions/v1beta1 (from $GOPATH)
W0208 18:45:12.236] pilot/pkg/config/kube/crd/client.go:27:2: cannot find package "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1" in any of:
W0208 18:45:12.236] 	/usr/local/go/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1 (from $GOROOT)
W0208 18:45:12.237] 	/home/bootstrap/go/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1 (from $GOPATH)
W0208 18:45:12.237] pilot/pkg/config/kube/crd/client.go:28:2: cannot find package "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset" in any of:
W0208 18:45:12.237] 	/usr/local/go/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset (from $GOROOT)
W0208 18:45:12.237] 	/home/bootstrap/go/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset (from $GOPATH)
W0208 18:45:12.237] pilot/pkg/config/kube/crd/client.go:29:2: cannot find package "k8s.io/apimachinery/pkg/api/errors" in any of:
W0208 18:45:12.237] 	/usr/local/go/src/k8s.io/apimachinery/pkg/api/errors (from $GOROOT)
W0208 18:45:12.237] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/api/errors (from $GOPATH)
W0208 18:45:12.237] pilot/pkg/serviceregistry/kube/controller.go:25:2: cannot find package "k8s.io/apimachinery/pkg/apis/meta/v1" in any of:
W0208 18:45:12.238] 	/usr/local/go/src/k8s.io/apimachinery/pkg/apis/meta/v1 (from $GOROOT)
W0208 18:45:12.238] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/apis/meta/v1 (from $GOPATH)
W0208 18:45:12.238] pilot/pkg/serviceregistry/kube/controller.go:26:2: cannot find package "k8s.io/apimachinery/pkg/runtime" in any of:
W0208 18:45:12.238] 	/usr/local/go/src/k8s.io/apimachinery/pkg/runtime (from $GOROOT)
W0208 18:45:12.238] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/runtime (from $GOPATH)
W0208 18:45:12.238] pilot/pkg/config/kube/crd/client.go:32:2: cannot find package "k8s.io/apimachinery/pkg/runtime/schema" in any of:
W0208 18:45:12.238] 	/usr/local/go/src/k8s.io/apimachinery/pkg/runtime/schema (from $GOROOT)
W0208 18:45:12.238] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/runtime/schema (from $GOPATH)
W0208 18:45:12.238] pilot/pkg/config/kube/crd/client.go:33:2: cannot find package "k8s.io/apimachinery/pkg/runtime/serializer" in any of:
W0208 18:45:12.239] 	/usr/local/go/src/k8s.io/apimachinery/pkg/runtime/serializer (from $GOROOT)
W0208 18:45:12.239] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/runtime/serializer (from $GOPATH)
W0208 18:45:12.239] pilot/pkg/serviceregistry/kube/conversion.go:26:2: cannot find package "k8s.io/apimachinery/pkg/util/intstr" in any of:
W0208 18:45:12.239] 	/usr/local/go/src/k8s.io/apimachinery/pkg/util/intstr (from $GOROOT)
W0208 18:45:12.239] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/util/intstr (from $GOPATH)
W0208 18:45:12.239] pilot/pkg/config/kube/crd/client.go:34:2: cannot find package "k8s.io/apimachinery/pkg/util/wait" in any of:
W0208 18:45:12.239] 	/usr/local/go/src/k8s.io/apimachinery/pkg/util/wait (from $GOROOT)
W0208 18:45:12.239] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/util/wait (from $GOPATH)
W0208 18:45:12.239] pilot/pkg/config/kube/crd/conversion.go:26:2: cannot find package "k8s.io/apimachinery/pkg/util/yaml" in any of:
W0208 18:45:12.240] 	/usr/local/go/src/k8s.io/apimachinery/pkg/util/yaml (from $GOROOT)
W0208 18:45:12.240] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/util/yaml (from $GOPATH)
W0208 18:45:12.240] pilot/pkg/serviceregistry/kube/controller.go:27:2: cannot find package "k8s.io/apimachinery/pkg/watch" in any of:
W0208 18:45:12.240] 	/usr/local/go/src/k8s.io/apimachinery/pkg/watch (from $GOROOT)
W0208 18:45:12.240] 	/home/bootstrap/go/src/k8s.io/apimachinery/pkg/watch (from $GOPATH)
W0208 18:45:12.240] pilot/cmd/istioctl/main.go:34:2: cannot find package "k8s.io/client-go/discovery" in any of:
W0208 18:45:12.240] 	/usr/local/go/src/k8s.io/client-go/discovery (from $GOROOT)
W0208 18:45:12.240] 	/home/bootstrap/go/src/k8s.io/client-go/discovery (from $GOPATH)
W0208 18:45:12.241] pilot/cmd/istioctl/main.go:35:2: cannot find package "k8s.io/client-go/dynamic" in any of:
W0208 18:45:12.241] 	/usr/local/go/src/k8s.io/client-go/dynamic (from $GOROOT)
W0208 18:45:12.241] 	/home/bootstrap/go/src/k8s.io/client-go/dynamic (from $GOPATH)
W0208 18:45:12.241] pilot/pkg/serviceregistry/kube/client.go:24:2: cannot find package "k8s.io/client-go/kubernetes" in any of:
W0208 18:45:12.241] 	/usr/local/go/src/k8s.io/client-go/kubernetes (from $GOROOT)
W0208 18:45:12.241] 	/home/bootstrap/go/src/k8s.io/client-go/kubernetes (from $GOPATH)
W0208 18:45:12.241] pilot/cmd/istioctl/config.go:25:2: cannot find package "k8s.io/client-go/kubernetes/scheme" in any of:
W0208 18:45:12.241] 	/usr/local/go/src/k8s.io/client-go/kubernetes/scheme (from $GOROOT)
W0208 18:45:12.241] 	/home/bootstrap/go/src/k8s.io/client-go/kubernetes/scheme (from $GOPATH)
W0208 18:45:12.242] pilot/pkg/serviceregistry/kube/client.go:33:2: cannot find package "k8s.io/client-go/plugin/pkg/client/auth/gcp" in any of:
W0208 18:45:12.242] 	/usr/local/go/src/k8s.io/client-go/plugin/pkg/client/auth/gcp (from $GOROOT)
W0208 18:45:12.242] 	/home/bootstrap/go/src/k8s.io/client-go/plugin/pkg/client/auth/gcp (from $GOPATH)
W0208 18:45:12.242] pilot/pkg/serviceregistry/kube/client.go:36:2: cannot find package "k8s.io/client-go/plugin/pkg/client/auth/oidc" in any of:
W0208 18:45:12.242] 	/usr/local/go/src/k8s.io/client-go/plugin/pkg/client/auth/oidc (from $GOROOT)
W0208 18:45:12.242] 	/home/bootstrap/go/src/k8s.io/client-go/plugin/pkg/client/auth/oidc (from $GOPATH)
W0208 18:45:12.242] pilot/pkg/serviceregistry/kube/client.go:25:2: cannot find package "k8s.io/client-go/rest" in any of:
W0208 18:45:12.243] 	/usr/local/go/src/k8s.io/client-go/rest (from $GOROOT)
W0208 18:45:12.243] 	/home/bootstrap/go/src/k8s.io/client-go/rest (from $GOPATH)
W0208 18:45:12.243] pilot/pkg/serviceregistry/kube/controller.go:29:2: cannot find package "k8s.io/client-go/tools/cache" in any of:
W0208 18:45:12.243] 	/usr/local/go/src/k8s.io/client-go/tools/cache (from $GOROOT)
W0208 18:45:12.243] 	/home/bootstrap/go/src/k8s.io/client-go/tools/cache (from $GOPATH)
W0208 18:45:12.243] pilot/pkg/serviceregistry/kube/client.go:26:2: cannot find package "k8s.io/client-go/tools/clientcmd" in any of:
W0208 18:45:12.243] 	/usr/local/go/src/k8s.io/client-go/tools/clientcmd (from $GOROOT)
W0208 18:45:12.243] 	/home/bootstrap/go/src/k8s.io/client-go/tools/clientcmd (from $GOPATH)
W0208 18:45:12.244] pilot/cmd/istioctl/main.go:38:2: cannot find package "k8s.io/client-go/tools/clientcmd/api" in any of:
W0208 18:45:12.244] 	/usr/local/go/src/k8s.io/client-go/tools/clientcmd/api (from $GOROOT)
W0208 18:45:12.244] 	/home/bootstrap/go/src/k8s.io/client-go/tools/clientcmd/api (from $GOPATH)
W0208 18:45:12.244] pilot/cmd/istioctl/config.go:28:2: cannot find package "k8s.io/client-go/tools/remotecommand" in any of:
W0208 18:45:12.244] 	/usr/local/go/src/k8s.io/client-go/tools/remotecommand (from $GOROOT)
W0208 18:45:12.244] 	/home/bootstrap/go/src/k8s.io/client-go/tools/remotecommand (from $GOPATH)
W0208 18:45:12.244] pilot/pkg/serviceregistry/kube/queue.go:22:2: cannot find package "k8s.io/client-go/util/flowcontrol" in any of:
W0208 18:45:12.244] 	/usr/local/go/src/k8s.io/client-go/util/flowcontrol (from $GOROOT)
W0208 18:45:12.245] 	/home/bootstrap/go/src/k8s.io/client-go/util/flowcontrol (from $GOPATH)
W0208 18:45:12.245] pilot/cmd/istioctl/main.go:43:2: cannot find package "k8s.io/client-go/util/homedir" in any of:
W0208 18:45:12.245] 	/usr/local/go/src/k8s.io/client-go/util/homedir (from $GOROOT)
W0208 18:45:12.245] 	/home/bootstrap/go/src/k8s.io/client-go/util/homedir (from $GOPATH)
W0208 18:45:12.245] pilot/cmd/istioctl/gendeployment/yaml.go:22:2: cannot find package "k8s.io/helm/pkg/chartutil" in any of:
W0208 18:45:12.245] 	/usr/local/go/src/k8s.io/helm/pkg/chartutil (from $GOROOT)
W0208 18:45:12.245] 	/home/bootstrap/go/src/k8s.io/helm/pkg/chartutil (from $GOPATH)
W0208 18:45:12.245] pilot/cmd/istioctl/gendeployment/yaml.go:23:2: cannot find package "k8s.io/helm/pkg/engine" in any of:
W0208 18:45:12.245] 	/usr/local/go/src/k8s.io/helm/pkg/engine (from $GOROOT)
W0208 18:45:12.246] 	/home/bootstrap/go/src/k8s.io/helm/pkg/engine (from $GOPATH)
W0208 18:45:12.246] pilot/cmd/istioctl/gendeployment/yaml.go:24:2: cannot find package "k8s.io/helm/pkg/proto/hapi/chart" in any of:
W0208 18:45:12.246] 	/usr/local/go/src/k8s.io/helm/pkg/proto/hapi/chart (from $GOROOT)
W0208 18:45:12.246] 	/home/bootstrap/go/src/k8s.io/helm/pkg/proto/hapi/chart (from $GOPATH)
W0208 18:45:12.246] pilot/cmd/istioctl/gendeployment/yaml.go:25:2: cannot find package "k8s.io/helm/pkg/timeconv" in any of:
W0208 18:45:12.246] 	/usr/local/go/src/k8s.io/helm/pkg/timeconv (from $GOROOT)
W0208 18:45:12.246] 	/home/bootstrap/go/src/k8s.io/helm/pkg/timeconv (from $GOPATH)
W0208 18:45:12.246] pilot/pkg/kube/inject/webhook.go:37:2: cannot find package "k8s.io/kubernetes/pkg/apis/core/v1" in any of:
W0208 18:45:12.247] 	/usr/local/go/src/k8s.io/kubernetes/pkg/apis/core/v1 (from $GOROOT)
W0208 18:45:12.247] 	/home/bootstrap/go/src/k8s.io/kubernetes/pkg/apis/core/v1 (from $GOPATH)
W0208 18:45:12.247] make: *** [istioctl] Error 1
I0208 18:45:12.247] Makefile:262: recipe for target 'istioctl' failed
E0208 18:45:12.247] Build failed
I0208 18:45:12.247] process 525 exited with code 2 after 0.0m
E0208 18:45:12.247] FAIL: e2e-smoke
```

**Comment by mattdelco** [comment] 2018-02-08 19:39
Looks like https://github.com/istio/istio/pull/3151 was merged despite the test results failing due to removal of dependencies.  The failure that @rshriram notes about "missing deps" is caused by the PR since it removed the dependencies that caused the dep tool to be run.

**Comment by hklai** [comment] 2018-02-08 22:08
Prow shows clearly that the tests started failing consistently after #3151.
https://prow.istio.io/?type=postsubmit&job=e2e-suite-rbac-auth

**Closed** 2018-02-11 01:49 UTC
Labels: area/test and release, ci/prow, kind/test-failure
