### ISSUE TITLE
istioctl inside a pod can't use internal API server

### ISSUE THREAD

**Issue by prune998** [istio/istio#4297] opened 2018-03-15 18:52 UTC
# Description

Inside a Pod in a Kubernetes cluster, running `istioctl kube-inject -f deployment.yml` requires a valid `.kube/config` file.
Running `kubectl get pods` automatically use the internal API and does not require a `.kube/config` file.

```
# ./istioctl kube-inject -f foo.yml
Error: kubernetes configuration file "/root/.kube/config" does not exist
```

Note : when using RBAC, you have to ensure your pod is allowed to query the API, which is the case for me as `kubectl get XXX` works.

# Expected 
running `istioctl kube-inject -f deployment.yml` should call the internal API, as `kubectl` is doing

# Details
Using Kubernetes 1.9.2 on GKE
```
~ # ./kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}
```
```
~ # ./istioctl version
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
```

**Comment by xiaolanz** [comment] 2018-03-22 21:12
Can you try this: 
https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod

**Comment by ozevren** [comment] 2018-06-13 21:42
Dupe of https://github.com/istio/istio/issues/1971

**Closed by ozevren** 2018-06-13 21:42 UTC
Labels: area/config
