### ISSUE TITLE
Istio 1.6.X does not honor the workloadlabel field in envoyfilter but it is not being rejected by admissioncontroller

### ISSUE THREAD

**Issue by fams** [istio/istio#29788] opened 2020-12-28 12:32 UTC
**After upgrade from istio 1.5.10 to istio 1.6.14 My envoyfilters in root became applied to all my workloads, despite envoyfilter has a workloadlabel field configured, but the admission controller accepts the deprecated config**

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
EnvoyFilter.spec.Workloadlabel limits the worload apply or this field be rejected by istio.

**Steps to reproduce the bug**

1. install istio 1.6.X ( i have tested with 1.6.14)

2. apply a manifest using WorlLoadlabels and verify that it's not limiting the filter apply

**Version** 
istioctl version --remote
client version: 1.6.14
control plane version: 1.6.14
data plane version: 1.6.14 (225 proxies)

kubectl version --short
Client Version: v1.19.0
Server Version: v1.17.12-eks-7684af

**How was Istio installed?**

istioctl manifest apply

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS eks

**Comment by howardjohn** [comment] 2020-12-28 15:29
This is working as intended. While I agree the upgrade strategy was not ideal here, its not appropriate to make a CRD pass validation in vN and fail in vN+1 and causes all sorts of issues; we intend to never do this.

While we may have been able to handle this better, this API changed so long ago in EOL'd versions (https://istio.io/latest/news/support/announcing-1.6-eol/) that I am not sure we can do anything.

**Comment by howardjohn** [comment] 2021-01-04 00:38
Closing per ^

**Closed by howardjohn** 2021-01-04 00:38 UTC
Labels: kind/need more info
