### ISSUE TITLE
Istioctl validate but for installation options

### ISSUE THREAD

**Issue by Stono** [istio/istio#25416] opened 2020-07-10 09:34 UTC
**Describe the feature request**
We have quite a large `values.yaml` for istio installation options, which has evolved since like 0.2.  I've no doubt that some of the fields aren't valuable any more but i'm hesitant to remove them through fear of unknown side effects or enforcing defaults which could change in the future.

I'm also thinking it would be good for an end user to be able to validate their config options, before attempting to deploy using them.

Therefore it'd be really nice to have the ability to do something like `istioctl validate-config installation.yaml` 🤷  

This would also help during upgrades to help you spot and deprecated or removed config items.

**Describe alternatives you've considered**
None really, if there was a json schema provided somewhere which we could validate against, that'd do too.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment] 2020-07-10 18:52
@esnible i think you looked into this at one point?

**Comment by esnible** [comment] 2020-07-12 10:28
This is a duplicate of https://github.com/istio/istio/issues/21473

I will target that issue for 1.8 and try to prioritize it.  Some of the hooks are present.

**Closed by esnible** 2020-07-12 10:28 UTC
Labels: area/environments, area/test and release, area/user experience, kind/enhancement
