### ISSUE TITLE
ingressgateway can't access https service. 

### ISSUE THREAD

**Issue by lubinson** [istio/istio#8029] opened 2018-08-17 14:44 UTC
**Describe the bug**
_I tried to set up a gateway and virtual service for an https service. But the gateway can only send clear http request to the https service. And the https service return 400 Bad Request - The plain HTTP request was sent to HTTPS port._ 

**Expected behavior**
_https request should be sent from gateway to https service._

**Steps to reproduce the bug**
1, Install the my-nginx project from istio sample. This is a https service. 
2, add gateway as below
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE #enables HTTPS on this port
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```
3, add virtual service
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-nginx
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  http:
  - match:  
    - uri:
        prefix: "/"  
    route:
    - destination:
        host: my-nginx
        port:
          number: 443
```
4, run test
run below command. I use NodePort. The 10.0.0.27 is the node IP, 31390 is the node port. 
```
curl https://10.0.0.27:31390 -k
```
run result
```
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.11.3</center>
</body>
</html>
```
**Version**
_What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`_
istioctl version
```
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

```
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not?**
_Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input._
```
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
```
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true
```
**Environment**
_Which environment, cloud vendor, OS, etc are you using?_
```
Linux k8s-m 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
**Cluster state**
_If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue._

**Comment by ijsnellf** [comment] 2018-08-17 15:09
cc @vadimeisenbergibm

**Comment by vadimeisenbergibm** [comment] 2018-08-17 16:01
@lubinson @ijsnellf let me describe how to configure it, will submit a PR to istio.io.

**Comment by vadimeisenbergibm** [comment] 2018-08-20 07:49
@lubinson Here is the example I wrote 
https://preliminary.istio.io/docs/examples/ingress-for-https/

Note that you have to use `PASSTHROUGH` `tls` `mode` since the gateway must not perform TLS termination. Also note that the `VirtualService` should have `tls` match by `sni_hosts`.

**Comment by lubinson** [comment] 2018-08-22 14:33
@vadimeisenbergibm 

Thanks. I have tried on Nginx Service. It works, even set ```sni_hosts``` to "*" in the VirtualService and even just using ```curl -i https://10.0.0.27:31390 -k```. My Gateway and VirtualService files are listed as below:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: PASSTHROUGH
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-nginx
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*"
    route:
    - destination:
        host: my-nginx
        port:
          number: 443
```
Run 
```
curl -i https://10.0.0.27:31390 -k
```
Result
```
HTTP/1.1 200 OK
Server: nginx/1.11.3
Date: Tue, 21 Aug 2018 18:52:52 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 26 Jul 2016 14:54:48 GMT
Connection: keep-alive
ETag: "579779b8-264"
Accept-Ranges: bytes

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```
Then I apply the same steps to my service. I got below error reported by curl. 
```
curl: (35) Encountered end of file
```
I found the ingress gateway send ```"Unknown CA"``` to the HTTPS service when handshaking. 

I thought it should be successful same as using ```-k``` option (ingore certificate verification) to access Nginx https service. But unfortunately not.

Then I follow your way to generate cert and key, use it to replace the cert and key in my service. Then use curl with ```--cacert``` option. But still the same failure. 

Why I did nothing it succeed when accessing Nginx service. But failed on my own service with all necessary steps. My service is a java service using keystore to store cert and keys. It didn't use secrets in k8s. 

Best Regards.

**Comment by vadimeisenbergibm** [comment] 2018-08-22 15:03
@lubinson 

Do you manage to call your HTTPS service from inside the cluster? Also note that the example has been moved to https://preliminary.istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/.

**Comment by lubinson** [comment] 2018-08-22 16:17
@vadimeisenbergibm 

This HTTPS service can be directly accessed by web browser by using the Node IP and Service Node Port (not the ingress node port). And also can be directly accessed by ```curl -i https://10.0.0.27:5443 -k ```. 5443 is the service node port. 

All these cmds including the failed and successed cases are running in the master node of the cluster. 

Yes, I have already follow the preliminary url you given. Thanks.

**Comment by vadimeisenbergibm** [comment] 2018-11-11 16:04
@lubinson Getting back to the issue, did you manage to fix it? Is it still relevant?

**Comment by kongyi-ibm** [comment] 2018-11-26 17:07
Except the SSL passthrough, do we have any other solution can let ingressgateway to terminal SSL and send https request to backend https service ?

I want to implement the solution like this:

https request --> ingressgateway --> https service 

gateway:
===================================
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt

virtualserivce:
========================================
spec:
  gateways:
  - mygateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /search
    route:
    - destination:
        host: search.default.svc.cluster.local
        port:
          number: 3738

But when I use curl to access, the ingress always report 503. But I can curl from the envoy sidecar and get correct response

[root@pe103 ~]# curl -v -k https://9.112.245.103:31390/search/admin/resources/health/ping
* About to connect() to 9.112.245.103 port 31390 (#0)
*   Trying 9.112.245.103...
* Connected to 9.112.245.103 (9.112.245.103) port 31390 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* Server certificate:
*       subject: CN=*
*       start date: Jun 09 15:40:43 2017 GMT
*       expire date: May 26 03:41:13 2027 GMT
*       common name: *
*       issuer: CN=testcert.watsoncommerce.ibm.com
> GET /search/admin/resources/health/ping HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 9.112.245.103:31390
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Mon, 26 Nov 2018 16:57:17 GMT
< server: envoy
< x-envoy-upstream-service-time: 8
<
* Connection #0 to host 9.112.245.103 left intact

========================================================
[root@pe103 ~]# istioctl authn tls-check search.default.svc.cluster.local
HOST:PORT                                 STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
search.default.svc.cluster.local:3738     OK         HTTP       HTTP       -                -

**Comment by lubinson** [comment] 2018-11-26 18:33
@vadimeisenbergibm Sorry, not have change to try again after latest reply to you. Will try again these several days.

**Comment by kongyi-ibm** [comment] 2018-11-27 04:08
@vadimeisenbergibm the TLS PASSTHROUGH can works on my environment.  Thanks!

But I just wondering If there have any other approach which is most like ( enable secret backend on ingress) to terminate TSL at ingressgateway (At Front ) and send https to backend https service

**Comment by lubinson** [comment] 2018-12-02 16:54
@vadimeisenbergibm 

This time succeed! I don't know what happened. I think most prossibly is the sidecar injection. Last time maybe I forget to inject it again after server times try. ~~ 

Another question is I want to confirm the messages between ingressgateway and service is using http/2. Then I dump the tcp packets. But the packets can't be decode into http messages using wireshark which is ok for direct service calling and packets between test client and ingressgateway.

Thanks.

**Comment by vadimeisenbergibm** [comment] 2018-12-03 02:52
@kongyi-ibm Yes, terminating TLS and originating TLS by the gateway should work. You just create  a DestinationRule to your service, and specify `tls` mode as SIMPLE. Something like:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-my-service
spec:
  host: myservice
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS
```

**Comment by vadimeisenbergibm** [comment] 2018-12-03 02:55
@lubinson Since currently it works for you, could you please close the issue?

Regarding http2, note that you have to specify the port name as `http2-<some suffix>`, e.g. `http2-myport`, so Istio will know to treat it as HTTP2. See https://istio.io/docs/setup/kubernetes/spec-requirements/.

**Comment by lubinson** [comment] 2018-12-03 08:37
@vadimeisenbergibm 

actually http/1.1 also has the same problem. I will try your confuration later. thanks.

**Comment by lubinson** [comment] 2018-12-03 16:02
@vadimeisenbergibm 

I tried add Gateway to http2, http2-api, http. And I also changed my service yaml port name to http2, http2-api, http. Results are all the same, istio use plan tcp to send messages to backend service. 

In the page you refered, is it applied to backend service yaml file or gateway yaml file or both?

Thanks.

**Closed** 2018-12-03 16:24 UTC

**Comment by vadimeisenbergibm** [comment] 2018-12-03 16:55
@lubinson The requirement is for the backend service kubernetes yaml.

Could you please open another issue with your full configuration? Additional question - do you experience the problem for the traffic from the gateway to your service, or also for the traffic from some pod to your service?

**Comment by JansonLiao** [comment] 2019-04-09 11:09
@vadimeisenbergibm  My problem is that I have a http2 service in the istio service mesh, I want the external service can approach the http2 service and build the http2 connection. So in this case, I must use the ingress, but I want the ingress do not decode the https packets instead send to the http2 service. the http2 service decode the http2 packet

**Comment by vadimeisenbergibm** [comment] 2019-04-09 16:19
@JansonLiao I think you should configure the ingress gateway not to perform TLS termination, see https://istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/

**Comment by JansonLiao** [comment] 2019-04-10 01:25
@vadimeisenbergibm Thanks, I followed the example, but the traffic can only approach to the ingress, can not reach to my http2 service. The ingress log can see the traffic but the istio-proxy of the http2 service can't see any traffic log.

**Comment by vadimeisenbergibm** [comment] 2019-04-10 06:36
@JansonLiao I would guess something is wrong in your virtual service.

Can you post here your Ingress gateway definition, your virtual service definition, your http2 service spec, and also an example of a curl call to your http2 service from inside the mesh. Please check that your http2 service is accessible from inside the mesh.

**Comment by JansonLiao** [comment] 2019-04-10 08:47
@vadimeisenbergibm I have already solved this problem, the reason is that the port name of my http2 service must consistent with the gateway's port  protocol, but I ignored it. Just like this: 
https://istio.io/docs/setup/kubernetes/prepare/requirements/
Really thanks for your help.

**Comment by kish3007** [comment] 2019-04-12 19:29
@vadimeisenbergibm My app-service is running on https port(443), I have my gateway for port 443 with tls.mode simple and I have http routes defined in virtualservice,  as per your instructions i added `apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-my-service
spec:
  host: myservice
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS` i still got the 503 error `upstream connect error or disconnect/reset before headers`,  can you help?

**Comment by vadimeisenbergibm** [comment] 2019-04-13 10:07
@JansonLiao You are welcome!

**Comment by vadimeisenbergibm** [comment] 2019-04-13 10:10
@kish3007 Please note that in the TLS passthrough mode you cannot use `http` routes, you can only use `tls`, see https://istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/#configure-an-ingress-gateway.

Also note that the traffic is TLS, Istio does not see the encrypted HTTP traffic, so Istio does not show it as HTTP in the dashboard.

**Comment by kish3007** [comment] 2019-04-13 13:09
Are there any solutions to monitor the TLS traffic in mesh dashboard or any other dashboards? Thanks

**Comment by kish3007** [comment] 2019-04-17 16:48
@vadimeisenbergibm is there a different approach we can take to get the HTTP metrics for tls enabled applications?

**Comment by JagadeeshSreeram** [comment] 2019-04-19 16:54
@vadimeisenbergibm  Thanks for above explanation of how to expose https service via ingress gateway. We have challenge where in mesh we have both  https and http services and we want to expose these services via istio ingress via a single ingress port.  I am not able to define a VirtualService and gateway that can handle this combination. Can you pls help?

**Comment by vadimeisenbergibm** [comment] 2019-04-21 06:52
@JagadeeshSreeram You can do it if you expose the services via different URLs. 

I followed:
1. https://istio.io/docs/tasks/traffic-management/secure-ingress/mount/#configure-a-tls-ingress-gateway-with-a-file-mount-based-approach to expose an HTTP service as `httpbin.example.com`
1. https://istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/ to expose an HTTPS service as `nginx.example.com`.

These examples work together, you just define two sets of Gateways/Virtual Services per hostname.

**Comment by vadimeisenbergibm** [comment] 2019-04-21 07:20
@kish3007 Sorry, I did not see your questions.

Regarding the TLS services - I checked and it looks like neither Grafana nor Kiali show TLS services. If so, it seems that in order to monitor a service and to collect HTTP metrics on it, you have to perform TLS termination by the ingress gateway, and then to perform TLS origination again on the route from the ingress gateway to the service. For that, you have to mount the service certificate/private key in the ingress gateway pod which is not ideal, or to use [Secret Discovery Service](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/). 

Alternatively, you can change the HTTPS service to become an HTTP one, let the ingress gateway perform TLS termination, and use Istio mutual TLS to encrypt the traffic to the service inside the mesh.

**Comment by JagadeeshSreeram** [comment] 2019-04-22 13:59
@vadimeisenbergibm  Thanks for quick response!   Since this thread is closed , if you want , I can start a new thread or we can use this thread here https://github.com/istio/istio/issues/12417.    The reason we need a workaround to support SSL service is because of issue #12417.   Today we are exposing all our service through single ingress gateway in production and if possible want to keep it that way.  All  our services are non-ssl  and we use istio to enable mTLS within mesh between all services and ingress calls . In ingress we route to right service based on URL prefix , but sni looks like we can't do that and we can't mix tls with non tls request in one VirtualService. Having two different FQDN's will be complex for us at this time. So, if you look at #12417 and suggest any reasonable workaround that will be helpful?

**Comment by vadimeisenbergibm** [comment] 2019-04-22 14:09
@JagadeeshSreeram Without going into details of #12417, let me understand what you describe here.

> All our services are non-ssl. 

If so, Istio Ingress Gateway can perform TLS termination, as described in https://istio.io/docs/tasks/traffic-management/secure-ingress/mount/#configure-a-tls-ingress-gateway-with-a-file-mount-based-approach. You then will be able to route the requests based on the URL path, as in the example.

**Comment by JagadeeshSreeram** [comment] 2019-04-22 14:23
@vadimeisenbergibm  Thx. This is exactly how we deployed in production today i.e. TLS termination at Ingress gateway with all our services being  non-ssl and let istio handle the ssl part.    By doing this we ran into issue that  is described in #12417.  When SSL is enabled for web via ingress the  browser (chrome) negotiates with ingress and uses h2 protocol and our UI service which uses nodejs supports only 1.1 with no-ssl. Now when istio try to convert from h2 to http/1.1 some of the connections hang (sockets on envoy goes to CLOSE_WAIT status) . We don't know yet if its an issue with nodejs or envoy, but looking at thread #12417 we think its envoy.  So, since we can't force ingress proxy to downgrade its protocol from h2 to http/1.1 . We tried enabling h2 on nodejs , but it requires SSl to be enabled and this causes ingress to support ssl service.

**Comment by vadimeisenbergibm** [comment] 2019-04-22 14:35
OK, so the issue is downgrading the protocol from HTTP/2 to HTTP/1.1 by Istio, it is not related to ingress per se. I would propose to rename #12417 to specify that this is the issue, and let's wait for the community to answer it. I do not know if this downgrading is possible.

**Comment by axsaucedo** [comment] 2020-06-23 15:33
@vadimeisenbergibm is there any way within istio to allow for setting up TLS passthrough but having a re-write rule? If not do you know if this is in the roadmap?

**Comment by vadimeisenbergibm** [comment] 2020-06-23 15:35
@axsaucedo I do not know, sorry.

**Comment by axsaucedo** [comment] 2020-06-23 17:33
Thank you for the propt reply @vadimeisenbergibm ! We found that the best practice to achieve this properly would be with mTLS, namely by referencing the certificate for the running service, although we've run into another issue which we opened via #24908

**Comment by bjwyun** [comment] 2020-09-11 09:58
@vadimeisenbergibm I follow your example of https://istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/  and it works well. but I can't get any trace in Jaeger and also no istio-ingressgateway node in kiali graph, do you have any ideas of this case ? thanks.
I use OCP 4.3 and service mesh operator 1.1.7 for setup istio.

**Comment by houshym** [comment] 2021-09-14 01:16
@vadimeisenbergibm 
Hi 
would you please add example to istio document for  SSL termination at ingress and SSL originatin at gateway to  https service. I tried many config but I could run just one scenario
1- GATEWAY SSL termination (SIMPLE)
2- Virtual service http and not tls
3- DR tls mode : SIMPLE
4- PA : Permessive.  
I expect that PA STRICT must work but it does not work. I think add this scenario to https://istio.io/latest/docs/ops/common-problems/network-issues/#tls-configuration-mistakes will be useful
