### ISSUE TITLE
UDP protocol support 

### ISSUE THREAD

**Issue by dengqian** [istio/istio#25730] opened 2020-07-22 02:47 UTC
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We are using Mosn as data plane and added udp_proxy feature to Mosn. So I want to know can istio support transport protocol config in LDS and udp_proxy CRD, or if there is any plan to support it? Thanks a lot.

**Comment by esnible** [comment] 2020-07-22 17:47
Closing as a duplicate of https://github.com/istio/istio/issues/1430

**Closed by esnible** 2020-07-22 17:47 UTC
