### ISSUE TITLE
Add Global Default Setting for DestinationRule TrafficPolicy

### ISSUE THREAD

**Issue by ethernoy** [istio/istio#38340] opened 2022-04-12 03:57 UTC
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Right now only `LocalityLoadBalancerSetting` in `DestinationRule` has a global default field in the global `MeshConfig`. I suggest we add the entire `TrafficPolicy` in the `MeshConfig` to act as a global default setting.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I am very happy to submit a PR on this improvement, but I will need some instructions :)

**Comment by GregHanson** [comment] 2022-04-12 14:40
duplicate of / related to https://github.com/istio/istio/issues/38242

**Closed by GregHanson** 2022-04-12 14:40 UTC
Labels: kind/enhancement, area/networking
