### ISSUE TITLE
Not able to see any traces from my req in jaeger

### ISSUE THREAD

**Issue by linsun** [istio/istio#16985] opened 2019-09-10 21:46 UTC
**Bug description**

When using the demo profile which has trace sampling 100% configured, I'm not seeing any trace spans from my req in jaeger.  The only trace spans I saw are from user Prometheus, nothing from my browsers.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
See correlated trace spans for each request

**Steps to reproduce the bug**

Deploy an app that worked in 1.2, then move to 1.3 rc 3.

I believe @BrianAvery also tried book info and hit the same issue.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3 RC 3

**How was Istio installed?**
demo profile

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud KS.

**Comment by brian-avery** [comment] 2019-09-10 22:00
I ran into the same issue with Bookinfo.

**Comment by bianpengyuan** [comment] 2019-09-10 22:21
The problem is related to tracing sample rate actually. Even demo profile set it to 100, it still sampled effectively at 1%. Still investigating why tracing rate is not effectively enforced..

**Comment by bianpengyuan** [comment] 2019-09-10 23:25
Looks like it was a behavior change in envoy: https://github.com/envoyproxy/envoy/pull/6986, specifically https://github.com/envoyproxy/envoy/pull/6986/files#diff-c68454405a6c92916edd63682d33246fL234

**Comment by bianpengyuan** [comment] 2019-09-10 23:36
@objectiser Any idea about this?

**Comment by rlenglet** [comment] 2019-09-11 14:34
@bianpengyuan can we close this issue? All the PRs got merged into `release-1.3` branches?

**Comment by bianpengyuan** [comment] 2019-09-11 14:44
We still need to fix master, and update e2e test to cover this.

**Comment by howardjohn** [comment] 2019-09-20 23:10
@bianpengyuan are you working on getting this into master?

**Comment by bianpengyuan** [comment] 2019-09-20 23:11
Yes, it needs a sha update in proxy and then this repo. It is on the way.

**Comment by howardjohn** [comment] 2019-09-20 23:20
Thanks!

**Comment by howardjohn** [comment] 2019-10-01 23:23
Is this resolved by https://github.com/istio/istio/pull/17403

**Comment by bianpengyuan** [comment] 2019-10-01 23:38
I need to make e2e test less aggressive on retry to prevent this from happening in future.

**Closed** 2019-10-08 20:46 UTC
Labels: area/policies and telemetry
