### ISSUE TITLE
Cronjob run incorrectly with istio

### ISSUE THREAD

**Issue by huikang** [istio/istio#11657] opened 2019-02-11 03:30 UTC
I have a question about running cronjob with istio. I have a cronjob which runs fine without istio; the cronjob has a schedule say every one minute (`*/1 * * * *`).

With istio, the cronjob is triggered once and then stopped. Following is the output of kubectl get pod

```
kubectl get pod
NAME                                   READY     STATUS    RESTARTS   AGE
myapp-sidecar-1549855200-c4f9h           1/2       Running   1          10m
```
If I force delete the pod, and then another pod of the cronjob is launched, but it stays in the same status. Could anyone help to look at this? Thanks.

**Comment by ymesika** [comment] 2019-02-11 06:52
What does your job do?
Which container is crashing? Is it your `myapp` or `istio-proxy`?
Any logs from crashed container?

**Comment by Stono** [comment] 2019-02-11 08:37
Ahhh this is a dupe of the issue I raised: https://github.com/istio/istio/issues/11659 - I've got a little more information on mien so perhaps close this issue?

**Closed** 2019-02-11 14:53 UTC
