### ISSUE TITLE
need Egress rule to git clone using SSH

### ISSUE THREAD

**Issue by prune998** [istio/istio#1296] opened 2017-11-01 12:21 UTC
One of my microservice is cloning an external GIT private repo. As we are using SSH keys for auth, I have to create an Egress rule of type SSH (or GIT) like : 

```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: gitlab-egress-rule
spec:
  destination:
    service: git.myserver.com
  ports:
    - port: 22
      protocol: ssh
```

Any idea how to support this ? 

```
Version: 0.2.10
GitRevision: f27f2803f59994367c1cca47467c362b1702d605
GitBranch: release-0.2
User: sebastienvas@ee792364cfc2
GolangVersion: go1.8
```
Kubernetes on GKE, version 1.7.8

**Comment by prune998** [comment] 2017-11-01 14:57
I wasn't able to git clone using an HTTPS url either...
I reverted using the includeIPRanges trick. it's working, but I'm losing Egress features...

I was also supprised the I had to use an `http://` request on port 443 to be able to reach an `https` website... All this sounds like bad design to me...

**Comment by rshriram** [comment] 2017-11-02 18:04
Egress rules are currently restricted to just http traffic. @vadimeisenbergibm is working on enabling tcp/mongo/redis. 
With regard to the https, I agree that its bad UX. But depending on what you want to leverage in egress, its not possible to use encrypted traffic and take advantage of routing rules as Istio has to be able to look at the headers in order to do something useful (for http). Once the TCP support lands, you can use https for sure, but you will lose out on any routing rule support there.

**Comment by prune998** [comment] 2017-11-02 18:13
I would love to live in a HTTP only world, but it's not the case. (I actually wouldn't love it anyway)
I hope the TCP ingress will cover both HTTPS and SSH... 
Do you have a lot of users that are using routing rules on external (Egress) URLs anyway ? I would love to understand the use case.

Do you have any schedule or issue I could track for TCP Egress ? 

Thanks for the answer.

**Comment by vadimeisenbergibm** [comment] 2017-11-04 18:01
@prune998 The issue is here - https://github.com/istio/istio/issues/1476, I will work on it starting tomorrow.

**Comment by vadimeisenbergibm** [comment] 2017-11-28 20:57
@prune998 The issue is fixed by #1651. Please specify tcp as the protocol in the Egress Rule.

**Closed by vadimeisenbergibm** 2017-11-28 20:57 UTC

**Comment by aroundthecode** [comment] 2018-02-09 14:45
A reference in documentation about default egress rule and how extend them would be really appreciated.

I faced same problem as @prune998 and couldn't find any hint until I landed on this issue (already tuned off istio sidecar on my container meanwhile).
SSH connection is quite common for both remote connection or git so an ad-hoc example is probably worth the case

Some details are provided at /docs/tasks/traffic-management/egress but still report includeIPRanges as the only solution to solve the problem.

**Comment by vadimeisenbergibm** [comment] 2018-02-09 14:58
@aroundthecode Please see this documentation item https://istio.io/docs/tasks/traffic-management/egress-tcp.html, created two days ago.
Please see also this blog post from yesterday - https://istio.io/blog/2018/egress-tcp.html.

**Comment by aroundthecode** [comment] 2018-02-09 15:06
Hi @vadimeisenbergibm thanks for the useful docs reference 👍 

Just one question, is TCP supported in 0.4.0 as well? we had to rollback since 0.5.0 wasn't working properly on our cluster and we are looking forward for 0.5.1

**Comment by vadimeisenbergibm** [comment] 2018-02-09 15:55
@aroundthecode Yes, the TCP egress rules were implemented starting from 0.3.0.

**Comment by MrMil** [comment] 2018-03-29 15:40
Hi.
I have the exact same problem, I need to clone a git repository over SSH from within a kubernetes cluster. I have made this rule:
`apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: allow-ssh-egress
spec:
  destination:
    service: 1.2.3.4/24
  ports:
    - port: 22
      protocol: tcp
`
Obviously without the made up IP range.
For some reason it doesn't work
An identical rule works for port 443 (to allow access to google apis for the python gcs python package)
Am I doing anything wrong?

**Comment by vadimeisenbergibm** [comment] 2018-04-01 06:03
@MrMi lYour egress rule is correct and it works for me on IBM Cloud Container Service. The only issue is that you have to define an egress rule per each CIDR of github.

To test it, perform git SSH test - https://help.github.com/articles/testing-your-ssh-connection/, with -v flag: `ssh -v -T git@github.com`. Check the IP that ssh is accessing and verify that it is handled by one of the egress rules.

In Istio 0.7, Egress Rules will be replaced by the External Services https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html#ExternalService. There you will be able to define multiple "hosts" in one rule, specifying multiple CIDR blocks.

**Comment by Hamdan-Atypon** [comment] 2019-03-11 10:47
@vadimeisenbergibm  can i access a container inside the pod using ssh ?

i want to make ansible access a container from the pod

**Comment by vadimeisenbergibm** [comment] 2019-03-11 17:18
@Hamdan-Atypon I think you can, you have to define a service on port 22, and set the name of the port to be of the form `tcp-<something>`, for example `tcp-ssh`.

**Comment by Hamdan-Atypon** [comment] 2019-03-12 08:46
@vadimeisenbergibm i managed to, thanks for the hint.
`
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
 name: sshd
spec:
 hosts:
 - <Host to Access>
 ports:
 - number: 22
   name: ssh
   protocol: tcp
`

**Comment by vadimeisenbergibm** [comment] 2019-03-12 09:40
@Hamdan-Atypon Is the host an internal host inside Kubernetes cluster? If so, you just need to define a Kubernetes Service, no need in Istio's ServiceEntry.

**Comment by Hamdan-Atypon** [comment] 2019-03-12 11:33
yes it is, i want to access specific pod, not through service ..
it's an SSH connection between 2 pods from 2 different services

**Comment by vadimeisenbergibm** [comment] 2019-03-12 11:55
OK, I see.

**Comment by Hamdan-Atypon** [comment] 2019-03-17 09:39
@vadimeisenbergibm ,

How can allow all ingress egress traffic between all the pods in the cluster? all internal communication ?

this option did not helped at all : 
--set global.proxy.includeIPRanges="10.0.0.1/8"

**Comment by vadimeisenbergibm** [comment] 2019-03-17 13:42
@Hamdan-Atypon All the traffic between all the pods is allowed by default for any Kubernetes service.

**Comment by Hamdan-Atypon** [comment] 2019-03-17 13:55
@vadimeisenbergibm well the envoy is dropping my connection ..

![image](https://user-images.githubusercontent.com/43438708/54492199-0e7bca00-48cd-11e9-90f7-7a86425f1fdf.png)

**Comment by vadimeisenbergibm** [comment] 2019-03-17 17:51
@Hamdan-Atypon Did you define a Kubernetes service for 10.19.75.49, port 50000 ?

**Comment by Hamdan-Atypon** [comment] 2019-03-18 08:18
yes, but with no luck

also i don't want it to be specific per IP, i want an IP range to allow all there ports ..
I've tried the annotations for exclude InBound and OutBound but nothings work

@vadimeisenbergibm

**Comment by vadimeisenbergibm** [comment] 2019-03-18 09:12
@Hamdan-Atypon What is your service definition?

**Comment by Hamdan-Atypon** [comment] 2019-03-18 09:27
@vadimeisenbergibm  i am not using them as a service, i need the pods to communicate directly as a cluster, without reaching for the service ..

i have tried this just for debugging, and i could not even telnet from inside the same pod on that port ..

``` bash
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cluster-comm
spec:
  hosts:
  - 10.19.75.49
  ports:
  - number: 50000
    name: cluster-comm
    protocol: tcp
```

what i need is that the pods can communicate on port 50000 (there will be a lot of pods)

**Comment by vadimeisenbergibm** [comment] 2019-03-18 09:31
@Hamdan-Atypon Note the Istio requirements for pods and services: https://istio.io/docs/setup/kubernetes/spec-requirements/

The port name must be `tcp-<some suffix>`.

**Comment by Hamdan-Atypon** [comment] 2019-03-18 09:41
@vadimeisenbergibm nice,

can i add a range in the hosts part not a single ip ?

**Comment by vadimeisenbergibm** [comment] 2019-03-18 11:52
@Hamdan-Atypon Oh, sorry, I meant you should define a Kubernetes Service - https://kubernetes.io/docs/concepts/services-networking/service/, not an Istio Service Entry.

**Comment by Hamdan-Atypon** [comment] 2019-03-18 15:09
why ? i don't need a service :( 
the communication should take place between all pods, directly, not through service (which will make load balancing, roundrobin)

**Comment by vadimeisenbergibm** [comment] 2019-03-18 15:24
But the pods' IPs are temporary, I mean pods can come and go any time and get new IPs.

**Comment by umomany** [comment] 2019-03-20 09:08
@vadimeisenbergibm, regarding of what @Hamdan-Atypon is talking about; the problem happens when using istio as a mid level of communication between applications (micro-services); for each deployment (one application) the pods behind its proxy fail to communicate with each other 
for example the pods of a java application that is deployed behind istio proxy can't communicate with each other for an inside cluster transactions 
now how to make this connection possible between these pods ?

**Comment by vadimeisenbergibm** [comment] 2019-03-20 09:27
@umomany As far as I know, the correct way for the pods to communicate with each other on Kubernetes is via Kubernetes services. So you have to define a Kubernetes service for your pods and then the communication between the pods will work with Istio.

Note that Istio will perform its own load-balancing between the pods of a Kubernetes Service, bypassing the tube-proxy and accessing the pods directly.
