### ISSUE TITLE
`istioctl manifest apply --set profile=demo` has proto: tag has too few fields: "-" warning

### ISSUE THREAD

**Issue by ericvn** [istio/istio#21214] opened 2020-02-18 15:40 UTC
**Bug description**
 `istioctl manifest apply --set profile=demo` yields a proto: tag has too few fields: "-" warning

```
istioctl manifest apply --set profile=demo 

proto: tag has too few fields: "-"
- Applying manifest for component Base...
...
```

**Expected behavior**

No **proto: tag has too few fields: "-"** error

**Steps to reproduce the bug**

Build `istioctl` on either the release-1.5 branch or master

Run istioctl manifest apply --set profile=demo 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
commit 3892338c1f9d9add4c9f45c0b7c00ddc2d36899c (HEAD -> release-1.5, upstream/release-1.5)

commit 88b0085faa96377c9705fac44276826344b609f2 (HEAD -> master, upstream/master, origin/master, origin/HEAD)

**How was Istio installed?**

istioctl built locally
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by johnma14** [comment] 2020-02-18 15:46
https://github.com/istio/operator/pull/735

**Comment by ericvn** [comment] 2020-02-18 15:46
I also see this on `1.5.0-beta.2`

**Comment by linsun** [comment] 2020-02-18 16:44
https://github.com/kubernetes/kubernetes/issues/86739

**Comment by linsun** [comment] 2020-02-18 16:45
same, i'm seeing it with latest master.

**Comment by esnible** [comment] 2020-02-20 20:56
Closing as a duplicate of https://github.com/istio/istio/issues/19735 .

**Closed by esnible** 2020-02-20 20:56 UTC
Labels: area/environments
