### ISSUE TITLE
All sidecars reported 503 “ no healthy upstream ” for egress cluster

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#10515] opened 2018-12-17 07:28 UTC
**Describe the bug**
{{ Succinctly describe the bug }}

the istio cluster run well for serveral days, however yesterday all sidecar report 503 error"no healthy upstream" for egress clusters suddenly.

sidecar logs:
```
[2018-12-17T07:32:46.204Z] "GET /HTTP/1.1" 503 UH 0 19 0 - "-" "curl/7.52.1" "90268738-bcc8-4990-94ff-3b122f58564d" "test.xxx.com" "-" - - 123.125.115.110:80 10.40.190.180:59570
```

the sidecar could receive the xds config and the config downloaded from "istioctl pc xxx" is also synced.
i exec command "istioctl pc endpoint podxxx", the host are all registry host, found no egress host.
meanwhile the new pod have all the host that can work well

i checked the pilot logs and founded three types of warn logs:
1)the logs occured before the first 503 error occured  randomly, and disappeared after this up to now.
```
2018-12-16T03:59:31.130793Z	warn	ads	LDS: overlap sidecar~10.40.191.181~data-consumer-845cf66b98-h28cg.data~data.svc.cluster.local-3 2018-12-16T03:59:25Z/125344 2018-12-16T03:59:29Z/125346
2018-12-16T03:59:31.133710Z	warn	ads	LDS: overlap sidecar~10.40.192.171~data-consumer-845cf66b98-vsrjk.data~data.svc.cluster.local-2 2018-12-16T03:59:25Z/125344 2018-12-16T03:59:29Z/125346
```
2)the logs occured randomly
```
2018-12-16T04:10:26.878690Z	error	Failed to update lock: Operation cannot be fulfilled on configmaps "istio-ingress-controller-leader-istio": the object has been modified; please apply your changes to the latest version and try again
2018-12-16T04:10:41.892364Z	error	Failed to update lock: Operation cannot be fulfilled on configmaps "istio-ingress-controller-leader-istio": the object has been modified; please apply your changes to the latest version and try again
```
3)the log occured randomly
```
2018-12-16T03:59:56.112690Z	warn	Omitting listener for management address 10.40.191.181_8080 ({%!s(*core.Address_SocketAddress=&{0xc420b33a40})}) due to collision with service listener 10.40.191.181_8080 ({%!s(*core.Address_SocketAddress=&{0xc42034f840})})
2018-12-16T03:59:56.117768Z	warn	Omitting listener for management address 10.40.192.171_8080 ({%!s(*core.Address_SocketAddress=&{0xc4209e8500})}) due to collision with service listener 10.40.192.171_8080 ({%!s(*core.Address_SocketAddress=&{0xc42183c380})})
``` 
today the new  pod can work well, however the old pod also report 503...

**Expected behavior**
{{ What did you expect to happen? }}
pod can request the egress cluster well.

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
istio:1.0.3
kubernetes: v1.9.5

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
kubernetes
**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by linsun** [comment] 2018-12-17 16:03
what is the pod/deployment status for your egress, is it possible it is crashed?  Do you have HA configured for your egress deployment?

**Comment by linsun** [comment] 2018-12-17 16:05
@vadimeisenbergibm can you help triage this?

**Comment by vadimeisenbergibm** [comment] 2018-12-17 20:55
@linsun Sure, will do.

**Comment by wansuiye** [comment] 2018-12-18 02:16
> what is the pod/deployment status for your egress, is it possible it is crashed? Do you have HA configured for your egress deployment?

Thank you for your reply, the egress instance is all healthy and the new pod can receive them. there is no HA configured for the egress instances. we have many egress config and they are all disabled.

**Comment by vadimeisenbergibm** [comment] 2018-12-18 08:51
@wansuiye You are accessing an external service by HTTP, thru an egress gateway, correct?
Could you please configure egress gateway according to https://istio.io/docs/examples/advanced-egress/egress-gateway/#define-an-egress-gateway-and-direct-http-traffic-through-it and see if it works? Alternatively, can you publish your existing egress configuration?

Additional diagnosing steps, if you can publish the output here:
```
bin/istioctl proxy-config listeners <your client pod> -n <your namespace> -o json
bin/istioctl proxy-config clusters  <your client pod> -n <your namespace> -o json
kubectl -n istio-system logs -l istio=pilot -c discovery
```

**Comment by wansuiye** [comment] 2018-12-18 11:14
@vadimeisenbergibm hi, we are  accessing services by HTTP/TCP directly, not using a egress gateway.
today i found something strange: 
The old pod that report error cannot connect to pilot today, so command "istioctl proxy-status pod" only show the new pod. they can connect to pilot yesterday...

And the new pod cannot connect to the new egress that i create today for test， although they can sync the config from pilot and the new egress config can be found from the result of “istioctl proxy-config clusters/route/endpoint newpod”.

Because we have a lot of egress configurations in a production environment, I just paste in only part of the configurations, for which i make minor changes.

the egress configuration:
[egress.txt](https://github.com/istio/istio/files/2690086/egress.txt)

the pilot logs are too much, so i just tail -n 1000, three types of warn logs are randomly occured as mentioned above

**Comment by duderino** [comment] 2018-12-18 19:20
@vadimeisenbergibm please assign a priority to this

**Comment by vadimeisenbergibm** [comment] 2018-12-19 08:39
@duderino Done, assigned P1.

**Comment by vadimeisenbergibm** [comment] 2018-12-19 08:49
@wansuiye So it seems you have two issues:
1. Some pods cannot connect to pilot.
2. Some pods can connect to pilot but cannot connect to an external service.

The problem 2 is a simpler one, so let's debug it first. I propose that you define egress to some public url, e.g. httpbin.org like in https://preliminary.istio.io/docs/tasks/traffic-management/egress/#configuring-istio-external-services, and see if it works. If it does not work, please publish your configuration, the log/listeners/clusters of the sidecar proxy of the pod and the command you use to call the external service.

**Comment by wansuiye** [comment] 2018-12-19 12:10
test the problem 2, it report 404:
```
bash-4.4# curl -v httpbin.org
* Rebuilt URL to: httpbin.org/
*   Trying 34.238.3.58...
* TCP_NODELAY set
* Connected to httpbin.org (34.238.3.58) port 80 (#0)
> GET / HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Wed, 19 Dec 2018 11:56:11 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host httpbin.org left intact
```

sidecar report:
```
[2018-12-19T11:56:11.777Z] "GET /HTTP/1.1" 404 NR 0 0 0 - "-" "curl/7.58.0" "98e7f522-7995-4801-a117-6a7238a91235" "httpbin.org" "-" - - 34.238.3.58:80 10.40.11.183:46330
```

the config is set as the wiki:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
```

the clusters of the proxy:
```
...
httpbin.org                                                    80        -          outbound      STRICT_DNS
instance-id-injector-webhook-svc.default.svc.cluster.local     443       -          outbound      EDS
istio-citadel.istio-system.svc.cluster.local                   8060      -          outbound      EDS
istio-citadel.istio-system.svc.cluster.local                   9093      -          outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local             80        -          outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local             443       -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local            80        -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local            443       -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local            853       -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local            8060      -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local            15011     -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local            15030     -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local            15031     -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local            31400     -          outbound      EDS
istio-pilot.istio-system.svc.cluster.local                     8080      -          outbound      EDS
istio-pilot.istio-system.svc.cluster.local                     9093      -          outbound      EDS
istio-pilot.istio-system.svc.cluster.local                     15010     -          outbound      EDS
istio-pilot.istio-system.svc.cluster.local                     15011     -          outbound      EDS
istio-policy.istio-system.svc.cluster.local                    9091      -          outbound      EDS
istio-policy.istio-system.svc.cluster.local                    9093      -          outbound      EDS
istio-policy.istio-system.svc.cluster.local
...
```

the endpoint of the proxy:
```
...
10.40.11.184:9093       HEALTHY     outbound|9093||istio-pilot.istio-system.svc.cluster.local
10.40.11.184:15010      HEALTHY     outbound|15010||istio-pilot.istio-system.svc.cluster.local
10.40.11.184:15011      HEALTHY     outbound|15011||istio-pilot.istio-system.svc.cluster.local
10.40.11.226:20001      HEALTHY     outbound|20001||kiali.istio-system.svc.cluster.local
10.40.11.229:8088       HEALTHY     outbound|8088||servicegraph.istio-system.svc.cluster.local
10.40.12.132:443        HEALTHY     outbound|443||instance-id-injector-webhook-svc.default.svc.cluster.local
10.40.12.170:80         HEALTHY     outbound|80||istio-egressgateway.istio-system.svc.cluster.local
10.40.12.170:443        HEALTHY     outbound|443||istio-egressgateway.istio-system.svc.cluster.local
10.40.12.226:3000       HEALTHY     outbound|3000||grafana.istio-system.svc.cluster.local
10.40.12.227:9091       HEALTHY     outbound|9091||istio-telemetry.istio-system.svc.cluster.local
10.40.12.227:9093       HEALTHY     outbound|9093||istio-telemetry.istio-system.svc.cluster.local
10.40.12.227:15004      HEALTHY     outbound|15004||istio-telemetry.istio-system.svc.cluster.local
10.40.12.227:42422      HEALTHY     outbound|42422||istio-telemetry.istio-system.svc.cluster.local
12.168.254.97:15010     HEALTHY     xds-grpc
12.168.255.162:9411     HEALTHY     zipkin
52.54.84.112:80          HEALTHY     outbound|80||httpbin.org
52.71.139.107:80         HEALTHY     outbound|80||httpbin.org
52.72.145.109:80         HEALTHY     outbound|80||httpbin.org
52.72.245.79:80          HEALTHY     outbound|80||httpbin.org
52.73.9.93:80            HEALTHY     outbound|80||httpbin.org
52.73.94.166:80          HEALTHY     outbound|80||httpbin.org
52.87.35.92:80           HEALTHY     outbound|80||httpbin.org
54.152.127.232:80        HEALTHY     outbound|80||httpbin.org
...
```

**Comment by vadimeisenbergibm** [comment] 2018-12-19 14:53
@wansuiye The listener looks OK, according to the log of the proxy the request was successfully forwarded to 34.238.3.58 which is an IP of httpbin.org. Could it be that you have some firewall that blocks traffic to httpbin.org? Can you run the same curl command from the proxy? You are using Istio 1.0.3, right?

**Comment by wansuiye** [comment] 2018-12-20 00:54
@vadimeisenbergibm  from the proxy, the command return 200, other new egress are also can not be accessed by the the pod, so it's not the problem of environment. 
``` 
istio-proxy@dj-dispatcher:/$ curl -v "httpbin.org"
* Rebuilt URL to: httpbin.org/
*   Trying 52.201.75.180...
* Connected to httpbin.org (52.201.75.180) port 80 (#0)
> GET / HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Date: Thu, 20 Dec 2018 00:48:32 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 10122
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Via: 1.1 vegur
< 
<!DOCTYPE html>
<html lang="en">

<head>
```
yeah, i'm using istio 1.0.3

**Comment by vadimeisenbergibm** [comment] 2018-12-20 08:36
@wansuiye I checked the meaning of  "NR" in the proxy log - it means that the request was not routed, my mistake, sorry.

So the problem is that the routing was somehow not performed, the listener definition you pasted did not take effect.

There is something in listeners' definition that confuses Envoy and it does not perform the routing, maybe some conflict on port 80.

Can you run `grep '_80"' listeners.json | grep name` where listeners.json is the output of `istioctl proxy-config listeners -o json` ?

Do you see maybe some conflicting listeners on port 80? 

Additional check is to check the statistics of the proxy: run 
`curl localhost:15000/stats | grep -v ": 0" | grep -v 'No recorded values' | grep -v P0 | grep listener | grep '_80.'`

then run your failing curl to httpbin.org, rerun the statistics and see which counter increases. If no counter was increased, repeat the same with the following statistics command:
`curl localhost:15000/stats | grep -v ": 0" | grep -v 'No recorded values' | grep -v P0`.

**Comment by wansuiye** [comment] 2018-12-20 13:06
@vadimeisenbergibm  hi, there are several 80 listener.
```
istioctl pc listeners dj-dispatcher-588d35e-deploy-2018-12-06t17-40-47-c7clhnk -o json|grep '_80\"'|grep name
        "name": "192.168.255.76_80",
        "name": "10.40.24.16_80",
        "name": "0.0.0.0_80",
```
and the counter: "listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_4xx" is increased by the test request. several other listener are also increased by the test request and other request:
```
bash-4.4# curl localhost:15000/stats | grep -v ": 0" | grep -v 'No recorded values' | grep -v P0 | grep listener | grep '_80.'
listener.0.0.0.0_80.downstream_cx_destroy: 9830
listener.0.0.0.0_80.downstream_cx_total: 9830
listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_2xx: 9730
**listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_4xx: 49**
listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_5xx: 51
listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_completed: 9830
listener.0.0.0.0_8000.downstream_cx_active: 1
listener.0.0.0.0_8000.downstream_cx_destroy: 1
listener.0.0.0.0_8000.downstream_cx_total: 2
listener.0.0.0.0_8000.http.0.0.0.0_8000.downstream_rq_2xx: 17880
listener.0.0.0.0_8000.http.0.0.0.0_8000.downstream_rq_completed: 17880
listener.0.0.0.0_8086.downstream_cx_destroy: 1
listener.0.0.0.0_8086.downstream_cx_total: 1
listener.0.0.0.0_8086.http.0.0.0.0_8086.downstream_rq_2xx: 1
listener.0.0.0.0_8086.http.0.0.0.0_8086.downstream_rq_completed: 1
listener.10.40.19.183_8080.downstream_cx_active: 1222
listener.10.40.19.183_8080.downstream_cx_destroy: 146931
listener.10.40.19.183_8080.downstream_cx_total: 148153
listener.10.40.19.183_8080.http.10.40.19.183_8080.downstream_rq_2xx: 480320
listener.10.40.19.183_8080.http.10.40.19.183_8080.downstream_rq_4xx: 2
listener.10.40.19.183_8080.http.10.40.19.183_8080.downstream_rq_5xx: 1708
100  978k    0  978k    0     0  20.7M      0 --:--:-- --:--:-- --:--:-- 20.7M
listener.10.40.19.183_8080.http.10.40.19.183_8080.downstream_rq_completed: 482030
listener.10.40.24.16_80.downstream_cx_active: 1
listener.10.40.24.16_80.downstream_cx_destroy: 9950
listener.10.40.24.16_80.downstream_cx_total: 9951
```
```
listener.0.0.0.0_80.downstream_cx_total: 9834
listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_2xx: 9733
**listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_4xx: 50**
listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_5xx: 51
listener.0.0.0.0_80.http.0.0.0.0_80.downstream_rq_completed: 9834
listener.0.0.0.0_8000.downstream_cx_active: 1
listener.0.0.0.0_8000.downstream_cx_destroy: 1
listener.0.0.0.0_8000.downstream_cx_total: 2
listener.0.0.0.0_8000.http.0.0.0.0_8000.downstream_rq_2xx: 17882
listener.0.0.0.0_8000.http.0.0.0.0_8000.downstream_rq_completed: 17882
listener.0.0.0.0_8086.downstream_cx_destroy: 1
listener.0.0.0.0_8086.downstream_cx_total: 1
listener.0.0.0.0_8086.http.0.0.0.0_8086.downstream_rq_2xx: 1
listener.0.0.0.0_8086.http.0.0.0.0_8086.downstream_rq_completed: 1
listener.10.40.19.183_8080.downstream_cx_active: 1222
listener.10.40.19.183_8080.downstream_cx_destroy: 146984
listener.10.40.19.183_8080.downstream_cx_total: 148206
listener.10.40.19.183_8080.http.10.40.19.183_8080.downstream_rq_2xx: 480322
listener.10.40.19.183_8080.http.10.40.19.183_8080.downstream_rq_4xx: 2
listener.10.40.19.183_8080.http.10.40.19.183_8080.downstream_rq_5xx: 1708
100  977k    0  977k    0     0  20.7M      0 --:--:-- --:--:-- --:--:-- 20.7M
listener.10.40.19.183_8080.http.10.40.19.183_8080.downstream_rq_completed: 482032
listener.10.40.24.16_80.downstream_cx_active: 1
listener.10.40.24.16_80.downstream_cx_destroy: 9953
listener.10.40.24.16_80.downstream_cx_total: 9954
```

**Comment by vadimeisenbergibm** [comment] 2018-12-20 13:32
@wansuiye OK, so we see that the listener 0.0.0.0_80 gets the request as expected. However, it does not manage to route it. Can you paste the listener definition? `istioctl proxy-config listeners -o json` ?

**Comment by wansuiye** [comment] 2018-12-21 05:14
@vadimeisenbergibm  the dump json file as blew:
[listener-test.txt](https://github.com/istio/istio/files/2701589/listener-test.txt)

**Comment by vadimeisenbergibm** [comment] 2018-12-21 08:21
@wansuiye The listeners dump looks correct. The only remaining issue could be with the routes, maybe there is some conflict there. Could you please publish the whole routes file?

**Comment by vadimeisenbergibm** [comment] 2018-12-21 08:47
@wansuiye Additional diagnosing step: run `curl localhost:15000/config_dump` from your pod - this will dump the configuration the envoy sees (as opposing to the configuration that is sent to it by pilot, returned by `istioctl proxy-config`.) Check the listener and the route in the dump.

**Comment by vadimeisenbergibm** [comment] 2018-12-21 09:30
@wansuiye Additional diagnosing step - set the Envoy's logging level to tracing, run the request and examine the log: `curl -X POST localhost:15000/logging?level=trace`

For a request, that is routed correctly, the following message should appear: `cluster 'outbound|80||httpbin.org' match for URL '/`

For a request which fails to be routed: `no cluster match for URL '/'`

**Comment by wansuiye** [comment] 2018-12-26 02:17
@vadimeisenbergibm hi, I'm sorry to reply you so late because I was delayed by other things. 
And the problem that sidecar report 503 i found the reason is that：
If no clusterid is specified for the registry, the registry will use "" as the default.
When running edsupdate, code causes coverage of different registry data.
Meanwhile EndpointShardsByService will also be affected, which will allect the incremental EDS push.
In our actual scene, we added a custom platform adapter(like consul), if no clusterid was specified, would cause the service instance data to be overwritten by the serviceentries at times. whcih is the direct reson. the egress may also be overwritten by the service  instances of the custom platform.
here is the [PR](https://github.com/istio/istio/pull/10621) please review it.

**Comment by vadimeisenbergibm** [comment] 2018-12-26 13:34
@wansuiye So can you resolve this issue? Or is there some other problem that has to be solved?

**Comment by vadimeisenbergibm** [comment] 2018-12-26 16:13
@wansuiye ^  I meant can you close this issue?

**Comment by wansuiye** [comment] 2019-01-10 15:08
ok i will close the issue, and please review the pr or solve the problem in another way, thanks

**Closed** 2019-01-10 15:09 UTC

**Comment by vadimeisenbergibm** [comment] 2019-01-10 15:14
@wansuiye The PR is not in the code that I am familiar with, sorry. Also, note that you have a conflict in the PR.
