### ISSUE TITLE
Istio Mixer help needed - how to scrape application metrics?

### ISSUE THREAD

**Issue by darrenhaken** [istio/istio#5673] opened 2018-05-17 15:28 UTC
**Background**
I have a K8 cluster deployed with Istio which is collecting pod metrics from services which are pushed into Prometheus and rendered in Grafana.

We are running a suite of Java services using Spring Boot which can expose metrics in a Prometheus format and covers metrics like JMX, response time etc. 

We are using [Micrometer](https://github.com/micrometer-metrics/micrometer) with Prometheus as the backend. This exposes a set of the metrics on `{application}/actuator/prometheus`.

We want to monitor our services and get a holistic view of how they are performing.
I can imagine we will also emit custom metrics from our applications based on the domain.

**Problem**
I can see two approaches and I'd like some advice on the best approach:

- Envoy scrapes `{application}/actuator/prometheus`, push the metrics to Mixer which is then scraped by Prometheus. If this is the right way to go how do we do this? Does this matter that not all pods running on the cluster will be JVM and emit these additional metrics?
 
- Prometheus scrapes the application pods directly. This will result in a duplication of metrics from Envoy/Mixer and the application e.g. response time.

**Comment by darrenhaken** [comment] 2018-05-17 17:11
@douglas-reid thanks for getting back to me about it, it definitely helps.

For now, I will go down the route of scraping the applications directly.
Do you know when the Direct API work will be ready? I don't know much about that so if there are any proposed docs I'd be interested to take a look.

You're right, the response time metrics etc could help diagnose any issues present within Envoy by comparing metrics.

**Comment by Stono** [comment] 2018-05-18 13:49
Hey folks, 
We (Darren and I) went down the route of having prometheus scrape the pods, however we have some complexity due to mTLS.

Long story short, in order for prometheus to scrape from the application pods (which are wrapped with mTLS envoys), we had to wrap prometheus in envoy too.

This worked to an extent, and the mTLS connection to the pods succeeded:

<img width="1305" alt="screen shot 2018-05-18 at 14 44 53" src="https://user-images.githubusercontent.com/1486729/40238054-0cde7e98-5aaa-11e8-8fb4-20338597a567.png">

However it's 404ing because the envoy on the app pods is expecting the service hostname.  We've worked around this with services in the past (such as ingress-nginx) by enforcing the upstream-hostname (basically in this scenario - prometheus would set `Host: our-service`), however there is no method of adding arbitrary headers to the request (there [is the option](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) for url parameters however).

I can't see any way around this right now, we can ask prometheus to add support for arbitrary headers too, in the interim I'm wondering if you can think of anything we can do at the istio level, @douglas-reid 

Cheers
Karl

**Comment by kyessenov** [comment] 2018-05-18 14:35
Interesting. The problem is that prometheus is trying to address pods directly (it looks like it resolves services to endpoints). For mTLS to work, prometheus' envoy needs to know which service the pod belongs to. This is why host header is needed, in addition to simply missing a route for the pod in the client-side envoy routing table.

**Comment by Stono** [comment] 2018-05-18 14:48
Yes that was my assumption but then I wasn't able to replicate the expected behaviour with a curl and the headers directly to the pod.

**Comment by kyessenov** [comment] 2018-05-18 14:56
The issue is not server-side envoy but the client-side envoy. I was expecting envoy to change the destination pod IP for the first curl request, since the host header will also pick the upstream for that host (which is where TLS settings reside). @rshriram : do we support a mode of keeping the original destination IP but applying upstream cluster settings?

**Comment by douglas-reid** [comment] 2018-05-18 16:32
@Stono Do you mind posting the prometheus scraping config you were using (for replication purposes)?

If we moved `/metrics` to a different port, I guess you could use annotations like: `auth.istio.io/8081: NONE`, but that seems like a big burden.

I feel like the work being done on liveliness/readiness checks would be applicable here. Unfortunately, I'm not up-to-date on the latest there.

**Comment by Stono** [comment] 2018-05-18 18:13
Sure thing @douglas-reid 

```
    - job_name: 'web-app-pods'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - rate-of-sale-model-service
      metrics_path: /actuator/prometheus
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: http-web
```

The pods have:

```
    ports:
    - containerPort: 8080
      name: http-web
      protocol: TCP
```

**Comment by darrenhaken** [comment] 2018-05-30 07:48
Hey circling back on this, any suggestions on how we might be able to resolve this?
@douglas-reid you mentioned the Direct API work, is there an ETA on that?

**Comment by mkjoerg** [comment] 2018-12-25 14:39
@Stono I am stumbling over the same issue. In my case, I didn't even activate mTLS right now, but prometheus (instantiated by prometheus operator) isn't able to find the actuator endpoint with injected sidecar. If I don't inject the sidecar into the prometheus pod, it can find them without problems. Did you manage to find a solution for this issue?

**Comment by ZhimaoL** [comment] 2019-03-07 19:15
@mkjoerg I also got the same problem when using rc.2. I am wondering have u fixed this?

**Comment by douglas-reid** [comment] 2019-03-07 20:10
@ZhimaoL what issue are you having precisely? I believe the current recommendation is *not* to use a proxy in front of prometheus, but rather have the prometheus pod mount the certs. This gets more complicated with the operator, etc., but with simple pod annotations, prom scraping of application metrics should be working in 1.1.

Please see: https://preliminary.istio.io/help/faq/metrics-and-logs/#prometheus-application-metrics

**Comment by chrisob** [comment] 2019-03-08 14:41
So does this mean that it's not possible to have a sidecar-injected Prometheus pod scrape Istio metrics via mTLS?

**Comment by douglas-reid** [comment] 2019-03-08 17:05
@chrisob sidecar-injected Prometheus isn't supported at this time. IIRC, there are issues around how prom addresses endpoints, etc., that need to be resolved. That's why support was added directly to our prom add-on via `tls_config` and mounting of the certs. 

If you desire sidecar-injection for Prometheus itself, please file a separate issue for discussion, etc.,

**Comment by douglas-reid** [comment] 2019-05-31 18:41
Closing, reflecting the updates that have been made to enable application metrics scrapping. Separate issues for sidecar injection of Prometheus should be opened as needed.

**Closed by douglas-reid** 2019-05-31 18:41 UTC
Labels: area/policies and telemetry, kind/customer issue
