### ISSUE TITLE
Pilot OOM cause envoy return 503 NR

### ISSUE THREAD

**Issue by ethanhanjiahao** [istio/istio#25495] opened 2020-07-14 12:49 UTC
**Bug description**
In our scenes, we use envoy as gateway， pilot as the controller.
Recently，cause of ram pilot OOM. At the same time, envoy return 503 and the response flag is NR.
In envoy log ,we find no cluster
![image](https://user-images.githubusercontent.com/10829448/87427089-d1cff800-c612-11ea-93f7-7d53a4868b40.png)
when pilot restarting , the route is ok, and return 200.

**Expected behavior**
How to avoid this scenes, when pilot OOM restart， not affect envoy route. 

**Steps to reproduce the bug**

**Version **
we use istio: 1.4
envoy: 1.12

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment] 2020-07-14 21:50
Was the route that is 503ing actively changing? Ie a new service or virtual service or something is created then pilot OOM shortly after?

**Comment by ethanhanjiahao** [comment] 2020-07-15 01:44
> Was the route that is 503ing actively changing? Ie a new service or virtual service or something is created then pilot OOM shortly after?

Before pilot OOM, the route is ok.  But i found some ads pushing at the same time pilot OOM.

**Comment by howardjohn** [comment] 2020-07-15 01:46
so it pushes some bad config then it crashes? can you provide. more info like logs and how much memory is used

**Comment by howardjohn** [comment] 2020-07-15 01:46
Also please be aware of https://istio.io/latest/news/support/announcing-1.4-eol-final/

**Comment by ethanhanjiahao** [comment] 2020-07-15 02:26
> so it pushes some bad config then it crashes? can you provide. more info like logs and how much memory is used

Cause of endpoint changing，pilot OOM. At the same time, envoy return some 503 route. memory is 8G.
I can got crashing pilot logs,
![image](https://user-images.githubusercontent.com/10829448/87496174-a0444480-c685-11ea-8d9a-7531d9e8badc.png)

**Comment by howardjohn** [comment] 2020-07-15 14:33
Can you upgrade Istio? Even if we find a bug in Istio 1.4 we won't fix it, and we have made *tons* of performance optimizations since then

**Comment by howardjohn** [comment] 2020-07-15 14:33
and see https://github.com/istio/istio/wiki/Analyzing-Istio-Performance

**Comment by caitong93** [comment] 2020-07-21 13:00
Hi, I'm colleague of @ethanhanjiahao . we have reproduced that pilot send bad config to envoy, it is similar to https://github.com/istio/istio/issues/20295 .  

To make it easier to reproduce, we disable pilot GC to simulate OOM and set pilot replicas to 1, set initial readiness probe delay seconds to 60s .

The timeline is as following:

07:16:46 pilot OOM , config grpc closed , envoy first try to reconnect failed, envoy second try to connect failed
07:16:47 pilot container started
07:16:49 envoy reconnect success
07:16:51 pilot pod ip removed from iptables
07:18:23 pilot pod ready

There is a high latency between pilot pod crash and iptables update ( 07:16:46 ~ 07:16:51 , due to kube-proxy cpu throttle), so even if pilot is not ready, envoy can connect to pilot.

Istio version is 1.2 , there is [an option](https://github.com/istio/istio/blob/1.2.0/pkg/features/pilot/pilot.go#L131) to let grpc server start after cache synced, but it is not enabled in our deploy. So envoy can establish connection to pilot even if pilot is not ready.

My concern is pilot should not assume readiness probe is always reliable. seeing from [master](https://github.com/istio/istio/blob/a9086ccfb9923f25035df02f77716e46d5fe3c9f/pilot/pkg/bootstrap/server.go#L348), there is no guarantee for that.

@howardjohn 

following is packets captured during envoy reconnect

<img width="1407" alt="Screen Shot 2020-07-20 at 3 36 04 PM" src="https://user-images.githubusercontent.com/5698045/88057283-74005a80-cb94-11ea-8e20-69b241aa4147.png">

**Comment by howardjohn** [comment] 2020-07-21 14:05
Thanks for the findings! @ramaraochavali I thought you had some code for  this, did it get lost?

**Comment by ramaraochavali** [comment] 2020-07-21 14:13
No. There we have only handled the case for local Envoy by pushing https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/server.go#L362 and relying on readiness probes for other Envoys?

There are two issues I see here
- In Istiod we do not have a check in readiness probe that validates caches have been synced. It is easy to add that.
- Based on the above description, it looks like  even if add cache sync to readiness probe - Envoys still might connect. I think we should reconsider this PR https://github.com/istio/istio/pull/20296 (which we have reverted in-favour of relying on readiness probes) which rejects connections till caches have been synced.

WDYT? 
If we agree with that approach, I can push a PR to cover both.

**Comment by howardjohn** [comment] 2020-07-21 14:25
Yeah sounds reasonable to reject connections. Note: our syncing is still
broken a bit, see https://github.com/istio/istio/pull/24339

**Comment by ramaraochavali** [comment] 2020-07-21 14:27
Ok. I will take a look and push a PR then

**Comment by ramaraochavali** [comment] 2020-07-24 07:39
This https://github.com/istio/istio/pull/25733 should address this. Please let us know if there are any open issues. I am closing this issue.

**Closed by ramaraochavali** 2020-07-24 07:39 UTC
Labels: lifecycle/needs-triage
