### ISSUE TITLE
destination.uid and source.uid in rules for templates with `TEMPLATE_VARIETY_CHECK`

### ISSUE THREAD

**Issue by vosst** [istio/istio#9556] opened 2018-10-26 07:57 UTC
**Describe the bug**
We are deploying our own adapter implementation handling the `apikey` and `authorization` template. For that, we have a rule in place that is meant to trigger if:

 * the source is marked as handling external traffic (label: `handles-external-traffic`, values in {`"true"`, `"false"`})
 * the destination is marked as requiring `apikey` or `authorization` checks (labels: `requires-apikey-check` and `requires-authorization-check`, value range as for `handles-external-traffic`)

Our `match` expression for `apikey` (`authorization` follows the same logic) reads as:
```
(destination.labels["requires-apikey-check"] | "true") == "true" && (source.labels["handles-external-traffic"] | "false") == "true"
```

The expression matches even if a destination is labeled with `"requires-apikey-check": "false"`. Investigating a little further and instrumenting `mixer` reveals that the `Check` call to `mixer` does neither include the `destination.uid` nor the `destination.ip`. With that, our `kubernetesenv` handler fails to generate the relevant attributes, in particular, `destination.labels`.

**Expected behavior**
The expression does not match if a destination is marked with `"requires-apikey-check": "false"`. Alternatively, it would be nice to have `destination.service.labels`. That would allow for modelling policy decisions based on service labels, hence avoiding `proxy` or `mixer` to resolve services to actual IP addresses prior or during `Check` invocations.

**Version**
istio: 1.1.0-snapshot1
k8s: 1.10.2

**Installation**
We rendered the helm chart into a set of yamls and rolled out with `kubectl apply -f`.

**Environment**
MS Azure, but reproducible on local clusters, too.

**Comment by kyessenov** [comment] 2019-01-25 18:22
I don't know if this is still an issue.
There was a problem found in mixer's cache that got resolved and may have been causing some unexpected matches.
If the issue is just missing attributes, then using `(destination.labels | emptyStringMap())` could help. I believe `_ | _ ` is recursive right now. We are trying to change the recursive nature, however, so expect some changes to expression language to make it less confusing.

**Comment by douglas-reid** [comment] 2019-05-31 18:44
Closing, given https://github.com/istio/istio/issues/9556#issuecomment-457670403.

**Closed by douglas-reid** 2019-05-31 18:44 UTC
Labels: area/policies and telemetry
