### ISSUE TITLE
for definitions of struct such as resource AuthorizationPolicy, int type of json:omitempty 

### ISSUE THREAD

**Issue by xcbeyond** [istio/istio#35805] opened 2021-10-30 15:32 UTC
### Bug Description

for definitions of struct such as resource AuthorizationPolicy, int type of json:omitempty is bug：

[AuthorizationPolicy. AuthorizationPolicy_Action](https://github.com/istio/api/blob/master/security/v1beta1/authorization_policy.pb.go#:~:text=Action-,AuthorizationPolicy_Action,-%60protobuf%3A%22varint%2C3)
```go
Action AuthorizationPolicy_Action `protobuf:"varint,3,opt,name=action,proto3,enum=istio.security.v1beta1.AuthorizationPolicy_Action" json:"action,omitempty"`
```

When Action=0(AuthorizationPolicy_ALLOW) is requested or returned, the field does not actually exist, and the value of 0 cannot be set correctly.

So in this case, this should be corrected as follows：
(to remove 'omitempty')
```go
Action AuthorizationPolicy_Action `protobuf:"varint,3,opt,name=action,proto3,enum=istio.security.v1beta1.AuthorizationPolicy_Action" json:"action"`
```

Similarly, when the type is int, bool, and the structure definition should not be set 'omitempty'.

### Version

```prose
client-go sdk current version and all previous versions
```

**Comment by howardjohn** [comment] 2021-10-30 17:14
This is controlled by the protobuf generator afaik and not customizable. I don't see the issue this is causing - setting to empty and setting to the zero-value should be identical?

**Comment by howardjohn** [comment] 2021-10-30 19:20
Also if you use the jsonpb library you can customize it to emit default values

**Comment by xcbeyond** [comment] 2021-10-31 12:52
> This is controlled by the protobuf generator afaik and not customizable. I don't see the issue this is causing - setting to empty and setting to the zero-value should be identical?

@howardjohn hi，setting to the zero-value, the field does not actually exist,but I also want it to return zero-value.

**Comment by howardjohn** [comment] 2021-10-31 14:28
Then use jsonpb and set EmitZeroValues (might not be the exact name, I didn't check the doc).

since this is not an Istio bug and is working as intended I'll close the issue. Thanks!

**Closed by howardjohn** 2021-10-31 14:28 UTC
Labels: kind/need more info

**Comment by xcbeyond** [comment] 2021-11-01 01:28
> Then use jsonpb and set EmitZeroValues (might not be the exact name, I didn't check the doc).
> 
> since this is not an Istio bug and is working as intended I'll close the issue. Thanks!

@howardjohn maybe  this is not an Istio bug, but this is the structure provided by the [API](https://github.com/istio/api/blob/master/security/v1beta1/authorization_policy.pb.go#:~:text=Action-,AuthorizationPolicy_Action,-%60protobuf%3A%22varint%2C3), and it suffers from the problems described above

**Comment by howardjohn** [comment] 2021-11-01 02:20
The output is determined by the protobuf library so even if we wanted to we
couldn't change it. There is a well defined way to emit the zero values in
protobuf jsonpb library.

**Comment by xcbeyond** [comment] 2021-11-01 02:34
@howardjohn 
ok, this is too bad,there are many similar problems in other structures.
