### ISSUE TITLE
Problems with rate limiting task

### ISSUE THREAD

**Issue by Tahler** [istio/istio#5692] opened 2018-05-17 23:41 UTC
The documentation is out of date for 
https://preliminary.istio.io/docs/tasks/policy-enforcement/rate-limiting.html (the prerequisites). The two sample yamls create kinds for istio-ingress, not istio-ingressgateway.

In debugging this, trying to use the new VirtualService and DestinationRule has not yielded successful results. They do not seem to cooperate with the memquota, quota, and rule created in the [task](https://preliminary.istio.io/docs/tasks/policy-enforcement/rate-limiting.html).

**Comment by douglas-reid** [comment] 2018-05-18 16:47
cc: @mandarjog

**Comment by mandarjog** [comment] 2018-05-21 21:41
It turns out that `rate-limits` is not implemented at all in networking alpha3. We should not release 0.8 without completing this feature. It represents a regression for a feature that has been there since 0.1/0.2. Thanks @douglas-reid for helping uncover this. 

@ostromart has sized the effort to about 1 day and has started working on it.

@hklai @jasminejaksic

**Comment by hklai** [comment] 2018-05-21 22:11
@mandarjog any idea why and how tests did not uncover this?

**Comment by mandarjog** [comment] 2018-05-21 22:20
Tests were disabled en-mass in the beginning. Once this implementation was completed it would have been enabled, but it has not been done yet.

**Comment by ldemailly** [comment] 2018-05-21 23:10
IMO we should run all (/most) the v1 tests + conversion tool  - that would test both regressions like this and that there is indeed a working upgrade path from v1 to v2

ps: and also keep v1 tests running for at least 0.8 so we don't break v1

**Comment by rshriram** [comment] 2018-05-23 03:07
what does this have to do with v1alpha3 ? This is mixer config.

**Comment by costinm** [comment] 2018-05-23 03:11
It's a v1alpha3 feature that is implemented by mixer - and is not ready yet, since mixer config format changed (which caused most of the delay and problems). Some parts of v1alpha3 may be incomplete or lack full testing - it's called 'alpha' :-) If it can make it in 0.8 great, if not I think we can document in release notes and do it in 0.8.1. Users who depend on this feature can stick with v1alpha1 until it is ready, that's why we keep both versions in 0.8.

**Comment by kyessenov** [comment] 2018-05-23 03:54
Mixer or pilot, this was a surprise. It is a feature that was available for
over a year, and there was no reason to disable it. Mixer filter config has
not changed, I had a good look at both the code and the API.

**Comment by ostromart** [comment] 2018-05-23 16:37
@kyessenov, the issue is in how mixer client expects to receive the config in v2, it's changed. Check with @qiwzhang for details.
I'm going to take a first pass at it today - other "1 day" issues are battling for attention :-)

**Comment by qiwzhang** [comment] 2018-05-23 16:46
The change is in Pilot.  When Pilot switched to use Envoy v2 config (proto), it did not add the code to fill quota config in.  The quota config only works when using Envoy v1 (json) format.

**Comment by kyessenov** [comment] 2018-05-23 17:04
Martin, mixer client config was moving towards v2 protos for much longer
than this release cycle. The only difference should be that in v1 the
config is under v2 field in the Json struct for http.

**Comment by rshriram** [comment] 2018-05-23 17:08
Which is clunky isn’t it? Given that we are making a clean break from old v1alpha1, can we also clean up the associated configs in Envoy to avoid doing this type of stick v2 config under v1 entry etc ?

**Comment by kyessenov** [comment] 2018-05-23 17:10
What v1 entry? Mixer filter config looks just fine in xDS API compatible
way.

**Comment by qiwzhang** [comment] 2018-05-23 17:59
@rshriram Only in Envoy v1 config (json),  we were using "v1" and "v2" field for the whole HttpClientConfig proto inside the filter config.   In Envoy v2 (proto), we remove "v1" and "v2", use HttpClientConfig proto directly as filter config.

**Comment by kyessenov** [comment] 2018-05-24 06:00
What is the plan regarding QuotaSpec and QuotaSpecBinding in v1alpha3? I don't see any corresponding configuration inputs to pilot. Is the plan to hardcode `requestcount` quota at value 1?

**Comment by hklai** [comment] 2018-05-30 17:57
@ostromart @mandarjog 

Is this fixed last week? Can we close the issue now?

**Comment by ostromart** [comment] 2018-05-30 21:08
Yes, this was resolved through https://github.com/istio/istio/pull/5853.

**Comment by jasmine-jaksic** [comment] 2018-06-01 19:13
Closing the issue...reopen if needed.

**Closed by jasmine-jaksic** 2018-06-01 19:13 UTC
Labels: area/policies and telemetry, kind/blocking release
