### ISSUE TITLE
Evaluate if we can enable rewriteAppHTTPProbe by default

### ISSUE THREAD

**Issue by rvennam** [istio/istio#16785] opened 2019-09-03 20:33 UTC
**Describe the feature request**
To configure health checking with the HTTP request option when mutual TLS is enabled, the doc suggests users to either install Istio with the sidecarInjectorWebhook.rewriteAppHTTPProbe=true Helm installation option, or modify the  sidecar config map
https://istio.io/docs/ops/setup/app-health-check/#probe-rewrite

This is a user experience item that can be improved if is enabled by default. It is currently set to false in the helm default profile. https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/values.yaml#L37

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Comment by incfly** [comment] 2019-10-22 18:52
Duplicate of the https://github.com/istio/istio/issues/10357, thanks! I've updated that bug to take this feedback into +1.

**Closed** 2019-10-22 23:25 UTC
Labels: area/environments, area/user experience, kind/enhancement

**Comment by devtestuseresp** [comment] 2020-03-22 08:21
Hi Enabling that option related to deploy pods,
now after deploy previous pod wasn't terminated but gets status "evicted" and stands to consume resources. That way in short period, depends how often you deploy, you will have lack of resources because of hundreds "Evicted" pods
