### ISSUE TITLE
Istio Standard metrics not coming for HTTPS traffic

### ISSUE THREAD

**Issue by doverk96** [istio/istio#38104] opened 2022-03-24 12:49 UTC
Have Istio Ingress Gateway, sidecars installed in application pods, receiving standard metrics - incoming and outgoing.
Problem here is - It is not showing any request which is coming/going via HTTPS, it only displays for HTTP protocol.

Query: 

1. Does Istio supports giving standard metrics for HTTPS traffic ?
2. Do we need to enable it for HTTPS traffic recording ? 
- If yes, please share some doc link or if a direct applied configuration YAML available, that would be helpful.

-If no, any other way to achieve this ? I want to record in/out requests from/to my Pod/Service on HTTPS protocol. 
@zirain @douglas-reid

**Comment by douglas-reid** [comment] 2022-03-24 16:17
Short answer: No.

HTTPS traffic all the way to the workload instances is not accessible to the proxies. It looks like TCP traffic to proxies (just like it does to any other hops it passes along the way). The proxies have no way of teasing out individual requests, etc.

If you want request level monitoring at the proxies for HTTPS, you may want to consider terminating TLS at the gateway, and using Istio mTLS secure traffic between the gateway and the target pod.

I'm going to close this issue, as this does not reflect an issue with Istio (this is HTTPS traffic working as intended). In the future, please use discuss.istio.io for support questions of this nature. There have been several threads on related topics, including:
- https://discuss.istio.io/t/prometheus-request-duration-collection-on-external-https-url/10750/3
- https://discuss.istio.io/t/egress-gateway-and-https-traffic-enforce-istio-requests-total-metric/9894/2

**Closed by douglas-reid** 2022-03-24 16:17 UTC
