### ISSUE TITLE
istio 1.5 prometheus target errors 

### ISSUE THREAD

**Issue by prageethw** [istio/istio#21986] opened 2020-03-09 07:41 UTC
**Bug description**
Prometheus target errors in 1.5 Prometheus installation

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
There should be no target errors
**Steps to reproduce the bug**
Install demo profile and go to the Prometheus UI target.this seems harmless though it is a terrible experience.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
istioctl demo profile installation

**Environment where bug was observed (cloud vendor, OS, etc)**
KOPS AWS 
<img width="1397" alt="Screen Shot 2020-03-09 at 10 58 48 am" src="https://user-images.githubusercontent.com/24377789/76192251-7ab9b100-6235-11ea-95c6-515d97b5a879.png">

**Comment by prageethw** [comment] 2020-03-09 11:19
I think the issue is somewhere else

**Comment by prageethw** [comment] 2020-03-09 12:10
can confirm after further investigation it is related to istio prometheus

**Comment by howardjohn** [comment] 2020-03-09 15:50
Yeah I think its trying to scrape prometheus itself at :15090 which isn't valid

**Comment by esnible** [comment] 2020-03-31 14:33
@prageethw May I close this?

**Comment by howardjohn** [comment] 2020-05-15 04:11
This is a duplicate of https://github.com/istio/istio/issues/21720 so I will close, I think its still an issue in 1.6 though

**Closed** 2020-05-15 04:16 UTC
Labels: area/policies and telemetry, area/user experience, lifecycle/needs-triage
