### ISSUE TITLE
pilot env are not updating on istiod

### ISSUE THREAD

**Issue by rampatnaik** [istio/istio#29368] opened 2020-12-03 16:40 UTC
Hello 
I am using istio 1.7.2 version 
eks : 1.17

I have enable the flag "PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE" in
env : PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE in istio-discovery

-> bake stage : I can see the flag
-> After deployment I cannot see the flag .

can I know what could be issue

**Comment by howardjohn** [comment] 2020-12-03 18:08
> -> bake stage : I can see the flag
> -> After deployment I cannot see the flag .

Can you give more info about what you are doing? "bake stage" is not a common phrase is Istio installation

**Comment by rampatnaik** [comment] 2020-12-04 01:40
I am using spinnaker for deployment the istio

I have enable the flag "PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE" in

istio-discovery/values.yaml

--set istio-discovery.pilot.env.PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE=true

In bake : manifect : stage : I can see the flag available in bake stage
after deployment  "kubectl apply -f "pilot.yaml"

in istiod pod I cannot find the flag

**Comment by howardjohn** [comment] 2021-02-10 17:23
@rampatnaik I am not sure this is an Istio problem. If you apply a Deployment spec that has `PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE` in the YAML set, and its not being applied by `kubectl apply`, this sounds like a Kubernetes issue.

**Comment by howardjohn** [comment] 2021-03-03 00:21
Closing as this doesn't seem to be caused by Istio

**Closed by howardjohn** 2021-03-03 00:21 UTC
Labels: kind/need more info
