### ISSUE TITLE
Request rewrite recursively with regex

### ISSUE THREAD

**Issue by vinodloha** [istio/istio#20412] opened 2020-01-22 15:03 UTC
**Bug description**
with uri regex the /g flag doesn't seem to be working, i need to rewrite part of a URL recursively.

"/(\/digital\/app[\/?])/g"

Above regex Doesn't work and only rewrites the match once, leaving the recurring instances as is.I am using v1alpha3. 

**Expected behavior**
Should be able to match and rewrite all instances in the request.

**Comment by howardjohn** [comment] 2020-01-22 20:29
We use RE2 which I think does not support this. I could be wrong though, please fact check me :slightly_smiling_face: https://github.com/google/re2/wiki/Syntax

**Comment by howardjohn** [comment] 2020-05-14 17:18
Closing as this is workign as intended per ^

**Closed by howardjohn** 2020-05-14 17:18 UTC
Labels: area/networking, kind/enhancement, lifecycle/needs-triage
