### ISSUE TITLE
Update grafana dashboard with Wasm metrics

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#25843] opened 2020-07-24 17:51 UTC
Wasm already shows

wasm.envoy.wasm.runtime.null.active: 18
wasm.envoy.wasm.runtime.null.created: 18
wasm_filter.stats_filter.cache.hit.metric_cache_count: 408405500
wasm_filter.stats_filter.cache.miss.metric_cache_count: 945
wasm_vm.envoy.wasm.runtime.null.active: 18
wasm_vm.envoy.wasm.runtime.null.cloned: 0
wasm_vm.envoy.wasm.runtime.null.created: 18

And newly added wasm config metrics: https://github.com/istio/proxy/pull/2939/files

In addition add: container_cpu_cfs_throttled_seconds_total. for istio-proxies to ensure that cpu is not being throttled.

**Comment by douglas-reid** [comment] 2020-07-27 19:01
Duplicate of #24920 ?

**Comment by carolynhu** [comment] 2020-10-23 20:30
Follow up issues: 
- https://github.com/istio/istio/issues/28240

**Comment by carolynhu** [comment] 2020-10-23 21:30
Todo: add a release grafana dashboard ID

**Closed** 2020-10-27 17:05 UTC
Labels: area/extensions and telemetry
