### ISSUE TITLE
[Quick Start with Kubernetes] Use Helm and Tiller to manage the Istio deployment fails

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#11951] opened 2019-02-21 18:32 UTC
**Describe the bug**
When following [option 4](https://preliminary.istio.io/docs/setup/kubernetes/quick-start/#option-4-use-helm-and-tiller-to-manage-the-istio-deployment): Use Helm and Tiller to manage the Istio deployment. [step 3](https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install) fails.
```
$ kubectl apply -f install/kubernetes/helm/helm-service-account.yaml
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created

$ helm init --service-account tiller
$HELM_HOME has been configured at /usr/local/google/home/yinjie/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!

$ helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
Error: release istio-init failed: namespaces "istio-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "istio-system"
```

**Expected behavior**
Install the istio-init chart to bootstrap all the Istio’s CRDs should succeed.

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
```
$ istioctl version
version.BuildInfo{Version:"1.1.0-rc.0", GitRevision:"3632361b439ae27962f0af472064d452fc63273b", User:"root", Host:"9efe8d69-34c2-11e9-b805-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.6-26-g3632361"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Installation**
istio-1.1.0-rc.0-linux.tar.gz.sha256

**Environment**
Google Kubernetes Engine

**Comment by duderino** [comment] 2019-02-26 18:38
@ostromart thinks he can handle this easily, but if it proves to be more complicated we will probably reassign to @howardjohn

**Comment by ostromart** [comment] 2019-02-26 18:41
It could be a case of the RBAC not yet having taken effect when you run helm install. Could you please try the last command again if your cluster is still in the same state, or repeat the install and wait for a while before helm install? 
You should also run helm init --upgrade to update your tiller pod as it looks to be quite a long way behind the client.

**Comment by sdake** [comment] 2019-02-28 22:13
```
Warning: Tiller is already installed in the cluster
```

If tiller is already present, these instructions do not need to be run.  This is more or less working as intended.

**Comment by ostromart** [comment] 2019-02-28 22:35
The warning is expected but the main complaint here is the error further down:
$ helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
Error: release istio-init failed: namespaces "istio-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "istio-system"

**Comment by sdake** [comment] 2019-03-01 02:54
@ostromart that means tiller was not installed with an appropriate service account.  Many people don't instantiate tiller properly.  This is not really a code problem - perhaps this could be handled with documentation.

**Comment by duderino** [comment] 2019-03-01 21:39
@sdake I wonder if this should be reassigned to you to send a doc PR?   Got the bandwidth?

**Comment by ostromart** [comment] 2019-03-04 23:00
Just did some direct debugging with @JimmyCYJ and I think we are good. He will update.

**Comment by JimmyCYJ** [comment] 2019-03-04 23:01
I solve this problem by running 
```
$ helm init --service-account tiller --upgrade
$HELM_HOME has been configured at /usr/local/google/home/yinjie/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!

$ helm install istio.io/istio-init --name istio-init --namespace istio-system
NAME:   istio-init
LAST DEPLOYED: Mon Mar  4 14:55:58 2019
NAMESPACE: istio-system
STATUS: DEPLOYED

$ kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l
59

$ helm install istio.io/istio --name istio --namespace istio-system
NAME:   istio
LAST DEPLOYED: Mon Mar  4 14:56:35 2019
NAMESPACE: istio-system
STATUS: DEPLOYED

```

**Comment by JimmyCYJ** [comment] 2019-03-04 23:01
Thanks for the help @ostromart

**Comment by duderino** [comment] 2019-03-05 17:43
Doc instructions say this:

```
Verify that all 58 Istio CRDs were committed to the Kubernetes api-server using the following command:

$ kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l
58
```

I think this is now a doc bug, albeit not a high priority one.

**Comment by geeknoid** [comment] 2019-03-08 23:19
This is now fixed with latest stuff.

**Closed by geeknoid** 2019-03-08 23:19 UTC
Labels: area/environments, kind/docs

**Comment by fuxinghua** [comment] 2019-10-10 08:08
> I solve this problem by running
> 
> ```
> $ helm init --service-account tiller --upgrade
> $HELM_HOME has been configured at path-to-helm.helm.
> 
> Tiller (the Helm server-side component) has been upgraded to the current version.
> Happy Helming!
> 
> $ helm install istio.io/istio-init --name istio-init --namespace istio-system
> NAME:   istio-init
> LAST DEPLOYED: Mon Mar  4 14:55:58 2019
> NAMESPACE: istio-system
> STATUS: DEPLOYED
> 
> $ kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l
> 59
> 
> $ helm install istio.io/istio --name istio --namespace istio-system
> NAME:   istio
> LAST DEPLOYED: Mon Mar  4 14:56:35 2019
> NAMESPACE: istio-system
> STATUS: DEPLOYED
> ```

it also solved my problem
