### ISSUE TITLE
Istio Proxy timing out the DB connection

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#25106] opened 2020-06-30 04:33 UTC
**Bug description**
I am using istio in AWS EKS, the istio version is 1.4.3. I see the below issue when I do performance test. 
Pod to DB connection is filing intermittently with the below errors only if I enable istio sidecar. From default namespace where istio injection is not enabled, it is working fine.

"HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@17baf65d marked as broken because of SQLSTATE(08S01), ErrorCode(0)",
"HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5f37ca9f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

I have 4 replicas and each replicas will make 50 connections to DB.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The connection to DB should remains stable.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Kubectl version: v1.16.0
Helm Version: v3.0.3

**How was Istio installed?**
Installed as part of Helm charts.

**Environment where bug was observed (cloud vendor, OS, etc)** AWS

**Service Entry I used to connect to DB:**

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: db-egress
  namespace: apps
spec:
  addresses:
  - 10.84.66.48/28
  - 10.84.66.64/28
  - 10.84.66.80/28
  - 10.84.66.96/28
  - 10.84.66.112/28
  - 10.84.66.128/28
  exportTo:
  - .
  hosts:
  - db.dev.com
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 3306
    protocol: tcp

I tried with the below destinationrule but no luck

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: db-destinationrule
spec:
  host:
    db-dev.com
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 200
        connectTimeout: 14400s
        tcpKeepalive:
          time: 14400s
          interval: 14400s

**Comment by howardjohn** [comment] 2020-07-29 21:21
duplicate of https://github.com/istio/istio/issues/24856

**Closed by howardjohn** 2020-07-29 21:21 UTC
Labels: lifecycle/needs-triage
