### ISSUE TITLE
Telemetry pod in a crash loop in 1.1.0-snapshot.2

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#9542] opened 2018-10-25 21:55 UTC
**K8**: 1.10.7
**Istio**: 1.1.0-snapshot.2

I have this strange behaviour with one of the telemetry pods going into a crash loop upon deployment of Istio.

```
helm install install/kubernetes/helm/istio --name istio --namespace control \
  --set global.hub=istio \
  --set global.tag=1.1.0-snapshot.2 \
  --set global.imagePullPolicy=Always \
  --set sidecarInjectorWebhook.enabled=true \
  --set global.proxy.envoyStatsd.enabled=false \
  --set global.mtls.enabled=true \
  --set global.controlPlaneSecurityEnabled=true \
  --set security.selfSigned=true \
  --set global.enableTracing=false \
  --set global.proxy.autoInject=enabled \
  --set global.proxy.statusPort=0 \
  --set tracing.enabled=false \
  --set prometheus.enabled=false \
  --set gateways.istio-ingressgateway.type=ClusterIP
```

It only affects one of the telemetry pods as seen below
```
istio-citadel-79f74c4f6c-h7m7n                      1/1       Running     0          1d        10.4.2.130   gke-riro-cluster-app-pool-2-d8bb865b-2fgr
istio-egressgateway-77997f845-xlm99                 1/1       Running     0          1d        10.4.9.117   gke-riro-cluster-control-pool-2-1fe826e8-vmcx
istio-galley-6cbfc579b5-kxtcl                       1/1       Running     0          1d        10.4.3.104   gke-riro-cluster-app-pool-2-d8bb865b-7jdg
istio-ingressgateway-684b6b4dd5-mp4d9               1/1       Running     0          1d        10.4.5.125   gke-riro-cluster-app-pool-2-d8bb865b-ptcs
istio-pilot-59f44f58bd-d2dmh                        2/2       Running     0          1d        10.4.8.135   gke-riro-cluster-control-pool-2-1fe826e8-krvk
istio-policy-596b87db8f-gwnqr                       2/2       Running     0          1d        10.4.6.153   gke-riro-cluster-control-pool-2-1fe826e8-j2sv
istio-policy-596b87db8f-lbjfj                       2/2       Running     0          1d        10.4.9.116   gke-riro-cluster-control-pool-2-1fe826e8-vmcx
istio-sidecar-injector-5674c746-5qwgg               1/1       Running     0          1d        10.4.9.118   gke-riro-cluster-control-pool-2-1fe826e8-vmcx
istio-telemetry-7f44479886-29ckg                    2/2       Running     731        1d        10.4.5.126   gke-riro-cluster-app-pool-2-d8bb865b-ptcs
istio-telemetry-7f44479886-bf6bj                    2/2       Running     0          1d        10.4.8.136   gke-riro-cluster-control-pool-2-1fe826e8-krvk
istio-telemetry-7f44479886-bnv7v                    2/2       Running     0          1d        10.4.6.151   gke-riro-cluster-control-pool-2-1fe826e8-j2sv
istio-telemetry-7f44479886-jxkbh                    2/2       Running     0          1d        10.4.6.152   gke-riro-cluster-control-pool-2-1fe826e8-j2sv
istio-telemetry-7f44479886-k6jwb                    2/2       Running     0          1d        10.4.9.119   gke-riro-cluster-control-pool-2-1fe826e8-vmcx
```

Events from the crashing pod,
```
Events:
  Type     Reason     Age                  From                                                Message
  ----     ------     ----                 ----                                                -------
  Warning  Unhealthy  19m (x1444 over 1d)  kubelet, gke-riro-cluster-app-pool-2-d8bb865b-ptcs  Liveness probe failed: Get http://10.4.5.126:9093/version: dial tcp 10.4.5.126:9093: getsockopt: connection refused
  Warning  BackOff    9m (x8464 over 1d)   kubelet, gke-riro-cluster-app-pool-2-d8bb865b-ptcs  Back-off restarting failed container
```

A log from the crashing pod.
```
k logs -p istio-telemetry-7f44479886-29ckg -n control -c mixer
gc 1 @1.483s 21%: 137+685+452 ms clock, 275+0.13/13/509+904 ms cpu, 4->4->2 MB, 5 MB goal, 2 P
Mixer started with
MaxMessageSize:  1048576
MaxConcurrentStreams:  1024
APIWorkerPoolSize:  1024
AdapterWorkerPoolSize:  1024
APIPort:  9091
APIAddress:  unix:///sock/mixer.socket
MonitoringPort:  9093
EnableProfiling:  true
SingleThreaded:  false
NumCheckCacheEntries:  1500000
ConfigStoreURL:  k8s://
CertificateFile:  /etc/istio/certs/cert-chain.pem
KeyFile:  /etc/istio/certs/key.pem
CACertificateFile:  /etc/istio/certs/root-cert.pem
ConfigDefaultNamespace:  control
LoggingOptions: log.Options{OutputPaths:[]string{"stdout"}, ErrorOutputPaths:[]string{"stderr"}, RotateOutputPath:"", RotationMaxSize:104857600, RotationMaxAge:30, RotationMaxBackups:1000, JSONEncoding:false, LogGrpc:true, outputLevels:"default:info", logCallers:"", stackTraceLevels:"default:none"}
TracingOptions: tracing.Options{ZipkinURL:"http://zipkin:9411/api/v1/spans", JaegerURL:"", LogTraceSpans:false}
IntrospectionOptions: ctrlz.Options{Port:0x2694, Address:"127.0.0.1"}

2018-10-25T21:37:45.415737Z	warn	Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
gc 2 @3.353s 35%: 0.022+838+1012 ms clock, 0.045+0.16/504/351+2024 ms cpu, 4->5->4 MB, 5 MB goal, 2 P
2018-10-25T21:37:46.663015Z	info	Kinds: []string{"rule", "edge", "kubernetes", "cloudwatch", "opa", "rbac", "listentry", "stackdriver", "listchecker", "signalfx", "servicecontrol", "servicecontrolreport", "checknothing", "logentry", "metric", "stdio", "handler", "memquota", "redisquota", "adapter", "template", "kubernetesenv", "denier", "tracespan", "dogstatsd", "noop", "instance", "reportnothing", "authorization", "statsd", "fluentd", "attributemanifest", "circonus", "apikey", "quota", "prometheus", "bypass", "solarwinds"}
2018-10-25T21:37:47.435452Z	info	Awaiting for config store sync...
gc 3 @7.459s 37%: 59+3884+1415 ms clock, 118+290/2812/278+2831 ms cpu, 6->7->6 MB, 7 MB goal, 2 P
2018-10-25T21:37:54.375102Z	info	Starting runtime config watch...
2018-10-25T21:37:54.392611Z	info	Built new config.Snapshot: id='0'
2018-10-25T21:37:54.392696Z	info	Cleaning up handler table, with config ID:-1
2018-10-25T21:37:55.482050Z	info	Built new config.Snapshot: id='1'
2018-10-25T21:37:55.521465Z	info	adapters	serving prometheus metrics on 42422	{"adapter": "prometheus.control"}
2018-10-25T21:37:55.563197Z	info	adapters	getting kubeconfig from: ""	{"adapter": "kubernetesenv.control"}
2018-10-25T21:37:55.578189Z	warn	Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2018-10-25T21:37:55.665744Z	info	adapters	Waiting for kubernetes cache sync...	{"adapter": "kubernetesenv.control"}
gc 4 @14.889s 41%: 497+2303+1347 ms clock, 994+932/1584/0+2695 ms cpu, 9->10->7 MB, 10 MB goal, 2 P
gc 5 @21.344s 41%: 0.014+1315+1669 ms clock, 0.028+0.35/922/475+3339 ms cpu, 12->13->9 MB, 14 MB goal, 2 P
2018-10-25T21:38:05.850077Z	info	adapters	Cache sync successful.	{"adapter": "kubernetesenv.control"}
2018-10-25T21:38:05.870297Z	info	adapters	getting kubeconfig from: ""	{"adapter": "kubernetesenv.control"}
2018-10-25T21:38:05.872541Z	warn	Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2018-10-25T21:38:05.961264Z	info	Setting up event handlers
2018-10-25T21:38:05.987928Z	info	Starting Secrets controller
2018-10-25T21:38:05.988242Z	info	Waiting for informer caches to sync
2018-10-25T21:38:06.381688Z	info	Cleaning up handler table, with config ID:0
gc 6 @26.165s 47%: 0.014+4212+3503 ms clock, 0.028+2791/2211/922+7007 ms cpu, 79->127->124 MB, 80 MB goal, 2 P
```

If I look at the `istio-proxy` logs just before it starts to go into a crash Ioop I see the following in the log.
```
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
```

My conclusion so far is that it initially crashes probably due to the above errors and goes into the crash loop as it does not have sufficient time to start the monitoring server for the health probes to ping.

**Comment by nixgadget** [comment] 2018-10-28 07:44
@douglas-reid any idea what the issue might be here ? i can provide more info if the description lacks details.

now so far i have deleted the crashing instance of the pod and let the autoscaling do its job to re-create the instance. this is ok but would like to get to the bottom of it to see if its a problem with the way i deploy.

**Comment by douglas-reid** [comment] 2018-10-29 16:20
@nixgadget no, but I haven't looked at this yet. @mandarjog any ideas here?

**Comment by mandarjog** [comment] 2018-10-29 16:38
Do you see a message 
“Starting gRPC server on port 9091” in the logs? That indicates mixer has started.

In absence of that, the port is not open, so you can see upstream connection reset error messages.

Peter does this snapshot have the waiting fix?

**Comment by bianpengyuan** [comment] 2018-10-29 17:32
Yes it has the waiting fix, but that should not be the cause of crashloop. The log does not have CRD discovery failure before `Awaiting for config store sync...` line.

**Comment by bianpengyuan** [comment] 2018-10-29 22:10
@nixgadget Could you check the start up time of other healthy mixer pods (time spent before `start monitoring server...` line) based on log? Also could you check if the unhealthy mixer pod running on a different node with other mixer pods?

**Comment by nixgadget** [comment] 2018-10-29 23:56
@bianpengyuan FYI this is what I have observed so far.
- The crashing telemetry pod initialises fine. I can see the `Starting monitor server` and I can also see telemetry information coming through. 
- However, for some reason (after few minutes or so) I can see that `istio-proxy` erroring with `Mixer Report failed with: UNAVAILABLE:upstream request timeout`. And then the pod begins to crash.
- The subsequent crashes (crashloops) are resulted from the short delay in the liveness probe (5s). As I cannot see the `Starting monitor server` in the logs I assume there is insufficient wait time for the probe to run the liveness check (i.e. 5s initial delay may not be enough).

Heres an excerpt of the logs from the crashing pod.
[crashing_telemetry_pod_mixer.txt](https://github.com/istio/istio/files/2527436/crashing_telemetry_pod_mixer.txt)
[crashing_telemetry_pod_istio-proxy.txt](https://github.com/istio/istio/files/2527437/crashing_telemetry_pod_istio-proxy.txt)

By the way I was observing this issue on **1.0.3** as well.

And for comparison heres an excerpt of the logs from a non-crashing pod.
[telemetry_pod_istio-proxy.txt](https://github.com/istio/istio/files/2527468/telemetry_pod_istio-proxy.txt)
[telemetry_pod_mixer.txt](https://github.com/istio/istio/files/2527469/telemetry_pod_mixer.txt)

**Comment by bianpengyuan** [comment] 2018-10-30 03:49
I cannot find any suspicious lines in the log. Could you increase the liveness probe initial delay to a longer period like 30s to at least check if that stops repetitive restarting?

**Comment by nixgadget** [comment] 2018-10-30 03:59
@bianpengyuan Yean i can try that.

By the way what does the error `Mixer Report failed with: UNAVAILABLE:upstream request timeout` mean ? Is that a red herring ? Does it happen when its connecting to the mixer itself ?

**Comment by bianpengyuan** [comment] 2018-10-30 04:30
Yes, as other proxy, mixer's proxy also makes report call to mixer. The log line indicates mixer container is not in a healthy state.

**Comment by nixgadget** [comment] 2018-10-30 04:41
@bianpengyuan thanks for the clarification. will post back when I test increasing the probe delay

**Comment by nixgadget** [comment] 2018-11-02 22:35
@bianpengyuan What in the end fixed the issue was increasing the mem for the telemetry pods. 
I had initially failed to notice that the pod was crashing due to a `OOM`. This is the first time it crashes.
I set it to a conservative number like `512Mi` and no issues since. Perhaps better to even have a note if restricting the cpu/memory for these pods.
I could not recover the subsequent crashes (crashloop) by increasing the initial delay of the liveness probe to even after setting `60s`. Something else must be causing these crashes. Yet to investigate !
I think we are ok to close this for now ?

**Comment by douglas-reid** [comment] 2018-11-02 23:01
@mandarjog does this imply anything about initial settings for the mixer related pods that we should consider for 1.1 and beyond?

**Comment by bianpengyuan** [comment] 2018-11-16 22:16
Close this for now since the initial issue has been resolved.

**Closed by bianpengyuan** 2018-11-16 22:16 UTC
Labels: area/policies and telemetry
