### ISSUE TITLE
1.3 Performance regression detected by regpatrol

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#16416] opened 2019-08-20 20:58 UTC
Since 1.3 builds [regpatrol](https://ibmcloud-perf.istio.io/regpatrol/) shows small but consistent degradation in TPS in Full and No Mixer case.
(B) No Mixer case removes Mixer filter. 1.2.x basline was 1139 and it dropped to 1080.

The drop is small but consistent.

Row | Build | (A) Istio Full | (B) No Mixer | (C) Ingress Only | (A)/(C) % | (B)/(C) %
-- | -- | -- | -- | -- | -- | --
1 | 1.2.3 (baseline) | 1032 | 1139 | 1324 | 77.9 | 86.0
2 | release-1.2-20190802-09-15 | 1040 | 1138 | 1378 | 75.5 | 82.6
3 | release-1.2-20190803-09-15 | 1021 | 1156 | 1369 | 74.6 | 84.4
4 | release-1.2-20190804-09-15 | 1048 | 1139 | 1371 | 76.4 | 83.1
5 | release-1.2-20190805-09-15 | 1000 | 1148 | 1374 | 72.8 | 83.6
6 | release-1.2-20190806-09-15 | 1016 | 1146 | 1364 | 74.5 | 84.0
7 | release-1.2-20190807-09-16 | 1020 | 1149 | 1368 | 74.6 | 84.0
8 | release-1.2-20190808-09-16 | 1006 | 1138 | 1358 | 74.1 | 83.8
9 | release-1.2-20190809-09-16 | 1023 | 1129 | 1366 | 74.9 | 82.7
10 | release-1.3-20190813-18-00 | 971 | 1078 | 1336 | 72.7 | 80.7
11 | release-1.3-20190814-09-16 | 957 | 1068 | 1342 | 71.3 | 79.6
12 | release-1.3-20190815-09-16 | 963 | 1091 | 1376 | 70.0 | 79.3
13 | release-1.3-20190816-09-16 | 962 | 1038 | 1369 | 70.3 | 75.8
14 | release-1.3-20190817-09-16 | 979 | 1090 | 1450 | 67.5 | 75.2
15 | release-1.3-20190818-09-16 | 958 | 1065 | 1338 | 71.6 | 79.6
16 | release-1.3-20190819-09-16 | 1001 | 1041 | 1344 | 74.5 | 77.5

**Comment by mandarjog** [comment] 2019-08-20 20:58
@jnativio

**Comment by mandarjog** [comment] 2019-08-20 20:59
@jnativio can you confirm that you can replicate 1.2 results on the current setup and it is not an environmental thing?

**Comment by jnativio** [comment] 2019-08-21 03:52
Yes, I repeated the run for build release-1.2-20190809-09-16 no_mixer and got similar results as before.

**Comment by mandarjog** [comment] 2019-08-21 11:23
@richardwxn Please look at how regpatrol was able to detect this.

**Comment by howardjohn** [comment] 2019-08-30 18:24
This is marked as release blocker, did anyone replicate the results? Is someone working on this?

If this is a release blocker it needs someone dedicated to working on this

**Comment by carolynhu** [comment] 2019-08-30 18:33
I am dedicated working on this issue. I just got 1.3 perf/benchmark test results. I need to compare with 1.2. Then investigate possible issues if there do have a degradation.

**Comment by howardjohn** [comment] 2019-08-30 18:35
Sounds good thanks @carlynhu!

**Comment by jnativio** [comment] 2019-08-30 18:56
The regpatrol results for the latest 1.3 builds do not show this regression anymore.

**Comment by howardjohn** [comment] 2019-09-03 15:28
@jnativio so was it environmental or was there a change that fixed it?

**Comment by carolynhu** [comment] 2019-09-03 15:33
@mandarjog @howardjohn @jnativio What I currently can get is the following graph:
![base_serveronly_v2_vs_v3](https://user-images.githubusercontent.com/29208297/64187414-6f6c6f80-ce25-11e9-87e7-6c50803f441d.png)

**Comment by jnativio** [comment] 2019-09-03 19:37
@howardjohn I am pretty sure that the drop was not caused by some environment change as I had rerun the scenario with a previous build and got good results, and today I reran with one of the affected builds and got bad results (see chart below). But as I said before, that regression affected 1.3 builds from 08/13 to  08/19 and since then the results have been in parity with 1.2 and even better than the baseline . I assume some change got in by that time and improved the performance.

![image](https://user-images.githubusercontent.com/18554027/64203056-ae6be680-ce60-11e9-8cf9-b8330d8ff66c.png)

**Comment by jnativio** [comment] 2019-09-03 19:42
@carolynhu So, given what I explained above, in order to verify if there was really a temporary regression on 1.3, you should get a build from that period and compare the results with the current ones.

**Comment by carolynhu** [comment] 2019-09-03 19:47
Ok, thanks for your information. Will do soon.

**Comment by carolynhu** [comment] 2019-09-11 20:33
Here is the latest istio 1.3 latency p90:
![latency_p90](https://user-images.githubusercontent.com/29208297/64732963-ad5a3b00-d498-11e9-8d0a-69ca74b7350b.png)
According to it, we do not have regression issues.

**Comment by howardjohn** [comment] 2019-09-13 23:10
Both people that tried this are showing no regressions

**Closed by howardjohn** 2019-09-13 23:10 UTC
Labels: area/perf and scalability
