### ISSUE TITLE
Configure a TLS ingress gateway for multiple hosts

### ISSUE THREAD

**Issue by samsonluo** [istio/istio#14296] opened 2019-05-22 13:39 UTC
Configure the routes for bookinfo.com. Define a VirtualService like the one in samples/bookinfo/networking/bookinfo-gateway.yaml

kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "bookinfo.com"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
EOF

gateways name is not httpbin-gateway, please replace it with bookinfo-gateway

**Comment by howardjohn** [comment] 2019-05-22 14:56
I am not sure what the problem you are facing is. In the same, it is bookinfo-gateway?

**Comment by howardjohn** [comment] 2019-05-31 17:39
As far as I can tell, this problem is already fixed in master, see samples/bookinfo/networking/bookinfo-gateway.yaml.

If this is not the case please follow up with more information as it is not clear what the problem is currently

**Closed** 2019-05-31 17:40 UTC
