### ISSUE TITLE
Multiple addresses of a ServiceEntry get lost in conversion to model.Service

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#5498] opened 2018-05-09 11:38 UTC
There is a mismatch between the pilot model of a Service with a single `Address` or a map of `Addresses`, an address per cluster, https://github.com/istio/istio/blob/release-0.8/pilot/pkg/model/service.go#L53, and the definition of the ServiceEntry https://github.com/istio/api/blob/master/networking/v1alpha3/service_entry.proto#L170.

Currently, a model.Service is built from each address of ServiceEntry.

A possible  renaming: rename model's  `Addresses` into `ClusterAddresses`, and `Address` into `Addresses`. Then take the `Addresses` into account in the code that builds tcp proxy filters - https://github.com/istio/istio/blob/release-0.8/pilot/pkg/networking/core/v1alpha3/listener.go#L381 .

**Comment by rshriram** [comment] 2018-05-09 19:33
+1.. call it multiclusterAddresses.. I thought I added a service  for each address in service entry.

**Comment by costinm** [comment] 2018-05-30 18:50
I'm not sure about renaming or other changes to the model.Service - I would rather spend the effort on moving the code generation to use ServiceEntry directly, and start migrating from model.Service to ServiceEntry.

**Comment by rshriram** [comment] 2018-05-30 20:04
Service entry is essentially model.service exposed as crd. And we are essentially doing what you suggest. Convert everything into a simple model.service for consumption everywhere.

**Comment by ronenschafferibm** [comment] 2018-05-31 12:48
The problem is that if one configures a `ServiceEntry` with multiple addresses, some of the addresses get lost.
Consider the following `ServiceEntry` taken from [Control Egress TCP Traffic](https://preliminary.istio.io/docs/tasks/traffic-management/egress-tcp/#creating-a-service-entry) task:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wikipedia-ext
spec:
  hosts:
  - wikipedia.org
  addresses:
  - 91.198.174.192/27
  - 103.102.166.224/27
  - 198.35.26.96/27
  - 208.80.153.224/27
  - 208.80.154.224/27
  ports:
  - number: 443
    protocol: TCP
    name: tcp-port
  resolution: NONE
```

The `ServiceEntry` is converted into 5 `model.Service`s (one for each address) with the same hostname "wikipedia.org". This conversion is done by `serviceregistry/external/conversion.go:convertServices()`

https://github.com/istio/istio/blob/23dec44e42474429391a09f5436bd252ed5373dd/pilot/pkg/serviceregistry/external/conversion.go#L35

Later, when `aggregate/controller.go:Services()` is called, it aggregates the services from all the service registries (e.g. k8s and external).
This aggregation allows only one service per hostname (while we have 5 servcies with the same hostname) so some of the addresses are lost.
This also populates the `ClusterVIPs` map so it maps between serviceregistry's clusterID and an address (ip).
https://github.com/istio/istio/blob/23dec44e42474429391a09f5436bd252ed5373dd/pilot/pkg/serviceregistry/aggregate/controller.go#L103
The result is that the service list contains a `model.Service` with the following data:
```
Hostname: "wikipedia.org"
Address: "91.198.174.192/27"                                # The first address specified in the yaml
ClusterVIPs: { "ServiceEntries", "208.80.154.224/27" }      # The last address specified in the yaml
```
The `ServiceEntries` key comes from here:
https://github.com/istio/istio/blob/f7831f4bf0ef25db9767b4423e2e812c13b68388/pilot/pkg/bootstrap/server.go#L688



This `Services()` func is called, for example, by `buildSidecarListeners()` which passes the service list to `buildSidecarOutboundListeners()` that can't build the the corresponding listener properly.

**Comment by costinm** [comment] 2018-05-31 20:42
Yes, I know - ideally we could use the actual ServiceEntry proto without extra conversions. 

Conversion = extra code, extra allocs, extra bugs.

**Comment by vadimeisenbergibm** [comment] 2018-06-01 18:42
@costinm I think we should refactor the code to handle multiple addresses anyway, either of `ServiceEntry` directly, or of `model.Service`. So the proposed approach is: 
1. Refactor `model.Service` to contain multiple addresses 
2. Refactor the code that consumes the address information to handle multiple addresses
3. Consider to replace `model.Service` with `ServiceEntry`

The third step is orthogonal to this issue, in my opinion. It could be discussed after 1. and 2. are performed and the bug https://github.com/istio/istio/issues/5916 is fixed.

**Comment by costinm** [comment] 2018-06-01 19:01
What I fail to understand is what 'multiple addresses' means - a Service
has an associated list of ServiceInstance, each with an address.
The 'Address' filed is the VIP.

Can you provide an example ? There was a discussion on multicluster having
different VIPs, but I think it was concluded it is
not needed. I don't remember the details.

On 3 - big +1, and while I'm generally trying to minimize risks - it's one
of the cases where I think it's well worth it.

**Comment by vadimeisenbergibm** [comment] 2018-06-02 03:12
@costinm The example is in https://github.com/istio/istio/issues/5498#issuecomment-393518902. wikipedia.org is a _mesh-external_ `ServiceEntry` and it has multiple addresses (multiple IP blocks).

**Comment by costinm** [comment] 2018-06-02 05:26
Well - I guess there is not a big harm from changing to an array of addresses, it may allow some multicluster use cases. Some form of merging ServiceEntries may become needed.

**Comment by vadimeisenbergibm** [comment] 2018-06-04 08:36
@costinm I did not say that I agree on (3) :) It is just an orthogonal issue to this one, and the current refactoring can still facilitate (3) if it will be agreed to perform (3).

Regarding the SNI sniffing - note that it is already implemented, see this PR https://github.com/istio/istio.github.io/pull/1421.

**Comment by rshriram** [comment] 2018-06-04 19:50
> Once we have SNI sniffing - I'm not sure if user configuring egress by knowing the (fixed) IP of
each site will be needed - and maybe it's something to consider for removal before moving to beta.

We do have SNI sniffing in 0.8

**Comment by vadimeisenbergibm** [comment] 2018-07-25 14:29
The original problem -https://github.com/istio/istio/issues/5916 is fixed, it seems this issue is not required.

**Closed** 2018-07-25 19:50 UTC
Labels: area/networking
