### ISSUE TITLE
istio-egress TPR "IstioConfig" is not ready (the server has asked for the client to provide credentials (get IstioConfigs.istio.io))

### ISSUE THREAD

**Issue by fatg1988** [istio/istio#419] opened 2017-06-18 01:43 UTC
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

![default](https://user-images.githubusercontent.com/3365952/27257544-1599f9c6-540d-11e7-8f60-ce9610f6f673.png)

![qq 20170618095014](https://user-images.githubusercontent.com/3365952/27257543-fb56ff8c-540c-11e7-8398-901514fc4194.png)

![default](https://user-images.githubusercontent.com/3365952/27257485-1859c738-540b-11e7-8e79-4941561e9cd5.png)

**Comment by Amit-PivotalLabs** [comment] 2017-07-03 00:23
I had a similar problem.  In my case, the root cause was that components like `istio-pilot` were authenticating with a service account token that was generated against the API server's TLS key (this is the default behaviour for service account token generation).  At some point I had to rotate my API server's TLS key, but the tokens don't automatically get regenerated, so the API server would fail to authenticate the token presented by `istio-pilot`.

I solved this heavy-handedly:

1. Delete all tokens:

    ```
    $ kubectl delete secret --all
    ```
    They will automatically get regenerated for you.
2. Scale all deployments down to 0:

    ```
    $ kubectl get deploy | grep -v NAME | cut -f1 -d' ' | xargs -I {} \
         kubectl scale deploy/{} --replicas 0
    ```
3. Scale everything back up:

    ```
    $ kubectl get deploy | grep -v NAME | cut -f1 -d' ' | xargs -I {} \
         kubectl scale deploy/{} --replicas 1
    $ kubectl scale deploy/istio-pilot --replicas 2
    ```

**Comment by spirrello** [comment] 2017-08-01 14:39
@Amit-PivotalLabs I'm having the same issue and I tried your workaround but I'm still having the same problem.

Is there a known fix for this?


kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by wuzhihui1123** [comment] 2017-08-11 01:40
@fatg1988   I have the same problem , Did you solve it ? thanks

**Comment by ldemailly** [comment] 2017-08-16 23:05
will move this issue to auth/

**Comment by ldemailly** [comment] 2017-08-16 23:05
Issue moved to [istio/auth #222](https://github.com/istio/auth/issues/222) via [**ZenHub**](https://www.zenhub.com/)

**Closed by ldemailly** 2017-08-16 23:05 UTC
