### ISSUE TITLE
[release-1.6] istiodRemote and base can not be specified in iop in release-1.6

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#23846] opened 2020-05-14 07:15 UTC
Using latest rc.0 build: https://github.com/istio/istio/releases/tag/1.6.0-rc.0
`istioctl install -f multi-remote-cluster.yaml`

`Error: failed to apply manifests: validation errors (use --force to override):
unknown field "base" in v1alpha1.GlobalConfig`

`cat multi-remote-cluster.yaml`

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    base:
      enabled: true
    pilot:
      enabled: false
    istiodRemote:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
  values:
    global:
      multiCluster:
        clusterName: remotecluster
      network: remotenetwork
      centralIstiod: true
      istiodRemote:
        injectionURL: https://irisdingbj:15017/inject
      base:
        validationURL: https://irisdingbj15017/validate
```

**Comment by irisdingbj** [comment] 2020-05-14 07:27
@linsun

**Comment by linsun** [comment] 2020-05-14 13:26
Thanks @irisdingbj I will download rc.0 and try.  I noticed one issue, why is your profile empty?

**Comment by linsun** [comment] 2020-05-14 13:49
@irisdingbj I think this may be an user error.  I just downloaded rc.0 and manifest generates fine for me.  Below is the IO yaml I used.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: false  
    istiodRemote:
      enabled: true 
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true 
  
  addonComponents:
    prometheus:
      enabled: false
  values:
    global:
      # The remote cluster's name and network name must match the values specified in the
      # mesh network configuration of the main cluster.
      multiCluster:
        clusterName: remote0 
      network: network2        
      centralIstiod: true
      
      # Replace ISTIOD_REMOTE_EP with the the value of ISTIOD_REMOTE_EP set earlier.
      remotePilotAddress: 169.x.x.x
    
    istiodRemote:
      injectionURL: https://169.x.x.x:15017/inject

    base:
      validationURL: https://169.x.x.x:15017/validate

  ## The istio-ingressgateway is not required in the remote cluster if both clusters are on
  ## the same network. To disable the istio-ingressgateway component, uncomment the lines below.
  #

```

**Comment by irisdingbj** [comment] 2020-05-18 08:50
```
./istioctl manifest generate -f ../../multi-remote-cluster.yaml > out.iyaml
Error: validation errors (use --force to override):
unknown field "istiodRemote" in v1alpha1.GlobalConfig
```

tried using rc.1 build

**Comment by linsun** [comment] 2020-05-18 13:24
@irisdingbj thanks for reporting this.  Can you share your multi-remote-cluster.yaml file so I can reproduce this?

**Comment by linsun** [comment] 2020-05-18 14:35
@irisdingbj I still can't reproduce this.  Did you remote `profile: empty` off your yaml file?

Here is what I did:

```
$ istioctl version                 
no running Istio pods in "istio-system"
1.6.0-rc.2

(⎈ |docker-desktop:default)
~/Downloads/istio-1.6.0-rc.2 ⌚ 10:33:21
$ istioctl manifest generate -f ~/go/src/istio.io/testingdir/istio-remote0-cluster-istiod-remote.yaml                                                 
# AddonComponents grafana component is disabled.

---
# AddonComponents istiocoredns component is disabled.

---
# AddonComponents kiali component is disabled.

---
# AddonComponents prometheus component is disabled.

---
# AddonComponents istio-tracing component is disabled.

# Resources for Base component

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:

```

**Comment by linsun** [comment] 2020-05-18 14:36
```
$ cat ~/go/src/istio.io/testingdir/istio-remote0-cluster-istiod-remote.yaml                                 
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: false  
    istiodRemote:
      enabled: true 
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true 
  
  addonComponents:
    prometheus:
      enabled: false
  values:
    global:
      # The remote cluster's name and network name must match the values specified in the
      # mesh network configuration of the main cluster.
      multiCluster:
        clusterName: remote0 
      network: network2        
      centralIstiod: true
      
      # Replace ISTIOD_REMOTE_EP with the the value of ISTIOD_REMOTE_EP set earlier.
      remotePilotAddress: 169.60.74.107
      caAddress: istiod.istio-system.svc:15012
    
    istiodRemote:
      injectionURL: https://169.60.74.107:15017/inject

    base:
      validationURL: https://169.60.74.107:15017/validate

  ## The istio-ingressgateway is not required in the remote cluster if both clusters are on
  ## the same network. To disable the istio-ingressgateway component, uncomment the lines below.
  #
```

**Comment by linsun** [comment] 2020-05-18 14:38
also, make sure your istioctl is the right version and not a developer built istioctl

**Comment by howardjohn** [comment] 2020-07-31 21:26
Closing as we cannot reproduce

**Closed by howardjohn** 2020-07-31 21:26 UTC
Labels: area/environments/installer, area/environments/multicluster, community/testing days, lifecycle/needs-triage
