### ISSUE TITLE
istioctl profile dump --config-path doesn't work in Istio 1.5.0 beta 3

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#21481] opened 2020-02-25 19:53 UTC
**Bug description**
When trying `istioctl profile dump --config-path components.pilot demo`, I get: 

Error: path not found at element components in path components.pilot

I tried looking at the YAML and formulating a path and I seem to get either `{}` or some variant of the above error regardless of what I enter. 

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
`--configpath` allows me to filter the output of `istioctl profile dump`

**Steps to reproduce the bug**
`istioctl profile dump --config-path components.pilot demo` as documented here: https://preliminary.istio.io/docs/setup/install/istioctl/

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.5.0 beta 3 on Kubernetes 1.4.2 on Minikube 1.7.3

**How was Istio installed?**
`istioctl manifest apply --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by richardwxn** [comment] 2020-02-25 23:57
looks like this this the regression introduced by this PR: https://github.com/istio/istio/pull/20912. @ayj

**Comment by richardwxn** [comment] 2020-02-26 00:01
and the fix PR fails to be auto cherry-picked into release-1.5?

**Comment by johnma14** [comment] 2020-02-27 23:16
Looks like this is fixed. Closing it. Thank you.

**Closed by johnma14** 2020-02-27 23:16 UTC
Labels: area/environments, community/testing days
