### ISSUE TITLE
sidecar pilot doesn't initialize

### ISSUE THREAD

**Issue by sdake** [istio/istio#11979] opened 2019-02-22 15:18 UTC
**Describe the bug**
Something is borked in 1.1 daily releases (or my install is borked).

Applier sidecar spins with this log (for 50+ minutes before I gave up):
```
* failed checking application ports. listeners="0.0.0.0:15090","10.3.0.25:443","10.3.0.223:15030","10.3.0.99:53","10.3.0.30:42422","10.3.0.1:443","10.3.0.223:443","10.3.0.223:15031","10.3.0.223:15443","10.3.0.172:443","10.3.0.223:31400","10.3.0.223:15029","10.3.0.223:15032","10.3.0.216:15011","0.0.0.0:10000","0.0.0.0:80","0.0.0.0:8080","0.0.0.0:15004","0.0.0.0:9091","0.0.0.0:15014","0.0.0.0:9901","0.0.0.0:9090","0.0.0.0:8060","0.0.0.0:15010","10.2.2.40:15020","0.0.0.0:15001"
* envoy missing listener for inbound application port: 0
* envoy missing listener for inbound application port: 10000
```

**Expected behavior**
application sidecar initializes properly.

**Steps to reproduce the bug**
1. Install Istio with following values.yaml
```
global:
  podDNSSearchNamespaces:
  - global
  - "[[ valueOrDefault .DeploymentMeta.Namespace \"default\" ]].global"

  multiCluster:
    enabled: true

  controlPlaneSecurityEnabled: true

  hub: gcr.io/istio-release

  tag: release-1.1-latest-daily

security:
  selfSigned: false

istiocoredns:
  enabled: true

gateways:
  istio-egressgateway:
    env:
      ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
```

1. label the default namespace

1. Install this manifest:
```
kind: Deployment
metadata:
  name: applier
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      containers:
      - name: applier
        image: gcr.io/stackpoint-public/applier:sdake
        imagePullPolicy: Always
        ports:
        - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: applier
  labels:
    app: applier
spec:
  ports:
  - port: 10000
    name: grpc
  selector:
    app: applier
```

**Version**
daily release 
<img width="528" alt="screen shot 2019-02-22 at 6 01 15 am" src="https://user-images.githubusercontent.com/755849/53251595-4438e480-367a-11e9-8a44-a12c883935eb.png">

**Installation**
See values.yaml above

**Environment**
Azure cloud environment deployed with kubeadm.

**Comment by sdake** [comment] 2019-02-22 15:19
@sbezverk had reported in his environment (bare metal or vms?) - that the same thing happens but killing the pilot pod gets things operational.  I killed pilot, and same result.

Cheers
-steve

**Comment by jmazzitelli** [comment] 2019-02-22 15:30
I was seeing the same things yesterday. @knrc was also seeing this.

I reproduced simply by installing bookinfo, then "kubectl delete namespace bookinfo", then re-installing bookinfo. Most (but not all) of my bookinfo pods had their sidecars fail to start with the same error as in the OP.

Interestingly, if I just deleted on pod (say the productpage pod), I would see it scale back up and the proxy would be fine (started up, no errors). But if I delete all the pods at the same time, then I would see problems.

I was seeing this on 1.1.0-snapshot.6 on OpenShift 3.11.

**Comment by jmazzitelli** [comment] 2019-02-22 15:34
@sdake this may be a dup of https://github.com/istio/istio/issues/9504

**Comment by knrc** [comment] 2019-02-22 15:36
@sdake We hit this yesterday and I'm investigating, we have a simple reproducer so it's not too difficult to test at the moment

**Comment by sdake** [comment] 2019-02-22 15:43
@knrc cool fair enough.

Note I tested with this hub and tag as well with no love:

```  hub: docker.io/istio

  tag: 1.1.0-rc.0
```

**Comment by sbezverk** [comment] 2019-02-22 15:51
@knrc Based on logs I saw there was something with the path to certificate:

do you see this error in your log?
```
[2019-02-21 15:21:07.525][23][critical][main] [external/envoy/source/server/server.cc:86] error initializing configuration '/etc/istio/proxy/envoy.yaml': Invalid path: /etc/certs/cert-chain.pem
```

**Comment by knrc** [comment] 2019-02-22 15:59
@sbezverk No, I'm seeing the same error as @sdake.  I investigated the envoy side yesterday and confirmed the missing listener, I'm now going through pilot and am suspecting a race on deployment.

**Comment by sdake** [comment] 2019-02-22 16:06
@sbezverk the problem you found is caused by a race with citadel creating certs and the mounting of said certs in the deployment (I think).  I believe this will self-resolve once the certs are created and remounted, but could be mistaken.

**Comment by sdake** [comment] 2019-02-22 16:11
none of the workarounds that @nmittler suggested work for me.

**Comment by sbezverk** [comment] 2019-02-22 16:23
@sdake how about restart pilot pod? Worked for me 100% of times..

**Comment by sdake** [comment] 2019-02-22 16:27
```kubectl delete po -n istio-system pilot-XYZ```

**Comment by duderino** [comment] 2019-02-22 17:41
@knrc is the effective assignee

**Comment by duderino** [comment] 2019-02-22 17:42
@costinm please help

**Comment by duderino** [comment] 2019-02-22 17:47
actually, closing this as a duplicate of #9504 since that has more state

**Closed by duderino** 2019-02-22 17:47 UTC

**Comment by sdake** [comment] 2019-02-23 00:01
@costinm found the root cause.  My manifest was incorrect.

The labels for the manifest of the service and deployment didn't match.  This caused weird errror results in the sidecar pilot-proxy.  Perhaps other folks are suffering with this same false symptom of the readiness check failing.

**Comment by kyessenov** [comment] 2019-02-23 00:11
Interesting, there is no requirement for labels to match between deployment and service in k8s... Service labels must select over pods, but the selector can be less restrictive.

**Comment by kyessenov** [comment] 2019-02-23 00:12
Ah, ok. I see that pod template and service don't match.
