### ISSUE TITLE
Setting `global.imagePullPolicy` has no effect with gateway injection

### ISSUE THREAD

**Issue by ethanchowell** [istio/istio#42852] opened 2023-01-17 23:38 UTC
### Bug Description

I'm trying to install istio in an airgapped environment with terraform's helm provider. I've loaded the images into the nodes, and installed the latest charts

- `istio/base`
- `istio/istiod`
- `istio/cni`

Successfully deploying each of their images. When I install `istio/gateway` the generated pod has `imagePullPolicy: Always`, even though I've set `global.imagePullPolicy=IfNotPresent`, and the pod dies because there's no connection to pull the image.

### Version

```prose
# istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: none

# kubectl version --short
Client Version: v1.23.12+rke2r1
Server Version: v1.23.12+rke2r1

# helm version --short
v3.10.2+g50f003e
```

### Additional Information

For istiod, I'm explicitly setting the `imagePullPolicy` for the injection template with

```terraform
resource "kubernetes_namespace_v1" "istio_system" {
  metadata {
    name = "istio-system"
    labels = {
      istio-injection = "enabled"
    }
  }
}

resource "helm_release" "istiod" {
  depends_on = [helm_release.istio_base]

  repository = local.helm_repo
  chart      = "istiod"
  version    = var.istio_version # 1.16.1

  name      = "istiod"
  namespace = kubernetes_namespace_v1.istio_system.metadata[0].name

  values = [
    var.mesh_config_values
  ]

  set {
    name = "global.imagePullPolicy"
    value = "IfNotPresent"
  }

  set {
    name  = "meshConfig.accessLogFile"
    value = "/dev/stdout"
  }

  set {
    name  = "meshConfig.defaultConfig.gatewayTopology.forwardClientCertDetails"
    value = "APPEND_FORWARD"
  }

  set {
    name  = "meshConfig.defaultConfig.proxyMetadata.ISTIO_META_DNS_CAPTURE"
    value = "true"
  }

  set {
    name  = "meshConfig.defaultConfig.proxyMetadata.ISTIO_META_DNS_AUTO_ALLOCATE"
    value = "true"
  }
}
```
I can see that the value is set in the config map
```yaml
values: |-
    {
      ...
        "imagePullPolicy": "IfNotPresent",
        "imagePullSecrets": [],
      ...
    }
```
But when I then install an ingress gateway
```terraform
resource "helm_release" "ingress_gateway" {
  depends_on = [helm_release.istiod]

  repository = local.helm_repo
  chart      = "gateway"
  version    = var.istio_version # 1.16.1

  name      = "istio-ingressgateway"
  namespace = kubernetes_namespace_v1.istio_system.metadata[0].name

  values = [
  <<-EOT
podAnnotations:
  inject.istio.io/templates: "gateway"
EOT
  ]

  set {
    name = "service.type"
    value = "NodePort"
  }

  set {
    name  = "securityContext.fsGroup"
    value = "1337"
  }

  set {
    name  = "securityContext.runAsGroup"
    value = "1337"
  }

  set {
    name  = "securityContext.runAsNonRoot"
    value = "true"
  }

  set {
    name  = "securityContext.runAsUser"
    value = "1337"
  }
}
```
The pod that gets created is set to pull the image
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject.istio.io/templates: gateway
    kubernetes.io/psp: global-unrestricted-psp
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    proxy.istio.io/overrides: '{"containers":[{"name":"istio-proxy","ports":[{"name":"http-envoy-prom","containerPort":15090,"protocol":"TCP"}],"resources":{"limits":{"cpu":"2","memory":"1Gi"},"requests":{"cpu":"100m","memory":"128Mi"}},"volumeMounts":[{"name":"kube-api-access-9vhp6","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always","securityContext":{"capabilities":{"drop":["ALL"]},"privileged":false,"runAsUser":1337,"runAsGroup":1337,"runAsNonRoot":true,"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false}}]}'
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/status: '{"initContainers":null,"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
  generateName: istio-ingressgateway-6c5d6c5b77-
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    istio.io/rev: default
    service.istio.io/canonical-name: istio-ingressgateway
    service.istio.io/canonical-revision: latest
    sidecar.istio.io/inject: "true"
  name: istio-ingressgateway-6c5d6c5b77-5lmn9
  namespace: istio-system
spec:
  containers:
    ...
    image: docker.io/istio/proxyv2:1.16.1
    imagePullPolicy: Always
    name: istio-proxy
    ...
```
I've also tried to install the gateway without the `podAnnotations` with no luck. Installing with `istioctl install` succeeds, deploying istiod and an ingress-gateway exactly as I would expect. I can also get istio running with `istioctl operator init` and then installing another helm chart with the `IstioOperator` spec and that works as well since I can explicitly define `imagePullPolicy` in the gateway spec. I'd like to avoid installing istio using the cli since terraform can track the chart state easier than doing a `local-exec`.

**Comment by howardjohn** [comment] 2023-01-17 23:51
Fixed in https://github.com/istio/istio/pull/42026 I think?

**Comment by dhawton** [comment] 2023-01-18 01:29
I've replicated this with the latest helm charts.

**Comment by ethanchowell** [comment] 2023-01-18 03:24
I can put up a PR if it's as simple as adding it to the chart. Adding it to the gateway deployment template worked for me, it just threw me since the actual pod looks to be generated from the gateway-injection-template https://github.com/istio/istio/blob/5f471c3a423a806970a9a31ccf94c85cd0c0e1f4/manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml#L128 and I would expect that pull policy to propagate. My understanding of it though, may not be correct.

**Comment by howardjohn** [comment] 2023-01-18 04:44
The issue is Kubernetes defaults the field before and the existing Deployment container spec has precedence

**Closed** 2023-01-26 14:42 UTC
Labels: area/environments
