### ISSUE TITLE
Test target uses binaries path from host pwd despite mounting to /work

### ISSUE THREAD

**Issue by emike922** [istio/istio#39828] opened 2022-07-07 16:05 UTC
### Bug Description

Running `make build test`, expecting to build and test in docker, fails.
The following warning implies to me that LOCAL_OUT is wrongly set to a path on the docker host file system:

```
2022-07-07T14:34:51.414247Z	warn	unable to resolve LOCAL_OUT. Dir /var/jenkins/workspace/istio-pre-cr/out/linux_amd64 does not exist
```

To confirm:
```
$ make shell
build-tools:/work$ printenv LOCAL_OUT
/var/jenkins/workspace/istio-pre-cr/out/linux_amd64
build-tools:/work$ ls -lh out/linux_amd64/
total 794M
-rwxr-xr-x 1 user docker  76M Jul  7 16:43 bug-report
-rw-r--r-- 1 user docker 3.1K Jul  7 16:35 cdsv2_sidecar.json
-rwxr-xr-x 1 user docker  27M Jul  7 16:43 client
-rwxr-xr-x 1 user docker  90M Jul  7 16:34 envoy
...
```

The same instructions work fine when overriding `TARGET_OUT_LINUX` using `TARGET_OUT_LINUX=/work/out/linux_amd64 make build test`

### Version

```prose
Istio 1.14.1
```

### Additional Information

Machine is running Ubuntu 18.04.6 LTS and has both docker and make

**Comment by ericvn** [comment] 2022-08-11 16:09
I'm trying to understand your problem and have been unable to recreate. 
Running `make build test` does not throw any immediate errors for me on the current main, nor the release-1.14 branch (even using the 1.14.1 tag).

LOCAL_OUT is an environment variable that points to a location on the host, not within the container, hence the prefix LOCAL. The CONTAINER prefix would indicate a location within the container. 

There was some work done in this space in https://github.com/istio/istio/pull/37992 so maybe the commit you are on might be earlier. I do note that before this PR, LOCAL_OUT is not set inside the SHELL, which does match what you are posting. 

Would you confirm the commit you are seeing the issue on.

**Comment by emike922** [comment] 2022-08-11 18:27
I'm afraid it's still occurring on the latest commit on main branch. This time I used a local VM running Ubuntu 20.04.4..

```
$ git clone https://github.com/istio/istio.git
$ cd istio
$ git log -1
commit 9c5f437581c53b336ee22838f2273a0d3cffd98a (HEAD -> master, origin/master, origin/HEAD)
Author: Istio Automation <istio-testing-bot@google.com>
Date:   Thu Aug 11 07:46:07 2022 -0700

    Automator: update proxy@master in istio/istio@master (#40404)
$ make build
Unable to find image 'gcr.io/istio-testing/build-tools:master-d630410610242ef7bc250b49d66e0de8af856f10' locally
master-d630410610242ef7bc250b49d66e0de8af856f10: Pulling from istio-testing/build-tools
...
Digest: sha256:2e07f32808aa72b96645060eaeaffc2031533b33920392a52c4c5c556b0e157e
Status: Downloaded newer image for gcr.io/istio-testing/build-tools:master-d630410610242ef7bc250b49d66e0de8af856f10
TARGET_OUT=/work/out/linux_amd64 ISTIO_BIN=/gobin GOOS_LOCAL=linux bin/retry.sh SSL_ERROR_SYSCALL bin/init.sh
Skipping envoy debug. Set DEBUG_IMAGE to download.
/work/out/linux_amd64/release /work
Downloading envoy: https://storage.googleapis.com/istio-build/proxy/envoy-alpha-d5be2e5cd8794ac1de8758f97147c39d40a9ebae.tar.gz to /work/out/linux_amd64/release/envoy-d5be2e5cd8794ac1de8758f97147c39d40a9ebae


$ make test
go test   -race ./... 2>&1 | tee >(/usr/bin/go-junit-report > /work/out/linux_amd64/junit.xml)
...
ok  	istio.io/istio/pkg/dns/server	0.171s
2022-08-11T18:02:54.024114Z	warn	unable to resolve LOCAL_OUT. Dir /home/ubuntu/istio/out/linux_amd64 does not exist
2022-08-11T18:02:54.025868Z	info	Starting proxy agent
2022-08-11T18:02:54.025976Z	info	starting
2022-08-11T18:02:54.026059Z	info	Envoy exited normally
2022-08-11T18:02:54.026280Z	info	Starting proxy agent
2022-08-11T18:02:54.026372Z	info	starting
2022-08-11T18:02:54.026514Z	info	Agent draining Proxy
--- FAIL: TestNewWithDuplicateOptionsShouldFail (0.01s)
    binary.go:54: lstat : no such file or directory
...
FAIL
FAIL	istio.io/istio/pkg/envoy	0.169s
...
FAIL
make[1]: *** [Makefile.core.mk:411: racetest] Error 1
make: *** [Makefile:44: test] Error 2


$ TARGET_OUT_LINUX=/work/out/linux_amd64 make test
...
$ echo $?
0
```

**Comment by ericvn** [comment] 2022-08-11 20:42
Thanks for the additional detail. I now see what the problem is. The TARGET variables should point to directories on the host, hence they are normally set using $(pwd). In this case, you are overriding it to point to a location within the container. I was incorrect above, in that LOCAL should actually point to directories where the build is occurring (inside the container in this case). There was a change a few months ago in this space.

I need to do a little more investigation as to which way to fix this problem.

**Comment by ericvn** [comment] 2022-08-11 21:44
The reason your change works is you end up forcing LOCAL_HOST to point inside the container, which the Envoy test likes.

I am testing a fix in #40413 to update the test to use TARGET_OUT instead of LOCAL_OUT to see if that fixes the issue. I need to fins a Linux machine to verify the same works within a contianer there (as the pipeline doesn't use a container for that test).

**Comment by ericvn** [comment] 2022-08-12 01:58
I did locate a Linux VM and test the fix in #40413 and test now passed. I t does pass on my Mac as well using a build container.

**Comment by emike922** [comment] 2022-08-12 07:50
Minor clarification: It's not just TestNewWithDuplicateOptionsShouldFail that is affected, but this whole bunch:
```
--- FAIL: TestNewWithDuplicateOptionsShouldFail (0.02s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestNewWithInvalidOptionShouldFail (0.00s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestNewWithoutAdminPortShouldFail (0.00s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestNewWithConfigPathShouldSucceed (0.02s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestNewWithConfigYamlShouldSucceed (0.02s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestStartEnvoyShouldSucceed (0.01s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestStartTwiceShouldDoNothing (0.01s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestHotRestartTwiceShouldFail (0.02s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestHotRestart (0.02s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestCommandLineArgs (0.01s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestShutdown (0.02s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestKillEnvoy (0.01s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestCancelContext (0.01s)
    binary.go:54: lstat : no such file or directory
--- FAIL: TestConfigDump (0.02s)
    binary.go:54: lstat : no such file or directory
FAIL
FAIL    istio.io/istio/pkg/envoy        0.508s
```

I just ran the tests using your changes and the envoy tests are indeed working :)
```
$ git log -1
commit 2491bc88e87fd55972e1bffe9d70f5c290c577ad (HEAD -> pr40413)
Author: Eric Van Norman <ericvn@us.ibm.com>
Date:   Thu Aug 11 16:26:25 2022 -0500

    Revert setenv change, update envoy test to use TARGET_OUT
$ docker volume prune  # I was getting gocache errors after switching from 1.14.3
$ make clean build
$ make test
...
ok      istio.io/istio/pkg/envoy        3.733s  # Works :)
```

But, today again using the CI host, I noticed that istio-agent tests seem to suffer from the same issue:
```
--- FAIL: TestAgent (337.55s)
    --- FAIL: TestAgent/Envoy_lifecycle (150.15s)
        agent_test.go:484: retry.UntilSuccessOrFail: timeout while waiting after 932 attempts (last error: envoy "first agent" is not ready)
    --- FAIL: TestAgent/Envoy_bootstrap_discovery (150.15s)
        agent_test.go:484: retry.UntilSuccessOrFail: timeout while waiting after 932 attempts (last error: envoy "bootstrap discovery" is not ready)
    --- FAIL: TestAgent/GCP (30.03s)
        agent_test.go:595: retry.UntilOrFail: timeout while waiting after 191 attempts (last error: expected condition not met)
FAIL
FAIL    istio.io/istio/pkg/istio-agent  338.496s
```
I think the fix could be the same: https://github.com/istio/istio/blob/81e2be94452faf40d7ec05bb48e6ec31f6794923/pkg/istio-agent/agent_test.go#L656

I also noticed a new/different issue that **does not occur on 1.14.3(!)**, and it does not go away when I override TARGET_OUT_LINUX (even though the LOCAL_OUT warning does disappear, the permission denied error on /tmp remains):
```
2022-08-12T07:13:02.409994Z     warn    unable to resolve LOCAL_OUT. Dir /home/<myuser>/istio/out/linux_amd64 does not exist
2022-08-12T07:13:02.496241Z     info    tf      === Test Framework Settings ===
2022-08-12T07:13:02.496436Z     info    tf      TestID:            pkg_test_framework_integration
RunID:             4c7003a6-aa72-425d-b8a2-88dcb41e8b6b
NoCleanup:         false
BaseDir:           /tmp
Selector:          
FailOnDeprecation: false
CIMode:            false
Retries:           0
StableNamespaces:  false
Revision:          
SkipWorkloads      []
Compatibility:     false
Revisions:         
Hub:               gcr.io/istio-testing
Tag:               latest
PullPolicy:        Always
PullSecret:        
MaxDumps:          10

2022-08-12T07:13:02.496485Z     info    tf      ===============================
2022-08-12T07:13:02.496562Z     info    tf      Test run dir: /tmp/pkg-test-framework-integration-
2022-08-12T07:13:02.496673Z     info    tf      === BEGIN: Setup: 'pkg_test_framework_integration' ===
2022-08-12T07:13:02.496734Z     info    tf      === DONE: Setup: 'pkg_test_framework_integration' (428ns) ===
2022-08-12T07:13:02.496786Z     info    tf      === BEGIN: Test Run: 'pkg_test_framework_integration' ===
--- FAIL: TestSynchronous (0.01s)
    testcontext.go:124: Error creating work dir "/tmp/pkg-test-framework-integration-/TestSynchronous/_test_context": mkdir /tmp/pkg-test-framework-integration-/TestSynchronous: permission denied
2022-08-12T07:13:02.510308Z     info    tf      === BEGIN: Test: 'pkg_test_framework_integration[TestParallel]' ===
2022-08-12T07:13:02.510838Z     info    tf      === DONE (failed):  Test: 'pkg_test_framework_integration[TestParallel] (521.275µs)' ===
--- FAIL: TestParallel (0.01s)
    --- FAIL: TestParallel/root[sync] (0.00s)
        testcontext.go:124: Error creating work dir "/tmp/pkg-test-framework-integration-/TestParallel/root[sync]/_test_context": mkdir /tmp/pkg-test-framework-integration-/TestParallel/root[sync]: permission denied
--- FAIL: TestMix (0.01s)
    testcontext.go:124: Error creating work dir "/tmp/pkg-test-framework-integration-/TestMix/_test_context": mkdir /tmp/pkg-test-framework-integration-/TestMix: permission denied
FAIL
2022-08-12T07:13:02.517155Z     info    tf      === FAILED: Test Run: 'pkg_test_framework_integration' (exitCode: 1) ===
2022-08-12T07:13:02.517684Z     info    tf      === Suite "pkg_test_framework_integration" run time: 20.987518ms ===
FAIL    istio.io/istio/pkg/test/framework/integration   0.250s
```

Should I raise a separate issue for that last one?

**Comment by ericvn** [comment] 2022-08-12 14:20
The reason I don't see all the test failures is some do have a check to only run on Linux, so on my Mac, they return early and I don't see the failure.

I agree that the agent_test.go change makes sense and will add that to my PR.

Also noting that the `warn    unable to resolve LOCAL_OUT. Dir /home/<myuser>/istio/out/linux_amd64 does not exist` has no affect on tests, unless they are using the LOCAL_OUT variable.

As for the last err, I just tried running `T=./pkg/test/framework/... make test` and it passed OK (on the main branch).

**Comment by ericvn** [comment] 2022-08-12 16:24
Closing this PR in favor of https://github.com/istio/common-files/pull/655 which includes the first commit of this PR.

**Closed** 2022-08-12 16:28 UTC
Labels: area/test and release, kind/need more info
