### ISSUE TITLE
"istioctl analyze" doesn't like the 1.9 EnvoyFilters

### ISSUE THREAD

**Issue by esnible** [istio/istio#30265] opened 2021-01-21 15:23 UTC
Using 1.9.0-beta.0:

```
$ istioctl version                 
client version: 1.9.0-beta.0
...

$ istioctl install 
...

$ istioctl analyze --all-namespaces
Warning [IST0133] (EnvoyFilter metadata-exchange-1.10.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter metadata-exchange-1.6.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter metadata-exchange-1.7.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter metadata-exchange-1.8.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter metadata-exchange-1.9.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter stats-filter-1.10.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter stats-filter-1.6.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter stats-filter-1.6.istio-system) Schema validation warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
Warning [IST0133] (EnvoyFilter stats-filter-1.7.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter stats-filter-1.7.istio-system) Schema validation warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
Warning [IST0133] (EnvoyFilter stats-filter-1.8.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter stats-filter-1.9.istio-system) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter tcp-stats-filter-1.10.istio-system) Schema validation warning: using deprecated filter name "envoy.tcp_proxy"; use "envoy.filters.network.tcp_proxy" instead
Warning [IST0133] (EnvoyFilter tcp-stats-filter-1.6.istio-system) Schema validation warning: using deprecated filter name "envoy.tcp_proxy"; use "envoy.filters.network.tcp_proxy" instead
Warning [IST0133] (EnvoyFilter tcp-stats-filter-1.7.istio-system) Schema validation warning: using deprecated filter name "envoy.tcp_proxy"; use "envoy.filters.network.tcp_proxy" instead
Warning [IST0133] (EnvoyFilter tcp-stats-filter-1.8.istio-system) Schema validation warning: using deprecated filter name "envoy.tcp_proxy"; use "envoy.filters.network.tcp_proxy" instead
Warning [IST0133] (EnvoyFilter tcp-stats-filter-1.9.istio-system) Schema validation warning: using deprecated filter name "envoy.tcp_proxy"; use "envoy.filters.network.tcp_proxy" instead
```

I don't know if the problem is the analyzer, or the EnvoyFilters.  The table of deprecated filter names comes from _istio.io/istio/pkg/config/xds/deprecated.go_, not from anything in the analyzers themselves.

**Comment by shamsher31** [comment] 2021-01-21 16:01
@esnible This is a duplicate of https://github.com/istio/istio/issues/30210 and fixed by https://github.com/istio/istio/pull/30220.

**Comment by howardjohn** [comment] 2021-01-21 18:50
fixed by https://github.com/istio/istio/pull/30220

**Closed by howardjohn** 2021-01-21 18:50 UTC
Labels: area/environments, area/user experience
