### ISSUE TITLE
Allow egress requests to variable IP CIDR ranges

### ISSUE THREAD

**Issue by tcnghia** [istio/istio#6146] opened 2018-06-11 15:38 UTC
Currently, outbound requests are blocked by default, unless we turn off proxy for an IP range (https://istio.io/docs/tasks/traffic-management/egress/).

This is difficult for many users, please investigate if we can have a better default for egress.

**Comment by frankbu** [comment] 2018-06-13 16:40
Have you tried configuring a ServiceEntry to enable traffic to a range of hosts? Is that not good enough?

**Comment by mdemirhan** [comment] 2018-06-13 17:31
That is unfortunately not good enough. The user needs to create a ServiceEntry for every possible domain or IP range they need to use and maintenance of this will be a non-starter for many use cases, especially for larger organizations sharing clusters across many teams. We want to get benefits of Istio for traffic within the cluster & ingress traffic to the cluster, but we need to keep the egress open by default. The only way to do this today is via a global configuration at Istio deployment time, or via `traffic.sidecar.istio.io/includeOutboundIPRanges` pod annotation; both of which require you to have a stable IP address range for all of your clusters. However; having a stable IP range is not guaranteed in all hosted environments. 

There are also cases where neither `ServiceEntry` nor `includeOutboundIPRanges` seem to work: For example, we couldn't find a way to make Cloud MemoryStore in GKE work with Istio.

**Comment by andraxylia** [comment] 2018-06-13 20:54
We need to configure a VirtualService for host * that points to a ServiceEntry with resolution NONE. The VirtualService * will be matched after the specific hosts.

**Comment by andraxylia** [comment] 2018-06-13 21:00
There is no solution involving includeIpRanges because we cannot change the iptables without re-deploying the pod due to lack of privileges. So the solution can be only by configuration, as suggested above (we need to test that this works).

**Comment by rshriram** [comment] 2018-06-14 15:00
But the subnet should be stable right? for example, you could specify the include range to be 100.* (assuming that all service IPs are going to be in this /8 prefix. If thats to big, a /16 prefix should help).

**Comment by rshriram** [comment] 2018-06-14 15:36
Here why we haven't done it programmatically

I think the easiest option to allow all external is the includeIP ranges.. but that precludes you from using service entries and have custom routing for one or more external services. 

There is a PR that I proposed where we would program envoy to simply forward unknown IPs to their requested destination (https://github.com/istio/istio/pull/4376) based on https://github.com/istio/istio/issues/3876 request. but this too has caveats when it comes to http services on ports like 80. The problem is that we setup wildcard listeners for all outbound HTTP connections (especially to headless services that do not have a service IP).  So, if a request is going to some external service over port 80 vs going to an internal headless service, there is no easy way to distinguish whether the traffic should be routed via our usual Envoy routing or simply forwarded as is. We would then need to look at the destination IP being requested by the app. If the IP is a service IP or a pod IP, then we pass it through http routing. If not, we forward it as it is..

But this brings us back to the problem of knowing what exactly is the list of service IPs and pod IPs.

One easy way to get the cluster CIDR (of pods) and the service IP cidr is by grepping through the output of ` kubectl cluster-info dump` and searching for -service-cluster-ip-range and -cluster-cidr.

**Comment by mdemirhan** [comment] 2018-06-14 20:57
@andraxylia Can you please provide an example YAML for your suggestion? I will try and see if it works.

@rshriram Thanks for the explanation, but we really need a solution to this. If a single configuration change that @andraxylia mentioned above works, that is great. We cannot ask our customers to create Istio rules for every external call they will do.

Can Istio not query k8s APIs and get cluster-cidr and service-cluster-ip-range periodically and propagate that information periodically to envoy to achieve this? That will solve our problem with "includeIpRanges" for environments that has changing IP ranges.

**Comment by rshriram** [comment] 2018-06-20 21:47
I wish we could. K8s is not exposing them as APIs!! Its just cli flags to api server

**Comment by wansuiye** [comment] 2018-06-26 02:19
@andraxylia Can you please provide an example YAML for your suggestion? I will try and see if it works.

**Comment by andraxylia** [comment] 2018-06-26 05:00
K8s does not support variabe cidr range AFAIK, the cluster and service IP are supplied when the kube-apiserver is started. Even with stable ranges, we still do not have the API. I asked k8s for the API about 1 year ago, when we initially added the include IP ranges, and it is still not there.

**Comment by andraxylia** [comment] 2018-06-26 05:03
Especially because we are dealing with changing CIDRs, we need a more dynamic solution that what k8s apis would offer. Using the VirtualService was suggested by Louis, if this does not work maybe we can make it work.

**Comment by wansuiye** [comment] 2018-06-26 08:16
@andraxylia thanks for your reply, 
you suggested above:"We need to configure a VirtualService for host * that points to a ServiceEntry with resolution NONE. The VirtualService * will be matched after the specific hosts."
how to configurate it ?

**Comment by ssuchter** [comment] 2018-10-10 22:36
I want to check on the status of this. I see that in PR 7236, Shriram indicated that it fixes this issue:

> Fixes #6695, #6146, #5916, #5498,

@rshriram/@andraxylia can you confirm that this issue is actually closed, or should still be open?

**Comment by andraxylia** [comment] 2018-10-10 23:57
In fact, with the latest changes in master, you only need to configure a ServiceEntry for "*", like below. I will close this issue for now, please re-open and ping me if you still have problems.

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc
spec:
  hosts:
  - "*"
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
   resolution: NONE

**Comment by mdemirhan** [comment] 2018-10-11 00:30
@andraxylia Thanks. I am assuming that this will work with all supported protocols (HTTP|HTTPS|GRPC|HTTP2|MONGO|TCP|TLS) - let me know if that is not the case.

Also, is there a way to enable egress over all ports for all protocols?

**Comment by mdemirhan** [comment] 2018-10-11 00:42
@andraxylia  Forgot to ask: in which version of Istio will this be included?

**Comment by wansuiye** [comment] 2018-10-29 07:36
@mdemirhan May I ask if you have verified this function? I did not find any specific code in the master branch. except that tag 1.0.3 has been updated, I wonder if it contains this function...

**Comment by amyroh** [comment] 2018-10-30 19:39
Istio 1.0.3 release notes (https://istio.io/about/notes/1.0.3/) state that "Service entry no longer allows wildcard (*) DNS resolution. The API has never allowed this, however ServiceEntry was erroneously excluded from validation in the previous release."  This issue should be re-opened then.

**Comment by wansuiye** [comment] 2018-10-31 02:56
@amyroh "The API has never allowed this"...,yeah the issue should be re-opened!

**Comment by ThomasWo** [comment] 2018-10-31 19:48
@andraxylia Please reopen as the work-around no longer works (Istio 1.0.3 removed this functionality)

**Comment by erezzarum** [comment] 2018-12-06 12:05
I have hit this one as well, it causes issues in environments where we have services that we can't control their egress endpoints, like crawlers, webhooks, etc..
It will be nice if it would be possible for example to mark those services/pods with a selector to allow only them an egress rule with allow all.

**Comment by dampersand** [comment] 2018-12-07 23:32
Chiming in with my support for this.  Currently migrating from nomad to k8s, which means lots of services still need to talk to their buddies in nomad... not to mention baremetal services.  Asking my developers to tell me ALL the things their stuff might possibly need to talk to is akin to pulling teeth.

**Comment by erezzarum** [comment] 2018-12-09 12:33
> asterix can be replaced by 0.0.0.0/0. that means if just the unknown CIDR blocks is issue, that should help.
> 
> ```
> kind: ServiceEntry
> metadata:
>   name: se-any-cidr
> spec:
>   addresses:
>   - 0.0.0.0/0
>   hosts:
>   - *.com
>   ports:
>   - ... (tcp/udp/...)
>   resolution: NONE
>   location: MESH_EXTERNAL
> ```
> for tcp/udp the hosts will be completely ignored, as it seems for https. so only for port 80 the proxy seems to fight (by accepting only **hosts** listed destinations).

perhaps marking tcp port 80 with a non "http-" name should work?
I will try to see if it works soon.

Thanks

**Comment by mk01** [comment] 2018-12-11 10:38
> perhaps marking tcp port 80 with a non "http-" name should work?

as pre docs & usual istio practice, it should. but to my surprise, proxy on outbound redirect is kicking in regardless of it's name or protocol. tried 
```
    ports:
    - name: tcp
      number: 80
      protocol: HTTP
```
tried
```
    ports:
    - name: tcp
      number: 80
      protocol: TCP
```
tried
```
    ports:
    - name: tcp-svc
      number: 80
      protocol: TCP
```

always getting:
```
root@test-5dcd4cc45f-4vwk9:/# curl www.sme.sk -v
* Rebuilt URL to: www.sme.sk/
*   Trying 104.20.93.202...
* TCP_NODELAY set
* Connected to www.sme.sk (104.20.93.202) port 80 (#0)
> GET / HTTP/1.1
> Host: www.sme.sk
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Tue, 11 Dec 2018 10:37:22 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host www.sme.sk left intact
```

**Comment by costinm** [comment] 2018-12-12 22:18
Moving this back to 1.1 - many people have this issue.

Using the IP range is clearly too difficult and doesn't work in all cases - we need an install option to make 
egress open by default ( by installing a tested set of ServiceEntries). 

AFAIK it'll still need to be done for a list of ports - I don't think we can emulate 'all ports allow egress to original destination by default', and likely we won't be able to do it for the ports where we have stateful sets - not sure about internal http services. But we can at least support 80 / 443 and a list of other ports, with documentation on the impact of having http/tcp mesh services on same ports.

**Comment by linsun** [comment] 2019-01-18 20:07
isn't this partly covered by https://github.com/istio/istio/issues/10330?

> Using the IP range is clearly too difficult and doesn't work in all cases - we need an install option to make
egress open by default ( by installing a tested set of ServiceEntries).

cc @costinm

**Comment by tcnghia** [comment] 2019-01-24 22:01
@linsun can you explain how #10330 will solve this?  Thanks

**Comment by linsun** [comment] 2019-01-25 03:30
because a mesh config param is added via remove deprecated from OutboundTrafficPolicy. REGISTRY_ONLY and ALLOW_ALL #744 (linked from #10330) that will enable users to configure this allow_all easily.

**Comment by vadimeisenbergibm** [comment] 2019-04-14 14:04
@tcnghia Please see this explanation https://istio.io/docs/tasks/traffic-management/egress/#envoy-passthrough-to-external-services, it works starting from Istio 1.1.

**Comment by rdsubhas** [comment] 2019-05-22 10:47
@vadimeisenbergibm it's great, except GKE Istio installs Istio as an addon, core configuration is not editable (addonmanager reconciles core config), and GKE Istio recommends:

> By default, Istio blocks all outbound requests from inside the cluster. To allow outbound requests, create ServiceEntries for permitted destinations.

So the only way is to create a `ServiceEntry` to allow HTTP with `0.0.0.0/0`.

But even keeping GKE Istio aside – maybe user expectation is, a `ServiceEntry` rule for HTTP should work? Do you think there is any core reason for that not working please?

### Test case

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: all-traffic
spec:
  hosts:
  - example.com # this is ignored according to docs
  addresses:
  - 0.0.0.0/0
  ports:
  - name: http
    number: 80
    protocol: tcp
  - name: https
    number: 443
    protocol: tcp
  location: MESH_EXTERNAL
  resolution: NONE
```

From a pod with istio injected:

```
curl -v http://httpbin.org/
< HTTP/1.1 404 Not Found
```

From a pod without istio injected:

```
curl -v http://httpbin.org/
< HTTP/1.1 200 OK
```

**Comment by howardjohn** [comment] 2019-08-05 19:45
Fixed by ALLOW_ANY mode ( the new default) https://istio.io/docs/tasks/traffic-management/egress/egress-control/#envoy-passthrough-to-external-services

**Closed by howardjohn** 2019-08-05 19:45 UTC
Labels: area/networking, kind/customer issue, kind/enhancement
