### ISSUE TITLE
Proxy: Segfault Stackdriver::exportLogEntry()

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#19208] opened 2019-11-26 00:01 UTC
`Version 1.4.0-beta.4-f6313b48f7596972d20a6c889c8a6f294bd6a88f-Clean`

```c++
[Envoy (Epoch 0)] [2019-11-25 23:56:59.446][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x20
[Envoy (Epoch 0)] [2019-11-25 23:56:59.446][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2019-11-25 23:56:59.446][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 26c485161145d45e6acc9a2ce029e556917dfb47/1.12.0/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2019-11-25 23:56:59.446][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7fef563e5890]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.454][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Extensions::Stackdriver::Log::Logger::exportLogEntry() [0x55d0aba1ec82]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.461][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: Envoy::Extensions::Common::Wasm::Null::Plugin::Stackdriver::StackdriverRootContext::onTick() [0x55d0aba1393d]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.468][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: std::__1::__function::__func<>::operator()() [0x55d0abb26bd7]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.475][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Extensions::Common::Wasm::Wasm::tickHandler() [0x55d0abf67a1f]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.481][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: std::__1::__function::__func<>::operator()() [0x55d0abf730a1]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.488][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: event_process_active_single_queue [0x55d0acd8b276]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.495][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: event_base_loop [0x55d0acd89c2e]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.502][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: Envoy::Server::InstanceImpl::run() [0x55d0aca41c33]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.509][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: Envoy::MainCommonBase::run() [0x55d0abbcf7e8]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.517][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: main [0x55d0abbce7c2]
[Envoy (Epoch 0)] [2019-11-25 23:56:59.517][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: __libc_start_main [0x7fef56003b97]
2019-11-25T23:57:00.390055Z	info	Envoy proxy is NOT ready: failed to get server info: failed retrieving Envoy stats: Get http://127.0.0.1:15000/server_info: dial tcp 127.0.0.1:15000: connect: connection refused
2019-11-25T23:57:00.705785Z	error	Epoch 0 exited with error: signal: segmentation fault (core dumped)
2019-11-25T23:57:00.705816Z	info	No more active epochs, terminating
```

**Comment by bianpengyuan** [comment] 2019-11-26 01:02
While trying to reproduce this, I got another crash:
```
[Envoy (Epoch 0)] [2019-11-26 00:31:12.172][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Envoy::Extensions::Common::Wasm::Exports::log() [0x56494eebbbee]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.180][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: std::__1::__function::__func<>::operator()() [0x56494e9691fd]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.187][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: std::__1::__function::__func<>::operator()() [0x56494e9604ed]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.194][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Extensions::Common::Wasm::Null::Plugin::RootContext::onGrpcClose() [0x56494e955356]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.201][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: std::__1::__function::__func<>::operator()() [0x56494ea6e67f]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.208][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: Envoy::Extensions::Common::Wasm::Context::onGrpcClose() [0x56494eead47d]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.214][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: Envoy::Extensions::Common::Wasm::Context::GrpcCallClientHandler::onFailure() [0x56494eeb2140]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.221][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: Envoy::Grpc::GoogleAsyncRequestImpl::onRemoteClose() [0x56494fa7568b]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.227][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: Envoy::Grpc::GoogleAsyncStreamImpl::notifyRemoteClose() [0x56494fa735b5]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.234][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: Envoy::Grpc::GoogleAsyncStreamImpl::handleOpCompletion() [0x56494fa7463a]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.241][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: Envoy::Grpc::GoogleAsyncStreamImpl::onCompletedOps() [0x56494fa712af]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.247][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #12: Envoy::Event::DispatcherImpl::runPostCallbacks() [0x56494f9fffc6]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.254][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #13: event_process_active_single_queue [0x56494fd0ab96]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.261][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #14: event_base_loop [0x56494fd0954e]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.268][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #15: Envoy::Server::WorkerImpl::threadRoutine() [0x56494f9f8338]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.275][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #16: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x56494fe932e3]
[Envoy (Epoch 0)] [2019-11-26 00:31:12.275][30][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #17: start_thread [0x7fb18c8fc6db]
2019-11-26T00:31:12.284371Z     error   Epoch 0 exited with error: signal: segmentation fault
2019-11-26T00:31:12.284417Z     info    No more active epochs, terminating
```

**Comment by bianpengyuan** [comment] 2019-11-26 01:56
Other crashes:
```
[Envoy (Epoch 0)] [2019-11-26 01:09:07.692][26][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x0
[Envoy (Epoch 0)] [2019-11-26 01:09:07.692][26][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2019-11-26 01:09:07.692][26][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: d2a7d319a593f1d75d366cbeb138aa913aa2d282/1.12.0/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2019-11-26 01:09:07.692][26][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7f6e90bfe890]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.699][26][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Envoy::Extensions::Common::Wasm::Exports::get_property() [0x560c9d2fbe21]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.706][26][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: Envoy::Extensions::Common::Wasm::Null::Plugin::getStringValue() [0x560c9cd99e1c]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.712][26][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: Wasm::Common::populateHTTPRequestInfo() [0x560c9cea8b1c]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.719][26][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Extensions::Common::Wasm::Null::Plugin::Stackdriver::StackdriverContext::onLog() [0x560c9cda0117]
```

```
[Envoy (Epoch 0)] [2019-11-26 01:09:07.696][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Envoy::Extensions::Common::Wasm::Exports::get_property() [0x55fe05ab7e21]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.703][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: Envoy::Extensions::Common::Wasm::Null::Plugin::getStringValue() [0x55fe05555e1c]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.710][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: Wasm::Common::populateHTTPRequestInfo() [0x55fe05664b1c]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.716][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Extensions::Common::Wasm::Null::Plugin::Stackdriver::StackdriverContext::onLog() [0x55fe0555c117]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.722][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: std::__1::__function::__func<>::operator()() [0x55fe0566f88a]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.729][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: Envoy::Extensions::Common::Wasm::Context::onLog() [0x55fe05aaebe4]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.735][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: Envoy::Extensions::Common::Wasm::Context::log() [0x55fe05aaeade]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.742][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: Envoy::Http::ConnectionManagerImpl::ActiveStream::~ActiveStream() [0x55fe0681aaf5]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.748][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: Envoy::Http::ConnectionManagerImpl::ActiveStream::~ActiveStream() [0x55fe0681b1de]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.754][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: Envoy::Event::DispatcherImpl::clearDeferredDeleteList() [0x55fe066014f3]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.761][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: event_process_active_single_queue [0x55fe0690cb96]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.767][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #12: event_base_loop [0x55fe0690b54e]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.773][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #13: Envoy::Server::WorkerImpl::threadRoutine() [0x55fe065fa338]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.781][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #14: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x55fe06a952e3]
[Envoy (Epoch 0)] [2019-11-26 01:09:07.781][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #15: start_thread [0x7f5e528bd6db]
```

**Comment by mandarjog** [comment] 2019-11-26 05:32
@bianpengyuan I was using a pre 1.4 build.
I am not seen this issue on 1.4 released proxy.

**Comment by bianpengyuan** [comment] 2019-11-26 06:03
I am using the latest build from master. We need to figure out them for master.

Let me try out 1.4 proxy.

**Comment by bianpengyuan** [comment] 2019-11-27 01:58
1.4 proxy works normally for me for couple of hours. I think we can use this log to track fix those crashes for master.

**Comment by bianpengyuan** [comment] 2019-11-27 17:58
Created https://github.com/envoyproxy/envoy-wasm/issues/327 and https://github.com/envoyproxy/envoy-wasm/issues/326 to track the newly found crashes in master branch. Closing since 1.4.0 does not have the issue.

**Closed by bianpengyuan** 2019-11-27 17:58 UTC
Labels: area/policies and telemetry
