### ISSUE TITLE
Flakey test condition

### ISSUE THREAD

**Issue by sdake** [istio/istio#10757] opened 2019-01-06 01:55 UTC
In a PR I am working on I see the following failure:
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/10756/e2e-bookInfoTests-envoyv2-v1alpha3/12250/build-log.txt

A clean run of this same test case is:
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/10756/e2e-bookInfoTests-envoyv2-v1alpha3/12250/build-log.txt

The code that is killed while looping is this:
https://github.com/istio/istio/blob/master/tests/e2e/framework/kubernetes.go#L496-L514

More debug coming.

**Comment by sdake** [comment] 2019-01-06 01:57
note, I am not sure if my PR is to blame, but if it is, the current test code is a bit brittle.  The PR in question is here:
https://github.com/istio/istio/pull/10562

Cheers
-steve

**Comment by smawson** [comment] 2019-01-11 18:09
Andy this looks like some sort of infra failure, resources were deleted and then something checked them, can you take a look and see what the cause is and pass it on to someone?

**Comment by hklai** [comment] 2019-01-15 18:33
This has been addressed by https://github.com/istio/istio/pull/10878.

**Closed by hklai** 2019-01-15 18:33 UTC
Labels: kind/test failure
