### ISSUE TITLE
helm Down/Upgrading Istio 1.1 <-> 1.0.6 fails

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#11990] opened 2019-02-22 22:36 UTC
**Describe the bug**

With Istio 1.1 installed:

```
$ helm upgrade istio install/kubernetes/helm/istio # istio 1.0.6
Error: UPGRADE FAILED: no ConfigMap with the name "istio-statsd-prom-bridge" found
```

**Expected behavior**
We should be able to downgrade to Istio 1.0.6 from 1.1

**Comment by howardjohn** [comment] 2019-02-22 22:43
Can't go the other way either.

Starting with 1.0.6:
```bash
$  helm upgrade istio install/kubernetes/helm/istio # istio 1.1
Error: UPGRADE FAILED: no PodDisruptionBudget with the name "istio-galley" found
$  helm rollback istio 1
Error: no ConfigMap with the name "istio-statsd-prom-bridge" found
$  helm rollback istio 1
Rollback was a success! Happy Helming
```

**Comment by harpratap** [comment] 2019-02-25 05:26
To iterate on this, can't upgrade from Snapshot 5 to 1.1rc-0 either. 
`Error: UPGRADE FAILED: Job.batch "istio-init-crd-10" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"29ecf762-30c6-11e9-b0a3-c454449ed6a0", "job-name":"istio-init-crd-10"}, Annotations:map[string]string{"sidecar.istio.io/inject":"false"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"crd-10", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc016098fc0), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"istio-init-crd-10", Image:"docker.io/istio/kubectl:1.1.0-rc.0", Command:[]string{"kubectl", "apply", "-f", "/etc/istio/crd-10/crd-10.yaml"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"crd-10", ReadOnly:true, MountPath:"/etc/istio/crd-10", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc046dedfc8), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"istio-init-service-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc0527000e0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil)}}: field is immutable && Job.batch "istio-init-crd-11" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"29ed7b1f-30c6-11e9-b0a3-c454449ed6a0", "job-name":"istio-init-crd-11"}, Annotations:map[string]string{"sidecar.istio.io/inject":"false"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"crd-11", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc016099e40), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"istio-init-crd-11", Image:"docker.io/istio/kubectl:1.1.0-rc.0", Command:[]string{"kubectl", "apply", "-f", "/etc/istio/crd-11/crd-11.yaml"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"crd-11", ReadOnly:true, MountPath:"/etc/istio/crd-11", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc0413bddc8), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"istio-init-service-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc0527008c0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil)}}: field is immutable && Job.batch "istio-init-crd-certmanager-10" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"job-name":"istio-init-crd-certmanager-10", "controller-uid":"29eeb602-30c6-11e9-b0a3-c454449ed6a0"}, Annotations:map[string]string{"sidecar.istio.io/inject":"false"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"crd-certmanager-10", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc04d4e3100), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"istio-init-crd-certmanager-10", Image:"docker.io/istio/kubectl:1.1.0-rc.0", Command:[]string{"kubectl", "apply", "-f", "/etc/istio/crd-certmanager-10/crd-certmanager-10.yaml"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"crd-certmanager-10", ReadOnly:true, MountPath:"/etc/istio/crd-certmanager-10", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc042e0fa38), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"istio-init-service-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc0400c6a10), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil)}}: field is immutable'

**Comment by munrodg** [comment] 2019-02-26 19:09
@sdake can you take a look at this one?

**Comment by duderino** [comment] 2019-02-26 20:19
Optimistically assigning to @sdake but if you don't have the cycles we can find someone else.  Thank you :)

**Comment by harpratap** [comment] 2019-02-27 06:32
Change in PR #10019 is causing the upgrade to fail since the http-monitoring port has changed and the new port cannot have duplicate name when doing a patch operation.

**Comment by ostromart** [comment] 2019-03-01 01:01
I'm blocked on https://github.com/istio/istio/issues/11868 because of this issue. istio-galley PodDisruptionBudget is defined in my case so I'm not sure how to even try to work around this:

helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
Error: UPGRADE FAILED: no PodDisruptionBudget with the name "istio-galley" found

kc get PodDisruptionBudget -n istio-system istio-galley -o yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: 2019-02-28T23:22:32Z
  generation: 1
  labels:
    app: galley
    chart: galley
    heritage: Tiller
    istio: galley
    release: istio
  name: istio-galley
  namespace: istio-system
  resourceVersion: "4900"
  selfLink: /apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istio-galley
  uid: b98998fb-3baf-11e9-acd7-42010a8000f8
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: galley
      istio: galley
      release: istio
status:
  currentHealthy: 1
  desiredHealthy: 1
  disruptedPods: null
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1

**Comment by linsun** [comment] 2019-03-01 13:50
@ostromart in your comment, is that upgrade or downgrade?  My guess is downgrade from 1.1 to 1.0?

**Comment by linsun** [comment] 2019-03-01 13:51
seems it is a known issue of helm

https://github.com/helm/helm/issues/2914

**Comment by linsun** [comment] 2019-03-01 14:05
would be good to check if `--force` param to helm fixes this.

**Comment by sdake** [comment] 2019-03-01 16:06
will take a look today.

**Comment by sdake** [comment] 2019-03-01 16:07
@harpratap thanks for doing the legwork of finding the offending patch.

Cheers
-steve

**Comment by duderino** [comment] 2019-03-01 21:43
@linsun @ostromart @sdake if we have a forced choice of pod disruption budget vs. helm downgrade, which one should we throw under the bus?

**Comment by sdake** [comment] 2019-03-02 06:25
here was my workflow:
```
### Insalling 1.0.6:

sdake@beast-01:~/istio-1.0.6$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system

### Upgrading to 1.1.0-rc1:

sdake@beast-01:~/istio-1.1.0-rc.1$ helm upgrade --install istio-init install/kubernetes/helm/istio-init --namespace istio-system
Release "istio-init" does not exist. Installing it now.
sdake@beast-01:~/istio-1.1.0-rc.1$ helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
Error: UPGRADE FAILED: no MeshPolicy with the name "default" found
sdake@beast-01:~/istio-1.1.0-rc.1$ helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
Error: UPGRADE FAILED: no PodDisruptionBudget with the name "istio-galley" found
```

**Comment by sdake** [comment] 2019-03-02 06:26
@duderino UPGRADE > Downgrade > pdb

**Comment by sdake** [comment] 2019-03-02 06:27
Note these problems only affect the `helm install/upgrade` paths, but do not affect the `helm template/kubectl apply` paths.

**Comment by sdake** [comment] 2019-03-02 06:28
@howardjohn helm has a specific rollback command `helm rollback` which should in theory rollback from 1.1.0.rc1 to 1.0.6.

**Comment by sdake** [comment] 2019-03-02 06:29
Note it appears upgrade is DOA: https://github.com/istio/istio/issues/11990#issuecomment-468890884

This was a fresh kubernetes cluster.  This problem may not exist on a cluster that has been through reuse.

**Comment by sdake** [comment] 2019-03-02 06:42
I reinitialized my cluster including helm, and had the same results. mtls was removed from 1.1-rc1 (or earlier) as a default.  Helm does not handle the removal of configmaps or custom resources particularly well.

Note kubectl apply paths work well in any condition.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-02 06:47
My initial off-the-cuff recommendations without personally testing them:
1. revert the change that removed mtls.  With the new installer, I am hopeful it will be possible to deprecate automated MTLS configuration in 1.2.
1. after this problem is fixed, I suspect we will run into problems with pod disruption budgets.  I would then revert these changes.
1. after this problem is fixed, I am hopeful upgrade and rollback work with helm commands.

We really need to make a strong effort in 1.2 to ween people from the usage of Helm for the full deployment of istio.  If operators want a Helm integration point (which they probably want), they could always use the operator - which should only contain the basics (a deployment, service, cluster role, etc).

Cheers
-steve

**Comment by sdake** [comment] 2019-03-02 06:53
@harpratap just an FYI, the Istio project does not support upgrading from an arbitrary snapshot or release candidate to a different arbitrary release candidate.  The only thing we support is 1.0.6->1.1.0 (when it is released).

Cheers
-steve

**Comment by sdake** [comment] 2019-03-02 07:16
i was able to reproduce this issue with current tip of release-1.1 (including https://github.com/istio/istio/pull/12177).  Headed to bed - will sort out the revert chain this weekend to get to a functional upgrade.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-02 20:54
This fixes part of the problem https://github.com/istio/istio/issues/11868.  Will test that PR and see if it fixes all of the problems.  nice work @morvencao for sorting that one out.

Cheers
-steve

**Comment by morvencao** [comment] 2019-03-03 10:48
@ostromart  @linsun I have tried helm upgrade/rollback locally for several times, just blocked by https://github.com/istio/istio/issues/12154 but never encountered issue like this
```
Error: UPGRADE FAILED: no PodDisruptionBudget with the name "istio-galley" found
```
Any detailed reproduced steps for this.

And `PodDisruptionBudget` is introduced in Istio 1.1, `helm/tiller` is supposed to handle the new added resources. 

@sdake As I mentioned in https://github.com/istio/istio/issues/12154#issuecomment-468696914, the change of removal mtls from `post-install hook` will break `helm upgrade`, suggest to put it back to `post-install hook`: https://github.com/istio/istio/pull/12173/files

**Comment by sdake** [comment] 2019-03-03 17:28
@morvencao Once your PR merges, I will test upgrade/rollback.  If all is good, all is good :)

The PDB thiing happens after two upgrades without that patch.  This is the wrong way to upgrade - as the deployment is in a failed state.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-03 17:30
> here was my workflow:
> 
> ```
> ### Insalling 1.0.6:
> 
> sdake@beast-01:~/istio-1.0.6$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system
> 
> ### Upgrading to 1.1.0-rc1:
> 
> sdake@beast-01:~/istio-1.1.0-rc.1$ helm upgrade --install istio-init install/kubernetes/helm/istio-init --namespace istio-system
> Release "istio-init" does not exist. Installing it now.
> sdake@beast-01:~/istio-1.1.0-rc.1$ helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
> Error: UPGRADE FAILED: no MeshPolicy with the name "default" found
> sdake@beast-01:~/istio-1.1.0-rc.1$ helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
> Error: UPGRADE FAILED: no PodDisruptionBudget with the name "istio-galley" found
> ```

@morvencao above was my workflow without PR https://github.com/istio/istio/issues/12154 that produced the PDB problem.  This is a non-problem because if a deployment of istio fails to upgrade, I think the whole thing is pretty much cratered.

**Comment by sdake** [comment] 2019-03-03 17:31
@duderino the TLDR is merge https://github.com/istio/istio/issues/12154 - and we think all is good with upgrade/rollback with Helm+Tiller.  With helm template+kubectl apply - everything works gloriously as is.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-03 17:34
I see https://github.com/istio/istio/pull/12177 has merged, will test upgrade/rollback from tip of release-1.1.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-03 19:36
All prior commentary is wrong.  https://github.com/istio/istio/pull/12173 may fix the upgrade/downgrade paths however, it has not yet merged.

**Comment by morvencao** [comment] 2019-03-04 02:31
@sdake See my verify results: https://github.com/istio/istio/issues/11868#issuecomment-469096645 Hopefully we can merged https://github.com/istio/istio/pull/12173 ASAP.

**Comment by duderino** [comment] 2019-03-04 18:10
On #12173 I will merge as soon as I see a lgtm form @sdake, but he may say this is too risky for 1.1.  Heads up

**Comment by sdake** [comment] 2019-03-04 18:33
This issue is a dup of https://github.com/istio/istio/issues/12154.

@duderino basically @morvencao 's work is a revert of someone else's work.  He introduced the original functionality.



Tested this PR https://github.com/istio/istio/pull/12173#pullrequestreview-210297980 and is good for merge.

**Comment by sdake** [comment] 2019-03-04 18:51
closing as a dup.

**Closed by sdake** 2019-03-04 18:51 UTC
Labels: area/environments
