### ISSUE TITLE
backend service stops responding when mixer is down.

### ISSUE THREAD

**Issue by jhaals** [istio/istio#549] opened 2017-08-09 11:34 UTC
Hi!

I've noticed that I can't reach my backend service via istio-ingress if the istio-mixer goes down, this is also true when not going via istio-ingress.
The overview image in the documentation shows mixer as the central point of communication but reading the FAQ gives a contradicting answer.

https://istio.io/faq/
> Reliability. Mixer and its open-ended extensibility model represents the most complex parts of the data path processing pipeline. By hosting this functionality in Mixer rather than Envoy, it creates distinct failure domains which enables Envoy to continue operating even if Mixer fails, preventing outages.

Is it suppose to work if mixer goes down temporarily?

**Comment by kyessenov** [comment] 2017-08-09 23:17
There's a fail-open and fail-closed options in Mixer filter in Envoy. I'm not sure what the current default is. @geeknoid and @qiwzhang this probably deserves updating the doc about.

**Comment by qiwzhang** [comment] 2017-08-09 23:24
default is fail-open.   So if mixer is done,   Check will pass.

**Comment by geeknoid** [comment] 2017-08-09 23:26
Note that Mixer proper is on a best-effort plan. If a backend Mixer depends
on fails, Mixer passes the failure on up to the caller. It's up to the
caller (Envoy) to decide whether to fail open or closed.

**Comment by gimaker** [comment] 2017-08-10 14:51
The default is documented here: https://github.com/istio/proxy/blob/ecb6869a3a4ceb1ebc3aaf4bba0069177e688086/src/envoy/mixer/README.md#how-to-change-network-failure-policy

It's not obvious if and how that can by changed by a user though.

**Comment by gimaker** [comment] 2017-08-10 15:04
I don't know if it matters but requests stopped working when mixer was down even though we had no access control, quotas or such configured.

If every single incoming request has to wait for a round-trip to mixer that seems like it could cause interesting failure scenarios if mixer is slow or down altogether.

**Comment by qiwzhang** [comment] 2017-08-10 16:10
@gimaker In Envoy config, in the mixer filter config,  

 "filters": [
      "type": "decoder",
      "name": "mixer",
      "config": {
        "network_fail_policy": "close",
        ...

you can use above mixer filter config to change the network_fail_policy.

Mixer Check result can be cached in Proxy.  You can enable check cache by adding  check_cache_keys in the current version.   

         "check_cache_keys": [
              "request.host",
              "request.path",
              "origin.user"
         ]

In the next version, we are going to change the proxy cache code.   Mixer will determine which attributes should be used for cache.  "check_cache_keys" will not be supported any more.

**Comment by qiwzhang** [comment] 2017-08-25 16:47
@jhaals 
In my test, Envoy will not block requests if mixer is down.   I need more information to debug it.
Could you provide Envoy config and log output?  It will be even better if it is in "-l debug" mode.

**Comment by gimaker** [comment] 2017-08-31 14:44
If I understand correctly, it is expected that requests fail when mixer is down (for Istio 0.1.6), since the default is fail-open. In other words, things seem to work as expected.

Although this would suggest otherwise:

> default is fail-open. So if mixer is done, Check will pass.

It would be nice if there was a way for an operator to change the behaviour to fail-close. I couldn't figure out a way to do this without modifying pilot (to change the config pushed out) or proxy (to change the default).

Documentation on how mixer and envoy interacts would be useful in the future, so an operator can reason about what happens if mixer fails and how it affects latency (I understand how there any big changes underway to how it works and that it doesn't necessarily make sense to document anything until those changes has landed).

---

I can easily reproduce this (expected) behaviour using the bookinfo example by taking the following steps:

1. Deploy bookinfo example: `$ kubectl apply -f <(istioctl kube-inject --verbosity 100 -f apps/bookinfo/bookinfo.yaml)`

2. Verify that everything works okay with mixer up and running:

```
$ curl -vs 35.195.76.246/productpage > /dev/null 
*   Trying 35.195.76.246...
* Connected to 35.195.76.246 (35.195.76.246) port 80 (#0)
> GET /productpage HTTP/1.1
> Host: 35.195.76.246
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 4098
< server: envoy
< date: Thu, 31 Aug 2017 13:42:14 GMT
< x-envoy-upstream-service-time: 175
< 
{ [4098 bytes data]
* Connection #0 to host 35.195.76.246 left intact
```

3. Delete mixer pod: `$ kubectl delete pods -l istio=mixer`

4. Immediately run `curl` again before the new mixer pod comes up. This leads to a 504 Gateway timeout:

```
$ curl -sv 35.195.76.246/productpage > /dev/null
*   Trying 35.195.76.246...
* Connected to 35.195.76.246 (35.195.76.246) port 80 (#0)
> GET /productpage HTTP/1.1
> Host: 35.195.76.246
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 504 Gateway Timeout
< content-length: 24
< content-type: text/plain
< date: Thu, 31 Aug 2017 13:52:00 GMT
< server: envoy
< 
* Connection #0 to host 35.195.76.246 left intact
```

I'd be happy to provide logs and envoy configs if needed, but given that things seem to work as expected I'm not sure that is useful.

**Comment by qiwzhang** [comment] 2017-08-31 16:43
@gimaker Your understanding is wrong.  fail-open means if any calls to Mixer fail at network layer, the Mixer Check should pass,  the original requests should proceed to the backend. 

So the behaviors you experienced is wrong. It is a bug.

If you can try with latest Istio code,  (I think 0.2 is out),  it will be great.  It is wasting time to debug old code.  The proxy code has been changed dramatically.  If still happen,  see if you can turn on "-l debug" when Envoy, and get me the Envoy log.

Thanks.

PS, you can open an issue for istio/pilot to allow config network_fail_policy into envoy config.

**Comment by gimaker** [comment] 2017-09-25 12:10
Running istio from master I can confirm that requests succeed even if mixer is unavailable, so the bug seems to be fixed and this issue can be closed. (I did notice latency increasing by 2 seconds when mixer is unavailable, which I assume is expected.)

Maybe I'm daft but I still think it's very non-intuitive that "fail-open" means that requests are allowed when mixer is down (no current flows in an open circuit), but oh well.

**Closed** 2017-09-25 13:01 UTC
Labels: docs
