### ISSUE TITLE
istioctl: Don't use xDS api's in a way that breaks on upgrade

### ISSUE THREAD

**Issue by gargnupur** [istio/istio#22164] opened 2020-03-13 18:40 UTC
Currently, some of the json unmarshaling in pilot fails whenever xDS API's upgrades.
Use it in a way, we are safe from them.

EX: PR: https://github.com/istio/istio/pull/22145
Test that breaks: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22145/integ-pilot-k8s-tests_istio/9722 because it needs https://github.com/envoyproxy/envoy/pull/10109/files change.

**Comment by kyessenov** [comment] 2020-03-13 18:41
cc @howardjohn -- this is preventing us from picking up proxy changes for older control planes.

**Comment by howardjohn** [comment] 2020-03-13 18:43
cc @esnible we should at least ignore unknown fields possibly?

This is istioctl by the way, not Pilot.

**Comment by esnible** [comment] 2020-04-27 15:23
@howardjohn Do you think this a duplicate of https://github.com/istio/istio/issues/20714 ?

**Comment by howardjohn** [comment] 2020-04-27 15:26
Yes, we can consolidate

**Closed by howardjohn** 2020-04-27 15:26 UTC
Labels: area/user experience, lifecycle/needs-triage
