### ISSUE TITLE
galley validation still expects older gateway resource format

### ISSUE THREAD

**Issue by zhqworld** [istio/istio#11686] opened 2019-02-12 01:55 UTC
**Describe the bug**
With sds node agent on ingress gateway, there is no more need to provide certificate path in gateway resources, but it failed with following yaml:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https-name1
      protocol: HTTPS
    tls:
      mode: SIMPLE
    hosts:
    - "httpbin1.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "httpbin1.example.com"
  gateways:
  - https-gateway
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
```

The failure message:

```
virtualservice.networking.istio.io "httpbin" created
Error from server: error when creating "STDIN": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 2 errors occurred:
```

**Expected behavior**
Gateway resource that does not specify a certificate path should be accepted by Galley given that the SDS agent loads the certificates dynamically from the API server.

**Steps to reproduce the bug**
After the Istio installation, the SDS agent for ingress gateway needs to be enabled in the configuration. Then use above yaml to reproduce the bug.

**Version**
kubernetes version: 1.12.5
Istio version:
image: gcr.io/istio-release/galley:release-1.1-20190211-09-16
imageID: docker-pullable://gcr.io/istio-release/galley@sha256:7154d0dedc05a432186cde9c6b258398eb733dbd17c3dfef217fa945db67e97b

**Installation**
Installed using helm.

**Environment**
private environment

**Cluster state**
n/a

**Comment by uk000** [comment] 2019-02-13 19:58
Apprently istio-1.1.0-snapshot.6 has the same issue as well.

```
Error from server: error when creating "./temp.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 2 errors occurred:

* SIMPLE TLS requires a server certificate
* SIMPLE TLS requires a private key
```

**Comment by duderino** [comment] 2019-02-13 21:26
@liminw will triage

@ozevren @ayj @myidpt @wenchenglu @wattli FYI

**Comment by ayj** [comment] 2019-02-13 21:37
[validateTLSOptions](https://github.com/istio/istio/blob/72683f6bb7e7e9d3f95b11293dd97cc8eb13aa66/pilot/pkg/model/validation.go#L499-L523), which is called by ValidateGateway, hasn't been updated to allow this combination yet.

**Comment by liminw** [comment] 2019-02-13 22:02
According to @JimmyCYJ , this is expected behavior. @zhqworld, you can put arbitrary string for "serverCertificate" and "privateKey" fields, because the validation code requires that the fields are not empty. This is a slight behavior change from what Jimmy demoed last time. Let us know if this works for you.

Jimmy is working on a tutorial for this Ingress cert manager feature, and he will clarify it in the document.

**Comment by zhqworld** [comment] 2019-02-13 23:14
By providing fake field can let galley pass the validation but ingress gateway component does not fetch certs from ingress sds agent as expected, even though sds agent container is running.

Note:  sds agent feature works with version1.1.0-snapshot.5
Please check why it's not working with below version:
1.1.0-snapshot.6
release-1.1-20190211-09-16

**Comment by JimmyCYJ** [comment] 2019-02-13 23:29
Hi, I am adding doc into istio.io for this feature. https://github.com/istio/istio.io/pull/3224.
Below is an example for the gateway definition. The feature is disabled by default. 
https://github.com/istio/istio/blob/27bfde8a011339ab63117b629fe0bf9f16d8fa2f/install/kubernetes/helm/subcharts/gateways/values.yaml#L17

```
$ cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: "use sds"         # arbitrary non-empty string
      privateKey: "use sds"                # arbitrary non-empty string
      credentialName: "httpbin-credential" # must be the same as secret
    hosts:
    - "httpbin.example.com"
EOF
```

**Comment by uk000** [comment] 2019-02-14 00:33
Confirmed the correct config (with serverCertificate, privateKey and credentialName) works with snapshot.6.
Apparently there was a change between snapshot.5 and 6. Snapshot.5 works even without these config fields, because it likely matched certs based on host/cn without explicitly passing the credentialName.
We had tried with arbitrary values serverCertificate and privateKey, but didn't know the new field "credentialName" had to be used as well.

**Comment by JimmyCYJ** [comment] 2019-02-14 00:43
Thanks for confirming that. There were API and function-wise changes recently. This final version will be introduced in the istio.io page once that PR is in.

**Comment by liminw** [comment] 2019-02-14 23:07
@zhqworld Can we close this issue?

**Comment by zhqworld** [comment] 2019-02-14 23:11
yes. Will we get istio document updated as well for the gateway tls section?

**Comment by liminw** [comment] 2019-02-14 23:24
@JimmyCYJ can confirm, but it seems that his PR (https://github.com/istio/istio.io/pull/3224) for updating the documentation is close to be merged. 

I will close this PR since the problem is already solved.

**Comment by duderino** [comment] 2019-02-15 14:50
Please leave this issue open until the PR is merged

**Comment by JimmyCYJ** [comment] 2019-03-01 23:32
The user guide [PR](https://github.com/istio/istio.io/pull/3224) is merged. I am closing this issue. Thanks.

**Closed by JimmyCYJ** 2019-03-01 23:32 UTC
