### ISSUE TITLE
Add egress rules to istioctl

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#552] opened 2017-08-10 14:05 UTC
Add egress-rule to istioctl, without taking egress-rules into effect yet. Part of https://github.com/istio/istio/issues/496

Format:
```yaml
type: egress-rule
spec:
    name: cnn
    domain:  "*cnn.com"
    ports:
      - port: 80
         protocol: http
      - port: 8080
         protocol: http
   use_egress_proxy: true
```

**Comment by ldemailly** [comment] 2017-08-17 00:23
I see commits but no PR ?

**Comment by vadimeisenbergibm** [comment] 2017-08-17 07:20
I am still working on it. Please note my convention - I add a string `istio/istio#<issue number>` to every commit, so every commit is linked to the issue even before a PR is submitted, and if not squashed, continues to point to an issue. So every commit always points to some issue - either not squashed, or squashed as part of a PR, in the PR's comment.

**Comment by ldemailly** [comment] 2017-08-17 20:38
Thanks for the explanation - I think that may be a bit floody/verbose but it's ok if it's your strong preference (and for an issue where only you is subscribed )

**Comment by vadimeisenbergibm** [comment] 2017-08-22 08:17
@ldemailly It is not my strong preference, so if this practice is discouraged by the Istio developers community, I am OK to stop using it.
Please note that with an issue you create it first and then start working on it. With a PR, you start working and then submit it after the work is done. So with an issue, you announce to others that there is an issue, you work on it, some details on the issue, references to design doc etc. The others can see it and your work in progress and comment before you compete your work. Somebody can comment that this work is not needed or covered by some other issue, etc. And you can create a hierarchy of issues - epics, set milestones, again - before you complete the work.

**Comment by andraxylia** [comment] 2017-08-22 15:33
I actually like this, I was not aware this is possible.

**Comment by andraxylia** [comment] 2017-08-22 15:35
It is not discouraged, we just did not encounter it in Istio. I agree with Laurent that it gets a bit verbose, but it is nice to know there is progress made on it.

**Comment by ldemailly** [comment] 2017-08-22 20:28
I think having the issue first is great (and everybody should do that), and saying you're working on it when you start (too), but I don't think there should be a bunch of invisible commits/updates - do your PR when it starts being in shape (possibly marking it as "wip"/not requesting a review yet) and update that rather than the issue ?

**Comment by andraxylia** [comment] 2017-08-22 21:00
This will be better indeed, as long as the PR links to the issue, and we can easily track if the issue is worked on.

**Comment by vadimeisenbergibm** [comment] 2017-08-28 13:07
@ldemailly @andraxylia OK, I see, next time I will do it with a WIP PR, linked to the issue. Thank you!

**Comment by rshriram** [comment] 2017-09-29 17:35
solved..

**Closed by rshriram** 2017-09-29 17:35 UTC
Labels: enhancement
