### ISSUE TITLE
[test-framework] Add mTLS support for local environment

### ISSUE THREAD

**Issue by nmittler** [istio/istio#8350] opened 2018-08-29 20:51 UTC
All communication for local testing is currently plaintext.  We need to support mTLS within the local mesh.

**Comment by hklai** [comment] 2018-09-04 18:59
@JimmyCYJ could you help with this?

**Comment by ozevren** [comment] 2019-04-19 16:09
@JimmyCYJ is this something that you will/can work for Code Mauve/Release 1.2?

**Comment by JimmyCYJ** [comment] 2019-04-19 18:22
This depends on a stand-alone Citadel https://github.com/istio/istio/issues/9177, let me check with @myidpt

**Comment by pitlv2109** [comment] 2019-06-14 18:36
Any update on this work?

**Comment by nmittler** [comment] 2019-06-14 19:13
@pitlv2109 I'm working on a rewrite of the native echo component using docker (#14614). Once that lands, this issue should be done (or very close).

**Comment by myidpt** [comment] 2019-06-14 22:22
Downgrading it to P1. Jimmy is working on writing tests to increase the test coverage now.

**Comment by howardjohn** [comment] 2019-10-03 17:21
Duplicate of https://github.com/istio/istio/issues/13778

**Closed by howardjohn** 2019-10-03 17:21 UTC
Labels: area/test and release
