### ISSUE TITLE
build istio and proxy RPMs is broken

### ISSUE THREAD

**Issue by zachidan** [istio/istio#19118] opened 2019-11-21 11:55 UTC
**Bug description**
tried to build istio and sidecar rpms for RedHat VM mesh expansion, but failed with a lot of errors because the build scripts are not up-to-date.

**Steps to reproduce the bug**
Steps to build the RPM package:

- Clone Istio repo (https://github.com/istio/istio.git) into dir /root/git/src/istio and cd into this dir
- Run cmd make VERSION=1.4.0 rpm/builder-image to build docker builder image: istio-rpm-builder
- Run cmd make VERSION=1.4.0 rpm/proxy to build, but had some git issue during build
- Try below command to debug the issue:
    docker run -it \\
    -v ${GO_TOP}:${GO_TOP} \\
    -w /builder \\
    -e USER=${USER} \\
    -e ISTIO_ENVOY_VERSION=${ISTIO_ENVOY_VERSION} \\
    -e ISTIO_GO=${ISTIO_GO} \\
    -e ISTIO_OUT=${ISTIO_OUT} \\
    -e PACKAGE_VERSION=${PACKAGE_VERSION} \\
    -e USER_ID=$(shell id -u) \\
    -e GROUP_ID=$(shell id -g) \\
    istio-rpm-builder \\
    bash
-  In docker constainer bash, run script in tools/packaging/rpm/build-proxy-rpm.sh, found the issue was because CentOS's Git version is too low, so upgrade Git to latest version
-  Run tools/packaging/rpm/build-proxy-rpm.sh again, got C++ compilation errors, logs are attached.

**Environment where bug was observed (cloud vendor, OS, etc)**
RedHat 7

**Comment by zachidan** [comment] 2019-11-21 12:14
Fixed by #19119

**Comment by jwendell** [comment] 2019-11-21 19:31
duplicate of https://github.com/istio/istio/issues/16787

**Closed by jwendell** 2019-11-21 19:31 UTC
