### ISSUE TITLE
iptables script does not intercept users whose group ID equals the number specified with -u option

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6576] opened 2018-06-23 14:43 UTC
iptables script from Istio does not intercept users whose group ID equals the number specified with -u option. 

https://github.com/istio/istio/blob/master/tools/deb/istio-iptables.sh#L265

For example, say there are two users: user-a and user-b:

username  |  user-id  |  group-id
user-a        |  5001     |  8001
user-b        |  8001     |  8001

If I evoke the script with: "sudo ./iptables.sh -u 8001", then both user-a and user-b will not be intercepted.

**Comment by ymesika** [comment] 2018-06-24 10:53
@andraxylia Should we just replace L264-265 with:

```command
iptables -t nat -A ISTIO_OUTPUT -m owner --uid-owner ${uid} --gid-owner ${uid} -j RETURN
```

**Comment by ymesika** [comment] 2018-06-24 15:03
And it's the exact duplicate of #6557

**Closed by ymesika** 2018-06-24 15:03 UTC
Labels: area/networking, community/help wanted
