### ISSUE TITLE
Sampling value for tracing configuration cannot be overriden by deployment metadata specification using proxy.istio.io/config annotation

### ISSUE THREAD

**Issue by mkaman** [istio/istio#30141] opened 2021-01-16 16:04 UTC
**Bug description**

Related documentation:
https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#create-a-meshconfig-with-trace-settings

No tracing data of the pods that have been overriden by proxy.istio.io/config annotation could be sent to / viewed on jaeger, when sampling value is specified in deployment metadata specification using proxy.istio.io/config annotation. There is no problem when only meshConfig is used / configured.

```yml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 20
```
Deployment metadata:

```yml
spec:
  template: 
    metadata:
      annotations:
        proxy.istio.io/config: |
          tracing:
            sampling: 100
```
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ X] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

The meshConfig sampling value (in this case 20) should be overridden by using proxy.istio.io/config annotation (100)  and tracing data should be collected by jaeger.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl:
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (5 proxies)

kubectl:
Client Version: v1.19.0
Server Version: v1.20.0

minikube 
version: v1.16.0

**How was Istio installed?**

via istioctl 

**Environment where the bug was observed (cloud vendor, OS, etc)**

Ubuntu 20.04

[bug-report.zip](https://github.com/istio/istio/files/5824697/bug-report.zip)

**Comment by diranged** [comment] 2021-01-19 18:33
I can confirm this is broken. We took the productpage deployment from the bookinfo example and tried this setting. It looks like the annotation is _replacing_ the tracing config, rather than being merged with it. When that happens, the cluster-level setting for the tracer endpoint goes away.

The "good" config (no custom annotation) configures the proxy like this:
```
            "PROXY_CONFIG": {
              "binaryPath": "/usr/local/bin/envoy",
              "concurrency": 2,
              "configPath": "./etc/istio/proxy",
              "controlPlaneAuthPolicy": "MUTUAL_TLS",
              "discoveryAddress": "istiod.istio-system.svc:15012",
              "drainDuration": "45s",
              "envoyAccessLogService": {},
              "envoyMetricsService": {},
              "parentShutdownDuration": "60s",
              "proxyAdminPort": 15000,
              "proxyMetadata": {
                "DNS_AGENT": ""
              },
              "serviceCluster": "productpage.bookinfo-example",
              "statNameLength": 189,
              "statusPort": 15020,
              "terminationDrainDuration": "5s",
              "tracing": {
                "zipkin": {
                  "address": "collector.jaeger:9411"
                }
              }
            },
```

Meanwhile once you add in the annotation, we get this new proxy config that is missing the zipkin address:
```
    "PROXY_CONFIG": {
              "binaryPath": "/usr/local/bin/envoy",
              "concurrency": 2,
              "configPath": "./etc/istio/proxy",
              "controlPlaneAuthPolicy": "MUTUAL_TLS",
              "discoveryAddress": "istiod.istio-system.svc:15012",
              "drainDuration": "45s",
              "envoyAccessLogService": {},
              "envoyMetricsService": {},
              "parentShutdownDuration": "60s",
              "proxyAdminPort": 15000,
              "proxyMetadata": {
                "DNS_AGENT": ""
              },
              "serviceCluster": "productpage.bookinfo-example",
              "statNameLength": 189,
              "statusPort": 15020,
              "terminationDrainDuration": "5s",
              "tracing": {
                "sampling": 100
              }
            },
```

**Comment by diranged** [comment] 2021-01-19 23:00
Ok - I see at https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#available-tracing-configurations this quote:

```Note that any pod annotations added for tracing configuration overrides global settings. In order to preserve any global settings you should copy them from global mesh config to pod annotations along with workload specific customization. In particular, make sure that the tracing backend address is always provided in the annotations to ensure that the traces are reported correctly for the workload.
```

This probably needs to be called out more loudly - its very easy to gloss over that section and skip right to the https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#using-proxy-istio-io-config-annotation-for-trace-settings section.. :(

**Comment by mkaman** [comment] 2021-01-20 14:46
Thank you very much @diranged for clarifying the point. But there seems to be a risk to transfer all global mesh configs to pod level in order to change a specific configuration. It will be more useful and less error-prone when pod annotations just override "related" meshconfigs. And in this case, unrelated configurations that pods don't aware of would apply at all times.

**Comment by dgpat** [comment] 2021-02-12 07:27
@mkaman Hello! Did you use VirtaulService or Ingress for testing?

**Comment by bianpengyuan** [comment] 2021-02-12 17:47
Thanks for reporting! Looks like this is a doc issue. https://github.com/istio/istio.io/pull/8967 should make the warning more visible.

**Closed** 2021-02-12 22:13 UTC
Labels: area/extensions and telemetry
