### ISSUE TITLE
"gRPC config stream closed: 13" closes all proxy connexions

### ISSUE THREAD

**Issue by prune998** [istio/istio#17383] opened 2019-09-25 15:57 UTC
**Bug description**
Istio 1.3.0 Ingress gateway (may also happen on any sidecar) is logging the error `[2019-09-25 15:35:47.514][22][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,` every few minutes, from 5 to 25 mins usually.

While the issue https://github.com/istio/istio/issues/8270 is stating that this is just an "info" log and should not be linked to any issue, I do see all my current connexions going through the gateway to be terminated.

Turning logs to info on the Gateway : 
```
istio-ingressgateway-7dc54f8787-w7gng istio-proxy [2019-09-25 15:35:47.514][22][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
istio-ingressgateway-7dc54f8787-w7gng istio-proxy [2019-09-25 15:35:47.740][22][info][filter] [src/istio/utils/logger.cc:83] Logger active
istio-ingressgateway-7dc54f8787-w7gng istio-proxy [2019-09-25 15:35:47.742][22][info][filter] [src/istio/utils/logger.cc:83] Logger active
istio-ingressgateway-7dc54f8787-w7gng istio-proxy [2019-09-25 15:35:47.742][22][info][upstream] [external/envoy/source/server/lds_api.cc:60] lds: add/update listener '0.0.0.0_443'
istio-ingressgateway-7dc54f8787-w7gng istio-proxy {"duration":"1463305","downstream_local_address":"10.230.128.165:443","upstream_transport_failure_reason":"-","route_name":"-","response_code":"0","user_agent":"grpc-go/1.23.0","response_flags":"DC","start_time":"2019-09-25T15:12:08.431Z","method":"POST","request_id":"aba73ff8-8418-4979-b8ac-cfd9ccab561e","upstream_host":"10.230.128.103:1081","x_forwarded_for":"10.230.128.4","requested_server_name":"useredged.alerting.devops.services","bytes_received":"2241","istio_policy_status":"-","bytes_sent":"0","upstream_cluster":"outbound|1081||useredged.alerting.svc.cluster.local","downstream_remote_address":"10.230.128.4:34886","authority":"useredged.alerting.devops.services:443","path":"/ra.useredgesvc.UserEdgeSVC/BiFeed","protocol":"HTTP/2","upstream_service_time":"-","upstream_local_address":"-"}
```

The logs here are showing a "change" in the listener on port 443, which obviously closes all the opened TCP connexions.
At the same time, Pilot is also logging `ads` errors while communicating to the IngressGateway.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
`gRPC config stream closed: 13` error should not lead to a loss of connexions

**Steps to reproduce the bug**
Deployed Istio 1.3.0 using helm chart. start a "streaming" GRPC connexion through the ingress gateway suing HTTPS

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
istioctl version --remote
client version: 1.3.0
control plane version: 1.3.0
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Helm chart using `helm template`

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS cluster 1.14.6

**Comment by prune998** [comment] 2019-09-25 17:56
The Proxy listener change on the Ingress Gateway is triggered when Pilot timeout it's connexions with each proxy.
It sounds to be linked to `keepaliveMaxServerConnectionAge` parameter on Pilot.

Looking at the docs at it states : https://istio.io/docs/reference/commands/pilot-discovery/
```
Maximum duration a connection will be kept open on the server before a graceful close. (default `2562047h47m16.854775807s`)
```

Why is mine set to 30s ? (deployed from Helm)
What is a real good value for this parameter ? 
Why does this timeout + reconnect is seeing a change in the listener on port 443 ? 

Any idea/help welcomed...

**Comment by prune998** [comment] 2019-09-25 18:06
Just dumped the listener config before / after the relaod using : 
```
istioctl -n istio-system proxy-config listener  istio-ingressgateway-b95849b6d-w5mmf -o json > ~/tmp/before`
.. wait for config change
istioctl -n istio-system proxy-config listener  istio-ingressgateway-b95849b6d-w5mmf -o json > ~/tmp/after

diff  ~/tmp/before ~/tmp/after
```
There is no change...

**Comment by howardjohn** [comment] 2019-09-25 18:56
> Why is mine set to 30s ? (deployed from Helm)

30 seconds or 30m? The default is 30m so if its 30s I suspect you may have configured it yourself somehow?

This may be linked to https://github.com/istio/istio/issues/12162? If you are in a cluster you can experiment, you could try setting `--set pilot.env.PILOT_DISABLE_XDS_MARSHALING_TO_ANY=true`, or just set the environment variable on the pilot deployment. Note this will result in a huge increase in Pilot CPU usage, so I wouldn't try it in production

**Comment by prune998** [comment] 2019-09-26 00:29
Sorry it's 30 minutes, not seconds :)
I'm going to try your option and let you know. Thanks

**Comment by prune998** [comment] 2019-09-26 11:21
setting `DISABLE_XDS_MARSHALING_TO_ANY=true` solved the issue.
CPU and memory is impacted, as suggested : 

![image](https://user-images.githubusercontent.com/1110398/65684683-35f6e080-e02e-11e9-806f-472b37e6f2ed.png)

Is there something wrong with my install or this is a regression ? 
Thanks.

**Comment by nrjpoddar** [comment] 2019-10-01 20:06
@howardjohn if I understand the issue correctly, every 30m Pilot will reset connections made to xDS servers by the Envoy proxy which can cause the proxy to drop all configuration and reload.

In the interim period the service can have disruption as there might be no listeners/routes/clusters/endpoint config at the Envoy proxies between a disconnect and config getting re-populated.

Is this accurate?

**Comment by prune998** [comment] 2019-10-01 20:07
it's exactly that @nrjpoddar  !

**Comment by howardjohn** [comment] 2019-10-01 20:21
> In the interim period the service can have disruption as there might be no listeners/routes/clusters/endpoint config at the Envoy proxies between a disconnect and config getting re-populated.

No, there should be no time period with no config -- it will hotswap in the new config so there should be no downtime.

**Comment by prune998** [comment] 2019-10-01 20:24
What I see is the Proxy (envoy) drops and re-create the listeners, so, yes, it does have to end all the opened TCP connexions... 
Maybe Envoy should compare the configs then decide to stop the listener if needed... I really feel it's an issue on Envoy side, but as this does not happen when setting `PILOT_DISABLE_XDS_MARSHALING_TO_ANY=true`, I feel like maybe Istio is sending some config it should not...

**Comment by nrjpoddar** [comment] 2019-10-01 20:29
> > 
> No, there should be no time period with no config -- it will hotswap in the new config so there should be no downtime.

That makes sense on the desired and hopefully implemented behavior. Why does this `PILOT_DISABLE_XDS_MARSHALING_TO_ANY` env matter in this case? I understand how it can be linked to CPU spikes but not destroying/re-creating listeners.

**Comment by howardjohn** [comment] 2019-10-01 20:48
> What I see is the Proxy (envoy) drops and re-create the listeners, so, yes, it does have to end all the opened TCP connexions...Maybe Envoy should compare the configs then decide to stop the listener if needed... I really feel it's an issue on Envoy side, but as this does not happen when setting PILOT_DISABLE_XDS_MARSHALING_TO_ANY=true, I feel like maybe Istio is sending some config it should not...

Envoy *does* do this comparing by computing the hash of the config. What is possible is that when Marshaling to Any it is not doing this in a stable manner (eg unordered list). See https://github.com/envoyproxy/envoy/issues/6252

**Comment by nrjpoddar** [comment] 2019-10-01 21:06
Thanks @howardjohn for the info. Looks like we will need to uplift https://github.com/istio/envoy/tree/release-1.3 to get the upstream Envoy PR and then change istio/proxy release-1.3 to the new SHA. I'm assuming we want this addressed in 1.3.x?

**Comment by howardjohn** [comment] 2019-10-01 21:09
Yes if possible. I had thought it was already fixed -- I think there were some attempts months back to fix this but apparently didn't fix all cases if you are still seeing this.

**Comment by nrjpoddar** [comment] 2019-10-01 21:10
Ok, I can take a stab at merging the envoy changes and go from there. Do we cherry-pick just the PR commit we need from envoyproxy or just move to the latest master in the Istio fork?

**Comment by howardjohn** [comment] 2019-10-01 21:12
Not actually sure.. @rlenglet @duderino how do we pull in envoy updates?

**Comment by rlenglet** [comment] 2019-10-01 23:41
> @rlenglet @duderino how do we pull in envoy updates?

For 1.3, just backport directly into `istio/envoy:release-1.3`.

`istio/envoy:master` is currently not used and is far behind. Just ignore it.

**Comment by prune998** [comment] 2019-10-02 12:33
Let me know when you have something merged (with docker images would be even simpler for me) so I can test it.
Many thanks for your help on this.

**Comment by nrjpoddar** [comment] 2019-10-02 14:55
> For 1.3, just backport directly into `istio/envoy:release-1.3`.
> 

My question is specific to release-1.3 branch, when you say backport are we just cherry-picking relevant commits/PR or are should we be doing merge of the current envoyproxy/envoy:master into istio/envoy:release-1.3?

**Comment by howardjohn** [comment] 2019-10-02 15:00
@rlenglet  ^

Can we check if this is in master already? If so maybe @prune998 or someone in #17139 (basically the same issue) try out the daily build and see if it is resolved?

**Comment by nrjpoddar** [comment] 2019-10-02 15:08
> Can we check if this is in master already?

istio/envoy:master is even more outdated than istio/envoy:release-1.3 afaict

**Comment by nrjpoddar** [comment] 2019-10-02 15:12
I just realized that istio/envoy:release-1.3 is based of envoyproxy/envoy-wasm and not envoyproxy/envoy so there is another refresh that needs to happen.

**Comment by rlenglet** [comment] 2019-10-02 22:04
> My question is specific to release-1.3 branch, when you say backport are we just cherry-picking relevant commits/PR or are should we be doing merge of the current envoyproxy/envoy:master into istio/envoy:release-1.3?

Please cherry-pick.

**Comment by howardjohn** [comment] 2019-10-03 14:09
thank you all for helping get to the bottom of this!! Let's consolidate this into https://github.com/istio/istio/issues/17139 since it is the same issue

**Closed by howardjohn** 2019-10-03 14:09 UTC
Labels: area/networking

**Comment by nrjpoddar** [comment] 2019-10-03 14:18
Hi @prune998 please follow the comments in this thread: https://github.com/istio/istio/issues/17139#issuecomment-537728166 and try it out in your environment to see if the issue is addressed.

Feel free to comment/re-open if that's not the case.

**Comment by prune998** [comment] 2019-10-03 14:45
will do in an hour. Thanks.

**Comment by prune998** [comment] 2019-10-03 17:39
Seems to solve the issue. I commentend in the other thread. Maybe we can close this issue ? 
https://github.com/istio/istio/issues/17139#issuecomment-538048560

**Comment by ckcd** [comment] 2019-10-15 08:39
update istio to 1.3.3 but still get errors: my grpc client <--> server still get some `erorr_msg:OS Error` and tcp `Reset`, and the logs of istio-proxy still has:
```
[2019-10-15 07:05:59.038][24][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-10-15 07:39:07.474][24][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-10-15 08:11:41.801][24][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
```

**Comment by BenjaminHuang** [comment] 2022-04-04 00:50
@nrjpoddar @rlenglet  could you assign project member on https://github.com/istio/istio/issues/27513?
People still encounter this same kind of issue in production from time to time, even after the fix has been applied. 
This lead me to believe that other root cause(s) is(are) still out there.

At lease these versions are still involved: 
1.6.8
1.6.14
1.7.3
1.9.2
1.10

**Comment by glyslxq** [comment] 2022-05-27 02:14
Same question：
istio 1.6.14
```
warning	envoy config	[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 13,
```
php error
```
fwrite(): send of 527 bytes failed with errno=32 Broken pipe
```

**Comment by howardjohn** [comment] 2022-05-27 15:49
Don't use Istio 1.6, it's over 2 years old and EOL. If you do, please don't
post issues for it.
