### ISSUE TITLE
Incorrect documented  istioctl ctl  in egressgateway manifest generation  

### ISSUE THREAD

**Issue by balamuru** [istio/istio#21379] opened 2020-02-22 16:08 UTC
**Bug description**
Executing the command to generate the egress gateway generates invalid output

[x] Configuration Infrastructure
[x] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The command should succeed and generate an egress gateway manifest
**Steps to reproduce the bug**
* Execute the following command as documented in https://istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#setup-egress-gateway-with-sni-proxy

```
$ cat <<EOF | istioctl manifest generate --set values.global.istioNamespace=istio-system -f - > ./istio-egressgateway-with-sni-proxy.yaml
> gateways:
>   enabled: true
>   istio-ingressgateway:
>     enabled: false
>   istio-egressgateway:
>     enabled: false
>   istio-egressgateway-with-sni-proxy:
>     enabled: true
>     labels:
>       app: istio-egressgateway-with-sni-proxy
>       istio: egressgateway-with-sni-proxy
>     replicaCount: 1
>     autoscaleMin: 1
>     autoscaleMax: 5
>     cpu:
>       targetAverageUtilization: 80
>     serviceAnnotations: {}
>     type: ClusterIP
>     ports:
>       - port: 443
>         name: https
>     secretVolumes:
>       - name: egressgateway-certs
>         secretName: istio-egressgateway-certs
>         mountPath: /etc/istio/egressgateway-certs
>       - name: egressgateway-ca-certs
>         secretName: istio-egressgateway-ca-certs
>         mountPath: /etc/istio/egressgateway-ca-certs
>     configVolumes:
>       - name: sni-proxy-config
>         configMapName: egress-sni-proxy-configmap
>     additionalContainers:
>     - name: sni-proxy
>       image: nginx
>       volumeMounts:
>       - name: sni-proxy-config
>         mountPath: /etc/nginx
>         readOnly: true
> EOF
could not read values from file -: open -: no such file or directory

```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$ istioctl  version --remote
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (8 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"2020-02-12T14:56:45Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Istioctl
**Environment where bug was observed (cloud vendor, OS, etc)**
Native k8s

**Comment by howardjohn** [comment] 2020-02-22 19:14
@ayj did you have some pr adding reading from stdin?

**Comment by ayj** [comment] 2020-02-22 23:31
Yes, support for reading from stdin went into master. 1.5 support is also pending.

**Comment by balamuru** [comment] 2020-02-23 02:10
Thanks . What's the equivalent command I can use in 1.4.x ? I tried reading the snippet from a temp file but that didn't work either . 

Please advise / update the 1.4.x doc . Thanks

**Comment by esnible** [comment] 2020-03-02 17:58
Closing as a duplicate of https://github.com/istio/istio/issues/21015

**Closed by esnible** 2020-03-02 17:58 UTC
Labels: area/config, area/networking, kind/docs, lifecycle/needs-triage
