### ISSUE TITLE
istioctl not reporting correct version info

### ISSUE THREAD

**Issue by jfourment** [istio/istio#11135] opened 2019-01-22 03:30 UTC
**Describe the bug**
Our cluster has been migrated from istio 1.0.2 to istio 1.0.5, but when running istioctl proxystatus the reported version of the proxy is 1.0.2

**Expected behavior**
I would expect version 1.0.5 to be returned by istioctl proxy-status

**Steps to reproduce the bug**
* set up a kube cluster with istio 1.0.5 installed
* run `istioctl proxy-status`

```
pod0-7dfdd54db6-4jmkf.banking                                SYNCED     SYNCED     SYNCED (100%)     SYNCED     istio-pilot-7f89897cf-g4fjs     1.0.2
pod1-58c5b7fb8f-6kf99.mimo                                        SYNCED     SYNCED     SYNCED (100%)     SYNCED     istio-pilot-7f89897cf-g4fjs     1.0.2
pod2-6c6d7b9f5c-kxmgw.mimo                                        SYNCED     SYNCED     SYNCED (100%)     SYNCED     istio-pilot-7f89897cf-g4fjs     1.0.2
```

**Version**
* istio 1.0.5
* kubernetes 1.11.5

**Installation**
{{ Please describe how Istio was installed }}

**Environment**

AWS 

Looking at the dockerfile here:https://github.com/istio/istio/blob/release-1.0/pilot/docker/Dockerfile.proxyv2#L9
It doesn't seem to have been updated since 1.0.2

**Comment by esnible** [comment] 2019-02-02 15:06
Closing as duplicate of https://github.com/istio/istio/issues/9597

**Closed by esnible** 2019-02-02 15:06 UTC
