### ISSUE TITLE
increased pilot pushes after istiod upgrade from 1.11.8 to 1.12.8

### ISSUE THREAD

**Issue by turbotankist** [istio/istio#39652] opened 2022-06-27 19:17 UTC
### Bug Description

Istio version 1.11.8 is End of Support so we decided to upgrade our clusters to 1.12.8
We use istio-operator for deploy it.
The upgrade was successful but in one time we are figure out that some jobs fails because istio-proxy was not ready. We checked istiod resource usage and it was huge increased.
I had tried to downgrade only the istiod deployment to 1.11.8 and all restored to normal usage. In 20 minutes I changed the version to 1.12.8 again and usage was increased.
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/9462236/176014926-a200698b-2843-4cb5-aa1c-74dd1788fcd3.png">
istiod has no other logs just they much more than early version
```
...
{"level":"info","time":"2022-06-27T18:36:36.676194Z","scope":"ads","msg":"CDS: PUSH for node:istio-ingressgateway-dps-7cc486466b-lnpr4.istio-system resources:6977 size:6.3MB cached:3497/3499"}
{"level":"info","time":"2022-06-27T18:36:36.677275Z","scope":"ads","msg":"EDS: PUSH for node:panel-7c6659d478-vcjs5.panel-dev resources:3061 size:772.2kB empty:0 cached:3061/3061"}
{"level":"info","time":"2022-06-27T18:36:36.715449Z","scope":"ads","msg":"LDS: PUSH for node:panel-7c6659d478-vcjs5.panel-dev resources:551 size:2.9MB"}
{"level":"info","time":"2022-06-27T18:36:37.100065Z","scope":"ads","msg":"NDS: PUSH for node:delay-queue-handler-stable-374-546894796f-8qppx.data-ceh-stable resources:1 size:297.4kB"}
{"level":"info","time":"2022-06-27T18:36:37.136090Z","scope":"ads","msg":"RDS: PUSH for node:clientpool-6c6c6bc77c-2vx8w.core-clientpool-dev resources:263 size:2.0MB cached:0/263"}
{"level":"info","time":"2022-06-27T18:36:37.141757Z","scope":"ads","msg":"NDS: PUSH for node:clientpool-6c6c6bc77c-2vx8w.core-clientpool-dev resources:1 size:297.4kB"}
{"level":"info","time":"2022-06-27T18:36:37.150535Z","scope":"ads","msg":"EDS: PUSH for node:istio-ingressgateway-vpn-ccb9bd5fb-29j5h.istio-system resources:6944 size:1.7MB empty:80 cached:6738/6944"}
...
```

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176016353-1f370c9b-4178-40a1-bc7b-e3c31b682d72.png">

I've tried to upgrade to 1.13.5 version but without any improvement. 
May be we have any legacy configs that could has this affect?

### Version

```prose
istioctl version
client version: 1.12.8
control plane version: 1.12.8
data plane version: 1.12.8 (495 proxies), 1.11.8 (511 proxies)

kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.12-eks-a64ea69
```

### Additional Information

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-state
  namespace: istio-system
spec:
  addonComponents:
    istiocoredns:
      enabled: false
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
      ...
    ingressGateways:
      ...
  
    pilot:
      enabled: true
      k8s:
        env:
          - name: PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE
            value: 'true'
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        hpaSpec:
          maxReplicas: 4
          metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 100
              type: Resource
          minReplicas: 2
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
  hub: docker.io/istio
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    accessLogFormat: ''
    certificates: []
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: 'false'
        ISTIO_META_DNS_CAPTURE: 'true'
      tracing:
        zipkin:
          address: 'jaeger-es-collector.jaeger-prod.svc.cluster.local:9411'
    enablePrometheusMerge: false
    enableTracing: true
    localityLbSetting:
      enabled: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    protocolDetectionTimeout: 0s
    trustDomain: cluster.local
  profile: default
  tag: 1.12.8
  values:
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        name: istio-egressgateway
        secretVolumes:
          - mountPath: /etc/istio/egressgateway-certs
            name: egressgateway-certs
            secretName: istio-egressgateway-certs
          - mountPath: /etc/istio/egressgateway-ca-certs
            name: egressgateway-ca-certs
            secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        secretVolumes:
          - mountPath: /etc/istio/wafgateway-certs
            name: wafgateway-certs
            secretName: istio-wafgateway-certs
          - mountPath: /etc/istio/wafgateway-ca-certs
            name: wafgateway-ca-certs
            secretName: istio-wafgateway-ca-certs
          - mountPath: /etc/istio/nexus-certs
            name: nexus-certs
            secretName: nexus-certs
        type: NodePort
        zvpn:
          enabled: false
    global:
      arch:
        amd64: 2
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 100m
      imagePullPolicy: IfNotPresent
      imagePullSecrets: []
      istioNamespace: istio-system
      jwtPolicy: third-party-jwt
      logAsJson: true
      logging:
        level: 'default:info'
      meshID: dev
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: eks-dev
        enabled: true
      network: "eks-cluster-one"
      omitSidecarInjectorConfigMap: false
      oneNamespace: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ''
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: 'misc:error'
        enableCoreDump: false
        excludeIPRanges: 169.254.169.254/32
        excludeInboundPorts: ''
        excludeOutboundPorts: '9093,9094'
        image: proxyv2
        includeIPRanges: '*'
        lifecycle:
          preStop:
            exec:
              command:
                - sh
                - '-c'
                - sleep 10
        logLevel: warning
        privileged: false
        readinessFailureThreshold: 30
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        resources:
          limits:
            cpu: 2000m
            memory: 1224Mi
          requests:
            cpu: 50m
            memory: 200Mi
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 500m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
```

**Comment by howardjohn** [comment] 2022-06-27 23:45
How is "pilot_push_triggers" metric? That shows _why_ it is pushing. Not sure it existed that long ago though. In newer (probably 1.13+) the exact config change is logged aswell

**Comment by turbotankist** [comment] 2022-06-28 10:00
On a grafana dashboard  timeline: `v1.12.8`(heavy loaded) --> 18:05 --> `v1.11.8` (is nice) --> 18:33 --> `v1.12.8`(heavy loaded). The difference only in istiod version
Sorry for a lot of images
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176146059-324d063b-c04d-46fd-9a92-44be5b707721.png">

There are push spikes of endpoints every 5 minutes. 
there is no difference in pilot_push_triggers but a big in pilot_xds_config_size_bytes_sum
`sum(rate(pilot_push_triggers[1m])) by(type)`
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176143186-84b70967-e596-43fb-bf73-25896ab3029e.png">
`sum(rate(pilot_xds_config_size_bytes_sum[1m])) by (type)`
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176149637-84702739-1d78-4e54-8351-caf6608538e2.png">
`sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{}[1m])) `
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176143439-18e47df9-af15-4999-adb5-c34f59b8c1f8.png">

It seems like an istiod push a full config instead of a diff
Also there are some pilot metrics with difference between versions
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176146961-a2304a51-8a8e-4dab-8792-68e87cb41eb5.png">
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176147859-b3cd0267-717a-4106-90c0-7c112b982291.png">
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176148801-3f10bf55-d596-4135-8fb4-371b9d94c490.png">

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176148071-bccad866-ea16-455d-a215-18efff7c8856.png">
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9462236/176150806-9839c2bd-c88c-493e-9e82-beb36395b32c.png">

**Comment by howardjohn** [comment] 2022-06-28 14:31
If the push_triggers is the same it will be tricky to debug. Might be helpful to run the latest version(master/1.14) which has more logs and look at those. Youcan simply run `go run ./pilot/cmd/pilot-discovery` locally (when connected to k8s) and it will trigger 'pushes' to 0 clients, and we can see the cause. That way it is ~zero risk. Or do a full upgrade if that is feasible in your env.

We are looking for: `Push debounce stable[12] 1 for config ServiceEntry/kube-system/kube-dns.kube-system.svc.cluster.local: 100.240969ms since last change, 100.240794ms since last push, full=false`

This means kube-dns endpoint changed, for example

**Comment by turbotankist** [comment] 2022-06-29 16:16
thank you!
I've run istiod locally and result
logs `Push debounce  ... full=false` don't have correlation with istiod load, however `Push debounce  ... full=true` does
example of it

```
Push debounce stable[5183] 1 for config ServiceEntry/data-ceh-stable/delay-queue-handler-stable-1-http.data-ceh-stable.svc.cluster.local: 120.879431ms since last change, 120.879247ms since last push, full=true
Push debounce stable[5182] 3 for config ServiceEntry/manager-stable/admin-panel.manager-stable.svc.cluster.local and 2 more configs: 100.566695ms since last change, 173.244626ms since last push, full=true
Push debounce stable[5180] 1 for config VirtualService/capt-processing-card-manager-stable/card-manager-router: 100.7953ms since last change, 100.795183ms since last push, full=true
Push debounce stable[5179] 1 for config ServiceEntry/data-ceh-stable/delay-queue-handler-stable-3-http.data-ceh-stable.svc.cluster.local: 111.18979ms since last change, 111.189693ms since last push, full=true
Push debounce stable[5177] 3 for config ServiceEntry/data-ceh-stable/delay-queue-handler-stable-474-http.data-ceh-stable.svc.cluster.local and 2 more configs: 104.271836ms since last change, 3.801250623s since last push, full=true
Push debounce stable[5176] 3 for config ServiceEntry/data-ceh-stable/avro-transformer-stable-299-http.data-ceh-stable.svc.cluster.local and 2 more configs: 1.007009289s since last change, 3.093004257s since last push, full=true
Push debounce stable[5175] 3 for config ServiceEntry/data-ceh-stable/change-transformer-stable-1015-http.data-ceh-stable.svc.cluster.local and 2 more configs: 126.37504ms since last change, 3.500773574s since last push, full=true
Push debounce stable[5174] 1 for config ServiceEntry/data-ceh-stable/delay-queue-handler-stable-107-http.data-ceh-stable.svc.cluster.local: 103.239345ms since last change, 103.239245ms since last push, full=true
Push debounce stable[5173] 1 for config ServiceEntry/data-ceh-stable/delay-queue-handler-stable-772-http.data-ceh-stable.svc.cluster.local: 1.221332347s since last change, 1.221332261s since last push, full=true
Push debounce stable[5172] 1 for config ServiceEntry/data-ceh-stable/delay-queue-handler-stable-40-http.data-ceh-stable.svc.cluster.local: 100.497262ms since last change, 100.497115ms since last push, full=true
Push debounce stable[5171] 2 for config ServiceEntry/data-ceh-stable/delay-queue-handler-stable-706-http.data-ceh-stable.svc.cluster.local and 1 more configs: 106.013856ms since last change, 200.343412ms since last push, full=true
Push debounce stable[5170] 1 for config ServiceEntry/data-ceh-stable/avro-transformer-stable-233-http.data-ceh-stable.svc.cluster.local: 100.008756ms since last change, 100.008637ms since last push, full=true
Push debounce stable[5169] 2 for config ServiceEntry/data-ceh-stable/avro-transformer-stable-698-http.data-ceh-stable.svc.cluster.local and 1 more configs: 132.80451ms since last change, 2.523311719s since last push, full=true
```

Also if I grep logs for 1 pod from 1 istiod then I get that :
```
"Jun 29, 2022 @ 18:34:34.439","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:65/254",info
"Jun 29, 2022 @ 18:34:34.095","LDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:551 size:2.8MB",info
"Jun 29, 2022 @ 18:34:33.865","EDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:2979 size:755.0kB empty:0 cached:2977/2979",info
"Jun 29, 2022 @ 18:34:33.441","CDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:3186 size:3.5MB cached:3181/3182",info
"Jun 29, 2022 @ 18:34:30.968","NDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:1 size:290.5kB",info
"Jun 29, 2022 @ 18:34:30.948","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:64/254",info
"Jun 29, 2022 @ 18:34:30.376","LDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:551 size:2.8MB",info
"Jun 29, 2022 @ 18:34:30.237","EDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:2979 size:753.9kB empty:0 cached:2977/2979",info
"Jun 29, 2022 @ 18:34:29.462","CDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:3186 size:3.5MB cached:3180/3182",info
"Jun 29, 2022 @ 18:34:29.287","NDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:1 size:290.5kB",info
"Jun 29, 2022 @ 18:34:29.221","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:65/254",info
"Jun 29, 2022 @ 18:34:28.161","LDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:551 size:2.8MB",info
"Jun 29, 2022 @ 18:34:28.094","EDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:2979 size:753.9kB empty:0 cached:2978/2979",info
"Jun 29, 2022 @ 18:34:27.496","CDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:3186 size:3.5MB cached:3182/3182",info
"Jun 29, 2022 @ 18:34:24.675","NDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:1 size:290.5kB",info
"Jun 29, 2022 @ 18:34:24.552","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:76/254",info
"Jun 29, 2022 @ 18:34:23.425","LDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:551 size:2.8MB",info
"Jun 29, 2022 @ 18:34:23.368","EDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:2979 size:753.4kB empty:0 cached:2978/2979",info
"Jun 29, 2022 @ 18:34:22.987","CDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:3186 size:3.5MB cached:1967/3182",info
"Jun 29, 2022 @ 18:34:19.324","NDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:1 size:290.5kB",info
"Jun 29, 2022 @ 18:34:19.180","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:0/254",info
"Jun 29, 2022 @ 18:34:18.309","LDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:551 size:2.8MB",info
"Jun 29, 2022 @ 18:34:18.269","EDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:2979 size:752.5kB empty:0 cached:2979/2979",info
"Jun 29, 2022 @ 18:34:17.499","CDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:3186 size:3.5MB cached:3182/3182",info
"Jun 29, 2022 @ 18:34:14.453","NDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:1 size:290.5kB",info
"Jun 29, 2022 @ 18:34:14.419","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:0/254",info
"Jun 29, 2022 @ 18:34:14.120","LDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:551 size:2.8MB",info
"Jun 29, 2022 @ 18:34:14.008","EDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:2979 size:752.5kB empty:0 cached:2978/2979",info
"Jun 29, 2022 @ 18:34:13.559","CDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:3186 size:3.5MB cached:3181/3182",info
"Jun 29, 2022 @ 18:34:12.524","NDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:1 size:290.5kB",info
"Jun 29, 2022 @ 18:34:12.509","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:0/254",info
"Jun 29, 2022 @ 18:34:12.328","LDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:551 size:2.8MB",info
"Jun 29, 2022 @ 18:34:12.279","EDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:2979 size:752.3kB empty:0 cached:2979/2979",info
"Jun 29, 2022 @ 18:34:11.096","CDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:3186 size:3.5MB cached:2020/3182",info
"Jun 29, 2022 @ 18:34:08.989","NDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:1 size:290.5kB",info
"Jun 29, 2022 @ 18:34:08.967","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:144/254",info
"Jun 29, 2022 @ 18:34:08.794","LDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:551 size:2.8MB",info
"Jun 29, 2022 @ 18:34:08.735","EDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:2979 size:752.0kB empty:0 cached:2978/2979",info
"Jun 29, 2022 @ 18:34:07.831","CDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:3186 size:3.5MB cached:2019/3182",info
"Jun 29, 2022 @ 18:34:06.835","NDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:1 size:290.5kB",info
"Jun 29, 2022 @ 18:34:06.726","RDS: PUSH for node:grpc-fma-6cbcdf5898-45fnn.p3-test resources:254 size:2.1MB cached:144/254",info
```
A lot of pushes during 1-2 minutes every 3-5 seconds
And these spikes about every 10 minutes
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/9462236/176485118-b6ed6b2d-b0f2-4524-a353-4e743232edb3.png">

**Comment by turbotankist** [comment] 2022-06-29 16:37
And I have this.
I don't know - `Full push, service accounts changed, xxxx.bbbb-stable.svc.cluster.local` mean that all pods in mesh get full push or that pods from service xxxx.bbbb-stable will get it?
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/9462236/176489518-10813663-e9ed-4a05-88c1-2545d94dcfda.png">

**Comment by howardjohn** [comment] 2022-06-29 17:40
Are they going from 1->0->1 instances of some Service/Deployment?

I am pretty sure this is not _supposed_ to trigger full push: https://github.com/istio/istio/blob/844e1f4747e7144498a6ded51d52ee682fd2e60a/pilot/pkg/xds/eds.go#L148 but maybe it is somehow

**Comment by turbotankist** [comment] 2022-06-29 17:46
No, VPA has this flow:
```
28m         Normal    EvictedByVPA             pod/delay-queue-handler-stable-107-899fb9b96-mnn9j     Pod was evicted by VPA Updater to apply resource recommendation.
28m         Normal    Killing                  pod/delay-queue-handler-stable-107-899fb9b96-mnn9j     Stopping container app
28m         Normal    Killing                  pod/delay-queue-handler-stable-107-899fb9b96-mnn9j     Stopping container istio-proxy
28m         Normal    Scheduled                pod/delay-queue-handler-stable-107-899fb9b96-mx4h7     Successfully assigned data-ceh-stable/delay-queue-handler-stable-107-899fb9b96-mx4h7
```
and it has a `kubectl get mutatingwebhookconfigurations  vpc-resource-mutating-webhook`. It sets recommended resources  during a new pod creating.

**Comment by yingzhuivy** [comment] 2022-08-05 18:16
we are seeing the same issue, increased propagation delay and increased xds size after we upgrade to 1.12. we upgraded to 1.13 recently and propagation delay is still pretty high.

one thing that i notice from the log
```
Push debounce stable[10082] 841 for config ServiceEntry/flink-athena-segment-homes-on-trip-staging/flink-jobmanager.flink-athena-segment-homes-on-trip-staging.svc.ea1.us.a and 178 more configs: 11.552281ms since last change, 1m10.370301595s since last push, full=true
```

we didn't set PILOT_DEBOUNCE_MAX, so we are using default 10s, but why is it `1m10.370301595s since last push`?

**Comment by howardjohn** [comment] 2022-09-07 19:45
I think https://github.com/istio/istio/blob/844e1f4747e7144498a6ded51d52ee682fd2e60a/pilot/pkg/xds/eds.go#L148 is essentially negated by https://github.com/istio/istio/pull/36882; We don't do a full push on the scale from 1->0, but we do on the scale from 0->1 which negates the optimization. This was merged in 1.12

**Comment by howardjohn** [comment] 2022-09-07 22:27
The fix (without just regressing in correctness by reverting https://github.com/istio/istio/pull/36882) likely depends on https://github.com/istio/istio/pull/39133 (1.15). That PR in turn cause its own small regression (https://github.com/istio/istio/issues/40801). 

So to fix this i think we need to fix 40801 first, then change the logic here. This will likely only be able to land in 1.15.x.

I also opened https://github.com/envoyproxy/envoy/issues/23027 to make this codepath more sane long term

**Closed** 2022-09-12 12:34 UTC
Labels: area/perf and scalability, area/upgrade

**Comment by howardjohn** [comment] 2022-11-08 13:43
1.15 only and it won't be backported
