### ISSUE TITLE
Error Installing the control plane in the external-istiod

### ISSUE THREAD

**Issue by pbonito** [istio/istio#36858] opened 2022-01-17 21:02 UTC
### Bug Description

Hi,
I'm trying to configure istio with external control plane following instruction https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/. 
I got the following error when trying to install the control plane:
2022-01-17T20:16:14.456517Z	error	installer	failed to update resource with server-side apply for obj EnvoyFilter/external-istiod/stats-filter-1.10: Internal error occurred: failed calling webhook "rev.validation.istio.io": Post "https://istio-test:443/validate?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "cluster.local")

I verified that ca-bundle is not empty but it doesn't match the root certificate on istiod pod::
kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml -o jsonpath='{.webhooks[0].clientConfig.caBundle}' |md5
7f643df5c33dc1f182160914946d4b3c

kubectl -n istio-system get configmap istio-ca-root-cert -o jsonpath='{.data.root-cert\.pem}' | base64| md5
f67a59362b15a58a7f9b48e2d4cebbd6

The issue is not fixed restarting istiod pod.

I 'm not using a CA but followed this https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ to expose ingress gateway.

Thanks in advance for your help

### Version

```prose
istioctl version
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (2 proxies)

kubectl version --short
Client Version: v1.21.3
Server Version: v1.21.5-gke.1302
```

**Comment by hzxuzhonghu** [comment] 2022-01-18 02:14
Maybe a regression, need to have a look

**Comment by pbonito** [comment] 2022-01-19 07:07
How can we proceed on troubleshooting this issue? We have been trying to install istio with external plane for a while.

**Comment by hzxuzhonghu** [comment] 2022-01-19 09:08
@frankbu @linsun may shed some lights here, I tried to install it with two kind clusters and failed too. In which step did you failed @pbonito

**Comment by pbonito** [comment] 2022-01-19 10:47
@hzxuzhonghu I got the error when I try to configure remote cluster. I also checked that regardless of the error pod is running so I proceeded with the other steps but when I try to deploy sample application helloworld and sleep pods are failing with the same error:
Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": Post "https://istio-test:15017/inject/:ENV:cluster=gke_cbuild-private-proj-a-c37a_europe-west2_istio-remote:ENV:net=network1?timeout=10s": x509: certificate signed by unknown authority
Can someone confirm if I need to use a valid CA to generate certificates or I can simple follow steps described here   https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ .

**Comment by hzxuzhonghu** [comment] 2022-01-20 02:30
I met this error too, as you can see there is no cabundle in validatingwebhookconfiguration `istio-validator-external-istiod` of the remote cluster.

**Comment by pbonito** [comment] 2022-01-20 07:48
@hzxuzhonghu for me is not empty but it doesn't match the one in configmap.
I

**Comment by litong01** [comment] 2022-01-26 13:55
@pbonito you probably can get around this issue by adding the following when deploy the external control plane.

```
        overlays:
        - kind: ValidatingWebhookConfiguration
          name: istio-validator-external-istiod
          patches:
          - path: webhooks[0].clientConfig.service.namespace
            value: istio-system
        - kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.volumes[100]

more stuff
```

What was added here is the patch to fix the validating webhook to use the istiod in istio-system namespace, rather than the one in external-istiod which is not available at the moment installing any other things such as envoy filters, that is why you are seeing the error.

**Comment by litong01** [comment] 2022-01-26 14:18
@pbonito even with that workaround, the install will succeed, but the validating webhook configurations will be updated many times and istio validation controller wont stop updating the web hook configurations.

**Comment by litong01** [comment] 2022-01-26 14:22
I think the real cause of the problem is that the two istiod validationControllers will keep changing validating webhook configuration and each update causing other one to update, then it creates this endless loop

**Comment by frankbu** [comment] 2022-01-26 17:47
Notice that the IOP for installing the external istiod includes these settings:
```
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: ""
        - name: VALIDATION_WEBHOOK_CONFIG_NAME
          value: ""
```
I think that's supposed to stop it from managing the webhooks. Has something changed in 1.12 so they're not being checked?

**Comment by litong01** [comment] 2022-01-26 17:53
@frankbu they are actually needed. If they are set to empty like that doc says, the caBundle patch wont work based on the code that I studied awhile back.

**Comment by pbonito** [comment] 2022-01-26 19:00
@litong01  yes, we added those values and issue was sorted, but than when we try to create resources  Gateway, VirtualService, and DestinationRule in control plane we get the following error:
Error from server (InternalError): error when creating "external-istiod-gw.yaml": Internal error occurred: failed calling webhook "rev.validation.istio.io": Post "https://istiod.external-istiod.svc:443/validate?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "cluster.local")
It's not clear how to propagate certificates among different clusters and namespaces. We simply pointed  SSL_SECRET_NAME  to the secret holding   tls certificates.

**Comment by litong01** [comment] 2022-01-27 13:57
after a discussion in the environment working group, I've found that the right fix for this problem is when installing the first instance of the istiod in the istio-system namespace, disable the validating and injection webhook is the correct action to take. The external control plane doc needs to be updated to reflect this.

add the following when deploy the istio into istio-system namespace (not the external-istiod namespace)

    pilot:
      k8s:
        env:
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: ""
        - name: VALIDATION_WEBHOOK_CONFIG_NAME
          value: ""

**Comment by litong01** [comment] 2022-01-27 14:01
@pbonito the external control plane (2nd instance) need to be patched to allow the right certificates to be injected into the web hook. please do the following in the addition to the fix that I indicated above.

For the 2nd instance of the istiod using the empty profile, do the following:

```
        env:
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: "istio-sidecar-injector-external-istiod"
        - name: VALIDATION_WEBHOOK_CONFIG_NAME
          value: "istio-validator-external-istiod"
```
Notice that the document says to set these two to empty string which will not allow control plane to modify the webhooks's caBundle in the remote cluster.

With these two above fixes, you should be ok with certificates as well.

**Comment by litong01** [comment] 2022-01-27 14:05
The document will be updated with a PR. Thanks.

**Closed** 2022-02-07 18:06 UTC
Labels: area/environments

**Comment by s7an-it** [comment] 2022-07-28 19:50
For me this is always resolved by deleting any pre-existing webhooks from istio before re-install or upgrade.
