### ISSUE TITLE
PEER_DID_NOT_RETURN_A_CERTIFICATE error for VirtualServices exposing only HTTPS traffic

### ISSUE THREAD

**Issue by braunsonm** [istio/istio#29107] opened 2020-11-21 00:22 UTC
**Bug description**
If you have a gateway you want terminating connections (due to a valid SSL cert) but a backend service with a self signed cert, the request will fail with errors from the envoy proxy.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The request from the browser should have SSL terminated at the gateway, then forwarded to the sidecar, then the sidecar should negotiate TLS with the service.

**Steps to reproduce the bug**
1. Have Istio deployed 
2. `helm repo add stratos https://cloudfoundry.github.io/stratos`
3. `helm install my-console stratos/console --namespace=stratos`
4. Define the following Istio services:

```
---
kind: Namespace
apiVersion: v1
metadata:
  name: stratos
  labels:
    name: stratos
    istio-injection: enabled
spec:
  finalizers:
    - kubernetes

---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: stratos
  namespace: stratos
spec:
  gateways:
    - cf-system/istio-ingressgateway
  hosts:
    - console.example.com
  http:
    - route:
        - destination:
            host: console-ui-ext
            
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: stratos
  namespace: stratos
spec:
  host: console-ui-ext
  trafficPolicy:
    tls:
      mode: SIMPLE

---
kind: Gateway
SNIP
  - hosts:
    - console.example.com
    port:
      name: https-workloads
      number: 443
      protocol: HTTPS
    tls:
      credentialName: my-cert
      mode: SIMPLE
```

Now try to reach your service and watch the logs of the sidecar with debug logging. You will see the following:
<details>
  <summary>Logs</summary>

  ```
2020-11-20T23:47:26.259969283Z 2020-11-20T23:47:26.259818Z	debug	envoy filter	[C1384] new tcp proxy session
2020-11-20T23:47:26.259983483Z 2020-11-20T23:47:26.259842Z	debug	envoy filter	[C1384] Creating connection to cluster inbound|443|https|console-ui-ext.stratos.svc.cluster.local
2020-11-20T23:47:26.259988083Z 2020-11-20T23:47:26.259855Z	debug	envoy pool	creating a new connection
2020-11-20T23:47:26.259992483Z 2020-11-20T23:47:26.259878Z	debug	envoy pool	[C1385] connecting
2020-11-20T23:47:26.259995983Z 2020-11-20T23:47:26.259881Z	debug	envoy connection	[C1385] connecting to 127.0.0.1:443
2020-11-20T23:47:26.260015883Z 2020-11-20T23:47:26.259938Z	debug	envoy connection	[C1385] connection in progress
2020-11-20T23:47:26.260025083Z 2020-11-20T23:47:26.259952Z	debug	envoy pool	queueing request due to no available connections
2020-11-20T23:47:26.260028983Z 2020-11-20T23:47:26.259956Z	debug	envoy conn_handler	[C1384] new connection
2020-11-20T23:47:26.261224184Z 2020-11-20T23:47:26.260934Z	debug	envoy connection	[C1384] handshake expecting read
2020-11-20T23:47:26.261247984Z 2020-11-20T23:47:26.260951Z	debug	envoy connection	[C1385] connected
2020-11-20T23:47:26.261252484Z 2020-11-20T23:47:26.260955Z	debug	envoy pool	[C1385] assigning connection
2020-11-20T23:47:26.261255984Z 2020-11-20T23:47:26.260965Z	debug	envoy filter	TCP:onUpstreamEvent(), requestedServerName: 
2020-11-20T23:47:26.261259684Z 2020-11-20T23:47:26.260978Z	debug	envoy connection	[C1384] handshake expecting read
2020-11-20T23:47:26.263129385Z 2020-11-20T23:47:26.262953Z	debug	envoy connection	[C1384] handshake error: 1
2020-11-20T23:47:26.263142685Z 2020-11-20T23:47:26.262981Z	debug	envoy connection	[C1384] TLS error: 268435648:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
2020-11-20T23:47:26.263146885Z 2020-11-20T23:47:26.262985Z	debug	envoy connection	[C1384] closing socket: 0
2020-11-20T23:47:26.263150385Z 2020-11-20T23:47:26.263018Z	debug	envoy connection	[C1385] closing data_to_write=0 type=0
2020-11-20T23:47:26.263153885Z 2020-11-20T23:47:26.263022Z	debug	envoy connection	[C1385] closing socket: 1
2020-11-20T23:47:26.263157285Z 2020-11-20T23:47:26.263043Z	debug	envoy pool	[C1385] client disconnected
2020-11-20T23:47:26.263160685Z 2020-11-20T23:47:26.263064Z	debug	envoy conn_handler	[C1384] adding to cleanup list
2020-11-20T23:47:26.263164185Z 2020-11-20T23:47:26.263070Z	debug	envoy pool	[C1385] connection destroyed
  ```

However from the sidecar you can use `curl -k https://localhost` and get a correct response.
  
</details>

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
client version: 1.8.0
control plane version: 1.7.3
data plane version: 1.7.3 (35 proxies)

Client Version: v1.19.3
Server Version: v1.18.10

version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

```

**How was Istio installed?**
Deployed with cf-for-k8s project.

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by howardjohn** [comment] 2020-11-21 04:56
Sounds like the sidecar is expecting mtls but you are sending plain tls (from destination rule setting)

**Comment by braunsonm** [comment] 2020-11-21 05:00
I think that's exactly what it is! @howardjohn I read the docs about how one might solve this with a `ServiceEntry` but that involves passing HTTP traffic to the backend service, where I would need HTTPS here. 

Any idea on how I might solve this with Istio?

**Comment by howardjohn** [comment] 2020-11-21 05:04
ah you actually need https to the backend.. that is a bit trickier. I don't think it's possible to make the gateway initiate mtls+tls (ie double encapsulated tls). So your options would be to passthrough the tls directly at the gateway, or you could disable mtls on the backend service (see PeerAuthentication).

In theory we should be able to distinguish between an mtls request and plain tls request and automagically handle this but I suspect we don't today, and it's not obvious to me that would be "correct"

**Comment by howardjohn** [comment] 2020-11-21 05:04
This new doc may help a bit possibly https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/

**Comment by braunsonm** [comment] 2020-11-21 05:18
If the TLS is passed through then it would be terminated at the sidecar? Otherwise the sidecar would just end up encrypting the SSL again.

**Comment by howardjohn** [comment] 2020-11-21 05:20
The gateway can do a few things: terminate+encrypt, terminate, passthrough+encrypt, passthrough.

You want passthrough+encrypt so the sidecar terminates the outer mtls and the application gets the original tls from the client

Or disable the mtls on the sidecar and do termination+send plaintext

**Comment by braunsonm** [comment] 2020-11-21 05:30
If it is passthrough+encrypted then the `DestinationRule` would no longer be required since that asks for the traffic to be encrypted, but it already will be from the gateway?

Also is there any documentation on these modes? These docs don't seem to list them: https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-TLSmode

It sounds like disabling mtls is the easiest route. And you were right that worked. 
Do you want to leave this open for perhaps a troubleshooting doc about this or better error messages for this case?

**Comment by howardjohn** [comment] 2021-02-13 00:48
No, I think we can close this since its working as intended and documented. Thanks.

**Closed by howardjohn** 2021-02-13 00:48 UTC
Labels: feature/Multi-control-plane
