### ISSUE TITLE
Can't install v1.3.3 with helm v2.15.0

### ISSUE THREAD

**Issue by frdeng** [istio/istio#18095] opened 2019-10-20 06:24 UTC
**Bug description**
The installation works fine with helm v2.14.3

$ helm version
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

$ helm install istio-1.3.3/install/kubernetes/helm/istio --name istio --namespace istio-system
Error: release istio failed: Deployment.apps "istio-sidecar-injector" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[*] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by willzhang** [comment] 2019-10-20 15:51
i have the same error
**kubernetes version**
```
[root@master istio-1.3.3]# kubectl version --short
Client Version: v1.16.1
Server Version: v1.16.1
[root@master istio-1.3.3]# kubectl get nodes
NAME     STATUS   ROLES    AGE     VERSION
master   Ready    master   5d10h   v1.16.1
[root@master istio-1.3.3]# 
```
**helm version**
```
[root@master istio-1.3.3]# helm version
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
[root@master istio-1.3.3]# 
```
**the error is :**
```
[root@master istio-1.3.3]# helm install install/kubernetes/helm/istio --name istio --namespace istio-system
Error: release istio failed: Deployment.apps "istio-sidecar-injector" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
```

**Comment by dumindu** [comment] 2019-10-21 05:03
Same issue. Any quick fix?

**Comment by dumindu** [comment] 2019-10-21 06:28
Having same issue. @morvencao Any update on this?

**Comment by Crayeth** [comment] 2019-10-21 16:25
Same for me with
`ENV TERRAFORM=0.12.12
ENV KUBE=1.16.2
ENV HELM=2.15.0
ENV ISTIO=1.3.3`

`Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Job.batch "istio-security-post-install-1.3.3" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Deployment.apps "istio-galley" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Deployment.apps "istio-ingressgateway" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Deployment.apps "kiali" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Deployment.apps "istio-policy" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Deployment.apps "istio-telemetry" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Deployment.apps "istio-pilot" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Deployment.apps "istio-citadel" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
Error from server (Invalid): error when creating "istio/1.3.3/istio.yaml": Deployment.apps "istio-sidecar-injector" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'`

**Comment by arctiqtim** [comment] 2019-10-21 17:05
Just ran into this today as well ... appears the issue is isolated to the latest helm release.  I confirmed installing helm 2.13 works.  All templates generate fine.  The issue seems to be that with helm 2.15 the "Values" for node affinity do NOT get populated.  Thus you end up with a failure to apply the deployment manifests.

Quick fix for now is a downgrade of Helm.

Cheers!

**Comment by morvencao** [comment] 2019-10-22 03:27
There is a filed issue in helm stream for helm v2.15, that a series of Helm template number functions are broken, suggest to skip this version of helm.
See: https://github.com/helm/helm/issues/6708

**Comment by dumindu** [comment] 2019-10-22 03:43
@arctiqtim  I tried to install istio with helm 2.13 but get following error while installing 
```
helm init --service-account tiller                                                                                                                                          1 ↵ | minikube ⎈ | 10:27:55 
$HELM_HOME has been configured at /home/dumindu/.helm.
Error: error installing: the server could not find the requested resource

```

**Comment by morvencao** [comment] 2019-10-22 04:11
@dumindu What's your k8s and helm version? What's the output of `helm init --output json`?

**Comment by dumindu** [comment] 2019-10-22 04:22
```js
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Deployment",
    "metadata": {
        "creationTimestamp": null,
        "labels": {
            "app": "helm",
            "name": "tiller"
        },
        "name": "tiller-deploy",
        "namespace": "kube-system"
    },
    "spec": {
        "replicas": 1,
        "strategy": {},
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "app": "helm",
                    "name": "tiller"
                }
            },
            "spec": {
                "automountServiceAccountToken": true,
                "containers": [
                    {
                        "env": [
                            {
                                "name": "TILLER_NAMESPACE",
                                "value": "kube-system"
                            },
                            {
                                "name": "TILLER_HISTORY_MAX",
                                "value": "0"
                            }
                        ],
                        "image": "gcr.io/kubernetes-helm/tiller:v2.13.1",
                        "imagePullPolicy": "IfNotPresent",
                        "livenessProbe": {
                            "httpGet": {
                                "path": "/liveness",
                                "port": 44135
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1
                        },
                        "name": "tiller",
                        "ports": [
                            {
                                "containerPort": 44134,
                                "name": "tiller"
                            },
                            {
                                "containerPort": 44135,
                                "name": "http"
                            }
                        ],
                        "readinessProbe": {
                            "httpGet": {
                                "path": "/readiness",
                                "port": 44135
                            },
                            "initialDelaySeconds": 1,
                            "timeoutSeconds": 1
                        },
                        "resources": {}
                    }
                ]
            }
        }
    },
    "status": {}
}
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "creationTimestamp": null,
        "labels": {
            "app": "helm",
            "name": "tiller"
        },
        "name": "tiller-deploy",
        "namespace": "kube-system"
    },
    "spec": {
        "ports": [
            {
                "name": "tiller",
                "port": 44134,
                "targetPort": "tiller"
            }
        ],
        "selector": {
            "app": "helm",
            "name": "tiller"
        },
        "type": "ClusterIP"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

**Comment by frdeng** [comment] 2019-10-22 05:07
The workaround is using helm 2.14.3, if you run in to `helm init` problem with k8s v1.16, use this workaround:
```
helm init --service-account tiller --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | sed 's@  replicas: 1@  replicas: 1\n  selector: {"matchLabels": {"app": "helm", "name": "tiller"}}@' | kubectl apply -f -

```

**Comment by dumindu** [comment] 2019-10-22 07:56
@frdeng Thanks for your tip. I always tried option 2 in https://istio.io/docs/setup/install/helm/ . This was worked perfectly with option 1. 

```
minikube start --memory=16384 --cpus=4

helm init --service-account tiller --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | sed 's@  replicas: 1@  replicas: 1\n  selector: {"matchLabels": {"app": "helm", "name": "tiller"}}@' | kubectl apply -f -

helm template istio-1.3.3/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f - 

helm template istio-1.3.3/install/kubernetes/helm/istio --name istio --namespace istio-system | kubectl apply -f -
```

**Comment by sdake** [comment] 2019-10-22 08:26
Reported this issue in istio/istio.io (our documentation).  Since this problem has been moved, I am closing this issue.

Cheers
-steve

**Closed by sdake** 2019-10-22 08:26 UTC
Labels: area/environments

**Comment by howardjohn** [comment] 2019-10-23 15:42
https://github.com/helm/helm/releases/tag/v2.15.1

**Comment by giggio** [comment] 2019-11-08 04:50
This still does not work with releases 2.15.2, and 2.16.0. I just tried both of them.
They found other errors on 2.16.0, and are planning a new release just now.
Any release beyond 2.14.3 breaks Istio and it seems that lots of other packages as well, so be really careful. I just lost a ton of time findind this out.
The end problem is that the mesh policy is not created because the jobs do not run.

**Comment by howardjohn** [comment] 2019-11-08 04:52
@giggio thanks for the info, I hadn't tried newer releases. They are helm bugs, nothing wrong on istio?

**Comment by giggio** [comment] 2019-11-08 15:33
Yes, all Helm bugs. I tried the exact same Istio chart, 1.3.4.

**Comment by ivankorn** [comment] 2019-11-28 15:46
> Any release beyond 2.14.3 breaks Istio and it seems that lots of other packages as well, so be really careful. I just lost a ton of time findind this out.

Helm 2.16.1 worked for me with doing the job for istio 1.4.0.

**Comment by giggio** [comment] 2019-11-28 16:53
I'm on Helm 3 now, and both `1.3.4` and `1.4.0` install fine.

**Comment by gadelkareem** [comment] 2020-01-22 15:19
@giggio can you confirm helm 3 is working with the latest chart? It seems that the CRDs are failing for everyone with helm 3

**Comment by giggio** [comment] 2020-01-22 18:37
I just got my whole team on `1.4.3` this week, we all installed our machines using Helm, including CRDs, using Helm3. It is working fine.
I don't know why, but on the Istio docs they mention that Istio does not work with Helm3, maybe some edge case is not working, but I haven't found anything breaking yet.

**Comment by gadelkareem** [comment] 2020-01-22 19:19
@giggio you are right I got it working too thanks. However adding the repo does not work, I had to clone the whole repo and point helm to the chart like so
```
git clone git@github.com:istio/istio.git istio
helm upgrade --install istio-init istio/install/kubernetes/helm/istio-init --namespace istio-system
helm upgrade --install istio istio/install/kubernetes/helm/istio --namespace istio-system
```
Did you do the same?

**Comment by giggio** [comment] 2020-01-22 20:00
I'm using the repos directly:

````bash
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.4.3/charts/
````

I don't know why they use the version on the url, it would be better to have all the versions under the same url, but anyway...

**Comment by gadelkareem** [comment] 2020-01-23 08:15
Oh got it the path to the chart was wrong, changed it to `istio.io/istio-init` :
```
helm upgrade --install istio-init istio.io/istio-init --namespace istio-system
```

**Comment by hazcod** [comment] 2020-02-25 08:50
@giggio : `NoSuchKeyThe specified key does not exist.No such object: istio-release/releases/1.4.3/charts/`
