### ISSUE TITLE
Cluster-Aware Service Routing: envoy not starting

### ISSUE THREAD

**Issue by jkbschmid** [istio/istio#12021] opened 2019-02-25 14:08 UTC
**Describe the bug**
Reproducing the example [Cluster-Aware Service Routing](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds) for milestone 1.1 is not possible, because [step 2.3 ](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/#setup-cluster-2) (Wait for the Istio pod on cluster2 to come up by checking their status) fails. This is because istio-egressgateway and istio-ingressgateway do not start and their readiness probe fails with Readiness probe statuscode 503.
```
istio-egressgateway-77b75f9c94-k6qpc      0/1     Running     0          55m
istio-ingressgateway-7f948b889-5sxh5      0/1     Running     0          54m
```
The logs of the istio-egressgateway show the following warnings:
```
2019-02-25 13:23:34.415][13][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:102] gRPC config stream closed: 14, no healthy upstream
[2019-02-25 13:23:34.415][13][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:56] Unable to establish new stream
[2019-02-25 13:23:34.717][13][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:102] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers
2019-02-25T13:23:35.572700Z     info    Envoy proxy is NOT ready: cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2019-02-25T13:23:37.572288Z     info    Envoy proxy is NOT ready: cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```
*Note*
This may be related to [another issue](https://github.com/istio/istio/issues/9504).

**Expected behavior**
The istio-ingressgateway and the istio-egressgateway readiness probe succeeds.

**Steps to reproduce the bug**
Follow the example until [step 2.3 ](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds).
**Version**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Istio 1.1.0-rc.0
**Installation**
Installed via helm install, as described in the example.

**Environment**
Cluster2 running on AWS, cluster1 on GCP.

**Comment by jkbschmid** [comment] 2019-02-25 14:08
Should be milestone 1.1 (community testing)

**Comment by nmittler** [comment] 2019-02-25 20:24
@jkbschmid it looks like your Pilot may not be coming up.  Other folks have been seen something similar: 

https://github.com/istio/istio/issues/9504#issuecomment-467139525
https://github.com/istio/istio/issues/12020#issuecomment-467040873

cc @sdake @markserrano915

**Comment by linsun** [comment] 2019-02-26 03:09
Is it possible your ingress gateway and egress gateway unable to talk to Pilot (I assume it is on the primary cluster)?  I have seen the case when my gateway can't talk to my pilot.

cc @ymesika

**Comment by ymesika** [comment] 2019-02-26 06:37
It's most probably that the proxies in your ingress/egress gateways weren't able to connect to the primary pilot.
I would do few things to try and find the root cause:
1. Wait a little. It takes some time for the Citadel on your 2nd cluster to generate the secrets and for the proxies to pick them up in order to securely connect to the primary pilot
1. Check Pilot's logs for errors
1. Did all the primary cluster's Istio component managed to run (e.g. did the primary ingress connect to Pilot)?
1. Check whether the IP address you provided when creating the `istio-remote-auth.yaml` (`$LOCAL_GW_ADDR`) is correct and accessible from the remote cluster

**Comment by jkbschmid** [comment] 2019-02-26 12:15
1. Waiting does not solve it (55m). We also looked at the logs and didn't see the typical error message that appears when envoy cannot find certs.
2. Pilot shows the following errors. The first one looks more interesting to me.
```
2019-02-26T11:52:57.751216Z     info    1 error occurred:

* gateway omitting listener "0.0.0.0_15011" due to: must have more than 0 chains in listener: &v2.Listener{Name:"0.0.0.0_15011", Address:core.Address{Address:
(*core.Address_SocketAddress)(0xc420a8b5a0), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, FilterChains:[]listener.Filter
Chain{}, UseOriginalDst:nil, PerConnectionBufferLimitBytes:nil, Metadata:(*core.Metadata)(nil), DeprecatedV1:(*v2.Listener_DeprecatedV1)(nil), DrainType:0, Li
stenerFilters:[]listener.ListenerFilter(nil), ListenerFiltersTimeout:(*time.Duration)(nil), Transparent:nil, Freebind:nil, SocketOptions:[]*core.SocketOption(
nil), TcpFastOpenQueueLength:nil, BugfixReverseWriteFilterOrder:nil, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
```
And also this one:
```
2019-02-26T12:03:01.927294Z     info    ads     ADS: "127.0.0.1:46906" router~100.96.1.6~istio-egressgateway-5fdcbdb595-5cjbq.istio-system~istio-system.svc.cluster.local-533 terminated rpc error: code = Canceled desc = context canceled
2019-02-26T12:03:02.127252Z     info    ads     ADS: "127.0.0.1:46906" router~100.96.1.4~istio-ingressgateway-6c8bf9f58d-gf66w.istio-system~istio-system.svc.cluster.local-534 terminated rpc error: code = Canceled desc = context canceled
```

Note that `egressgateway-5fdcbdb595` and `ingressgateway-6c8bf9f58d` are from cluster 1. We cannot find anything from cluster 2 in the pilot's log.

3. The primary cluster's components managed to run:
```
$ kubectl get pods  --context=$CTX_CLUSTER1 -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-5959bcdb74-cqpdx            1/1     Running     0          21h
istio-cleanup-secrets-1.1.0-rc.0-jndff    0/1     Completed   0          21h
istio-egressgateway-5fdcbdb595-5cjbq      1/1     Running     0          21h
istio-galley-7f76d7479f-rsnc2             1/1     Running     0          21h
istio-ingressgateway-6c8bf9f58d-gf66w     1/1     Running     0          21h
istio-pilot-6dcb45898c-mgbn9              2/2     Running     0          21h
istio-policy-5f9b54b85f-94brf             2/2     Running     2          21h
istio-sidecar-injector-5769c94686-s6hfx   1/1     Running     0          21h
istio-telemetry-69d8bcdb95-2gjrr          2/2     Running     2          21h
prometheus-68c5594ddc-hqhsv               1/1     Running     0          21h
```

4. IP is correct.

**Comment by ymesika** [comment] 2019-02-26 13:12
@jkbschmid Yes, the error relevant because port 15011 is the gateway port that remote ingress/egress are connecting through it to the primary Pilot. Because it got omitted (because of this error) they are failing to start.

Can you please put somewhere (pastebin?) the `istio-auth.yaml` and `istio-remote-auth.yaml` that have been created?

**Comment by jkbschmid** [comment] 2019-02-26 14:12
[istio-auth.yaml](https://pastebin.com/hL2sfnuM) [istio-remote-auth.yaml](https://pastebin.com/apjVEG7g). 
 Before uploading to pastebin, we replaced the IP we use with $LOCAL_GW_ADDR.
Other than that, you should be able to reproduce these files by applying the two `helm template` commands in the [example](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds).

**Comment by ymesika** [comment] 2019-02-26 18:52
Seems like you are hitting the https://github.com/istio/istio/issues/8374 problem.

Because I'm unable to reproduce it on my IKS clusters with rc0, are you able to help checking whether removing the `meshexpansion-gateway` `Gateway` from the `istio-auth.yaml` into its own file and deploying it after `istio-auth.yaml` is indeed solving this?

Do you consistently getting this? Based on the issue above it's a timing issue and pretty rare based on my experience.

**Comment by jkbschmid** [comment] 2019-02-27 07:58
I did as you suggested and deployed the `meshexpansion-gateway` in a separate file and with some delay. This did indeed fix the `gateway omitting listener`-error in the pilot, but the gateways on cluster 2 are still not becoming ready. :(
These are the logs of istio-egress on cluster 2, if that gives you any more information.
```
[2019-02-27 07:40:12.243][13][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.listener.Filter.conf
ig'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-02-27 07:40:12.243][13][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.Cluster.hosts'. This
 configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-02-27 07:40:12.243][13][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.Cluster.hosts'. This
 configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-02-27 07:40:12.243][13][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.Cluster.hosts'. This
 configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-02-27 07:40:12.243][13][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.trace.v2.Tracing.Htt
p.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-02-27 07:40:12.254][13][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_
stream.h:102] gRPC config stream closed: 14, no healthy upstream
[2019-02-27 07:40:12.254][13][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_
stream.h:56] Unable to establish new stream
[2019-02-27 07:40:12.345][13][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_
stream.h:102] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers
[2019-02-27 07:40:12.742][13][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_
stream.h:102] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers
2019-02-27T07:40:13.429792Z     info    Envoy proxy is NOT ready: cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```
For the record, cluster 1 is an AWS cluster and cluster 2 is a GKE cluster. Not sure if this has anything to do with the issue we are seeing.

**Comment by linsun** [comment] 2019-04-12 13:55
@vadimeisenbergibm can you check if this is being addressed in some of the multicluster stabilization work being planned?

**Comment by vadimeisenbergibm** [comment] 2019-04-12 16:33
@vadimeisenbergibm will do.

**Comment by vadimeisenbergibm** [comment] 2019-04-12 16:33
@linsun will do.

**Comment by vadimeisenbergibm** [comment] 2019-09-04 02:25
@jkbschmid Do you still have this issue?

**Comment by jkbschmid** [comment] 2019-09-04 08:25
@vadimeisenbergibm I haven't seen the issue lately.

**Comment by vadimeisenbergibm** [comment] 2019-09-04 12:22
OK, @jkbschmid, thanks, if so, could you please close this issue?

**Closed** 2019-09-04 13:32 UTC
Labels: area/environments, area/networking
