### ISSUE TITLE
Better support for sidecar containers in batch jobs

### ISSUE THREAD

**Issue by ayj** [istio/istio#6324] opened 2018-06-15 16:16 UTC
Sidecar containers do not play well with k8s jobs. The job will keep running so long as the sidecar proxy is running. This is a general problem not specific to Istio (see https://github.com/kubernetes/kubernetes/issues/25908). The typical workaround includes explicit terminate signaling between app and sidecar container such that the sidecar can exit when the app does.

**Comment by ayj** [comment] 2018-06-15 16:17
cc @Rigdon

**Comment by costinm** [comment] 2018-06-25 17:51
Martin going in vacation. 

Targeting to 1.0 - since it seems to just not work for batch jobs as expected.

**Comment by costinm** [comment] 2018-06-25 17:52
Quick fix: Add a '/quitquitquit' handler to proxy-agent. Users can manually add a curl or http request to localhost to stop sidecar when the job is done ( or we can add it automatically - but P0 is to have a workaround, we can improve it in 1.1 )

**Comment by cjongseok** [comment] 2018-06-29 16:46
Hello guys. I had the same issue on my k8s cronjob. It seems /quitquitquit handler in pilot-agent is not implemented yet. So I made a PR. 

I looked through both envoy and pilot-agent and could notice [Agent waits until the next 'config update'](https://github.com/istio/istio/blob/a4df8f85dcf3c32d4fd944e69f662a51b1eb43da/pilot/pkg/proxy/agent.go#L185), if the last epoch terminates normally. I think in case of 'config update' Istio users do not explicitly terminate epochs, since it supports hot-reloading. So the main purpose of the normal termination of the last epoch would be closer to the pilot-agent termination.

With this assumption, the PR does gracefule shutdown of the pilot-agent on the last normal epoch termination. I think it can reduce the chance of being zombie agent in not only /quitquitquit but also other normal envoy terminations.

I hope the PR saves you guys’ time for this issue.

**Comment by jwendell** [comment] 2018-10-12 18:37
So, here's a working PoC: https://github.com/istio/istio/pull/9307

It uses kubernetes API to watch for pod changes, and finishes pilot-agent when all the pod containers finish.

Caveats:
- The job must use a service account with permission to get,list,watch pods in the namespace
- Automatic sidecar injection (via MutatingAdmissionWebhook) does not add the the volume mount for the service account (containing `mountPath: /var/run/secrets/kubernetes.io/serviceaccount`) preventing an in-cluster k8s client to work on the istio-proxy container. It works fine with manual injection though. https://github.com/kubernetes/kubernetes/issues/69733

Comments? Ideas?

**Comment by kyessenov** [comment] 2018-10-12 18:42
There was a strong opposition to linking client-go into sidecar agent due to the size of the library.
I wonder if there is a mechanism to achieve the effect without contacting the api server -- maybe using termination commands on containers.

**Comment by zombor** [comment] 2019-01-11 20:54
Is there any kind of reasonable workaround for this?

**Comment by GregHanson** [comment] 2019-01-25 21:49
@zombor A user has had some success with: https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/
involves:
- appending this to the container command: `pkill -f /usr/local/bin/pilot-agent`
- and add `shareProcessNamespace: true` to the *Pod* spec

**Comment by TristanPeers** [comment] 2019-02-07 08:32
@GregHanson - many thanks for the tip. Alas the command listed always caused the pod to exit abnormally for me:

```
    State:          Terminated
      Reason:       Error
      Exit Code:    143
```

I found changing the pkill signal fixed the issue properly. Note I'm using this in `helm test` and need the correct exit value from the main container. Here's a simple example:

Before:
```
Command:
     sh
     -c
     sleep 20;/usr/bin/curl http://dl-cdn.alpinelinux.org --fail; exit_code=$?; echo code is $exit_code; pkill -f /usr/local/bin/pilot-agent; exit $exit_code;
   State:          Terminated
     Reason:       Error
     Exit Code:    143
```

After:
```
    Command:
      sh
      -c
      sleep 20;/usr/bin/curl http://dl-cdn.alpinelinux.org --fail; exit_code=$?; echo code is $exit_code; pkill -INT /usr/local/bin/pilot-agent; exit $exit_code;
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
```

**Comment by Stono** [comment] 2019-02-11 10:38
@costinm the `quitquitquit` doesn't work, see: https://github.com/istio/istio/issues/11659

**Comment by cmeyertons** [comment] 2019-03-14 11:38
@TristanPeers worked enough for me as a workaround.

I see in his, he has a sleep in there -- I was noticing things erroring out unless I put in a sleep.  It sounds like some logic is missing in the init_container to properly initialize before letting the main container run wild.

**Comment by esnible** [comment] 2019-03-23 22:20
Another work around would be an `istioctl quit-terminated-jobs` hack to look for jobs and do `kubectl exec <pod> -c istio-proxy -- curl -X POST localhost:15000/quitquitquit` on them.  That would at least make it easy to script this process.

Could Galley or another component could include a controller to watch for Job pods going into `containerStatuses[*].state.terminated.reason=completed` and POST a quit message to the sidecar?  Or pollute Pilot's gRPC stream with some kind of poison pill that causes Envoy to suicide?

**Comment by esnible** [comment] 2019-03-23 22:24
@cmeyertons Kubernetes won't let the Envoy sidecar pod start until the init container has completed.  Kubernetes starts the job and the sidecar together.  The app won't have networking until Envoy initializes.  We are tracking possible solutions under https://github.com/istio/istio/issues/11130

I add some code to my deployment descriptor to cause it to sleep before Envoy is ready.  (Replace `startup.sh` below with the original command)

```
command: ["/bin/bash", "-c"]
args: ["until curl --head localhost:15000 ; do echo Waiting for Sidecar; sleep 3 ; done ; echo Sidecar available; ./startup.sh"]
```

**Comment by cjongseok** [comment] 2019-04-08 11:33
It seems sidecar container support in k8s is under development here (https://github.com/kubernetes/enhancements/issues/753). I hope it would be merged into the next k8s release and resolve this issue.

**Comment by jackkleeman** [comment] 2019-04-18 11:47
Hey, we here at Monzo have open sourced our solution to this sequencing problem:
https://github.com/monzo/envoy-preflight
The idea is, it's a wrapper around your main application, which ensures it starts after envoy is live, and shuts down envoy when its done. You'll still need to prevent sigterms from reaching envoy.
We use this for batch jobs to ensure that all containers actually exit when the work is done.

**Comment by planetf1** [comment] 2019-05-14 11:54
See https://istio.io/help/ops/setup/injection/

**Comment by howardjohn** [comment] 2019-08-14 16:15
> Quick fix: Add a '/quitquitquit' handler to proxy-agent. Users can manually add a curl or http request to localhost to stop sidecar when the job is done

In 1.3 we added a /quitquitquit endpoint to pilot-agent

**Comment by planetf1** [comment] 2019-08-21 19:42
This looks like a useful example for the general case (for example I have some k8s jobs which will fail to complete once istio sidesar is deployed) https://medium.com/@cotton_ori/how-to-terminate-a-side-car-container-in-kubernetes-job-2468f435ca99

**Comment by howardjohn** [comment] 2019-09-22 22:13
In 1.3 we added a new `/quitquitquit` endpoint to pilot agent which should resolve this. Its not perfect since it requires some manual action, but I think a longer term solution would depend on https://github.com/kubernetes/kubernetes/issues/65502 or https://github.com/istio/istio/issues/11366 or similar. If there is anything else we can do to improve these in the short term I would be happy to take a look at

**Closed by howardjohn** 2019-09-22 22:13 UTC
Labels: area/environments, kind/customer issue

**Comment by wreed4** [comment] 2019-09-25 19:28
The referenced commit here seems to provide a good liveness probe for cronjobs, but not regular jobs or simply on-demand pods run by `kubectl run`.

**Comment by planetf1** [comment] 2019-10-04 09:36
I agree that a real fix likes in #k8s, but the perception is that by enabling istio (auto injection), an existing application is broken where it uses jobs. Without that being addressed having the issue closed seems uncomfortable - whilst I recognize it's hard to fix. This is the case even though this isn't istio specific, but a k8s sidecar issue.

At a minimum I would suggest adding some caveat into the docs (especially wrt sidecar injection), and possibly linking the k8s issue (and push that). Ideally outlining any mitigation strategies.

Apologies I've not got around to working through approaches on my project yet.

**Comment by kenske** [comment] 2020-02-19 00:55
Here's what I ended up doing as a workaround. Only works with istio >= 1.3. Modify your entrypoint to make a call to the proxy container asking it to shut itself down:

```
containers:
   command: ["/bin/bash", "-c", "/path/to/your/main/entrypoint && curl -X POST http://localhost:15020/quitquitquit"]
```

**Comment by tcnghia** [comment] 2020-04-19 18:33
The K8s fix seems not yet prioritized (https://github.com/kubernetes/enhancements/issues/753), so I am reopening this bug to see if we can find more workarounds in the short term.

A Job `foo`'s Pods would have labels `job-name: foo`.  They also often have `restartPolicy: Never`.  Can we make the sidecar injection require explicit opt-in for these kinds of Pods?  Then the job doesn't need to explicitly call `/quitquitquit`.

**Comment by pbn4** [comment] 2020-05-28 13:16
For Istio 1.6 and kubernetes I changed entrypoint to following:

```
        command: ["/bin/sh", "-c"]
        args: [
          'until $(curl --output /dev/null --silent --head --fail http://localhost:15021/healthz/ready); do echo . ; sleep 5; done; my_command'
        ] 
```

**Comment by ismailbaskin** [comment] 2020-05-29 11:34
@pbn4 Doesn't Istio need `/quitquitquit`?

**Comment by diseku** [comment] 2021-01-14 12:09
```
- command:
  - /bin/sh
  - -c
  - |
    until curl -fsI http://localhost:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done;
    echo \"Sidecar available. Running the command...\";
    <YOUR_COMMAND>;
    x=$(echo $?); curl -fsI -X POST http://localhost:15020/quitquitquit && exit $x
```

**Comment by sneko** [comment] 2022-02-10 22:29
I'm for a long time using the `/quitquiquit` technic to end properly my job... but that's true I added a durty "sleep" in the past to wait for the sidecards to be ready (didn't want to add shell loops on all my deployments... moreover when you use Helm charts managing the command is not always possible).

Trying to catch up what's new I found this:
https://github.com/istio/istio/issues/33911#issuecomment-877010732

Do you use now this technic @diseku @pbn4 instead of the loop over `/ready`?

Thank you,

**Comment by abdolence** [comment] 2023-07-18 12:54
The provided workaround is not good enough if no shell available in your docker images (consider Distroless images for example). What are other possible options here? 
I think this ticket should be reopened, since this is not resolved for all of the cases.

**Comment by ismailbaskin** [comment] 2023-07-18 13:07
Let's have a little more patience and watch the upcoming sidecar containers solve this problem properly.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers

https://github.com/kubernetes/kubernetes/pull/116429

**Comment by Stono** [comment] 2023-07-18 13:14
I agree with @imikushin; sidecar contains are coming in 1.29.
In the interim we've written a custom controller that watches Pods, waits for them to be in a terminating state and then kills the sidecars.  It's less than ideal but this is a core kubernetes problem (hence the kep).

Here's the source code for our handler (effectively something that responds to a watch on kubernetes pods): https://gist.github.com/Stono/05d3137c166890bb5587b3f0cc59dc80.  You obviously won't be able to use it verbatim but the logic might help you.

**Comment by abdolence** [comment] 2023-07-18 13:21
Thanks @Stono for the example - definitively will be valuable not just for me 👍🏻 

This is not about patience (the issue is from 2018, so I think we're crossed that check). My point is more like making awareness that the problem is not closed, yet ticket status was confusing. I understand there are limitations coming from k8s, and long term fix only possible with the kubernetes upgrades.

**Comment by ofey404** [comment] 2023-09-20 05:47
+1, I encounter this problem too.

**Comment by hzxuzhonghu** [comment] 2023-09-20 06:12
@ofey404 Istio has supported sidecar container feature, you need to upgrade to  k8s 1.18+, and istio 1.19+

**Comment by zirain** [comment] 2023-09-20 06:41
see the blog: https://istio.io/latest/blog/2023/native-sidecars/

**Comment by abdolence** [comment] 2023-09-20 07:12
> you need to upgrade to k8s 1.18+

You probably meant 1.28+, not 1.18.

**Comment by hzxuzhonghu** [comment] 2023-09-20 10:09
updated
