### ISSUE TITLE
Istio readiness probe failed throughout Istio on AKS (Azure's Hosted platform)

### ISSUE THREAD

**Issue by sdake** [istio/istio#12020] opened 2019-02-25 14:07 UTC
**Describe the bug**
Depoy Istio rc0 on AKS results in loads of readiness failures and the Istio control plane doesn't start.

**Expected behavior**
The Istio control plane starts.

**Steps to reproduce the bug**
Deploy istio using steps described in **installation**

**Version**
AKS / Kubernetes 1.12.1 + rc0

**Installation**
```
helm template install/kubernetes/helm/istio-init --namespace istio-system > ~/istio-init.yaml
helm template install/kubernetes/helm/istio --namespace istio-system > ~/istio.yaml
kubectl apply -f $HOME/istio-init.yaml
<wait until 57 crds are registered>
kubectl apply -f $HOME/istio.yaml
```

**Environment**
Azure AKS

Some extra information:
```sdake-mac-0:istio-1.1.0-rc.0 sdake$ kubectl get pods -n istio-system
NAME                                     READY   STATUS      RESTARTS   AGE
istio-citadel-6c6c9c9fb9-m7crp           1/1     Running     0          14m
istio-cleanup-secrets-1.1.0-rc.0-gj9j9   0/1     Completed   0          15m
istio-egressgateway-8679595ccb-sc2cg     0/1     Running     0          14m
istio-galley-7688dd7f6d-l5n77            1/1     Running     0          14m
istio-ingressgateway-68ff9578c5-86s4g    0/1     Running     0          14m
istio-init-crd-10-rlkwm                  0/1     Completed   0          16m
istio-init-crd-11-tqk5f                  0/1     Completed   0          15m
istio-init-crd-certmanager-10-qkvcz      0/1     Completed   0          15m
istio-pilot-854768f46d-9kvdx             0/2     Pending     0          14m
istio-policy-855d9c6d88-87gqm            2/2     Running     2          14m
istio-sidecar-injector-b59745dc6-xzhsl   1/1     Running     0          14m
istio-telemetry-76cdf96544-vr259         2/2     Running     2          14m
prometheus-5f558dd7cf-m7s7r              1/1     Running     0          14m
```

```
sdake-mac-0:istio-1.1.0-rc.0 sdake$ kubectl describe po istio-ingressgateway-68ff9578c5-86s4g -n istio-system
Name:               istio-ingressgateway-68ff9578c5-86s4g
Namespace:          istio-system
Priority:           0
PriorityClassName:  <none>
Node:               aks-defaultpool-10399049-0/172.23.0.35
Start Time:         Mon, 25 Feb 2019 06:50:44 -0700
Labels:             app=istio-ingressgateway
                    chart=gateways
                    heritage=Tiller
                    istio=ingressgateway
                    pod-template-hash=68ff9578c5
                    release=release-name
Annotations:        scheduler.alpha.kubernetes.io/critical-pod: 
                    sidecar.istio.io/inject: false
Status:             Running
IP:                 172.23.0.57
Controlled By:      ReplicaSet/istio-ingressgateway-68ff9578c5
Containers:
  istio-proxy:
    Container ID:  docker://efaf97fd0bb43648882ac706b409c9aa13f8465916ef0824389d2caec188e202
    Image:         docker.io/istio/proxyv2:1.1.0-rc.0
    Image ID:      docker-pullable://istio/proxyv2@sha256:7f0c76289e96cbc2a3e2508b5408282c31321c9649d03c535711337cd33b45a4
    Ports:         80/TCP, 443/TCP, 31400/TCP, 15029/TCP, 15030/TCP, 15031/TCP, 15032/TCP, 15443/TCP, 15090/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      router
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --log_output_level
      info
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --connectTimeout
      10s
      --serviceCluster
      istio-ingressgateway
      --zipkinAddress
      zipkin:9411
      --proxyAdminPort
      15000
      --statusPort
      15020
      --controlPlaneAuthPolicy
      NONE
      --discoveryAddress
      istio-pilot:15010
    State:          Running
      Started:      Mon, 25 Feb 2019 06:50:58 -0700
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                      istio-ingressgateway-68ff9578c5-86s4g (v1:metadata.name)
      POD_NAMESPACE:                 istio-system (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      ISTIO_META_POD_NAME:           istio-ingressgateway-68ff9578c5-86s4g (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:   istio-system (v1:metadata.namespace)
      ISTIO_META_ROUTER_MODE:        sni-dnat
      KUBERNETES_PORT_443_TCP_ADDR:  netu53b1f2-b191c42a.hcp.eastus.azmk8s.io
      KUBERNETES_PORT:               tcp://netu53b1f2-b191c42a.hcp.eastus.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://netu53b1f2-b191c42a.hcp.eastus.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       netu53b1f2-b191c42a.hcp.eastus.azmk8s.io
    Mounts:
      /etc/certs from istio-certs (ro)
      /etc/istio/ingressgateway-ca-certs from ingressgateway-ca-certs (ro)
      /etc/istio/ingressgateway-certs from ingressgateway-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-ingressgateway-service-account-token-c2rbr (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-ingressgateway-service-account
    Optional:    true
  ingressgateway-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-certs
    Optional:    true
  ingressgateway-ca-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-ca-certs
    Optional:    true
  istio-ingressgateway-service-account-token-c2rbr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-service-account-token-c2rbr
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                 Message
  ----     ------     ----                 ----                                 -------
  Normal   Scheduled  15m                  default-scheduler                    Successfully assigned istio-system/istio-ingressgateway-68ff9578c5-86s4g to aks-defaultpool-10399049-0
  Normal   Pulling    15m                  kubelet, aks-defaultpool-10399049-0  pulling image "docker.io/istio/proxyv2:1.1.0-rc.0"
  Normal   Pulled     15m                  kubelet, aks-defaultpool-10399049-0  Successfully pulled image "docker.io/istio/proxyv2:1.1.0-rc.0"
  Normal   Created    15m                  kubelet, aks-defaultpool-10399049-0  Created container
  Normal   Started    15m                  kubelet, aks-defaultpool-10399049-0  Started container
  Warning  Unhealthy  49s (x444 over 15m)  kubelet, aks-defaultpool-10399049-0  Readiness probe failed: HTTP probe failed with statuscode: 503
```

**Comment by sdake** [comment] 2019-02-25 14:08
This looks sort of odd ``` Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP```

**Comment by sdake** [comment] 2019-02-25 14:13
This may be 1.1.1 material - but moving into 1.1 for the moment.  I know @nmittler has done some work around readiness probes, and I recently saw @hzxuzhonghu fixed a related bug to port 0 listeners (although it may not be this actual bug).

Cheers
-steve

**Comment by sdake** [comment] 2019-02-25 14:15
Load balancer looks good:
```
sdake-mac-0:istio-1.1.0-rc.0 sdake$ kubectl describe svc istio-ingressgateway -n istio-system
Name:                     istio-ingressgateway
Namespace:                istio-system
Labels:                   app=istio-ingressgateway
                          chart=gateways
                          heritage=Tiller
                          istio=ingressgateway
                          release=release-name
Annotations:              kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","chart":"gateways","heritage":"Til...
Selector:                 app=istio-ingressgateway,istio=ingressgateway,release=release-name
Type:                     LoadBalancer
IP:                       10.3.0.208
LoadBalancer Ingress:     13.68.140.227
Port:                     http2  80/TCP
TargetPort:               80/TCP
NodePort:                 http2  31380/TCP
Endpoints:                
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  31390/TCP
Endpoints:                
Port:                     tcp  31400/TCP
TargetPort:               31400/TCP
NodePort:                 tcp  31400/TCP
Endpoints:                
Port:                     https-kiali  15029/TCP
TargetPort:               15029/TCP
NodePort:                 https-kiali  31826/TCP
Endpoints:                
Port:                     https-prometheus  15030/TCP
TargetPort:               15030/TCP
NodePort:                 https-prometheus  31066/TCP
Endpoints:                
Port:                     https-grafana  15031/TCP
TargetPort:               15031/TCP
NodePort:                 https-grafana  31206/TCP
Endpoints:                
Port:                     https-tracing  15032/TCP
TargetPort:               15032/TCP
NodePort:                 https-tracing  30076/TCP
Endpoints:                
Port:                     tls  15443/TCP
TargetPort:               15443/TCP
NodePort:                 tls  31135/TCP
Endpoints:                
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  24m   service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   23m   service-controller  Ensured load balancer```

**Comment by sdake** [comment] 2019-02-25 14:46
If any Istio member contributor is willing to debug this issue, ping me, and I'll provide a kubeconfig file for the cluster in question.

Cheers
-steve

**Comment by sdake** [comment] 2019-02-25 14:54
just noticed pilot is pending - insufficient CPU with default install.  WIll increase the CPU core count in the cluster and redeploy.  This is likely an environmental problem but will reset to 1.1 if not.

**Comment by ozevren** [comment] 2019-02-25 19:36
Ignore my add/remove of milestone 1.1, didn't see @sdake's milestone edits.

**Comment by duderino** [comment] 2019-02-26 20:32
P0 so we don't lose track of this, but i'm hoping it's a duplicate of the issues @nmittler referenced or perhaps https://github.com/istio/istio/issues/11964

**Comment by sdake** [comment] 2019-03-01 03:01
@duderino I will retest, but I believe the root cause was insufficient CPU in my cloud provider.  The defaults have changed to north of 6 CPUs (from 1).  The readiness error is a red herring - instead the fact that pilot was never scheduled was the root of the problem.  This is exacerbated by the fact that application sidecars without a pilot present spit out this nonsensical error about port 0 not being ready, further confusing operators with small eval deployments.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-01 03:52
@duderino pretty sure we can close this, assuming someone opens a bug in istio.io to document the minimum requirements for CPU and memory for Istio in the default deployment.  I ran with 4 worker nodes running 4 CPU * 8GB each and had a successful deployment.

Cheers
-steve

**Comment by duderino** [comment] 2019-03-01 21:45
thanks @sdake

**Closed by duderino** 2019-03-01 21:45 UTC
Labels: area/environments
