### ISSUE TITLE
Support direct response in VirtualService

### ISSUE THREAD

**Issue by illidan80** [istio/istio#29264] opened 2020-11-30 09:31 UTC
For example, I would like to have something like this:

```
apiVersion: networking.istio.io/v1alpha3 
kind: VirtualService 
metadata:
  name: myservice-vs 
  namespace: mynamespace
spec:
  hosts:
  - "my.host"
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        prefix: /mypath
    route:
     - response:
         code: 200
         body: "this is automatic response"
```

**Comment by hzxuzhonghu** [comment] 2020-11-30 12:48
Looks like a necessary feature

**Comment by esnible** [comment] 2020-11-30 13:27
Duplicate of auto-closed https://github.com/istio/istio/issues/12096 and discussed at https://discuss.istio.io/t/support-for-envoys-direct-response/2349

I believe this could be done with an EnvoyFilter today https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/direct_response/v2/config.proto

**Comment by p53** [comment] 2021-03-09 13:37
this would be useful, can be done several ways but with workarounds would consume more resources than optimal

**Comment by Zeka13** [comment] 2021-04-28 17:13
I am still confused how I can implement this with istio (I am migrating from nginx ingress controller)

**Comment by esnible** [comment] 2021-05-03 12:09
You can do this with WebAssembly code and `sendLocalResponse()`.  I have tried it and it works.

A better way is to use Envoy's [DirectResponseAction](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-directresponseaction).  I believe Istio can provide this configuration to Envoy using an EnvoyFilter [RouteMatch.Action](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch-RouteMatch-Action).  I have not tried it myself nor was I able to locate an example to point you at.

**Comment by Zeka13** [comment] 2021-05-03 13:17
@esnible Hello! Actually I am also didn't find any proper example and noone answered me back there https://discuss.istio.io/t/please-assist-me-with-using-envoyfilter-routeconfigurationmatch-action-direct-response/10388

This is really not easy to undestand this EnvoyFilter entity without simple examples :(

**Comment by esnible** [comment] 2021-05-03 16:45
I have tagged `extensions and telemetry`, you really have what the Istio developers would call an "extension" use case.

I will ask if anyone has examples as the next Telemetry and Extensions meeting.

**Comment by Zeka13** [comment] 2021-05-03 17:54
@esnible thanks a lot

**Comment by esnible** [comment] 2021-05-05 16:12
I asked at T&E.  I was pointed to https://github.com/istio/istio/wiki/EnvoyFilter-Samples which is where the EnvoyFilter samples are kept.  My hope is that someone adds one.  If not, I will see what I can do.  (But not this week...)

**Comment by ostapio** [comment] 2021-05-31 13:16
hey @esnible 
im trying to figure out direct_response too...

`apiVersion:` networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: direct-response
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        portNumber: 8080
        vhost:
          name: "demo.default.svc.cluster.local:8080"
    patch:
      operation: INSERT_FIRST
      value:
        name: "direct"
        decorator:
          operation: "demo.default.svc.cluster.local:8080/*"
        match:
          path: "/direct"
        directResponse:
          body:
            inlineString: 'hello world'
          status: 200
`
with this filter i got 
`
"routes": [
    {
        "match": {
            "path": "/direct"
        },
        "decorator": {
            "operation": "demo.default.svc.cluster.local:8080/*"
        },
        "direct_response": {
            "status": 200,
            "body": {
                "inline_string": "hello world"
            }
        },
        "name": "direct"
    },
    {
        "match": {
            "prefix": "/"
        },
        "route": {
            "cluster": "outbound|8080||demo.default.svc.cluster.local",
            "timeout": "0s",
            "retry_policy": {
                "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                "num_retries": 2,
                "retry_host_predicate": [
                    {
                        "name": "envoy.retry_host_predicates.previous_hosts"
                    }
                ],
                "host_selection_retry_max_attempts": "5",
                "retriable_status_codes": [
                    503
                ]
            },
            "max_stream_duration": {
                "max_stream_duration": "0s"
            }
        },
        "decorator": {
            "operation": "demo.default.svc.cluster.local:8080/*"
        },
        "name": "default"
    }
]
`
config generated but im still getting response from downstream...
istio 1.8.2 envoy 1.16.1

**Comment by Zeka13** [comment] 2021-05-31 17:08
this looks very complicated for me, I hope one day there will be just annotion for it (like in another ingress controllers)

**Comment by ostapio** [comment] 2021-05-31 17:23
managed to get it working on gateway level

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: direct
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: <domain_here>:443
    patch:
      operation: INSERT_FIRST
      value:
        name: direct
        match:
          path: /direct
        directResponse:
          body:
            inlineString: 'hello world'
          status: 200
```

**Comment by Zeka13** [comment] 2021-06-01 12:58
@ostapio could you please take a look at my setup, because I am getting HTTP ERROR 404

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-istio-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - some.server
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https-443
        protocol: HTTPS
      hosts:
        - some.server
      tls:
        mode: SIMPLE
        credentialName: full-chain-certificate
```

then I create your EnvoyFilter in default namespace with 

```
      routeConfiguration:
        vhost:
          name: some.server:443
```

And https://some.server/direct returns 404

Am I missing something?

**Comment by ostapio** [comment] 2021-06-01 13:05
@Zeka13 do u have VirtualService created for that gataway/domain? 
mine setup is following

gateway (istio-system ns)
envoy-filter (istio-system ns)
vservice (default ns) (points to same gateway/domain and forwards traffic to demo with / prefix)
demo depployment (default ns)

**Comment by Zeka13** [comment] 2021-06-02 12:41
IMHAO this is too much for this purpose, anyway thx!

**Comment by p53** [comment] 2021-11-02 09:54
any work on this?

**Comment by jiangshantao-dbg** [comment] 2021-12-09 10:08
any work on this? i think this is an important feature, many cases will use this feature. 
1. gateway temporarily forbidden a route of the host
2. service forbidden some route according to deployment environment
etc...
 
envoy has implement three type of route, istio just support two of them. and it's difficult to use envoyfilter to implement and maintain the config in gateway situation, because http and https has different virtualhost name,  the automate program must generated the name according to gateway config.
 
```
oneof action {
    option (validate.required) = true;

    // Route request to some upstream cluster.
    RouteAction route = 2;

    // Return a redirect.
    RedirectAction redirect = 3;

    // Return an arbitrary HTTP response directly, without proxying.
    DirectResponseAction direct_response = 7;

    // [#not-implemented-hide:]
    // If true, a filter will define the action (e.g., it could dynamically generate the
    // RouteAction).
    FilterAction filter_action = 17;
  }
```

**Comment by vvatlin** [comment] 2022-02-23 15:00
+1

**Comment by zirain** [comment] 2022-02-24 01:06
not stale

**Comment by rverma-nsl** [comment] 2022-06-07 14:25
@robw-ca Thanks for the config. I wonder if we can apply this to the SIDECAR_OUTBOUND context in place of the INBOUND. I can observe that when using the inbound context the envoy filter will be processed on the proxy sidecar of the target service. However, I am trying to push this to the caller service's envoy sidecar to avoid the extra hop. Is that even possible?

**Comment by Complyadvantage-user** [comment] 2022-06-07 15:21
> @robw-ca Thanks for the config. I wonder if we can apply this to the SIDECAR_OUTBOUND context in place of the INBOUND. I can observe that when using the inbound context the envoy filter will be processed on the proxy sidecar of the target service. However, I am trying to push this to the caller service's envoy sidecar to avoid the extra hop. Is that even possible?

I don't see why it couldn't work, but you'll probably need to match a different vhost. If you dump the outbound sidecar via https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--config_dump?include_eds you should be able to search the (Admittedly long) JSON for the relevant settings. Do post back your findings!

**Comment by robw-ca** [comment] 2022-06-07 15:22
> @robw-ca Thanks for the config. I wonder if we can apply this to the SIDECAR_OUTBOUND context in place of the INBOUND. I can observe that when using the inbound context the envoy filter will be processed on the proxy sidecar of the target service. However, I am trying to push this to the caller service's envoy sidecar to avoid the extra hop. Is that even possible?

I don't see why it couldn't work, but you'll probably need to match a different vhost. If you dump the outbound sidecar via https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--config_dump?include_eds you should be able to search the (Admittedly long) JSON for the relevant settings. Do post back your findings!

**Closed** 2022-07-07 22:33 UTC
Labels: kind/enhancement, area/networking, area/extensions and telemetry
