### ISSUE TITLE
Helm installation ends with error

### ISSUE THREAD

**Issue by marcin-kasinski** [istio/istio#10588] opened 2018-12-19 21:18 UTC
**Describe the bug**
{{ Succinctly describe the bug }}

Im trying to install istio (current versio 1.0.5)  on fresh kubernetes installation.

curl -L https://git.io/getLatestIstio | sh -
ISTIO_VERSION=$(ls | grep istio- )
cd $ISTIO_VERSION
helm install install/kubernetes/helm/istio --name istio --namespace istio-system 

Im gettin g error:

Error: release istio failed: customresourcedefinitions.apiextensions.k8s.io "noops.config.istio.io" already exists

I've tested it many times on fresh Kubernetes.

If I run : kubectl apply -f install/kubernetes/istio-demo.yaml it works fine.

I have problem with helm only.

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

root@k8smaster:~/istio-1.0.5# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
{{ Please describe how Istio was installed }}

**Environment**

It's kubernetes on 4 bare metal nodes

**Comment by irisdingbj** [comment] 2018-12-20 05:59
Please try to  clean up the environment before hand:
kubectl delete -f install/kubernetes/helm/istio/templates/crds.yaml

then helm install install/kubernetes/helm/istio --name istio --namespace istio-system
It should succeed.

**Comment by marcin-kasinski** [comment] 2018-12-20 06:21
There is nothing to clean up.
Like I said it is first installation on istio always.
I know that this problex exists if I try to install istio with help another thime, but this is always first installation.

I tried your commands without succeed.

It ends with error
`Error: release istio failed: customresourcedefinitions.apiextensions.k8s.io "checknothings.config.istio.io" already exists
`

Another thind I havent mentioned: 
Everytime it complains about different customresourcedefinitions.

**Comment by oaudry** [comment] 2018-12-20 10:01
hello

I can confirm. I got the same error on minikube.

```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
$minikube version
minikube version: v0.31.0
```

```
$helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

```
$curl -L https://git.io/getLatestIstio | sh -
$cd ~/istio*
$sudo mv bin/istioctl /usr/local/bin
$helm install install/kubernetes/helm/istio --name istio --namespace istio-system
Error: customresourcedefinitions.apiextensions.k8s.io "gateways.networking.istio.io" already exists
```

**Comment by jstol** [comment] 2018-12-20 16:58
I'm also running into this issue with 1.0.4 and 1.0.5, but with the following CRDs: `adapters.config.istio.io`, `apikeys.config.istio.io`, `attributemanifests.config.istio.io`, `authorizations.config.istio.io`, `bypasses.config.istio.io`, `gateways.networking.istio.io`. Tried deleting with `kubectl delete -f install/kubernetes/helm/istio/templates/crds.yaml`, but that didn't seem to solve the issue. Using Helm `v2.11.0`.

**Comment by isnellfeikema-isp** [comment] 2018-12-20 23:30
There is a helm bug. Upgrading to helm/tiller v2.12.1 and installing worked for me. You may have to delete/purge your existing Istio install as well.

**Comment by marcin-kasinski** [comment] 2018-12-21 06:07
We are not talking about delete/purge Istio.
We are talking about creating Istio with helm in fresh kubernetes installation.

Everytime i try to install with helm I get error.
Everythime this error refers to different customresourcedefinitions.

I'm pretty sure it worked week or two ago.

**Comment by nalbam** [comment] 2018-12-23 05:01
Same error to me...

```
$ helm upgrade --install istio ./kops-cui/build/istio/istio-1.0.5/install/kubernetes/helm/istio --namespace istio-system --values ./kops-cui/build/kops-cui-istio-istio.yaml
Release "istio" does not exist. Installing it now.
Error: release istio failed: customresourcedefinitions.apiextensions.k8s.io "redisquotas.config.istio.io" already exists
```
```
$ kops version
Version 1.10.0 (git-8b52ea6d1)
```
```
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```
```
$ kubectl get no
NAME                                             STATUS   ROLES    AGE   VERSION
ip-10-0-37-69.ap-northeast-2.compute.internal    Ready    node     29m   v1.10.11
ip-10-0-60-78.ap-northeast-2.compute.internal    Ready    master   31m   v1.10.11
ip-10-0-87-240.ap-northeast-2.compute.internal   Ready    node     29m   v1.10.11
```

**Comment by snguyen-ith** [comment] 2019-01-02 21:45
I can install 1.0.4 just fine, but it looks like the 1.0.5 release is giving problems with the CRDS when installing via the helm chart

**Comment by mkinoshi** [comment] 2019-01-04 20:35
It' still happening on helm `1.12.1`. Cleaned up the environment and purge deleted istio, but no luck.

**Comment by isnellfeikema-isp** [comment] 2019-01-04 22:02
@mkinoshi: You may need to delete the CRD definitions manually.

**Comment by wutianya** [comment] 2019-01-22 09:39
I also encountered the same problem, helm version v2.12.0 
Error: release istio failed: customresourcedefinitions.apiextensions.k8s.io "rbacconfigs.rbac.istio.io" already exists
The solution is to use helm version v2.10.0

**Comment by kish3007** [comment] 2019-02-13 17:23
any update on this issue?

**Comment by isnellfeikema-isp** [comment] 2019-02-13 22:49
@marcin-kasinski: I also hit the issue with Helm v2.12.0 on a pristine, 100% fresh cluster. Helm v2.12.1 works on a completely fresh cluster, but if you've already attempted to install Istio with Helm v2.12.0 you will have to manually delete the CRDs.

**Comment by kish3007** [comment] 2019-02-14 15:27
This issue doesn't exist/fixed in 2.12.2  version.

**Comment by marcin-kasinski** [comment] 2019-02-15 08:43
I can confirm. 
It works with newest version.

**Closed** 2019-02-15 08:42 UTC

**Comment by chris-hamper** [comment] 2019-02-24 13:22
I ran into this issue as well while running through the quick-start walkthrough at https://istio.io/docs/setup/kubernetes/quick-start/ with a "side-quest" at https://istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install

It looks like this was a result of outdated/confusing documentation. If you read the instructions carefully on the "Installation with Helm" page, you can see that the command: 
```
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
```
should only be run if you're using **Helm versions 2.10.0 or earlier**. The same line on the quick-start page **does not** specify this, so I had already run it before attempting the helm install. The fix was to delete the CRDs created earlier by (carefully) running:
```
kubectl delete crd --namespace istio-system --all
```
and then continuing with the Helm install.
