### ISSUE TITLE
Operator controller pod ignores delete/create cycle of iop

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#22325] opened 2020-03-19 19:46 UTC
**Bug description**

The following install/uninstall cycle is not working for us with 1.5.0

- Operator pod is deployed and  running 
- apply iop
- control plane resources created
- delete iop
- control plane resources removed
- apply iop (exact same one as above)
- nothing  happens in the cluster!
   -  see this in the logs `Generated manifest objects are the same as cached for component ...`

- If I restart the operator pod, then the control plane is created, that should not be necessary, any cache should be removed when the iop is deleted.

[operator.log.txt](https://github.com/istio/istio/files/4356616/operator.log.txt)

**Expected behavior**

Should be able to cycle install (create iop) and uninstall (delete iop) and see the control plane resources come and go.

**Steps to reproduce the bug**

above

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5.0

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by kramvan1** [comment] 2020-03-19 19:47
cc @sdake @linsun @howardjohn

**Comment by sdake** [comment] 2020-03-19 20:54
@dgn @ostromart I believe one of you was responsible for the implementation of the caching layer. I'd really really like to bundle this in the 1.5.1 release. Anything you can do to fix this on your own or provide pointers for me to fix myself would be appreciated.

It sort of appears like the caching is not flushed on a removal of an IOP.

**Comment by sdake** [comment] 2020-03-19 23:49
@kramvan1 this was fixed in https://github.com/istio/istio/pull/21847. It appears while this PR merged prior to release 1.5 (march 5th), the PR itself didn't make it into the final build. I have tested 1.5.0 (broken), 1.5-dev (works correctly), master (works correctly).

This also appears to be a duplicate of https://github.com/istio/istio/issues/21467

If you feel this issue was closed in error, please feel free to reopen.

**Closed by sdake** 2020-03-19 23:49 UTC
Labels: area/environments, area/environments/operator

**Comment by kramvan1** [comment] 2020-03-20 15:29
fixed, thx!
