### ISSUE TITLE
Galley validation allows unknown fields, but rejects them internally

### ISSUE THREAD

**Issue by sushicw** [istio/istio#15012] opened 2019-06-20 00:02 UTC
**Bug description**

Adding invalid entries to match rules, or simply misspelling a valid one, fails silently instead of triggering the webhook validation. The impact is that although you think your config was successfully applied, it was not, and you don't know something's wrong until your stuff doesn't work and/or you dig in the logs. 

e.g. if your match YAML uses "sourcelabels" instead of "sourceLabels", you may not realize why the config isn't working when it appeared to apply successfully.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

The expected behavior is that bogus "match" entries should trigger a webhook validation failure, like bogus entries elsewhere in the YAML do. (See below). 

**Steps to reproduce the bug**

**temp3a.yaml** (all valid):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - match:
    - sourceLabels:
        app: productpage
        version: v2
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v2
```
Works as expected:
```console
crwilson@crwilson:~/go/src/istio.io/istio$ kubectl apply -f /tmp/temp3a.yaml 
virtualservice.networking.istio.io/reviews configured
```

**temp3b.yaml** (bogus entry under http):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - BOGUS: true
  - match:
    - sourceLabels:
        app: productpage
        version: v2
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v2
```
Fails on apply, as expected, thanks to webhook:
```console
crwilson@crwilson:~/go/src/istio.io/istio$ kubectl apply -f /tmp/temp3b.yaml 
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"reviews\",\"namespace\":\"default\"},\"spec\":{\"hosts\":[\"reviews\"],\"http\":[{\"BOGUS\":true},{\"match\":[{\"sourceLabels\":{\"app\":\"productpage\",\"version\":\"v2\"}}],\"route\":[{\"destination\":{\"host\":\"reviews\",\"subset\":\"v3\"}}]},{\"route\":[{\"destination\":{\"host\":\"reviews\",\"subset\":\"v2\"}}]}]}}\n"}},"spec":{"http":[{"BOGUS":true},{"match":[{"sourceLabels":{"app":"productpage","version":"v2"}}],"route":[{"destination":{"host":"reviews","subset":"v3"}}]},{"route":[{"destination":{"host":"reviews","subset":"v2"}}]}]}}
to:
Resource: "networking.istio.io/v1alpha3, Resource=virtualservices", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=VirtualService"
Name: "reviews", Namespace: "default"
Object: &{map["apiVersion":"networking.istio.io/v1alpha3" "kind":"VirtualService" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"reviews\",\"namespace\":\"default\"},\"spec\":{\"hosts\":[\"reviews\"],\"http\":[{\"match\":[{\"sourceLabels\":{\"app\":\"productpage\",\"version\":\"v2\"}}],\"route\":[{\"destination\":{\"host\":\"reviews\",\"subset\":\"v3\"}}]},{\"route\":[{\"destination\":{\"host\":\"reviews\",\"subset\":\"v2\"}}]}]}}\n"] "creationTimestamp":"2019-06-19T18:20:36Z" "generation":'\x1f' "name":"reviews" "namespace":"default" "resourceVersion":"73032" "selfLink":"/apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices/reviews" "uid":"eeddc3b7-92be-11e9-ad0c-42010a8a0151"] "spec":map["hosts":["reviews"] "http":[map["match":[map["sourceLabels":map["app":"productpage" "version":"v2"]]] "route":[map["destination":map["host":"reviews" "subset":"v3"]]]] map["route":[map["destination":map["host":"reviews" "subset":"v2"]]]]]]]}
for: "/tmp/temp3b.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: HTTP route or redirect is required

```

**temp3c.yaml** (Bogus entry under match):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - match:
    - sourceLabels:
        app: productpage
        version: v2
    BOGUS: true
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v2
```
Does NOT fail as expected in kubectl:
```console
crwilson@crwilson:~/go/src/istio.io/istio$ kubectl apply -f /tmp/temp3c.yaml 
virtualservice.networking.istio.io/reviews configured
```
Although it does fail silently, as reflected in the galley logs:
```
{
 insertId:  "963fktg161paig"  
 labels: {…}  
 logName:  "projects/google.com:crwilson-gcp-experimental/logs/galley"  
 receiveTimestamp:  "2019-06-19T23:51:56.482640880Z"  
 resource: {…}  
 severity:  "INFO"  
 textPayload:  "2019-06-19T23:51:50.904031Z	error	kube	Unable to convert unstructured to proto: default/reviews/74364: unknown field "BOGUS" in v1alpha3.HTTPRoute
"  
 timestamp:  "2019-06-19T23:51:50.904243694Z"  
}
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Built on tip of master (0d210f251ece736b2d97747e2244c27517257355)

```console
crwilson@crwilson:~/go/src/istio.io/istio$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.6", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-05-23T11:42:40Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
crwilson@crwilson:~/go/src/istio.io/istio$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
citadel version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
egressgateway version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
galley version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
ingressgateway version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
pilot version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
pilot version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
pilot version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
policy version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
sidecar-injector version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
telemetry version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
```

**How was Istio installed?**
Built locally & installed to test env

**Environment where bug was observed (cloud vendor, OS, etc)**
BookInfo demo app on GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment] 2019-06-20 00:43
I think this is working as intended based on https://github.com/istio/istio/issues/14533#issuecomment-500622559

**Comment by linsun** [comment] 2019-06-20 13:41
I personally prefer fail or at the minimum give a warning out in this case if we are loosing up validation because of upgrade ad our CRDs are still under renovation.  Else, we'd keep getting issues like this.

cc @ozevren @geeknoid

**Comment by esnible** [comment] 2019-06-21 14:15
@howardjohn I was allowed to add validation of top-level keys ( https://github.com/istio/istio/pull/11791   This patch caught invalid YAML in our own _samples_).  I can understand why we might allow formerly-valid YAML, but there is no use case for a MatchCondition of `BOGUS: true`!

**Comment by esnible** [comment] 2019-06-21 16:17
As an experiment I added validation of unexpected keys to `istioctl validate` and ran validation over Istio 1.2 _samples_.  I found three weird things:

```
samples/bookinfo/platform/kube/rbac/rbac-config-on-permissive.yaml
	ClusterRbacConfig//default: unknown field "enforcement_mode"

samples/external/github.yaml
	* ServiceEntry//github-tcp: unknown field "location"

samples/httpbin/httpbin-gateway.yaml
	* VirtualService//httpbin: zero-length "http/match"
```

The Istio team can't get our own hand-inspected official samples correct.  Let's help users by doing deep validation in `istioctl validate` and the validation web hook.

@frankbu Let's update the samples
@howardjohn Are the incorrect fields in the samples older, deprecated fields or simple errors?

**Comment by howardjohn** [comment] 2019-06-21 16:27
Running istioctl validate on our samples in presubmit seems like a good idea.

Warning for unknown fields in istioctl validate (as it does today) is a good idea.

Kubernetes does reject unknown fields (example: `error validating data: ValidationError(Service.spec): unknown field "foo" in io.k8s.api.core.v1.ServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false`).

We have two identical issues with split conversations, so I am going to close https://github.com/istio/istio/issues/14533 and we can continue

@ozevren can you explain the versioning problem? Is the issue that our CRDs are not actually static, so we could add a field to them without changing the version, which would get rejected if you had an older Galley? Whereas kubernetes doesn't have that issue as there CRDs are fully static?

**Comment by howardjohn** [comment] 2019-06-21 16:35
@esnible 
```
samples/external/github.yaml
	* ServiceEntry//github-tcp: unknown field "location"
```

This field should exist: https://github.com/istio/istio/blob/cc0f7ada51435945559104eda0871aefad956541/vendor/istio.io/api/networking/v1alpha3/service_entry.proto#L391

**Comment by esnible** [comment] 2019-06-21 17:45
@howardjohn My quick-and-dirty unknown field checker was incorrect for enums holding default values; ignore my comment about location.

Proposal: Both the validation webhook and `istioctl validate` should be attempting to call ConvertAndLog() to prevent entries from being admitted that will fail later.

**Comment by sushicw** [comment] 2019-07-02 17:02
@esnible Would you mind posting your quick&dirty validation code? Even if it's not the solution we want, I at least would find it educational. 

Your proposal makes sense to me: if we can do a "dry run" in validation of the same code that will actually try to execute later, we should be able to catch a lot of things. Either way, it's failing, but it's better to fail sooner and more obviously.

**Comment by sushicw** [comment] 2019-07-02 18:38
After talking with @ozevren it sounds like we actually want to keep the non-strict validation for now. Eventually we want to be able to validate the schema, but in the meantime, we shouldn't fail on extra / unexpected fields. So the first immediate tactical move is to make it so that when Galley is trying to convert the unstructured proto, we ignore extra fields instead of failing on them.

**Comment by sushicw** [comment] 2019-07-02 22:15
https://github.com/istio/istio/pull/15307 to do the above and make the conversion nonstrict.

**Comment by howardjohn** [comment] 2019-07-10 15:11
fixed by 15307?

**Closed** 2019-07-10 20:29 UTC
Labels: area/config, area/user experience
