### ISSUE TITLE
Mesh internal calls break with TPROXY mode

### ISSUE THREAD

**Issue by yannuil** [istio/istio#27565] opened 2020-09-27 13:28 UTC
**Bug description**
Under a default profile setup,  the sample `sleep` can call sample `httpbin` but get the error message below for `httpbin-tproxy` , a `httpbin` with `sidecar.istio.io/interceptionMode: TPROXY` annotation added. The full yaml is given under **Steps to reproduce the bug** section.
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
`sleep` should get the same result for calling `httpbin-tproxy` as `httpbin`.

**Steps to reproduce the bug**
I run the steps below in a single node Linode kubernetes cluster.

1. Deploy the istio operator with `istioctl operator init`
2. `kubectl apply -f istio.yaml` The content of `istio.yaml` is shown below.
```yaml
apiVersion: install.istio.io/v1alpha1
metadata:
  namespace: istio-system
  name: istio-control-plane
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  profile: default
```
3. `kubectl label namespace default istio-injection=enabled`
4. `kubectl apply -f sleep.yaml` The sample [sleep.yaml](https://github.com/istio/istio/blob/1.6.10/samples/sleep/sleep.yaml) from is used.
5. `kubectl apply -f httpbin.yaml` The sample [httpbin.yaml](https://github.com/istio/istio/blob/1.6.10/samples/httpbin/httpbin.yaml)` is used.
6. `kubectl apply -f httpbin-tproxy.yaml` The content of `httpbin-tproxy.yaml` is shown below.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-tproxy
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-tproxy
  labels:
    app: httpbin-tproxy
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin-tproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-tproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-tproxy
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/interceptionMode: TPROXY
      labels:
        app: httpbin-tproxy
        version: v1
    spec:
      serviceAccountName: httpbin-tproxy
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80

```
7. Run `kubectl exec -it $(kubectl get pods -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl httpbin.default:8000/ip` It returns the expected result.
```json
{
  "origin": "127.0.0.1"
}
```
8. Run `kubectl exec -it $(kubectl get pods -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl httpbin-tproxy.default:8000/ip` It returns the error message below.
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Istio version
```
client version: 1.6.10
control plane version: 1.6.10
data plane version: 1.6.10 (5 proxies)
```
Kubernetes version
```
Client Version: v1.19.2
Server Version: v1.18.8
```

**How was Istio installed?**
Installed with the istio operator.

**Environment where bug was observed (cloud vendor, OS, etc)**
Linode Kubernetes Engine

The dump file [`istio-dump.tar.gz`](https://github.com/istio/istio/files/5288336/istio-dump.tar.gz) was created with `./dump_kubernetes.sh -n default -n istio-system -n istio-operator -z`

**Comment by yannuil** [comment] 2020-09-27 13:48
I have reproduced this under istio version 1.7.2 as well.

From the `httpbin-tproxy` access log, it shows a `PassthroughCluster` rather than an `inbound|8000|http|httpbin.default.svc.cluster.local` entry.
```
[2020-09-27T13:41:53.185Z] "- - -" 0 UF,URX "-" "-" 0 0 10016 - "-" "-" "-" "-" "10.2.0.34:80" PassthroughCluster - 10.2.0.34:80 10.2.0.32:40786 - -
```
This is the access log entry from `httpbin`.
```
2020-09-27T13:42:33.850Z] "GET /ip HTTP/1.1" 200 - "-" "-" 0 28 7 6 "-" "curl/7.69.1" "fa5e5c56-5ec3-4b84-975a-36d570dd5e0b" "httpbin.default:8000" "127.0.0.1:80" inbound|8000|http|httpbin.default.svc.cluster.local 127.0.0.1:53950 10.2.0.33:80 10.2.0.32:56444 outbound_.8000_._.httpbin.default.svc.cluster.local default
```

**Comment by howardjohn** [comment] 2020-10-22 19:35
Liekly the same as https://github.com/istio/istio/issues/26569

**Comment by hzxuzhonghu** [comment] 2020-10-23 17:34
same  with  1.7.3

**Comment by hzxuzhonghu** [comment] 2020-10-23 17:35
The traffic dead loop

**Comment by howardjohn** [comment] 2020-11-19 22:11
This is fixed in https://github.com/istio/istio/pull/28457. Since this is tracked in a few places, lets consolidate on https://github.com/istio/istio/issues/5679. Thanks!

**Closed by howardjohn** 2020-11-19 22:11 UTC
Labels: area/networking

**Comment by ramaraochavali** [comment] 2021-01-20 13:55
It looks like outbound calls when the interception mode is set to TPROXY are failing with connection failures.  

I am wondering if it is because of setting transparent on virtual outbound listener https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener_builder.go#L336? Is the interception mode is supposed to work for inbound only https://github.com/istio/api/blob/master/annotation/annotations.yaml#L160?  As per doc it seems so.  If it is so, why are we setting transparent to true for virtual outbound listener? I am not sure if that is problem but want to check. @lambdai  @rlenglet Any idea on this?
cc: @hzxuzhonghu @howardjohn

**Comment by howardjohn** [comment] 2021-01-20 15:12
@ramaraochavali its still not working with https://github.com/istio/istio/pull/28457?

**Comment by ramaraochavali** [comment] 2021-01-20 15:31
@howardjohn  Inbound calls including original src are working.  But outbound calls specially TCP are failing with upstream_cx_connect_fail in the target cluster . gRPC/Http seem to be working (not able to figure out why though). 

I could not find any difference in the config generated other than the transparent set on virtual outbound listener. In both REDIRECT/TPROXY cases the correct target envoy cluster is picked so I am assuming there is no issue with IP Table rules. But in TPROXY mode, call from envoy cluster -> destination fails with upstream_cx_connect_fail
7:44
in REDIRECT mode same cluster call works





7:45
wondering it is because of transparent = true in virtual outbound listener - i could not find any other difference in config other than this

**Comment by lambdai** [comment] 2021-01-20 18:09
@ramaraochavali I doubt if `traffic.sidecar.istio.io/includeOutboundPorts:8485` is the trouble. Setting specific outbound port is a rare case. I don't even remember a single scenario. Is there an iptables dump at your side?

**Comment by ramaraochavali** [comment] 2021-01-21 04:20
Yes. I was also douting that. I tested with another app that runs on port 7443 but does not have this added and it seems to work there. Here is the ip table dump. Any suggestions on how to fix  this?
```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=TPROXY
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=127.1.2.3/32
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=50010,50020,50075,50070,50090,9000,8019,8480,8481,8485,2181
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

ip -f inet rule add fwmark 1337 lookup 133
ip -f inet route add local default dev lo table 133
Writing following contents to rules file:  /tmp/iptables-rules-1611150449926010472.txt021495827
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -p tcp --dport 50010 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 50020 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 50075 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 50070 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 50090 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 9000 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 8019 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 8480 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 8481 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 8485 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp --dport 2181 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -d 127.1.2.3/32 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -j RETURN
COMMIT
* mangle
-N ISTIO_DIVERT
-N ISTIO_TPROXY
-N ISTIO_INBOUND
-A ISTIO_DIVERT -j MARK --set-mark 1337
-A ISTIO_DIVERT -j ACCEPT
-A ISTIO_TPROXY ! -d 127.0.0.1/32 -p tcp -j TPROXY --tproxy-mark 1337/0xffffffff --on-port 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j ISTIO_DIVERT
-A ISTIO_INBOUND -p tcp -j ISTIO_TPROXY
-A PREROUTING -p tcp -m mark --mark 1337 -j CONNMARK --save-mark
-A OUTPUT -p tcp -m connmark --mark 1337 -j CONNMARK --restore-mark
-I ISTIO_INBOUND 1 -p tcp -m mark --mark 1337 -j RETURN
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1611150449926010472.txt021495827
Writing following contents to rules file:  /tmp/ip6tables-rules-1611150450616768940.txt191332950

ip6tables-restore --noflush /tmp/ip6tables-rules-1611150450616768940.txt191332950
iptables-save 
# Generated by iptables-save v1.4.21 on Wed Jan 20 13:47:30 2021
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_DIVERT - [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_TPROXY - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A PREROUTING -p tcp -m mark --mark 0x539 -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -p tcp -m connmark --mark 0x539 -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A ISTIO_DIVERT -j MARK --set-xmark 0x539/0xffffffff
-A ISTIO_DIVERT -j ACCEPT
-A ISTIO_INBOUND -p tcp -m mark --mark 0x539 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j ISTIO_DIVERT
-A ISTIO_INBOUND -p tcp -j ISTIO_TPROXY
-A ISTIO_TPROXY ! -d 127.0.0.1/32 -p tcp -j TPROXY --on-port 15006 --on-ip 0.0.0.0 --tproxy-mark 0x539/0xffffffff
COMMIT
# Completed on Wed Jan 20 13:47:30 2021
# Generated by iptables-save v1.4.21 on Wed Jan 20 13:47:30 2021
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -p tcp -m tcp --dport 50010 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 50020 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 50075 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 50070 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 50090 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 9000 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 8019 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 8480 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 8481 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 8485 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -p tcp -m tcp --dport 2181 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -d 127.1.2.3/32 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Wed Jan 20 13:47:30 2021
```

**Comment by ramaraochavali** [comment] 2021-01-21 10:08
@lambdai 
`traffic.sidecar.istio.io/includeOutboundPorts` is working with REDIRECT. Only with `TPROXY` the outbound traffic is failing. Attached is both the IP table scripts. Not able to figure out if it is because of iptable difference or because of transparent flag set on virtual outbound listener (not able to verify because I am not able to change it via Envoy filter as it is proto Boolean and we set it to true). 
[init_log_redirect.txt](https://github.com/istio/istio/files/5848459/init_log_redirect.txt)
[init_log_tproxy.txt](https://github.com/istio/istio/files/5848461/init_log_tproxy.txt)

**Comment by ramaraochavali** [comment] 2021-01-22 07:07
@lambdai Confirmed that it is problem with `traffic.sidecar.istio.io/includeOutboundPorts` in `TPROXY` mode. I have added `7443` which was working earlier to this and traffic to that port results in the same behaviour i.e. it gets upstream_cx_connect_fail and upstream_cx_connect_timeout.
What could be the difference for it in TPROXY mode?

**Comment by hzxuzhonghu** [comment] 2021-01-25 03:47
I have tested with community provided sleep application, when i enable the `TPROXY` on it, nothing exception happens. I can access  services no matter mesh internal or external successfully.
```
# 
# iptables-save
iptables-save v1.6.1: Cannot initialize: Permission denied (you must be root)

# 
command terminated with exit code 1
root@opensrc:~# k logs sleep-66d849f7cc-7xcg5 -c istio-init
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=TPROXY
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

ip -f inet rule add fwmark 1337 lookup 133
ip -f inet route add local default dev lo table 133
Writing following contents to rules file:  /tmp/iptables-rules-1611545995238845650.txt973968718
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
* mangle
-N ISTIO_DIVERT
-N ISTIO_TPROXY
-N ISTIO_INBOUND
-A ISTIO_DIVERT -j MARK --set-mark 1337
-A ISTIO_DIVERT -j ACCEPT
-A ISTIO_TPROXY ! -d 127.0.0.1/32 -p tcp -j TPROXY --tproxy-mark 1337/0xffffffff --on-port 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j ISTIO_DIVERT
-A ISTIO_INBOUND -p tcp -j ISTIO_TPROXY
-A PREROUTING -p tcp -m mark --mark 1337 -j CONNMARK --save-mark
-A OUTPUT -p tcp -m connmark --mark 1337 -j CONNMARK --restore-mark
-I ISTIO_INBOUND 1 -p tcp -m mark --mark 1337 -j RETURN
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1611545995238845650.txt973968718
Writing following contents to rules file:  /tmp/ip6tables-rules-1611545995281567654.txt593316437

ip6tables-restore --noflush /tmp/ip6tables-rules-1611545995281567654.txt593316437
iptables-save 
# Generated by iptables-save v1.6.1 on Mon Jan 25 03:39:55 2021
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Mon Jan 25 03:39:55 2021
# Generated by iptables-save v1.6.1 on Mon Jan 25 03:39:55 2021
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Mon Jan 25 03:39:55 2021
# Generated by iptables-save v1.6.1 on Mon Jan 25 03:39:55 2021
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_DIVERT - [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_TPROXY - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A PREROUTING -p tcp -m mark --mark 0x539 -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -p tcp -m connmark --mark 0x539 -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A ISTIO_DIVERT -j MARK --set-xmark 0x539/0xffffffff
-A ISTIO_DIVERT -j ACCEPT
-A ISTIO_INBOUND -p tcp -m mark --mark 0x539 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j ISTIO_DIVERT
-A ISTIO_INBOUND -p tcp -j ISTIO_TPROXY
-A ISTIO_TPROXY ! -d 127.0.0.1/32 -p tcp -j TPROXY --on-port 15006 --on-ip 0.0.0.0 --tproxy-mark 0x539/0xffffffff
COMMIT
# Completed on Mon Jan 25 03:39:55 2021

```

**Comment by ramaraochavali** [comment] 2021-01-25 04:05
The error only happens if `includeOutboundPorts` is used otherwise it works fine. Also looks like there is some discrepancy in the way `runAsGroup` is set probably because of the way we are patching security context as described here https://github.com/istio/istio/pull/30306#issuecomment-766310964

If you still have the pod running, can you share the securityContext of the pod with TPROXY?

**Comment by hzxuzhonghu** [comment] 2021-01-25 07:01
securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: false
      runAsUser: 0

**Comment by ramaraochavali** [comment] 2021-01-25 07:03
Ok. It makes sense. `runAsGroup` 1337 will help. Will figure out why it is not coming for us

**Comment by hzxuzhonghu** [comment] 2021-01-25 07:09
can you run this in the server proxy `cat  /proc/sys/net/ipv4/conf/eth0/route_localnet`

**Comment by OnlyPiglet** [comment] 2023-06-28 07:40
same on 1.17.2 sad
