### ISSUE TITLE
Failing test: TestGolden.Bootstrap-tracing_datadog

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13095] opened 2019-04-05 16:18 UTC
https://prow.k8s.io/view/gcs/istio-prow/logs/istio-postsubmit/4898
The tests seems to be failing consistently. It seems to be in 1.1 branch.

/cc @duderino 
This seems to be where it is introduced: https://github.com/istio/istio/pull/12687

```
--- FAIL: TestGolden/Bootstrap-tracing_datadog (0.01s)
bootstrap_config_test.go:165: difference: modified: .StaticResources.Clusters[1].DnsLookupFamily = 0
bootstrap_config_test.go:166:
got: {id:"sidecar~1.2.3.4~foo~bar" cluster:"istio-proxy" metadata:<fields:<key:"ISTIO_META_INSTANCE_IPS" value:<string_value:"10.3.3.3,10.4.4.4,10.5.5.5,10.6.6.6" > > fields:<key:"istio" value:<string_value:"sidecar" > > > locality:<> listeners:<address:<socket_address:<address:"0.0.0.0" port_value:15090 > > filter_chains:<filters:<name:"envoy.http_connection_manager" config:<fields:<key:"codec_type" value:<string_value:"AUTO" > > fields:<key:"http_filters" value:<struct_value:<fields:<key:"name" value:<string_value:"envoy.router" > > > > > fields:<key:"route_config" value:<struct_value:<fields:<key:"virtual_hosts" value:<list_value:<values:<struct_value:<fields:<key:"domains" value:<list_value:<values:<string_value:"*" > > > > fields:<key:"name" value:<string_value:"backend" > > fields:<key:"routes" value:<list_value:<values:<struct_value:<fields:<key:"match" value:<struct_value:<fields:<key:"prefix" value:<string_value:"/stats/prometheus" > > > > > fields:<key:"route" value:<struct_value:<fields:<key:"cluster" value:<string_value:"prometheus_stats" > > > > > > > > > > > > > > > > > > fields:<key:"stat_prefix" value:<string_value:"stats" > > > > > > clusters:<name:"prometheus_stats" type:STATIC connect_timeout:<nanos:250000000 > hosts:<socket_address:<address:"127.0.0.1" port_value:15000 > > > clusters:<name:"xds-grpc" type:STRICT_DNS connect_timeout:<seconds:1 > hosts:<socket_address:<address:"istio-pilot" port_value:15010 > > circuit_breakers:<thresholds:<max_connections:<value:100000 > max_pending_requests:<value:100000 > max_requests:<value:100000 > > thresholds:<priority:HIGH max_connections:<value:100000 > max_pending_requests:<value:100000 > max_requests:<value:100000 > > > http2_protocol_options:<> dns_lookup_family:V4_ONLY upstream_connection_options:<tcp_keepalive:<keepalive_time:<value:300 > > > > clusters:<name:"datadog_agent" type:STRICT_DNS connect_timeout:<seconds:1 > hosts:<socket_address:<address:"localhost" port_value:8126 > > > lds_config:<ads:<> > cds_config:<ads:<> > ads_config:<api_type:GRPC grpc_services:<envoy_grpc:<cluster_name:"xds-grpc" > > > <nil> <nil> [] stats_tags:<tag_name:"cluster_name" regex:"^cluster\\.((.+?(\\..+?\\.svc\\.cluster\\.local)?)\\.)" > stats_tags:<tag_name:"tcp_prefix" regex:"^tcp\\.((.*?)\\.)\\w+?$" > stats_tags:<tag_name:"response_code" regex:"_rq(_(\\d{3}))$" > stats_tags:<tag_name:"response_code_class" regex:"_rq(_(\\dxx))$" > stats_tags:<tag_name:"http_conn_manager_listener_prefix" regex:"^listener(?=\\.).*?\\.http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)" > stats_tags:<tag_name:"http_conn_manager_prefix" regex:"^http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)" > stats_tags:<tag_name:"listener_address" regex:"^listener\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)" > stats_tags:<tag_name:"mongo_prefix" regex:"^mongo\\.(.+?)\\.(collection|cmd|cx_|op_|delays_|decoding_)(.*?)$" > use_all_default_tags:<> stats_matcher:<inclusion_list:<patterns:<prefix:"cluster_manager" > patterns:<prefix:"listener_manager" > patterns:<prefix:"http_mixer_filter" > patterns:<prefix:"tcp_mixer_filter" > patterns:<prefix:"server" > patterns:<prefix:"cluster.xds-grpc" > > > <nil> <nil> http:<name:"envoy.tracers.datadog" config:<fields:<key:"collector_cluster" value:<string_value:"datadog_agent" > > fields:<key:"service_name" value:<string_value:"istio-proxy" > > > > <nil> <nil> access_log_path:"/dev/null" address:<socket_address:<address:"127.0.0.1" port_value:15000 > > <nil> {} [] 0}
want: {id:"sidecar~1.2.3.4~foo~bar" cluster:"istio-proxy" metadata:<fields:<key:"ISTIO_META_INSTANCE_IPS" value:<string_value:"10.3.3.3,10.4.4.4,10.5.5.5,10.6.6.6" > > fields:<key:"istio" value:<string_value:"sidecar" > > > locality:<> listeners:<address:<socket_address:<address:"0.0.0.0" port_value:15090 > > filter_chains:<filters:<name:"envoy.http_connection_manager" config:<fields:<key:"codec_type" value:<string_value:"AUTO" > > fields:<key:"http_filters" value:<struct_value:<fields:<key:"name" value:<string_value:"envoy.router" > > > > > fields:<key:"route_config" value:<struct_value:<fields:<key:"virtual_hosts" value:<list_value:<values:<struct_value:<fields:<key:"domains" value:<list_value:<values:<string_value:"*" > > > > fields:<key:"name" value:<string_value:"backend" > > fields:<key:"routes" value:<list_value:<values:<struct_value:<fields:<key:"match" value:<struct_value:<fields:<key:"prefix" value:<string_value:"/stats/prometheus" > > > > > fields:<key:"route" value:<struct_value:<fields:<key:"cluster" value:<string_value:"prometheus_stats" > > > > > > > > > > > > > > > > > > fields:<key:"stat_prefix" value:<string_value:"stats" > > > > > > clusters:<name:"prometheus_stats" type:STATIC connect_timeout:<nanos:250000000 > hosts:<socket_address:<address:"127.0.0.1" port_value:15000 > > > clusters:<name:"xds-grpc" type:STRICT_DNS connect_timeout:<seconds:1 > hosts:<socket_address:<address:"istio-pilot" port_value:15010 > > circuit_breakers:<thresholds:<max_connections:<value:100000 > max_pending_requests:<value:100000 > max_requests:<value:100000 > > thresholds:<priority:HIGH max_connections:<value:100000 > max_pending_requests:<value:100000 > max_requests:<value:100000 > > > http2_protocol_options:<> upstream_connection_options:<tcp_keepalive:<keepalive_time:<value:300 > > > > clusters:<name:"datadog_agent" type:STRICT_DNS connect_timeout:<seconds:1 > hosts:<socket_address:<address:"localhost" port_value:8126 > > > lds_config:<ads:<> > cds_config:<ads:<> > ads_config:<api_type:GRPC grpc_services:<envoy_grpc:<cluster_name:"xds-grpc" > > > <nil> <nil> [] stats_tags:<tag_name:"cluster_name" regex:"^cluster\\.((.+?(\\..+?\\.svc\\.cluster\\.local)?)\\.)" > stats_tags:<tag_name:"tcp_prefix" regex:"^tcp\\.((.*?)\\.)\\w+?$" > stats_tags:<tag_name:"response_code" regex:"_rq(_(\\d{3}))$" > stats_tags:<tag_name:"response_code_class" regex:"_rq(_(\\dxx))$" > stats_tags:<tag_name:"http_conn_manager_listener_prefix" regex:"^listener(?=\\.).*?\\.http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)" > stats_tags:<tag_name:"http_conn_manager_prefix" regex:"^http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)" > stats_tags:<tag_name:"listener_address" regex:"^listener\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)" > stats_tags:<tag_name:"mongo_prefix" regex:"^mongo\\.(.+?)\\.(collection|cmd|cx_|op_|delays_|decoding_)(.*?)$" > use_all_default_tags:<> stats_matcher:<inclusion_list:<patterns:<prefix:"cluster_manager" > patterns:<prefix:"listener_manager" > patterns:<prefix:"http_mixer_filter" > patterns:<prefix:"tcp_mixer_filter" > patterns:<prefix:"server" > patterns:<prefix:"cluster.xds-grpc" > > > <nil> <nil> http:<name:"envoy.tracers.datadog" config:<fields:<key:"collector_cluster" value:<string_value:"datadog_agent" > > fields:<key:"service_name" value:<string_value:"istio-proxy" > > > > <nil> <nil> access_log_path:"/dev/null" address:<socket_address:<address:"127.0.0.1" port_value:15000 > > <nil> {} [] 0}
```

**Comment by douglas-reid** [comment] 2019-04-05 16:38
It was passing the unit tests in presubmit... Did it get merged past other changes?

**Comment by douglas-reid** [comment] 2019-04-05 16:40
@cgilmour can you take a look at fixing the golden file?

**Comment by cgilmour** [comment] 2019-04-05 16:58
Already opened #13082 shortly after this was reported in #13078.
It fails to merge automatically because codecov.
codecov is checking the PR coverage vs head of release-1.1, which got into a bad state.

It got into that state because my earlier PR got slightly stale, and newer changes to protos had been applied since it was branched, which affects the goldenfiles.

**Comment by howardjohn** [comment] 2019-04-05 16:58
Dupe of https://github.com/istio/istio/issues/13078

**Closed by howardjohn** 2019-04-05 16:58 UTC
Labels: area/policies and telemetry
