### ISSUE TITLE
kubectl edit mutatingwebhookconfiguration istio-sidecar-injector gets overwritten after short time interval

### ISSUE THREAD

**Issue by Svendegroote91** [istio/istio#19041] opened 2019-11-18 14:37 UTC
**Bug description**
If I change the namespaceSelector in the mutatingwebhookconfiguration via `kubectl editmutatingwebhookconfiguration istio-sidecar-injector`
to 
``` 
 namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: NotIn
      values:
      - disabled
```
I noticed that the mutatingwebhookconfiguration is updated shortly to the desired state I defined above. After just a few seconds, the mutatingwebhookconfiguration gets updated by another mechanism and it defines the following state: 

``` 
namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: NotIn
      values:
      - disabled
    matchLabels:
      istio-injection: enabled 
```

It's not clear to me what I should do differently in order to get the desired state that I claimed at the top (only select namespaces that do not have the disabled label). Can somebody help me point at what I am doing wrong here?

**Expected behavior**
After updating the target state of the namespaceSelector via kubectl edit, it should keep that state.
**Steps to reproduce the bug**
Update namespaceSelector from 
```  
namespaceSelector:
    matchLabels:
      istio-injection: enabled
```
to 
```
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: NotIn
      values:
      - disabled
```

via `kubectl edit mutatingwebhookconfiguration istio-sidecar-injector`.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
istioctl version: 
```
client version: version.BuildInfo{Version:"1.1.13", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765", User:"root", Host:"0f070bc0-b950-11e9-acd3-2edd5d7d4cc8", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.12"}
citadel version: version.BuildInfo{Version:"0f52910f512029f0f8860b4c586cf9667545dd35", GitRevision:"0f52910f512029f0f8860b4c586cf9667545dd35", User:"root", Host:"4d4db80bcdb0", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.16-gke.0"}
galley version: version.BuildInfo{Version:"0f52910f512029f0f8860b4c586cf9667545dd35", GitRevision:"0f52910f512029f0f8860b4c586cf9667545dd35", User:"root", Host:"4d4db80bcdb0", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.16-gke.0"}
ingressgateway version: version.BuildInfo{Version:"0f52910f512029f0f8860b4c586cf9667545dd35", GitRevision:"0f52910f512029f0f8860b4c586cf9667545dd35", User:"root", Host:"4d4db80bcdb0", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.16-gke.0"}
pilot version: version.BuildInfo{Version:"0f52910f512029f0f8860b4c586cf9667545dd35", GitRevision:"0f52910f512029f0f8860b4c586cf9667545dd35", User:"root", Host:"4d4db80bcdb0", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.16-gke.0"}
policy version: version.BuildInfo{Version:"0f52910f512029f0f8860b4c586cf9667545dd35", GitRevision:"0f52910f512029f0f8860b4c586cf9667545dd35", User:"root", Host:"4d4db80bcdb0", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.16-gke.0"}
sidecar-injector version: version.BuildInfo{Version:"0f52910f512029f0f8860b4c586cf9667545dd35", GitRevision:"0f52910f512029f0f8860b4c586cf9667545dd35", User:"root", Host:"4d4db80bcdb0", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.16-gke.0"}
telemetry version: version.BuildInfo{Version:"0f52910f512029f0f8860b4c586cf9667545dd35", GitRevision:"0f52910f512029f0f8860b4c586cf9667545dd35", User:"root", Host:"4d4db80bcdb0", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.16-gke.0"}
```
**How was Istio installed?**
As a GKE add-on.

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Cloud GKE cluster with Istio add-on.

**Comment by howardjohn** [comment] 2019-11-18 14:44
This is due to using the GKE add-on any changes will be reconciled . Since this is working as intended, and outside the control of the open source istio I'll close this, if you need help with this maybe contact Google support

**Closed by howardjohn** 2019-11-18 14:44 UTC
Labels: area/config, kind/docs

**Comment by Svendegroote91** [comment] 2019-11-18 14:54
Got it - Thanks for the swift support.
