### ISSUE TITLE
Ingress fails to start with bogus Gateway

### ISSUE THREAD

**Issue by esnible** [istio/istio#28541] opened 2020-11-03 18:40 UTC
I had a problem.  Install of 1.8.0-alpha.2 failed when the IngressGateway pod didn't start.  I verified deleting a particular Gateway let the IngressGateway start, and restoring that Gateway caused a failure.

If the following Gateway is present, the Istio Ingress won't become ready.

``` bash
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: alpha
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "foo.bar"
EOF
```

Envoy rejects config from Pilot with 

```
2020-11-03T18:19:40.169491Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: Proto constraint validation failed (HttpConnectionManagerValidationError.HttpFilters[i]: ["embedded message failed validation"] | caused by HttpFilterValidationError.Name: ["value length must be at least " '\x01' " runes"]): stat_prefix: "outbound_0.0.0.0_8080"
```

`istioctl analyze` doesn't notice this.  Possible related https://github.com/istio/istio/issues/28189 .  I am using Kubernetes 1.17.

**Comment by jasonwzm** [comment] 2020-11-10 00:28
Is this an upgrade? I could not reproduce this on GKE 1.17 with the mentioned gateway preinstalled.

**Comment by esnible** [comment] 2020-11-10 14:09
I see problems even with a fresh install.  This is how I am reproducing:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: alpha
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "foo.bar"
EOF
gateway.networking.istio.io/alpha created
snible@Eds-64-Macbook ~ % kubectl -n istio-system get pods
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-7c67845d44-7x6d8   1/1     Running   0          6d19h
istiod-684ffd6f56-kbdtj                 1/1     Running   0          6d19h
snible@Eds-64-Macbook ~ % kubectl -n istio-system delete pod istio-ingressgateway-7c67845d44-7x6d8
pod "istio-ingressgateway-7c67845d44-7x6d8" deleted
snible@Eds-64-Macbook ~ % kubectl -n istio-system get pods
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-7c67845d44-8gq6b   0/1     Running   0          15s
istiod-684ffd6f56-kbdtj                 1/1     Running   0          6d19h
snible@Eds-64-Macbook ~ % kubectl -n istio-system get pods
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-7c67845d44-8gq6b   0/1     Running   0          41s
istiod-684ffd6f56-kbdtj                 1/1     Running   0          6d19h
kubectl -n istio-system logs deployment/istio-ingressgateway | grep warn
...
```

**Comment by linsun** [comment] 2020-11-12 03:18
I also saw this in a user's cluster where he is testing upgrade from 1.7 to 1.8 alpha 2.  The error in the log is the same with same symptom that ingress gw can't reach running.

```
2020-11-11T20:47:20.556720Z	info	sds	resource:ROOTCA pushed root cert to proxy
2020-11-11T20:47:20.564602Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: Proto constraint validation failed (HttpConnectionManagerValidationError.HttpFilters[i]: ["embedded message failed validation"] | caused by HttpFilterValidationError.Name: ["value length must be at least " '\x01' " runes"]): stat_prefix: "outbound_0.0.0.0_8080"
rds {
  config_source {
    ads {
    }
    resource_api_version: V3
  }
  route_config_name: "http.80"
}
http_filters {
}
http_filters {
  name: "envoy.filters.http.cors"
  typed_config {
    [type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors] {
    }
  }
}
http_filters {
  name: "envoy.filters.http.fault"
  typed_config {
    [type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault] {
    }
  }
}
http_filters {
}
http_filters {
  name: "envoy.filters.http.router"
  typed_config {
    [type.googleapis.com/envoy.extensions.filters.http.router.v3.Router] {
    }
  }
}
tracing {
  client_sampling {
    value: 100
  }
  random_sampling {
    value: 1
  }
  overall_sampling {
    value: 100
  }
}
http_protocol_options {
}
server_name: "istio-envoy"
use_remote_address {
  value: true
}
forward_client_cert_details: SANITIZE_SET
set_current_client_cert_details {
  subject {
    value: true
  }
  cert: true
  dns: true
  uri: true
}
upgrade_configs {
  upgrade_type: "websocket"
}
stream_idle_timeout {
}
normalize_path {
  value: true
}


2020-11-11T20:47:22.556462Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
```

**Comment by linsun** [comment] 2020-11-12 03:20
@howardjohn any idea?  Is this related to switch non-root to root gw stuff?

**Comment by howardjohn** [comment] 2020-11-12 03:28
no it's a bug in alpha.2. It's already fixed

**Comment by howardjohn** [comment] 2020-11-12 16:16
#28421 is the fix

**Comment by linsun** [comment] 2020-11-12 16:57
Another one https://github.com/istio/istio/pull/28758

**Comment by howardjohn** [comment] 2020-11-19 21:54
Closing as fixed by ^

**Closed by howardjohn** 2020-11-19 21:54 UTC
Labels: area/networking
