### ISSUE TITLE
Tooling in operator/Pilot to simplify mesh federation / multi-cluster 

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#13623] opened 2019-04-25 18:12 UTC
**Describe the feature request**

**Describe alternatives you've considered**

**Additional context**

**Comment by esnible** [comment] 2019-06-14 14:57
I suggest we also add tooling for istioctl to show the current multi-cluster configuration.  Possibly to interact with the operator and/or manipulate the config maps.  I made a proposal for the `istioctl mc` subcommand.  It was reviewed on a UX call that was not recorded.  Looking for feedback.  https://docs.google.com/document/d/19mQojPz0A6W56CE9iREjSfCXjrvCf_hkU-bw5trzRpI/edit

**Comment by ayj** [comment] 2019-09-30 16:54
duplicate of https://github.com/istio/istio/issues/12080

**Closed by ayj** 2019-09-30 16:54 UTC
Labels: area/networking, kind/enhancement
