### ISSUE TITLE
Incorrect mesh config in Istio 1.1.0-rc.1

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#12158] opened 2019-02-28 14:26 UTC
**Describe the bug**
I did a clean install of Istio 1.1.0-rc.1 with Helm.
After the startup Pilot continuously logs this error message:
```
2019-02-28T13:58:26.044889Z     error   error initially creating leader election record: ConfigMap "istio-ingress-controller-leader-" is invalid: metadata.name: Invalid value: "istio-ingress-controller-leader-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
This results in routes not pushed to the sidecars.

It looks like this is due to the parameter IngressClass in the mesh config not being set at all.

The installation file `install/kubernetes/istio-demo.yaml` is also missing this entry.

**Expected behavior**
A plain helm installation should result in a running pilot.

Of course anybody can update the ConfigMap himself, but it would be good to know a good value for this seemingly new parameter.

**Steps to reproduce the bug**
Install Istio:
```
helm install ~/istio/istio-1.1.0-rc.1/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system -f ~/istio/istio-1.1.0-rc.1/install/kubernetes/helm/istio/values-istio-auth-mcp.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set tracing.enabled=true --set grafana.enabled=true --set global.useMCP=true

helm install ~/istio/istio-1.1.0-rc.1/install/kubernetes/helm/istio --name istio --namespace istio-system -f ~/istio/istio-1.1.0-rc.1/install/kubernetes/helm/istio/values-istio-auth-mcp.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set tracing.enabled=true --set grafana.enabled=true --set global.useMCP=true
```

**Version**
Istio 1.1.0-rc.1
Kubernetes v1.13.0

**Installation**
```
helm install ~/istio/istio-1.1.0-rc.1/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system -f ~/istio/istio-1.1.0-rc.1/install/kubernetes/helm/istio/values-istio-auth-mcp.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set tracing.enabled=true --set grafana.enabled=true --set global.useMCP=true

helm install ~/istio/istio-1.1.0-rc.1/install/kubernetes/helm/istio --name istio --namespace istio-system -f ~/istio/istio-1.1.0-rc.1/install/kubernetes/helm/istio/values-istio-auth-mcp.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set tracing.enabled=true --set grafana.enabled=true --set global.useMCP=true
```

**Environment**
Running on a local Docker for Mac

**Comment by duderino** [comment] 2019-03-01 00:10
Closing this as a duplicate of https://github.com/istio/istio/issues/12119 which is a P0 in the 1.1 milestone

**Closed** 2019-03-01 00:10 UTC
Labels: area/networking

**Comment by p4ali** [comment] 2019-03-15 00:13
Verified in rc.5.

In rc.5, `useMCP` by default is true.  And `values-istio-auth-mcp.yaml` is gone.
