### ISSUE TITLE
manifests - istio-galley broken in master

### ISSUE THREAD

**Issue by beckend** [istio/istio#21381] opened 2020-02-23 01:16 UTC
https://github.com/istio/istio/pull/20883#discussion_r382954410

@howardjohn 

The Deployment "istio-galley" is invalid: spec.template.spec.containers[1].volumeMounts[0].name: Not found: "istio-certs"

```shell
function installerInstall() {
  local NAMESPACE="$1"
  shift
  local COMPONENT="$1"
  shift
  local CONFIGDIR="$1"
  shift

  helm template "$CONFIGDIR" --namespace "$NAMESPACE" \
    --name-template "$COMPONENT" \
    -f "$DIR_INSTALLER/global.yaml" \
    -f "$DIR/istio/global-override.yaml" $* | kubectl apply -n $NAMESPACE -l release=$COMPONENT -f -
}

# function ran on istio-config manifest
```

**Comment by beckend** [comment] 2020-02-23 01:18
https://github.com/howardjohn/istio/blob/f5230526bc0312eeef90065e09520d60ce24e184/manifests/istio-control/istio-config/templates/deployment.yaml#L164-L167 requires that which was removed in https://github.com/istio/istio/pull/20883

**Comment by howardjohn** [comment] 2020-05-13 21:08
Sorry I did see this earlier - Duplicate of https://github.com/istio/istio/issues/21635 which has some more info

**Closed by howardjohn** 2020-05-13 21:08 UTC
Labels: lifecycle/needs-triage
