### ISSUE TITLE
Prepare Release-1.6 branches

### ISSUE THREAD

**Issue by johnma14** [istio/istio#22078] opened 2020-03-11 15:08 UTC
This issue aims to track all steps needed to prepare the release 1.6 branches/builds.

Please add all steps taken here so we can document for future releases

-  [X] Set up release manager team (owner: @jacob-delgado) - Make sure the new team has write access to the repositories.  
- [X] (Optional) Update go dependencies. This must be done **before branching** so that PRs can be easily backported later. (owner: @irisdingbj: according to @howardjohn  this is  done ) _See discussion below if this should be a pre or post branch item._
  - [ ] istio/istio 
  - [ ] istio/pkg
  - [ ] istio/api 
  - [ ] istio/cni 
  - [ ] istio/client-go
- [X] Update common-files in _master_. This will prevent larger differences between _master_ and the new release as the common-files are updated after the branching (only change should be branch). (@jacob-delgado: according to @howardjohn  this is automated and done)
  - [ ] istio/istio 
  - [ ] istio/pkg 
  - [ ] istio/api 
  - [ ] istio/cni
  - [ ] istio/client-go 
  - [ ] istio/release-builder 
  - [ ] istio/gogo-genproto 
- [ ] Adjust istio/proxy to correct version of istio/envoy (@brian-avery)
- [x] Create a `release-1.6` branch in every Istio repo - run commands `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout -b release-1.6 && git push --set-upstream origin release-1.6)`.
  - [x] istio/istio
  - [x] istio/pkg
  - [x] istio/api
  - [x] istio/cni
  - [x] istio/proxy  
  - [x] istio/envoy 
  - [x] istio/client-go
  - [x] istio/tools
  - [x] istio/common-files
  - [x] istio/gogo-genproto
  - [x] istio/release-builder
  - [] Explicitly skipped: istio-releases/pipeline, istio/tests, istio/istio.io, istio/test-infra
- [x] Set up prow on release branches (@brian-avery)
  - [x] istio/istio 
  - [x] istio/pkg
  - [x] istio/api 
  - [x] istio/cni
  - [x] istio/proxy
  - [x] istio/envoy - does not use prow
  - [x] istio/client-go 
  - [x] istio/tools 
  - [x] istio/common-files
  - [x] istio/release-builder
  - [x] istio/gogo-genproto
- [x] Set up branch protection (owner: @brian-avery )
- [x] Update all repos that point to master branch of another repo to point to the release branch. `master-latest-daily` -> `1.6-dev` (see https://discuss.istio.io/t/deprecation-notice-daily-builds/3991), `latest` -> `1.6-dev`, `git clone master` to `git clone release-1.5`, etc. Commit a PR into every `release-1.6` branch to modify every `CODEOWNERS` to contain only the release managers for this release. Command: `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout release-1.6 && git checkout -b release-1.6-codeowners && echo '* @istio/release-managers-1-6' > CODEOWNERS && git add CODEOWNERS && git commit -m 'Set release managers as CODEOWNERS for release-1.6' && git push --set-upstream origin release-1.6-codeowners)`.
  - [x] istio/istio (@jacob-delgado)
  - [x] istio/pkg
  - [x] istio/api
  - [x] istio/cni
  - [x] istio/proxy 
  - [x] istio/envoy 
  - [x] istio/client-go
  - [x] istio/tools 
  - [x] istio/common-files 
  - [x] istio/gogo-genproto 
  - [x] istio/release-builder 
  - [x] istio/release-builder branch change in build.sh too!
- [x] Update common-files in _new release_. You first have to manually update the _common/Makefile.common.mk_ *update-common* target to point to the _new release_ and then run 'make update-common'. It may be that this step could be combined in the prior step in the 'make update-common' was done before the branch.
  - [x] istio/common-files should have the branch updated above.
  - [x] istio/istio
  - [x] istio/pkg 
  - [x] istio/api 
  - [x] istio/cni 
  - [x] istio/client-go 
  - [x] istio/gogo-genproto 
  - [x] istio/proxy
  - [x] istio/release-builder 
  - [x] istio/tools 
- [x] Bump master to version 1.7 
- [x] Stop publishing `latest` tags 
- [x] Add new label: cherrypick/release-1.6
- [x] Run the long-running tests on the dev builds
- [x] Send an announcement on Discuss similar to https://discuss.istio.io/t/1-6-release-branch-cut/6344
- [x] Publish a beta release

**Comment by howardjohn** [comment] 2020-03-11 15:10
I suggest you also start keeping track of release notes on https://github.com/istio/istio/wiki/Istio-Release-1.6 or otherwise. We don't really have a formal release note process but I think we can agree that waiting until 1 week before the release date and trying to handle 300 comments on a PR is less than ideal :slightly_smiling_face:

**Comment by johnma14** [comment] 2020-03-11 17:41
@brian-avery @irisdingbj @jacob-delgado I just created this PR to help you track the tasks to prepare 1.6 release branch. Feel free to update this PR or open a new one for tracking 1.6 changes.

**Comment by johnma14** [comment] 2020-03-11 17:48
I updated the wiki to include the important dates to track for the release and added the release managers but we need to add the dates and your GitHub handles.

**Comment by jacob-delgado** [comment] 2020-04-03 17:31
Another relevant doc: https://docs.google.com/document/d/1ejb4HvPYlEchkD5klDKTMIzFZrHGJ5n5lNij8NjRE-Y/edit

**Comment by howardjohn** [comment] 2020-04-24 17:15
TODO: add new label: `cherrypick/release-1.6`

**Comment by brian-avery** [comment] 2020-04-24 17:42
1.6 cherrypick label PR is here: https://github.com/istio/bots/pull/177

**Comment by brian-avery** [comment] 2020-04-24 17:42
Branch protection PR is here: https://github.com/istio/test-infra/pull/2612

**Comment by jacob-delgado** [comment] 2020-04-24 17:51
Disregard. Done to preserve old PRs. Will remove later.

This issue aims to track all steps needed to prepare the release 1.6 branches/builds.

Please add all steps taken here so we can document for future releases

-  [X] Set up release manager team (owner: @jacob-delgado) - Make sure the new team has write access to the repositories.  
- [X] (Optional) Update go dependencies. This must be done **before branching** so that PRs can be easily backported later. (owner: @irisdingbj: according to @howardjohn  this is  done ) _See discussion below if this should be a pre or post branch item._
  - [ ] istio/istio 
  - [ ] istio/pkg
  - [ ] istio/api 
  - [ ] istio/cni 
  - [ ] istio/client-go
- [X] Update common-files in _master_. This will prevent larger differences between _master_ and the new release as the common-files are updated after the branching (only change should be branch). (@jacob-delgado: according to @howardjohn  this is automated and done)
  - [ ] istio/istio 
  - [ ] istio/pkg 
  - [ ] istio/api 
  - [ ] istio/cni
  - [ ] istio/client-go 
  - [ ] istio/release-builder 
  - [ ] istio/gogo-genproto 
- [ ] Adjust istio/proxy to correct version of istio/envoy (@brian-avery)
- [ ] Create a `release-1.6` branch in every Istio repo - run commands `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout -b release-1.5 && git push --set-upstream origin release-1.5)`.
  - [ ] istio/istio
  - [ ] istio/pkg
  - [ ] istio/api
  - [ ] istio/cni
  - [ ] istio/proxy  
  - [ ] istio/envoy 
  - [ ] istio/client-go
  - [ ] istio/tools
  - [ ] istio/common-files
  - [ ] istio/gogo-genproto
  - [ ] istio/release-builder
  - [] Explicitly skipped: istio-releases/pipeline, istio/tests, istio/istio.io, istio/test-infra
- [ ] Set up prow on release branches (@brian-avery)
  - [ ] istio/istio 
  - [ ] istio/pkg
  - [ ] istio/api 
  - [ ] istio/cni
  - [ ] istio/proxy
  - [ ] istio/envoy - does not use prow
  - [ ] istio/client-go 
  - [ ] istio/tools 
  - [ ] istio/common-files
  - [ ] istio/release-builder
  - [ ] istio/gogo-genproto
- [ ] Set up branch protection (owner: @brian-avery ) https://github.com/istio/test-infra/pull/2612
- [ ] Update all repos that point to master branch of another repo to point to the release branch. `master-latest-daily` -> `1.6-dev` (see https://discuss.istio.io/t/deprecation-notice-daily-builds/3991), `latest` -> `1.6-dev`, `git clone master` to `git clone release-1.5`, etc. Commit a PR into every `release-1.6` branch to modify every `CODEOWNERS` to contain only the release managers for this release. Command: `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout release-1.6 && git checkout -b release-1.6-codeowners && echo '* @istio/release-managers-1-6' > CODEOWNERS && git add CODEOWNERS && git commit -m 'Set release managers as CODEOWNERS for release-1.6' && git push --set-upstream origin release-1.6-codeowners)`.
  - [ ] istio/istio (@jacob-delgado) https://github.com/istio/istio/pull/20559
  - [ ] istio/pkg https://github.com/istio/pkg/pull/102
  - [ ] istio/api https://github.com/istio/api/pull/1256
  - [ ] istio/cni https://github.com/istio/cni/pull/233
  - [ ] istio/proxy TODO after branch https://github.com/istio/proxy/pull/2641
  - [ ] istio/envoy TODO after branch https://github.com/istio/envoy/pull/134
  - [ ] istio/client-go https://github.com/istio/client-go/pull/42
  - [ ] istio/tools https://github.com/istio/tools/pull/705
  - [ ] istio/common-files https://github.com/istio/common-files/pull/184
  - [ ] istio/gogo-genproto https://github.com/istio/gogo-genproto/pull/33
  - [ ] istio/release-builder https://github.com/istio/release-builder/pull/122
  - [  ] istio/release-builder branch change in build.sh too! https://github.com/istio/release-builder/pull/144
- [ ] Update common-files in _new release_. You first have to manually update the _common/Makefile.common.mk_ *update-common* target to point to the _new release_ and then run 'make update-common'. It may be that this step could be combined in the prior step in the 'make update-common' was done before the branch.
  - [ ] istio/common-files should have the branch updated above.
  - [ ] istio/istio
  - [ ] istio/pkg https://github.com/istio/pkg/pull/105
  - [ ] istio/api https://github.com/istio/api/pull/1264
  - [ ] istio/cni https://github.com/istio/cni/pull/238
  - [ ] istio/client-go https://github.com/istio/client-go/pull/46
  - [ ] istio/gogo-genproto https://github.com/istio/gogo-genproto/pull/34
  - [ ] istio/proxy
  - [ ] istio/release-builder https://github.com/istio/release-builder/pull/124
- [ ] Bump master to version 1.7 https://github.com/istio/istio/pull/20549
- [ ] Stop publishing `latest` tags https://github.com/istio/istio/pull/20587
- [ ] Add new label: cherrypick/release-1.6 https://github.com/istio/bots/pull/177#pullrequestreview-400152500
- [ ] Run the long-running tests on the dev builds
- [ ] Send announcement on Discuss/Slack/Twitter
- [ ] Publish a beta release https://github.com/istio/release-builder/pull/128 / https://github.com/istio/release-builder/pull/127

**Comment by jacob-delgado** [comment] 2020-04-24 17:54
Cleaned up the tasks. Put older comment at https://docs.google.com/document/d/1ejb4HvPYlEchkD5klDKTMIzFZrHGJ5n5lNij8NjRE-Y/edit if we need help troubleshooting it.

**Comment by jacob-delgado** [comment] 2020-04-24 21:10
cc @howardjohn @fpesce 

I get the following error when I try to create a branch for `gogo-genproto`

```
Switched to a new branch 'release-1.6'
ERROR: Permission to istio/gogo-genproto.git denied to jacob-delgado.
fatal: Could not read from remote repository.
```

This works for the other repositories.

**Comment by brian-avery** [comment] 2020-04-24 21:10
PR to update CODEOWNERS and Makefile for common-files. Based off of https://github.com/istio/common-files/pull/184/files

**Comment by fpesce** [comment] 2020-04-24 21:16
> cc @howardjohn @fpesce
> 
> I get the following error when I try to create a branch for `gogo-genproto`
> 
> ```
> Switched to a new branch 'release-1.6'
> ERROR: Permission to istio/gogo-genproto.git denied to jacob-delgado.
> fatal: Could not read from remote repository.
> ```
> 
> This works for the other repositories.

Weird @jacob-delgado , I haven't seen this one before. I'm not sure there is a need for particular privileges, do you want me to create the branch as a quick workaround?

**Comment by jacob-delgado** [comment] 2020-04-24 21:16
> > cc @howardjohn @fpesce
> > I get the following error when I try to create a branch for `gogo-genproto`
> > ```
> > Switched to a new branch 'release-1.6'
> > ERROR: Permission to istio/gogo-genproto.git denied to jacob-delgado.
> > fatal: Could not read from remote repository.
> > ```
> > 
> > 
> > This works for the other repositories.
> 
> Weird @jacob-delgado , I haven't seen this one before. I'm not sure there is a need for particular privileges, do you want me to create the branch as a quick workaround?

That's fine. A root cause can be done later.

**Comment by brian-avery** [comment] 2020-04-24 21:49
PR for updating common-files on release-builder: https://github.com/istio/release-builder/pull/213

**Comment by jacob-delgado** [comment] 2020-04-24 21:49
PR for updating CODEOWNERS istio/pkg: https://github.com/istio/pkg/pull/148

**Comment by jacob-delgado** [comment] 2020-04-24 21:56
PR to update common files for istio/api: https://github.com/istio/api/pull/1402 similar to https://github.com/istio/api/pull/1264

**Comment by jacob-delgado** [comment] 2020-04-24 22:04
PR to update common files for istio/cni: https://github.com/istio/cni/pull/307 similar to https://github.com/istio/cni/pull/238

**Comment by jacob-delgado** [comment] 2020-04-24 22:21
PR to update common files and CODEOWNERS for istio/client-go https://github.com/istio/client-go/pull/108 similar to https://github.com/istio/client-go/pull/42 and https://github.com/istio/client-go/pull/46

**Comment by jacob-delgado** [comment] 2020-04-24 22:40
PR to update common files and CODEOWNERS for istio/gogo-genproto https://github.com/istio/gogo-genproto/pull/68 similar to https://github.com/istio/gogo-genproto/pull/34 and https://github.com/istio/gogo-genproto/pull/33

**Comment by jacob-delgado** [comment] 2020-04-24 23:09
PR to update common files and CODEOWNERS for istio/tools https://github.com/istio/tools/pull/914 similar to https://github.com/istio/tools/pull/705. This may have more work given the previous PR

**Comment by irisdingbj** [comment] 2020-04-25 08:26
PR to update common files and CODEOWNERS for istio/proxy https://github.com/istio/proxy/pull/2826. similar to https://github.com/istio/proxy/pull/2641

**Comment by irisdingbj** [comment] 2020-04-25 08:57
PR to update common files and CODEOWNERS for istio/istio https://github.com/istio/istio/pull/23268 . similar to https://github.com/istio/istio/pull/20559

**Comment by irisdingbj** [comment] 2020-04-25 09:06
PR to update  CODEOWNERS for istio/envoy https://github.com/istio/envoy/pull/203. similar to https://github.com/istio/envoy/pull/134

**Comment by brian-avery** [comment] 2020-04-25 21:18
Need to get https://github.com/istio/istio/pull/23265 and https://github.com/istio/istio/pull/23268/files merged before we can finish the branch process and kick off the build.

**Comment by brian-avery** [comment] 2020-04-25 21:30
PR to set branches for release-builder: https://github.com/istio/release-builder/pull/215

**Comment by brian-avery** [comment] 2020-04-25 21:46
This PR stops publishing latest for 1.6: https://github.com/istio/istio/pull/23273 similar to https://github.com/istio/istio/pull/20587

**Comment by jacob-delgado** [comment] 2020-04-25 23:05
We are awaiting PR https://github.com/istio/istio/pull/23265 before we can launch a beta build. Envoy 14.1 is deemed necessary for Istio 1.6. The current cause of why tests are failing is being actively investigated. We will keep this updated with more information as it becomes available. Thanks for your understanding and patience.

**Comment by brian-avery** [comment] 2020-04-25 23:26
PR to bump to 1.7 is here: https://github.com/istio/istio/pull/23274

**Comment by jacob-delgado** [comment] 2020-04-26 20:44
> We are awaiting PR #23265 before we can launch a beta build. Envoy 14.1 is deemed necessary for Istio 1.6. The current cause of why tests are failing is being actively investigated. We will keep this updated with more information as it becomes available. Thanks for your understanding and patience.

This was fixed and cherry picked into 1.6 via https://github.com/istio/istio/pull/23276. Thanks to everyone for their hard work.

**Comment by brian-avery** [comment] 2020-04-29 14:35
Announcements posted and the beta is out :) Closing.

**Closed by brian-avery** 2020-04-29 14:35 UTC
Labels: lifecycle/needs-triage

**Comment by jacob-delgado** [comment] 2020-05-01 21:20
PR to build new build tools image https://github.com/istio/tools/pull/932

**Comment by jacob-delgado** [comment] 2020-05-01 21:21
PR to update common-files to use build image https://github.com/istio/common-files/pull/241/files

**Comment by jacob-delgado** [comment] 2020-05-06 19:21
PR to make sure Automator works correctly in istio/test-infra for release-1.6 branch: https://github.com/istio/test-infra/pull/2643

**Comment by brian-avery** [comment] 2020-06-05 20:58
PRs to upgrade build tools: 
https://github.com/istio/tools/pull/932/files
https://github.com/istio/common-files/pull/241/files
