### ISSUE TITLE
ISTIO 1.1 - ingressgateway not working on a fresh install. Version 1.0.6 worked

### ISSUE THREAD

**Issue by marcin-kasinski** [istio/istio#12755] opened 2019-03-25 17:21 UTC
I have problem with istio 1.1.0.

I had no problem with 1.0.6 version.
It worked.
Now current version is 1.1.0 and it doen't work.

My install process:
```

curl -L https://git.io/getLatestIstio | sh -
ISTIO_VERSION=$(ls | grep istio- )
cd $ISTIO_VERSION

echo Install the istio-init 
helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system

echo Install the istio
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort --set pilot.traceSampling=100 --set tracing.enabled=true

echo listing cruds

kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l

kubectl delete svc -n istio-system grafana
kubectl delete svc -n istio-system prometheus
kubectl delete deployment -n istio-system grafana
kubectl delete deployment -n istio-system prometheus

```
Then based on https://istio.io/docs/tasks/traffic-management/ingress/ I've created Gateway and virtual service

Problem is that curl retuns 503
```

root@k8smaster:~/istio-1.1.0/bin# curl -I -H Host:httpbin.example.com http://$INGRESS_HOST:$INGRESS_PORT/status/200
HTTP/1.1 503 Service Unavailable
date: Mon, 25 Mar 2019 17:14:32 GMT
server: istio-envoy
transfer-encoding: chunked

```
Pods
```

root@k8smaster:~/istio-1.1.0/bin# kubectl get po -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-645ffc4999-f58l2            1/1     Running     0          81m
istio-galley-978f9447f-6kw5m              1/1     Running     1          81m
istio-ingressgateway-8ccdc79bc-kzsqh      1/1     Running     0          81m
istio-init-crd-10-tq8lv                   0/1     Completed   0          91m
istio-init-crd-11-bpdrr                   0/1     Completed   0          91m
istio-pilot-679c6b45b8-gbmd8              2/2     Running     0          81m
istio-policy-c9469c4df-p4cq9              2/2     Running     2          81m
istio-sidecar-injector-6dcc9d5c64-tgwdf   1/1     Running     0          81m
istio-telemetry-55d5b7d4dc-dg48p          0/2     Pending     0          66m
istio-tracing-656f9fc99c-8xd4q            1/1     Running     0          81m

```

Kubernetes version

```
root@k8smaster:~/istio-1.1.0/bin# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

ingressgateway logs:

```
...
[2019-03-25 17:04:53.769][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.listener.Filter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.770][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.770][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.770][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.770][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.775][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.775][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.775][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.775][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-25 17:04:53.775][29][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.



```

**Comment by marcin-kasinski** [comment] 2019-03-26 09:14
Pilot logs:

```

kubectl logs  -n istio-system istio-pilot-65c7879659-5mdtx istio-proxy
...
[2019-03-26 08:55:00.980][28][warning][main] [external/envoy/source/server/server.cc:533] terminating parent process
[2019-03-26 08:55:00.982][36][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-26 08:55:00.983][36][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-26 08:55:00.993][36][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-26 08:55:00.993][36][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-26 08:55:00.995][36][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-26 08:55:00.995][36][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-26 08:55:00.996][36][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-26 08:55:00.996][36][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-26 08:56:00.999][28][warning][main] [external/envoy/source/server/server.cc:405] caught SIGTERM
2019-03-26T08:56:01.001871Z     info    Epoch 0 exited normally
2019-03-26T08:56:01.001900Z     warn    Failed to delete config file /etc/istio/proxy/envoy-rev0.json for 0, remove /etc/istio/proxy/envoy-rev0.json: no such file or directory
vagrant@k8smaster:~$

```

**Comment by marcin-kasinski** [comment] 2019-03-26 11:42
With istio-1.1.1 still no success.

**Comment by markmssd** [comment] 2019-03-26 13:02
Same issue here, trying to upgrade to 1.1 for all its performance improvements, but `503`s, `503`s everywhere!

**Comment by linsun** [comment] 2019-03-26 14:39
are you using the out of box sample yaml files?  I believe I ran this on 1.1 or 1.1-rc5 and it works fine.

**Comment by markmssd** [comment] 2019-03-26 14:45
Hey @linsun , in my case I am. I've also tried to uninstall 1.0.6 completely and do a fresh install of 1.1.1, but it's the same.

**Comment by markmssd** [comment] 2019-03-26 16:59
@linsun I've created a fresh cluster to test this on. I've installed Istio 1.0.6 first along with my application code, and it was working. I've `upgraded` it to 1.1.1 and it wasn't anymore.

I've also tried to `helm del istio --purge` then re-install it from scratch (first the CRDs through istio-init, then istio itself). Then I've `helm del myapp --purge` and redeployed my application from scratch as well... but no luck :/

Here is the events of my application's pod:
<img width="1247" alt="Screen Shot 2019-03-26 at 12 56 16 PM" src="https://user-images.githubusercontent.com/5899024/55017202-a1e88580-4fc6-11e9-9935-a538e4acaf2a.png">

And here is my installation script (using the default profile and override some configs):
```
# Should be run from Istio's folder, downloadable here:
# https://github.com/istio/istio/tree/1.1.1/install/kubernetes/helm/istio

# Install Istio CRDs
helm upgrade --install istio-init install/kubernetes/helm/istio-init --namespace istio-system

# Install Istio
helm upgrade --install istio install/kubernetes/helm/istio --namespace istio-system --force --recreate-pods \
--set global.k8sIngress.enabled=true \
--set global.mtls.enabled=false \
--set gateways.istio-egressgateway.enabled=true \
--set certmanager.enabled=false \
--set grafana.enabled=true \
--set grafana.persist=true \
--set grafana.accessMode=ReadWriteOnce \
--set servicegraph.enabled=true \
--set tracing.enabled=true \
--set kiali.enabled=true \
--set kiali.tag=v0.14 \
--set kiali.dashboard.grafanaURL="" \
--set kiali.dashboard.jaegerURL=""
```

**Comment by marcin-kasinski** [comment] 2019-03-27 09:18
Additional info :


```
root@k8smaster:~/istio-1.1.1/bin# ./istioctl proxy-status
NAME                                                   CDS        LDS        EDS               RDS        PILOT                            VERSION
istio-ingressgateway-56bbdd69bf-fvjkx.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED     istio-pilot-65c7879659-xq47z     1.1.0
```





```
root@k8smaster:~/istio-1.1.1/bin# ./istioctl proxy-status istio-ingressgateway-56bbdd69bf-fvjkx.istio-system
--- Pilot Clusters
+++ Envoy Clusters
@@ -1,13 +1,12 @@
 {
    "dynamicActiveClusters": [
       {
          "cluster": {
             "name": "BlackHoleCluster",
-            "type": "STATIC",
             "connectTimeout": "1s"
          }
       },
       {
          "cluster": {
             "name": "PassthroughCluster",
             "type": "ORIGINAL_DST",

Listeners Match
Routes Match (RDS last loaded at Wed, 27 Mar 2019 10:08:15 CET)
root@k8smaster:~/istio-1.1.1/bin#
```


```
root@k8smaster:~/istio-1.1.1/bin# kubectl get gateways.networking.istio.io
NAME              AGE
httpbin-gateway   44m
root@k8smaster:~/istio-1.1.1/bin# kubectl get gateways.networking.istio.io httpbin-gateway
NAME              AGE
httpbin-gateway   45m
root@k8smaster:~/istio-1.1.1/bin# kubectl describe gateways.networking.istio.io httpbin-gateway
Name:         httpbin-gateway
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"httpbin-gateway","namespace":"default"}...
API Version:  networking.istio.io/v1alpha3
Kind:         Gateway
Metadata:
  Creation Timestamp:  2019-03-27T08:28:37Z
  Generation:          1
  Resource Version:    2840
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/default/gateways/httpbin-gateway
  UID:                 512c681c-506a-11e9-95b5-02365dd2e995
Spec:
  Selector:
    Istio:  ingressgateway
  Servers:
    Hosts:
      httpbin.example.com
    Port:
      Name:      http
      Number:    80
      Protocol:  HTTP
Events:          <none>
root@k8smaster:~/istio-1.1.1/bin#


```




```

root@k8smaster:~/istio-1.1.1/bin# kubectl get virtualservices.networking.istio.io
NAME      GATEWAYS            HOSTS                   AGE
httpbin   [httpbin-gateway]   [httpbin.example.com]   46m
root@k8smaster:~/istio-1.1.1/bin# kubectl get virtualservices.networking.istio.io httpbin
NAME      GATEWAYS            HOSTS                   AGE
httpbin   [httpbin-gateway]   [httpbin.example.com]   46m
root@k8smaster:~/istio-1.1.1/bin# kubectl describe virtualservices.networking.istio.io httpbin
Name:         httpbin
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"httpbin","namespace":"default"},...
API Version:  networking.istio.io/v1alpha3
Kind:         VirtualService
Metadata:
  Creation Timestamp:  2019-03-27T08:28:37Z
  Generation:          1
  Resource Version:    2841
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices/httpbin
  UID:                 5130c90d-506a-11e9-95b5-02365dd2e995
Spec:
  Gateways:
    httpbin-gateway
  Hosts:
    httpbin.example.com
  Http:
    Match:
      Uri:
        Prefix:  /status
      Uri:
        Prefix:  /delay
    Route:
      Destination:
        Host:  httpbin
        Port:
          Number:  8000
Events:            <none>
root@k8smaster:~/istio-1.1.1/bin#

```


Policy logs:

```

[2019-03-27 08:28:05.175][26][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.Cluster.hosts'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:28:05.175][26][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.Cluster.hosts'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:28:05.175][26][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.Cluster.hosts'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:28:05.176][14][warning][main] [external/envoy/source/server/server.cc:525] shutting down admin due to child startup
[2019-03-27 08:28:05.176][14][warning][main] [external/envoy/source/server/server.cc:533] terminating parent process
[2019-03-27 08:28:05.183][26][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:28:05.185][26][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:29:05.197][14][warning][main] [external/envoy/source/server/server.cc:405] caught SIGTERM
2019-03-27T08:29:05.199625Z     info    Epoch 0 exited normally
2019-03-27T08:29:05.199704Z     warn    Failed to delete config file /etc/istio/proxy/envoy-rev0.json for 0, remove /etc/istio/proxy/envoy-rev0.json: no such file or directory

```



Pilot logs:

```
[2019-03-27 08:30:33.817][40][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:30:33.817][40][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:30:33.820][40][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:30:33.820][40][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:30:33.822][40][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.network.http_connection_manager.v2.HttpFilter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:30:33.822][40][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 08:31:33.833][29][warning][main] [external/envoy/source/server/server.cc:405] caught SIGTERM
2019-03-27T08:31:33.893520Z     info    Epoch 0 exited normally
2019-03-27T08:31:33.893551Z     warn    Failed to delete config file /etc/istio/proxy/envoy-rev0.json for 0, remove /etc/istio/proxy/envoy-rev0.json: no such file or directory

```

Ingress logs:


```
[2019-03-27 09:05:49.470][28][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 09:05:50.772][28][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.listener.Filter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 09:05:50.774][28][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 09:05:50.776][28][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 09:08:15.159][28][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:102] gRPC config stream closed: 13,
[2019-03-27 09:08:15.667][28][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.listener.Filter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 09:08:15.683][28][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
[2019-03-27 09:08:15.683][28][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.

```

**Comment by marcin-kasinski** [comment] 2019-03-28 13:26
Additional info:

In pilot Logs I can see:

`[2019-03-28 08:53:36.037][59][critical][main] [external/envoy/source/server/server.cc:86] error initializing configuration '/etc/istio/proxy/envoy.yaml': Invalid path: /etc/certs/cert-chain.pem
`

**Comment by marcin-kasinski** [comment] 2019-03-29 07:45
Hello.

Any news here?

I'm 100% Istio 1.0.6 works but istio 1.1.1 doesn't.

**Comment by hobbytp** [comment] 2019-04-08 09:03
Is it similar with the issue: https://github.com/istio/istio/issues/12308? I also meet the similar issue when I use istio 1.1.0, I meet the issue in both minikube and real cluster. In my deployment, I don't install galley, is it related?

**Comment by bweston92** [comment] 2019-06-27 14:15
Just took the day to try upgrade from 1.0 to 1.2 and I have had nothing but 503s and connections refused. I deleted all Istio deployments etc with the `helm delete --purge istio` but I am struggling to get it working again.

Do I need to build a fresh cluster? (not ideal)

Where is there any state that would cause this to happen?

**Comment by howardjohn** [comment] 2019-09-29 03:38
Sorry to close this without proper resolution, but please try this out on Istio 1.2 or 1.3 and open a new issue with all info from https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2. We have been unable to reproduce this and are not longer supporting 1.1

**Closed by howardjohn** 2019-09-29 03:38 UTC
Labels: area/networking
