### ISSUE TITLE
Routing to a wrong endpoint with multiple virtualservices for the same host, when the virtualservices have header rules.

### ISSUE THREAD

**Issue by dreadbird** [istio/istio#10485] opened 2018-12-14 08:00 UTC
**Describe the bug**
I see a new feature：https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host
but when I match the header rules,the root path"/" will override the other rules.

**Expected behavior**
the virtualservices like these:
```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trident-web
  namespace: iop
spec:
  gateways:
  - default.istio-system.svc.cluster.local
  hosts:
  - multi-example.iop.com
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*\s*)?(canary)(.*)?$
      uri:
        prefix: /
    route:
    - destination:
        host: trident-web.iop.svc.cluster.local
        subset: canary
    timeout: 60s
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: trident-web.iop.svc.cluster.local
        subset: stable
    timeout: 60s
--------------------------
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cicd-api
  namespace: iop
spec:
  gateways:
  - default.istio-system.svc.cluster.local
  hosts:
  - multi-example.iop.com
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*\s*)?(canary)(.*)?$
      uri:
        prefix: /cicd
    route:
    - destination:
        host: cicd-api.iop.svc.cluster.local
        subset: canary
    timeout: 60s
  - match:
    - uri:
        prefix: /cicd
    route:
    - destination:
        host: cicd-api.iop.svc.cluster.local
        subset: stable
    timeout: 60s
```
and the svc:

```
apiVersion: v1
kind: Service
metadata:
  name: cicd-api
  namespace: iop
spec:
  ports:
  - name: http-cicd-apis
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: cicd-api
  type: ClusterIP
-----------------
apiVersion: v1
kind: Service
metadata:
  name: trident-web
  namespace: iop
spec:
  ports:
  - name: http-trident-web-pro
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    appinstance: trident-web
    application: trident-web
    user: cks
  type: ClusterIP
```

**Steps to reproduce the bug**
When I call the  url "http://multi-example.iop.com/cicd/core/v1/jenkins-env" from chrom with cookie witch has "roles=cannary", it should routing to the *cicd-api* service,
but I get 404 because the request was routed to the *trident-web* service,I find this at ingressgateway logs:
```
[2018-12-14T07:43:51.933Z] "GET /cicd/core/v1/jenkins-envHTTP/2" 404 - 0 571 8 0 "10.1.211.192" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "a0c33090-489c-9b1f-a2ac-730cd68895e2" "multi-example.iop.com" "10.1.101.6:80" outbound|8080|canary|trident-web.iop.svc.cluster.local - 10.1.75.6:443 10.1.211.192:55836

```

**Version**
istio version: v1.0.4
k8s version: v1.11.1+icp-ee

**Installation**
install istio with helm

**Environment**
ICP from IBM

**Comment by linsun** [comment] 2018-12-17 14:50
@frankbu can you help check this out?

**Comment by frankbu** [comment] 2018-12-17 15:54
This is working as designed. In the documentation it says `Although the order of evaluation for rules in any given source VirtualService will be retained, the cross-resource order is UNDEFINED. In other words, there is no guaranteed order of evaluation for rules across the fragment configurations, so it will only have predictable behavior if there are no conflicting rules or order dependency between rules across fragments.`.

The rules in this example do have order dependency. This rule:
```
  - match:
    - headers:
        cookie:
          regex: ^(.*\s*)?(canary)(.*)?$
      uri:
        prefix: /
    route:
    - destination:
        host: trident-web.iop.svc.cluster.local
        subset: canary
```
needs to be ordered after (i.e., lower priority) than these ones:
```
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*\s*)?(canary)(.*)?$
      uri:
        prefix: /cicd
    route:
    - destination:
        host: cicd-api.iop.svc.cluster.local
        subset: canary
    timeout: 60s
  - match:
    - uri:
        prefix: /cicd
    route:
    - destination:
        host: cicd-api.iop.svc.cluster.local
        subset: stable
    timeout: 60s
```
because any request to a uri starting with `/cicd` will also match rules for `prefix: /`.

To use this feature, there must be no overlapping conditions in the rules, or you will get UNDEFINED behavior, so even if you were lucky and it did work, there is no guarantee it will work in the future.

Btw, your second `/` rule:
```
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: trident-web.iop.svc.cluster.local
        subset: stable
    timeout: 60s
```
should work fine, because it is a "catch-all" rule which will automatically get moved to the end of the list in the merged configuration.

**Comment by dreadbird** [comment] 2018-12-18 08:02
Tks for u reply.
I thought the rules with uri `prefix: /` is "catch-all" rules whether it has overlapping conditions or not. and as the document says `the All such “catch-all” rules will be moved to the end of the list in the merged configuration`.
We have 50+ microservices, all the rules in one virtualservice will be over 1000+ lines. So this feature is very useful.
I think there is a solution that might solve the order problem.
First, sorted by the uri type: `exact`, `prefix`, `regex`
Secondly, sorted according to the length of the rule's  uri
The "catch-all" rules will be at the end of the list.

The order will be mutch better than no order.

**Comment by frankbu** [comment] 2018-12-18 15:16
Yes, the rule with ONLY `prefix: /` as match is a "catch-all", so it will go to the end. The problem is that one of your rules has two conditions in the match, `prefix: /` AND `header: ...`, so that one is NOT a catch-all. Catch-all means that it applies to ALL requests, which the header condition obviously prevents.

More intelligent merge ordering is a possible future enhancement that has been discussed, but the right way to order rules that include multiple match conditions, like your example above, is challenging. This is where user intent is hard to determine.

**Comment by dreadbird** [comment] 2018-12-19 04:07
I find a pr "VirtualService simple merging of http routes at Gateway"#8113 which commit by @rshriram  can satisfy my needs very well.
The code from https://github.com/rshriram/istio/blob/06a85dea6bab82afb0053b7b2819a597b5d44211/pilot/pkg/networking/core/v1alpha3/route/route.go#L749 
```
func CombineVHostRoutes(first []route.Route, second []route.Route) []route.Route {
	combined := append(first, second...)
	sort.SliceStable(combined, func(i, j int) bool {
		var iType, jType envoyRouteType
		var iVal, jVal string

		switch iR := combined[i].Match.PathSpecifier.(type) {
		case *route.RouteMatch_Path:
			iType = envoyPath
			iVal = iR.Path
		case *route.RouteMatch_Prefix:
			if iR.Prefix == "/" {
				iType = envoyCatchAll
			} else {
				iType = envoyPrefix
			}
			iVal = iR.Prefix
		case *route.RouteMatch_Regex:
			if iR.Regex == "*" {
				iType = envoyCatchAll
			} else {
				iType = envoyRegex
			}
			iVal = iR.Regex
		}

		switch jR := combined[j].Match.PathSpecifier.(type) {
		case *route.RouteMatch_Path:
			jType = envoyPath
			jVal = jR.Path
		case *route.RouteMatch_Prefix:
			if jR.Prefix == "/" {
				jType = envoyCatchAll
			} else {
				jType = envoyPrefix
			}
			jVal = jR.Prefix
		case *route.RouteMatch_Regex:
			if jR.Regex == "*" {
				jType = envoyCatchAll
			} else {
				jType = envoyRegex
			}
			jVal = jR.Regex
		}

		// path before prefix
		// prefix before regex
		// regex before catchall prefix / or catch all regex *
		// longest path before shorter path
		// longest prefix before shorter prefix
		// longest regex before shorter regex. it doesn't make any difference, but
		// we do it anyway to get a stable ordering
		if iType == jType {
			return len(iVal) < len(jVal)
		}

		return iType < jType
	})

	return combined
}
```
but, I am very confused , is it had been merged to master? @rshriram

**Comment by frankbu** [comment] 2018-12-19 15:18
That implementation had side effects that were not backward compatible, so the implementation was changed in #8114, before it was released.

It currently works exactly as documented, as I explained above.
https://github.com/istio/istio/blob/ab79844e47ff881a0aadcb1c9e361d7ab8ea62a4/pilot/pkg/networking/core/v1alpha3/route/route.go#L841

**Comment by frankbu** [comment] 2019-01-08 01:00
Closing this issue as it is working as designed.

**Closed by frankbu** 2019-01-08 01:00 UTC
