### ISSUE TITLE
Add local time support for istio log

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#30550] opened 2021-02-01 08:58 UTC
The current time format of istio log is UTC format. Maybe some users like local time format.
Should we add option for supporting local time format? If so, I want to support it. Thanks.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment] 2021-02-01 17:35
This will not be done unless Envoy adds support, which is not planned: https://github.com/envoyproxy/envoy/issues/3546#issuecomment-394786436. If envoy doesn't do it, we cannot/should not as it would lead to conflicting times.

Closing as working as intended. Thanks!

**Closed by howardjohn** 2021-02-01 17:35 UTC
