### ISSUE TITLE
EDS Pushes are not recorded in Proxy Push Time

### ISSUE THREAD

**Issue by rinormaloku** [istio/istio#27435] opened 2020-09-21 11:29 UTC
The metric `pilot_proxy_convergence_time_bucket` is not being used to track/record the time when EDS pushes are made.

Code where the push is not being recorded: https://github.com/istio/istio/blob/14e17ec192/pilot/pkg/xds/eds.go#L384-L390

Code where the push is being recorded: 
https://github.com/istio/istio/blob/14e17ec192/pilot/pkg/xds/ads.go#L558

To test this simply delete a pod and let it be recreated then check Grafana where you will see Pilot Pushes, but not Proxy Push Time:
![image](https://user-images.githubusercontent.com/9026451/93761367-f5fd1600-fc0d-11ea-99b7-71fa36b6d257.png)

Version: Istio 1.7.2

**Comment by howardjohn** [comment] 2020-09-21 19:44
This is (sort of) intended because EDS pushes are "incremental" and only do a fraction of the work normal pushes do, to avoid skewing the results. Very open to suggestions here though

**Comment by howardjohn** [comment] 2020-10-22 15:26
Closing as "working as intended". Happy to open if we have suggestions for improvement though.

**Closed by howardjohn** 2020-10-22 15:26 UTC
Labels: area/networking
