### ISSUE TITLE
istio 0.8 ingress doesn't have listen port 

### ISSUE THREAD

**Issue by dzendmitry** [istio/istio#5726] opened 2018-05-19 22:06 UTC
I have a bare-metal installation of kubernetes + istio 0.8
Also I have a NodePort service to Istio Ingress deployment
```
istio-system     istio-ingress-nodeport     NodePort       10.233.37.227   <none>        80:32664/TCP
```
```
Name:                     istio-ingress-nodeport
Namespace:                istio-system
Labels:                   app=ingress
                          chart=ingress-0.8.0
                          heritage=Tiller
                          istio=ingress
                          release=istio
Annotations:              <none>
Selector:                 istio=ingress
Type:                     NodePort
IP:                       10.233.37.227
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  32664/TCP
Endpoints:                10.233.102.154:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
Istio Ingress deployment exposes port 80
```
ame:                   istio-ingress
Namespace:              istio-system
CreationTimestamp:      Sat, 19 May 2018 20:44:15 +0300
Labels:                 app=ingress
                        chart=ingress-0.8.0
                        heritage=Tiller
                        istio=ingress
                        release=istio
Annotations:            deployment.kubernetes.io/revision=1
Selector:               istio=ingress
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           istio=ingress
  Annotations:      sidecar.istio.io/inject=false
  Service Account:  istio-ingress-service-account
  Containers:
   ingress:
    Image:       docker.io/istionightly/proxyv2:nightly-release-0.8
    Ports:       80/TCP, 443/TCP
```
but if I go to istio ingress pod I won't see any 80 port has beed exposed 
```
$ kubectl exec -it istio-ingress-6c6b94f8f6-56jgp -n istio-system /bin/bash
root@istio-ingress-6c6b94f8f6-56jgp:/# netstat -nap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      -
tcp        0      0 10.233.102.154:47322    10.233.30.168:15010     ESTABLISHED -
udp        0      0 10.233.102.154:52451    10.233.7.196:9125       ESTABLISHED -
udp        0      0 10.233.102.154:54821    10.233.7.196:9125       ESTABLISHED -
udp        0      0 10.233.102.154:56897    10.233.7.196:9125       ESTABLISHED -
udp        0      0 10.233.102.154:43760    10.233.0.3:53           ESTABLISHED -
udp        0      0 10.233.102.154:44816    10.233.7.196:9125       ESTABLISHED -
udp        0      0 10.233.102.154:33600    10.233.7.196:9125       ESTABLISHED -
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ]         DGRAM                    146911   -                   @envoy_domain_socket_0
root@istio-ingress-6c6b94f8f6-56jgp:/#
```
Why can it be? How can I solve that?
I suppose it's the reason I can't connect to service from outside the cluster
```
curl -v http://10.21.3.184:32664/health-check
*   Trying 10.21.3.184...
* TCP_NODELAY set
* Connection failed
* connect to 10.21.3.184 port 32664 failed: Connection refused
* Failed to connect to 10.21.3.184 port 32664: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 10.21.3.184 port 32664: Connection refused
```
and from inside the cluster
```
root@istio-pilot-79fbf89bf7-l7pfg:/# curl -v http://10.233.102.154/
*   Trying 10.233.102.154...
* connect to 10.233.102.154 port 80 failed: Connection refused
* Failed to connect to 10.233.102.154 port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 10.233.102.154 port 80: Connection refused
root@istio-pilot-79fbf89bf7-l7pfg:/# curl -v http://10.233.102.154/
```

**Comment by dzendmitry** [comment] 2018-05-20 09:38
in istio-0.7.1 release
```
root@istio-ingress-5bb556fcbf-298c7:/# netstat -nap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      229/envoy
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16/envoy
```
so how to solve it in 0.8 ?

**Comment by vietwow** [comment] 2018-05-21 10:04
@dzendmitry

Hi, I am curious that istio 0.8 was release ? I can't find it in release page.

VietNC

**Comment by dzendmitry** [comment] 2018-05-21 11:38
No, it's not release version, but you can install 0.8 using https://preliminary.istio.io/docs/setup/kubernetes/helm-install.html#install-istio-with-helm
I tried 0.8 because I encountered a problem with precedence as in issue  https://github.com/istio/istio/issues/4468 
I tried to use new v1alpha3 api for networking https://istio.io/docs/tasks/traffic-management-v1alpha3/  but, as I understood, new api don't really work in 0.7.1 release version.

**Comment by dzendmitry** [comment] 2018-05-21 20:53
Interesting. Maybe it's because I use calico network plugin in my k8s installation. @ymesika do you use some any network plugins?
My service is named `istio-ingress-nodeport` because I don't have external load balancer in installation. I suppose it's the only way to expose istio-ingress in bare-metal environment.

**Comment by dzendmitry** [comment] 2018-05-22 09:45
It doesn't matter. I just made NodePort service after istio-0.8 installation using helm.
@ymesika as you have an installation of istio-0.8 i want to ask you, does v1alpha3 networking work in 0.8 out of the box? https://preliminary.istio.io/blog/2018/v1alpha3-routing.html

**Comment by ymesika** [comment] 2018-05-22 11:15
It does but read this #5701. Might save you some time.

**Comment by esnible** [comment] 2018-05-23 17:44
I am seeing the Istio Ingress listening on 15000, but not on 80:

```
# netstat -nap | grep LISTEN
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      -      
```

**Comment by dzendmitry** [comment] 2018-05-27 17:16
You must to have LISTEN for port 80 because container proxyv2 in pod istio=ingress exposes this port and service NodePort redirects traffic to that pod.

**Comment by sakshigoel12** [comment] 2018-06-04 23:36
cc. @andraxylia

**Comment by charlesakalugwu** [comment] 2018-06-14 09:07
i'm also experiencing exactly the same as @cwocwo

**Comment by dzendmitry** [comment] 2018-06-14 11:32
As I know everything is fine in 0.8

**Comment by andraxylia** [comment] 2018-06-14 15:53
Gateway is not mandatory, but strongly recommended, especially if you want to apply routing rules to ingressing traffic. See here some of the reasons why this was introduced:

https://istio.io/blog/2018/v1alpha3-routing/

Ingress without routing rules works fine with 0.8, and we have a tool to convert from Ingress to Gateway, if it cannot be done manually.

I will close this for now, please re-open if I misunderstood anything.

**Comment by dunjut** [comment] 2018-07-12 09:01
I'm experiencing the same issue in 0.8, don't really understand how this can be resolved so far.

Can anyone please offer more details?

**Comment by andraxylia** [comment] 2018-07-12 17:01
@dunjut can you please try the Gateway? 

https://preliminary.istio.io/docs/tasks/traffic-management/ingress

with this image:
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180711-09-15/

**Comment by andraxylia** [comment] 2018-07-12 17:24
Best approach is to have the gateway controller handle k8s ingresses. Needs to be re-tested with latest pre 1.0 image.

**Comment by dunjut** [comment] 2018-07-13 08:18
@andraxylia I've tried Gateway under istio 0.8 and successfully got it worked! Thanks!

Turns out ingress(envoy) will not listen on port 80 until you explicitly tells it to (by creating a Gateway).

**Comment by kubaj** [comment] 2018-07-14 08:04
I have same problem as mentioned above. istio-ingress and istio-ingress-gateway both have service type LoadBalancer. Without creating any resources, I can access istio-ingress with LoadBalancer IP, but I cannot access istio-ingress-gateway - it is returning 'Connection refused'. 

I have tried to create Gateway and VirtualService resource according to documentation posted above, but istio-ingress-gateway is not listening again. It also doesn't have any logs about reconfiguring gateway with new configuration. I have also tried docker image 
```
docker.io/istionightly/proxyv2:nightly-release-1.0 
```
but it didn't work too.

**Comment by brianmori** [comment] 2018-08-01 18:38
I have the same issue as well with Istio 1.0.0

`apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
  labels:
    chart: gateways-1.0.0
    release: istio
    heritage: Tiller
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: NodePort
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    - name: http2
      nodePort: 31380
      port: 80
      targetPort: 80
    - name: https
      nodePort: 31390
      port: 443
    - name: tcp
      nodePort: 31400
      port: 31400
    - name: tcp-pilot-grpc-tls
      port: 15011
      targetPort: 15011
    - name: tcp-citadel-grpc-tls
      port: 8060
      targetPort: 8060
    - name: http2-prometheus
      port: 15030
      targetPort: 15030
    - name: http2-grafana
      port: 15031
      targetPort: 15031
`

but as I do the netstat 

`tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      4171/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      4082/master
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      15010/kubelet
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      14914/kube-proxy
tcp        0      0 0.0.0.0:6443            0.0.0.0:*               LISTEN      15237/nginx: master
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd
tcp6       0      0 :::32691                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::31380                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      4171/sshd
tcp6       0      0 :::31390                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::31618                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::31972                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::30564                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::30437                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::31400                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::30730                :::*                    LISTEN      14914/kube-proxy
tcp6       0      0 :::10250                :::*                    LISTEN      15010/kubelet
tcp6       0      0 :::9099                 :::*                    LISTEN      16254/calico-felix
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd
tcp6       0      0 :::10256                :::*                    LISTEN      14914/kube-proxy
`
there are no ports listening, I remember the 0.8.0 had the node ports for the ingress in LISTEN 
@kubaj if it returning connection refused, it means you have a similar problem as me, could you check if there is a process listening on that port

@andraxylia, could it be a regression ?

**Comment by esnible** [comment] 2018-08-01 19:31
Is it possible you have multiple Gateways?  Perhaps in different K8s namespaces?  The IngressGateway not listen and do its job if there are multiple
Gateways with hosts `*`.  The `kubectl logs` for the IngressGateway will report:

``` 
gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener http_0.0.0.0_80: Only a single wildcard domain is permitted
```

To fix this, delete all but one Gateway (using `istioctl delete` or `kubectl delete`)
using `*` for _hosts_.

You can check the ports the IngressGateway is listening on by doing

```
kubectl exec -n istio-system $(kubectl get pod --namespace istio-system --selector istio=ingressgateway --output jsonpath='{.items[0].metadata.name}') -- netstat -tulpn
```

**Comment by kubaj** [comment] 2018-08-01 20:26
I was trying latest nightly version before 1.0.0 release and this bug was solved for me and everything worked as expected. Ingress-gateway was bind to a port after the first gateway resource was created in the cluster.

**Comment by arghya88** [comment] 2018-08-05 17:45
Having the same problem. How to resolve it?

**Comment by dunjut** [comment] 2018-08-06 02:07
@arghya88 Try to create a [Gateway](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Gateway) as discussed above.

**Comment by louiscryan** [comment] 2018-08-07 18:39
Consider work for 1.0.1

https://github.com/istio/istio/issues/7672

**Comment by costinm** [comment] 2018-08-07 18:40
Typically if you don't see the port in netstat it means pilot didn't send a listener. That would happen if config is invalid / rejected by envoy.

1. Look in the envoy logs, see if any error messages are shown
2. Look in pilot logs, look for 'nacks' ( grep/search for the IP of the ingress ). 

This is likely a config validation - we should fix whatever we find in 1.0.1 ( 2 weeks) if we get enough data.

**Comment by jsco2t** [comment] 2018-08-24 05:59
Also having the same issue - I understand the benefits of `gateway/virtualservices` but for various reasons we aren't ready to transition to them yet. Any chance we can get this fixed in the 1.0.1 servicing release?

**Comment by linsun** [comment] 2018-12-07 18:59
not sure if there is much we can do while waiting for additional info.

@ymesika @esnible has participated in the discussion in the past, assign to you for triage when more info is avail

**Comment by esnible** [comment] 2018-12-11 18:53
Can anyone reproduce this with a valid set of Gateway CRDs?

**Comment by hustcat** [comment] 2018-12-14 10:38
hit the same issue with v1.0.3:

```
# kubectl -n istio-system exec -it  istio-ingressgateway-7958d776b5-9t2z7 -- netstat -ltnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      20/envoy        
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      20/envoy      
```



```
# kubectl -n istio-system get  pods/istio-ingressgateway-7958d776b5-9t2z7 -o yaml                   
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
    sidecar.istio.io/inject: "false"
  creationTimestamp: 2018-12-13T12:27:03Z
  generateName: istio-ingressgateway-7958d776b5-
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    pod-template-hash: 7958d776b5
  name: istio-ingressgateway-7958d776b5-9t2z7
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istio-ingressgateway-7958d776b5
    uid: 65bec608-fed2-11e8-bd82-525460110101
  resourceVersion: "748066"
  selfLink: /api/v1/namespaces/istio-system/pods/istio-ingressgateway-7958d776b5-9t2z7
  uid: 65c14887-fed2-11e8-bd82-525460110101
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  containers:
  - args:
    - proxy
    - router
    - -v
    - "2"
    - --discoveryRefreshDelay
    - 1s
    - --drainDuration
    - 45s
    - --parentShutdownDuration
    - 1m0s
    - --connectTimeout
    - 10s
    - --serviceCluster
    - istio-ingressgateway
    - --zipkinAddress
    - zipkin:9411
    - --proxyAdminPort
    - "15000"
    - --controlPlaneAuthPolicy
    - NONE
    - --discoveryAddress
    - istio-pilot:8080
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: ISTIO_META_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: docker.io/istio/proxyv2:1.0.3
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    - containerPort: 31400
      protocol: TCP
    - containerPort: 15011
      protocol: TCP
    - containerPort: 8060
      protocol: TCP
    - containerPort: 853
      protocol: TCP
    - containerPort: 15030
      protocol: TCP
    - containerPort: 15031
      protocol: TCP
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    resources:
      requests:
        cpu: 10m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/certs
      name: istio-certs
      readOnly: true
    - mountPath: /etc/istio/ingressgateway-certs
      name: ingressgateway-certs
      readOnly: true
    - mountPath: /etc/istio/ingressgateway-ca-certs
      name: ingressgateway-ca-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: istio-ingressgateway-service-account-token-cb4l5
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: kube-node2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: istio-ingressgateway-service-account
  serviceAccountName: istio-ingressgateway-service-account
  terminationGracePeriodSeconds: 30
  volumes:
  - name: istio-certs
    secret:
      defaultMode: 420
      optional: true
      secretName: istio.istio-ingressgateway-service-account
  - name: ingressgateway-certs
    secret:
      defaultMode: 420
      optional: true
      secretName: istio-ingressgateway-certs
  - name: ingressgateway-ca-certs
    secret:
      defaultMode: 420
      optional: true
      secretName: istio-ingressgateway-ca-certs
  - name: istio-ingressgateway-service-account-token-cb4l5
    secret:
      defaultMode: 420
      secretName: istio-ingressgateway-service-account-token-cb4l5
```

any advise?

**Comment by esnible** [comment] 2019-01-08 16:37
Closing because we cannot reproduce.

**Closed by esnible** 2019-01-08 16:37 UTC
Labels: area/networking, kind/customer issue, kind/need more info

**Comment by Tushar120120** [comment] 2019-03-22 12:00
if I install Isto with helm and follow the steps below, I still get error with istio 1.0.6 and 1.1.0 https://istio.io/docs/tasks/traffic-management/ingress/

**Comment by Tushar120120** [comment] 2019-03-22 12:01
if I install Isto with helm and follow the steps below, I still get error with istio 1.0.6 and 1.1.0 https://istio.io/docs/tasks/traffic-management/ingress/
