### ISSUE TITLE
Multicluster Testing Epic

### ISSUE THREAD

**Issue by ericvn** [istio/istio#23618] opened 2020-05-07 20:25 UTC
Epic to contain the changes needed for test framework for coverage of the new multicluster direction.

**Comment by stevenctl** [comment] 2020-06-08 20:39
The general plan is to start porting existing integration tests to support using however many clusters are supplied to the test framework. 

Currently I'm working on https://github.com/istio/istio/pull/24162 which removes `RequireSingleCluster()`from the TestMains in tests/integration/pilot so we can run nteg-pilot-k8s-tests_istio with the `MULTICLUSTER` topology. (As a hack to test things I just took out [that check temporarily](https://github.com/istio/istio/pull/24162/files#diff-673aff64479faae463f4138228590777L104) in the prow setup).

One disadvantage is this requires us to run the istio deploy on every cluster even though they'll incrementally start actually utilizing all clusters. 

Would it make sense to have a separate prow job for "multicluster x tests", at least temporarily. This would let us keep `RequireSingleCluster` on tests until they're converted. 

Thoughts @nmittler ?

**Comment by nmittler** [comment] 2020-06-08 21:19
> One disadvantage is this requires us to run the istio deploy on every cluster even though they'll incrementally start actually utilizing all clusters.

@stevenctl I believe we run the deploy in parallel? If not then we probably should. Otherwise, this SGTM.

**Comment by stevenctl** [comment] 2020-06-09 19:20
> I believe we run the deploy in parallel? If not then we probably should.

There are issues using multiple `istioctl/cmd GetRootCommand` in parallel. Tested with os.exec instead and it works but isn't really a valid workaround imo.

**Comment by nmittler** [comment] 2020-06-09 22:13
@stevenctl I recall trying that before and ran into a similar issue. Do you know exactly what the issue is? Are separate instances of the command somehow sharing global data?

**Comment by stevenctl** [comment] 2020-06-09 23:49
istioctl/cmd uses a lot of package level [vars](https://github.com/istio/istio/blob/master/istioctl/cmd/root.go#L46) meant to be set by flags:
```
	kubeconfig       string
	configContext    string
	namespace        string
	istioNamespace   string
	defaultNamespace string
```

**Comment by stevenctl** [comment] 2020-06-11 18:12
It actually took only a couple 1-line tweaks to get things working for parallel deploys: https://github.com/istio/istio/pull/24523

That should merge first followed by https://github.com/istio/test-infra/pull/2703. That job will end up skipping all tests until https://github.com/istio/istio/pull/24549 merges.

**Comment by nmittler** [comment] 2020-10-05 15:26
I'm closing this since it's effectively a dup of the beta graduation epic (#27137). I've moved all children there.

**Closed by nmittler** 2020-10-05 15:26 UTC
Labels: Epic, area/test and release, feature/Multi-cluster, feature/Multi-control-plane
