### ISSUE TITLE
 istiod - need namespace selector to watch a subset of namespaces in very large clusters

### ISSUE THREAD

**Issue by rshriram** [istio/istio#26679] opened 2020-08-19 23:45 UTC
**Describe the feature request**

In very large clusters with 1000s of namespaces, having istiod watch all namespaces is sometimes not desired as the mesh footprint is restricted to a small set of namespaces. We currently support a cli flag that allows the user to specify the specific sets of namespaces to watch. Following the kubernetes conventions, we should also allow the user to specify a namespace selector (set of labels) that can then be used to filter out namespaces that should be watched. We dont necessarily have to use the namespace selection mechanism in the informers (as per @howardjohn , its not performant), but we can do the filtering in our informer callbacks [get namespace of config/api object, get labels of namespace, match with selectors and determine if we should react to it or not].

The label selection mechanism allows the platform team to progressively add namespaces to the mesh as its footprint expands. XDS configs generated by us will automatically be confined to the services within these namespaces. The caveat here is that all of our APIs (Sidecar, exportTo, etc.) will be confined to the namespaces selected by these selectors (this is the case anyway when the user specifies a set of namespaces to watch).

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by rshriram** [comment] 2020-08-19 23:48
cc @pnambiar @ramaraochavali - I believe this pertains to your use case?

**Comment by sudhi-vm** [comment] 2020-08-25 21:53
@rshriram We have the same requirement at eBay. As a first quick step, we solved it by adding a new command-line argument (`appNamespaces`) to accept a comma-separated set of namespaces. This has the limitation of having to restart pilot every time a new namespace needs to be included. As you have mentioned, we were looking at specifying  namespace selector in the command line. 

We would like to help either with the implementation or the reviews. Please let me know.

**Comment by rshriram** [comment] 2020-08-26 03:24
help would be greatly appreciated. its a simple enough cli change but the code internally needs some work to plug in the namespace controller (that we already have) and cross reference the namespace for which change notifications are received with the namespace controller, and check if the labels match the user specified selectors..

**Comment by rshriram** [comment] 2020-08-26 03:27
to clarify, the primary goal is

>The label selection mechanism allows the platform team to progressively add namespaces to the mesh as its footprint expands. XDS configs generated by us will automatically be confined to the services within these namespaces. The caveat here is that all of our APIs (Sidecar, exportTo, etc.) will be confined to the namespaces selected by these selectors (this is the case anyway when the user specifies a set of namespaces to watch).

**Comment by l8huang** [comment] 2020-10-19 21:18
Any progress on this issue?

**Comment by phenixblue** [comment] 2020-11-09 23:43
We have a similar use case for this. Regardless of cluster size, the rate of change for resources seems to affect the Pilot discovery mechanism within istiod. With clusters that have a large number of batch jobs that run around the clock, istiod seems to max out CPU trying to keep up with XDS pushes to gateways/sidecars. This also means the gateways/sidecars start to fail readiness probes regularly as the configs constantly shift between STALE/SYNCED states.

**Comment by harveyxia** [comment] 2020-12-03 19:52
I'm interested in implementing this feature and was hoping to vet my approach first. Under my current understanding, at a high level we'll need the following:

1. Expose to the user a way to configure watched namespaces both by name and by selector (call it the watch namespace criteria)
2. Internally store the watched namespace criteria in a way that's accessible to the relevant controllers
3. Update the relevant controllers to filter out k8s events by the watched namespace criteria

Various questions:

1. The existing `appNamespace` [flag](https://github.com/solo-io/istio/blob/ad8781737259ae65b8dc15a6ae90433960b548fc/pilot/cmd/pilot-discovery/main.go#L128-L129) doesn't appear to have its documented effect. It appears only to be used for the [InprocessAnalysisController](https://github.com/solo-io/istio/blob/62df776bbffa8491ad3c41dd9e3440479efedc76/pilot/pkg/bootstrap/configcontroller.go#L215). Is this understanding correct?

2. In terms of where the service discovery controller needs to be modified in order to respect the watch namespace criteria, I've identified service discovery's [registerHandlers function](https://github.com/solo-io/istio/blob/f348ce0f163515d92ceb0b63c7fc9714e66cdd77/pilot/pkg/serviceregistry/kube/controller/controller.go#L506) as  potentially the spot to insert the filtering logic. Can someone confirm?

3. Are there any other components that need to be updated to respect the watched namespace criteria?

Looking forward to collaborating with you all on this project, thank you!

**Comment by howardjohn** [comment] 2020-12-03 19:59
One thing i would like to see is proof that filtering namespaces has any meaningful impact on performance when paired with Sidecar. The reasons I am suspicious is:
* We already need to watch all namespaces anyways, since k8s doesn't support watches on namespace list/selector, so we already need to read all data for k8s and store it in local cache (informer cache)
* We already filter out pushes based on Sidecar scoping, so a change to some irrelevant namespace should have no impact

**Comment by christian-posta** [comment] 2020-12-07 21:29
So we are running into two main issues:

1) Some organizations cannot take advantage of the Sidecar resource.. specifically where their processes and abstractions are either not in place or would be too onerous to put into place. This feature is to give users of Istio an option to filter things fine grained for the data plane (with Sidecar) but also on the control plane side (by not processing  resources that should be ignored as specified by the administrator)

2) We have some evidence of the impact of a feature like this re perf cc/ @yuval-k

Even with 2), point 1) is really the more important consideration of UX here.

**Comment by howardjohn** [comment] 2020-12-07 21:31
Do we have any data on performance impacts of pushing this namespace scoping into all the controllers (there are a lot of them...) vs applying it at the same level we do as Sidecar (in push_context), but instead of using just Sidecar scoping also have some global list of excluded namespaces?

**Comment by yuval-k** [comment] 2020-12-07 21:37
we are seeing excessive processing of XDS resources (this is when istio watches a namespace with large amount of pod churn):
![image](https://user-images.githubusercontent.com/325621/101408227-1d2cc080-38aa-11eb-9a59-c358ad901a08.png)

**Comment by howardjohn** [comment] 2020-12-07 21:42
@yuval-k to be clear, the issue above is the InitContext is a large amount of CPU, right? We are not concerned with StreamAggregatedResources (which is expected to be high CPU)

The initSidecarScopes only triggers if `servicesChanged || virtualServicesChanged || destinationRulesChanged || sidecarsChanged`. So are those namespaces experiencing high Service churn as well, not just pods?

**Comment by christian-posta** [comment] 2020-12-07 22:40
Yes, Services are churning and changing as well in this case.

**Comment by ramaraochavali** [comment] 2020-12-08 11:12
> also have some global list of excluded namespaces?

If the problem is sending huge configuration to proxies + proxy startup time increasing because of this huge config,  would namespace exclusion work?  

Are we trying solve Istiod perf in large clusters or are we trying to reduce the config sent to proxies (basically only generate config for namespaces that use mesh in a cluster)?

**Comment by christian-posta** [comment] 2020-12-08 15:19
Yes namespace exclusion is exactly what we'd like to do. But we'd like it to be specified by labels/selectors like we see for the sidecar injection. The list of namespaces should be dynamic and not set at startup (ie, `--appNamespace` flag won't work here.

**Comment by howardjohn** [comment] 2020-12-08 16:02
> Yes namespace exclusion is exactly what we'd like to do.

I don't think this answers the question above.

Are we:
1) Trying to reduce the size of config sent to proxies
2) Trying to reduce the frequency of config updates
3) Trying to reduce CPU/RAM cost of reading k8s resources
4) Trying to reduce CPU/RAM cost of *processing* all of the k8s resources (and then later not sending them due to Sidecar scope)

"All of the above" is a great answer but a lot more work :slightly_smiling_face:

**Comment by christian-posta** [comment] 2020-12-08 21:41
We are trying to give administrative control to mesh/platform owners to restrict what parts of a cluster are  processed to achieve "all  the above" :)

**Comment by howardjohn** [comment] 2020-12-08 21:42
(3) is more or less incompatible with "we'd like it to be specified by labels/selectors like we see for the sidecar injection." because kubernetes only allows watching a single or all namespaces, which is why I am being a bit nitpicky on the details of what we are trying to achieve - it matters

**Comment by christian-posta** [comment] 2020-12-08 22:07
Yah makes sense. So I know we probably won't be able to accomplish #3 because of the watch limitation... but we can do the #1 , #2, and #4 which would be big wins

**Comment by howardjohn** [comment] 2020-12-08 22:09
If (3) is not required, which I agree with, we should also consider making the Sidecar.Egress allow a "denylist" mode rather than just "allowlist". That way its consistent. maybe it turns out being not the right route, but we should at least consider it as a possible approach

**Comment by christian-posta** [comment] 2020-12-08 22:37
Agreed that Sidecar.Egress is related to the problem, but to be clear the focus of this change and this issue is to be able to get this perf wins without having to specify Sidecars at all if it's untenable for a specific environment.

**Comment by christian-posta** [comment] 2020-12-08 22:39
I'm happy to jump on a call to explain more.

**Comment by howardjohn** [comment] 2020-12-08 22:40
> Sidecars at all if it's untenable for a specific environment.

Sidecars have inheritence. If you have a top level Sidecar with:
```yaml
egress:
- not kube-system # theoretical syntax
```

I don't see why this would not be feasible

**Comment by christian-posta** [comment] 2020-12-08 22:43
How can we make that dynamic? I think what you're suggesting gets closer, but we we need to be able to dynamically update that list with minimal overhead... ie, using labels and selectors similar to  what we do for sidecar injection

**Comment by howardjohn** [comment] 2020-12-08 22:58
Why is updating a label easier than updating the Sidecar? Is this about resource ownership?

**Comment by christian-posta** [comment] 2020-12-08 23:09
Unfortunately in our  case hundreds  of these temp namepsaces/services/pods will be created and constantly churn on this very large cluster, and it would be preferable to just label the namespaces that  istio should watch (which won't change as much) than constantly updating a sidecar resource every few seconds

**Comment by mandarjog** [comment] 2020-12-09 16:06
@howardjohn i think the behavior needed is an istio-system scoped sidecar resource that says

Egress: { ns-selector-labels: { ... } }

Ns-selector is only valid for istio-system.
That we we are providing the selector input, but doing through the api and not the command line.

**Comment by howardjohn** [comment] 2020-12-09 16:08
@mandarjog that is one option but it shoulds like we don't actually need the label to be configurable? Like we have `istio-injection=enabled`, we can have `istio.io/watch-namespace={true,false}` or something.

One implementation concern is we don't watch namespaces right now

**Comment by linsun** [comment] 2020-12-09 16:37
Either using istio.io/watch-namespace or have a proper API for configuring this.  For example, RHSM has member rolls: https://github.com/maistra/istio-operator/blob/maistra-2.0/manifests-maistra/2.0.0/servicemeshmemberrolls.crd.yaml

BTW, the sidecar API helps with the size of config sent to proxy but doesn't help with the amount of services/pods/resources watched by istiod.  It also didn't help the scenario where operators want to run multiple meshes in a cluster where 1 mesh is only managing a few namespaces.

**Comment by linsun** [comment] 2020-12-09 16:38
cc @knrc @dgn @rcernich

**Comment by howardjohn** [comment] 2020-12-09 16:40
> but doesn't help with the amount of services/pods/resources watched by istiod. 

I don't think this is the right approach. I know Maistra does it, but Kubernetes makes it a huge pain to have this granularity. 

Also, while we should consider both topics, lets be clear if we are trying to solve scalability or limited permissions/"multitenancy" - they are different concerns.

**Comment by howardjohn** [comment] 2020-12-09 16:42
>  doesn't help with the amount of services/pods/resources watched by istiod

Also, I have yet to see someone give concrete evidence that this is a true bottleneck. I have tested Istiod with 20k pods and the resource usage for this part of the code is trivial. Unless someone can provide some data on this being a bottleneck, I am working under the assumption this is a non-issue for performance and we can filter them out in Istiod

**Comment by mandarjog** [comment] 2020-12-09 16:51
If we start watching ns objects, then istio.io/watch should suffice @christian-posta ’s requirements since that is primarily a UX and manageability concern.

The performance issue can be dealt with separately?

**Comment by rcernich** [comment] 2020-12-09 16:57
At one point there was code in istio that supported multi-list/watcher, which allowed for dynamically managing a list of watched namespaces, but I think that's since been removed.  I'm not sure I understand why supporting such a thing is so controversial, when the solution allows for both _watch all_ and _watch some_ namespaces.  As pointed out, it also helps support soft multitenancy and allows for a reduction of global permissions, all of which are good things, a step in the right direction.  And, it does not preclude supporting other approaches to multitenancy nor other approaches to security.  I would ask, why can't we do this?

**Comment by howardjohn** [comment] 2020-12-09 17:02
@rcernich from a low-permission multitenancy perspective, perhaps that makes sense. I am not sure it does from a performance perspective, since the number of watches scale with the number of namespaces. As such, I would guess (happy to be proven wrong by real data) that performance would actually decrease if we just want to filter out a single namespace. For example, if we have 100 namespaces in the cluster, and want to filter out one, we now need 99 watches per resource and we watch ~20-30 resources so that is ~2000 watches on the apiserver which is quite a lot.

**Comment by howardjohn** [comment] 2020-12-09 17:03
Not to mention the complete lack of support in client-go leading to every controller needing to be modified to support this method, whereas today we just use the standard SharedInformerFactory used by the api-server controller-manager

**Comment by rcernich** [comment] 2020-12-09 17:12
However, if it's the reverse case, where  you want to watch say five of those 100, you need to filter out 95, and then manage cases where every new namespace created needs to be filtered or not; opt-in vs opt-out.  I haven't heard a technical argument around why both use cases can't be supported.

**Comment by howardjohn** [comment] 2020-12-09 19:32
@rcernich I haven't claimed we should not do that - if someone is willing to propose a design, API, and most important testing, we can evaluate. I would like us to stop mixing multi-tenancy and performance -  the requirements in this issue are strictly about reducing the churn of noisy namespaces, so I would prefer we focus on options to solve this issue and then see if or how it aligns with possible goals of multitenancy.

**Comment by rcernich** [comment] 2020-12-09 20:13
Agreed.  I think the use case is simply opt-in vs opt-out and there currently is minimal support for the former.  Before getting into design, let's start with the basic use case and some simple requirements:

Use case: I want to choose which namespaces are included in a mesh (opt-in model for member inclusion)

Requirements:
* List of member namespaces should be dynamic, i.e. namespaces may be added or removed at any time
* Updates to the list of member namespaces should not cause a disruption of service (e.g. current mechanism requires a bounce of pilot)
* Nonexistent namespaces in the member list should not cause a disruption of service, nor should it result in log spamming

Additional requirements: (nice to have)
* Adding nonexistent namespaces to the members list should result in a validation error
* Deletion of namespaces present in the members list should be managed appropriately (maybe removed from members list, managed by finalizer to prevent deletion, etc.)

Design:
The obvious place for members list would be MeshConfig.

**Comment by rcernich** [comment] 2020-12-09 20:19
Regarding performance issues and the use of `Sidecar`, that approach assumes the topology of the mesh is known ahead of time, which may be fine, but I think it also increases operational complexity.  I'll also chime in that I know of folks that are having issues with sidecar container resourcing, as those containers are being OOM killed if they are not sized correctly.  This also adds to the cost of running the sidecars.  FWIW

**Comment by howardjohn** [comment] 2020-12-09 20:23
@rcernich I understand that those are your requirements, but I do not think these are the requirements of the 3-4 large users above in this issue, nor do I think it meets their requirements.

My understanding of the above users requirements:
* Istio scales well even when there are namespaces in the cluster with massive scale/churn that we do not care about in the mesh
   * This may be addressed in any way, including not watching these namespaces, filtering these namespaces somewhere in pilot, or simply becoming so performant that it doesn't matter
   * If this is done by some sort of filtering of namespaces, the control of filtering must be done at the namespace level (presumably a label no the namespace), not in some centralized list (like ServiceMeshMemberRoll or mesh config or my proposed `not kube-system` Sidecar addition

I am not saying their requirements are anymore valid or invalid than yours, but I certainly don't think they are the same

**Comment by mandarjog** [comment] 2020-12-09 20:28
Folks, this needs to go onto the agenda for networking WG call tomorrow 9 am PT. 

Folks that are advocating for the feature: @rcernich @yuval-k @christian-posta @linsun can you have requirements and challenges ready for discussion?

**Comment by christian-posta** [comment] 2020-12-09 20:31
Sorry, just catchup on on this thread.
Yah I can join networking WG  briefly tomorrow. Thanks!

**Comment by ilevine** [comment] 2020-12-09 20:32
awesome - I will come too :-)

**Comment by yuval-k** [comment] 2020-12-09 20:35
will join as well

**Comment by rcernich** [comment] 2020-12-09 21:13
@howardjohn, I guess I'm confused because the first two posts specifically mention restricting the control plane to a subset of namespaces in the mesh.

Regarding namespace labeling, that implies the user has the ability to add labels to namespaces.  Speaking for OpenShift, regular users do not have permission to do that, JFYI.

Regarding ServiceMeshMemberRoll, I think that's irrelevant as I'm merely advocating for a generic opt-in model, without any specific preconceived implementation (as laid out by those requirements, which can be met in any number of ways, including namespace labeling or a list in mesh config).  I think the opt-out model is less useful for large clusters with many namespaces, especially if those namespaces are indeed transient.

**Comment by howardjohn** [comment] 2020-12-09 21:21
> I guess I'm confused because the first two posts specifically mention restricting the control plane to a subset of namespaces in the mesh.

The important detail is *why* we are doing this. Performance or security/access control are extremely different, despite a similar sounding request of "restricting the control plane to a subset of namespaces in the mesh.". @christian-posta requirements, and if I recall from previous discussions, Shriram and Rama's, for example are strictly about performance as I understand it.

* "restricting the control plane to a subset of namespaces in the mesh" is an implementation detail of how we solve performance in clusters where un-important namespaces are impacting performance
* "restricting the control plane to a subset of namespaces in the mesh" is also an implementation detail of how we solve low privileged control plane and/or stricter namespace isolation

But the requirements are not the same

**Comment by rcernich** [comment] 2020-12-09 21:39
Agreed, that we need to know why, but we also need to consider the usability of the solution.  As I mentioned, Sidecar resource may not be the best approach, especially given that folks can already use that to mitigate some of these issues, so why aren't they?  And I did mention performance issues related to inclusion of all namespaces in large clusters.  This incurs a real cost to running the sidecars.

From an efficiency standpoint, namespace restriction solves many problems and is a pretty simple concept for users to understand, and most likely pretty usable in any of the manifestations described in this thread.  (FWIW, I think we should have asked these _why_ kinds of questions when we started filtering namespaces to begin with, because maybe not all namespaces belong in the mesh.  Seems we globbed onto kube-system and kube-public, but didn't consider anything beyond those.)

**Comment by howardjohn** [comment] 2020-12-09 21:57
**when not using openshift** I am not sure I fully agree that namespace restriction is even a feature for "not all namespaces belong in the mesh". Whether something has a sidecar injected is orthogonal to whether we read configuration from that namespace. For example, you cannot configure kube-proxy/Kubernetes to not read Endpoints from `foo` namespace, because there is no reason to - if you want to restrict networking you would use NetworkPolicy and if kube-proxy cannot scale then that can be addressed in other ways; what kube-proxy reads is purely an implementation detail. Similar tools like cilium and linkerd also do not expose a way to restrict the namespaces (as far as I know), for what I imagine is for the same reasons.

Having a namespace restriction at all, in my opinion, is strictly a compromise. The Sidecar egress restriction is not a "good" API/feature, its purely a compromise for the fact that we haven't been able to scale Istio without it. I suspect all of our users would be quite happy if they didn't have to configure all their dependencies like this and still got the performance they desire. Similarly, any of the changes proposed here are also a compromise.

**Comment by rcernich** [comment] 2020-12-09 22:30
I don't think OpenShift has anything at all to do with it.  It's just k8s.  It does bring along some default configuration to make it more secure out of the box, along with some features to make it easier to use and manage, but if you know k8s, you know OpenShift.

If all namespaces belong in the mesh, why then do we filter kube-system and kube-public?  As a user, why can't I restrict workloads from being members of the mesh?  As a user why can't I segregate portions of my cluster?  Why don't I have any control over what's in and what's out?  What if my cluster is shared by multiple users/groups?  If I understand what you're saying, you're saying that once you install Istio, everybody on the cluster is responsible for knowing that and taking appropriate actions.

I think the conceptual difference here is how folks use k8s: single cluster with many namespaces, segregated at department or group level; cluster per department/group; namespace per user; mix?

And regarding sizing, let's think about clusters with 500, 1000, or more namespaces.  I think managing this with opt-out policies and Sidecar resources becomes its own administrative hassle.

To be honest, I really don't know why this is so controversial.

**Comment by howardjohn** [comment] 2020-12-09 22:40
> why then do we filter kube-system and kube-public

I don't think we do - the only place I see doing this is in the analyzer to filter out noisy false positives. 
```
$ rg kube-public
galley/pkg/config/analysis/analyzers/util/config.go
23:// "kube-public": This namespace is mostly reserved for cluster usage.
29:     SystemNamespaces = []string{"kube-system", "kube-public", "kube-node-lease", "local-path-storage"}

galley/pkg/config/analysis/analyzers/testdata/service-no-port-name-system-namespace.yaml
2:# If the service is in system namespace, i.e., kube-system, istio-system, kube-public, the check will be skipped.
39:  namespace: kube-public
```

We certainly read endpoints from kube-system.

> As a user, why can't I restrict workloads from being members of the mesh?

What does this mean? That we don't read Istio configuration from those namespaces? That we *cannot* send traffic to them? That they cannot send traffic to us? That we can send traffic to them, but it is just like an external service (ie no load balancing)? That Istiod doesn't have permission to these namespaces?

These are all very different concerns, with potentially different implementations and configurations. This issue is about *one* specific concern - scalability. I don't think we should overload it with a bunch of other related feature requests

> If I understand what you're saying, you're saying that once you install Istio, everybody on the cluster is responsible for knowing that and taking appropriate actions.

What appropriate actions? Most users of Istio are running a deployment of Istio with no namespace selection (ie not Maistra, not sure if there is anything else adding such a feature today), and it can be deployed just fine without the rest of the cluster caring. Istio being deployed doesn't actually do anything until a namespace opts into injection

**Comment by rcernich** [comment] 2020-12-09 23:09
See my comment about clusters with 100s of namespaces, where the cluster is shared across departments.  Maybe some departments want to adopt Istio, maybe some don't, maybe some are on different versions, etc.  This totally depends on how the user is adopting k8s and istio.

Also, based on this thread, and the other users' comments, it seems that providing an opt-in model for namespace inclusion is something folks would like to see.

Regarding Maistra, it is tailored to our users' needs and their use cases.  It would be great if the broader Istio community could benefit from some of the innovations we've added on top of Istio.  As I keep mentioning, none of what we're talking about here restricts the way Istio is used.  Still not sure why we can't do both.

**Comment by phenixblue** [comment] 2020-12-09 23:25
Just to add a little more color to my original comment and some additional context in our use case...

Istio is an opt-in strategy for us on a namespace by namespace basis. We have large multi-tenant clusters with hundreds of namespaces. We chose an opt-in model to allow for gradual adoption and to limit support burden on the platform team that administers the Istio Controlplane (we need time to learn and mature on this stuff just as much as the consumers of the Mesh do!). We've seen a few instances where actions/configurations that happen in namespaces that aren't using Istio affect users that are using Istio. In a multi-tenant world, this type of issue leads to major instability and a low degree of trust in the Mesh. It's luck more than anything else that this hasn't bitten us more.

If a non-mesh user can deploy services/pods frequently enough to kill the Mesh Controlplane and gateways.....that's a huge problem and in that instance it is both a performance and isolation concern. We have enough scale that manually managing a list of namespaces to opt-in or opt-out of discovery is untenable. 

Since we're already relying on namespace labels for automatic sidecar injection, that becomes a simple solution to solve this and feels...well....very K8s idiomatic in nature which just adds to the warm and fuzzies.

I'm less in the know on the Istio code base, but happy to talk more in-depth if it helps.

**Comment by costinm** [comment] 2020-12-10 01:30
I think the use case is valid - it should be possible to view only a subset of namespaces, and ignore the rest. We do have an API for this - the Sidecar (import), and we also have the export API to restrict who can see a namespace. I think it's reasonable to expand this further - for example have an option to only watch namespaces that have a label. 

However how we implement this is a different story, and I want to make sure we have the right design and implementation. Having 100s of watchers, one per namespace, does not scale well and does not allow users to 'segment' with multiple istiod instances ( revisions/etc). It also requires each Istiod to still run with high RBAC permissions, and/or makes RBAC management complicated if you also restrict an Istiod with a whitelist of namespaces. 

Instead we can support all the use cases by continuing to use the current watch code, and filtering. We do this already to implement the Sidecar API, a namespace using API will ignore any config in a namespace that is not explicitly declared. This is also dynamic - you can change the Sidecar and get more or less namespaces. We can also do this filtering when using the 
API generator, so it will be possible for low-permission Istiod that doesn't directly watches k8s, but gets a filtered set of configs from the 'default'/master istiod. 

I think such an implementation will also allow us to do further optimizations ( sharding, etc) and improve multicluster - and the 
general design was approved as part of Galley/MCP. Adding back MCP ( using XDS federation instead of a custom proto ) is somewhere on the planning list I think, and adding extra filtering to it is quite desirable.

**Comment by costinm** [comment] 2020-12-10 01:36
To answer some of the previous comments: while I do agree with the use case of having an Istiod only know about a (dynamic) subset of namespaces, I think it is important to implement it in the best way and not hack it. 

I will add the requirement that such instances of Istiod that only serve a subset of namespaces are enforced, i.e. they can't 
see Secret or configs from any other namespace, and the solution works across clusters ( and possibly non-k8s envs).

**Comment by howardjohn** [comment] 2020-12-10 02:01
> We chose an opt-in model to allow for gradual adoption and to limit support burden on the platform team that administers the Istio Controlplane

One thing I wanted to clarify in case anyone didn't know, just because only namespace `foo` has sidecars doesn't mean Istio can only watch `foo`. It needs to know *all* of the Services, Endpoints, etc in the cluster to get full telemetry and load balancing functionality.

**Comment by mandarjog** [comment] 2020-12-10 02:57
Consider 1000 ns x 10 svc x 10 endpoints 
If you have 1000 ns and out of 10 have opted in for sidecar and collectively they access 50 ns, then that is the true universe of namespaces istio needs to care about.
If the opted-in ns expects load balancing to work for other ns then istio must watch endpoints. If not orig_dst will do.
Telemetry needs to know destination service for client side metrics (endpoints less so).

 * best case istio is watching services in 50 ns and endpoints in just 10 namespaces. That is 60 watches, 500 services and 1000 endpoints (10x10x10)
* worst case we have 2 watches, 10k svc and 100k endpoints.
* if eventually the whole cluster is going to adopt the mesh, then this is a transient optimization.

However all these are performance concerns.

@linsun also mentioned the ability to run multiple meshes in the same cluster. Is that just multiple control planes or multiple controlplanes that do not share a root of trust?

If you want “watched” to be a properly of the namespace like the label, then different controlplanes *cannot* treat it differently.
Can you elaborate on that requirement?

**Comment by rcernich** [comment] 2020-12-10 15:23
@mandarjog, you're assuming the entire cluster will eventually be a part of the mesh.  This usage model does not support teams/departments sharing the cluster and forces istio onto everyone, whether they want it or not.  I think it's important to understand not only how folks are adopting istio, but also how they're adopting k8s too.

I also don't understand your comment about telemetry.  I think that's embedding an assumption that services within the mesh will be communicating with services not in the mesh.  I don't think that's a concern, as services can already call outside k8s, and calling a service within k8s that is outside the mesh's control is no different.  It also assumes that users are not segregating their mesh from other services and forcing all ingress/egress to/from the mesh through gateways (which we're doing).

**Comment by howardjohn** [comment] 2020-12-10 15:36
@rcernich its clear that different users have different setups, goals, and plans for their mesh. I think we are aware of the model you are describing - but its not the only model. There are users who want the exact opposite, and they *do* want to call services not in the mesh, and they *do* want to get Istio value add out of the box for these.

If we simplify things, in any use case, Istio can be "better" if it has more information about the cluster. For example, even in your example use case, the user is strictly benefited by Istio knowing information about services outside of the mesh (this is the whole reason ServiceEntry exists)! There are, however, cases where we want to intentionally limit how smart Istio can be, as a compromise, in order to improve {security,isolation,performance}.

As I have mentioned, I do not want us to mix the concerns of performance and security. While we may end up with a common solution to both, they are vastly different problems that we need to think about independently.

**Comment by rcernich** [comment] 2020-12-10 15:48
@howardjohn, absolutely agree, and I don't think any of the options folks have been talking about on this thread preclude being able to support any of these different approaches to adoption.  (Yes, I know about ServiceEntry.)

**Comment by howardjohn** [comment] 2020-12-10 15:52
Sorry I think I had this in my head only - but my ideal long term end state
from a performance perspective is that we either don't have any controls
around this (including Sidecar and whatever we come up with here), or we
use them as "hints" only. Ultimately, what we send to Envoy is an
implementation detail, and exposing that is a leaky abstraction/compromise.
However, in the (perhaps distant) future we may be able to handle
performance problems transparently (delta xds, on demand, or whatever new
thing comes up).

If we approach it from an isolation standpoint it's totally different,
since, as I understand it, these are no longer "hints" but hard
requirements.

**Comment by rcernich** [comment] 2020-12-10 15:57
From a performance standpoint, totally agree, and I think this is something that should be addressed.  Configuring namespace inclusion is more about managing what is controlled by the mesh (although, it does mitigate performance issues in large clusters where the mesh is intended to manage a subset of namespaces).

**Comment by howardjohn** [comment] 2020-12-10 16:00
> controlled by the mesh

What do you mean by control? I would consider this doing something like
injecting a sidecar - this can already be controlled in the webhook,
whereas this issue has been more about reading Kubernetes configs from
these namespaces, which does not impact those namespaces at all.

**Comment by linsun** [comment] 2020-12-10 16:45
> @linsun also mentioned the ability to run multiple meshes in the same cluster. Is that just multiple control planes or multiple controlplanes that do not share a root of trust?

@mandarjog it could be multiple control planes that don't share the same root of trust so they are isolated meshes but within a single cluster.  These type of isolation are common in banking industry where they want each team (who may own 1+ namespaces) are isolated as much as possible.

**Comment by howardjohn** [comment] 2021-02-13 01:25
Fixed by https://github.com/istio/istio/pull/29802

**Closed by howardjohn** 2021-02-13 01:25 UTC
Labels: area/networking, community/help wanted, kind/enhancement
