### ISSUE TITLE
http2 requests fail with "protocol error: The user callback function failed"

### ISSUE THREAD

**Issue by markns** [istio/istio#6421] opened 2018-06-20 14:06 UTC
**Describe the bug**
Using the daily-build/master-20180615-09-15, http2 requests to an HTTPS service fail in the sidecar with the following message:
```
[2018-06-20 13:37:29.830][30][info][client] external/envoy/source/common/http/codec_client.cc:117] [C6] protocol error: The user callback function failed
[2018-06-20T13:37:29.825Z] "GET / HTTP/2" 503 UC 0 57 5 - "10.132.0.8" "curl/7.60.0" "5c2bfba2-ea0d-932b-b937-dbe03cdda2df" "httpbin.mydomain.xyz" "127.0.0.1:80"
```

http1.1 requests are successful: 
```
$ curl -I --http1.1 https://httpbin.mydomain.xyz
HTTP/1.1 200 OK
server: envoy
date: Wed, 20 Jun 2018 13:41:01 GMT
content-type: text/html; charset=utf-8
content-length: 7814
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 111
```
But http2 requests fail:
```
$ curl -I --http2 https://httpbin.mydomain.xyz
HTTP/2 503
content-length: 57
content-type: text/plain
date: Wed, 20 Jun 2018 13:46:03 GMT
server: envoy
x-envoy-upstream-service-time: 88
```

**Expected behavior**
http2 requests should succeed.

**Steps to reproduce the bug**

Deploy Istio into a fresh GKE 1.9.7-gke.3 cluster, with cert-manager installed and a certificate created for the *.mydomain.xyz domain.

Edit the istio config map to add istio-system namespace to the statsdUdpAddress: `statsdUdpAddress: istio-statsd-prom-bridge.istio-system:9125`

```
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
        --set global.mtls.enabled=true \
        --set global.controlPlaneSecurityEnabled=true \
        --set global.proxy.includeIPRanges="10.28.0.0/14\,10.31.240.0/20" \
        --set global.proxy.resources.limits.cpu=100m \
        --set global.proxy.resources.limits.memory=128Mi \
        --set ingressgateway.enabled=true \
        --set ingress.enabled=false \
        --set egressgateway.enabled=false \
        --set prometheus.enabled=false
```

Deploy httpbin service. Update the gateway host to something available.
```
$ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
  labels:
    name: httpbin
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - '*.mydomain.xyz'
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: httpbin
spec:
  hosts:
  - httpbin.mydomain.xyz
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: httpbin.httpbin.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: Always
        name: httpbin
        ports:
        - containerPort: 80
EOF

```

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

```
Istio release https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-20180615-09-15/

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
Enabled, command line above.

**Environment**
GKE

**Comment by markns** [comment] 2018-06-20 21:43
Hi @ymesika, I just tested with the `host: '*'` change you mention, but it makes no difference for me. I'll test with the latest version of GKE and the latest daily release in the morning. 

(btw, latest daily I've tried so far is istio-master-20180618-09-15 - same issue)

**Comment by ymesika** [comment] 2018-06-21 04:51
I didn't mean the `hosts` change to fix anything. Just was too lazy to trick `curl` with headers etc ;-)

Please let us know if it worked with the new GKE/daily.

**Comment by markns** [comment] 2018-06-21 06:18
Heh, yes I was a bit skeptical for that change fixing anything too, but I'll try anything at this stage :)

Just tested with a new GKE 1.10.4-gke.2 cluster, but still the same result.

```
[2018-06-21T06:12:27.561Z] "GET / HTTP/1.1" 200 - 0 7716 24 16 "10.132.0.7" "curl/7.60.0" "cea151fc-de5d-9602-8a98-867e0afea791" "httpbin.gridarrow.xyz" "127.0.0.1:80"
[2018-06-21 06:12:33.260][24][info][client] external/envoy/source/common/http/codec_client.cc:117] [C6] protocol error: The user callback function failed
[2018-06-21T06:12:33.249Z] "GET / HTTP/2" 503 UC 0 57 10 - "10.132.0.7" "curl/7.60.0" "66f0a44d-a110-955d-8be8-d3b8bca7d531" "httpbin.gridarrow.xyz" "127.0.0.1:80"
```

No newer daily than istio-master-20180618-09-15, so I guess it's time to figure out how to compile Istio myself. 

Since the 06/15 daily was marked as [the first RC for the June release](https://groups.google.com/d/msg/istio-dev/3i-xlzmjKmo/cE__V0bkBQAJ), isn't it worth someone from the team testing with this release though?

**Comment by markns** [comment] 2018-06-21 07:56
Just built and deployed latest master (df751e4ec43df82695c824b3a7aede1b5857ec2f), and still see the same problem.

@ymesika did you deploy Istio using helm, or another method?

**Comment by ymesika** [comment] 2018-06-21 09:00
Just went again through the following steps:
1. Deployed master using Helm
1. `kubectl create -f <your_yaml_above_with_*>`
1. Created tls.crt and tls.key (without password) using openssl
1. `kubectl create -n istio-system secret tls istio-ingressgateway-certs --key ./tls.key --cert ./tls.crt`
1. Find out the ingressgateway external IP with `kubectl get svc -n istio-system`
1. `curl -I -k --http1.1 https://x.x.x.x` -> HTTP/1.1 200 OK
1. `curl -I -k https://x.x.x.x` -> HTTP/2 200

However, this has been done with an IBM cluster and not GKE but I'm not sure it matters.

**Comment by markns** [comment] 2018-06-21 09:21
@ymesika Ok, I'll try exactly these steps, but can you let me know your exact helm command pls?

**Comment by markns** [comment] 2018-06-21 09:35
Yep, already built my images with master this morning. I'm also using `--set global.proxy.envoyStatsd.host=istio-statsd-prom-bridge.istio-system` to work around the bug I think you're referring to.
Trying your steps out now....

**Comment by markns** [comment] 2018-06-21 10:03
Nope, still the same behaviour:

Exact helm command (had to disable galley because `...no endpoints available for service "istio-galley"`
```
helm upgrade istio install/kubernetes/helm/istio  --namespace istio-system \
                               --set global.imagePullPolicy=Always \
                               --set galley.enabled=false \
                               --set global.hub=$myrepo/istio
```

```
$ curl -k --http1.1  https://httpbin.gridarrow.xyz
[2018-06-21T09:53:29.918Z] "GET / HTTP/1.1" 200 - 0 7716 18 16 "10.132.0.7" "curl/7.60.0" "aa908232-ca3b-9267-b547-4e5099c15d82" "httpbin.gridarrow.xyz" "127.0.0.1:80"

$ curl -k  https://httpbin.gridarrow.xyz
[2018-06-21 09:53:35.303][27][info][client] external/envoy/source/common/http/codec_client.cc:117] [C7] protocol error: The user callback function failed
[2018-06-21T09:53:35.291Z] "GET / HTTP/2" 503 UC 0 57 11 - "10.132.0.7" "curl/7.60.0" "12102785-568d-9d87-b0ad-8feb895f3469" "httpbin.gridarrow.xyz" "127.0.0.1:80"

$ curl -k --http1.1 https://35.205.143.128
[2018-06-21T09:54:21.568Z] "GET / HTTP/1.1" 200 - 0 7716 5 3 "10.132.0.7" "curl/7.60.0" "b6e721b3-61ac-9cff-b590-9301818a9991" "35.205.143.128" "127.0.0.1:80"

$ curl -k  https://35.205.143.128
[2018-06-21 09:54:31.800][27][info][client] external/envoy/source/common/http/codec_client.cc:117] [C10] protocol error: The user callback function failed
[2018-06-21T09:54:31.797Z] "GET / HTTP/2" 503 UC 0 57 3 - "10.132.0.7" "curl/7.60.0" "239191c4-ef11-9b9d-8921-9a89009f0d5f" "35.205.143.128" "127.0.0.1:80"
```

Using a self-signed cert from letsencrypt, but surely that's not relevant.... is it?!

What's left to test?

**Comment by rshriram** [comment] 2018-06-21 14:18
Thanks for debugging guys. I found the problem.. but the fix is thorny. This behavior (that @markns is seeing) was introduced by https://github.com/istio/istio/pull/6158 (cc @zachgersh / @Nino-K ) where the idea was that if the client is communicating over H2, it should carry over till the end even if server asked for plain HTTP (assuming server supports upgrades), while if the client is communicating over H1, it could upgrade to H2 if the server explicitly asks for H2 only.

i.e. old behavior was
```
client ----- HTTP/2----> envoy ----- HTTP/1.1 ----> backend-service
```

and the new/current behavior is

```
client ----- HTTP/2----> envoy ----- HTTP/2 ----> backend-service

client ----- HTTP/1.1----> envoy ----- HTTP/1.1 ----> backend-service
```

What is happening here is that the client is communicating over H2 but the server is explicitly asking for H1 only (i.e. it does not support any upgrade). You want the old behavior in your scenario.

Fixing @markns 's issue would cause problems in deployments that @zachgersh / @Nino-K et al have, where the h1 to backend was problematic?

The real solution though is one where envoy clusters could auto upgrade to H2, eliminating the need for us to set any of these options.

**Comment by markns** [comment] 2018-06-22 14:23
Not really sure what the correct way to proceed is with this, but just to say that I recompiled master having reverted the changes from https://github.com/istio/istio/pull/6158 and everything is working fine. Of course, I would prefer not to have to rely on a build I hacked together myself...

**Comment by zachgersh** [comment] 2018-06-22 17:18
@markns we talked about this in slack (bringing it the open issue here for posterity) - we have to actually make envoy support upgrades before this will actually be fixed (essentially what @rshriram mentioned above). I think the behavior introduced in #6158 is probably correct in a world that doesn't support h1.1 -> h2 upgrades (since it leads to the least surprising result).

Just a quick question - why make an H2 request just to the envoy and not have your backend also support H2?

**Comment by markns** [comment] 2018-06-22 17:44
Hey @zachgersh, actually I wasn't consciously making an H2 request. Would Chrome automatically upgrade the request based on the negotiation with Envoy (the ingressgateway in this case)?

**Comment by PiotrSikora** [comment] 2018-06-22 22:50
There is nothing thorny here, #6158 introduced invalid behavior. Because of how ALPN and HTTP/2 negotiation works, downstream protocol negotiated between client and the sidecar is not necessarily the same as the one client would negotiate directly with the upstream server, and it might be one that upstream server doesn't support at all, e.g. `client(h1,h2) -> server(h1)` negotiates `h1`, but `client(h1,h2) -> proxy(h1,h2) -> server(h1)` negotiates `h2` on the downstream and `h1` on the upstream.

**Comment by andraxylia** [comment] 2018-06-23 03:02
@PiotrSikora should we revert #6158 meanwhile?

**Comment by zachgersh** [comment] 2018-06-23 03:20
Think we should have a discussion around that in slack - mentioned it in the other issue.

**Comment by andraxylia** [comment] 2018-06-23 14:37
@zachgersh How about having the discussion in github?

**Comment by zachgersh** [comment] 2018-06-25 20:41
@andraxylia - I'd prefer not to revert this because that just puts us in a state where we are again broken. I think the behavior right now (with protocol) stays the same all the way through is correct. The true fix, though it is long term, is that envoy supports h1.1 --> h2 upgrade and then this problem disappears completely.

So instead of thrashing on this I think we prioritize that work if more people end up running into this.

**Comment by PiotrSikora** [comment] 2018-06-25 21:18
Broken how, exactly?

The previous behavior is the correct one (configure/negotiate HTTP protocol version on each leg). Yes, we could optimize it with opportunistic upgrades to HTTP/2, but that's only an optimization.

The behavior introduced in #6158 completely ignores capabilities of other peers and forces HTTP protocol version negotiated on the downstream leg to peers that don't even support it, as seen in this issue.

Also, if you think that opportunistic upgrades to HTTP/2 (which automatically negotiate HTTP protocol version on each leg, and don't guarantee that the same protocol is used all the way through) are the correct long-term fix, then I'm puzzled by the reasoning behind #6158, because it's moves into opposite direction.

Lastly, this is far from "trashing" - you've replaced perfectly good behavior with something that breaks existing installations, and instead of reverting it, you're insisting that adding optimization (which would effectively revert it anyway) is the only way forward.

cc @costinm

**Comment by costinm** [comment] 2018-06-25 21:30
I think if this affects gateway - it's P0, it means gateways is unusable. 

A H2 client should be able to talk with a H1 backend using the gateway - it's basic HTTP functionality.

**Comment by PiotrSikora** [comment] 2018-06-26 03:04
@andraxylia why reopen? @markns previously [confirmed](https://github.com/istio/istio/issues/6421#issuecomment-399459602) that reverting #6158 fixes this issue.

**Comment by andraxylia** [comment] 2018-06-26 04:51
@PiotrSikora I agree the revert is the way to good, I must have re-opened it when I assigned the pipeline, did not notice it got closed meanwhile. Closing it.

**Closed by andraxylia** 2018-06-26 04:51 UTC
Labels: area/networking, kind/customer issue

**Comment by bobbytables** [comment] 2018-07-03 12:54
Would this effect GRPC Gateways ([This project](https://github.com/grpc-ecosystem/grpc-gateway))  as well? We have a setup like so:

```
AWS ELB -> NGINX Ingress -> GRPC Gateway (Sidecar'd) -> GRPC Service (Sidecar'd)
```

We see this error _only_ on GRPC gateways:

```
{
  "error": "stream terminated by RST_STREAM with error code: PROTOCOL_ERROR",
  "code": 13
}
```

Just want to make sure I found the correct issue affecting us.

**Comment by jmzwcn** [comment] 2019-04-23 09:14
the same issue happen too.
