### ISSUE TITLE
istio-proxy takes so long time to work-status, so if the application is started before this time and the application need call external network, it will be failed!

### ISSUE THREAD

**Issue by tanshungang** [istio/istio#4620] opened 2018-03-29 08:39 UTC
the log of istio-proxy like: 
[2018-03-18 11:25:49.520][14][warning][main] external/envoy/source/server/server.cc:157] initializing epoch 0 (hot restart version=9.200.16384.256)
[2018-03-18 11:25:49.811][14][warning][main] external/envoy/source/server/server.cc:344] starting main dispatch loop
[2018-03-18 11:27:20.710][14][warning][main] external/envoy/source/server/server.cc:328] all clusters initialized. initializing init manager
[2018-03-18 11:27:30.191][14][warning][config] external/envoy/source/server/listener_manager_impl.cc:448] all dependencies initialized. starting workers

you see, [2018-03-18 11:25:49.520], the proxy is runing, but to [2018-03-18 11:27:30.191], the proxy is working, abort 2m, it is too long time, why?

PS: my istio version is 0.4.0

**Comment by tanshungang** [comment] 2018-03-30 08:13
my scenarios is like this:   server A is a config-center, and it is outside of service-mesh, B is a application and is inside of service mesh, B will call A to get config information when B is installing, so i set a egressrule for A.  
When kubernetes start a pod, the istio-proxy will be running firstly, when its status is running, the B will be started running immediately, but it will be failed because it cant connect A. 
wait some minutes, i restart B container by docker cmd from pod's node, and ti will be runnging normally. so, i think, the istio-proxy takes so long time to be working status since its status was running.

**Comment by ZackButcher** [comment] 2018-06-18 21:46
This is a duplicate of https://github.com/istio/istio/issues/4341. The advice in the short term is to configure the `restartPolicy` of your application container to attempt to restart until Envoy starts up and can route the request. The full solution will be whatever we decide to do in https://github.com/istio/istio/issues/4363.

**Closed by ZackButcher** 2018-06-18 21:46 UTC
Labels: area/networking
