### ISSUE TITLE
Make helmchart more cilium friendly

### ISSUE THREAD

**Issue by cccsss01** [istio/istio#48602] opened 2024-01-01 16:53 UTC
**Describe the feature request**

No value to set hostNetwork: true which is a requirement when using cilium in VXLAN mode

When using Kubernetes admission webhooks to [inject sidecar proxies](https://istio.io/latest/docs/ops/configuration/mesh/webhook/) together with Cilium overlay mode (VXLAN or GENEVE), istiod pods must be running with hostNetwork: true in order to be reachable by the API server.

**Describe alternatives you've considered**

Can be patched and/or overlayed with the helm chart

**Affected product area (please put an X in all that apply)**
istio-control/istio-discovery/values.yaml
1.20.1 helm chart for istiod

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hanxiaop** [comment] 2024-01-02 01:46
We don't have options for every custom settings, but I think this can be done with https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Comment by howardjohn** [comment] 2024-01-02 21:53
Duplicate of https://github.com/istio/istio/issues/45738

**Closed by howardjohn** 2024-01-02 21:53 UTC
Labels: kind/enhancement, area/environments, area/user experience
