### ISSUE TITLE
istioctl authn tls-check is not deterministic when multiple pilot pods are in play

### ISSUE THREAD

**Issue by gotwarlost** [istio/istio#13445] opened 2019-04-19 06:26 UTC
**Bug description**

`istioctl authn tls-check <pod>.<namespace>` does not work reliably when there are multiple pilot pods. It is only reliable when there is exactly one pilot pod.

From my reading of the code, the `authn tls-check` command execs a binary in the pilot pod's container and tries to get information about a specific pod (`proxyID=pod.namespace`).

This only works when the pilot pod that the istioctl command reached out to actually has the config for the pod for which the TLS check is needed.

I verified what was happening with the following script:
```
for pod in $(kubectl get pods -n istio-system | grep pilot | awk '{print $1}')
do
     kubectl exec -n istio-system ${pod} -- \
             pilot-discovery request GET /debug/authenticationz?proxyID=POD.NAMESPACE
done
```
4 of our 5 pods that are running return an empty response and the 5th returns the response.

That is to say, for this command to be reliable it needs to exec the command on all pilot pods and return the one response it finds. This is clearly [not what happens today](https://github.com/istio/istio/blob/a8b2ec15d4c7e7a0dc5350b3ae8eef9404264594/istioctl/cmd/istioctl/authn.go#L48).

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio 1.1.2

**Comment by esnible** [comment] 2019-05-14 17:44
This is a duplicate of https://github.com/istio/istio/issues/13028 and will be fixed by https://github.com/istio/istio/pull/13724 .

**Closed by esnible** 2019-05-14 17:44 UTC
Labels: area/user experience
