### ISSUE TITLE
VM healthchecks and heartbeats

### ISSUE THREAD

**Issue by S-Chan** [istio/istio#24159] opened 2020-05-28 01:13 UTC
**Describe the feature request**

In Kubernetes, Pods are actively checked for liveness and/or readiness, which affects whether or not they show up in endpoints and are distributed by EDS. Similarly, Nodes have heartbeats, updated by Kubelet, and are marked unresponsive after a configurable period by the Controller Manager, affecting the readiness of Pods running on unresponsive Nodes.

Today, in the WorkloadEntry API, there are no fields for marking readiness or last heartbeat. The endpoints/pod behavior can be emulated with labels from the WorkloadEntry and selectors from a corresponding ServiceEntry, but there is no notion of a timed expiration such as with heartbeats. I'm interested in expanding the WorkloadEntry API to include fields for recording healthcheck and heartbeat results, which would allow a richer readiness policy to evolve. Additionally, there would need to be some mechanism on the control plane to remove WorkloadEntries from a ServiceEntry after a configurable time period.

**Describe alternatives you've considered**

Using labels/selectors to perform basic readiness/unreadiness.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by rshriram** [comment] 2020-05-28 02:51
>Today, in the WorkloadEntry API, there are no fields for marking readiness or last heartbeat. The endpoints/pod behavior can be emulated with labels from the WorkloadEntry and selectors from a corresponding ServiceEntry, but there is no notion of a timed expiration such as with heartbeats. I'm interested in expanding the WorkloadEntry API to include fields for recording healthcheck and heartbeat results, which would allow a richer readiness policy to evolve. Additionally, there would need to be some mechanism on the control plane to remove WorkloadEntries from a ServiceEntry after a configurable time period.

So this was precisely the goal for the workload entry API.  We would be happy to guide you with regard to the implementation.

**Comment by S-Chan** [comment] 2020-05-28 04:10
Glad to hear it. Are there existing roadmap/design documents for Workload Entry, in particular the structure of healthcheck and heartbeat fields?

**Comment by sdake** [comment] 2020-05-29 00:14
This is the design: https://docs.google.com/document/d/1VDV4-prbMbzW06hslfp12sn7V6oUvnIAst6mT6FtSWc/edit#heading=h.xw1gqgyqs5b

**Comment by jack2684** [comment] 2020-05-29 00:42
Appreciate it @sdake . Would you please grant us access request?

**Comment by sdake** [comment] 2020-05-29 22:04
@ja30278 see https://github.com/istio/community/blob/master/CONTRIBUTING.md#design-documents.

Cheers,
-steve

**Comment by S-Chan** [comment] 2020-06-18 17:53
x-posting the latest health checking design doc for VMs: https://docs.google.com/document/d/1G4s_PrmvkwCKoH_kXVeSUAszsaj3ZfpIlraSdeTSPKU/edit

**Comment by howardjohn** [comment] 2020-10-22 15:15
Closing as a duplicate of https://github.com/istio/istio/issues/27713. We are actively working on this. Thanks Stephen

**Closed by howardjohn** 2020-10-22 15:15 UTC
Labels: area/networking, area/user experience, feature/Virtual-machine, kind/enhancement, lifecycle/needs-triage
