### ISSUE TITLE
EDS race misses service instances

### ISSUE THREAD

**Issue by spikecurtis** [istio/istio#5588] opened 2018-05-14 21:16 UTC
If two goroutines are updating an EDS cluster load assignment, we use locks to prevent them both from doing so at the same time.

https://github.com/istio/istio/blob/3bea9a15cbcef19f21b87eb5245c4aa340f76410/pilot/pkg/proxy/envoy/v2/eds.go#L189

But, we don't have any way to enforce the "newer" update is processed later, meaning we could end with stale load assignments on the cluster, and no indication that the cluster needs recomputation. The stale load assignments persist until something triggers a full recalculation.

**Comment by mandarjog** [comment] 2018-05-14 21:42
Great find.
If we still do periodic recompute, this blind write will be corrected then.
If not  this is a release blocking issue.

**Comment by spikecurtis** [comment] 2018-05-14 22:30
I don't believe we do a periodic recompute. I have UTs that hit this issue and hang for 9 minutes.

**Comment by costinm** [comment] 2018-05-14 22:35
I suppose safe fix is to do periodic recompute, there is an V2_REFRESH env variable (duration) so should be just template fix ( or we can change the default value). What would be reasonable ? 1 min ? 5 min ?

**Comment by mandarjog** [comment] 2018-05-15 01:17
Since the fall back PR is merged removing blocking label.
Keeping the issue open, because we want a proper fix to this problem.

**Comment by dpacierpnik** [comment] 2018-05-15 05:18
Probably causes this issue: https://github.com/istio/issues/issues/329 . Can you confirm?

**Comment by mikedoug** [comment] 2018-05-15 13:43
A periodic refresh is great and all, but it would seem like you would want istio to recover sooner than 60 seconds when instances change.  

I posted about a bug I was seeing yesterday: https://groups.google.com/forum/#!topic/istio-users/DdRgV9YhH3o.  I had four pods (hello) which communicated with the (counter102) pod through the counter service; ignore the counter pod since routingrules make it not used.

The two hello pods which could not talk to the counter service were connecting to an OLD pod IP address.  Even restarting the counter pod a second time did not get those pods to catch up -- they were frozen in their existing configuration state.  The two healthy hello pods (because they had been restarted) were able to communicate just fine to the new counter pod after the second restart.  It required killing the bad hello pods to get two fresh pods with new envoys obtaining the configuration.

I haven't read through the Istio/envoy code, but I have to assume that when pods change there is an event that triggers telling the envoy proxies to reconfigure themselves.  This would seem to have become completely wedged -- not just a race condition where we missed a single update -- but a wedge where we get no future updates.

Is there anything else I can provide to help debug this issue.  For me, this is absolutely a show stopper.

**Comment by jasmine-jaksic** [comment] 2018-06-25 20:52
@costinm What could potentially be done to fix this? And can it be done in 1.0 timeline? 
Also, has anyone complained about the 60sec push (delays on large clusters)?

**Comment by costinm** [comment] 2018-06-25 20:53
Just got back from vacation - not clear yet if the locking is the root cause (would be easy to fix), I agree that 60 sec delay on pod is not acceptable and needs to be fixed. Once I can repro and understand the root cause I can have an estimate.

**Comment by costinm** [comment] 2018-06-25 20:54
(the 60 sec was a gross fix to unblock 0.8 launch - not intended as a permanent solution)

**Closed** 2018-06-27 16:23 UTC
Labels: area/networking
