### ISSUE TITLE
//tests/e2e/tests/simple:go_default_test is flaky

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#1229] opened 2017-10-25 19:12 UTC
I keep on having to rerun the test.
Here is an example
https://storage.googleapis.com/istio-prow/pull/istio_istio/1225/e2e-suite-rbac-no_auth/1366/build-log.txt

@ldemailly  originally wrote the test but is out. @ijsnellf Could you take a look at it since you are on call.

**Comment by ldemailly** [comment] 2017-10-26 09:32
It wasn't flacky before - what changed ?

**Comment by ijsnellf** [comment] 2017-10-26 16:10
Could just be that the network got a little flaky, or things started taking longer to spin up. The issue is that the tests fail if any of the `kubectl` commands fail, which means one random `getsockopt` will cause everything to fail. I think we just need to have some retry logic.

**Comment by ldemailly** [comment] 2017-10-30 17:10
I'm back. is it still happening ? 
for kubectl retries if needed - I think the retry logic should be in the e2e framework so it's done once for all tests

**Comment by guptasu** [comment] 2017-11-14 20:45
Hi @ldemailly can we close this if no one is looking into it and it is not happening right now ?

**Comment by guptasu** [comment] 2017-11-14 20:45
or reduce the priority to p2 or something.

**Comment by ldemailly** [comment] 2017-11-16 19:17
I haven't seen the flackyness - sadly I don't know if those important tests are still running

**Closed by ldemailly** 2017-11-16 19:17 UTC
Labels: oncall
