### ISSUE TITLE
Istio does not route outgoing HTTP if it is intended for ports 5983 or 5984

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3729] opened 2018-02-23 19:10 UTC
@esnible commented on [Fri Feb 23 2018](https://github.com/istio/issues/issues/227)

**Bug:** Y

**What Version of Istio and Kubernetes are you using**
Kubernetes v1.8.3+icp+ee
Kubernetes version 0.5.0
Sidecar version http://<istio-proxy>:15000/server_info reports "envoy 0/1.6.0-dev//DEBUG live 1922 1922 0"

**Is Istio Auth enabled or not ?** Y

**What happened**:
I deployed CouchDB with MutualTLS enabled.  My application containers could not reach Couch.  Eventually I realized that although Pilot knows about my CouchDB the sidecar did not.

**How to reproduce it:**
Let's not bother with installing and exposing CouchDB.  This can be demonstrated with just two Services and _curl_.  First, `kubectl apply` this file:

```
apiVersion: v1
kind: Service
metadata:
  name: ecs-easychair
  labels:
    micro: easychair
spec:
  type: ClusterIP
  ports:
  - port: 5985 # if this is 5984, it does not appear in http://<sidecar>:15000/routes
    targetPort: 5984
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ecs-couch
  labels:
    micro: couch
spec:
  type: ClusterIP
  ports:
  - port: 5984 # if this is 5984, it does not appear in http://<sidecar>:15000/routes
    targetPort: 5984
    protocol: TCP
    name: http
```

After deploying this, ssh into the istio-proxy of any bookinfo pod, and do `curl istio-pilot.istio-system:8080/v1/routes/5985/foo/sidecar~127.0.0.1~boz~bip` and `curl istio-pilot.istio-system:8080/v1/routes/5984/foo/sidecar~127.0.0.1~boz~bip` to verify that Pilot is aware of the services and they are equivalent.

Then do `curl localhost:15000/routes | grep 5985` and `curl localhost:15000/routes | grep 5984` and see that although the istio-proxy knows about 5985 it does not know about 5984.

I noticed that 5983 has a similar issue.

**Comment by andraxylia** [comment] 2018-02-27 17:00
@costinm are you working on this for 0.7? If not, let's clear the milestone field.

**Comment by esnible** [comment] 2018-02-28 14:28
I should point out the failure behavior is very different in the TLS and NONE configurations.

I was able to make my app functional by adding "auth.istio.io/5984: NONE" to the Service when running under TLS mode.

Another symptom is that because Envoy doesn't know that 5984 is being described by Istio configuration it does not send necessary data to Zipkin.  If expected data is missing from Zipkin or combined with other parts of a deep trace and the port is 5984 it is a symptom of this issue.

**Comment by esnible** [comment] 2018-06-21 18:58
@mbanikazemi Can you look at this?  The problem is in the Envoy code base.  We need to understand if we can fix Envoy, or need to document the problem, or add logging to Pilot when this problem is about to occur.

**Comment by esnible** [comment] 2018-06-22 15:29
Closing this item because post Istio 0.7 the 5984 services *do* appear in /config_dump and /clusters.

**Closed by esnible** 2018-06-22 15:29 UTC
Labels: area/networking
