### ISSUE TITLE
go generate fails inside mixer/adapter when run from Docker container

### ISSUE THREAD

**Issue by eyeofthefrog** [istio/istio#10789] opened 2019-01-08 01:09 UTC
**Describe the bug**
This happens with any 1.1 branch/tag, including the latest master.
When running `go generate ./...` from mixer/adapter/cloudwatch, I get the following errors:
```
root@e2d3b73e3a16:~/go/src/istio.io/istio/mixer/adapter/cloudwatch# go generate ./...
/root/go/src/istio.io/istio/vendor/istio.io/api: warning: directory does not exist.
/root/go/src/istio.io/istio/vendor/github.com/gogo/protobuf: warning: directory does not exist.
/root/go/src/istio.io/istio/vendor/github.com/gogo/googleapis: warning: directory does not exist.
/root/go/src/istio.io/istio/mixer/adapter/cloudwatch/config/config.proto: No such file or directory
cloudwatch.go:16: running "/root/go/src/istio.io/istio/bin/mixer_codegen.sh": exit status 1
```

The directories do exist:
```
# ls -ld /root/go/src/istio.io/istio/vendor/istio.io/api
drwxr-xr-x 25 root root 800 Jan  7 23:46 /root/go/src/istio.io/istio/vendor/istio.io/api
# ls -ld /root/go/src/istio.io/istio/vendor/github.com/gogo/protobuf
drwxr-xr-x 39 root root 1248 Jan  7 23:46 /root/go/src/istio.io/istio/vendor/github.com/gogo/protobuf
```

If I switch the branch/tag to 1.0.5, it works fine:
```
# go generate ./...
mixer/adapter/cloudwatch/config/config.proto:46:6: no comment found for Unit
mixer/adapter/cloudwatch/config/config.proto:47:8: no comment found for None
mixer/adapter/cloudwatch/config/config.proto:48:8: no comment found for Seconds
mixer/adapter/cloudwatch/config/config.proto:49:8: no comment found for Microseconds
mixer/adapter/cloudwatch/config/config.proto:50:8: no comment found for Milliseconds
mixer/adapter/cloudwatch/config/config.proto:51:8: no comment found for Count
mixer/adapter/cloudwatch/config/config.proto:52:8: no comment found for Bytes
...
```

This is all within a Docker container. If I run it on my Mac, then it works. 

**Expected behavior**
No errors during `go generate`

**Steps to reproduce the bug**
```
go get istio.io/istio
docker run -v ${GOPATH}:/root/go -v /var/run/docker.sock:/var/run/docker.sock -e GOPATH=/root/go -w /root/go/src/istio.io/istio/mixer/adapter/cloudwatch -it --rm eyeofthefrog/codegen go generate ./...
```

**Version**
Any 1.1 related branch, including latest master.

**Comment by douglas-reid** [comment] 2019-01-08 18:20
@eyeofthefrog my guess is that running docker inside of docker is the likely the cause of what is happening here. awhile back (iirc, post 1.0 but pre 1.1), the protoc stuff was switched to use a docker image.

Is there a reason you desire to use your own docker container (instead of allowing `mixer_codegen.sh` to start one for you from the istio-blessed image) ?

Docker is not my forte, but I suspect that a docker run that leads to another docker run is potentially problematic. I'm not sure what happens with the transitive volume mounts and working directories, etc. So, the `/bin/protoc.sh` invocation probably isn't getting the full set of mounts it expects/needs for the image *it* launches.

Adding some `set -x` calls to `mixer_codegen.sh` and `protoc.sh` end up showing a call chain that ultimately invokes:

`docker run -i --volume /var/run/docker.sock:/var/run/docker.sock --rm --entrypoint /usr/bin/protoc -v /root/go/src/istio.io/istio:/root/go/src/istio.io/istio -w /root/go/src/istio.io/istio/mixer/adapter/cloudwatch gcr.io/istio-testing/protoc:2018-06-12 --proto_path=/root/go/src/istio.io/istio --proto_path=/root/go/src/istio.io/istio/vendor/istio.io/api --proto_path=/root/go/src/istio.io/istio/vendor/github.com/gogo/protobuf --proto_path=/root/go/src/istio.io/istio/vendor/github.com/gogo/googleapis --proto_path=/root/go/src/istio.io/istio --gogoslick_out=plugins=grpc,Mgogoproto/gogo.proto=github.com/gogo/protobuf/gogoproto,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,Mgoogle/rpc/status.proto=github.com/gogo/googleapis/google/rpc,Mgoogle/rpc/code.proto=github.com/gogo/googleapis/google/rpc,Mgoogle/rpc/error_details.proto=github.com/gogo/googleapis/google/rpc,:/root/go/src/istio.io/istio --docs_out=warnings=true,mode=html_fragment_with_front_matter:/root/go/src/istio.io/istio/mixer/adapter/cloudwatch/config /root/go/src/istio.io/istio/mixer/adapter/cloudwatch/config/config.proto`

**Comment by eyeofthefrog** [comment] 2019-01-08 18:39
Thanks for the reply @douglas-reid. We're building an out-of-process adapter, and the build process for the adapter is done inside a docker container. 

When mounting volumes, docker binds them using the daemon running on the host. So when the docker inside my build container attempts to bind those paths, it expects those paths on the host...but uses the path names from the container. However, I've run into this before and have the proper symlinks to get around this issue. I'm curious why it doesn't work here. Maybe I need to run a separate docker daemon inside our build container to make this work. I'll try a few things out and update this issue.

One thing that looks odd to me in the above command, the docker.sock is mounted into the container. This is usually only done when running docker commands inside of the container, which is why it's in my command. I'm surprised if it's needed here.

I believe you'll run into people having this issue more and more as they create adapters. It would be cool to make the build process easier, or help users in defining exactly what they'll need to do when building their adapters. Here's a semi-related issue we're following that we're working around...but it would be nice to have fixed as well: #8191

**Comment by douglas-reid** [comment] 2019-01-08 18:48
@eyeofthefrog any help you can provide here is much appreciated. we should loop in the folks that updated `protoc.sh` as well.

@gargnupur can you provide any insight into the docker invocation in `protoc.sh`? It works fine directly from a shell, but seems to cause issues when invoked from a `docker run` command that remaps the mounts, etc.

**Comment by douglas-reid** [comment] 2019-01-08 19:39
Either way. I'm fine closing it for now, I guess. I feel like we may want to add that command to the wiki or something similar (with instructions) in case this comes up again. Thoughts?

**Comment by eyeofthefrog** [comment] 2019-01-08 19:52
I'm trying to think of a way to phrase it. Maybe something like:

Note: The protoc command is executed inside a Docker container during the `go generate` command. If you will be running `go generate` within a container during your build process, ensure the file system matches the host and that the `docker.sock` file is mounted inside your container. For example:
```
docker run -v ${HOME}:${HOME} -v /var/run/docker.sock:/var/run/docker.sock -e GOPATH=${HOME}/go -w ${HOME}/workspace/youradapter -it --rm yourcontainer:tag go generate ./...
```

**Comment by gargnupur** [comment] 2019-01-08 20:49
@douglas-reid:  Hadn't run this scenario of running go generate within docker..
We needed to add /var/run/docker.sock because otherwise container was not able to find certain files on host...

@eyeofthefrog : Thanks for the command ! We should add this to wiki..

**Comment by eyeofthefrog** [comment] 2019-01-08 23:37
Cool, I'll leave this issue open for wiki updating. Thanks!

**Closed** 2019-01-09 18:23 UTC
