### ISSUE TITLE
Headless service broken in 1.6.0 (no healthy upstream)

### ISSUE THREAD

**Issue by cvandesande** [istio/istio#24082] opened 2020-05-25 17:32 UTC
Upgrading from 1.5.4 to 1.6.0 resulted in "no healthy upstream" errors from Envoy. It worked perfectly when rolling back to 1.5.4

Finally resolved the issue by removing `clusterIP: None` from the affected services.
Seems 1.5.4 was Ok with headless services: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

But 1.6.0 is not.  Not sure if really a bug, or working as expected, but I thought I'd put the issue in for visibility.

[X] Networking

**Expected behavior**
Envoy to work with headless services

**Steps to reproduce the bug**
Create a "headless" service with clusterIP: None.  This will still work with an ingress controller, and works with Istio 1.5.4 but not since upgrading to 1.6.0

**How was Istio installed?**
`istioctl manifest apply --set values.kiali.enabled=true --set values.gateways.istio-ingressgateway.type=NodePort`

**Environment where bug was observed (cloud vendor, OS, etc)**
"Bare metal" kubeadm deployment 1.18.3

**Comment by hzxuzhonghu** [comment] 2020-05-26 01:14
>Finally resolved the issue by removing clusterIP: None from the affected services.

For headless service, there is no clusterIP, not sure how does your service look like and how is it accessed?

**Comment by cvandesande** [comment] 2020-05-26 09:42
> For headless service, there is no clusterIP, not sure how does your service look like and how is it accessed?

My understanding is that when there's no clusterIP, then a DNS lookup for the kube service will return all of the pod IPs.  This is necessary if say you needed to send a message to all of your Pods at once. Otherwise only the service IP is returned.

Maybe that is a situation that Istio has it's own solution for, I'm not sure, still learning Istio.

**Comment by mraszplewicz** [comment] 2020-05-26 19:47
I have exactly the same problem. Same configuration worked with Istio 1.5.1, 1.5.4 and does not work with 1.6.0. My service has clusterIP: None set because it i headless: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services.

**Comment by hzxuzhonghu** [comment] 2020-05-27 02:23
>My understanding is that when there's no clusterIP, then a DNS lookup for the kube service will return all of the pod IPs.

Assume you mean one of the pod IP.   I can think of with istio 1.6, if the headless service is not injected with a sidecar, then it works well after upgrading from 1.5 to 1.6.

I believe the cause is that #21987. Note that if the headless service has sidecar injected, then you need to either enable mtls with a Destinationrule or disable the mtls required by the headless service with a PeerAuthentication .

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: xxxx
spec:
  host: headless-service
    tls:
      mode: ISTIO_MUTUAL
```
or 
```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  selector:
    matchLabels:
      app: headlessxxx
      version: v1
  mtls:
    mode: DISABLE 
```

**Comment by cvandesande** [comment] 2020-05-27 12:56
> Assume you mean one of the pod IP.

No, I specifically mean all of the pod IPs.

If you perform an nslookup on a kube headless service then every single pod IP will be returned.

This is an example nslookup of a headless service that is running 2 replicas:
```
kubectl run -it --rm alpine --image=alpine --restart=Never --rm -- sh

If you don't see a command prompt, try pressing enter.
/ # nslookup headless-svc.team-chris.svc.cluster.local
Server:		10.118.240.10
Address:	10.118.240.10:53

Non-authoritative answer:
Name:	headless-svc.team-chris.svc.cluster.local
Address: 10.118.213.17
Name:	headless-svc.team-chris.svc.cluster.local
Address: 10.118.211.11
/ #
```
Both replica pod addresses have been returned from the DNS lookup. This is a feature of the headless service.

I will however test your suggestions later today.

**Comment by cvandesande** [comment] 2020-05-27 19:29
So I tried a fresh installation of Kubernetes, with a fresh Istio 1.6.0, and used the "helloworld" app from this repo.

The only change I made was to set the helloworld service as headless:
```
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  clusterIP: None
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
```

Attempting to disable mtls with a peer authentication:
```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  selector:
    matchLabels:
      app: helloworld
      version: v1
  mtls:
    mode: DISABLE
```

After applying the PeerAuthentication I still get "no healthy upstream"

```
cvandesande@kube1:~/istio/samples/helloworld$ kubectl get po
NAME                             READY   STATUS    RESTARTS   AGE
helloworld-v1-5b75657f75-98pqm   2/2     Running   0          20m

cvandesande@kube1:~/istio/samples/helloworld$ kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
helloworld   ClusterIP   None         <none>        5000/TCP   15m
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP    123m

cvandesande@kube1:~/istio/samples/helloworld$ kubectl get gateway
NAME                 AGE
helloworld-gateway   20m

cvandesande@kube1:~/istio/samples/helloworld$ kubectl get vs
NAME         GATEWAYS               HOSTS   AGE
helloworld   [helloworld-gateway]   [*]     20m

cvandesande@kube1:~/istio/samples/helloworld$ kubectl get peerauthentication
NAME      AGE
default   17m

cvandesande@kube1:~/istio/samples/helloworld$ kubectl -n istio-system get svc

NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                      AGE
istio-ingressgateway   NodePort    10.100.37.204   <none>        15021:30153/TCP,80:31861/TCP,443:30789/TCP,15443:30351/TCP   119m
istiod                 ClusterIP   10.109.90.46    <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP,53/UDP,853/TCP         119m
kiali                  ClusterIP   10.107.82.254   <none>        20001/TCP                                                    119m
prometheus             ClusterIP   10.102.64.236   <none>        9090/TCP                                                     119m

cvandesande@kube1:~/istio/samples/helloworld$ curl -i http://localhost:31861/hello
HTTP/1.1 503 Service Unavailable
content-length: 19
content-type: text/plain
date: Wed, 27 May 2020 19:24:30 GMT
server: istio-envoy

no healthy upstream
```

When I tried to apply the destinationrule, I got an yaml to json error:
```
$ cat destrule.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-destrule
spec:
  host: helloworld
    tls:
      mode: ISTIO_MUTUAL

$ kubectl apply -f destrule.yaml 
error: error parsing destrule.yaml: error converting YAML to JSON: yaml: line 7: mapping values are not allowed in this context
```

Not sure if I applied everything correctly but I think so

**Comment by hzxuzhonghu** [comment] 2020-05-28 01:41
@cvandesande Sorry i have to apologize, #21987 is not inc 1.6.0. Will be in 1.6.1.

**Comment by hzxuzhonghu** [comment] 2020-05-28 01:43
You can debug it, and get the config dump.

**Comment by cvandesande** [comment] 2020-05-30 18:57
Any particular config I should be looking for?
This is the endpoints output for the pod
```
$ istioctl proxy-config endpoints helloworld-v1-5b75657f75-98pqm
ENDPOINT                         STATUS      OUTLIER CHECK     CLUSTER
10.109.90.46:15012               HEALTHY     OK                xds-grpc
10.244.0.17:15010                HEALTHY     OK                outbound|15010||istiod.istio-system.svc.cluster.local
10.244.0.17:15012                HEALTHY     OK                outbound|15012||istiod.istio-system.svc.cluster.local
10.244.0.17:15014                HEALTHY     OK                outbound|15014||istiod.istio-system.svc.cluster.local
10.244.0.17:15017                HEALTHY     OK                outbound|443||istiod.istio-system.svc.cluster.local
10.244.0.17:15053                HEALTHY     OK                outbound|853||istiod.istio-system.svc.cluster.local
10.244.0.18:9090                 HEALTHY     OK                outbound|9090||prometheus.istio-system.svc.cluster.local
10.244.0.19:8080                 HEALTHY     OK                outbound|80||istio-ingressgateway.istio-system.svc.cluster.local
10.244.0.19:8443                 HEALTHY     OK                outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
10.244.0.19:15021                HEALTHY     OK                outbound|15021||istio-ingressgateway.istio-system.svc.cluster.local
10.244.0.19:15443                HEALTHY     OK                outbound|15443||istio-ingressgateway.istio-system.svc.cluster.local
10.244.0.20:20001                HEALTHY     OK                outbound|20001||kiali.istio-system.svc.cluster.local
10.244.0.21:53                   HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
10.244.0.21:9153                 HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
10.244.0.22:53                   HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
10.244.0.22:9153                 HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
127.0.0.1:5000                   HEALTHY     OK                inbound|5000|http|helloworld.default.svc.cluster.local
127.0.0.1:15000                  HEALTHY     OK                prometheus_stats
127.0.0.1:15020                  HEALTHY     OK                agent
127.0.0.1:15021                  HEALTHY     OK                inbound|15021|mgmt-15021|mgmtCluster
192.168.122.88:6443              HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
unix://./etc/istio/proxy/SDS     HEALTHY     OK                sds-grpc
```

**Comment by so-jelly** [comment] 2020-06-24 16:09
I am having the same problem with 1.6.3.  1.5.6 seems to work.  I have tried applying permissive peer auth to relevant workloads.   I am using strict mtls in the mesh.   seems some work on the transport socket here that seems related. https://github.com/istio/istio/pull/21987

**Comment by jshum2479** [comment] 2020-06-27 22:37
I am having the same problem.  It works in 1.5.4.   It seems that there are no listeners created even though there is an inbound endpoint.

**Comment by 4qv907rtet5r** [comment] 2020-06-30 04:10
> I am having the same problem with 1.6.3. 1.5.6 seems to work. I have tried applying permissive peer auth to relevant workloads. I am using strict mtls in the mesh. seems some work on the transport socket here that seems related. #21987

@so-jelly 
In version 1.6.3 I have the same problem.
Have you solved it?

**Comment by hzxuzhonghu** [comment] 2020-07-03 01:23
you need this https://github.com/istio/istio/pull/24319

**Comment by suninuni** [comment] 2020-07-15 09:27
@4qv907rtet5r @jshum2479 @so-jelly 

I resolved my problem by set `PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES` as `true` and `PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS` as `false` in istiod which in version 1.6.5.

I found them in https://istio.io/latest/docs/reference/commands/pilot-agent/#envvars

![image](https://user-images.githubusercontent.com/7345529/87520062-07c5b880-c6b5-11ea-895f-3f2ef4ea290b.png)

After this, i found those headless services in `istioctl pc endpoints` and i can request them successfully in the mesh.

**Comment by 4qv907rtet5r** [comment] 2020-07-16 01:40
> @4qv907rtet5r @jshum2479 @so-jelly
> 
> I resolved my problem by set `PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES` as `true` and `PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS` as `false` in istiod which in version 1.6.5.
> 
> I found them in https://istio.io/latest/docs/reference/commands/pilot-agent/#envvars
> 
> ![image](https://user-images.githubusercontent.com/7345529/87520062-07c5b880-c6b5-11ea-895f-3f2ef4ea290b.png)
> 
> After this, i found those headless services in `istioctl pc endpoints` and i can request them successfully in the mesh.

@suninuni 

Can you tell me how to change envvar?

Or you can tell me the links.

**Comment by suninuni** [comment] 2020-07-16 01:59
> > @4qv907rtet5r @jshum2479 @so-jelly
> > I resolved my problem by set `PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES` as `true` and `PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS` as `false` in istiod which in version 1.6.5.
> > I found them in https://istio.io/latest/docs/reference/commands/pilot-agent/#envvars
> > ![image](https://user-images.githubusercontent.com/7345529/87520062-07c5b880-c6b5-11ea-895f-3f2ef4ea290b.png)
> > After this, i found those headless services in `istioctl pc endpoints` and i can request them successfully in the mesh.
> 
> @suninuni
> 
> Can you tell me how to change envvar?
> 
> Or you can tell me the links.

https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec

You can change those envs in your IstioOperator file and the path is `spec/components/pilot/k8s/env`.

**Comment by 4qv907rtet5r** [comment] 2020-07-16 02:43
> https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec
> 
> You can change those envs in your IstioOperator file and the path is `spec/components/pilot/k8s/env`. You can also edit your istiod deployment and add those envs for test

@suninuni 

`istioctl install --set values.pilot.env.PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES=true --set values.pilot.env.PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS=false`

I tried it and it is the same result as before.

thanks!

**Comment by hzxuzhonghu** [comment] 2020-10-10 02:49
@4qv907rtet5r @jshum2479 @so-jelly Any feedback on latest version?

**Comment by jshum2479** [comment] 2020-10-10 11:47
I tested 1.7.3 and it works fine.

**Comment by hzxuzhonghu** [comment] 2020-10-12 01:13
Thanks for the feedback

**Comment by hobbytp** [comment] 2020-10-14 03:19
@hzxuzhonghu @incfly @howardjohn can I understand that the correct behavious/configuration are as below when mtls.auto=true, mtls.enabled=false in global, please help to confirm if it is what we want.

1. not need to update env PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES (false as default) and PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS (true as default)
2. not need to update headless service port name as <protocol>-xxx (for Iuse legacy service which does not follow istio port name requirement.)

3. when headless service WITH sidecar injected, 
   3.1 if wants to use plaintext between client and headless service, need to setup PeerAuthentication with "mtls.mode: DISABLE" or DR with tls.mode: DISABLE
   3.2 if want to use mtls, need to setup DR with ISTIO_MUTUAL
4. when headless service WITHOUT sidecar injected.
  4.1 if want to use plaintext between client and headless service, need to setup PeerAuthentication with "mtls.mode: DISABLE" or DR with tls.mode: DISABLE
  4.2 for headless service is not in-mesh, so not in-mesh mtls here. 

My team tests case 3.1 with DR(DISABLE) in 1.7.2 with headless service is kafka, and case 4.2 with DR (ISTIO_MUTUAL) and headless service is database in 1.6.7, and both work. 


The PeerAuthentication and DR configuration from hzxuzhonghu I list as below for reference only.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: xxxx
spec:
  host: headless-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL/DISABLE
```

```yaml
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  selector:
    matchLabels:
      app: headlessxxx
      version: v1
  mtls:
    mode: DISABLE
```

**Comment by hobbytp** [comment] 2020-10-23 01:02
@howardjohn can we add a doc to summary the headless service specific behaviors and configuration in different configuration?

**Comment by howardjohn** [comment] 2020-11-24 22:27
Since 1.7, headless+auto mtls should work in all cases.

https://github.com/istio/istio.io/issues/8393 tracks better docs
1.6 is EOL https://istio.io/latest/news/support/announcing-1.6-eol/

So I think there is no action left here

**Closed by howardjohn** 2020-11-24 22:27 UTC
Labels: area/networking
