### ISSUE TITLE
[helm] Change documentation to pull the stable release?

### ISSUE THREAD

**Issue by YingjunHu** [istio/istio#12889] opened 2019-03-28 18:18 UTC
**Describe the feature request**
I want to have the documentation about how to pull the stable helm chart release. 

Right now the readme in any branch or tag (such as master and release 1.1.0 or 1.1.1 that I checked) are all adding the daily-release repository to helm. `https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/README.md#L110`

I'm not sure if I missed the stable release somewhere, please correct me if I'm wrong.

What I would expect and the way I found it working is something like `helm fetch --untar  https://storage.googleapis.com/istio-release/releases/1.1.1/charts/istio-1.1.1.tgz` which will fetch the certain stable release. Or it's totally fine if we can get a repo that only stores these stable releases.

**Describe alternatives you've considered**

**Additional context**
{{ Add any other context about the feature request here }}

**Comment by howardjohn** [comment] 2019-03-28 22:49
Install documentation is kept at https://istio.io/docs/setup/kubernetes/install/, I don't think we want to maintain two sets of docs and try to keep them up to date with every release, etc.

That being said, we do have the readme you linked, and it is outdated in many ways, so we should probably clean that up

**Comment by YingjunHu** [comment] 2019-03-28 23:12
@howardjohn Thanks for the clarification. I understand that we wanna keep the documentation in istio.io website. But what I'm thinking is that it will be better if developers can download the charts easier.

The best documentation I can find to install istio using helm is `https://istio.io/docs/setup/kubernetes/download/`. There we can know the shell command to download the whole istio repo, and helm charts is under `install` folder.

But since there's actually a way that we can download the pacted charts directly by using the url I mentioned before, would that be a good idea to mention this somewhere? And what if we want to set istio as a dependency to another chart? We won't be able to set repository url in `requirements.yaml` if we don't know the repo that contains the istio chart.

I know maintaining the helm chart (and doc) might not be a main job for you guys but I would really appreciate if we can address this issue so that others can also know how to pull a stable release image from the official repo.

**Comment by howardjohn** [comment] 2019-03-28 23:23
Ok so the problem is that we don't have documentation for the repo essentially?

We are working on adding this to the docs. In the mean time, the Helm repos are linked at https://github.com/istio/istio/releases under "Helm Chart Index"

**Comment by YingjunHu** [comment] 2019-03-28 23:27
Well the issue referenced is exactly what I want. Will wait for it to be fixed. Thank you!

**Comment by howardjohn** [comment] 2019-03-28 23:28
I'll close this in favor of that issue then

**Closed by howardjohn** 2019-03-28 23:28 UTC
