### ISSUE TITLE
Support headless services with auth

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1373] opened 2017-11-03 22:26 UTC
@kyessenov commented on [Tue Sep 12 2017](https://github.com/istio/old_pilot_repo/issues/1253)

Tracking issue to support mTLS auto-upgrade for headless services.

---

@rshriram commented on [Tue Sep 12 2017](https://github.com/istio/old_pilot_repo/issues/1253#issuecomment-328971370)

Currently auth is automatically disabled for headless services.. see #1249

**Comment by selmanj** [comment] 2018-02-22 16:49
Any upcoming plans on adding support for headless services? Using a StatefulSet requires use of a headless service.

Right now the experience is subpar as well - rather than getting any error/log messages anywhere, the connection is merely dropped.

**Comment by andraxylia** [comment] 2018-05-18 18:21
Duplicate of #1277

**Closed by andraxylia** 2018-05-18 18:21 UTC
Labels: area/networking
