### ISSUE TITLE
Virtual Service Add HeaderOperation Not working 

### ISSUE THREAD

**Issue by dominicqi** [istio/istio#23847] opened 2020-05-14 07:50 UTC
**Bug description**
Use Add HeaderOperation  want append value vs comma but it add a same name new header.

**Steps to reproduce the bug**
1. one echoserver pod `gcr.io/google_containers/echoserver:1.0`
2. one curl pod .
3. VirtualService 

> apiVersion: networking.istio.io/v1beta1
> kind: VirtualService
> metadata:
>   name: echoserver
>   namespace: bookinfo
> spec:
>   hosts:
>     - echoserver
>   http:
>     - route:
>         - destination:
>             host: echoserver
>           headers:
>             request:
>               add:
>                 test: test22

4. curl in curl pods 
    

> [ root@curl-deployment-7bcfc87447-hp64g:/ ]$ curl -v -H "test:testm" echoserver
> > GET / HTTP/1.1
> > User-Agent: curl/7.35.0
> > Host: echoserver
> > Accept: */*
> > test:testm
> > 
> < HTTP/1.1 200 OK
> < date: Thu, 14 May 2020 07:39:54 GMT
> < content-type: text/plain
> < server: envoy
> < x-envoy-upstream-service-time: 1
> < transfer-encoding: chunked
> < 
> 
> 
> Hostname: echoserver-d9c8b99cd-m9v8z
> 
> Pod Information:
> 	-no pod information available-
> 
> Server values:
> 	server_version=nginx: 1.14.2 - lua: 10015
> 
> Request Information:
> 	client_address=127.0.0.1
> 	method=GET
> 	real path=/
> 	query=
> 	request_version=1.1
> 	request_scheme=http
> 	request_uri=http://echoserver:8080/
> 
> Request Headers:
> 	accept=*/*
> 	content-length=0
> 	host=echoserver
> 	test=testm
> 	test=test22
> 	user-agent=curl/7.35.0
> 	x-b3-parentspanid=375365b511541bb4
> 	x-b3-sampled=0
> 	x-b3-spanid=5a7cc6dc343ed8f2
> 	x-b3-traceid=13ffa51a25f358e3375365b511541bb4
> 	x-envoy-attempt-count=1
> 	x-forwarded-client-cert=By=spiffe://cluster.local/ns/bookinfo/sa/default;Hash=551b305a9d8898808ef8c04e7ff155e40d00665495ec2509c01e3ab063cb1d88;Subject=&quot;&quot;;URI=spiffe://cluster.local/ns/bookinfo/sa/default
> 	x-forwarded-proto=http
> 	x-request-id=0180c4d2-beca-45db-9da3-4ff4976c1a2d
> 
> Request Body:
> 	-no body in request-

5.  here is the envoy debug log 

> 2020-05-14T07:44:34.428682Z     debug   envoy router    

> [external/envoy/source/common/router/router.cc:634] [C3487][S2797866053039229206] router decoding headers:
> ':authority', 'echoserver'
> ':path', '/'
> ':method', 'GET'
> ':scheme', 'https'
> 'user-agent', 'curl/7.35.0'
> 'accept', '*/*'
> 'test', 'testm'
> 'x-forwarded-proto', 'http'
> 'x-request-id', '456d504a-3a08-456f-8124-e987068d24a7'
> 'x-envoy-decorator-operation', 'echoserver.bookinfo.svc.cluster.local:80/*'
> 'x-envoy-peer-metadata', 'ChoKCkNMVVNURVJfSUQSDBoKS3ViZXJuZXRlcwodCgxJTlNUQU5DRV9JUFMSDRoLMTcyLjE3LjAuMTAK4wEKBkxBQkVMUxLYASrVAQoQCgNhcHASCRoHY3VybHBvZAoZCgxpc3Rpby5pby9yZXYSCRoHZGVmYXVsdAohChFwb2QtdGVtcGxhdGUtaGFzaBIMGgo3YmNmYzg3NDQ3CiQKGXNlY3VyaXR5LmlzdGlvLmlvL3Rsc01vZG
> USBxoFaXN0aW8KLAofc2VydmljZS5pc3Rpby5pby9jYW5vbmljYWwtbmFtZRIJGgdjdXJscG9kCi8KI3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLXJldmlzaW9uEggaBmxhdGVzdAoaCgdNRVNIX0lEEg8aDWNsdXN0ZXIubG9jYWwKKgoETkFNRRIiGiBjdXJsLWRlcGxveW1lbnQtN2JjZmM4NzQ0Ny1ocDY0ZwoXCglOQU1FU1BBQ0USChoIYm9va2luZm8KVA
> oFT1dORVISSxpJa3ViZXJuZXRlczovL2FwaXMvYXBwcy92MS9uYW1lc3BhY2VzL2Jvb2tpbmZvL2RlcGxveW1lbnRzL2N1cmwtZGVwbG95bWVudAocCg9TRVJWSUNFX0FDQ09VTlQSCRoHZGVmYXVsdAoiCg1XT1JLTE9BRF9OQU1FEhEaD2N1cmwtZGVwbG95bWVudA=='
> 'x-envoy-peer-metadata-id', 'sidecar~172.17.0.10~curl-deployment-7bcfc87447-hp64g.bookinfo~bookinfo.svc.cluster.local'
> 'x-envoy-attempt-count', '1'
> 'x-b3-traceid', '783251e0ac171c1c6805625a999d5fb7'
> 'x-b3-spanid', '6805625a999d5fb7'
> 'x-b3-sampled', '0'
> 'test', 'test22'

6. I see the envoy config 

> "requestHeadersToAdd": [
>                                             {
>                                                 "header": {
>                                                     "key": "test",
>                                                     "value": "test22"
>                                                 },
>                                                 "append": true
>                                             }
>                                         ]

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
 1.5.1 1.5.2 1.6.0-beta1.   
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
> istioctl version
> client version: 1.5.2
> control plane version: 1.6.0-beta.1
> data plane version: 1.6.0-beta.1 (10 proxies)

**How was Istio installed?**
Istioctl 
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by dominicqi** [comment] 2020-05-19 17:04
Any one help ?

**Comment by howardjohn** [comment] 2020-07-28 20:55
@dominicqi I don't understand the issue. Your VS says to add header `test: test22`. 

If I send request I get `"Test": "test22",`. If I already had test header, I get `"Test": "foo,test22"`.

This meets my expectations based on https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#:~:text=Multiple%20message%2Dheader%20fields%20with,%5Bi.e.%2C%20%23(values)%5D.

What is your desired behavior?

**Comment by howardjohn** [comment] 2020-08-24 22:52
@dominicqi any more info?

**Comment by howardjohn** [comment] 2020-09-12 00:18
Closing as this seems working as intended and we don't have additional info. thanks!

**Closed by howardjohn** 2020-09-12 00:18 UTC
Labels: area/networking, kind/need more info, lifecycle/needs-triage
