### ISSUE TITLE
Create convenience tool to convert v1alpha1 configs to v1alpha3

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#3621] opened 2018-02-20 21:48 UTC
Create a tool to convert v1alpha1 configs to v1alpha2 configs to make v1alpha1 deprecation less painful. 

Considerations:
1. For convenience only. Should be able to handle the majority of configs, but not all edge cases. The tool should warn the user in these cases ideally.
1. Not all sets of v1alpha1 config can be converted perfectly. Warn when this happens.
1. Output should just be a _starting point_ for the v1alpha3 configs. Users will probably want to clean up and rename generated names etc.

Part of https://github.com/istio/istio/issues/1925

**Comment by ijsnellf** [comment] 2018-02-20 21:49
cc @rshriram

**Comment by ldemailly** [comment] 2018-02-20 22:22
that'd be awesome ! and tbh required for just before whenever we stop supporting alpha1

**Comment by esnible** [comment] 2018-04-20 17:37
I tried to convert https://github.com/retroryan/istio-workshop/blob/master/guestbook/route-rule-80-20.yaml using `istioctl experimental convert-networking-config` and ran into two problems.

First the output RouteRule is incorrect because the subset name is invalid because it contains a period:

```
Error: 2 errors occurred:

* output config(s) are invalid: subnet name is invalid: version-1.0
* output config(s) are invalid: subnet name is invalid: version-2.0
```

Even if that is fixed a VirtualService cannot represent the old RouteRule because it refers to an undefined subset.  To make it work we need something like the following to be generated in addition to the VirtualService.

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-destination
spec:
  host: reviews
  subsets:
  - name: version-v1
    labels:
      version: v1
  - name: version-v2
    labels:
      version: v2
```

**Comment by ijsnellf** [comment] 2018-04-20 18:10
@esnible: Yeah, the converter tool does not create missing subsets right now. That's why this issue is still open: https://github.com/istio/istio/blob/master/istioctl/cmd/istioctl/convert/cmd.go#L134

The errors you hit are a bug. The tool is not doing enough to make sure that the subset name is a dns1123 label: https://github.com/istio/istio/blob/master/istioctl/pkg/convert/route.go#L352 Thanks for reporting that!

**Comment by esnible** [comment] 2018-04-20 18:40
@ldemailly I will test the tool against our V1 tests.

@ijsnellf 
I ran the tool against the rest of the .yaml in https://github.com/retroryan/istio-workshop/tree/master/guestbook

The tool complained when run against non-Istio Kubernetes things, like Service, as expected.

The tool complained when run against config.istio.io/v1alpha2 kinds, such as _metric_.  I would have expected the tool to return either return nothing or the input in those cases.  Not a big problem.

I found two gaps:

_destination-rule-helloworld.yaml_
```
Error: 1 error occurred:
* output config(s) are invalid: cannot cast to virtual service
```

_route-rule-retry.yaml_
```
Error: configuration is invalid: 1 error occurred:
* perTryTimeout invalid:  duration: nil Duration
```

You can reproduce my test by doing `git clone https://github.com/retroryan/istio-workshop.git`, `cd istio-workshop/guestbook`, `for file in *.yaml; do    echo "$file" >> results.out && istioctl experimental convert-networking-config -f "$file" 2>> results.out; done`

**Comment by esnible** [comment] 2018-04-30 15:06
I will be creating a new PR for Ingress resources to support #5097 at Lin Sun's request.  The new PR will convert Ingress to Gateway + Virtual Service.

**Comment by esnible** [comment] 2018-06-12 12:34
Closing because I believe we have covered all of the types we expect to cover.

**Closed by esnible** 2018-06-12 12:34 UTC
Labels: area/config, kind/enhancement, kind/needed for 1.0
