### ISSUE TITLE
Istio does not route traffic correctly if it's deployed in a namespace other than istio-system

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#23401] opened 2020-04-29 22:44 UTC
**Bug description**

When I deploy Istio to a namespace which is not `istio-system`, It is unable to route traffic from the ingress-gateway to the application pods situated in another namespace. It's only able to route traffic when the application pods are in the same namespace as that of the istio control plane

cc @GregHanson who has confirmed that it is reproducible

**Expected behaviour**
It should route traffic to the bookinfo pods in the default namespace as suggested by the tutorial [here](https://istio.io/docs/examples/bookinfo/).

Please note that if I deploy Istio in `istio-system`, it works as expected. It's able to route traffic from Ingress-gateway to the bookinfo pods in the default namespace.

**Steps to reproduce the bug**

Deploy Istio to a custom namespace with the following`istioctl` command

```
istioctl manifest apply --set components.cni.enabled=true --set values.global.istioNamespace=<custom_ns> --set values.global.configNamespace=<custom_ns> --set values.global.prometheusNamespace=<custom_ns>
```

Next, I deploy the Bookinfo application, as directed by the steps [here](https://istio.io/docs/examples/bookinfo/).

When I try to hit the `productpage` endpoint via the ingress-gateway LB, the request never goes through. On enabling the envoyAccessLogs, I found instances of `400`s 

```
GET /productpage HTTP/1.1" 400 - "-" "-" 0 0 24 4 "10.2.8.52" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0" "d1f05cd7-2bac-48bd-abef-f06a97dc2014" "aff84ac935eb447afa9b1f649a782b77-1672155039.us-east-1.elb.amazonaws.com" "10.244.65.85:9080" outbound|9080||productpage.default.svc.cluster.local 10.244.65.105:60994 10.244.65.105:80 10.2.8.52:5176 - -
[2020-04-28T23:02:50.983Z] "GET /productpage HTTP/1.1" 400 - "-" "-" 0 0 0 0 "10.2.8.52" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0" "218d05a1-7627-4d63-a0e6-a46e87a9bf68" "aff84ac935eb447afa9b1f649a782b77-1672155039.us-east-1.elb.amazonaws.com" "10.244.65.85:9080" outbound|9080||productpage.default.svc.cluster.local 10.244.65.105:32784 10.244.65.105:80 10.2.8.52:5176 - -
[2020-04-28T23:02:52.515Z] "GET /productpage HTTP/1.1" 400 - "-" "-" 0 0 0 0 "10.2.8.52" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0" "29d24187-43fa-4c61-a3fc-9a4b7e07a20f" "aff84ac935eb447afa9b1f649a782b77-1672155039.us-east-1.elb.amazonaws.com" "10.244.65.85:9080" outbound|9080||productpage.default.svc.cluster.local 10.244.65.105:32802 10.244.65.105:80 10.2.8.52:5176 - -
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

v1.5.1

**How was Istio installed?**
`Istioctl manifest apply`

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by GregHanson** [comment] 2020-04-29 23:17
verified the problem exists in 1.6.0-beta branch as well

**Comment by GregHanson** [comment] 2020-04-29 23:42
ingress gateway access log:
```
[2020-04-29T23:26:25.517Z] "GET /productpage HTTP/1.1" 400 - "-" "-" 0 0 4 2 "10.221.41.12" "curl/7.64.1" "d8386fa3-d655-4e42-9433-3e6d0234a229" "150.238.42.227" "172.30.90.156:9080" outbound|9080||productpage.default.svc.cluster.local 172.30.90.157:42750 172.30.90.157:8080 10.221.41.12:57155 - -
```

trace level logs of ingress gateway on 400
https://gist.github.com/GregHanson/2427b6c49a513bfe3b2c8727c492e262

listeners:
```
istioctl proxy-config listener istio-ingressgateway-67c89cfdd8-nqcd9.test
ADDRESS     PORT      TYPE
0.0.0.0     8080      HTTP
0.0.0.0     15090     HTTP
```
https://gist.github.com/GregHanson/2a4a86cd619b321e58dcafb8c1d76a08

routes:
https://gist.github.com/GregHanson/c1ebf34801af9ae033a6fe8d2dc2d14a

clusters:
https://gist.github.com/GregHanson/92acfbb87a3a492422bd1f3d0228faa9

**Comment by GregHanson** [comment] 2020-04-29 23:49
ingressgateway can reach productpage directly via curl:
```
k exec -it -n test istio-ingressgateway-67c89cfdd8-nqcd9 -- curl productpage.default.svc.cluster.local:9080/productpage
```

and service to service communication works for booking services:
```
kubectl exec -it "$(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}')" -c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>"
```

bookinfo Gateway and VirtualService are the only istio resources in effect:
```
k get virtualservices,destinationrules,peerauthentication,gateways --all-namespaces
NAMESPACE   NAME                                          GATEWAYS             HOSTS   AGE
default     virtualservice.networking.istio.io/bookinfo   [bookinfo-gateway]   [*]     101m

NAMESPACE   NAME                                           AGE
default     gateway.networking.istio.io/bookinfo-gateway   101m
```

Seems like a port configuration issue on the ingress gateway but I can't see the problem in the config dumps

**Comment by howardjohn** [comment] 2020-04-29 23:59
envoy logs:
```
[Envoy (Epoch 0)] [2020-04-29 23:58:37.915][31][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:176] [C72] handshake complete
[Envoy (Epoch 0)] [2020-04-29 23:58:37.915][31][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:278] [C72] dispatch error: http/1.1 protocol error: HPE_INVALID_METHOD
[Envoy (Epoch 0)] [2020-04-29 23:58:37.915][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:101] [C72] closing data_to_write=66 type=2

```

btw to reproduce this I had to fix the webhook config - did you guys both do something?

**Comment by tariq1890** [comment] 2020-04-30 00:03
Oh yes, I did do that. A Kubectl deploy edit to point to the right MWC.

Looks like this fix isn't included yet: https://github.com/istio/istio/pull/22828

**Comment by howardjohn** [comment] 2020-04-30 00:17
I think this is due to telemetry v2, going to eat dinner but will update soon more info. tl;dr `kubectl delete envoyfilter --all` will fix it (not the proper fix though)

**Comment by GregHanson** [comment] 2020-04-30 00:19
@howardjohn I am using the 1.6.0-beta.0 release.  Yes, `kubectl delete EnvoyFilter --all -n <control_plan_ns>` does resolve the issue

**Comment by tariq1890** [comment] 2020-04-30 00:26
+1 I can confirm that deleting the envoy filters solves the issue

**Comment by howardjohn** [comment] 2020-04-30 00:37
The problem is that the envoyfilters only apply to the gateway, not the `default` ns. Thats why it works when they are in the same namespace as well, since its scoped to that namespace. The reasoning is that Istio has a concept of "root" namespace where (some) configs there are treated as global objects. Its not the best documented feature there is... Basically its istio-system by default, so they envoyfilter apply to all namespaces. However, in this case the envoyfilters are now deployed to <my-ns>, while the rootnamespace remains istio-system. The fix would be to set `--set meshConfig.rootNamespace=my-ns`.

**Comment by tariq1890** [comment] 2020-04-30 00:41
https://github.com/istio/istio/pull/23407

**Comment by mandarjog** [comment] 2020-04-30 00:52
@GregHanson were you able to reproduce it with 1.6 telemetry v2?

**Comment by howardjohn** [comment] 2020-04-30 00:54
I can try on master

**Comment by howardjohn** [comment] 2020-04-30 00:57
On master I see the same

**Comment by mandarjog** [comment] 2020-04-30 01:41
@gargnupur  The client `advertised that it supports alpn, but did not actually support MX.`
Why is it inserted in a http filterchain?

```
2020-04-29T23:26:25.521412Z	trace	envoy filter	[src/envoy/tcp/metadata_exchange/metadata_exchange.cc:230] Alpn Protocol Matched. Magic not matched.
2020-04-29T23:26:25.521452Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:470] [C18] parsing 66 bytes
2020-04-29T23:26:25.521485Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:672] [C18] message begin
2020-04-29T23:26:25.521511Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C18] completed header: key=content-length value=0
2020-04-29T23:26:25.521562Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:573] [C18] onHeadersCompleteBase
2020-04-29T23:26:25.521606Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:433] [C18] completed header: key=connection value=close
2020-04-29T23:26:25.521655Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:986] [C18] Client: onHeadersComplete size=2
2020-04-29T23:26:25.521678Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:649] [C18] message complete
2020-04-29T23:26:25.521713Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:1019] [C18] message complete
2020-04-29T23:26:25.521752Z	debug	envoy client	[external/envoy/source/common/http/codec_client.cc:104] [C18] response complete
2020-04-29T23:26:25.521800Z	trace	envoy main	[external/envoy/source/common/event/dispatcher_impl.cc:163] item added to deferred deletion list (size=1)
2020-04-29T23:26:25.521843Z	debug	envoy router	[external/envoy/source/common/router/router.cc:1149] [C17][S15063866600729796806] upstream headers complete: end_stream=true
2020-04-29T23:26:25.521910Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1565] [C17][S15063866600729796806] encode headers called: filter=0x5618eea6b860 status=0
2020-04-29T23:26:25.521950Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1565] [C17][S15063866600729796806] encode headers called: filter=0x5618eee4dea0 status=0
2020-04-29T23:26:25.521970Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1565] [C17][S15063866600729796806] encode headers called: filter=0x5618eea515e0 status=0
2020-04-29T23:26:25.522030Z	trace	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1565] [C17][S15063866600729796806] encode headers called: filter=0x5618eea580a0 status=0
2020-04-29T23:26:25.522082Z	debug	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:1706] [C17][S15063866600729796806] encoding headers via codec (end_stream=true):
':status', '400'
'content-length', '0'
'x-envoy-upstream-service-time', '2'
'date', 'Wed, 29 Apr 2020 23:26:25 GMT'
'server', 'istio-envoy'
```

**Comment by gargnupur** [comment] 2020-04-30 05:55
For Http Filterchain, "istio-peer-exchange" protocol should not be added in alpn protocols.

@yxue : https://sourcegraph.com/github.com/istio/istio@master/-/blob/pilot/pkg/networking/core/v1alpha3/cluster.go#L1071:12, could this be adding "istio-peer-exchange" alpn for Http filterchains too?

**Comment by sdake** [comment] 2020-04-30 11:16
Appears to be a legitimate bug requiring some resolution. I marked as a P0, although this feels like a blocker.

Cheers
-steve

**Comment by GregHanson** [comment] 2020-04-30 15:11
What are the expected istioctl flags/settings for installing istio in a different namespace with demo or default profile?
```
--set values.global.istioNamespace=<custom_ns> 
--set values.global.configNamespace=<custom_ns> 
--set meshConfig.rootNamespace=<custom_ns>
```

**Comment by mandarjog** [comment] 2020-04-30 15:26
@gargnupur are you able to reproduce the issue? You can get config dump and verify if it is being added.

**Comment by tariq1890** [comment] 2020-04-30 22:10
Any updates on this? @mandarjog @gargnupur

**Comment by gargnupur** [comment] 2020-04-30 22:14
@tariq1890 : I am working to get a local repro of this on istio/istio to be able to debug this easily and will update the bug as I have more info...

As of now here is the update we have:
It's happening because http traffic is negotiating TCP Alpn (istio-peer-exchange) and that should not be happening...
Client has mxc filter and server does not because of which client sends metadata exchange information and server does not understand it and fails with codec error 400.

**Comment by tariq1890** [comment] 2020-05-07 19:59
Can this issue be closed now?

**Comment by gargnupur** [comment] 2020-05-07 20:43
Yes.. closing.. please reopen if you see any other issues..

**Closed by gargnupur** 2020-05-07 20:43 UTC
Labels: area/config, area/environments, area/networking, area/policies and telemetry, community/testing days, testing/day-1
