### ISSUE TITLE
Istio release `1.7.3` is not a part of `release-1.7` branch

### ISSUE THREAD

**Issue by yskopets** [istio/istio#27698] opened 2020-10-02 16:31 UTC
**Bug description**

* Istio release `1.7.3` is not a part of `release-1.7` branch

**Expected behavior**

* Changes of the Istio release `1.7.3` should be in the `release-1.7` branch to avoid losing them in the next patch release

**Comment by howardjohn** [comment] 2020-10-02 18:37
Our security release process (https://docs.google.com/document/d/19qf0-0GIopEZZWuG-lj8_VpyQF4N9nIKXiZgcJHwBRM/) has us pushing to a dedicated branch then merging into the main (release-1.7) branch. We are still in progress on the latter part as the PRs take some time to go through the repos and tests

**Comment by howardjohn** [comment] 2020-10-20 18:59
Closing as this is working as intended and the change has propogated to release-1.7 now. thanks.,

**Closed by howardjohn** 2020-10-20 18:59 UTC
