### ISSUE TITLE
bug in release-0.2 bot setup

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1139] opened 2017-10-14 19:52 UTC
the bot keep trying to and successfully merging auth changes into release-0.2 while there has been no such changes

https://github.com/istio/istio/commits/release-0.2 has 2 that went through 
for instance
https://github.com/istio/istio/commit/6b3c74568fe241dfca8f8d479a6b345d519591d8

https://github.com/istio/auth/tree/release-0.2
last change was 12 days ago

cc @ayj who is trying to make a 0.2 release and will need to make sure the SHAs/tags are all from the actual release-0.2 branches unlike what is now in istio/istio release-0.2 for CA

**Comment by yutongz** [comment] 2017-10-15 00:45
Yeah, it tried to get new changes from auth:master to istio:release-0.2. Thanks for pointing it out. Well I don't know about release branch super well, but I suppose release branches should only look at release branches right? If so, I can work on this fix.

**Comment by ldemailly** [comment] 2017-10-15 03:19
Yes release-X.Y branch should only get updates from same name branch in other repos

strangely it seems it wasn't doing it wrong for pilot and mixer, only auth that I noticed?

**Comment by yutongz** [comment] 2017-10-15 05:03
Well, not really, I noticed in https://github.com/istio/istio/pull/1132, it updated almost all repos. And actually it kept doing this kind of thing [here](https://github.com/istio/istio/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20is%3Aunmerged%20base%3Arelease-0.2%20)  after https://github.com/istio/test-infra/pull/537, but they all failed until Jason fixed linter in release-0.2 branch https://github.com/istio/istio/pull/1129

The issue is in istio/istio:release-0.2 branch, it still looks at head SHA of its dependencies from their "stable" branch. It should look at release-0.2 like pilot/mixer. And I am wondering if we should have "release-0.2-stable"

**Comment by yutongz** [comment] 2017-10-15 05:10
https://github.com/istio/istio/pull/1140

**Comment by ldemailly** [comment] 2017-10-15 05:24
can the bot use the branch name implicitly ? it seems error prone to have to update N files * M branches each time, we're bound to forget something somewhere

(maybe it's nice to have the option to override the branch but by default it should be the same branch as the target branch/configured branch)

**Comment by yutongz** [comment] 2017-10-15 05:33
/assign @chxchx 
We should take current branch as default except if current branch is "master", in that case we look at "stable".

Actually we should have release-0.2-stable. Currently postsubmit in release branch is partly broken  https://k8s-gubernator.appspot.com/build/istio-prow/auth-postsubmit/66/?log#log. It doesn't actually make fast-forward.

**Comment by ldemailly** [comment] 2017-10-15 05:36
I think for the release-branch we don't need -stable as checkins are carefully put in - it'd be weird for the postsubmit to fail when presubmit tests passes (though clearly having said it, it will now happen ;-) )

**Comment by yutongz** [comment] 2017-10-15 05:40
Well, postsubmit is meant to catch bugs brought by direct/force merge. If we can make sure no one does that on changes about actual code, then I guess it's fine.

**Comment by yutongz** [comment] 2017-10-27 00:11
/close
Close this issue since I fixed the release-0.2 branch and in the future, flat build/repo tool is going to handle dependency.

**Closed by yutongz** 2017-10-27 00:11 UTC
Labels: automated-release, test-infra
