### ISSUE TITLE
istio-mixer unable to start due to statsd mapping file can't be found?

### ISSUE THREAD

**Issue by jeffwji** [istio/istio#1935] opened 2017-11-30 16:46 UTC
Hi, I'm deploying istio version 0.2.12 to my Kubernetes cluster following by this instruction: https://istio.io/docs/setup/kubernetes/quick-start.html#installation-steps, but encountering error with mixer pod which is unable to be fully started. 

The error is when I check the pods status:

```
 # kubectl -n istio-system get pods
 NAME                                READY     STATUS             RESTARTS   AGE
 istio-ca-57f9bd7ddb-cbbj7           1/1       Running            1          19d
 istio-egress-6c6b84cd5d-bpxsh       1/1       Running            1          19d
 istio-ingress-79cf84458b-hkzx2      1/1       Running            1          19d
 istio-initializer-865bc594c-cbj4r   1/1       Running            0          19d
 istio-mixer-6fdc6784c7-mtl5d        1/2       CrashLoopBackOff   117        19d
 istio-pilot-5f4865659b-z4ldh        1/1       Running            0          19d
```

```
# kubectl -n istio-system describe istio-mixer-6fdc6784c7-mtl5d
...
      Message:   oci runtime error: container_linux.go:265: starting container process caused "exec: \"-statsd.mapping-config=/etc/statsd/mapping.conf\": stat -statsd.mapping-config=/etc/statsd/mapping.conf: no such file or directory"
...
```

I'm not sure how statsd works, but it kinds like it trying to load the mapping configuration from somewhere, what I should do to let it able to find it?

**Comment by jeffwji** [comment] 2017-11-30 19:17
Checked with `istio.yaml`, I find the volume is mounted from `istio-mixer` configMap, and it has been created already with empty content
```
# kubectl -n istio-system describe cm/istio-mixer
Name:         istio-mixer
Namespace:    istio-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","data":{"mapping.conf":""},"kind":"ConfigMap","metadata":{"annotations":{},"name":"istio-mixer","namespace":"istio-system"}}


Data
====
mapping.conf:
----
```
Not sure what this means for statsd-exporter

**Comment by douglas-reid** [comment] 2018-01-22 22:42
I'm not able to reproduce. I'm closing for now. Please re-open if you are still not able to start Mixer pods.

**Closed by douglas-reid** 2018-01-22 22:42 UTC
Labels: mixer, policies-and-telemetry

**Comment by jeffwji** [comment] 2018-02-13 17:13
I dumped the configuration and modify liveness value and then forced pushing to replace, but pod status now is fixing on "Pending"...
