### ISSUE TITLE
MongoDB HelmChart breaks with Istio

### ISSUE THREAD

**Issue by Gottox** [istio/istio#8443] opened 2018-09-03 13:17 UTC
**Describe the bug**
When installing the [official MongoDB helm chart](https://github.com/helm/charts/blob/master/stable/mongodb/Chart.yaml) with `helm install --name mongodb stable/mongodb`, the istio sidecar fails with a `permission denied` error message:
```
 kubectl logs mongodb-sec-enabled-64766bbcdd-mzpdk istio-init
+ iptables -t nat -N ISTIO_REDIRECT
Environment:
------------
ENVOY_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
INBOUND_CAPTURE_PORT=15001
PROXY_UID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=27017,
INBOUND_PORTS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=

iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
+ dump
+ iptables-save
iptables-save v1.6.0: Cannot initialize: Permission denied (you must be root)
```

**Expected behavior**
The expected behavior is that both the init container and the mongodb container start properly.

**Steps to reproduce the bug**`
1. Get a k8s cluster
2. Install helm as described [here](https://docs.helm.sh/using_helm/#installing-helm)
3. Install istio as described [here](https://istio.io/docs/setup/kubernetes/helm-install/)
4. Enable automatic sidecar injection as described [here](https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection)
5. `helm install stable/mongodb --name mongodb-sec-enabled`
6. Inspect the error with `kubectl logs mongodb-sec-enabled-XXX istio-init`

**Version**
Kubernetes:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"archive", BuildDate:"2018-08-25T18:33:09Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
helm:
```
$ helm version
Client: &version.Version{SemVer:"v2.9+unreleased", GitCommit:"", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```
Istio:
```
$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Is Istio Auth enabled or not?**
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system -f ~/src/cluster-setup/istio/values.yaml
cat ~/src/cluster-setup/istio/values.yaml
global:
  proxy:
    envoyStatsd:
      enabled: false
ingress:
  enabled: false
gateways:
  istio-ingressgateway:
    enabled: false
  istio-egressgateway:
    enabled: false
galley:
  enabled: false
sidecarjectorWebhook:
  enabled: true
mixer:
  enabled: false
prometheus:
  enabled: false
```

**Environment**
AWS, deployed with KOPS

**Cluster state**
Will generate on request. (New cluster needs to be set up, as I don't want to leak sensitive informations)

**Comment by jabdoa2** [comment] 2018-09-09 09:49
This seems to be related to the security context in the chart which changes the user id. The real question here seems to be: Are security contexts supposed to work with istio or not?

**Comment by Gottox** [comment] 2018-09-10 04:40
I guess that causes the issue. Unfortunatelly, mongodb with security context disabled may allow the istio-init container to finish successfully, but fails to spin up mongodb afterwards.

**Comment by marshall007** [comment] 2018-09-12 14:56
This is also the case with the official [`mariadb`](https://github.com/helm/charts/tree/master/stable/mariadb) chart (and any other containers that are configured to run as non-root). It would be great if we could get some clarification on the intended behavior here and/or a recommended workaround.

**Comment by swistaczek** [comment] 2018-10-10 08:42
@marshall007 did you tried to use changes introduced in #7488? I have the same issue related to SecurityContext and changes from above PR did not help, there is still error related to 'Permission denied' and iptables.

**Comment by tim-beatson** [comment] 2018-10-15 12:38
I too am seeing no resolution following https://github.com/istio/istio/pull/7488 . Would be grateful for at least a workaround asap

**Comment by tim-beatson** [comment] 2019-01-14 08:46
Thanks @thedodd, for me this was resolved by setting the relevant security context to allow the Istio sidecar to alter IP tables.

**Comment by thedodd** [comment] 2019-01-15 17:06
Just an update:
- I am running a k8s cluster on DO (which is excellent, btw).
- Standard istio installation in recommended namespace.
- Used the MongoDB helm chart to create a 3 node replicaset ... haven't had any issues.
- Replicaset was able to cluster and stay in sync, microservices haven't had any issues.

Figured I would just update this issue with my results.

**Comment by Bessonov** [comment] 2019-01-24 14:08
Have same issue with [stable/redis](https://github.com/helm/charts/tree/master/stable/redis) chart. Lets summarize issues together.

The issue https://github.com/istio/old_issues_repo/issues/316 propose 3 ways:
1. [Set securityContext to false](https://github.com/istio/old_issues_repo/issues/316#issuecomment-449626408), which is worked for me, but well, that's not great.
2. [To run as root](https://github.com/istio/old_issues_repo/issues/316#issuecomment-399612674). More or less same as above.
3. Use [istio cni](https://deploy-preview-2902--preliminary-istio.netlify.com/docs/setup/kubernetes/istio-cni-install/) should help [to resolve the issue](https://github.com/istio/old_issues_repo/issues/316#issuecomment-456071212). But it looks like that istio cni is in [pre-alpha stage](https://github.com/istio/cni).

[Discussion](https://github.com/bitnami/bitnami-docker-redis/issues/106) on bitnami.

**Comment by salehmashal** [comment] 2019-02-22 21:41
I have faced the same issue,  
The problem was the Istio sidecar proxy need to be privileged and has the "NET_ADMIN" capability,  but at the same time, the pod has securityContext to run with user 1001, which does not have the "NET_ADMIN" capability, which is making the istio sidecar to not be able to start.
 **The solution was moving the security context from the pod level to the container level.**

**Comment by howardjohn** [comment] 2019-05-22 16:21
@philrud is this fixed by https://github.com/istio/istio/pull/12708? If so we can close this

**Comment by philrud** [comment] 2019-05-22 18:28
@howardjohn this looks like the same issue so should be resolved now, but would be great if somebody could actually verify that particular chart before we close the issue

**Comment by howardjohn** [comment] 2019-05-29 17:27
I believe this is fixed. If not please open another issue or ping us to reopen this. Thanks

**Closed by howardjohn** 2019-05-29 17:27 UTC
Labels: area/environments
