### ISSUE TITLE
Set flag not taking effect in manifest generate

### ISSUE THREAD

**Issue by ostromart** [istio/istio#16305] opened 2019-08-15 16:49 UTC
It looks like the `--set` option doesn't always override the values in the specified input: file`default.yaml` is a copy of the built-in default profile spec. 

$ ~go/bin/mesh manifest generate -f default.yaml -s security.components.citadel.common.values.selfSigned=false | grep self-signed-ca
            - --self-signed-ca=true

**Comment by elfinhe** [comment] 2019-08-16 19:14
Root cause: set-value is mapped to .Values.citadel.selfSigned, but template (deployment.yaml) is using .Values.security.selfSigned.

**Comment by elfinhe** [comment] 2019-08-16 19:28
All templates are using Values.security rather than Values.citadel.

**Comment by elfinhe** [comment] 2019-08-16 19:53
TranslateHelmValues() is not translating to "security:"?

**Comment by elfinhe** [comment] 2019-08-16 22:04
There is another issue: the value passed from CLI is typed to string (i.e., "false") rather than boolean. The Helm Render engine will ignore it if the type does not match the corresponding path in chart.

**Comment by morvencao** [comment] 2019-08-18 06:48
```
# out/bin/mesh manifest generate -f data/profiles/default.yaml -s security.components.citadel.common.values.selfSigned=false | grep self-signed-ca
            - --self-signed-ca=false
```

Fixed in https://github.com/istio/operator/pull/208, closing...

**Closed by morvencao** 2019-08-18 06:48 UTC
Labels: area/environments/operator
