### ISSUE TITLE
istioctl install fails on windows

### ISSUE THREAD

**Issue by kkadir** [istio/istio#19020] opened 2019-11-17 01:00 UTC
**Bug description**
The `istioctl manifest apply --set profile=demo` fails with the following error message: `Could not configure logs: couldn't open sink "/dev/null": open /dev/null: The system cannot find the path specified.`

**Affected product area**

**Expected behavior**
The command should instaill istio as described in the [document](https://istio.io/docs/setup/getting-started/).

**Steps to reproduce the bug**
1. Download the **istio-1.4.0-win.zip** from the [releases page](https://github.com/istio/istio/releases/download/1.4.0/istio-1.4.0-win.zip).
2. Extract the content of the zipped file to C:\istio
3. Add the C:\istio\bin path to the environment paths.
4. Open the command-line as an administrator.
5. Issue the `istioctl manifest apply --set profile=demo` command.
6. Observe the error message: `Could not configure logs: couldn't open sink "/dev/null": open /dev/null: The system cannot find the path specified.`

**Version**
- **Istio:** 1.4.0
- **Docker Desktop:** Client/Engine 19.03.4
- **Kubectl:** Client/Server v1.14.7

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
- **OS Name:**  Microsoft Windows 10 Pro
- **OS Version:** 10.0.18362 N/A Build 18362
- **Docker Desktop:** Client/Engine 19.03.4
- **Kubectl:** Client/Server v1.14.7

**Comment by sfxworks** [comment] 2019-11-17 11:12
```
C:\Users\Samuel Walker>istioctl profile list
Could not configure logs: couldn't open sink "/dev/null": open /dev/null: The system cannot find the path specified.
```

This also happens if you just download the fresh binary and trying to list the available profiles. 

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

```
istioctl version
2019-11-17T11:09:06.753488Z     warn    will use `--remote=false` to retrieve version info due to `no Istio pods in namespace "istio-system"`
1.4.0
```

**Comment by howardjohn** [comment] 2019-11-17 15:16
Thanks for reporting this, I think I know the issue and we should be able to fix in 1.4.1

**Comment by Abrishges** [comment] 2019-11-18 20:25
@howardjohn when can I expect 1.4?

**Comment by howardjohn** [comment] 2019-11-18 20:28
2 weeks maybe? most folks are out for kubecon and Thanksgiving so slower than normal. The issue is windows specific by the way

**Comment by tomstreet** [comment] 2019-11-19 17:18
Using `--logtostderr` appears to work around the issue in the mean time.

**Comment by kkadir** [comment] 2019-11-21 11:30
> Using `--logtostderr` appears to work around the issue in the mean time.

With the suggested workaround, now I receive `error: chart metadata (Chart.yaml) missing`

**Comment by oguztekin** [comment] 2019-11-22 07:10
> > Using `--logtostderr` appears to work around the issue in the mean time.
> 
> With the suggested workaround, now I receive `error: chart metadata (Chart.yaml) missing`

I receive the same error too

**Comment by wxq851685279** [comment] 2019-11-25 03:29
On win10, I also encountered the same problem, how to solve

**Comment by magicFire** [comment] 2019-11-26 10:20
Is there a way to solve this problem before 1.4.1 temporarily?

**Comment by wxq851685279** [comment] 2019-11-27 01:59
> > > Using `--logtostderr` appears to work around the issue in the mean time.
> > 
> > 
> > With the suggested workaround, now I receive `error: chart metadata (Chart.yaml) missing`
> 
> I receive the same error too
istioctl manifest apply --set profile=demo --logtostderr
2019-11-27T01:59:08.541731Z     info    ReadProfileYAML for profile name: demo
2019-11-27T01:59:08.542729Z     info    Loading values from compiled in VFS at path profiles\demo.yaml
2019-11-27T01:59:08.543729Z     info    ReadProfileYAML for profile name: default
2019-11-27T01:59:08.544724Z     info    Loading values from compiled in VFS at path profiles\default.yaml
2019-11-27T01:59:08.769829Z     info    Failed to generate and apply manifests, error: failed to generate manifest: failed to create Istio control plane with spec:
default_namespace:"istio-system" traffic_management:<enabled:<BoolValue:<value:true > > components:<pilot:<enabled:<BoolValue:<value:true > > k8s:<env:<name:"POD_NAME" valueFrom:<fieldRef:<apiVersion:"v1" fieldPath:"metadata.name" > > > env:<name:"POD_NAMESPACE" valueFrom:<fieldRef:<apiVersion:"v1" fieldPath:"metadata.namespace" > > > env:<name:"GODEBUG" value:"gctrace=1" > env:<name:"PILOT_TRACE_SAMPLING" value:"100" > env:<name:"CONFIG_NAMESPACE" value:"istio-config" > hpa_spec:<scaleTargetRef:<kind:"Deployment" name:"istio-pilot" apiVersion:"apps/v1" > minReplicas:1 maxReplicas:5 metrics:<type:"Resource" resource:<name:"cpu" targetAverageUtilization:80 > > > readiness_probe:<httpGet:<path:"/ready" port:<IntOrString:<type:0 intVal:8080 > > > initialDelaySeconds:5 timeoutSeconds:5 periodSeconds:30 > resources:<requests:<key:"cpu" value:"10m" > requests:<key:"memory" value:"100Mi" > > strategy:<rollingUpdate:<maxUnavailable:<IntOrString:<type:1 strVal:"25%" > > maxSurge:<IntOrString:<type:1 strVal:"100%" > > > > > > > > policy:<enabled:<BoolValue:<value:true > > components:<policy:<enabled:<BoolValue:<value:true > > k8s:<env:<name:"POD_NAMESPACE" valueFrom:<fieldRef:<apiVersion:"v1" fieldPath:"metadata.namespace" > > > hpa_spec:<scaleTargetRef:<kind:"Deployment" name:"istio-policy" apiVersion:"apps/v1" > minReplicas:1 maxReplicas:5 metrics:<type:"Resource" resource:<name:"cpu" targetAverageUtilization:80 > > > resources:<requests:<key:"cpu" value:"10m" > requests:<key:"memory" value:"100Mi" > > strategy:<rollingUpdate:<maxUnavailable:<IntOrString:<type:1 strVal:"25%" > > maxSurge:<IntOrString:<type:1 strVal:"100%" > > > > > > > > telemetry:<enabled:<BoolValue:<value:true > > components:<telemetry:<enabled:<BoolValue:<value:true > > k8s:<env:<name:"POD_NAMESPACE" valueFrom:<fieldRef:<apiVersion:"v1" fieldPath:"metadata.namespace" > > > env:<name:"GOMAXPROCS" value:"6" > hpa_spec:<scaleTargetRef:<kind:"Deployment" name:"istio-telemetry" apiVersion:"apps/v1" > minReplicas:1 maxReplicas:5 metrics:<type:"Resource" resource:<name:"cpu" targetAverageUtilization:80 > > > replica_count:1 resources:<limits:<key:"cpu" value:"4800m" > limits:<key:"memory" value:"4G" > requests:<key:"cpu" value:"50m" > requests:<key:"memory" value:"100Mi" > > strategy:<rollingUpdate:<maxUnavailable:<IntOrString:<type:1 strVal:"25%" > > maxSurge:<IntOrString:<type:1 strVal:"100%" > > > > > > > > security:<enabled:<BoolValue:<value:true > > components:<citadel:<enabled:<BoolValue:<value:true > > k8s:<strategy:<rollingUpdate:<maxUnavailable:<IntOrString:<type:1 strVal:"25%" > > maxSurge:<IntOrString:<type:1 strVal:"100%" > > > > > > cert_manager:<enabled:<BoolValue:<> > > node_agent:<enabled:<BoolValue:<> > > > > config_management:<enabled:<BoolValue:<value:true > > components:<galley:<enabled:<BoolValue:<value:true > > k8s:<replica_count:1 resources:<requests:<key:"cpu" value:"100m" > > strategy:<rollingUpdate:<maxUnavailable:<IntOrString:<type:1 strVal:"25%" > > maxSurge:<IntOrString:<type:1 strVal:"100%" > > > > > > > > auto_injection:<enabled:<BoolValue:<value:true > > components:<injector:<enabled:<BoolValue:<value:true > > k8s:<replica_count:1 strategy:<rollingUpdate:<maxUnavailable:<IntOrString:<type:1 strVal:"25%" > > maxSurge:<IntOrString:<type:1 strVal:"100%" > > > > > > > > gateways:<enabled:<BoolValue:<value:true > > components:<ingress_gateway:<enabled:<BoolValue:<value:true > > k8s:<hpa_spec:<scaleTargetRef:<kind:"Deployment" name:"istio-ingressgateway" apiVersion:"apps/v1" > minReplicas:1 maxReplicas:5 metrics:<type:"Resource" resource:<name:"cpu" targetAverageUtilization:80 > > > resources:<limits:<key:"cpu" value:"2000m" > limits:<key:"memory" value:"1024Mi" > requests:<key:"cpu" value:"10m" > requests:<key:"memory" value:"40Mi" > > strategy:<rollingUpdate:<maxUnavailable:<IntOrString:<type:1 strVal:"25%" > > maxSurge:<IntOrString:<type:1 strVal:"100%" > > > > > > egress_gateway:<enabled:<BoolValue:<value:true > > k8s:<hpa_spec:<scaleTargetRef:<kind:"Deployment" name:"istio-egressgateway" apiVersion:"apps/v1" > minReplicas:1 maxReplicas:5 metrics:<type:"Resource" resource:<name:"cpu" targetAverageUtilization:80 > > > resources:<limits:<key:"cpu" value:"2000m" > limits:<key:"memory" value:"1024Mi" > requests:<key:"cpu" value:"10m" > requests:<key:"memory" value:"40Mi" > > strategy:<rollingUpdate:<maxUnavailable:<IntOrString:<type:1 strVal:"25%" > > maxSurge:<IntOrString:<type:1 strVal:"100%" > > > > > > > > cni:<enabled:<BoolValue:<> > > values:<key:"certmanager" value:map[hub:quay.io/jetstack image:cert-manager-controller tag:v0.6.2] > values:<key:"clusterResources" value:true > values:<key:"galley" value:map[enableAnalysis:false image:galley] > values:<key:"gateways" value:map[istio-egressgateway:map[autoscaleEnabled:false env:map[ISTIO_META_ROUTER_MODE:sni-dnat] ports:[map[name:http2 port:80] map[name:https port:443] map[name:tls port:15443 targetPort:15443]] secretVolumes:[map[mountPath:/etc/istio/egressgateway-certs name:egressgateway-certs secretName:istio-egressgateway-certs] map[mountPath:/etc/istio/egressgateway-ca-certs name:egressgateway-ca-certs secretName:istio-egressgateway-ca-certs]] type:ClusterIP zvpn:map[enabled:true suffix:global]] istio-ingressgateway:map[applicationPorts: autoscaleEnabled:false debug:info domain: env:map[ISTIO_META_ROUTER_MODE:sni-dnat] meshExpansionPorts:[map[name:tcp-pilot-grpc-tls port:15011 targetPort:15011] map[name:tcp-citadel-grpc-tls port:8060 targetPort:8060] map[name:tcp-dns-tls port:853 targetPort:853]] ports:[map[name:status-port port:15020 targetPort:15020] map[name:http2 port:80 targetPort:80] map[name:https port:443] map[name:kiali port:15029 targetPort:15029] map[name:prometheus port:15030 targetPort:15030] map[name:grafana port:15031 targetPort:15031] map[name:tracing port:15032 targetPort:15032] map[name:tls port:15443 targetPort:15443]] sds:map[enabled:false image:node-agent-k8s resources:map[limits:map[cpu:2000m memory:1024Mi] requests:map[cpu:100m memory:128Mi]]] secretVolumes:[map[mountPath:/etc/istio/ingressgateway-certs name:ingressgateway-certs secretName:istio-ingressgateway-certs] map[mountPath:/etc/istio/ingressgateway-ca-certs name:ingressgateway-ca-certs secretName:istio-ingressgateway-ca-certs]] type:LoadBalancer zvpn:map[enabled:true suffix:global]]] > values:<key:"global" value:map[arch:map[amd64:2 ppc64le:2 s390x:2] certificates:[] configValidation:true controlPlaneSecurityEnabled:false defaultNodeSelector:map[] defaultPodDisruptionBudget:map[enabled:true] defaultResources:map[requests:map[cpu:10m]] disablePolicyChecks:false enableHelmTest:false enableTracing:true imagePullPolicy:IfNotPresent imagePullSecrets:[] k8sIngress:map[enableHttps:false enabled:false gatewayName:ingressgateway] localityLbSetting:map[enabled:true] logAsJson:false logging:map[level:default:info] meshExpansion:map[enabled:false useILB:false] meshNetworks:map[] mtls:map[auto:false enabled:false] multiCluster:map[clusterName: enabled:false] network: omitSidecarInjectorConfigMap:false oneNamespace:false operatorManageWebhooks:false outboundTrafficPolicy:map[mode:ALLOW_ANY] policyCheckFailOpen:false priorityClassName: proxy:map[accessLogEncoding:TEXT accessLogFile:/dev/stdout accessLogFormat: autoInject:enabled clusterDomain:cluster.local componentLogLevel:misc:error concurrency:2 dnsRefreshRate:300s enableCoreDump:false envoyAccessLogService:map[enabled:false host:<nil> port:<nil>] envoyMetricsService:map[enabled:false host:<nil> port:<nil> tcpKeepalive:map[interval:10s probes:3 time:10s] tlsSettings:map[caCertificates:<nil> clientCertificate:<nil> mode:DISABLE privateKey:<nil> sni:<nil> subjectAltNames:[]]] envoyStatsd:map[enabled:false host:<nil> port:<nil>] excludeIPRanges: excludeInboundPorts: excludeOutboundPorts: image:proxyv2 includeIPRanges:* includeInboundPorts:* kubevirtInterfaces: logLevel:warning privileged:false protocolDetectionTimeout:100ms readinessFailureThreshold:30 readinessInitialDelaySeconds:1 readinessPeriodSeconds:2 resources:map[limits:map[cpu:2000m memory:1024Mi] requests:map[cpu:10m memory:40Mi]] statusPort:15020 tracer:zipkin] proxy_init:map[image:proxyv2 resources:map[limits:map[cpu:100m memory:50Mi] requests:map[cpu:10m memory:10Mi]]] sds:map[enabled:false token:map[aud:istio-ca] udsPath:] tracer:map[datadog:map[address:$(HOST_IP):8126] lightstep:map[accessToken: address: cacertPath: secure:true] zipkin:map[address:]] trustDomain:cluster.local useMCP:true] > values:<key:"grafana" value:map[accessMode:ReadWriteMany contextPath:/grafana dashboardProviders:map[dashboardproviders.yaml:map[apiVersion:1 providers:[map[disableDeletion:false folder:istio name:istio options:map[path:/var/lib/grafana/dashboards/istio] orgId:1 type:file]]]] datasources:map[datasources.yaml:map[apiVersion:1 datasources:<nil>]] enabled:true env:map[] envSecrets:map[] image:map[repository:grafana/grafana tag:6.4.3] ingress:map[annotations:<nil> enabled:false hosts:[grafana.local] tls:<nil>] nodeSelector:map[] persist:false podAntiAffinityLabelSelector:[] podAntiAffinityTermLabelSelector:[] replicaCount:1 security:map[enabled:false passphraseKey:passphrase secretName:grafana usernameKey:username] service:map[annotations:map[] externalPort:3000 loadBalancerIP:<nil> loadBalancerSourceRanges:<nil> name:http type:ClusterIP] storageClassName: tolerations:[]] > values:<key:"istiocoredns" value:map[coreDNSImage:coredns/coredns coreDNSPluginImage:istio/coredns-plugin:0.2-istio-1.1 coreDNSTag:1.6.2 enabled:false] > values:<key:"kiali" value:map[contextPath:/kiali createDemoSecret:true dashboard:map[grafanaURL:<nil> jaegerURL:<nil> passphraseKey:passphrase secretName:kiali usernameKey:username viewOnlyMode:false] enabled:true hub:quay.io/kiali ingress:map[annotations:<nil> enabled:false hosts:[kiali.local] tls:<nil>] nodeSelector:map[] podAntiAffinityLabelSelector:[] podAntiAffinityTermLabelSelector:[] prometheusNamespace:<nil> replicaCount:1 security:map[cert_file:/kiali-cert/cert-chain.pem enabled:false private_key_file:/kiali-cert/key.pem] tag:v1.9] > values:<key:"mixer" value:map[adapters:map[kubernetesenv:map[enabled:true] prometheus:map[enabled:true metricsExpiryDuration:10m] stackdriver:map[auth:map[apiKey: appCredentials:false serviceAccountPath:] enabled:false tracer:map[enabled:false sampleProbability:1]] stdio:map[enabled:true outputAsJson:false] useAdapterCRDs:false] policy:map[adapters:map[kubernetesenv:map[enabled:true] useAdapterCRDs:false] autoscaleEnabled:false image:mixer sessionAffinityEnabled:false] telemetry:map[autoscaleEnabled:false image:mixer loadshedding:map[latencyThreshold:100ms mode:enforce] nodeSelector:map[] podAntiAffinityLabelSelector:[] podAntiAffinityTermLabelSelector:[] replicaCount:1 reportBatchMaxEntries:100 reportBatchMaxTime:1s sessionAffinityEnabled:false tolerations:[] useMCP:true]] > values:<key:"nodeagent" value:map[image:node-agent-k8s] > values:<key:"pilot" value:map[appNamespaces:[] autoscaleEnabled:false autoscaleMax:5 autoscaleMin:1 configMap:true configNamespace:istio-config cpu:map[targetAverageUtilization:80] deploymentLabels:<nil> enableProtocolSniffingForInbound:false enableProtocolSniffingForOutbound:true env:map[] image:pilot ingress:map[ingressClass:istio ingressControllerMode:OFF ingressService:istio-ingressgateway] keepaliveMaxServerConnectionAge:30m meshNetworks:map[networks:map[]] nodeSelector:map[] podAntiAffinityLabelSelector:[] podAntiAffinityTermLabelSelector:[] policy:map[enabled:false] replicaCount:1 tolerations:[] traceSampling:1 useMCP:true] > values:<key:"prometheus" value:map[contextPath:/prometheus enabled:true hub:docker.io/prom ingress:map[annotations:<nil> enabled:false hosts:[prometheus.local] tls:<nil>] nodeSelector:map[] podAntiAffinityLabelSelector:[] podAntiAffinityTermLabelSelector:[] replicaCount:1 retention:6h scrapeInterval:15s security:map[enabled:true] tag:v2.12.0 tolerations:[]] > values:<key:"security" value:map[dnsCerts:map[istio-pilot-service-account.istio-control:istio-pilot.istio-control] enableNamespacesByDefault:true image:citadel selfSigned:true trustDomain:cluster.local] > values:<key:"sidecarInjectorWebhook" value:map[enableNamespacesByDefault:false image:sidecar_injector injectLabel:istio-injection objectSelector:map[autoInject:true enabled:false] rewriteAppHTTPProbe:false selfSigned:false] > values:<key:"telemetry" value:map[enabled:true v2:map[enabled:false]] > values:<key:"tracing" value:map[enabled:true ingress:map[annotations:<nil> enabled:false hosts:<nil> tls:<nil>] jaeger:map[accessMode:ReadWriteMany hub:docker.io/jaegertracing memory:map[max_traces:50000] persist:false spanStorageType:badger storageClassName: tag:1.14] nodeSelector:map[] opencensus:map[exporters:map[stackdriver:map[enable_tracing:true]] hub:docker.io/omnition resources:map[limits:map[cpu:1 memory:2Gi] requests:map[cpu:200m memory:400Mi]] tag:0.1.9] podAntiAffinityLabelSelector:[] podAntiAffinityTermLabelSelector:[] provider:jaeger service:map[annotations:map[] externalPort:9411 name:http-query type:ClusterIP] zipkin:map[hub:docker.io/openzipkin javaOptsHeap:700 maxSpans:500000 node:map[cpus:2] probeStartupDelay:200 queryPort:9411 resources:map[limits:map[cpu:300m memory:900Mi] requests:map[cpu:150m memory:900Mi]] tag:2.14.2]] > values:<key:"version" value: > profile:"demo" hub:"docker.io/istio" tag:"1.4.0"
error: chart metadata (Chart.yaml) missing

**Comment by richardwxn** [comment] 2019-11-27 06:17
probably vfs gen files issues for the compiled in charts. I don't have a windows machine though to verify, @howardjohn any idea what might be the cause?

**Comment by howardjohn** [comment] 2019-11-27 15:21
@richardwxn the first error about `Could not configure logs: couldn't open sink "/dev/null": open /dev/null: The system cannot find the path specified.` is probably because there is no /dev/null on windows. The charts.yaml one -- no clue

**Comment by joakimr-axis** [comment] 2019-11-28 14:39
I guess the initial reported issue here, being the /dev/null one, is to be regarded as solved with the verified --logtostderr suggestion?
And that it reveals this new issue (to be handled separately?) with the compiled in charts.

**Comment by LosGlennos** [comment] 2019-11-28 15:05
I got the Charts-error as well. If you want to get around this issue, I managed to get `istioctl manifest apply` working with WSL for Windows. As an interim solution.

**Comment by howardjohn** [comment] 2019-12-02 01:33
Finally got my hands on a windows machine. Workaround for 1.4.0: `--logtostderr --set installPackagePath=install/kubernetes/operator/charts` (folder from the Istio release archive)

Hoping to have this properly fixed in 1.4.1. I at least have a fix for the logging part

**Comment by sdake** [comment] 2019-12-02 06:33
nice @howardjohn !

**Comment by joakimr-axis** [comment] 2019-12-02 13:24
Wonderful. Tested here at my end and it works (as expected) like a charm. Thanks @howardjohn !!

**Closed** 2019-12-02 19:06 UTC
Labels: area/environments, cherrypick/release-1.4

**Comment by howardjohn** [comment] 2019-12-02 19:23
This will be in 1.4.1 which will be shipped by end of week (hopefully)
