### ISSUE TITLE
wasm: TCP stats share state with HTTP stats, and configurations race

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#28017] opened 2020-10-15 23:31 UTC
TCP and HTTP stats reporting apply to the same root context, meaning the last one wins. This is mostly a concern for customizations and reporting durations.

FYI @douglas-reid @gargnupur @mandarjog

**Comment by bianpengyuan** [comment] 2020-10-15 23:53
This only applies to v8 but not nullvm right?

Isn't this a configuration issue? This can be worked around by either share the same metric customization between TCP and HTTP, or use different root context id to distinguish.

**Comment by kyessenov** [comment] 2020-10-16 00:59
It applies to nullvm from what I can tell. There's a still single nullvm root context for stats inbound.

I think it makes more sense to split the root context than trying to retrofit the same root context for two purposes. WDYT?

**Comment by bianpengyuan** [comment] 2020-10-16 01:21
> It applies to nullvm from what I can tell. There's a still single nullvm root context for stats inbound.

oh yes, that is right. Null vm instance is also thread local and shared by streams.

> I think it makes more sense to split the root context than trying to retrofit the same root context for two purposes. WDYT?

Yeah that makes sense to me. I think we used to talk about adding TCP as separated root context, which is something like this: https://github.com/istio/proxy/compare/master...bianpengyuan:tcp-context?expand=1

**Comment by mandarjog** [comment] 2020-10-17 00:26
Good catch, this should go on the wiki. I think it makes sense to split the root contexts.
There is some shared code between the tcp and http but that can be refactored as library / common code.
Would it make sense to just explicitly separate them? Right now in several places we have if (tcp) type code.

**Comment by kyessenov** [comment] 2020-10-17 01:03
Given that I'm adding interval reporting that is very similar to TCP, I
think we should keep the combined implementation and just introduce a
couple more root contexts.

**Comment by kyessenov** [comment] 2020-10-19 17:26
Change of plans: adding new root context leads to unexpected crashes, so something is broken in Wasm (again). Let's keep one root and share the config instead.

**Comment by kyessenov** [comment] 2020-10-21 01:53
CC @PiotrSikora @douglas-reid 

I think this is a serious flaw in the design for onConfigure that makes it hard to implement a usable telemetry API on top. There are two major problems:

- Its effect is immediate, retroactive, and permanent.  Whenever a new xDS config is pushed, the _existing_ report batches and on-going streams are affected. If the xDS configuration is ultimately rejected (because of Wasm or something else), it is still applied. Once an incorrect configuration is applied, it is not reverted. The same configuration is applied repeatedly from many listeners that carry it (which might be causing the CPU spikes).

- It breaks isolation between listeners. TCP and HTTP listener configuration apply to the same root. Depending which one is applied last during xDS, it wins. The only sensible way it can work is if the entire xDS is swapped atomically. If one mixes stale LDS for HTTP with fresh LDS for TCP, onConfigure will flip flop between the two versions, with a CPU spike. If LDS is not 100% synced with ECDS, it will flip flop.

**Comment by douglas-reid** [comment] 2020-10-21 02:09
@kyessenov i think i understand issues with new config. does this also imply an issue with per-listener customizations (which i think was your second point)?

**Comment by kyessenov** [comment] 2020-10-21 02:12
@douglas-reid The way I understand it, we cannot have per-listener customizations in principle with onConfigure. It's a singleton.

**Comment by PiotrSikora** [comment] 2020-10-21 08:10
OK, I've looked at the code. The WasmVM is keyed on `vm_id + vm_configuration + plugin bytecode`, but not on the `plugin configuration`, so that's obviously going to be broken if we have different `plugin configurations` randomly reconfiguring the only instance of the extension running inside the same WasmVM.

There are a few solutions that come to mind:
1) Add `plugin configuration` to the key. This is easy to implement, but will results in many more WasmVMs being active.
2) For each config update, create a new instance of the root context inside the WasmVM. This will result in many different instances of the same plugin running at the same time, but they'll have different `root_context_id`, so as long as they don't store any global variables that should be fine.

Separately, we should be ignoring config updates if nothing changed. It sounds like that's not the case right now.

**Comment by kyessenov** [comment] 2020-10-21 16:59
Should we consider this a blocking bug? I agree about the need to change our modules to diff incoming configs.

**Comment by bianpengyuan** [comment] 2020-10-21 17:43
> Should we consider this a blocking bug? I agree about the need to change our modules to diff incoming configs.

Probably not if the short term fix to have different contexts does not work (https://github.com/istio/istio/issues/28017#issuecomment-712315223). This is not a regression so I am reluctant to make this a release blocker.

**Comment by bianpengyuan** [comment] 2020-10-21 17:44
And we should try to make the context separation work by 1.8 if not a very hard fix.

**Comment by kyessenov** [comment] 2020-10-21 17:49
Context separation is constrained by v8. We'll double the number of VMs if we split TCP and HTTP root context. Even then, each root context suffers from the same problem (e.g. if you submit a bad EnvoyFilter, it will not undo the changes by removing the EnvoyFilter).

**Comment by gargnupur** [comment] 2020-10-21 17:50
For `plugin configuration`to work, we would have to add something in config to say this is tcp and http. Currently the config is also same for both http and tcp

**Comment by douglas-reid** [comment] 2020-10-21 18:30
> @douglas-reid The way I understand it, we cannot have per-listener customizations in principle with onConfigure. It's a singleton.

This seems like a big drawback, and could be hard to make visible properly to users (especially in a Telemetry API).

**Comment by kyessenov** [comment] 2020-10-21 18:34
A few design ideas, although solving this probably deserves a real re-design:
- Add a generation number to plugin config with the last one winning. Plugins must keep the old generation config if the new one is broken.
- Debounce onConfigure, so that Envoy applies it every 1-10 seconds. In case of conflicts, sort them in some deterministic order.
- Detach root config from plugin config, and make it a first class resource in bootstrap extensions. Implement ECDS for it.

**Comment by bianpengyuan** [comment] 2020-10-21 19:29
> Detach root config from plugin config, and make it a first class resource in bootstrap extensions. Implement ECDS for it.

I think this is the right way to go, although not sure what do you mean by `bootstrap extensions`. I think it would be cleaner if we have another discovery resource (Wasm Context discovery), and Wasm VM and context lifecycle will tie to this resource.

**Comment by mandarjog** [comment] 2020-10-22 06:46
@PiotrSikora @kyessenov onConfigure is called on the baseVM *before* being called on the worker, correct?
In that case we should be assured that the config is valid.

If we can do something equivalent to the how it happens in native filters that should work.
I *think* that is what Piotr suggested as well.

**Comment by kyessenov** [comment] 2020-10-22 18:29
@mandarjog 
In our extensions, onConfigure always returns true, or the proxy crashes with LDS update.

Native filters have two general patterns:
- Shared fate with the listener. This would get rid of root_id concept, and just create a root for every listener. It would be created once listener is accepted and deleted once listener is drained. This works fine for stats filter I think.
- Key by configuration. Instantiate thread local roots for each configuration (again, not sure why we need root ID). Create when a new configuration is mentioned, delete when all listeners referencing it are drained.

**Comment by PiotrSikora** [comment] 2020-10-26 08:16
> Should we consider this a blocking bug? I agree about the need to change our modules to diff incoming configs.

I think so. Even though it's not a regression, it's terribly broken.

> * Detach root config from plugin config, and make it a first class resource in bootstrap extensions. Implement ECDS for it.

But `root config` is `plugin config`.

> In our extensions, onConfigure always returns true, or the proxy crashes with LDS update.

Could you file an issue for that in Envoy repo? If you always return `true`, then there is no way to catch configuration issues, and you'll end up with events dispatched on misconfigured plugin.

**Comment by PiotrSikora** [comment] 2020-10-29 05:55
https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/78 and https://github.com/envoyproxy/envoy/pull/13753 are ready for review and they should fix the issue if anyone wants to give it a try.

**Comment by kyessenov** [comment] 2021-01-28 01:09
I think we should have separate configs for TCP and HTTP now, but needs end-to-end validation.

**Comment by PiotrSikora** [comment] 2021-03-06 07:48
The configuration race has been fixed in 1.9 already, but I don't believe we updated the Istio plugins accordingly.

@kyessenov @bianpengyuan could one of you update them to use separate configs instead of relying on `root_id` for inbound/outbound?

**Comment by PiotrSikora** [comment] 2021-05-15 07:54
@kyessenov @bianpengyuan ping.

**Comment by ryantking** [comment] 2021-07-26 20:27
Moving to 1.12 due to recent inactivity

**Comment by Kmoneal** [comment] 2021-10-20 21:19
@kyessenov @bianpengyuan Any updates? I don't want to just push this back without checking in.

**Comment by kyessenov** [comment] 2022-05-12 20:14
Still an issue.
/reopen

**Comment by douglas-reid** [comment] 2022-08-29 21:00
@kyessenov i assume still an issue?

**Closed** 2022-10-05 06:25 UTC
Labels: lifecycle/automatically-closed, area/networking/envoy/wasm
