### ISSUE TITLE
EnvoyFilter doesn't merge set_current_client_cert_details with ingress gateway envoy config

### ISSUE THREAD

**Issue by infa-rbliznet** [istio/istio#23178] opened 2020-04-23 16:31 UTC
**Use case: I need to disable client certificate being propagated to XFCC header. For that I need to update set_current_client_cert_details.cert=false but it doesn't work. Istio doesn't merge in the false value. Mutating of numeric values work perfectly.** 

**Expected behavior**
Boolean 'false' values from EnvoyFilter should be merged in into the config

**Steps to reproduce the bug**
1. Configure EnvoyFilter to opt out some XFCC details:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xffc-details
  namespace: masked 
spec:
  workloadSelector:
    labels:
      app: iics-ingress-gateway
      ns: masked
      
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          set_current_client_cert_details: 
            subject: true
            cert: false
            chain: false
            dns: false
            uri: true
          xffNumTrustedHops: 2
```
2. Apply the EnvoyFilter and restart ingressgateway pods, make sure that they all initialized. Check that boolean 'false' values weren't honored, xffNumTrustedHops which is numeric was honored in the config (just in sake of testing).
```
istioctl proxy-config listener iicsgateway-75d578fcbf-vg6h9.masked -o json
[
    {
        "name": "0.0.0.0_10002",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 10002
            }
        },
        "filterChains": [
            {
                "tlsContext": {
                    "commonTlsContext": {
                        "tlsCertificates": [
                            {
                                "certificateChain": {
                                    "filename": "/etc/istio/ingressgateway-certs/tls.crt"
                                },
                                "privateKey": {
                                    "filename": "/etc/istio/ingressgateway-certs/tls.key"
                                }
                            }
                        ],
                        "validationContext": {
                            "trustedCa": {
                                "filename": "/etc/istio/ingressgateway-ca-certs/ca-chain.cert.pem"
                            }
                        },
                        "alpnProtocols": [
                            "h2",
                            "http/1.1"
                        ]
                    },
                    "requireClientCertificate": true
                },
                "filters": [
                    {
                        "name": "envoy.http_connection_manager",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
                            "statPrefix": "outbound_0.0.0.0_10002",
                            "rds": {
                                "configSource": {
                                    "ads": {}
                                },
                                "routeConfigName": "https.10002.https.iics-masked.masked"
                            },
                            "httpFilters": [
                                {
                                    "name": "mixer",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/istio.mixer.v1.config.client.HttpClientConfig",
                                        "transport": {
                                            "networkFailPolicy": {
                                                "policy": "FAIL_CLOSE",
                                                "baseRetryWait": "0.080s",
                                                "maxRetryWait": "1s"
                                            },
                                            "checkCluster": "outbound|15004||istio-policy.istio-system.svc.cluster.local",
                                            "reportCluster": "outbound|15004||istio-telemetry.istio-system.svc.cluster.local",
                                            "reportBatchMaxEntries": 100,
                                            "reportBatchMaxTime": "1s"
                                        },
                                        "serviceConfigs": {
                                            "default": {
                                                "disableCheckCalls": true
                                            }
                                        },
                                        "defaultDestinationService": "default",
                                        "mixerAttributes": {
                                            "attributes": {
                                                "context.proxy_version": {
                                                    "stringValue": "1.4.6"
                                                },
                                                "context.reporter.kind": {
                                                    "stringValue": "outbound"
                                                },
                                                "context.reporter.uid": {
                                                    "stringValue": "kubernetes://iicsgateway-fd5bcbddf-dlrfn.masked"
                                                },
                                                "source.namespace": {
                                                    "stringValue": "masked"
                                                },
                                                "source.uid": {
                                                    "stringValue": "kubernetes://iicsgateway-fd5bcbddf-dlrfn.masked"
                                                }
                                            }
                                        },
                                        "forwardAttributes": {
                                            "attributes": {
                                                "source.uid": {
                                                    "stringValue": "kubernetes://iicsgateway-fd5bcbddf-dlrfn.masked"
                                                }
                                            }
                                        },
                                        "ignoreForwardedAttributes": true
                                    }
                                },
                                {
                                    "name": "envoy.cors"
                                },
                                {
                                    "name": "envoy.fault"
                                },
                                {
                                    "name": "envoy.lua",
                                    "config": {
                                        "inlineCode": "masked"
                                    }
                                },
                                {
                                    "name": "envoy.router"
                                }
                            ],
                            "tracing": {
                                "operationName": "EGRESS",
                                "clientSampling": {
                                    "value": 100
                                },
                                "randomSampling": {
                                    "value": 1
                                },
                                "overallSampling": {
                                    "value": 100
                                }
                            },
                            "httpProtocolOptions": {},
                            "serverName": "istio-envoy",
                            "streamIdleTimeout": "0s",
                            "accessLog": [
                                {
                                    "name": "envoy.file_access_log",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog",
                                        "path": "/dev/stdout",
                                        "format": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%DYNAMIC_METADATA(istio.mixer:status)%\" \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                                    }
                                }
                            ],
                            "useRemoteAddress": true,
                            "xffNumTrustedHops": 2,
                            "generateRequestId": true,
                            "forwardClientCertDetails": "SANITIZE_SET",
                            "setCurrentClientCertDetails": {
                                "subject": true,
                                "cert": true,
                                "dns": true,
                                "uri": true
                            },
                            "upgradeConfigs": [
                                {
                                    "upgradeType": "websocket"
                                }
                            ],
                            "normalizePath": true
                        }
                    }
                ]
            }
        ],
        "listenerFilters": [
            {
                "name": "envoy.listener.tls_inspector"
            }
        ],
        "trafficDirection": "OUTBOUND"
    },
    {
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 15090
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.http_connection_manager",
                        "config": {
                            "codec_type": "AUTO",
                            "http_filters": {
                                "name": "envoy.router"
                            },
                            "route_config": {
                                "virtual_hosts": [
                                    {
                                        "domains": [
                                            "*"
                                        ],
                                        "name": "backend",
                                        "routes": [
                                            {
                                                "match": {
                                                    "prefix": "/stats/prometheus"
                                                },
                                                "route": {
                                                    "cluster": "prometheus_stats"
                                                }
                                            }
                                        ]
                                    }
                                ]
                            },
                            "stat_prefix": "stats"
                        }
                    }
                ]
            }
        ]
    }
]
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.4.5
control plane version: 1.4.6
data plane version: 1.4.6 (43 proxies), 1.4.5 (1 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

```

**How was Istio installed?**
Using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by infa-rbliznet** [comment] 2020-04-23 16:57
I see that there were a similar issue of setting boolean to false: https://github.com/istio/istio/issues/12549

**Comment by howardjohn** [comment] 2020-04-23 21:09
should it be set_current_client_cert_details -> setCurrentClientCertDetails? I don't think its the bool issue because its missing the whole struct not individual bool fields

**Comment by infa-rbliznet** [comment] 2020-04-23 21:43
I tried but the result is the same:
```
          xffNumTrustedHops: 2
          setCurrentClientCertDetails: 
            subject: true
            cert: false
            chain: false
            dns: false
            uri: true
```

Also if property is wrong it complains usually

**Comment by infa-rbliznet** [comment] 2020-04-28 16:23
Found an another duplicate: https://github.com/istio/istio/issues/18169

**Comment by howardjohn** [comment] 2020-07-28 20:59
Closing as duplicate of https://github.com/istio/istio/issues/18169

**Closed by howardjohn** 2020-07-28 20:59 UTC
Labels: area/config, area/networking, lifecycle/needs-triage
