### ISSUE TITLE
Multicluster installation failed with function "valueOrDefault" not defined

### ISSUE THREAD

**Issue by JackTroy** [istio/istio#23754] opened 2020-05-12 12:53 UTC
**Bug description**
When doing multicluster installation following https://preliminary.istio.io/docs/setup/install/multicluster/gateways/,  it gives below error.

```
>istioctl manifest apply  -f manifests/examples/multicluster/values-istio-multicluster-gateways.yaml
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
Error: failed to apply manifests: template: :263: function "valueOrDefault" not defined
```
Error happens on  both1.6.0-beta.1 and 1.6.0-beta.0.

**Expected behavior**
Successful Installation

**Steps to reproduce the bug**
`>istioctl manifest apply  -f manifests/examples/multicluster/values-istio-multicluster-gateways.yaml`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.0-beta.1 
1.6.0-beta.0

**Environment where bug was observed (cloud vendor, OS, etc)**
kubernetes 1.16
ubuntu 18.04

**Comment by esnible** [comment] 2020-05-12 13:25
I am seeing the same on beta.1 (and also on Master with `istioctl manifest apply -f operator/data/examples/multicluster/values-istio-multicluster-gateways.yaml`.)

**Comment by howardjohn** [comment] 2020-05-12 16:29
@ostromart sounds like we are trying to template the IOP when we shouldn't?

**Comment by howardjohn** [comment] 2020-05-12 17:13
duplicate of https://github.com/istio/istio/issues/23711

**Closed by howardjohn** 2020-05-12 17:13 UTC
Labels: area/environments, feature/Multi-cluster
