### ISSUE TITLE
v2 metrics response size doesn't seem to work

### ISSUE THREAD

**Issue by Stono** [istio/istio#20536] opened 2020-01-26 09:33 UTC
**Bug description**
Switched over one of our bigger clusters to v2 metrics and response sizes are just broken.  All other metrics are fine.

<img width="1569" alt="Screenshot 2020-01-26 at 09 28 29" src="https://user-images.githubusercontent.com/1486729/73133306-bbab8c80-401e-11ea-9dfa-be3011a9959f.png">

Response size are being recorded, just incorrect (looking at metrics reported after the v2 rollout)
<img width="1631" alt="Screenshot 2020-01-26 at 09 50 34" src="https://user-images.githubusercontent.com/1486729/73133495-560ccf80-4021-11ea-9753-d080187d0da3.png">

Request sizes are fine:
<img width="1680" alt="Screenshot 2020-01-26 at 09 51 02" src="https://user-images.githubusercontent.com/1486729/73133501-64f38200-4021-11ea-8129-89a1c8f2af08.png">

We're rolling back to v1 :-( 

**Expected behavior**
Some discrepancy due to buckets, but not this.

**Steps to reproduce the bug**
Hard to say, just what we've observed on our cluster

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.3

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by Stono** [comment] 2020-01-26 09:43
Also reopened https://github.com/istio/istio/issues/20476

**Comment by mandarjog** [comment] 2020-01-26 18:59
Marking it as a release blocker.

**Comment by mandarjog** [comment] 2020-01-26 19:47
@kyessenov this is 1.4.
the problem is likely already fixed in 1.5. @bianpengyuan

**Comment by kyessenov** [comment] 2020-01-26 23:45
I can take a look. Do we _know_ it is fixed in 1.5?

**Comment by Stono** [comment] 2020-01-27 07:31
I have only tested `1.4.3` @kyessenov

**Comment by douglas-reid** [comment] 2020-01-27 17:20
I was not seeing this issue with response sizes in testing against httpbin on Friday.

**Comment by douglas-reid** [comment] 2020-01-27 17:33
From a `sleep` pod, executing the following:

` # curl -v httpbin:8000/bytes/9000 -s -o /dev/null`

Produces:

![image](https://user-images.githubusercontent.com/21148125/73198560-07763880-40e8-11ea-864e-349ce481c2a0.png)

**Comment by mandarjog** [comment] 2020-01-27 17:35
We should retry the httpbin experiment with 1.4.3

**Comment by douglas-reid** [comment] 2020-01-27 17:37
@mandarjog i'm testing with a 1.4.2 build, it turns out.

**Comment by douglas-reid** [comment] 2020-01-27 17:40
Interestingly, I see `0.475` as the p95 for _request_ size (for empty requests):

![image](https://user-images.githubusercontent.com/21148125/73199092-101b3e80-40e9-11ea-9f9c-af90ebac31fb.png)

**Comment by Stono** [comment] 2020-01-27 17:48
Here are metrics directly from the proxy.  Ignore the unkonwn labels in this example as i didn't apply the filters globally to capture this data on this example.  This service is returning sizeable bodies as seen by v1 mixer:

<img width="1672" alt="Screenshot 2020-01-27 at 17 33 26" src="https://user-images.githubusercontent.com/1486729/73199684-3236b000-412d-11ea-8c04-a39ce1ffae36.png">

But v2 metrics as you can see, all responses are just in every bucket:
```
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="0.5"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="1"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="5"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="10"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="25"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="50"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="100"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="250"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="500"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="1000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="2500"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="5000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="10000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="30000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="60000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="300000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="600000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="1800000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="3600000"} 387
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_app="unknown",source_version="unknown",destination_workload="api-gateway",destination_workload_namespace="api-gateway",destination_principal="spiffe://cluster.local/ns/api-gateway/sa/default",destination_app="api-gateway",destination_version="unknown",destination_service="app.api-gateway.svc.cluster.local",destination_service_name="app",destination_service_namespace="api-gateway",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="+Inf"} 387
```

**Comment by mandarjog** [comment] 2020-01-27 17:52
From doug's previous comment it seems like the response is zero. I am wondering if we are capturing the response size correctly with chunked encoding.

**Comment by douglas-reid** [comment] 2020-01-27 18:15
Currently investigating whether or not the presence of the 'mixer' filter in proxy config could be impacting the stats filter.

**Comment by douglas-reid** [comment] 2020-01-27 18:29
Still seeing the same results without `mixer` filter. @Stono 's cluster is using chunked encoding, but my test cluster with chunked encoding does not demonstrate the same issue.

**Comment by Stono** [comment] 2020-01-27 18:31
So everyone is on the same page about what we've done:

1. v1 enabled - validated a config_dump
2. v1 enabled - validated mixer filter removed
3 v2 enabled - validated a config_dump for new filters

Requesting 5mb responses multiple times from test service (chunked encoded), all `istio_response_bytes_bucket` both source and destination reporters record the request in every bucket (effectively recording a 0 size response).

**Comment by douglas-reid** [comment] 2020-01-27 19:08
Currently investigating if the difference in observations is `1.4.2` v `1.4.3`.

**Comment by Stono** [comment] 2020-01-27 19:11
OK, by downgrading the proxy to `1.4.2` the buckets are correct:

```
# TYPE istio_response_bytes histogram
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="0.5"} 0
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="1"} 0
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="5"} 0
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="10"} 0
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="25"} 0
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="50"} 0
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="100"} 0
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="250"} 0
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="500"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="1000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="2500"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="5000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="10000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="30000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="60000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="300000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="600000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="1800000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="3600000"} 4
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="vehicle-metric-service",source_workload_namespace="vehicle-metric-service",source_principal="spiffe://cluster.local/ns/vehicle-metric-service/sa/default",source_app="vehicle-metric-service",source_version="unknown",destination_workload="search-one-read",destination_workload_namespace="search-one-read",destination_principal="spiffe://cluster.local/ns/search-one-read/sa/default",destination_app="search-one-read",destination_version="unknown",destination_service="app.search-one-read.svc.cluster.local",destination_service_name="app",destination_service_namespace="search-one-read",request_protocol="http",response_flags="-",connection_security_policy="MUTUAL_TLS",permissive_response_code="none",permissive_response_policyid="none",le="+Inf"} 4
```

Went back and forth a few times between versions and can confirm this is a `1.4.3` regression.

**Comment by mandarjog** [comment] 2020-01-27 20:57
Waiting on: https://github.com/envoyproxy/envoy/pull/9839

**Comment by fpesce** [comment] 2020-01-30 18:47
@mandarjog / @douglas-reid  envoyproxy/envoy#9839 was merged, any update on this release blocker ?

**Comment by kyessenov** [comment] 2020-01-30 18:56
Need https://github.com/envoyproxy/envoy/pull/9862 as well.

**Comment by kyessenov** [comment] 2020-01-30 20:46
PR https://github.com/istio/proxy/pull/2642

**Comment by kyessenov** [comment] 2020-02-03 18:30
PR for 1.5: https://github.com/istio/envoy/pull/136

**Comment by fpesce** [comment] 2020-02-04 22:21
> PR for 1.5: [istio/envoy#136](https://github.com/istio/envoy/pull/136)

@kyessenov merged

**Comment by douglas-reid** [comment] 2020-02-04 22:25
@kyessenov can we bump this down from release blocker for 1.5 then now?

**Comment by kyessenov** [comment] 2020-02-04 23:24
Still not in master.

**Comment by kyessenov** [comment] 2020-02-14 17:31
I believe the cherry-picks all made it through to the release branches.

**Closed by kyessenov** 2020-02-14 17:31 UTC
Labels: area/policies and telemetry

**Comment by Stono** [comment] 2020-02-14 17:32
@kyessenov was that into 1.5, or 1.4.5 too?

**Comment by kyessenov** [comment] 2020-02-14 17:39
I sent to both 1.4 and 1.5. 1.4 I manually checked, 1.5 hasn't been released yet.
