### ISSUE TITLE
Envoy: unknown message type "envoy.admin.v3.BootstrapConfigDump"

### ISSUE THREAD

**Issue by dkirrane** [istio/istio#24046] opened 2020-05-22 17:12 UTC
**Bug description**
```
istioctl -n istio-system proxy-config route istio-ingressgateway-88cd9c959-6cbnj
Error: error unmarshalling config dump response from Envoy: unknown message type "envoy.admin.v3.BootstrapConfigDump"
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.2.5
ingressgateway version: 1.5.2
pilot version: 1.5.2
/c/DEV/GitHubSpokenCloud/istio/examples/helloworld-host-routing (master)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS 1.15.10

**Comment by esnible** [comment] 2020-05-22 18:38
The problem is
```
client version: 1.2.5
ingressgateway version: 1.5.2
```

You need to use a 1.5.x or 1.6.x _istioctl_ with 1.5.x control plane.

Istioctl usually works with +/- 1 minor release only.

When I am maintaining clusters at different levels of Istio, I usually rename _istioctl_ and keep one for each version I test.  e.g. `mv $(which istioctl) $(dirname $(which istioctl))/istioctl-1.5.4`

Close this issue if your problem is solved.

**Comment by esnible** [comment] 2020-05-26 13:14
Can you upgrade your istioctl to 1.5.x and try again?  Close the issue if it works for you.

**Comment by howardjohn** [comment] 2020-06-22 16:16
Please upgrade istioctl, this is expected with an unsupported version skew as seen here

**Closed by howardjohn** 2020-06-22 16:16 UTC
Labels: kind/need more info, lifecycle/needs-triage
