### ISSUE TITLE
Service unavailable from sidecar-injector.istio

### ISSUE THREAD

**Issue by JungukCho** [istio/istio#12441] opened 2019-03-13 00:47 UTC
**Describe the bug**
{{ Succinctly describe the bug }}

After installing istio on K8s, I tried to deploy application, but it did not run application.
I checked apiserver log and it showed this messages in apiserver log.
W0313 00:29:38.938716       1 dispatcher.go:72] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: Service Unavailable

In console in another container (using kubectl exec), I tried to do this.
nslookup istio-sidecar-injector.istio-system.svc
It found a right IP for https://istio-sidecar-injector.istio-system.svc.

Before installing istio, I could run the same application on default K8s.

**Expected behavior**
{{ What did you expect to happen? }}
Should deploy the applications.

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}
After installing application like guestbook, it is not scheduled.
kubectl get deployment 
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
frontend       0/3     0            0           11s
redis-master   0/1     0            0           15s
redis-slave    0/2     0            0           13s

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version --remote` and `kubectl version` }}
 kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

I tried istio-1.0.1 and istio-1.0.6 both, but both showed the same problem.
istioctl version 
Version: 1.0.6
GitRevision: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2
User: root@464fc845-2bf8-11e9-b805-0a580a2c0506
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

**Installation**
{{ Please describe how Istio was installed }}

kubectl apply -f install/kubernetes/helm/helm-service-account.yaml
helm init --service-account tiller
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort --set global.proxy.includeIPRanges="10.244.0.0/16" 
kubectl label namespace default istio-injection=enabled 

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
Ubuntu 16.04 and behind proxy

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

kubectl get svc -n istio-system
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                                   AGE
istio-citadel            ClusterIP   10.99.116.99     <none>        8060/TCP,9093/TCP                                                                                                         20m
istio-egressgateway      NodePort    10.106.224.181   <none>        80:30289/TCP,443:31069/TCP                                                                                                20m
istio-galley             ClusterIP   10.111.17.119    <none>        443/TCP,9093/TCP                                                                                                          20m
istio-ingressgateway     NodePort    10.110.71.91     <none>        80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:30437/TCP,8060:32515/TCP,853:30455/TCP,15030:32752/TCP,15031:31971/TCP   20m
istio-pilot              ClusterIP   10.97.203.114    <none>        15010/TCP,15011/TCP,8080/TCP,9093/TCP                                                                                     20m
istio-policy             ClusterIP   10.104.18.96     <none>        9091/TCP,15004/TCP,9093/TCP                                                                                               20m
istio-sidecar-injector   ClusterIP   10.96.93.139     <none>        443/TCP                                                                                                                   20m
istio-telemetry          ClusterIP   10.104.211.113   <none>        9091/TCP,15004/TCP,9093/TCP,42422/TCP                                                                                     20m
prometheus               ClusterIP   10.110.80.11     <none>        9090/TCP            

kubectl get pods --all-namespaces 
NAMESPACE      NAME                                      READY   STATUS    RESTARTS   AGE
istio-system   istio-citadel-6f444d9999-vdjjm            1/1     Running   0          21m
istio-system   istio-egressgateway-6d79447874-5vvbz      1/1     Running   0          21m
istio-system   istio-galley-685bb48846-qjpv7             1/1     Running   0          21m
istio-system   istio-ingressgateway-5b64fffc9f-zskwv     1/1     Running   0          21m
istio-system   istio-pilot-8645f5655b-d597g              2/2     Running   0          21m
istio-system   istio-policy-547d64b8d7-v9ssb             2/2     Running   0          21m
istio-system   istio-sidecar-injector-5d8dd9448d-fhzrb   1/1     Running   0          16m
istio-system   istio-telemetry-c5488fc49-vhw29           2/2     Running   0          21m
istio-system   prometheus-76b7745b64-kpcrn               1/1     Running   0          21m
kube-system    coredns-86c58d9df4-psc62                  1/1     Running   0          110m
kube-system    coredns-86c58d9df4-wkhvc                  1/1     Running   0          105m
kube-system    etcd-edge-fabric-3                        1/1     Running   0          5h38m
kube-system    kube-apiserver-edge-fabric-3              1/1     Running   0          5h38m
kube-system    kube-controller-manager-edge-fabric-3     1/1     Running   0          5h38m
kube-system    kube-flannel-ds-amd64-hmw2q               1/1     Running   0          5h37m
kube-system    kube-flannel-ds-amd64-rtz9v               1/1     Running   0          5h38m
kube-system    kube-flannel-ds-amd64-rwg54               1/1     Running   0          5h37m
kube-system    kube-flannel-ds-amd64-snmbb               1/1     Running   0          5h37m
kube-system    kube-flannel-ds-amd64-zpcqp               1/1     Running   0          5h37m
kube-system    kube-proxy-4vhtt                          1/1     Running   0          5h37m
kube-system    kube-proxy-8mbzp                          1/1     Running   0          5h37m
kube-system    kube-proxy-l8sdx                          1/1     Running   0          5h37m
kube-system    kube-proxy-mb7d5                          1/1     Running   0          5h38m
kube-system    kube-proxy-ng99z                          1/1     Running   0          5h37m
kube-system    kube-scheduler-edge-fabric-3              1/1     Running   0          5h38m
kube-system    kubernetes-dashboard-57df4db6b-vx2vw      1/1     Running   0          5h31m
kube-system    tiller-deploy-5b7c66d59c-ztcm7            1/1     Running   0          3h59m

kubectl log istio-sidecar-injector-5d8dd9448d-fhzrb -n istio-system
log is DEPRECATED and will be removed in a future version. Use logs instead.
2019-03-13T00:23:52.984749Z     info    version root@464fc845-2bf8-11e9-b805-0a580a2c0506-docker.io/istio-1.0.6-98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2-dirty-Modified
2019-03-13T00:23:52.988797Z     info    New configuration: sha256sum 887ee5353df9830b6373ae05229afb516bf36d2c0f8f9d949f7438088301e192
2019-03-13T00:23:52.988832Z     info    Policy: enabled
2019-03-13T00:23:52.988858Z     info    Template: |
  initContainers:
  - name: istio-init
    image: "docker.io/istio/proxy_init:1.0.6"
    args:
    - "-p"
    - [[ .MeshConfig.ProxyListenPort ]]
    - "-u"
    - 1337
    - "-m"
    - [[ annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode ]]
    - "-i"
    - "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeOutboundIPRanges`  "10.244.0.0/16"  ]]"
    - "-x"
    - "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/excludeOutboundIPRanges`  ""  ]]"
    - "-b"
    - "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (includeInboundPorts .Spec.Containers) ]]"
    - "-d"
    - "[[ excludeInboundPort (annotation .ObjectMeta `status.sidecar.istio.io/port`  0 ) (annotation .ObjectMeta `traffic.sidecar.istio.io/excludeInboundPorts`  "" ) ]]"
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    restartPolicy: Always
  containers:
  - name: istio-proxy
    image: [[ annotation .ObjectMeta `sidecar.istio.io/proxyImage`  "docker.io/istio/proxyv2:1.0.6"  ]]

    ports:
    - containerPort: 15090
      protocol: TCP
      name: http-envoy-prom

    args:
    - proxy
    - sidecar
    - --configPath
    - [[ .ProxyConfig.ConfigPath ]]
    - --binaryPath
    - [[ .ProxyConfig.BinaryPath ]]
    - --serviceCluster
    [[ if ne "" (index .ObjectMeta.Labels "app") -]]
    - [[ index .ObjectMeta.Labels "app" ]]
    [[ else -]]
    - "istio-proxy"
    [[ end -]]
    - --drainDuration
    - [[ formatDuration .ProxyConfig.DrainDuration ]]
    - --parentShutdownDuration
    - [[ formatDuration .ProxyConfig.ParentShutdownDuration ]]
    - --discoveryAddress
    - [[ annotation .ObjectMeta `sidecar.istio.io/discoveryAddress` .ProxyConfig.DiscoveryAddress ]]
    - --discoveryRefreshDelay
    - [[ formatDuration .ProxyConfig.DiscoveryRefreshDelay ]]
    - --zipkinAddress
    - [[ .ProxyConfig.ZipkinAddress ]]
    - --connectTimeout
    - [[ formatDuration .ProxyConfig.ConnectTimeout ]]
    - --proxyAdminPort
    - [[ .ProxyConfig.ProxyAdminPort ]]
    [[ if gt .ProxyConfig.Concurrency 0 -]]
    - --concurrency
    - [[ .ProxyConfig.Concurrency ]]
    [[ end -]]
    - --controlPlaneAuthPolicy
    - [[ annotation .ObjectMeta `sidecar.istio.io/controlPlaneAuthPolicy` .ProxyConfig.ControlPlaneAuthPolicy ]]
  [[- if (ne (annotation .ObjectMeta `status.sidecar.istio.io/port`  0 ) "0") ]]
    - --statusPort
    - [[ annotation .ObjectMeta `status.sidecar.istio.io/port`  0  ]]
    - --applicationPorts
    - "[[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/applicationPorts` (applicationPorts .Spec.Containers) ]]"
  [[- end ]]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: ISTIO_META_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ISTIO_META_INTERCEPTION_MODE
      value: [[ or (index .ObjectMeta.Annotations "sidecar.istio.io/interceptionMode") .ProxyConfig.InterceptionMode.String ]]
    [[ if .ObjectMeta.Annotations ]]
    - name: ISTIO_METAJSON_ANNOTATIONS
      value: |
             [[ toJson .ObjectMeta.Annotations ]]
    [[ end ]]
    [[ if .ObjectMeta.Labels ]]
    - name: ISTIO_METAJSON_LABELS
      value: |
             [[ toJson .ObjectMeta.Labels ]]
    [[ end ]]
    imagePullPolicy: IfNotPresent
    [[ if (ne (annotation .ObjectMeta `status.sidecar.istio.io/port`  0 ) "0") ]]
    readinessProbe:
      httpGet:
        path: /healthz/ready
        port: [[ annotation .ObjectMeta `status.sidecar.istio.io/port`  0  ]]
      initialDelaySeconds: [[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/initialDelaySeconds`  1  ]]
      periodSeconds: [[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/periodSeconds`  2  ]]
      failureThreshold: [[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/failureThreshold`  30  ]]
    [[ end -]]securityContext:

      readOnlyRootFilesystem: true
      [[ if eq (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) "TPROXY" -]]
      capabilities:
        add:
        - NET_ADMIN
      runAsGroup: 1337
      [[ else -]]
      runAsUser: 1337
      [[ end -]]
    restartPolicy: Always
    resources:
      [[ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) -]]
      requests:
        cpu: "[[ index .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU` ]]"
        memory: "[[ index .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory` ]]"
    [[ else -]]
      requests:
        cpu: 10m

    [[ end -]]
    volumeMounts:
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /etc/certs/
      name: istio-certs
      readOnly: true
  volumes:
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - name: istio-certs
    secret:
      optional: true
      [[ if eq .Spec.ServiceAccountName "" -]]
      secretName: istio.default
      [[ else -]]
      secretName: [[ printf "istio.%s" .Spec.ServiceAccountName ]]
      [[ end -]]

kubectl log istio-galley-685bb48846-qjpv7 -n istio-system
log is DEPRECATED and will be removed in a future version. Use logs instead.
2019-03-13T00:19:14.913125Z     info    server-side configuration validation enabled
2019-03-13T00:19:19.916111Z     info    istio-galley validatingwebhookconfiguration (re)loaded:
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  labels:
    app: istio-galley
    chart: galley-1.0.6
    heritage: Tiller
    release: istio
  name: istio-galley
  namespace: istio-system
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: istio-galley
    uid: 9ada3bd8-4525-11e9-a989-ac162d85318c
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1VENDQWMyZ0F3SUJBZ0lRS0Jad2dzbDVsNDgzd3ZNTkFjdzNHekFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFLRXhGck9ITXVZMngxYzNSbGNpNXNiMk5oYkRBZUZ3MHhPVEF6TVRJeU1qTTBNREZhRncweQpNREF6TVRFeU1qTTBNREZhTUJ3eEdqQVlCZ05WQkFvVEVXczRjeTVqYkhWemRHVnlMbXh2WTJGc01JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdRcmphNTdHQW11MHZDR2NrRjJoOWE5T2xrRDYKc2dKbjBPTitsQllZQ0swb3pqVDJ2RTNaQjc0V1NTQ3lTVHlRUWVHazh6QkxTUHV0QmZ3OXlRL0JLTm52dGsxLwpBcHhybGs5eUtDSlorSis0ZEVCM0FXY084WS9pSjBKQ1YwYnJEZmt5RjhHSFpSSmhtQ3BqQVNlcURxMWxpSUdoCkpBMVNER21IbXlZVVovYS9QOEczN3psU2R3UytPRDNqUDRmRk5ISmp6YVQzTGd1dHhOTmxlRmM2SGxBcTZXUVoKRzNxa212TE0xUG5lL09ESklYTmxzbDZRR0c5TXIzRUpVRVUxQStSQWtrN2VyYjZ3bGhwMzFVMGZFU3RoWUg5VwpSNEpkTTZxZmhTczlZT0hrT0pTdllZWS9EdFlBWkh2R1o1dTU5QTgzcFFhQklJZkF5dHgzUXByYlh3SURBUUFCCm95TXdJVEFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEIKQVFzRkFBT0NBUUVBRVBBY0dlbkJNeE0wUHI2bDErSXZ4cVZxMWJXU2dHYnlnZWNjTkp0cTc4WDlMRGgyVFYzawpNOVJMSzlJS2pZNFpIeEFWWFpnRzE1eEpPbDl0UDJ4SFM4RnBNSlNJMG50cncxRndJenVLQTRZV29XYklkdkRrCnZnQlNveTBtVk1JRDlDSnlMekJqbEw0VFg1dFB2Mmx4U2lPK1hva2ZpQUg5OEJPWlE5YVlvS3JzM1ZlT3hDVjAKZ21IRndnOU9OdnR4MFFVMVNJcVhCZzYvWmdyUFhtV25GRnZxbW0yMjFua3BEYzUrQmhmZjdCVlRJeTNtLy9JOAo5TllGUThVbGU2K0lZM0dMMWJqTGN4VStudDdVQUdGMHBYWm8yNUFQK1k4YWt0d2psSHFLSHl2MjhlZkRxY0p2Ck5QVzAvc2pRejZtcWFuVkNkNklpelp4c2FSand3RlpjZGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: istio-galley
      namespace: istio-system
      path: /admitpilot
  failurePolicy: Fail
  name: pilot.validation.istio.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - config.istio.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - httpapispecs
    - httpapispecbindings
    - quotaspecs
    - quotaspecbindings
  - apiGroups:
    - rbac.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
  - apiGroups:
    - authentication.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
  - apiGroups:
    - networking.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - destinationrules
    - envoyfilters
    - gateways
    - serviceentries
    - virtualservices
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1VENDQWMyZ0F3SUJBZ0lRS0Jad2dzbDVsNDgzd3ZNTkFjdzNHekFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFLRXhGck9ITXVZMngxYzNSbGNpNXNiMk5oYkRBZUZ3MHhPVEF6TVRJeU1qTTBNREZhRncweQpNREF6TVRFeU1qTTBNREZhTUJ3eEdqQVlCZ05WQkFvVEVXczRjeTVqYkhWemRHVnlMbXh2WTJGc01JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdRcmphNTdHQW11MHZDR2NrRjJoOWE5T2xrRDYKc2dKbjBPTitsQllZQ0swb3pqVDJ2RTNaQjc0V1NTQ3lTVHlRUWVHazh6QkxTUHV0QmZ3OXlRL0JLTm52dGsxLwpBcHhybGs5eUtDSlorSis0ZEVCM0FXY084WS9pSjBKQ1YwYnJEZmt5RjhHSFpSSmhtQ3BqQVNlcURxMWxpSUdoCkpBMVNER21IbXlZVVovYS9QOEczN3psU2R3UytPRDNqUDRmRk5ISmp6YVQzTGd1dHhOTmxlRmM2SGxBcTZXUVoKRzNxa212TE0xUG5lL09ESklYTmxzbDZRR0c5TXIzRUpVRVUxQStSQWtrN2VyYjZ3bGhwMzFVMGZFU3RoWUg5VwpSNEpkTTZxZmhTczlZT0hrT0pTdllZWS9EdFlBWkh2R1o1dTU5QTgzcFFhQklJZkF5dHgzUXByYlh3SURBUUFCCm95TXdJVEFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEIKQVFzRkFBT0NBUUVBRVBBY0dlbkJNeE0wUHI2bDErSXZ4cVZxMWJXU2dHYnlnZWNjTkp0cTc4WDlMRGgyVFYzawpNOVJMSzlJS2pZNFpIeEFWWFpnRzE1eEpPbDl0UDJ4SFM4RnBNSlNJMG50cncxRndJenVLQTRZV29XYklkdkRrCnZnQlNveTBtVk1JRDlDSnlMekJqbEw0VFg1dFB2Mmx4U2lPK1hva2ZpQUg5OEJPWlE5YVlvS3JzM1ZlT3hDVjAKZ21IRndnOU9OdnR4MFFVMVNJcVhCZzYvWmdyUFhtV25GRnZxbW0yMjFua3BEYzUrQmhmZjdCVlRJeTNtLy9JOAo5TllGUThVbGU2K0lZM0dMMWJqTGN4VStudDdVQUdGMHBYWm8yNUFQK1k4YWt0d2psSHFLSHl2MjhlZkRxY0p2Ck5QVzAvc2pRejZtcWFuVkNkNklpelp4c2FSand3RlpjZGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: istio-galley
      namespace: istio-system
      path: /admitmixer
  failurePolicy: Fail
  name: mixer.validation.istio.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - config.istio.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - rules
    - attributemanifests
    - circonuses
    - deniers
    - fluentds
    - kubernetesenvs
    - listcheckers
    - memquotas
    - noops
    - opas
    - prometheuses
    - rbacs
    - servicecontrols
    - solarwindses
    - stackdrivers
    - statsds
    - stdios
    - apikeys
    - authorizations
    - checknothings
    - listentries
    - logentries
    - metrics
    - quotas
    - reportnothings
    - servicecontrolreports
    - tracespans

2019-03-13T00:19:19.932403Z     info    istio-galley validatingwebhookconfiguration updated

**Comment by ctonur** [comment] 2019-05-20 21:40
hi,

have you found any solution ?

**Comment by simox-83** [comment] 2019-05-31 07:00
@JungukCho were you able to solve your issue? I am hitting the same problem..

**Comment by howardjohn** [comment] 2019-06-03 17:20
Seems to be a dupe of https://github.com/istio/istio/issues/7233. There is some more info there that may help

**Closed by howardjohn** 2019-06-03 17:20 UTC

**Comment by JungukCho** [comment] 2019-06-20 07:54
@ctonur, @simox-83, after setting up below env variable **(.svc)**, it worked.
export no_proxy=other ip addresses,**.svc**
