### ISSUE TITLE
Consistent Hashing not consistent across proxies when Outlier Detection enabled

### ISSUE THREAD

**Issue by stvleung** [istio/istio#41674] opened 2022-10-27 20:58 UTC
### Bug Description

I'm trying to implement session affinity/sticky session via ConsistentHash in an Istio DestinationRule TrafficPolicy, whether via `useSourceIp`, `httpHeaderName`, or `httpCookie`. Traffic will be coming in from outside of the service mesh via a Gateway and load balanced to a Deployment of multiple replicas of Pods. While it worked initially, after some time, Istio seems to enter some state in which traffic gets distributed to two different pods.

Upon research, I discovered istio/istio#27466. I attempted to reproduce by scaling the number of replicas for my ingress gateway down to 1. Indeed the issue can no longer be reproduced.

I tried to track down what exactly leads to this situation, so I created a new EKS 1.23 cluster and installed Istio 1.15.2. I enabled Envoy access logging. Please see my attached configuration:
[istio-operator-1.15.2.yaml.zip](https://github.com/istio/istio/files/9883070/istio-operator-1.15.2.yaml.zip)

Then I created a simple "app" with `nginx`, which simply responds to all HTTP requests with a JSON containing various information, including Pod name (`$hostname` according to `nginx`). I then ran a script that simply repetitively `curl` the `nginx` app at the LoadBalancer Service URL (a Classic ELB address). I scaled up both the `nginx` app and the ingress gateway to 10 replicas. Please refer to my attached app configuration:
[myapp.zip](https://github.com/istio/istio/files/9883073/myapp.zip)

After some fiddling, I discovered that if I remove the `outlierDetection` configuration from the DestinationRule, the traffic will consistently be routed to a single Pod, according to Envoy access logs and the JSON response from the `nginx` app.  Setting any of the parameters, `consecutiveLocalOriginFailures`, `consecutiveGatewayErrors`, or `consecutive5xxErrors` would cause the traffic be routed to two Pods, therefore breaking session affinity.

### Version

```prose
$ istioctl version
client version: 1.15.2
control plane version: 1.15.2
data plane version: 1.15.2 (20 proxies)
$ kubectl version --short
Client Version: v1.23.10
Server Version: v1.23.10-eks-15b7512
$ helm version --short
v3.10.1+g9f88ccb
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/9883075/bug-report.tar.gz)

```
$ istioctl --context usw2stage bug-report        

Target cluster context: usw2stage
Running with the following config: 

context: usw2stage
istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-10-27 16:48:04.363801 -0400 EDT



Cluster endpoint: https://6D583AAAC619906E7CA70D8127D5509A.gr7.us-west-2.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.15.2", GitRevision:"b542583af7f8240ad0c9cab56eb9f8d55e1357ab-dirty", GolangVersion:"go1.19.2", BuildStatus:"Clean", GitTag:"1.15.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.2", GitRevision:"b542583af7f8240ad0c9cab56eb9f8d55e1357ab", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.15.2"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.2", GitRevision:"b542583af7f8240ad0c9cab56eb9f8d55e1357ab", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.15.2"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.2", GitRevision:"b542583af7f8240ad0c9cab56eb9f8d55e1357ab", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.15.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.15.2}


Fetching proxy logs for the following containers:

default/myapp/myapp-5979b857c5-259zr/istio-proxy
default/myapp/myapp-5979b857c5-259zr/nginx
default/myapp/myapp-5979b857c5-4w54c/istio-proxy
default/myapp/myapp-5979b857c5-4w54c/nginx
default/myapp/myapp-5979b857c5-8hn9l/istio-proxy
default/myapp/myapp-5979b857c5-8hn9l/nginx
default/myapp/myapp-5979b857c5-8thm4/istio-proxy
default/myapp/myapp-5979b857c5-8thm4/nginx
default/myapp/myapp-5979b857c5-dgl4s/istio-proxy
default/myapp/myapp-5979b857c5-dgl4s/nginx
default/myapp/myapp-5979b857c5-dlzmw/istio-proxy
default/myapp/myapp-5979b857c5-dlzmw/nginx
default/myapp/myapp-5979b857c5-kpqkq/istio-proxy
default/myapp/myapp-5979b857c5-kpqkq/nginx
default/myapp/myapp-5979b857c5-lp29w/istio-proxy
default/myapp/myapp-5979b857c5-lp29w/nginx
default/myapp/myapp-5979b857c5-mvmzq/istio-proxy
default/myapp/myapp-5979b857c5-mvmzq/nginx
default/myapp/myapp-5979b857c5-q9f7k/istio-proxy
default/myapp/myapp-5979b857c5-q9f7k/nginx
istio-system//istio-cni-node-5ztcn/install-cni
istio-system//istio-cni-node-gz72w/install-cni
istio-system//istio-cni-node-hjwtn/install-cni
istio-system//istio-cni-node-kl4tv/install-cni
istio-system//istio-cni-node-l69hw/install-cni
istio-system//istio-cni-node-lwsb6/install-cni
istio-system//istio-cni-node-mlntt/install-cni
istio-system//istio-cni-node-n748w/install-cni
istio-system//istio-cni-node-qsvln/install-cni
istio-system//istio-cni-node-x8nh2/install-cni
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-5nl5g/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-b5t7h/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-bvkt9/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-gmktx/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-mrq9l/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-ncrd8/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-qkgkr/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-qqjzn/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-s8mt5/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c4465ccf-xzq69/istio-proxy
istio-system/istiod/istiod-9b6c6995c-hz6dk/discovery
istio-system/istiod/istiod-9b6c6995c-v77zd/discovery
istio-system/istiod/istiod-9b6c6995c-wg8nq/discovery
karpenter/karpenter/karpenter-7856bd49f9-gmkcr/controller
karpenter/karpenter/karpenter-7856bd49f9-gmkcr/webhook
karpenter/karpenter/karpenter-7856bd49f9-mddlp/controller
karpenter/karpenter/karpenter-7856bd49f9-mddlp/webhook

Fetching Istio control plane information from cluster.

The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,awsnodetemplates.karpenter.k8s.aws,bgpconfigurations.crd.projectcalico.org,bgppeers.crd.projectcalico.org,blockaffinities.crd.projectcalico.org,caliconodestatuses.crd.projectcalico.org,clusterinformations.crd.projectcalico.org,destinationrules.networking.istio.io,eniconfigs.crd.k8s.amazonaws.com,envoyfilters.networking.istio.io,felixconfigurations.crd.projectcalico.org,gateways.networking.istio.io,globalnetworkpolicies.crd.projectcalico.org,globalnetworksets.crd.projectcalico.org,hostendpoints.crd.projectcalico.org,ipamblocks.crd.projectcalico.org,ipamconfigs.crd.projectcalico.org,ipamhandles.crd.projectcalico.org,ippools.crd.projectcalico.org,ipreservations.crd.projectcalico.org,istiooperators.install.istio.io,kubecontrollersconfigurations.crd.projectcalico.org,networkpolicies.crd.projectcalico.org,networksets.crd.projectcalico.org,peerauthentications.security.istio.io,provisioners.karpenter.sh,proxyconfigs.networking.istio.io,requestauthentications.security.istio.io,securitygrouppolicies.vpcresources.k8s.aws,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,wasmplugins.extensions.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml --context usw2stage
  ProxyGet istio-system/istio-ingressgateway-6c4465ccf-mrq9l:stats/prometheus
  ProxyGet istio-system/istio-ingressgateway-6c4465ccf-qkgkr:stats/prometheus
  ProxyGet default/myapp-5979b857c5-4w54c:stats/prometheus
  ProxyGet default/myapp-5979b857c5-8thm4:stats/prometheus
  ProxyGet istio-system/istio-ingressgateway-6c4465ccf-xzq69:server_info
  ProxyGet istio-system/istio-ingressgateway-6c4465ccf-s8mt5:server_info
  PodExec istio-system/istiod-9b6c6995c-wg8nq/discovery:pilot-discovery request GET debug/configz
  ProxyGet default/myapp-5979b857c5-259zr:stats/prometheus
  ProxyGet istio-system/istio-ingressgateway-6c4465ccf-gmktx:stats/prometheus
  ProxyGet default/myapp-5979b857c5-8hn9l:stats/prometheus

Running istio analyze on all namespaces and report as below:
Analysis Report:

Creating an archive at /Users/sleung/Downloads/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/dj/h31dlwb53ms2jbcjlr5dz28r0000gp/T/bug-report.
Done.
```

**Comment by howardjohn** [comment] 2022-10-27 22:46
Can you check if it's actually outlier detection that is the issue or locality load balancing (which depends on outlierDetection to start being used)? By explicitly turning off locality load balancing

**Comment by stvleung** [comment] 2022-10-28 00:41
Thanks for the tip @howardjohn, it seems you are right. With `localityLbSetting` disabled according to this TrafficPolicy:
```
spec:
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-client-id
      localityLbSetting:
        enabled: false
    outlierDetection:
      consecutive5xxErrors: 5
      baseEjectionTime: 30s
      interval: 10s
```
I get consistent hashing as desired. Once I flip it on
```
spec:
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-client-id
      localityLbSetting:
        enabled: true
    outlierDetection:
      consecutive5xxErrors: 5
      baseEjectionTime: 30s
      interval: 10s
```
traffic gets distributed all over. This is the case even though I don't have `distribute`, `failover`, nor `failoverPriority` defined anywhere.

I've tried flipping it back and forth a few times and was able to consistently get the expected results, ie. `localityLbSetting` disabled allows successful consistent hashing, while `localityLbSetting` enabled leads to traffic getting distributed semi-randomly.

So what's the next step? Is this by design? Consistent hashing in conjunction with outlier detection settings and locality weighted load balancing does seem to be conflict with either other. Although maybe it's a matter of which has higher priority.

**Comment by howardjohn** [comment] 2022-10-28 19:08
Its effectively by design. Basically you can think of each proxy having a list of endpoints, and consistent hashing selecting `endpoints[key % len]`.

With locality LB, the `endpoints` list is ordered by closest endpoints, so while `key%len` will return the same index on each proxy, that means something different.

This should be documented though.

https://github.com/istio/api/pull/2469 is another option once implemented, which encodes the IP address itself (not an index) in a header. It only works for HTTP.

**Comment by stvleung** [comment] 2022-10-28 20:24
Thanks @howardjohn! Well, this is helpful to know at least, so I can work around since I don't actually need Locality LB yet.

I wasn't aware there is a new Stateful Session feature. I believe I can wait for it.

Feel free to close this issue as you deem necessary, or else you can leave it open to document that caveat with Consistent Hashing and Locality LB. Thanks!

**Comment by hzxuzhonghu** [comment] 2022-10-29 01:31
@howardjohn https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash From this it says 
```
When priority based load balancing is in use, the priority level is also chosen by hash, so the endpoint selected will still be consistent when the set of backends is stable.
```

**Comment by howardjohn** [comment] 2022-10-29 01:36
But the priorities are different as well?

**Comment by hzxuzhonghu** [comment] 2022-10-29 01:41
OK, so expected. https://github.com/istio/api/pull/2469 would be a potential solution.

**Comment by ramaraochavali** [comment] 2022-10-31 10:44
yes. I plan to make changes based on labels that we discussed. I am closing this now in favour of that api + implementation support.

**Closed by ramaraochavali** 2022-10-31 10:44 UTC
Labels: area/networking
