### ISSUE TITLE
[ambient] authz port matching not respected

### ISSUE THREAD

**Issue by npolshakova** [istio/istio#41204] opened 2022-09-28 13:58 UTC
### Bug Description

Following the Get Started Ambient [guide](https://istio.io/latest/blog/2022/get-started-ambient/#secure-application-access), it looks like the port match is not respected. 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  generation: 2
  name: productpage-viewer
  namespace: default
  resourceVersion: "20035695"
  uid: 50c8e232-2b6b-4137-b93e-06350502383a
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/default/sa/sleep
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
    to:
    - operation:
        ports:
        - "9080"
  selector:
    matchLabels:
      app: productpage
```

# this is supposed to work
❯ kubectl exec deploy/sleep -- curl -s http://productpage:9080/ | head -n1
command terminated with exit code 52
# this should fail with an empty reply
❯ kubectl exec deploy/notsleep -- curl -s http://productpage:9080/
command terminated with exit code 52

Logs from the ztunnel: 
```
istio-proxy [2022-09-27T18:28:59.313Z] "- - -" 0 - - rbac_access_denied_matched_policy[none] "-" 233 0 1 - "-" "-" "-" "-" "-" - - 10.64.135:15008 10.64.3.51:45702 - - capture inbound listener
```

### Version

```prose
istioctl version
client version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
control plane version: 0.0.0
data plane version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82 (2 proxies)
```

**Comment by ymesika** [comment] 2022-09-29 08:31
Root cause is that the authz network filter is matching port against the ztunnel inbound port (15008) rathar than the original dst port.
This one is being restored only after http termination based on the headers.

Can be validated by setting the policy rule port to `15008` instead.

@howardjohn Just checking whether it's something you were aware of? Is there a way to resolve this without internal listeners?

**Comment by howardjohn** [comment] 2022-09-29 13:14
I was not aware

**Comment by ymesika** [comment] 2022-09-30 08:45
@howardjohn @kyessenov Is there a way to fix this? Or should we just mention this specific case in the limitations of AuthorizationPolicy bullet?

**Comment by howardjohn** [comment] 2022-09-30 13:40
I am not sure off-hand how we should fix this, but it will be a requirement
to go beyond experimental. Will need to think about it more.

**Comment by kyessenov** [comment] 2022-09-30 15:31
I'm not entirely sure what needs to be fixed, but there are really only two ways to go about it:
* apply authz on the tunnel directly;
* apply authz on the decapped streams;

Either way, the policy will not look the same as on the direct path. The control plane needs to generate policy in the context of the decapped streams (or for something like port, on the tunnel directly is more performance). For example, we copy the entire SSL context just to read a SAN, which is very wasteful, and needs to be fixed.

**Comment by ymesika** [comment] 2022-10-03 13:03
@kyessenov not sure how to technically go on each way of the two. Can you please explain?

I would like to throw in an idea I had to get your feedback on it.
I've been experimenting with adding the authz to the captured inbound http filter as well and replacing:
```yaml
to:
    - operation:
        ports:
        - "5000"
```
with:
```yaml
when:
    - key: request.headers[:authority]
      values: ["*:5000"]
```

achieves the same allowance rule but with the last one it is being correctly matched.
Is it a reasoable direction that the control plane will "transform" policy conditions? My guts feeling tells me it's not.

**Comment by dhawton** [comment] 2023-01-13 19:58
Reopening. #41491 is being reverted by #42808 after discussion in #42768. We cannot utilize the `:authority` header to do authz policy port matching as it is easy to override. Conversation: https://github.com/istio/istio/pull/42768#discussion_r1067580705

**Comment by SkyfireFrancisZ** [comment] 2023-01-17 18:16
Daniel will followup with John on this, progress blocked.

**Comment by SkyfireFrancisZ** [comment] 2023-01-23 19:18
done, blocked by integration test before merging

**Comment by dhawton** [comment] 2023-01-31 22:09
Splitting the PRs. https://github.com/istio/istio/pull/42890 will close this issue

**Comment by SkyfireFrancisZ** [comment] 2023-02-06 19:17
feature PR still needs review, John or Lin will provide.

**Comment by SkyfireFrancisZ** [comment] 2023-02-13 19:07
PR merged.

**Comment by SkyfireFrancisZ** [comment] 2023-02-13 19:08
@dhawton please move this to done column once confirmed.

**Comment by SkyfireFrancisZ** [comment] 2023-02-27 19:05
@dhawton, please move this to the Done column if it's completed.

**Closed** 2023-02-27 19:17 UTC
Labels: area/ambient, OSS Alpha, P0
