### ISSUE TITLE
The Istio Reference doc seems to be empty

### ISSUE THREAD

**Issue by stepanv** [istio/istio#908] opened 2017-09-22 19:37 UTC
Navigating to https://istio.io/docs/reference/ I only see the `Reference` heading and one sentence about Reference doc. There is no navigation tree which used to be there I think. There is no way how to continue in reading the Reference docs.

**Comment by ZackButcher** [comment] 2017-09-22 19:39
We're in transition getting docs together for our 0.2 release. Unfortunately as a side-effect we broke the main site. You can find the previous docs at https://istio.io/v-0.1/docs/.

**Comment by ZackButcher** [comment] 2017-09-22 20:21
Closing as "broken as intended" right now - we'll have full docs up for 0.2 in the next few days, and all of the pre-existing docs are still there, if a little hidden.

**Closed by ZackButcher** 2017-09-22 20:21 UTC
