### ISSUE TITLE
Error from server (Timeout): error when creating "STDIN": Timeout: request did not complete within requested timeout 30s

### ISSUE THREAD

**Issue by xiaoyaolaotou** [istio/istio#22899] opened 2020-04-13 10:13 UTC
## istio-system
[root@kvm-10-112-76-53 httpbin]# kubectl get po -n istio-system
NAME                                      READY   STATUS    RESTARTS   AGE
grafana-6c8f45499-djc74                   1/1     Running   0          55m
istio-citadel-58c6fb56fb-8h9zs            1/1     Running   0          55m
istio-egressgateway-75869dcbf6-48pmt      1/1     Running   0          55m
istio-galley-67f97d7c8b-sbv8c             1/1     Running   0          55m
istio-ingressgateway-66cd7b9b8b-pwtxk     1/1     Running   0          55m
istio-pilot-8dcc5647f-6x4sp               1/1     Running   0          55m
istio-policy-68f46f5f89-g92g6             1/1     Running   6          55m
istio-sidecar-injector-678578c6d6-nkp58   1/1     Running   0          55m
istio-telemetry-6cb5b99c7f-p6x8k          1/1     Running   6          55m
istio-tracing-78548677bc-bjn7v            1/1     Running   0          55m
kiali-fb5f485fb-zm6hc                     1/1     Running   0          55m
prometheus-685585888b-zv99j               1/1     Running   0          55m

##istio version
[root@kvm-10-112-76-53 httpbin]# istioctl version
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (2 proxies)

## kubectl version
[root@kvm-10-112-76-53 httpbin]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
[root@kvm-10-112-76-53 httpbin]# 

[root@kvm-10-112-76-53 httpbin]# cat httpbin-gateway.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 8000
[root@kvm-10-112-76-53 httpbin]# 

[root@kvm-10-112-76-53 httpbin]# kubectl apply -f httpbin-gateway.yaml
Error from server (Timeout): error when creating "httpbin-gateway.yaml": Timeout: request did not complete within requested timeout 30s
Error from server (Timeout): error when creating "httpbin-gateway.yaml": Timeout: request did not complete within requested timeout 30s

**Comment by feliperfmarques** [comment] 2020-04-14 02:05
I got same error.

**Comment by xiaoyaolaotou** [comment] 2020-04-14 02:07
> I got same error.

How did you solve？

**Comment by feliperfmarques** [comment] 2020-04-14 02:10
Sorry, I has deleted my previous comment, because I received this error in installation process and I think that is not your case.

**Comment by richardmcsong** [comment] 2020-04-14 20:05
@feliperfmarques was your issue related to #22944 ?

**Comment by feliperfmarques** [comment] 2020-04-14 22:08
@richardmcsong I think so. I have comment there https://github.com/istio/istio/issues/22944#issuecomment-613701732

**Comment by feliperfmarques** [comment] 2020-04-16 08:52
This issue can also to be a problem of webhook validation. For webhook works, firewall rule needs setting to port 15017 instead of 9443 on Istio 1.5, as mentioned here #19532 (comment). Try add this firewall rule.

**Comment by howardjohn** [comment] 2020-08-04 22:55
I think this is a duplicate of https://github.com/istio/istio/issues/22944#issuecomment-613701732 https://github.com/istio/istio/issues/19532. Lets track there. Thanks!

**Closed by howardjohn** 2020-08-04 22:55 UTC
Labels: lifecycle/needs-triage
