### ISSUE TITLE
Some ingress gateway instances may be inactive.

### ISSUE THREAD

**Issue by jnativio** [istio/istio#10904] opened 2019-01-11 21:05 UTC
**Describe the bug**
The results of regression patrol have been flaky since beginning of December. There are connection errors at the start of each run (rg.apache.http.conn.HttpHostConnectException), some jmeter clients are terminated, and in the worst case, all are terminated.  I noticed that only some of the ingress gateway replicas (spawned after hpa kicks in) are taking traffic and others are idle. The idle ones are stuck in such a state that they will never accept requests.
Another way to simulate the problem is to disable horizontal scaling for ingress gateway and delete the single replica. Sometimes the new one comes up okay, sometimes not and in this case, no traffic can go through it. 
When the ingress-gw instance does not work, its log stays stuck in this warning message: 
```
[2019-01-11 20:27:35.535][000019][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, no healthy upstream
[2019-01-11 20:27:35.535][000019][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:51] Unable to establish new stream
```
while the one that works continues with:
```
[2019-01-11 20:27:36.455][000019][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2019-01-11 20:27:36.456][000019][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2019-01-11 20:27:36.457][000019][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
```
**Expected behavior**
All ingress gateway replicas should be taking traffic.

**Steps to reproduce the bug**
Drive traffic through a ingress gateway cause scale out. Stop and restart traffic and verify that not all instances are active.

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
Istio Version:"release-1.1-20190107-09-15"
K8s version: 1.10.11_1538

**Installation**
{{ Please describe how Istio was installed }}
Helm chart

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
IKS

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
[ingressgateway.log](https://github.com/istio/istio/files/2751134/ingressgateway.log)

**Comment by mandarjog** [comment] 2019-01-14 19:57
Can you clarify what you mean by active.
Are they not ready per k8s or they are simply not receiving any traffic ?

**Comment by jnativio** [comment] 2019-01-14 20:17
I meant by inactive, the instances that do not take any traffic. They appear as Running status in the kubectl command, but they seem to be stuck in such state that they are not functional.

**Comment by jnativio** [comment] 2019-01-14 21:45
I restarted Pilot in the situation where I had 5 ingress-gateway replicas but some of them were "inactive". After the new Pilot instance came up, all 5 ingress-gw replicas were taking traffic.

**Comment by mandarjog** [comment] 2019-01-16 00:08
@jwendell can you investigate this ?
Some ingresses are not getting any traffic so it could either be an issue with the cloud provider LB or pilot itself. After pilot is restarted all ingresses start receiving traffic.

@jnativio is this problem repeatable ?

**Comment by mandarjog** [comment] 2019-01-16 00:09
@linsun can you have someone from IBM look at this problem?

**Comment by mandarjog** [comment] 2019-01-16 22:00
Do you use LB health checks? 
We expect `2019-01-16T19:13:08.656329Z     info    Envoy proxy is ready` message to show up in the logs.

**Comment by jnativio** [comment] 2019-01-17 15:06
@mandarjog I am afraid I did not understand your question. Where is this log message? 
The http requests are directed to the public ip/ port of the ingressgateway service, which is type Load Balancer, e.g.:
istio-ingressgateway     LoadBalancer   10.10.10.176   169.46.63.219   80:31380/TCP

**Comment by linsun** [comment] 2019-01-17 18:04
@GregHanson do you have bandwidth to check this out?  let me know!

**Comment by nixgadget** [comment] 2019-01-23 11:30
I certainly have seen this happening as well with `1.1.0-snapshot.4`
Despite of the gateway deployed correctly and running looking at the listening ports `80` is missing.

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      51/envoy
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      51/envoy
tcp        0      0 192.168.8.139:33730     10.100.47.201:15011     ESTABLISHED 51/envoy
```

**Comment by jnativio** [comment] 2019-01-23 14:36
@GregHanson Thanks for the investigation. I can confirm that I see the same but in my case the problem occurs all the time, like in the case below where 4 out the 5 ingressgateway instances are "dead":

`root@dal10-vsi1:/mount/may# /mount/istio_regpatrol/istio-1.1.0-snapshot.4/bin/istioctl proxy-status
Warning! error execing into istio-pilot-684c86bdfd-5vjhm/istio-system discovery container: gc 1 @0.058s 3%: 0.025+3.3+1.4 ms clock, 0.10+0.23/1.7/0.097+5.7 ms cpu, 4->4->1 MB, 5 MB goal, 4 P
gc 2 @0.081s 4%: 0.055+1.2+1.4 ms clock, 0.22+0.18/1.0/1.1+5.8 ms cpu, 4->4->2 MB, 5 MB goal, 4 P`

`NAME                                                  CDS        LDS        EDS               RDS          PILOT                            VERSION
auth-7d5d8549c-wgxdt.default                          SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-684c86bdfd-5vjhm     1.1.0
booking-779cc5ccf5-khsbd.default                      SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-684c86bdfd-5vjhm     1.1.0
customer-66c587d555-cq84b.default                     SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-684c86bdfd-5vjhm     1.1.0
flight-59f6c558d7-xmjh9.default                       SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-684c86bdfd-5vjhm     1.1.0
istio-egressgateway-665b6667c4-7qcrz.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-684c86bdfd-5vjhm     1.1.0
istio-ingressgateway-dcb75c76f-dxwqh.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-684c86bdfd-5vjhm     1.1.0
istio-ingressgateway-dcb75c76f-fkxqp.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-684c86bdfd-5vjhm     1.1.0
istio-ingressgateway-dcb75c76f-hgqwm.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-684c86bdfd-5vjhm     1.1.0
istio-ingressgateway-dcb75c76f-lfldx.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-684c86bdfd-5vjhm     1.1.0
istio-ingressgateway-dcb75c76f-w2wcd.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-684c86bdfd-5vjhm     1.1.0
main-764dd48c5-dcp5l.default                          SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-684c86bdfd-5vjhm     1.1.0`

Good replica:
`root@dal10-vsi1:/mount/may# kubectl exec -it -n istio-system istio-ingressgateway-dcb75c76f-hgqwm -- curl localhost:15000/listeners
["0.0.0.0:15090","0.0.0.0:15029","0.0.0.0:15032","0.0.0.0:80"]`

Bad replica:
`root@dal10-vsi1:/mount/may# kubectl exec -it -n istio-system istio-ingressgateway-dcb75c76f-lfldx -- curl localhost:15000/listeners
["0.0.0.0:15090"]`

Restarting Pilot fix the problem.

**Comment by GregHanson** [comment] 2019-01-23 18:05
@mandarjog please observe my steps in https://github.com/istio/istio/issues/10904#issuecomment-456605277

**Comment by mandarjog** [comment] 2019-01-23 19:57
@GregHanson @jnativio can you guys upload logs from pilot, galley and ingress gateways ?

**Comment by GregHanson** [comment] 2019-01-23 20:13
@mandarjog here are the logs:
https://gist.github.com/GregHanson/0ff0ab351db063175429448e72aaedef

**Comment by nixgadget** [comment] 2019-01-23 22:09
Just killing the pilot may not be sufficient as I found out that the ingress gateway needed to be killed as well.

For me this seems to be happening every time the `gateway` config is published.

**Comment by linsun** [comment] 2019-01-24 15:43
looking at the logs I saw an error connecting to MCP:

```2019-01-23T17:26:12.660128Z error mcp Failed to create a new MCP stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.21.52.14:9901: connect: connection timed out"```

**Comment by mandarjog** [comment] 2019-01-31 18:46
@costinm @munrodg someone needs to do next level of debugging here.
If this is being hit so frequently, we want to make it P0. @jnativio sees this is latest regpatrols.

@ayj does   the latest 1.1 build have mcp enabled by default?

**Comment by GregHanson** [comment] 2019-02-15 22:09
I have found that in at least the case for LDS, gateways on startup don’t receive the correct config from Gateway rules because the pods do not have the correct labels.  Turns out, when pilot gets to the gateway logic, for comparing labels of the pod with gateway selector, the instance occasionally won’t have any labels: https://github.com/istio/istio/blob/release-1.1/pilot/pkg/model/config.go#L697 Almost like the registry pulled a service and converted it before its labels were applied.
I originally thought a XDS update was getting dropped somewhere, but turns out we are just generating a bad config because the labels don’t match for some reason
```
2019-02-15T14:37:57.653647Z    info    workload labels [] did not match gatewayselector istio=ingressgateway
2019-02-15T14:37:57.653750Z    debug    buildGatewayListeners: no gateways for router istio-ingressgateway-6cf4d5cdb7-nfh6j.istio-system labels []
2019-02-15T14:37:57.653915Z    info    ads    LDS: PUSH for node:istio-ingressgateway-6cf4d5cdb7-nfh6j.istio-system addr:"172.30.142.146:50918" listeners:0 106
```
the `/healthz/ready` probe passes because behind the scenes, it calls the local envoy `/stats` API and checks for CDS and LDS success messages.  This check passes because it has received those updates but they are incomplete because the labels didn’t match

I had to add some additional logs in `pilot/pkg/model/config.go Gateways()` method to capture the error.  My images are available if anyone is interested in reproducing using the steps documented in my previous comment: `--set global.hub=gihanson --set global.tag=021419-3`

**Comment by linsun** [comment] 2019-02-18 02:54
@ymesika could you look at this issue and see if you have any ideas?  Greg also tried to run the tests with useMCP=false and same result.

**Comment by ymesika** [comment] 2019-02-18 16:19
See https://github.com/istio/istio/pull/11816#discussion_r257745665 for suggested directions to fix this.

**Comment by ayj** [comment] 2019-02-19 21:27
> @ayj does the latest 1.1 build have mcp enabled by default?

Yes, MCP was enabled by default in release-1.1 on 2018-12-03 (see https://github.com/istio/istio/pull/10222).

> I checked past results in the regression patrol and the last daily builds without this problem were release-1.1-20181120-09-15 for 1.1 branch and master-20181127-09-15 for master branch.

release-1.1-20181120-09-15 corresponds to e8bccd2e9bfe18d86becb795a8b8278275010336 / https://github.com/istio/istio/pull/10049.

https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-20181129-09-15 should be the first release with this regression. That corresponds to commit 0770d7aba62f3608a3b2ce3762c9b10d2d7a09ce / https://github.com/istio/istio/pull/10184.

The following changes were introduced between those releases (see below).

```bash
$ git log e8bccd2e9bfe18d86becb795a8b8278275010336..0770d7aba62f3608a3b2ce3762c9b10d2d7a09ce --pretty=format:"%h%x09%an%x09%x09%s"
0770d7aba       Douglas Reid            Update bootstrap config to use stats_matcher to filter metrics gen (#10184)
25e5644e0       Zhonghu Xu              bump istio/api to include networkscope (#10187)
c725141e4       Andy Lai                Disable verbosity for PR head and base tests (#10183)
4103c230a       Andy Lai                Adding test retry to codecov job (#10156)
eefab86bb       Douglas Reid            Alter mixer redisquota e2e tests in attempt to deflake behaviour (#10171)
9cd4a06d3       Andy Lai                Fix linter (#10173)
78db68197       Douglas Reid            Add support for mongo metrics in envoy bootstrap (#9974)
e8de706b2       Douglas Reid            Add initial metrics for tracking tcp conn open/close (#9648)
60f9c35f0       Alberto Gutierrez               Update Jaeger to version 1.8 (#10162)
63903943d       Andy Lai                Revert "Implementation to enable TCP keepalive configuration." (#10157)
3e4a5503c       Andy Lai                Adding metric support to codecov job (#10137)
2205d021b       Venil Noronha           Enable Redis CDS (#9917)
75153eb2e       Ivan Mikushin           Import cluster local ExternalName services (#9975)
e3653d5a8       istio-bot               Update_Dependencies (#10146)
d5cb616b6       Shakti Das              Implementation to enable TCP keepalive configuration. (#10102)
38979786a       Martin Ostrowski                Limit dump size, add namespace and label flags (#10022)
3b6edd671       Yossi Mesika            Allow choosing only mixer policy enabled (#10144)
ff20fff27       Chunlin Yang            Fix citadel sync issue (#10067)
38183709e       Itay Shakury            Fix request/response header validation (#10121)
edc5e22df       Zhonghu Xu              simplify RDS and EDS request process (#10113)
79f125b59       Zhonghu Xu              remove PILOT_CACHE_SQUASH env parse (#10145)
121ea871e       Zhonghu Xu              only updateEDS when endpoint resource update (#10143)
6e5b3bcc4       Morven Cao              fix if conditions in gateways. (#10142)
d4e83c0e5       Zhonghu Xu              remove duplicate line (#10125)
88c232da8       Chunlin Yang            Fixed https://github.com/istio/istio/issues/9880 (#9924)
793d0a453       Chunlin Yang            replace proxy_name with pod_name (#9958)
8bebdb326       Andy Lai                Revert https://github.com/istio/istio/pull/10066 (#10135)
9f976cca1       Andy Lai                Update codecov threshold due to non-deterministism (#10132)
15ce59f4d       Lin Sun         fix spelling error (#10131)
2f31c1816       Jason Young             Improve robustness of validation readiness checks in galley and test framework (#9871)
b4751e04e       Zhonghu Xu              secure grpc server start clean (#10004)
0952b19ef       Zhonghu Xu              misc fix for discovery server (#10065)
5e79abb5f       Yossi Mesika            Fixed incorrect event name for delete (#10104)
7cd97193d       Yossi Mesika            Increase the test-integration-kubernetes test timeout from 10m to 15m (#10106)
4f5c58e41       Zhonghu Xu              Set Locality (#10099)
cdeb27719       Jason Young             Fix replica count field inkiali helm deployment template (#10089)
05a0f9e24       Krishna Pagadala                remove old code that assumes tag were created before building (#10095) (#10097)
fc352e3f2       Andy Lai                Adding codecov threshold file (#10085)
33d7cb1f5       Jimmy Chen              Update Proxy SHA and go-control-plane (#9915) (#10093)
ca67fe3e6       Venil Noronha           pilot: add support for grpc-web prefixed ports (#10064)
60e6e9b58       Yossi Mesika            Post-merge review addressed (#10071)
4ad050248       Pengyuan Bian           make target for mixer codegen (#8602)
1e2a83bdf       Gregory Hanson          switch naming convention and behavior for access log format vs encoding (#10074)
2bb3950b8       Andy Lai                codecov job update (#10078)
75977a465       Yossi Mesika            Allow adding gateway to istio remote + updates to Helm networks values (#9986)
256da0176       Zhonghu Xu              SNI dnat cleanup (#10046)
ddf993e6e       Andy Lai                Update upgrade test to remove hard-coded 1.1 reference (#10066)
f9fe4797d       Yossi Mesika            Remove empty unused file (#10073)
53562f50c       john-a-joyce            Fixes flaky secret controller unit tests (#10055)
```

**Comment by munrodg** [comment] 2019-02-27 00:30
@GregHanson anything left to be done on this issue?

**Comment by GregHanson** [comment] 2019-03-01 15:00
haven't been able to reproduce since #11905 merged, marking as resolved

**Closed by GregHanson** 2019-03-01 15:00 UTC

**Comment by infa-ddeore** [comment] 2020-01-05 13:06
> I was able to reproduce after a few scaling attempts. In addition to the setup in the istio docs [here](https://preliminary.istio.io/docs/tasks/traffic-management/ingress/) , these are the steps I followed:
> 
> ```
> #in one tab run:
> for i in {1..500}; do curl -w "%{http_code}\n" -HHost:httpbin.example.com http://$INGRESS_HOST:$INGRESS_PORT/status/200; done
> 
> kubectl scale --replicas=5 deployment/istio-ingressgateway -n istio-system
> 
> #another tab periodically run this to verify all ingress gateways are getting hit:
> for i in `kubectl get po -n istio-system | grep ingressgateway | awk '{print $1}'`; do echo $i `kubectl logs -n istio-system $i | grep "httpbin.example.com" | wc -l`; done
> istio-ingressgateway-7554cdc98-5w456 17
> istio-ingressgateway-7554cdc98-czlzs 22
> istio-ingressgateway-7554cdc98-g8rc9 1
> istio-ingressgateway-7554cdc98-hfsz7 247
> istio-ingressgateway-7554cdc98-v4v8d 0
> ```
> 
> The continuous curl command returned a few `curl: (7) Failed to connect to XXX.XX.XXX.XX port 31380: Connection refused` errors
> 
> The ingressgateway pod in question was missing the envoy listener on port 80:
> 
> ```
> #bad pod
> $ kubectl exec -it -n istio-system istio-ingressgateway-7554cdc98-v4v8d -- curl localhost:15000/listeners
> ["0.0.0.0:15090"]
> #good pod
> $ kubectl exec -it -n istio-system istio-ingressgateway-7554cdc98-hfsz7 -- curl localhost:15000/listeners
> ["0.0.0.0:15090","0.0.0.0:80"]
> ```
> 
> Does appear one of the ingressgateways missed a config push from pilot
> 
> ```
> $ istioctl proxy-status
> 2019-01-22T23:24:22.398563Z	info	Channelz: socket options are not supported on non-linux os and appengine.
> Warning! error execing into istio-pilot-6d7d697759-xcxpv/istio-system discovery container: gc 1 @0.012s 9%: 0.020+1.7+1.4 ms clock, 0.040+0.045/0.087/1.6+2.8 ms cpu, 4->4->2 MB, 5 MB goal, 2 P
> gc 2 @0.023s 10%: 0.008+1.8+1.2 ms clock, 0.016+0.19/0.19/1.4+2.4 ms cpu, 4->4->2 MB, 5 MB goal, 2 P
> 
> NAME                                                  CDS        LDS        EDS               RDS          PILOT                            VERSION
> httpbin-5fc7cf895d-m4vpt.default                      SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-6d7d697759-xcxpv     1.1.0
> istio-egressgateway-685cd5bb49-4kgts.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-6d7d697759-xcxpv     1.1.0
> istio-ingressgateway-7554cdc98-v4v8d.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-6d7d697759-xcxpv     1.1.0
> istio-ingressgateway-7554cdc98-hfsz7.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-6d7d697759-xcxpv     1.1.0
> istio-ingressgateway-7554cdc98-j5pff.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-6d7d697759-xcxpv     1.1.0
> istio-ingressgateway-7554cdc98-pw675.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-6d7d697759-xcxpv     1.1.0
> istio-ingressgateway-7554cdc98-z2jhm.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-6d7d697759-xcxpv     1.1.0
> ```

we are facing same issue with `1.4.2`, looks like this issue still presents, killing pilot pods is a workaround but we need to keep an eye when HPA scales out the pods
