### ISSUE TITLE
EDS updating to empty resulting in clearing of all EDS in a namespace

### ISSUE THREAD

**Issue by nadeemhussain** [istio/istio#25100] opened 2020-06-29 22:48 UTC
**Setup :** 

- istio  with istio components in the istio-system namespace,
- rest components in a single namespace , app

**Issue:**

- istiod restart after which all the EDS got deleted causing S2S communication in cluster  blocked.
-  **istioctl ps** had the EDS  status to **NOT SENT**  for all pod in the app namespace, but was synced for al pods in istio-system namespace
- **istioctl pc**  for cluster, endpoints, routes too didn't had those endpoints in there for any pod in the app namespace.

Istiod was running on info logging mode , so this is the log sample logs from there .

```
2020-06-29T07:01:26.928759Z info ads EDS: PUSH for node:invoice-fc7b8759-vldp4.app clusters:361 endpoints:0 empty:361
```
**FIx**

- Restarting istiod fixed the issue.
- Though istiod has hpa but it was running only 1 pod when this happened.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.5.4
citadel version: 1.5.4
egressgateway version: 1.5.4
galley version: 1.5.4
ingressgateway-com version:
ingressgateway-com version:
ingressgateway-com version:
ingressgateway-internal version:
ingressgateway-internal version:
ingressgateway-internal version:
ingressgateway-kul version:
ingressgateway-kul version:
ingressgateway-kul version:
ingressgateway-sivvi version:
ingressgateway-sivvi version:
ingressgateway-sivvi version:
ingressgateway-team version:
ingressgateway-team version:
ingressgateway-team version:
policy version: 1.5.4
sidecar-injector version: 1.5.4
telemetry version: 1.5.4
pilot version: 1.5.4
data plane version: 1.5.4 (565 proxies)


$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

```
**How was Istio installed?**
istoctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP

**Comment by howardjohn** [comment] 2020-07-29 23:14
Possible same root cause as https://github.com/istio/istio/issues/24117? Does the logs have anything else interesting? Has this happened repeatedly or just 1 time? Did it happen for a long period of time?

**Comment by nadeemhussain** [comment] 2020-08-07 19:15
@howardjohn  this happened 2 times for us and in both cases there was only one pod of istiod running ( though we have hpa on it ), after this we made the min replica to 3 for istiod and we have not seen this issue since then, its been more than a month now.

As istiod was running on info logging there was not much of the information there apart from this one above .

when this happened we did try to delete some virtual service and recreate those again but that didn't helped, only restarting the istiod pod resolved the issue in both cases.

**Comment by howardjohn** [comment] 2020-10-21 21:08
I am fairly sure this is fixed by https://github.com/istio/istio/pull/26142. Since we don't have any info suggesting otherwise and cannot reproduce this, I will close. If you run into this on newer versions please open an issue as this is, of course, a major problem if its triggered.

**Closed by howardjohn** 2020-10-21 21:08 UTC
Labels: area/networking, kind/need more info, lifecycle/needs-triage
