### ISSUE TITLE
EKS nodes don't come up after scaling down and then scaling up if enableNamespacesByDefault is true

### ISSUE THREAD

**Issue by sachin-ks** [istio/istio#40984] opened 2022-09-14 10:56 UTC
### Bug Description

EKS nodes don't come up after scaling down and scaling up the EKS nodes if enableNamespacesByDefault is true.

Warning from istiod-1-15-0 pod:

 

>  Warning  FailedScheduling  3m43s                 default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
> Warning  FailedScheduling  41s (x3 over 2m41s)   default-scheduler  0/2 nodes are available: 2 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.

Warning from istiod-1-15-0 service:

> Warning | FailedToUpdateEndpointSlices | 3 minutes | endpoint-slice-controller | Error updating Endpoint Slices for Service istio-system/istiod-1-15-0: node "ip-192-168-5-17.us-west-2.compute.internal" not found

Screenshot of the above warning:
<img width="1127" alt="Screenshot 2022-09-14 at 4 19 24 PM" src="https://user-images.githubusercontent.com/20788238/190135374-f42c422a-9c2a-4d69-829f-b4e4a67786da.png">

Warning from kube-proxy DaemonSet:

> Warning | FailedCreate | 13 minutes | daemonset-controller | Error creating: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod-1-15-0.istio-system.svc:443/inject?timeout=10s": no endpoints available for service "istiod-1-15-0"

Warning from aws-node DaemonSet:

> Warning | FailedCreate | 14 minutes | daemonset-controller | Error creating: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod-1-15-0.istio-system.svc:443/inject?timeout=10s": no endpoints available for service "istiod-1-15-0"

Screenshot of above warning from EKS UI:
<img width="1159" alt="Screenshot 2022-09-14 at 4 08 23 PM" src="https://user-images.githubusercontent.com/20788238/190132649-04931894-a2dd-4e5c-8bde-60af18dd0dca.png">

### Version

```prose
$ ./istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: none
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.12-eks-6d3986b
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

### Additional Information

**Steps to Reproduce:**

1. Create an EKS clusters with 2 nodes
2. Save this as istioEnabledByDefault.yaml :
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: minimal
  revision: 1-15-0
  values:
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
```
3. Install istio using command:
`
istioctl install -f istioEnabledByDefault.yaml
`
4. Scale the EKS nodes to 0
5. Scale the EKS nodes back to 2. The nodes will not become ready.

Screenshot from AWS:
<img width="1127" alt="Screenshot 2022-09-14 at 4 25 18 PM" src="https://user-images.githubusercontent.com/20788238/190135990-f42273bb-3a51-4441-8f5d-4558ba32bcef.png">

**Comment by howardjohn** [comment] 2022-09-15 14:01
kube-proxy should be in kube-system which is opted out I thought?

**Comment by howardjohn** [comment] 2022-09-15 14:02
Yikes, its not part of the `namespaceSelector`, just in the code...

**Comment by cnvergence** [comment] 2022-09-16 10:18
We encountered a similar error in the past, we did patches independently.
Since Kubernetes v1.21 it is also possible to exclude `kube-system` by its name.
I have opened the PR for testing this out.

**Comment by linsun** [comment] 2022-11-15 21:01
Hi - can this be closed now?

**Comment by cnvergence** [comment] 2022-11-16 08:14
Yes, we can close it
@sachin-ks confirmed that it was solved

**Closed by cnvergence** 2022-11-16 08:14 UTC
Labels: community/help wanted, area/networking, area/user experience
