### ISSUE TITLE
Istio Pilot 1.4.0 and 1.4.3 push too much configuration to envoy proxies.

### ISSUE THREAD

**Issue by TomasKohout** [istio/istio#20100] opened 2020-01-11 20:40 UTC
**Bug description**

**Expected behavior**
As it is in 1.3.6, pilot push configuration only if it is needed and CPU utilization do not reach the stars. 
**Steps to reproduce the bug**
For me it was enough to install 1.4.0. Then I've upgraded to 1.4.3 because I thought that the issue could be fixed.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istioctl:
client version: 1.4.0
control plane version: 1.4.3
data plane version: 1.4.0 (246 proxies), 1.4.3 (14 proxies)
Kubectl:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-10T03:03:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Helm:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**How was Istio installed?**
Via helm.
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS, Istio PIlot

When I set the PILOT_DISABLE_XDS_MARSHALING_TO_ANY to true, config was pushed lesser but it didn't helped with the CPU.

IMHO it is related to this one. https://github.com/istio/istio/issues/18229

If you need anything don't hesitate to ask me. :)

**Comment by howardjohn** [comment] 2020-01-12 00:41
I think this will needs a lot more information for us to find anything useful out of this. Cluster size, number of pods, number of pilots, number of pushes, amount of config, pilot resource requests, etc will all be useful if you are interested in debugging this further

**Comment by TomasKohout** [comment] 2020-01-12 08:17
Currently we have 1 cluster with 22 nodes, 262 pods with sidecar injected (according to istioctl).

We have approx 500 istio related configurations, DestinationRule and VirtualService for each application. Each application has canary deployment with 0 replicas (could this be the issue?).

Pilot has default 500m CPU and 2048Mi memory requrests. 

For this, I've changed the CPU requests to 1500m so that there wont be any disturbances by unknown node etc.

1.4.3:
![cpu-1 4 3](https://user-images.githubusercontent.com/16974829/72215996-423e7500-351b-11ea-8a8e-910f6f16a404.png)
![pushes-1 4 3](https://user-images.githubusercontent.com/16974829/72216001-51bdbe00-351b-11ea-8cb7-35b9fb04dd58.png)
![push-time-1 4 3](https://user-images.githubusercontent.com/16974829/72215999-44a0cf00-351b-11ea-983f-0fc11fa9ff2f.png)


1.3.6:
![after-1 3 6-downgrade-cpu](https://user-images.githubusercontent.com/16974829/72216053-fd670e00-351b-11ea-85d9-316c2d4ac362.png)
![after-1 3 6-downgrade-push](https://user-images.githubusercontent.com/16974829/72216054-ffc96800-351b-11ea-8536-93e99a3aaeb5.png)
![after-1 3 6-downgrade-push-time](https://user-images.githubusercontent.com/16974829/72216055-022bc200-351c-11ea-8f6f-200489c08d80.png)

If there is anything else that I could do, please tell me. I really like Istio so I'll do my best. :)

**Comment by TomasKohout** [comment] 2020-01-12 10:45
After 3 hours of 1.3.6:

![after-3-hours](https://user-images.githubusercontent.com/16974829/72217640-01e9f180-3531-11ea-83a3-62f681532c71.png)
![after-3-hours-pushes](https://user-images.githubusercontent.com/16974829/72217642-07dfd280-3531-11ea-9cff-b6fdb296c201.png)
![after-3-hours-push-time](https://user-images.githubusercontent.com/16974829/72217643-0f06e080-3531-11ea-8250-e4cb604288dc.png)

**Comment by howardjohn** [comment] 2020-01-12 15:43
so looks like 1.3.6 is high cpu initially then goes dormant since there are no changes, are you saying that 1.4.3 never goes dormant and continues to have high cpu?

**Comment by TomasKohout** [comment] 2020-01-12 15:59
Yes, that is what I'm saying. :-)

**Comment by howardjohn** [comment] 2020-01-12 16:02
when you did your experiment above were you switching just pilot or all the proxies as well to 1.3?

Seems there are 2 issues here - too many pushes and when those do happen it's really slow.

For the first we need to see what is triggering the pushes. Do the logs from pilot indicate anything? is it just constant pushing for hours (the graph only shows a couple minutes)?

for the second it may be due to your 100s of configs

**Comment by TomasKohout** [comment] 2020-01-12 16:24
Could it be that the bug fix was not propagated to the 1.4.0 release?

**Comment by howardjohn** [comment] 2020-01-12 16:30
> Could it be that the bug fix was not propagated to the 1.4.0 release?

what bug fix?

**Comment by TomasKohout** [comment] 2020-01-12 18:19
> > Could it be that the bug fix was not propagated to the 1.4.0 release?
> 
> what bug fix?

I'm sorry, It was a misstake. I was a bit tired yesterday and thought that the link in original post is related. 



> when you did your experiment above were you switching just pilot or all the proxies as well to 1.3?
> 
> Seems there are 2 issues here - too many pushes and when those do happen it's really slow.
> 
> For the first we need to see what is triggering the pushes. Do the logs from pilot indicate anything? is it just constant pushing for hours (the graph only shows a couple minutes)?
> 
> for the second it may be due to your 100s of configs

It is constantly pushing.

Logs for 3 minutes.

[pilot-logs.txt](https://github.com/istio/istio/files/4050953/pilot-logs.txt)

About the configs, I'm not sure. I'd expect that if those configs do not change as they do not, then it should not be an issue. For 1.3.6 it is not.

**Comment by howardjohn** [comment] 2020-01-12 18:44
Root cause likely: https://github.com/istio/istio/pull/16967. If you look at the logs youll see a bunch of stuff like `Full push, new service mw-asynccomm-ib.monkeys-feature-ldb-22885.svc.cluster.local`. This PR is only in 1.4, so it would explain the difference you see.

That PR was changed in https://github.com/istio/istio/pull/17957, but that is NOT in 1.4. I am pretty sure with that PR you would have minimal issues - a push would still be triggered but it would be an incremental endpoint only push which is really cheap. I have backported this to 1.4 locally and built to gcr.io/howardjohn-istio/pilot:pr-20100-0 if you would like to try it and see if that solves the problem, but please note I did not test this at all. You can do that same by checking out release-1.4 branch and running `git cp 759684c71 && make docker.pilot` if you prefer.

What is the behavior of services like `api-gateway.mock-master.svc.cluster.local`, or others causing these (grep for "Full push" on your log)? Are they rapidly fluctuating between 0 and N endpoints?

**Comment by TomasKohout** [comment] 2020-01-12 19:02
With the version you have provided pilot is behaving properly. 

api-gateway is a nginx that forward requests and they are not fluctuating. At the moment there is zero traffic and none of them is in a restart loop.

**Comment by TomasKohout** [comment] 2020-01-12 19:12
Wait, now I see that there are 51 events where envoy proxy was not ready. I'm not sure though if this is not related to me performing upgrades of Pilot.

**Comment by howardjohn** [comment] 2020-01-12 19:46
ok great. we can cherry pick that for a 1.4.x release.

It would be nice if you could look at the logs and anytime you see "full push" figure out what was going on with that pod so we can understand the situation fully.

Also if you aren't already I suggest you take a look at the Sidecar object which can help scope down the config for each proxy which will help a lot for performance

**Comment by TomasKohout** [comment] 2020-01-12 20:16
I will check it and will try to figure it out and write it down here if you don't mind to keep this issue open. 

I've skipped the Sidecar object before, but I'll check it out. :-) Thank you very much for your help. :-)

**Comment by TomasKohout** [comment] 2020-01-14 09:28
@howardjohn Hi, I've applied global sidecar so the proxies know only about other proxies in their namespace plus about multitenant services, but Pilot still have a peaks, when creating a new namespace. I thought that those CPU peaks would be gone. Would you have any idea about what could be wrong with configuration? I suppose that it is configuration issue only. I set THROTTLE_PUSH to 10 and even then the peaks persisted. 

I do not want to bother you, so answer only if you want to. :-)

**Comment by TomasKohout** [comment] 2020-01-14 12:11
So, I've increased PILOT_DEBOUNCE_MAX and AFTER, now the peaks are not so big. Approx 500m of CPU. It happens only after whole environment deployment. :)

**Comment by hzxuzhonghu** [comment] 2020-01-14 12:43
`PILOT_DEBOUNCE_AFTER` will influence the cpu usage mostly in your case. I think you should findout what triggers the push happened so frequently firstly.

**Comment by TomasKohout** [comment] 2020-01-14 13:05
> `PILOT_DEBOUNCE_AFTER` will influence the cpu usage mostly in your case. I think you should findout what triggers the push happened so frequently firstly.

It happen when environment is deployed into namespace. Thank you. :-)

**Comment by hzxuzhonghu** [comment] 2020-01-15 02:09
What does `environment ` mean? Can you translate it into normal configs in istio? Please share your pilot logs if possible

**Comment by TomasKohout** [comment] 2020-01-15 09:37
[pilot-logs.log](https://github.com/istio/istio/files/4064082/pilot-logs.log)

Pilot logs after environment creation (cca 50 new proxies).

**Comment by hzxuzhonghu** [comment] 2020-01-15 12:36
Seeing too many `transport: closing server transport due to maximum connection age.` Reconnect absolutely will request for new xDS.

**Comment by TomasKohout** [comment] 2020-01-15 13:10
> Seeing too many `transport: closing server transport due to maximum connection age.` Reconnect absolutely will request for new xDS.

pilot.keepaliveMaxServerConnectionAge is set to default 30m as it was in 1.4.0. I could increase it, but I do not feel that it is the issue. We had issues with full push, wich is solved with the mentioned PR and then with peaks after deployment. Now we do not have any issues. :-)

**Comment by hzxuzhonghu** [comment] 2020-01-16 03:02
It is better if you could send your cpu profile. We can see what takes more cpu. I am not sure if it related to services with no ready endpoints

**Comment by TomasKohout** [comment] 2020-01-23 11:51
Sorry for posting after 7 days. :) Here you can see CPU profile of PIlot. We have 2 of them deployed. Those peaks happen when new namespace is created and applications are deployed. 

![pilot-6-hours](https://user-images.githubusercontent.com/16974829/72982292-08088980-3ddf-11ea-8ecc-cb7d618039b3.png)

**Comment by kalamba** [comment] 2020-02-05 12:57
We got the same problem when upgraded istio from 1.3.6  to 1.4.3.
Istio installed and upgraded from helm chart with parameters:
```
 	        --set sidecarInjectorWebhook.enabled=false \
		--set grafana.enabled=true --set kiali.enabled=true \
		--set global.proxy.accessLogFile="/dev/stdout" \
		--set global.outboundTrafficPolicy.mode=REGISTRY_ONLY \
		--set global.enableTracing=false \
```
High CPU usage by pilot and much more pilot pushes configs:
![pilot_high_cpu](https://user-images.githubusercontent.com/11312631/73835790-11eaad80-481f-11ea-883b-b043ec5a03c3.png)
![pilot_pushes_high](https://user-images.githubusercontent.com/11312631/73835795-131bda80-481f-11ea-9df3-3961535007d0.png)
"istioctl proxy-status" show random STALE statuses in different proxies:
![istioctl_proxy_status_high_cpu](https://user-images.githubusercontent.com/11312631/73835997-6f7efa00-481f-11ea-86bb-f342e61cf58e.png)

We checked proxy status for envoy in pod "nginx-test-istio-696ff9f8cd-8j57f.identity-stage"
```
istioctl proxy-status nginx-test-istio-696ff9f8cd-8j57f.identity-stage
```
and got interesting output:
```
--- Pilot Clusters
+++ Envoy Clusters
@@ -1727,14 +1727,55 @@
             "dnsRefreshRate": "300s",
             "respectDnsTtl": true,
             "dnsLookupFamily": "V4_ONLY"
          }
       },
       {
          "cluster": {
+            "name": "outbound|443||www.google.com",
+            "type": "STRICT_DNS",
+            "connectTimeout": "10s",
+            "loadAssignment": {
+               "clusterName": "outbound|443||www.google.com",
+               "endpoints": [
+                  {
+                     "lbEndpoints": [
+                        {
+                           "endpoint": {
+                              "address": {
+                                 "socketAddress": {
+                                    "address": "www.google.com",
+                                    "portValue": 443
+                                 }
+                              }
+                           },
+                           "loadBalancingWeight": 1
+                        }
+                     ],
+                     "loadBalancingWeight": 1
+                  }
+               ]
+            },
+            "circuitBreakers": {
+               "thresholds": [
+                  {
+                     "maxConnections": 4294967295,
+                     "maxPendingRequests": 4294967295,
+                     "maxRequests": 4294967295,
+                     "maxRetries": 4294967295
+                  }
+               ]
+            },
+            "dnsRefreshRate": "300s",
+            "respectDnsTtl": true,
+            "dnsLookupFamily": "V4_ONLY"
+         }
+      },
+      {
+         "cluster": {
             "name": "outbound|443||www.googleapis.com",
             "type": "STRICT_DNS",
             "connectTimeout": "10s",
             "loadAssignment": {
                "clusterName": "outbound|443||www.googleapis.com",
                "endpoints": [
                   {
@@ -8227,32 +8268,14 @@
                "maxConcurrentStreams": 1073741824
             },
             "protocolSelection": "USE_DOWNSTREAM_PROTOCOL"
          }
       },
       {
          "cluster": {
-            "name": "outbound|80||www.google.com",
-            "type": "ORIGINAL_DST",
-            "connectTimeout": "10s",
-            "lbPolicy": "CLUSTER_PROVIDED",
-            "circuitBreakers": {
-               "thresholds": [
-                  {
-                     "maxConnections": 4294967295,
-                     "maxPendingRequests": 4294967295,
-                     "maxRequests": 4294967295,
-                     "maxRetries": 4294967295
-                  }
-               ]
-            }
-         }
-      }

Listeners Match
Routes Match (RDS last loaded at Tue, 04 Feb 2020 11:57:52 +03)
```
There was diffs between envoy and istio pilot configs. Then we checked ServiceEntry objects. We had 2 ServiceEntry objects with the same domain www.google.com but with different port numbers 80 and 443.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-http
spec:
  hosts:
  ...
  - "www.google.com"
  ...
  exportTo:
  - "."
  ports:
  - number: 80
    name: http
    protocol: HTTP

---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  ...
  - www.google.com
  ...
  exportTo:
  - "."
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
```
When we merged these two files into one file, cleaned old ServiceEntry and added new one:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-google
spec:
  exportTo:
  - "."
  hosts:
  - www.google.com
  ports:
  - number: 80
    protocol: HTTP
    name: http
  - number: 443
    protocol: HTTPS
    name: https
```
conflicts configurations between pilot and envoy has gone, high cpu usage by pilot has gone to.
![pilot_high_cpu_gone](https://user-images.githubusercontent.com/11312631/73842845-73fedf00-482e-11ea-9644-222ea6ec4d5f.png)

So I have a question:
Is it a feature in 1.4.x istio release or a bug?

**Comment by TomasKohout** [comment] 2020-02-05 13:00
> We got the same problem when upgraded istio from 1.3.6 to 1.4.3.
> Istio installed and upgraded from helm chart with parameters:
> 
> ```
>  	        --set sidecarInjectorWebhook.enabled=false \
> 		--set grafana.enabled=true --set kiali.enabled=true \
> 		--set global.proxy.accessLogFile="/dev/stdout" \
> 		--set global.outboundTrafficPolicy.mode=REGISTRY_ONLY \
> 		--set global.enableTracing=false \
> ```
> 
> High CPU usage by pilot and much more pilot pushes configs:
> ![pilot_high_cpu](https://user-images.githubusercontent.com/11312631/73835790-11eaad80-481f-11ea-883b-b043ec5a03c3.png)
> ![pilot_pushes_high](https://user-images.githubusercontent.com/11312631/73835795-131bda80-481f-11ea-9df3-3961535007d0.png)
> "istioctl proxy-status" show random STALE statuses in different proxies:
> ![istioctl_proxy_status_high_cpu](https://user-images.githubusercontent.com/11312631/73835997-6f7efa00-481f-11ea-86bb-f342e61cf58e.png)
> 
> We checked proxy status for envoy in pod "nginx-test-istio-696ff9f8cd-8j57f.identity-stage"
> 
> ```
> istioctl proxy-status nginx-test-istio-696ff9f8cd-8j57f.identity-stage
> ```
> 
> and got interesting output:
> 
> ```
> --- Pilot Clusters
> +++ Envoy Clusters
> @@ -1727,14 +1727,55 @@
>              "dnsRefreshRate": "300s",
>              "respectDnsTtl": true,
>              "dnsLookupFamily": "V4_ONLY"
>           }
>        },
>        {
>           "cluster": {
> +            "name": "outbound|443||www.google.com",
> +            "type": "STRICT_DNS",
> +            "connectTimeout": "10s",
> +            "loadAssignment": {
> +               "clusterName": "outbound|443||www.google.com",
> +               "endpoints": [
> +                  {
> +                     "lbEndpoints": [
> +                        {
> +                           "endpoint": {
> +                              "address": {
> +                                 "socketAddress": {
> +                                    "address": "www.google.com",
> +                                    "portValue": 443
> +                                 }
> +                              }
> +                           },
> +                           "loadBalancingWeight": 1
> +                        }
> +                     ],
> +                     "loadBalancingWeight": 1
> +                  }
> +               ]
> +            },
> +            "circuitBreakers": {
> +               "thresholds": [
> +                  {
> +                     "maxConnections": 4294967295,
> +                     "maxPendingRequests": 4294967295,
> +                     "maxRequests": 4294967295,
> +                     "maxRetries": 4294967295
> +                  }
> +               ]
> +            },
> +            "dnsRefreshRate": "300s",
> +            "respectDnsTtl": true,
> +            "dnsLookupFamily": "V4_ONLY"
> +         }
> +      },
> +      {
> +         "cluster": {
>              "name": "outbound|443||www.googleapis.com",
>              "type": "STRICT_DNS",
>              "connectTimeout": "10s",
>              "loadAssignment": {
>                 "clusterName": "outbound|443||www.googleapis.com",
>                 "endpoints": [
>                    {
> @@ -8227,32 +8268,14 @@
>                 "maxConcurrentStreams": 1073741824
>              },
>              "protocolSelection": "USE_DOWNSTREAM_PROTOCOL"
>           }
>        },
>        {
>           "cluster": {
> -            "name": "outbound|80||www.google.com",
> -            "type": "ORIGINAL_DST",
> -            "connectTimeout": "10s",
> -            "lbPolicy": "CLUSTER_PROVIDED",
> -            "circuitBreakers": {
> -               "thresholds": [
> -                  {
> -                     "maxConnections": 4294967295,
> -                     "maxPendingRequests": 4294967295,
> -                     "maxRequests": 4294967295,
> -                     "maxRetries": 4294967295
> -                  }
> -               ]
> -            }
> -         }
> -      }
> 
> Listeners Match
> Routes Match (RDS last loaded at Tue, 04 Feb 2020 11:57:52 +03)
> ```
> 
> There was diffs between envoy and istio pilot configs. Then we checked ServiceEntry objects. We had 2 ServiceEntry objects with the same domain [www.google.com](http://www.google.com) but with different port numbers 80 and 443.
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: external-svc-http
> spec:
>   hosts:
>   ...
>   - "www.google.com"
>   ...
>   exportTo:
>   - "."
>   ports:
>   - number: 80
>     name: http
>     protocol: HTTP
> 
> ---
> 
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: external-svc-https
> spec:
>   hosts:
>   ...
>   - www.google.com
>   ...
>   exportTo:
>   - "."
>   location: MESH_EXTERNAL
>   ports:
>   - number: 443
>     name: https
>     protocol: TLS
>   resolution: DNS
> ```
> 
> When we merged these two files into one file, cleaned old ServiceEntry and added new one:
> 
> ```
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: external-google
> spec:
>   exportTo:
>   - "."
>   hosts:
>   - www.google.com
>   ports:
>   - number: 80
>     protocol: HTTP
>     name: http
>   - number: 443
>     protocol: HTTPS
>     name: https
> ```
> 
> conflicts configurations between pilot and envoy has gone, high cpu usage by pilot has gone to.
> ![pilot_high_cpu_gone](https://user-images.githubusercontent.com/11312631/73842845-73fedf00-482e-11ea-9644-222ea6ec4d5f.png)
> 
> So I have a question:
> Is it a feature in 1.4.x istio release or a bug?

Hi, are you able to use the istio pilot which John prepared? Try that and see if it helped.

**Comment by kalamba** [comment] 2020-02-05 14:31
@TomasKohout Hi, I checked John's image "gcr.io/howardjohn-istio/pilot:pr-20100-0" and it's working fine, there are not any STALE statuses or high cpu usage by pilot. 
![pilot_pr_cool](https://user-images.githubusercontent.com/11312631/73850744-4ff6ca00-483d-11ea-87ad-e23cd2c1d1ae.png)

**Comment by TomasKohout** [comment] 2020-02-12 09:46
@kalamba I've upgraded to 1.4.4 and it seems ok. :-)

Thank you guys. :-)

**Closed** 2020-02-12 09:47 UTC
Labels: area/networking, area/perf and scalability, kind/need more info, lifecycle/needs-triage
