### ISSUE TITLE
no healthy host for HTTP connection pool, ':status', '503'

### ISSUE THREAD

**Issue by LinLshare** [istio/istio#18375] opened 2019-10-28 10:03 UTC
**Bug description**

I use istio ingress-gateway enable https in aws EKS and then test my service by locust.
When testing, everything seems good, but when I stop testing, the error occurs.

```shell
2019-10-28T09:30:30.543691991Z [2019-10-28 09:30:30.543][22][debug][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:1146] no healthy host for HTTP connection pool
2019-10-28T09:30:30.543787183Z [2019-10-28 09:30:30.543][22][debug][http] [external/envoy/source/common/http/async_client_impl.cc:91] async http request response headers (end_stream=false):
2019-10-28T09:30:30.543794774Z ':status', '503'
2019-10-28T09:30:30.54379803Z 'content-length', '19'
2019-10-28T09:30:30.54380137Z 'content-type', 'text/plain'
```

**Expected behavior**
':status', '200'

**Steps to reproduce the bug**

1. apply an test service;
2. bind a https cert to the test service;
3. use [locust](https://docs.locust.io/en/stable/installation.html) to run to http test;
4. press [Ctrl +C] to stop locust test, then you will see 503 error.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.3.3
control plane version: 1.3.0

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-eks-5876d6", GitCommit:"5876d6b7429820450950ade17fe7b4bf5ccada7f", GitTreeState:"clean", BuildDate:"2019-09-24T20:54:25Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
by the repo: https://github.com/LinLshare/istio-test

**Environment where bug was observed (cloud vendor, OS, etc)**
Amazon Linux

**Comment by howardjohn** [comment] 2019-10-28 14:11
Seems like this may just be locust nit gracefully shutting down and closing the connection before a request is complete?

**Comment by LinLshare** [comment] 2019-10-28 15:14
@howardjohn maybe, but in our production environment, there are several 503 errors one after one every about 15 minutes, so annoying 😣. It's all the client side's wrong, or I should ignore the error ?

**Comment by LinLshare** [comment] 2019-10-28 15:26
and I wonder why client side's wrong results in 503 error. I think 503 should be the server side's error called  _503 internal error_.

**Comment by howardjohn** [comment] 2019-10-28 15:32
So, 503s are basically the catch-all error for any issues, so just knowing you get 503s is not enough to root cause this. I would take a look at https://karlstoney.com/2019/05/31/istio-503s-ucs-and-tcp-fun-times, it is an excellent blog about debugging a 503 problem (in a previous release, which has now been fixed). We also have some more 503 fixes in 1.3.4 coming out this week.

One immediate thing you can do is turn on access logs https://istio.io/docs/tasks/telemetry/logs/access-log/ and there is a "Response Flag" field that will give more details about the 503 (like DC, UC, etc)

**Comment by LinLshare** [comment] 2019-10-28 15:40
@howardjohn thanks a lot, I will try it

**Comment by LinLshare** [comment] 2019-10-28 16:07
I had a try, it shows `DC` as following
```shell
[2019-10-28T16:02:46.181Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 329 0 0 - "<ip-a>" "python-requests/2.22.0" "6ec21141-cd04-4f3d-9582-4e106b393c7a" "<domain>" "127.0.0.1:8080" inbound|8080|http|test-app.default.svc.cluster.local - <ip-b>:8080 <ip-a>:0 - default
```

**Comment by lambdai** [comment] 2019-10-29 04:37
1. std::string ResponseFlagUtils::DOWNSTREAM_CONNECTION_TERMINATION = "DC";
Did you look for parameters in locust to see if 503 could be mitigated?
2. Is the below timestamp close to the locust stop timing? Which component is print the log? ingressgateway or a sidecar proxy behind ingressgateway?
```
2019-10-28T09:30:30.543691991Z [2019-10-28 09:30:30.543][22][debug][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:1146] no healthy host for HTTP connection pool
2019-10-28T09:30:30.543787183Z [2019-10-28 09:30:30.543][22][debug][http] [external/envoy/source/common/http/async_client_impl.cc:91] async http request response headers (end_stream=false):
```
3. The log also shows `no healthy host for HTTP connection pool`. The upstream service of this ingress/sidecar jitter? Did you shutdown the tested service before shutting down locust?

**Comment by LinLshare** [comment] 2019-10-30 00:12
@lambdai I try to answer your 3 questions,
1. I use locust to test my service, just because 503s occur in our production env, so I had not tried to look  look for parameters in locust for mitigating.
2. Yes, and the sidecar proxy print the log. I open the istio-proxy's debug logs following this article https://karlstoney.com/2019/05/31/istio-503s-ucs-and-tcp-fun-times/index.html.
3. No, I never do anything to the tested service before shutting down locust. I'm confused about the log `no healthy host for HTTP connection pool`

**Comment by lambdai** [comment] 2019-10-31 18:53
I am curious how many envoy instances are involved in the test cases.
You mentioned using istio-ingressgateway, so 
1. is it  locust_outside_mesh -> istio-ingressgateway -> service_sidecar_envoy -> service ?
2. is the service_sidecar_envoy print the DC log?
If both answer are yes, the DC should be referring to istio-ingressgateway and <ip-a> is either the ip of istio-ingressgateway  or anything between locust and istio-ingressgateway.
Anyway, could you paste the access log of istio-ingressgateway?
What's more, could you extend the time to confirm if you only see the bad request on locust termination?
The sidecar envoy reports DC, which means it probably there is nothing sidecar envoy could do. Is there any logs from ingressgateway.

**Comment by LinLshare** [comment] 2019-11-01 04:04
@lambdai I had tested it again, please look at following.
> 1. is it locust_outside_mesh -> istio-ingressgateway -> service_sidecar_envoy -> service ?
-------
YES, I'm sure.
> 2. is the service_sidecar_envoy print the DC log?
-------
YES, look at the following log:
**locust say bye**
```shell
^C[2019-11-01 03:24:53,176] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr: Traceback (most recent call last):
[2019-11-01 03:24:53,176] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr:
[2019-11-01 03:24:53,176] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr: File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
[2019-11-01 03:24:53,176] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr:
[2019-11-01 03:24:53,176] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr: File "/usr/local/lib/python3.7/site-packages/locust/runners.py", line 114, in start_locust
    locust().run(runner=self)
.......
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr:
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr: File "/usr/lib64/python3.7/os.py", line 679, in __getitem__
    return self.decodevalue(value)
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr:
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr: File "/usr/lib64/python3.7/os.py", line 756, in decode
    return value.decode(encoding, 'surrogateescape')
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr:
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr: KeyboardInterrupt
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr:
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr: 2019-11-01T03:24:53Z
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr:
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/ERROR/stderr: <Greenlet at 0x7f821150eb90: start_locust(<class 'latte_perf_test.HostListLocust'>)> failed with KeyboardInterrupt
[2019-11-01 03:24:53,178] ip-10-2-17-199.us-west-2.compute.internal/INFO/locust.main: Shutting down (exit code 0), bye.
```
**test-svc service_sidecar_envoy say DC**
```shell
[ec2-user@ip-10-2-17-199 ~]$ kubectl logs test-svc-75d859c76b-8hzfr -n ecp-cafe -c istio-proxy --tail=20  -f | grep DC
[2019-11-01T03:24:54.128Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 334 0 4 - "33.218.21.68" "python-requests/2.22.0" "f37ccf8c-6a3d-4a64-9e0b-b8d600ddb697" "test-svc.com" "-" - - 10.2.67.66:8080 33.218.21.68:0 - -
[2019-11-01T03:24:54.129Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 347 0 6 - "33.218.21.68" "python-requests/2.22.0" "783dd755-c0e5-4d9f-84a6-7bca0d8b9587" "test-svc.com" "-" - - 10.2.67.66:8080 33.218.21.68:0 - -
[2019-11-01T03:24:54.132Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 326 0 10 - "33.218.21.68" "python-requests/2.22.0" "1a866ba2-f6a1-40df-87a0-b66eec8f22a6" "test-svc.com" "127.0.0.1:8080" inbound|8080|http|test-svc.test-ns.svc.cluster.local - 10.2.67.66:8080 33.218.21.68:0 - default
[2019-11-01T03:24:54.135Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 343 0 10 - "33.218.21.68" "python-requests/2.22.0" "18abc738-2e63-486f-8a6c-26ca54f22f23" "test-svc.com" "-" - - 10.2.67.66:8080 33.218.21.68:0 - -
[2019-11-01T03:24:54.193Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 338 0 15 - "33.218.21.68" "python-requests/2.22.0" "5ff5102d-83fb-4736-b5a9-9425c8dea570" "test-svc.com" "-" - - 10.2.67.66:8080 33.218.21.68:0 - -
```
**istio-ingressgateway say DC**
```shell
[ec2-user@ip-10-2-17-199 istio-1.3.3]$ kubectl logs istio-ingressgateway-67fbf57b85-m85kq -n istio-system --tail=20  -f | grep DC
[2019-11-01T03:24:54.128Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 347 0 2 - "33.218.21.68" "python-requests/2.22.0" "783dd755-c0e5-4d9f-84a6-7bca0d8b9587" "test-svc.com" "10.2.67.66:8080" outbound|8080|stable|test-svc.test-ns.svc.cluster.local - 10.2.97.93:443 33.218.21.68:51206 - -
[2019-11-01T03:24:54.127Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 334 0 4 - "33.218.21.68" "python-requests/2.22.0" "f37ccf8c-6a3d-4a64-9e0b-b8d600ddb697" "test-svc.com" "10.2.67.66:8080" outbound|8080|stable|test-svc.test-ns.svc.cluster.local - 10.2.97.93:443 33.218.21.68:51626 - -
[2019-11-01T03:24:54.131Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 326 0 10 - "33.218.21.68" "python-requests/2.22.0" "1a866ba2-f6a1-40df-87a0-b66eec8f22a6" "test-svc.com" "10.2.67.66:8080" outbound|8080|stable|test-svc.test-ns.svc.cluster.local - 10.2.97.93:443 33.218.21.68:51684 - -
[2019-11-01T03:24:54.131Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 343 0 14 - "33.218.21.68" "python-requests/2.22.0" "18abc738-2e63-486f-8a6c-26ca54f22f23" "test-svc.com" "10.2.67.66:8080" outbound|8080|stable|test-svc.test-ns.svc.cluster.local - 10.2.97.93:443 33.218.21.68:51992 - -
[2019-11-01T03:24:54.192Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 338 0 15 - "33.218.21.68" "python-requests/2.22.0" "5ff5102d-83fb-4736-b5a9-9425c8dea570" "test-svc.com" "10.2.67.66:8080" outbound|8080|stable|test-svc.test-ns.svc.cluster.local - 10.2.97.93:443 33.218.21.68:51696 - -
[2019-11-01T03:24:54.193Z] "POST /host/list/v1 HTTP/1.1" 0 DC "-" "-" 355 0 18 - "33.218.21.68" "python-requests/2.22.0" "b2a2c68b-7917-4151-8f75-46cd48553be2" "test-svc.com" "10.2.67.66:8080" outbound|8080|stable|test-svc.test-ns.svc.cluster.local - 10.2.97.93:443 33.218.21.68:52004 - -
```

> Tip: The public IPs above had been modified for security.

**Comment by LinLshare** [comment] 2019-11-04 04:15
@howardjohn I have tested it with the v1.3.4 istio, but still show the problem. Is there any plan to solve the problem?

**Closed** 2020-05-24 05:01 UTC
Labels: area/perf and scalability, lifecycle/needs-triage
