### ISSUE TITLE
503 NR's during load testing canary deployment

### ISSUE THREAD

**Issue by pliutak-nih** [istio/istio#26861] opened 2020-08-27 15:48 UTC
**Bug description**
I see 503 NR's during load testing canary deployment using Agro Rollouts.
I'll describe min setup with steps to reproduce the issue, reflecting the same sequence of actions Agro Rollouts does during canary deployment.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
No downtime during canary deployment using Agro Rollouts.

**Steps to reproduce the bug**

1. Create a cluster in GKE and install Istio using istioctl (exact command is below).

2. `kubectl apply` resources:

- Gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: example-ingress
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.example'
    port:
      name: http
      number: 80
      protocol: HTTP
```

- Stable deployment (`reviews` app v1):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
```

- Canary deployment (`reviews` app v2):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
```

- Stable deployment service (aimed to v1 deployment):
```
apiVersion: v1
kind: Service
metadata:
  name: reviews-stable
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
    version: v1
```

- Canary deployment service (aimed to v1 as well at the very beginning):
```
apiVersion: v1
kind: Service
metadata:
  name: reviews-canary
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
    version: v1
```

- Virtual Service definition (100% of traffic goes to stable deployment service):
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-vsvc
spec:
  gateways:
  - istio-system/example-ingress
  hosts:
  - reviews.example
  http:
  - name: primary
    route:
    - destination:
        host: reviews-stable
      weight: 100
    - destination:
        host: reviews-canary
      weight: 0
```

3. Execute JMeter load test against `review.example`:
```
...
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain">reviews.example</stringProp>
          <stringProp name="HTTPSampler.port"></stringProp>
          <stringProp name="HTTPSampler.protocol">http</stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path">/health</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.proxyHost">10.20.30.40</stringProp>
          <stringProp name="HTTPSampler.proxyPort">80</stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
        </HTTPSamplerProxy>
...
```

4. Aim canary deployment service to Deployment v2:
```
curl -X PATCH -H "Content-Type: application/merge-patch+json" --data '{"spec": {"selector": {"version": "v2"}}}' http://localhost:8080/api/v1/namespaces/default/services/reviews-canary
```

5. Observe some downtime:
```
$ tail results -f | grep -Ev '(200,OK)'
1598539426258,165,HTTP Request,503,Service Unavailable,Thread Group 1-3,,false,,148,177,5,5,http://reviews.example/health,165,0,28
1598539426256,184,HTTP Request,503,Service Unavailable,Thread Group 1-4,,false,,149,177,5,5,http://reviews.example/health,184,0,29
```

All traffic goes through stable deployment service, but it was not touched at all. Please help to explain downtime.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (5 proxies)
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
istioctl install --set profile=demo
kubectl label namespace default istio-injection=enabled
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE, 1.16.13-gke.1

**Comment by howardjohn** [comment] 2020-08-31 17:57
I tried to reproduce this. I was unable to. I applied the exact same configuration above, and ran

```xml
<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="4.0" jmeter="4.0 r1823414">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Test Plan" enabled="true">
      <stringProp name="TestPlan.comments"></stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Thread Group" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <stringProp name="LoopController.loops">1</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">10</stringProp>
        <stringProp name="ThreadGroup.ramp_time">5</stringProp>
        <boolProp name="ThreadGroup.scheduler">true</boolProp>
        <stringProp name="ThreadGroup.duration">30</stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
      </ThreadGroup>
      <hashTree>
        <LoopController guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">true</boolProp>
          <intProp name="LoopController.loops">-1</intProp>
        </LoopController>
        <hashTree>
<HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
    <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
    <collectionProp name="Arguments.arguments"/>
    </elementProp>
    <stringProp name="HTTPSampler.domain">reviews.example</stringProp>
    <stringProp name="HTTPSampler.port"></stringProp>
    <stringProp name="HTTPSampler.protocol">http</stringProp>
    <stringProp name="HTTPSampler.contentEncoding"></stringProp>
    <stringProp name="HTTPSampler.path">/health</stringProp>
    <stringProp name="HTTPSampler.method">GET</stringProp>
    <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
    <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
    <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
    <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
    <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
    <stringProp name="HTTPSampler.proxyHost">34.66.249.189</stringProp>
    <stringProp name="HTTPSampler.proxyPort">80</stringProp>
    <stringProp name="HTTPSampler.connect_timeout"></stringProp>
    <stringProp name="HTTPSampler.response_timeout"></stringProp>
</HTTPSamplerProxy>
          <hashTree/>
        </hashTree>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>
```

then `./jmeter -n -t plan.jmx -l log.log`

I see all 200s when switch back and forth from v1 to v2 with `kubectl patch svc reviews-stable --patch '{"spec": {"selector": {"version": "v2"}}}'`.

I also tried fortio as a load client, could not reproduce there either.

Can you enable access logging maybe and show what errors are seen? They will give more detail than simple 503

**Comment by pliutak-nih** [comment] 2020-09-01 13:56
Hi John, thanks for looking into it.

I see that you're trying to patch **reviews-stable**. Please note, I'm patching **reviews-canary** on step 4 (it's exactly, what argo-rollouts is doing prior to switch traffic to canary).

**Comment by howardjohn** [comment] 2020-09-04 00:44
I see, thanks, I can reproduce this now

**Comment by howardjohn** [comment] 2020-09-04 01:04
Here is what is happening. When both the Services point to the same pod, we get into a conflict, because Istio needs to setup inbound configuration and we have two different services. When this happens, conflict resolution picks the oldest service first. In our case, either canary was created first or it was created at exact same time at which point we resolve by alphabetical - canary comes before stable. This means every time we switch the service, we are now switching which service "wins". This causes some churn in envoy, which is somehow causing the issue.

Full reproducing config:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: example-ingress
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-stable
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-canary
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
    version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-vsvc
spec:
  gateways:
  - istio-system/example-ingress
  hosts:
  - reviews
  http:
  - name: primary
    retries:
      attempts: 0
    route:
    - destination:
        host: reviews-stable
      weight: 100
    - destination:
        host: reviews-canary
      weight: 0
```

Then just `fortio load -qps 40 -t 0s -H "Host: reviews.default.svc.cluster.local" IP/health`

Access logs on inbound sidecar:
```
[2020-09-04T01:03:17.418Z] "GET /health HTTP/1.1" 503 NR "-" "-" 0 0 0 - "10.128.15.218" "fortio.org/fortio-1.3.1" "73799c60-de7b-41f7-b51f-0260c576123d" "reviews.default.svc.cluster.local" "-" - - 10.28.3.75:9080 10.128.15.218:0 outbound_.9080_._.reviews-stable.default.svc.cluster.local default
```

**Comment by howardjohn** [comment] 2020-09-04 01:05
A diff from before and after patch of config dump:
```diff
236c236
<                 "name": "inbound|9080|http|reviews-stable.default.svc.cluster.local",
---
>                 "name": "inbound|9080|http|reviews-canary.default.svc.cluster.local",
250c250
<                           "cluster": "inbound|9080|http|reviews-stable.default.svc.cluster.local",
---
>                           "cluster": "inbound|9080|http|reviews-canary.default.svc.cluster.local",
255c255
<                           "operation": "reviews-stable.default.svc.cluster.local:9080/*"
---
>                           "operation": "reviews-canary.default.svc.cluster.local:9080/*"
470c470
<                 "name": "inbound|9080|http|reviews-stable.default.svc.cluster.local",
---
>                 "name": "inbound|9080|http|reviews-canary.default.svc.cluster.local",
484c484
<                           "cluster": "inbound|9080|http|reviews-stable.default.svc.cluster.local",
---
>                           "cluster": "inbound|9080|http|reviews-canary.default.svc.cluster.local",
489c489
<                           "operation": "reviews-stable.default.svc.cluster.local:9080/*"
---
>                           "operation": "reviews-canary.default.svc.cluster.local:9080/*"
```

**Comment by howardjohn** [comment] 2020-09-04 01:22
Failures are from `unknown cluster 'inbound|9080|http|reviews-canary.default.svc.cluster.local'`.
```
2020-09-04T01:19:07.943092Z     debug   envoy config    new fc_contexts has 2 filter chains, including 1 newly built
2020-09-04T01:19:07.943111Z     debug   envoy config    add warming listener: name=virtualInbound, hash=16388031564279754452, address=0.0.0.0:15006
2020-09-04T01:19:07.943115Z     debug   envoy misc      Initialize listener virtualInbound local-init-manager.
2020-09-04T01:19:07.943119Z     debug   envoy init      init manager Listener-local-init-manager virtualInbound 16388031564279754452 contains no targets
2020-09-04T01:19:07.943121Z     debug   envoy init      init manager Listener-local-init-manager virtualInbound 16388031564279754452 initialized, notifying Listener-local-init-watcher virtualInbound
2020-09-04T01:19:07.943126Z     debug   envoy config    execute in place filter chain update: name=virtualInbound, hash=16388031564279754452, address=0.0.0.0:15006
2020-09-04T01:19:07.943128Z     debug   envoy config    replacing existing listener 34
2020-09-04T01:19:07.943141Z     debug   envoy config    replacing existing listener 34
2020-09-04T01:19:07.943335Z     debug   envoy config    draining 1 filter chains in listener virtualInbound: name=virtualInbound, hash=8678904662938936619, address=0.0.0.0:15006
2020-09-04T01:19:07.943349Z     info    envoy upstream  lds: add/update listener 'virtualInbound'
2020-09-04T01:19:07.943358Z     debug   envoy config    Resuming discovery requests for type.googleapis.com/envoy.config.route.v3.RouteConfiguration
2020-09-04T01:19:07.943361Z     debug   envoy config    Resuming discovery requests for type.googleapis.com/envoy.api.v2.RouteConfiguration
2020-09-04T01:19:07.943366Z     debug   envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener accepted with 18 resources with version 2020-09-04T01:19:07Z/594
2020-09-04T01:19:07.943541Z     debug   envoy config    Received gRPC message for type.googleapis.com/envoy.config.route.v3.RouteConfiguration at version 2020-09-04T01:19:07Z/594
2020-09-04T01:19:07.943827Z     debug   envoy config    gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration accepted with 1 resources with version 2020-09-04T01:19:07Z/594
2020-09-04T01:19:07.944004Z     debug   envoy config    gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration accepted with 1 resources with version 2020-09-04T01:19:07Z/594
2020-09-04T01:19:07.944085Z     debug   envoy config    gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration accepted with 1 resources with version 2020-09-04T01:19:07Z/594
2020-09-04T01:19:07.944178Z     debug   envoy config    gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration accepted with 1 resources with version 2020-09-04T01:19:07Z/594
2020-09-04T01:19:07.979455Z     debug   envoy http      [C4927] new stream
2020-09-04T01:19:07.979528Z     debug   envoy http      [C4927][S4090577500600274274] request headers complete (end_stream=true):
':authority', 'reviews.default.svc.cluster.local'
':path', '/health'
':method', 'GET'
'user-agent', 'fortio.org/fortio-1.3.1'
'x-forwarded-for', '10.128.15.218'
'x-forwarded-proto', 'http'
'x-envoy-internal', 'true'
'x-request-id', '785254b3-fc80-4eda-be31-1407c4089ea9'
'x-envoy-decorator-operation', 'reviews-stable.default.svc.cluster.local:9080/*'
'x-envoy-attempt-count', '1'
'x-b3-traceid', 'fb8092a7dd2ba68dfb68366366902242'
'x-b3-spanid', 'fb68366366902242'
'x-b3-sampled', '0'
'content-length', '0'

2020-09-04T01:19:07.979533Z     debug   envoy http      [C4927][S4090577500600274274] request end stream
2020-09-04T01:19:07.979576Z     debug   envoy filter    AuthenticationFilter::decodeHeaders with config
policy {
}
skip_validate_trust_domain: true

2020-09-04T01:19:07.979581Z     debug   envoy filter    No method defined. Skip source authentication.
2020-09-04T01:19:07.979585Z     debug   envoy filter    Set principal from peer:
2020-09-04T01:19:07.979587Z     debug   envoy filter    Origin authenticator succeeded
2020-09-04T01:19:07.979591Z     debug   envoy filter    Saved Dynamic Metadata:

2020-09-04T01:19:07.979600Z     debug   envoy router    [C4927][S4090577500600274274] unknown cluster 'inbound|9080|http|reviews-canary.default.svc.cluster.local'
2020-09-04T01:19:07.979623Z     debug   envoy http      [C4927][S4090577500600274274] Sending local reply with details cluster_not_found
2020-09-04T01:19:07.979648Z     debug   envoy http      [C4927][S4090577500600274274] drain closing connection
2020-09-04T01:19:07.979654Z     debug   envoy http      [C4927][S4090577500600274274] encoding headers via codec (end_stream=true):
':status', '503'
'date', 'Fri, 04 Sep 2020 01:19:07 GMT'
'server', 'istio-envoy'
'connection', 'close'
```

**Comment by howardjohn** [comment] 2020-09-04 15:29
@lambdai we send the cluster before the listener. Is it just applying the new FC before it applies the new cluster that comes in or something leading to this issue?

**Comment by pliutak-nih** [comment] 2020-09-14 13:55
Any update on it?

**Comment by howardjohn** [comment] 2020-09-14 14:40
@pliutak-nih not at this time. I have identified the root cause and am trying to get confirmation from the Envoy team whether this is an Envoy bug or if there is something we can do on Istio side.

**Comment by howardjohn** [comment] 2020-09-14 22:36
Ah its actually not (or at least, not *only*) an issue of failing to send to the new cluster. We remove the cluster, THEN we send the listener update pointing to the new cluster. So there is a short period of time where we point to a non existant cluster.

**Comment by turaleck** [comment] 2020-09-15 13:26
Hi @howardjohn I am seeing similar issues with Argo rollout using [blue/green deployment strategy](https://argoproj.github.io/argo-rollouts/features/bluegreen/) and Istio 1.4.9. I maintain load on the system while the deployment is taking place, and in some cases, gRPC client services that are calling the service being redeployed get `UNAVAILABLE` response code (gRPC code 14) with response flags `NR` or `URX`. These errors happen for a very short period of time and then disappear. Would you say I'm running into the same issue you identified here?

**Comment by howardjohn** [comment] 2020-09-15 14:26
If the server pod shows `503 NR` its very likely the same. If its something else, may be different

**Comment by turaleck** [comment] 2020-09-15 17:20
@howardjohn thank you for the quick response. I have envoyproxy configured to retry on 5xx. So I suppose after it exhausts all the retries it fails with `503 URX`

**Comment by DmitryKiselev** [comment] 2020-09-15 21:50
@howardjohn - thanks for all your comments above. We are having the same issue which is a GA blocker in our case. As I understand your proposed PR fix was not approved. Hence I was wondering:

a) if you could think of a work around that can be used in the meantime.
b) if you would recommend some other way to switch from Blue to Green as opposed to what Argo Rollouts are doing to avoid the 503 situation?

thanks in advance,
Dmitriy

**Comment by howardjohn** [comment] 2020-09-15 21:54
@DmitryKiselev in the short term you can use VS to do this (see https://medium.com/infinite-lambda/canary-and-blue-green-deployments-with-helm-and-istio-4139886447b6 for example). You can also make sure the Service is created in the "right" order (see comment in https://github.com/istio/istio/issues/26861#issuecomment-686840121) - this is a HUGE hack though, just thinking short term mitigation.

My PR is not yet merged but I am hoping to discuss this issue in the networking WG meeting in 2 days to get a wider audience for some ideas.

**Comment by DmitryKiselev** [comment] 2020-09-15 22:47
@howardjohn - thanks for a quick response! Appreciate it. 

Argo does use the VS already. Could you, please, give a few more hints what is the differentiator in the work around you pointed out?
Thanks!

**Comment by howardjohn** [comment] 2020-09-15 22:49
Instead of shifting the Service around, just switch the VS weights:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-vsvc
spec:
  gateways:
  - istio-system/example-ingress
  hosts:
  - reviews.example
  http:
  - name: primary
    route:
    - destination:
        host: reviews-stable
      weight: 0
    - destination:
        host: reviews-canary
      weight: 100
```

For example, the VS above is sending 100% of traffic to canary ^. Or you can do a percentage split, etc - lot of options here.

The key to working around this bug is to not change the Service associated with the pod.

**Comment by DmitryKiselev** [comment] 2020-09-15 23:11
Perfect, thanks!!

Side Question: can someone from our team join the SIG meeting that you have mentioned happening in 2 days if its public?

**Comment by howardjohn** [comment] 2020-09-15 23:13
@DmitryKiselev certainly. https://github.com/istio/community/blob/master/WORKING-GROUPS.md has all the info. It should be mentioned there but its at 9am PST Thursdays

**Comment by ngms06** [comment] 2020-09-16 23:11
@howardjohn: In our istio setup using argo rollouts for blue green deployments, the client is using the same virtual service pre and post deployment. The virtual service references a K8s service and argo rollouts updates the selector(replicaset hash of the pods) from blue to green pods during a deployment. We are getting NRX errors on the client post this switch. 
The core issue seems to envoy configuration update delay post K8s update. Is that understanding correct?

**Comment by howardjohn** [comment] 2020-09-16 23:13
@ngms06 the issue isn't so much as delay its that we are swapping something non atomically.

Before:
listener points to cluster v1, we have clusters [v1] - all good

Intermediate state (should be a couple ms):
listener points to cluster v1, we have clusters [v2] - broken

After:
listener points to cluster v2, we have clusters [v2] - all good

**Comment by brianwolfe** [comment] 2020-09-26 03:07
@howardjohn 

FWIW, we ran into this issue on 1.6.9, but instead of having an explicit change, we were ran into it because we had a small set of collaborating errors.

1. We use sidecar traffic ingress configuration.
2. We often see the first xDS push to the proxies before istiod can determine the service instance.
3. This means we end up in findOrCreateInstance https://github.com/istio/istio/blob/4385fd8f0043f88add2eb085d62e44ba8ced2317/pilot/pkg/networking/core/v1alpha3/cluster.go#L345-L367 and create a fake service instance based on the sidecar object's name & namespace.
4. So we end up `<sidecar-name>.<namespace>` as the cluster name. When the connection to istiod is closed due to timeout (5 mins for us), we get the same issue where the cluster is deleted (and a new one is created w/ the hostname portion equal to <service-name>.<namespace>.<domain-suffix>).
5. This results in 503 NR spikes ~ 5 minutes after every pod rotation. 😢 

It looks like your patch will fix this for us. I am going to try backporting your patch to run on 1.6.x and see if that can mitigate it for us. Can I provide any other information that would be helpful?

**Comment by ramaraochavali** [comment] 2020-09-26 05:11
@brianwolfe  I think #2 should not happen in 1.7. It was fixed there with the following PRs https://github.com/istio/istio/pull/25733
https://github.com/istio/istio/pull/26394

Please verify if you see this issue in 1.7 - if it is fixed in 1.7, may be we should backport those two PRs.

**Comment by brianwolfe** [comment] 2020-09-26 15:27
@ramaraochavali thanks for pinging me on this fix. If I'm understanding correctly, those fixes are for fixing the configurations pushed when istiod restarts. I think I wasn't completely clear. We are seeing this as a transient state when workload pods start up or are recycled, but where Istiod has been stable for a while.

**Comment by brianwolfe** [comment] 2020-09-27 03:52
I tested a backported version of the patch over the latest release-1.6 branch, it appears to be working in our test cluster, no 503 NRs. Still cleaning up some unit & integration test failures.

**Comment by ramaraochavali** [comment] 2020-09-28 10:39
Ok. Good to hear that backport is working. I agree if istiod is stable, the issue I mentioned is not the issue.

**Comment by brianwolfe** [comment] 2020-09-29 23:13
Correction, telemetryv2 is broken w/ the backport. I'm looking for a workaround, but it may require changes to istio/proxy if we change the cluster name.

**Comment by Eslamanwar** [comment] 2020-10-19 16:18
@howardjohn I saw your PR that tries to solve this issue , are we expecting a batch for the current istio version 1.7 or we will wait to 1.8 for extra modification to envoy-proxy, thank you

**Comment by howardjohn** [comment] 2020-10-19 16:28
This is highly unlikely to land in 1.7 as it required substantial changes to the telemetry code in order to work, (which is why it has not been merged - should be soon though)

**Closed** 2020-10-22 16:31 UTC
Labels: area/networking
