### ISSUE TITLE
Sidecar injection with mutating webhooks

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1464] opened 2017-11-03 22:56 UTC
@andraxylia commented on [Fri Oct 13 2017](https://github.com/istio/old_pilot_repo/issues/1474)

---

@ayj commented on [Tue Oct 17 2017](https://github.com/istio/old_pilot_repo/issues/1474#issuecomment-337326673)

Initializers will not be beta in k8s 1.9. Instead the k8s API machinary SIG's plan is to push mutating webhooks to beta in 1.9. The automatic sidecar injection feature should use these mutating webhooks instead of the initializer mechanism.

Ref https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/OTApxKFiGt8

---

@ayj commented on [Tue Oct 17 2017](https://github.com/istio/old_pilot_repo/issues/1474#issuecomment-337326800)

/fyi @gyliu513 @linsun 

---

@linsun commented on [Tue Oct 17 2017](https://github.com/istio/old_pilot_repo/issues/1474#issuecomment-337340270)

thank you @ayj !

**Comment by cmluciano** [comment] 2017-11-09 16:47
duplicate of #1465

**Closed by cmluciano** 2017-11-09 16:47 UTC
Labels: pilot
