### ISSUE TITLE
The destinationRule wants to support the same functionality as the NGINX error_page

### ISSUE THREAD

**Issue by chanyying** [istio/istio#33607] opened 2021-06-24 04:04 UTC
**Describe the feature request**
`The destinationRule wants to support the same functionality as the NGINX error_page`
**Describe alternatives you've considered**
```
subsets:
  - name: testversion
    labels:
      version: v3
    errorPage:
        code:
            - 503
            - 404
        route:
           # cluster external
            - disable: false
               type: redirect
               url: http://xxx.com
          # cluster internal
           - disable: true
              type: host
              host: ratings.prod.svc.cluster.local
              labels:
                   version: v3
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Additional context**

Envoy endorses a similar ability
https://github.com/envoyproxy/envoy/blob/main/docs/root/configuration/http/http_conn_man/local_reply.rst

**Comment by esnible** [comment] 2021-06-24 13:26
I had the same use case.  My solution was custom WebAssembly code, deployed to Envoy using an Istio EnvoyFilter.  The code handled `HttpCall::onResponseHeaders()` and if it saw a 40x/50x it took over, changing body and headers.  It was a lot of work and a declarative way to get the same behavior would be great.

**Comment by howardjohn** [comment] 2021-06-24 18:38
This is a duplicate of https://github.com/istio/istio/issues/29264, lets track there. Thanks!

**Closed by howardjohn** 2021-06-24 18:38 UTC
Labels: area/networking, kind/enhancement
