### ISSUE TITLE
istioctl delete -f option

### ISSUE THREAD

**Issue by sb1975** [istio/istio#24497] opened 2020-06-07 21:03 UTC
**Describe the feature request**
There should be a simple option to specify istioctl delete -f.
The commands are too complex and also if a user dont remember the previous commands used, can he not delete it cleanly ?

There should be a simple command as below :

istioctl delete -f <manifest-file-name>

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[x ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by morvencao** [comment] 2020-06-08 08:02
See discussion for this in https://github.com/istio/istio/issues/18900

**Comment by esnible** [comment] 2020-06-08 11:47
Closing as a duplicate of #18900

**Closed by esnible** 2020-06-08 11:47 UTC
Labels: area/environments, area/user experience, kind/docs, kind/enhancement
