### ISSUE TITLE
istio-ingressgateway fails to start, Envoy proxy is NOT ready

### ISSUE THREAD

**Issue by dprotaso** [istio/istio#32110] opened 2021-04-12 04:13 UTC
**Bug description**

My istio-ingressgateway fails to start because it fails readiness checks

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Installation succeeds and all pods start

**Steps to reproduce the bug**

Using https://github.com/vmware-tanzu/carvel-kapp

```bash
$ kubectl create namespace knative-serving
$ kapp deploy -a knative-istio \
   -f https://github.com/knative-sandbox/net-istio/releases/download/v0.22.1/net-istio.yaml \
   -f https://github.com/knative-sandbox/net-istio/releases/download/v0.22.1/istio.yaml
```
*note this will fail for other reasons (missing resources) - I just noticed introducing more resources changes the timing

notable logs from the ingress pod is
```
2021-04-12T03:42:20.353936Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8081: duplicate listener 0.0.0.0_8081 found

2021-04-12T03:42:20.670847Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
... repeats
```

I think generally Knative has been installing istio with kubectl in two phases - ie. install istio and then knative's additional gateways. see gateways here: https://github.com/knative-sandbox/net-istio/blob/main/config/203-local-gateway.yaml. It's unclear to me if the issue is with our configuration (I believe it is) and how we should change it to avoid this problem.

But with `kapp` the resources are created close enough in time we end up creating the gateway prior to the ingress pod coming up thus surfacing this issue.

**Version** 

Istio 1.8.4 & manifests generated from [this operator file](https://github.com/knative-sandbox/net-istio/blob/main/third_party/istio-stable/istio-ci-no-mesh.yaml)

**Comment by bianpengyuan** [comment] 2021-04-12 04:17
Likely a dup of https://github.com/istio/istio/issues/31084.

**Comment by howardjohn** [comment] 2021-04-12 16:22
Closing as dupe of https://github.com/istio/istio/issues/31084. thanks

**Closed by howardjohn** 2021-04-12 16:22 UTC
