### ISSUE TITLE
Non-strict validation of VirtualService and other resources leads to confusing behavior

### ISSUE THREAD

**Issue by pedrohjordao** [istio/istio#17438] opened 2019-09-27 10:07 UTC
**Bug description**

I have the following VirtualService

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-vs
  namespace: dev
spec:
  hosts:
    - "*"
  gateways:
    - http-gateway
  http:
    - name: "frontend"
      match:
        - uri:
          exact: /app
        - uri:
          exact: /
      route:
        - destination:
            port:
              number: 8081
            host: sa-frontend
    - name: "postauth"
      match:
      - uri:
        prefix: /postauth
      route:
        - destination:
            port:
              number: 8080
            host: postauth

```

I would expect that only the endpoints /, /app and /postauth/* would get exposed, with each being routed to its respective services. Right now every endpoint (even those not listed) are being routed to the first service in the list (so if i change the order the behavior changes)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Routing of the endpoints to the correct services and 404 on end points that do not match the list

**Steps to reproduce the bug**

On a cluster with istio, add the above virtual service definition and try to access endpoints through the gateway. Every endpoint will be routed to the first service on the VS definition

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```bash
$ ./istioctl version --remote
client version: 1.3.0
control plane version: 1.3.0
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T21:50:21Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Installed using the helm charts with the following configuration:

```bash
$ helm template install/kubernetes/helm/istio \
  --set global.mtls.enabled=false \
  --set tracing.enabled=true \
  --set kiali.enabled=true \
  --set grafana.enabled=true \
  --namespace istio-system 
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Ubuntu 19.04 

```bash
 minikube version
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
```

Using the minikube tunnel as a LoadBalancer
[istio-dump.zip](https://github.com/istio/istio/files/3662194/istio-dump.zip)

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by esnible** [comment] 2019-09-27 13:07
It is possible this VirtualService is being ignored because there is another VirtualService for the host "*".  The output of `kubectl get gw,vs --all-namespaces` might help.

It can also be helpful to replace `- "*"` with `- "test"` and use `curl -HHOST=test` to troubleshoot problems where the wrong VirtualService is being used.

Although this VirtualService is correct I have done troubleshooting where another configuration was invalid -- a secret or something -- causing the Envoy sidecar to reject changes to your VirtualService and continuing to use an older one.  Sometimes `kubectl -n istio-system logs <ingresspod>` will show something.  Sometimes I do `istioctl dashboard envoy <ingresspod>.istio-system` and look at the Envoy config_dump.

**Comment by pedrohjordao** [comment] 2019-09-27 13:27
Ok, 
right now i only have one gateway and one VS, so i don't think is the first case (the command confirms that)

Changing the host to test didn't really made a difference.

No errors on the pod log, and i'm not sure what to look for in the envoy dashboard.

**Comment by pedrohjordao** [comment] 2019-09-27 13:37
Huh, ok, i explored a bit of the config_dump, if i'm interpreting it right, the relevant part should be this, right?

```
   "dynamic_route_configs": [
    {
     "version_info": "2019-09-27T13:34:38Z/37",
     "route_config": {
      "name": "http.80",
      "virtual_hosts": [
       {
        "name": "*:80",
        "domains": [
         "*",
         "*:80"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/",
           "case_sensitive": true
          },
          "route": {
           "cluster": "outbound|8081||sa-frontend.socialcheck-dev.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_grpc_timeout": "0s"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking/v1alpha3/namespaces/socialcheck-dev/virtual-service/external-vs"
            }
           }
          },
          "decorator": {
           "operation": "sa-frontend.socialcheck-dev.svc.cluster.local:8081/*"
          },
          "typed_per_filter_config": {
           "mixer": {
            "@type": "type.googleapis.com/istio.mixer.v1.config.client.ServiceConfig",
            "disable_check_calls": true,
            "mixer_attributes": {
             "attributes": {
              "destination.service.host": {
               "string_value": "sa-frontend.socialcheck-dev.svc.cluster.local"
              },
              "destination.service.name": {
               "string_value": "sa-frontend"
              },
              "destination.service.namespace": {
               "string_value": "socialcheck-dev"
              },
              "destination.service.uid": {
               "string_value": "istio://socialcheck-dev/services/sa-frontend"
              }
             }
            },
            "forward_attributes": {
             "attributes": {
              "destination.service.host": {
               "string_value": "sa-frontend.socialcheck-dev.svc.cluster.local"
              },
              "destination.service.name": {
               "string_value": "sa-frontend"
              },
              "destination.service.namespace": {
               "string_value": "socialcheck-dev"
              },
              "destination.service.uid": {
               "string_value": "istio://socialcheck-dev/services/sa-frontend"
              }
             }
            }
           }
          },
          "name": "frontend"
         }
        ]
       }
      ],
      "validate_clusters": false
     },
     "last_updated": "2019-09-27T13:34:38.818Z"
    }
   ]
  },
```

And if i'm getting this right, it seems like the mapping didn't actually got applied, since the only route there is the prefix / mapping...

**Comment by esnible** [comment] 2019-09-27 15:08
I figured it out.

The problem is your YAML indentation:

```
        - uri:
          exact: /app
        - uri:
          exact: /
```

It should be

```
        - uri:
            exact: /app
        - uri:
            exact: /
```

I will continue working on this to see why Istio allowed this configuration.

**Comment by esnible** [comment] 2019-09-27 15:19
@sushicw Here is an example of a customer problem related to non-strict validation you discussed in your comment https://github.com/istio/istio/issues/15012#issuecomment-507797247 .

The web hook and `istioctl validate` should be doing strict validation.  Once the web hook has accepted something, it makes sense for Galley to be less strict about processing it.

**Comment by pedrohjordao** [comment] 2019-09-27 15:29
Wow, that was silly.
Thank you very much!

**Comment by esnible** [comment] 2019-09-27 16:03
@kyessenov I see https://github.com/istio/istio/blob/master/pkg/util/gogoprotomarshal/protomarshal.go#L78 explicitly retries with `AllowUnknownFields`.  Disabling the retry allows `istioctl validate` to detect the problem.

protomarshal.go is new; I didn't look to see how this works in 1.2.

Is there a way we can disable gogoprotomarshal AllowUnknownFields for the web hook and `istioctl validate`?  It wouldn't be hard to add `strict bool` as a parameter to schema.ConvertObject() and all of its friends and callers, but perhaps there is a more elegant way?

**Comment by kyessenov** [comment] 2019-09-27 16:12
@esnible This file is just a copy of another one: https://github.com/istio/istio/blame/master/pkg/util/protomarshal/protomarshal.go#L79

Git blame shows @nmittler as the last one to touch it. I don't know why it's done this way.

**Comment by nmittler** [comment] 2019-09-27 16:56
That was just a code move ... it used to be under pilot: https://github.com/istio/istio/pull/15634/files#diff-a81ffcf40edc6cb8320783f666dc6fe9L97

**Comment by esnible** [comment] 2019-09-27 17:18
I have learned that @pedrohjordao 's mistake was detected by `istioctl validate` in Istio 1.1.5 but not in 1.1.6.  The relaxation was introduced by @ayj 
https://github.com/istio/istio/commit/03977fc3c6d3ae00099009254f4db81021e713a0

Under 1.1.5 and earlier `istioctl validate` on the example yields
```
unknown field "exact" in v1alpha3.HTTPMatchRequest
```

@ayj Can you think of a more elegant way to make istioctl and perhaps the webhook strict about unknown fields, but preserve what you were going for with your change?

**Comment by ayj** [comment] 2019-09-27 17:48
We've gone back and forth on this in the past. I'd prefer strict but we kept hitting compatibility issues when adding/removing new flags to MeshConfig. 

`ApplyYAML()` excepts `strict` flag. You could plumb that through accordingly and default to true for config validation. We can use strict as well for MeshConfig since we're moving towards using that as _the_ install/runtime API instead values.yaml

**Comment by jasonwzm** [comment] 2019-11-01 17:35
With the CRD validation, API server will output errors for the incorrect config. The example config will have the following error:
`The VirtualService "external-vs" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"networking.istio.io/v1alpha3", "kind":"VirtualService", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"external-vs\",\"namespace\":\"dev\"},\"spec\":{\"gateways\":[\"http-gateway\"],\"hosts\":[\"*\"],\"http\":[{\"match\":[{\"exact\":\"/app\",\"uri\":null},{\"exact\":\"/\",\"uri\":null}],\"name\":\"frontend\",\"route\":[{\"destination\":{\"host\":\"sa-frontend\",\"port\":{\"number\":8081}}}]},{\"match\":[{\"prefix\":\"/postauth\",\"uri\":null}],\"name\":\"postauth\",\"route\":[{\"destination\":{\"host\":\"postauth\",\"port\":{\"number\":8080}}}]}]}}\n"}, "creationTimestamp":"2019-11-01T17:33:27Z", "generation":1, "name":"external-vs", "namespace":"dev", "uid":"b6f0169d-fccd-11e9-9797-42010a80004e"}, "spec":map[string]interface {}{"gateways":[]interface {}{"http-gateway"}, "hosts":[]interface {}{"*"}, "http":[]interface {}{map[string]interface {}{"match":[]interface {}{map[string]interface {}{"exact":"/app", "uri":interface {}(nil)}, map[string]interface {}{"exact":"/", "uri":interface {}(nil)}}, "name":"frontend", "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"sa-frontend", "port":map[string]interface {}{"number":8081}}}}}, map[string]interface {}{"match":[]interface {}{map[string]interface {}{"prefix":"/postauth", "uri":interface {}(nil)}}, "name":"postauth", "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"postauth", "port":map[string]interface {}{"number":8080}}}}}}}}: validation failure list:
spec.http.match.uri in body must be of type object: "null"`

**Closed by jasonwzm** 2019-11-01 17:35 UTC
Labels: area/config
