### ISSUE TITLE
Can't set Ingress Gateway's service annotation with istioctl

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#20683] opened 2020-01-30 08:09 UTC
**Bug description**

Service annotation can't be set via istioctl installation.

Tried setting:

spec.unvalidatedValues.gateways.istio-ingressgateway.serviceAnnotations
spec.gateways.components.ingressGateway.k8s.service.annotations
spec.values.gateways.istio-ingressgateway.serviceAnnotations

But no success

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by esnible** [comment] 2020-01-30 19:03
There are PRs for `--set` behavior.  The one related to commas has merged.  The one related to slices will merge soon.  https://github.com/istio/istio/issues/20381

**Comment by esnible** [comment] 2020-01-30 19:29
Closing as a duplicate of https://github.com/istio/istio/issues/19307 and https://github.com/istio/istio/issues/19196

**Closed by esnible** 2020-01-30 19:29 UTC
Labels: area/environments, area/user experience

**Comment by morvencao** [comment] 2020-01-31 02:32
@cagataygurturk 
Have you tried this?
```
spec.gateways.components.ingressGateway.k8s.serviceAnnotations
```

This should be the right way to add `serviceAnnotations`?
