### ISSUE TITLE
Continuous CrashLoopBackOff: istio-statsd-prom-bridge pod

### ISSUE THREAD

**Issue by focks** [istio/istio#8797] opened 2018-09-18 07:25 UTC
**Continuous CrashLoopBackOff: istio-statsd-prom-bridge pod**
```
NAME                                       READY     STATUS             RESTARTS   AGE
. . .
istio-statsd-prom-bridge-f8fcf6c74-jwjd6   0/1       CrashLoopBackOff   5          5m
. . .
```
The log is `statsd_exporter: error: unknown short flag '-s', try --help`

**Version**
* kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
* istioctl version
```
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```
**Installation**
followed option two https://istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install inorder to install istio.

**Environment**
kubernetes cluster in `aws`. The cluster was created using kops.
admission controllers are enabled in the cluster.

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2391589/istio-dump.tar.gz)

**Comment by sdake** [comment] 2018-09-20 11:01
This is caused by the use of the `latest` tag in 0.8.0 for the statsd exporter.  statsd-exporter had breaking changes in the CLI API from 0.6.0 to 0.7.0.  A workaround is to add the following to the helm command line: `--set mixer. prometheusStatsdExporter.tag=v0.6.0`.

Istio 0.8.0 is no longer under LTS support; recommend upgrading to Istio 1.0.2 or later.

Since this is a KI with a workaround and Istio 0.8.0 is no longer under LTS support, I am closing this issue.  If you feel this is an error, please feel free to reopen the issue.

See https://github.com/istio/istio/issues/8293 and https://github.com/istio/istio/pull/8249 for more details.

Cheers
-steve

**Closed by sdake** 2018-09-20 11:01 UTC
