### ISSUE TITLE
TestXdsProxyStatus failures

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37169] opened 2022-02-04 18:29 UTC
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37162/integ-pilot-istiodremote_istio/1489422911918837760

Here https://github.com/istio/istio/blob/7227423b6b062293188d00d1151578e74d2bdab3/pkg/test/framework/components/istio/operator.go#L628 we set the Istiod Address

This is a pod IP
Istiod autoscales up to 2 pods, because the istiodless code doesn't set the same config as in cluster (which has autoscaling disable)
We picked the wrong istiod in that code above, so we hit an istiod with 0 connections and fail

**Comment by frankbu** [comment] 2022-02-07 19:20
In the integration test environment, an external control plane's istiod is exposed as a loadbalancer-type service:
https://github.com/istio/istio/blob/b2685544d40c10b5c01a0e33c80e13949f6bb5d1/tests/integration/iop-externalistiod-primary-integration-test-defaults.yaml#L19
The framework should use the service IP if there is one, but the problem is that `kind` doesn't support LoadBalance out of the box, so we use the pod IP instead:
https://github.com/istio/istio/blob/7227423b6b062293188d00d1151578e74d2bdab3/pkg/test/framework/components/istio/util.go#L108
So, the problem is because the integration framework uses `kind` without metallb or some other loadbalancer support. We could conceivably setup the cluster using metallb, like [we suggest users do for testing with kind](https://github.com/istio/istio/tree/master/samples/kind-lb), or we could set up a gateway, like we do in the external control plane docs.

I'm inclined to think that since this is just for integration testing, and there's no real benefit to scaling up istiod for these tests, why not just fix this by disabling autoscaling of istiod, that is, I think the temporary workaround for this issue,  #37170, is the permanent fix.

@howardjohn WDYT?

**Comment by howardjohn** [comment] 2022-02-07 20:18
I think for all of our tests we always deploy metallb. So I feel like we can disable scaling long term and use load balancer -- since that is what any real user would need anyways.

**Comment by frankbu** [comment] 2022-02-08 16:31
I wasn't aware that we always deploy metaldb in the integration test env. I ran the tests locally and confirmed that, in fact, `s.LoadBalancerSupported` is `true`, so I don't understand how this part of the issue description can be true:

> we set the Istiod Address
>
> This is a pod IP

The code uses the service IP for the istiodAddress if there is loadbalancer support.

Is the `postsubmit` configuration different, i.e., no metaldb deployment)?

@howardjohn Am I missing something here?

**Comment by frankbu** [comment] 2022-02-08 21:04
Opened new issue #37217.

This issue is fixed by #37170.

**Comment by howardjohn** [comment] 2022-07-18 16:52
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39896/integ-pilot-istiodremote_istio/1548796671507304448, https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39896/integ-pilot-istiodremote_istio/1548635578541543424

**Comment by howardjohn** [comment] 2022-07-20 18:07
https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-istiodremote_istio_postsubmit/1549524310748565504

**Closed** 2022-08-12 15:25 UTC
Labels: area/networking, kind/test failure
