### ISSUE TITLE
Generate OpenAPI Spec for our CRDs

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12085] opened 2019-02-26 19:59 UTC
We should generate OpenAPI Spec for our CRDs.

/cc @geeknoid

**Comment by mingfang** [comment] 2019-03-26 21:27
This feature https://github.com/kubernetes/kubernetes/pull/71192 in Kubernetes v1.14 makes CRDs with OpenAPI very useful for tools that using the openapi to work with Kubernetes.
My Terraform Provider for Kubernetes https://github.com/mingfang/terraform-provider-k8s is one such tool.  It would be great if the Istio CRDs have OpenAPI specs.

**Comment by esnible** [comment] 2019-03-28 19:06
Closing as a duplicate of https://github.com/istio/istio/issues/10872 .  Adding `area/config` to that issue.

**Closed** 2019-06-12 15:01 UTC
Labels: area/config
