### ISSUE TITLE
RPM package as available artifact

### ISSUE THREAD

**Issue by MrTrustor** [istio/istio#9117] opened 2018-10-03 14:41 UTC
**Describe the feature request**
I was able to expand an istio mesh to a Debian VM following [this tutorial](https://github.com/GoogleCloudPlatform/gke-istio-gce-demo/). This tutorial relies on the istio-sidecar.deb (available as an artifact in the github release page) being installed on the VM.
In reality, we need to expand the mesh to CentOS VMs, so I would need an RPM package.

**Describe alternatives you've considered**
We thought about using the Debian-based Docker images and running them on our CentOS VMs, but we're not sure if that's even an option.

**Additional context**
In both cases (RPM package or Docker images), I'm first looking for help scoping the work that would be needed.

cc @racyber

**Comment by knrc** [comment] 2018-10-03 17:44
@MrTrustor We have been developing RPMs and containers based on CentOS and RHEL, with the CentOS images currently available through docker hub.  The CentOS RPMs are being built on COPR with most of the istio components covered.  Would any of this help?

https://copr.fedorainfracloud.org/coprs/g/maistra/istio/build/797491/

Note we are using a different versioning scheme from upstream, the 0.2.0 release is based on Istio 1.0.2.

**Comment by MrTrustor** [comment] 2018-10-05 07:02
Hi @knrc, thanks for the answer!
We will take a look at what you have and report back. That may take a while though :-)

**Comment by MrTrustor** [comment] 2018-10-17 10:05
So I took a look at your RPMs @knrc, and they seem a good start to me, but from what I understand it's not enough to actually extend an istio mesh to a CentOS VM.
For reference, here is what I get on Debian with the `istio-sidecar.deb` package:

```
root@istio-vm:~# dpkg -L istio-sidecar
/.
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/istio.service
/lib/systemd/system/istio-auth-node-agent.service
/usr
/usr/share
/usr/share/doc
/usr/share/doc/istio-sidecar
/usr/share/doc/istio-sidecar/changelog.gz
/usr/local
/usr/local/bin
/usr/local/bin/node_agent
/usr/local/bin/envoy
/usr/local/bin/istio-iptables.sh
/usr/local/bin/istio-start.sh
/usr/local/bin/pilot-agent
/usr/local/bin/istio-node-agent-start.sh
/var
/var/lib
/var/lib/istio
/var/lib/istio/envoy
/var/lib/istio/envoy/envoy_bootstrap_tmpl.json
/var/lib/istio/envoy/sidecar.env
```

Actually creating a RPM that packages the same things and does the same doesn't seem too hard, but the question is how do we ensure that this RPM is tested regularly and maintained by someone. Is that something you could help with?

**Comment by MrTrustor** [comment] 2018-10-23 11:58
Hi,

Quick update on the topic: we tried to extend an istio mesh to a CentOS vm manually with no success.
We are blocked by an incompatible envoy binary. We tried 3 of them:

- the one from the Debian package doesn't work because of a wrong libc version
- the one from the package you linked earlier in this issue doesn't work because it doesn't have the "--allow-unknown-fields" flag.
- the one we extracted from a Docker image doesn't work for the same reason.

**Comment by knrc** [comment] 2018-10-23 12:12
@MrTrustor If you are getting an unknown flag error then it's likely the version of istio you are using doesn't match these images, we are currently building RPMs for 1.0.2 and will shortly update to 1.0.3.

Which version are you using?

**Comment by MrTrustor** [comment] 2018-10-23 13:19
We took the content of the [istio-sidecar.deb 1.0.2 package](https://github.com/istio/istio/releases/tag/1.0.2) and tried to adapt it to run on CentOS.
The `pilot-agent` from that package launches envoy with the following arguments:

```
/usr/local/bin/envoy -c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 2 --parent-shutdown-time-s 3 --service-cluster mysqldb --service-node sidecar~10.132.0.12~istio-vm.vm~vm.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warn --v2-config-only
```

**Comment by knrc** [comment] 2018-10-24 08:40
@MrTrustor I'm going to talk with Andy and see about getting some RPMs built as part of this issue, in the meantime if you can send me more detailed information about your testing, I'll try to reproduce it.  I'm concerned our 1.0.2 images appear to be incompatible with the ones you are trying to use so would like to understand what is happening.

**Comment by MrTrustor** [comment] 2018-11-27 17:50
For the records, some initial work on this is being done on #9701

**Comment by SrinivReddy** [comment] 2019-01-24 05:15
@MrTrustor  , Did you configure mesh expansion on RHEL/CesntOS ?

**Comment by MrTrustor** [comment] 2019-01-24 09:03
Yes. I've been working with the istio team at Google, along with the RedHat team.
We have a working prototype for now (I'll let the istio team decide if they want to share it). Producing a production-ready RPM as part of the release process is currently being worked on.

**Comment by SrinivReddy** [comment] 2019-01-24 09:16
@MrTrustor , Great, how soon we expect a release or pre-release..?

**Comment by MrTrustor** [comment] 2019-01-24 09:19
Probably sometime this spring, but I don't have a specific schedule.

**Comment by knrc** [comment] 2019-01-24 09:48
@MrTrustor If you want to share your work with us then we can help, we already publish CentOS RPMs via copr with containers based on those to dockerhub as well as push RHEL based containers to our public repo.

**Comment by MrTrustor** [comment] 2019-01-24 12:31
@knrc you are still talking about those packages, right? https://copr.fedorainfracloud.org/coprs/g/maistra/istio/packages/
If so, I can probably test them again in the next 2 weeks and will report back after that.

**Comment by SrinivReddy** [comment] 2019-01-24 12:38
@MrTrustor, I am also facing same issue with envoy binary 

earlier you mention below points about envoy binary

1)the one from the Debian package doesn't work because of a wrong libc version
2) the one from the package you linked earlier in this issue doesn't work because it doesn't have the --allow-unknown-fields flag.
3) the one we extracted from a Docker image doesn't work for the same reason.

I am also facing same issue, can you please guide me, where to get suitable envoy binary ???

**Comment by MrTrustor** [comment] 2019-01-24 15:40
@SrinivReddy you can try [this RPM](https://storage.googleapis.com/theochamley-share/istio-sidecar.rpm). This is our PoC. It comes with all the warnings you can expect: it's not supported, I don't guarantee that it will work, etc., etc.

**Comment by SrinivReddy** [comment] 2019-01-25 09:50
@MrTrustor , Sorry Its working fine, thanks a lot, 
1) I am able to connect k8s services, and en=xternal Vm registered with k8s cluster(istioctl proxy-status)
2) But in istio.err.log getting  metadata missing warning.

[ec2-user@ip-xx-xx-xx-xx istio]$ cat istio.err.log
[2019-01-25 08:17:33.596][006119][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, no healthy upstream
[2019-01-25 08:17:33.596][006119][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:51] Unable to establish new stream
[2019-01-25 08:17:35.208][006119][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2019-01-25 08:17:35.213][006119][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2019-01-25 08:17:35.217][006119][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2019-01-25 08:17:35.221][006119][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:

**Comment by MrTrustor** [comment] 2019-01-25 15:31
@SrinivReddy I don't think I had this exact error at any point, but try to check the TLS parameters of istio on your VM. That's what caused us the most problems.

**Comment by SrinivReddy** [comment] 2019-01-25 15:41
@MrTrustor , Okay, Can please tell us for which istio version above istio-sidecar.rpm will suitable...?

**Comment by MrTrustor** [comment] 2019-01-25 15:48
It should be OK for 1.0.x.

**Comment by SrinivReddy** [comment] 2019-01-29 07:08
@MrTrustor , I tried with differe ISTIO versions and both RHEL and CentOS but no luck, I think i am missing some configurations, can you please tell us the steps to configure  RHEL/CentOS vm.

**Comment by MrTrustor** [comment] 2019-01-29 20:43
@SrinivReddy Sorry, I can't really help you here. We managed to make it work more or less following what [this repo](https://github.com/GoogleCloudPlatform/gke-istio-gce-demo) does, but you will need to work it out waiting for an official support.

**Comment by MrTrustor** [comment] 2019-03-26 15:57
For those following this issue, a PR has been created: #12704

**Comment by howardjohn** [comment] 2019-06-04 01:19
I think this is fixed by https://github.com/istio/istio/pull/13088, @jwendell can you close this if this is completed?

**Comment by incfly** [comment] 2019-06-04 02:09
This is not done yet we haven't generated rpm as of cloud build artifacts.
I have a pending PR for this.

**Comment by jwendell** [comment] 2019-09-09 17:33
> I think this is fixed by #13088, @jwendell can you close this if this is completed?

rpm's can be built manually, but AFAICT they're not released as artifacts yet.

**Comment by incfly** [comment] 2019-09-09 17:38
@jwendell I gave it a shot trying to add the build rpm target to the Makefile as of cloud/release build process. However it's taking too much time, and timeout for the 20 minute deadline of release.sh script. This is mostly due to the Envoy build process.

We need to do things similar to deb, add builds in istio/proxy and istio/istio just download from prebuild GCS bucket. https://github.com/istio/istio/pull/13802#issuecomment-519730442

I took a look of the `pkg_rpm` bazel rule, that takes RPM spec rule file as input as well.

**Comment by PapashaEnot** [comment] 2019-09-19 17:52
HI! Is there any progress in making rpm release artifact ? My company want to expand Istio on VM with RHEL/Centos. And we are very interested in rpm package for Istio. How can we build prm package manualy ? And what the difference between docker image sidecar and package sidecar ? Is it possible to expand Istio with docker image ?

**Comment by vadimeisenbergibm** [comment] 2019-09-24 19:48
+1 for the requirement for RPM.

**Comment by incfly** [comment] 2019-10-10 06:35
2019/10/08 Summarize of an unsuccessful attempt of adding this to cloud build
https://github.com/istio/istio/pull/13802

Naively build proxy by `make rpm` from scratch does not work efficiently, which time out our release build target in CI/CD. Instead as [suggested](https://github.com/istio/istio/pull/13802#issuecomment-519730442), we should use pre-built bazel RPM target somewhere, and Istio target just download and package it with pilot agent.

On the other hand, I remembered correct some Istio/Envoy vendor already provide Envoy RPM artifacts... not sure if it's feasible to reuse the efforts.

**Comment by howardjohn** [comment] 2019-10-10 15:40
Not familiar with RPM, but for the deb ones we don't rely on a "pre-built bazel deb target". We just use the standard envoy binary that istio/proxy produces (just like we do with proxyv2 docker image). Is that something we can do it rpm as well, or do we need a special RPM artifact of envoy?

**Comment by zachidan** [comment] 2019-11-13 14:37
What is the status of this issue ?

Is there any progress/plan in making rpm release artifact ?

**Comment by incfly** [comment] 2019-11-13 18:37
@smawson FYI as part of the VM story.

**Comment by daniyalj** [comment] 2020-03-19 02:03
+1 for Redhat/Centos support

**Comment by jwendell** [comment] 2020-04-29 22:36
@howardjohn is this essentially what you're doing on #22448? We should close this one then if it's the case...

**Comment by howardjohn** [comment] 2020-04-29 22:45
Yes its the same. We can probably close that one instead as this one has much more history

**Comment by sdake** [comment] 2020-05-15 19:31
@howardjohn I have extensive knowledge of RPM. I can help here. How were you able to solve the glibc problem? Every solution I have seen thus far involves patching Envoy.

**Comment by sdake** [comment] 2020-05-15 19:33
RPM [Spec file](https://download.copr.fedorainfracloud.org/results/@maistra/istio/epel-8-x86_64/01062229-istio-proxy/istio-proxy.spec)

**Comment by sdake** [comment] 2020-05-15 19:36
More recent spec files: https://github.com/Maistra/rpms

**Comment by howardjohn** [comment] 2020-05-18 16:58
Steve, the approach I came up with is  we need to create a
build-tools-centos that is based on CentOS 7 and build the proxy image with
that. I have such a Dockerfile in the tools repo but haven't gotten things
running end to end yet. Once we build with that, it will have the correct
glibc version.

With the proper envoy binary, the RPM shouldn't be too much work. The main
work here is in envoy build system/CI

**Closed** 2020-07-14 15:45 UTC
Labels: area/test and release, feature/Virtual-machine, kind/enhancement
