### ISSUE TITLE
Non deterministic ingress gateway https request hanging

### ISSUE THREAD

**Issue by piotrmsc** [istio/istio#23855] opened 2020-05-14 12:51 UTC
**Bug description**

I have an issue with connectivity via ingress gateway to the sidecar enabled service over HTTPS. Requests made via ingress hangs in a non-deterministic way.
In my case, I have an application deployed in the namespace with sidecar. This application reads request body, modifies it (adds more content), and returns it in the response. 
For payloads with size like a couple of KB or couple of MB I have no issue, however, for some reason when I send payload around 700KB it starts to hang in a non-deterministic way. Some calls pass and some of them just hang.

It sometimes succeed with 200 status and sometimes hang, handshake is established. Additional verbose logs from curl : 
```
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fbb9b808200)
> POST /anything HTTP/2
> Host: test.$DOMAIN
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 744977
> Content-Type: application/x-www-form-urlencoded
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
* We are completely uploaded and fine
```
and that's all. 

In the ingress istio-proxy container I noticed following logs : 
`2020-05-14T11:30:55.486687Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2020-05-14T11:30:55.486711Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc000407d70, {CONNECTING <nil>}
2020-05-14T11:30:55.493338Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc000407d70, {READY <nil>}`

and the same one in application sidecar but not when the request is being made.
Additional info: 
- The issue does not reproduce in calls made internally - pod A to pod B ( all pods have sidecars) but only when making a request via ingress gateway.
- The issue does not reproduce using HTTP via ingress.

Let me know if you need any specific information ;-)

Istio setup : 
- istio deployed with demo profile and mtls enabled.
- Gateway with HTTP and HTTPS (TLS simple) (not you will need to provide your own cert)
- VirtualService 
- Sample httpbin app (for reproducing the issue)

**Expected behavior**

Calls do not hang and return the response to the client.

**Steps to reproduce the bug**

- Deploy istio with mtls enabled
- Deploy sample httpbin with sidecar (in the example my namespace pm has sidecar injection enabled)

```
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: pm
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: pm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        command:
          - /bin/bash
          - -c
          - |
            sleep 20
            gunicorn -b 0.0.0.0:80 httpbin:app -k gevent
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```
- Create Gateway and VirtualService

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: pm
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gateway-certs
      minProtocolVersion: TLSV1_1
      cipherSuites:
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-SHA
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-SHA
    hosts:
      - "*.$DOMAIN"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*.$DOMAIN"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-test
  namespace: pm
spec:
  hosts:
    - 'test.$DOMAIN'
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            regex: /.*
      route:
        - destination:
            host: httpbin.pm.svc.cluster.local
            port:
              number: 8000
```

- Make a curl to httpbin service via ingress with the attached file as payload:
`curl -ik -X POST -d @payload.txt https://test.$DOMAIN/anything -o /dev/null -s -w "%{http_code}"`
Notice I have used `/anything` endpoint of httpbin as it also returns the request body in the response to simulate my scenario.

The attached file [payload.txt](https://github.com/istio/istio/files/4628262/payload.txt) is just a sample json in text file (Github does not allow me to attach JSON files) with some random data generated [by generator](https://www.json-generator.com/) for reproducing purposes.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio 1.5.2 and istio 1.4.7

`client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 (5 proxies)
`
**How was Istio installed?**
`istioctl manifest apply --set profile=demo --set values.global.mtls.enabled=true`
**Environment where bug was observed (cloud vendor, OS, etc)**
GCP,kubernetes 1.16.9

**Comment by howardjohn** [comment] 2020-07-28 21:20
Thanks for the detailed reproducer! I tried this out on my cluster, following the same steps, but was unable to reproduce. How rare is it? I ran about 1000 requests and didn't see it. It would be interesting to see envoy debug logs when this happens.

When it hangs, what happens? It is slow or it never completes?

**Comment by piotrmsc** [comment] 2020-08-11 06:32
@howardjohn which version did you use to reproduce? I did not test it on the 1.6/1.7. In general when it happens it looks like it never completes. How frequent it was? On average 1 in 10 requests, but I was able to reproduce in "worst" case 1 on 5 requests. I will try to use latest version and try to reproduce.

**Comment by howardjohn** [comment] 2020-08-11 14:38
I probably used 1.7/master, wasn't sure if I was expecting to see it once every 1 million requests and miss it though looks like its more obvious than that so must be a difference in environment or setup

**Comment by howardjohn** [comment] 2020-10-23 00:28
Did you get a chance to try on newer version?

**Comment by amckee23** [comment] 2020-11-02 14:47
I am seeing the same issue on 1.7.4 

It seems to be approx 1/4 requests to the endpoint are impacted.  Interestingly only when the content type is not application/json.  If i set it correctly i see traffic working the issue appears if i change it to text/plain.

**Comment by howardjohn** [comment] 2020-11-02 15:10
@amckee23 any chance you have some reproducible config?

If not, is it possible for you to get a config dump and debug logs from the ingress pod? see https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2 for more info

**Comment by amckee23** [comment] 2020-11-02 16:33
Sorry for the delay @howardjohn i was doing a little extra digging.

for us it looks to be an issue when the upstream server returns an exception and istio tries to reuse the connection.  Adding a destination rule with the following:
`apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-flakey-host
spec:
  host: my-flakey-host.dev.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1`

**Comment by piotrmsc** [comment] 2020-11-02 16:42
@howardjohn I did not have later on time to test on new version.

@amckee23 what do you exactly mean by "server returns an exception"? In my scenario, I reproduced it with example httpbin and there wasn't any server-side errors.

Did limiting connectionPool : maxRequestsPerConnection  as above helped in your case?

**Comment by amckee23** [comment] 2020-11-02 16:50
Yes sorry im not suggesting the exception was the reason for the issue.  I suspect (although i haven't had time to go into the next level of detail) that the issue is the server is closing connections incorrectly in-between requests. We are running our regression packs now but we have gone from ~25 failures per run to so far 0.

**Comment by howardjohn** [comment] 2020-12-29 00:15
Since we cannot reproduce and there is no updates for many months, and its for EOL'd versions, I am going to close this. if any progress is made on reproducing on a latter version please re-open and we can investigate this further. Thanks!!

**Closed by howardjohn** 2020-12-29 00:15 UTC
Labels: area/networking, kind/need more info
