### ISSUE TITLE
Adding Probes to sidecars

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1404] opened 2017-11-03 22:38 UTC
@kameshsampath commented on [Wed Jul 05 2017](https://github.com/istio/old_pilot_repo/issues/908)

I see right now the sidecars does not have liveliness and readiness probes attached to them, sometime when i restart the servers e.g. minikube the apps immediately shows its Running 2/2 but when the apps tries to connect it shows connection refused ...  the `kubectl describe <pod>` shows that its trying to pull images with policy "Always"..

will it be worth to add probes or is there any other rationale behind not adding ?

---

@kyessenov commented on [Wed Jul 05 2017](https://github.com/istio/old_pilot_repo/issues/908#issuecomment-313162369)

Yes, it's definitely worth adding them to the sidecar. Ideally, to the proxy itself, so that k8s awaits for the first successful fetch of RDS/LDS from Envoy.

---

@sakshigoel12 commented on [Fri Aug 18 2017](https://github.com/istio/old_pilot_repo/issues/908#issuecomment-323488245)

Please add assignees

---

@cmluciano commented on [Mon Oct 30 2017](https://github.com/istio/old_pilot_repo/issues/908#issuecomment-340575933)

/assign

**Comment by cmluciano** [comment] 2017-11-09 16:51
duplicate of https://github.com/istio/istio/issues/1472

**Closed by cmluciano** 2017-11-09 16:51 UTC
Labels: pilot
