### ISSUE TITLE
Helm test failed with istio-injection enabled

### ISSUE THREAD

**Issue by zaisongz** [istio/istio#13166] opened 2019-04-09 05:23 UTC
k8s version: v1.13.4
Helm version: v2.13.0
istio version: 1.0.6

When i enabled istio-injection in my namespace, the ETCD cluster could be established correctly, but the helm test command always get below error,
[stan-istio]# helm test stan
RUNNING: stan-000-status-test
ERROR: timed out waiting for the condition
Error: 1 test(s) failed

When there is no istio enabled, the test could pass, but now it always hung there until timeout. From log, i can see the test has been run, and passed. What should i do to make this works?

**Comment by zaisongz** [comment] 2019-04-09 07:27
Just have a try if i logon the envoy sidecar, and run 'kill 1', the test will get pass.
[tests]# helm test stan
RUNNING: stan-000-status-test
PASSED: stan-000-status-test

Anyone has idea about how to terminate the sidecar?

**Comment by howardjohn** [comment] 2019-04-09 17:53
What does the `helm test` do?

**Comment by zaisongz** [comment] 2019-04-10 01:20
i used a chart to deploy etcd cluster, and the test just run some cases to check the cluster healthy.
The reason is that the sidecar keep runing even the main container has finished it works. 
# kubectl get pods -o wide -n istio-csdc
NAME                      READY   STATUS    RESTARTS   AGE   IP              NODE                                    
stan-000-status-test   1/2     Running   0                17h   192.168.1.38

Once sidecar was killed, the status will become "completed", then helm test will show the  result.

**Comment by howardjohn** [comment] 2019-04-10 01:29
Ok so the problem is your container exits, and envoy (Sidecar) remains running?

**Comment by zaisongz** [comment] 2019-04-10 02:22
yes.

**Comment by zaisongz** [comment] 2019-04-12 02:19
@howardjohn any idea?

**Comment by howardjohn** [comment] 2019-04-16 17:01
Just found this today - https://github.com/istio/istio/issues/6324. There is alot of discussion around this there (although there doesn't seem to be a great solution yet). I am going to close this as it is a duplicate of that issue

**Closed by howardjohn** 2019-04-16 17:01 UTC
