### ISSUE TITLE
Ingress downtime during rollouts

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#26524] opened 2020-08-14 20:59 UTC
**Bug description**

When rolling out a new version of the Istio Ingressgateways, we expect there to be no downtime or failed requests. However, we observe failed requests.

**Steps to reproduce the bug**

Given a kubernetes cluster with Istio installed [with istioctl](https://istio.io/latest/docs/setup/install/istioctl/)
And [bookinfo](https://istio.io/latest/docs/examples/bookinfo/) deployed
And I have more than one ingressgateway
When I repeatedly send requests to my app during a rollout
Then I expect no errors, and no unreasonable latencies

**Observed behavior**

We used the following ruby (sorry) test script to repeatedly request our endpoint. It repeatedly makes requests against an endpoint as quickly as it can, and then when it receives an interrupt it outputs the errors it received.

<details>
 <summary>test.rb</summary>

```ruby
require 'net/http'

errors = 0
successes = 0
begin
  Kernel.loop do
    begin
      request = Net::HTTP.get_response("35.236.26.249", "/productpage")

      if request.is_a?(Net::HTTPSuccess)
        successes += 1
      else
        puts "ERROR:"
        puts request.code
        puts request.message
        puts request.http_version
        errors += 1
      end
    rescue Errno::ECONNREFUSED
      puts "ERROR:"
      puts "Connection refused!"
      errors += 1
    end
  end
rescue Interrupt
  puts "interrupted"
  puts "Successes:\t" + successes.to_s
  puts "Errors:\t" + errors.to_s
  puts "Success %:\t" + ((successes.to_f / (successes + errors)) * 100).to_s
end
```
</details>

When we run it without a rollout happening, we reliably get zero errors.

When we run the script while simultaneously running `kubectl rollout restart deployment -n istio-system istio-ingressgateway` we often (but not always) see multiple connection refused errors. We wrote the ruby script because we weren't sure that [our golang implementation of the same concept](https://github.com/cloudfoundry/cf-k8s-networking/blob/upgrade-ci/test/uptime/data_plane_uptime_test.go#L37-L65) that we're using in our pipelines was the culprit, but we see the problem in both.

Our service level objective for dataplane uptime during deployments is 99%, and most of the time in our tests these errors cause us to come in under that objective.

We've experimented with sleeping in a preStop and postStart, as well as modifying values around liveness and readiness probes, but have not seen sufficient improvement to meet 99% uptime.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (17 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
$ istioctl install
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by howardjohn** [comment] 2020-08-19 02:57
I think this is fixed by the above pr. I tried with your test script and it passes now. Please let me know if you see the same

**Comment by ndhanushkodi** [comment] 2020-08-19 21:26
Hi @howardjohn we created an istioproxxyv2 image with your changes from the above PR, and when we run our test with `TERMINATION_DRAIN_DURATION_SECONDS` set to 30 on the ingressgateway deployment, we see all of the requests succeed. Thanks!

cc @KauzClay

**Comment by howardjohn** [comment] 2020-09-23 01:05
Closing as this is fixed in https://github.com/istio/istio/pull/26528

**Closed by howardjohn** 2020-09-23 01:05 UTC
Labels: area/networking, area/perf and scalability, lifecycle/needs-triage

**Comment by iliyan-velichkov** [comment] 2022-05-10 10:35
Hi @howardjohn,
I'm observing the same behaviour with istio 1.12.6 using istio-ingressgateway service config `externalTrafficPolicy: Local`.
It is working as expected with `externalTrafficPolicy: Cluster`.
I also tried to modify `terminationDrainDuration` default mesh config but it didn't help.
Do you have any suggestions how to resolve this issue?

**Comment by howardjohn** [comment] 2022-05-10 13:17
If you use Local it's your responsibility to ensure all nodes have >1 replicas active at a time

**Comment by iliyan-velichkov** [comment] 2022-05-10 18:33
I increased the ingressgateway instances to 2 instances per node and it looks like the issue is resolved. 
Could you please explain why there are connection errors if we have one instance per node and how two instances resolves the problem?

**Comment by jonnylangefeld** [comment] 2022-05-12 17:10
I'm also curious about why 2 ingressgateway instances per node would work better. If a node is scheduled to get deleted all the pods on it get terminated right? So `terminationDrainDuration` sounds like it should help (it also didn't in our case).

How can we configure a kubernetes deployment to always schedule 2 ingressgateway pods per node? We can only have 1 per node (with podAntiAffinity) or `n` per node, but not exactly 2...

**Comment by vnhirenko** [comment] 2022-10-12 07:22
Same problem. Does anyone resolved this problem?

**Comment by mirobertod** [comment] 2023-01-13 16:58
> If you use Local it's your responsibility to ensure all nodes have >1 replicas active at a time

Hi @howardjohn , could you elaborate on that?
Thanks!

**Comment by howardjohn** [comment] 2023-01-13 17:09
This is a k8s thing, not istio. Various blogs like https://www.asykim.com/blog/deep-dive-into-kubernetes-external-traffic-policies can help

**Comment by mirobertod** [comment] 2023-01-13 19:43
> This is a k8s thing, not istio. Various blogs like https://www.asykim.com/blog/deep-dive-into-kubernetes-external-traffic-policies can help

Thanks @howardjohn  for the link, but that does not explain why we should ensure all nodes have >1 replicas active at a time.
Also, as said by @jonnylangefeld , having 1 or >1 replicas on the same node wouldn't make any difference in caso of node shutdown.
