### ISSUE TITLE
Warn if istioctl version is different from that installed in the cluster

### ISSUE THREAD

**Issue by ostromart** [istio/istio#25328] opened 2020-07-08 16:23 UTC

**Comment by esnible** [comment] 2020-07-09 14:48
This is a duplicate of https://github.com/istio/istio/issues/23074 .  Please close this one and set the mileston and priority of that one.

**Comment by esnible** [comment] 2020-07-09 16:11
Related: https://github.com/istio/istio/issues/18487

**Closed** 2020-07-23 21:08 UTC
Labels: area/environments/operator, lifecycle/needs-escalation
