### ISSUE TITLE
Rate Limits error

### ISSUE THREAD

**Issue by Belyenochi** [istio/istio#14525] opened 2019-06-03 13:53 UTC
**Bug description**
environment:
  Handler: When a request is made in five seconds duration 60s;
  Client: JMeter 20 req/s

result: 
  use maxcount,no dimensions in handler, no match in rule. real success: 0.95% expect: 1%
  use maxcount,use dimensions in handler, no match in rule. real success: 1.30% expect: 1%
  use maxcount,use dimensions in handler, no match in rule. real success: 1.88% expect: 1%

I want to know the reasons for these errors (except The memquota adapter uses a sliding window of sub-second resolution to enforce rate limits.),thanks very much.

**Affected product area (please put an X in all that apply)**
global.

**Comment by douglas-reid** [comment] 2019-06-03 18:48
I believe this is a duplicate of #3028. Rate limit quotas are not exact, especially over small time windows for low levels of traffic. Closing in favor of the original issue. For discussion, please use the discuss.istio.io forum.

**Closed by douglas-reid** 2019-06-03 18:48 UTC
Labels: area/policies and telemetry
