### ISSUE TITLE
Istio sidecar injection failed ( Internal error occurred: failed calling webhook "sidecar-injector.istio.io" )

### ISSUE THREAD

**Issue by ghost** [istio/istio#21058] opened 2020-02-12 11:02 UTC
- Problem: **Istio sidecar injection failed**.

- How to reproduce:
=======================
1. follow this link to **successfully** created a k8s cluster with **flannel**
(3 machines with **centos 7, Kubernetes: v1.17.2**):
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

2. run test pods (successfully, and pods can connect each other within different nodes):
kubectl run curl     --image=curlimages/curl --replicas=4 -- sleep 3600
kubectl run nginx    --image=nginx           --replicas=4 --port=80
kubectl expose deployment nginx --port=80   --target-port=80   --name=nginx-svc

3. install istio (**version 1.4.4**, successfully without error):
istioctl manifest apply --set profile=demo

4. enable auto sidecar injection:
kubectl label namespace demo istio-injection=enabled

5. scale test deployment created at previous step:
kubectl  scale --replicas=6 deployment nginx

6. check whether deployment has been scaled.

7. get the result:
deployment has not been scaled, and got the error as below.

=======================
**"kubectl describe replicaset/nginx-5578584966"** shows:
Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: context deadline exceeded

**"kubectl logs --tail=30 -n kube-system pod/kube-apiserver-****"** shows:
dispatcher.go:180] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: context deadline exceeded

Would any one please help me? Thanks a lot.

**Comment by esnible** [comment] 2020-02-13 18:47
Do `kubectl -n istio-system describe service istio-pilot` and tell me if there are any endpoints?

`kubectl -n istio-system get pods` should show a pod either named istio-pilot-* or istiod-* that implements the webhook.

**Comment by zzl1** [comment] 2020-02-15 13:00
Thanks a lot @esnible 
* kubectl -n istio-system describe service istio-pilot
```
Name:              istio-pilot
Namespace:         istio-system
Labels:            app=pilot
                   istio=pilot
                   operator.istio.io/component=Pilot
                   operator.istio.io/managed=Reconcile
                   operator.istio.io/version=1.4.4
                   release=istio
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"pilot","istio":"pilot","operator.istio.io/component":"Pi...
Selector:          istio=pilot
Type:              ClusterIP
IP:                10.104.141.166
Port:              grpc-xds  15010/TCP
TargetPort:        15010/TCP
Endpoints:         10.244.2.36:15010
Port:              https-xds  15011/TCP
TargetPort:        15011/TCP
Endpoints:         10.244.2.36:15011
Port:              http-legacy-discovery  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.244.2.36:8080
Port:              http-monitoring  15014/TCP
TargetPort:        15014/TCP
Endpoints:         10.244.2.36:15014
Session Affinity:  None
Events:            <none>
```

* kubectl -n istio-system get pods
```
NAME                                      READY   STATUS    RESTARTS   AGE
grafana-6b65874977-nck8p                  1/1     Running   0          3d4h
istio-citadel-58c44d6964-h6z65            1/1     Running   0          3d4h
istio-egressgateway-74b6995559-7bbgn      1/1     Running   0          3d4h
istio-galley-5bf54d9674-q7bm6             1/1     Running   0          3d4h
istio-ingressgateway-7f4b56656f-mt2zk     1/1     Running   0          3d4h
istio-pilot-568855fb7-vj4xb               1/1     Running   0          3d4h
istio-policy-fdb9d6845-ws9cc              1/1     Running   0          3d4h
istio-sidecar-injector-56b7656fd8-n7qwl   1/1     Running   0          3d4h
istio-telemetry-676db4d695-rkmbs          1/1     Running   0          3d4h
istio-tracing-c66d67cd9-jl2x5             1/1     Running   0          3d4h
kiali-8559969566-229vq                    1/1     Running   0          3d4h
prometheus-66c5887c86-259nf               1/1     Running   0          3d4h
```

* kubectl -n istio-system get svc istio-sidecar-injector

```
NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
istio-sidecar-injector   ClusterIP   10.100.93.71   <none>        443/TCP   3d4h
```

*  kubectl -n istio-system get ep istio-sidecar-injector

```
NAME                     ENDPOINTS          AGE
istio-sidecar-injector   10.244.3.40:9443   3d4h
```

# when I debug within **kube-apiserver**:
* I am able to connect istio-sidecar-injector via **endpoint**:
/ $ nc -vz 10.244.3.40 9443
10.244.3.40 (10.244.3.40:9443) open

* but wait a long time to connect via **service** (more than 30s, which may cause the error "context deadline exceeded"??): 
/ $ nc -vz 10.100.93.71 443 
10.100.93.71 (10.100.93.71:443) open

* and failed with **certificate problem** if I curl: 
/ $ curl https://10.100.93.71
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
# So, the root cause is the SSL certificate problem? I will continue investigating.

**Comment by zzl1** [comment] 2020-02-29 02:53
I don't know why. I notice that the output of **traceroute** is not correct.

If I **_traceroute <endpoint-ip:port>,_** it's completed quickly.
But if I **_traceroute <service-ip:port>,_** it takes a long time, routing packages even to outside of the k8s cluster (Why???).

So now the temp solution is to **manually add route rule for the service IP range to device** **_cni0_**. And it's working.

**Comment by happycloudpak** [comment] 2020-03-03 08:37
> I don't know why. I notice that the output of **traceroute** is not correct.
> 
> If I **_traceroute endpoint-ip:port,_** it's completed quickly.
> But if I **_traceroute service-ip:port,_** it takes a long time, routing packages even to outside of the k8s cluster (Why???).
> 
> So now the temp solution is to **manually add route rule for the service IP range to device** **_cni0_**. And it's working.

I've exactly same problem as you. k8s cluster with kubeadm on centos7.
Can you explain more detail how to  "manually add route rule for the service IP range to device cni0" ?

**Comment by zzl1** [comment] 2020-03-05 00:46
Hi, @happycloudpak  I add the route rule as below:
ip r add 192.168.0.0/16 dev cni0

Note: 192.168.0.0/16 is the IP range of k8s service. You may need to change it.

**Comment by hiondal** [comment] 2020-03-05 11:29
I'm happycloudpak user. 
Thanks for your kind answer. but, it doesn't work for me. 
I did as followed because I use flannel as CNI(Container Network Interface).
$ ip r add 10.244.0.0/16 dev cni0

**Comment by hiondal** [comment] 2020-03-05 11:31
**** SOLVED ****
I changed CNI tool from flannel to calico.
After then, auto sidecar injection works very well.
I assume flannel has some problem with istio. 

Thanks zzl1

**Comment by zzl1** [comment] 2020-03-06 06:29
Good job! I did encountered issues with flannel. One issue is flannel uses UDP but UDP is blocked in my network. I spent a long time to figure out the root cause.  I will take a look at calico later. Interesting.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hiondal** [comment] 2020-03-07 01:54
I made upload this issue on flannel github community.   
https://github.com/coreos/flannel/issues/1259

**Comment by zzl1** [comment] 2020-03-08 04:10
Thanks.. Seeing if it could be fixed

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by howardjohn** [comment] 2020-08-04 22:30
https://github.com/istio/istio/wiki/Troubleshooting-Istio#diagnostics for more info, may be firewall rules as well

**Comment by howardjohn** [comment] 2020-11-03 03:24
closing as we haven't gotten any followup info on this. We can proceed in https://github.com/istio/istio/issues/27585#issuecomment-700604617

**Closed by howardjohn** 2020-11-03 03:24 UTC
Labels: area/environments

**Comment by shangyu2** [comment] 2021-09-03 05:35
Istio and flannel adaptation problem
Switch the flannel network plug-in mode to host-gw, and the automatic injection of istio is no problem
![1630647141(1)](https://user-images.githubusercontent.com/76041752/131955394-c952279b-1b67-4a9d-ba45-f3efe8acc6d9.png)

对应的文件flannel-host-gw.yml、kube-flannel.yml
