### ISSUE TITLE
Put in place updated versioning scheme.

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#15069] opened 2019-06-21 17:32 UTC
TOC agreed on an update versioning scheme: https://docs.google.com/document/d/1ilwz-HGSeiRDCFwP5rm-5d_UY6OOYL_nflx7bNggek0/edit#heading=h.7zgnj8bwqfld

**Comment by howardjohn** [comment] 2019-09-11 18:47
dupe of https://github.com/istio/istio/issues/14770

**Closed by howardjohn** 2019-09-11 18:47 UTC
Labels: area/test and release
