### ISSUE TITLE
Pilot connectivity issues in 0.5.1

### ISSUE THREAD

**Issue by rlguarino** [istio/istio#3487] opened 2018-02-14 06:54 UTC
We've upgraded o 0.5.1 and we're seeing issues where the Envoy sidecars can't communicate properly with Pilot. As a result the Envoys don't get LDS,RDS,CDS configuration this effects both the sidecar proxies and Ingress proxies. Eventually this results in the unavailability of the entire cluster.

When a proxy is in a broken state is doesn't log any interesting information other than EOF fetching Availability Zones.

**Comment by terinjokes** [comment] 2018-02-14 07:31
The cluster is running Kubernetes 1.9.2. Istio's MTLS is enabled. The Istio configuration is from the 0.5.1 release tarball. Pods are in the Running state, no restarts.

As noted in the OP, nothing in the logs gives us any suggestion as what's going wrong.

**Comment by michaeljquinn** [comment] 2018-02-14 09:34
Also having connectivity issues with pilot 0.5.1, 0.5.0 works fine
using docker-compose

Virt Box VM. Unbunto 16.04LTS running 
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
docker-compose version 1.17.0, build ac53b73
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

seems there is a difference in the istio.yml file
 pilot:                                                          pilot:
    image: docker.io/istio/pilot:0.5.0                        |     image: docker.io/istio/pilot:0.5.1
    networks:                                                       networks:
      istiomesh:                                                      istiomesh:
        aliases:                                                        aliases:
          - istio-pilot                                                   - istio-pilot
    expose:                                                         expose:
      - "8080"                                                |       - "15003"
    ports:                                                          ports:
      - "8081:8080"                                           |       - "8081:15003"
[consul_pilot_1-log-20181402.txt](https://github.com/istio/istio/files/1723357/consul_pilot_1-log-20181402.txt)

**Comment by GregHanson** [comment] 2018-02-14 14:58
@michaeljquinn there was an issue for the consul docker-compose files see: https://github.com/istio/istio/issues/2788

**Comment by terinjokes** [comment] 2018-02-14 16:55
We are seeing a bunch of attribute messages in the istio-ingress logs.

```
[libprotobuf ERROR external/mixerclient_git/src/check_cache.cc:147] Referenced attributes: Absence-keys: destination.ip, source.uid, target.ip, Exact-keys: context.protocol, destination.service, destination.uid, source.ip, 
[libprotobuf ERROR external/mixerclient_git/src/check_cache.cc:145] Response referenced mismatchs with request
```

Is this a signal of something that's wrong?

**Comment by rlguarino** [comment] 2018-02-14 18:11
Noticed this in the ingress logs:

```
2018-02-14T17:50:50.193459Z	info	Epoch 12 exited normally
terminate called after throwing an instance of 'Envoy::EnvoyException'
  what():  unknown cluster 'mixer_server'
2018-02-14T17:51:18.821359Z	warn	Epoch 13 terminated with an error: signal: aborted (core dumped)
2018-02-14T17:51:18.821396Z	warn	Aborted all epochs
2018-02-14T17:51:18.821544Z	info	Epoch 13: set retry delay to 200ms, budget to 9

```

**Comment by terinjokes** [comment] 2018-02-14 18:20
After rotating epochs, I'm noticing (after ~10 minutes) sidecar proxies get LDS and CDS configuration, but never get RDS, so the pod is unable to communicate with anything.

**Comment by rlguarino** [comment] 2018-02-14 19:24
The certificates rotated on the hour, the ingress certificates rotated about 10 minutes before, and the ingress went down for about 7 minutes before coming back online. During that time connections toto the ingress were getting connection reset. Meanwhile pod -> pod communications continued to work.

On the hour the CAs rotated the certificates for the rest of the cluster and around a minute later all of the epochs restarted. Some came back up withing a few minutes but still right now (~25 minutes after cert rotation) majority of the sidecars don't have any listeners and are rejecting connections.

**Comment by rlguarino** [comment] 2018-02-14 19:44
Shortly after my last message a lot (but not all) of the sidecars finally found listeners but they didn't have any routes configured, so Ingress -> Pod would work but any time a Pod tried to talk to another pod it wouldn't work.

About 5-10 minutes ago the routes appeared slowly across the pods but we're still not at seeing every proxy working, just the majority of them. It's now 40 minutes after the CA rotated.

**Comment by rlguarino** [comment] 2018-02-14 23:30
We're also seeing incredible CPU usage from the pilot instances 10 minutes before the hour (corresponding to the Ingress CA rotation & Epoch reload). The CPU load lasts for about 3-5 minutes and ends right before the non-ingress sidecar envoys restart.

**Comment by michaeljquinn** [comment] 2018-02-15 09:02
still getting pilot exiting, fails for both 0.5.0 and 0.5.1
2018-02-14T08:43:12.493173Z     info    registering CRD "routerules.config.istio.io"
Error: failed to create discovery service: failed to register custom resources. Post http://istio-apiserver:8080/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 172.28.0.13:8080: getsockopt: connection refused
Usage:

**Comment by michaeljquinn** [comment] 2018-02-15 09:12
moved pilot out of the istio.yml into separate docker-compose file
started all istio components (except pilot)
waited 10 sec 
then started pilot docker container separately (docker-compose install/console/pilot.yml) up -d
and it started fine
getting "cleared discovery service cache"every 2 sec though

**Comment by ldemailly** [comment] 2018-02-15 09:27
this seems quite severe - cc @costinm , @andraxylia

**Comment by bobbytables** [comment] 2018-02-19 14:02
I believe we're experiencing the same issue. Kubernetes 1.9.2, Istio 0.5.1 (w/o mTLS).

**Comment by bobbytables** [comment] 2018-02-19 14:49
We have 3 pods that are routed to via an ingress rule (which worked on 0.5.0). Right now we see "upstream connect error or disconnect/reset before headers" 33% of each request. Looking at the logs for the 3 pods there's one that receives no traffic at all.

Checked the logs for the `istio-proxy` on the sidecar not receiving traffic. No errors (or really anything for that matter, just the envoy json being spit out).

Checked logs for istio-ingress and it just says 503 with no detail as to why.
Logs for Pilot do have something that might be interesting:

```
Overriding cached data for entry /v1/registration/bifrost-public.applications.svc.cluster.local%7Chttp
```

(Bifrost is the name of our application with 3 pods). Not sure why there's a %7C (A pipe `|` char).

Logs for istio-ingress have this line when we receive a 503:

```
[2018-02-19T14:43:10.128Z] "GET /users/login HTTP/1.1" 503 UF 0 57 2 - "172.16.50.146, 172.16.50.146, 10.2.106.113" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" "58865563-cf0c-9b55-8a2c-ab5cefb07309" "bobbytables-sandbox.i1.namely.com" "10.2.63.131:9000"
```

Checking the destination IP (10.2.63.131) for that log line it does match the single pod (not surprisingly) that's not receiving any traffic.

I then deleted all of the pods (Bifrost) and now it's just 503ing indefinitely.

**Comment by bobbytables** [comment] 2018-02-19 15:02
Update: Once I bounce the Pilot pod for Istio my ingress starts working. My guess is that on the initial boot it does a discovery of everything immediately but if something dies in the middle it doesn't catch that the cluster's state has changed.

**Comment by bobbytables** [comment] 2018-02-19 16:39
Here's some more of my dive:

When I kill the pods, the Pilot discovery service does start printing logs of new endpoints being registered, however.. what I find strange is this log line immediately after it:

```
2018-02-19T15:37:01.283771Z	info	Handle endpoint bifrost-namely in namespace applications
2018-02-19T15:37:01.283835Z	info	Cleared discovery service cache
2018-02-19T15:39:15.483779Z	info	Handle endpoint bifrost-namely in namespace applications
2018-02-19T15:39:15.483837Z	info	Cleared discovery service cache
2018-02-19T15:39:15.492430Z	warn	Overriding cached data for entry /v1/registration/taxservices.applications.svc.cluster.local%7Cgrpc
2018-02-19T15:39:15.983774Z	info	Handle endpoint bifrost-namely in namespace applications
2018-02-19T15:39:15.983914Z	info	Cleared discovery service cache
2018-02-19T15:39:15.986339Z	warn	Overriding cached data for entry /v1/registration/istio-pilot.istio-system.svc.cluster.local%7Chttp-monitoring
2018-02-19T15:39:16.483850Z	info	Handle endpoint bifrost-namely in namespace applications
2018-02-19T15:39:16.483929Z	info	Cleared discovery service cache
2018-02-19T15:39:16.983714Z	info	Handle endpoint bifrost-public in namespace applications
2018-02-19T15:39:16.983790Z	info	Cleared discovery service cache
2018-02-19T15:39:17.583803Z	info	Handle endpoint bifrost-public in namespace applications
2018-02-19T15:39:17.583881Z	info	Cleared discovery service cache
```

This would indicate to me that the moment these are added cache is flushed. Which seems fine since the cache should be re-populated. But clearing after every change seems like a lot.

Further, when I hit the registration endpoint in Pilot, I do see all of my endpoints for Bifrost (all 3):

`curl http://istio-pilot.istio-system.svc.cluster.local:8080/v1/registration`

```json
{
   "service-key": "bifrost-public.applications.svc.cluster.local|http",
   "hosts": [
    {
     "ip_address": "10.2.106.128",
     "port": 9000,
     "tags": {
      "az": "us-east-1/us-east-1c"
     }
    },
    {
     "ip_address": "10.2.16.131",
     "port": 9000,
     "tags": {
      "az": "us-east-1/us-east-1b"
     }
    },
    {
     "ip_address": "10.2.49.159",
     "port": 9000,
     "tags": {
      "az": "us-east-1/us-east-1e"
     }
    }
   ]
  }
```

I also checked the Envoy internal admin and also see the routes there for the ingress controller.

This error seems to be the cause of intermittent 503s but I don't understand why: 

> Response referenced mismatchs with request

This seems to come from Mixer: https://github.com/istio/mixerclient/blob/1f0f0404628c42114c3e5e0fd1128a2c528c1fed/src/check_cache.cc#L145

**Comment by PiotrSikora** [comment] 2018-02-22 22:57
@qiwzhang @jimmycyj any ideas? Looking at changes between 0.5.0 and 0.5.1, it seems to me that https://github.com/istio/mixerclient/commit/0a6974f97bb4dccaaeb77c27d70f7dc13238e6ad might be to breaking things, but it's unclear why TCP filter would be active on connections to Pilot?

**Comment by JimmyCYJ** [comment] 2018-02-23 00:47
I think it is possible that this istio/mixerclient@[0a6974f](0a6974f97bb4dccaaeb77c27d70f7dc13238e6ad) caused the issue. Because the TCP filter report delta feature is implemented in two PRs, this one and istio/proxy@[dbd2cd](dbd2cde303d6f247a5ddd701aae53cf38498a797). The second one is not in 0.5.1

**Comment by qiwzhang** [comment] 2018-02-23 01:15
The log "Response referenced mismatchs with request"  is benign.  Its is a mis-match between mixer-client and mixer referenced attributes used for client cache.  Its impact is its Check result will not be cached.  

MixerClient changes should not cause this problem.

**Comment by rshriram** [comment] 2018-04-13 18:58
closing, as we don't really support 0.5.1 anymore. Please open a new issue if this symptom persists in 0.7+

**Closed by rshriram** 2018-04-13 18:58 UTC
Labels: area/networking, area/perf and scalability, kind/needed for 1.0
