### ISSUE TITLE
ConfigMap "istio-ingress-controller-leader-" is invalid

### ISSUE THREAD

**Issue by sbezverk** [istio/istio#12119] opened 2019-02-27 13:48 UTC
**Describe the bug**
due to empty IngressClass field, the election id gets incorrectly generated which results in this error:
```
2019-02-27T02:05:38.424206Z     error   error initially creating leader election record: ConfigMap "istio-ingress-controller-leader-" is invalid: metadata.name: Invalid value: "istio-ingress-controller-leader-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Expected behavior**
correct election id returned

**Version**
latest release-1.1

**Comment by linsun** [comment] 2019-02-27 14:15
@sbezverk curious how you hit this issue?  Do you hit it with an out of istio build pilot or the default mesh config without pilot pod's provided mesh file ?

**Comment by howardjohn** [comment] 2019-02-28 15:32
Same issue with some more details here: https://github.com/istio/istio/issues/12158

I have also hit this issue before but not ure what config I had. If I run into it again I will update

**Comment by sbezverk** [comment] 2019-02-28 15:59
@linsun it is very basic config, nothing special, not sure why other folks did not see it, or maybe not everybody read pilot's logs :)

**Comment by duderino** [comment] 2019-03-01 19:52
@ymesika why did you close this?  duplicate of something else?

**Comment by duderino** [comment] 2019-03-01 19:57
I see, PR merged, sorry

**Closed by duderino** 2019-03-01 19:57 UTC
