### ISSUE TITLE
ingress service nodeport problem (Prober does not exists url /)

### ISSUE THREAD

**Issue by marcin-kasinski** [istio/istio#13474] opened 2019-04-19 19:32 UTC
Istio objects:
```

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: itzone-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
#curl -H "Host: springbootweb.apps.svc.cluster.local:30999" localhost:30999/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: springbootweb
spec:
  hosts:
#  - "springbootweb.apps.svc.cluster.local:30999"
#  - "springbootweb:30999"
#  - "springbootweb.com:30999"
  - "springbootweb.apps.svc.cluster.local"
  - "springbootweb"
  - "springbootweb.com"
  gateways:
  - itzone-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: springbootweb # interpreted as springbootweb.apps.svc.cluster.local
        #host: ambassador.default.svc.cluster.local # interpreted as springbootweb.apps.svc.cluster.local
        port:
          number: 7070
          #number: 80
---          
```

Istio version 1.1.3
```

root@k8smaster:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
root@k8smaster:~#

```
Hello.
I have istio and ingres gateway with service nodeport type.

nodeport points to port 30999 on my woring node.

I can access my service using ingress pod IP .
I can not access my service using kubernetes work node ip and service nodeport 
```


export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.clusterIP}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export INGRESS_NODEPORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT

echo INGRESS_HOST $INGRESS_HOST
echo INGRESS_PORT $INGRESS_PORT
echo INGRESS_NODEPORT $INGRESS_NODEPORT
echo GATEWAY_URL $GATEWAY_URL
log "checking internal"
curl -I -H Host:springbootweb.apps.svc.cluster.local http://$INGRESS_HOST:$INGRESS_PORT/
log "checking external"
curl -I -H Host:springbootweb.apps.svc.cluster.local http://192.168.1.11:30999/

```
curl -I -H Host:springbootweb.apps.svc.cluster.local http://$INGRESS_HOST:$INGRESS_PORT/ returns service content

In ingress gateway I can see logs:
`
[2019-04-19T19:27:59.146Z] "HEAD / HTTP/1.1" 500 - "-" 0 0 635 634 "10.38.0.0" "curl/7.58.0" "3507bde3-0452-9c11-b217-b7704bc235d7" "springbootweb.apps.svc.cluster.local" "10.40.0.7:7070" outbound|7070||springbootweb.apps.svc.cluster.local - 10.44.0.3:80 10.38.0.0:56122 -`

curl -I -H Host:springbootweb.apps.svc.cluster.local http://192.168.1.11:30999/ (k8s node) returns HTTP/1.1 400 Bad Request

In ingress gateway I can see error logs:
`
2019-04-19T19:28:20.922966Z     error   Prober does not exists url /
`

**Comment by marcin-kasinski** [comment] 2019-04-23 09:07
additional info:

With  istio 1.1.2 it works fine.
Problem " Prober does not exists " exists with istio 1.1.3.

**Comment by frankbu** [comment] 2019-04-29 14:10
Maybe this is caused by this recent change? https://github.com/istio/istio/pull/12872

cc @hzxuzhonghu @incfly

**Comment by marcin-kasinski** [comment] 2019-04-29 18:20
Problem " Prober does not exists " exists with istio 1.1.4 too.

**Comment by jnativio** [comment] 2019-04-29 20:48
I have hit this problem too with 1.1.3, and it works with 1.1.2. I don't think this is caused by PR #12872 as it was merged on master but not on 1.1 branch.

**Comment by incfly** [comment] 2019-04-30 19:26
https://github.com/istio/istio/commit/f724bc3e1a9e8cc621809a8b56fa9cbde2f309aa#diff-c1bdb159b354a382bbfe6a0bb13863b8R79

This line seems wrong to me... But it was introduced since 1.1.0, does not match the description that it was a regresssion between 1.1.3 and 1.1.2...

**Comment by incfly** [comment] 2019-04-30 19:39
I'll try it myself some time later today. Let me try to summarize the reproducing setup,

- Deploy an app, maybe httpbin should work?.
- Declare nodeport service.
- Access using `node_ip:service_port` will not work.
- Binding with gateway/virtualservice, will work.
- And this bug was introduced between 1.1.2 and 1.1.3

Seems gateway is not related to this bug because it's working as before? We can just focus on why node_ip:port is not accessible?

Let me know if I miss anything.

**Comment by incfly** [comment] 2019-04-30 19:43
Also by the way, what's the Helm installation profile you're using? Do you use `sidecarInjectorWebhook.rewriteAppHTTPProbe` = true?

**Comment by jnativio** [comment] 2019-04-30 20:28
I use the default value for this which is `false`

**Comment by jnativio** [comment] 2019-04-30 20:31
The application I use does not have liveness probes. Here is the gateway and virtual services definition:
##################################################################
# Gateway for Acmeair
##################################################################
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: acmeair-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
###################################################################
# Virtual Services for Acmeair
###################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: acmeair
spec:
  hosts:
  - "*"
  gateways:
  - acmeair-gateway
  http:
  - match:
    - uri:
        prefix: /flight
    route:
    - destination:
        port:
          number: 9080
        host: flight
  - match:
    - uri:
        prefix: /booking
    route:
    - destination:
        port:
          number: 9080
        host: booking
  - match:
    - uri:
        prefix: /customer
    route:
    - destination:
        port:
          number: 9080
        host: customer
  - match:
    - uri:
        prefix: /auth
    route:
    - destination:
        port:
          number: 9080
        host: auth
  - match:
    - uri:
        prefix: /acmeair
    route:
    - destination:
        port:
          number: 9080
        host: main
---

**Comment by frankbu** [comment] 2019-04-30 21:39
@jnativio How are you accessing the service when you get the prober does not exist error? Are you also only seeing the problem when using a nodeport to access the service?

**Comment by jnativio** [comment] 2019-04-30 23:35
@frankbu This is my ingressgateway service:
root@dal10-vsi1:/mount/istio_regpatrol# kubectl -n istio-system get svc istio-ingressgateway
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   172.21.226.206   169.47.196.186   15020:32258/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30865/TCP,15030:31974/TCP,15031:32222/TCP,15032:30333/TCP,15443:30704/TCP   2d

I use port 169.47.196.186:31380 to access the app and that is when I am getting the prober error.

**Comment by incfly** [comment] 2019-05-02 00:10
I failed to reproduce. Here's what I did.

- Install istio-1.1.3, with `istio-demo.yaml`.
- Apply minimal necessary config for gateway/virtualservice/httpbin. I use httpbin, [gist](**https://gist.githubusercontent.com/incfly/5316c0cf5e907d41fe06f9c04cbd769e/raw/bb43ec8c1b48381dcb944b25e3b73d21f0edca60/gistfile1.txt**) can be found here.
- run the bash above
```bash
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.clusterIP}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export INGRESS_NODEPORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT

echo INGRESS_HOST $INGRESS_HOST
echo INGRESS_PORT $INGRESS_PORT
echo INGRESS_NODEPORT $INGRESS_NODEPORT
echo GATEWAY_URL $GATEWAY_URL
```
I got
```
INGRESS_HOST 10.43.254.101
INGRESS_PORT 80
INGRESS_NODEPORT 31380
GATEWAY_URL 10.43.254.101:80
```
- `gcloud compute instances list&& gcloud compute ssh gke-istio-dev-default-pool-88c47b60-6x9s`. login into one of the gke node.
```
NAME                                          ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP    EXTERNAL_IP     STATUS
gke-istio-dev-default-pool-88c47b60-6x9s      us-central1-a  n1-standard-2               10.128.15.195  23.251.144.112  RUNNING
```
- The gke node internal ip is 10.128.15.195 obtained from gcloud output above. curl via the nodeport, `curl -H Host:httpbin.default.svc.cluster.local 10.128.15.195:31380/ip`

```
curl -H Host:httpbin.default.svc.cluster.local 10.128.15.195:31380/ip
{
  "origin": "10.40.2.1"
}
```

**Comment by frankbu** [comment] 2019-05-02 16:15
@incfly, I wonder if the problem only occurs if the service does not implement the uri path `/`, since that's what the prober error is complaining about. Can you try your same setup, only using the helloworld sample, instead of httpbin? https://github.com/istio/istio/tree/master/samples/helloworld

@jnativio if you add `/` to your service, does the prober error go away?

**Comment by jnativio** [comment] 2019-05-02 20:30
@frankbu  I figured out what was my problem: my script was getting the ingress-gw http nodeport based on its position only. Until 1.1.2, it was always the first port in the json. At some point after that, the status port started appearing in first place, so I was getting the wrong nodeport. Fixed my script to look for "http2" port.  Thanks.

**Comment by frankbu** [comment] 2019-05-02 20:49
Ah, that makes sense.

@marcin-kasinski Could this be the same problem you are having? How did you get the nodeport value `30999` that you are using?

**Comment by marcin-kasinski** [comment] 2019-05-02 21:30
Hello.

After installing istio I set nodeport with code

`kubectl patch svc istio-ingressgateway -n istio-system --type=json -p='[{"op": "replace", "path": "/spec/ports/0/nodePort", "value": 30999}]'
`

I get host nodeport with code:

`export INGRESS_NODEPORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
`

**Comment by frankbu** [comment] 2019-05-03 13:21
@marcin-kasinski So that is your problem. You are setting 30999 as the nodeport for the first port (`/spec/ports/0`).
```
kubectl patch svc istio-ingressgateway -n istio-system --type=json -p='[{"op": "replace", "path": "/spec/ports/0/nodePort", "value": 30999}]'
```
 Since 1.1.3 port 0 has become the status port, as @jnativio discovered. You need to set the http2 port, not port 0.

**Closed by frankbu** 2019-05-03 13:21 UTC
Labels: area/networking

**Comment by marcin-kasinski** [comment] 2019-05-03 16:01
Thank you to all of you.
Now it is clear
