### ISSUE TITLE
Unable to launch NiFi with envoy sidecar injection

### ISSUE THREAD

**Issue by duriti** [istio/istio#17918] opened 2019-10-16 11:14 UTC
**Bug description**

Facing issue setting up NiFi using Istio. 

Both NiFi and Envoy proxy containers comes up successfully, but unable to invoke the web UI and receives the error 
*curl: (56) Recv failure: Connection reset by peer*

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

access NiFi on the http port (8080)

**Steps to reproduce the bug**

**Inject Istio**

kubectl label ns nifi istio-injection=enabled 

**Pod Spec :**  
```
apiVersion: extensions/v1beta1
kind: Service             #+
apiVersion: v1            #+
metadata:                 #+
  name: nifi-service     #+
  namespace: nifi
spec:                     #+
  selector:               #+
    app: nifi            #+
  ports:                  #+
  - protocol: TCP         #+
    targetPort: 8080     #+
    port: 8080              #+
    name: ui            #+
  - protocol: TCP         #+
    targetPort: 9088     #+
    port: 9088              #+
    name: node-protocol-port            #+
  - protocol: TCP         #+
    targetPort: 8888     #+
    port: 8888              #+
    name: s2s            #+
  type: LoadBalancer      #+
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nifi
  namespace: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi-container
        image: apache/nifi:1.9.2
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 22
          name: ssh
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "1"
        env:
        - name: VERSION
          value: "1.9.2"
```

**Access the Nifi:** 
```
nifi@nifi-79bd794b-jwxz2:/opt/nifi/nifi-current$ curl -kv http://nifi-79bd794b-jwxz2:8080/nifi --no-tcp-nodelay
*   Trying 172.21.0.36...
* Connected to nifi-79bd794b-jwxz2 (172.21.0.36) port 8080 (#0)
> GET /nifi HTTP/1.1
> Host: nifi-79bd794b-jwxz2:8080
> User-Agent: curl/7.52.1
> Accept: */*
>
* Recv failure: Connection reset by peer
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

istio version: 1.3.2

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

GCP VM Instance - CentOS7

**Comment by esnible** [comment] 2019-10-16 14:21
I have not used NiFi.

Istio may have difficulty with apps talking directly to the pod IP.  The problem you are having may be https://github.com/istio/istio/issues/15367

Can you try communicating to http://localhost:8080/nifi (from the Pod itself) or http://<a service selecting the pod>:8080/nifi (from the cluster)?

**Comment by duriti** [comment] 2019-10-16 18:31
@esnible Thanks for responding to my query. 

Here is the output from the pod when I try with localhost. 

```
nifi@nifi-79bd794b-ztg2t:/opt/nifi/nifi-current$ curl -kv http://localhost:8080/nifi
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8080 failed: Connection refused
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Network is unreachable
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Network is unreachable
* Failed to connect to localhost port 8080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

**Comment by duriti** [comment] 2019-10-29 05:50
@esnible is there some progress on providing support for NiFi?

**Comment by esnible** [comment] 2019-10-29 13:49
I added this to Istio's _List of Incompatible Applications_.

Using Istio, Envoy, the sidecar, communicates over `localhost` to the app.  I had some trouble with apps that only listen on their network socket address, not on `0.0.0.0` or `127.0.0.1`, and had to tweak that configuration to get them working with Envoy.

I created https://github.com/istio/istio.io/issues/5278 to try to get our documentation team to produce more documentation about this kind of problem (if this is a problem with Nifi not listening the way Envoy is talking).  I can't assign anyone to learn NiFi and get it working.

If the problem is how Nifi is listening and you come up with a solution we can add your solution to our FAQ.  I don't know Nifi and can't troubleshoot this myself.

Communication flows like this:

```
App1     App2
 |               |
Envoy1-Envoy2
```

I troubleshoot problems with App1 talking to App2 by testing each of the three connection.  First, can I `kubectl exec` into App1's `istio-proxy` container and connect to App1.  That is why I had you do the `curl`.  So far it seems like the problem is with the communication between the co-located App1 Envoy and App1 itself.  Do you know Nifi?  Can you do further troubleshooting?

**Comment by eric4321** [comment] 2019-11-05 11:06
Hi, 

The problem seems to be that ```istio-proxy``` cannot reach the nifi container in the same pod via localhost.

This is can be fixed by modifying the ```nifi.web.http.host``` property in ```nifi.properties``` to ```nifi.web.http.host=localhost```.

NOTE: This only works in non-secure mode (not https).

**Comment by byess123** [comment] 2019-11-20 16:06
One solution that worked for me was attaching the `lo` network interface in the docker container to NiFi in `nifi.properties` using `nifi.web.http.network.interface.lo=lo`. With this property update I was able to use a clustered NiFi in K8s with Istio while also maintaining my FQDN for my node address.

**Comment by danielpcox** [comment] 2020-01-15 01:20
I had a similar problem, and solved it by setting the host to 127.0.0.1 through this environment variable. The `../scripts/start.sh` entrypoint script pulls the value out of that environment variable and uses it to set `nifi.web.http.host` in nifi.properties before starting NiFi. Since this value defaults to `$HOSTNAME` in `start.sh`, it _doesn't_ get bound to 127.0.0.1 by default, which was the cause of the problem.
![image](https://user-images.githubusercontent.com/56411/72396557-e548e780-36f1-11ea-87ad-1bf9305221e3.png)

**Comment by jpapejr** [comment] 2020-05-11 16:47
I'm writing a new FAQ for Apache Nifi based on some work a team at IBM did recently.. tl;dr is that they resolved this (on IBM Cloud) with 

```
nifi.web.https.network.interface.default=eth0
nifi.web.https.network.interface.lo=lo
```

Where `eth0` was the interface pointing to the node ip and `lo` - was, well, localhost like Istio wants. 

I'll post here again when I get the PR submitted. Happy to collaborate with others to make sure all angles are covered as I'm not a Nifi expert, nor did I participate directly in the configuration of Nifi for this effort.

**Comment by jpapejr** [comment] 2020-05-11 21:40
https://github.com/istio/istio.io/pull/7266 Is the work in progress PR.

**Comment by richa-misra** [comment] 2020-07-24 16:26
Hi All,

I am facing the same issue when trying to access Nifi on HTTP with Istio sidecar proxies.
I have tried setting `nifi.web.proxy.host=0.0.0.0` `nifi.web.proxy.host=127.0.0.1` `nifi.web.proxy.host=localhost`
on their own and also alongwith setting `nifi.web.http.network.interface.default=eth0` but none of these seem to work.
Also, there doesn't seem to be parameter `nifi.web.http.network.interface.lo=` present in `nifi.properties` for Nifi version 1.11.4

**Istio version**: 1.6.5
**Nifi version**: 1.11.4
**Environment**: AWS EKS

Any help/suggestions on this please?  
Many thanks

**Comment by jpapejr** [comment] 2020-07-24 18:52
w/r/t `nifi.web.http.network.interface.default=eth0` - Is eth0 the correct interface name for your EC2 instances? This was the case on IBM Cloud VSIs but I can almost guarantee that it will differ between cloud providers..

**Comment by richa-misra** [comment] 2020-07-27 12:53
@jpapejr  Thanks for your reply `nifi.web.http.network.interface.default=eth0` was fine key thing was to add a new property for loopback device `nifi.web.http.network.interface.lo=lo` nifi.properties file, that fixed the issue !

**Comment by jpapejr** [comment] 2020-07-27 14:46
Great, glad to hear it! With @richa-misra's success, I think the documented method for using NiFi inside an Istio mesh is validated. Closing this issue, if anyone objects, please feel free to re-open.

**Closed by jpapejr** 2020-07-27 14:46 UTC
Labels: area/networking, community/help wanted, lifecycle/needs-triage

**Comment by chrisharms** [comment] 2021-11-11 00:57
I realize this hasn't been touched in a while, but I came across this post when trying to integrate NiFi with Service Mesh and adding the 2 properties for the network interfaces fixed my issues. I was just wondering if there's similar functionality in Apache NiFi Registry. I also want to include NiFi Registry in my deployment but I don't see those properties in the nifi-registry.properties file, and I'm not sure if there's another way to add those network interfaces. If anyone knows how to resolve this in NiFi Registry that'd be great.
