### ISSUE TITLE
TestTraffic/serverfirst/auto-tcp-server:ISTIO_MUTUAL/STRICT flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#26639] opened 2020-08-19 10:30 UTC
https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/3428

@howardjohn

**Comment by howardjohn** [comment] 2020-08-19 15:25
Looking into it, dupe of https://github.com/istio/istio/issues/26620. Thanks!

**Closed by howardjohn** 2020-08-19 15:25 UTC
Labels: area/networking
