### ISSUE TITLE
Application down time issue during istio upgrade time window

### ISSUE THREAD

**Issue by zhqworld** [istio/istio#10683] opened 2018-12-27 23:09 UTC
During istio upgrade time window, sidecar of the application reporting 503 due to mixer not available. Here are details:
Istio version 1.0.2, upgrading to 1.0.4
k8s version: 1.12.4

### Test Setup:
istio version: 1.0.2
itstio-policy replicas set to 2, both policy pods running
setup a client app without sidecar, replicas: 1
setup a server app with istio sidecar, replicas: 2

### Test:
client app making 8 calls to server app service, both 2 of the server pods receiving requests, no failure.

### Upgrade:
Then start upgrading istio to version 1.0.4 by helm:
`/bin/bash -c ./helm upgrade --tiller-namespace=kube-system --kube-context=my-cluster --version=1.0.4 --values=... --namespace=istio-system --tls --install istio istio`

Then wait for the upgrade to finish, and collect logs from istio-proxy of two server app pods:
at same time, both two sidecar started reporting response 503 with below error log after upgrade started, and the failure lasted around 10 seconds time window, after that, all sidecar back to reporting 200 again.

### Error logs from both sidecars:
`[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers`

Seems even though we have 2 mixer pods, but sidecar seems was still not able to talk to mixer hence failed the requests during upgrade process.

### mixer unavailable confirming:
Below can confirm the failure was because of mixer unavailable:
Set policyCheckFailOpen to true for istio 1.0.2, then re-run the test and upgrade again, no 503 reported, even though the error log still appeared in sidecar logs.

So please confirm this is the expected behavior of the mixer or not? If yes, do you have plan to make mixer component rolling upgrade during istio upgrade process?

**Comment by louiscryan** [comment] 2019-01-04 01:16
@mandarjog can you triage ?

**Comment by duderino** [comment] 2019-01-16 22:52
Duplicate of https://github.com/istio/istio/issues/9992

**Closed by duderino** 2019-01-16 22:52 UTC
Labels: kind/customer issue
