### ISSUE TITLE
backward compatibility for flags 

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3763] opened 2018-02-24 20:36 UTC
As soon as we have customers in production, we can't have flags from any component disappear and must ensure all flags from the past continue to work and/or spew abundant warnings for a couple releases before (if ever) disappearing

A good example of breaking change across the board is `-v 2` - maybe we can do this in 0.7 but certainly not after 1.0

We probably need a small library to register old flags and have them translate to new flags/schema in 1 place without having the main code peppered with IFs

cc @costinm @geeknoid

**Comment by geeknoid** [comment] 2018-02-24 21:37
Is this actionable at this point? I'm not clear what the issue is trying to capture.

**Comment by ldemailly** [comment] 2018-02-24 21:51
the AIs are

1) decide when we start making sure we don't break backward compatibility
2) start working on a small simple library to solve the problem past that point

**Comment by ldemailly** [comment] 2018-02-26 22:42
@smawson can you make a call on 1. above: when do we start to have to preserve "no crash" backward compatibility for flags - specifically if 0.7 can ship with flag incompatibilities from 0.5/0.6 or 0.8 or 1.0 is the first release after which we won't break flags for mixer, pilot, etc.. startup (and/or if we do we'd clearly document the change and have at least 1 release where both old and new are supported)

**Comment by smawson** [comment] 2018-02-27 00:16
I can't unilateraly decide that, added to ToC agenda for Friday to discuss when we're comfortable requiring no backwards compatibility breakages.

**Comment by yusuoh** [comment] 2018-02-27 18:52
In general, command line flags should be deprecated instead of removed directly from the code. We have some nice ways to handle that in C++ and borg. We'd better find some similar mechanism to do that in Go.

Regarding backward compatibility, I think it is also important to ensure API compatibility and have some tests to gate API changes, e.g. by comparing protobuf schemas between versions.

**Comment by ldemailly** [comment] 2018-02-27 18:54
I believe cobra has support for that already btw, just a matter of setting it up

**Comment by ldemailly** [comment] 2018-02-27 21:55
#3759 would break backward compatibility for instance (though one can argue functionally it's been broken by #1840 onward

**Comment by costinm** [comment] 2018-02-27 23:15
Since Istio is in use by real customers, and we have quite a few external ways to install it ( k8s addon, single-click installer, etc ) - we must pay attention to backward compat even if we haven't 
officially committed or decided it. We can still make changes - and in extreme cases take the 
hit and break customer's installs on upgrade - but I think we should prevent breakages when we 
can.

**Comment by xiaolanz** [comment] 2018-04-06 21:09
From the TOC meeting today, seems like 1.0 is certified on k8s 1.9 and 1.10 without any promise at the moment to past/future releases. The configuration API compatibility discussion is in istio/api#1880

**Closed by xiaolanz** 2018-04-06 21:09 UTC
Labels: area/config, area/environments, area/test and release, kind/needed for 1.0

**Comment by ldemailly** [comment] 2018-04-06 21:25
I was on the call, the discussion was about which k8s version we will test for/support

It's unrelated to the decision on whether flags in our components are backward compatible or not
(which is a sub issue of the general backward compatibility and upgradability expectations)

My understanding is that 0.7 will be upgradeable to 0.8 and 1.0 will also be compatible with 0.8

**Comment by ozevren** [comment] 2018-06-13 21:05
This doesn't look like config related. Removing label. Please re-add if you disagree.
