### ISSUE TITLE
Enable istio for ingress controller

### ISSUE THREAD

**Issue by maxkondr** [istio/istio#4840] opened 2018-04-10 11:44 UTC
Hi,

I have installed istio with webhook enabled, labeled namespace `ingress-nginx` where nginx ingress controller is running with:

```kubectl get namespace -L istio-injection
NAME            STATUS    AGE       ISTIO-INJECTION
default         Active    18d       enabled
ingress-nginx   Active    18d       enabled
istio-system    Active    2h        
kube-public     Active    18d       
kube-system     Active    18d       
logging         Active    18d       
monitoring      Active    18d       
tracing         Active    14d 
```

deleted pods in order to recreate it with sidecar container
```
kubectl get pods -n ingress-nginx
NAME                                      READY     STATUS    RESTARTS   AGE
default-http-backend-566469d447-b7wd5     1/1       Running   6          5m
nginx-ingress-controller-94cd4df9-c4ndg   1/1       Running   0          1h
```

> kubectl delete pod -n ingress-nginx default-http-backend-566469d447-b7wd5
> kubectl delete pod -n ingress-nginx nginx-ingress-controller-94cd4df9-c4ndg

but ingress controller is still running alone:

```
kubectl get pods -n ingress-nginx
NAME                                      READY     STATUS    RESTARTS   AGE
default-http-backend-566469d447-5hpvd     2/2       Running   0          3m
nginx-ingress-controller-94cd4df9-f4cfx   1/1       Running   0          2m

```

Could you please describe the reason of such behavior and how to overcome it?

In general I want to achieve the following:
----HTTPS(using ingress certs)--->  |NGINX-->Envoy|  --mTLS(istio auth)-->  |Envoy-->SERVICE_A|

Is it possible?

**Comment by rshriram** [comment] 2018-04-10 13:33
cc @nmittler since he was working on this recently

**Comment by maxkondr** [comment] 2018-04-10 14:27
BTW, please take into accounting that NGINX ingress controller connects to service_A's PODs directly.

**Comment by maxkondr** [comment] 2018-04-16 09:55
any news here please?

**Comment by Globegitter** [comment] 2018-04-16 10:30
@maxkondr it seems @stono got this setup to work and you can find more here: https://github.com/kubernetes/ingress-nginx/issues/2126

**Comment by Stono** [comment] 2018-04-16 10:39
Indeed I did, it's all in that issue but at a high level you need to wrap `istio-ingress` with a pre-boot script which removes the inbound iptables rule for traffic interception:

```
iptables -t nat -D PREROUTING -j ISTIO_REDIRECT -m comment --comment "istio/install-istio-prerouting"
```
Naturally wrapping things with iptables scripts isn't great, and the istio team have recently done https://github.com/istio/istio/pull/4569 and https://github.com/istio/istio/pull/4778 which will enable you to do this as configuration instead.  I believe that will land in 0.9

You also need to ensure that `istio-ingress` uses the service names for upstream communication, rather than its default behaviour of resolving the pool:

```
 nginx.ingress.kubernetes.io/service-upstream: "true"
 nginx.ingress.kubernetes.io/upstream-vhost: at-consumer-platform-service.default.svc.cluster.local
```

**Comment by ayj** [comment] 2018-04-16 19:14
> ... an issue with the webhook injector silently failing, resulting in an uninjected pod

The MutatingAdmissionWebhook originally failed open and could allow pods to be created without the sidecar. This was changed to fail-close on 2/23 (see [here](https://github.com/istio/istio/pull/3724)). The current configuration is [here](https://github.com/istio/istio/blob/e373621f2a8e12df7386a96b9e1f22d59345075b/install/kubernetes/helm/istio/charts/sidecar-injector/templates/mutatingwebhook.yaml#L24).

**Comment by nmittler** [comment] 2018-04-19 14:52
@maxkondr you said that you deleted pods so they would be recreated with a sidecar.  Does that mean you modified the namespace to add injection after the nginx controller was already deployed? If so, I suspect that's the issue. In that case, you would need to re-deploy nginx.

**Comment by maxkondr** [comment] 2018-04-22 18:52
@nmittler 
Yes, I did it exactly in the way you have described. But there is one fact to mention:
- my ingress-nginx namespace had 2 pods: nginx itself and default-backend
- when I delete both these pods with `kubectl delete pod <...> -n ingress-nginx` command, the default-backend is being recreated with sidecar container but ingress not. 

Anyway I will try to modify namespace before deploying nginx and inform you abut results.

**Comment by maxkondr** [comment] 2018-06-12 06:36
Finally, I have came back to this task :)

@nmittler  I did the same way as you asked me - and now I see that there is a sidecar container running in nginx pod. But requests are not processed anyway. 
Now I see errors in nginx pod:

> tail -f nginx-ingress-controller-7f4c6b6fbc-ntw9m_ingress-nginx_nginx-ingress-controller-6aa33bcb162ff4f5a4bd3fa50031187213b39c454ff601831190d6f84e2c86ad.log
```
{"log":"NGINX Ingress controller\n","stream":"stdout","time":"2018-06-11T14:57:25.939419439Z"}
{"log":"  Release:    0.15.0\n","stream":"stdout","time":"2018-06-11T14:57:25.939423749Z"}
{"log":"  Build:      git-df61bd7\n","stream":"stdout","time":"2018-06-11T14:57:25.939426129Z"}
{"log":"  Repository: https://github.com/kubernetes/ingress-nginx\n","stream":"stdout","time":"2018-06-11T14:57:25.939428554Z"}
{"log":"-------------------------------------------------------------------------------\n","stream":"stdout","time":"2018-06-11T14:57:25.939430999Z"}
{"log":"\n","stream":"stdout","time":"2018-06-11T14:57:25.939433277Z"}
{"log":"W0611 14:57:25.952837       7 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.\n","stream":"stderr","time":"2018-06-11T14:57:25.953392803Z"}
{"log":"I0611 14:57:25.953603       7 main.go:158] Creating API client for https://10.3.0.1:443\n","stream":"stderr","time":"2018-06-11T14:57:25.953876761Z"}
{"log":"F0611 14:59:41.332499       7 main.go:224] Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration). Reason: an error on the server (\"\") has prevented the request from succeeding\n","stream":"stderr","time":"2018-06-11T14:59:41.332891918Z"}
{"log":"Refer to the troubleshooting guide for more information: https://github.com/kubernetes/ingress-nginx/blob/master/docs/troubleshooting.md\n","stream":"stderr","time":"2018-06-11T14:59:41.332996291Z"} 
```

I have tried to mark kubernetes.default service with 
> kubectl get svc kubernetes -o yaml
```
kind: Service
metadata:
  annotations:
    auth.istio.io/443: NONE  <------------- skip mTLS
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
spec:
  clusterIP: 10.3.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
```

but with no luck.

Any suggestions how to overcome this issue ?

**Comment by Stono** [comment] 2018-06-12 06:59
You need a destination rule for the Kubernetes master

I'll send it you when I get back to the desk

**Comment by Stono** [comment] 2018-06-12 07:12
OK so you need:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-to-k8s
  namespace: istio-system
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

That'll fix your "error connecting to k8s".

**Comment by nmittler** [comment] 2018-06-13 20:36
Closing this as a duplicate of #6028

Feel free to re-open if you feel appropriate

**Closed by nmittler** 2018-06-13 20:36 UTC
Labels: area/networking
