### ISSUE TITLE
 Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate

### ISSUE THREAD

**Issue by shinynz** [istio/istio#40094] opened 2022-07-25 12:00 UTC
### Bug Description

<html>
<body>

2022-07-25T11:53:23.523943Z info klog k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "c1c7389621d312782ec499a82")
--
2022-07-25 7:53:23 pm | 2022-07-25T11:53:23.523994Z error klog k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "c1c7389621d312782ec499a82")
2022-07-25 7:54:11 pm | 2022-07-25T11:54:11.396824Z info klog k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "c1c7389621d312782ec499a82")
2022-07-25 7:54:11 pm | 2022-07-25T11:54:11.396872Z error klog k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "c1c738962d312782ec499a82")
2022-07-25 7:55:09 pm | 2022-07-25T11:55:09.643759Z info klog k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "c1c7389621d312782ec499a82")
2022-07-25 7:55:09 pm | 2022-07-25T11:55:09.643825Z error klog k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "c1c7389621d312782ec499a82")
2022-07-25 7:55:56 pm | 2022-07-25T11:55:56.164976Z info klog k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "c1c7389621d312782ec499a82")
2022-07-25 7:55:56 pm | 2022-07-25T11:55:56.165033Z error klog k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.25.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "c1c7389621d312782ec499a82")

</body>
</html>

### Version

```prose
istioctl version 
client version: 1.14.1
control plance version: 1.14.1
data plane version: 1.14.1

kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-aliyun.1", GitCommit:"937757761d3c1db7080f179102b437c26c521ecd", GitTreeState:"clean", BuildDate:"2022-05-27T07:42:41Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-aliyun.1", GitCommit:"937757761d3c1db7080f179102b437c26c521ecd", GitTreeState:"clean", BuildDate:"2022-05-26T12:38:52Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by howardjohn** [comment] 2022-07-25 14:22
I think you need to either set env var `GODEBUG=x509sha1=1` or change your cert on the k8s cluster.

Note I would expect ALL go programs to fail to connect to the API server, and GODEBUG=x509sha1=1 will be removed eventually I imagine, so I would recommend the latter.

See https://github.com/golang/go/issues/41682

Closing this as Istio will not make any changes here, this is working as intended per ^

**Closed by howardjohn** 2022-07-25 14:22 UTC
