### ISSUE TITLE
Consolidate common stuff across repos

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#412] opened 2017-06-15 13:34 UTC
We have a growing amount of boilerplate across repos (mixer/bin/* broker/bin/* galley/bin/* for example). It'd be great if we can consolidate. Perhaps we need to put all this stuff into a common repo and just include that common repo as a submodule in all the other repos?

**Comment by sebastienvas** [comment] 2017-06-15 17:55
This is a duplicate of https://github.com/istio/test-infra/issues/91, which we ll looking at during 0.2 timeframe.

**Closed** 2017-06-15 18:26 UTC
