### ISSUE TITLE
Enabling configuration per namespace/deployment

### ISSUE THREAD

**Issue by iandyh** [istio/istio#14285] opened 2019-05-22 02:08 UTC
**Describe the feature request**
Finer granularity control over various configurations. Some examples on top of my head:

1. Sidecar proxy resource usage. Since each app might have different requirements for the performance of the injected proxy.
2. Sampling rate. When a cluster serves both high/low traffic applications, a global sampling rate might not be helpful.

**Additional context**
I understand that there might be many configurations required to be applied at finer granularity level and it will take time for them to be implemented. But hopefully this issue can raise the awareness and start to discuss the foundation work required to achieve the goal. I've seen people are submitting similar issues: https://github.com/istio/istio/issues/13534

Thank you!

**Comment by iandyh** [comment] 2019-06-26 06:45
@howardjohn Hello. I would like to start working on this for configuring sampling rate. The requirement should be:

One service is able to control the trace sampling rate for one or several services. 

Looking at the existing building blocks, `sidecar` resource may be the place to put the configurations. Based on my current understanding, The workflow will be:

1. Configure the `sidecar` with `labelSelector` and sample rate to the remote service
2. Pilot fetch the configuration from above and push to the corresponding workload sidecar proxy

If I miss important point, please let me know.

Thanks.

**Comment by howardjohn** [comment] 2019-06-26 14:21
I think @douglas-reid had worked extensively on that exact feature - I am not sure what the outcome was, there were some debates on the API. I would suggest you sync up with him.

**Comment by howardjohn** [comment] 2019-06-26 14:21
Or in the TOC meeting notes there may be some notes a week or 2 back

**Comment by douglas-reid** [comment] 2019-06-26 19:52
This is a duplicate of https://github.com/istio/istio/issues/12818. It has also been discussed in https://github.com/istio/istio/issues/11582 and https://github.com/istio/istio/issues/14433. There is even a proposal doc for the feature: https://tinyurl.com/y3lnlf7n. It has been discussed in an official Istio API review and at the TOC. More work in this direction will be coming shortly.

Closing this issue in favor of the other issues covering this FR.  Please follow along on the existing issues and provide comments and inputs to the doc, as it evolves.

**Closed by douglas-reid** 2019-06-26 19:52 UTC
Labels: area/config, kind/enhancement
