### ISSUE TITLE
Terraform plan fails during initial run of helm_release for Istiod

### ISSUE THREAD

**Issue by ElkRom** [istio/istio#41792] opened 2022-11-04 14:33 UTC
### Bug Description

I have following Terrafrom code for deploying Istio via Terraform helm_release resource:
 ```
resource "helm_release" "istio-base" {
  chart            = "base"
  namespace        = "istio-system"
  create_namespace = "true"
  name             = "istio-base"
  version          = "1.15.3"
  repository       = "https://istio-release.storage.googleapis.com/charts"
  #force_update     = var.force_update
  #recreate_pods    = var.recreate_pods
}

resource "helm_release" "istiod" {
  depends_on        = [helm_release.istio-base]
  name              = "istiod"
  namespace         = "istio-system"
  dependency_update = true
  repository        = "https://istio-release.storage.googleapis.com/charts"
  chart             = "istiod"
  version           = "1.15.3"
  atomic            = true
  lint              = true
}
 ```

During first deployment(initial setup) of Istio on new k8s cluster, Terraform **plan** fails with error:
 ```
│ Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "stats-filter-1.13" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "stats-filter-1.14" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "stats-filter-1.15" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "tcp-stats-filter-1.13" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "tcp-stats-filter-1.14" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "tcp-stats-filter-1.15" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first]
 ```

From error I see that during Terraform **plan** , it tries to validate CRDs, which are not supposed to be installed during Terraform **plan** via  **resource "helm_release" "istio-base"** .

I thought that once you set **skip_crds   = true** for helm_release, issue will be resolved, but it didn't help.

### Version

```prose
Terraform version: 1.3.3
Helm provider version: v2.7.1.
Istio helm chart version: 1.15.3
```

**Comment by zioproto** [comment] 2022-11-04 17:39
I can't reproduce it.

% cat istio.tf
```
resource "helm_release" "istio-base" {
  chart            = "base"
  namespace        = "istio-system"
  create_namespace = "true"
  name             = "istio-base"
  version          = "1.15.3"
  repository       = "https://istio-release.storage.googleapis.com/charts"
  #force_update     = var.force_update
  #recreate_pods    = var.recreate_pods
}

resource "helm_release" "istiod" {
  depends_on        = [helm_release.istio-base]
  name              = "istiod"
  namespace         = "istio-system"
  dependency_update = true
  repository        = "https://istio-release.storage.googleapis.com/charts"
  chart             = "istiod"
  version           = "1.15.3"
  atomic            = true
  lint              = true
}



terraform {
  required_providers {
    helm = {
      version = "= 2.7.1"
    }
  }

  required_version = "= 1.3.3"
}

provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}
```
In the folder with this single `istio.tf` file I run:

```
minikube start
terraform init -upgrade
terraform plan
```

Here is my output:

```
% terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # helm_release.istio-base will be created
  + resource "helm_release" "istio-base" {
      + atomic                     = false
      + chart                      = "base"
      + cleanup_on_fail            = false
      + create_namespace           = true
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = false
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "istio-base"
      + namespace                  = "istio-system"
      + pass_credentials           = false
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://istio-release.storage.googleapis.com/charts"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + verify                     = false
      + version                    = "1.15.3"
      + wait                       = true
      + wait_for_jobs              = false
    }

  # helm_release.istiod will be created
  + resource "helm_release" "istiod" {
      + atomic                     = true
      + chart                      = "istiod"
      + cleanup_on_fail            = false
      + create_namespace           = false
      + dependency_update          = true
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = true
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "istiod"
      + namespace                  = "istio-system"
      + pass_credentials           = false
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://istio-release.storage.googleapis.com/charts"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + verify                     = false
      + version                    = "1.15.3"
      + wait                       = true
      + wait_for_jobs              = false
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

**Comment by SerhiiPodlesnyi** [comment] 2022-11-15 09:30
I tried this setup. It doesn't work for me as well.

> I can't reproduce it.
> 
> % cat istio.tf
> 
> ```
> resource "helm_release" "istio-base" {
>   chart            = "base"
>   namespace        = "istio-system"
>   create_namespace = "true"
>   name             = "istio-base"
>   version          = "1.15.3"
>   repository       = "https://istio-release.storage.googleapis.com/charts"
>   #force_update     = var.force_update
>   #recreate_pods    = var.recreate_pods
> }
> 
> resource "helm_release" "istiod" {
>   depends_on        = [helm_release.istio-base]
>   name              = "istiod"
>   namespace         = "istio-system"
>   dependency_update = true
>   repository        = "https://istio-release.storage.googleapis.com/charts"
>   chart             = "istiod"
>   version           = "1.15.3"
>   atomic            = true
>   lint              = true
> }
> 
> 
> 
> terraform {
>   required_providers {
>     helm = {
>       version = "= 2.7.1"
>     }
>   }
> 
>   required_version = "= 1.3.3"
> }
> 
> provider "helm" {
>   kubernetes {
>     config_path = "~/.kube/config"
>   }
> }
> ```
> 
> In the folder with this single `istio.tf` file I run:
> 
> ```
> minikube start
> terraform init -upgrade
> terraform plan
> ```
> 
> Here is my output:
> 
> ```
> % terraform plan
> 
> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
>   + create
> 
> Terraform will perform the following actions:
> 
>   # helm_release.istio-base will be created
>   + resource "helm_release" "istio-base" {
>       + atomic                     = false
>       + chart                      = "base"
>       + cleanup_on_fail            = false
>       + create_namespace           = true
>       + dependency_update          = false
>       + disable_crd_hooks          = false
>       + disable_openapi_validation = false
>       + disable_webhooks           = false
>       + force_update               = false
>       + id                         = (known after apply)
>       + lint                       = false
>       + manifest                   = (known after apply)
>       + max_history                = 0
>       + metadata                   = (known after apply)
>       + name                       = "istio-base"
>       + namespace                  = "istio-system"
>       + pass_credentials           = false
>       + recreate_pods              = false
>       + render_subchart_notes      = true
>       + replace                    = false
>       + repository                 = "https://istio-release.storage.googleapis.com/charts"
>       + reset_values               = false
>       + reuse_values               = false
>       + skip_crds                  = false
>       + status                     = "deployed"
>       + timeout                    = 300
>       + verify                     = false
>       + version                    = "1.15.3"
>       + wait                       = true
>       + wait_for_jobs              = false
>     }
> 
>   # helm_release.istiod will be created
>   + resource "helm_release" "istiod" {
>       + atomic                     = true
>       + chart                      = "istiod"
>       + cleanup_on_fail            = false
>       + create_namespace           = false
>       + dependency_update          = true
>       + disable_crd_hooks          = false
>       + disable_openapi_validation = false
>       + disable_webhooks           = false
>       + force_update               = false
>       + id                         = (known after apply)
>       + lint                       = true
>       + manifest                   = (known after apply)
>       + max_history                = 0
>       + metadata                   = (known after apply)
>       + name                       = "istiod"
>       + namespace                  = "istio-system"
>       + pass_credentials           = false
>       + recreate_pods              = false
>       + render_subchart_notes      = true
>       + replace                    = false
>       + repository                 = "https://istio-release.storage.googleapis.com/charts"
>       + reset_values               = false
>       + reuse_values               = false
>       + skip_crds                  = false
>       + status                     = "deployed"
>       + timeout                    = 300
>       + verify                     = false
>       + version                    = "1.15.3"
>       + wait                       = true
>       + wait_for_jobs              = false
>     }
> 
> Plan: 2 to add, 0 to change, 0 to destroy.
> ```

**Comment by zioproto** [comment] 2022-11-17 08:31
@SerhiiPodlesnyi @ElkRom can you confirm that with `minikube` it works for you ?

I understand you are using AKS version 1.23.12

Can you provide the details of a minimal `az aks create` command to create a cluster where the problem can be reproduced ?

I tried the following:

```
az group create --location eastus --name debug

az aks create \
--location eastus \
--name issue41792 \
--resource-group debug \
--network-plugin azure \
--kubernetes-version 1.23.12 \
--node-vm-size Standard_DS2_v2 \
--node-count 2

az aks get-credentials --resource-group debug --name issue41792
```
Then with the same `istio.tf` as comment https://github.com/istio/istio/issues/41792#issuecomment-1303930124
```
terraform init -upgrade
terraform plan
```

It is working for me and it is generating this plan:

```
% terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # helm_release.istio-base will be created
  + resource "helm_release" "istio-base" {
      + atomic                     = false
      + chart                      = "base"
      + cleanup_on_fail            = false
      + create_namespace           = true
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = false
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "istio-base"
      + namespace                  = "istio-system"
      + pass_credentials           = false
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://istio-release.storage.googleapis.com/charts"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + verify                     = false
      + version                    = "1.15.3"
      + wait                       = true
      + wait_for_jobs              = false
    }

  # helm_release.istiod will be created
  + resource "helm_release" "istiod" {
      + atomic                     = true
      + chart                      = "istiod"
      + cleanup_on_fail            = false
      + create_namespace           = false
      + dependency_update          = true
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = true
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "istiod"
      + namespace                  = "istio-system"
      + pass_credentials           = false
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://istio-release.storage.googleapis.com/charts"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + verify                     = false
      + version                    = "1.15.3"
      + wait                       = true
      + wait_for_jobs              = false
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

Please provide the `az aks create` command to create the AKS cluster with environment where you can reproduce this problem. Thanks

**Comment by ElkRom** [comment] 2022-11-17 16:52
@zioproto for us it doesn't make sence to test on Minikube, as we are using AKS.
@SerhiiPodlesnyi  will run commands which you provided above.

Will keep you posted. Thanks @zioproto

**Comment by zioproto** [comment] 2022-11-17 17:04
@ElkRom if you could reproduce the issue on Minikube, it would mean the issue is generated from something in your environment and it is independent from AKS. It would be a good test for you to try on minikube, if you can reproduce the issue. Thanks

**Comment by pderrierw** [comment] 2022-11-21 10:49
Hello 
I have the same issue on GKE. depends_on seems to be ignored.
I tried to introduce a "delay" null_resource between istio-base et istiod resources but I keep having the same issue.

Note it works if you create istio-base alone first and then do another pla/apply with istio-base and istiod resources together

**Comment by zioproto** [comment] 2022-11-21 11:04
@pderrierw thanks for your input. It seems to me a race condition between the CRDs being ready, and the Terraform Helm provider moving to the next Chart.

I found a similar issue here: 
* https://github.com/hashicorp/terraform-provider-helm/issues/496
* https://github.com/gavinbunney/terraform-provider-kubectl/issues/41

**Comment by pderrierw** [comment] 2022-11-21 11:13
@zioproto 
indeed, that's why I tried to introduce a "null_resource" "delay" in between, but whatever the delay the result is the same .

```
   resource "null_resource" "delay" {
        provisioner "local-exec" {
            command = "sleep 20"
         }
        triggers = {
            "before" = helm_release.istio-base[0].id
         }
}```

- Actually, I am not sure the "terraform plan" can actually be tweaked this way, maybe it only impacts the "apply", isn't it ?

**Comment by zioproto** [comment] 2022-11-21 11:17
@pderrierw you are right. At the `terraform plan` phase the CRDs are not yet installed to the cluster, so cannot be the race condition.

I tried to reproduce with a completely empty Terraform state. Are you folks reproducing the issue with some initial data in the terraform state ? Or you can reproduce with an empty ( or missing ) Terraform state file ?

**Comment by zioproto** [comment] 2022-11-21 15:01
Folks, I tested again running `terraform plan` and intercepting the API calls with `mitmproxy`. To generate the plan I dont make any API call to the Kubernetes cluster.
I am pretty sure the Terraform code shared in the issue description is not enough to reproduce the bug.
Please provide more data. Thanks

**Comment by zioproto** [comment] 2022-11-21 20:47
I confirm @chris-arsenault is correct. I can reproduce on minikube

```
% cat istio.tf

resource "helm_release" "istio-base" {
  chart            = "base"
  namespace        = "istio-system"
  create_namespace = "true"
  name             = "istio-base"
  version          = "1.15.3"
  repository       = "https://istio-release.storage.googleapis.com/charts"
  #force_update     = var.force_update
  #recreate_pods    = var.recreate_pods
}

resource "helm_release" "istiod" {
  depends_on        = [helm_release.istio-base]
  name              = "istiod"
  namespace         = "istio-system"
  dependency_update = true
  repository        = "https://istio-release.storage.googleapis.com/charts"
  chart             = "istiod"
  version           = "1.15.3"
  atomic            = true
  lint              = true
}

terraform {
  required_providers {
    helm = {
      version = "= 2.7.1"
    }
  }

  required_version = "= 1.3.3"
}

provider "helm" {
  experiments { // this enables diff detection of helm templates
    manifest = true
  }
  kubernetes {
    config_path = "~/.kube/config"
  }
}
```

In the folder with `istio.tf` I run:
```
minikube start
terraform init -upgrade
terraform plan
```

here my failing output:

```
% terraform plan
╷
│ Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "stats-filter-1.13" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "tcp-stats-filter-1.13" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "stats-filter-1.14" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "tcp-stats-filter-1.14" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "stats-filter-1.15" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first, resource mapping not found for name: "tcp-stats-filter-1.15" namespace: "istio-system" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
│ ensure CRDs are installed first]
│
│   with helm_release.istiod,
│   on istio.tf line 12, in resource "helm_release" "istiod":
│   12: resource "helm_release" "istiod" {
│
╵
```

@ElkRom can you confirm if you have the `experiments` with `manifest = true` in your provider configuration ?

**Comment by zioproto** [comment] 2022-11-21 21:22
@ElkRom I believe this is not an Istio issue, I would close this GitHub issue and open a new one on the hashicorp/terraform-provider-helm GitHub repository:

I also found this related issue there:
* https://github.com/hashicorp/terraform-provider-helm/issues/976

Please confirm if we can close this issue. Thanks

**Comment by ElkRom** [comment] 2022-11-21 21:24
Yeah, definetly this issue have to be closed for Istio.
Thanks

**Closed** 2022-11-22 01:15 UTC
Labels: area/environments
