### ISSUE TITLE
Helm Chart.yaml for istio 1.1.3 release is 1.1.0

### ISSUE THREAD

**Issue by erezzarum** [istio/istio#13416] opened 2019-04-18 11:14 UTC
That Chart.yaml and requirements.yaml in the Helm charts (all the subcharts as well) for release 1.1.3 are set to 1.1.0 while the ones for 1.1.2 are set to 1.1.2.

I also noticed that the helm repository index (https://storage.googleapis.com/istio-release/releases/1.1.3/charts/index.yaml) is set to istio-1.1.0.tgz and istio-init-1.1.0.tgz.

It may cause conflicts when using helm.

**Comment by thangbn** [comment] 2019-04-18 17:27
notice it too

**Comment by ibm-jason** [comment] 2019-04-18 17:43
@erezzarum, @thangbn - this one is most likely a duplicate of #12777, but I'll grab this one since I'm working on the other. 👍

**Comment by thangbn** [comment] 2019-04-18 17:46
@ibm-jason this is pretty urgent fix, it broke our current deployment

**Comment by ibm-jason** [comment] 2019-04-18 17:48
@utka ☝️ -

**Comment by utka** [comment] 2019-04-18 18:25
Fixed

**Closed by utka** 2019-04-18 18:25 UTC

**Comment by ibm-jason** [comment] 2019-04-18 20:43
For documentation purposes, I'm commenting on this close issue to document what we did here.

The [public storage bucket](https://console.cloud.google.com/storage/browser/istio-release/releases/1.1.3/charts) that hosts the Istio build artifacts was manually updated by unarchiving the `istio-1.1.3.tgz` file, updating each of the Chart.yaml files, then re-archived and re-upload back to the storage bucket. This is considered a "manual fix" for this issue. The fix for #12777 will ensure that the versions are fixed _BEFORE_ being published to the public storage bucket for consumption.

/cc @utka
