### ISSUE TITLE
the network of container cant connect when spring clound start with istio sidecar

### ISSUE THREAD

**Issue by mrwenhui** [istio/istio#13911] opened 2019-05-08 10:57 UTC
**Bug description**
the network of container cant connect when spring clound start with istio sidecar
**Expected behavior**
the spring cloud service can connect to config-server and get config to start up.
**Steps to reproduce the bug**
i have one project with  a config-server and more than 10 spring clouod service.
when enable auto inject sidecar, I deployment those all the services, and config initcontainer to start config-server first.
the issue i encounter is that few services cant  connect to config-server and  hint "connected refused" in spirng clound service logs.
I also encounter the config-server can't access git repository and with connected refused log.
if i deployment those services without any istio component, all those services works fine.

I guess the sidecar take over the network and block network access.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
the istio works fine.

**Environment where bug was observed (cloud vendor, OS, etc)**
aliyun  ubuntu 18.04  custom k8s   5 nodes include 1 master

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[* ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by esnible** [comment] 2019-05-08 17:36
This may be a duplicate of https://github.com/istio/istio/issues/9454 and https://github.com/istio/istio/issues/11130 .

If I run into this I add scripting to wait for Envoy in my deployment YAML:

```
command: ["/bin/bash", "-c"]
args: ["until curl --head localhost:15000 ; do echo Waiting for Sidecar; sleep 3 ; done ; echo Sidecar available; ./startup.sh"] # replace startup.sh with actual startup command.
```

Try something like the above.  A similar variant is to do

```
command: ["/bin/bash", "-c"]
args: ["sleep 999999999"]
```

and then `kubectl exec` into your pod and start the app manually.

It would be better if networking was ready when the app container started.  For more details see the Issues.

**Comment by mrwenhui** [comment] 2019-05-09 09:05
@esnible  I modified the script curl --head localhost:15000 can 't mean you can get connected  with outside thought sidecar. Only you check if you services can  connected though sideccar
```
 command: ["/bin/bash", "-c"]
          args: ["until [ $(curl -m 5 -s -o /dev/null -w %{http_code} config-server:8888) -eq 401 ] ; do echo Waiting for Sidecar; sleep 3 ; done ; 
```

**Comment by esnible** [comment] 2019-05-09 14:38
@mrwenhui Did this change mitigate your problem?

**Comment by mrwenhui** [comment] 2019-05-10 02:05
yes, all the services run as my expection.

**Closed** 2019-05-10 14:26 UTC
