### ISSUE TITLE
Envoy container prevents job from ending

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#42824] opened 2023-01-16 07:51 UTC
Hi,

I am running jobs with istio, when my job is complete, my job container is marked as completed, but the envoy container stays up and prevents the job from completing.

I saw a few examples of how to solve this issue, like overriding the command and killing Envoy with the /quitquitquit endpoint, but this is only a workaround, and I am looking for a better way.

any advice?

Thanks!

**Comment by ymesika** [comment] 2023-01-16 12:04
There is a long discussion about this here: https://github.com/istio/istio/issues/11659
I believe the `/quitquitquit` call at the end of the job is still the way to go although it looks like a workaround.

**Comment by hzxuzhonghu** [comment] 2023-01-17 03:58
No progress in Kubernetes https://github.com/kubernetes/kubernetes/issues/25908

**Comment by howardjohn** [comment] 2023-02-20 22:35
dupe of https://github.com/istio/istio/issues/11659

**Closed by howardjohn** 2023-02-20 22:35 UTC
