### ISSUE TITLE
Large amounts of AAAA (ipv6) DNS queries from istio-proxy/envoy

### ISSUE THREAD

**Issue by Stono** [istio/istio#12968] opened 2019-04-01 19:22 UTC
**Describe the bug**
I'm seeing a lot of `AAAA` queries hitting our DNS servers, most of which seem to be istio related, from sidecar (**1000s/sec** due to the size of my cluster):

We're talking **12** `AAAA` queries (specifically 6 `zipkin`, 6 `istio-pilot`), per pod, every **5** seconds.  On a cluster like mine with **500** pods, we're talking **6,000** queries every **5** seconds.

Running on GKE each kube-dns instance can only handle **150** concurrent requests, so i've had to scale wider to accommodate `AAAA` queries, despite my cluster being ipv4 only.

```
19:18:22.427902 IP 10.198.31.17.35811 > 10.198.41.5.53: 50425+ AAAA? zipkin.istio-system.recruitment-website.svc.cluster.local. (75)
19:18:22.428076 IP 10.198.36.4.44103 > 10.198.41.5.53: 16192+ AAAA? istio-pilot.istio-system.cluster.local. (56)
19:18:22.429425 IP 10.198.36.4.44103 > 10.198.41.5.53: 51265+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-preprod.internal. (82)
19:18:22.429490 IP 10.198.41.5.8155 > 169.254.169.254.53: 23059+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-preprod.internal. (82)
19:18:22.429956 IP 10.198.31.17.35811 > 10.198.41.5.53: 37293+ AAAA? istio-pilot.istio-system.svc.cluster.local. (60)
19:18:22.429967 IP 10.198.31.17.35811 > 10.198.41.5.53: 26153+ AAAA? zipkin.istio-system.svc.cluster.local. (55)
19:18:22.430559 IP 10.198.31.17.35811 > 10.198.41.5.53: 33019+ AAAA? zipkin.istio-system.cluster.local. (51)
19:18:22.430561 IP 10.198.31.17.35811 > 10.198.41.5.53: 57939+ AAAA? istio-pilot.istio-system.cluster.local. (56)
19:18:22.430810 IP 10.198.36.4.44103 > 10.198.41.5.53: 54396+ AAAA? istio-pilot.istio-system.google.internal. (58)
19:18:22.430956 IP 10.198.41.5.9704 > 169.254.169.254.53: 19947+ AAAA? istio-pilot.istio-system.google.internal. (58)
19:18:22.431206 IP 10.198.31.17.35811 > 10.198.41.5.53: 56497+ AAAA? zipkin.istio-system.c.at-delivery-platform-preprod.internal. (77)
19:18:22.431224 IP 10.198.31.17.35811 > 10.198.41.5.53: 38725+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-preprod.internal. (82)
19:18:22.431281 IP 10.198.41.5.28680 > 169.254.169.254.53: 9142+ AAAA? zipkin.istio-system.c.at-delivery-platform-preprod.internal. (77)
19:18:22.431347 IP 10.198.41.5.10254 > 169.254.169.254.53: 60+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-preprod.internal. (82)
19:18:22.431871 IP 10.198.36.4.44103 > 10.198.41.5.53: 51553+ AAAA? istio-pilot.istio-system. (42)
19:18:22.431989 IP 10.198.41.5.44943 > 169.254.169.254.53: 31950+ AAAA? istio-pilot.istio-system. (42)
19:18:22.432005 IP 10.198.31.17.35811 > 10.198.41.5.53: 48525+ AAAA? zipkin.istio-system.google.internal. (53)
19:18:22.432059 IP 10.198.41.5.31591 > 169.254.169.254.53: 60643+ AAAA? zipkin.istio-system.google.internal. (53)
19:18:22.432082 IP 10.198.31.17.35811 > 10.198.41.5.53: 24157+ AAAA? istio-pilot.istio-system.google.internal. (58)
19:18:22.432163 IP 10.198.41.5.18137 > 169.254.169.254.53: 6658+ AAAA? istio-pilot.istio-system.google.internal. (58)
19:18:22.432965 IP 10.198.31.17.35811 > 10.198.41.5.53: 23375+ AAAA? zipkin.istio-system. (37)
19:18:22.432974 IP 10.198.31.17.35811 > 10.198.41.5.53: 9264+ AAAA? istio-pilot.istio-system. (42)
19:18:22.433030 IP 10.198.41.5.34606 > 169.254.169.254.53: 22153+ AAAA? zipkin.istio-system. (37)
19:18:22.433117 IP 10.198.41.5.25907 > 169.254.169.254.53: 51493+ AAAA? istio-pilot.istio-system. (42)
19:18:22.453207 IP 10.198.36.14.43815 > 10.198.41.5.53: 45671+ AAAA? istio-pilot.istio-system.advertising-preferences-service.svc.cluster.local. (92)
19:18:22.453216 IP 10.198.36.14.43815 > 10.198.41.5.53: 56926+ AAAA? zipkin.istio-system.advertising-preferences-service.svc.cluster.local. (87)
19:18:22.454125 IP 10.198.36.14.43815 > 10.198.41.5.53: 43764+ AAAA? istio-pilot.istio-system.svc.cluster.local. (60)
19:18:22.454260 IP 10.198.36.14.43815 > 10.198.41.5.53: 52728+ AAAA? zipkin.istio-system.svc.cluster.local. (55)
19:18:22.454439 IP 10.198.28.12.56608 > 10.198.41.5.53: 32292+ AAAA? istio-pilot.istio-system.vehicle-check-report-generator.svc.cluster.local. (91)
19:18:22.454455 IP 10.198.28.12.56608 > 10.198.41.5.53: 15306+ AAAA? zipkin.istio-system.vehicle-check-report-generator.svc.cluster.local. (86)
19:18:22.454862 IP 10.198.36.14.43815 > 10.198.41.5.53: 51507+ AAAA? istio-pilot.istio-system.cluster.local. (56)
19:18:22.454870 IP 10.198.36.14.43815 > 10.198.41.5.53: 36680+ AAAA? zipkin.istio-system.cluster.local. (51)
19:18:22.455403 IP 10.198.36.14.43815 > 10.198.41.5.53: 58591+ AAAA? zipkin.istio-system.c.at-delivery-platform-preprod.internal. (77)
19:18:22.455458 IP 10.198.41.5.24304 > 169.254.169.254.53: 43112+ AAAA? zipkin.istio-system.c.at-delivery-platform-preprod.internal. (77)
19:18:22.455504 IP 10.198.36.14.43815 > 10.198.41.5.53: 58153+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-preprod.internal. (82)
19:18:22.455531 IP 10.198.41.5.61203 > 169.254.169.254.53: 27870+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-preprod.internal. (82)
19:18:22.456006 IP 10.198.28.12.56608 > 10.198.41.5.53: 23935+ AAAA? istio-pilot.istio-system.svc.cluster.local. (60)
19:18:22.456016 IP 10.198.28.12.56608 > 10.198.41.5.53: 34637+ AAAA? zipkin.istio-system.svc.cluster.local. (55)
19:18:22.456352 IP 10.198.36.14.43815 > 10.198.41.5.53: 15355+ AAAA? zipkin.istio-system.google.internal. (53)
19:18:22.456519 IP 10.198.36.14.43815 > 10.198.41.5.53: 13755+ AAAA? istio-pilot.istio-system.google.internal. (58)
19:18:22.456560 IP 10.198.41.5.47088 > 169.254.169.254.53: 49168+ AAAA? zipkin.istio-system.google.internal. (53)
19:18:22.456793 IP 10.198.28.12.56608 > 10.198.41.5.53: 24878+ AAAA? zipkin.istio-system.cluster.local. (51)
19:18:22.456808 IP 10.198.41.5.42095 > 169.254.169.254.53: 47806+ AAAA? istio-pilot.istio-system.google.internal. (58)
19:18:22.457004 IP 10.198.28.12.56608 > 10.198.41.5.53: 57194+ AAAA? istio-pilot.istio-system.cluster.local. (56)
19:18:22.457384 IP 10.198.28.12.56608 > 10.198.41.5.53: 64330+ AAAA? zipkin.istio-system.c.at-delivery-platform-preprod.internal. (77)
19:18:22.457477 IP 10.198.41.5.54980 > 169.254.169.254.53: 63541+ AAAA? zipkin.istio-system.c.at-delivery-platform-preprod.internal. (77)
19:18:22.457507 IP 10.198.28.12.56608 > 10.198.41.5.53: 64052+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-preprod.internal. (82)
19:18:22.457552 IP 10.198.41.5.29646 > 169.254.169.254.53: 15297+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-preprod.internal. (82)
19:18:22.457583 IP 10.198.36.14.43815 > 10.198.41.5.53: 37576+ AAAA? zipkin.istio-system. (37)
19:18:22.457616 IP 10.198.36.14.43815 > 10.198.41.5.53: 16933+ AAAA? istio-pilot.istio-system. (42)
19:18:22.457700 IP 10.198.41.5.37225 > 169.254.169.254.53: 50738+ AAAA? zipkin.istio-system. (37)
19:18:22.457764 IP 10.198.41.5.18609 > 169.254.169.254.53: 61010+ AAAA? istio-pilot.istio-system. (42)
```

Even when things run with:
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

And pods don't have ipv6 addresses:
```
root@platform-testing-6f98ccd788-sg5vv:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 1e:72:c3:04:da:92
          inet addr:10.206.0.7  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:780 errors:0 dropped:0 overruns:0 frame:0
          TX packets:781 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:235251 (235.2 KB)  TX bytes:98687 (98.6 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:214 errors:0 dropped:0 overruns:0 frame:0
          TX packets:214 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:135779 (135.7 KB)  TX bytes:135779 (135.7 KB)
```

It appears to be doing is ipv6 lookups *first*, and then on all search domains because they fail, and then finally ipv4, which resolves correctly.  And it's doing it every 5 seconds:

````
21:25:00.012352 IP platform-testing-6f98ccd788-cmfp8.46785 > kube-dns.kube-system.svc.cluster.local.53: 33255+ AAAA? zipkin.istio-system.platform-testing.svc.cluster.local. (72)
21:25:00.014811 IP platform-testing-6f98ccd788-cmfp8.46785 > kube-dns.kube-system.svc.cluster.local.53: 31335+ AAAA? zipkin.istio-system.svc.cluster.local. (55)
21:25:00.015544 IP platform-testing-6f98ccd788-cmfp8.46785 > kube-dns.kube-system.svc.cluster.local.53: 11582+ AAAA? zipkin.istio-system.cluster.local. (51)
21:25:00.016128 IP platform-testing-6f98ccd788-cmfp8.46785 > kube-dns.kube-system.svc.cluster.local.53: 34934+ AAAA? zipkin.istio-system.c.at-delivery-platform-testing.internal. (77)
21:25:00.017375 IP platform-testing-6f98ccd788-cmfp8.46785 > kube-dns.kube-system.svc.cluster.local.53: 41290+ AAAA? zipkin.istio-system.google.internal. (53)
21:25:00.018359 IP platform-testing-6f98ccd788-cmfp8.46785 > kube-dns.kube-system.svc.cluster.local.53: 36159+ AAAA? zipkin.istio-system. (37)
21:25:00.019646 IP platform-testing-6f98ccd788-cmfp8.46785 > kube-dns.kube-system.svc.cluster.local.53: 62659+ A? zipkin.istio-system.platform-testing.svc.cluster.local. (72)
````

And it does this for `zipkin` and `istio-pilot`.

I'm sure there's a reason why you update those services every 5 seconds, and I wouldn't mind so much if this was just for A records, but AAAA is 6x the load and useless. 

Is there any way to stop istio bothering with ipv6?    I know work has been done to enable it (https://github.com/istio/istio/issues/1756) but, how can i opt out?  For example in java we do `preferIPV4Stack=true`.

I'm running on GKE, my (default) /etc/resolv.conf looks like this:
```
nameserver 10.192.96.10
search platform-testing.svc.cluster.local svc.cluster.local cluster.local c.at-delivery-platform-testing.internal google.internal
options ndots:5
```

I'm on istio 1.1.1

**Comment by Stono** [comment] 2019-04-01 20:44
So I tried with an initContainer to disable ipv6 on the interface, as you can see:

```
root@platform-testing-6f98ccd788-sg5vv:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 1e:72:c3:04:da:92
          inet addr:10.206.0.7  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:780 errors:0 dropped:0 overruns:0 frame:0
          TX packets:781 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:235251 (235.2 KB)  TX bytes:98687 (98.6 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:214 errors:0 dropped:0 overruns:0 frame:0
          TX packets:214 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:135779 (135.7 KB)  TX bytes:135779 (135.7 KB)
```

But istio-proxy is still making a whole bunch of ipv6 requests?
```
root@platform-testing-6f98ccd788-sg5vv:~# tcpdump -i eth0 port 53 | grep AAAA
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
20:43:18.588927 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 28504+ AAAA? zipkin.istio-system.platform-testing.svc.cluster.local. (72)
20:43:18.589021 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 31834+ AAAA? istio-pilot.istio-system.platform-testing.svc.cluster.local. (77)
20:43:18.591463 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 9465+ AAAA? zipkin.istio-system.svc.cluster.local. (55)
20:43:18.591485 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 46048+ AAAA? istio-pilot.istio-system.svc.cluster.local. (60)
20:43:18.592232 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 51103+ AAAA? zipkin.istio-system.cluster.local. (51)
20:43:18.592258 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 8692+ AAAA? istio-pilot.istio-system.cluster.local. (56)
20:43:18.592810 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 53043+ AAAA? zipkin.istio-system.c.at-delivery-platform-testing.internal. (77)
20:43:18.592820 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 13298+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-testing.internal. (82)
20:43:18.593949 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 41586+ AAAA? zipkin.istio-system.google.internal. (53)
20:43:18.594067 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 36267+ AAAA? istio-pilot.istio-system.google.internal. (58)
20:43:18.594520 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 25729+ AAAA? zipkin.istio-system. (37)
20:43:18.595776 IP platform-testing-6f98ccd788-sg5vv.51587 > kube-dns.kube-system.svc.cluster.local.53: 24486+ AAAA? istio-pilot.istio-system. (42)
^C34 packets captured
34 packets received by filter
0 packets dropped by kernel

```

**Comment by Stono** [comment] 2019-04-01 20:59
OK so what we see is every istio-proxy doing AAAA queries for these hosts:

```
20:56:59.949118 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 41115+ AAAA? zipkin.istio-system.platform-testing.svc.cluster.local. (72)
20:56:59.949235 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 36699+ AAAA? istio-pilot.istio-system.platform-testing.svc.cluster.local. (77)
20:56:59.952027 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 15858+ AAAA? zipkin.istio-system.svc.cluster.local. (55)
20:56:59.952049 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 38977+ AAAA? istio-pilot.istio-system.svc.cluster.local. (60)
20:56:59.952965 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 47222+ AAAA? zipkin.istio-system.cluster.local. (51)
20:56:59.953004 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 15990+ AAAA? istio-pilot.istio-system.cluster.local. (56)
20:56:59.953572 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 37565+ AAAA? zipkin.istio-system.c.at-delivery-platform-testing.internal. (77)
20:56:59.953585 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 59975+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-testing.internal. (82)
20:56:59.954859 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 17109+ AAAA? zipkin.istio-system.google.internal. (53)
20:56:59.954876 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 20862+ AAAA? istio-pilot.istio-system.google.internal. (58)
20:56:59.955679 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 43254+ AAAA? istio-pilot.istio-system. (42)
20:56:59.955768 IP platform-testing-6f98ccd788-sg5vv.60388 > kube-dns.kube-system.svc.cluster.local.53: 16826+ AAAA? zipkin.istio-system. (37)
```

Every 5 seconds.

So to put that into perspective for us that's 30,000 `AAAA` queries every 5 seconds, so 6,000/second.

On a cluster which has ipv6 largely disabled 🤷‍♂️

**Comment by Stono** [comment] 2019-04-01 21:11
The 5s thing is nothing to do with failed requests btw, istio-proxy is just looking up zipkin and istio-pilot every 5s:

```
root@platform-testing-6f98ccd788-sg5vv:~# tcpdump -i eth0 port 53 | grep " A? "
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
21:09:56.248463 IP platform-testing-6f98ccd788-sg5vv.46213 > kube-dns.kube-system.svc.cluster.local.53: 16066+ A? zipkin.istio-system.platform-testing.svc.cluster.local. (72)
21:09:56.248951 IP platform-testing-6f98ccd788-sg5vv.46213 > kube-dns.kube-system.svc.cluster.local.53: 28896+ A? zipkin.istio-system.svc.cluster.local. (55)
21:09:56.249431 IP platform-testing-6f98ccd788-sg5vv.46213 > kube-dns.kube-system.svc.cluster.local.53: 54202+ A? istio-pilot.istio-system.platform-testing.svc.cluster.local. (77)
21:09:56.249810 IP platform-testing-6f98ccd788-sg5vv.46213 > kube-dns.kube-system.svc.cluster.local.53: 62043+ A? istio-pilot.istio-system.svc.cluster.local. (60)
21:10:01.254648 IP platform-testing-6f98ccd788-sg5vv.58866 > kube-dns.kube-system.svc.cluster.local.53: 42553+ A? zipkin.istio-system.platform-testing.svc.cluster.local. (72)
21:10:01.254674 IP platform-testing-6f98ccd788-sg5vv.58866 > kube-dns.kube-system.svc.cluster.local.53: 47272+ A? istio-pilot.istio-system.platform-testing.svc.cluster.local. (77)
21:10:01.255231 IP platform-testing-6f98ccd788-sg5vv.58866 > kube-dns.kube-system.svc.cluster.local.53: 6973+ A? zipkin.istio-system.svc.cluster.local. (55)
21:10:01.255284 IP platform-testing-6f98ccd788-sg5vv.58866 > kube-dns.kube-system.svc.cluster.local.53: 55656+ A? istio-pilot.istio-system.svc.cluster.local. (60)
```

I wouldn't mind so much if this was just for A records, but AAAA is 6x the load and useless.

**Comment by Stono** [comment] 2019-04-02 08:49
@howardjohn suggested setting `global.proxy.dnsRefreshRate` higher as an interim work around.  However that setting had no effect, and these queries still happen every 5 seconds.

**Comment by Stono** [comment] 2019-04-02 08:54
cc. @costinm @mandarjog @nmittler - can anyone help me looking at this please?

**Comment by hzxuzhonghu** [comment] 2019-04-02 09:03
This value only valid for 	two cluster types 
        1: "STRICT_DNS",
	2: "LOGICAL_DNS",

And I think the control-plane service is  `STATIC` type

**Comment by Stono** [comment] 2019-04-02 09:07
Thanks.  So back to the original issue, why is istio-proxy querying ipv6 records for pilot and zipkin every 5 seconds?

**Comment by hzxuzhonghu** [comment] 2019-04-02 09:44
I think this has something todo with the envoy bootstrap config, you can check it. And there is no setting for dns resolve. So the root is `/etc/istio/proxy/envoy-rev0.json`, I think we should fix it in tools/deb/envoy_bootstrap_v2.json

**Comment by rshriram** [comment] 2019-04-02 14:12
that wont help.. you would simply swap ipv6 for ipv4 and have that many DNS queries.
we should use FQDN for pilot and zipkin

**Comment by howardjohn** [comment] 2019-04-02 14:16
I think it's doing ipv6 AND ipv4 queries right now

**Comment by Stono** [comment] 2019-04-02 14:19
It is, @rshriram change should reduce the zipkin ones hopefully a little bit (will report back), but not `istio-pilot`, and not the fact it's doing ipv6 **first**.

**Comment by rshriram** [comment] 2019-04-02 14:24
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/configmap.yaml#L234 and similar for zipkin - is using name.namespace.. this will cause libc to try to resolve with all DNS suffixes.. if you use FQDN, it "might" help reduce the traffic. And as far as the ipv6 is concerned, i think it has to do with the way libc detects ipv6 support on the system

**Comment by howardjohn** [comment] 2019-04-02 14:29
From Slack:

> Etai Lev Ran   [2 minutes ago]
> There is an upstream cluster option in the Envoy v2 API - https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#enum-cluster-dnslookupfamily
> Perhaps we need to allow user to override the default (`AUTO` which does an IPv6 lookup first)

**Comment by rshriram** [comment] 2019-04-02 14:31
yes I know that. but the question is why is it not happening for ipv4

**Comment by howardjohn** [comment] 2019-04-02 14:32
> if AUTO is specified, the DNS resolver will first perform a lookup for addresses in the IPv6 family and fallback to a lookup for addresses in the IPv4 family

Sounds like we specify AUTO (the default), and then Envoy looks up ipv6 then ipv4. Sounds exactly like what is being seen here

**Comment by rshriram** [comment] 2019-04-02 14:41
That is not the root cause IMO.. Its just triggering the symptom. The fact that envoy is trying to do ipv6 even when there is no ipv6 address in the pod is a clear bug. Secondly, ndots is high (i think it should be 4 instead of 5). Its effectively forcing any DNS query to go through the search list before accepting the DNS name as is. So, you will still see load for ipv4 as well
```21:25:00.019646 IP platform-testing-6f98ccd788-cmfp8.46785 > kube-dns.kube-system.svc.cluster.local.53: 62659+ A? zipkin.istio-system.platform-testing.svc.cluster.local. (72)```

notice the platform-testing being appended to zipkin.istio-system 

from man pages
```
Resolver queries having fewer than ndots dots
              (default is 1) in them will be attempted using each component
              of the search path in turn until a match is found.  For
              environments with multiple subdomains please read options
              ndots:n below to avoid man-in-the-middle attacks and
              unnecessary traffic for the root-dns-servers.  Note that this
              process may be slow and will generate a lot of network traffic
              if the servers for the listed domains are not local, and that
              queries will time out if no server is available for one of the
              domains.
```

**Comment by Stono** [comment] 2019-04-02 14:46
That ndots value is the out of the box config on GKE btw.  You'd have to
override the DNS settings on every pod to change it which isn't a simple
thing to do.

**Comment by Stono** [comment] 2019-04-02 14:54
Also with a lower ndots, we would still get all the V6 fails first.

**Comment by Stono** [comment] 2019-04-02 15:05
Changing to FQDN didn't do a lot to be honest as it's still going to go over the search domains as the ipv6 versions don't exist:

```
15:04:18.417559 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 26845+ AAAA? zipkin.istio-system.svc.cluster.local.platform-testing.svc.cluster.local. (90)
15:04:18.418757 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 42962+ AAAA? istio-pilot.istio-system.svc.cluster.local.platform-testing.svc.cluster.local. (95)
15:04:18.420199 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 14486+ AAAA? zipkin.istio-system.svc.cluster.local.svc.cluster.local. (73)
15:04:18.420237 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 41552+ AAAA? istio-pilot.istio-system.svc.cluster.local.svc.cluster.local. (78)
15:04:18.420954 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 36934+ AAAA? zipkin.istio-system.svc.cluster.local.cluster.local. (69)
15:04:18.421041 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 24240+ AAAA? istio-pilot.istio-system.svc.cluster.local.cluster.local. (74)
15:04:18.421710 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 50851+ AAAA? zipkin.istio-system.svc.cluster.local.c.at-delivery-platform-testing.internal. (95)
15:04:18.421773 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 59118+ AAAA? istio-pilot.istio-system.svc.cluster.local.c.at-delivery-platform-testing.internal. (100)
15:04:18.425551 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 10163+ AAAA? istio-pilot.istio-system.svc.cluster.local.google.internal. (76)
15:04:18.426905 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 21879+ AAAA? zipkin.istio-system.svc.cluster.local.google.internal. (71)
15:04:18.431596 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 27078+ AAAA? zipkin.istio-system.svc.cluster.local. (55)
15:04:18.431625 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 24710+ AAAA? istio-pilot.istio-system.svc.cluster.local. (60)
15:04:18.433942 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 7109+ A? zipkin.istio-system.svc.cluster.local.platform-testing.svc.cluster.local. (90)
15:04:18.433978 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 22970+ A? istio-pilot.istio-system.svc.cluster.local.platform-testing.svc.cluster.local. (95)
15:04:18.434685 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 43086+ A? zipkin.istio-system.svc.cluster.local.svc.cluster.local. (73)
15:04:18.434703 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 23076+ A? istio-pilot.istio-system.svc.cluster.local.svc.cluster.local. (78)
15:04:18.435247 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 27039+ A? zipkin.istio-system.svc.cluster.local.cluster.local. (69)
15:04:18.435365 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 26225+ A? istio-pilot.istio-system.svc.cluster.local.cluster.local. (74)
15:04:18.436079 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 39741+ A? zipkin.istio-system.svc.cluster.local.c.at-delivery-platform-testing.internal. (95)
15:04:18.436103 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 30340+ A? istio-pilot.istio-system.svc.cluster.local.c.at-delivery-platform-testing.internal. (100)
15:04:18.440044 IP platform-testing-6f98ccd788-x59qj.42279 > kube-dns.kube-system.svc.cluster.local.53: 52900+ A? zipkin.istio-system.svc.cluster.local.google.internal. (71)
```

**Comment by Stono** [comment] 2019-04-02 15:07
In fact it's worse than than using short names in the config!  This is what you get *not* using fqdns:
```
15:06:37.195010 IP platform-unsee-65bb8c7d45-d2gjh.37358 > kube-dns.kube-system.svc.cluster.local.53: 31287+ AAAA? istio-pilot.istio-system.platform-unsee.svc.cluster.local. (75)
15:06:37.196471 IP platform-unsee-65bb8c7d45-d2gjh.37358 > kube-dns.kube-system.svc.cluster.local.53: 31076+ AAAA? istio-pilot.istio-system.svc.cluster.local. (60)
15:06:37.197256 IP platform-unsee-65bb8c7d45-d2gjh.37358 > kube-dns.kube-system.svc.cluster.local.53: 23127+ AAAA? istio-pilot.istio-system.cluster.local. (56)
15:06:37.197892 IP platform-unsee-65bb8c7d45-d2gjh.37358 > kube-dns.kube-system.svc.cluster.local.53: 54519+ AAAA? istio-pilot.istio-system.c.at-delivery-platform-testing.internal. (82)
15:06:37.202355 IP platform-unsee-65bb8c7d45-d2gjh.37358 > kube-dns.kube-system.svc.cluster.local.53: 48938+ AAAA? istio-pilot.istio-system.google.internal. (58)
15:06:37.203458 IP platform-unsee-65bb8c7d45-d2gjh.37358 > kube-dns.kube-system.svc.cluster.local.53: 59186+ AAAA? istio-pilot.istio-system. (42)
15:06:37.204497 IP platform-unsee-65bb8c7d45-d2gjh.37358 > kube-dns.kube-system.svc.cluster.local.53: 24222+ A? istio-pilot.istio-system.platform-unsee.svc.cluster.local. (75)
15:06:37.205193 IP platform-unsee-65bb8c7d45-d2gjh.37358 > kube-dns.kube-system.svc.cluster.local.53: 59860+ A? istio-pilot.istio-system.svc.cluster.local. (60)
```

**Comment by Stono** [comment] 2019-04-02 15:16
And also, it's not just IPV6 first, why does it need to check the IP of a **service**, every 5 seconds?  That feels excessive, kubernetes service IP's only change if you purge the service and recreate it?

So there are two issues really:

  - Inability to resolve IPV4 first results in lots of IPV6 questions first
  - Inability to configure the DNS resolution check interval means we're checking a service ip every 5 seconds

**Comment by Stono** [comment] 2019-04-02 15:30
It's also worth noting that `global.proxy.dnsRefreshRate` which is supposed to control the DNS checks for clusters with `STRICT_DNS` (which looking at https://github.com/istio/istio/blob/release-1.1/tools/deb/envoy_bootstrap_v2.json both `zipkin` and `istio-pilot` are), does not apply to that bootstrap config, so you can't change that 5s check on these.

**Comment by elevran** [comment] 2019-04-02 15:30
Envoy supports v4only, v6only or auto (which is v6 first and if that fails, fallback to v4).
Doing IPv4 first requires an Envoy change.
I do think we can change the bootstrap config clusters to use LBFamily = v4only (without v6 fallback) if that would resolve the issue. Can also look if there is a way to make the DNS cache timeout higher

**Comment by Stono** [comment] 2019-04-02 15:34
@elevran see the PR I linked where @rshriram has modified the bootstrap config to be ipv4 only (which i think makes sense, unless you know of anyone building ipv6 only clusters!?).

Yeah increasing the timeout would be good - as i mentioned - driving it from `global.proxy.dnsRefreshRate` makes sense if possible.

**Comment by elevran** [comment] 2019-04-02 15:36
Sounds like that change could go into the same PR

**Comment by Stono** [comment] 2019-04-02 15:36
Whatever gets it merged sooner so i can drop my DNS servers sweating ;)

**Comment by Stono** [comment] 2019-04-04 14:41
Using the last nightly build `1.1-20190404-09-16` with this fix in = no AAAA anymore, yay. 

Thanks @rshriram

**Comment by howardjohn** [comment] 2019-05-10 15:23
I am going to close this to consolidate a few DNS related issues we have. This ipv6 issue in particular is fixed. Other DNS improvements are being tracked in https://github.com/istio/istio/issues/13710

**Closed by howardjohn** 2019-05-10 15:23 UTC
