### ISSUE TITLE
`istioctl manifest migrate` outputs info/error messages into stdout, mixed with output manifest

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#19505] opened 2019-12-10 22:41 UTC
`istioctl manifest migrate` outputs info/error messages into stdout, mixed with output manifest, which makes it not able to pipe the output to kubectl.

```
taohe@taohe:~/istio.io/operator$ istioctl manifest migrate 
translating in cluster specs

autoInjection:
  components:
    injector:
      enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution: []
            requiredDuringSchedulingIgnoredDuringExecution: []
        nodeSelector: {}
        podAnnotations: {}
        replicaCount: 1
        resources: {}
        strategy:
...
```

**Comment by ostromart** [comment] 2019-12-12 19:11
Duplicate of https://github.com/istio/istio/issues/17743

**Closed by ostromart** 2019-12-12 19:11 UTC
Labels: area/environments/operator
