### ISSUE TITLE
All Sidecar resources need istio-system defined as egress host which is unclear from docs

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#12237] opened 2019-03-04 22:13 UTC
**Describe the bug**
The new [Sidecar](https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/sidecar/) resource requires that `istio-system` is explicitly defined as an egress host if the Sidecar resource includes any egress hosts. This seems broken as users will be caught off guard  when using this feature for the first time, they will see failures from the sidecar to Mixer, Pilot which in turn can have cascading failures.
 
**Expected behavior**
Either `istio-system` is always allowed as an egress host or documentation clearly states that users need to add `istio-system` in every Sidecar resource they define which I think is a poor user experience.

**Version**
[Istio 1.1.0-rc0 ](https://github.com/istio/istio/releases/tag/1.1.0-rc.0)

We will be willing to submit a PR for updating the docs if the maintainers have agreement on the expected behavior. Thanks @jacob-delgado for testing the new functionality.

**Comment by nrjpoddar** [comment] 2019-03-04 22:21
@louiscryan can you add some color on this from API/user experience point of view?

**Comment by howardjohn** [comment] 2019-03-04 23:23
Why does a Sidecar resource require `istio-system` in the egress?

**Comment by nrjpoddar** [comment] 2019-03-05 00:44
The sidecars need to talk to istio-telemetry, istio-policy & istio-pilot in the istio-system namespace, based on our testing if you add a Sidecar resource with egress rules which doesn't contain istio-system, you end up blocking the traffic.

**Comment by nrjpoddar** [comment] 2019-03-05 21:36
Based on suggestion from @esnible ran the following test:

* Validated if `istioctl` rejects Sidecar config which doesn't have `istio-system` in egress.
  - Used `istioctl` (both `istioctl create -f` and `istioctl validate -f`) in [istio 1.1.0-rc0](https://github.com/istio/istio/releases/tag/1.1.0-rc.0), I was able to apply the following YAML:
    ```yaml
      apiVersion: networking.istio.io/v1alpha3
      kind: Sidecar
      metadata:
        name: default
        namespace: bookinfo-1
      spec:
      egress:
        - hosts:
          - bookinfo-1/*
    ```
     and the resource was successfully created without any warning:
  - Using `istioctl` in [istio 1.1.0-rc2](https://github.com/istio/istio/releases/tag/1.1.0-rc.2) has the same behavior.

**Comment by esnible** [comment] 2019-03-05 23:17
@rshriram @mbanikazemi Need advice.  One way to solve this is to document that `istio-system` SHOULD be included in lists of egress hosts.  Another is to have kube-inject add it.  Another is to have the system always behave as if the istio-system is an egress without explicitly modeling it.  Which approach is preferred for 1.1?

**Comment by linsun** [comment] 2019-03-06 02:51
I would much prefer to have  istio-system auto configured as an egress without user explicitly modeling it.

cc @costinm @louiscryan @frankbu

**Comment by nrjpoddar** [comment] 2019-03-06 03:11
@linsun I agree in principle.

Although I'm assuming `istio-system` is a place holder for the namespace where istio control plane is deployed and we will support cases where `istio-mixer` pods might be a different namespace than `istio-pilot`.

**Comment by howardjohn** [comment] 2019-03-06 03:26
I think having istio-system a special case that's always included is not the best approach.
* There are valid reasons to not have istio-system (https://github.com/istio/istio/issues/11762 as one example - probably others as well)
* we shouldn't have any requirement for Istio to be installed in istio-system, and it won't be if we use Costins new installer

**Comment by nrjpoddar** [comment] 2019-03-14 15:56
@esnible is this going to handled via docs being more explicit? I was unaware that the maintainers had made that decision.

**Comment by frankbu** [comment] 2019-04-17 19:20
At a minimum, every sidecar resource currently needs to have at least a host like `- "istio-system/*"` as one of the egress hosts or the proxy just won't work. Seems that disabling egress to control plane components (pilot/etc.) is not something that should be configurable, because it's required for Istio to work.

Seems to me that a sidecar should only be configuring the application egress separate from the default system egress requirements. Otherwise this does seem like a terrible UX.

^^^ @rshriram WDYT?

**Comment by nrjpoddar** [comment] 2019-04-18 04:38
@frankbu totally agree with you. Doesn’t make much sense to force users to add the same egress rules in every Sidecar resource.

**Comment by rshriram** [comment] 2019-04-18 15:09
if you dont have policy or telemetry, then there is no reason to talk to control plane. Communication between pilot and envoy is already hardcoded in the bootstrap. That configuration is not controlled by the sidecar resource.

Also, istio-system is just a namespace. We cannot hard code it just like that. If I have a different telemetry service in a different namespace, then implicitly adding istio system creates more issues. In addition to automatically importing all the configurations in istio-system.

**Comment by frankbu** [comment] 2019-04-18 15:56
Ah, good to know it's only policy and telemetry, but since they are "system services" I still think it doesn't make much sense to allow a user configuration to interfere with their functioning. I agree that we should not hardcode or handle the `istio-system` namespace in any special way, but since Envoy needs to know where Mixer is, also configuring its namespace doesn't seem like a big stretch. How about something along these lines:

Add two more configuration values in the istio configmap, e.g.:
```
mixerCheckNamespace: {{ .Release.Namespace }}
mixerReportNamespace: {{ .Release.Namespace }}
```
next to the corresponding server config values:
https://github.com/istio/istio/blob/6c0e7fe23589eee40695812dad3dd80f20da4a6b/install/kubernetes/helm/istio/templates/configmap.yaml#L57

Then we can automatically add egress entries for `mixerCheckNamespace/mixerCheckServer` and  `mixerReportNamespace/mixerReportServer` in every sidecar.

**Comment by rshriram** [comment] 2019-04-18 16:13
if mixer is enabled.. and is running in kubernetes. Plus, mixer policy is going away real soon. Telemetry as well.

**Comment by frankbu** [comment] 2019-04-18 17:40
You lost me at `and is running in kubernetes.` If it's running outside of kubernetes, there would still need to be a ServiceEntry for it in some namespace, otherwise you can't manually configure the egress to it either. Right?

If I'm understanding you, the important consideration is that in the near future Envoy isn't going to need to communicate with mixer, anyway, so this is only a temporary problem. Do I have that right? If so, I agree that there's no point in fixing it, but instead we should document the temporary limitation with a clear warning in the Sidecar doc.

@rshriram Please confirm my understanding is correct.

**Comment by rshriram** [comment] 2019-04-18 17:46
Its going away in near future that this is just a temp issue. No point in adding special considerations for this in our code.

**Comment by linsun** [comment] 2019-04-23 13:50
folks, we also have this file...install/kubernetes/global-default-sidecar-scope.yaml, did you apply this file @nrjpoddar ?  This file currently defaults to allow communication to istio-telemetry or istio-policy.

If we feel users will install istio in non istio-system ns, we can update the hosts to 

    - "*/istio-telemetry.istio-system.svc.cluster.local"
    - "*/istio-policy.istio-system.svc.cluster.local"

for 1.2.

**Comment by howardjohn** [comment] 2019-04-23 13:53
Lin that still has Istio-system in the hostname

**Comment by frankbu** [comment] 2019-04-23 14:28
@linsun install/kubernetes/global-default-sidecar-scope.yaml doesn't help here. The default sidecar scope is not the problem. The problem is when users want to define their own sidecar, they need to add the policy and telemetry services to the egress in every sidecar they create, since they override the default egress. https://github.com/istio/api/pull/903 is the only solution for now.

**Comment by linsun** [comment] 2019-04-23 14:31
@frankbu yes, that is precisely where my question is - this may not be how the code works today but could we inherit the default sidecar scope and overwrite it with user's own sidecar scope for the namespace?

BTW, the mixer v2 won't land in v1.2 so this extra step could take a while.

**Comment by frankbu** [comment] 2019-04-23 15:03
Sidecar inheritance would be pretty complicated in general and a lot harder to implement then what I suggested above (https://github.com/istio/istio/issues/12237#issuecomment-484571607).

**Comment by linsun** [comment] 2019-04-23 15:50
agreed @frankbu sidecar inheritance is bigger than this and can be used for other purposes too.  I had envisioned (or dreamed?) we had this already with calling our default sidecar file global-default-sidecar-scope.yaml.

I think we need to decide if we should do something about this in 1.2 (ideally we should do something simple so user doesn't have to worry about control plane config in their app sidecar config), considering mixer v2 schedule.  My vote is to implement the simple solution you outlined for 1.2, especially if mixer v2 won't land in v1.3.

**Comment by nrjpoddar** [comment] 2019-04-23 15:59
@linsun I know about the defaults but as you all have been discussing without inheritance any new Sidecar resource overrides the defaults.

I don't see any harm in implementing what @frankbu has suggested. I understand that in 1.2 or 1.x we will change interfaces and this might not be a problem but providing poor user experience (possibly breaking) until that happens should not be an acceptable answer.

**Comment by frankbu** [comment] 2019-04-23 16:51
@nrjpoddar I tend to agree.

@rshriram, @howardjohn WDYT?

**Comment by frankbu** [comment] 2019-07-23 17:46
Fixed with doc warning in https://github.com/istio/api/pull/985

**Closed by frankbu** 2019-07-23 17:46 UTC
Labels: area/user experience, kind/docs
