### ISSUE TITLE
Multi-Cluster/Multi-Network - kind eastwest-gateways

### ISSUE THREAD

**Issue by mikala3** [istio/istio#31081] opened 2021-02-25 20:09 UTC
Im trying to get communication between two clusters. I'm using kubernetes kind and MetalLb on each cluster. 

Install Multi-Primary on different networks - https://istio.io/v1.8/docs/setup/install/multicluster/multi-primary_multi-network/

The guide above is the one i followed. Everything seems to be ok until the "verify the installation part", where i expect cluster1 to use the service in cluster2.

Identification of the istioctl proxy-config endpoint for the sleep pod in cluster1:
`istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld`

`10.244.2.3:5000                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local`

And when i call the helloworld service:

`while true; do kubectl exec --context="${CTX_CLUSTER1}" -n sample -c sleep     "$(kubectl get pod --context="${CTX_CLUSTER1}" -n sample -l \     app=sleep -o jsonpath='{.items[0].metadata.name}')"     -- curl -s helloworld.sample:5000/hello; done`

Hello version: v1, instance: helloworld-v1-776f57d5f6-lbnwh
Hello version: v1, instance: helloworld-v1-776f57d5f6-lbnwh
Hello version: v1, instance: helloworld-v1-776f57d5f6-lbnwh
Hello version: v1, instance: helloworld-v1-776f57d5f6-lbnwh
Hello version: v1, instance: helloworld-v1-776f57d5f6-lbnwh
Hello version: v1, instance: helloworld-v1-776f57d5f6-lbnwh
Hello version: v1, instance: helloworld-v1-776f57d5f6-lbnwh
Hello version: v1, instance: helloworld-v1-776f57d5f6-lbnwh

Here i was expected to get the a response from the service in cluster2 also. Any suggestion what i can try?

**Comment by stevenctl** [comment] 2021-02-26 18:45
Can you try the steps here and see if anything solves the problem: https://preliminary.istio.io/latest/docs/ops/diagnostic-tools/multicluster/

**Comment by mikala3** [comment] 2021-02-28 19:22
I'm not sure if i suppose to test the "Locality load balancing", the trust configuration is ok . However at this step from the link i see that something is wrong compared to my output:

`istioctl --context $CTX_CLUSTER1 proxy-config endpoint sleep-dd98b5f48-djwdw.sample | grep helloworld
10.0.5.11:5000                   HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.0.6.13:5000                   HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
`
The above is from the example.

From my terminal:

`istioctl --context $CTX_CLUSTER1 proxy-config endpoint sleep-854565cb79-8phxb.sample | grep helloworld
10.244.3.3:5000                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local`

I guess i should see the endpoints from both services here?

**Comment by stevenctl** [comment] 2021-03-01 17:03
You should see an endpoint for the Pod in cluster 1 and the gateway in cluster 2. This means the gateway might not have a LoadBalancer address.
 
You can check if it has an external IP by running `kubectl get services -n istio-system` against cluster 2. If that doesn't succeed, you'll need to check your MetalLB install, or find a way to customize your installation so that easy west gateway is a NodePort service.

**Comment by kstreee-furiosa** [comment] 2021-03-02 07:30
I have the same situation under different settings. In my case, 
1. on-prem cluster (no LB, NodePort and manually entered externalIP)
2. aws cluster (classic LB)
and multi cluster/multi network

When I check `istioctl proxy-config endpoint` on two clusters, AWS cluster works well, but on-prem cluster does not catch AWS's helloworld service. I checked everything on the below diagnostic on two clusters and looks fine to me. What should I check more for this issue?

> Can you try the steps here and see if anything solves the problem: https://preliminary.istio.io/latest/docs/ops/diagnostic-tools/multicluster/

**Comment by kstreee-furiosa** [comment] 2021-03-02 08:42
I resolved my issue through https://github.com/istio/istio/issues/29359#issuecomment-739258089
It turns out I mis-configured 'meshNetworks' fields, and after I confirmed meshNetwork configuration logs of the istiod, it works well.

**Comment by mikala3** [comment] 2021-03-02 18:22
> You should see an endpoint for the Pod in cluster 1 and the gateway in cluster 2. This means the gateway might not have a LoadBalancer address.
> 
> You can check if it has an external IP by running `kubectl get services -n istio-system` against cluster 2. If that doesn't succeed, you'll need to check your MetalLB install, or find a way to customize your installation so that easy west gateway is a NodePort service.

I have an external IP for cluster2:

`kubectl get services -n istio-system`

NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                                                      AGE
istio-eastwestgateway   LoadBalancer   10.96.194.215   172.18.255.2   15021:32376/TCP,15443:31620/TCP,15012:32033/TCP,15017:30317/TCP              103m
istio-ingressgateway    LoadBalancer   10.96.29.123    172.18.255.1   15021:32253/TCP,80:31131/TCP,443:31755/TCP,15012:31228/TCP,15443:31940/TCP   110m
istiod                  ClusterIP      10.96.98.32     <none>         15010/TCP,15012/TCP,443/TCP,15014/TCP                                        112m


I got this message when i install metallb on my cluster:

`kubectl apply -f - -n kube-system`
Warning: resource configmaps/kube-proxy is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.

**Comment by stevenctl** [comment] 2021-03-05 22:17
If you're running KinD, check that the kubeconfig in your remote secrets doesn't use 127.0.0.1 or localhost. Accessing the kubeapi server from within docker needs to use the container IP:

```
# Kind currently supports getting a kubeconfig for internal or external usage. To simplify our tests,
    # its much simpler if we have a single kubeconfig that can be used internally and externally.
    # To do this, we can replace the server with the IP address of the docker container
    # https://github.com/kubernetes-sigs/kind/issues/1558 tracks this upstream
    CONTAINER_IP=$(docker inspect "${CLUSTER_NAME}-control-plane" --format "{{ .NetworkSettings.Networks.kind.IPAddress }}")
    kind get kubeconfig --name "${CLUSTER_NAME}" --internal | \
      sed "s/${CLUSTER_NAME}-control-plane/${CONTAINER_IP}/g" > "${CLUSTER_KUBECONFIG}"
```

**Comment by mikala3** [comment] 2021-03-08 15:24
> If you're running KinD, check that the kubeconfig in your remote secrets doesn't use 127.0.0.1 or localhost. Accessing the kubeapi server from within docker needs to use the container IP:
> 
> ```
> # Kind currently supports getting a kubeconfig for internal or external usage. To simplify our tests,
>     # its much simpler if we have a single kubeconfig that can be used internally and externally.
>     # To do this, we can replace the server with the IP address of the docker container
>     # https://github.com/kubernetes-sigs/kind/issues/1558 tracks this upstream
>     CONTAINER_IP=$(docker inspect "${CLUSTER_NAME}-control-plane" --format "{{ .NetworkSettings.Networks.kind.IPAddress }}")
>     kind get kubeconfig --name "${CLUSTER_NAME}" --internal | \
>       sed "s/${CLUSTER_NAME}-control-plane/${CONTAINER_IP}/g" > "${CLUSTER_KUBECONFIG}"
> ```

I'm not sure about the last part "> "${CLUSTER_KUBECONFIG}", what should i fill in there?

When i run following command:
`    CONTAINER_IP=$(docker inspect "${CLUSTER_NAME}-control-plane" --format "{{ .NetworkSettings.Networks.kind.IPAddress }}")
    kind get kubeconfig --name "${CLUSTER_NAME}" --internal | \
      sed "s/${CLUSTER_NAME}-control-plane/${CONTAINER_IP}/g"`

I get the following, where the ip is the for the container:

`    server: https://172.18.0.2:6443
  name: kind-cluster1
contexts:
- context:
    cluster: kind-cluster1
    user: kind-cluster1
  name: kind-cluster1
current-context: kind-cluster1
kind: Config
preferences: {}
users:
- name: kind-cluster1
`

**Comment by mikala3** [comment] 2021-03-08 15:49
and when i run "kubectl config view":

`apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:35553
  name: kind-cluster1
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:35229
  name: kind-cluster2
contexts:
- context:
    cluster: kind-cluster1
    user: kind-cluster1
  name: kind-cluster1
- context:
    cluster: kind-cluster2
    user: kind-cluster2
  name: kind-cluster2
current-context: kind-cluster1
kind: Config
preferences: {}
users:
- name: kind-cluster1
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: kind-cluster2
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
`

**Comment by mikala3** [comment] 2021-03-09 18:25
I did try with istio-1.6, https://istio.io/v1.6/docs/setup/install/multicluster/shared/ and at this step it is failing:

`$ istioctl install -f istio-remote0-cluster.yaml --context ${REMOTE_CLUSTER_CTX}`

How can i verify that my external IP is working on the istio-ingressgateway? After installing metallb on my cluster i get the external IP.

**Comment by stevenctl** [comment] 2021-03-09 20:03
The script I pasted is an excerpt of what we use for test setup. If your kubeconfig has the docker IPs, you will need to re-create the remote secrets in the cluster. Check your istiod logs to make sure the clusters can actually reach eachother.

**Comment by mikala3** [comment] 2021-03-09 22:11
I already tried that. But the log looks the same. I did theese steps:

`$ istioctl x create-remote-secret \
  --context="${CTX_CLUSTER1}" \
  --name=cluster1 | \
  kubectl apply -f - --context="${CTX_CLUSTER2}"`

`istioctl x create-remote-secret \
  --context="${CTX_CLUSTER2}" \
  --name=cluster2 | \
  kubectl apply -f - --context="${CTX_CLUSTER1}"
`

**Comment by stevenctl** [comment] 2021-03-09 22:16
Did you restart istiod afterwards?

**Comment by mikala3** [comment] 2021-03-09 22:26
Yes, like this:

`kubectl -n istio-system rollout restart deploy
deployment.apps/istio-eastwestgateway restarted
deployment.apps/istio-ingressgateway restarted
deployment.apps/istiod restarted
`

**Comment by stevenctl** [comment] 2021-03-09 22:44
Hmm.. the kubeconfig istioctl is reading must not have the correct `Server` field since you're seeing `dial tcp 127.0.0.1:39587`.

**Comment by mikala3** [comment] 2021-03-09 23:01
Not sure where i can find that kubeconfig for istioctl. But i will give it a try.

**Comment by mikala3** [comment] 2021-03-09 23:10
`apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:44499
  name: kind-cluster1
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:39587
  name: kind-cluster2
contexts:
- context:
    cluster: kind-cluster1
    user: kind-cluster1
  name: kind-cluster1
- context:
    cluster: kind-cluster2
    user: kind-cluster2
  name: kind-cluster2
current-context: kind-cluster1
kind: Config
preferences: {}
users:
- name: kind-cluster1
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: kind-cluster2
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
`

well, i posted this before.

**Comment by stevenctl** [comment] 2021-03-09 23:25
In https://github.com/istio/istio/issues/31081#issuecomment-792829449 you showed you could generate a new kubeconfig, where the server had a docker IP (172 instead of 127.0.0.1).

You need to use that kubeconfig with istioctl (`--kubeconfig` parameter, or edit your main kubeconfig).

**Comment by mikala3** [comment] 2021-03-09 23:36
Ok im not sure how i can apply that config with istioctl --kubeconfig. But here is my main kubeconfig:

`    server: https://127.0.0.1:44499
  name: kind-cluster1
- cluster:
    certificate-authority-data:  (--------------
------------------------------
I DELETE SOME HERE FOR SIMPLICITY
---------------------------
    server: https://127.0.0.1:39587
  name: kind-cluster2
contexts:
- context:
    cluster: kind-cluster1
    user: kind-cluster1
  name: kind-cluster1
- context:
    cluster: kind-cluster2
    user: kind-cluster2
  name: kind-cluster2
current-context: kind-cluster1
kind: Config
preferences: {}
users:
- name: kind-cluster1
`
So i should use the IP with 172 here at kind-cluster1 from #31081?

**Comment by stevenctl** [comment] 2021-03-09 23:37
Right.

**Comment by mikala3** [comment] 2021-03-09 23:43
The log looks the same about the dial 127... I did restart the istiod, is that enough?

**Comment by mikala3** [comment] 2021-03-10 00:02
istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld (from cluster2)

```
10.244.0.13:5000                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
172.19.255.201:15443             HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```

This is new also, before i did not see 172.19.255.201:15443 which is the eastwest-ingress in cluster1

**Comment by stevenctl** [comment] 2021-03-10 00:21
Double check that injection is enabled for pods in both clusters, and that you've configured a common root of trust. At this point it seems like you're not dealing with KinD specific issues, so I'd like to close this issue. I'd be happy to help you troubleshooting, please reach out to me on the istio slack.

**Closed by stevenctl** 2021-03-10 00:21 UTC

**Comment by ZeChArtiahSaher** [comment] 2021-04-08 17:32
I found one of the ways to solve the dialing issue is with providing kubernetes api ip directly: ```istioctl x create-remote-secret --context=... --name=... --server=https://docker-ip:6443``` which you can get with `docker inpect kind`

And even better is that when I do: `istioctl -n sample --context=${CTX_CLUSTER2} proxy-config endpoint "$(kubectl get pod --context="${CTX_CLUSTER2}" -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld`
I get:
```
10.244.0.9:5000                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
172.23.0.21:15443                HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```
Assuming that second ip being eastwest's gateway ip with tls port is correct.

Still however, when I send request from sample app, it only ever sends requests to local pod.

**Comment by ZeChArtiahSaher** [comment] 2021-04-08 17:56
I found one of the ways to solve the dialing issue is with providing kubernetes api ip directly: ```istioctl x create-remote-secret --context=... --name=... --server=https://IP:6443``` which you can get with `docker inpect kind`

Also after adding certs if it's best to literally restart everything (if you are not paying attention to order or operations)
