### ISSUE TITLE
unknown flag: --dnsRefreshRate

### ISSUE THREAD

**Issue by tibetsam** [istio/istio#14208] opened 2019-05-17 14:45 UTC
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
after installed master-latest-daily istio images, bookinfo pod can't be brought up.
that's bcz of istio-proxy is not coming up.

root@mastermint:~/go/src/istio.io/istio# kb logs productpage-v1-7c8b44b5c5-b4vlz istio-proxy
2019-05-17T12:33:16.912504Z     error   unknown flag: --dnsRefreshRate

**Expected behavior**
shouldn't have below conflict in the code.

pilot/cmd/pilot-agent/main.go:
envoyProxy := envoy.NewProxy(proxyConfig, role.ServiceNode(), proxyLogLevel, proxyComponentLogLevel, pilotSAN, role.IPAddre
    sses, dnsRefreshRate)

install/kubernetes/helm/istio/files/injection-template.yaml:
 - --dnsRefreshRate
 - {{ .Values.global.proxy.dnsRefreshRate }}
**Steps to reproduce the bug**
install istio, enable auto-inject and install bookinfo

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
root@mastermint:~/go/src/istio.io/istio# istioctl version
client version: unknown
citadel version: master-20190510-09-16
galley version: master-20190510-09-16
ingressgateway version: master-20190510-09-16
pilot version: master-20190510-09-16
policy version: master-20190510-09-16
sidecar-injector version: master-20190510-09-16
telemetry version: master-20190510-09-16
root@mastermint:~/go/src/istio.io/istio# kb version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**
helm install
**Environment where bug was observed (cloud vendor, OS, etc)**
Linux mastermint 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Affected product area (please put an X in all that apply)**

[x ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment] 2019-05-17 15:05
Fixed in https://github.com/istio/istio/pull/14176
Although the real root cause is https://github.com/istio/istio/issues/14182 -- the daily builds haven't been building so they got out of sync with the installer

**Comment by tibetsam** [comment] 2019-05-17 15:14
@howardjohn great to know. but why i can't find any existing issue which subject includes "dnsRefreshRate"

**Comment by howardjohn** [comment] 2019-05-17 15:20
The new flag got added yesterday

**Comment by howardjohn** [comment] 2019-05-17 15:25
By the way, we don't support/guarantee to be stable installing straight from source at all. If you want stable releases please install from https://github.com/istio/istio/releases.

If you want latest daily builds: https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-latest-daily/. Also not guaranteed to be stable but we appreciate bug reports from them

**Comment by howardjohn** [comment] 2019-05-22 16:59
This is fixed now that master is updated. We may or may not merge https://github.com/istio/istio/pull/14176 which would make this never happen, but at least now unless you go out of your way to get a mismatched proxy image you won't run into this

**Closed by howardjohn** 2019-05-22 16:59 UTC
