### ISSUE TITLE
istioctl delete or replace got error

### ISSUE THREAD

**Issue by janevalleye2e** [istio/istio#4215] opened 2018-03-12 21:45 UTC
1. **Error on istioctl delete**
`istioctl delete -f samples/bookinfo/route-rule-all-v1.yaml`
```
Error: 4 errors occurred:
* cannot delete route-rule//productpage-default: an empty namespace may not be set when a resource name is provided
* cannot delete route-rule//reviews-default: an empty namespace may not be set when a resource name is provided
* cannot delete route-rule//ratings-default: an empty namespace may not be set when a resource name is provided
* cannot delete route-rule//details-default: an empty namespace may not be set when a resource name is provided
```
2. **Error on istioctl replace**
`istioctl replace -f samples/bookinfo/route-rule-reviews-50-v3.yaml`
Error: revision is required

------------------------------------------------

**Workaround**

`istioctl replace -n default -f samples/bookinfo/route-rule-reviews-50-v3.yaml`
```
Updated config route-rule/default/reviews-default to revision 1364
```

`istioctl delete -n default -f samples/bookinfo/route-rule-reviews-50-v3.yaml`
```
Deleted config: route-rule/default/reviews-default
```
------------------------------------------------

`istioctl version`
```
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
```

**Comment by janevalleye2e** [comment] 2018-03-13 20:17
@kidiyoor

**Comment by kidiyoor** [comment] 2018-03-13 20:27
Looks similar to - https://github.com/istio/istio/issues/3545
Which was closed 26 days ago. We can except this to be fixed in next Istio release.

**Comment by SeriyBg** [comment] 2018-03-15 16:09
@kidiyoor the issue with the replace is not fixed, it is fixed only for delete command. However, the issue is similar. I will work on it and submit a PR.

**Comment by SeriyBg** [comment] 2018-03-15 16:28
Also this looks like a duplicate with #3669

**Comment by SeriyBg** [comment] 2018-03-15 16:41
Submitted the PR #4290

**Comment by SeriyBg** [comment] 2018-03-16 09:41
There is a similar issue with `istioctl get`:
Having a `routerule foo` in the `default` namespace and calling `istioctl get routeruel foo` will return `No resources found.`
Have fix this in the submitted PR as well.

**Comment by ayj** [comment] 2018-03-26 20:28
fixed by https://github.com/istio/istio/pull/4290

**Closed by ayj** 2018-03-26 20:28 UTC
