### ISSUE TITLE
istio 0.7.1 installing webhook error

### ISSUE THREAD

**Issue by truyet** [istio/istio#4933] opened 2018-04-13 12:02 UTC
I start minikube with:
minikube start --extra-config=apiserver.Authentication.PasswordFile.BasicAuthFile=~/minikube.csv \\n\t--extra-config=controller-manager.ClusterSigningCertFile="/var/lib/localkube/certs/ca.crt" \\n\t--extra-config=controller-manager.ClusterSigningKeyFile="/var/lib/localkube/certs/ca.key" \\n\t--extra-config=apiserver.Admission.PluginNames=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota \\n\t--kubernetes-version=v1.9.0

and install istio:
kubectl apply -f install/kubernetes/istio.yaml

install webhook:
./install/kubernetes/webhook-create-signed-cert.sh \
    --service istio-sidecar-injector \
    --namespace istio-system \
    --secret sidecar-injector-certs

and result:
creating certs in tmpdir /var/folders/2c/438nh3qn3zj_dyhp2t1kclzr0000gn/T/tmp.SOWheKL1
Generating RSA private key, 2048 bit long modulus
.....+++
.............+++
e is 65537 (0x10001)
certificatesigningrequest "istio-sidecar-injector.istio-system" deleted
certificatesigningrequest "istio-sidecar-injector.istio-system" created
NAME                                  AGE       REQUESTOR       CONDITION
istio-sidecar-injector.istio-system   1s        minikube-user   Pending
certificatesigningrequest "istio-sidecar-injector.istio-system" approved
ERROR: After approving csr istio-sidecar-injector.istio-system, the signed certificate did not appear on the resource. Giving up after 10 attempts.
See https://istio.io/docs/setup/kubernetes/sidecar-injection.html for more details on troubleshooting.

OS: macosx 10.13.4

**Comment by aneslozo** [comment] 2018-04-13 15:25
I have the same issue. I am using minikube v0.25.2 and k8s version 1.10.0.

**Comment by yusuoh** [comment] 2018-04-13 17:46
There a related issue of minikube that might be the cause.
https://github.com/kubernetes/kubernetes/issues/47911

**Comment by life1347** [comment] 2018-05-19 09:54
After trial and error all day
Following are the commands you need to launch minikube
** command for 1.9 and 1.10 are different

For  minikube v0.27.0, k8s 1.9.x
```
  minikube start \
	--extra-config=controller-manager.ClusterSigningCertFile="/var/lib/localkube/certs/ca.crt" \
	--extra-config=controller-manager.ClusterSigningKeyFile="/var/lib/localkube/certs/ca.key" \
	--extra-config=apiserver.Admission.PluginNames=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota \
	--kubernetes-version=v1.9.4
```

For  minikube v0.27.0, k8s 1.10.0
```
minikube start \
	--extra-config=controller-manager.cluster-signing-cert-file="/var/lib/localkube/certs/ca.crt" \
	--extra-config=controller-manager.cluster-signing-key-file="/var/lib/localkube/certs/ca.key" \
         --extra-config=apiserver.admission-control="NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota" \
         --kubernetes-version=v1.10.0
```

**Comment by ostromart** [comment] 2018-06-22 05:40
Seems to be minikube only, setting to P1.

**Comment by ostromart** [comment] 2018-06-26 18:11
Closing due to staleness, please reopen if still relevant.

**Closed by ostromart** 2018-06-26 18:11 UTC
Labels: area/environments
