### ISSUE TITLE
Galley improperly parses Pod yaml/json

### ISSUE THREAD

**Issue by nmittler** [istio/istio#10891] opened 2019-01-11 02:06 UTC
This is mostly an issue for the file-based input source. During testing for #10846, I noticed that the parsing of the following fields are problematic when running the [Galley conversion test](https://github.com/istio/istio/blob/master/tests/integration2/galley/conversion/conversion_test.go):

- IntOrString (used in the liveness/readiness Probe/Handler/HTTPGetAction/Port)
- Quantity (used in Container/Resources/Limits)

For the PR listed above, I had to hack the conversion test input a bit to get things working, but we should probably fix the parser for these cases.

**Comment by irisdingbj** [comment] 2019-01-14 01:18
@nmittler Is there a way for me to get details of the failure?  eg: a file example which caused the parsing fail? Then I can see how to fix it. thanks!

**Comment by nmittler** [comment] 2019-01-14 04:38
@irisdingbj just grab json for a real k8s pod ... should be easy to repro.

**Comment by ozevren** [comment] 2019-01-15 04:12
I think the problem is with certain fields. The original bug should have a
the field names

**Comment by irisdingbj** [comment] 2019-01-15 09:20
seems now jsonpb.UnmarshalString(js, pb) can not deal with inline struct.  It fails in https://github.com/istio/istio/blob/master/vendor/github.com/gogo/protobuf/jsonpb/jsonpb.go:L1005

I tried to use  json.Unmarshal([]byte(js), pb) directly , but using this way, it will skip all the inline struct..

@ozevren any suggestions for moving on?

**Comment by ozevren** [comment] 2019-01-16 20:58
Hey @irisdingbj, @nmittler has a PR in-flight that should take care of this:
https://github.com/istio/istio/pull/10995

**Comment by irisdingbj** [comment] 2019-01-21 08:30
@ozevren thanks, I will close this issue now.

**Closed** 2019-01-21 08:30 UTC
Labels: area/config
