### ISSUE TITLE
CRD quotas.config.istio.io hides k8s original quotas

### ISSUE THREAD

**Issue by supereagle** [istio/istio#10169] opened 2018-11-28 16:30 UTC
**Describe the bug**
K8s has resourcequotas (aka 'quota'), but it will be hidden by Istio CRD quotas.config.istio.io after install Istio. Then the pods with quota can not be created.

```
# kubectl -n bookinfo describe rs app-3813184607-app-v1-0-958bdd964
Name:           app-3813184607-app-v1-0-958bdd964
Namespace:      bookinfo
Controlled By:  Deployment/app-3813184607-app-v1-0
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Containers:
   c0:
    Image:      test.caicloudprivatetest.com/istio/examples-bookinfo-productpage-v1:1.8.0
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     500m
      memory:  512Mi
    Requests:
      cpu:     250m
      memory:  256Mi
    Environment:
      POD_NAMESPACE:     (v1:metadata.namespace)
      POD_NAME:          (v1:metadata.name)
      POD_IP:            (v1:status.podIP)
      NODE_NAME:         (v1:spec.nodeName)
      SERVICES_DOMAIN:  bookinfo.svc.cluster.local
    Mounts:             <none>
  Volumes:              <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  46s (x6 over 2m)   replicaset-controller  (combined from similar events): Error creating: pods "app-3813184607-app-v1-0-958bdd964-pwf9m" is forbidden: failed quota: bookinfo: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```

After install istio:

```
# kubectl -n bookinfo get quota bookinfo
Error from server (NotFound): quotas.config.istio.io "bookinfo" not found
```

After delete `quotas.config.istio.io` and restart apiserver:

```
# kubectl -n bookinfo get quota
NAME       AGE
bookinfo   1h
```

**Expected behavior**
K8s original quotas should not be hidden.

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**

```
istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by supereagle** [comment] 2018-12-17 15:22
It works to use full name. Only short name of `resourcequota` (quota) conflicts with Istio CRD `quotas.config.istio.io`.

**Comment by ozevren** [comment] 2019-02-22 23:59
Custom CRD per instance model is going away. The CRD is deprecated, and should go away in future releases.

**Comment by douglas-reid** [comment] 2019-06-06 17:15
This was a dupe of #5532 . Closing for the same reason.

**Closed by douglas-reid** 2019-06-06 17:15 UTC
Labels: area/config, area/policies and telemetry
