### ISSUE TITLE
Istioctl port-forward error

### ISSUE THREAD

**Issue by kkwekkeboom** [istio/istio#27317] opened 2020-09-15 12:39 UTC
**Bug description**
When upgrading from istio 1.6.5 to istio 1.7.1 (including istioctl) istioctl reports errors on some commands, e.g. on `version`. 

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
Have a control plane with istio 1.6.5 and installed using istioctl-1.6.5
```
curl -L https://istio.io/downloadIstio | sh -
${HOME}/.istioctl/bin/istioctl version
5 errors occurred:
	* error port-forewarding into cluster-local-gateway-77546bb4b4-6m4f6 : the server is currently unable to handle the request (get pods cluster-local-gateway-77546bb4b4-6m4f6:15014)
	* error port-forewarding into cluster-local-gateway-77546bb4b4-fjfbn : the server is currently unable to handle the request (get pods cluster-local-gateway-77546bb4b4-fjfbn:15014)
	* error port-forewarding into cluster-local-gateway-77546bb4b4-rm4zs : the server is currently unable to handle the request (get pods cluster-local-gateway-77546bb4b4-rm4zs:15014)
	* error port-forewarding into istiod-7c955fcbc9-bgnfz : the server is currently unable to handle the request (get pods istiod-7c955fcbc9-bgnfz:15014)
	* error port-forewarding into istiod-7c955fcbc9-mjmxc : the server is currently unable to handle the request (get pods istiod-7c955fcbc9-mjmxc:15014)

```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
The issue is with istioctl 1.7.1 and istio-1.7.1. 
```
${HOME}/.istioctl/bin/istioctl version --remote=false
1.7.1
```

With istioctl 1.6.0 there are no issues 
```
istioctl version
client version: 1.6.0
cluster-local-gateway version: 
cluster-local-gateway version: 
cluster-local-gateway version: 
pilot version: 1.7.1
pilot version: 1.7.1
data plane version: 1.7.1 (4 proxies)
```

**How was Istio installed?**
istioctl 

**Environment where bug was observed (cloud vendor, OS, etc)**
1.16.13-gke.401

**Comment by esnible** [comment] 2020-09-15 13:02
Earlier versions of Istio did the equivalent of `kubectl exec` to ask the control plane for the version.
Istio now uses the equivalent of `kubectl port-forward` for the same behavior.

The change was made to be more secure (letting cluster users contact ports on the control plane is safer than letting them run commands on the control plane) and because we are moving to a more secure communication pattern between _istioctl_ and the control plane for 1.8.

If you were on a cluster that gave you exec permission to pods in istio-system, but not port-forward permission, this could happen.  Check `kubectl get role -n istio-system` and `kubectl get clusterrole` to see if your cluster has this kind of security.

**Comment by kkwekkeboom** [comment] 2020-09-15 14:28
I myself am admin of my cluster. 

Can it be that the default istiod-istio-system role does not have permission to port-forward?

**Comment by howardjohn** [comment] 2020-09-15 15:43
`the server is currently unable to handle the request (get pods cluster-local-gateway-77546bb4b4-6m4f6:15014)`

Looks like we are trying to call port 15014 (Istiod port) on a gateway which seems wrong

**Comment by esnible** [comment] 2020-09-15 17:31
> Looks like we are trying to call port 15014 (Istiod port) on a gateway which seems wrong

That is really how _istioctl_ gets the control plane version.  The code is `result, err := c.proxyGet(pod.Name, pod.Namespace, "/version", 15014).DoRaw(ctx)`.

**Comment by howardjohn** [comment] 2020-09-15 17:35
`cluster-local-gateway` is not the control plane though, its part of the data plane

**Comment by kkwekkeboom** [comment] 2020-09-16 07:38
It's not restricted to the cluster-local-gateway (ticket updated)
```
5 errors occurred:
	* error port-forewarding into cluster-local-gateway-77546bb4b4-6m4f6 : the server is currently unable to handle the request (get pods cluster-local-gateway-77546bb4b4-6m4f6:15014)
	* error port-forewarding into cluster-local-gateway-77546bb4b4-fjfbn : the server is currently unable to handle the request (get pods cluster-local-gateway-77546bb4b4-fjfbn:15014)
	* error port-forewarding into cluster-local-gateway-77546bb4b4-rm4zs : the server is currently unable to handle the request (get pods cluster-local-gateway-77546bb4b4-rm4zs:15014)
	* error port-forewarding into istiod-7c955fcbc9-bgnfz : the server is currently unable to handle the request (get pods istiod-7c955fcbc9-bgnfz:15014)
	* error port-forewarding into istiod-7c955fcbc9-mjmxc : the server is currently unable to handle the request (get pods istiod-7c955fcbc9-mjmxc:15014)
```

**Comment by esnible** [comment] 2020-09-16 10:41
I can reproduce this.

This problem manifests when a user installs with an Ingress Gateway Deployment Pod with label `istio=<anything-other-than-ingressgateway>`.

You should not use `istio: cluster-local-gateway` in your Istio Operator.  I have a possible fix for 1.8, but for now just don't use `istio` labels on custom ingress gateways.

**Comment by howardjohn** [comment] 2020-09-16 14:58
@esnible sounds like the istiod is failing too though:

`	* error port-forewarding into istiod-7c955fcbc9-bgnfz : the server is currently unable to handle the request (get pods istiod-7c955fcbc9-bgnfz:15014)`

**Comment by casparrolfe** [comment] 2020-09-16 15:33
Unsure if its related, but we are seeing something similar with an install of 1.7.1

```
istioctl version

6 errors occurred:
	* error port-forewarding into istio-policy-6f7cc759bd-5d2tl : an error on the server ("unknown") has prevented the request from succeeding (get pods istio-policy-6f7cc759bd-5d2tl:15014)
	* error port-forewarding into istio-policy-6f7cc759bd-lcmtt : an error on the server ("unknown") has prevented the request from succeeding (get pods istio-policy-6f7cc759bd-lcmtt:15014)
	* error port-forewarding into istio-telemetry-686669b49c-dtvxh : an error on the server ("unknown") has prevented the request from succeeding (get pods istio-telemetry-686669b49c-dtvxh:15014)
	* error port-forewarding into istio-telemetry-686669b49c-v8scb : an error on the server ("unknown") has prevented the request from succeeding (get pods istio-telemetry-686669b49c-v8scb:15014)
	* error port-forewarding into istiod-6d5d45d9f6-s2cs7 : an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-6d5d45d9f6-s2cs7:15014)
	* error port-forewarding into istiod-6d5d45d9f6-tlkm4 : an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-6d5d45d9f6-tlkm4:15014)


1.7.1
```

```
istioctl ps
Error: an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-6d5d45d9f6-s2cs7:8080)
```

I can provide any other information to help debug as its requested.

**Closed** 2020-09-16 15:39 UTC
Labels: area/environments, area/user experience
