### ISSUE TITLE
TestPostInstallControlPlaneVerification test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28863] opened 2020-11-13 16:39 UTC
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28852/integ-operator-controller-tests_istio/1327276301232377856

**Comment by howardjohn** [comment] 2020-11-13 16:39
cc @richardwxn

**Comment by howardjohn** [comment] 2020-11-14 00:49
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-117_istio_postsubmit/1327395823285178368
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-116_istio_postsubmit/1327335908151660544

**Comment by howardjohn** [comment] 2020-11-17 01:37
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1328188304503345152

@richardwxn can you take a look? This seems extremely flaky, I am worried there is a regerssion

**Comment by howardjohn** [comment] 2020-11-17 18:49
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28965/integ-operator-controller-tests_istio/1328766282153070592

**Comment by howardjohn** [comment] 2020-11-17 21:17
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28490/integ-operator-controller-tests_istio/1328757294015451136

**Comment by howardjohn** [comment] 2020-11-18 01:08
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28490/integ-operator-controller-tests_istio/1328809496054599680

**Comment by howardjohn** [comment] 2020-11-19 01:07
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29027/integ-operator-controller-tests_istio/1329224649644445696

**Comment by howardjohn** [comment] 2020-11-20 21:07
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29046/integ-operator-controller-tests_istio/1329829829163356160

**Comment by richardwxn** [comment] 2020-11-25 20:26
This test was recently added in https://github.com/istio/istio/pull/28255/files, I couldn't find any suspicious errors from the logs though and hard to reproduce locally, I am wondering whether this was because the resources were still being deleted from previous test. Can you please take a look? @su225

**Comment by su225** [comment] 2020-11-26 02:32
Sure. Let me take a look.

**Comment by su225** [comment] 2020-11-26 13:18
@richardwxn @howardjohn - They all are timeouts. In that test, we install Istio and verify control plane health. When installation times out (as seen in logs), it fails. Why would it time out so frequently? Is it observed for other tests involving istio installation through `istioctl`?

Also, I think it is better to start `TestPostInstallControlPlaneVerification` with a clean cluster - like uninstall, then remove `istio-system`, `istio-operator` and then do installation. I'll raise a PR for that.

**Comment by richardwxn** [comment] 2021-02-02 01:14
The postsubmit flakiness was resolved, closing the issue

**Closed** 2021-02-02 08:28 UTC
Labels: area/environments/operator, kind/test failure
