### ISSUE TITLE
1.1.2 - Cannot use wildcard in prefix hosts in ServiceEntry

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#13241] opened 2019-04-11 11:12 UTC
**Describe the bug**
Cannot use wildcard in prefix hosts in ServiceEntry

**Expected behavior**
In the documentation, you mention that the wildcard prefix is accepted, but it throws this error:
`* hosts must be FQDN if no endpoints are provided for resolution mode DNS`

In your code: 
https://github.com/istio/istio/blob/master/pilot/pkg/model/validation.go#L250
i see that you call **`validateDNS1123Labels `** function directly instead of calling **`ValidateWildcardDomain `** function

**Steps to reproduce the bug**
1. Create new serviceEntry:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-network
spec:
  hosts:
  - '*.hooks.slack.com'
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```
2. Run `kubectl apply -f ../egress-network.yaml`
3. You will get this error: 
`* hosts must be FQDN if no endpoints are provided for resolution mode DNS`

**Version**
istio version: 1.1.2
kubectl client version: v1.12.0
kubectl server version: v1.12.6-eks-d69f1b

**Installation**
- `kubectl apply -f install/kubernetes/helm/helm-service-account.yaml ;`
- `helm install --tls install/kubernetes/helm/istio-init --name istio-init --namespace istio-system ;`
`-helm install --tls install/kubernetes/helm/istio --name istio --namespace istio-system  --values install/kubernetes/helm/istio/values.yaml`

**Environment**
EKS

**Comment by 1hanymhajna** [comment] 2019-04-16 10:21
any news?

**Comment by chaudyg** [comment] 2019-07-20 10:21
+1

**Comment by caofb** [comment] 2019-08-07 08:17
+1

**Comment by kheraud** [comment] 2019-09-09 15:33
+1

**Comment by esauser** [comment] 2019-09-13 14:07
We are also experiencing this issue.  Is it fixed in the recently released 1.3?

@andraxylia @rlenglet

**Comment by howardjohn** [comment] 2019-09-29 03:32
This is working as intended. Please see the error message:

`* hosts must be FQDN if no endpoints are provided for resolution mode DNS`

You either need to not use DNS resolution, or provide a list of endpoints. DNS resolution type does dns resolution to get a set of endpoints.. we cannot do dns lookup for `*.foo.com`.

**Closed by howardjohn** 2019-09-29 03:32 UTC
Labels: area/networking, area/user experience, kind/customer issue

**Comment by Hronom** [comment] 2023-05-20 17:02
@howardjohn example here is misleading when https://istio.io/latest/docs/reference/config/networking/service-entry/
