### ISSUE TITLE
Error: Istio installation failed, incomplete or does not match "istio-new.yaml" - deployment "istio-ingressgateway" exceeded its progress deadline

### ISSUE THREAD

**Issue by nikhilbalekundargi** [istio/istio#22309] opened 2020-03-19 05:36 UTC
**Bug description**

**Expected behavior**
Istio should be installed without errorrs

**Steps to reproduce the bug**
istioctl manifest generate \
--set values.prometheus.enabled=true \
--set components.pilot.enabled=true \
--set components.base.enabled=true \
--set components.citadel.enabled=true \
--set components.galley.enabled=true \
--set components.policy.enabled=true \
--set components.sidecarInjector.enabled=true \
--set components.telemetry.enabled=true \
--set values.mixer.adapters.stackdriver.enabled=true \
--set values.gateways.enabled=true \
--set values.global.mtls.enabled=true \
--set values.gateways.istio-ingressgateway.enabled=true \
--set values.gateways.istio-ingressgateway.sds.enabled=true \
--set values.global.k8sIngress.enabled=true \
--set values.global.k8sIngress.enableHttps=true \
> istio-new.yaml

kubectl apply -f istio-new.yaml

istioctl verify-install -f istio-new.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
istioctl 

------------------------ 
kubectl get pods -n istio-system 

NAME                                      READY   STATUS    RESTARTS   AGE
istio-citadel-657c747d77-9ssjr            1/1     Running   0          30m
istio-galley-5d54bc88b8-pw97s             2/2     Running   0          30m
**istio-ingressgateway-598796f4d9-zm2sp     0/1**     Running   0          30m
istio-policy-b7678b6b6-2nprr              2/2     Running   0          29m
istio-sidecar-injector-66bd566876-9rdx6   1/1     Running   0          29m
istio-telemetry-597bbb79b6-9f5vm          2/2     Running   0          29m
istiod-7d9c7bdd6-st8lf                    1/1     Running   0          30m
prometheus-b47d8c58c-zwt8r                2/2     Running   0          6m52s

------------------------------------------------------------------
Logs from istio-proxy container from istio-ingressgateway pod -
info Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 9 successful, 0 rejected; lds updates: 0 successful, 8 rejected

Events -
containers with unready status: [istio-proxy]
Readiness probe failed: HTTP probe failed with statuscode: 503

**Comment by howardjohn** [comment] 2020-03-19 15:21
>  8 rejected

Paste the full logs from the gateway and istiod please, so we can see what was rejected

**Comment by anarcher** [comment] 2020-03-19 15:43
I think that I have the same problem with this issue. 

```
$istioctl15 version --remote 
client version: 1.5.0
ingressgateway version: 1.5.0
ingressgateway version: 1.4.5 <- ingressgateway 1.5.0 is not ready.. 
pilot version: 1.5.0
data plane version: 1.5.0 (3 proxies)
```

- `istiod`
```
2020-03-19T08:28:43.798395Z     warn    ads     ADS:LDS: ACK ERROR   121.121.212.232:36876 router~~istio-ingres
sgateway-5ddw6479ffd-5qsz4.istio-system~istio-system.svc.cluster.local-108 Internal:Error adding/updating listener(s) 0.0.0.0_443: Invalid path: /etc/certs/cert-chain.pem
```

- `ingressgateway` 
```
2020-03-19T08:00:25.627366Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cd
s updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2020-03-19T08:00:29.629236Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cd
s updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2020-03-19T08:01:13.626286Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cd
s updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
(infinitely repeated this logs) 
```

Unfortunately, I'm not familiar with Istio. 
IMHO, `Invalid path: /etc/certs/cert-chain.pem`  seems to be the cause of my issue. 
`istio.default` secret has `cert-chain.pem` and other pems. 
What do I do for debugging my issue? 
Thanks,

**Comment by nikhilbalekundargi** [comment] 2020-03-19 16:37
> > 8 rejected
> 
> Paste the full logs from the gateway and istiod please, so we can see what was rejected

[istiod-logs.txt](https://github.com/istio/istio/files/4355757/istiod-logs.txt)
[istio-ingressgateway-logs.txt](https://github.com/istio/istio/files/4355758/istio-ingressgateway-logs.txt)

**Comment by howardjohn** [comment] 2020-03-19 16:39
"2020-03-19T16:16:12.804303Z    warn    ads     ADS:LDS: ACK ERROR
10.2.1.6:35108
router~10.2.1.6~istio-ingressgateway-598796f4d9-db72h.istio-system~istio-system.svc.cluster.local-6
Internal:Error adding/updating listener(s) 0.0.0.0_443: Invalid path:
/etc/istio/ingressgateway-certs/tls.crt

You have some Gateway referencing /etc/istio/ingressgateway-certs/tls.crt
which isn't mounted

**Comment by nikhilbalekundargi** [comment] 2020-03-19 16:43
> etc/istio/ingressgateway-certs/tls.crt

Do i need to mount these? I believe this should be part of istio setup? isn't it?

**Comment by hanoisteve** [comment] 2020-03-24 10:44
How do you get the logs for Istiod?

**Comment by hanoisteve** [comment] 2020-03-24 11:04
Is there a work around or resolution for the issue shown above? Please clarify about exactly what needs to be mounted and how it should be done

**Comment by guyromb** [comment] 2020-04-02 13:02
I have the same issue.
For some reason, if I change values.global.k8sIngress.gatewayName to something different than ingressgateway e.g. k8s-ingressgateway it becomes green (and if I change it back to ingressgateway it is OK again).

For me it sometimes happens also with egress (Readiness probe returns 503)

**Comment by howardjohn** [comment] 2020-05-12 23:32
I see, yes this is actually a bug with `global.k8sIngress.enableHttps=true`. This has been fixed in #22227

**Closed by howardjohn** 2020-05-12 23:32 UTC
Labels: area/environments, area/environments/installer, kind/need more info, lifecycle/needs-triage
