### ISSUE TITLE
istioctl controlz dashboard UI shows errors in subpage

### ISSUE THREAD

**Issue by AsCat** [istio/istio#21959] opened 2020-03-07 09:41 UTC
**Bug description**
istioctl controlz dashboard UI shows error in subpage  'Process Info' and 'Version Info'

**Expected behavior**
display the correct debug info in 'Process Info' and 'Version Info' sub page

**Steps to reproduce the bug**
1. install the istio 1.5 release version
2. install the bookinfo demo
3. exec cmd: istioctl dashboard controlz istiod-<xxxxxx>.istio-system
4. open web browser and navigate to 'http://localhost:9876/', click the 'Process Info' or  'Version Info' sub menu
5. you will get error messge as below:
`template: base:28:18: executing "content" at <.User>: can't evaluate field User in type *version.BuildInfo`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.5.0
egressgateway version: 1.5.0
ingressgateway version: 1.5.0
pilot version: 36d71286472022e5d49cd8f404a86f163086b310-dirty
data plane version: 1.5.0 (9 proxies)

**How was Istio installed?**
follow the release 1.5 release doc with demo profile 

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 18.04

**Comment by AsCat** [comment] 2020-03-07 09:43
The fix PR is created [here](https://github.com/istio/pkg/pull/120)

**Comment by esnible** [comment] 2020-03-09 16:05
This is a duplicate of https://github.com/istio/istio/issues/21342

**Comment by AsCat** [comment] 2020-03-18 16:13
The PR is merged and this issue can be closed.

**Closed** 2020-03-19 07:39 UTC
Labels: area/user experience
