### ISSUE TITLE
istio ingress gateway segmentation fault

### ISSUE THREAD

**Issue by dontreboot** [istio/istio#19211] opened 2019-11-26 02:07 UTC
**Bug description**
I noticed frequent segmentation from Istio ingress gateway pods even though there is active traffic going through the gateway.
```
2019-11-26T01:30:14.160911Z	info	FLAG: --applicationPorts="[]"
2019-11-26T01:30:14.160933Z	info	FLAG: --binaryPath="/usr/local/bin/envoy"
2019-11-26T01:30:14.160938Z	info	FLAG: --concurrency="0"
2019-11-26T01:30:14.160941Z	info	FLAG: --configPath="/etc/istio/proxy"
2019-11-26T01:30:14.160946Z	info	FLAG: --connectTimeout="10s"
2019-11-26T01:30:14.160950Z	info	FLAG: --controlPlaneAuthPolicy="MUTUAL_TLS"
2019-11-26T01:30:14.160955Z	info	FLAG: --controlPlaneBootstrap="true"
2019-11-26T01:30:14.160958Z	info	FLAG: --customConfigFile=""
2019-11-26T01:30:14.160960Z	info	FLAG: --datadogAgentAddress=""
2019-11-26T01:30:14.160963Z	info	FLAG: --disableInternalTelemetry="false"
2019-11-26T01:30:14.160966Z	info	FLAG: --discoveryAddress="istio-pilot:15011"
2019-11-26T01:30:14.160968Z	info	FLAG: --dnsRefreshRate="300s"
2019-11-26T01:30:14.160972Z	info	FLAG: --domain="istio-system.svc.cluster.local"
2019-11-26T01:30:14.160974Z	info	FLAG: --drainDuration="45s"
2019-11-26T01:30:14.160977Z	info	FLAG: --envoyAccessLogService=""
2019-11-26T01:30:14.160979Z	info	FLAG: --envoyMetricsServiceAddress=""
2019-11-26T01:30:14.160982Z	info	FLAG: --help="false"
2019-11-26T01:30:14.160984Z	info	FLAG: --id=""
2019-11-26T01:30:14.160987Z	info	FLAG: --ip=""
2019-11-26T01:30:14.160989Z	info	FLAG: --lightstepAccessToken=""
2019-11-26T01:30:14.160991Z	info	FLAG: --lightstepAddress=""
2019-11-26T01:30:14.160994Z	info	FLAG: --lightstepCacertPath=""
2019-11-26T01:30:14.160997Z	info	FLAG: --lightstepSecure="false"
2019-11-26T01:30:14.161000Z	info	FLAG: --log_as_json="false"
2019-11-26T01:30:14.161003Z	info	FLAG: --log_caller=""
2019-11-26T01:30:14.161006Z	info	FLAG: --log_output_level="default:info"
2019-11-26T01:30:14.161008Z	info	FLAG: --log_rotate=""
2019-11-26T01:30:14.161011Z	info	FLAG: --log_rotate_max_age="30"
2019-11-26T01:30:14.161014Z	info	FLAG: --log_rotate_max_backups="1000"
2019-11-26T01:30:14.161016Z	info	FLAG: --log_rotate_max_size="104857600"
2019-11-26T01:30:14.161021Z	info	FLAG: --log_stacktrace_level="default:none"
2019-11-26T01:30:14.161029Z	info	FLAG: --log_target="[stdout]"
2019-11-26T01:30:14.161036Z	info	FLAG: --mixerIdentity=""
2019-11-26T01:30:14.161040Z	info	FLAG: --parentShutdownDuration="1m0s"
2019-11-26T01:30:14.161042Z	info	FLAG: --pilotIdentity=""
2019-11-26T01:30:14.161046Z	info	FLAG: --proxyAdminPort="15000"
2019-11-26T01:30:14.161048Z	info	FLAG: --proxyComponentLogLevel="misc:error"
2019-11-26T01:30:14.161051Z	info	FLAG: --proxyLogLevel="warning"
2019-11-26T01:30:14.161053Z	info	FLAG: --serviceCluster="istio-ingressgateway"
2019-11-26T01:30:14.161056Z	info	FLAG: --serviceregistry="Kubernetes"
2019-11-26T01:30:14.161058Z	info	FLAG: --statsdUdpAddress=""
2019-11-26T01:30:14.161060Z	info	FLAG: --statusPort="15020"
2019-11-26T01:30:14.161063Z	info	FLAG: --templateFile=""
2019-11-26T01:30:14.161065Z	info	FLAG: --trust-domain=""
2019-11-26T01:30:14.161067Z	info	FLAG: --zipkinAddress="zipkin:9411"
2019-11-26T01:30:14.161079Z	info	Version root@da309950-0184-11ea-81d4-9e75043cf248-docker.io/istio-1.3.5-9c4f3fa302ac85a70ec5b03049c6a66a5b626f7a-Clean
2019-11-26T01:30:14.161172Z	info	Obtained private IP [10.4.7.216]
2019-11-26T01:30:14.161209Z	info	Proxy role: &model.Proxy{ClusterID:"", Type:"router", IPAddresses:[]string{"10.4.7.216", "10.4.7.216"}, ID:"istio-ingressgateway-7bf4dcb8b5-rhvpw.istio-system", Locality:(*core.Locality)(nil), DNSDomain:"istio-system.svc.cluster.local", TrustDomain:"cluster.local", PilotIdentity:"", MixerIdentity:"", ConfigNamespace:"", Metadata:map[string]string{}, SidecarScope:(*model.SidecarScope)(nil), MergedGateway:(*model.MergedGateway)(nil), ServiceInstances:[]*model.ServiceInstance(nil), WorkloadLabels:labels.Collection(nil), IstioVersion:(*model.IstioVersion)(nil)}
2019-11-26T01:30:14.161219Z	info	PilotSAN []string{"spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account"}
2019-11-26T01:30:14.161592Z	info	Effective config: binaryPath: /usr/local/bin/envoy
configPath: /etc/istio/proxy
connectTimeout: 10s
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istio-pilot:15011
drainDuration: 45s
envoyAccessLogService: {}
envoyMetricsService: {}
parentShutdownDuration: 60s
proxyAdminPort: 15000
serviceCluster: istio-ingressgateway
statNameLength: 189
tracing:
  zipkin:
    address: zipkin:9411

2019-11-26T01:30:14.161619Z	info	waiting 1m0s for /var/run/sds/uds_path
2019-11-26T01:30:14.161642Z	info	PilotSAN []string{"spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account"}
2019-11-26T01:30:14.161722Z	info	Starting proxy agent
2019-11-26T01:30:14.161755Z	info	Opening status port 15020

2019-11-26T01:30:14.161886Z	info	watching /etc/certs for changes
2019-11-26T01:30:14.161893Z	info	Received new config, resetting budget
2019-11-26T01:30:14.161896Z	info	Reconciling retry (budget 10)
2019-11-26T01:30:14.161935Z	info	Epoch 0 starting
2019-11-26T01:30:15.172090Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.4.7.216~istio-ingressgateway-7bf4dcb8b5-rhvpw.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --allow-unknown-fields -l warning --component-log-level misc:error]
[2019-11-26 01:30:15.182][20][warning][config] [external/envoy/source/server/options_impl.cc:193] --allow-unknown-fields is deprecated, use --allow-un
known-static-fields instead.
[2019-11-26 01:30:15.201][20][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/c
onfig/grpc_stream.h:87] gRPC config stream closed: 14, no healthy upstream
[2019-11-26 01:30:15.201][20][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:50] Unable to establish new stream
2019-11-26T01:30:15.744022Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2019-11-26T01:30:17.744791Z     info    Envoy proxy is ready
[2019-11-26 01:35:20.436][20][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-11-26 01:40:20.687][20][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
2019-11-26T01:44:47.563777Z     info    watchFileEvents: "/etc/certs/..2019_11_26_01_44_47.316320464": CREATE
2019-11-26T01:44:47.563825Z     info    watchFileEvents: "/etc/certs/..2019_11_26_01_44_47.316320464": MODIFY|ATTRIB
2019-11-26T01:44:47.563834Z     info    watchFileEvents: "/etc/certs/..data_tmp": RENAME
2019-11-26T01:44:47.563924Z     info    watchFileEvents: "/etc/certs/..data": CREATE
2019-11-26T01:44:47.563956Z     info    watchFileEvents: "/etc/certs/..2019_11_26_01_30_12.378283367": DELETE
2019-11-26T01:44:57.563914Z     info    watchFileEvents: notifying
2019-11-26T01:44:57.564057Z     info    Received new config, resetting budget
2019-11-26T01:44:57.564069Z     info    Reconciling retry (budget 10)
2019-11-26T01:44:57.564092Z     info    Epoch 1 starting
2019-11-26T01:44:57.565035Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev1.json --restart-epoch 1 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.4.7.216~istio-ingressgateway-7bf4dcb8b5-rhvpw.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --allow-unknown-fields -l warning --component-log-level misc:error]
[2019-11-26 01:44:57.577][54][warning][config] [external/envoy/source/server/options_impl.cc:193] --allow-unknown-fields is deprecated, use --allow-unknown-static-fields instead.
[2019-11-26 01:44:57.582][20][warning][main] [external/envoy/source/server/server.cc:616] shutting down admin due to child startup
[2019-11-26 01:44:57.582][20][warning][main] [external/envoy/source/server/server.cc:622] terminating parent process
[2019-11-26 01:44:57.596][54][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, no healthy upstream
[2019-11-26 01:44:57.596][54][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:50] Unable to establish new stream
[2019-11-26 01:45:20.738][20][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-11-26 01:45:58.263][20][warning][main] [external/envoy/source/server/server.cc:504] caught SIGTERM
[2019-11-26 01:45:58.267][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Segmentation fault, suspect faulting address 0x4c5dba0
[2019-11-26 01:45:58.267][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-11-26 01:45:58.267][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #0: __restore_rt [0x7f279fcd1390]
[2019-11-26 01:45:58.274][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #1: Envoy::Config::GrpcMuxImpl::sendDiscoveryRequest() [0x1c34b09]
[2019-11-26 01:45:58.280][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #2: Envoy::Config::GrpcMuxImpl::GrpcMuxWatchImpl::~GrpcMuxWatchImpl() [0x1c36da7]
[2019-11-26 01:45:58.286][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #3: Envoy::Config::GrpcMuxImpl::GrpcMuxWatchImpl::~GrpcMuxWatchImpl() [0x1c36e3e]
[2019-11-26 01:45:58.292][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #4: Envoy::Config::GrpcSubscriptionImpl::~GrpcSubscriptionImpl() [0x1c2c69a]
[2019-11-26 01:45:58.297][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #5: Envoy::Secret::SdsApi::~SdsApi() [0x1acde1a]
[2019-11-26 01:45:58.303][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #6: Envoy::Extensions::TransportSockets::Tls::ContextConfigImpl::~ContextConfigImpl() [0x1a3a93d]
[2019-11-26 01:45:58.309][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #7: Envoy::Extensions::TransportSockets::Tls::ClientContextConfigImpl::~ClientContextConfigImpl() [0x1a3b983]
[2019-11-26 01:45:58.315][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #8: Envoy::Extensions::TransportSockets::Tls::ClientSslSocketFactory::~ClientSslSocketFactory() [0x1a37aa2]
[2019-11-26 01:45:58.321][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #9: Envoy::Upstream::ClusterInfoImpl::~ClusterInfoImpl() [0x1c148f3]
[2019-11-26 01:45:58.327][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #10: Envoy::Upstream::ClusterInfoImpl::~ClusterInfoImpl() [0x1c1494e]
[2019-11-26 01:45:58.332][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #11: Envoy::Upstream::HostDescriptionImpl::~HostDescriptionImpl() [0xcb8cf9]
[2019-11-26 01:45:58.338][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #12: Envoy::Upstream::HostImpl::~HostImpl() [0xcbfc47]
[2019-11-26 01:45:58.344][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #13: std::__1::__shared_ptr_pointer<>::__on_zero_shared() [0xcb9cf9]
[2019-11-26 01:45:58.350][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #14: Envoy::Upstream::HostSetImpl::~HostSetImpl() [0x18a24b6]
[2019-11-26 01:45:58.356][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #15: Envoy::Upstream::HostSetImpl::~HostSetImpl() [0x1c144fe]
[2019-11-26 01:45:58.362][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #16: Envoy::Upstream::PrioritySetImpl::~PrioritySetImpl() [0xcb662b]
[2019-11-26 01:45:58.367][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #17: Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::ClusterEntry::~ClusterEntry() [0x1aece3e]
[2019-11-26 01:45:58.373][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #18: Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::~ThreadLocalClusterManagerImpl() [0x1aea75d]
[2019-11-26 01:45:58.379][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #19: Envoy::ThreadLocal::InstanceImpl::shutdownThread() [0x1a679e9]
[2019-11-26 01:45:58.385][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #20: Envoy::Server::InstanceImpl::terminate() [0x1a70f31]
[2019-11-26 01:45:58.390][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #21: Envoy::Server::InstanceImpl::run() [0x1a75c41]
[2019-11-26 01:45:58.396][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #22: Envoy::MainCommonBase::run() [0xc74ac0]
[2019-11-26 01:45:58.402][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #23: main [0xc73c12]
[2019-11-26 01:45:58.402][20][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #24: __libc_start_main [0x7f279f916830]
2019-11-26T01:45:58.422140Z     warn    Epoch 0 terminated with an error: signal: segmentation fault (core dumped)
2019-11-26T01:45:58.422237Z     warn    Aborting epoch 1...
2019-11-26T01:45:58.422278Z     warn    Aborted all epochs
2019-11-26T01:45:58.422357Z     warn    Aborting epoch 1
2019-11-26T01:45:58.422627Z     info    Epoch 0: set retry delay to 200ms, budget to 9
2019-11-26T01:45:58.422683Z     info    Epoch 1 aborted
2019-11-26T01:45:58.622726Z     info    Reconciling retry (budget 9)
2019-11-26T01:45:58.622775Z     info    Epoch 0 starting
2019-11-26T01:45:58.623888Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.4.7.216~istio-ingressgateway-7bf4dcb8b5-rhvpw.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --allow-unknown-fields -l warning --component-log-level misc:error]
[2019-11-26 01:45:58.635][87][warning][config] [external/envoy/source/server/options_impl.cc:193] --allow-unknown-fields is deprecated, use --allow-unknown-static-fields instead.
[2019-11-26 01:45:58.655][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, no healthy upstream
[2019-11-26 01:45:58.655][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:50] Unable to establish new stream
[2019-11-26 01:50:59.189][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-11-26 01:51:35.808][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-11-26 01:51:47.012][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-11-26 01:56:47.178][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-11-26 02:01:47.583][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-11-26 02:06:47.831][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-11-26 02:11:48.050][87][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
2019-11-26T02:15:32.647825Z     info    watchFileEvents: "/etc/certs/..2019_11_26_02_15_32.270039766": CREATE
2019-11-26T02:15:32.647870Z     info    watchFileEvents: "/etc/certs/..2019_11_26_02_15_32.270039766": MODIFY|ATTRIB
2019-11-26T02:15:32.647878Z     info    watchFileEvents: "/etc/certs/..data_tmp": RENAME
2019-11-26T02:15:32.647915Z     info    watchFileEvents: "/etc/certs/..data": CREATE
2019-11-26T02:15:32.647932Z     info    watchFileEvents: "/etc/certs/..2019_11_26_01_44_47.316320464": DELETE
2019-11-26T02:15:42.647946Z     info    watchFileEvents: notifying
2019-11-26T02:15:42.648127Z     info    Received new config, resetting budget
2019-11-26T02:15:42.648139Z     info    Reconciling retry (budget 10)
2019-11-26T02:15:42.648155Z     info    Epoch 1 starting
2019-11-26T02:15:42.648921Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev1.json --restart-epoch 1 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.4.7.216~istio-ingressgateway-7bf4dcb8b5-rhvpw.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --allow-unknown-fields -l warning --component-log-level misc:error]
```

**Expected behavior**
No segmentation fault
**Steps to reproduce the bug**
see **How was Istio installed?**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
 21:41:40  ~  istioctl version --remote
client version: 1.3.3
citadel version: 1.3.5
galley version: 1.3.5
galley version: 1.3.5
ingressgateway version: 1.3.5
ingressgateway version: 1.3.5
ingressgateway-private version:
ingressgateway-private version:
ingressgateway-restricted version:
ingressgateway-restricted version:
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.3.5
policy version: 1.3.5
policy version: 1.3.5
sidecar-injector version: 1.3.5
sidecar-injector version: 1.3.5
telemetry version: 1.3.5
telemetry version: 1.3.5

 21:41:56  ~  kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
```
helm template install/kubernetes/helm/istio-init --name istio-init --set certmanager.enabled=true --namespace istio-system > 01-crd.yaml
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-sds-auth.yaml \
        --set certmanager.enabled=true \
        --set certmanager.replicaCount=2 \
        --set galley.replicaCount=2 \
        --set mixer.policy.autoscaleMin=2 \
        --set mixer.telemetry.autoscaleMin=2 \
        --set sidecarInjectorWebhook.replicaCount=2 \
        --set security.workloadCertTtl=1h \
        --set global.outboundTrafficPolicy.mode=REGISTRY_ONLY \
        --set grafana.enabled=true \
        --set gateways.istio-ingressgateway.loadBalancerSourceRanges="{54.213.100.75/32,10.4.0.0/14,10.50.0.0/16}" \
        --set gateways.istio-ingressgateway.serviceAnnotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
        > 02-istio-sds.yaml
kubectl apply -f 01-crd.yaml
kubectl apply -f 02-istio-sds.yaml
```
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS 1.14.7

**Comment by howardjohn** [comment] 2019-11-26 03:58
Am I missing something or is there no seg fault in your logs you added?

**Comment by dontreboot** [comment] 2019-11-26 16:11
> Am I missing something or is there no seg fault in your logs you added?

my mistake. I just updated my logs to include the seg fault part.

**Comment by dontreboot** [comment] 2019-12-04 19:29
any update on this issue?

**Comment by mandarjog** [comment] 2019-12-05 08:56
This is a known issue for a long time. https://github.com/istio/istio/issues/16597

It was put on the back burner because it happens when envoy has already started shutting down.

**Comment by dontreboot** [comment] 2019-12-05 17:45
> This is a known issue for a long time. #16597
> 
> It was put on the back burner because it happens when envoy has already started shutting down.

Does this mean there is no real impact with this segfault? It's just that there are lots of coredump files filling up disks.

**Comment by howardjohn** [comment] 2020-03-16 23:55
Close as dupe of https://github.com/istio/istio/issues/16597

**Closed by howardjohn** 2020-03-16 23:55 UTC
Labels: area/networking/envoy, lifecycle/needs-triage
