### ISSUE TITLE
Some incorrect warning in istio-proxy (istio0.8)

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#6099] opened 2018-06-08 06:49 UTC
Some incorrect warning in istio-proxy (istio0.8 )

**_Error is like below:_**
[2018-06-07 18:20:42.406][30][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Proto constraint validation failed (ListenerValidationError.Address: ["embedded message failed validation"] | caused by AddressValidationError.SocketAddress: ["embedded message failed validation"] | caused by SocketAddressValidationError.Address: ["value length must be at least " '\x01' " bytes"]): name: "tcp__4222"
address {
  socket_address {
    port_value: 4222
  }
}
filter_chains {
  filter_chain_match {
  }
  filters {
    name: "envoy.tcp_proxy"
    config {
      fields {
        key: "deprecated_v1"
        value {
          bool_value: true
        }
      }
      fields {
        key: "value"
        value {
          struct_value {
            fields {
              key: "route_config"
              value {

Our service entry is like:
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-natscluster
spec:
  hosts:
  - 172.240.2.5 # not used
  ports:
  - number: 4222 
    name: nats
    protocol: TCP 
  location: MESH_EXTERNAL
  resolution: STATIC 
  endpoints:
  - address: 172.240.2.5 
  - address: 172.240.2.241
  - address: 172.240.2.97

**Comment by frankbu** [comment] 2018-06-12 19:47
Can't reproduce. Are you sure you are using envoy v2?

**Comment by rlenglet** [comment] 2018-06-12 23:21
@frankbu Yes, this is envoy V2. Why did you close this issue?

**Comment by frankbu** [comment] 2018-06-13 13:49
Sorry, I hit the wrong button when I added my comment. Can you provide more details of your env and what exactly you did to observe the problem? I tried to create a ServiceEntry like the above one, and did not see an error.

**Comment by rlenglet** [comment] 2018-06-13 16:27
We just injected and deployed deployments. Nothing special.
This failure is sporadic. We have no reliable reproducer.

**Comment by andraxylia** [comment] 2018-06-13 21:28
@ostromart any idea?

**Comment by ostromart** [comment] 2018-06-13 23:43
I think the warning is valid. I haven't seen this issue specifically but have seen cases where updating routes causes virtual services to disappear for a couple of seconds. It doesn't disrupt traffic because the resulting listener is invalid and the update is rejected until a new correct one comes along. 
Would need to look more deeply in to kube client / cache code but haven't had time to get to this.

**Comment by rlenglet** [comment] 2018-06-14 04:03
In general, I would suggest validating all xDS resources in Pilot's xDS server before returning them to Envoy. That's a pretty low hanging fruit. And that would give us hints re: the root cause of such invalid resources.

**Comment by kyessenov** [comment] 2018-06-14 04:13
Complete agree @rlenglet . I added the entire validation code synthesizer to envoy APIs, and have no idea why we are still not using it.

**Comment by rlenglet** [comment] 2018-06-16 00:07
I'll give a shot at a PR to validate on the server side.

**Comment by andraxylia** [comment] 2018-06-16 00:28
thanks @rlenglet

**Comment by andraxylia** [comment] 2018-06-21 19:00
@rlenglet can you please join the Istio organization so I can assign the issue to you?

**Closed** 2018-06-21 19:00 UTC
Labels: area/networking, kind/customer issue

**Comment by rlenglet** [comment] 2018-06-21 19:53
@andraxylia sure, please invite me to the org. Anything I need to do on my side?

**Comment by andraxylia** [comment] 2018-06-21 20:08
@geeknoid can you please invite @rlenglet to istio org he contributed to Istio
