### ISSUE TITLE
Auto sidecar injection not work when using calico and jumbo frame

### ISSUE THREAD

**Issue by MikuZZZ** [istio/istio#25170] opened 2020-07-02 04:29 UTC
**Bug description**
The istio 1.6.4 is installed on a cluster on AWS EC2 created using Kops with calico networking and 8912 mtu. When I try to deploy an app to default namespace, the pod shows the following error.

Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istiod.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

After I change the mtu back to default. The error disappear.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The pod should be created without error.

**Steps to reproduce the bug**
1. Use Kops to deploy a cluster on AWS EC2 with calico networking and 8912 mtu
2. Install istio using `istioctl install`
3. create a deployment in default namespace

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.4

**How was Istio installed?**
`istioctl install`

**Environment where bug was observed (cloud vendor, OS, etc)**
K8s 1.18.3
Kops on AWS EC2

**Comment by howardjohn** [comment] 2020-07-29 23:58
Not an expert on "jumbo frame" but what makes this an Istio bug and not a bug in calico/kubernetes not supporting this? In other words, what would Istio need to change to support this? is it possible?

**Comment by howardjohn** [comment] 2020-10-22 15:22
Closing as we do not have more info and I believe this is a calico issue

**Closed by howardjohn** 2020-10-22 15:22 UTC
Labels: area/networking, lifecycle/needs-triage
