### ISSUE TITLE
High memory use for Galley

### ISSUE THREAD

**Issue by costinm** [istio/istio#11158] opened 2019-01-22 19:53 UTC
I've left a small-size test Istio cluster over the long weekend - Grafana and k8s showed ~16G in use for galley. The good news is that it was constant, not increasing. I did have some frequent config changes while I was setting up the cluster ( it had a pilot in a test namespace that was updating ingress at the same time with the one in istio-system, resulting in frequent config changes ) - but I fixed it.

After restarting galley - it went back to normal.

I suggest more tests for frequent changes are needed and some profiles to figure out where the memory is going and why it's not GC.

**Comment by costinm** [comment] 2019-01-22 19:54
[grafana_galley.pdf](https://github.com/istio/istio/files/2784373/grafana_galley.pdf)

**Comment by ozevren** [comment] 2019-01-22 20:16
This is most likely the same issue with https://github.com/istio/istio/issues/11041. That one is crash looping due to much faster accumulation of leaked go routines, this one is most likely holding onto the go-routines, which in turn hold on to the snapshot data.

@ayj is working on an isolated fix for the go-routine leak in the MCP Server right now. That should address both issues.

**Comment by costinm** [comment] 2019-01-22 22:23
Might be the same - but Pilot was not crash looping or reconnecting, it was quite stable. 

Either way - we need load tests for both client reconnections and high rate of change in k8s.

**Comment by hzxuzhonghu** [comment] 2019-01-23 06:16
I meet the same issue, deployed 1.1.-.snapshot.3 yesterday. but galley memory is 1.68G now.

**Comment by ayj** [comment] 2019-01-25 02:15
https://github.com/istio/istio/pull/11167 has been merged which should fix the goroutine leak. I've run a 24+ hour test in the scale cluster (w/400 services + config churn) in addition to scaling pilot replicas up and down between 10 and 100 to check for resource leaks in Galley. The memory usage has been hovering around few hundred MB. Restarting pods (mixer maybe?) could trigger this leak.

FWIW, each client connection requires 5 goroutines (similar to Pilot). One for the MCP specific logic and four for golang's net/grpc stack. The k8s CRD watches also add another ~500 goroutines. This number is proportional to the number of CRD/k8s types and should decrease over time when the legacy mixer CRD are removed.

**Comment by ayj** [comment] 2019-01-25 02:20
@hzxuzhonghu, can you confirm whether or not mixer/pilot pods have been restarted at all when you observed this problem? #11167 has been merged into the 1.1 release branch and may be worth testing. Additionally, if you can reproduce the problem, could you enable galley pprof profiling (add --enableProfilingflag) and capture pprof profiles for memory and goroutines? e.g.

```bash
GALLEY_POD=$(kubectl -n istio-system get pod -listio=galley --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}
kubectl -n istio-system port-forward ${GALLEY_POD} 9094 

curl -s http://localhost:9094/debug/pprof/goroutine?debug=2 > goroutines.txt
curl -s http://localhost:9094/debug/pprof/heap --out heap.out
```

**Comment by ayj** [comment] 2019-01-25 17:32
https://github.com/istio/istio/pull/10893 and https://github.com/istio/istio/pull/11167 should address the memory leaks.

Are those health check failure logs from the latest image / tip of release-1.1? That seems to indicate an issue with port reuse which I thought was fixed by https://github.com/istio/istio/pull/10339?

**Comment by hzxuzhonghu** [comment] 2019-01-26 01:34
I deployed `istio-release-1.1-20190124-15-51` yesterday, and until now, I do not find exception of galley.

**Comment by ayj** [comment] 2019-01-29 17:22
I no longer observe any increased memory usage with #10893 and #11167 running in one of our large scale test clusters over the last week.

As part of verifying #111167 I instrumented a client re-connect stress test to confirm no resources are leaked. Total goroutine cost per connected client is 5 (1 MCP + 4 for net/grpc stack), which is similar to pilot xDS per-client goroutine usage. 

For reference, the goroutine dump below is with 18 clients connected. 

5 goroutines per client (1 MCP plus 4 for golang net/grpc server). We have 55 CRDs and 4 built-in k8s types (service/pod/node/endpoint) accounts for most of the other goroutines. This number should go down once the legacy mixer CRDs are removed.

```
$ curl -s http://localhost:9094/debug/pprof/goroutine?debug=2 |grep ^"created by" | sort | uniq -c
      5 created by istio.io/istio/galley/cmd/galley/cmd.GetRootCmd.func2
      2 created by istio.io/istio/galley/pkg/crd/validation.RunValidation
      1 created by istio.io/istio/galley/pkg/crd/validation.(*Webhook).monitorWebhookChanges
      1 created by istio.io/istio/galley/pkg/crd/validation.(*Webhook).Run
      1 created by istio.io/istio/galley/pkg/meshconfig.NewCacheFromFile
      1 created by istio.io/istio/galley/pkg/runtime.(*Processor).Start
      1 created by istio.io/istio/galley/pkg/server.(*Server).Run
      1 created by istio.io/istio/galley/pkg/server.StartProfiling
      1 created by istio.io/istio/galley/pkg/server.StartSelfMonitoring
     55 created by istio.io/istio/galley/pkg/source/kube/dynamic.(*listener).start                                    # corresponds to non-built in types
      1 created by istio.io/istio/pilot/pkg/model.newJwksResolver
      1 created by istio.io/istio/pkg/cache.NewTTLWithCallback
      1 created by istio.io/istio/pkg/ctrlz.Run
      1 created by istio.io/istio/pkg/filewatcher.(*fsNotifyWatcher).Add
     18 created by istio.io/istio/pkg/mcp/server.(*Server).StreamAggregatedResources                               
      2 created by istio.io/istio/pkg/probe.(*controller).Start
      1 created by istio.io/istio/vendor/github.com/fsnotify/fsnotify.NewWatcher
      4 created by istio.io/istio/vendor/github.com/howeyc/fsnotify.NewWatcher
      1 created by istio.io/istio/vendor/golang.org/x/net/http2.(*Transport).newClientConn
     36 created by istio.io/istio/vendor/google.golang.org/grpc/internal/transport.newHTTP2Server   # 2x clients
     18 created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleRawConn                   # 1x clients
     18 created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1             # 1x clients
      1 created by istio.io/istio/vendor/go.opencensus.io/stats/view.init.0
    221 created by istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
     56 created by istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.poller.func1                           # 55 CRDs + one shared watch for built-in types?
     56 created by istio.io/istio/vendor/k8s.io/apimachinery/pkg/watch.NewStreamWatcher
     56 created by istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*controller).Run
     56 created by istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
      1 created by net/http.(*connReader).startBackgroundRead
      1 created by net/http.(*http2serverConn).serve
      4 created by net/http.(*Server).Serve
      2 created by net/http.(*Transport).dialConn
      1 created by os/signal.init.0
```

The picture below shows goroutines over time. The peaks correspond to scaling pilot to 100 replicas. The valleys correspond to scaling pilot down to 5 replicas. The extra 6 replicas are mixer. There is a baseline of around ~485 goroutines without any clients

![](https://user-images.githubusercontent.com/116378/51631864-b8a92800-1f02-11e9-926d-5fa5b73f32d2.png)

**Closed by ayj** 2019-01-29 17:22 UTC
Labels: area/config
