### ISSUE TITLE
Envoy proxy taking forever to start / Is pilot running? 1 CDC update received successfully

### ISSUE THREAD

**Issue by bnicholson85** [istio/istio#18228] opened 2019-10-23 15:46 UTC
**It is taking 60-90secs to become available due to delay in sidecar injection**
We deployed istio on our QA cluster, and we are facing slow problems with the sidecar proxy startup, in this cluster it always take more than 60 seconds for the proxy to be ready.
We are not using the GKE's istio, we deployed it using helm charts. 
We already change the namespace and the problem remains the same
We tested in other clusters (minikube and a new gke cluster just for tests) and we couldn't replicate the problem.
We think this issue might be related with the cluster size?  

Logs are attached below

**Expected behavior**
Envoy proxy comes right up

**Steps to reproduce the bug**
Deployed Istio via

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
GKE --> 1.13.7-gke.24 
istio - 1.3.1

**How was Istio installed?**
via helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Cloud - GKE

[helloworldv2.log](https://github.com/istio/istio/files/3763195/helloworldv2.log)
[istio-pilot.log](https://github.com/istio/istio/files/3763198/istio-pilot.log)

**Comment by howardjohn** [comment] 2019-10-23 16:48
Some details:
* Is every single pod taking a long time? Just helloworldv2? Do ingressgateways take the same long time?
* How big is the cluster?
* What is resource (cpu/memory) usage of Pilot and the proxies that are slow to start up

From the logs, it looks like helloworld connects at :21 and gets CDS req then pushes CDS, as seen in proxy logs, but no LDS. Later, at :23, we see a bunch of EDS pushes, then immediately after an LDS push.

Envoy startup sequence is build request clusters, then request endpoints for those cluster, then request listeners. So there are two possibilities:
* Envoy does not send EDS/LDS reqest until :23
* Pilot ignores the request for 2 minutes.

The easiest way to do this is to turn on debug logging on Pilot. Please use the controlz interface https://istio.io/docs/ops/troubleshooting/controlz/ to do this, since otherwise you would redeploy pilot and maybe lose some state that can help debug this. You are not the only one that has seen this so I would like to find the root cause of possible, since I have not been able to reproduce.

Once you turn on debug, start a pod and attach the logs for the pod + pilot. Specifically what I will be looking for are when Pilot gets the EDS/LDS requests

**Comment by bnicholson85** [comment] 2019-10-23 17:12
Hello, thanks for your response.  I'm working with our client on this to get the additional info and debug logs, here's what I already know though:

Details:
* It's every single pod, which has made scaling difficult and impossible to bring into production
* Currently, the QA cluster is 12 nodes n1-standard-16, with 265 pods in it.
* Will check on utilization of Pilot and proxies.

Thanks,

Bryan

**Comment by bnicholson85** [comment] 2019-10-24 17:01
Current cpu/memory usage reported by client - they believe that they have adjusted in the past though:    
          cpu: 10m
          memory: 100Mi

still working on debug logs

**Comment by bnicholson85** [comment] 2019-10-24 17:47
Here's the requested debug logging @howardjohn 

[istio-pilot-discovery.log](https://github.com/istio/istio/files/3768791/istio-pilot-discovery.log)
[helloworldv2 (1).log](https://github.com/istio/istio/files/3768792/helloworldv2.1.log)

**Comment by howardjohn** [comment] 2019-10-24 17:57
Thank you! Very helpful, I think with that we can start tracking down the root cause.

Just wondering, you mentioned this applies only to one cluster, any idea what the difference is? Were the other ones not the full scale? I will attempt to reproduce it so that could simplify things.

**Comment by howardjohn** [comment] 2019-10-24 17:57
I have seen this from some other users before as well, by the way, so this seems like a pretty high priority

**Comment by howardjohn** [comment] 2019-10-24 19:46
cc @lambdai

**Comment by howardjohn** [comment] 2019-10-24 19:56
Sequence of events:

* 31:33 CDS Req, Push, and ACK
* No activity at all in pilot logs, just GC
* 32:46 new, unrelated pod starts up (frontend-splitter) triggering incremental EDS inc to 5 connected endpoints. We then see 4 EDS inc pushes, to everything but the pod in question (helloworld2). All are ACKed. Not pushed to helloworld since it hasn't requested EDS yet?
* 32:48 first EDS REQ. Followed by 30 Req/Push pairs
* 32:49 Pushes done, get 30 EDS ACKs
* 32:49 Get first LDS req, Push, and ACK
* 32:49 Pod marked as ready

Open questions:
* Is pilot stuck and not processing requests, or does envoy not send eds requests?
* Why does a new pod startup cause the EDS REQ to come in (may be coincidence)
* Why is Envoy sending so many EDS requests instead of one? This is probably unrelated to this issue

**Comment by howardjohn** [comment] 2019-10-24 19:58
The first set of logs has the same sequence, except the first EDS push is not correlated to any other action, so maybe that was a coincidence.

Pilot has only 5 connections so its load is extremely low, and it sounds like Envoy load is minimal as well, so likely this is not a load issue.

**Comment by lambdai** [comment] 2019-10-24 21:30
helloworld-v2 envoy is reporting grpc config stream closed. It might explain why there is a config push stall.
I don't explain why it is 1 minute long.

```
2019-10-24T11:31:32.385955Z	info	watching /etc/certs for changes
2019-10-24T11:31:32.402296Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster helloworld.default --service-node sidecar~10.227.9.196~helloworld-v2-b659bf5fd-g9jpq.default~default.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --allow-unknown-fields -l warning --component-log-level misc:error --concurrency 2]
[2019-10-24 11:31:32.418][18][warning][config] [external/envoy/source/server/options_impl.cc:193] --allow-unknown-fields is deprecated, use --allow-unknown-static-fields instead.
[2019-10-24 11:31:32.439][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, no healthy upstream
[2019-10-24 11:31:32.439][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:50] Unable to establish new stream
```

**Comment by lambdai** [comment] 2019-10-24 21:34
I will investigate the reconnection at envoy. Hopefully I don't need to dive into the google grpc impl.
I also suspect pilot may wrongly assumess the envoy has the latest config while envoy didn't. 

It's unknown why there is a stream close.

**Comment by lambdai** [comment] 2019-10-24 21:38
in terms of spamming of EDS request and response:
I am working at the envoy to dedup request at best efforts. Honestly it's not fault: envoy should send EDS request when it need new EDS. 
I am exploring some low hanging fruit instead of implementing a Nagle's algorithm at XDS protocol

**Comment by fsequeira1** [comment] 2019-10-24 22:50
> Thank you! Very helpful, I think with that we can start tracking down the root cause.
> 
> Just wondering, you mentioned this applies only to one cluster, any idea what the difference is? Were the other ones not the full scale? I will attempt to reproduce it so that could simplify things.

We tried to replicate this issue with minikube and with a new gke cluster with less deployments and we couldn't replicate the slow start in none of these clusters (where envoy started in about two seconds).
Btw, if you need more logs or want to test any behavior just ask @howardjohn  @lambdai

**Comment by lambdai** [comment] 2019-10-25 07:04
I go through the code at envoy but I find nothing suspicious.
The worth notice thing is that envoy report no healthy upstream, which is pilot. But immediately (in 2s) envoy got the CDS update which means stream is established. Pilot push log timestamp also support this sequence (Assume times drift is small enough).

it's either envoy not sending EDS request, or pilot stop processing EDS request.
- Envoy is innocent since there is no reasonable event to resume the envoy request EDS 
- Pilot seems innocent as well since there is 2 seconds gap between the helloworldv2 eds push and others.

I am gonna add temporary code in istio/envoy, to inspect itself during CDS and EDS initialization. Hopefully we will have something in the future days

**Comment by bnicholson85** [comment] 2019-10-26 03:05
I am out of country for the next week, any additional details can be provided by @fsequeira1 .. Thanks for your help @lambdai @howardjohn !!!

**Comment by lambdai** [comment] 2019-10-26 08:16
Not root caused yet but it's an envoy issue.
I read the code and I think the EDS push storm, where consequent EDS request has 1 cluster vary, is not the expected behavior.

The culprit is likely the below.
```
[2019-10-15 20:21:47.441][23][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, no healthy upstream
[2019-10-15 20:21:47.441][23][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:50] Unable to establish new stream
```

**Comment by howardjohn** [comment] 2019-10-26 18:55
@lambdai I have seen the EDS push storm before, but I tried reproducing just now and was unable too, so it seems its not the normal behavior -- there must be something that triggers it

**Comment by ramaraochavali** [comment] 2019-10-27 12:48
There was a fix in Envoy that stopped sending too many EDS requests - https://github.com/envoyproxy/envoy/pull/7976 and corresponding issue https://github.com/envoyproxy/envoy/issues/7955. 1.3 may not have that fix - I have not verified to confirm though.
@howardjohn  Did you test this on master ?

**Comment by howardjohn** [comment] 2019-10-27 16:05
Yes I was testing on master

**Comment by lambdai** [comment] 2019-10-28 17:09
The easiest approach to recreate "no healthy upstream" is to delete the pilot. But the consequences are not the same.

@fsequeira1  To help us better understanding the scenario, could you turn the "config" component log level to "trace" in istio-proxy  during the istio-proxy starting?

One possible way is to change the cm/istio-sidecar-injector, replace `"componentLogLevel":""` by `"componentLogLevel":"config:trace,misc:error"` <- @howardjohn Does this operation sound good to you?

It should clearly show the connections logs between envoy and pilot, and the discovery requests

**Comment by fsequeira1** [comment] 2019-11-04 12:50
@lambdai I'm having some problems making this change, I've already changed the value in the cm/istio-sidecar-injector and apparently the value is not propagated to the istio-proxy. I've also tried to change the value directly as an argument in the helloworld-v2 deployment but it doesn't work since this value is received by the pilot-agent process and not the envoy one. I can try to install istio from scratch with the values.yaml changed but I might lose the pilot state

**Comment by lambdai** [comment] 2019-11-06 19:18
@howardjohn  Any suggestion on how to propagate `componentLogLevel`? The less breakage on the istio the better.

**Comment by howardjohn** [comment] 2019-11-06 19:21
Changes to injector should be picked up automatically but require restarting the pod wih the proxy so it is re-injected. If thats not working try restarting the sidecar injector pod and/or looking in sidecar injector pod for errors

**Comment by fsequeira1** [comment] 2019-11-06 19:41
Ok, I have some news, and none of them are good. Since I had this issue with changing the configuration I decided to reapply the changes once again modifying the helm directly to see if this would correct the issue. 
I've used this values:
```
logLevel: "trace"
componentLogLevel: "config:trace,misc:error,connection:debug"
```
This was the output and I've confirmed the configmap really changed.

`poddisruptionbudget.policy/istio-galley unchanged
poddisruptionbudget.policy/istio-ingressgateway unchanged
poddisruptionbudget.policy/istio-policy unchanged
poddisruptionbudget.policy/istio-telemetry unchanged
poddisruptionbudget.policy/istio-pilot unchanged
poddisruptionbudget.policy/istio-sidecar-injector unchanged
configmap/istio-galley-configuration unchanged
configmap/prometheus unchanged
configmap/istio-security-custom-resources unchanged
configmap/istio unchanged
configmap/istio-sidecar-injector configured
serviceaccount/istio-galley-service-account unchanged
serviceaccount/istio-ingressgateway-service-account unchanged
serviceaccount/istio-mixer-service-account unchanged
serviceaccount/istio-pilot-service-account unchanged
serviceaccount/prometheus unchanged
serviceaccount/istio-security-post-install-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-security-post-install-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-security-post-install-role-binding-istio-system unchanged
job.batch/istio-security-post-install-1.3.1 unchanged
serviceaccount/istio-citadel-service-account unchanged
serviceaccount/istio-sidecar-injector-service-account unchanged
serviceaccount/istio-multi unchanged
clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istio-mixer-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/prometheus-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istio-citadel-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istio-sidecar-injector-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istio-reader unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-galley-admin-role-binding-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-mixer-admin-role-binding-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-citadel-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-sidecar-injector-admin-role-binding-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-multi unchanged
role.rbac.authorization.k8s.io/istio-ingressgateway-sds unchanged
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds unchanged
service/istio-galley unchanged
service/istio-ingressgateway unchanged
service/istio-policy unchanged
service/istio-telemetry unchanged
service/istio-pilot unchanged
service/prometheus unchanged
service/istio-citadel unchanged
service/istio-sidecar-injector unchanged
deployment.apps/istio-galley configured
deployment.apps/istio-ingressgateway configured
deployment.apps/istio-policy configured
deployment.apps/istio-telemetry configured
deployment.apps/istio-pilot configured
deployment.apps/prometheus unchanged
deployment.apps/istio-citadel configured
deployment.apps/istio-sidecar-injector configured
horizontalpodautoscaler.autoscaling/istio-ingressgateway unchanged
horizontalpodautoscaler.autoscaling/istio-policy unchanged
horizontalpodautoscaler.autoscaling/istio-telemetry unchanged
horizontalpodautoscaler.autoscaling/istio-pilot unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector configured
attributemanifest.config.istio.io/istioproxy unchanged
attributemanifest.config.istio.io/kubernetes unchanged
instance.config.istio.io/requestcount unchanged
instance.config.istio.io/requestduration unchanged
instance.config.istio.io/requestsize unchanged
instance.config.istio.io/responsesize unchanged
instance.config.istio.io/tcpbytesent unchanged
instance.config.istio.io/tcpbytereceived unchanged
instance.config.istio.io/tcpconnectionsopened unchanged
instance.config.istio.io/tcpconnectionsclosed unchanged
handler.config.istio.io/prometheus unchanged
rule.config.istio.io/promhttp unchanged
rule.config.istio.io/promtcp unchanged
rule.config.istio.io/promtcpconnectionopen unchanged
rule.config.istio.io/promtcpconnectionclosed unchanged
handler.config.istio.io/kubernetesenv unchanged
rule.config.istio.io/kubeattrgenrulerule unchanged
rule.config.istio.io/tcpkubeattrgenrulerule unchanged
instance.config.istio.io/attributes unchanged
destinationrule.networking.istio.io/istio-policy unchanged
destinationrule.networking.istio.io/istio-telemetry unchanged
`
So I've deleted the sidecar-injector and the helloworld-v2 and nothing changed. Actually the output from shows that the log values are not received by the istio-proxy. 

`2019-11-06T19:26:04.144051Z	info	FLAG: --proxyComponentLogLevel="misc:error"`

After this I've decided to reapply the helm once again (why not, nothing seems to solve the issue). 
I've deleted the pilot, sidecar injector and the helloworld and the problem remains the same. :( 

Is there anyway to enter the istio-proxy container, kill the envoy process start the process once again with different arguments without getting the pod evicted?

**Comment by fsequeira1** [comment] 2019-11-08 15:46
I finally found a way to change the log level it's not pretty, but it worked:

```
kubectl get pods --selector=app=helloworld | awk '{ if (NR!=1) ; if($3=="Running"){print $1} }' | grep v2 | xargs -i kubectl delete pod {} ; kubectl get pods --selector=app=helloworld | awk '{ if (NR!=1) ; if($3=="Running"){print $1} }' | grep v2 | xargs -i kubectl exec {} -c istio-proxy -- curl -X POST 'localhost:15000/logging?level=debug' ; kubectl get pods --selector=app=helloworld | awk '{ if (NR!=1) ; if($3=="Running"){print $1} }' | grep v2 | xargs -i kubectl logs -f {} -c istio-proxy > ~/test-istio
``` 
I searched for the running pod, killed it, change the debugging level with `curl -X POST 'localhost:15000/logging?level=debug'` and sent the logs to a file. the only problem here is that I have enabled the debug logs to every component in envoy.
[test-istio.txt](https://github.com/istio/istio/files/3825166/test-istio.txt)

Since I was finally able to change the log level values I've decided to take a look into the arguments sent to both envoy and pilot-agent and there is definitely a problem here not sure if the problem comes from the template or the way the image is reading the values. 

![Screenshot from 2019-11-08 15-40-08](https://user-images.githubusercontent.com/8819291/68489089-4eb60100-023e-11ea-89c9-1175b0df2271.png)

@howardjohn @lambdai

**Comment by howardjohn** [comment] 2019-11-08 17:06
Relevant logs:
first CDS from pilot-agent: `2019-11-08T15:13:44.608879Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected`

Not until a minute later do we see this log from envoy:
```
[2019-11-08 15:14:58.469][19][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:123] cm init: initializing secondary clusters
2019-11-08T15:14:58.657452Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected
[2019-11-08 15:14:59.751][19][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:147] cm init: all clusters initialized
[2019-11-08 15:14:59.751][19][info][main] [external/envoy/source/server/server.cc:541] all clusters initialized. initializing init manager
```

We get thousands of logs like
```
[external/envoy/source/common/config/grpc_mux_subscription_impl.cc:61] gRPC config for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment accepted with 1 resources with version 2019-11-08T13:53:23Z/151
```

@lambdai should it be initializing endpoints 1 at a time?

**Comment by ramaraochavali** [comment] 2019-11-10 11:04
@howardjohn For EDS, the above log line indicates a top level `ClusterLoadAssignment` for a cluster that has set of `LocalityLbEndpoints` - so Envoy is actually initializing one cluster at time.

**Comment by howardjohn** [comment] 2019-11-11 21:43
This will be fixed in 1.4.0 releasing this week

**Comment by fsequeira1** [comment] 2019-11-25 15:48
@howardjohn I have updated istio to 1.4.0 and the problem remained the same.

**Comment by benceBortnyak** [comment] 2019-12-11 12:15
Same issues for me with 1.4.1 
I installed Istio with the rancher UI
[Logs](https://pastebin.com/Nd1T3TLF)

**Comment by howardjohn** [comment] 2019-12-11 16:26
@benceBortnyak that is not the same issue, and @fsequeira1 I suspect the same but please post logs.

This problem is only about getting a CDS update and NO LDS update because envoy/pilot are stuck. In the case above, you get neither, because you can't connect to pilot at all (see logs about failed to connect to config stream).

Assuming this is fixed in 1.4; if you see this again please open an issue with logs and ping me

**Closed by howardjohn** 2019-12-11 16:26 UTC
Labels: area/networking/envoy, area/perf and scalability, lifecycle/needs-triage

**Comment by bnicholson85** [comment] 2019-12-17 17:18
@howardjohn just to clarify, @fsequeira1 was the issue owner for this, I simply reported initially as they're one of my clients.  Apparently the issue hasn't been resolved?

**Comment by Janesee3** [comment] 2020-02-13 10:30
Hi, I'm also facing this issue.

I'm constantly getting these logs `info Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected`. 

I'm also seeing some of the Pilot connection error logs in between: 
```
[2019-10-24 11:31:32.439][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, no healthy upstream
[2019-10-24 11:31:32.439][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:50] Unable to establish new stream
```

I suppose this is related to the Pilot connectivity issue that @howardjohn was talking about above? How do we resolve this? For my case, it does not happen all the time, but it is frequent enough to cause pain. Thanks!

---

Installed Istio via Helm
Istio Version: 1.4.4
Using EKS on 1.14

**Comment by Jeskz0rd** [comment] 2020-04-11 18:21
I can confirm the same as @Janesee3 happening with Istio 1.4.6 (helm) on GKE!

```
[Envoy (Epoch 0)] [2020-04-11 17:48:37.057][17][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, no healthy upstream
[Envoy (Epoch 0)] [2020-04-11 17:48:37.057][17][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:54] Unable to establish new stream
2020-04-11T17:48:38.327200Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2020-04-11T17:48:40.646755Z     info    Envoy proxy is NOT ready: server is not live, current state is: INITIALIZING
2020-04-11T17:48:42.271240Z     info    Envoy proxy is ready
```

The difference for me is that the issue is consistent to initialise the `istio-proxy` sidecar. This causes some pods to fail since external resources cannot be accessed until the envoy sidecar gets ready.

**Comment by 1hanymhajna** [comment] 2020-08-31 10:35
the same in 1.4.7, it just starts happened recently
