### ISSUE TITLE
Istiod crash at TestTraffic/dns integ test

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#31231] opened 2021-03-04 03:00 UTC
Got a istiod crash at TestTraffic/dns test: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31226/integ-pilot-multicluster-tests_istio/1367299148813963264

Istiod log: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/31226/integ-pilot-multicluster-tests_istio/1367299148813963264/artifacts/pilot-28fc333159904893b36b9352f/TestTraffic/dns/_test_context/istio-state031270621/cross-network-primary/istiod-7d8df56c7-rw6lt_discovery.previous.log

**Comment by howardjohn** [comment] 2021-03-05 00:57
dupe of https://github.com/istio/istio/issues/31247 (you beat me though :slightly_smiling_face: )

**Closed by howardjohn** 2021-03-05 00:57 UTC
Labels: area/networking, kind/test failure
