### ISSUE TITLE
TestMultipartEvents is flaky

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12682] opened 2019-03-21 20:47 UTC
https://circleci.com/gh/istio/istio/360223?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
     --- PASS: TestMultipartEvents/Add/event_2 (0.00s)
    --- FAIL: TestMultipartEvents/Delete (0.00s)
        testing_t_support.go:22: 
            	/go/src/istio.io/istio/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x1ed
            istio.io/istio/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc00040e840, 0x186a960, 0xc0004add30, 0x0, 0x0, 0x0, 0x187d920)
            	/go/src/istio.io/istio/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xaf
            istio.io/istio/galley/pkg/source/fs_test.TestMultipartEvents.func2(0xc00051a500)
            	/go/src/istio.io/istio/galley/pkg/source/fs/source_test.go:468 +0x36f
            testing.tRunner(0xc00051a500, 0xc00040e700)
            	/usr/local/go/src/testing/testing.go:827 +0xbf
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:878 +0x353
            
            Expected
                <resource.Event>: {
                    Kind: 3,
                    Entry: {
                        Metadata: {
                            CreateTime: 0001-01-01T00:00:00Z,
                            Labels: nil,
                            Annotations: nil,
                        },
                        ID: {
                            Key: {
                                Collection: {
                                    string: "istio/config/v1alpha2/legacy/deniers",
                                },
                                FullName: {
                                    string: "some.mixer.denier",
                                },
                            },
                            Version: "v0",
                        },
                        Item: nil,
                    },
                }
            to equal
                <resource.Event>: {
                    Kind: 3,
                    Entry: {
                        Metadata: {
                            CreateTime: 0001-01-01T00:00:00Z,
                            Labels: nil,
                            Annotations: nil,
                        },
                        ID: {
                            Key: {
                                Collection: {
                                    string: "istio/policy/v1beta1/rules",
                                },
                                FullName: {
                                    string: "some.mixer.rule",
                                },
                            },
                            Version: "v0",
                        },
                        Item: nil,
                    },
                }
```

**Comment by nmittler** [comment] 2019-04-02 17:18
This no longer appears to be flakey on testgrid. Also not able to reproduce.  Closing for now.

**Closed by nmittler** 2019-04-02 17:18 UTC
Labels: area/config, kind/test failure
