### ISSUE TITLE
eureka_istio-pilot_1 Exit 255

### ISSUE THREAD

**Issue by zhuozl** [istio/istio#2433] opened 2018-01-05 03:11 UTC
istio-0.4.0

docker-compose -f install/eureka/istio.yaml ps 

              Name                             Command                             State                              Ports               

    eureka_etcd_1                      /usr/local/bin/etcd -adver ...     Up                                 0.0.0.0:2379->2379/tcp,          
                                                                                                         0.0.0.0:2380->2380/tcp,          
                                                                                                         0.0.0.0:4001->4001/tcp           
    eureka_eureka_1                    /tomcat/bin/catalina.sh run        Up                                 0.0.0.0:8082->8080/tcp           
    eureka_istio-apiserver_1           kube-apiserver --etcd-serv ...     Up                                 0.0.0.0:8080->8080/tcp           
    eureka_istio-pilot_1               /usr/local/bin/pilot-disco ...     Exit 255                                                            
    eureka_registrator_1               /bin/registrator -internal ...     Up                                                                  
    eureka_zipkin_1                    /bin/sh -c test -n "$STORA ...     Up                                 9410/tcp, 0.0.0.0:9411->9411/tcp 

docker logs -f eureka_istio-pilot_1:

    ERROR: logging before flag.Parse: E0105 03:07:16.707430       1 main.go:123] failed to create discovery 
    service: failed to connect to Kubernetes API. Error loading config file "/etc/istio/config/kubeconfig": 
    read /etc/istio/config/kubeconfig: is a directory

**Comment by markstgodard** [comment] 2018-01-06 18:43
I encountered the same issue w/ the consul docker-compose install:
https://istio.io/docs/setup/consul/quick-start.html

**Comment by markstgodard** [comment] 2018-01-06 20:14
To get pilot to talk to the api server, what I did locally was:

Change pilot to reference a file under kubeconfig mount:

```
    command: ["discovery", "-v", "2",
              "--registries", "Consul",
              "--consulserverURL", "http://consul:8500",
              "--kubeconfig", "/etc/istio/config/kubeconfig/config"
              ]
    volumes:
      - ./kubeconfig:/etc/istio/config/kubeconfig
```
and added a kubeconfig file (named config) under the kubeconfig dir,  and an entry for the istio server

i.e. snippet from config
```
- cluster:
    server: http://istio-apiserver:8080
  name: istio
```

Again I am not sure how it was intended to work, but just what I hacked around to get to work..

Would like to know if I missed something in the Install instructions or if there is something missing in docs:

https://istio.io/docs/setup/consul/quick-start.html

Cheers

**Comment by pparth** [comment] 2018-01-30 17:16
Same problem with eureka for me, in a Mac.

**Comment by GregHanson** [comment] 2018-02-22 18:40
There are probably two separate problems occurring here.  First is a missing kubeconfig file which is needed pilot to talk to the apiserver.  This issue can be resolved by switching to the most recent version of istio (0.5.1 or later) by following the steps here: https://istio.io/docs/setup/kubernetes/quick-start.html OR by creating the kubeconfig file https://github.com/istio/istio/blob/master/install/consul/kubeconfig in install/consul or install/eureka depending on your setup.

The second is a default port mismatch between the client (pilot-agent) and server (pilot-discovery) described here: https://github.com/istio/istio/issues/2788
You can make the changes describe in the linked issue or you can install a newer version of istio from the quick-start guide linked above

**Closed by GregHanson** 2018-02-22 18:40 UTC
Labels: area/environments, automated-release
