### ISSUE TITLE
Real Client-IP not visible in the envoy proxy

### ISSUE THREAD

**Issue by sidhlipu** [istio/istio#22197] opened 2020-03-15 18:45 UTC
**Bug description**
Real Client-IP not visible in the envoy proxy

istio-1.5.0

[ ] Networking
Enabled externalTrafficPolicy to Local is not respected.
kubectl get svc istio-ingressgateway -n istio-system -o yaml|grep externalTraffic
  externalTrafficPolicy: Local

**Expected behavior**
Real Client IP should be visible in the envoy proxy logs

**Steps to reproduce the bug**
Patch envoy to enable externalTrafficPolicy to Local.
1. kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'
2. Hit a service with sidecar injection true and verify the logs. The external loadbalancer IP is visible rather than the real-client ip.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (4 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"4f504dd9ee54a3621502518bc64f0df487587d12", GitTreeState:"clean", BuildDate:"2020-01-23T00:34:28Z", GoVersion:"go1.12.7 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using the document here.
https://istio.io/docs/setup/getting-started/#download

**Environment where bug was observed (cloud vendor, OS, etc)**
Oracle Cloud Infrastructure

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive
[istio-dump.tar.gz](https://github.com/istio/istio/files/4334850/istio-dump.tar.gz)
) by attaching
the dump file to this issue.

**Comment by sidhlipu** [comment] 2020-03-16 08:14
Can someone from @istio take a look please.

**Comment by DanielQujun** [comment] 2020-03-24 15:52
I think this depends on your LoadBlance, It might have done the SNAT. 

Maybe you can try tcpdump in your ingressgateway's namespace to identify the real client IP

**Comment by howardjohn** [comment] 2020-08-04 22:08
Duplicate of https://github.com/istio/istio/issues/21527

**Closed by howardjohn** 2020-08-04 22:08 UTC
Labels: lifecycle/needs-triage
