### ISSUE TITLE
gateways fail on XDS grpc connection when istiod installed in different namespace

### ISSUE THREAD

**Issue by patrickppeng** [istio/istio#29088] opened 2020-11-20 18:01 UTC
**Bug description**
Ingress/egress gateways fail to connect to XDS server due to incorrect discoveryAddress when istiod installed in different namespace

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
gateways should pick up the correct discoveryAddress for XDS server connection

**Steps to reproduce the bug**

Install istio with the istiooperator CR
- istio-operator chart installed in istio-operator namespace
- install istiod/pilot in istio-control namespace
- install ingressgateway and egressgateway in istio-system namespace

````
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: empty
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-control.svc:15012
  addonComponents:
    istiocoredns:
      enabled: false
  components:
    base:
      enabled: false
    cni:
      enabled: false
    istiodRemote:
      enabled: false
    egressGateways:
    - enabled: true
      namespace: istio-system
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      namespace: istio-system
      name: istio-ingressgateway
    pilot:
      enabled: true
      namespace: istio-control
  values:
    global:
      istioNamespace: istio-control
````

All the resources are created in expected namespace but the gateway pods cannot come up due to the XDS server connection failure.
````
[root@flex188-33 templates]# k get all -n istio-control
NAME                        READY   STATUS    RESTARTS   AGE
pod/istiod-fc74d554-55kkh   1/1     Running   0          57m

NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
service/istiod   ClusterIP   10.100.200.118   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP   57m

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/istiod   1/1     1            1           57m

NAME                              DESIRED   CURRENT   READY   AGE
replicaset.apps/istiod-fc74d554   1         1         1       57m
````
````
[root@flex188-33 templates]# k get all -n istio-system
NAME                                        READY   STATUS    RESTARTS   AGE
pod/istio-egressgateway-7584d78957-hdqmh    0/1     Running   0          59m
pod/istio-ingressgateway-544cbb6698-kxmd7   0/1     Running   0          59m

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                    AGE
service/istio-egressgateway    ClusterIP   10.100.200.113   <none>        80/TCP,443/TCP,15443/TCP   59m
service/istio-ingressgateway   ClusterIP   10.100.200.170   <none>        15021/TCP,80/TCP,443/TCP   59m

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/istio-egressgateway    0/1     1            0           59m
deployment.apps/istio-ingressgateway   0/1     1            0           59m

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/istio-egressgateway-7584d78957    1         1         0       59m
replicaset.apps/istio-ingressgateway-544cbb6698   1         1         0       59m
````
Here is the ingressgateway logs (egressgateway has similar logs with same error).
- the "discoveryAddress" is pointing to incorrect namespace "discoveryAddress: istiod.istio-system.svc:15012"
- SAN string has incorrect host: PilotSAN []string{"istiod.istio-system.svc"}
- CA address is correct and gateway was able to get certs : sa.serverOptions.CAEndpoint == istiod.istio-control.svc:15012 Citadel

````
2020-11-20T16:25:40.027082Z     info    FLAG: --concurrency="0"
2020-11-20T16:25:40.027127Z     info    FLAG: --domain="istio-system.svc.cluster.local"
2020-11-20T16:25:40.027134Z     info    FLAG: --help="false"
2020-11-20T16:25:40.027138Z     info    FLAG: --log_as_json="false"
2020-11-20T16:25:40.027142Z     info    FLAG: --log_caller=""
2020-11-20T16:25:40.027146Z     info    FLAG: --log_output_level="default:info"
2020-11-20T16:25:40.027150Z     info    FLAG: --log_rotate=""
2020-11-20T16:25:40.027154Z     info    FLAG: --log_rotate_max_age="30"
2020-11-20T16:25:40.027158Z     info    FLAG: --log_rotate_max_backups="1000"
2020-11-20T16:25:40.027162Z     info    FLAG: --log_rotate_max_size="104857600"
2020-11-20T16:25:40.027167Z     info    FLAG: --log_stacktrace_level="default:none"
2020-11-20T16:25:40.027178Z     info    FLAG: --log_target="[stdout]"
2020-11-20T16:25:40.027183Z     info    FLAG: --meshConfig="./etc/istio/config/mesh"
2020-11-20T16:25:40.027186Z     info    FLAG: --outlierLogPath=""
2020-11-20T16:25:40.027190Z     info    FLAG: --proxyComponentLogLevel="misc:error"
2020-11-20T16:25:40.027194Z     info    FLAG: --proxyLogLevel="warning"
2020-11-20T16:25:40.027198Z     info    FLAG: --serviceCluster="istio-ingressgateway"
2020-11-20T16:25:40.027202Z     info    FLAG: --stsPort="0"
2020-11-20T16:25:40.027206Z     info    FLAG: --templateFile=""
2020-11-20T16:25:40.027210Z     info    FLAG: --tokenManagerPlugin="GoogleTokenExchange"
2020-11-20T16:25:40.027226Z     info    Version 1.8.0-c87a4c874df27e37a3e6c25fa3d1ef6279685d23-Clean
2020-11-20T16:25:40.027493Z     info    Obtained private IP [10.200.8.156]
2020-11-20T16:25:40.028419Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 0
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
envoyAccessLogService: {}
envoyMetricsService: {}
parentShutdownDuration: 60s
proxyAdminPort: 15000
serviceCluster: istio-ingressgateway
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411

2020-11-20T16:25:40.028518Z     info    JWT policy is first-party-jwt
2020-11-20T16:25:40.028566Z     info    PilotSAN []string{"istiod.istio-system.svc"}
2020-11-20T16:25:40.225984Z     info    sa.serverOptions.CAEndpoint == istiod.istio-control.svc:15012 Citadel
2020-11-20T16:25:40.226338Z     info    Using CA istiod.istio-control.svc:15012 cert with certs: var/run/secrets/istio/root-cert.pem
2020-11-20T16:25:40.226700Z     info    citadelclient   Citadel client using custom root: istiod.istio-control.svc:15012 -----BEGIN CERTIFICATE-----
MIIC/DCCAeSgAwIBAgIQTbl1NZFfeKOH8IgVhjMmoTANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIwMTExOTIzMTgwOFoXDTMwMTEx
NzIzMTgwOFowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAKffM3PfBU0LZyxGCKjqv3TQA9JwVcGcgZOMMNV1
bHeZtqXMmfEr6xfkZUAmfcyeeLfDmzCcA5DIJR53wliVisrlgZKcGp0gGVibgbqQ
H8C+pSWo1202cxerWmTmr1P0g7zoCoBcDEreYGyL12MEcvWPXNAgX2BDC2vV5+Tg
MwypzVhj3rN6oEoN9qEULavZDpgQ1vZ/MpkECk1ad5WaSStlyEXH0EwD3avfYuf/
6yXi6NZY1ZrPBby+E3KTBgZQeCnmQlrXAZQ54G5ZqNawApIJEkvDiBcg+8WdEZt6
da3rhZKyw3pjJQTTSuhHBKBHgZ2YzhyFMP0IDCb520eDt+kCAwEAAaNCMEAwDgYD
VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFJjQV7+6fatf
5f6//pGm0xs76LlYMA0GCSqGSIb3DQEBCwUAA4IBAQCnBkpS0FfSSI44tVuiti/q
+j1Evkf5cywSRJQAxUVrzUll9YjZIL7msJb3/Wj+NOwP63jgELofGi05dAZ4YcP1
xLMjsYkDJtx0sbCtY2CL1Huc3NuK4ffo144INFQdXLmgLpMA8YBw7QYhK6ZhW2rz
kxxpsD0jzcBqDqr6Ju4ZRMkmY4sIKbs7exW8tQaZfEM7P5IrGLB9MF8hK3zwsjVi
hpbbGfEuARrbNM/G3ZCUC6zIc+F/a/FhcmMY0TNO7ojEl3N6h0AARlUQEu/lPXn+
JH4P4JKme5I9Bfx3K+zUBV8vL5bVgNEOlVz+/Wv+dmukWY+6zZ5HPTM82RFCwLpe
-----END CERTIFICATE-----

2020-11-20T16:25:41.032074Z     info    Starting gateway SDS
2020-11-20T16:25:41.326983Z     warn    secretfetcher   failed load server cert/key pair from secret local-registry-secret: server cert or private key is empty
2020-11-20T16:25:41.327016Z     warn    secretfetcher   failed load server cert/key pair from secret sh.helm.release.v1.istio.v1: server cert or private key is empty
2020-11-20T16:25:41.327026Z     warn    secretfetcher   failed load server cert/key pair from secret cacerts: server cert or private key is empty
2020-11-20T16:25:41.329194Z     info    sds     SDS gRPC server for workload UDS starts, listening on "./etc/istio/proxy/SDS"

2020-11-20T16:25:41.329495Z     info    sds     Start SDS grpc server
2020-11-20T16:25:41.329608Z     info    sds     SDS gRPC server for gateway controller starts, listening on "./var/run/ingress_gateway/sds"

2020-11-20T16:25:41.329678Z     info    xdsproxy        Initializing with upstream address istiod.istio-system.svc:15012 and cluster Kubernetes
2020-11-20T16:25:41.329721Z     info    sds     Start SDS grpc server for ingress gateway proxy
2020-11-20T16:25:41.330339Z     info    xdsproxy        adding watcher for certificate var/run/secrets/istio/root-cert.pem
2020-11-20T16:25:41.330794Z     info    Starting proxy agent
2020-11-20T16:25:41.330948Z     info    Received new config, creating new Envoy epoch 0
2020-11-20T16:25:41.330954Z     info    Opening status port 15020

2020-11-20T16:25:41.331004Z     info    Epoch 0 starting
2020-11-20T16:25:41.427932Z     info    Envoy command: [-c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.200.8.156~istio-ingressgateway-544cbb6698-446xc.istio-system~istio-system.svc.cluster.local --local-address-ip-version v4 --bootstrap-version 3 --log-format-prefix-with-location 0 --log-format %Y-%m-%dT%T.%fZ     %l      envoy %n        %v -l warning --component-log-level misc:error]
2020-11-20T09:25:42.129414Z     warning envoy runtime   Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size
2020-11-20T09:25:42.129552Z     warning envoy runtime   Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size
2020-11-20T09:25:42.130186Z     warning envoy runtime   Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size
2020-11-20T09:25:42.130257Z     warning envoy runtime   Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size
2020-11-20T16:25:42.727389Z     info    xdsproxy        Envoy ADS stream established
2020-11-20T16:25:42.727575Z     info    xdsproxy        connecting to upstream XDS server: istiod.istio-system.svc:15012
2020-11-20T09:25:42.731062Z     warning envoy main      there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
2020-11-20T16:25:42.825871Z     error   xdsproxy        failed to create upstream grpc client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.100.200.10:53: no such host"
2020-11-20T16:25:42.825892Z     info    xdsproxy        disconnected from XDS server: istiod.istio-system.svc:15012
2020-11-20T09:25:42.827427Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.100.200.10:53: no such host"
````
***
it seems like:
- Set "global.istioNamespace: istio-control" only affects CA destination, not discoveryAddress for XDS connection.
- Set "meshConfig.defaultConfig.discoveryAddress: istiod.istio-control.svc:15012" only affects injected proxy, not gateway.

***

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
The same issue occurred on 1.7.4 and 1.8.0
Istioctl version cannot retrieve the version due to:
- no running Istio pods in "istio-system"
- istiod running in istio-control namespace

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Install with IstioOperator CR

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by JohnMops** [comment] 2021-01-07 15:02
Any news on this one ?

**Comment by morvencao** [comment] 2021-01-11 03:10
A workaround the issue is adding pod annotation `proxy.istio.io/config` to make sure gateways konws the correct discovery address:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  components:
    ingressGateways:
    - enabled: true
      namespace: istio-system
      name: istio-ingressgateway
      k8s:
        podAnnotations:
          proxy.istio.io/config: '{"discoveryAddress" : "istiod.istio-control.svc:15012" }'
    egressGateways:
    - enabled: true
      namespace: istio-system
      name: istio-egressgateway
      k8s:
        podAnnotations:
          proxy.istio.io/config: '{"discoveryAddress" : "istiod.istio-control.svc:15012" }'
```

**Comment by howardjohn** [comment] 2021-02-16 20:33
Closing as duplciate of https://github.com/istio/istio/issues/27265. We are working on a fix for this. Thanks!

**Closed by howardjohn** 2021-02-16 20:33 UTC
Labels: area/environments
