### ISSUE TITLE
grpc-go info log appears in istioctl on Mac, causing kube-inject to fail

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#10725] opened 2019-01-03 12:25 UTC
The message :`info	Channelz: socket options are not supported on non-linux os and appengine.` appears in stdout on Mac, in the latest build https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-20190101-09-15/.

A related issue https://github.com/grpc/grpc-go/issues/2335.

**Comment by linsun** [comment] 2019-01-04 18:20
@ibm-jason could you help look at this?

**Comment by ibm-jason** [comment] 2019-01-04 18:21
@linsun absolutely!

**Comment by linsun** [comment] 2019-01-04 18:23
@esnible assign to you to help review any PR for it, since I can't assign to @ibm-jason.

**Comment by esnible** [comment] 2019-01-08 16:37
@ibm-jason Can you update the status of this work item?  It is assigned to me as a place-holder until you are allowed as an Assignee.

**Comment by ibm-jason** [comment] 2019-01-08 16:49
I'm in the process of testing this out locally on my mac workstation. Once I've done this, I can begin to look at how to fix this.

**Comment by esnible** [comment] 2019-01-08 16:56
@ibm-jason Ping me on Slack if you have trouble reproducing or fixing.

**Comment by esnible** [comment] 2019-01-15 21:07
The message comes from a gRPC library init() function that isn't called except by the Go runtime.

@ibm-jason and I have reproduced the issue and are working on finding the particular commit.  This problem was introduced between commit fc88f5881854901e4621fe033aafbfcacd3d475e 28 days ago and e38bbc8373648750d12548e610380ed4d835554b 21 days ago.  The message is coming from _vendor/google.golang.org/grpc/internal/channelz/types_nonlinux.go_:26 which is only compiled on non-Linux systems.  This is why it was able to get past the _istioctl_ tests.

**Comment by ibm-jason** [comment] 2019-01-16 17:27
@esnible I **think** that I've identified the commit that causes the issue. 59c0a8d19d604e56de5fa77b0332da9997445c24 is the first commit where the `2019-01-16T17:25:20.736811Z     info    Channelz: socket options are not supported on non-linux os and appengine.` is observed after building and running istioctl. Looking at the code now to see what changed that could've affected this.

**Comment by ibm-jason** [comment] 2019-01-18 20:48
Update:

I was able to narrow down the package dependencies that are most likely causing the issue:

```
"go.opencensus.io/stats"
"go.opencensus.io/stats/view"
"go.opencensus.io/tag"
```
By commenting out the packages above, alongside any code that leverages them, the log message is no longer shown:

<img width="1075" alt="screen shot 2019-01-18 at 3 46 45 pm" src="https://user-images.githubusercontent.com/38068894/51412076-5e8e1880-1b38-11e9-807a-e3a497b7934e.png">

I'm guessing that the next step is to "fix" the opencensus.io pkgs so that the log output is not observed?

**Closed** 2019-02-06 19:13 UTC
