### ISSUE TITLE
No Jaeger trace if X-Request-ID is manually set in request

### ISSUE THREAD

**Issue by qi-min** [istio/istio#17973] opened 2019-10-17 08:23 UTC
**Bug description**
When `X-Request-ID` is provided in request header, the request can no be displayed in Jaeger. Is there any format requirement to the `X-Request-ID`?
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Request can be displayed in Jaeger trace
**Steps to reproduce the bug**
Take bookinfo sample as example. When accessing api by `curl http://localhost:31380/productpage -I`, request can be shown in Jaeger with correct trace.
But there is no trace in Jaeger if `X-Request-ID` is provided in request like below:
```
curl http://localhost:31380/productpage -I -H 'X-Request-ID: 90f1fe22ab377a463d681afc59412407'
``` 

If the request id follows the format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, the trace is ok too. So there is trace only when no `X-Request-ID` is not provided or the format is xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (e.g. aff95183-98ab-911c-a852-ac1f4a1b3269). `X-Request-ID` with other format does not work.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
istioctl version --remote
client version: 1.2.5
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5
telemetry version: 1.2.5
```
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by bianpengyuan** [comment] 2019-10-17 15:08
Envoyproxy only consider UUID that follows https://tools.ietf.org/html/rfc4122 as traceable. I am going to close this as this works as intended. Please consider open an feature request in envoyproxy repo if alternative request id format is desired.

**Closed by bianpengyuan** 2019-10-17 15:08 UTC

**Comment by objectiser** [comment] 2019-10-17 16:23
A feature request and proposal has already been raised for this: https://github.com/envoyproxy/envoy/issues/7624
