### ISSUE TITLE
operator fails to generate egressgateway even if I have egressGateways enabled in my iop cr

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#20328] opened 2020-01-20 09:35 UTC
[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment] 2020-01-20 18:19
dupe of https://github.com/istio/istio/issues/19799? Or is this different

**Comment by irisdingbj** [comment] 2020-01-21 07:21
> dupe of #19799? Or is this different

This is a different problem. The issue here is we use protobuf as source of truth and the generated pb.go are using different names for ingressGateways and egressGateways.

**Comment by irisdingbj** [comment] 2020-02-03 06:46
@ostromart @morvencao @sdake Can you please take a look at above change in operator API? otherwise we can not have gateway generated via in cluster operator.

**Comment by ostromart** [comment] 2020-02-21 22:35
Fixed.

**Closed by ostromart** 2020-02-21 22:35 UTC
Labels: area/environments/operator, lifecycle/needs-triage
