### ISSUE TITLE
Environment Variable Substitution Not Working in IstioControlPlane

### ISSUE THREAD

**Issue by zimmertr** [istio/istio#21014] opened 2020-02-10 23:29 UTC
**Bug description**

When defining an `IstioControlPlane` file to be ingested by `istioctl manifest apply -f FILE.yml` Environment Variables are not  expanded.

For example, I want to specify the Image Repository for Grafana. Which could be an ECR that is different each time it is applied:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
    grafana:
      enabled: true
      image:
        repository: ${REGISTRY_URL}/grafana/grafana
```

I have tried the following environment variable syntaxes:
```
${REGISTRY_URL}
$${REGISTRY_URL}
$(REGISTROY_URL)
$$(REGISTRY_URL)
$REGISTRY_URL
```

But all of them seem to be interpreted as string literals. For  example, from  `kubectl describe pod`:
```
Containers:
  grafana:
    Container ID:
    Image:          ${REGISTRY_URL}/grafana/grafana:6.4.3
```

**Expected behavior**

The environment variable should be expanded to either NULL or the contents of the system environment variable if it is set. 

**Steps to reproduce the bug**

1) Create an `istioControlPlane` configuration file that uses Environment Variables.
2) Set the environment variable on your system.
3) Run `istioctl manifest apply -f FILE.yml` and  see that the variables are considered string literals and are not expanded. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

*Istio:* 1.4.3
*Kubernetes:* 1.17.0

**How was Istio installed?**

I used the scary recommended method of piping the internet into my shell. 

**Environment where bug was observed (cloud vendor, OS, etc)**

Local `kubeadm` based cluster.

**More Information:**

This process can be worked around like so. Which is really hacky:

`cat FILE.yml | envsubst > /tmp/FILE.yml && istioctl manifest apply -f /tmp/FILE.yml && rm /tmp/FILE.yml`

I tried to pipe the file into `istioctl manifest apply -f` using STDIN like so: 

```
$> cat ~/Desktop/example.yml | envsubst | istioctl manifest apply -f -
Failed to generate and apply manifests, error: failed to generate manifest: could not read values from file -: open -: no such file or directory
```

By switching to the `<()` operator for STDIN parsing, Istio just ignores the STDIN entirely and simply deploys the default configuration:

`cat ~/Desktop/example.yml | envsubst | istioctl manifest apply -f <()`

**Comment by zimmertr** [comment] 2020-02-10 23:35
A separate bug report pertaining to the issues with providing a configuration to STDIN has been created [here](https://github.com/istio/istio/issues/new?template=bug_report.md).

**Comment by ayj** [comment] 2020-02-10 23:48
You can use the `--set` flag to achieve the desired behavior. 

```bash
istioctl manifest apply -f FILE.yaml --set values.grafana.image.repository=<image name>
```

You can use envsubt for substitution via envvar. kubectl doesn't search/replace arbitrary envars either (see below). https://github.com/istio/istio/pull/20912 adds support for reading from STDIN.

```bash
$ cat test.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAME}

$ NAME=foo kubectl create -f test.yaml -o yaml --dry-run
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAME}
  namespace: default
```

**Comment by zimmertr** [comment] 2020-02-11 00:32
Thanks for the response. I recognize that I can use the `--set` argument but a configuration file is more appropriate for version control when doing IaC than a long form shell command. This feels more like a workaround than a solution. I think a more refined workaround is using this approach:

```
cat FILE.yml | envsubst > /tmp/FILE.yml && istioctl manifest apply -f /tmp/FILE.yml && rm /tmp/FILE.yml
```

If this is a limitation of kubectl as opposed to istioctl feel free to close.

**Comment by esnible** [comment] 2020-02-13 19:01
I am closing this because it is working as intended.

I have used istioctl and kubectl with bash "here-documents" to achieve this effect.  Helm templates provide this effect.  istioctl and kubectl do not process environment variable templates.

**Closed by esnible** 2020-02-13 19:01 UTC
Labels: area/config, area/environments
