### ISSUE TITLE
istio1.1-pre mcp pilot needs to more CPU than non mcp

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#10220] opened 2018-11-30 22:51 UTC
Investigate why [mcp pilot](http://grafana.v11-mcp.qualistio.org/d/3/pilot-dashboard?refresh=5s&orgId=1) [snapshot](https://snapshot.raintank.io/dashboard/snapshot/3TjSEM70HR3JQT9jUfgv2NXS1s81EyQY) needs more cpu than  [non-mcp pilot](http://grafana.v11.qualistio.org/d/3/pilot-dashboard?refresh=5s&orgId=1&panelId=47)  [snapshot](https://snapshot.raintank.io/dashboard/snapshot/j12o6M7v5i58GUqywDbX7ZrtEn58eIzE)version.

Things to note: MCP pilot has a higher number of rejected CDS configs.
MCP version uses: 30 - 50 cpus non-mcp uses less than 20 at the similar number of total endpoints.

**Comment by ayj** [comment] 2018-11-30 22:56
MCP currently supports pushing the full set of resource (per type) each time. Pilot's MCP client integration [computes](https://github.com/istio/istio/blob/df0d817c5ecf6f3fab94cb599ddd90c363c4d533/pilot/pkg/config/coredatamodel/controller.go#L213-L241) a diff against the previous snapshot to generate add/update/remove events. 

For starters, we can optimize dispatch by type. I believe only ServiceEntry needs actually events for each add/remove/update. For other user authored config we can take advantage of the fact that global cache invalidation and trigger a single dummy event per batch per type.

Longer term, incremental MCP will eliminate the need for Pilot to compute the diff itself for ServiceEntry.

**Comment by mandarjog** [comment] 2018-12-01 13:46
Since we would like to make MCP default for 1.1, we should do these optimization. For completeness, can you investigate CDS rejections too?

**Comment by mandarjog** [comment] 2018-12-01 13:51
![MCP flamegraph](https://storage.googleapis.com/artifacts.mixologist-142215.appspot.com/perfdata/MCP-istio-pilot-5fb4cbd4d-8tprh__1543618218.svg)
 
![Non MCP flamegraph](https://storage.googleapis.com/artifacts.mixologist-142215.appspot.com/perfdata/NONMCP-1.1-istio-pilot-5b6d5c4488-nmz2w__1543618436.svg) 

![MCP heap](https://storage.googleapis.com/artifacts.mixologist-142215.appspot.com/perfdata/mcp_pilot_mem.svg)
 
![Non MCP heap](https://storage.googleapis.com/artifacts.mixologist-142215.appspot.com/perfdata/no_mcp_pilot_mem.svg)

**Comment by mandarjog** [comment] 2018-12-01 13:53
Non MCP flamegraph
![Non MCP flamegraph](https://storage.googleapis.com/artifacts.mixologist-142215.appspot.com/perfdata/NONMCP-1.1-istio-pilot-5b6d5c4488-nmz2w__1543618436.svg) 

 Non MCP heap
![Non MCP heap](https://storage.googleapis.com/artifacts.mixologist-142215.appspot.com/perfdata/no_mcp_pilot_mem.svg)

**Comment by costinm** [comment] 2018-12-01 16:54
The diffs are not currently needed - any config change causes a push in
1.1, and the plan is for pilot to do its own
checks on what needs to be pushed - but with "isolation" it'll be a very
different implementation.
So just remove the diff - it is not needed now nor in the future.

ServiceEntry can be sent as configuration - they don't change very often,
but please make sure and test that no
'synthetic' ServiceEntry is ever sent to pilot ( i.e. created from k8s
Service + Endpoints), only real, user created ServiceEntry
objects.

**Comment by costinm** [comment] 2018-12-01 16:59
Also: for endpoints we expect to only use 'on-demand', not incremental.

For configs - in 1.2 we will likely need incremental ( similar with K8S
watch interface ).

**Comment by mandarjog** [comment] 2018-12-01 18:55
Note: MCP flame graph shows more time on GC.

**Comment by ayj** [comment] 2018-12-03 19:21
Pilot e2e tests using ServiceEntry were failing w/o the service/endpoint events (requiring diff). Unlike user authored config, it seems that the external service registry is updating its internal state using the events. Maybe that changed since we did the initial MCP client integration in Pilot.

It sounds like we'll want 'synthetic` ServiceEntry generation to be guarded by a flag/API (when its added, 1.2+) initially to avoid Pilot getting dup endpoints from Galley and k8s directly. 

Pilot-to-envoy ondemand/incremental xDS discussion is orthogonal to Galley-to-pilot incremental MCP. MCP incremental should reduce memory allocations and decode costs. e.g. the cost of adding one more config/endpoint is N+1 with full-state and 1 with incremental. Note that k8s watch is essentially incremental today in some sense, full-state is a regression in turns of memory allocation costs.

**Comment by ayj** [comment] 2018-12-04 19:08
I'm looking into improving memory usage in Pilot MCP client.

**Comment by costinm** [comment] 2018-12-04 20:49
Please just remove all diff in pilot. Not needed now or in furure.

**Comment by costinm** [comment] 2018-12-04 20:50
MCP should not affect eds in 1.1

**Comment by ayj** [comment] 2018-12-05 00:36
I made a few small adjustments to Pilot MCP integration to reduce memory allocations. The resulting pprof memory profile highlighted the fact that Pilot now validates configuration w/MCP (see below) when deciding whether to ACK/NACK. Pilot w/k8s didn't validate user authored config. 

```bash
(pprof) top
Showing nodes accounting for 288.55MB, 99.81% of 289.10MB total
Dropped 7 nodes (cum <= 1.45MB)
Showing top 10 nodes out of 11
      flat  flat%   sum%        cum   cum%
  142.01MB 49.12% 49.12%   142.01MB 49.12%  strconv.Atoi
     136MB 47.04% 96.16%      136MB 47.04%  strings.genSplit
    8.04MB  2.78% 98.95%   286.05MB 98.95%  istio.io/istio/pilot/pkg/config/coredatamodel.(*Controller).Apply
    2.50MB  0.86% 99.81%   288.55MB 99.81%  istio.io/istio/pilot/pkg/config/coredatamodel_test.BenchmarkApply
         0     0% 99.81%   278.01MB 96.16%  istio.io/istio/pilot/pkg/model.ValidateServiceEntry
         0     0% 99.81%   278.01MB 96.16%  istio.io/istio/pilot/pkg/model.ValidateWildcardDomain
         0     0% 99.81%   188.51MB 65.20%  istio.io/istio/pilot/pkg/model.validateDNS1123Labels
         0     0% 99.81%    46.50MB 16.08%  strings.Split
         0     0% 99.81%    89.50MB 30.96%  strings.SplitN
         0     0% 99.81%   288.55MB 99.81%  testing.(*B).launch
```

**Comment by Nino-K** [comment] 2018-12-10 22:11
:+1: with @ayj's suggestion, we can start by dispatching the add/remove/update events only for service entries since it looks like [external service discovery](https://github.com/istio/istio/blob/df0d817c5ecf6f3fab94cb599ddd90c363c4d533/pilot/pkg/serviceregistry/external/servicediscovery.go#L66-L90) is taking advantage of the diff, however I'm not too sure if the diff can just be removed at this point.

**Comment by costinm** [comment] 2018-12-11 00:43
Or better: fix ServiceEntry.

For Service event, the conversion is useless - it'll trigger a ConfigUpdate
that will convert again, it is not used for anything.

For Endpoint event - conversion and diff is equally unnecessary, just need
to change the code to trigger the EndpointUpdate(all).
For ServiceEntry changes we can do a full EDS push - they are treated as
user configuration.

In general - most of the event/conversion was never used, just part of the
API for planned changes. We still plan to push
on-demand based on a specific config change - but not in 1.1 and likely
after 'incremental' is part of the protocol.

**Comment by ayj** [comment] 2018-12-12 03:12
It sounds like switching to MCP is highlighting the fact that the ServiceEntry path needs to be optimized? @costinm, can someone from networking team a stab at this?

In addition, there are several MCP enhancements we can make to reduce CPU/memory across the board, e.g. reduced memory allocations and decode/validation costs.

**Comment by Nino-K** [comment] 2018-12-12 19:52
In the env-config meetup @costinm  agreed that adding a service entries filter to the diff might be a reasonable solution for now (until we have incremental updates) due to the way Cloud Foundry today sends only Service Entries to register it's endpoints. Alternative solution would be if copilot introduces a new MCP type that is specific to CF (however it would be using the service entry proto underneath). This requires both changes to Copilot (CF service registry) and Pilot, which could potentially allow us to remove the diff?

**Comment by ayj** [comment] 2018-12-12 20:01
I would strongly prefer filtering diff by type for service entries. This aligns well with incremental updates (when available) and avoids introducing duplicate CF specific types. I'm not sure how adding a CF specific type would help long term, considering we plan to use ServiceEntry for k8s discovery as well (via out-of-process adapter or Galley).

**Comment by Nino-K** [comment] 2018-12-12 20:48
Yes, agreed. Having a duplicate type in the future to handle service registry for two separate platforms seems to be an anti-goal in MCP.

**Comment by costinm** [comment] 2018-12-12 22:47
Agree - having duplicated type for separate platforms, or in general platform specific features is an anti-goal.

However this is in no way specific to CF - we do plan to use ServiceEntry for Consul and K8S (in 1.2) and we have exactly the same problem, that ServiceEntry is used for both config (egress) and to map the endpoints. 

Using a separate config type ( but with the same protocol ) to isolate the discovery/endpoint from the config changes is also consistent with how Pilot works today. 

As an alternative to a separate config type ( which IMO is the cleanest solution) - we can add an extra bit to the envelope to indicate that a change is an 'endpoints only' change ( i.e. corresponds to a discovery event or Serivce.EndpointSet in k8s). 

We'll revisit this in 1.2, as we move consul/k8s endpoints to use MCP - it's not exposed to the users so we can iterate without backward compat risks.

In any case - it is far better than current 'diff' solution.

**Comment by costinm** [comment] 2018-12-12 22:51
@ayj: diff does not align at all with incremental updates - and as I mentioned support for incremental 
update of endpoints is already present in ADS/EDS ( and implicitly in MCP ) protocol.

The incremental support for other configs is different - and does require changes in ADS, which are in progress, but endpoints are clearly supporting incremental in the protocol ( since we are using it ), and I don't see any reason why CF couldn't implement it in their server ( Galley will eventually need this as well in 1.2 for k8s endpoints ). It is not a protocol change, and is an optimization CF should do anyways, otherwise they'll have delays and scale issue server side.

**Comment by ayj** [comment] 2018-12-12 22:59
This GH issue is about MCP. Incremental updates refers to MCP which is orthogonal to incremental ADS. We're not talking about adding incremental ADS/EDS in this thread. This issue is about efficiently pushing config from Galley to Pilot. Pilot can use whatever form of xDS/ADS it wants in dependent on MCP.

FWIW, k8s config delivery today is incremental in the sense that the kube-apiserver pushes incremental add/update/delete resources to Pilot.

**Comment by costinm** [comment] 2018-12-12 23:33
We have about 1 month until 1.1 AFAIK - I guess I can live with diff only
on ServiceEntry, but I would rather move in the right direction and
fix the underlying problem. Sending _all_ endpoints from all Services from
Copilot and doing a diff is a scalability issue in both ends.
It will not affect K8S too much since there are not so many egress
ServiceEntry changes - but I doubt CF users will be very happy.

**Comment by andraxylia** [comment] 2018-12-13 18:55
I proposed an API to separate what the user configures from the synthetic ServiceEntries, and also to separate Endpoints so they are handled by incremental MCP:
https://github.com/istio/api/pull/628

**Comment by costinm** [comment] 2018-12-14 21:46
To break down things: 
- diff for everything except ServiceEntry - I hope we agree that it needs to go, and it's P0
- fixing ServiceEntry to call ConfigUpdate and not require a diff - I hope we also agree it's clear and simple change
- doing diffs for ServiceEntry when CF is used - I can live with that, but I would prefer the fix I suggested that avoids it

Long term Pilot and Envoy will need MCP to support a protocol compatible ( and if possible identical ) with Envoy ADS on-demand/incremental.  If there are strong reasons the protocol adopted by Envoy is 
bad - it would be good to find them ASAP so we can take this back to Envoy and fix ADS.

Incremental Endpoints - which is what I'm suggesting for CF - can also be used for Istio MC and is a change we can get in 1.1, and doesn't require any protocol change. MCP is based on ADS, and ADS already supports this and we're using the feature already.  I'll start a separate thread for this part, since quite a few people expressed concerns with the current MC secrets.

**Comment by Nino-K** [comment] 2019-01-07 19:48
>doing diffs for ServiceEntry when CF is used - I can live with that, but I would prefer the fix I suggested that avoids it

I don't think the diff today is necessarily related to CF use case, I believe after the incremental update changes the diff should completely go away (even for CF), of course this requires some changes in configuration provider for CF (co-pilot).

**Comment by jasminejaksic** [comment] 2019-01-15 00:46
@ozevren and @ayj this is assigned to you two? Are you working on CF? If not, who is working on it and what's still pending? Also, why is this a blocker (P0) for 1.1?

**Comment by ayj** [comment] 2019-01-15 18:04
@costinm and @Nino-K are working on https://github.com/istio/istio/pull/10446 to address this.

**Comment by costinm** [comment] 2019-01-31 17:39
Yes, this solves the issue. We may need few small changes once Nate's PR is in - but not blocking 1.1

**Closed by costinm** 2019-01-31 17:39 UTC
Labels: area/config, area/networking, area/perf and scalability
