### ISSUE TITLE
regression: hpa spec broken with new iop API

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20143] opened 2020-01-14 01:34 UTC
Config:
```
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 2000m

    policy:
      enabled: false
    
    telemetry:
      enabled: false
    galley:
      enabled: false
    citadel:
      enabled: false
    ingressGateways:
    - enabled: true
      k8s:
         hpaSpec:
           minReplicas: 3
           maxReplicas: 10
        resources:
          limits:
            cpu: 6000m
            memory: 512Mi
          requests:
            cpu: 4000m
            memory: 512Mi
```

```
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ""
    name: ""
``

See scaleTargetRef, it is not correct.

**Comment by richardwxn** [comment] 2020-01-21 19:32
Took a look at the code, I think the reason is that we treat the hpa spec as a whole block during merging. For example, in this case, the overlay you have doesn't specify scaleTargetRef, so during merging with the HPA specs in the templates(which has scaleTargetRef defined actually), the overlay would override the base, resulting in an empty scaleTargetRef.

Maybe we should update the merge logic during k8s setting overlay?

**Comment by howardjohn** [comment] 2020-01-21 19:34
Its hard because if we make it purely additive there is no way to remove something that is already set? I think? We should probably do whatever https://github.com/kubernetes-sigs/kustomize does

**Comment by ostromart** [comment] 2020-01-25 20:34
The root cause is actually that we are using a k8s include for HPA spec specifically rather than mirroring as we are doing for other k8s proto messages. Because k8s protos are v2, they do not compile with "omitempty". Therefore, when a HorizontalPodAutoscalerSpec object is created, the empty string fields are included and JSON strategic merge overlays the empty fields for the entire object, not just the fields defined in the overlay. Fixed in https://github.com/istio/api/pull/1251.

**Comment by ostromart** [comment] 2020-01-25 20:36
@richardwxn we do use merge logic in the overlay phase. This problem is peculiar to this field. we already mirror all the others.

**Closed** 2020-01-27 23:47 UTC
Labels: area/environments/operator
