### ISSUE TITLE
webhook "sidecar-injector.istio.io" error converting YAML to JSON

### ISSUE THREAD

**Issue by vikramkhatri** [istio/istio#7762] opened 2018-08-09 02:59 UTC
**Describe the bug**

Main Error: `admission webhook "sidecar-injector.istio.io" denied the request: error converting YAML to JSON: yaml: line 83: did not find expected key`

When I try to deploy BookInfo pods, it fails with the error:
```
Events:
  Type     Reason        Age              From                   Message
  ----     ------        ----             ----                   -------
  Warning  FailedCreate  5m (x6 over 8m)  replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  FailedCreate  5m               replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: read tcp 192.168.142.102:42382->10.0.0.177:443: read: connection reset by peer; some request body already written
  Warning  FailedCreate  5m (x4 over 5m)  replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: dial tcp 10.0.0.177:443: getsockopt: connection refused
  Warning  FailedCreate  6s (x7 over 4m)  replicaset-controller  Error creating: Internal error occurred: admission webhook "sidecar-injector.istio.io" denied the request: error converting YAML to JSON: yaml: line 83: did not find expected key
```
Then I tried to generate the template manually, using `helm --debug template ./ibm-istio -n istio --namespace istio-systrem -f /tmp/values.yaml > /tmp/istio.yaml` and looking through the generated file, I see the issue as shown where after `"-p"`, there is this value: `[[ .MeshConfig.ProxyListenPort ]]` - which seems like a helm variable.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: ibm-istio
    chart: ibm-istio-1.0.1
    heritage: Tiller
    release: istio
    istio: sidecar-injector
data:
  config: |-
    policy: enabled
    template: |-
      initContainers:
      - name: istio-init
        image: ibmcom/istio-proxy_init:1.0.0
        imagePullPolicy: IfNotPresent
        args:
        - "-p"
        - [[ .MeshConfig.ProxyListenPort ]]
        - "-u"
        - 1337
        - "-m"
        - [[ or (index .ObjectMeta.Annotations "sidecar.istio.io/interceptionMode") .ProxyConfig.InterceptionMode.String ]]
        - "-i"
        [[ if (isset .ObjectMeta.Annotations "traffic.sidecar.istio.io/includeOutboundIPRanges") -]]
        - "[[ index .ObjectMeta.Annotations "traffic.sidecar.istio.io/includeOutboundIPRanges"  ]]"
        [[ else -]]
        - "*"
        [[ end -]]
        - "-x"
        [[ if (isset .ObjectMeta.Annotations "traffic.sidecar.istio.io/excludeOutboundIPRanges") -]]
        - "[[ index .ObjectMeta.Annotations "traffic.sidecar.istio.io/excludeOutboundIPRanges"  ]]"
        [[ else -]]
        - ""
        [[ end -]]
        - "-b"
```
I can verify that using `kubectl -n istio-system get cm istio-sidecar-injector -o yaml`

The log from sidecar show this:
```
2018-08-09T01:28:14.121183Z	warn	Failed to unmarshall template error converting YAML to JSON: yaml: line 83: did not find expected key initContainers:
```
**Version**
```
# istioctl version --short
root@71a9470ea93c-gcr.io/istio-release-1.0.0-3a136c90ec5e308f236e0d7ebb5c4c5e405217f4-Clean
# kubectl version --short
Client Version: v1.10.0
Server Version: v1.10.0+icp-ee
```
**Environment**
IBM Cloud Private 2.1.0.3-FP1

**Comment by morvencao** [comment] 2018-08-09 03:43
@vikramkhatri The value: `[[ .MeshConfig.ProxyListenPort ]]` is normal, since the template needs to be rendered by `sidecar injector webhook` again with mesh configuration.

**Comment by morvencao** [comment] 2018-08-09 08:13
You have set resource limits for sidecar injector webhook:
```
sidecarinjectorwebhook:
  enabled: true
  replicaCount: 1
  enableNamespacesByDefault: false
  image:
    repository: ibmcom/istio-sidecar_injector
    tag: 1.0.0
  resources:
    limits:
      cpu: 50m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi
```

That's maybe the root cause.
I'm not sure the minimal resource applied to sidecar injector webhook.
It should require more resources once workloads come to the pod.

Anyway, you can delete the resource limits to workaround this.

**Comment by morvencao** [comment] 2018-09-05 09:26
Close this as this is resource limits issue.

**Closed by morvencao** 2018-09-05 09:26 UTC
