### ISSUE TITLE
503 upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by vitalijsvolodenkovsmagebit** [istio/istio#9906] opened 2018-11-12 18:55 UTC
Istio version: 1.0.3
Kubernetes version: 1.11.2

Setup:
Kuberentes Ingress -> ServiceA->nginx_proxy_to_ServiceB
        server {
            listen       80;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
            resolver kube-dns.kube-system.svc.cluster.local valid=5s;
            location /api {
                proxy_pass   http://serviceb.ns.svc.cluster.local:13301$uri;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
            }
        }
For 5-20 % of requests to /api we are getting 503 response.

**Comment by AtebMT** [comment] 2018-11-15 08:17
Ditto. Looked like a timeout after 1sec with some requests. Downgraded to 1.0.2 and all seems fine again.

**Comment by Javatar81** [comment] 2018-11-20 12:04
We encountered the same problem. In the logs of the ingress gateway pod, we found several 200 OKs and several 503 errors. The log contains the target pod ips and we found that the ones returning 503 do not pertain to any of the pods behind the k8s service. This issue might disappear when you redeploy your pods. I would assume that the ips returning the error are obsolete pod ips and the ingress gateway is not aware of the new endpoints after a deployment.

**Comment by wnstar** [comment] 2018-11-22 10:20
This issue might disappear when you  reedit gateways or virtualservices or service.

**Comment by Javatar81** [comment] 2018-11-29 07:45
The problem disappeared after updating to 1.0.4. Maybe this fix solved it: https://github.com/istio/istio/pull/9805

**Comment by xilu0** [comment] 2018-12-25 11:37
We encountered the same problem

**Comment by MrSaints** [comment] 2018-12-27 09:16
Since upgrading to 1.0.4 (and now, 1.0.5), the issue appears to be resolved.

**Comment by dankirkpatrick** [comment] 2019-02-20 20:22
I've also been having intermittent 503 errors.  I'm running v1.0.5, though.  The errors occur on the ingressgateway, with nothing logged by the backing service.  The errors occur during the initial request, and fail immediately (i.e. not after a timeout).

I've also see intermittent 503 errors with Istio sidecars when calling our service directly, from inside our cluster.  Additionally, I've also seen intermittent 503 errors with an Ambassador api gateway (also built atop Envoy).  

As a result, I've started investigating Envoy changes, and discovered that Envoy recently added a stream idle timeout of 5 minutes.  

https://github.com/envoyproxy/envoy/pull/3841
https://github.com/envoyproxy/envoy/pull/3879

I've also found that Istio does connection pooling for HTTP1.1 and 2.0 traffic, and that it utilizes a TCP keepalive set to 5 minutes.  It appears that Istio has introduced a configuration setting that will be included in Istio v1.1.

https://github.com/istio/istio/pull/10159

I believe there is a race condition between these.  If a connection in the connection pool is idle for 5 minutes, then the keepalive heartbeat will be sent.  But, with both set to 5 minutes, a race condition exists: if the timeout occurs before the keepalive, the connection is closed.  The next request that attempts to use that connection from the connection pool will receive a 503 error immediately, and without the backing service ever receiving the request.

I've had to resort to configuring envoy to retry on error (in the VirtualService spec, under http:, I add "retries:\n  attempts: 2" so that Envoy automatically retries on 5xx errors.  It does not by default.  This has completely eliminated our 503 errors.

In Istio 1.1, they've also exposed the "retryOn" field in Envoy, so you can specify automatic retries only on 5xx errors.  This would be better than retrying every failed request.

When Istio 1.1 is released, we'll test configuring the tcp keepalive setting to shorter than 5 minutes.  Hopefully this will eliminate the need to do automatic retries with 5xx errors.  At this point, this is all just a hypothesis, as we have not tested against the 1.1 snapshot releases.

**Comment by rshriram** [comment] 2019-02-27 19:13
@dankirkpatrick thanks for tracking this down.. I remember the envoy per stream idle timeouts.. and IIRC, we set those to 0 in istio.. https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener.go#L1403 which I believe went into 1.0 series (https://github.com/istio/istio/pull/7428). 

So, the connection manager level timeout is disabled, while the OS level keep alive timeout appeared recently. So I believe what happened here is that at envoy level, it kept the connection open, and idle without setting TCP keep alives. The OS closes the connection after 5 minutes. When you send a request after a while, it might land on a dead connection and hence the 503.. So, yes a retry helps here..

**Comment by iandyh** [comment] 2019-03-22 10:13
@dankirkpatrick Hello. I've tested your trick using `destinationrule` and it seems it still has 503s. I am using istio-1.1-rc5 though, because this is the fast version I can test with. 

I am more than happy if you correct me....

**Comment by howardjohn** [comment] 2019-08-25 23:17
There has been a lot of work reducing 503s since Istio 1.0, is this still an issue on new versions?

**Comment by reste85** [comment] 2019-08-27 14:56
We're experiencing the same behaviour (503) when hitting directly the service from inside our cluster. We've a pod with a service container and the istio proxy. 
Istio version: 1.2.4.
Could it be possible that the problem is still around?

**Comment by howardjohn** [comment] 2019-09-19 00:09
Its very possible there are still issues that may cause 503s - generally all envoy errors are exposed as 503s so its kind of a catch all situation. At this point, I doubt any issues experienced now are the same as the original issue, or that many will notice comments on such an old issue. If you are still seeing issues, I would encourage you to open a new issue with a lot of information - especially if it is reproducible.

**Closed by howardjohn** 2019-09-19 00:09 UTC
Labels: area/networking, kind/need more info
