### ISSUE TITLE
helm upgrade fail for 1.1.0-rc.0

### ISSUE THREAD

**Issue by xianke9** [istio/istio#12015] opened 2019-02-25 12:53 UTC
```
root@m-1:~/istio-1.1.0-rc.0# helm upgrade --install istio install/kubernetes/helm/istio --namespace istio-system \
   --set ingress.enabled=true \
   --set gateways.istio-ingressgateway.enabled=true \
   --set gateways.istio-egressgateway.enabled=true \
   --set galley.enabled=true \
   --set sidecarInjectorWebhook.enabled=true \
   --set mixer.enabled=true \
   --set prometheus.enabled=true \
   --set global.hub=istionightly \
   --set global.tag=1.1.0-rc.0 \
   --set global.imagePullPolicy=Always \
   --set global.proxy.envoyStatsd.enabled=true \
   --set global.mtls.enabled=true \
   --set security.selfSigned=false \
   --set global.enableTracing=true \
   --set global.proxy.autoInject=true \
   --set tracing.enabled=true \
   --tls
```
```
Error: UPGRADE FAILED: YAML parse error on istio/charts/ingress/templates/deployment.yaml: error converting YAML to JSON: yaml: line 50: did not find expected key
root@m-1:~/istio-1.1.0-rc.0# pwd
/root/istio-1.1.0-rc.0
```

**Comment by sdake** [comment] 2019-02-25 14:44
@xianke9 what flags did you use to install originally?  Not that it is relevant to the problem, but it may help me reproduce.

Cheers
-steve

**Comment by xianke9** [comment] 2019-02-26 01:44
root@m-1:~# istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

**Comment by xianke9** [comment] 2019-02-26 04:43
Do I need some pre-actions for this upgrade? for example, repo set, or others.

**Comment by sdake** [comment] 2019-03-01 10:11
It is unclear if anyone has tested ingress enabled in the RC candidates.  While ingress gateway is heavily tested by our gating system, ingress itself is not.

I was able to duplicate this issue.

Here is what the deployments file looks like (rendered):
```
# Source: istio/charts/ingress/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    app: ingress
    chart: ingress
    heritage: Tiller
    release: release-name
    istio: ingress
spec:
  template:
    metadata:
      labels:
        app: ingress
        chart: ingress
        heritage: Tiller
        release: release-name
        istio: ingress
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: istio-ingress-service-account
      containers:
        - name: ingress
          image: "istionightly/proxyv2:1.1.0-rc.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          args:
          - proxy
          - ingress
          - --domain
          - $(POD_NAMESPACE).svc.cluster.local
          - --log_output_level
          - 'info'
          - --drainDuration
          - '45s' #drainDuration
          - --parentShutdownDuration
          - '1m0s' #parentShutdownDuration
          - --connectTimeout
          - '10s' #connectTimeout
          - --serviceCluster
          - istio-ingress
          - --zipkinAddress
          - zipkin:9411
          - --statsdUdpAddress
          - :
          - --proxyAdminPort
          - "15000"
          - --statusPort
          - "15020"
          - --controlPlaneAuthPolicy
          - NONE
          - --discoveryAddress
          - istio-pilot:15010
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15020
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 10m

          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          volumeMounts:
          - name: istio-certs
            mountPath: /etc/certs
            readOnly: true
          - name: ingress-certs
            mountPath: /etc/istio/ingress-certs
            readOnly: true
      volumes:
      - name: istio-certs
        secret:
          secretName: istio.istio-ingress-service-account
          optional: true
      - name: ingress-certs
       secret:
          secretName: istio-ingress-certs
          optional: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
```

**Comment by sdake** [comment] 2019-03-01 10:14
@xianke9 to answer your question, yes, you need to install i`stio-init` first prior to upgrading.  We are working on improving the documentation for 1.1 prior to release, but this is the current upgrade documentation:
https://preliminary.istio.io/docs/setup/kubernetes/upgrade/#helm-upgrade

**Comment by sdake** [comment] 2019-03-01 10:16
statsd is deprecated.  I believe it has been entirely removed, however, the ingress chart keys off of it's values.  @douglas-reid can you confirm?

Cheers
-steve

**Comment by sdake** [comment] 2019-03-01 16:01
@xianke9 this is user error:

You are specifying the following
```
 --set global.proxy.envoyStatsd.enabled=true 
```

From `values.yaml`, (the current canonical documentation):
```
    envoyStatsd:
      # If enabled is set to true, host and port must also be provided. Istio no longer provides a statsd collector.
      enabled: false
      host: # example: statsd-svc.istio-system
      port: # example: 9125
```
This problem would occur during install as well as upgrade.

I recognize the error is vague and doesn't explain this problem.  This is a limitation of the underlying technology in use (Helm).  We are correcting this problem in later versions of Istio by validating user input.

Cheers
-steve

**Comment by douglas-reid** [comment] 2019-03-01 17:59
@sdake we left it in so that those that wished to use a statsd exporter (of their own deploying) could still.

**Comment by sdake** [comment] 2019-03-04 18:35
This is just a doc issue - this is not blocking the release.

**Comment by linsun** [comment] 2019-03-04 20:59
agreed on doc issue for this with @sdake.

Also, I don't think we no longer support the ingress.enabled=true in v1.1.

**Comment by xianke9** [comment] 2019-03-04 21:43
in summary, we should refer to https://preliminary.istio.io/docs/setup/kubernetes/upgrade/#helm-upgrade for upgrade, and remove param ingress.enabled=true, global.proxy.envoyStatsd.enabled=true, right?

**Comment by duderino** [comment] 2019-03-05 00:33
Being pedantic here, sorry, I'd love to see a doc PR or P0 doc bug created before we demote this one.  Otherwise it'll fall of our short list of frequently revisited bugs

**Comment by sdake** [comment] 2019-03-05 01:29
@duderino ack, no problem - I won't move around priorities in iissues in istio/istio repo.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-05 01:32
> in summary, we should refer to https://preliminary.istio.io/docs/setup/kubernetes/upgrade/#helm-upgrade for upgrade, and remove param ingress.enabled=true, global.proxy.envoyStatsd.enabled=true, is it right?

you may want ingress enabled - it depends on your deployment.  As far as statsd enabled goes this also depends on your deployment, if you enable this, you must also enable the statsd server and statsd port as Istio no longer provides one.

**Comment by sdake** [comment] 2019-03-05 01:34
@linsun if we don't support ingress.enabled=true in 1.1, then we should probably remove ingress.  I don't know the state of ingress, as it is outside of my current focus areas.  @andraxylia or @rshriram can you comment?

Cheers
-steve

**Comment by linsun** [comment] 2019-03-05 03:35
cc @costinm to comment, I'd be happy to remove it.  I recall discussing this in a TOC mtg recently.

**Comment by andraxylia** [comment] 2019-03-05 07:03
@philrud got the ingress to work, let's wait for his input, I do not think we need to remove ingress.

**Comment by rshriram** [comment] 2019-03-05 15:03
lets remove it from the main install and docs.. While people get it to "work" for some definition, we have not tested it as extensively as the gateway. Since we have been gating other improvements (e.g., concurrency level, etc.) based on how extensively they have been tested, we should do the same for ingress - i.e. its 100% untested. Our defaults disable ingress. Scale issues are unknown, especially with the leader election thing in the client.

**Comment by sdake** [comment] 2019-03-05 16:06
how does someone migrate from ingress to ingressgateway?  The docs wg led by @geeknoid will need guidance...

**Comment by costinm** [comment] 2019-03-05 16:40
+1 on removing it from the main install. 

We did actually test ingress extensively - including with Certmanager and SDS, as well as multiple ingresses. However it is far better for anyone using k8s ingress to move to the new installer and not install ingress with the 'demo'-based installer.

**Comment by linsun** [comment] 2019-03-05 16:58
Thanks, I'll submit a PR for it shortly.

**Comment by philrud** [comment] 2019-03-05 17:05
From what I found over last couple of weeks: user experience with K8S Ingress has greatly improved since 1.0. I haven't found any functional issues besides what's known to be not supported. As @costinm mentioned Ingress + TLS + SDS + cert-manager now works pretty much out of the box, here's an "Example" of this (as part of the docs effort): https://github.com/istio/istio.io/pull/3498 (preview link: https://deploy-preview-3498--preliminary-istio.netlify.com/docs/examples/advanced-gateways/ingress-certmgr/)

We're not talking making this change for 1.1, are we? The new installer is right around the corner, I don't see what are we gaining by removing it now right ahead of the release.

**Comment by sdake** [comment] 2019-03-05 17:35
@philrud yes this is open for debate for 1.1.

I don't have a strong opinion, and everyone tells me ingress isn't qualified properly...  So I am more happy to delete code that isn't used and won't be.

Cheers
-steve

**Comment by rshriram** [comment] 2019-03-05 17:47
> From what I found over last couple of weeks: user experience with K8S Ingress has greatly improved since 1.0. I haven't found any functional issues besides what's known to be not supported. As @costinm mentioned Ingress + TLS + SDS + cert-manager now works pretty much out of the box, here's an "Example" of this (as part of the docs effort): istio/istio.io#3498 (preview link: https://deploy-preview-3498--preliminary-istio.netlify.com/docs/examples/advanced-gateways/ingress-certmgr/)

where the value we provide is just SDS plus some metrics for ingress? the user cannot use any other aspect of gateway or virtual service. No routing rules or any form of customization, for various reasons. IF these users start asking for the ability to customize, we will end up directing them to use the Gateways.

**Comment by duderino** [comment] 2019-03-06 00:11
Discussion from slack and comments on  https://github.com/istio/istio/pull/12259 say keep k8s ingress.

slack networking channel:

```
costin [10:04 AM]
New data... It seems Philip did actually test and has a doc PR.
My testing was all done in 'separate namespace' with the new installer.
So we have a choice to keep it - my preference is to still simplify the install and point to the new installer
But I'm also ok if Lin's instructions for 'only gateway' can be tested to work for ingress as well
And I can live with Philip's PR and leaving it in as well - my primary concern is that it's far better for users to have the ingress in separate namespaces and manage it separately
Also AFAIK most of Philip's testing was also done with 'separate namespace for ingress' scenario, and that's what the users are using.

Joshua Blatt [12:52 PM]
So what's the call here on k8s ingress?  Keep it because Phil had done a bunch of testing and updated the docs or scramble to drop it?

costin [1:24 PM]
I would say: leave it as is ( disabled by default ), since we know it works and minimizes risk for people who were using it in 1.0
But new documentation that Phils has should go with Lin's 'standalone gateway / different namespace' method of install
( or with the new installer - which is basically doing almost the same thing )
This way we double check Lin's standalone gateway setup as well, not sure how much testing it got
New problem: '''if nt.Type == model.Router && (nt.ServiceInstances == nil || len(nt.ServiceInstances) == 0) {
        return errors.New("gateway has no associated service instances")
    } - '''
With a clean install ( no options at all ) - it seems there is no Gateway created so Ingress gateway will crash loop until one is created.
Not a major problem I think
I mean not blocking - workaround is to just create a Gateway or not install the gateway if it won't be used.

costin [1:45 PM]
And it seems to recover.
So all good
```

**Comment by duderino** [comment] 2019-03-06 00:34
@philrud @sdake @xianke9 how can we close out this bug?  What needs to be doc'd?

**Comment by sdake** [comment] 2019-03-06 20:45
This bug can be closed.  I am unclear what needs to be documented.  I understand (someone) has a document on this topic - not sure where - not sure what state it is in.  @costinm had more context.

Cheers
-steve

**Comment by philrud** [comment] 2019-03-06 20:53
After this is merged: https://github.com/istio/istio/pull/12284 (remote old "ingress" from the installer, keep "k8sIngress"), we will need to remove "ingress.enabled" flag from the docs and mention in the release notes that "ingress.enabled" installer flag is obsolete and has been removed (in favor of gateways).

**Comment by sdake** [comment] 2019-03-06 21:47
@philrud is that handled by https://github.com/istio/istio.io/pull/3498?  ingress.enabled is used throughout the install codebase.  For some reason @costinm indicated this has indicated you ahve fixed this?

**Comment by philrud** [comment] 2019-03-06 22:15
@sdake looks like there are several conversations in different threads. Let me summarize everything here.

1. "ingress.enabled" != Kubernetes Ingress resource support
2. "ingress.enabled" is known to be broken and should not be used, we need to remove it. Here's a PR for this: https://github.com/istio/istio/pull/12284 (similar to your PR from yesterday, see the PR notes highlighting the key differences).
3. After that PR is merged, we will need to remote "ingress.gateway" installer flags from the Istio.io documentation, there's no PR for that yet, I can do it once 12284 is merged. Also we probably need to indicate that "ingress.enabled" flag is removed in the 1.1 release notes (not sure how to handle this one).
4. Kubernetes Ingress resource support works and is tested, it can be enabled via "global.k8sIngress.enabled" flag and will by default be handled by "ingressgateway" since https://github.com/istio/istio/pull/12284
5. This is documented in my docs PR that demonstrates the use of k8sIngress, this example does not rely on "ingress.enabled" (that is what's being removed): https://github.com/istio/istio.io/pull/3498

I think this is all there is to it. Let me know if this makes sense. Also would appreciate any help with getting those 2 PRs in. Thanks!

**Comment by sdake** [comment] 2019-03-06 22:37
thanks @philrud - we were struggling to understand the state of these things.

Cheers
-steve

**Comment by duderino** [comment] 2019-03-07 00:21
Remaining work here is captured in steps 3 and 5 from https://github.com/istio/istio/issues/12015#issuecomment-470299110 and these are both doc issues that will be done with @philrud

**Comment by duderino** [comment] 2019-03-11 18:34
Steps 3 and 5 are done.  @philrud can this now be closed?

**Comment by philrud** [comment] 2019-03-11 18:39
"ingress.*" flags are removed from 1.1 installer. related PRs:
* https://github.com/istio/istio/pull/12284
* https://github.com/istio/istio.io/pull/3588
* https://github.com/istio/istio.io/pull/3558
closing this one if nobody has any objections

**Closed** 2019-03-11 18:40 UTC
Labels: area/environments
