### ISSUE TITLE
Mixer report to mixer does not work with V2

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#5414] opened 2018-05-04 16:56 UTC
With v1, no matter control plane auth enabled or not, all check and report calls goes through mixer sidecars (port 15004) and mixer internal metrics will be available.

With v2, behavior changes to that traffic will only go through sidecar if auth is enabled. Non-auth traffic goes directly to mixer port (9091), which causes mixer metrics unavailable and MixerReportsToMixer e2e test failure.

cc @douglas-reid @kyessenov @ostromart @costinm @rshriram

**Comment by kyessenov** [comment] 2018-05-04 17:58
Yes, thanks for confirming. Can we please not route through port 9091? Non-auth traffic needs to go through a proxy enabled port. Why can't we use the same port 15004?

**Comment by douglas-reid** [comment] 2018-05-05 00:05
I have the same question as @kyessenov : why can't we use the same port any more? This seems like a regression and, naively, an arbitrary one as well.

If we can't use the same port, then we need to add the right listeners for the non-auth port.

@hklai why is this a 1.0 target and not a 0.8 target? this was working. we shouldn't turn features off for other features.

**Comment by hklai** [comment] 2018-05-05 00:31
@douglas-reid as discussed in the code orange meeting this does not block 0.8.0, so I just added this to 1.0.

If this is intended for 0.8.1, we can change it to 0.8.

**Comment by costinm** [comment] 2018-05-05 01:04
We can't use port 15004 because there are no certificates - that's the port
with TLS enabled, and if auth is off
there are no certs.

Open another port that is proxied and plain text - and we can use it.

**Comment by costinm** [comment] 2018-05-05 01:06
And the change is due to using regular EDS and CDS for mixer - which follow
the global auth
setting, so all clusters (unless explicitly set) will follow the data plane
auth policy. So when
MTLS is disabled - we need a non-TLS port to connect to.

**Comment by kyessenov** [comment] 2018-05-05 01:43
It seems that if this is a bug fix, it should not have been forced by pilot config, but verified end-to-end. I also don't see how this is going to play nice with CDS generating a single mixer cluster.

**Comment by kyessenov** [comment] 2018-05-05 01:49
We need to communicate better about formal deprecation of control plane auth setting. It sounds like that got removed in favor of data plane auth setting, but we only discover it post-factum, intentionally causing a regression.

**Comment by costinm** [comment] 2018-05-05 06:07
What are you talking about ? CDS generates clusters the same for all
services and destinations - one cluster
for each service+port, based on settings from destinationpolicy and
defaulting to the global auth policy.

If mixer doesn't want to use the normal clusters - it can define a custom
cluster in the bootstrap,
like it had before. Whoever implemented/reviewed the mixer in v2 believed
it's cleaner to not do
one-offs - and I think it was the right decision. But if the mixer team
feels more complexity is needed
or need special code - send a PR.

I don't really see anything wrong here - the mixer plugin can pick any
cluster, and you can use
destination policy if you believe mixer should only be accessible via TLS.

The use case of gradual adoption ('a la carte') has been communicated for a
long time - and
everyone should expect and support a mixed environment.

**Comment by douglas-reid** [comment] 2018-05-05 11:43
@hklai @costinm I obviously have not been able to attend Code Orange meetings this week. However, the ability for Mixer to report to Mixer was an existing feature for over a month. We've talked about publicly and coordinated with other teams on this ability.  Whatever conversion to v2 happened _should_ have included support for _existing_ features.

I feel quite strongly that it should be included in the 0.8 release.

**Comment by douglas-reid** [comment] 2018-05-05 11:47
@bianpengyuan / @kyessenov : it sounds like the fix is simple-ish.  Is it just a matter of duplicating the filter stuff in an additional listener?

Can we do that first, and then figure out how we want things to work properly subsequently?

**Comment by mandarjog** [comment] 2018-05-05 11:58
I think we need to reconcile these two streams of thought. Does mixer require an envoy in front for proper functioning or not.

If mtls is implemented in mixer then envoy is not needed. 

That said we can add an envoy listener on 9091 and ensure that mixer only binds to local host and then we are good.
So fix is easy.

**Comment by douglas-reid** [comment] 2018-05-05 12:06
@mandarjog let's please not decide to start reimplementing envoy in mixer right now. I think that is too big an architectural change and will be controversial at best.

I think the easy fix of 9091 listener (or whatever) is the correct approach.

@hklai et. al: I want to stress that Mixer telemetry collection (which Mixer reporting to Mixer provides) is P0 for 1.0 and was considered "Beta" status for May. Turning it off entirely and waiting for 1.0 is not acceptable.

**Comment by douglas-reid** [comment] 2018-05-05 15:57
@hklai - one other point to consider: this feature is already mentioned prominently in the 0.8 release notes. See here: [0.8 Release Notes - Telemetry](https://preliminary.istio.io/about/notes/0.8.html#telemetry).

I know that the decision to not have it in 0.8 was made with the best of intentions. However, from the outside, it feels that it was made without full information, or was made motivated by expediency rather than from principles.

I considered this feature to be in the Beta stage. This carries the following promise according to: https://github.com/istio/community/blob/master/FEATURE-LIFECYCLE.md

> The overall feature will not be dropped, though details may change.

I'd rather we not play semantic games around `details changing` and `dropped`, or even what is considered Beta. This should be in 0.8.

The fix should be straightforward and easily testable.

Please reconsider its inclusion.

**Comment by kyessenov** [comment] 2018-05-06 00:29
@costinm let me understand what you are saying, and correct me if I'm wrong.
We have two features that we want to ship. Feature 1 is istio-on-istio telemetry -- meaning mixer adapters can take advantage of new data coming to mixer from pilot/mixer. Feature 2 is "gradual adoption", which I presume means ability to have a mixed deployment in which half of the mesh is using mTLS, but half is not. 

Feature 1 needs to remain throughout any changes necessary to pilot or mixer such as moving to another envoy protocol. Otherwise, it's a clear regression, and whatever introduced the regression needs to be fixed or rolled back.

Feature 2 is also important, but it cannot come at the expense of feature 1. It's actually not very relevant to this discussion I think, since it can be implemented in parallel to feature 1. The implementation for feature 2 needs to provide a solution for 1) what to do with control plane auth enabled flag; 2) what to do with check_report_server setting since it is a single global value for both halves of the mesh. Using hard-coded ports or port-names is again, a regression, since the port is not fixed in the deployment.

Please do not fix the two discussions. It's not helping to gain clarity.

**Comment by ldemailly** [comment] 2018-05-06 16:02
We should not be doing mTLS in mixer

**Comment by hklai** [comment] 2018-05-07 01:06
@douglas-reid Do you think this is blocking 0.8.0, or this should be in 0.8.x eventually? I believe we concluded this was not blocking 0.8.0 as nobody needed/relied on this for 0.8.0. If you think otherwise, I can add the blocking release label and discuss this in the code orange meeting.

@bianpengyuan do you have ETA when this can be resolved?

**Comment by costinm** [comment] 2018-05-07 14:47
I still don't understand the big storm in the teacup...

Mixer was completely broken with v2 just 2 weeks ago (since the old v1
params
no longer worked - I'm still not sure how this happened ). Auth finally
started
 to work late last week. We spent a hellish week dealing with the flaky
tests.

Is the biggest problem adding a new port in mixer service with envoy in
front of it ???

From networking perspective the requirement was to use CDS/EDS for
connecting
to mixer instead of the old bootstrap config and cluster IP. This allows
any service
to do whatever it wants with its ports - and use the standard config to
enable
TLS or use any other routing feature. Pilot doesn't really care how the
service
is implemented or if it collects metrics or not.

Using envoy in front of mixer or not is primarily between the perf and
mixer teams.
As long as Laurent (or mixer team) have some data confirming policy check
latency
are not regressing - or there is some way for users to chose latency or
extra metrics
- I don't see a problem with adding envoy or not.

**Comment by wattli** [comment] 2018-05-07 18:26
@costinm , why we don't have cert for mixer? The cert is generated by istio citadel and should be there

**Comment by costinm** [comment] 2018-05-07 18:53
We have a cert for mixer, and it has both Spiffe and DNS SANs.
I think there was some confusion about the 'authority' - it's not a cert
issue.

**Comment by mandarjog** [comment] 2018-05-10 12:52
This should be resolved by #5370

**Comment by mandarjog** [comment] 2018-05-10 13:26
@ostromart where is this test running ?

**Comment by hklai** [comment] 2018-05-17 21:41
@mandarjog any update? did you get a chance to verify?

**Comment by bianpengyuan** [comment] 2018-05-17 23:12
@hklai I am verifying this.

**Comment by bianpengyuan** [comment] 2018-05-18 00:59
MixerReportingToMixer passed with v2. Created a PR to remove bypass logic.

**Closed** 2018-05-18 16:17 UTC
Labels: area/policies and telemetry, kind/blocking release
