### ISSUE TITLE
creating gateways times out on clean install

### ISSUE THREAD

**Issue by stephen-dahl** [istio/istio#10815] opened 2019-01-08 23:23 UTC
**Describe the bug**
creating gateways times out on a clean install

**Steps to reproduce the bug**
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
kubectl apply -f .\samples\helloworld\helloworld.yaml
service "helloworld" created
deployment.extensions "helloworld-v1" created
deployment.extensions "helloworld-v2" created
Error from server (Timeout): error when creating ".\\samples\\helloworld\\helloworld.yaml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when creating ".\\samples\\helloworld\\helloworld.yaml": Timeout: request did not complete within allowed duration
```

**Version**
Istio 1.0.5
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3",
Compiler:"gc", Platform:"windows/amd64"}neties>Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
helm

**Environment**
AWS EKS

**Comment by douglas-reid** [comment] 2019-01-09 21:00
@stephen-dahl there have been reports of issues on AWS EKS before that may be related. If you have a chance, you may consider trying with a 1.1 snapshot release, setting the mixer option of "useAdapterCRDs" to "false" to see if that helps.

**Comment by stephen-dahl** [comment] 2019-01-09 22:33
after more digging, I found it is timing out trying to run the sidekick injection hook also. EKS is supposed to support mutation hooks now. I will try with the 1.1

**Comment by clyang82** [comment] 2019-01-10 14:20
FYI @morvencao

**Comment by stephen-dahl** [comment] 2019-01-10 15:44
@douglas-reid I was not able to find the "useAdapterCRDs" setting in values.yaml is it a helm configuration? if not where do I set it?

**Comment by stephen-dahl** [comment] 2019-01-10 17:36
found the pull request that adds useAdapterCRDs I'm guessing that it is not a part of any of the snapshots, it is only on the 1.1 branch

**Comment by stephen-dahl** [comment] 2019-01-10 19:15
put this in my values file and helm installed with the release-1.1 branch. still same result.
```
mixer:
  adapters:
    useAdapterCRDs: false
```

**Comment by stephen-dahl** [comment] 2019-01-10 19:17
`kubectl get deployments -o yaml`
```
...
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:io
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"helloworld-v1","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"helloworld","version":"v1"}},"spec":{"containers":[{"image":"istio/examples-helloworld-v1","imagePullPolicy":"IfNotPresent","name":"helloworld","ports":[{"containerPort":5000}],"resources":{"requests":{"cpu":"100m"}}}]}}}}steph\PhpstormProjects\istio-1.0.3>
    creationTimestamp: 2019-01-10T19:12:54Z
    generation: 1
    labels:
      app: helloworld
      version: v1
    name: helloworld-v1
    namespace: default
    resourceVersion: "9257"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/helloworld-v1
    uid: bb438b63-150b-11e9-8b11-06307125b3b2
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: helloworld
        version: v1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: helloworld
          version: v1
      spec:
        containers:
        - image: istio/examples-helloworld-v1
          imagePullPolicy: IfNotPresent
          name: helloworld
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: 2019-01-10T19:12:54Z
      lastUpdateTime: 2019-01-10T19:12:54Z
      message: Created new replica set "helloworld-v1-c64bc46f5"
      reason: NewReplicaSetCreated
      status: "True"
      type: Progressing
    - lastTransitionTime: 2019-01-10T19:12:54Z
      lastUpdateTime: 2019-01-10T19:12:54Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2019-01-10T19:13:24Z
      lastUpdateTime: 2019-01-10T19:13:24Z
      message: 'Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io":
        Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s:
        net/http: request canceled while waiting for connection (Client.Timeout exceeded
        while awaiting headers)'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    observedGeneration: 1
    unavailableReplicas: 1
...
```

**Comment by douglas-reid** [comment] 2019-01-10 19:18
@stephen-dahl OK. Thanks for trying. 

It looks like you are having issues reaching the sidecar injector webhook. What is the state of that pod in your `istio-system` namespace ?

**Comment by douglas-reid** [comment] 2019-01-10 19:19
/assign @ayj 

Jason, it looks like the sidecar-injector webhook is having issues. Would you mind taking a look?

**Comment by stephen-dahl** [comment] 2019-01-10 19:20
the pods where find when i was running on 1.0.5 looks like problems with some in this branch
```
kubectl get pods -n istio-system
NAME                                      READY     STATUS             RESTARTS   AGE
istio-citadel-67cd9b9955-mr2vk            1/1       Running            0          7m
istio-egressgateway-664b74cc59-2vtd8      1/1       Running            0          7m
istio-galley-568ffcbd4c-nmpt5             0/1       CrashLoopBackOff   4          7m
istio-ingressgateway-78458c6fb-8b6v7      1/1       Running            0          7m
istio-pilot-645c7d777c-6bkl5              1/2       Running            0          7m
istio-policy-75f67d857d-ccwhr             1/2       CrashLoopBackOff   7          7m
istio-sidecar-injector-7876c6cc75-57tgr   1/1       Running            0          7m
istio-telemetry-59947698d4-vtppq          1/2       CrashLoopBackOff   7          7m
prometheus-d8666f8d5-nm8k2                1/1       Running            0          7m
```

**Comment by stephen-dahl** [comment] 2019-01-10 19:59
in 1.0.5
```
kubectl create -f install/kubernetes/namespace.yaml
```
```
helm install --name=istio --namespace=istio-system install/kubernetes/helm/istio
```
```
kubectl get svc -n istio-system
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP        PORT(S)                                                                                                                   AGE
istio-citadel            ClusterIP      172.20.167.208   <none>             8060/TCP,9093/TCP                                                                                                         12m
istio-egressgateway      ClusterIP      172.20.130.221   <none>             80/TCP,443/TCP                                                                                                            12m
istio-galley             ClusterIP      172.20.50.89     <none>             443/TCP,9093/TCP                                                                                                          12m
istio-ingressgateway     LoadBalancer   172.20.80.194    a223afd04150f...   80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:31576/TCP,8060:30721/TCP,853:30318/TCP,15030:30419/TCP,15031:30295/TCP   12m
istio-pilot              ClusterIP      172.20.22.208    <none>             15010/TCP,15011/TCP,8080/TCP,9093/TCP                                                                                     12m
istio-policy             ClusterIP      172.20.219.141   <none>             9091/TCP,15004/TCP,9093/TCP                                                                                               12m
istio-sidecar-injector   ClusterIP      172.20.240.59    <none>             443/TCP                                                                                                                   12m
istio-telemetry          ClusterIP      172.20.30.89     <none>             9091/TCP,15004/TCP,9093/TCP,42422/TCP                                                                                     12m
prometheus               ClusterIP      172.20.7.13      <none>             9090/TCP 
```
```
kubectl get pods -n istio-system
NAME                                     READY     STATUS    RESTARTS   AGE
istio-citadel-7dd558dcf-24zv8            1/1       Running   0          7m
istio-egressgateway-88887488d-8psm8      1/1       Running   0          7m
istio-galley-787758f7b8-2sbjm            1/1       Running   0          7m
istio-ingressgateway-58c77897cc-79h4g    1/1       Running   0          7m
istio-pilot-868cdfb5f7-spcqt             2/2       Running   0          7m
istio-policy-56c4579578-llxrv            2/2       Running   0          7m
istio-sidecar-injector-d7f98d9cb-tdlgr   1/1       Running   0          7m
istio-telemetry-7fb48dc68b-sfwl9         2/2       Running   0          7m
prometheus-76db5fddd5-vc6t9              1/1       Running   0          7m
```
```
kubectl label namespace default istio-injection=enabled
namespace "default" labeled
```
```
kubectl get namespace -L istio-injection
NAME           STATUS    AGE       ISTIO-INJECTION
default        Active    1h        enabled
istio-system   Active    53m       disabled
kube-public    Active    1h
kube-system    Active    1h
```
```
kubectl apply -f .\samples\helloworld\helloworld.yaml
service "helloworld" created
deployment.extensions "helloworld-v1" created
deployment.extensions "helloworld-v2" created
Error from server (Timeout): error when creating ".\\samples\\helloworld\\helloworld.yaml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when creating ".\\samples\\helloworld\\helloworld.yaml": Timeout: request did not complete within allowed duration
```
```
kubectl describe -f .\samples\helloworld\helloworld.yaml
Name:              helloworld
Namespace:         default
Labels:            app=helloworld
Annotations:       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"helloworld"},"name":"helloworld","namespace":"default"},"spec":{"port...
Selector:          app=helloworld
Type:              ClusterIP
IP:                172.20.16.250
Port:              http  5000/TCP
TargetPort:        5000/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>


Name:                   helloworld-v1
Namespace:              default
CreationTimestamp:      Thu, 10 Jan 2019 11:56:02 -0800
Labels:                 app=helloworld
                        version=v1
Annotations:            deployment.kubernetes.io/revision=1
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"helloworld-v1","namespace":"default"},"spec":{"replicas":1,...
Selector:               app=helloworld,version=v1
Replicas:               1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  app=helloworld
           version=v1
  Containers:
   helloworld:
    Image:      istio/examples-helloworld-v1
    Port:       5000/TCP
    Host Port:  0/TCP
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Progressing      True    NewReplicaSetCreated
  Available        True    MinimumReplicasAvailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     helloworld-v1-c64bc46f5 (0/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  2m    deployment-controller  Scaled up replica set helloworld-v1-c64bc46f5 to 1


Name:                   helloworld-v2
Namespace:              default
CreationTimestamp:      Thu, 10 Jan 2019 11:56:02 -0800
Labels:                 app=helloworld
                        version=v2
Annotations:            deployment.kubernetes.io/revision=1
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"helloworld-v2","namespace":"default"},"spec":{"replicas":1,...
Selector:               app=helloworld,version=v2
Replicas:               1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  app=helloworld
           version=v2
  Containers:
   helloworld:
    Image:      istio/examples-helloworld-v2
    Port:       5000/TCP
    Host Port:  0/TCP
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Progressing      True    NewReplicaSetCreated
  Available        True    MinimumReplicasAvailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     helloworld-v2-6489d9fb5 (0/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  2m    deployment-controller  Scaled up replica set helloworld-v2-6489d9fb5 to 1
Error from server (NotFound): gateways.networking.istio.io "helloworld-gateway" not found
Error from server (NotFound): virtualservices.networking.istio.io "helloworld" not found
```

**Comment by stephen-dahl** [comment] 2019-01-10 21:32
It looks like this is a problem with my cluster setup. I was having the problem on a terraform setup that I wrote myself. I just tried again using `eksctl` and everything works. are there any extra required ports or something like that that could be causing this?

**Comment by ayj** [comment] 2019-01-18 18:25
Closing this issue as it seems to be caused by an environment setup issue.

@stephen-dahl, you might try checking your environments no_proxy setting:

https://github.com/kubernetes/kubeadm/issues/666
https://github.com/kubernetes/kubernetes/pull/58698#discussion_r163879443

**Closed by ayj** 2019-01-18 18:25 UTC
Labels: area/environments, area/networking, area/perf and scalability

**Comment by gregdurham** [comment] 2019-02-26 20:35
For those running into this with EKS (side car injection) and are using Terraform to provision the cluster, I found that the issue for me, was that you needed to allow the kubernetes master access to the worker node on 443. Basically, you create another security group rule allowing this, and it resolved the issue for me. Hopefully this is helpful to someone.

**Comment by chris530** [comment] 2019-11-01 19:18
@gregdurham   thank you !   Finally istio pod injection works in EKS

**Comment by gregdurham** [comment] 2019-11-01 20:33
@chris530 np! Glad I could be of some help :)
