### ISSUE TITLE
Test Flake (general): Prometheus pod is failing to start

### ISSUE THREAD

**Issue by ozevren** [istio/istio#11593] opened 2019-02-07 17:17 UTC
https://circleci.com/gh/istio/istio/318829?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The failure is in e2e-galley test, but it is caused by Prometheus pod not starting.

We have seen this failure a couple of times when investigating some flakes.

**Comment by douglas-reid** [comment] 2019-02-07 17:20
@bianpengyuan can you take a look?  this seems like it might be related to the recent changes to Prom readiness ?

**Comment by douglas-reid** [comment] 2019-02-07 18:45
BTW, I'm seeing this failure to initialize in a number of PRs and not limited strictly to the Prometheus pod.

**Comment by bianpengyuan** [comment] 2019-02-07 19:26
I don't think prom-init container is the culprit. Its behavior is deterministic (check existence of certs file) and should not introduce any flake. In fact, while investigating the issue, I found a issue that prom-init container will always pass even when secret is not ready. So I suspect this is more of a general test-infra issue.

**Comment by esnible** [comment] 2019-02-10 17:05
Happened for me this morning on https://circleci.com/gh/istio/istio/321930

"Failed to complete Init. Error context deadline exceeded" caused by Prometheus getting stuck in `0/1       Init:0/1   0          16m`.  The build attempts `Running command kubectl logs prometheus-68896c5775-5rtm6 -n istio-system -c prometheus --kubeconfig=` which fails with `Command error: exit status 1` and of course there are no logs in Init:0/1.

I propose that `FetchAndSaveClusterLogs()` should do `kubectl describe` in additional to `kubectl logs`.  Perhaps for every pod but definitely for the pods that failed `kubectl logs`.

**Comment by esnible** [comment] 2019-02-15 13:22
Happened for me this morning in https://circleci.com/gh/istio/istio/326914 .  @GregHanson are you the test-watcher this month?  How about the idea I proposed above, having FetchAndSaveClusterLogs() record pod status so we can see why Prometheus is getting stuck?

**Comment by esnible** [comment] 2019-02-28 18:55
@ozevren Please let's merge https://github.com/istio/istio/pull/11904 so we can get descriptions of why the non-starting pods aren't starting.

**Comment by douglas-reid** [comment] 2019-05-13 19:02
Since https://github.com/istio/istio/pull/13571, I have not seen evidence that this issue persists.

Last report was 2 months ago.

Closing. Please re-open if issue persists.

**Closed by douglas-reid** 2019-05-13 19:02 UTC
Labels: code mauve, kind/test failure
