### ISSUE TITLE
istio-ingressgateway HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by zhaojizhuang** [istio/istio#29643] opened 2020-12-15 12:06 UTC
**Bug description**

After installed with `istio-operator`, istio-ingressgateway  `Readiness probe failed: HTTP probe failed with statuscode: 503`

**Part of ingress-gateway'logs as follows:**

```shell
2020-12-15T11:42:02.776767Z	info	xdsproxy	disconnected from XDS server: istiod.faas.svc:15012
2020-12-15T11:42:02.777000Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 0,
2020-12-15T11:42:02.879287Z	info	xdsproxy	Envoy ADS stream established
2020-12-15T11:42:02.879395Z	info	xdsproxy	connecting to upstream XDS server: istiod.faas.svc:15012
2020-12-15T11:42:02.901418Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8081: duplicate listener 0.0.0.0_8081 found

2020-12-15T11:42:02.910663Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:04.910742Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:06.910657Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:08.910624Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:10.910725Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:12.910757Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:14.910725Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:16.910757Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:18.910651Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:20.910791Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:22.910689Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:24.910675Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:26.910711Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:28.910725Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:30.910734Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:32.910649Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
2020-12-15T11:42:34.910679Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds 
```

[x] Networking

**Expected behavior**
ingress-gateway works well

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**
`istio-operator`

**version:1.8.1**

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: faas
spec:
  values:
    global:
      istioNamespace: faas
      hub: registry.zjcdn.com/public/istio
      tag: 1.8.1
      imagePullPolicy: IfNotPresent
      proxy:
        clusterDomain: bdcdn-gyct
      trustDomain: bdcdn-gyct

```

**Environment where the bug was observed (cloud vendor, OS, etc)**

```shell
root@admin01.jzct:~/faas/faas_deploy# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment] 2020-12-15 15:39
Can you post more info about your config (services, service entry, gateway, vs) on port 8081 and get a config dump (https://github.com/istio/istio/wiki/Troubleshooting-Istio)? or fill out http://istio.io/help/bugs/#generating-a-cluster-state-archive

**Comment by shenkonghui** [comment] 2020-12-16 09:14
I have encountered this problem many times. There are the following reasons.
1. No service created select this pod
2. Too many global services, causing performance problems

The first reason is to create a pod.
If you have a lot of services, more than 5000, this problem may occur.

You can use the following command to verify.
```
[root@os311 ~]# kubectl get ep --all-namespaces |wc -l
5134
```
This is because each istio-proxy needs to pull the global configuration, resulting in poor performance, mainly due to insufficient cpu. You need to give at least 0.5 core or more CPU.
Another method is to set namespace isolation and configure sidecar.
Like this
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: istio-config
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
```

When istio-proxy starts, it will only get the current namespace and kube-system configuration.

Hope to solve your problem!

**Comment by zhaojizhuang** [comment] 2020-12-17 08:16
> Can you post more info about your config (services, service entry, gateway, vs) on port 8081 and get a config dump (https://github.com/istio/istio/wiki/Troubleshooting-Istio)? or fill out http://istio.io/help/bugs/#generating-a-cluster-state-archive

I reinstall use a lower version istio,and 501 not exists,but facing a `envoy not listen 8080 in istio-ingressgateway` problem #29680

**Comment by howardjohn** [comment] 2020-12-17 15:41
Can you please provide the config on port 8081?

**Comment by howardjohn** [comment] 2021-02-10 17:22
I think this is a duplicate of https://github.com/istio/istio/issues/29291. Thanks

**Closed by howardjohn** 2021-02-10 17:22 UTC
Labels: area/networking, kind/need more info
