### ISSUE TITLE
Default HTTP route retry policy calls a non-idempotent service two times with a single request

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#27340] opened 2020-09-16 03:41 UTC
**Bug description**

Pilot adds a default retry policy to HTTP routes, which can potentially call a non-idempotent service two times with a single request.  Event though retries only happen when the connection fails or an error response by the server, the server may have already done some modification on its state. In this case, it's better to let the downstream decide whether it should retry or not.

[ ] Docs
[ ] Installation
[*] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

We should not add the default retry policy, or at least it can be turned off.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

1.7

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment] 2020-10-20 19:07
Closing as a duplicate of https://github.com/istio/istio/issues/13851

**Closed by howardjohn** 2020-10-20 19:07 UTC
