### ISSUE TITLE
Flaky Test: CircleCI e2e-pilot-auth-v1alpha3-v2

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7863] opened 2018-08-13 15:44 UTC
https://circleci.com/gh/istio/istio/155069?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
=== RUN   TestHttp/request/b_from_primary_cluster->d.istio-system_80
=== RUN   TestHttp/request/b_from_primary_cluster->d_8080
=== RUN   TestHttp/request/b_from_primary_cluster->d.istio-system_8080
=== RUN   TestHttp/request/t_from_primary_cluster->a_
2018-08-12T00:26:21.013119Z	error	client request error command failed: "2018/08/12 00:26:21 [0] Url=http://a:/t\n2018/08/12 00:26:21 Error Get http://a/t: read tcp 172.17.0.3:35846->10.99.75.33:80: read: connection reset by peer\ncommand terminated with exit code 1\n" exit status 1 for http://a:/t in t from primary cluster
=== RUN   TestHttp/request/t_from_primary_cluster->a.istio-system_
2018-08-12T00:26:21.359576Z	error	client request error command failed: "2018/08/12 00:26:21 [0] Url=http://a.istio-system:/t\n2018/08/12 00:26:21 Error Get http://a.istio-system/t: read tcp 172.17.0.3:35862->10.99.75.33:80: read: connection reset by peer\ncommand terminated with exit code 1\n" exit status 1 for http://a.istio-system:/t in t from primary cluster
=== RUN   TestHttp/request/t_from_primary_cluster->a_80
2018-08-12T00:26:21.647043Z	error	client request error command failed: "2018/08/12 00:26:21 [0] Url=http://a:80/t\n2018/08/12 00:26:21 Error Get http://a:80/t: read tcp 172.17.0.3:35874->10.99.75.33:80: read: connection reset by peer\ncommand terminated with exit code 1\n" exit status 1 for http://a:80/t in t from primary cluster

```

**Comment by ozevren** [comment] 2018-08-13 15:45
```
        --- PASS: TestHttp/request/a_from_primary_cluster->b.istio-system_80 (0.34s)
        --- PASS: TestHttp/request/a_from_primary_cluster->b_8080 (0.48s)
        --- PASS: TestHttp/request/a_from_primary_cluster->b.istio-system_8080 (0.32s)
        --- FAIL: TestHttp/request/a_from_primary_cluster->headless_ (12.81s)
        	pilot_test.go:145: try again
        --- FAIL: TestHttp/request/a_from_primary_cluster->headless.istio-system_ (12.42s)
        	pilot_test.go:145: try again
        --- FAIL: TestHttp/request/a_from_primary_cluster->headless_80 (12.87s)
        	pilot_test.go:145: try again
        --- FAIL: TestHttp/request/a_from_primary_cluster->headless.istio-system_80 (12.35s)
        	pilot_test.go:145: try again
        --- FAIL: TestHttp/request/a_from_primary_cluster->headless_8080 (13.09s)
        	pilot_test.go:145: try again
        --- FAIL: TestHttp/request/a_from_primary_cluster->headless.istio-system_8080 (12.81s)
        	pilot_test.go:145: try again
        --- PASS: TestHttp/request/a_from_primary_cluster->d_ (0.32s)
        --- PASS: TestHttp/request/a_from_primary_cluster->d.istio-system_ (0.37s)
        --- PASS: TestHttp/request/a_from_primary_cluster->d_80 (0.41s)
        --- PASS: TestHttp/request/a_from_primary_cluster->d.istio-system_80 (0.39s)
```

**Comment by esnible** [comment] 2018-12-17 14:47
I have been watching the failures of this for the last 10 days.

Status:

Almost always the failures have been "container \"citadel\" in pod \"istio-citadel-69d6674759-hxl6s\" is waiting to start: trying and failing to pull image\n" exit status 1".  All of the pods in the istio-system namespace have this problem.  I suspect a race condition between jobs on the same CircleCI machine or problems with the registry there.  These failure runs always take between 12-15 minutes.  (Successful builds always took 15-19.)

During this time a single failure case with actual tests being flaky happened.  This run took nearly 20 minutes.  The failures were with pilot TestTcpNonHeadlessPorts and 5 others.  Because all failures happened in the same failed run I suspect some setup failed.  Unfortunately I didn't notice until two days later and the logs were already gone.

Continuing to monitor and diagnose.

**Comment by sdake** [comment] 2019-01-06 08:07
@esnible confirmed tonight while I was debuugging other gate failures:

```
++ cat /proc/sys/net/ipv4/ip_forward
+ echo 'IP forwarding setting: 0'
IP forwarding setting: 0
```
https://circleci.com/gh/istio/istio/282475?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

nice find!

**Comment by smawson** [comment] 2019-01-11 18:17
What's the status on the fix for these issues?

**Comment by linsun** [comment] 2019-01-14 20:03
status update from Ed:  I am actively monitoring Gubernator and will close that issue when I have some confirmation.  Strangely over the weekend all release-1.1 builds succeeded and 1/3 of the release-1.0 builds that don’t have the proposed fix failed.  But I can’t confirm my fix is the reason.
I have not forgotten the issue.

**Comment by esnible** [comment] 2019-01-15 19:55
Closing.  These problems stopped happening on release-1.1 builds after the change.

If there is interest we can update the release-1.0 branch.  However the script should eventually turn on the IPv4 forwarding on all the build machines so that may be unneeded.

**Closed** 2019-01-18 17:45 UTC
Labels: area/networking, kind/test failure
