### ISSUE TITLE
VirtualService error logging

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#5016] opened 2018-04-17 18:51 UTC
The current error handling for virtual services does not give enough information about what the issue is. Due to having a large virtual service with lots of matches its not easy to tell where i went wrong. I have over 40 clusters currently configured and this is the error i get when applying the VirtualService

```
error_detail:<code:13 message:"route: unknown cluster 'unresolved-cluster'" >
```

**Comment by linsun** [comment] 2018-04-17 19:01
@GregHanson could you help check this?  Could we print more meaningful messages for the user?

Also, do we have an istioctl tool to validate user's virtual service yaml file?

cc @esnible @ijsnellf @frankbu @ZackButcher @costinm @rshriram

**Comment by ijsnellf** [comment] 2018-04-17 19:27
Here is the code that is generating the `unresolved-cluster` cluster name:
```go
// ConvertDestinationToCluster produces a cluster naming function using the config context.
func ConvertDestinationToCluster(
	serviceIndex map[string]*model.Service,
	defaultPort int) ClusterNameGenerator {
	return func(destination *networking.Destination) string {
		// detect if it is a service
		svc := serviceIndex[destination.Host]

		// TODO: create clusters for non-service hostnames/IPs
		if svc == nil {
			return UnresolvedCluster
		}

		// default port uses port number
		svcPort, _ := svc.Ports.GetByPort(defaultPort)
		if destination.Port != nil {
			switch selector := destination.Port.Port.(type) {
			case *networking.PortSelector_Name:
				svcPort, _ = svc.Ports.Get(selector.Name)
			case *networking.PortSelector_Number:
				svcPort, _ = svc.Ports.GetByPort(int(selector.Number))
			}
		}

		if svcPort == nil {
			return UnresolvedCluster
		}

		// use subsets if it is a service
		return model.BuildSubsetKey(model.TrafficDirectionOutbound, destination.Subset, svc.Hostname, svcPort)
	}
}
```
It looks like there is a missing service (perhaps a missing ExternalService definition) or a missing port.

**Comment by ijsnellf** [comment] 2018-04-17 19:32
@linsun: we validate config structure, but we don't check references. Specifically, somewhere in the config there is a routing destination without a corresponding service in the registry (or a service that is missing a port).

**Comment by ijsnellf** [comment] 2018-04-17 19:49
The validation logic for virtual services isn't being tested properly. There aren't any tests: https://github.com/istio/istio/blob/master/pilot/pkg/model/validation_test.go

**Comment by linsun** [comment] 2018-04-17 19:53
Thank you @ijsnellf for looking into this!  Yes, it would be great if we can add logging to tell user exactly which one(s) have issue.

**Comment by ijsnellf** [comment] 2018-04-17 22:33
Some of the virtual service route destinations were missing the `host` field. This is checked for by the validation code, but the error was being eaten because of a bug. https://github.com/istio/istio/pull/5027 should fix the issue (though it won't help with the limited context provided by errors).

**Comment by ZackButcher** [comment] 2018-04-17 22:48
I just updated this code while implementing SNI to add better errors as I got tripped up by exactly the same issue while testing Gateways:

https://github.com/istio/istio/blob/7b26e4a6cb3f0023f19886ecf2b04b885f1419da/pilot/pkg/networking/core/v1alpha3/route/route.go#L158-L191

I believe that now all call sites will log when they get an error, though in every place but Gateways we'll still build a route with an unresolved cluster name (I was preserving the existing behavior). I'd be fine with just not emitting unresolved clusters across the board; as long as we have cluster validation enabled (=> Envoy rejects updates with unresolved clusters) we might as well IMO.

**Comment by nmnellis** [comment] 2018-04-18 00:05
@ZackButcher do you think we can consider this one resolved or is there more error handling/printing that is needed?

**Comment by costinm** [comment] 2018-04-20 21:04
Users don't read pilot logs - even if  they did, many errors are lost in the noise.

We need a map or list of errors since the last cache invalidation/update, with a handler to return the list, and some counters that prometheus/grafana can show.

**Comment by rshriram** [comment] 2018-05-11 03:37
Most of this code will be invalid now with #5543. Blackhole clusters won’t occur much, except for user mid configuration

**Comment by liamawhite** [comment] 2018-06-12 20:13
Based on comments in this issue I'm going to close. Please re-open if the issue is still present in 0.8+.

**Closed by liamawhite** 2018-06-12 20:13 UTC
Labels: area/networking
