### ISSUE TITLE
Quick Start on Docker: Unable to read certificates for pilot

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [istio/istio#12024] opened 2019-02-25 15:47 UTC
**Describe the bug**
When following the [quick start guide](https://preliminary.istio.io/docs/setup/consul/quick-start/#installation-steps), the pilot will exit directly after start with the error log

```
2019-02-25T15:25:28.802876Z	info	ads	Starting ADS server with rateLimiter=10 burst=100
Error: failed to create discovery service: discovery service: secure grpc server: open /etc/certs/cert-chain.pem: no such file or directory
2019-02-25T15:25:28.803183Z	error	failed to create discovery service: discovery service: secure grpc server: open /etc/certs/cert-chain.pem: no such file or directory
```

We also executed step 5, but this didn't change anything.
```
kubectl config set-context istio --cluster=istio
kubectl config set-cluster istio --server=http://localhost:8080
kubectl config use-context istio

```

**Expected behavior**
Expect pilot to start and not exit immediately.

**Steps to reproduce the bug**
Follow described [steps](https://preliminary.istio.io/docs/setup/consul/quick-start/#installation-steps) 

**Version**
Istio 1.1.0-rc.0 (osx version)

**Installation**
see quick start guide

**Environment**
OSX

**Comment by c0d1ngm0nk3y** [comment] 2019-02-25 15:48
This issue was found as part of community testing for 1.1, but we can't set the milestone.

**Comment by duderino** [comment] 2019-02-25 18:51
@wattli could you nominate someone to work on this?

**Comment by wattli** [comment] 2019-03-01 23:26
It's actually an issue, Phillip will work on a fix, thanks Phillip!

**Comment by wenchenglu** [comment] 2019-03-04 14:34
@pitlv2109 
any update on this one?

**Comment by pitlv2109** [comment] 2019-03-04 17:52
@wenchenglu 
Thanks for checking in. I have submitted a PR to fix the issue. Thanks @wattli for helping out :)

**Comment by wenchenglu** [comment] 2019-03-04 17:54
@pitlv2109 
awesome. Can this issue be closed now?

**Comment by wattli** [comment] 2019-03-04 17:55
The root cause is the TLS grpc server introduced in Pilot. By default, pilot will always create a secure grpc server, however, if the key/cert is not there (which is the case for consul), it will fail.

The fix is to remove the secure grpc server. Here is the https://github.com/istio/istio/pull/12228

**Comment by wattli** [comment] 2019-03-04 18:01
The PR is still under review and need your power to be merged (once all tests passed)

**Comment by pitlv2109** [comment] 2019-03-04 18:07
/close
PR merged. Issue closed.

**Closed by pitlv2109** 2019-03-04 18:07 UTC
