### ISSUE TITLE
configuring multiple gateway objects and virtualservice objects in different namespaces not working

### ISSUE THREAD

**Issue by nataraj24** [istio/istio#23851] opened 2020-05-14 11:20 UTC
i am configuring multiple gateway, virutalservice objects with different hostnames in different namespaces. but the requests are getting routed only to first one.  

namespace: k8s
hosts: k8s.example.com
gateway: k8s-gateway
virtualservice: k8s-virtualservice(referring to k8s-gateway)

namespace: k8s1
hosts: k8s1.example.com
gateway: k8s1-gateway
virtualservice: k8s1-virtualservice(referring to k8s1-gateway)

when i invoke url http://k8s1.example.com/appname the request are getting routed only k8s.example.com instead of k8s1.example.com gateway and virtualservice

we have only one istio-ingressgateway pod and istio-ingressgateway service exposed.  

i had referred istio documentation but didnt help. do i need to create multiple ingressgateway pod and multiple ingressgateway services under istio-system namespace.  Please some on this erquirement

**Comment by howardjohn** [comment] 2020-08-05 01:12
Can you please provide  the full config you have, not just a tiny snippet, so we can attempt to reproduce? and a config dump from ingress: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by nataraj24** [comment] 2020-08-07 12:51
its issue with host name based routing i saw a thread where it was mentioned it was fixed in istio 1.6.  for 1.5.2 version we have a workaround sending request host header from browser using browser plugin with hostname then the requests are getting routed properly appropriate gateway for multiple namespace.  unfortunately when i use 1.6 version external services arent working.  i had raised request #24575.

**Comment by nataraj24** [comment] 2020-08-14 17:30
Hi @howardjohn 

The issue i am referring in this thread is the same issue where other people are facing and same is discussed in #8807.  In #8807 thread you had mentioned that the issue is fixed in istio 1.6.  can you please confirm whether its fixed in 1.6.x of istio.  also you had mentioned that its not fully fixed.  so its confusing.  i am not able test hostname based routing feature using 1.6 with our application as i am facing external service issue mentioned in #24575.

**Comment by nataraj24** [comment] 2020-08-19 09:13
Hi @howardjohn 

External service issue we had experienced in 1.5.2 version also when we enable mTLS option.  we use external service to connect to database residing outside the mesh and cluster and when we enable mtls  get “java.sql.SQLException: Cannot create PoolableConnectionFactory”  error.  When we disable mTLS option the applications are able to connect to the db.

**Comment by howardjohn** [comment] 2020-09-12 00:19
We cannot reproduce this unless you give the full configuration as requested.

**Comment by howardjohn** [comment] 2020-09-23 00:31
Closing as we do not have enough information to proceed

**Closed by howardjohn** 2020-09-23 00:31 UTC
Labels: area/networking, kind/need more info, lifecycle/needs-triage
