### ISSUE TITLE
All containers run as root by default

### ISSUE THREAD

**Issue by MarkDeckert** [istio/istio#14201] opened 2019-05-17 05:10 UTC
**Bug description**
By not explicitly defining runAsUser, all istio components are set to run as UID 0 (ROOT) by default (with the exception of grafana).

**Expected behavior**
Nothing should be running as root.  The default deployments should specifically define a non-0 UID runAsUser in securityContext section.

Is there any reason to run any of the istio processes as root? By now it should be basic best security practice to restrict uid 0 in PodSecurityPolicy and require any deployments to explicitly set runAsUser.  Especially in the case of using istio-cni -- no container should require any elevated permissions except for the cni-installers.

There is no downside to this, as even for those who choose to run insecure clusters without any PodSecurityPolicy, explicitly setting UID in a deployment will do no harm.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience

**Comment by esnible** [comment] 2019-05-17 14:03
Closing as a duplicate of https://github.com/istio/istio/issues/10768

**Closed by esnible** 2019-05-17 14:03 UTC
