### ISSUE TITLE
updateVersion problems

### ISSUE THREAD

**Issue by frankbu** [istio/istio#220] opened 2017-05-09 22:23 UTC
1. `updateVersion.sh -c` doesn't work

2. `updateVersion.sh` has been moved out of the `tests` directory, but `tests/README.md` is still the doc for it.

3. The generated comment in `istio.INSTALL` also refers to `tests/updateVersion.sh` and `tests/README.md`

PR #209 fixes these problems, and also simplifies the design to remove the files in `install/kubernetes/templates` and instead just update istio.yaml and istio-auth.yaml in place. This is a necessary simplification IMO, since the current design is very confusing. When you call updateVersion.sh, it not only updates the expected files (istio.VERSION, istio.yaml, and istio-auth.yaml) but it also updates 8 other template files, so the resulting git commit has 10 updated files. The fact that there are 10, instead of just 2 yaml files in the install directory is also confusing. The small benefit of not needing to make the same update to 2 files when there are non-image changes, which is fairly rare, is not worth the complexity.

If, however, we don't want to merge #209 before alpha, the above 3 problems need to be fixed in the current version.

**Comment by andraxylia** [comment] 2017-05-10 02:06
If the problem is with the number of files updateVersion touches, let's change the templates to be template, i.e. to contain a {hub} and {tag}, and do the substitution directly in the generated files.

**Comment by frankbu** [comment] 2017-05-10 04:11
@andraxylia yes, that would be better. I think that if we stick with templates, they should really be templates, not yaml files that are also updated every time they are used.

Right now, they aren't really templates, but rather yaml fragments that are being composed into larger ones (a yaml !include would be nice). The only reason we need them now is for two composed files (istio.yaml and istio-auth.yaml) that would otherwise have duplication. Isn't the goal is to only have one of these in the future? If so, aren't we adding this complexity to solve a short-term problem?

We also have the option of simply splitting up the yaml files used for install. We could have bash scripts to pull in the right ones for different configurations, if it's too complicated, although it certainly isn't today.

Anyway, if we use templates or simply split up yaml files we should be leveraging the separation better. See my related comment in https://github.com/istio/istio/pull/224.

**Comment by andraxylia** [comment] 2017-05-10 04:18
Let's use the templates, it is easier to do kubectl apply, than to run a bash script (or .bat, or .zsh etc). 
Indeed, it would be nice to have a single yaml file. The expectation is auth enabled will become the default option for installation.

**Comment by frankbu** [comment] 2017-05-10 17:10
OK, I closed #209 and moved the fixes and template improvement to #229. 

@andraxylia, @sebastienvas: PTAL

**Comment by sebastienvas** [comment] 2017-06-06 20:41
@frankbu I think we can close this right ?

**Closed** 2017-06-06 22:42 UTC
Labels: bug, hackathon
