### ISSUE TITLE
pilot failure on OpenShift: a cluster is returned without a matching service-key in /v1/registration

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#2031] opened 2017-12-08 16:37 UTC
This example stopped working in 0.3.0. 
https://github.com/snowdrop/spring-boot-quickstart-istio

listeners, clusters, routes and endpoints info here - https://gist.github.com/cmoulliard/19614d3e05d64e5ddba3f699162ec241#file-gistfile1-txt-L275

For a domain "greeting-service", the following cluster is defined:

```
{
            "connect_timeout_ms": 1000,
            "lb_type": "round_robin",
            "name": "out.greeting-service.demo-istio.svc.cluster.local|http",
            "service_name": "greeting-service.demo-istio.svc.cluster.local|http",
            "type": "sds"
},
```

However, /v1/registration does not return the matching service_key for "greeting-service.demo-istio.svc.cluster.local|http".

The instructions for deploying the examples are here https://github.com/snowdrop/spring-boot-quickstart-istio#instructions .

**Comment by cmoulliard** [comment] 2017-12-08 16:47
@vadimeisenbergibm Instructions followed to setup istio 0.3.0 with our Spring Boot project are defined here in fact : https://github.com/snowdrop/spring-boot-quickstart-istio/blob/master/INSTALLATION.md#with-istio-03

Master branch of the example will continue to use 0.2.12 version as default value to inject the [proxy](https://github.com/snowdrop/spring-boot-quickstart-istio/blob/master/say-service/src/main/istio/profiles.yml#L27)

**Comment by christian-posta** [comment] 2017-12-08 19:57
So i've gotten your services up with istio and I see that the RDS does work correctly. 

I've burned through all my battery on this flight so gonna have to stop for the moment. I'll have to go back and verify some port settings because I cannot query the services properlly, but i'm sure that's something i overlooked.

Will updaate as I get a chance to dig deeper.

**Comment by vadimeisenbergibm** [comment] 2017-12-09 15:35
@christian-posta LDS, RDS and CDS work correctly. The only thing that does not work is SDS (/v1/registration) that does not return the entry for "greeting-service.demo-istio.svc.cluster.local|http".

**Comment by christian-posta** [comment] 2017-12-09 17:27
So I've got this example deployed on OpenShift  3.7 using k8s Deployment not OpenShift DeploymentConfig and using the istioctl tooling, not the maven plugin Charles is using. Everything works as expected (all SDS/RDS/CDS). So i'm not seeing a bug in istio per-se. The next step is to figure out if OpenShift DeploymentConfigs or the maven tooling is setting up the Pilot agent incorrectly or where else the difference is.

**Comment by cmoulliard** [comment] 2017-12-10 17:34
> maven tooling is setting up the Pilot agent incorrectly

The [enricher](https://github.com/snowdrop/fmp-istio-enricher/blob/master/src/main/java/me/snowdrop/cloud/fabric8/IstioEnricher.java) used to update the DeploymentConfig relies exactly one the same config as generated/injected by kubectl. 

Generated file : https://gist.github.com/cmoulliard/5dc443b23853c77c327a001765a1212c

- The `Say Service` is well registered but not the `Greeting Service` called by `Say Service`
- The same project deployed on istio 0.2.12 works perfectly !

**Comment by cmoulliard** [comment] 2017-12-12 07:45
Feedback from @vadimeisenbergibm 

From what I found, the code is here:
1. REST API for /v1/registration:
https://github.com/istio/istio/blob/249dfaa3008dc82d9024e17e545e57fb43b8bd81/pilot/proxy/envoy/discovery.go#L241 calls ListAllEndpoints()

2. https://github.com/istio/istio/blob/9386e6c1cc95f2f405383c547b9d8329e557397b/pilot/proxy/envoy/discovery.go#L355. ListAllEndpoints() ultimately calls Services() https://github.com/istio/istio/blob/1f22391d8e6aba7926276c10e4b64a9a0db4c721/pilot/platform/kube/controller.go#L185

3. The Services() function calls functions of https://github.com/kubernetes/client-go to query Kubernetes APIs. See their examples https://github.com/kubernetes/client-go/tree/master/examples how to query Kubernetes APIs.

To lunch a pilot, what you need is actually the pilot discovery - the command is here https://github.com/istio/istio/blob/master/pilot/cmd/pilot-discovery/main.go.

The parameters are here https://github.com/istio/istio/blob/master/install/kubernetes/istio.yaml#L1109. When built with Bazel, the compiled command is here bazel-bin/pilot/cmd/pilot-discovery/pilot-discovery.

**Comment by cmoulliard** [comment] 2017-12-12 08:18
Log of istio-pilot using 0.2.12

```
I1212 07:59:07.151833       1 main.go:93] mesh configuration (*istio_proxy_v1_config.MeshConfig)(0xc4200c0750)(egress_proxy_address:"istio-egress.istio-system:80" mixer_address:"istio-mixer.istio-system:9091" proxy_listen_port:15001 connect_timeout:<seconds:1 > ingress_class:"istio" ingress_service:"istio-ingress" ingress_controller_mode:STRICT rds_refresh_delay:<seconds:1 > enable_tracing:true access_log_file:"/dev/stdout" default_config:<config_path:"/etc/istio/proxy" binary_path:"/usr/local/bin/envoy" service_cluster:"istio-proxy" drain_duration:<seconds:45 > parent_shutdown_duration:<seconds:60 > discovery_address:"istio-pilot.istio-system:8080" discovery_refresh_delay:<seconds:1 > zipkin_address:"zipkin.istio-system:9411" connect_timeout:<seconds:10 > statsd_udp_address:"istio-mixer.istio-system:9125" proxy_admin_port:15000 > )
I1212 07:59:07.152094       1 main.go:94] version root@c97afd9816cb-998e0e00d375688bcb2af042fc81a60ce5264009-998e0e00d375688bcb2af042fc81a60ce5264009
I1212 07:59:07.162473       1 main.go:95] flags (main.args) {
 kubeconfig: (string) "",
 meshconfig: (string) (len=22) "/etc/istio/config/mesh",
 namespace: (string) "",
 controllerOptions: (kube.ControllerOptions) {
  WatchedNamespace: (string) "",
  ResyncPeriod: (time.Duration) 1m0s,
  DomainSuffix: (string) (len=13) "cluster.local"
 },
 discoveryOptions: (envoy.DiscoveryServiceOptions) {
  Port: (int) 8080,
  EnableProfiling: (bool) true,
  EnableCaching: (bool) true
 },
 registries: ([]string) (len=1 cap=1) {
  (string) (len=10) "Kubernetes"
 },
 consul: (main.consulArgs) {
  config: (string) "",
  serverURL: (string) ""
 },
 eureka: (main.eurekaArgs) {
  serverURL: (string) ""
 },
 admissionArgs: (admit.ControllerOptions) {
  Descriptor: (model.ConfigDescriptor) <nil>,
  ExternalAdmissionWebhookName: (string) (len=22) "pilot-webhook.istio.io",
  ServiceName: (string) (len=20) "istio-pilot-external",
  ServiceNamespace: (string) "",
  ValidateNamespaces: ([]string) <nil>,
  DomainSuffix: (string) "",
  SecretName: (string) (len=13) "pilot-webhook",
  Port: (int) 443,
  RegistrationDelay: (time.Duration) 5s
 }
}
W1212 07:59:07.172176       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1212 07:59:07.189343       1 client.go:169] registering CRD "routerules.config.istio.io"
I1212 07:59:07.741340       1 client.go:169] registering CRD "egressrules.config.istio.io"
I1212 07:59:07.867476       1 client.go:169] registering CRD "destinationpolicies.config.istio.io"
I1212 07:59:08.468129       1 client.go:189] established CRD "routerules.config.istio.io"
I1212 07:59:08.469970       1 client.go:189] established CRD "egressrules.config.istio.io"
I1212 07:59:08.472389       1 client.go:189] established CRD "destinationpolicies.config.istio.io"

I1212 07:59:08.832003       1 controller.go:93] ingress event add for demo-istio/say-service
I1212 07:59:08.732150       1 controller.go:93] ingress event add for demo-istio/greeting-service

I1212 07:59:09.732346       1 controller.go:447] Handle endpoint greeting-service in namespace demo-istio
I1212 07:59:09.732353       1 controller.go:447] Handle endpoint say-service in namespace demo-istio

I1212 07:59:11.032138       1 controller.go:427] Handle service greeting-service in namespace demo-istio
I1212 07:59:11.132812       1 controller.go:427] Handle service say-service in namespace demo-istio

I1212 07:59:15.136524       1 controller.go:447] Handle endpoint say-service in namespace demo-istio
I1212 07:59:19.735658       1 controller.go:447] Handle endpoint greeting-service in namespace demo-istio
 ```

**Comment by cmoulliard** [comment] 2017-12-12 11:54
Both pods doesn't display localhost:15000/routes from istio-proxy pod terminal

```
curl localhost:15000/routes
envoy admin commands:
  /certs: print certs on machine
  /clusters: upstream cluster status
  /cpuprofiler: enable/disable the CPU profiler
  /healthcheck/fail: cause the server to fail health checks
  /healthcheck/ok: cause the server to pass health checks
  /hot_restart_version: print the hot restart compatability version
  /listeners: print listener addresses
  /logging: query/change logging levels
  /quitquitquit: exit the server
  /reset_counters: reset all counters to zero
  /server_info: print server version/status information
  /stats: print server stats
```

**Comment by cmoulliard** [comment] 2017-12-13 16:42
@vadimeisenbergibm @andraxylia 

It seems that we have a DNS issue. When I change the logging level to debug for `upstream`, then dns error message appears

```
[2017-12-13 16:20:41.854][25][debug][upstream] external/envoy/source/server/lds_subscription.cc:35] lds: starting request
[2017-12-13 16:20:42.554][25][debug][upstream] external/envoy/source/common/upstream/cds_subscription.cc:35] cds: starting request
[2017-12-13 16:20:42.857][25][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2017-12-13 16:20:43.553][25][info][upstream] external/envoy/source/common/upstream/cds_subscription.cc:70] cds: fetch failure: network error
[2017-12-13 16:20:44.822][25][debug][upstream] external/envoy/source/server/lds_subscription.cc:35] lds: starting request
[2017-12-13 16:20:45.334][25][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2017-12-13 16:20:45.502][25][debug][upstream] external/envoy/source/common/upstream/cds_subscription.cc:35] cds: starting request
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:534] starting async DNS resolution for istio-pilot.istio-system
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 3750 milliseconds
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:534] starting async DNS resolution for istio-pilot.istio-system
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 3750 milliseconds
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:534] starting async DNS resolution for zipkin.istio-system
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 3437 milliseconds
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:534] starting async DNS resolution for istio-pilot.istio-system
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 3124 milliseconds
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:534] starting async DNS resolution for istio-pilot.istio-system
[2017-12-13 16:20:45.593][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 3124 milliseconds
[2017-12-13 16:20:45.594][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 2812 milliseconds
[2017-12-13 16:20:45.594][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 2812 milliseconds
[2017-12-13 16:20:45.594][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 2812 milliseconds
[2017-12-13 16:20:45.594][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 2812 milliseconds
[2017-12-13 16:20:45.594][25][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 2812 milliseconds
[2017-12-13 16:20:45.594][25][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:541] async DNS resolution complete for zipkin.istio-system
[2017-12-13 16:20:45.594][25][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:541] async DNS resolution complete for istio-pilot.istio-system
[2017-12-13 16:20:45.594][25][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:541] async DNS resolution complete for istio-pilot.istio-system
```

This is not at all the case when I run the same project with 0.2.12

```
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/server/lds_subscription.cc:35] lds: starting request
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:498] starting async DNS resolution for zipkin.istio-system
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 4061 milliseconds
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:498] starting async DNS resolution for istio-pilot.istio-system
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 4061 milliseconds
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:498] starting async DNS resolution for istio-pilot.istio-system
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 4061 milliseconds
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:498] starting async DNS resolution for istio-pilot.istio-system
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 3750 milliseconds
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/upstream/upstream_impl.cc:498] starting async DNS resolution for istio-pilot.istio-system
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/common/network/dns_impl.cc:129] Setting DNS resolution timer for 3750 milliseconds
[2017-12-13 16:29:08.678][12][debug][upstream] external/envoy/source/server/lds_subscription.cc:43] lds: parsing response
[2017-12-13 16:29:08.689][12][debug][upstream] external/envoy/source/server/lds_api.cc:48] lds: add/update listener 'virtual' skipped
[2017-12-13 16:29:08.689][12][debug][upstream] external/envoy/source/server/lds_api.cc:48] lds: add/update listener 'http_0.0.0.0_3000' skipped
[2017-12-13 16:29:08.689][12][debug][upstream] external/envoy/source/server/lds_api.cc:48] lds: add/update listener 'http_0.0.0.0_443' skipped
[2017-12-13 16:29:08.689][12][debug][upstream] external/envoy/source/server/lds_api.cc:48] lds: add/update listener 'http_0.0.0.0_80' skipped
....
```

**Comment by cmoulliard** [comment] 2017-12-13 18:05
@vadimeisenbergibm @christian-posta @andraxylia 

There is well a difference between 0.2.12 and 0.3.0 which is responsible of this issue

The istio pilot - 0.2.12 only runs a container with 2 opened ports : 8080/443 and they are well exposed as service on OpenShift 3.7

With 0.3.0, the pilot runs now 2 containers: pilot and proxy with the following ports: 443/8080 and 15003. 
But when the service is created, then the IP address only exposes the port 15003/443 and not anymore 8080.
This is why the envoy proxy can't get the /routes or /listeners from the pilot = management server as it tries to access the port 8080

I have edited the pilot service to change the port and then to scale down/up my spring boot pods and now that works

curl http://say-service.demo-istio.svc.cluster.local:8080/say
{"id":3,"content":"Hello, World!"}

To fix the issue, we must change the selector definition within the istio.yaml file used to install istio on Openshift !

**Comment by andraxylia** [comment] 2017-12-14 00:46
@cmoulliard thanks for getting to the bottom of this. It appears to be collateral damage from istio-on-istio (securing pilot with an Envoy proxy). Will you be able to submit the PR? The change would go in the template file, istio.yaml is generated: https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-pilot.yaml.tmpl

There is also a helm file being added (please ignore the fact we have duplication):
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/pilot/templates/pilot.yaml

**Comment by ldemailly** [comment] 2017-12-14 04:53
cc @rkpagadala 
(as far as I know dropping the old port is by design)

**Comment by cmoulliard** [comment] 2017-12-14 08:02
No PR is required as the fault is coming from our Java enricher which was not up to date according to info that we have within the configMap. I will change it

I will create separate tickets to improve istio and get more infos (log, ...) when such a situation occurs

- The istio proxy should be monitored by kube health check and pod not started if the envoy proxy can't call the pilot
- Message should be logged that calling to the pilot is failing (without the need to change the logging level to debug for the proxy) -> so we should maybe use info level instead of warning by default to see such message within the log "[2017-12-13 16:20:46.508][25][info][upstream] external/envoy/source/common/upstream/cds_subscription.cc:70] cds: fetch failure: network error"
- Watcher of istio proxy should be maybe enhanced in order to change the address of the pilot, mesh, ... if configmap changes

**Comment by rkpagadala** [comment] 2017-12-14 22:46
@cmoulliard the port change is by design. 15003 port forwards to port 8080 of pilot. So the choice is to point envoy to 15003 or edit pilot container to expose 8080 as you have done.

**Comment by andraxylia** [comment] 2018-06-23 05:41
We switched to v2 in 0.8, closing.

**Closed by andraxylia** 2018-06-23 05:41 UTC
Labels: area/networking
