### ISSUE TITLE
Add FTP protocol for external service entry

### ISSUE THREAD

**Issue by courcelm** [istio/istio#15776] opened 2019-07-23 12:22 UTC
**Describe the feature request**

Add the FTP protocol to Service entry to allow file download from external FTP. FTP start the connection with TCP and then switch to UDP. I did find a way to allow two protocols on the same port.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment] 2019-08-01 15:35
We don't yet support UDP so we are blocked by https://github.com/istio/istio/issues/1430

**Comment by howardjohn** [comment] 2019-10-03 19:09
Closing as duplicate of https://github.com/istio/istio/issues/15972

**Closed by howardjohn** 2019-10-03 19:09 UTC
Labels: area/networking, kind/enhancement
