### ISSUE TITLE
istiod crashing if an AuthorizationPolicy is created before the corresponding waypoint proxy is running

### ISSUE THREAD

**Issue by djannot** [istio/istio#43538] opened 2023-02-22 19:09 UTC
### Bug Description

I create an AuthorizationPolicy which selects the waypoint proxy (as a workaround of https://github.com/istio/istio/issues/43476) but if I create it while the corresponding waypoint proxy isn't running yet (the Gateway object has just been created), istiod crashes.

Here is the error in the istiod log:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aa1c53]

goroutine 193 [running]:
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).AuthorizationPolicyHandler(_, {{{{0x3763e5e, 0x11}, {0x374a75f, 0x7}, {0x376799b, 0x13}}, {0xc001c2ce40, 0x24}, {0xc001c10c90, ...}, ...}, ...}, ...)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/ambientindex.go:291 +0x373
istio.io/istio/pilot/pkg/config/kube/crdclient.(*cacheHandler).callHandlers(_, {{{{0x3763e5e, 0x11}, {0x374a75f, 0x7}, {0x376799b, 0x13}}, {0xc001c2ce40, 0x24}, {0xc001c10c90, ...}, ...}, ...}, ...)
	istio.io/istio/pilot/pkg/config/kube/crdclient/cache_handler.go:86 +0x17d
istio.io/istio/pilot/pkg/config/kube/crdclient.(*cacheHandler).onEvent(0xc0011bfd40, {0x36d5b20, 0xc0014683c0}, {0x36d5b20, 0xc002797e00}, 0x1)
	istio.io/istio/pilot/pkg/config/kube/crdclient/cache_handler.go:65 +0x748
istio.io/istio/pilot/pkg/config/kube/crdclient.createCacheHandler.func3.1()
	istio.io/istio/pilot/pkg/config/kube/crdclient/cache_handler.go:123 +0x33
istio.io/istio/pkg/queue.(*queueImpl).processNextItem(0xc00166fd10)
	istio.io/istio/pkg/queue/instance.go:109 +0x3a
istio.io/istio/pkg/queue.(*queueImpl).Run(0xc00166fd10, 0xc0000ef140)
	istio.io/istio/pkg/queue/instance.go:135 +0x125
istio.io/istio/pilot/pkg/config/kube/crdclient.(*Client).Run(0xc00127b590, 0xc0000ef140)
	istio.io/istio/pilot/pkg/config/kube/crdclient/client.go:251 +0x1cc
created by istio.io/istio/pilot/pkg/config/aggregate.(*storeCache).Run
	istio.io/istio/pilot/pkg/config/aggregate/config.go:213 +0xd0
```

### Version

```prose
istioctl and Istio images built from the main branch after commit c9c020d71e9842dd5077236e8cc59d3df1a4d7b3
```

**Comment by hanxiaop** [comment] 2023-03-13 03:03
I cannot reproduce this. Can you test with the latest commit?

**Comment by howardjohn** [comment] 2023-05-09 15:25
should be fixed in https://github.com/istio/istio/commit/d070b64f83185e19b64fac2725eb127bdb4cdc74#diff-698573a8cf81b7bbd18b4e8d0e644ae539d40dfbefa1c95971ac85d0689f64cfR315

**Closed by howardjohn** 2023-05-09 15:25 UTC
Labels: kind/need more info, area/ambient
