### ISSUE TITLE
istio cni not working with  traffic.sidecar.istio.io annotations

### ISSUE THREAD

**Issue by ssurapan** [istio/istio#22893] opened 2020-04-12 19:13 UTC
**Bug description**

Istio CNI is not putting proper IP table rules when using traffic.sidecar.istio.io annotations

I am using the below annotations
traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
traffic.sidecar.istio.io/excludeInboundPorts: "9300"

I am attaching 2 files with IP tables output for
1) working one with CNI not enabled
2) not working with CNI enabled

**Expected behavior**
Expected to behave same when CNI is enabled or not enabled

**Steps to reproduce the bug**
Deploy an app with the above annotations . If CNI is enabled, app is failing due to wrong iptables rules

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
 1.5.1
**How was Istio installed?**
kubectl create namespace istio-system

helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -

helm template install/kubernetes/helm/istio --name istio --set istio_cni.enabled=true --set istio_cni.logLevel=debug  --set global.controlPlaneSecurityEnabled=true --set global.mtls.enabled=true --namespace istio-system | kubectl apply -f -

helm template install/kubernetes/helm/istio-cni --name=istio-cni --namespace=kube-system | kubectl apply -f -
[istio_working.pdf](https://github.com/istio/istio/files/4466892/istio_working.pdf)
[istio_cni_notworking.pdf](https://github.com/istio/istio/files/4466893/istio_cni_notworking.pdf)

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by ssurapan** [comment] 2020-04-12 23:28
This is caused by istio_iptables.sh block
if [ "${INBOUND_PORTS_INCLUDE}" == "*" ]; then
    # Makes sure SSH is not redirected
    iptables -t ${table} -A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
    # Apply any user-specified port exclusions.
    if [ -n "${INBOUND_PORTS_EXCLUDE}" ]; then
      for port in ${INBOUND_PORTS_EXCLUDE}; do
        iptables -t ${table} -A ISTIO_INBOUND -p tcp --dport "${port}" -j RETURN
      done
    fi

We have to explicitly use the below annotation to make it work with CNI
traffic.sidecar.istio.io/includeInboundPorts: "*"
This behavior is not same with and without CNI

**Comment by cagataygurturk** [comment] 2020-04-13 15:41
Just filed the same issue after a discussion in a PR: istio/istio#22902

**Comment by rlenglet** [comment] 2020-04-13 16:17
@cagataygurturk this issue is different. It is about two specific annotations being ignored by Istio CNI plugin. It is not a duplicate of #22902.

**Comment by rolandkool** [comment] 2020-04-13 16:58
@rlenglet wasn't this fixed with https://github.com/istio/cni/pull/282 ?
We had similar issue reported with CNI and annotations not taking effect in issue https://github.com/istio/istio/issues/22498. We've validated last Friday that the fix (that can be applied using a nightly build) works for us.

**Comment by ajitchahal** [comment] 2020-05-19 19:34
With istio 1.5.4, adding the annotations work, but now even the envoy own readiness is failing because of https://github.com/istio/istio/issues/22498
```
Readiness probe failed: Get http://100.96.17.11:15020/healthz/ready: dial tcp 100.96.17.11:15020: connect: connection refused
```

So even for envoy i need a POD annotation to ignore its healthcheck port.
```
traffic.sidecar.istio.io/excludeOutboundPorts: "9090,15020"
traffic.sidecar.istio.io/excludeInboundPorts: "9090,15020"
```
15020: is istio proxy health check & 9090 is my own port that I want to exclude.

**Comment by ajitchahal** [comment] 2020-05-20 14:28
Update: addingsidecar.istio.io/rewriteAppHTTPProbers: "true" as pod annotation fixes the issue.

**Closed** 2020-09-12 05:06 UTC
Labels: area/networking/cni, lifecycle/needs-triage
