### ISSUE TITLE
the version is still 1.1.3 in the output for istioctl proxy-status

### ISSUE THREAD

**Issue by mailzyok** [istio/istio#14263] opened 2019-05-21 05:40 UTC
Hello,

1. Download and make a clean installation of istio 1.1.7
2. execute command "istioctl proxy-status", the version shows 1.1.3 in the output.

Is it by design or a bug?

Thanks.

**Comment by howardjohn** [comment] 2019-05-21 14:48
This is by design, but we are changing it (https://github.com/istio/istio/pull/14222). The "version" is the version of the proxy which is more of an internal thing to describe its capabilities/compatibility. This confuses a lot of users so we are switching it to show the Istio version (1.1.7) like you would expect. It should be in 1.2.

**Comment by howardjohn** [comment] 2019-06-06 23:10
Fixed in 1.2 by #14222

**Closed by howardjohn** 2019-06-06 23:10 UTC
Labels: area/user experience
