### ISSUE TITLE
LDS Failure for Egress Gateway in istio.io test

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#25544] opened 2020-07-15 16:57 UTC
Failing test: https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/k8s-tests_istio.io/2585

Passing test: https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/k8s-tests_istio.io/2588

rollback PR in istio.io: https://github.com/istio/istio.io/pull/7725

**Comment by therealmitchconnors** [comment] 2020-07-15 16:57
I am working to repro on GKE.

**Comment by therealmitchconnors** [comment] 2020-07-15 21:14
I added some diagnostic info to the test framework, and found that Config is indeed failing to synchronize to the egress gateways for LDS.  Modifying title to reflect true nature of the failure, and reassigning.

**Comment by therealmitchconnors** [comment] 2020-07-15 21:15
Here is the doc being tested: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/

And here is the test output showing from `istioctl ps` that LDS isn't distributing: https://prow.istio.io/view/gcs/istio-prow/logs/k8s-tests_istio.io_postsubmit/680

**Comment by frankbu** [comment] 2020-07-15 21:47
`istioctl ps` shows 2 egress-gateway pods. Could things be getting messed up because the egress gateway is restarting, so the old pod hasn't gone away yet? https://preliminary.istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#redeploy-the-egress-gateway-with-the-client-certificates

**Comment by nschhina** [comment] 2020-07-15 21:51
kubectl patch should update API object in place, also it was fine in like forever and only with istio/istio dep update in istio.io this has started to break ...

**Comment by GregHanson** [comment] 2020-07-17 20:16
@therealmitchconnors I think this is duplicate of https://github.com/istio/istio.io/issues/7512

should be resolved by https://github.com/istio/istio/pull/25588 and https://github.com/istio/istio.io/pull/7732

**Comment by nschhina** [comment] 2020-07-20 19:23
Closing this as pointed out this is not a LDS misconfiguration error and seems like the problem is now resolved in istio.io

**Closed by nschhina** 2020-07-20 19:23 UTC
Labels: area/networking, kind/test failure, lifecycle/needs-triage
