### ISSUE TITLE
Ingress + Gateway always returns 404

### ISSUE THREAD

**Issue by caulagi** [istio/istio#24584] opened 2020-06-10 17:15 UTC
**Bug description**

We have a setup based on https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/. So we use Ingress + Gateway to route traffic into the cluster. But the request always returns 404 from istio-envoy

```
$ kubectl get gateways.networking.istio.io istio-ingressgateway -o yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: secret-name
      mode: SIMPLE

$ kubectl get ingresses -n monitoring external-thanos-ingress -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: external-istio
  labels:
    app: auth-proxy
  name: external-thanos-ingress
  namespace: monitoring
spec:
  rules:
  - host: prometheus.development-01.netent.tech
    http:
      paths:
      - backend:
          serviceName: auth-proxy
          servicePort: 8088
status:
  loadBalancer:
    ingress:
    - ip: REDACTED

$ curl -k -v https://prometheus.development-01.netent.tech/
...
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
< HTTP/2 404
< date: Wed, 10 Jun 2020 16:58:13 GMT
< server: istio-envoy
```

**Debug information** - https://gist.github.com/caulagi/a675c517e32e72128d37f1f4dee1ac3b

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

`curl -k -v https://prometheus.development-01.netent.tech/` to give 401 response (for unauthenticated requests to this service)

**Steps to reproduce the bug**

Using the example yamls above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```shell
$ istioctl version --remote
client version: 1.6.1
control plane version: 1.6.0
data plane version: 1.6.0 (2 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-dispatcher", GitCommit:"f2a77f678d6baccda27740d700f6cba2754dfacf", GitTreeState:"clean", BuildDate:"2020-04-21T04:44:03Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.7-gke.32", GitCommit:"4ce968103257586ffc7adc1b3fb93f640875c2fc", GitTreeState:"clean", BuildDate:"2020-03-06T01:30:29Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

We first installed operator and configure operator to install istio

**Environment where bug was observed (cloud vendor, OS, etc)** - in our own data center and we use F5 loadbalancer

**Comment by caulagi** [comment] 2020-06-15 19:25
It didn't work for me when I tried 1.6.0 and 1.6.1 but I can make this work if I used the gateway `istio-system/istio-autogenerated-k8s-ingress` as described in https://github.com/istio/istio/issues/23989

**Comment by howardjohn** [comment] 2020-07-29 19:13
The problem is you have configured your Ingress for HTTP traffic only, but are sending TLS. The ingress spec is notoriously vague, but I am pretty sure based on https://kubernetes.io/docs/concepts/services-networking/ingress/#tls, https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#setting_up_https_tls_between_client_and_load_balancer, and https://kubernetes.github.io/ingress-nginx/examples/tls-termination/, Ingress will only serve on HTTPS if a `tls` config is provided. This makes sense to me, as we need to know what cert to use

Based on this i think this is a user configuration issue (and possibly docs?) not a bug in Istio. Does that make sense to you?

**Comment by howardjohn** [comment] 2020-08-24 22:49
Closing as I think there is Working As Inteded. Thanks!

**Closed by howardjohn** 2020-08-24 22:49 UTC
Labels: area/networking, kind/need more info, lifecycle/needs-triage
