### ISSUE TITLE
Upstream raise and servicename.namespacename cannot be accessed sometimes.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#6116] opened 2018-06-08 17:45 UTC
Ingress raises an upstream error and the backend service (`servicename.namespacename`) cannot be accessed sometimes.

**_Environment:_**
istio0.7.1 + cilium1.0 + k8s 1.9.5 + Auth disabled
(Note k8s installed with kubespray 2.5.)

**_Steps:_**
1. Devops deployed some new versions on several service in k8s.
2. QA tests pass for two hours, and everything works well (i.e. service are accessible via ingress). 
3. After a few hours, without doing any changes in k8s (no services restarts or deployments), several (~5) services (but not all) become unaccessible via ingress. Services are accessed at a URL like `https://XXX.ing.prod.XXX.com/myservice/v1/health`. The client receives 503 upstream errors.
4. In the `istio-ingress` logs, we consistently see 503 errors. The backend service / pod IPs are correct in those logs.
5. We see no logs about those requests in the backend pod's logs.
6. Within the backend pod, the service is accessible at 127.0.0.1 (the service port is 3000):
```
kubectl exec -ti myservice-pod -- curl localhost:3000/myservice/v1/health
   return 200
```
7. Within the backend pod, the service is unaccessible via its service domain name:
```
kubectl exec -ti myservice-pod -- curl servicename.namespacename/myservice/v1/health
    **Connection refused**
```
8. The issue doesn't recovery automatically, even after one hour.
9. Restarting `istio-pilot` restores connectivity quickly, after only ~20s.

**Comment by frankbu** [comment] 2018-06-13 14:28
Can you reproduce this problem, or was it a one time corruption? Can you upgrade to Istio 0.8 and see if the problem is still there?

**Comment by andraxylia** [comment] 2018-06-13 21:12
Could you please try with Gateway and VirtualService, and release 0.8?

**Comment by johnzheng1975** [comment] 2018-06-20 02:04
Yes, we upgraded to 0.8, will check whether it raise again or not.
@andraxylia , will gateway & virtualService resolve this? will access of "servicename.namespacename" go through gateway & virtualService?

**Comment by johnzheng1975** [comment] 2018-06-21 09:19
@frankbu @andraxylia  Yes, in istio0.8, this issue still exists.
Environment: k8s1.9.5 + istio0.8 + cilium1.1.0-rc3 (istio auth is disabled)
There are two service l1ham and ham in my platform, l1ham service accesses ham service unstable.
I write a jenkins job, which will run below command each minute continually.
kubectl  exec -ti hp-l1ham-deploy-66594c5559-54825 --namespace=hp -- curl -v hp-ham-service.hp/ham/api//v1/devices/detail/3CR6440058 
About 10% of them are fail, and 90% are pass. Error is as below:
'''
Could not resolve host: hp-ham-service.hp
* Closing connection 0
curl: (6) Could not resolve host: hp-ham-service.hp
'''

**Comment by johnzheng1975** [comment] 2018-06-21 11:13
add more log
[istio-pilot-5fd8c4bb89-8996n_istio-proxy.log](https://github.com/istio/istio/files/2123309/istio-pilot-5fd8c4bb89-8996n_istio-proxy.log)
[istio-policy-578f8c599f-th4lq_istio-proxy.log](https://github.com/istio/istio/files/2123310/istio-policy-578f8c599f-th4lq_istio-proxy.log)
[istio-policy-578f8c599f-th4lq_mixer.log](https://github.com/istio/istio/files/2123311/istio-policy-578f8c599f-th4lq_mixer.log)
[istio-sidecar-injector-dbd67c88d-wthgt.log](https://github.com/istio/istio/files/2123312/istio-sidecar-injector-dbd67c88d-wthgt.log)
[istio-statsd-prom-bridge-6dbb7dcc7f-k4bb2.log](https://github.com/istio/istio/files/2123313/istio-statsd-prom-bridge-6dbb7dcc7f-k4bb2.log)
[istio-telemetry-54b5bf4847-85gv8_istio-proxy.log](https://github.com/istio/istio/files/2123314/istio-telemetry-54b5bf4847-85gv8_istio-proxy.log)
[istio-telemetry-54b5bf4847-85gv8_mixer.log](https://github.com/istio/istio/files/2123315/istio-telemetry-54b5bf4847-85gv8_mixer.log)
[kube-dns-79d99cdcd5-mkz6c.log](https://github.com/istio/istio/files/2123316/kube-dns-79d99cdcd5-mkz6c.log)
[kube-dns-79d99cdcd5-r5zbf.log](https://github.com/istio/istio/files/2123317/kube-dns-79d99cdcd5-r5zbf.log)
[hp-ham-deploy-5d7dffbcc8-ndjbs_ham.log](https://github.com/istio/istio/files/2123318/hp-ham-deploy-5d7dffbcc8-ndjbs_ham.log)

[hp-l1ham-deploy-66594c5559-54825_istio-proxy.log](https://github.com/istio/istio/files/2123319/hp-l1ham-deploy-66594c5559-54825_istio-proxy.log)
[Uploading hp-l1ham-deploy-66594c5559-54825_l1ham.log…]()
[istio-citadel-ff5696f6f-6vxqk.log](https://github.com/istio/istio/files/2123321/istio-citadel-ff5696f6f-6vxqk.log)
[istio-egressgateway-9cd955fbc-5x4m2.log](https://github.com/istio/istio/files/2123322/istio-egressgateway-9cd955fbc-5x4m2.log)
[istio-ingress-6fb78f687f-2xkrk.log](https://github.com/istio/istio/files/2123323/istio-ingress-6fb78f687f-2xkrk.log)
[istio-ingressgateway-5f4f8d568c-klf6g.log](https://github.com/istio/istio/files/2123324/istio-ingressgateway-5f4f8d568c-klf6g.log)
[istio-mixer-post-install-cvmdp.log](https://github.com/istio/istio/files/2123325/istio-mixer-post-install-cvmdp.log)
[istio-pilot-5fd8c4bb89-8996n_discovery.log](https://github.com/istio/istio/files/2123326/istio-pilot-5fd8c4bb89-8996n_discovery.log)

**Comment by johnzheng1975** [comment] 2018-06-21 11:22
add more logs
[hp-ham-deploy-5d7dffbcc8-ndjbs_ham.log](https://github.com/istio/istio/files/2123354/hp-ham-deploy-5d7dffbcc8-ndjbs_ham.log)
[hp-ham-deploy-5d7dffbcc8-ndjbs_istio-proxy.log](https://github.com/istio/istio/files/2123355/hp-ham-deploy-5d7dffbcc8-ndjbs_istio-proxy.log)
[hp-l1ham-deploy-66594c5559-54825_istio-proxy.log](https://github.com/istio/istio/files/2123356/hp-l1ham-deploy-66594c5559-54825_istio-proxy.log)
[hp-l1ham-deploy-66594c5559-54825_l1ham.log](https://github.com/istio/istio/files/2123357/hp-l1ham-deploy-66594c5559-54825_l1ham.log)
[istio-citadel-ff5696f6f-6vxqk.log](https://github.com/istio/istio/files/2123358/istio-citadel-ff5696f6f-6vxqk.log)
[istio-egressgateway-9cd955fbc-5x4m2.log](https://github.com/istio/istio/files/2123359/istio-egressgateway-9cd955fbc-5x4m2.log)
[istio-ingress-6fb78f687f-2xkrk.log](https://github.com/istio/istio/files/2123360/istio-ingress-6fb78f687f-2xkrk.log)
[istio-ingressgateway-5f4f8d568c-klf6g.log](https://github.com/istio/istio/files/2123361/istio-ingressgateway-5f4f8d568c-klf6g.log)
[istio-mixer-post-install-cvmdp.log](https://github.com/istio/istio/files/2123362/istio-mixer-post-install-cvmdp.log)
[istio-pilot-5fd8c4bb89-8996n_discovery.log](https://github.com/istio/istio/files/2123363/istio-pilot-5fd8c4bb89-8996n_discovery.log)
[istio-pilot-5fd8c4bb89-8996n_istio-proxy.log](https://github.com/istio/istio/files/2123364/istio-pilot-5fd8c4bb89-8996n_istio-proxy.log)
[istio-policy-578f8c599f-th4lq_istio-proxy.log](https://github.com/istio/istio/files/2123365/istio-policy-578f8c599f-th4lq_istio-proxy.log)
[istio-policy-578f8c599f-th4lq_mixer.log](https://github.com/istio/istio/files/2123366/istio-policy-578f8c599f-th4lq_mixer.log)
[istio-sidecar-injector-dbd67c88d-wthgt.log](https://github.com/istio/istio/files/2123367/istio-sidecar-injector-dbd67c88d-wthgt.log)
[istio-statsd-prom-bridge-6dbb7dcc7f-k4bb2.log](https://github.com/istio/istio/files/2123368/istio-statsd-prom-bridge-6dbb7dcc7f-k4bb2.log)
[istio-telemetry-54b5bf4847-85gv8_istio-proxy.log](https://github.com/istio/istio/files/2123369/istio-telemetry-54b5bf4847-85gv8_istio-proxy.log)
[istio-telemetry-54b5bf4847-85gv8_mixer.log](https://github.com/istio/istio/files/2123370/istio-telemetry-54b5bf4847-85gv8_mixer.log)
[kube-dns-79d99cdcd5-mkz6c.log](https://github.com/istio/istio/files/2123371/kube-dns-79d99cdcd5-mkz6c.log)
[kube-dns-79d99cdcd5-r5zbf.log](https://github.com/istio/istio/files/2123372/kube-dns-79d99cdcd5-r5zbf.log)

**Comment by rshriram** [comment] 2018-06-21 18:47
You either use shortname or use FQDN (name.namespace.svc.cluster.local)

**Comment by johnzheng1975** [comment] 2018-06-22 01:45
@rshriram , sorry not got you.
Are you asking me use servicename.namespace.svc.cluster.local instead of servicename.namespace?

**Comment by andraxylia** [comment] 2018-06-22 01:48
yes.

**Comment by frankbu** [comment] 2019-04-10 21:46
@johnzheng1975 Is this still happening with Istio 1.1?

**Comment by frankbu** [comment] 2019-05-03 15:05
Closing this issue because things have changed significantly in this area since last June and there has been no further update about this problem.

@johnzheng1975 Please try to move to Istio 1.1 and if you are still having 503 problems, either reopen this issue or open a new one with more specific details of the problem you are having in the 1.1 env.

**Closed by frankbu** 2019-05-03 15:05 UTC
Labels: area/networking, kind/customer issue, kind/need more info
