### ISSUE TITLE
Integration tests misleadingly use the word galley

### ISSUE THREAD

**Issue by sdake** [istio/istio#22938] opened 2020-04-14 16:28 UTC
**Bug description**
Some folks look at the code base and think galley is still present in the integration tests. Would be nice to close this out as a low priority issue.

**Expected behavior**
no change in behavior needed.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

master@ 64f6913a2e040bd23dba8574a107503c0e72d70e

**How was Istio installed?**
not installed.

**Environment where bug was observed (cloud vendor, OS, etc)**
in a testing environment.

**Comment by kramvan1** [comment] 2020-04-14 16:32
Example: https://github.com/istio/istio/blob/master/tests/integration/pilot/main_test.go#L43

**Comment by sdake** [comment] 2020-04-26 13:43
@nmittler I unassigned you and am closing this window. Hopefully an intern can pick this up as a day 30 project and hopefully you can coach.

Cheers
-steve

**Comment by howardjohn** [comment] 2020-05-13 21:09
Agreed. This is a duplicate of https://github.com/istio/istio/issues/20299, lets consolidate there. We have made some progress on this

**Closed by howardjohn** 2020-05-13 21:09 UTC
Labels: area/test and release, community/intern-help-wanted
