### ISSUE TITLE
Log entry in ingressgateway access log if TLS handshake error

### ISSUE THREAD

**Issue by JesperBerggren** [istio/istio#29300] opened 2020-12-01 14:43 UTC
**Describe the feature request**
We’ve globally enabled access logging and it generally works ok.
But if the request fails during a TLS handshake we get absolutely nothing in the ingressgateway log.

We can of course enable debugging in the ingressgateway, which will tell us what the issue is but for our production system that is not really an option.

When one of our partners experiences some connection issue with our service mesh, we need to be able to:

- identify the request (at the very least have an entry in the access log if they actually tried to access our ingressgateway)
- see what the issue is. E.g.
  - handshake error - PEER_DID_NOT_RETURN_A_CERTIFICATE

For similar requests see: envoyproxy/envoy#13563
For further reading see: [https://discuss.istio.io/t/istio-installations-on-a-single-cluster/9077/2](https://discuss.istio.io/t/istio-installations-on-a-single-cluster/9077/2)

**Describe alternatives you've considered**
Trying to implement it with a LUA filter but to me it seems like it should be a common problem for many and thus should be implemented as a standard log output on info.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment] 2020-12-01 15:19
Are you on 1.8? We added listener access logs which should expose this I think

**Comment by JesperBerggren** [comment] 2020-12-01 15:22
Good question.
No, I'm currently on 1.7.3 but it sounds like I need to move to 1.8 and test it asap.
Thanks for answering!

**Comment by JesperBerggren** [comment] 2021-03-11 13:40
Hi @howardjohn,

We've tried with Istio 1.8 and now on Istio 1.9.1. It still doesn't work.

E.g. when I call without a certificate on an MTLS connection. Nothing shows up, if I set loglevel to INFO.
But when set to DEBUG I get the following:

```
2021-03-11T13:34:50.631143Z	debug	envoy connection	[C5896] TLS error: 268435648:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
```

Do we need to make any changes to log settings or other things to enable the _listener access logs_ ?

**Comment by howardjohn** [comment] 2021-03-11 16:14
No I think thats a different error than the ones I was thinking of. @kyessenov do you know if this is possible to get into access logs?

**Comment by howardjohn** [comment] 2021-03-11 16:41
This is duplicate of https://github.com/istio/istio/issues/29565 actually, lets track there. thanks!

**Closed by howardjohn** 2021-03-11 16:41 UTC
Labels: area/extensions and telemetry, area/networking, feature/Multi-cluster, feature/Multi-control-plane, feature/Virtual-machine, kind/enhancement
