### ISSUE TITLE
how can redisquota work with a redis use password?

### ISSUE THREAD

**Issue by jianglijie** [istio/istio#16686] opened 2019-08-30 02:24 UTC
I find the config for redusquota in docs. It show `redisServiceUrl: <redis_server_url>` for the redis instance url , how can I config it with password?(redis auth)

**Comment by hzxuzhonghu** [comment] 2019-08-30 08:11
cc @kyessenov

**Comment by esnible** [comment] 2019-08-30 18:39
https://discuss.istio.io is a good place to ask questions.

**Comment by douglas-reid** [comment] 2019-08-30 22:57
Closing, as is a duplicate of: https://github.com/istio/istio/issues/14830

**Closed by douglas-reid** 2019-08-30 22:57 UTC
Labels: area/policies and telemetry
