### ISSUE TITLE
Istioctl manifest gen does not add operator labels

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#19206] opened 2019-11-25 22:11 UTC
**Bug description**
When using istioctl to generate manifest based on icp, it does not apply operator labels, which potentially could make `istioctl upgrade` leak resources when use it to upgrade a cluster set up by manifest apply.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by bianpengyuan** [comment] 2019-11-25 22:11
@ostromart assign to you for triaging.

**Comment by sdake** [comment] 2019-12-09 04:29
@bianpengyuan the operator annotations are used by the controller-runtime IIUC. In other words, the CLI mode does not understand how to use these annotations correctly.

A better approach would be to use ownerRefs for all objects throughout Istio all the way up to the original owner (either helm in the short term or the operator in the medium/long term)

Cheers
-steve

**Comment by ostromart** [comment] 2020-03-06 01:05
Duplicate of #21225

**Closed by ostromart** 2020-03-06 01:05 UTC
Labels: area/environments/operator
