### ISSUE TITLE
ipv6 and ipv4 ISTIO_INBOUND iptables rule are not aligned

### ISSUE THREAD

**Issue by tibetsam** [istio/istio#19940] opened 2020-01-06 14:12 UTC
**Bug description**
in istio/tools/packaging/common/istio-iptables.sh ISTIO_INBOUND chain, ipv4 redirect remaining inbound traffic to Envoy but ipv6 doesn't.

ipv4:
421     # Redirect remaining inbound traffic to Envoy.
422     if [ "${INBOUND_INTERCEPTION_MODE}" = "TPROXY" ]; then
423       # If an inbound packet belongs to an established socket, route it to the
424       # loopback interface.
425       iptables -t mangle -A ISTIO_INBOUND -p tcp -m socket -j ISTIO_DIVERT || echo "No socket match support"
426       # Otherwise, it's a new connection. Redirect it using TPROXY.
427       iptables -t mangle -A ISTIO_INBOUND -p tcp -j ISTIO_TPROXY
**428     else
429       iptables -t nat -A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
430     fi
431   else**

ipv6:
537     if [ "${INBOUND_PORTS_INCLUDE}" == "*" ]; then
538         # Makes sure SSH is not redirected
539         ip6tables -t ${table} -A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
540         # Apply any user-specified port exclusions.
541         if [ -n "${INBOUND_PORTS_EXCLUDE}" ]; then
542         for port in ${INBOUND_PORTS_EXCLUDE}; do
543             ip6tables -t ${table} -A ISTIO_INBOUND -p tcp --dport "${port}" -j RETURN
544         done
**545         fi
546     else**

**Expected behavior**
same logic should be applied for both ipv4 and ipv6.
**Steps to reproduce the bug**
n/a
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.2
**How was Istio installed?**
n/a
**Environment where bug was observed (cloud vendor, OS, etc)**
n/a

**Comment by howardjohn** [comment] 2020-01-06 16:15
cc @rlenglet @abhide

**Comment by rlenglet** [comment] 2020-01-07 01:19
This has been missing since the initial PR that introduced IPv6 support: https://github.com/istio/istio/pull/11916.

**Comment by jleadford** [comment] 2020-02-05 00:48
@rlenglet , will this behavior be triggered in practice? Asked another way, is a `INBOUND_PORTS_INCLUDE` wildcard the default, or?

**Comment by emike922** [comment] 2020-03-30 13:33
We suspect it affects envoy access logs, which are not generated as expected in IPv6. Is this plausible?

**Comment by sha-rath** [comment] 2020-05-04 13:27
Yes, definitely the rule to capture all istio inbound traffic and redirect it to the envoy chain (`ip6tables -t nat -A ISTIO_INBOUND -p tcp --dport "${port}" -j ISTIO_IN_REDIRECT`) is missing in the IPv6 logic.

@emike922 it affects envoy access logs and I can confirm that adding this missing rule makes the logs visible on istio-proxy (sidecar) container. @sbezverk any idea when this fix would be merged? Thanks.

**Comment by lambdai** [comment] 2020-07-09 09:50
tools/istio-iptables/pkg/cmd/run.go at master has v6 catch all `ip6tables -t nat -A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT` and iptables.sh is erased from repo.

But I see other breakage, including exclude include disorder and dns/udp rules. Need a refactor.

**Closed** 2020-07-23 17:36 UTC
Labels: area/networking, lifecycle/needs-triage
