### ISSUE TITLE
OSX installation with make fails

### ISSUE THREAD

**Issue by Morriz** [istio/istio#16053] opened 2019-08-05 16:29 UTC
On OSX I get:
```
docker: Error response from daemon: Mounts denied:
The paths /etc/timezeone and /etc/localtime
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

**Comment by ericvn** [comment] 2019-08-09 17:19
Thanks for reporting the issue. I believe this was fixed in a number of PRs across various components over the last week.

If the problem is still occurring, would you point to a particular repo and command, and reopen the issue. Thanks

**Closed by ericvn** 2019-08-09 17:19 UTC
Labels: area/test and release
