### ISSUE TITLE
MongoDB TLS Egress not working using Bitnami helm charts "The server is configured to only allow SSL connections"

### ISSUE THREAD

**Issue by Aryan-NBS** [istio/istio#33323] opened 2021-06-08 12:45 UTC
Error: The server is configured to only allow SSL connections

[values-tls.zip](https://github.com/istio/istio/files/6616474/values-tls.zip)
I have attached the values. yaml.

**Comment by howardjohn** [comment] 2021-06-08 20:03
This looks like a duplicate of https://github.com/istio/istio/issues/33324

**Closed by howardjohn** 2021-06-08 20:03 UTC
