### ISSUE TITLE
Istio CNI race condition on cluster restart

### ISSUE THREAD

**Issue by NilsWild** [istio/istio#14327] opened 2019-05-23 07:34 UTC
**Bug description**
When restarting a cluster istio CNI doesnt setup correct routing depending on pod start time. Traffic is not proxied through sidecars. Restart of those pods with sidecars fix that. Seems to be like case 1 of https://github.com/istio/cni/issues/82 and might be related to these changes https://github.com/containernetworking/plugins/pull/269

**Expected behavior**
Traffic should be routed through sidecars after cluster restart even without restarting the pods.

**Steps to reproduce the bug**
Cluster with calico 3.4.4. Setup istio with istio-cni. Add some Pod with sidecar injection. Restart all cluster hosts. Result: Traffic not routed through sidecar.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubernetes: 1.13.5
istio: 1.1.7
calico: 3.4.4

**How was Istio installed?**
helm chart istio-init, istio-cni and istio with mTLS enabled

**Environment where bug was observed (cloud vendor, OS, etc)**
Bare Metal Ubuntu 18.04, Cluster Set Up with kubespray, ipvs proxy mode

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by NilsWild** [comment] 2019-05-23 07:54
As cni issues are not accessible anymore: https://github.com/istio/cni/pull/83 is the PR that should have fixed https://github.com/istio/cni/issues/82

**Comment by rlenglet** [comment] 2019-06-15 07:36
The solution should be to give a higher priority to the `istio-cni-node` pods using [priorityClassName](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#pod-priority) in the DaemonSet spec. [`priorityClassName: system-node-critical`](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/) is the highest priority and would be appropriate here. This will guarantee that the `istio-cni-node` pods [will always start first](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#effect-of-pod-priority-on-scheduling-order) on the nodes.

**Comment by rlenglet** [comment] 2019-06-15 07:40
Just in case, for running on older k8s versions, we should also set the [`scheduler.alpha.kubernetes.io/critical-pod: ""` annotation](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/), which will be deprecated.

**Comment by rlenglet** [comment] 2019-06-15 07:58
Sent a PR to do that: https://github.com/istio/cni/pull/126.

There is still a race condition with Calico. `istio-cni-node` should wait for Calico to start before installing the Istio CNI plugin.

**Comment by tiswanso** [comment] 2019-06-15 13:25
@rlenglet -- the install-cni script will detect its CNI config getting clobbered from the conflist and/or the conflist file being preempted by a new conf file.  Upon detecting that it will exit and on restart redo the istio-cni config logic to create or add to the cni conflist file.   

So, the ordering scenarios I see here are:
1.  calico -> istio-cni -> app pods
     - this is the normal and best case
2.  istio-cni -> calico -> app pods
     - this is the case where istio-cni might have to restart due to calico clobbering its config.  It needs to reapply prior to app pods coming up, so perhaps there's a window there.

In scenario 2, if we can't guarantee istio-cni pod restarts prior to app pods coming up, we'd have to see how we can more quickly detect cni config changes and restore istio-cni config.  Rather than install-cni polling, we can maybe use something like inotify to detect changes to the conflist file and possibly the cni conf directory but I'm not sure if there are other implications on the use of inotify in a pod.

But overall, is there a pointer to any best practices on node restarts in general and/or with Istio involved?  My understanding is typical maintenance reboots of nodes would involve a pod drain, cordon the node, reboot, ensure its operational, and finally uncordon.  In that sequence, the cni config should have time to converge before node uncordon.  So, I'm curious as to best practices/expectations for unexpected node reboots and how much effort we should put into prioritizing those.

**Comment by rlenglet** [comment] 2019-06-15 15:32
OK, that's good.

The issue we have is that we're not a "real" CNI. If we were a real CNI, the pods wouldn't be able to start until our CNI plugin is installed.

Another way to deal with this would be scan all existing pods on the node and update iptables for all running injected pods? That would allow us to upgrade the CNI too, after the injected pods are started.

**Comment by rlenglet** [comment] 2019-06-15 15:35
> we'd have to see how we can more quickly detect cni config changes and restore istio-cni config. Rather than install-cni polling, we can maybe use something like inotify to detect changes to the conflist file and possibly the cni conf directory but I'm not sure if there are other implications on the use of inotify in a pod.

I like that idea.
I would prefer to avoid restarting `istio-cni-node` as much as possible, since it uninstalls the CNI plugin when it exits, and we may miss pods starting at that time, so if we could eliminate this condition for restarting that'd be great.

And if we re-injected iptables redirect into existing pods when we restart, that would mitigate this issue even further.

**Comment by gotwarlost** [comment] 2019-10-03 21:48
Even after setting the priority classes to `system-node-critical`, the istio CNI/ calico race is pretty severe and happens often in our cluster (where we use the cluster autoscaler to scale out nodes just in time when pods are pending; this increases the odds of a non-critical pod being scheduled on the node as soon as it comes up).

We have ditched istio-cni because of this. What we saw today was:

* istio-cni and calico pods were started early
* istio-cni came up first and dropped a simple config because calico config was not present
* calico dropped its config
* istio-cni took 2 wait cycles to fix this which took around a minute
* in the meantime a regular pod was launched on the node

**Comment by artyomtkachenko** [comment] 2019-10-10 22:48
We ran into the same problem in our clusters when we scale up/down our node groups.
Thinking to use node taints as a workaround for this problem. 
The logic I am thinking of:
*  Always start node some special taint which repels all pods except the pods from <whatever>-cni , istio-cni and a special cni-check DaemonSets 
* Write a simple cni check DaemonSet which will wait for both CNIs to report "healthy" and remove the node taint, so other pods can be scheduled on it.

**Comment by gotwarlost** [comment] 2019-10-16 02:26
> * Write a simple cni check DaemonSet which will wait for both CNIs to report "healthy" and remove the node taint, so other pods can be scheduled on it.

Note that this may not be good enough. See the race condition I documented above. If the istio-cni comes up before calico, it drops a basic config and declares itself healthy. It then takes 2 wait cycles (~1m) for the istio cni config to be injected into the calico config and for the combination to be truly healthy. 

Even with your check, you might let slip a pod during the wait cycle without the istio CNI being applied.

**Comment by artyomtkachenko** [comment] 2019-10-16 03:31
It is a valid point @gotwarlost 
The two phase check,  taint update, i believe, can be used to workaround the issue you described. 

Like
*  taint node with two taints when booting 
*  remove first taint when whatever-cni is running
*  remove the second taint when istio-cni is running 

I will spike it when get some time.

**Comment by rlenglet** [comment] 2019-10-18 17:21
One way to mitigate this problem would be to lower the polling period, e.g., from 30 seconds to 5 seconds.

**Comment by duderino** [comment] 2019-10-23 18:15
@ruigulala is going to take this one, but since he's not yet a member of the Istio github org, I'll assign the bug to myself

**Comment by ruigulala** [comment] 2019-10-24 17:04
@rlenglet Went through all the above suggestions and did some digging. How about the following to mitigation?
1. Change the pod priority of istio-cni from system-node-critical to system-cluster-critical.
Since istio-cni depends on the "real" CNI, changing to a relatively lower priority level makes sure it's scheduled after calico and also makes sure it's scheduled before "normal" pods. 
https://docs.openshift.com/container-platform/3.11/admin_guide/scheduling/priority_preemption.html

2. Reduce the polling period from 30 seconds to 5 seconds as suggested.

**Comment by rlenglet** [comment] 2019-10-24 17:31
@ruigulala ok, that sounds like a good plan.

**Comment by gotwarlost** [comment] 2019-10-24 22:46
Some thoughts:

* Lowering the polling period to 1s has the effect of doing busy work for the entirety of the node's lifetime rather than just in the critical period where this race could happen.
* I don't know if cluster-node-critical vs cluster-system-critical would make a crucial difference. Perhaps it will. 
* The script exits when it finds a problem in the config (`check_install` function), which means that the container will be relaunched by the kubelet and is subject to crash loop backoffs. 

To me, the logic should be something along these lines:

* on startup, copy binaries, create a kubeconfig as is being done now
* wait in a 1s sleep loop for a real CNI config to appear (give up after 5 minutes or something)
* patch said config
* sleep in a loop with a longer interval and do the `check_install` thing.

This strategy will only exit the container when something is really borked rather than the more common case of the real CNI config not being present initially and later appearing. It has the effect of reducing the race and not depending on the kubelet to restart the container in timely fashion for the common case.

**Comment by artyomtkachenko** [comment] 2019-10-24 23:41
I can definitely say that playing with cluster-node-critical vs cluster-system-critical does not make any difference. I tried it before.

**Comment by ruigulala** [comment] 2019-10-25 16:25
@gotwarlost @artyomtkachenko Thanks for the comments. Do you have any minimum reproducible example I can use? The goal is to get a more accurate and detailed understanding of the root cause.

**Comment by duderino** [comment] 2019-10-25 18:06
Reopening until we're sure this actually fixes the problem

**Comment by ruigulala** [comment] 2019-11-06 22:31
> I can definitely say that playing with cluster-node-critical vs cluster-system-critical does not make any difference. I tried it before.

priorityClass requires a particular feature gate(DynamicKubeletConfig) to be enabled. Prior to Kubernetes 1.11, this feature gate is "false" by default. Do you have that flag enabled?
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
https://v1-13.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

If the above is not the case, do you mind to provide a minimum reproducible example for me to further investigate? Thanks.

**Comment by duderino** [comment] 2019-11-06 23:46
@artyomtkachenko ^

**Comment by mandarjog** [comment] 2019-11-21 06:11
@rlenglet can we use an initcontainer in addition to cni to test if cni was applied correctly? That init container should not need net_admin

**Comment by artyomtkachenko** [comment] 2019-11-21 20:39
> > I can definitely say that playing with cluster-node-critical vs cluster-system-critical does not make any difference. I tried it before.
> 
> priorityClass requires a particular feature gate(DynamicKubeletConfig) to be enabled. Prior to Kubernetes 1.11, this feature gate is "false" by default. Do you have that flag enabled?
> https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
> https://v1-13.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
> 
> If the above is not the case, do you mind to provide a minimum reproducible example for me to further investigate? Thanks.

Sorry guys for a delay in a reply. I might have missed it somehow.
I tried it in 1.13.7 (EKS)
system-cluster-critical   2000000000   false            24d
system-node-critical      2000001000   false            24d
critical-priority         10000        false            24d
high-priority             1000         false            24d
low-priority              10           false            24d
medium-priority           100          true             24d

I think the scheduling queue is too short ( just CNI and Istio CNI ) for  priorityClass to make any difference. 

Istio CNI always comes first -> fails -> restarts, but other pods get into a place between  fail and restart phase

**Comment by howardjohn** [comment] 2019-11-24 02:19
This is pretty trivial to reproduce on GKE with pre-emptible nodes. I am not sure how to simulate a pre-emption though so you have to wait 24hrs... This was on 1.3.x as well, haven't tried with 1.4

**Comment by michaeldduffield** [comment] 2019-11-25 15:03
I believe I'm seeing this issue on a GKE test cluster using pre-emptible nodes and Istio 1.4.0.

Sometimes (but not always) when the pod restarts after pre-emption the primary container starts to receive TLS traffic directly; in these cases the Istio iptables rules seem to be missing entirely from the pod.

Happy to do some more investigation the next time I see this, if anyone can point me towards something it would be useful for me to dig into further?

**Comment by mandarjog** [comment] 2019-11-25 16:06
I am working on a solution.

**Comment by mandarjog** [comment] 2019-11-26 03:08
The main issue here is that the plugin installation itself is done by a daemonset which races with other pods on the system. If an application pod starts before the installation is done, istio plug-in will not be called. The options I am considering
1. Use netd on gke so that installation is done by platform and not by a daemonset. Perhaps not call k8s platforms support it, but it will work for gke.
2. On CNi install, inspect pods on the node , and configure ones that are still not configured. Inside the injected proxy , proxy will stall for configuration to appear and not declare ready.

**Comment by rlenglet** [comment] 2019-11-26 06:29
> On CNi install, inspect pods on the node , and configure ones that are still not configured. Inside the injected proxy , proxy will stall for configuration to appear and not declare ready.

This needs to be done also on "re-install," i.e. anytime Istio CNI detects that the CNI plugin config has been modified.

**Comment by rlenglet** [comment] 2019-11-26 06:30
@mandarjog as we discussed, it will be tricky to scan the pods and/or network namespaces on the node and correlate pods with network namespaces, after the pods have been configured.

**Comment by rolandkool** [comment] 2019-11-28 10:25
> This is pretty trivial to reproduce on GKE with pre-emptible nodes. I am not sure how to simulate a pre-emption though so you have to wait 24hrs... This was on 1.3.x as well, haven't tried with 1.4

I've verified it is still an issue with 1.4. After a node got reinstalled, pods on that node no longer have the necessary iptable rules for envoy.

**Comment by svrc-pivotal** [comment] 2019-12-18 17:53
Here is how we workaround this.  

1.  Ensure `kubectl` binary is in the istio-cni image in a system path
2. Introduce an init container to wait for the parent CNI to come up, configurable by selector.

e.g. for Calico as parent installed as a DaemonSet:

```
 initContainers:
      - name: wait-for-parent
        image: parasubvert/istio-cni:1.4.0-sc2
        command: [ "sh", "-c"]
        args:
        - until kubectl get pods -n kube-system -l ${CNI_SELECTOR} -o json | jq -e -r ".items[] | select(.status.phase == \"Running\" and ([ .status.conditions[] | select(.type == \"Ready\" and .status == \"True\") ] | length ) == 1 ) | select (.spec.nodeName == \"${NODE_NAME}\") | .metadata.namespace + \"/\" + .metadata.name "; do
            echo "waiting for $NODE_NAME to come up";
            sleep 2;
          done;
        env:
        - name: CNI_SELECTOR
          value: "k8s-app=calico-node"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
containers:
        # This container installs the Istio CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: docker.io/istio/install-cni:1.4.0
```

**Comment by howardjohn** [comment] 2020-01-24 16:17
This is mitigated by @stewartbutler s work to add an init check, bumping to 1.6 milestone for future improvements

**Comment by stewartbutler** [comment] 2020-02-13 20:36
An additional controller has been added to the CNI daemonset which will detect uninitialized pods that have run the race condition against the CNI daemonset and either label them (so they can be identified by a controller or a cluster operator) or delete them (so their pod sandbox is recreated, thus rerunning the CNI setup). It has been added to master, 1.5, and 1.4.5. 

Associated PRs, for those interested: 
https://github.com/istio/istio/pull/19534
https://github.com/istio/istio/pull/20130
https://github.com/istio/istio/pull/20712
https://github.com/istio/cni/pull/226
https://github.com/istio/cni/pull/229
https://github.com/istio/istio/pull/20715
https://github.com/istio/istio/pull/20877
https://github.com/istio/installer/pull/654

And probably a few others I missed.

The iptables validation init container (which detects if the CNI rules are applied) is installed by default if you enable CNI in 1.4.5+, 1.5+, and master. It can be disabled by an istioctl or helm setting, if desired.

The repair controller will also be enabled by default in 1.4.5+, 1.5+, and master, and can also be disabled by an istioctl flag or helm setting. The pod deletion behavior will be disabled by default in 1.4.5, but from 1.5 onward it will be enabled by default so that CNI installations will repair themselves automatically. 

For 1.4.5+ CNI installations, a default installation will see the following changes: all pods with sidecars injected will also have a new unprivileged init container injected. This init container will run a few checks inside the pod to detect whether the correct iptables routing rules have been injected before start. If those rules are missing, the container will die with an error. The repair controller, a new container inside the existing istio-cni daemonset, will identify pods that have died with this error and label them with the kubernetes label `cni.istio.io/uninitialized=true`.

In 1.5+, the default behavior will be much the same, except that when detected as broken, the pods will be immediately deleted.

This should solve the problem until such time as additional machinery is in place in Kubernetes to guarantee that all CNI pods are reporting ready before workload pods begin to schedule on the node.

**Comment by stewartbutler** [comment] 2020-02-13 20:38
Closing the issue.

**Comment by marshallford** [comment] 2020-02-19 04:06
I upgraded from 1.4.4 to 1.4.5 with the stand alone operator and CNI enabled. I'm seeing pods with the label `cni.istio.io/uninitialized=true` as you described but the pods were created well after the CNI pod (single node cluster) was reporting ready. In addition, I can delete the pod after the CNI is ready and I still run into the issue when its replacement is spun up.

**Comment by marshallford** [comment] 2020-02-19 04:35
I'm still investigating but my current theory is that k3s doesn't use the standard `cniBinDir` and `cniConfDir` locations. If this is the case, it might explain a seperate problem I've been having that requires dest rules to get traffic from an ingress gateway to an injected pod.

**Comment by stewartbutler** [comment] 2020-02-19 17:41
@marshallford Thanks for reporting in! Can you please open up a new issue and assign it to me? This issue is getting a bit overloaded, so I'd like to separate it out, that way I can keep track of it while you are investigating the k3s angle.

**Comment by gotwarlost** [comment] 2020-02-25 16:17
I have used the phrase "software development should not be so hard" multiple times this week in various contexts :)

Is there an upstream issue in k8s for not requiring such shenanigans in order to set up chained CNI plugins in a sane way? Just curious.

**Comment by rlenglet** [comment] 2020-02-25 18:57
> Is there an upstream issue in k8s for not requiring such shenanigans in order to set up chained CNI plugins in a sane way? Just curious.

Yes. We will revive the Node Readiness Gates proposal:
https://github.com/kubernetes/enhancements/pull/1003

**Comment by duderino** [comment] 2020-02-25 18:58
> I have used the phrase "software development should not be so hard" multiple times this week in various contexts :)
> 

software development is hard, let's go shopping!

**Closed** 2020-03-05 00:20 UTC
Labels: area/networking/cni, bug bashed, cherrypick/release-1.4, lifecycle/needs-escalation

**Comment by jammerful** [comment] 2020-04-01 19:56
> An additional controller has been added to the CNI daemonset which will detect uninitialized 
> For 1.4.5+ CNI installations, a default installation will see the following changes: all pods with sidecars injected will also have **a new unprivileged init container injected**. This init container will run a few checks inside the pod to detect whether the correct iptables routing rules have been injected before start. If those rules are missing, the container will die with an error. The repair controller, a new container inside the existing istio-cni daemonset, will identify pods that have died with this error and label them with the kubernetes label `cni.istio.io/uninitialized=true`.

@rlenglet @stewartbutler I was trying to upgrade 1.4.5+, but I'm seeing the init-container doesn't comply with my Pod Security Policy. In particular, the init-container wants to have RW access to the root filesystem. Below is the error I'm seeing. Is there an actual need for the RW access?

```
Error creating: pods "XXX" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.readOnlyRootFilesystem: Invalid value: false: ReadOnlyRootFilesystem must be set to true]
```

**Comment by rlenglet** [comment] 2020-04-01 20:01
@jammerful please file a separate GitHub issue. In that new issue, please give your Istio configuration, esp. the flags you passed to enable Istio CNI. Also, please give the pod spec of a pod or replica set that is failing.
