### ISSUE TITLE
Helm charts not following idiomatic versioning

### ISSUE THREAD

**Issue by sdake** [istio/istio#12974] opened 2019-04-01 23:33 UTC
**Describe the bug**
The helm repo add is not properly setup.

**Expected behavior**
helm repo add works correctly.

**Steps to reproduce the bug**
```
sdake@beast-01:~/istio-1.1.0$ helm init --service-account tiller
$HELM_HOME has been configured at /home/sdake/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
sdake@beast-01:~/istio-1.1.0$ helm repo add istio.io https://storage.googleapis.com/istio-release/releases/charts
Error: Looks like "https://storage.googleapis.com/istio-release/releases/charts" is not a valid chart repository or cannot be reached: Failed to fetch https://storage.googleapis.com/istio-release/releases/charts/index.yaml : 404 Not Found
sdake@beast-01:~/istio-1.1.0$ 
```

**Version**
Istio 1.1.1, Kubernetes 1.14, metallb 0.7.3

**Installation**
See reproducer

**Environment**
Linux bare metal

**Extra Notes**
A helm repository contains all releases of Istio in tgz format created with `helm package version`.  An index file is then built which references these tgz files in one place.  This enables upgrade and installation of pinned versions.

More detailed documentation:
https://hackernoon.com/using-a-private-github-repo-as-helm-chart-repo-https-access-95629b2af27c

Cheers
-steve

**Comment by sdake** [comment] 2019-04-01 23:37
Just to be clear, only x.y.z versions should go here - not latest master builds.  This will prevent a future where our operators/SREs are stumped because their helm repo update doesn't produce new versions or land them on a daily release that is expired.

Cheers
-steve

**Comment by howardjohn** [comment] 2019-07-16 00:40
Closing, dupe of https://github.com/istio/istio/issues/15498

**Closed by howardjohn** 2019-07-16 00:40 UTC
Labels: area/test and release
