### ISSUE TITLE
Istio 1.6.4: Wrong Envoy endpoint for mesh services after numerous pods creation/deletion

### ISSUE THREAD

**Issue by ael-g** [istio/istio#25312] opened 2020-07-08 10:37 UTC
**Bug description**
When I increase the number of replicas on a deployment, say 1 -> 500, then when all new pods are running I scale it back to 1, I update another deployment which makes new pods popping, and then if I 
```
istioctl proxy-config endpoint any-pod-on-the-namespace
A_WRONG_IP:3001   HEALTHY     OK  outbound_.80_._.a-pod-created-after-upscale-downscale.svc.cluster.local

---
kubectl get endpoints a-deployment-updated-after-upscale
NAME          ENDPOINTS          AGE
a-pod-created-after-upscale-downscale   GOOD_IP:3001   39d
```
So I have the Kubernetes endpoints IP which is right for the service, but the one in Envoy's conf is wrong, resulting in services which cannot communicate with the newly created pod (the WRONG_IP is most probably the endpoint of the pod before deployment upgrade - I need to check that).

I'm not sure yet how to 'fix' things ubt restarting istiod/pod in the service mesh eventualy make it.

[X] Networking
[X] Performance and Scalability

**Expected behavior**
I can upscale/downscale any deployment as much as I want without breaking communication within the service mesh

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (507 proxies)

---
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
```
istioctl install --profile default
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment] 2020-07-09 00:19
Interesting.. that is not good. Just to clarify, you go from 1 -> 500 -> 1 for deployment A. Then, you scale an unrelated deployment, B (say, from 5 -> 10, as an example). 

Then the end result is for B we point to a wrong IP address? 

If possible would be great to know what the IP address actually is

**Comment by ael-g** [comment] 2020-07-09 07:02
@howardjohn this is almost this: I go from 1 -> 500 -> 1 for deployment A, and then update the image on deployment B -> Istio endpoint for service B is wrong.
I'm going to make new tests this morning to clarify if this wrong IP is from pod B before upscaling/downscaling deployment A.

**Comment by ael-g** [comment] 2020-07-09 07:45
So I can confirm, the situation is as follow:

0 - Deployment B has the same IP endpoints seen with `kubectl get endpoints` and `istioctl proxy-config endpoints any-pod-in-the-mesh`
1 - I go from 1 -> 500 -> 1 on deployment A
2 - I `kubectl edit` anything on deployment B -> new pods pops up
3 - `istioctl proxy-config endpoints pod-from-deployment-C` shows same IP endpoints for deployment B than on point 0, which are wrong (`kubectl get endpoints` shows the right ones)

However I see that `istioctl proxy-config endpoints pod-from-deployment-B` (the deployment I updated) shows the right IP endpoints for itself.

I also have lots of messages like this on istiod after scaling up/down deployment A:
````
2020-07-09T07:42:51.823192Z	error	Endpoint without pod 10.48.19.51 pod-from-deployment-A
2020-07-09T07:42:51.873902Z	warn	failed to get pod microservice/pod-from-deployment-A from kube-apiserver: pods "pod-from-deployment-A" not found
```
which was apparently an bug from an older istio version.

**Comment by stevenctl** [comment] 2020-07-13 22:53
@ael-g 

Having a hard time reproducing this:
```
$ k scale deployment a --replicas 500
deployment.apps/a scaled
$ k scale deployment a --replicas 1
deployment.apps/a scaled
$ k apply -f change-deployment-b.yaml
deployment.apps/b configured
$ k get ep b
NAME   ENDPOINTS                           AGE
b      10.32.3.142:9000,10.32.3.142:9001   58m
$ istioctl proxy-config endpoints "$(kubectl get pods -l app=c -ojsonpath='{.items[0].metadata.name}')" | grep 'b.default'
10.32.3.142:9000                 HEALTHY     OK                outbound|9000||b.default.svc.cluster.local
10.32.3.142:9001                 HEALTHY     OK                outbound|9001||b.default.svc.cluster.local
```

A couple of questions:

- What K8S version are you running? 
- How many istiod pods are you running?
- Is there other load on the control plane outside of this example/this namespace?

**Comment by ael-g** [comment] 2020-07-15 07:39
Oh I forgot to mention, the upscale/downscale is made through a HorizontalPodAutoscaler, setting minReplicas to 1 -> 500 -> 1 (maxReplicas stays at 500), and not directly on the deployment.
It seems to make a difference because I just tested again, it doesn't reproduce when upscaling the deployement, it reproduce when manually upscaling the HPA.

I originally ran into this problem because my HPA follows a Pub/Sub subscription which gets ~100k messages in some secs, making the HPA scaling the deployement very steeply (I see it's possible to slow it down which I guess may make the problem dissapear, but would not be very sturdy).

- What K8S version are you running?
Running on GKE: **1.15.9-gke.24**

- How many istiod pods are you running?
It goes from 1 to 4 during upscale (5 max on the HPA), but the load does not seem to be evenly reparted
```
istiod-6fcd4b5579-g6zh6                 133m         86Mi
istiod-6fcd4b5579-ltnhf                 1404m        377Mi      <- Seem to get all the load
istiod-6fcd4b5579-m4m25                 17m          86Mi
istiod-6fcd4b5579-rxnhm                 15m          93Mi
```

- Is there other load on the control plane outside of this example/this namespace?
No

Today, doing a `kubectl delete pod` on istiod was enough to fix the problem, istio and kube endpoints where reconciliated. But I'm almost sure it wasn't the case last week, I had to way some x10 minutes for the endpoints to reconciliate.
Is there a way to see if istiod is getting lag handling events ? If it misses some ?

**Comment by howardjohn** [comment] 2020-07-30 15:11
Possible related to https://github.com/istio/istio/issues/25112? Do you see any of the symptoms reported there, especially the "endpoint without pod" logs?

**Comment by ael-g** [comment] 2020-08-05 11:41
Indeed this seems related, and I do see the `endpoint without pod`.

**Comment by howardjohn** [comment] 2020-08-05 15:21
@ael-g that is fixed in 1.6.7. It would be great if you can try this out. Sending the wrong IP is a pretty nasty bug so I want to make sure if its not actually fixed we can give this some more attention

**Comment by howardjohn** [comment] 2020-08-24 22:58
@ael-g did you get a chance to try 1.6.7+?

**Comment by howardjohn** [comment] 2020-10-21 21:38
Since we don't have more info I will assume this is fixed. if not, please let us know

**Closed by howardjohn** 2020-10-21 21:38 UTC
Labels: area/networking, area/perf and scalability, kind/need more info, lifecycle/needs-triage
