### ISSUE TITLE
Better Webhook and domain cert support 

### ISSUE THREAD

**Issue by costinm** [istio/istio#15304] opened 2019-07-02 18:32 UTC
Explore the use of https://github.com/JoelSpeed/webhook-certificate-generator for managing
the Webhook configs and Pilot/Galley DNS-based certificates.

Example:
```
go get github.com/joelspeed/webhook-certificate-generator/cmd/webhook-certificate-generator

webhook-certificate-generator -a -n istio-system -s istio-pilot -k $KUBECONFIG -o pilot

```
Results in a secret named "pilot", signed by the public key of the Apiserver, with 

```
...
 Validity
            Not Before: Jul  2 18:06:00 2019 GMT
            Not After : Jul  1 18:06:00 2020 GMT
CN=istio-pilot.istio-system.svc
 X509v3 Subject Alternative Name: 
                DNS:istio-pilot, DNS:istio-pilot.istio-system, DNS:istio-pilot.istio-system.svc
```

For webhook (new installer in istio-control):

```
webhook-certificate-generator -a -n istio-control -s istio-sidecar-injector -k $KUBECONFIG -o injector --patch-mutating istio-sidecar-injector-istio-control
```

will update the mutating webhook with the apiservers own CA ( not sure if this is really needed - apiserver should recognize its own key ? ) and generates a secret with:

```
kubectl -n istio-control  get secrets injector -o 'go-template={{index .data "cert.pem"}}' | base64 -d > cert.pem
 openssl x509 -in cert.pem -text

...
 X509v3 Subject Alternative Name: 
                DNS:istio-sidecar-injector, DNS:istio-sidecar-injector.istio-control, DNS:istio-sidecar-injector.istio-control.svc
 Subject: CN = istio-sidecar-injector.istio-control.svc

```

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by costinm** [comment] 2019-07-02 18:35
Gaps so far:
- cert rotation after 1 year
- may need to be integrated as a library into operator/istioctl to not distribute a second binary

It would be nice to extend the tool to also generate SPIFFE certificates ( relatively easy, just 
change the CSR), and maybe to auto-generate them by watching the service accounts - this would provide equivalent functionality with citadel, but using K8S own CA.

**Comment by costinm** [comment] 2019-07-17 21:52
I did some testing for this - it's a pretty good library, works very nicely. 

https://github.com/costinm/webhook-certificate-generator has an extension to auto-generate DNS-based certs for istio service accounts ( in particular for webhooks ).

Confirmed that K8S can't sign URL SANs nor intermediary CAs - so this is only useful for DNS-based certs for webhooks or legacy services.

**Comment by ostromart** [comment] 2019-09-19 17:05
@costinm, can I mark this as a duplicate of https://github.com/istio/istio/issues/17060?

**Comment by ostromart** [comment] 2019-11-22 23:38
Duplicate of https://github.com/istio/istio/issues/17060, closing.

**Closed by ostromart** 2019-11-22 23:38 UTC
Labels: area/environments/installer, area/environments/operator, area/user experience, kind/enhancement
