### ISSUE TITLE
helm install fails due to incorrect default tag

### ISSUE THREAD

**Issue by wbrefvem** [istio/istio#6433] opened 2018-06-20 17:43 UTC
**Describe the bug**
`install/kubernetes/helm/istio/values.yaml` contains the wrong default tag name, so that helm attempts (and fails) to pull, e.g., `istio/proxyv2:0.8.latest`.

**Expected behavior**
The default tag value should match the latest tag on Docker Hub (currently `0.8.0`).

**Steps to reproduce the bug**
On a k8s cluster with Tiller installed, run the helm installation:
`helm install install/kubernetes/helm/istio --name istio --namespace istio-system` 

Then get pods in `istio-system` to see that pod scheduling has failed:
```
$ kubectl get po -n istio-system
NAME                                        READY     STATUS              RESTARTS   AGE
istio-citadel-74dd8f4d48-xb7gz              0/1       ImagePullBackOff    0          1h
...
istio-egressgateway-65995fdb46-pjjkx        0/1       ImagePullBackOff    0          1h
...
istio-ingress-569bdc546c-6m8xs              0/1       ImagePullBackOff    0          1h
istio-ingressgateway-6769ff64-j5zg4         0/1       ImagePullBackOff    0          1h
...
istio-policy-77f456ccb4-8pd6b               0/2       ImagePullBackOff    0          1h
...
istio-telemetry-7f9589c77b-jqxhg            0/2       ImagePullBackOff    0          1h
...
```
Finally read scheduler logs:
```
$ kubectl get ev --field-selector reason=BackOff -n istio-system
LAST SEEN   FIRST SEEN   COUNT     NAME                                                       KIND                      SUBOBJECT                         TYPE      REASON                    SOURCE                                        MESSAGE
37m         1h           130       istio-citadel-74dd8f4d48-xb7gz.1539e93e1c107138            Pod                       spec.containers{citadel}          Normal    BackOff                   kubelet, gke-cje-default-pool-592c27ab-mplr   Back-off pulling image "docker.io/istio/citadel:0.8.latest"
3m          1h           278       istio-egressgateway-65995fdb46-pjjkx.1539e93e5c58013e      Pod                       spec.containers{egressgateway}    Normal    BackOff                   kubelet, gke-cje-default-pool-592c27ab-mshn   Back-off pulling image "docker.io/istio/proxyv2:0.8.latest"
17m         1h           210       istio-ingress-569bdc546c-6m8xs.1539e93e1fcb8545            Pod                       spec.containers{ingress}          Normal    BackOff                   kubelet, gke-cje-default-pool-592c27ab-mshn   Back-off pulling image "docker.io/istio/proxy:0.8.latest"
8m          1h           256       istio-ingressgateway-6769ff64-j5zg4.1539e93df5c8265b       Pod                       spec.containers{ingressgateway}   Normal    BackOff                   kubelet, gke-cje-default-pool-592c27ab-9wmd   Back-off pulling image "docker.io/istio/proxyv2:0.8.latest"
3m          1h           274       istio-policy-77f456ccb4-8pd6b.1539e949a28016aa             Pod                       spec.containers{mixer}            Normal    BackOff                   kubelet, gke-cje-default-pool-592c27ab-mshn   Back-off pulling image "docker.io/istio/mixer:0.8.latest"
2m          1h           277       istio-telemetry-7f9589c77b-jqxhg.1539e93e32277789          Pod                       spec.containers{mixer}            Normal    BackOff                   kubelet, gke-cje-default-pool-592c27ab-9wmd   Back-off pulling image "docker.io/istio/mixer:0.8.latest"
```

**Version**
```
$ istioctl version 
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
`helm install install/kubernetes/helm/istio --name istio --namespace istio-system`

**Environment**
GKE 1.9.7

**Comment by ymesika** [comment] 2018-06-20 17:50
Duplicate of istio/old_issues_repo#387

**Closed by ymesika** 2018-06-20 17:50 UTC
