### ISSUE TITLE
Operator test takes 15min+ due to non-fatal failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37661] opened 2022-03-02 16:16 UTC
https://storage.googleapis.com/istio-prow/logs/integ-k8s-117_istio_postsubmit/1498866655147593728/build-log.txt

https://storage.googleapis.com/istio-prow/logs/integ-k8s-119_istio_postsubmit/1498866656842092544/build-log.txt

```
2022-03-02T03:57:38.694785Z	info	tf	=== BEGIN: Deploy echo instances ===
2022-03-02T03:57:43.576487Z	info	tf	=== DONE: Deploy echo instances ===
2022-03-02T03:57:43.672802Z	info	tf	=== succeeded ===
2022-03-02T03:57:43.672835Z	info	tf	cleaning up in-cluster CRs
    switch_cr_test.go:252: deleting CR test-istiocontrolplane
    switch_cr_test.go:252: deleting CR test-istiocontrolplane-v2
2022-03-02T03:57:43.684962Z	info	tf	waiting for pods in istio-system to be deleted
    switch_cr_test.go:276: failed to delete pods in istio-system: timeout while waiting after 1195 attempts (last error: pods still remain in istio-system)
```

Note the huge 15 min gap. Happens every time I think

**Comment by howardjohn** [comment] 2022-03-02 20:13
cc @litong01

**Comment by litong01** [comment] 2022-03-02 20:19
@howardjohn I am looking into this.

**Comment by litong01** [comment] 2022-03-02 20:59
@howardjohn after briefly looked at the issue, I think we are having a sequence issue here, the cleanup process trying to remove the istiod v2 but istio operator is still alive, while it is trying to remove, operator faithfully trying to recreate, so in this case, nobody wins, I think we just need to remove the operator first. Let me dig a bit deeper and see if we can fix this easily.

**Comment by litong01** [comment] 2022-03-03 00:44
The cleanup process was trying to delete the CR, but it got error like this.
```
Failed to delete resources with helm reconciler: action is required before deleting the iop instance: there are proxies still pointing to the pruned control plane: istio-ingressgateway-54cbdc7f48-m6rpl.istio-system..
```
That error prevented the Istiod instance (CR) being removed, thus the pods wont be removed, it went to a loop whose condition will never be satisfied, that is why it was waiting until 15 minutes timeout.

**Comment by litong01** [comment] 2022-03-03 04:00
@howardjohn john, the cause of the problem is that operator handles revisioned control plane differently. When a revisioned control plane to be removed, the operator will look for gateways, if there is any gateway still using the control plane, it will not allow the deletion to go on. This issue can be very easily recreated:

With a clean cluster, do the following:
1. Deploy a revisioned operator by running this command `istioctl operator init --revision=v2`
2. Once the operator is running, create a control plane by using the following:
```
cat << EOF | kubectl apply -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: test-istiocontrolplane-v2
  namespace: istio-system
spec:
  revision: v2
  profile: default
EOF
``` 
3. Once everything is running, you can delete the control plane, which will hang
```
   kubectl delete -n istio-system istiooperator test-istiocontrolplane-v2
```

Then the error msg from the operator log will show the following:
```
2022-03-03T03:45:57.531365Z	error	installer	Failed to delete resources with helm reconciler: action is required before deleting the iop instance: there are proxies still pointing to the pruned control plane: istio-ingressgateway-dfb7d8945-ztgz6.istio-system..
```

Even manually remove the gateway wont help because the operator will immediately recreate the gateway. So at this point, the control plane really stuck. There is no way to gracefully delete the control plane.

The test has a revisioned operator and revisioned control plane, that is why it is hanging until the timeout.

So I think that the operator revision is broken at present.

**Comment by litong01** [comment] 2022-03-03 04:05
@howardjohn at this moment, we either need to revisit the logic on why the existence of the gateway prevents the deletion being carried out or we can remove the revisioned operator tests to at least speed up the integration test. Let me know what you think.

**Comment by howardjohn** [comment] 2022-03-03 04:11
I don't know much about the operator itself for the first part. But fine
skipping this test for now (with a link to this issue so we don't
forget...) in the meantime if we cannot fix it quickly. Nice debugging

**Comment by litong01** [comment] 2022-03-03 14:27
@howardjohn John, I think that that the root cause is that the test uses same profile to create revisioned control plane and none revisioned control plane in the same namespace, which created a shared gateway, the revisioned gateway cannot be deleted for the reason I described above. So the fix is to rearrange the creation sequence of the control planes so that the gateway resource wont be owned by revisioned control plane. I will put up a PR asap.

**Comment by litong01** [comment] 2022-03-03 15:15
@howardjohn can we close this issue then? because of this https://github.com/istio/istio/pull/37684

**Closed** 2022-03-03 15:34 UTC
Labels: community/help wanted, area/environments/operator
