### ISSUE TITLE
Envoy locality weighted LB appears to require Outlier Detection

### ISSUE THREAD

**Issue by nmittler** [istio/istio#28942] opened 2020-11-16 23:55 UTC
Our [operations docs for Istio <= 1.7](https://istio.io/v1.6/docs/ops/configuration/traffic-management/locality-load-balancing/) as well as our [DR docs](https://github.com/istio/istio.io/pull/8402) imply that Outlier Detection is only needed for priority based LB (not weighted).

However, while working on a [task for locality LB](https://github.com/istio/istio.io/pull/8402), it seems that weighted distribution only works when Outlier Detection is enabled. Without it, the endpoints that are defined in the `Distribute` all share an even load, regardless of the weights.

Reference:

- [Envoy locality weighted LB](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight)

- [Istio Code](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go#L59)

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by nmittler** [comment] 2020-11-16 23:55
FYI @lambdai @howardjohn

**Comment by nmittler** [comment] 2020-11-19 18:26
@lambdai @howardjohn who is the right person to look into this?

**Comment by nmittler** [comment] 2020-11-24 21:04
This appears to be a pilot bug. I compared config dump (http://localhost:15000/config_dump?include_eds=true) with and without Outlier Detection. When it's set, the weight is set properly (e.g. `"load_balancing_weight": 70`). Without OD, all weights are `1`.

Will continue digging.

**Comment by nmittler** [comment] 2020-11-24 21:20
I've also confirmed in the pilot logs that envoy did not reject the config from Pilot and that pilot's EDS (via `http://localhost:8080/debug/edsz?proxyID=podname`) does not contain the correct weights.

Appears to confirm a pilot bug.

**Comment by ramaraochavali** [comment] 2020-11-25 13:55
Can you please add/refer to the config (Mesh Config/ DR etc) you are trying with?

**Comment by nmittler** [comment] 2020-11-25 18:41
@ramaraochavali I ran into this issue when preparing a new [docs task](https://github.com/istio/istio.io/tree/master/content/en/docs/tasks/traffic-management/locality-load-balancing/distribute) for locality distribution.

This task uses the default MeshConfig and [this DR](https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/snips.sh#L23). The task works fine with OD, but if I remove it traffic is balanced evenly across all clusters and the config_dump shows that everything has a weight of 1.

**Comment by ramaraochavali** [comment] 2020-11-27 04:44
@nmittler Thanks you for the details. I looked at the code but could not find any thing obviously wrong.  Weight calculation is not triggered other than [at this place](https://github.com/istio/istio/blob/748c6209f606fb2276bdd4abaf277d4979d172bc/pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go#L70) AFAIK.

@hzxuzhonghu Do you have any other thoughts?

**Comment by hzxuzhonghu** [comment] 2020-11-28 02:35
I found something skeptical,   we only set locality_weighted load balancing if outlier detection set.

```
	if c.OutlierDetection != nil {
		if c.CommonLbConfig == nil {
			c.CommonLbConfig = &cluster.Cluster_CommonLbConfig{}
		}
		// Locality weighted load balancing - set it only if Locality load balancing is enabled.
		if lbSetting != nil {
			c.CommonLbConfig.LocalityConfigSpecifier = &cluster.Cluster_CommonLbConfig_LocalityWeightedLbConfig_{
				LocalityWeightedLbConfig: &cluster.Cluster_CommonLbConfig_LocalityWeightedLbConfig{},
			}
		}
	}
```

**Comment by hzxuzhonghu** [comment] 2020-11-28 03:17
// Locality weights are only considered when :ref:`locality weighted load
	// balancing <arch_overview_load_balancing_locality_weighted_lb>` is
	// configured. These weights are ignored otherwise. If no weights are
	// specified when locality weighted load balancing is enabled, the locality is
	// assigned no load.

**Comment by ramaraochavali** [comment] 2020-11-28 06:10
Good catch

**Comment by nmittler** [comment] 2020-11-30 18:20
@hzxuzhonghu 

> 	// Locality weights are only considered when :ref:`locality weighted load
	// balancing <arch_overview_load_balancing_locality_weighted_lb>` is
	// configured. These weights are ignored otherwise. If no weights are
	// specified when locality weighted load balancing is enabled, the locality is
	// assigned no load.

Can you clarify the implications here? Does "locality weighted load balancing is configured" imply that outlier detection is also configured? I'm trying to understand if this is a restriction imposed by Envoy or if it's a potential pilot bug.

**Comment by hzxuzhonghu** [comment] 2020-12-01 07:57
It should equal to the below
```
c.CommonLbConfig.LocalityConfigSpecifier = &cluster.Cluster_CommonLbConfig_LocalityWeightedLbConfig_{
				LocalityWeightedLbConfig: &cluster.Cluster_CommonLbConfig_LocalityWeightedLbConfig{},
			}
```

I think we should document that it also requires outlier detection for distribute lb

**Comment by ramaraochavali** [comment] 2020-12-03 08:17
@nmittler once https://github.com/istio/istio/pull/29238 is merged, we should remove document part that Distribute needs outlier detection.

Also we should clarify,  that outlier detection is specified, Envoy recalculate weights  based on outlier detection results.

**Comment by ramaraochavali** [comment] 2021-01-29 05:28
reopening this since the PR is being reverted

**Comment by nmittler** [comment] 2021-01-29 17:30
@ramaraochavali please just test locally rather than reverting?

**Comment by ramaraochavali** [comment] 2021-02-01 11:36
@nmittler I do not know how to test it locally - but seems @ericvn tested it and found it is not because of this PR.

**Comment by nmittler** [comment] 2021-02-02 17:41
@ramaraochavali 

> Also this test https://github.com/istio/istio/blob/master/tests/integration/pilot/locality_test.go#L167 seems to validate distribute with outlier detection.

Yeah that's right. The plan is to remove outlier detection from this doc, but it should also work with outlier detection ... the fact that it doesn't is a regression.

I'm fine re-assigning the issue ... who would be the best person to pick this up?

**Comment by hzxuzhonghu** [comment] 2021-02-03 02:53
https://github.com/istio/istio/issues/30181#issuecomment-772153162

**Comment by ramaraochavali** [comment] 2021-02-03 04:08
Thank you @hzxuzhonghu for the find. I will close this issue as it is not the cause.

**Closed by ramaraochavali** 2021-02-03 04:08 UTC
Labels: area/networking
