### ISSUE TITLE
The HTTP header should be passed transparently without changing the case of the key.

### ISSUE THREAD

**Issue by pantianying** [istio/istio#30579] opened 2021-02-02 04:36 UTC
**Describe the feature request**

When I was using Istio to transparently hijack traffic, I found some applications reporting errors. It turns out that these applications have some irregular code. They are case-sensitive from the HTTP header values. For example, this is also the case in the code of nacos. 
![image](https://user-images.githubusercontent.com/20589945/106552752-d9c19c00-6552-11eb-90d3-f999f349e2fa.png)

**Describe alternatives you've considered**
While I know that the HTTP standard is to ignore the case of the key in the header, it is inevitable that many programmers have written code that does not comply with the specification. This code is difficult to troubleshoot, and when we use istio we have to check all the business logic, which is very difficult. So I think, if possible, the HTTP header should be copied and not modified.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment] 2021-02-02 15:48
Envoy does not currently support this. You can set a different casing (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-http1protocoloptions-headerkeyformat) but not preserve.

https://github.com/envoyproxy/envoy/issues/6589 *might* solve this, but the issue is about "path" so its not clear to me

**Comment by howardjohn** [comment] 2021-02-02 15:49
actually if you look at https://github.com/envoyproxy/envoy/issues/8463 it sounds like its pretty unlikely to happen

**Comment by howardjohn** [comment] 2021-02-10 17:27
Closing as this depends on Envoy implementation and they have said this will not happen. if this changes on Envoy side feel free to re-open. Thank you @pantianying !

**Closed by howardjohn** 2021-02-10 17:27 UTC
Labels: area/networking/envoy, area/user experience, kind/enhancement, kind/need more info

**Comment by antoniovicente** [comment] 2021-02-16 23:20
The code snippet in the first comment which does case-sensitive operations on HTTP request header keys does not comply with HTTP RFCs which state that header keys should be considered case insensitive.  It would be best to get that code fixed.
