### ISSUE TITLE
Config analysis should report Virtual Service with identical match clauses in different http blocks

### ISSUE THREAD

**Issue by synuwxy** [istio/istio#25533] opened 2020-07-15 10:28 UTC
I configured access latency and mirroring according to the official website, but they don't seem to work at the same time

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  creationTimestamp: "2020-07-15T10:26:20Z"
  generation: 2
  name: sample-foo-cluster01
  namespace: foo
  resourceVersion: "6137202"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/foo/virtualservices/sample-foo-cluster01
  uid: 78f6ef0f-a278-4767-a503-f7251a934708
spec:
  hosts:
  - sample.foo.svc.cluster.local
  http:
  - fault:
      delay:
        fixedDelay: 5s
        percentage:
          value: 100
    route:
    - destination:
        host: sample.foo.svc.cluster.local
  - mirror:
      host: sample.bar.svc.cluster.local
    route:
    - destination:
        host: sample.bar.svc.cluster.local
        subset: v1
```

Is it my wrong configuration?

**Comment by esnible** [comment] 2020-07-16 14:59
I can verify that when I applied this VirtualService mirroring was not enabled in the Envoy config.  I then applied a version without the fault, and saw `"request_mirror_policies"` in the Envoy config.  (Using Master branch).  The webhook does not see a problem with it, and neither does `istioctl analyze`.

I have added `area/user experience` because I am uncertain if this is a networking bug or validation/analysis bug.  Can someone from @istio/wg-networking-maintainers tell me if this SHOULD work?

- If it should work, this is a networking bug.
- If it should not work, the webhook should reject when a user tries to create this.

**Comment by GregHanson** [comment] 2020-07-17 19:44
@synuwxy you basically have two `http` blocks defined and both have an empty `match` criteria ([ref doc ](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute).  In VirtualService resources, the order matters, and envoy will use the first matching block.  Since no `match` criteria is provided, the first block (the delay in this case) will always match and the seconds block's behavior will never be seen.

If you want the see the 5sec delay to sample.foo.svc.cluster.local AND have the traffic mirrored sample.bar.svc.cluster.local:v1, you should only have 1 `http` block defined with both fault and mirror defined:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sample-foo-cluster01
  namespace: foo
spec:
  hosts:
  - sample.foo.svc.cluster.local
  http:
  - fault:
      delay:
        fixedDelay: 5s
        percentage:
          value: 100
    mirror:
      host: sample.bar.svc.cluster.local
      subset: v1
    route:
    - destination:
        host: sample.foo.svc.cluster.local

```

**Comment by esnible** [comment] 2020-07-17 20:20
@GregHanson would it make sense to create an analyzer that issues warnings for all VirtualService with >1 HTTPRoute with identical `match`?

Similar logic may help with TcpRoute and TlsRoute.

(Because the HttpMatchRequest/ L4MatchAttributes / TlsMatchAttributes are slices with **and** semantics when I say "identical" I mean order-independent identical)

**Comment by GregHanson** [comment] 2020-07-17 21:39
@esnible seems like a worthy addition - I can't think of any scenarios where this would be used (i.e. multiple http/tcp blocks with no matching criteria). It may be worth moving to the validation logic itself - but it's kind of grey area where it is a valid rule - but won't behave as expected.  So maybe istioctl is the best place for it

**Comment by synuwxy** [comment] 2020-07-18 05:47
> @synuwxy you basically have two `http` blocks defined and both have an empty `match` criteria ([ref doc ](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute)). In VirtualService resources, the order matters, and envoy will use the first matching block. Since no `match` criteria is provided, the first block (the delay in this case) will always match and the seconds block's behavior will never be seen.
> 
> If you want the see the 5sec delay to sample.foo.svc.cluster.local AND have the traffic mirrored to sample.bar.svc.cluster.local:v1, you should only have 1 `http` block defined with both fault and mirror defined:
> 
> ```
> apiVersion: networking.istio.io/v1beta1
> kind: VirtualService
> metadata:
>   name: sample-foo-cluster01
>   namespace: foo
> spec:
>   hosts:
>   - sample.foo.svc.cluster.local
>   http:
>   - fault:
>       delay:
>         fixedDelay: 5s
>         percentage:
>           value: 100
>     mirror:
>       host: sample.bar.svc.cluster.local
>       subset: v1
>     route:
>     - destination:
>         host: sample.foo.svc.cluster.local
> ```

That solved my question. Thank you very much

**Comment by esnible** [comment] 2020-08-03 20:19
This may be a duplicate of https://github.com/istio/istio/issues/23073

**Closed** 2020-09-08 07:06 UTC
Labels: area/user experience, kind/enhancement
