### ISSUE TITLE
Request for more DOCUMENTATION in addition to samples

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#12573] opened 2019-03-18 15:54 UTC
I have noticed that when one tries to do something a little bit different to the examples, Istio FAILS, and since almost all your documentation is based on examples, it is very hard to get what is going wrong.

I prefer to read hundreds and hundreds of pages, and get a solid knowledge of what is this technology, rather then to read all your examples for some specific scenarios, and have no idea why am I doing what am I doing?

I have already pointed out may be 20 "unexpected behavior"?, and I have no way to know what is it, because it is simply not documented.

You just come up with "and in this example we are going to do this", "and in this other example we are going to do that", "and now we are going to put a destination rule", "and now we are going to make it work without destination rules". Just give us the concepts. We already know that the book store and httpbin work fine.

So, my feature request is a decent documentation. All you have are scenarios that are not even explained in detail. There is a 1 or 2 lines of explanation, bunch of yaml files and commands to test...That's not a concept. That's just a bad way to learn.

**Comment by esnible** [comment] 2019-03-23 18:19
@nerusnayleinad I cannot find the 20 unexpected behavior items you mention.

**Comment by nerusnayleinad** [comment] 2019-03-29 18:54
Just go through "Issues" tab, and you will get more than 20. And if you pay attention, you will see that mostly people are doing tests with your examples, because there is simply no room to come up with more.

And it's not only the documentation that is missing, it also is the way you guys wrote it. Things like "client side Envoy also does a secure naming check to verify that the service account presented in the server certificate is authorized to run the target service.".

What does that mean? I know what you mean! But, what do you mean with "service account presented in the server certificate is authorized to run the target service"? Run the target service? It just doesn't make sense.

This is just a feature request. Note that it is not only about a good product, but also about a good documentation. Someone who writes code is not necessarily entitles to write documentation, and I have the impression that your docs are written by the same guys who write Istio source code.

**Comment by howardjohn** [comment] 2019-06-17 15:05
@nerusnayleinad guilty as charged, a lot of our docs are written by our devs and could use some improvements :slightly_smiling_face:. We have a ton of ongoing work on the docs side at https://github.com/istio/istio.io. There are at least 4 people I know of dedicating 80%+ of their time to the docs and have made a lot of improvements - especially the concept pages you mentioned, and they are focusing on exactly what you are talking about, explaining concepts, making things more clear, etc.

Since we have people working on this, I don't think there is any actionable work off of this issue so I am going to close it if that is alright (we are trying to trim down are issues so we don't lose track in the sea of issues, etc).

If you do have specific feedback on areas that are confusing, it would be greatly appreciated as an issue at https://github.com/istio/istio.io. I think there is a button on each page to report an issue directly as well, but we may have gotten rid of that.

Thanks for bringing this up!

**Closed by howardjohn** 2019-06-17 15:05 UTC
Labels: area/user experience, kind/docs, kind/need more info, kind/question
