### ISSUE TITLE
mixer adapter listening on check event is never called (since ISTIO 1.4)

### ISSUE THREAD

**Issue by NilsRenaud** [istio/istio#19067] opened 2019-11-19 11:02 UTC
**Bug description**

My custom mixer adapter that listened on check events is not called anymore when a service is accessed. 

I guess that's because of the move of telemetry from mixer to envoy proxy. So are the adapter listening on check events are deprecated ? Or is that a bug ?

**Expected behavior**

An out of process adapter listening on check events should be called on each service call.

This expected behavior comes from version <1.4.0. 

**Steps to reproduce the bug**

Create an out of process adapter listening on check events. It is never called.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (3 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

On minikube, using the demo profile : 
```
$ istioctl manifest apply --set profile=demo
```

**Environment where bug was observed (cloud vendor, OS, etc)**

minikube for MacOs.

**Comment by kyessenov** [comment] 2019-11-19 16:47
Did you enable policy during installation? The policy external adapters should continue to work. Telemetry v2 is separate from policy checks.

**Comment by bianpengyuan** [comment] 2019-11-19 16:55
I think demo profile should have policy check enabled: https://github.com/istio/operator/blob/b6be277e9613a4acdd8acbbb8919165499ed4d4a/data/profiles/demo.yaml#L68

So you probably should check (1) error logs in istio-policy pod, if any (2) istio-policy pod's metrics (:15014/metrics).

**Comment by NilsRenaud** [comment] 2019-11-22 16:41
So did I, I checked the logs in istio-policy, there is no errors in the log not even in the metrics.

I can't see any interactions in any logs between the the envoy side car proxy and the istio-policy pod.

@kyessenov is there a way to print the MeshConfig currently applied in an Istio managed cluster ? This way I would be sure that the policy is enabled.

**Comment by howardjohn** [comment] 2019-11-24 02:20
@nilsrenaud try `kubectl -n kube-system get cm istio -o jsonpath={.data.mesh} `

**Comment by howardjohn** [comment] 2019-11-24 02:23
I just tried this, in the demo policy checks are disabled. Most likely the same root cause as #19139 @richardwxn

**Comment by NilsRenaud** [comment] 2019-11-25 09:38
Agreed with @howardjohn, Here is what I got after my demo profile installation: 

```
$ istioctl manifest apply --set profile=demo
[...]
$ kubectl -n istio-system get cm istio -o jsonpath={.data.mesh}
[...]
disablePolicyChecks: true
[...]
```

**Comment by NilsRenaud** [comment] 2019-11-27 14:10
A workaround to this demo profile bug is to run this command after having deployed Istio's Demo profile : 

```
$ istioctl manifest apply --set values.pilot.policy.enabled=true
```

**Comment by howardjohn** [comment] 2019-12-20 17:08
Closing as a duplicate of https://github.com/istio/istio/issues/19139. Thanks!

**Closed by howardjohn** 2019-12-20 17:08 UTC
Labels: area/policies and telemetry, lifecycle/needs-escalation
