### ISSUE TITLE
Connection Failure to a MySQL Service

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#10062] opened 2018-11-20 01:01 UTC
**Describe the bug**
When running a MySQL service over Istio, other services are able to discover it; however, on attempting a connection, the following error is observed.

```console
$ kubectl run -i --tty --rm mysql-cli --image=mysql --restart=Never -- mysql -hmysql.default.svc.cluster.local -uroot -proot
If you don't see a command prompt, try pressing enter.

ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
pod "mysql-cli" deleted
```

**Expected behavior**
The connection should succeed.

**Steps to reproduce the bug**
Create the necessary storage.

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: "fast"
  selector:
    matchLabels:
      release: dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmp-mysql-1
  labels:
    release: dev
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "fast"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/mysql
```

Deploy MySQL with the following config.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    name: tcp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        version: v1
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.22
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
      restartPolicy: Always
```

**Version**
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

```console
$ istioctl version
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

**Installation**
Using `istio-demo.yaml`.

**Environment**
Local Ubuntu 18.04 cluster.

**Comment by dotw** [comment] 2018-11-23 07:35
I have checked the proxy-config endpoint and it listen on 3306, but it can't be connected through another client without sidecar.
```
[root@ri-32 mysql]# istioctl proxy-config endpoint mysqldb-v1-7bd5cb6987-zhxtm -n qq2 | grep inbound
127.0.0.1:3306          HEALTHY     inbound|3306||mysqldb.qq2.svc.cluster.local
```
```
[root@ri-32 mysql]# kubectl exec -it mysqldb-v2-67b69498b-twjsj sh -n qq2
# mysql -h mysqldb.qq2.svc.cluster.local -uroot -p
Enter password:
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
#
```

**Comment by maorfr** [comment] 2018-11-26 09:39
Hi,

We are also facing this issue, and found that it is related to the default `MeshPolicy`.
Do you get a `CONFLICT` when running this command?
```
istioctl authn tls-check mysqldb.qq2.svc.cluster.local
```
Deleting the default `MeshPolicy` solved this issue right away:
```
kubectl delete meshpolicies.authentication.istio.io default
```

@venilnoronha can this be an issue with the `PERMISSIVE` mode for tls?

**Comment by mabushey** [comment] 2018-11-28 22:07
All versions of Istio above 1.0.2 (ie 1.0.3 and 1.0.4) have this bug.

**Comment by mabushey** [comment] 2018-11-28 22:18
```
istioctl authn tls-check  cdx-mysql.wordpress.svc.cluster.local
Warning! error execing into istio-pilot-864dc8c497-qlg5t/istio-system discovery container: gc 1 @0.010s 4%: 0.010+0.53+0.41 ms clock, 0.082+0.063/0.72/1.1+3.3 ms cpu, 4->4->1 MB, 5 MB goal, 8 P
gc 2 @0.018s 6%: 0.006+0.51+0.68 ms clock, 0.050+0.33/0.68/1.6+5.4 ms cpu, 4->4->2 MB, 5 MB goal, 8 P

HOST:PORT                                      STATUS       SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
cdx-mysql.wordpress.svc.cluster.local:3306     CONFLICT     mTLS       HTTP       default/         -
```

**Comment by mabushey** [comment] 2018-11-29 00:57
```
kubectl get meshpolicies.authentication.istio.io default -o yaml
apiVersion: authentication.istio.io/v1alpha1
kind: MeshPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"authentication.istio.io/v1alpha1","kind":"MeshPolicy","metadata":{"annotations":{},"labels":{"app":"istio-security","chart":"security-1.0.4","heritage":"Tiller","release":"istio"},"name":"default","namespace":""},"spec":{"peers":[{"mtls":{"mode":"PERMISSIVE"}}]}}
  creationTimestamp: 2018-11-28T23:52:37Z
  generation: 1
  labels:
    app: istio-security
    chart: security-1.0.4
    heritage: Tiller
    release: istio
  name: default
  resourceVersion: "6425"
  selfLink: /apis/authentication.istio.io/v1alpha1/meshpolicies/default
  uid: af51778d-f368-11e8-8c24-02ab19fe584a
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
```

This mesh policy was added in 1.0.3, and explains why 1.0.2 was the last working version.

**Comment by mabushey** [comment] 2018-11-29 01:02
```
cat istio-destination.yaml
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "default"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

kubectl apply -f istio-destination.yaml
destinationrule.networking.istio.io/default created

istioctl authn tls-check  cdx-mysql.wordpress.svc.cluster.local
Warning! error execing into istio-pilot-864dc8c497-76c7v/istio-system discovery container: gc 1 @0.010s 7%: 0.007+0.50+0.75 ms clock, 0.059+0.068/0.68/1.0+6.0 ms cpu, 4->4->2 MB, 5 MB goal, 8 P
gc 2 @0.016s 8%: 0.005+0.44+0.49 ms clock, 0.047+0.047/0.73/1.7+3.9 ms cpu, 4->4->2 MB, 5 MB goal, 8 P

HOST:PORT                                      STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
cdx-mysql.wordpress.svc.cluster.local:3306     OK         mTLS       mTLS       default/         default/default
```
This gets rid of the conflict but results in a different mysql error:
```
mysql -h cdx-mysql -ppa554cdx_n0w_1n
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2026 (HY000): SSL connection error: socket layer receive error
```

**Comment by rafik8** [comment] 2018-11-30 11:53
> Hi,
> 
> We are also facing this issue, and found that it is related to the default `MeshPolicy`.
> Do you get a `CONFLICT` when running this command?
> 
> ```
> istioctl authn tls-check mysqldb.qq2.svc.cluster.local
> ```
> Deleting the default `MeshPolicy` solved this issue right away:
> 
> ```
> kubectl delete meshpolicies.authentication.istio.io default
> ```
> @venilnoronha can this be an issue with the `PERMISSIVE` mode for tls?

Deleting the default MeshPolicy resolve the issue for me. Thank you @maorfr for sharing this workaround. I spent two days debugging the whole platform end to end, I haven't get this path in my mind as mTLS is disabled in my case, so strange that we had mTLS disabled and getting the connection served over mTLS.

**Comment by rafik8** [comment] 2018-11-30 11:56
> ```
> cat istio-destination.yaml
> apiVersion: "networking.istio.io/v1alpha3"
> kind: "DestinationRule"
> metadata:
>   name: "default"
>   namespace: "default"
> spec:
>   host: "*.local"
>   trafficPolicy:
>     tls:
>       mode: ISTIO_MUTUAL
> 
> kubectl apply -f istio-destination.yaml
> destinationrule.networking.istio.io/default created
> 
> istioctl authn tls-check  cdx-mysql.wordpress.svc.cluster.local
> Warning! error execing into istio-pilot-864dc8c497-76c7v/istio-system discovery container: gc 1 @0.010s 7%: 0.007+0.50+0.75 ms clock, 0.059+0.068/0.68/1.0+6.0 ms cpu, 4->4->2 MB, 5 MB goal, 8 P
> gc 2 @0.016s 8%: 0.005+0.44+0.49 ms clock, 0.047+0.047/0.73/1.7+3.9 ms cpu, 4->4->2 MB, 5 MB goal, 8 P
> 
> HOST:PORT                                      STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
> cdx-mysql.wordpress.svc.cluster.local:3306     OK         mTLS       mTLS       default/         default/default
> ```
> This gets rid of the conflict but results in a different mysql error:
> 
> ```
> mysql -h cdx-mysql -ppa554cdx_n0w_1n
> mysql: [Warning] Using a password on the command line interface can be insecure.
> ERROR 2026 (HY000): SSL connection error: socket layer receive error
> ```

Hi @mabushey, What I can see from the tls-check command that mTLS is enabled, could you disable mTLS and retest ?

**Comment by mabushey** [comment] 2018-11-30 19:23
@rafik8 yes, disabling mTLS works, having meshpolicies.authentication.istio.io setting for mTLS (added in all istio releases newer than 1.0.2) just bricks all internal traffic. I figured if mTLS is sent on the receiving (server) end, then adding the DestinationRule to make both client and server use mTLS would work. The STATUS shows OK, but it still does not work. Really strange why istio is shipping releases with internal networking defective as the default. :/

**Comment by rshriram** [comment] 2018-11-30 20:03
I think @diemtvu wanted to set the default policy to PERMISSIVE but @costinm had some reservations.

**Comment by rafik8** [comment] 2018-11-30 22:04
> @rafik8 yes, disabling mTLS works, having meshpolicies.authentication.istio.io setting for mTLS (added in all istio releases newer than 1.0.2) just bricks all internal traffic. I figured if mTLS is set on the receiving (server) end, then adding the DestinationRule to make both client and server use mTLS would work. The STATUS shows OK, but it still does not work. Really strange why istio is shipping releases with internal networking defective as the default. :/

I see now @mabushey, I will enable mTLS and retest to confirm that.

**Comment by saturnism** [comment] 2018-12-14 08:42
is there a solution for keeping the default meshpolicy?

**Comment by incfly** [comment] 2018-12-14 18:07
In another issue, we find some issue for default mesh policy in 1.0.x, but fixed somehow in 1.1. MySQL issue might be the same...

**Comment by mabushey** [comment] 2018-12-14 19:18
@incfly So the issues have issues?

**Comment by incfly** [comment] 2018-12-18 06:16
@mabushey Not sure what you mean by "issues have issues"?

@mabushey @venilnoronha could you try see if the issue still exists with 1.1 snapshot release? https://github.com/istio/istio/releases 

I''m working on adding an e2e test for `permissive` mode to make sure app is able to terminate tls traffic by itself.

**Comment by zombor** [comment] 2019-01-08 22:23
Can anyone chime in about what

```
kubectl delete meshpolicies.authentication.istio.io default
```

affects other than fixing this bug? We've ran into it, but I'm curious about what other impact it has.

**Comment by zombor** [comment] 2019-01-09 18:14
I guess this means that turns off service-to-service TLS encryption? Any way to fix this bug without disabling TLS?

**Comment by zombor** [comment] 2019-01-10 14:43
I was able to get things working by applying this `DestinationRule`

```
cat <<EOF | kubectl apply -f -
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "istio-client-mtls"
spec:
  host: "*.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```

I'm able to connect to mysql from another pod after this was applied.

**Comment by YealZoy** [comment] 2019-01-28 07:43
> I was able to get things working by applying this `DestinationRule`
> 
> ```
> cat <<EOF | kubectl apply -f -
> apiVersion: "networking.istio.io/v1alpha3"
> kind: "DestinationRule"
> metadata:
>   name: "istio-client-mtls"
> spec:
>   host: "*.svc.cluster.local"
>   trafficPolicy:
>     tls:
>       mode: ISTIO_MUTUAL
> EOF
> ```
> And this MeshPolicy:
> 
> ```
> cat <<EOF | kubectl apply -f -
> apiVersion: "authentication.istio.io/v1alpha1"
> kind: "MeshPolicy"
> metadata:
>   name: "default"
> spec:
>   peers:
>   - mtls:
>         mode: PERMISSIVE
> EOF
> ```
> I'm able to connect to mysql from another pod after this was applied.

thank you

**Comment by bussyjd** [comment] 2019-02-04 23:58
I have been affected by this with istio version 1.0.5

```
kubectl delete meshpolicies.authentication.istio.io default
```

Did indeed fix it

**Comment by liemng** [comment] 2019-02-06 18:45
FYI... If you don't want to disable mTLS globally, you can just disable mTLS for mysql only:

apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "mysql-policy"
spec:
  targets:
  - name: mysql
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "mysql-policy"
spec:
  host: mysql
  trafficPolicy:
    tls:
      mode: DISABLE

**Comment by cmeyertons** [comment] 2019-02-12 12:49
had the same issue connecting from AKS -> external Azure MySql database.

performing the combination of `ServiceEntry` & `Destination Rule` worked for me:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: magento-to-mysql
spec:
  hosts:
  - mydb.domain.com
  ports:
  - number: 3306
    name: mysql
    protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: "magento-to-mysql"
spec:
 host: mydb.domain.com
 trafficPolicy:
   tls:
     mode: DISABLE
```

**Comment by dkrieger** [comment] 2019-02-20 19:14
> @zombor
> 
> > Any way to fix this bug without disabling TLS?
> 
> The bug is TLS is broken.

@mabushey  can you give a little explanation here?

If I'm understanding the gist of this, this seems like a pretty serious issue affecting a very typical use case for istio, but the tone of the discussion here doesn't seem to reflect that. Surely the elevator pitch of "istio creates a secure mesh between your services" isn't realized if it doesn't work for mysql, one of the most popular databases in the world. If this is fixed in 1.1, are there plans to backport the fix to 1.0?

**Comment by mabushey** [comment] 2019-02-20 19:37
@dkrieger

No one cares about the pitch of "istio creates a secure mesh between your services" because it's a fallacy. MySQL is not an outlier, it's just the current example. Istio provides awesome routing rules, and the grafana/Jaeger integration is showing promise of being a useful tool someday.

If you enable mTLS, you have a broken cluster.

**Comment by incfly** [comment] 2019-02-20 19:40
The TLS broken is not accurate. I believe if we change MTLS policy from PERMISSIVE to STRICT and configure DestinationRule correspondingly, the MTLS should work. I'll come back after deploy a mysql to verify that.

Thanks for the suggestion of backporting the fix from 1.1 to 1.0. I think a reasonable thing to do is removing `PERMISSIVE` by default in potential 1.0.7.

Sorry about the friction.

**Comment by zombor** [comment] 2019-02-20 19:48
> Thanks for the suggestion of backporting the fix from 1.1 to 1.0. I think a reasonable thing to do is removing `PERMISSIVE` by default

this is what we've done. Enable strict TLS, and add a destinationrule that turns off mtls to mysql and it works fine. We'd still like to get mTLS working against mysql, though.

**Comment by dkrieger** [comment] 2019-02-20 20:27
@incfly that's encouraging, I'll also experiment with configs and report back my findings. I'm on istio 1.0.5

@mabushey

> No one cares about the pitch of "istio creates a secure mesh between your services" because it's a fallacy.

This is a bold statement, considering the second-most prominent card on the istio.io homepage reads:

> **Secure**
> Automatically secure your services through managed authentication, authorization, and encryption of communication between services.

I gather you're a frustrated early adopter and not a maintainer. If the second word in "Connect, secure, control, and observe services." is sufficiently broken to be accurate, there should be a lot more focus on 1.0.X than 1.1.X to fix this massive bug. If it's a matter of bad configuration as @incfly seems to think, and the mtls functionality fundamentally works, a bugfix release is certainly in order, and maybe a prominently documented workaround (no, turning off mtls is not a workaround) in the meantime.

**Comment by mabushey** [comment] 2019-02-20 21:45
@dkrieger 

> This is a bold statement, considering the second-most prominent card on the istio.io homepage

You probably mean second-most prominent item of disinformation. I doubt the developers are in any kind of agreement as to the overall goals. The istio.is site is so far from reality it's a waste of time even looking at it; It's all wrong. If there is a tutorial of 12 steps, step 1 will error/not apply. Even the spec pages have yaml elements listed the wrong item. Istio is a great product I'm using in production. I just don't confuse myself by looking at the site anymore.

**Comment by Bessonov** [comment] 2019-02-20 22:02
@mabushey although your statement isn't far from reality, well, it isn't fair. It is not how the open source works. If you find a mistake, you are welcome to open an appropriate pull request.

By the way, I give up istio because it is far away from to be production ready. Go from istio error to istio bug doesn't make any fun. But I'm open to look at it some time later again.

**Comment by dkrieger** [comment] 2019-02-20 22:11
@incfly I tried modifying the default MeshPolicy to specify mtls.mode = "STRICT" and ensured the default DestinationRule specified trafficPolicy.tls.mode = "ISTIO_MUTUAL" to no avail. This is disappointing to say the least. I've also tested redis and while at first it appeared to work, it no longer works ("Error: Connection reset by peer"). So, as a blanket statement, it appears that mtls exclusively works for HTTP. Yikes.

@Bessonov have you found another sidecar-based solution for transparent mTLS? This was the biggest selling point for Istio in my book, and not only does it not work, but it's a claimed feature in a v1+ release.

**Comment by Bessonov** [comment] 2019-02-20 22:23
@dkrieger the solution in https://github.com/istio/istio/issues/10062#issuecomment-453119184 works for me with istio 1.0.5. I'm not on my work PC to validate it, but I'm sure I used `mode: STRICT` for `MeshPolicy`. Only tcp auth doesn't work now, but should be fixed in 1.1.

One of most painful point is actually the sidecar-based solution. Most of problems ([like non-root containers](https://github.com/istio/istio/pull/10507)) I can resolve with my custom helm-based (template + script + apply) automation workflow. But I have way too much workarounds and headaches with istio.

**Comment by dkrieger** [comment] 2019-02-20 22:35
@Bessonov thanks, I'll have another look at that solution. Do you use something like consul connect in production instead of istio? I'm about ready to jump ship over this, despite what the project's version implies, I have to agree istio does not seem production ready. I've already sunk considerable time into getting it working (or so I thought), and now this problem rears its head. If the solution you referenced fails for my use case, I'm afraid it's game over.

**Comment by Bessonov** [comment] 2019-02-20 22:46
@dkrieger we had very bad experience with consul and docker and because I don't even look at consul connect. Look at [Linkerd 2](https://linkerd.io/2/reference/architecture/). It's another sidecar-based solution. I hope https://github.com/istio/istio/issues/11366 can resolve some problems, but I'm not deep enough in this topic.

BTW, check it [with this one](https://github.com/istio/istio/issues/10062#issuecomment-442626457). After I get `OK` everything was fine. And I don't used `host: "*.svc.cluster.local"`, but specify concrete service in it's namespace.

**Comment by dkrieger** [comment] 2019-02-20 22:51
@incfly  @mabushey

The crucial edit to the default DestinationRule in my case was `host: "*.local"` -> `host: "*.svc.cluster.local"`, that was the final missing piece that I had overlooked when looking at the DestinationRule described in <https://github.com/istio/istio/issues/10062#issuecomment-453119184> (thanks @Bessonov).

It's not obvious to me why the previous configuration worked for HTTP, and sometimes TCP (redis), but the new configuration works for mysql/redis/misc TCP services. Now I'm worried I need to add my own sidecar to snoop on the network traffic to make sure it's actually being encrypted consistently.

**Comment by dkrieger** [comment] 2019-02-20 23:02
> @dkrieger we had very bad experience with consul and docker and because I don't even look at consul connect. Look at [Linkerd 2](https://linkerd.io/2/reference/architecture/). It's another sidecar-based solution. I hope #11366 can resolve some problems, but I'm not deep enough in this topic.
> 
> BTW, check it [with this one](https://github.com/istio/istio/issues/10062#issuecomment-442626457). After I get `OK` everything was fine. And I don't used `host: "*.svc.cluster.local"`, but specify concrete service in it's namespace.

'*.svc.cluster.local' as well as your solution of explicitly defining the desired service and applying the DestinationRule to the same namespace suggests that the namespacing had a lot to do with the issue. I installed istio 1.0.5 to the cluster using a barely modified set of values w/ the distributed helm chart, so maybe some default config improvements ought to be made in an upcoming point release as previously mentioned.

Given that the workaround seems to be working for me (a couple more smell tests to perform first), I'll probably stick with Istio for this project (it's part of a continuous delivery system that doesn't actually deploy to production), but Linkerd2 seems like a great alternative to investigate for future usage -- a quick google suggests it may even interop with Istio.

**Comment by mabushey** [comment] 2019-02-20 23:36
@dkrieger @Bessonov 

Thanks for your notes here. For me, Istio is production ready with the following considerations:

1. Any new Istio version needs to be fully tested. Quirks will probably surface that need to be resolved before deploying to prod. The community is awesome.
2. Some services just don't seem to work with a sidecar, such as services that initiate outgoing SSL connections. For these, I run them in a namespace without sidecars. Routing still works perfect.
3. Ignore the docs. They are a net negative. Github issues provide valid info.

**Comment by incfly** [comment] 2019-02-27 05:48
Sorry for the delay of the response. Long story short.

- Permissive mode does not work for MySQL where server side initiates the TLS handshake per @rshriram . 
- The solution is to change it to authn to STRICT and set DestinationRule TLSSettings to ISTIO_MUTUAL correspondingly.
- Why `*.cluster.local` and `*.local` behaves differently is unknown and might be a networking API bug or conflicting config. We need to follow-up separately.
- @rshriram made a change #11907 where if you specify port name as "mysql-xx" we will ignore `PERMISSIVE` mode.

Action items for this issue
1. Document the limitation for MySQL in istio.io
1. Add a release qualification for a MySQL deployment.

**Comment by incfly** [comment] 2019-02-27 19:48
In addition to that, we could add a special handling for `istioctl authn tls-check` for mysql service. If the k8s service define the port name as `mysql-xx`, istioctl will ensure combination of no `authn.PERMISSIVE` configured on MySQL pod. This will not help if customers define the service port name as "tcp".

/cc @diemtvu

**Comment by mabushey** [comment] 2019-02-28 18:19
@rshriram
> if you specify port name as "mysql-xx" we will ignore PERMISSIVE mode

What the hell? Who thinks this is acceptable? Networking should not act totally different based on the name. This is already being done with the http and https prefixes and has caused tons of confusion because it's not something anyone else does. This is insanity. How about making things work right and not changing the behavior based on a name?  I'd prefer to have Istio stick around, but choices like this are going to make Linkerd2 (or another project) become the winning service mesh.

**Comment by esnible** [comment] 2019-02-28 18:44
Should we consider using a Kubernetes Annotation in addition to the port *name* to control behavior?

If I saw something like this I would understand that this port is special.

```
      annotations:
        sidecar.istio.io/mysql-protocol-port: 3306
```

We could do something clever like 3306 is considered MySQL protocol by default.  If the user runs MySQL protocol on a different port this annotation would be used.  If the user runs HTTPS we could override that destination with something like:

```
      annotations:
        sidecar.istio.io/https-protocol-port: 443,3306
```

I am not proposing we throw away the current behavior, but it new users are often surprised that the name of the port affects how traffic is allowed to flow.

**Comment by rshriram** [comment] 2019-03-01 03:07
> @rshriram
> if you specify port name as "mysql-xx" we will ignore PERMISSIVE mode
> What the hell? Who thinks this is acceptable?

I think @incfly misspoke based on a stale PR state. I was simply testing the hack for some other thing.. We are not most certainly creating any such hacks in the networking code based on port name prefix.. So rest assured :).

**Comment by rshriram** [comment] 2019-03-01 03:15
well except for using http-, https-, mysql- as the port names to indicate the protocol to use for that port. And the only way to get rid of this prefix requirement is to turn envoy into a wireshark and do some acrobatics at runtime. But then, the more magic you put into the data plane, the more surprises you get. 

Case in point is the trouble caused by TLS sniffing -- allowing a single listener on a port on envoy to receive both TLS and non-TLS traffic, and magically detecting if the client is using mTLS or not. it relies on client sending data first, which breaks for a variety of service-first protocols like mysql.

**Comment by incfly** [comment] 2019-04-04 18:23
Closing this issue given the doc and release qualification test suites are both added. Sorry for all the inconvenience.

**Closed by incfly** 2019-04-04 18:23 UTC
Labels: area/networking, area/user experience

**Comment by dotw** [comment] 2019-05-06 06:50
Hi @incfly , I got connection failure from istio 1.1.4 & 1.1.5 without the default mesh policy, but it works in 1.1.2.

```
# mysql -h 10.1.226.216 -P 33061 -u root -p
Enter password:
ERROR 2026 (HY000): SSL connection error: socket layer receive error
```
This costs me several hours to investigate the cause, and suddenly it works when I rename the port name for mysql-33061 to tcp.
```
# mysql -h 10.0.137.145 -P 33061 -u root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7
Server version: 5.7.26 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
```
Do we have any changes from 1.1.2 on this part?

**Comment by jdomag** [comment] 2020-05-04 15:05
I\m using Istio 1.5.2 and havving same issue - none of solutions described under below docs helped https://istio.io/faq/security/#mysql-with-mtls

Any idea how to solve it or troubleshoot further?

![image](https://user-images.githubusercontent.com/28705876/80980806-622ad900-8e29-11ea-9d9a-b1703ecb654d.png)

**Comment by Ultrafenrir** [comment] 2020-05-27 13:16
version 1.6.0 - same problem, but none of the above tricks did not help

**Comment by ccctask** [comment] 2021-08-10 08:12
version 1.8   same problem

**Comment by jameslombard** [comment] 2022-02-18 13:16
Solved it through applying the following config in the istio-discovery helm-chart:

proxy:
    excludeOutboundPorts: "5432" #port where SQL server is running
This tells the side-car proxy to allow any traffic on the specified port to access the service directly.

**Comment by wyljpn** [comment] 2022-12-05 03:31
I've encountered this issue, version 1.9. 
Fixed it using 
```
apiVersion: v1
kind: Service
metadata:
  name: mysql-test
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      # name: http   # It was http which caused error, because it requires https. To make it work, specify https or no to specify it.
  selector:
    app: mysql-test
```
![image](https://user-images.githubusercontent.com/37242439/205543322-a3fb6f9d-3534-4117-80f3-cc776cb59c81.png)

Istio reads the name of ports. 
If it is http, Istio configs it as http protocol. 
If it is https, Istio configs it as https protocol.
See: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
