### ISSUE TITLE
VirtualService rules change when active namespace is changed

### ISSUE THREAD

**Issue by mabushey** [istio/istio#11606] opened 2019-02-07 23:22 UTC
Istio 1.0.5, k8s 1.11.6

Changing the active namespace changes the namespace in the Virtualservice. Notice the `host:` line change from `httpbin.httpbin.svc.cluster.local` to `httpbin.microservice-stg.svc.cluster.local` 
```
➜  kops  git:(master) ✗ kubectl get virtualservices -o yaml | grep httpbin
        {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"microservice-stg","namespace":"microservice-stg"},"spec":{"gateways":["elb-gateway"],"hosts":["microservice-stg.example.com","microservice-stg.green.example.com","microservice-stg.blue.example.com"],"http":[{"match":[{"uri":{"exact":"/info-xxx"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-xxx.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/xxx"}}],"route":[{"destination":{"host":"microservice-xxx.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"exact":"/info-yyy"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-yyy.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/yyy"}}],"route":[{"destination":{"host":"microservice-yyy.microservice-stg.svc.cluster.local","port":{"number":8080}}}],"timeout":"360s"},{"match":[{"uri":{"exact":"/info-zzz"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-zzz.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/zzz"}}],"route":[{"destination":{"host":"microservice-zzz.microservice-stg.svc.cluster.local","port":{"number":8080}}}],"timeout":"360s"},{"match":[{"uri":{"prefix":"/"}}],"route":[{"destination":{"host":"httpbin.httpbin.svc.cluster.local","port":{"number":8000}}}]}]}}
          host: httpbin.httpbin.svc.cluster.local
➜  kops  git:(master) ✗ kubens default
Context "k8s-blue.example2.com" modified.
Active namespace is "default".
➜  kops  git:(master) ✗
➜  kops  git:(master) ✗ kubectl get virtualservices -o yaml | grep httpbin
        {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"microservice-stg","namespace":"default"},"spec":{"gateways":["elb-gateway"],"hosts":["microservice-stg.example.com","microservice-stg.blue.example.com","microservice-stg.green.example.com"],"http":[{"match":[{"uri":{"exact":"/info-xxx"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-xxx.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/xxx"}}],"route":[{"destination":{"host":"microservice-xxx.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"exact":"/info-yyy"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-yyy.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/yyy"}}],"route":[{"destination":{"host":"microservice-yyy.microservice-stg.svc.cluster.local","port":{"number":8080}}}],"timeout":"360s"},{"match":[{"uri":{"exact":"/info-zzz"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-zzz.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/zzz"}}],"route":[{"destination":{"host":"microservice-zzz.microservice-stg.svc.cluster.local","port":{"number":8080}}}],"timeout":"360s"},{"match":[{"uri":{"prefix":"/"}}],"route":[{"destination":{"host":"httpbin.microservice-stg.svc.cluster.local","port":{"number":8000}}}]}]}}
          host: httpbin.microservice-stg.svc.cluster.local
```

**Comment by mabushey** [comment] 2019-02-07 23:30
Somehow the rules got applied against multiple namespaces (depending on active namespace), which makes no sense as the route file specifies the `microservice-stg` namespace. I moved httpbin from `httpbin.microservice-stg` to `httpbin.httpbin`. The VirtualService stayed in `microservice-stg`.

**Comment by mabushey** [comment] 2019-02-07 23:37
It looks like the same VirtualService can be applied to multiple namespaces, and as they're "global", one will randomly take priority.

**Comment by esnible** [comment] 2019-02-08 17:01
Most of the Istio samples do not specify a namespace.  For example _samples/httpbin/httpbin.yaml_ has no namespace.  It can be applied to whatever namespace you wish using `-n <namespace>`.

This allows users to deploy the service in whichever namespace they want without modifying the .yaml.

**Comment by mabushey** [comment] 2019-02-08 18:11
@esnible I gave up on any of the Istio examples, and highly recommend everyone to do the same. Saying they're a wild goose chance is an understatement. Even the spec pages for Istio are almost always wrong. Love the project, but have never seen more inaccurate docs in my life. Even the httpbin you're mentioning is an out of date fork. I'm using the real one.

My bug report is that if you do not specify a namespace in the VirtualService. you can set up a VirtualService for routing, update the VirtualService, and if you changed the default namespace, you will have both the new and the old routing rules in different namespaces and have no idea which one Istio is going to pick.

There's some other issues with this going on too, I can apply a VirtualService in default and xxxx-stg and they work, but if I apply them in xxxx-prd they do not take effect.

**Comment by esnible** [comment] 2019-02-08 20:48
I am trying to make the samples better.

The httpbin.yaml example is the latest version and can be seen at https://github.com/istio/istio/blob/release-1.1/samples/httpbin/httpbin.yaml

How do you change the namespace of a virtual service?  I tried with `kubectl edit` and `kubectl patch` and always received ```Error from server (BadRequest): the namespace of the object (istio-system) does not match the namespace on the request (default)``` from Kubernetes.

**Comment by mabushey** [comment] 2019-02-08 22:51
@esnible
> I am trying to make the samples better.
That's awesome! You have your work cut out for you! Thank you. :)

I figured out a little more. I have services in `xxxx-stg` and `xxxx-prd`. I tried putting the VirtualServices in each namespace, but only one worked. This was on a fresh setup of K8s 1.11 with kops and Istio 1.0.5. Once I set them to both use a namespace of `default`, both sets of rules worked.

To change the namespace you have to do a `kubectl delete -f virtualservice-stg`, edit the file, then ``kubectl apply -f virtualservice-stg`

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxxx-prd
  namespace: default
```

**Comment by esnible** [comment] 2019-02-09 12:46
@mabushey II reproduced a problem, I am not sure if it is yours because I don't know what you are using for `hosts`.  Are you using two VirtualServices for the *same host*, in two different namespaces?  I don't think it is allowed, because the VirtualService is not bound to the namespace it is created in.

I created two VirtualServices `default` and `ns`, both for ns1-httpbin.ns1.svc.cluster.local:80, in different Namespaces, and Istio created an Envoy configuration with two Routes both with the same name.


```
kubectl create ns ns1
cat <<EOF | kubectl -n ns1 apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - ns1-httpbin
  http:
  - match:
     - uri:
        prefix: /
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
EOF

kubectl create ns ns1
cat <<EOF | kubectl -n default apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - ns1-httpbin.ns1.svc.cluster.local
  http:
  - match:
     - uri:
        prefix: /
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
EOF
```

Then I checked a pod in default (it could be any pod, I used a ratings instance from bookinfo) for the Envoy route configuration.  I found Envoy was misconfigured with two entries for the same route.  (I have the `jq` JSON query language tool installed).

`kubectl exec ratings-v1-65dd9d89dd-ww7jm -c istio-proxy -- curl --silent localhost:15000/config_dump | jq '.configs[]?.dynamic_route_configs[]?.route_config?.virtual_hosts[]?.name' /tmp/config_dump.json  | uniq -c`

The output showed one entry for every Envoy route but two identical route entries:

```
...
   1 "istio-ingressgateway.istio-system.svc.cluster.local:80"
   2 "ns1-httpbin.ns1.svc.cluster.local:80"
   1 "productpage.default.svc.cluster.local:80"
...
```

@andraxylia @rshriram What should Istio do in this situation?

**Comment by rshriram** [comment] 2019-02-11 14:48
if you use shortnames in the hosts, they will be expanded based on the namespace of the virtualService. It is possible that k8s triggers a CRD change update causing Pilot to reevaluate the virtualServices, expanding short names like httpbin to httpbin.Namespace.default.svc.cluster.local ..

**Comment by mabushey** [comment] 2019-02-11 18:30
@esnible - no my host for `stg` is `xxx-stg.example.com`. and `prd` is `xxx-prd.example.com`
Putting them in `xxx-stg` and `xxx-prd` namespaces resulted in one set of rules that worked, and one that did not. Putting them both in `default` results in both rules working.

**Comment by mabushey** [comment] 2019-02-11 18:31
@rshriram I've used both full names and also short names within the namespace, that does not seem to change the behavior.

**Comment by linsun** [comment] 2019-02-15 19:43
@mabushey would it be possible for you to provide some examples?  Virtual Service in 1.0 is global scoped so I would expect only 1 is effective (probably the newer one).  

I am having a bit trouble to understand this ```Putting them both in default results in both rules working.```.   Do you mean you have a virtual service for stage host, and the same named VS for prod host where stage and prod are the 2 services with 2 deployments?

**Comment by linsun** [comment] 2019-02-15 20:11
@mabushey I would like to make sure we have an automated tests for your scenario to demonstrate the expected behavior for this in 1.1 or 1.1.x.

In 1.1, I'm expecting you to use the new export_To support to mark if you want a given VS to be exported.  Further, you can also use the sidecar API to indicate the ingress and egress scope of the sidecar for your service.

**Comment by mabushey** [comment] 2019-02-15 21:36
@linsun 

Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: elb-gateway
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:{act#}:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http-elb
      protocol: HTTP
    hosts:
    - "example.com"
    - "*.example.com"
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https-elb
      protocol: HTTP
    hosts:
    - "example.com"
    - "*.example.com"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector: {}
  ingress:
  - {}

```

Prd:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxx-prd
  namespace: default
spec:
  hosts:
  - "xxx-prd.example.com"
  - "xxx-prd.green.example.com"
  - "xxx-prd.blue.example.com"
  gateways:
  - elb-gateway
  http:
  - match:
...
```
Stg:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxx-stg
  namespace: default
spec:
  hosts:
  - "xxx-stg.example.com"
  - "xxx-stg.green.example.com"
  - "xxx-stg.blue.example.com"
  gateways:
  - elb-gateway
  http:
  - match:
...
```

When they are both in the default namespace they work. When stg is in xxx-stg and prd is in www-prd, Only stg works, which I assume is because it was applied first.

**Comment by linsun** [comment] 2019-02-18 20:32
thank you  @mabushey, i am able to recreate this with the simple httpbin example and 2 VSs in 1 namespace or in 2 namespaces.  The behavior is different as you described.  investigating

**Comment by linsun** [comment] 2019-02-19 18:55
it looks like dynamic route config isn't pushed to the ingress gateway when the VS is applied to the 2nd namespace.

**Comment by linsun** [comment] 2019-03-19 18:41
@mabushey more investigation revealed that you need to refer the gateway with its namespace to get the VS bound to it properly. 

I have tested the following examples in 1.1.rc.5:

https://github.com/linsun/istio-traffic-examples/blob/master/httpbin/vs-ns1.yaml. (ns1 namespace)
https://github.com/linsun/istio-traffic-examples/blob/master/httpbin/vs-default.yaml (default namespace)

The two works the same way, you can deploy either for curl -I -HHost:httpbin2.example.com  {ingress_ip}:{port}/delay/200

cc @rshriram @frankbu

**Comment by linsun** [comment] 2019-03-19 18:44
@rshriram @frankbu should we simply recommend users to specify namespace/ when referring to the gateway from VS?   Anything else we need for this issue?

cc @andraxylia @costinm

**Comment by linsun** [comment] 2019-03-19 18:59
cc @louiscryan do we need to update release note for namespace scoping when referring to gateway?

**Comment by frankbu** [comment] 2019-03-20 15:15
@linsun, the original issue, discussed with @esnible at the top, seems to have morphed into at least 3 separate complaints. I would like to understand all 3 better, so that we can make any needed changes to the docs.

1. the first problem discussed in this issue seems to be a known and documented behavior that the documentation explicitly warns about. If you use short names for VirtualService hosts, they will expand to the fully qualified names according to the VS namespace (not the Service's namespace), so changing the VS namespace will have some pretty nasty side-effects. The recommendation is to always use qualified names. See the `host` field documentation [here](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#VirtualService) for details.

2. Quote from @mabushey `I gave up on any of the Istio examples, and highly recommend everyone to do the same. Saying they're a wild goose chase is an understatement. Even the spec pages for Istio are almost always wrong. Love the project, but have never seen more inaccurate docs in my life.`

   This concerns me a lot. I would like to understand something more specific. Can you point to specific docs that you found were incorrect, or led you on a "wild goose chase"? A blanket statement that all the doc is bad and nobody should use it is not very helpful, to say the least.

3. The final problem seems to be related to cross namespace references between VirtualServices and Gateways. We recognized there was an open-ended set of issues that the global (crossing all namespaces) config scope can cause, so we've made a lot of changes in this area for 1.1. Note that now you can also link Gateways to VirtualServices from the gateway side. Bottom line is that this could use better documentation still. It's not clear to me if there's also some pilot change that could handle this kind of misconfiguration better, improve validation, or otherwise.

**Comment by linsun** [comment] 2019-03-20 18:06
@frankbu thanks, i only focus on the 3rd issue.  The question is if we feel better documentation is sufficient for fixing this, e.g. you should always refer to the gateway with namespace/gateway-name from VS when gateway resource and VS resource aren't in the same namespace.

**Comment by frankbu** [comment] 2019-03-20 20:50
For number 3, I'm wondering if we should also add a warning in the validator if the namespace is not provided. Documentation alone doesn't seem to always be enough, as number 1 is documented already. Maybe we should add a validator warning for number 1 too?

For number 2 I would encourage @mabushey to open one or more istio/istio.io issues with some specific examples of problems with the docs.

**Comment by linsun** [comment] 2019-03-20 22:28
@frankbu for 3, how do you validate if the namespace is not provided because the gateway is in the same namespace (which in the case the `namespace/` is not required) vs in a different namespace which requires the `namespace/`?

**Comment by frankbu** [comment] 2019-03-21 13:45
Recommend always being explicit. Use `./` for same namespace.

**Comment by linsun** [comment] 2019-03-21 13:46
ok fair @frankbu  - then I don't think there is anything we need from this issue.
@mabushey please retry your scenario with `namespace/` when referring to the gateway resource from a VS in a different namespace.

**Comment by linsun** [comment] 2019-04-10 20:12
closing this, as it works fine when configured properly as my example has demonstrated.

**Closed by linsun** 2019-04-10 20:13 UTC
Labels: area/networking
