### ISSUE TITLE
Almost all tests under galley/pkg/config/source/kube/apiserver are flaky (5% error rate)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20072] opened 2020-01-10 16:48 UTC
Given they are all flaky, this heavily suggests a bug in the code to me rather than the test.

These tests are failing 5% of the time. To reproduce, I ran the following:

```
go test -c -race ./galley/pkg/config/source/kube/apiserver
stress -p 64 ./apiserver.test
```

Test failures by test:
```
     16 TestEvents
      4 TestEvents_NoneForDisabled
     33 TestEvents_WatchUpdatesStatusCtl
     49 TestSource_WatcherFailsCreatingInformer
```

cc @sushicw @nmittler not sure who owns this these days, I couldn't grok the code to fix this

**Comment by nmittler** [comment] 2020-01-10 21:05
@howardjohn do you know how long they've been flaky? Was it possibly a recent change or an issue that's been around a while?

**Comment by howardjohn** [comment] 2020-01-10 21:07
I am pretty sure its not a new issue. I had seen the occasional flake before, and there may be some issues opened for individual test cases. The 5% error rate is not from CI, its when running locally with high concurrency so its slightly inflated

**Comment by ayj** [comment] 2020-01-10 22:53
@sushicw, possibly related to the recent async watcher start change?

**Comment by howardjohn** [comment] 2020-01-11 00:08
Actually does look like it recently got worse: https://testgrid.k8s.io/istio_istio_postsubmit#unit-tests_istio_postsubmit&width=20&exclude-non-failed-tests= you can see 4 failures in the last 20 or so commits

**Comment by sushicw** [comment] 2020-01-13 19:48
After experimenting with different commits, I can confirm that 101b3380b (#19890) caused a jump in error rate from around 0.3% to about 10%. I'll put together a revert.

**Comment by sushicw** [comment] 2020-01-14 20:04
The specific failures I'm seeing:

```
/tmp/go-stress-20200114T174135-795508150:--- FAIL: TestEvents_NoneForDisabled (1.00s)
/tmp/go-stress-20200114T174135-795508150-    source_dynamic_test.go:342: 
/tmp/go-stress-20200114T174135-795508150-        Timed out after 1.001s.
```

```
/tmp/go-stress-20200114T174135-813035236:--- FAIL: TestSource_WatcherFailsCreatingInformer (2.15s)
/tmp/go-stress-20200114T174135-813035236-    source_dynamic_test.go:395: retry.UntilSuccessOrFail: timeout while waiting (last error: element [Event](Added: k8s/collection1/ns/i1) not found. Diff:
```
The test retry has a hardcoded 2 second timeout. I can make the error rate go down significantly by increasing that. 

I wondered at first if at least on my system, running the stress test at -p 64 is simply creating enough CPU pressure that we hit the timeout more often. But even increasing the timeout to 60s, I still get 3-5% error rates. There's more going on here. 

Looking deeper at the logs, it looks like we're sometimes sending CRD FullSync before CRD adds. It looks like this happens when we're not blocking on `cache.WaitForCacheSync` as expected. Looking in to why this could be.

**Comment by sushicw** [comment] 2020-01-14 21:08
Worth noting that I'm seeing exactly the same kinds of errors both with and without the timeout change... with the timeout change, there's just more of them. I think there's a race that exists regardless, and the timeout change just makes it hit more often.

My best guess so far as to what the race is: when the informer gets resource events and "sends" them to the calling code, it allows `sharedIndexInformer.HasSynced()` to return true. However, it has no way of knowing if the event has been "received" by the apiserver source, which is what we really want to know. So the wrong ordering of goroutine execution can trigger the race condition. The apiserver can detect if it gets stuff out of order and send a Reset, but our test code doesn't appear to handle Reset events at all, so we end up timing out waiting for it to get into the correct state.

**Comment by sushicw** [comment] 2020-01-15 16:41
Some options I've considered, none of which I'm thrilled about:

1. Abandon `--timeout` (don't attempt to redo #19890). This doesn't fix the underlying race, but does keep it pretty rare. Now that we're doing a permissions pre-check to prevent infinite execution on insufficient permissions, analyze-wide timeout is probably downgraded to just a "nice to have."

2. Keep timeout, but also add a short time.Sleep between `cache.WaitForCacheSync` and sending the `FullSync` event. This is a gross hack, but experimentally a 10ms sleep here does seem to keep the error rate down to the same levels as not having `--timeout` at all. It still doesn't really solve the race, just keeps it "acceptably" (?) rare.  

3. Update the tests to properly handle the Reset event somehow, so we can automatically redrive whenever we get CRD events out of order. This is how the prod galley code solves the race. This will probably involve fairly significant refactoring effort to get right and risks adding a lot of complexity to test code. 

4. Acknowledge that these tests are inherently flaky and paper over it by sticking a dumb retry loop in front of each of them. (This is a less-fancy version of option 3). 

Option 1 is the de-facto default and where I'm currently leaning. @howardjohn any thoughts?

**Comment by howardjohn** [comment] 2020-01-15 16:45
1 seems reasonable if we have avoided the "normal" case of infinite
execution. Other tools like kubectl don't have --timeout on
potentially long operations, so it seems fine

**Comment by sushicw** [comment] 2020-01-15 17:09
Created https://github.com/istio/istio/issues/20209 to track the rare test flake. Closing this since the revert successfully fixed the immediate P0 issue.

**Closed by sushicw** 2020-01-15 17:09 UTC
Labels: area/config, kind/test failure
