### ISSUE TITLE
Istio returns patch error when upgrading from 0.8.0 to 1.0.0

### ISSUE THREAD

**Issue by sdake** [istio/istio#7072] opened 2018-07-13 00:30 UTC
**Describe the bug**
Upgrading from 0.8.0 to istio-release-1.0-20180711-09-15 fails.

**Expected behavior**
Upgrade should not fail.

|**Is Istio Auth enabled or not?**
istio-demo.yaml

**Environment**
Bare metal Kubernetes 1.10 with metallb.

**Steps to reproduce**

```
curl -L https://github.com/istio/istio/releases/download/0.8.0/istio-0.8.0-linux.tar.gz -o istio-0.8.0.tar.gz
tar -xzvf istio-0.8.0.tar.gz
(download manually istio-release-1.0-20180711-09-15)
kubectl apply -f istio-0.8.0/install/kubernetes/istio-demo.yaml
kubectl apply -f istio-release-1.0-20180711-09-15/install/kubernetes/istio-demo.yaml
```

**Results**

```
namespace "istio-system" configured
configmap "istio-grafana-custom-resources" created
configmap "istio-statsd-prom-bridge" configured
configmap "istio-mixer-custom-resources" configured
configmap "prometheus" configured
configmap "istio-security-custom-resources" created
configmap "istio" configured
configmap "istio-sidecar-injector" configured
serviceaccount "istio-galley-service-account" created
serviceaccount "istio-egressgateway-service-account" configured
serviceaccount "istio-ingressgateway-service-account" configured
serviceaccount "istio-grafana-post-install-account" created
clusterrole.rbac.authorization.k8s.io "istio-grafana-post-install-istio-system" created
clusterrolebinding.rbac.authorization.k8s.io "istio-grafana-post-install-role-binding-istio-system" created
job.batch "istio-grafana-post-install" created
serviceaccount "istio-mixer-post-install-account" configured
clusterrole.rbac.authorization.k8s.io "istio-mixer-post-install-istio-system" configured
clusterrolebinding.rbac.authorization.k8s.io "istio-mixer-post-install-role-binding-istio-system" configured
serviceaccount "istio-mixer-service-account" configured
serviceaccount "istio-pilot-service-account" configured
serviceaccount "prometheus" unchanged
serviceaccount "istio-cleanup-secrets-service-account" created
clusterrole.rbac.authorization.k8s.io "istio-cleanup-secrets-istio-system" created
clusterrolebinding.rbac.authorization.k8s.io "istio-cleanup-secrets-istio-system" created
job.batch "istio-cleanup-secrets" created
serviceaccount "istio-citadel-service-account" configured
serviceaccount "istio-sidecar-injector-service-account" configured
customresourcedefinition.apiextensions.k8s.io "rules.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "attributemanifests.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "bypasses.config.istio.io" created
customresourcedefinition.apiextensions.k8s.io "circonuses.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "deniers.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "fluentds.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "kubernetesenvs.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "listcheckers.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "memquotas.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "noops.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "opas.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "prometheuses.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "rbacs.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "servicecontrols.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "signalfxs.config.istio.io" created
customresourcedefinition.apiextensions.k8s.io "solarwindses.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "stackdrivers.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "statsds.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "stdios.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "apikeys.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "authorizations.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "checknothings.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "kuberneteses.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "listentries.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "logentries.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "edges.config.istio.io" created
customresourcedefinition.apiextensions.k8s.io "metrics.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "quotas.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "reportnothings.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "servicecontrolreports.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "tracespans.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "serviceroles.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "servicerolebindings.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "adapters.config.istio.io" created
customresourcedefinition.apiextensions.k8s.io "instances.config.istio.io" created
customresourcedefinition.apiextensions.k8s.io "templates.config.istio.io" created
customresourcedefinition.apiextensions.k8s.io "handlers.config.istio.io" created
customresourcedefinition.apiextensions.k8s.io "destinationpolicies.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "egressrules.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "routerules.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "virtualservices.networking.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "destinationrules.networking.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "serviceentries.networking.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "gateways.networking.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "policies.authentication.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "meshpolicies.authentication.istio.io" created
customresourcedefinition.apiextensions.k8s.io "httpapispecbindings.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "httpapispecs.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "quotaspecbindings.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "quotaspecs.config.istio.io" configured
customresourcedefinition.apiextensions.k8s.io "envoyfilters.networking.istio.io" created
clusterrole.rbac.authorization.k8s.io "istio-galley-istio-system" created
clusterrole.rbac.authorization.k8s.io "istio-egressgateway-istio-system" created
clusterrole.rbac.authorization.k8s.io "istio-ingressgateway-istio-system" created
clusterrole.rbac.authorization.k8s.io "istio-mixer-istio-system" configured
clusterrole.rbac.authorization.k8s.io "istio-pilot-istio-system" configured
clusterrole.rbac.authorization.k8s.io "prometheus-istio-system" configured
clusterrole.rbac.authorization.k8s.io "istio-citadel-istio-system" configured
clusterrole.rbac.authorization.k8s.io "istio-sidecar-injector-istio-system" configured
clusterrolebinding.rbac.authorization.k8s.io "istio-galley-admin-role-binding-istio-system" created
clusterrolebinding.rbac.authorization.k8s.io "istio-egressgateway-istio-system" created
clusterrolebinding.rbac.authorization.k8s.io "istio-ingressgateway-istio-system" created
clusterrolebinding.rbac.authorization.k8s.io "istio-mixer-admin-role-binding-istio-system" configured
clusterrolebinding.rbac.authorization.k8s.io "istio-pilot-istio-system" configured
clusterrolebinding.rbac.authorization.k8s.io "prometheus-istio-system" configured
clusterrolebinding.rbac.authorization.k8s.io "istio-citadel-istio-system" configured
clusterrolebinding.rbac.authorization.k8s.io "istio-sidecar-injector-admin-role-binding-istio-system" configured
service "istio-galley" created
service "istio-egressgateway" configured
service "istio-ingressgateway" configured
service "grafana" configured
service "istio-policy" configured
service "istio-telemetry" configured
service "istio-statsd-prom-bridge" configured
deployment.extensions "istio-statsd-prom-bridge" configured
service "istio-pilot" configured
service "prometheus" unchanged
service "istio-citadel" unchanged
service "servicegraph" unchanged
service "istio-sidecar-injector" unchanged
deployment.extensions "istio-galley" created
deployment.extensions "istio-egressgateway" configured
deployment.extensions "istio-ingressgateway" configured
deployment.extensions "grafana" configured
deployment.extensions "istio-policy" configured
deployment.extensions "istio-telemetry" configured
deployment.extensions "istio-pilot" configured
deployment.extensions "prometheus" configured
deployment.extensions "istio-citadel" configured
deployment.extensions "servicegraph" configured
deployment.extensions "istio-sidecar-injector" configured
deployment.extensions "istio-tracing" configured
horizontalpodautoscaler.autoscaling "istio-egressgateway" configured
horizontalpodautoscaler.autoscaling "istio-ingressgateway" configured
service "zipkin" unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io "istio-sidecar-injector" configured
validatingwebhookconfiguration.admissionregistration.k8s.io "istio-galley" created
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"helm.sh/hook-delete-policy":"hook-succeeded","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"batch/v1\",\"kind\":\"Job\",\"metadata\":{\"annotations\":{\"helm.sh/hook\":\"post-install\",\"helm.sh/hook-delete-policy\":\"hook-succeeded\"},\"labels\":{\"app\":\"mixer\",\"chart\":\"mixer-1.0.0\",\"heritage\":\"Tiller\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-mixer-post-install\",\"namespace\":\"istio-system\"},\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"app\":\"mixer\",\"release\":\"RELEASE-NAME\"},\"name\":\"istio-mixer-post-install\"},\"spec\":{\"containers\":[{\"command\":[\"/bin/bash\",\"/tmp/mixer/run.sh\",\"/tmp/mixer/custom-resources.yaml\"],\"image\":\"quay.io/coreos/hyperkube:v1.7.6_coreos.0\",\"name\":\"hyperkube\",\"volumeMounts\":[{\"mountPath\":\"/tmp/mixer\",\"name\":\"tmp-configmap-mixer\"}]}],\"restartPolicy\":\"OnFailure\",\"serviceAccountName\":\"istio-mixer-post-install-account\",\"volumes\":[{\"configMap\":{\"name\":\"istio-mixer-custom-resources\"},\"name\":\"tmp-configmap-mixer\"}]}}}}\n"},"labels":{"chart":"mixer-1.0.0"}},"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"hyperkube"}],"containers":[{"command":["/bin/bash","/tmp/mixer/run.sh","/tmp/mixer/custom-resources.yaml"],"name":"hyperkube"}],"restartPolicy":"OnFailure"}}}}
to:
&{0xc420d5e540 0xc420171c00 istio-system istio-mixer-post-install istio-demo.yaml 0xc420bda370 1219 false}
for: "istio-demo.yaml": Job.batch "istio-mixer-post-install" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"istio-mixer-post-install", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"release":"RELEASE-NAME", "app":"mixer", "controller-uid":"b17c8df4-8630-11e8-ae6a-eeeeeeeeeeee", "job-name":"istio-mixer-post-install"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"tmp-configmap-mixer", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc435b17dc0), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"hyperkube", Image:"quay.io/coreos/hyperkube:v1.7.6_coreos.0", Command:[]string{"/bin/bash", "/tmp/mixer/run.sh", "/tmp/mixer/custom-resources.yaml"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"tmp-configmap-mixer", ReadOnly:false, MountPath:"/tmp/mixer", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc4320df830), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"istio-mixer-post-install-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc42eea8dc0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil)}}: field is immutable
Error from server (Invalid): Service "tracing" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

**Comment by sdake** [comment] 2018-07-13 01:37
For error:
```
Error from server (Invalid): Service "tracing" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```
Reference Kubernetes issue: https://github.com/kubernetes/kubectl/issues/221

**Comment by sdake** [comment] 2018-07-13 01:51
`helm upgrade` also fails:

```
sdake@falkor-07:~/istio-release-1.0-20180711-09-15$ helm upgrade istio install/kubernetes/helm/istio
Error: UPGRADE FAILED: ClusterRoleBinding.rbac.authorization.k8s.io "istio-ingress-istio-system" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"istio-ingress-istio-system"}: cannot change roleRef
```

**Comment by sdake** [comment] 2018-07-13 01:55
Looks like `helm upgrade` being worked here: https://github.com/istio/istio/issues/7023

**Comment by ayj** [comment] 2018-07-13 16:52
#7023 address the ingress/pilot upgrade problem. This issue is caused by a change to the mixer post-install job changing. See https://github.com/istio/istio/pull/7087

**Comment by sdake** [comment] 2018-07-13 17:03
@ayj I think there is still the tracing issue left, which i'm not clear on how to fix - so leaving this issue open.

**Comment by costinm** [comment] 2018-07-14 00:53
I was able to run upgrades after the rollback for the rolebinding.
Re nodeport: we should not ship with node port for services, except maybe a 'nodeport' gateway.
Apps should be exposed using Gateway - with TCP ports or hostnames. We also need to get rid of all ingresses in helm, and make sure in review people don't add more nodeport or ingress.

**Comment by sdake** [comment] 2018-07-16 14:17
@costinm were you able to run `helm upgrade` or istio apply -f istio-demo.yaml?  It is this second case that presents the nodeport/clusterid errors.

**Comment by vilobhmm** [comment] 2018-07-19 20:06
Running into

Normal   Pulling                3m (x3 over 4m)  kubelet, gke-istio-demo-default-pool-7a204284-cbzd  pulling image "gcr.io/istio-release/proxy:release-1.0-latest-daily"

@costinm @sdake : Looks like either the image or the image tag is wrong.

**Comment by vilobhmm** [comment] 2018-07-19 22:33
Looks like there is no such image as gcr.io/istio-release/proxy:release-1.0-latest-daily
It should be  gcr.io/istio-release/proxyv2:release-1.0-latest-daily 

$ gcloud docker -- pull gcr.io/istio-release/proxy:release-1.0-latest-daily
Error response from daemon: manifest for gcr.io/istio-release/proxy:release-1.0-latest-daily not found

$ gcloud docker -- pull gcr.io/istio-release/proxyv2:release-1.0-latest-daily
Status: Downloaded newer image for gcr.io/istio-release/proxyv2:release-1.0-latest-daily

**Comment by sdake** [comment] 2018-07-26 08:06
@hklai any thoughts on https://github.com/istio/istio/issues/7072#issuecomment-406434701.  I assume this was during an upgrade scenario.

**Comment by hklai** [comment] 2018-07-26 09:12
I think @vilobhmm 's problem had been addressed in the later daily releases.

**Comment by costinm** [comment] 2018-08-06 19:25
Seems to be addressed.

**Closed by costinm** 2018-08-06 19:25 UTC
Labels: area/environments
