### ISSUE TITLE
Tracing bookinfo sample doesn't work with fresh istio 1.1.1 install on GKE

### ISSUE THREAD

**Issue by edude03** [istio/istio#13171] opened 2019-04-09 11:16 UTC
**Describe the bug**
Traces from the bookinfo example (or other services) don't show up in the Jaeger tracing GUI. 
Traces from the istio-ingress however do show up, but no other spans. (see image). This works when we deploy istio 1.0.6  to the same environment. 

**Expected behavior**
We expect spans to show as per the example. 

**Steps to reproduce the bug**
- We created a new kubernetes 1.12 cluster on GKE with Network Policy Enabled
- We install istio with the settings listed below using `helm template`
- We installed the bookinfo sample + bookinfo ingress. 
- We curled the endpoint multiple times as per the sample curl request.

**Version**
```
istioctl version --remote
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
```

**Installation**
- Downloaded the istio 1.1.1 release 
 - Installed istio_cni, ran istio-init, and installed istio using `helm template` + the following values file

```
tracing:
  enabled: true
kiali:
  enabled: true
istio_cni:
  enabled: true
pilot:
  traceSampling: "100"
global:
  proxy:
    accessLogFile: /dev/stdout
```

(note, the accessLogFile setting doesn't work, see #13051)

**Environment**
Google GKE v1.12.6-gke.7 + Container Optimized OS

**Cluster state**

![image](https://user-images.githubusercontent.com/494483/55796116-c599e880-5afb-11e9-8572-464199b1c354.png)
[istio-dump.tar.gz](https://github.com/istio/istio/files/3058597/istio-dump.tar.gz)

**Comment by douglas-reid** [comment] 2019-04-15 18:35
Have you tried without CNI?  I verified tracing working without CNI in several test clusters in the run up to 1.1.X. Perhaps there is something broken with the CNI-related setup?

**Comment by edude03** [comment] 2019-04-16 05:18
@douglas-reid I have not, no. Realistically that's most likely the issue since that was the only change to our setup (other than upgrading to 1.1.1 of course) 

That said, if CNI is breaking it, it still needs a proper fix as PSP is needed in our environment so we can't roll out to production until we can use CNI for now.

**Comment by dingxiangfei2009** [comment] 2019-04-16 08:37
@douglas-reid I ran two separate tests in two freshly created GKE clusters (Kubernetes 1.12.10) having Istio 1.1.1 installed. One cluster has CNI enabled and another has it disabled. Both clusters had the `bookinfo` sample installed in the `default` namespace with `istio-injection=enabled`.

The Jaeger on the cluster with CNI could only see `istio-ingressgateway` traces, while the Jaeger on the other could see all the services.

**Comment by douglas-reid** [comment] 2019-04-16 14:16
/cc @howardjohn who has done some testing with CNI on GKE.

Is it possible that something is incorrect with your CNI install?  I know that the one time I tried, I was using outdated instructions and nothing was working (no traffic was going through the proxies).

**Comment by douglas-reid** [comment] 2019-04-16 14:19
@edude03 @dingxiangfei2009 can you confirm that you don't have the issue discussed here: https://github.com/istio/istio/issues/11638#issuecomment-482188415 ?

**Comment by howardjohn** [comment] 2019-04-16 14:48
Just tested. With CNI I had access logs. I suspect tracing issue is same as access log. Can you run:

```
kubectl get daemonset -n istio-system
kubectl describe pod PRODUCTPAGEPOD # or some other pod you expect logging from
```

**Comment by dingxiangfei2009** [comment] 2019-04-17 05:05
The CNI `daemonset` is running.

`kubectl get daemonset -n istio-system` produces the following.
```
NAME             DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
istio-cni-node   7         7         7         7            7           beta.kubernetes.io/os=linux   33m
```

`kubectl describe pod -l app=productpage` produces the following.
```
Name:               productpage-v1-6597cb5df9-jzqdb
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               gke-istio-cni-test-pool-1-ed6560b8-8gj2/10.148.0.49
Start Time:         Wed, 17 Apr 2019 12:39:54 +0800
Labels:             app=productpage
                    pod-template-hash=6597cb5df9
                    version=v1
Annotations:        cni.projectcalico.org/podIP=10.12.4.4/32
                    kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container productpage
                    sidecar.istio.io/status={"version":"10a671b31a5e531c88e94f9f741b8f10a409c838b3dcd9302b7514862e4a7b4c","initContainers":null,"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imageP...
Status:             Running
IP:                 10.12.4.4
Controlled By:      ReplicaSet/productpage-v1-6597cb5df9
Containers:
  productpage:
    Container ID:   docker://2f9becdd4a05a37576bb8c0601073e0be606b5c4f5343259bd15f0ad0ca59e43
    Image:          istio/examples-bookinfo-productpage-v1:1.10.1
    Image ID:       docker-pullable://istio/examples-bookinfo-productpage-v1@sha256:a427e10277a814b27c066d9ea5f2605b656fc1948714ed09e55c97342c5a721d
    Port:           9080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 17 Apr 2019 12:40:35 +0800
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9gqj8 (ro)
  istio-proxy:
    Container ID:  docker://c867221bd163f678b3d44d997b730c399626fc4c8cd8a94dd4007c0e9a3aa673
    Image:         docker.io/istio/proxyv2:1.1.1
    Image ID:      docker-pullable://istio/proxyv2@sha256:ca41c2c715db0bf2369f892451008a631de6af519ad0bebf3e657bcbb5afb9df
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      productpage.$(POD_NAMESPACE)
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15010
      --zipkinAddress
      zipkin.istio-system:9411
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      NONE
      --statusPort
      15020
      --applicationPorts
      9080
    State:          Running
      Started:      Wed, 17 Apr 2019 12:40:48 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                      productpage-v1-6597cb5df9-jzqdb (v1:metadata.name)
      POD_NAMESPACE:                 default (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      ISTIO_META_POD_NAME:           productpage-v1-6597cb5df9-jzqdb (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:   default (v1:metadata.namespace)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_ANNOTATIONS:    {"kubernetes.io/limit-ranger":"LimitRanger plugin set: cpu request for container productpage"}

      ISTIO_METAJSON_LABELS:  {"app":"productpage","pod-template-hash":"6597cb5df9","version":"v1"}

    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9gqj8 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-9gqj8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9gqj8
    Optional:    false
  istio-envoy:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  Memory
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.default
    Optional:    true
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age   From                                              Message
  ----     ------     ----  ----                                              -------
  Normal   Scheduled  6m    default-scheduler                                 Successfully assigned default/productpage-v1-6597cb5df9-jzqdb to gke-istio-cni-test-pool-1-ed6560b8-8gj2
  Normal   Pulling    6m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  pulling image "istio/examples-bookinfo-productpage-v1:1.10.1"
  Normal   Pulled     5m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  Successfully pulled image "istio/examples-bookinfo-productpage-v1:1.10.1"
  Normal   Created    5m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  Created container
  Normal   Started    5m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  Started container
  Normal   Pulling    5m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  pulling image "docker.io/istio/proxyv2:1.1.1"
  Normal   Pulled     5m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  Successfully pulled image "docker.io/istio/proxyv2:1.1.1"
  Normal   Created    5m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  Created container
  Normal   Started    5m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  Started container
  Warning  Unhealthy  5m    kubelet, gke-istio-cni-test-pool-1-ed6560b8-8gj2  Readiness probe failed: HTTP probe failed with statuscode: 503
```

Also, `kubectl describe pod <one-of-istio-cni-node> -n istio-system` produces this.
```
Name:               istio-cni-node-7jh6t
Namespace:          istio-system
Priority:           0
PriorityClassName:  <none>
Node:               gke-istio-cni-test-default-pool-a51996af-z5sd/10.148.0.46
Start Time:         Wed, 17 Apr 2019 12:19:59 +0800
Labels:             controller-revision-hash=5f98c8dc59
                    k8s-app=istio-cni-node
                    pod-template-generation=1
Annotations:        scheduler.alpha.kubernetes.io/critical-pod=
Status:             Running
IP:                 10.148.0.46
Controlled By:      DaemonSet/istio-cni-node
Containers:
  install-cni:
    Container ID:  docker://a2aec57e75f04730704b26584a1c071bd8548cb21451d94de5c425f69aff2a4c
    Image:         gcr.io/istio-release/install-cni:master-latest-daily
    Image ID:      docker-pullable://gcr.io/istio-release/install-cni@sha256:f61f6cbef226fd0ca45f3784b70cbdea09061e190563b1eec0b2b74e09317ee3
    Port:          <none>
    Host Port:     <none>
    Command:
      /install-cni.sh
    State:          Running
      Started:      Wed, 17 Apr 2019 12:20:01 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      CNI_NETWORK_CONFIG:  <set to the key 'cni_network_config' of config map 'istio-cni-config'>  Optional: false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-cni-token-cv2k7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /home/kubernetes/bin
    HostPathType:  
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  istio-cni-token-cv2k7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-cni-token-cv2k7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     :NoSchedule
                 :NoExecute
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type    Reason     Age   From                                                    Message
  ----    ------     ----  ----                                                    -------
  Normal  Scheduled  43m   default-scheduler                                       Successfully assigned istio-system/istio-cni-node-7jh6t to gke-istio-cni-test-default-pool-a51996af-z5sd
  Normal  Pulling    43m   kubelet, gke-istio-cni-test-default-pool-a51996af-z5sd  pulling image "gcr.io/istio-release/install-cni:master-latest-daily"
  Normal  Pulled     43m   kubelet, gke-istio-cni-test-default-pool-a51996af-z5sd  Successfully pulled image "gcr.io/istio-release/install-cni:master-latest-daily"
  Normal  Created    43m   kubelet, gke-istio-cni-test-default-pool-a51996af-z5sd  Created container
  Normal  Started    43m   kubelet, gke-istio-cni-test-default-pool-a51996af-z5sd  Started container
```

**Comment by dingxiangfei2009** [comment] 2019-04-17 05:30
@howardjohn How did you set up the GKE test cluster? Are the tests running on a freshly created cluster?

My installation instruction is described in #13051, which is mostly taken from https://istio.io/docs/setup/kubernetes/additional-setup/cni/ and https://preliminary.istio.io/docs/setup/kubernetes/install/helm/, with `helm template` exclusively. I am not installing the Istio provided by Google.

**Comment by howardjohn** [comment] 2019-04-17 15:02
Ok so the problem isn't tracing or logging, this is a CNI is not creating iptables issue. Thanks for the debugging. When you set up your GKE cluster did you enable network policy? This looks like a little checkmark in the advanced settings that says "Enable network policy" if you use the UI. This is required for CNI.

The other thing for GKE is you need to set `--set cniBinDir=/home/kubernetes/bin`, but I think you would see explicit errors from the CNI node if you didn't so probably not the issue. (see https://istio.io/docs/setup/kubernetes/additional-setup/cni/#gke-setup)

**Comment by dingxiangfei2009** [comment] 2019-04-17 17:00
@howardjohn Yes, network policy is enabled according to `gcloud container clusters describe`:
```
networkPolicy:
  enabled: true
  provider: CALICO
```

Also, I have `--set cniBinDir=/home/kubernetes/bin` in `helm template`. Logs from the pods in the `istio-cni-node` `DaemonSet` can confirm that this setting is in effect.
```
Removing existing binaries
Wrote Istio CNI binaries to /host/opt/cni/bin
/host/secondary-bin-dir is non-writeable, skipping
Using CNI config template from CNI_NETWORK_CONFIG environment variable.
CNI config: {
  "type": "istio-cni",
  "log_level": "debug",
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig",
      "cni_bin_dir": "/home/kubernetes/bin",
      "exclude_namespaces": [ "istio-system" ]
  }
}
Created CNI config 10-calico.conflist
Done configuring CNI.  Sleep=true
```
I have `ssh`ed into the instances, and in each of the instances `istio-cni` has been placed in `/home/kubernetes/bin` folder.

**Comment by dingxiangfei2009** [comment] 2019-04-21 14:43
According to https://github.com/containernetworking/cni/blob/ec5ec68fa4979e8f98c13845dbc2352380ad179b/libcni/conf.go#L70, `cni` cannot find the `name` field in `10-calico.conflist`, but it is there.

@edude03 should we create a separate issue for this?

**Comment by howardjohn** [comment] 2019-04-21 15:38
@tiswanso @john-a-joyce can you guys provide any insight here?

**Comment by howardjohn** [comment] 2019-04-21 15:38
And thanks for all the debugging so far, very thorough and useful

**Comment by john-a-joyce** [comment] 2019-04-22 18:45
Tim or I can take a detailed look at the debugging you have above.   FWIW a few quick notes. There is a prow job that runs with CNI enabled on every PR.   You can look at prow/e2e-simpleTests-cni.sh.   In theory that should ensure Istio, Istio CNI and GKE (prow) stay aligned.  Additionally, I have a PR in flight that should allow an easy way to run the bookinfo e2e test on GKE.  It is https://github.com/istio/istio/pull/12529.   This would allow you a quick way to repeat test scenarios.   On caveat I have tested it in numerous scenarios but I have not specifically tested it on GKE with the bookinfo tests.

**Comment by tiswanso** [comment] 2019-04-22 18:55
Please share the contents of `10-calico.conflist` on the GKE node/s with the error.

**Comment by edude03** [comment] 2019-04-23 09:30
```
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "mtu": 1460,
      "log_level": "warning",
      "datastore_type": "kubernetes",
      "nodename": "gke-istio-cni-test-pool-1-ed6560b8-5qf6",
      "ipam": {
        "type": "host-local",
        "subnet": "usePodCidr"
      },
      "policy": {
        "type": "k8s",
        "k8s_auth_token": "<redacted>"
      },
      "kubernetes": {
        "k8s_api_root": "https://10.78.0.1:443",
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "snat": true
    }
  ]
}
```

**Comment by tiswanso** [comment] 2019-04-23 13:36
@edude03 --thanks for the update.  It looks like the istio-cni `plugins` config portion either didn't get applied OR it got removed/clobbered by calico.  This condition should be detected by the install-cni daemon on that node and the config reapplied--here's the check:  https://github.com/istio/cni/blob/master/deployments/kubernetes/install/scripts/install-cni.sh#L64-L73

Is the kubectl log output you shared above for the same node as the effected one/s (where the `10-calico.conflist` file has no `istio-cni` entry in the `plugins` list)?  If not, please include that output.

**Comment by tiswanso** [comment] 2019-04-23 16:14
Ok, playing around on GKE with istio-cni, it looks like the fixes for detecting removal of the istio-cni CNI config from the `plugins` list aren't working correctly on GKE: https://github.com/istio/cni/issues/82 and/or https://github.com/istio/cni/pull/86

If I manually remove the istio-cni `plugins` list entry from a node's CNI config, the install-cni pod doesn't detect it and exit (restart) and reapply.  I will try to figure out why that is BUT

**workaround is to manually restart the istio-cni pod for the node**, ie. `kubectl delete pod -n istio-system istio-cni-node-v28rd`.

@edude03 potentially the nodes got into this state due to something like
- node restart after istio-cni and calico daemonsets are installed, ie. enabling network-policy on GKE after istio-cni is already installed.
- adding nodes after istio-cni and calico daemonsets are installed

**Comment by tiswanso** [comment] 2019-04-23 19:06
Root-cause:  the `gcr.io/istio-release/install-cni:master-latest-daily` images are built with an older version of istio-cni.  Need to update the `istio.deps` SHA to pick up new stable version

**Comment by howardjohn** [comment] 2019-04-23 19:08
Would this be fixed by merging **https://github.com/istio/istio/pull/13549**

**Comment by tiswanso** [comment] 2019-04-23 19:45
@howardjohn -- Yes... I didn't see that and posted a different PR.  I'll close mine if that's going to be the way to go for this.

**Comment by howardjohn** [comment] 2019-04-23 19:56
Those prs haven't been merged in a long time, need to bug owners

**Closed** 2019-04-30 20:33 UTC
Labels: area/networking
