### ISSUE TITLE
Use Jmeter to test the istio performance: the istio with mixer test result is better than the istio without mixer

### ISSUE THREAD

**Issue by zxDiscovery** [istio/istio#8590] opened 2018-09-10 10:44 UTC
**Describe the bug**
I use the jmeter to test the istio performance, the result of istio with mixer is better than istio without mixer. 

**Expected behavior**
Because the mixer needs to deal with data, so the istio without mixer performance test result should be better than the istio with mixer.

**Steps to reproduce the bug**
environment:  ubuntu 16.04,  IBMPrivateCloud, jmeter 4.0, istio-1.0.3 (From https://github.com/IBM/charts/blob/master/repo/stable/ibm-istio-1.0.3.tgz , but this chart is using Istio 1.0 image)

Install the istio without mixer

```
helm install ./ibm-istio-1.0.3.tgz -f values.yaml --name istio --namespace istio-system --tls
```
The file `values.yaml` enable all add-on deployment except `mixer`, the change set as follows:
```
--set global.proxy.envoyStatsd.enabled=false
--set mixer.enabled=false
```
Get ibm-istio-1.0.3.tgz at here https://github.com/IBM/charts/blob/master/repo/stable/ibm-istio-1.0.3.tgz

Deploy the bookinfo follow the step https://istio.io/docs/examples/bookinfo/. Because we have 100 nodes on IBMPrivateCloud, so set 100 to `replicas` in bookinfo.yaml.

Use jmeter start test:
```
jmeter -n -t bookinfo.jmx -JHOST=$host -JPORT=31380 -j jMeter-log -l jMeter-results -e -o resultReport -JTHREAD=100 -JDURATION=300 -JRAMP=300
```
The file `bookinfo.jmx` 
[bookinfo.jmx.zip](https://github.com/istio/istio/files/2366192/bookinfo.jmx.zip)

After the steps above, we can get the jmeter test report about the istio without mixer. Then we test the istio with mixer. The result as follows:
Istio without mixer
<img width="1159" alt="2018-09-10 6 38 45" src="https://user-images.githubusercontent.com/40016978/45292799-ddd76400-b528-11e8-8527-7d3cbae2875b.png">

Istio with mixer
<img width="1162" alt="2018-09-10 6 40 11" src="https://user-images.githubusercontent.com/40016978/45292829-fb0c3280-b528-11e8-892c-4c7c9a8095f6.png">

We can see the istio with mixer test result is better than istio without mixer.

**Version**
istio 1.0.3

**Is Istio Auth enabled or not?**
No

**Environment**
ubuntu 16.04,  IBMPrivateCloud, jmeter 4.0, istio-1.0.3

**Cluster state**
All nodes state are normal

**Comment by gyliu513** [comment] 2018-09-11 06:53
@linsun @costinm @sdake comments for this? Does setting following parameter to disable mixer is good enough in a performance test environment?

```
--set global.proxy.envoyStatsd.enabled=false
--set mixer.enabled=false
```

Regarding to the test https://ibmcloud-perf.istio.io/regpatrol/release-1.0-20180907-09-15/ , any detailed steps for how to disable mixer for such case?

![image](https://user-images.githubusercontent.com/4461983/45343062-61995b00-b5d2-11e8-8983-3c4e0babed17.png)

**Comment by sdake** [comment] 2018-09-15 20:46
Not sure where you are getting istio-1.0.3 from - that hasn't been released yet.

@gyliu513 on bare metal the best performance I can wring out is with these flags with 1.0.2:
```
 --set mixer.enabled=false
–-set prometheus.enabled=false 
–-set global.proxy.envoyStatsd.enabled=false
--set global.proxy.accessLogFile=””
```

Prometheus is enabled in the defaults for values.yaml and is unnecessary if you plan to run without telemetry.  I find increasing the replicaCount of the ingressgateway (to something like 10) valuable.  In this mode, I can run a 32 core 40gig network bare metal system at 88% utilization.  My test cases run 10 copies of fortio's echo server and I run fortio with 512 threads from another beefy bare metal machine on the same network.  My typical clusters are AIO, no idea how multiple nodes impact performance.

Performance is a tricky thing.  Lots of things can have an impact - memory bandwidth, cpu context switches, network bandwidth, how much contention there is in the kernel wait queues, etc.

Since your running on virt (?), someone may have turned on memory overcommit, or increased the ratio if you have noticed performance regressions in the same version of the software, or reduced your available memory, or reduced the speed at which your CPUs run, or changed any of hundreds of possible variables :).  Its really hard to define performance on virtual machines when the underlying infrastructure can change without clear notification to the users.  I'd recommend running perf regressions on bare metal to prevent these variables.

Cheers
-steve

**Comment by gyliu513** [comment] 2018-09-16 00:41
Thanks @sdake , we'll disable prometheus and re-run the test. Yes, we are running on VM, but both test `wit mixer` and `without mixer` are test on same machine, so I assume that even if there are resource overcommit, we should still have better performance when running `without mixer`.

https://user-images.githubusercontent.com/4461983/45343062-61995b00-b5d2-11e8-8983-3c4e0babed17.png

Does anyone know how Isito run the test of `Istio No Mixer`?

**Comment by linsun** [comment] 2018-09-18 15:53
` --set mixer.enabled=false ` is the right flag.  See https://istio.io/docs/setup/kubernetes/minimal-install/.  You should be able to validate by listing of the components in istio-system ns too.

Is it possible this is caused by the fact you run with mixer first?

**Comment by gyliu513** [comment] 2018-09-19 14:48
> Is it possible this is caused by the fact you run with mixer first?

@linsun what do you mean of `run with mixer first?`?

**Comment by jnativio** [comment] 2018-09-27 13:55
@gyliu513  Regarding your question about how the mixer is disabled in the regression patrol, these two lines  in the deployment file are commented out:
     mixerCheckServer: istio-policy.istio-system.svc.cluster.local:9091
     mixerReportServer: istio-telemetry.istio-system.svc.cluster.local:9091

The deployment file used is based on the istio-demo.yaml that comes with each build. The performance numbers obtained with no mixer configuration are consistently better than the one with mixer ( around double of max. throughput for latest builds).
One thing I noticed from the jmeter results posted above is that the error rate for no mixer case is much higher. Depending on the nature of the error, it can wrongly increase the throughput (error response comes back quickly).
Also, the response times are huge for this test. What is the network latency between the load generator and the ICP cluster.  If there is a large network latency, the latency added by mixer becomes irrelevant.

**Comment by gyliu513** [comment] 2018-09-27 14:00
Thanks @jnativio , we will check the environment when the cluster is back ;-)

**Comment by gyliu513** [comment] 2018-11-29 00:02
Thanks @jnativio for the reminder. Close it first, and we are going to do another test based in Istio 1.1 after it released. Let's check the result then.

FYI @zxDiscovery

**Closed by gyliu513** 2018-11-29 00:02 UTC
Labels: area/perf and scalability
