### ISSUE TITLE
session affinity when running multiple replicas of a pod

### ISSUE THREAD

**Issue by colltie** [istio/istio#6011] opened 2018-06-04 16:38 UTC
Our scenario is easy:
  1. We run Multiple replicas of all and  particular containers
  2. We expect the same container to get all the request from a particular client for a given session

Issue:
This seems to work sometimes and fails other times.

Our test : Has been based on creating 20 different sessions 

Question: Does istio ingress currently support session affinity ?

Thanks

**Comment by Tharun-Sabbu** [comment] 2018-06-04 17:22
We are also having the same issue, as per my understanding mixer should have the configuration for session affinity. But I'm not sure where exactly it needs to be reconfigured if we doesn't need session affinity for multiple replicas of a deployment.

**Comment by gyliu513** [comment] 2018-06-06 03:47
@colltie @Tharun-Sabbu  Is this duplicate with https://github.com/istio/istio/issues/1703 , this was already in 1.0 scope. Feel free to open this if it is different with https://github.com/istio/istio/issues/1703

/cc @rshriram

**Comment by colltie** [comment] 2018-06-06 12:37
@gyliu513 @rshriram 
That is not the same thing.

issue 1703 forces all the traffic to the same backend service which can be backed by multiple replicas of a certain container.

We are talking about forcing the same request to the same backend replica

**Comment by gyliu513** [comment] 2018-06-06 22:29
@colltie got it, re-open it.

**Comment by rshriram** [comment] 2018-06-06 22:33
Session affinity is not supported. Working on adding cookie based affinity.

**Comment by igoooor** [comment] 2018-07-25 12:18
Do we have some news about this issue? Because I'm facing the same problem.
I have:
- 1 Deployment with 2 replicas and 1 nginx/phpfpm container

The problem is that if the same client requests multiple times the nginx/phpfpm server, it will randomly pick 1 of the 2 pods, and therefor will have different php session files.
I don't see how to solve this problem.

Note that without istio, so just with kubernetes, the 
`kind:Service  spec.sessionAffinity: ClientIP` does the trick, as 1 same client will always hit the 1 same pod.
But with that same config + istio, then it does not work anymore

**Comment by denniseffing** [comment] 2018-10-04 13:14
Can this be closed? As far as I can see, the current consistent hash load balancer allows (soft) session affinity across multiple replicas of the same backend service.

See https://istio.io/docs/reference/config/istio.networking.v1alpha3/#LoadBalancerSettings-ConsistentHashLB

**Comment by frankbu** [comment] 2018-10-04 14:51
Closing. ConstitentHashLB addresses this issue.

**Closed by frankbu** 2018-10-04 14:51 UTC
Labels: area/networking

**Comment by zifahs** [comment] 2019-08-27 05:30
Hey, but "LoadBalancerSettings-ConsistentHashLB" only works on http requests.
