### ISSUE TITLE
Istioctl or the operator warns of installing different istio version than the operators itself

### ISSUE THREAD

**Issue by antonioberben** [istio/istio#25539] opened 2020-07-15 14:03 UTC
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

In the operator CR there is a field to specify which version of istio to install.

There can be a situation where a istioctl o the istio-operator with a version 1.5.x tries to apply an `IstioOperaotr` manifest with a version 1.6.x making istiod deployment not matching due to differences in versions

istioctl or the operator populates the istio manifest based on its own version (1.5.x) but setting the image contianers at the version specified in the IstioOperator manifest (1.6.x)

It would be very helpful that this is stated at installation time. Or even blocked, since it makes no sense to use an installer (istioctl/operator) with a different version than the object to install (istio components)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ X ] Multi Cluster
[ ] Virtual Machine
[ X ] Multi Control Plane

**Additional context**

**Comment by ostromart** [comment] 2020-09-24 18:49
Duplicate of https://github.com/istio/istio/issues/18487.

**Closed by ostromart** 2020-09-24 18:49 UTC
Labels: area/environments/operator, area/user experience, lifecycle/needs-triage
