### ISSUE TITLE
TestGatewayConformance/GatewayObservedGenerationBump flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44850] opened 2023-05-10 15:30 UTC
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44833/integ-pilot_istio/1656036865121193984

Probably regression after 0.7.0 bump

**Comment by dddddai** [comment] 2023-05-19 01:53
How about making deployment controller update the `Programmed` condition dynamically by watching ready replicas of the deployment?
This means we update the `Programmed` condition only for "managed" gateways

**Comment by howardjohn** [comment] 2023-05-19 20:53
I don't think we want to watch deployments specifically, we should be using our higher abstraction (Service Instances). But its tricky to plumb that through since those updates do not trigger push context recompute.

But we only actually care about scaling from 0 to 1, right? We already do a full push in that case IIUC

**Comment by dddddai** [comment] 2023-05-22 05:58
> But we only actually care about scaling from 0 to 1, right? We already do a full push in that case IIUC

Yes but we don't do a full push when scaling from 1 to 0?
https://github.com/istio/istio/blob/3894a7f234c2581b9f626a2a64874f8a3f019f26/pilot/pkg/xds/eds.go#L102-L110

Or when 1 -> 2 -> 1 (rolling update), which is the test case I think:
https://github.com/kubernetes-sigs/gateway-api/blob/99d878d4a281d7e37ede18e191e69ba1bb6deb7f/conformance/tests/gateway-observed-generation-bump.go#L66-L76

**Comment by howardjohn** [comment] 2023-05-22 16:17
I don't think we need from 1 -> 0, at least for this test. The test is saying it is stuck on "not ready". 1->2->1 is also not an issue, its `Gateway not Programmed yet`. It actually has nothing to do with observedGeneration, its just failing due to a generic NamespacesMustBeReady

**Comment by dddddai** [comment] 2023-05-23 02:41
Ah yeah, I think the issue is due to a race condition:

1. [gateway updated](https://github.com/kubernetes-sigs/gateway-api/blob/99d878d4a281d7e37ede18e191e69ba1bb6deb7f/conformance/tests/gateway-observed-generation-bump.go#L66-L76)
2. service updated (by deployment controller)
3. full push
4. gateway status updated (could not find service instances because EndpointSlice is not sycned yet)
5. EndpointSlice synced
6. EDS push
7. `NamespacesMustBeReady` failed:
**Assigned to service(s) gateway-observed-generation-bump-istio.gateway-conformance-infra.svc.cluster.local:80, but failed to assign to all requested addresses: port 8080 not found** for hostname "gateway-observed-generation-bump-istio.gateway-conformance-infra.svc.cluster.local"

**Comment by howardjohn** [comment] 2023-05-25 17:32
But with 0->1 don't we hit https://github.com/istio/istio/blob/e65e97c8e1f93a569867838410f0f84f41c846c5/pilot/pkg/xds/eds.go#L179-L184?

**Comment by dddddai** [comment] 2023-05-26 01:14
[Updating `Spec.Listeners`](https://github.com/kubernetes-sigs/gateway-api/blob/99d878d4a281d7e37ede18e191e69ba1bb6deb7f/conformance/tests/gateway-observed-generation-bump.go#L66-L76) does not change the deployment spec, so there's no 0->1 or rolling update

**Comment by howardjohn** [comment] 2023-05-26 14:48
sorry I am being slow but I don't get it.

* If there are 0 replicas, we write status fail
* If there is N replicas, we write status success

If there was 0 replicas, eventually we would scale 0->1, trigger push, and
recompute...?

**Comment by dddddai** [comment] 2023-05-29 02:07
The full process is:

1. gateway created
2. gateway service/deployment created (by deployment controller)
3. EndpointSlice synced (0->1)
4. gateway status updated (`Programmed: True`, everything is good until now)
5. [gateway updated](https://github.com/kubernetes-sigs/gateway-api/blob/99d878d4a281d7e37ede18e191e69ba1bb6deb7f/conformance/tests/gateway-observed-generation-bump.go#L66-L76) (add port 8080 in `Spec.Listeners`)
6. service updated (by deployment controller)
7. gateway status updated (`Programmed: False`, could not find service instances for port 8080 because EndpointSlice is not synced yet)
8. EndpointSlice synced (**no 0->1**, it's just a port update)
9. EDS push without recomputing
10. `NamespacesMustBeReady` failed:
Assigned to service(s) gateway-observed-generation-bump-istio.gateway-conformance-infra.svc.cluster.local:80, **but failed to assign to all requested addresses: port 8080 not found** for hostname "gateway-observed-generation-bump-istio.gateway-conformance-infra.svc.cluster.local"

**Comment by dddddai** [comment] 2023-06-01 04:27
A possible fix is to [trigger a full push](https://github.com/dddddai/istio/commit/9115462d71e07692795be7d83bb0124502b06585) when endpoint ports are updated
It does not solve the 1->0 case though, but that's out of the scope of this issue. Just not sure if it's an ideal solution...

**Closed** 2023-09-29 21:33 UTC
Labels: area/networking, lifecycle/automatically-closed
