### ISSUE TITLE
perf: istio-proxy (envoy) optimization

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8274] opened 2018-08-27 19:37 UTC
**Describe the feature request**
Improve performance of istio-proxy

**Comment by cmluciano** [comment] 2018-08-30 16:50
Can we add more context to this in terms of what we think the bottleneck is? Also we should add SLIs to indicate what we are targeting in general.

**Comment by suryadu** [comment] 2018-08-30 19:54
As shown in fig.3.2.6.1 of Istio performance report (https://docs.google.com/document/d/1ob9M2TfI5GS3_rqrEhWFIpVyfFVKPTE8N3YZpeiDJxw/edit?usp=sharing), istio-proxy is taking more cpu than the service itself. We understand some of this cost is coming from telemetry portion as well. This issue is to track all the optimization work around side car proxy to reduce the overall costs of Istio service mesh.
@mandarjog has some flame graphs and @jnativio has more data from the regression tests.

**Comment by cmluciano** [comment] 2018-11-06 17:58
@suryadu @jnativio 

Since we have landed https://github.com/istio/istio/pull/8993 , the [flamegraphs](https://ibmcloud-perf.istio.io/regpatrol/release-1.0-20181030-09-15/full-helm2/flamegraphs/) show a much more tenable CPU profile for tracing. 

The graph now shows the majority of time is Mixer-specific filters. @mandarjog are you currently working on perf enhancements to the mixer filters?

**Comment by jnativio** [comment] 2018-11-06 18:34
Flamegraph link above has moved --> https://ibmcloud-perf.istio.io/regpatrol/pre-1.0.3_results/release-1.0-20181030-09-15/full-helm2/flamegraphs/

**Comment by jnativio** [comment] 2018-11-06 18:37
There was no switch from Jaegar to Zipkin. Jaegar has been used as the default tracing add-on for quite some time. Having a tool to consume the tracing generated by envoy does not alter its CPU usage profile.

**Comment by cmluciano** [comment] 2018-11-06 18:46
> There was no switch from Jaegar to Zipkin. Jaegar has been used as the default tracing add-on for quite some time.

Ah sorry about the confusion

**Comment by jnativio** [comment] 2018-11-07 22:18
#9802 was opened to investigate mixer filtering optimization

**Comment by jnativio** [comment] 2018-11-07 22:20
PR #9798 was created to merge #8993 into master/1.1 branches.

**Comment by cmluciano** [comment] 2018-11-26 22:07
closing since #9798 & #8993 is good to go

**Comment by cmluciano** [comment] 2018-11-27 16:40
reopen-ing as epic

**Comment by howardjohn** [comment] 2019-08-12 00:22
All associated issues here are completed

**Closed by howardjohn** 2019-08-12 00:22 UTC
Labels: Epic, area/perf and scalability
