### ISSUE TITLE
nginx with istio-proxy fails to route with http 503 Service Unavailable

### ISSUE THREAD

**Issue by satishmane** [istio/istio#25267] opened 2020-07-07 05:54 UTC
**Bug description**

I have nginx running with istio-proxy injected. Nginx proxy.conf has proxy_ rules defined to intercept ingress traffic and re-write header, url etc. 

nginx fails with http 503 Service Unavailable when forwarding traffic to a service in different namespace enabled MTLS strict mode.

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

istio-proxy injected in nginx pod should add "x-forwarded-client-cert" to the header so that 

**Steps to reproduce the bug**

traffic flow
========

GKE Load balancer -> NgINX Pod with istio-proxy (namespace : x, permissive mode) -> App Pod with istio-proxy (namespace : y, STRICT mode)
 
Nginx has proxy rules defined in proxy.conf which rewrites header and replace url with full fqdn of cluster IP service name and its port.

Intercept traffic dump on Nginx istio-proxy for App service port and do not see "x-forwarded-client-cert" in the header. I can see only header fields added by nginx proxy_set header..

It works fine from other all pods with istio-proxy to app pod except nginx pod with istio-proxy.

nginx too works fine if mtls set to permissive mode.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3 (34 proxies)

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T17:02:08Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istioctl install   --set values.global.proxy.privileged=true

**Environment where bug was observed (cloud vendor, OS, etc)**

Google Cloud GKE

**Comment by satishmane** [comment] 2020-07-07 07:26
If I change proxy_set header as below, then it works.

current rule
proxy_set_header Host $http_host;

changed to 
proxy_set_header Host clusterIP service name : port number; e.g. foo-service:8080

**Comment by howardjohn** [comment] 2020-07-30 00:30
This a duplicate of https://github.com/istio/istio/issues/24668, see more info there. Thanks!

**Closed by howardjohn** 2020-07-30 00:30 UTC
Labels: area/config, area/networking, lifecycle/needs-triage
