### ISSUE TITLE
How to build istio image on arm64 plantform？

### ISSUE THREAD

**Issue by DrowringMan** [istio/istio#26155] opened 2020-08-05 08:23 UTC
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by wenyuangui** [comment] 2020-08-14 10:27
any suggestion for arm64 docker images?

**Comment by howardjohn** [comment] 2020-08-14 15:24
Closing as a duplicate of https://github.com/istio/istio/issues/26508 and/or https://github.com/istio/istio/issues/21094. We currently only support building istioctl on arm; other binaries are community supported. See the second issue especially, tons of info there. Thanks!

**Closed by howardjohn** 2020-08-14 15:24 UTC
Labels: area/test and release, kind/enhancement, lifecycle/needs-triage
