### ISSUE TITLE
the hpa is not right for istiod of istio1.6.0  installed by operator!

### ISSUE THREAD

**Issue by lic17** [istio/istio#24598] opened 2020-06-11 06:04 UTC
**Bug description**

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"False","lastTransitionTime":"2020-05-27T07:20:54Z","reason":"FailedGetScale","message":"the
      HPA controller was unable to get the target''s current scale: deployments/scale.apps
      \"istio-pilot\" not found"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2020-05-19T08:33:01Z","reason":"FailedGetResourceMetric","message":"the
      HPA was unable to compute the replica count: unable to get metrics for resource
      cpu: no metrics returned from resource metrics API"}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource":"installed-state","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.0","release":"istio"},"name":"istiod","namespace":"istio-system"},"spec":{"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","targetAverageUtilization":80},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"istio-pilot"}}}
  creationTimestamp: "2020-05-19T08:32:45Z"
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: installed-state
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.0
    release: istio
  name: istiod
  namespace: istio-system
  resourceVersion: "18191092"
  selfLink: /apis/autoscaling/v1/namespaces/istio-system/horizontalpodautoscalers/istiod
  uid: 3f1f22e4-1f03-44bc-867d-414a09310d0b
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-pilot
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 1
  desiredReplicas: 0
```
the deployment name is  istio-pilot in the hpa for istiod,that is not right,it should be istiod.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
./istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (105 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-aliyun.1", GitCommit:"3632be0", GitTreeState:"", BuildDate:"2020-02-21T02:22:35Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-aliyun.1", GitCommit:"27fbcf7", GitTreeState:"", BuildDate:"2020-03-11T10:33:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
  istioctl operator init
```
**Environment where bug was observed (cloud vendor, OS, etc)**
```
aliyun cloud
```

**Comment by morvencao** [comment] 2020-06-13 02:39
Looks like you installed istio with in-cluster operator.
What's your IOP instance CR for the istio installation?
I 'm asking because I can't reproduce this, the name has been fixed in 1.6.x released.

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource":"example-istiocontrolplane","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.0","release":"istio"},"name":"istiod","namespace":"istio-system"},"spec":{"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","targetAverageUtilization":80},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"istiod"}}}
  creationTimestamp: "2020-06-13T02:34:38Z"
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: example-istiocontrolplane
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.0
    release: istio
  name: istiod
  namespace: istio-system
  resourceVersion: "1219"
  selfLink: /apis/autoscaling/v1/namespaces/istio-system/horizontalpodautoscalers/istiod
  uid: c4e67f51-d9f5-4e8d-a0bf-4727a39b99ab
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
```

**Comment by lic17** [comment] 2020-06-13 02:54
> Looks like you installed istio with in-cluster operator.
> What's your IOP CR for the istio installation?
> I 'm asking because I can't reproduce this, the name has been fixed in 1.6.x released.
> 
> ```
> apiVersion: autoscaling/v1
> kind: HorizontalPodAutoscaler
> metadata:
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource":"example-istiocontrolplane","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.0","release":"istio"},"name":"istiod","namespace":"istio-system"},"spec":{"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","targetAverageUtilization":80},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"istiod"}}}
>   creationTimestamp: "2020-06-13T02:34:38Z"
>   labels:
>     app: istiod
>     install.operator.istio.io/owning-resource: example-istiocontrolplane
>     istio.io/rev: default
>     operator.istio.io/component: Pilot
>     operator.istio.io/managed: Reconcile
>     operator.istio.io/version: 1.6.0
>     release: istio
>   name: istiod
>   namespace: istio-system
>   resourceVersion: "1219"
>   selfLink: /apis/autoscaling/v1/namespaces/istio-system/horizontalpodautoscalers/istiod
>   uid: c4e67f51-d9f5-4e8d-a0bf-4727a39b99ab
> spec:
>   maxReplicas: 5
>   minReplicas: 1
>   scaleTargetRef:
>     apiVersion: apps/v1
>     kind: Deployment
>     name: istiod
>   targetCPUUtilizationPercentage: 80
> status:
>   currentReplicas: 0
>   desiredReplicas: 0
> ```

this is the command. And the same problem I met in 1.6.1 
```
[root@ym-hk-master01 ~]# history | grep istioctl
  985  istioctl operator init
  986  ./istioctl operator init
  987  ./istioctl  manifest apply --set addonComponents.grafana.enabled=true --set addonComponents.kiali.enabled=true --set addonComponents.tracing.enabled=true
  988  history | grep istioctl
```
```
[root@jump-server ~]# kubectl get hpa -n istio-system istiod -o yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"False","lastTransitionTime":"2020-06-09T15:44:41Z","reason":"FailedGetScale","message":"the
      HPA controller was unable to get the target''s current scale: deployments/scale.apps
      \"istio-pilot\" not found"}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource":"installed-state","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.1","release":"istio"},"name":"istiod","namespace":"istio-system"},"spec":{"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","targetAverageUtilization":80},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"istio-pilot"}}}
  creationTimestamp: 2020-06-09T15:44:26Z
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: installed-state
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.1
    release: istio
  name: istiod
  namespace: istio-system
  resourceVersion: "126545178"
  selfLink: /apis/autoscaling/v1/namespaces/istio-system/horizontalpodautoscalers/istiod
  uid: 9e3832f5-f9f2-4214-8181-b313018c9ebb
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-pilot
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0

```
```
[root@ym-hk-master01 src]# ./istioctl version
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (2 proxies)
```

**Comment by kallependers** [comment] 2020-07-08 10:54
Same issue here (version 1.6.4). Temp fix: 

`kubectl -n istio-system patch hpa istiod -p '{"spec":{"scaleTargetRef":{"name":"istiod"}}}'`

**Comment by morvencao** [comment] 2020-07-09 02:20
@kallependers 1.6.4 should have the fix, https://github.com/istio/istio/blob/1.6.4/manifests/charts/istio-control/istio-discovery/templates/autoscale.yaml
I also verified this in my env:
```
# kubectl -n istio-system get hpa istiod -o yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2020-07-09T02:18:41Z"
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.4
    release: istio
  name: istiod
  namespace: istio-system
  resourceVersion: "1119"
  selfLink: /apis/autoscaling/v1/namespaces/istio-system/horizontalpodautoscalers/istiod
  uid: c11b115c-3ac4-4dca-a997-e6afb7d9346d
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 1
  desiredReplicas: 0
```

**Comment by kallependers** [comment] 2020-07-09 08:19
@morvencao that file never changed since it was created (1.6.0). Even master has no changes.

I don't think that file is used to be frank. For example: the metadata name would be the same (istiod vs istio-pilot) and the apiVersion in both our HPA is not equal to the one in the file (autoscaling/v1 vs autoscaling/v2beta1). 

`$ kubectl -n istio-system get hpa istiod -o yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2020-07-09T08:02:47Z"
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.4
    release: istio
  name: istiod
  namespace: istio-system
  resourceVersion: "5470725"
  selfLink: /apis/autoscaling/v1/namespaces/istio-system/horizontalpodautoscalers/istiod
  uid: 91125910-5af0-40f3-a0c5-696f183dfb83
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  targetCPUUtilizationPercentage: 80
status:
  currentCPUUtilizationPercentage: 40
  currentReplicas: 2
  desiredReplicas: 2
  lastScaleTime: "2020-07-09T08:12:56Z"`

**Comment by morvencao** [comment] 2020-07-09 09:10
@kallependers Is your env fresh install, or upgrade from older version? Actually I don't think I got your point.
The issue should be fixed since https://github.com/istio/istio/pull/24887

Can you show me your istioOperator spec that is used to install istio?

**Comment by kallependers** [comment] 2020-07-09 14:01
@morvencao I reapplied a custom IstioOperator and then it doesn't work. A clean-up of Istio and fresh install of 1.6.4 solves indeed the problem.

What I meant is https://github.com/istio/istio/blob/1.6.4/manifests/charts/istio-control/istio-discovery/templates/autoscale.yaml has different settings (version, namespace name) than installed HPA.

I guess this issue can be closed.

**Closed** 2020-07-10 03:12 UTC
Labels: area/environments, lifecycle/needs-triage
