### ISSUE TITLE
Istio Pilot consuming huge CPU resources

### ISSUE THREAD

**Issue by piyush-pruthi** [istio/istio#20262] opened 2020-01-17 09:25 UTC
**Expected behavior**
Limited CPU Usage

**Steps to reproduce the bug**
Deploy pods to a GKE cluster in a sequential manner.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

kubectl version - v1.15.0
helm version - v2.14.3
Istio Version - 1.4.3

**How was Istio installed?**
Using helm template.

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 
8 Cores

We ran a test for 15 minutes in which we deployed around 200 pods in a sequential manner.
As soon as a pod comes in Ready state, then only we deploy next pod.
For the test, Pilot CPU Usage went as high as 5 cores.
In some cases, it even went above 6 cores.
There were slight improvements after tuning GOGC but not much.

From the pprof output , analysed that a lot of time was being spent by protobuf.
Attaching grafana pictures and pprof output.

<img width="1419" alt="pilot-cpu" src="https://user-images.githubusercontent.com/55531020/72599405-a60bd800-3937-11ea-8617-c8a0aba31305.png">
<img width="1419" alt="pilot-mem" src="https://user-images.githubusercontent.com/55531020/72599407-a60bd800-3937-11ea-90b2-30544d527665.png">

<img width="793" alt="cpu-profile" src="https://user-images.githubusercontent.com/55531020/72600261-5201f300-3939-11ea-96ea-b19404e7885b.png">
<img width="922" alt="memory-profile" src="https://user-images.githubusercontent.com/55531020/72600265-529a8980-3939-11ea-848d-669a8b4fb69e.png">

**Comment by rshriram** [comment] 2020-01-17 19:32
can you give some stats on the configs you have in your system (EnvoyFilters, or other networking APIs, etc.) ?

**Comment by rshriram** [comment] 2020-01-17 19:32
cc @howardjohn / @mandarjog

**Comment by howardjohn** [comment] 2020-01-17 19:35
Can you upload the cpu profile as well?

Also is my math here correct that you are deploying a new pod every 4s?

**Comment by howardjohn** [comment] 2020-01-17 19:35
And are the pods all in one deployment/Service?

**Comment by piyush-pruthi** [comment] 2020-01-18 21:30
@howardjohn : On an average, in every 8 seconds, a new nginx deployment is being created.

[pprof.pilot-discovery.samples.cpu.041.pb.gz](https://github.com/istio/istio/files/4081796/pprof.pilot-discovery.samples.cpu.041.pb.gz)

**Comment by howardjohn** [comment] 2020-01-18 23:42
So you have 200 deployments of a single pod each, right? What you have described is pretty much the worst case scenario for Pilot. You are making changes fast enough that it needs to do a ton of work, but slow enough that it won't group changes together as a batch

**Comment by piyush-pruthi** [comment] 2020-01-20 05:01
yes...200 deployments of single pod each.
A major bottleneck, this creates is - beyond 100 workloads deployed, the ping time for a service starts taking more than 10 minutes.
Also, when we deployed a single workload per second, the cpu usage graph was like this only.

Can we configure pilot batch size to tune for performance acc. to our requirements?
Also, can you suggest some things here to reduce the ping time?

**Comment by howardjohn** [comment] 2020-01-20 05:02
@piyush-pruthi I think there must be some other factors here. Pilot should have no correlation to your service ping time? Its on the control plane path only, not impacting traffic to your service

**Comment by mandarjog** [comment] 2020-01-20 05:03
Are you holding the first ping until the pods are ready like knative?

**Comment by piyush-pruthi** [comment] 2020-01-20 05:42
This is the script for deploying workloads.
Create a deployment - wait for it to be in ready state - note ping time - then go for next deployment.

<img width="977" alt="Screenshot 2020-01-20 at 11 07 25 AM" src="https://user-images.githubusercontent.com/55531020/72701484-76e2aa00-3b75-11ea-88c5-0d41c1cbf80d.png">

**Comment by howardjohn** [comment] 2020-01-20 05:44
Reproduce this. 

Same setup, 200 deployment+svc+vs (single replica). I created them every 1s though since I am impatient...

results of various settings

Baseline: https://snapshot.raintank.io/dashboard/snapshot/MPan18WkEpkp780Q3VmNwvEAthvXmn3g?orgId=2. 5 CPU, 2.6s push time

PILOT_PUSH_THROTTLE=1: https://snapshot.raintank.io/dashboard/snapshot/EJujuyFo3K8wXY01JenH75CUkeVxGf1r?orgId=2. 2.5PCPU, 5s push time

PILOT_DEBOUNCE_AFTER=10s: https://snapshot.raintank.io/dashboard/snapshot/YeIefT5A8bUXkKVO7fQDkyfs4g861VUo?orgId=2&refresh=5s. 0.8 CPU, 2.6s push time

**Comment by piyush-pruthi** [comment] 2020-01-21 05:11
After this configuration on my setup,
CPU came down significantly.

With PILOT_PUSH_THROTTLE=1:
https://snapshot.raintank.io/dashboard/snapshot/U2RWfGwn3nndegfAUFMxYXjth27y02sD?orgId=2
2.2 CPU

PILOT_DEBOUNCE_AFTER=10s:
https://snapshot.raintank.io/dashboard/snapshot/lj2WXXrZSZOAJdVMgOI5QqM1M62ohRJp?orgId=2
1.25 CPU

PILOT_PUSH_THROTTLE=2:
https://snapshot.raintank.io/dashboard/snapshot/F4S8d2J6QEyDAmEr40l8o96FkdI3aZIL?orgId=2
3 CPU

Now, I think we just need to find a sweet spot by tuning these 2 variables, keeping in mind the nature of workload.
Thanks for helping out here.

As for previous ping time concern(taking more than 10 min.) , you are absolutely right - there was some other factor.
Albeit, one thing to note here is :-

PILOT_PUSH_THROTTLE=1 :- 
Average ping time for the last 10 services(191-200) was 3.4 seconds.

PILOT_PUSH_THROTTLE=2 :- 
Average ping time for the last 10 services came down to 1.8 seconds.

PS - By ping time, what I mean here is , for pod to come from ready to running state and route being available.

So, PILOT_PUSH_THROTTLE may impact our route availability time, right ?

**Comment by howardjohn** [comment] 2020-01-21 14:53
push throttle will limit the speed at which updates are sent (as will the denounce), so pods may not be able to communicate to new pods for some period of time. However the new pod should get its own config quickly still

**Comment by piyush-pruthi** [comment] 2020-01-23 08:11
@howardjohn : We are doing a ping from outside to the newly created pod. 

These results were captured with PILOT_DEBOUNCE_AFTER=10s.
From the logs, it looks like that PILOT_DEBOUNCE_AFTER is affecting new config also.
[debounce_10s.log](https://github.com/istio/istio/files/4101927/debounce_10s.log)

**Comment by howardjohn** [comment] 2020-01-23 16:07
I would need to look at the logs for pilot I guess? But there is two codepaths: one where Envoy requests resources (mainly during startup) and one where we push updates (mainly from config change/new services). The debounce should only impact the second case

**Comment by piyush-pruthi** [comment] 2020-01-24 12:00
[discovery.txt](https://github.com/istio/istio/files/4108258/discovery.txt)

2020-01-24T10:37:28.698732Z info  ads CDS: PUSH for node:istio-ingressgateway-64ddd9c7c5-mjpv8.istio-system clusters:93 services:25 version:2020-01-24T10:37:28Z/2
2020-01-24T10:37:28.699474Z info  ads EDS: PUSH for node:nginx-1-6bfdd944f8-ptd9l.default clusters:44 endpoints:45 empty:[]
2020-01-24T10:37:28.699625Z info  ads EDS: PUSH for node:nginx-7db75b8b78-4cj8h.default clusters:44 endpoints:45 empty:[]
2020-01-24T10:37:28.699956Z info  ads EDS: PUSH for node:nginx-2-7bcdf89db4-mc2rp.default clusters:44 endpoints:45 empty:[]
2020-01-24T10:37:28.702094Z info  ads EDS: PUSH for node:istio-ingressgateway-64ddd9c7c5-mjpv8.istio-system clusters:90 endpoints:110 empty:[]
2020-01-24T10:37:28.702362Z info  ads LDS: PUSH for node:istio-ingressgateway-64ddd9c7c5-mjpv8.istio-system listeners:1
2020-01-24T10:37:28.702781Z info  ads RDS: PUSH for node:istio-ingressgateway-64ddd9c7c5-mjpv8.istio-system routes:1
2020-01-24T10:37:28.705610Z info  ads LDS: PUSH for node:nginx-1-6bfdd944f8-ptd9l.default listeners:47

From the logs, found out that push to "ingress gateway" also happens alongside other events.
I think, this is causing a delay in route availability.

**Comment by infa-ddeore** [comment] 2020-07-24 05:32
I ran a test: 

- 1200 pods with istio sidecar, svc and virtualservice for each pod
- wait 1 second between each pod deployment (it is more aggressive)

PILOT_PUSH_THROTTLE=1
PILOT_DEBOUNCE_AFTER=10s

istiod cpu load isnt even, does it mean only 1 istiod pod was doing most of the job and others not? how to make sure all istiod pods share even load?

![image](https://user-images.githubusercontent.com/39782583/88363224-e8a5e580-cd9c-11ea-87f3-cc7db0601b73.png)

**Comment by ramaraochavali** [comment] 2020-07-24 07:37
They will get load balanced over a period of time - but to start with the load balancing might be skewed. Refer to https://github.com/istio/istio/issues/11181

**Comment by howardjohn** [comment] 2020-09-12 00:44
Can you try 1.7? We made a ton of performance improvements

**Comment by howardjohn** [comment] 2020-10-22 15:01
Closing as this is assumed fixed

**Closed by howardjohn** 2020-10-22 15:01 UTC
Labels: area/networking, area/perf and scalability, kind/need more info, lifecycle/needs-triage

**Comment by taitelman** [comment] 2020-11-26 11:09
```
$ istioctl version --remote
client version: 1.7.0
control plane version: 1.7.4
data plane version: 1.7.4 (516 proxies)
```
istiod can easily consume 3 (or more) vCPU cores on a relative medium istio artifact creations stress (creating PAs, AuthorizationPolicy etc)

**Comment by teebu** [comment] 2022-08-04 19:43
I'm noticing some high numbers in our relatively small cluster, now sure why its happening. 

![image](https://user-images.githubusercontent.com/5531844/182939084-c0f79c6f-792c-4a1e-afce-c2fa66eddafe.png)



```
 istioctl version --remote
client version: 1.14.0
control plane version: 1.12.0
data plane version: 1.12.0 (19 proxies)
```

**Comment by howardjohn** [comment] 2022-08-04 19:46
https://github.com/istio/istio/wiki/Analyzing-Istio-Performance. Please open an issue with profiles.
