### ISSUE TITLE
Istio 1.3.5 - sidecar-injector.istio.io returns function "structToJSON" not defined

### ISSUE THREAD

**Issue by popopanda** [istio/istio#18915] opened 2019-11-13 01:01 UTC
**Bug description**

After upgrading istio 1.3.5 from 1.2.2, all deployment rollouts via replicasets fail with error:

```
Warning  FailedCreate  3s (x15 over 85s)  replicaset-controller  Error creating: Internal error occurred: admission webhook "sidecar-injector.istio.io" denied the request: template: inject:139: function "structToJSON" not defined
````

obtaining logs from the sidecar-injector pod returns:

`2019-11-13T00:42:31.437993Z	info	Injection data: err=template: inject:139: function "structToJSON" not defined spec=`

**Expected behavior**
Pods should be able to be created from the replicaset without errors

**Steps to reproduce the bug**

kubectl rollout restart deployment <my_deployment>

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
via helm

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by blhagadorn** [comment] 2019-11-13 02:01
@popopanda I ran into this issue today but I believe I resolved it with updating my `istioctl` to the latest version.  What do you get when you run `istioctl version --remote`?

**Comment by howardjohn** [comment] 2019-11-13 05:46
the problem is a mismatch with the injection code and config map. In @blhagadorn case this was istioctl, but in this case it seems like your sidecar injector deployment is old

**Comment by howardjohn** [comment] 2019-11-13 05:46
please run `istioctl version` as requested in the issue template and I suspect you will see the wrong version

**Comment by popopanda** [comment] 2019-11-13 07:22
I might need some clarification, but how does istioctl relate to the replica set error?

My version:
`istioctl version`

```
client version: 1.2.2
citadel version: 1.3.5
citadel version: 1.3.5
egressgateway version: 1.3.5
egressgateway version: 1.3.5
galley version: 1.3.5
galley version: 1.3.5
ingressgateway version: 1.3.5
ingressgateway version: 1.3.5
pilot version: 1.3.5
pilot version: 1.3.5
policy version: 1.3.5
policy version: 1.3.5
sidecar-injector version: 1.3.5
telemetry version: 1.3.5
telemetry version: 1.3.5
```

I've tried manually deleting the existing sidecar-injector pod, so a new one would be deployed.  Then attempted to roll my deployment to a new release on a replicaset and still running into the same problem.

Thanks

**Comment by howardjohn** [comment] 2019-11-13 15:17
then maybe the sidecar injection template is old? or newer? it's a config map in istio-system named "istio-sidecar-injector"

**Comment by popopanda** [comment] 2019-11-13 18:36
Apologies, the istioctl versions above are incorrect. I've updated the post.

```
citadel version: 1.3.5
citadel version: 1.3.5
egressgateway version: 1.3.5
egressgateway version: 1.3.5
galley version: 1.3.5
galley version: 1.3.5
ingressgateway version: 1.3.5
ingressgateway version: 1.3.5
pilot version: 1.3.5
pilot version: 1.3.5
policy version: 1.3.5
policy version: 1.3.5
sidecar-injector version: 1.2.2
telemetry version: 1.3.5
telemetry version: 1.3.5
```

The istio-sidecar-injector deployment, it never creates a new replicaset 

```
OldReplicaSets:  istio-sidecar-injector-57d8bcb5d5 (1/1 replicas created)
NewReplicaSet:   <none>
````

```
istio-sidecar-injector-54d6cbc58f            0         0         0       96d
istio-sidecar-injector-57d8bcb5d5            1         1         1       90d
istio-sidecar-injector-6d8f88c98f            0         0         0       232d
istio-sidecar-injector-6dd64c6bbd            0         0         0       90d
istio-sidecar-injector-97f9878bc             0         0         0       111d
```

```
kubectl describe deployment istio-sidecar-injector -n istio-system

Normal  ScalingReplicaSet  4m29s (x2 over 19h)  deployment-controller  Scaled down replica set istio-sidecar-injector-57d8bcb5d5 to 1
```

All other resources such as pilot, gateways, policy are deployed from their new replicasets

How do I determine if the configmap is old or new? And would that prevent new deployments from occuring?

Thanks for your help

**Comment by howardjohn** [comment] 2019-11-13 18:51
Do a describe on one of the replicasets and it may give more info. That is why you get the error, the injector image is old. It needs to be 1.3.5

**Comment by popopanda** [comment] 2019-11-13 21:30
The replicaset is still on 1.2.2, though the deployment says to use image v1.3.5

```
# sidecar-injector deployment
        image: docker.io/istio/sidecar_injector:1.3.5
```

I manually edited the existing replicaset to use the v1.3.5 image, and deleted the existing sidecar-injector pod. It's working now, but I guess im confused as to why new replicaset for v1.3.5 never created

**Comment by howardjohn** [comment] 2020-05-13 18:31
This is fixed by upgrading the image as above, so closing this. Thanks!

**Closed by howardjohn** 2020-05-13 18:31 UTC
Labels: area/config, lifecycle/needs-triage
