### ISSUE TITLE
404

### ISSUE THREAD

**Issue by wfwf1990** [istio/istio#17140] opened 2019-09-17 11:22 UTC
hello, Accessible through curl, not through browsers, and I don't want to solve this problem through *
Is there any other solution?

kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /headers
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
EOF

 

[2019-09-17T11:11:11.939Z] "GET /status/200HTTP/1.1" 404 NR 0 0 0 - "172.30.74.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "72bf6a54-8a81-9cee-b34f-b9afd08d331d" "httpbin.example.com:31080" "-" - - 172.30.76.15:80 172.30.74.0:57750
[2019-09-17T11:11:33.197Z] "HEAD /status/200HTTP/1.1" 200 - 0 0 3 2 "172.30.74.0" "curl/7.29.0" "907df364-7aed-952e-88eb-6c2d45ecc651" "httpbin.example.com" "172.30.76.13:8000" outbound|8000||httpbin.default.svc.cluster.local - 172.30.76.15:80 172.30.74.0:40284

**Comment by howardjohn** [comment] 2019-09-17 13:46
That means you don't have a virtual service that matches the request

**Comment by howardjohn** [comment] 2019-09-17 13:47
Closing this as working as intended. If you have any questions please feel free to open a topic on discuss.istio.io

**Closed by howardjohn** 2019-09-17 13:47 UTC
