### ISSUE TITLE
Installing from HEAD causing mixer init failing

### ISSUE THREAD

**Issue by salrashid123** [istio/istio#1932] opened 2017-11-30 04:13 UTC
If i attempt to install istio using HEAD, the mixer fails to init on startup:
```Error: unknown flag: --zipkinURL```

I realize the installation mechanism detailed below isn't what is recommended in our docs but filing this so we can catch this well prior to release.

repro on GCP:
```
gcloud container  clusters create "cluster-1" --zone "us-central1-a"   --enable-kubernetes-alpha --num-nodes "3" --network "default" --no-enable-cloud-logging --no-enable-cloud-monitoring --enable-legacy-authorization
```

then
```
git clone https://github.com/istio/istio.git
cd istio

kubectl apply -f install/kubernetes/istio.yaml
```

---

- the mixer pod shows

```
  mixer:
    Container ID:  docker://48c0fbcf689302790f13f38fa02e9d445d03574bebadd107185032159966905d
    Image:         gcr.io/istio-testing/mixer:5253b6b574a98b209c0ef3d0d6e90c1b8d6a5c2a
    Image ID:      docker-pullable://gcr.io/istio-testing/mixer@sha256:445a7ca236c6f1f4754da1e57379a001f530c4f21dfed7a2f86981774a1d4434
    Ports:         9091/TCP, 9094/TCP, 42422/TCP
    Args:
      --configStoreURL=fs:///etc/opt/mixer/configroot
      --configStore2URL=k8s://
      --configDefaultNamespace=istio-system
      --zipkinURL=http://zipkin:9411/api/v1/spans
      --logtostderr
      -v
      2
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 29 Nov 2017 18:21:35 -0800
      Finished:     Wed, 29 Nov 2017 18:21:35 -0800
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from istio-mixer-service-account-token-p20b0 (ro)
```
---

- with logs

```
mixer	2017-11-30T02:21:35.470851524Z	--clientCertFiles string A set of comma-separated client X509 cert files
mixer	2017-11-30T02:21:35.470849136Z	--apiWorkerPoolSize int Max number of goroutines in the API worker pool (default 1024)
mixer	2017-11-30T02:21:35.470845065Z	--adapterWorkerPoolSize int Max number of goroutines in the adapter worker pool (default 1024)
mixer	2017-11-30T02:21:35.470842895Z	Flags:
mixer	2017-11-30T02:21:35.470840715Z	
mixer	2017-11-30T02:21:35.470838052Z	mixs server [flags]
mixer	2017-11-30T02:21:35.470825846Z	Usage:
mixer	2017-11-30T02:21:35.470038740Z	Error: unknown flag: --zipkinURL
```

/cc @selmanj

**Comment by salrashid123** [comment] 2017-11-30 19:23
I tried specific 0.3.0 and see it there too:

```
git clone https://github.com/istio/istio.git
git checkout tags/0.3.0
Note: checking out 'tags/0.3.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 24ec6a3a... update proxy sha (#1918)
```

----

```
  kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value core/account)
 kubectl apply -f install/kubernetes/istio.yaml
```
  
```
  $ kubectl get po -n istio-system
NAME                            READY     STATUS             RESTARTS   AGE
istio-ca-557681425-csm48        1/1       Running            0          2m
istio-ingress-301425920-33s5s   1/1       Running            0          2m
istio-mixer-793605709-2phx5     2/3       CrashLoopBackOff   4          2m
istio-pilot-3881298009-fmd76    2/2       Running            0          2m
```

```
$ kubectl logs istio-mixer-793605709-2phx5  mixer --namespace istio-system | grep -i zipkin
Error: unknown flag: --zipkinURL
  -t, --traceOutput string              If the literal string 'STDOUT' or 'STDERR', traces will be produced and written to stdout or stderr respectively. Otherwise the address is assumed to be a URL and HTTP zipkin traces are sent to that address. Note that when providing a URL it must be the full path to the span collection endpoint, e.g. 'http://zipkin:9411/api/v1/spans'.

```

**Comment by selmanj** [comment] 2017-11-30 19:26
Note, this appears to be an issue due to how @salrashid123 and I are installing istio. Instead of using an official release, we are checking out a specific tag of the repo and installing the yaml files found in the `install` directory. Those specify a specific sha tag to use for the different component's image, and this sha1 tag hasn't been updated in a long time.

It appears that `updateVersion.sh` overwrites these sha1 tags with a specific name-release tag. This is fairly confusing!

**Comment by danehans** [comment] 2017-12-05 22:51
I am seeing this issue using head (sha 620a7c7f). If the mixer image has not been updated in a while, what is the tag of a newer image that can be used? Do other images need to be updated too? I'm searching through the images at `gcr.io/istio-testing`, but I'm unsure which one to use.

**Comment by danehans** [comment] 2017-12-05 23:06
I am using the `0.3.1` image tag and I see the same error.

**Comment by selmanj** [comment] 2017-12-06 01:08
@danehans Someone associated with the Istio-project can correct me, but I think the yaml files in the install directory are meant to be templates and are not meant to be installed directly. The `updateVersion.sh` script does some `sed` magic to make sure that the tags are correct.

Did you try using the templates published in https://github.com/istio/istio/releases/tag/0.3.0?

(Note that this assumes you're trying to run an official release; if you're trying to run the latest I think you're meant to [run the version update script yourself](https://github.com/istio/istio/blob/master/DEV-GUIDE.md#building-the-istio-manifests))

**Comment by sdake** [comment] 2017-12-11 13:11
Just pulled master and this problem occurs with no modifications to the repository:

```
NAMESPACE      NAME                                        READY     STATUS             RESTARTS   AGE
istio-system   grafana-666cd9c9c-9wlh2                     1/1       Running            0          47s
istio-system   istio-ca-cf6847f4b-wdhqg                    1/1       Running            0          47s
istio-system   istio-ingress-5664456b47-8d7xg              1/1       Running            1          47s
istio-system   istio-mixer-7796d9954d-t58np                2/3       CrashLoopBackOff   2          47s
istio-system   istio-pilot-87f89966-tpb59                  2/2       Running            0          47s
istio-system   prometheus-778b44d4fb-r4l24                 1/1       Running            0          47s
istio-system   servicegraph-7ff8cbcc7f-26qrv               1/1       Running            0          47s
istio-system   zipkin-77575b5c89-znvzf                     1/1       Running            0          47s
kube-system    calico-etcd-fb58c                           1/1       Running            0          47s
kube-system    calico-node-7nhmc                           2/2       Running            0          47s
kube-system    calico-policy-controller-59fc4f7888-kjdbm   1/1       Running            0          47s
kube-system    kube-apiserver-falkor-07                    1/1       Running            0          9s
kube-system    kube-controller-manager-falkor-07           1/1       Running            0          17s
kube-system    kube-dns-545bc4bfd4-zpdx2                   3/3       Running            0          47s
kube-system    kube-proxy-v654m                            1/1       Running            0          47s
kube-system    kube-scheduler-falkor-07                    1/1       Running            0          5s
sdake@falkor-07:~/istio$ kubectl logs istio-mixer-7796d9954d-t58np -n istio-system mixer
Error: unknown flag: --zipkinURL
Usage:
  mixs server [flags]
```

I'll try building custom images and report back if the images are just out of date and this problem is already resolved.

**Comment by sdake** [comment] 2017-12-11 14:17
Note building custom images does not exhibit this problem.  The updateVersions.sh script needs to be run by someone that can also at the same time build and push images to gcr.io.

**Comment by geeknoid** [comment] 2017-12-12 22:30
I believe Mixer is fine, the issue is with the images that end up being used.

**Comment by fotinakis** [comment] 2017-12-13 03:40
Loving istio! Just a +1 to say this was pretty confusing — used the yaml file directly from the v0.3.0 tag of the repo and everything was broken. Used the yaml source downloaded from the Releases page and everything works.

**Comment by danehans** [comment] 2017-12-13 18:35
Since installing the release tarball has been validated, should this issue be closed or should a PR be submitted against master to update `istio.VERSION` with the appropriate image tags?

**Comment by geeknoid** [comment] 2017-12-13 18:46
Can we improve our processes/docs so a similar problem doesn't surface
again?

**Comment by hklai** [comment] 2017-12-14 18:40
@rkpagadala, could you document the root cause of the problem here? We will then work out a plan to address this and update the issue.

**Comment by rkpagadala** [comment] 2017-12-15 20:03
In older releases before the repo merge istio.yaml were checked in to the istio repo. Since the merge this not being done. With the daily/weekly/monthly builds that we have now.  I would like to remove them from the source tree. This avoids confusion, while also allowing istio users to use the latest code via builds of their choice.

**Comment by svenmueller** [comment] 2017-12-18 14:36
i followed the offcial setup documentation (https://istio.io/docs/setup/kubernetes/quick-start.html) and downloaded version 0.4 from the release page and ended up with the same issue.

**Comment by selmanj** [comment] 2017-12-18 18:27
@svenmueller Did you download one of the release tarballs (e.g. `istio-0.4.0-linux.tar.gz`, `istio-0.4.0-osx.tar.gz`, or `istio_0.4.0_win.zip`) or the source code? I just pulled the linux tarball and I don't see the issue documented here (specifically, that the image tag is old in the kubernetes `istio.yaml` install).

It's confusing because both the release tar/zip files and the source code have the same install directory structure, but the release files have install yamls with correct tags.

**Comment by rkpagadala** [comment] 2017-12-18 19:00
@svenmueller downloading the 0.4 version from https://github.com/istio/istio/releases/tag/0.4.0 and following the instructions works for me. Did you clone the repo and use istio.yaml from there?

**Comment by svenmueller** [comment] 2017-12-18 19:35
@rkpagadala i think i downloaded the zip artifact from the release page (https://github.com/istio/istio/archive/0.4.0.zip)

**Comment by rkpagadala** [comment] 2017-12-18 19:55
@svenmueller I see the confusion you downloaded source code. Please try one of
https://github.com/istio/istio/releases/download/0.4.0/istio_0.4.0_win.zip for windows
https://github.com/istio/istio/releases/download/0.4.0/istio-0.4.0-linux.tar.gz for linux or
https://github.com/istio/istio/releases/download/0.4.0/istio-0.4.0-osx.tar.gz for mac

**Comment by sirajmansour** [comment] 2017-12-20 06:37
@rkpagadala the problem exists even when downloading from the mentioned windows URL

**Comment by sirajmansour** [comment] 2017-12-20 06:39
@rkpagadala actually ignore my previous comment, i updated the container from tsandall/mixer:dev4 based on the OPA demo on https://github.com/tsandall/cloudnativecon17-istio-opa-demo

**Comment by rkpagadala** [comment] 2017-12-20 19:23
@sirajmansour the zipkinURL argument is expected and should work in the 0.4.0 release.

**Comment by sdake** [comment] 2018-01-03 14:33
should be resolved by the work that shakes out of: https://github.com/istio/istio/pull/2378

**Comment by rkpagadala** [comment] 2018-01-09 00:53
we no longer have installation yaml's in source code

**Closed** 2018-01-09 00:53 UTC
Labels: install

**Comment by azr** [comment] 2018-02-22 10:22
Hi there, I somehow just had the problem.

I did:

* create a kluster on `1.9.2-gke.1`
* ran: 
```
kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=$(gcloud config get-value core/account)
```
 * in the istio repo: `git checkout 0.5.1 && ./install/updateVersion.sh && kubectl apply -f install/kubernetes/istio.yaml`

now running `kubectl  -n istio-system logs deploy/istio-mixer mixer` gives me:

```
Error: unknown flag: --zipkinURL
Usage:
  mixs server [flags]
```
