### ISSUE TITLE
Istio 1.0.2 Tracker

### ISSUE THREAD

**Issue by rkpagadala** [istio/istio#8225] opened 2018-08-24 18:55 UTC
1.0.1 patch has been released on the 1.00 train.
We may create another patch release 1.0.2 next month if there are critical issues* in 1.0.1.

If you have any PRs that should be considered for 1.0.2, please add them to this issue.

(*) Critical Issues Definition
Regression of a feature that is used by customers in prior releases.
Runtime crashes that severely regress stability of the system (i.e. SLO)

**Comment by rkpagadala** [comment] 2018-08-24 18:56
Referencing #7672 which is tracker for 1.0.1

**Comment by k** [comment] 2018-08-25 01:04
#7553

**Comment by sdake** [comment] 2018-08-27 13:26
This may remove a regression - pending review: https://github.com/istio/istio/pull/8250

**Comment by PiotrSikora** [comment] 2018-08-30 04:48
#8310 - easily reproducible istio-proxy segfaults, IMHO warrants 1.0.2 as soon as it's fixed.

cc @costinm @louiscryan

**Comment by rkpagadala** [comment] 2018-08-30 23:15
@k regarding #7553 please cherrypick to branch release-1.0 and send a PR

**Comment by k** [comment] 2018-08-31 19:46
@rkpagadala okay waiting on #8416 for a bug fix

**Comment by sdake** [comment] 2018-09-04 03:43
gateway-telemetry feature has been DOA since 1.0.0 - https://github.com/istio/istio/pull/8450

**Comment by sdake** [comment] 2018-09-04 03:52
Istio multicluster failure in many scenarios since the introduction of envoyv2 discovery - https://github.com/istio/istio/pull/8451

**Comment by pennyluis** [comment] 2018-09-04 03:54
Approve

**Comment by hklai** [comment] 2018-09-04 22:57
Update: we can cutting 1.0.2 for two urgent bug fixes:
https://github.com/istio/istio/pull/8452
https://github.com/istio/istio/pull/8389

Some earlier mentioned PRs will also be included:
https://github.com/istio/istio/pull/8252
https://github.com/istio/istio/pull/8250

Here is a list of all included commits since 1.0.1
https://github.com/istio/istio/compare/1.0.1...release-1.0

Other bug fixes are pushed to 1.0.3.

**Comment by sdake** [comment] 2018-09-05 10:19
@hklai - can you confirm everything in https://github.com/istio/istio/compare/1.0.1...release-1.0 will be released in 1.0.2?  Specifically looking for the merged https://github.com/istio/istio/pull/8377 to make 1.0.2 as multicluster is semi-DOA without it.

Cheers
-steve

**Comment by hklai** [comment] 2018-09-05 16:33
@sdake Right, #8377 will be included.

**Comment by hklai** [comment] 2018-09-05 19:34
RC for 1.0.2 is available at
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180905-18-29/

Please test it and report problem, if any.

**Comment by PiotrSikora** [comment] 2018-09-05 21:28
@hklai I verified that RC works fine (i.e. no more proxy segfaults), thanks!

**Comment by hklai** [comment] 2018-09-06 19:56
The RC had been verified by @costinm, @myidpt, @mandarjog and @PiotrSikora.

We will proceed to cut the release today.

**Comment by hklai** [comment] 2018-09-06 21:58
https://github.com/istio/istio/releases/tag/1.0.2 is published.

**Closed by hklai** 2018-09-06 21:58 UTC
Labels: area/test and release
