### ISSUE TITLE
what guarantees prometheus scraping from multiple mixer ?

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#2531] opened 2018-01-10 19:07 UTC
Looking at the configuration of prometheus its not clear on how prometheus scrapping guarantee no data loss from mixer in case of multiple mixer.

Currently prometheus scrape from multiple mixer based on IP returned(load balanced) by kube dns ?  

Prometheus might loose data from few mixer instance if operator screws up the scrap time interval ? 

```
global:
  scrape_interval: 15s
scrape_configs:

- job_name: 'istio-mesh'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
  - targets: ['istio-mixer.istio-system:42422']

- job_name: 'envoy'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
  - targets: ['istio-mixer.istio-system:9102']

- job_name: 'mixer'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
  - targets: ['istio-mixer.istio-system:9093']
```

**Comment by mandarjog** [comment] 2018-01-17 22:32
The issue is that we are using dns name as a scrape target.
It should be the actual mixer endpoint. Without that even with just 2 Mixer we will loose data or give unexpected results.

For example consider a situation where both Mixers are maintaining histograms of latencies. The correct answer is to merge the histogram by simple addition from two mixers. Using a dns name, prometheus will randomly get one histogram and produce incorrect results. The histograms as seen my prometheus may not have monotonically increasing values.

As next steps, we need to have a process / agent that does endpoints discovery and programs prometheus instance. There may be other first class ways of doing this that prometheus supports.

**Comment by douglas-reid** [comment] 2018-01-17 23:52
There are prometheus config options that integrate with k8s. I believe we will want to transition to something like [k8s sd service config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#service) for mixer metrics scrapping.

We should do some testing / experimentation to validate as we transition to HA Mixer.

**Comment by douglas-reid** [comment] 2018-01-17 23:55
I should mention that I've been experimenting with this recently as we work towards an pre-alpha version of a dashboard for Mixer itself.

**Comment by jeffmendoza** [comment] 2018-01-24 01:38
Looks like this is the correct setup, it is working nicely for me:
https://github.com/istio/istio/compare/master...jeffmendoza:prom-config

I'll do some more tests tomorrow and open a PR

**Comment by kidiyoor** [comment] 2018-01-24 02:42
@jeffmendoza  This solution is will only with Kubernetes. This won't solve the problem in scenarios where 'consul is used as service registry' or 'VM ONLY Istio setup' etc.

Another way of solving this problem would be pilot (or another agent) updating prometheus with mixer endpoints dynamically via prometheus APIs, this solution would be platform agnostic.

**Comment by mandarjog** [comment] 2018-01-24 04:07
@kidiyoor since Prometheus provides an API, would be good if you can create an updater agent.
It is unclear if Prometheus will support reading from arbitrary registries.

**Comment by jeffmendoza** [comment] 2018-01-24 04:21
Prometheus will have to use whatever service discovery is available in the environment to find all the mixer instances. It looks like [Consul is supported](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#consul_sd_config), along with many others.

I don't see any prometheus templates in https://github.com/istio/istio/tree/master/install/consul is this provided somewhere else?

**Comment by douglas-reid** [comment] 2018-01-24 17:51
my thoughts: let's get a config option that works for k8s and HA Mixer, and then we can figure out how we want to generate configs (or otherwise) for different Mixer deployment environments. A separate updater agent may be the best to provide as an add-on for other environments, or maybe just auto-generating the config for Prometheus is enough.

**Comment by douglas-reid** [comment] 2018-06-13 21:30
I believe that we can close this issue now. Adding service discovery for other environments can be handled in separate issues per environment.

**Closed by douglas-reid** 2018-06-13 21:30 UTC
Labels: area/policies and telemetry
