### ISSUE TITLE
Fluentd 记录日志 error_class=MessagePack::UnknownExtTypeError error="unexpected extension type

### ISSUE THREAD

**Issue by shancang** [istio/istio#14479] opened 2019-05-31 15:16 UTC
[x] Policies and Telemetry
根据官方文档，https://istio.io/zh/docs/tasks/telemetry/logs/fluentd/  deployment。
报错如下：
  2019-05-31 15:04:52 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-05-31 15:06:52 +0000 [error]: #0 unexpected error on reading data host="10.42.5.106" port=59140 error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2019-05-31 15:06:52 +0000 [error]: #0 suppressed same stacktrace
2019-05-31 15:07:52 +0000 [error]: #0 unexpected error on reading data host="10.42.5.106" port=33416 error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2019-05-31 15:07:52 +0000 [error]: #0 suppressed same stacktrace
2019-05-31 15:08:52 +0000 [error]: #0 unexpected error on reading data host="10.42.5.106" port=35906 error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by douglas-reid** [comment] 2019-05-31 18:13
I don't know what the issue is from this description, but it does appear that the `zh` lang docs are missing recent updates. One of those missing updates is a WARNING:

```
If you use Istio 1.1.2 or prior, please use the following configuration instead:
kubectl apply -f samples/bookinfo/telemetry/fluentd-istio-crd.yaml
```

I'm going to close this, pending more information. Please re-open if the issue persists and more detail is available to provide.

**Closed by douglas-reid** 2019-05-31 18:13 UTC
Labels: area/policies and telemetry, kind/customer issue

**Comment by shancang** [comment] 2019-06-01 00:53
谢谢
