### ISSUE TITLE
Create real e2e test for operator controller

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21468] opened 2020-02-25 17:08 UTC
The current controller test TestIOPController_SwitchProfile is more of a unit test in the sense that it stubs out any external components like the k8s API server and just tests the controller code itself. 
We need a real e2e test which interacts with a real cluster. It can be as simple as installing the controller, running bookinfo, changing profile and check for errors, re-run bookinfo.

**Comment by sdake** [comment] 2020-02-25 21:39
sounds good to me. This is a duplicate of https://github.com/istio/istio/issues/21069. I will close 21069 as @irisdingbj is unavailable to do the rework.

This is a test regression from 1.4 which included e2e tests pretty much as you describe here: https://github.com/istio/operator/blob/master/Makefile.core.mk#L90-L91. Unfortunately, as e2e has been deprecated, there is no simple answer to this regression for the 1.5 operator test cases.

Cheers
-steve

**Comment by sdake** [comment] 2020-02-25 21:42
The rationale for why this is needed is explained in more detail in this thread in github: https://github.com/istio/istio/issues/21063#issuecomment-589877940

**Comment by richardwxn** [comment] 2020-02-27 00:35
I will start working on this after fixing the existing bugs

**Comment by ostromart** [comment] 2020-02-27 19:58
I think there's already a test in istio/operator that just wasn't ported over.

**Comment by ostromart** [comment] 2020-02-27 21:31
See https://github.com/istio/istio/issues/21063#issuecomment-589879234

**Comment by ostromart** [comment] 2020-03-06 00:57
Actually I take it back - that test doesn't use the controller and it's also a bash script. It should be using the new test framework. Looking around there a bit I propose creating an alternative deploy() function that uses the controller instead of manifest apply here:
https://github.com/istio/istio/blob/44faef2d3fd9f2945c3d753fb9b3e01774fd9d12/pkg/test/framework/components/istio/operator.go#L150
The trick is how to reference the controller image ($HUB:$TAG should work?)

**Closed** 2020-04-22 18:23 UTC
Labels: area/environments/operator, lifecycle/needs-escalation
