### ISSUE TITLE
Split-horizon EDS deployment fails to resolve remote service name.

### ISSUE THREAD

**Issue by dkushner** [istio/istio#15341] opened 2019-07-03 20:02 UTC
**Bug description**

In a split-horizon EDS deployment (as documented under the cluster-aware service routing), with a three-cluster configuration, I am unable to resolve any service in the mesh from the remote by internal host name (`service.somewhere.svc.cluster.local`). The gateway correctly forwards inbound traffic to services in the remote clusters but none of the remotes are able to resolve any services by name. 

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

With split-horizon EDS I would expect to be able to resolve any service in the mesh from any pod with a mounted `istio-proxy` sidecar. Given that this installation type leverages a single control plane (i.e. each node in the mesh shares the same pilot instance) I would expect that every proxy sidecar maintained the same endpoint configuration. I have confirmed that this is the case by using the `istioctl proxy-config endpoints` utility on pods in one of the remote clusters. 

Next, I would expect that pods in the mesh would leverage these distributed endpoint configurations to resolve services in remote clusters by via FQDN or short-name (i.e. `service.remotens.svc.cluster.local` or `service.remotens`). Neither of these names are resolvable from any node in the mesh. However, the gateway in the control plane cluster _does_ appear to be able to correctly forward traffic to services in the remote. 

**Steps to reproduce the bug**

1.  Create a multi-cluster installation of Istio using the split-horizon EDS configuration method for cluster-aware routing. 
2.  Install a service and accompanying virtual-service definition in the primary, control-plane cluster (`service-a`) in a given namespace (`namespace-a`).
3. Install a service in the remote cluster (`service-b`) in a given namespace (`namespace-b`) and create an accompany VirtualService definition in the control-plane cluster. 
4. Attempt to resolve `service-a.namespace-a.svc.cluster.local` from any pod of `service-b` and note that the resolution fails.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
citadel version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
galley version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
ingressgateway version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean", GitTag:"1.1.6"}
pilot version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
pilot version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
pilot version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
pilot version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
pilot version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
policy version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
sidecar-injector version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
telemetry version: version.BuildInfo{Version:"release-1.1-20190514-09-15", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"e7fd30c9-7628-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
```

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-21T13:09:06Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.10", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-06-19T20:11:19Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm chart, following the instructions contained in the [cluster-aware service routing documentation](https://istio.io/docs/tasks/multicluster/split-horizon-eds/). 

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by ericvn** [comment] 2019-07-16 17:30
@vadimeisenbergibm Would you be able to provide any guidance on this one? If I understand this one correctly, Kubernetes doesn't know about a service since it exists in another cluster so it can't resolve the host and we never even get the request into the service mesh. If a service exists in all the clusters, things are OK, but if a service exists in a subset, it can't be called from outside that subset. Is there a way to make the subsetted service resolvable across all the clusters?

In the documentation we use the _helloworld_ app in the _sample_ namespace in each cluster so Kubernetes can find the service within each cluster, and then the mesh can route between instances. If I have a _helloworld-b_ service in _sample-b_ in cluster 2 for example, Kubernetes can resolve both _helloworld_ and _helloworld-b_ within cluster 2 so things work normally within the cluster. However, Kubernetes can't resolve _helloworld-b_ within cluster 1, so we get back a failure before things reach the mesh.

**Comment by vadimeisenbergibm** [comment] 2019-07-17 02:04
@dkushner @eric4545 This is by design. You have to create a selector-less Kubernetes service in the cluster that does not have the equivalent of the remote service and from which you want to call to remote service. See https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors. Provide it an Endpoint with the ip address of the remote gateway. I did not try it, I think it should work.

**Comment by ericvn** [comment] 2019-07-17 18:57
Thanks @vadime. I was able to get this to work in my test environment using:
```
apiVersion: v1
kind: Service
metadata:
  name: helloworld-b
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: helloworld-b
subsets:
  - addresses:
      - ip: 169.55.89.66
    ports:
      - port: 5000
```
My test env was basically setting up the example SH two clusters, then creating in the remote cluster a second _sample-b_ namespace and running in it a _helloworld-b_ and _sleep_ pod similar to the _sample_ namespace. 

Before applying the above yaml to the _sample-b_ namespace in cluster one, I would see the unresolved error trying to curl from the _sample/sleep_ to helloworld-b.sample-b:5000/hello.  After applying the yaml, I get back the desired response.

**Comment by ericvn** [comment] 2019-07-22 13:18
Since @vadimeisenbergibm says this is by design and provided a work-around which I verified in my scenario, I will close this issue. If you think this was in error, please re-open the issue and we can look into this some more.

**Closed by ericvn** 2019-07-22 13:18 UTC
Labels: area/config, area/networking, area/user experience, kind/need more info
