### ISSUE TITLE
TestTCPMixerFilterPeriodicalReport is flaky and often fails

### ISSUE THREAD

**Issue by hklai** [istio/istio#8283] opened 2018-08-27 21:21 UTC
**Describe the bug**
TestTCPMixerFilterPeriodicalReport has become flaky and fails more often than not in Prow.

According to https://k8s-testgrid.appspot.com/istio-postsubmits#postsubmit, the trend seems to have started since https://github.com/istio/istio/commit/5c3a283ad96010007ead9f34b9a7905988bfbadb

**Expected behavior**
No flake

**Steps to reproduce the bug**
N/A

**Version**
N/A

**Is Istio Auth enabled or not?**
N/A

**Environment**
N/A

**Cluster state**
N/A

**Comment by kyessenov** [comment] 2018-08-27 21:26
Dupe of https://github.com/istio/istio/issues/8133, which seems to be closed too soon.

**Comment by nmittler** [comment] 2018-08-27 21:33
Re-opened #8133 ... closing this as a dup.

**Closed by nmittler** 2018-08-27 21:33 UTC
Labels: area/policies and telemetry, kind/test failure
