### ISSUE TITLE
istioctl for multicluster

### ISSUE THREAD

**Issue by clyang82** [istio/istio#16761] opened 2019-09-03 02:59 UTC
follow this guide to install istio multicluster - https://preliminary.istio.io/docs/examples/multicluster/icp/. after done, run `cloudctl ps` in cluster1, it can list `review-v3` which is in cluster-2. 
```
NAME                                                   CDS                            LDS                            EDS        RDS          PILOT                            VERSION
details-v1-68fbb76fc-xm9dw.default                     STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-tmv2x     1.3.0-rc.1
istio-egressgateway-75cbf7445d-pqrfg.istio-system      SYNCED                         SYNCED                         SYNCED     NOT SENT     istio-pilot-85dd8f5755-tmv2x     1.3.0-rc.1
istio-ingressgateway-5cdbc4cdf5-99r82.istio-system     SYNCED                         SYNCED                         SYNCED     SYNCED       istio-pilot-85dd8f5755-tmv2x     1.3.0-rc.1
productpage-v1-6c6c87ffff-7zxdd.default                STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-tmv2x     1.3.0-rc.1
ratings-v1-7bdfd65ccc-7qzr9.default                    STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-tmv2x     1.3.0-rc.1
reviews-v1-5c5b7b9f8d-l8d7l.default                    STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-tmv2x     1.3.0-rc.1
reviews-v2-569796655b-cjcxd.default                    STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-tmv2x     1.3.0-rc.1
reviews-v3-59cb5dbbcd-dcrgb.default                    SYNCED                         SYNCED                         SYNCED     SYNCED       istio-pilot-85dd8f5755-tmv2x     1.3.0-rc.1
```

when run `istioctl ps reviews-v3-59cb5dbbcd-dcrgb.default `, the output is 
```
root@cyang1:~/istio-1.3.0-rc.1# istioctl ps reviews-v3-59cb5dbbcd-dcrgb.default
Error: unable to retrieve proxy container name: unable to retrieve Pod: pods "reviews-v3-59cb5dbbcd-dcrgb" not found
```

**Comment by esnible** [comment] 2019-09-03 19:21
Duplicate of https://github.com/istio/istio/issues/12501

**Closed by esnible** 2019-09-03 19:21 UTC
Labels: area/user experience
