### ISSUE TITLE
Upgrading from 1.7.0 to  1.8.0-alpha.0 failed

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#28189] opened 2020-10-22 13:15 UTC
I am using canary upgrade according to official doc.

But it failed waiting for ingress gateway with this error 

```
2020-10-22T12:51:42.053822Z	warn	ads	ADS:LDS: ACK ERROR router~10.244.0.33~istio-ingressgateway-846f77dc5f-rbmnk.istio-system~istio-system.svc.cluster.local-1 Internal:Error adding/updating listener(s) 0.0.0.0_8080: Proto constraint validation failed (HttpConnectionManagerValidationError.HttpFilters[i]: ["embedded message failed validation"] | caused by HttpFilterValidationError.Name: ["value length must be at least " '\x01' " runes"]): stat_prefix: "outbound_0.0.0.0_8080"
rds {
  config_source {
    ads {
    }
    resource_api_version: V3
  }
  route_config_name: "http.80"
}
http_filters {
}
http_filters {
  name: "envoy.filters.http.cors"
  typed_config {
    [type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors] {
    }
  }
}
http_filters {
  name: "envoy.filters.http.fault"
  typed_config {
    [type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault] {
    }
  }
}
http_filters {
}
http_filters {
  name: "envoy.filters.http.router"
  typed_config {
    [type.googleapis.com/envoy.extensions.filters.http.router.v3.Router] {
    }
  }
}
tracing {
  client_sampling {
    value: 100
  }
  random_sampling {
    value: 1
  }
  overall_sampling {
    value: 100
  }
}
http_protocol_options {
}
server_name: "istio-envoy"
access_log {
  name: "envoy.access_loggers.file"
  typed_config {
    [type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog] {
      path: "/dev/stdout"
      log_format {
        text_format: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
      }
    }
  }
}
use_remote_address {
  value: true
}
forward_client_cert_details: SANITIZE_SET
set_current_client_cert_details {
  subject {
    value: true
  }
  cert: true
  dns: true
  uri: true
}
upgrade_configs {
  upgrade_type: "websocket"
}
stream_idle_timeout {
}
normalize_path {
  value: true
}

```

I have httpbin deployed before and with `samples/httpbin/httpbin-gateway.yaml` applied.

**Comment by howardjohn** [comment] 2020-10-22 14:25
Weird, injecting empty http filters. I saw this once before but I forget why

**Comment by hzxuzhonghu** [comment] 2020-10-23 01:40
The empty httpfilter should be `istio.metadata_exchange` and "istio.stats" compared with the 1.7 listener. @bianpengyuan Any idea?

**Comment by bianpengyuan** [comment] 2020-10-23 03:08
I tried canary upgrade but cannot reproduce. Stats filters are working correctly for me with canary control planes.

**Comment by kyessenov** [comment] 2020-10-23 03:59
Maybe it's xDS proxy? The proto format changed between 1.7 and 1.8/

**Comment by howardjohn** [comment] 2020-10-23 04:11
is the nack from 1.7 proxy or 1.8 proxy?

**Comment by bianpengyuan** [comment] 2020-10-23 16:46
This is marked as a release blocker, @hzxuzhonghu Assign this to you to get more info.

**Comment by hzxuzhonghu** [comment] 2020-10-26 02:12
Let me reproduce it today

**Comment by hzxuzhonghu** [comment] 2020-10-26 02:12
>is the nack from 1.7 proxy or 1.8 proxy?

It is the nack from the 1.8 ingress gateway

**Comment by hzxuzhonghu** [comment] 2020-10-26 06:46
I can reproduce it easily:

First: install 1.7.3 with default profile

2. install httpbin from sample  `httpbin.yaml` and `httpbin-gateway.yaml`

3.  install canary release from 1.8.0-alpha `./bin/istioctl install --set revision=canary`


```
 ./bin/istioctl  install --set revision=canary
This will install the Istio profile into the cluster. Proceed? (y/N) y
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/v1.8/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed                                                                                                                                                                       
✔ Istiod installed                                                                                                                                                                           
- Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-ingressgateway                                                                                        

- Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-ingressgateway                                                                                        
✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition                                                    
Deployment/istio-system/istio-ingressgateway        
- Pruning removed resources                                                                                                                                                                  Error: failed to install manifests: errors occurred during operation

```

And i found the ingress gateway never get ready, an interesting point is that the envoyfilter installed it not right

```
 k get envoyfilter -n istio-system metadata-exchange-1.8-canary  -oyaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"EnvoyFilter","metadata":{"annotations":{},"labels":{"install.operator.istio.io/owning-resource":"unknown","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"canary","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.8.0-alpha.0"},"name":"metadata-exchange-1.8-canary","namespace":"istio-system"},"spec":{"configPatches":[{"applyTo":"HTTP_FILTER","match":{"context":"SIDECAR_INBOUND","listener":{"filterChain":{"filter":{"name":"envoy.http_connection_manager"}}},"proxy":{"proxyVersion":"^1\\.8.*"}},"patch":{"operation":"INSERT_BEFORE","value":{"name":"istio.metadata_exchange","typed_config":{"@type":"type.googleapis.com/udpa.type.v1.TypedStruct","type_url":"type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm","value":{"config":{"configuration":{"@type":"type.googleapis.com/google.protobuf.StringValue","value":"{}\n"},"vm_config":{"code":{"local":{"inline_string":"envoy.wasm.metadata_exchange"}},"runtime":"envoy.wasm.runtime.null"}}}}}}},{"applyTo":"HTTP_FILTER","match":{"context":"SIDECAR_OUTBOUND","listener":{"filterChain":{"filter":{"name":"envoy.http_connection_manager"}}},"proxy":{"proxyVersion":"^1\\.8.*"}},"patch":{"operation":"INSERT_BEFORE","value":{"name":"istio.metadata_exchange","typed_config":{"@type":"type.googleapis.com/udpa.type.v1.TypedStruct","type_url":"type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm","value":{"config":{"configuration":{"@type":"type.googleapis.com/google.protobuf.StringValue","value":"{}\n"},"vm_config":{"code":{"local":{"inline_string":"envoy.wasm.metadata_exchange"}},"runtime":"envoy.wasm.runtime.null"}}}}}}},{"applyTo":"HTTP_FILTER","match":{"context":"GATEWAY","listener":{"filterChain":{"filter":{"name":"envoy.http_connection_manager"}}},"proxy":{"proxyVersion":"^1\\.8.*"}},"patch":{"operation":"INSERT_BEFORE","value":{"name":"istio.metadata_exchange","typed_config":{"@type":"type.googleapis.com/udpa.type.v1.TypedStruct","type_url":"type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm","value":{"config":{"configuration":{"@type":"type.googleapis.com/google.protobuf.StringValue","value":"{}\n"},"vm_config":{"code":{"local":{"inline_string":"envoy.wasm.metadata_exchange"}},"runtime":"envoy.wasm.runtime.null"}}}}}}}]}}
  creationTimestamp: "2020-10-26T06:35:00Z"
  generation: 1
  labels:
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: canary
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.0-alpha.0
  managedFields:
       *
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
      proxy:
        proxyVersion: ^1\.8.*
    patch:
      operation: INSERT_BEFORE
      value: {}
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
      proxy:
        proxyVersion: ^1\.8.*
    patch:
      operation: INSERT_BEFORE
      value: {}
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
      proxy:
        proxyVersion: ^1\.8.*
    patch:
      operation: INSERT_BEFORE
      value: {}

```


As we can see the value is empty, so that the root cause. Maybe has releated to https://github.com/istio/istio/issues/28189#issuecomment-714894313.

**Comment by hzxuzhonghu** [comment] 2020-10-26 06:46
Anyone want to take a look in my env, PLMK.

**Comment by bianpengyuan** [comment] 2020-10-26 16:24
The canary mx filter installed in my cluster is correct. Can you generate the manifest and check if it is correct?

**Comment by hzxuzhonghu** [comment] 2020-10-27 01:54
all right, i can not reproduce now. The envoyfilters in the generated manifest are all correct.

**Comment by bianpengyuan** [comment] 2020-10-27 02:00
@hzxuzhonghu Any idea what might change? It is even more concerning if the installed resource is non-deterministic..

**Comment by howardjohn** [comment] 2020-10-28 22:50
@nmittler got basically the same

**Comment by hzxuzhonghu** [comment] 2020-10-29 02:09
Yes, that's why i file https://github.com/istio/istio/pull/28298 Not sure which component changed all the envoyfilters.

**Comment by bianpengyuan** [comment] 2020-10-29 16:21
I can reproduce this with KinD, but not GKE.

**Comment by bianpengyuan** [comment] 2020-10-29 19:15
Some findings:
* Use official 1.8 istioctl (which has server side apply) install canary, all envoyfilters are rewritten with empty value, including the ones installed by 1.7 istioctl. and from now on, any installation of envoyfilter will be override with empty value, even clean up the istio-system namespace.
* Use an customzied istioctl which does not have server side apply install canary, everything works fine.

**Comment by richardwxn** [comment] 2020-10-29 19:20
taking a look, but still not sure why it happen only on Kind but not GKE though

**Comment by howardjohn** [comment] 2020-10-29 19:34
CRD pruning may be relevant as well @jasonwzm. I am now remembered when we saw this before, its because we had pruning enabled on the CRD. Sounds like its the serverside apply, but probably relevant

**Comment by jasonwzm** [comment] 2020-10-29 22:17
@howardjohn EnvoyFilter should allow any fields thus should not prune unknown fields.

**Comment by richardwxn** [comment] 2020-10-30 02:58
Updates:
1. the issue can happen on GKE as well, but just 1.18, cannot reproduce it on 1.17/1.16. It is suspicious that related to the beta2 change launched with k8s 1.18
2. the CRD managedFields look suspicious so CRD probably should not be applied with server-side apply as it may collide with controller-manager or api-server and also it might not be necessary

Will create a PR to exclude the CRDs from the list

**Closed** 2020-10-30 20:04 UTC
Labels: area/environments/operator, area/networking
