### ISSUE TITLE
Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration on fresh installation

### ISSUE THREAD

**Issue by gganssauge** [istio/istio#42945] opened 2023-01-23 12:08 UTC
We are installing istio (tried 1.15.3 as well as 1.16.1) on a freshly created kubernetes-1.25.4 cluster on Azure AKS.

The installation runs with the following steps:

```text
[2023-01-23T11:37:16.308Z] + /tmp/istioctl manifest generate --set profile=default --set spec.values.global.defaultNodeSelector.stack=monitoring --set spec.values.telemetry.v2.prometheus.enabled=true
[2023-01-23T11:37:16.563Z] + /tmp/istioctl manifest install --skip-confirmation --set profile=default --set spec.values.global.defaultNodeSelector.stack=monitoring --set spec.values.telemetry.v2.prometheus.enabled=true
[2023-01-23T11:37:17.921Z] 
[2023-01-23T11:37:22.076Z] - Processing resources for Istio core.
[2023-01-23T11:37:22.076Z] ✔ Istio core installed
[2023-01-23T11:37:23.962Z] - Processing resources for Istiod.
[2023-01-23T11:37:30.490Z] - Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
[2023-01-23T11:37:30.490Z] ✔ Istiod installed
[2023-01-23T11:37:30.490Z] - Processing resources for Ingress gateways.
[2023-01-23T11:37:37.018Z] - Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-ingressgat...
[2023-01-23T11:37:37.018Z] ✔ Ingress gateways installed
[2023-01-23T11:37:38.904Z] - Pruning removed resources
[2023-01-23T11:37:39.162Z] ✔ Installation completeMaking this installation the default for injection and validation.
[2023-01-23T11:37:41.050Z] 
[2023-01-23T11:37:41.050Z] Thank you for installing Istio 1.16.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/99uiMML96AmsXY5d6
[2023-01-23T11:37:41.306Z] + progress '>> Verify istio installation ...'
[2023-01-23T11:37:41.306Z] + echo '>> Verify istio installation ...'
[2023-01-23T11:37:41.306Z] + export NAMESPACE=istio-system
[2023-01-23T11:37:41.306Z] + NAMESPACE=istio-system
[2023-01-23T11:37:41.306Z] >> Verify istio installation ...
[2023-01-23T11:37:41.306Z] + /tmp/istioctl verify-install -f generated-manifest.yaml
[2023-01-23T11:37:41.562Z] ✔ CustomResourceDefinition: authorizationpolicies.security.istio.io.istio-system checked successfully

... lots of checks - all successful

[2023-01-23T11:37:45.760Z] ✔ Deployment: istiod.istio-system checked successfully
[2023-01-23T11:37:45.760Z] Error: Istio installation failed
[2023-01-23T11:37:45.760Z] Checked 15 custom resource definitions
[2023-01-23T11:37:45.760Z] Checked 2 Istio Deployments
```

The istiod pod logs the following error message (those are the only messages with severity error)

```text
2023-01-23T11:37:41.018800Z	error	validationController	Failed to update validatingwebhookconfiguration istiod-default-validator (failurePolicy=Fail, resourceVersion=4369): Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io "istiod-default-validator": the object has been modified; please apply your changes to the latest version and try again
2023-01-23T11:37:41.018845Z	error	klog	Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io "istiod-default-validator": the object has been modified; please apply your changes to the latest version and try again
```

The same script works on kubernetes-1.24 with istio-1.15.3 since months without a single problem - in that case there are no error messages in the istiod log.

Can I do anything to
1. make it work, or
2. to help you identify the problem

???

**Comment by howardjohn** [comment] 2023-01-24 00:30
That error is likely transient unless its constantly looping, due to fighting between replicas. it may not be a concern if its only logged a couple of times

**Comment by gganssauge** [comment] 2023-01-24 08:25
True.
It is only a message - but it prevents completion of the installation.

I cannot install istio on k8s-1.25, consistently - and that message is the only indication at something going wrong :(

**Comment by howardjohn** [comment] 2023-01-24 17:45
I wonder if its just an `istioctl verify-install` false negative. What is
the full output of that?

Everything seems healthy.

**Comment by gganssauge** [comment] 2023-01-25 11:42
Here is the complete log from the installation on our build server:

[istio-install-fail.log](https://github.com/istio/istio/files/10498914/istio-install-fail.log)

**Comment by gganssauge** [comment] 2023-01-25 11:44
If it helps I can send also successful installations on kubernetes 1.24.
To me that seems the only variation in the process.

**Comment by howardjohn** [comment] 2023-01-25 15:35
I think its just a bug in `verify-install`, which also happens to not be logging the error for some reason. I don't think there isanything wrong with the actual install

**Comment by gganssauge** [comment] 2023-01-25 18:14
Hmmm, thanks.
My feelings are a bit mixed towards omitting the verification step. For the moment it would not a problem, the installation with k8s-1.25 is experimental, anyway.
Although we never had it fail, before, it kind of promises some safety; a promise it obviously can't hold :(

Is there any hope that it may be fixed in one of the following releases?
Can I help to debug the problem?
I certainly would run debug versions of the validator on our cluster if that could help.

**Comment by howardjohn** [comment] 2023-01-25 18:16
It appears we get an error but dont report it. The best way would be to modify https://github.com/istio/istio/blob/373fc89518c986c9f48ed3cd891930da6fdc8628/istioctl/pkg/verifier/verifier.go#L445 to include `err` (`return fmt.Errorf("Istio installation failed: %v",  err)` then run (`go run ./istioctl/cmd/istioctl ..`) and see the result.

of course we should also fix the tool properly, but that will at least say what the error is for debugging

**Comment by gganssauge** [comment] 2023-01-25 18:19
I will give it a try - never tried to build anything in istio myself.

But "Wer nicht wagt, der nicht gewinnt" (old german saying, meaning "nothing ventured, nothing gained" :)

**Comment by gganssauge** [comment] 2023-01-26 09:52
I did it 😄 

Wasn't that difficult, after all - I just had to follow the instructions which were pretty good.

The result is attached.

The error message was
```text
Error: Istio installation failed: resource mapping not found for name: "istio-ingressgateway" namespace: "istio-system" from "generated-manifest.yaml": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```
You probably know what that means - and why that mapping was obviously present in kubernetes 1.24 and is not anymore with 1.25.

**Comment by gganssauge** [comment] 2023-01-26 09:53
[verify.log](https://github.com/istio/istio/files/10508086/verify.log)

**Comment by gganssauge** [comment] 2023-01-26 10:11
Could have to do with PodDisruptionBudget in policy/v1 since kubernetes-1.25 whereas the generated-manifest still has it in policy/v1beta.
[generated-manifest.zip](https://github.com/istio/istio/files/10508211/generated-manifest.zip)

Is there a switch, maybe, to istioctl to change that?

**Comment by gganssauge** [comment] 2023-01-26 10:24
On the cluster there are no PodDisruptionPolicies defined, indeed - whereas in 1.24 there are.

**Comment by gganssauge** [comment] 2023-01-26 12:27
I tried to fix the generated-manifest.yaml with sed -e 's,policy/v1beta1,policy/v1,g' and that fixed the problem with the installation failing.
The PodDisruptionBudgets where not created, though.

**Comment by hanxiaop** [comment] 2023-01-28 07:53
The cause is https://github.com/istio/istio/pull/42513 didn't get cherry-picked. `istioctl manifest generate` will generate `policy/v1beta1` manifests. I'm going to do the cherry-pick. Instead of waiting for the new release, you may try `istioctl manifest generate --cluster-specific` to generate the correct manifests for 1.25

**Comment by keithmattix** [comment] 2023-02-15 15:01
Now that the cherrypick was merged, can this be closed?

**Closed** 2023-02-15 15:02 UTC
Labels: area/user experience, community/intern-help-wanted

**Comment by robertofabrizi** [comment] 2023-03-28 07:32
I tried to install istio 1.17.1 but failed due to PodDisruptionBudgets being removed from kubernetes 1.25, is the fix included in a future release?
