### ISSUE TITLE
A lots of  ERROR after istio 0.4 installed

### ISSUE THREAD

**Issue by smashpunk** [istio/istio#2667] opened 2018-01-18 08:13 UTC
According to quick start, just install istio 0.4 on kubernetes, all pod is up. But, the logs shows istio componets connect pilot timeout. Is it normal?

**platform**: Kubernetes 1.8, with RBAC enable
**command**:
`kubectl logs istio-pilot-55bb7f5d9d-lq9gg -c istio-proxy -n istio-system`
**output**:
```
ERROR: logging before flag.Parse: I0118 07:48:30.643689       1 main.go:70] Version root@cc5c34bbd1ee-0.4.0-24089ea97c8d244493c93b499a666ddf4010b547-dirty
ERROR: logging before flag.Parse: I0118 07:49:00.689926       1 main.go:114] Error retrieving availability zone from pilot: Get http://istio-pilot:15003/v1/az/istio-proxy/pilot~~.~.svc.cluster.local: dial tcp 10.110.16.48:15003: i/o timeout
ERROR: logging before flag.Parse: I0118 07:49:00.690734       1 main.go:124] Proxy role: proxy.Node{Type:"pilot", IPAddress:"", ID:".", Domain:".svc.cluster.local"}
ERROR: logging before flag.Parse: I0118 07:49:00.694897       1 main.go:184] Effective config: binaryPath: /usr/local/bin/envoy
configPath: /etc/istio/proxy
connectTimeout: 1.000s
customConfigFile: /etc/istio/proxy/envoy_pilot.json
discoveryAddress: istio-pilot:15003
discoveryRefreshDelay: 1.000s
drainDuration: 2.000s
parentShutdownDuration: 3.000s
proxyAdminPort: 15000
serviceCluster: istio-proxy
ERROR: logging before flag.Parse: I0118 07:49:00.699242       1 main.go:201] Monitored certs: []envoy.CertSource{envoy.CertSource{Directory:"/etc/certs/", Files:[]string{"cert-chain.pem", "key.pem", "root-cert.pem"}}}
ERROR: logging before flag.Parse: I0118 07:49:00.705667       1 agent.go:164] Starting proxy agent
ERROR: logging before flag.Parse: I0118 07:49:00.705943       1 agent.go:186] Received new config, resetting budget
ERROR: logging before flag.Parse: I0118 07:49:00.706038       1 agent.go:261] Reconciling configuration (budget 10)
ERROR: logging before flag.Parse: I0118 07:49:00.706294       1 agent.go:281] Epoch 0 starting
ERROR: logging before flag.Parse: I0118 07:49:00.706431       1 watcher.go:270] Envoy command: [-c /etc/istio/proxy/envoy_pilot.json --restart-epoch 0 --drain-time-s 2 --parent-shutdown-time-s 3 --service-cluster istio-proxy --service-node pilot~~.~.svc.cluster.local --max-obj-name-len 189]
[2018-01-18 07:49:00.906][10][warning][main] external/envoy/source/server/server.cc:157] initializing epoch 0 (hot restart version=9.200.16384.256)
[2018-01-18 07:49:01.273][10][warning][main] external/envoy/source/server/server.cc:328] all clusters initialized. initializing init manager
[2018-01-18 07:49:01.274][10][warning][config] external/envoy/source/server/listener_manager_impl.cc:448] all dependencies initialized. starting workers
[2018-01-18 07:49:01.275][10][warning][main] external/envoy/source/server/server.cc:344] starting main dispatch loop
[2018-01-18 07:49:04.275][10][warning][main] external/envoy/source/server/drain_manager_impl.cc:62] shutting down parent after drain
ERROR: logging before flag.Parse: I0118 07:49:50.602521       1 watcher.go:123] watchFileEvents: "/etc/certs//..1981_18_01_15_49_50.870420508": CREATE
ERROR: logging before flag.Parse: I0118 07:49:50.603720       1 watcher.go:123] watchFileEvents: "/etc/certs//..1981_18_01_15_49_50.870420508": MODIFY|ATTRIB
ERROR: logging before flag.Parse: I0118 07:49:50.603765       1 watcher.go:123] watchFileEvents: "/etc/certs//key.pem": CREATE
ERROR: logging before flag.Parse: I0118 07:49:50.603810       1 watcher.go:123] watchFileEvents: "/etc/certs//root-cert.pem": CREATE
ERROR: logging before flag.Parse: I0118 07:49:50.603819       1 watcher.go:123] watchFileEvents: "/etc/certs//cert-chain.pem": CREATE
ERROR: logging before flag.Parse: I0118 07:49:50.603826       1 watcher.go:123] watchFileEvents: "/etc/certs//..data_tmp": RENAME
ERROR: logging before flag.Parse: I0118 07:49:50.604304       1 watcher.go:123] watchFileEvents: "/etc/certs//..data": CREATE
ERROR: logging before flag.Parse: I0118 07:50:00.603833       1 watcher.go:136] watchFileEvents: notifying
ERROR: logging before flag.Parse: I0118 07:50:00.607295       1 agent.go:186] Received new config, resetting budget
ERROR: logging before flag.Parse: I0118 07:50:00.607370       1 agent.go:261] Reconciling configuration (budget 10)
ERROR: logging before flag.Parse: I0118 07:50:00.608358       1 agent.go:281] Epoch 1 starting
ERROR: logging before flag.Parse: I0118 07:50:00.608450       1 watcher.go:270] Envoy command: [-c /etc/istio/proxy/envoy_pilot.json --restart-epoch 1 --drain-time-s 2 --parent-shutdown-time-s 3 --service-cluster istio-proxy --service-node pilot~~.~.svc.cluster.local --max-obj-name-len 189]
[2018-01-18 07:50:00.747][15][warning][main] external/envoy/source/server/server.cc:157] initializing epoch 1 (hot restart version=9.200.16384.256)
[2018-01-18 07:50:00.763][10][warning][main] external/envoy/source/server/server.cc:381] shutting down admin due to child startup
[2018-01-18 07:50:00.764][10][warning][main] external/envoy/source/server/server.cc:386] terminating parent process
[2018-01-18 07:50:00.881][15][warning][main] external/envoy/source/server/server.cc:328] all clusters initialized. initializing init manager
[2018-01-18 07:50:00.885][15][warning][config] external/envoy/source/server/listener_manager_impl.cc:448] all dependencies initialized. starting workers
[2018-01-18 07:50:00.885][10][warning][main] external/envoy/source/server/server.cc:91] closing and draining listeners
[2018-01-18 07:50:00.885][15][warning][main] external/envoy/source/server/server.cc:344] starting main dispatch loop
[2018-01-18 07:50:03.885][15][warning][main] external/envoy/source/server/drain_manager_impl.cc:62] shutting down parent after drain
[2018-01-18 07:50:03.886][10][warning][main] external/envoy/source/server/hot_restart_impl.cc:420] shutting down due to child request
[2018-01-18 07:50:03.886][10][warning][main] external/envoy/source/server/server.cc:303] caught SIGTERM
[2018-01-18 07:50:03.886][10][warning][main] external/envoy/source/server/server.cc:348] main dispatch loop exited
[2018-01-18 07:50:03.887][10][warning][main] external/envoy/source/server/server.cc:369] exiting
ERROR: logging before flag.Parse: I0118 07:50:03.899100       1 agent.go:211] Epoch 0 exited normally
ERROR: logging before flag.Parse: W0118 07:50:03.899215       1 watcher.go:300] Failed to delete config file /etc/istio/proxy/envoy-rev0.json for 0, remove /etc/istio/proxy/envoy-rev0.json: no such file or directory

```

**Comment by zhuwenjie11** [comment] 2018-01-27 18:34
I also have the same problem. Do anyone know what the problem is?

**Comment by idevz** [comment] 2018-01-28 13:00
so do I.
```bash
ERROR: logging before flag.Parse: I0128 12:48:39.682601       1 main.go:70] Version root@cc5c34bbd1ee-0.4.0-24089ea97c8d244493c93b499a666ddf4010b547-dirty
ERROR: logging before flag.Parse: I0128 12:48:39.684113       1 main.go:114] Error retrieving availability zone from pilot: Get http://istio-pilot:15003/v1/az/istio-ingress/ingress~~istio-ingress-848655c7dc-2d8sk.istio-system~istio-system.svc.cluster.local: dial tcp 10.96.161.123:15003: getsockopt: connection refused
ERROR: logging before flag.Parse: I0128 12:48:39.684136       1 main.go:124] Proxy role: proxy.Node{Type:"ingress", IPAddress:"", ID:"istio-ingress-848655c7dc-2d8sk.istio-system", Domain:"istio-system.svc.cluster.local"}
ERROR: logging before flag.Parse: I0128 12:48:39.684164       1 resolve.go:35] Attempting to lookup address: istio-mixer
ERROR: logging before flag.Parse: I0128 12:48:39.685193       1 resolve.go:45] Addr resolved to: 10.111.243.167:9125
ERROR: logging before flag.Parse: I0128 12:48:39.685201       1 resolve.go:46] Finished lookup of address: istio-mixer
ERROR: logging before flag.Parse: I0128 12:48:39.685633       1 main.go:184] Effective config: binaryPath: /usr/local/bin/envoy
```

**Comment by GregHanson** [comment] 2018-02-22 19:20
@smashpunk @idevz @zhuwenjie11 are you still seeing this problem in istio version 0.5.1 or later?

**Comment by GregHanson** [comment] 2018-02-27 14:31
closing until issue can be reproduced with istio version 0.5.1 or later

**Closed by GregHanson** 2018-02-27 14:31 UTC
