### ISSUE TITLE
caching not working for ingress, issue with Absence-keys: destination.ip

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3292] opened 2018-02-08 02:41 UTC
Caching doesn't work on mixer checks from ingress

It appears that mixer server receives ingress checks calls without destination.ip (see below) so it puts it into the Absence-keys set yet it seems the mixerclient has it or at least decide to not cache

(related to #3289 which is the slightly longer term issue of not putting unused keys in the bags)

[libprotobuf ERROR external/mixerclient_git/src/check_cache.cc:147] Referenced attributes: Absence-keys: destination.ip, source.uid, target.ip, Exact-keys: context.protocol, destination.service, destination.uid, source.ip, 

The first snippet shows an external request arriving at ingress.
`destination.service == ingress`.

```
2018-02-08T02:35:17.420479Z	debug	Creating bag with attributes: &CompressedAttributes{Words:[35.199.14.248 istio/fortio-0.6.8 /fortio1/echo istio-ingress.istio-system.svc.cluster.local kubernetes://istio-ingress-1242246297-9l7nv.istio-system x-on-behalf-of 104.133.9.85:56019 c57c0d08-abcc-9699-8da6-47f541103871 10.150.0.6 89d46e3bf0062a22 89d46e3bf0062a22;89d46e3bf0062a22;0000000000000000 x-envoy-decorator-operation fortio1-redir],Strings:map[int32]int32{17: -3,18: -1,19: 90,22: 92,25: -2,131: 92,152: -4,154: -5,},Int64S:map[int32]int64{1: 42350,},Doubles:map[int32]float64{},Bools:map[int32]bool{},Timestamps:map[int32]time.Time{24: 2018-02-08 02:35:17.419034042 +0000 UTC,},Durations:map[int32]time.Duration{},Bytes:map[int32][]byte{0: [10 150 0 6],},StringMaps:map[int32]StringMap{15: {map[-12:-13 86:-2 118:113 120:-11 -6:-7 100:92 102:-8 122:135 31:-1 32:90 33:-3 98:-9 121:-10 123:-10]},},}
2018-02-08T02:35:17.420529Z	debug	Dispatching Preprocess Check
2018-02-08T02:35:17.420542Z	debug	Resolve: skipping duplicate namespace istio-system
2018-02-08T02:35:17.420577Z	debug	filterActions: rule kubeattrgenrulerule.rule.istio-system selected ResourceType:{HTTP /Check Report Preprocess}
2018-02-08T02:35:17.420595Z	debug	Resolved (TEMPLATE_VARIETY_ATTRIBUTE_GENERATOR) 1 actions
2018-02-08T02:35:17.420608Z	debug	runAsync {0xc4209bee00 0xc420fb5830 handler.kubernetesenv.istio-system kubernetesenv [0xc420d95710]}
2018-02-08T02:35:17.420642Z	debug	runAsync kubernetes:handler.kubernetesenv.istio-system(kubernetesenv) -> {0xc4209bee00 0xc420fb5830 handler.kubernetesenv.istio-system kubernetesenv [0xc420d95710]}
2018-02-08T02:35:17.420791Z	debug	runAsync kubernetes:handler.kubernetesenv.istio-system(kubernetesenv) <- <nil>
2018-02-08T02:35:17.420860Z	debug	Attributes generated from preprocess phase are ---
destination.labels            : map[istio:ingress pod-template-hash:1242246297]
destination.namespace         : istio-system
destination.service           : istio-ingress.istio-system.svc.cluster.local
destination.serviceAccount    : istio-ingress-service-account
source.ip                     : []
source.labels                 : map[]
source.namespace              : 
source.service                : 
source.serviceAccount         : 

2018-02-08T02:35:17.420913Z	debug	Preprocess Check returned with: OK
2018-02-08T02:35:17.420918Z	debug	Dispatching to main adapters after running processors
2018-02-08T02:35:17.420979Z	debug	Attribute Bag: 
context.protocol              : http
destination.service           : istio-ingress.istio-system.svc.cluster.local
destination.uid               : kubernetes://istio-ingress-1242246297-9l7nv.istio-system
request.headers               : {request.headers map[user-agent:istio/fortio-0.6.8 x-b3-traceid:89d46e3bf0062a22 x-b3-spanid:89d46e3bf0062a22 x-envoy-internal:true x-on-behalf-of:104.133.9.85:56019 x-ot-span-context:89d46e3bf0062a22;89d46e3bf0062a22;0000000000000000 x-envoy-decorator-operation:fortio1-redir x-forwarded-for:10.150.0.6 x-b3-sampled:1 x-forwarded-proto:http x-request-id:c57c0d08-abcc-9699-8da6-47f541103871 :authority:35.199.14.248 :method:GET :path:/fortio1/echo] 0xc42117b2c0}
request.host                  : 35.199.14.248
request.method                : GET
request.path                  : /fortio1/echo
request.scheme                : http
request.time                  : 2018-02-08 02:35:17.419034042 +0000 UTC
request.useragent             : istio/fortio-0.6.8
source.ip                     : [10 150 0 6]
source.port                   : 42350
---
destination.labels            : map[istio:ingress pod-template-hash:1242246297]
destination.namespace         : istio-system
destination.serviceAccount    : istio-ingress-service-account
source.labels                 : map[]
source.namespace              : 
source.service                : 
source.serviceAccount         : 

2018-02-08T02:35:17.420983Z	debug	Dispatching Check
2018-02-08T02:35:17.420990Z	debug	Resolve: skipping duplicate namespace istio-system
2018-02-08T02:35:17.421004Z	debug	Resolved (TEMPLATE_VARIETY_CHECK) 0 actions
2018-02-08T02:35:17.421025Z	debug	Check <nil>
2018-02-08T02:35:17.421033Z	debug	Check returned with ok
```
2nd snippet shows `destination.service = echosrv1`
```
2018-02-08T02:35:17.428343Z	debug	Creating bag with attributes: &CompressedAttributes{Words:[kubernetes://echo-svc-deployment1-101521057-b3x8j.istio c57c0d08-abcc-9699-8da6-47f541103871 10.150.0.6 x-envoy-original-path /fortio1/echo istio/fortio-0.6.8 89d46e3bf0062a22 89d46e3bf0062a22;89d46e3bf0062a22;0000000000000000 /echo x-on-behalf-of 104.133.9.85:56019 35.199.14.248 cluster.local/ns/istio-system/sa/default kubernetes://istio-ingress-1242246297-9l7nv.istio-system echosrv1.istio.svc.cluster.local],Strings:map[int32]int32{3: -14,6: -13,17: -9,18: -12,19: 90,22: 92,25: -6,131: 92,152: -15,154: -1,},Int64S:map[int32]int64{1: 59322,},Doubles:map[int32]float64{},Bools:map[int32]bool{},Timestamps:map[int32]time.Time{24: 2018-02-08 02:35:17.422048029 +0000 UTC,},Durations:map[int32]time.Duration{},Bytes:map[int32][]byte{0: [10 36 1 6],150: [0 0 0 0 0 0 0 0 0 0 255 255 10 36 5 7],},StringMaps:map[int32]StringMap{15: {map[32:90 102:-2 118:113 55:134 31:-12 123:-7 33:-9 100:92 86:-6 120:-8 121:-7 122:135 -10:-11 -4:-5 98:-3]},},}
2018-02-08T02:35:17.428512Z	debug	Dispatching Preprocess Check
2018-02-08T02:35:17.428535Z	debug	filterActions: rule kubeattrgenrulerule.rule.istio-system selected ResourceType:{HTTP /Check Report Preprocess}
2018-02-08T02:35:17.428562Z	debug	Resolved (TEMPLATE_VARIETY_ATTRIBUTE_GENERATOR) 1 actions
2018-02-08T02:35:17.428581Z	debug	runAsync {0xc4209bee00 0xc420fb5830 handler.kubernetesenv.istio-system kubernetesenv [0xc420d95710]}
2018-02-08T02:35:17.428742Z	debug	runAsync kubernetes:handler.kubernetesenv.istio-system(kubernetesenv) -> {0xc4209bee00 0xc420fb5830 handler.kubernetesenv.istio-system kubernetesenv [0xc420d95710]}
2018-02-08T02:35:17.428924Z	debug	runAsync kubernetes:handler.kubernetesenv.istio-system(kubernetesenv) <- <nil>
2018-02-08T02:35:17.429213Z	debug	Attributes generated from preprocess phase are ---
destination.labels            : map[app:echosrv1 pod-template-hash:101521057]
destination.namespace         : istio
destination.service           : echosrv1.istio.svc.cluster.local
destination.serviceAccount    : default
source.ip                     : [10 36 1 6]
source.labels                 : map[istio:ingress pod-template-hash:1242246297]
source.namespace              : istio-system
source.service                : istio-ingress.istio-system.svc.cluster.local
source.serviceAccount         : istio-ingress-service-account

2018-02-08T02:35:17.429292Z	debug	Preprocess Check returned with: OK
2018-02-08T02:35:17.429299Z	debug	Dispatching to main adapters after running processors
2018-02-08T02:35:17.429567Z	debug	Attribute Bag: 
context.protocol              : http
destination.ip                : [0 0 0 0 0 0 0 0 0 0 255 255 10 36 5 7]
destination.service           : echosrv1.istio.svc.cluster.local
destination.uid               : kubernetes://echo-svc-deployment1-101521057-b3x8j.istio
request.headers               : {request.headers map[x-envoy-original-path:/fortio1/echo :method:GET content-length:0 user-agent:istio/fortio-0.6.8 x-ot-span-context:89d46e3bf0062a22;89d46e3bf0062a22;0000000000000000 x-b3-traceid:89d46e3bf0062a22 x-on-behalf-of:104.133.9.85:56019 x-forwarded-for:10.150.0.6 :authority:35.199.14.248 x-b3-spanid:89d46e3bf0062a22 x-forwarded-proto:http x-request-id:c57c0d08-abcc-9699-8da6-47f541103871 x-envoy-internal:true :path:/echo x-b3-sampled:1] 0xc4213a4f00}
request.host                  : 35.199.14.248
request.method                : GET
request.path                  : /echo
request.scheme                : http
request.time                  : 2018-02-08 02:35:17.422048029 +0000 UTC
request.useragent             : istio/fortio-0.6.8
source.ip                     : [10 36 1 6]
source.port                   : 59322
source.uid                    : kubernetes://istio-ingress-1242246297-9l7nv.istio-system
source.user                   : cluster.local/ns/istio-system/sa/default
---
destination.labels            : map[app:echosrv1 pod-template-hash:101521057]
destination.namespace         : istio
destination.serviceAccount    : default
source.labels                 : map[istio:ingress pod-template-hash:1242246297]
source.namespace              : istio-system
source.service                : istio-ingress.istio-system.svc.cluster.local
source.serviceAccount         : istio-ingress-service-account
```

cc @ozevren for your entertainment

**Comment by mandarjog** [comment] 2018-02-26 22:28
@bianpengyuan Please take this one. 
It has three scenarios
1. Caching within mesh. source and dest and both inside mesh
2. Ingress
3. Egress

**Comment by bianpengyuan** [comment] 2018-03-07 02:13
I'm not able to reproduce this issue. Now, both ingress and mixer treat destination IP as a absense-keys:

Logs from Ingress:
```
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:155] Add a new Referenced for check cache: Absence-keys: adapter_template_kubernetes.output.source_labels, adapter_template_kubernetes.output.source_namespace, adapter_template_kubernetes.output.source_pod_ip, adapter_template_kubernetes.output.source_pod_name, adapter_template_kubernetes.output.source_service, adapter_template_kubernetes.output.source_service_account_name, destination.ip, source.uid, target.ip, Exact-keys: context.protocol, destination.service, destination.uid, source.ip, 
```
Logs from Mixer:
```
2018-03-07T01:47:06.623283Z     debug   Creating bag with attributes: &CompressedAttributes{Words:[35.224.46.198 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 /productpage connection.mtls istio-ingress.istio-system.svc.cluster.local kubernetes://istio-ingress-5cf6c449c5-xs8pc.istio-system 1e5c39f8ce75436f;1e5c39f8ce75436f;0000000000000000 x-envoy-decorator-operation default-route en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6 1e5c39f8ce75436f upgrade-insecure-requests 71765ec3-8131-9c26-a7c2-cfcd29b2db04 10.128.0.2 text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8],Strings:map[int32]int32{17: -3,18: -1,19: 90,22: 92,25: -2,131: 92,152: -5,154: -6,},Int64S:map[int32]int64{1: 56809,},Doubles:map[int32]float64{},Bools:map[int32]bool{-4: false,},Timestamps:map[int32]time.Time{24: 2018-03-07 01:47:06.620479478 +0000 UTC,},Durations:map[int32]time.Duration{},Bytes:map[int32][]byte{0: [10 128 0 2],},StringMaps:map[int32]StringMap{15: {map[33:-3 44:-10 86:-2 31:-1 120:-7 122:135 98:-14 100:92 51:116 -12:135 118:113 43:115 121:-11 123:-11 32:90 102:-13 46:-15 -8:-9]},},}
2018-03-07T01:47:06.623488Z     debug   Dispatching Preprocess Check
2018-03-07T01:47:06.623579Z     debug   begin dispatch: destination='kubernetes:handler.kubernetesenv.istio-system(kubernetesenv)'
2018-03-07T01:47:06.623711Z     debug   Attribute 'adapter_template_kubernetes.output.source_service_account_name' not in either global or message dictionaries
2018-03-07T01:47:06.623771Z     debug   Attribute 'adapter_template_kubernetes.output.source_pod_ip' not in either global or message dictionaries
2018-03-07T01:47:06.623855Z     debug   Attribute 'adapter_template_kubernetes.output.source_pod_name' not in either global or message dictionaries
2018-03-07T01:47:06.623883Z     debug   Attribute 'adapter_template_kubernetes.output.source_namespace' not in either global or message dictionaries
2018-03-07T01:47:06.623916Z     debug   Attribute 'adapter_template_kubernetes.output.source_labels' not in either global or message dictionaries
2018-03-07T01:47:06.623935Z     debug   Attribute 'adapter_template_kubernetes.output.source_service' not in either global or message dictionaries
2018-03-07T01:47:06.623949Z     debug   complete dispatch: destination='kubernetes:handler.kubernetesenv.istio-system(kubernetesenv)' {err:<nil>}
2018-03-07T01:47:06.624049Z     debug   Preprocess Check returned with: OK
2018-03-07T01:47:06.624067Z     debug   Dispatching to main adapters after running processors
2018-03-07T01:47:06.624176Z     debug   Attribute Bag: 
connection.mtls               : false
context.protocol              : http
destination.service           : istio-ingress.istio-system.svc.cluster.local
destination.uid               : kubernetes://istio-ingress-5cf6c449c5-xs8pc.istio-system
request.headers               : {request.headers map[user-agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 x-forwarded-proto:http upgrade-insecure-requests:1 x-envoy-internal:true x-ot-span-context:1e5c39f8ce75436f;1e5c39f8ce75436f;0000000000000000 x-request-id:71765ec3-8131-9c26-a7c2-cfcd29b2db04 x-envoy-decorator-operation:default-route accept-language:en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6 x-forwarded-for:10.128.0.2 :path:/productpage cache-control:max-age=0 x-b3-spanid:1e5c39f8ce75436f :method:GET :authority:35.224.46.198 x-b3-sampled:1 accept-encoding:gzip, deflate x-b3-traceid:1e5c39f8ce75436f accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8] 0xc42263a240}
request.host                  : 35.224.46.198
request.method                : GET
request.path                  : /productpage
request.scheme                : http
request.time                  : 2018-03-07 01:47:06.620479478 +0000 UTC
request.useragent             : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
source.ip                     : [10 128 0 2]
source.port                   : 56809
---
destination.ip                : [10 12 1 48]
destination.labels            : map[istio:ingress pod-template-hash:1792700571]
destination.namespace         : istio-system
destination.podName           : istio-ingress-5cf6c449c5-xs8pc
destination.serviceAccount    : istio-ingress-service-account
source.labels                 : map[]
source.namespace              : default
source.podName                : unknown
source.service                : unknown
source.serviceAccount         : unknown
```
Closing this bug and use #2160 to track e2e tests for this.

**Closed** 2018-03-07 02:13 UTC
Labels: area/perf and scalability, area/policies and telemetry, kind/fixit, kind/needed for 1.0

**Comment by ldemailly** [comment] 2018-03-07 02:28
it seems quite buggy to have adapter_template_kubernetes.* in the keys btw, it's not like the mixerclient can ever have those - want to file a different issue for that ?
