### ISSUE TITLE
IPV6 address in Virtual Services are assumed as short names & updated as incorrect fqdn in ingress routing info.  

### ISSUE THREAD

**Issue by vbalaganes** [istio/istio#28645] opened 2020-11-06 08:36 UTC
Hi , 

I have installed Istio **1.6.8** in a IPv6 K8s Cluster.
I created a Virtual Service with IPv6 Address in Host Field.

spec:
  gateways:
  - istio-k8s-ingress
  hosts:
  - **2a00:4000::614**
  http:
  - match:
              
When I checked the routing info in ingress gateway pod with [ curl [::1]:15000/config_dump2].
It shows , 

"domains": [
"2a00:4000::614.ns.svc.cluster.local",
"2a00:4000::614.ns.svc.cluster.local:* ---> IPV6 address treated as short name & Resolved as FQDN
],

Since it is resolved as FQDN , iam not able to do curl requests with IPv6 address.

In case of IPv4
"domains": [
"10.96.175.244",
"10.96.175.244:*" -----------> Correct.
],

Kindly help to solve this.

**Comment by Monkeyanator** [comment] 2020-11-06 14:44
Think the issue is that we're checking whether the host is FQDN by just doing

https://github.com/istio/istio/blob/eaacb6e0037b81551fa2c6017406d4f3de703d80/pilot/pkg/model/config.go#L201

**Comment by Monkeyanator** [comment] 2020-11-06 21:37
Thanks for reporting this @vbalaganes! Should be fixed in 1.7.5 with #28661

**Closed by Monkeyanator** 2020-11-06 21:37 UTC
Labels: area/networking
