### ISSUE TITLE
Support Warning in Validation Webhook

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#26970] opened 2020-09-01 18:50 UTC
Need further analysis on which features to implement in this design doc:

https://docs.google.com/document/d/1A5ydzR7iNaiefUJWKVHE1IwqqrwYNx04-QC9nhcqknE

/cc @howardjohn

**Comment by howardjohn** [comment] 2020-11-03 19:02
This is fixed and a duplicate of https://github.com/istio/istio/issues/27179

**Closed by howardjohn** 2020-11-03 19:02 UTC
Labels: area/config, area/user experience
