### ISSUE TITLE
istioctl analyze should return a non-zero status code when issues are found

### ISSUE THREAD

**Issue by selmanj** [istio/istio#17872] opened 2019-10-15 00:20 UTC
This supports using the command in a CI-style environment.

It's probably a good idea to also support a non-zero status code on errors only via a command line flag.

**Comment by esnible** [comment] 2019-10-15 18:55
Closing as a duplicate of https://github.com/istio/istio/issues/17862

**Closed by esnible** 2019-10-15 18:55 UTC
Labels: area/config
