### ISSUE TITLE
Envoy infinite loops requests to itself causing OOM

### ISSUE THREAD

**Issue by vaibhavjain882** [istio/istio#28058] opened 2020-10-18 21:21 UTC
**Bug description**

Istio proxy is calling itself infinite times.

Inbound and outbound is the same:

2020-10-18T19:38:17.631816Z	debug	envoy router	[external/envoy/source/common/router/router.cc:477] [C499946][S2310090886296450400] cluster 'inbound|80|http|xxx-xxx-aggregator.xxx.svc.cluster.local' match for URL '/api/async-search-result'

2020-10-18T19:38:17.632811Z	debug	envoy router	[external/envoy/source/common/router/router.cc:477] [C499914][S12742769214774077339] cluster 'outbound|80||xxx-xxx-aggregator.xxx.svc.cluster.local' match for URL '/api/async-search-result'

Requests keep piling up and Pod ends with OOM.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ x] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

It should not call infinitely.

**Steps to reproduce the bug**

I just enabled the sidecar proxy on my deployment and it started happening. 

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3 (119 proxies)

Client Version: v1.16.0
Server Version: v1.17.9-eks-4c6976

version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

**How was Istio installed?**

Using istioctl with profile.

**Environment where bug was observed (cloud vendor, OS, etc)**

Cloud - AWS EKS

**Additional issues, which seems relevant**
1. https://github.com/istio/istio/issues/26946
2. https://stackoverflow.com/questions/63602585/istio-envoy-proxy-request-loop-causing-oom

**Note: I am not using mTLS**

**Comment by howardjohn** [comment] 2020-10-23 17:21
Duplicate of https://github.com/istio/istio/issues/26946, see there for resolution

**Closed by howardjohn** 2020-10-23 17:21 UTC
