### ISSUE TITLE
Convert Telemetry Integration Tests to use multicluster.

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#26888] opened 2020-08-28 17:50 UTC
Convert tests under `tests/integration/telemetry/` to support running with any number of clusters provided by the test framework. 

There is a broader conversation to have on if these tests needs to be part of a separate suite, or can be assertions on top of generic traffic tests. 

We have one multicluster telemetry test currently, which will temporarily live under pilot/ (https://github.com/istio/istio/pull/26781) so we can dismantle the multicluster job. 

https://github.com/istio/istio/blob/e4d4b6bda3abff4ee6747d51f6f1318bb44438eb/tests/integration/multicluster/telemetry.go#L28-L30

See https://github.com/istio/istio/wiki/Writing-Good-Tests#support-all-environments-multi-cluster-multi-network-etc for general pointers on converting tests and reducing test time. 

Example prow job: 
https://github.com/istio/test-infra/blob/8f4346254004038b034084540dcc54f97653566c/prow/config/jobs/istio.yaml#L104-L115

---

- [x] Tests run without RequiresSingleCluster
- [x] Connectivity/Telemetry values between every pair of clusters is exercised
- [x] Test time stays below some agreed upon number (~15 min, this may require additional work before hand to improve test times)
- [x] Create a Prow job that targets telemetry with multicluster topology (make sure its optional, so it's not blocking PRs while stabilizing).

**Comment by gargnupur** [comment] 2020-11-17 18:44
Based on test times here: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_i
stio/28963/integ-telemetry-mc-k8s-tests_istio/1328750246913642496 and https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28963/integ-telemetry-k8s-tests_istio/1328757643715547136, we look to be within the range of 15 
mins...

/cc @nmittler @stevenctl @mandarjog @douglas-reid

**Comment by stevenctl** [comment] 2020-11-17 18:49
Looks more like 55 mins: https://prow.istio.io/?repo=istio%2Fistio&job=integ-telemetry-mc-k8s-tests_istio

**Comment by gargnupur** [comment] 2020-11-18 18:53
I think after @howardjohn's PR https://github.com/istio/istio/pull/28963, it has come down to around 45-55 mins. Looking at single cluster runs, it's at around 20-30 mins (https://prow.istio.io/?repo=istio%2Fistio&job=integ-telemetry-k8s-tests_istio).

So we do have work to get the times down a lil more for the multicluster tests. In the mean time for 1.8, if folks are ok, we can make the multicluster test required..

@howardjohn , @mandarjog , @nmittler , @stevenctl, @douglas-reid, @bianpengyuan : wdyt?

**Comment by howardjohn** [comment] 2020-11-18 19:06
I do not think we can have a 55 minute test. We spent many many months of effort to get test times down, its now down to ~25 mins (bottleneck is security and telemetry), and I would be very disappointed to regress from that.

I think we should invest in making the single cluster telemetry test more optimized, which will in turn lead to improvements in the multicluster time and bring it down. These tests seem to have a lot of time involved with sleeping and waiting for prometheus metrics that leads to slow tests which may be possible to improve?

**Comment by nmittler** [comment] 2020-11-18 19:11
Without this test, we won't have telemetry test coverage for 1.8 which is a gate for multicluster beta. I'd prefer we land this for 1.8 and then have a P0 to improve performance immediately following the release. WDYT?

**Comment by howardjohn** [comment] 2020-11-18 19:15
I personally would rather have sane test times and stability than multicluster beta. I really, really do not want to go back to waking up at midnight to hit `/retest` on all my PRs because of slow, flaky tests.

They are not just slow, currently at 74% pass rate: https://prow.istio.io/?job=integ-telemetry-mc-k8s-tests_istio_postsubmit. We had a month where the *aggregate* postsubmit success rate for ALL jobs combined was like 99%. We have regressed quite a bit since then, partially as a result of multicluster and some other factors. But for comparison even today the pilot test pass rate is 94%

**Comment by nmittler** [comment] 2020-11-18 19:20
@stevenctl do you have a feel for why multicluster tests are so flaky in comparison?

**Comment by gargnupur** [comment] 2020-11-18 19:24
Also, I looked at https://prow.istio.io/?job=integ-telemetry-mc-k8s-tests_istio_postsubmit and all the recent runs they have failed because of setup error in one of the test.
There are errors like these: 
"- Processing resources for Ingress gateways, Istiod remote. Waiting for Deployment/istio-system/i...2020-11-18T18:26:12.060349Z	error	installer	failed to create "EnvoyFilter/istio-system/metadata-exchange-1.9": Internal error occurred: failed calling webhook "validation.istio.io": Post https://172.18.255.156:15017/validate?timeout=30s: read tcp 172.18.0.3:54446->172.18.255.156:15017: read: connection reset by peer
2020-11-18T18:26:12.060507Z	error	installer	failed to create "EnvoyFilter/istio-system/metadata-exchange-1.9": Internal error occurred: failed calling webhook "validation.istio.io": Post https://172.18.255.156:15017/validate?timeout=30s: read tcp 172.18.0.5:34458->172.18.255.156:15017: read: connection reset by peer"

**Comment by douglas-reid** [comment] 2020-11-18 19:33
> I do not think we can have a 55 minute test. We spent many many months of effort to get test times down, its now down to ~25 mins (bottleneck is security and telemetry), and I would be very disappointed to regress from that.
> 
> I think we should invest in making the single cluster telemetry test more optimized, which will in turn lead to improvements in the multicluster time and bring it down. These tests seem to have a lot of time involved with sleeping and waiting for prometheus metrics that leads to slow tests which may be possible to improve?

Surely we don't have a test with 30 minutes of waiting for metrics, right? 

Looking at the average test time reported in an example log, it looks like the actual run time of the tests is ~1m on average for 19 different tests (if i'm reading https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28998/integ-telemetry-mc-k8s-tests_istio/1329117899503177728 correctly).

Do we need to look at test setup/teardown instead?

**Comment by mandarjog** [comment] 2020-11-18 19:34
Looking at https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28998/integ-telemetry-mc-k8s-tests_istio/1329117899503177728 which took 50 mins  only 8 mins are accounted for by the tests running.
Is 42 mins spent in setup?

**Comment by howardjohn** [comment] 2020-11-18 19:43
By my check 9 min test time for MC, vs 7m30s for standard

standard:
```
TestLocalRateLimiting 0.13s
TestLocalRouteSpecificRateLimiting 0.13s
TestTCPStackdriverMonitoring 9.10s
TestIstioctlMetrics 9.27s
TestClientTracing 9.44s
TestStackdriverMonitoring 10.31s
TestTcpMetric 11.02s
TestWASMTcpMetric 11.05s
TestStatsFilter 17.03s
TestWasmStatsFilter 17.08s
TestProxyTracing 24.63s
TestVMTelemetry 24.74s
TestProxyTracing 31.12s
TestCustomizeMetrics 42.15s
TestDashboard 45.94s
TestRateLimiting 60.24s
TestOutboundTrafficPolicy_RegistryOnly 63.10s
TestOutboundTrafficPolicy_AllowAny 76.62s
```

mc (note some are not yet MC enabled it seems)
```
TestIstioctlMetrics 7.41s
TestTCPStackdriverMonitoring 13.35s
TestStackdriverMonitoring 13.59s
TestProxyTracing 25.18s
TestVMTelemetry 25.88s
TestCustomizeMetrics 32.18s
TestWASMTcpMetric 35.53s
TestTcpMetric 35.59s
TestClientTracing 37.28s
TestProxyTracing 46.71s
TestStatsFilter 65.31s
TestWasmStatsFilter 66.41s
TestDashboard 137.49s
```

As far as test setup: the initial overhead for building docker images, setting up kind cluster is ~5minutes. This does NOT include the time it takes to spin up Istio and tear it down; the telemetry tests do this 12 times (as does security; pilot does it 5 times).

So looking closer it seems like even making "prometheus sleep" type problems go to 0, it would still help, but would likely not be sufficient to get the MC test times down without further improvements

**Comment by gargnupur** [comment] 2020-11-18 19:53
The quick refactor that I know of is as follows:
1) Move dashboard test to istio/istio/tests/integration/telemetry/stats/prometheus/nullvm/ suite
2) Move client tracing zipkin test to  istio/istio/tests/integration/telemetry/stats/prometheus/nullvm/ suite
3) Move TestCustomizeMetrics test to istio/istio/tests/integration/telemetry/stats/prometheus/nullvm/ suite
3) TestVMTelemetry -> mark it as singlecluster as vm tests are not converted to multicluster yet.

Another optimization that we can do in tests is verify each cluster in parallel rather than sequential.. something that can help reduce test runtime...

**Comment by douglas-reid** [comment] 2020-11-18 19:53
> This does NOT include the time it takes to spin up Istio and tear it down; the telemetry tests do this 12 times (as does security; pilot does it 5 times).

We should be able to reduce the count from 12 to 3 fairly easily with a refactor of the existing tests (stackdriver, prom + zipkin, opencensus). That should be significant savings. With extra creativity, we may be even be able to get to 1 (control plane revisions, etc.).

I think that is where we should spend this effort.

**Comment by howardjohn** [comment] 2020-11-19 01:09
Added better timing to the tests: https://github.com/istio/istio/pull/29027

Kind creation seems to be 90-147s for single cluster. I think the slow ones are due to metallb which we recently added to single cluster tests. For multicluster, 188s (small sample size since I was too impatient for the others to finish...)

Building images is always around 50-70s.

But based on this looks like the vast majority of the time is spent in the test code (this includes istio install), the "pre setup" is pretty quick

**Comment by howardjohn** [comment] 2020-11-19 22:17
```
2020-11-19T22:02:13.588720Z     info    tf      === SUCCEEDED: Deploy Istio in 2m11.240952362s [Suite=telemetry]===
2020-11-19T22:06:24.688418Z     info    tf      === DONE: Cleanup Istio in 1m40.742859485s [Suite=telemetry] ===
2020-11-19T22:08:23.160033Z     info    tf      === SUCCEEDED: Deploy Istio in 1m25.87333318s [Suite=telemetry_stackdriver]===
2020-11-19T22:12:20.996520Z     info    tf      === DONE: Cleanup Istio in 1m31.874954261s [Suite=telemetry_stackdriver] ===
2020-11-19T22:13:39.395439Z     info    tf      === SUCCEEDED: Deploy Istio in 1m8.936619182s [Suite=telemetry_stackdriver_vm]===
```

The multicluster cleanup is different than the single cluster, and far far slower: https://github.com/istio/istio/blob/879a94aa2e5e868107b2636a05bb8de76425fc16/pkg/test/framework/components/istio/operator.go#L172

compare to single cluster
```
2020-11-19T21:59:38.888720Z     info    tf      === SUCCEEDED: Deploy Istio in 25.089487189s [Suite=telemetry]===
2020-11-19T22:00:20.185441Z     info    tf      === DONE: Cleanup Istio in 2.080190014s [Suite=telemetry] ===
2020-11-19T22:01:07.466841Z     info    tf      === SUCCEEDED: Deploy Istio in 39.609539698s [Suite=telemetry_outboundtrafficpolicy]===
2020-11-19T22:03:37.305742Z     info    tf      === DONE: Cleanup Istio in 688.20369ms [Suite=telemetry_outboundtrafficpolicy] ===
2020-11-19T22:04:31.444809Z     info    tf      === SUCCEEDED: Deploy Istio in 47.226638929s [Suite=telemetry_policy]===
2020-11-19T22:05:54.810886Z     info    tf      === DONE: Cleanup Istio in 768.140783ms [Suite=telemetry_policy] ===
2020-11-19T22:06:48.003648Z     info    tf      === SUCCEEDED: Deploy Istio in 38.708302733s [Suite=telemetry_stackdriver]===
2020-11-19T22:07:30.774652Z     info    tf      === DONE: Cleanup Istio in 3.187802177s [Suite=telemetry_stackdriver] ===
2020-11-19T22:08:21.852836Z     info    tf      === SUCCEEDED: Deploy Istio in 43.068168945s [Suite=telemetry_stackdriver_vm]===
2020-11-19T22:08:52.093210Z     info    tf      === DONE: Cleanup Istio in 728.34913ms [Suite=telemetry_stackdriver_vm] ===
```

**Comment by howardjohn** [comment] 2020-11-20 16:38
https://github.com/istio/istio/pull/29084 shaves quite a bit off istio deploy

**Comment by gargnupur** [comment] 2020-12-17 22:07
@howardjohn , @nmittler , @douglas-reid , @mandarjog , @richardwxn : we can improve the test times more, but currently https://prow.istio.io/?job=integ-telemetry-mc-k8s-tests_istio_postsubmit is at around 30-35 minutes, so we can make the multicluster job required.

@ririchardwxn: handing over the issue to you...

**Comment by douglas-reid** [comment] 2021-01-06 01:59
Can we mark these tests as required now, and begin to address any additional refactorings needed to further reduce overall run time?  Last few runs have been ~30mins. That is reasonably close to the prior tent pole, and would get us appropriate coverage while the test refactoring effort can be tackled. The cost of not doing it is any sort of test regression or flakiness introduced in the lag between now and the refactoring.

**Comment by nmittler** [comment] 2021-01-06 16:59
I think so ... @howardjohn wdyt?

**Comment by bianpengyuan** [comment] 2021-02-18 06:22
I think this is done as the test has been marked as required.

**Closed by bianpengyuan** 2021-02-18 06:22 UTC
Labels: area/extensions and telemetry, area/test and release, feature/Multi-cluster
