### ISSUE TITLE
pods with istio-sidecar container , cannot reach the external services (sometimes).

### ISSUE THREAD

**Issue by tapanhalani** [istio/istio#15806] opened 2019-07-24 04:06 UTC
** Bug description **
My kubenretes default namespace is istio-sidecar injection enabled. So all pods start with an extra "istio-proxy" container along with my own.  The problem is that with istio-proxy container, the application containers in some of my pods cannot connect to external services like slack.com, listerner-eu.logz.io etc.  The error that occurs is as follows:

```
2019-07-23 07:47:53,711 - 1 - INFO - log - [*] Starting NATS listener: rexv2
2019-07-23 07:47:53,712 - 1 - DEBUG - selector_events - Using selector: EpollSelector
2019-07-23 07:47:53,745 - 1 - ERROR - log - Failed to send to slack...
2019-07-23 07:47:53,746 - 1 - INFO - log - [*] Exposing NATS: rexv2
2019-07-23 07:47:53,746 - 1 - ERROR - log - Failed to send to slack...
2019-07-23 07:47:53,747 - 1 - DEBUG - log - [*] connecting to nats (nats://mycompany_staging:***@nats-tls.databases.svc.cluster.local:4222) as rexv2 [TLS=True]
2019-07-23 07:47:53,760 - 1 - ERROR - base_events - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /usr/local/lib/python3.6/site-packages/slack/web/base_client.py:182> exception=ClientConnectorError(111, "Connect call failed ('13.35.250.164', 443)")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('13.35.250.164', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slack/web/base_client.py", line 211, in _send
    http_verb=http_verb, api_url=api_url, req_args=req_args
  File "/usr/local/lib/python3.6/site-packages/slack/web/base_client.py", line 240, in _request
    async with session.request(http_verb, api_url, **req_args) as res:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 931, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.slack.com:443 ssl:None [Connect call failed ('13.35.250.164', 443)]
Got exception while sending logs to Logz.io, Try (1/4). Message: HTTPSConnectionPool(host='listener-eu.logz.io', port=8071): Max retries exceeded with url: /?token=OKCdoELa44h7sncjs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe93157dc50>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-07-23 07:47:56,725 - 1 - ERROR - sender - Got exception while sending logs to Logz.io, Try (1/4). Message: HTTPSConnectionPool(host='listener-eu.logz.io', port=8071): Max retries exceeded with url: /?token=OKCdoELa44h7sncjs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe93157dc50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Although some times, the connection issue gets resolved on it's own after 10-15 minutes, but many times, the issue persists even over pod restarts. The issue gets completely and permanently resolved when I stop istio-sidecar injection and remove istio-proxy container from pod. Then, there is no connection issue ever.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
There shouldn't be any (sporadic, automatically appearing/disappearing) connection issues with istio-proxy to external services. The expected behaviour is shown in a separate AKS cluster with same version of istio deployed, and no connection issues for external services arise in it.

**Steps to reproduce the bug**
I am not sure there is any particular pattern for reproducing this. In  my case, 1 of the pods with istio-proxy container fails to connect to slack and logz.io ,most of the times , upon pod startup.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.1.10
kubernetes: 1.12.8
Cloud provider: AKS (Azure kubernetes service)

**How was Istio installed?**
Using Helm chart. Following the process of first installing the new CRD's , followed by helm upgrade.

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes is deployed using AKS (azure kubernetes service ), and istio is installed in AKS using helm.

**Comment by howardjohn** [comment] 2019-09-07 00:13
I believe this is a duplicate of https://github.com/istio/istio/issues/11130

**Closed by howardjohn** 2019-09-07 00:13 UTC
Labels: area/networking
