### ISSUE TITLE
Random TCP Resets

### ISSUE THREAD

**Issue by prsauer** [istio/istio#13107] opened 2019-04-05 21:20 UTC
**Describe the bug**
We've been seeing random TCP connection resets under low load conditions.

We were seeing some very strange behavior on some connections and traced it back to a strange looking TCP handshake causing a RST.

<img width="893" alt="Screen Shot 2019-04-05 at 5 16 32 PM" src="https://user-images.githubusercontent.com/15525519/55656903-a121d180-57c6-11e9-90ec-142eca2784bf.png">

Shown is an example -- the Ack number in packet 2 seems very strange (as does TSecr to be honest). I think this should also be a SYN-ACK. I'm not entirely sure how this would happen but we've A/B tested config and the only correlation we could find was Istio. Pods that used Istio exhibited this failure and ones without it did not.

**Version**
Istio 1.1.1

**Environment**
Azure KS

**Comment by arianmotamedi** [comment] 2019-04-09 15:34
> the Ack number in packet 2 seems very strange (as does TSecr to be honest). I think this should also be a SYN-ACK

This happens when the client closes a connection that remains open the server side on that port (443). Next time the client tries to establish a new connection by sending a SYN packet, but the server sees that the connection is already open, so it responds with ACK (even though it doesn't know how to respond to SYN, it can't send RST either because the _connection_ is still in a valid state). The client sees ACK without SYN, so it knows the response belongs to another connection, therefore sends an RST to server to have it close the stale connection. Generally though this shouldn't cause a 503 - the client should re-establish a new connection by sending another SYN. Is that not the case here? Are there anymore captures in the log? This is the exact opposite of what's happening in https://github.com/envoyproxy/envoy/issues/6190 which is a known bug in Envoy.

**Comment by howardjohn** [comment] 2019-06-03 04:20
@prsauer there hasn't been any activity on this for months, and it looks like a thorough answer was given so I am going to close this for now. If there is more info needed we can reopen this. Thanks

**Closed by howardjohn** 2019-06-03 04:20 UTC
Labels: area/networking

**Comment by prsauer** [comment] 2019-06-03 14:23
No worries - we actually never found the root cause on this and ended up removing Istio

**Comment by wxdao** [comment] 2019-06-05 08:53
Hi @howardjohn, I'd like to know whether the bug fix from envoy (envoyproxy/envoy#6578) is applied in latest istio releases?

**Comment by sujayran** [comment] 2021-08-19 20:58
Seeing the exact same issue mentioned in this thread, until we change either the port/ip on the client-side or restart the istio-proxy we keep seeing this issue 

The issue is server keeps sending ACK instead of [SYN,ACK], and this happens intermittently when the client crashes (i.e. doesn't close the connection gracefully)

![image](https://user-images.githubusercontent.com/42414820/130142435-efbb8a2b-2742-4b0c-b518-135fa2a38d68.png)
