### ISSUE TITLE
istio-1.8.0   istio-ingressgateway nodeport is NOT exposed

### ISSUE THREAD

**Issue by hillbun** [istio/istio#29189] opened 2020-11-25 10:06 UTC
```
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: NodePort
```

```
kubectl get service -n istio-system  
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                     AGE
istio-ingressgateway   NodePort    10.233.13.180   <none>        15021:2805/TCP,80:24547/TCP,443:20403/TCP,31400:32200/TCP,15443:21128/TCP   4m3s
istiod                 ClusterIP   10.233.47.232   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                       4m3s
```

I  curl http://10.233.13.180:24547/

but get no response.

Any advice?

**Comment by howardjohn** [comment] 2020-11-25 19:43
Please follow the steps on https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#determining-the-ingress-ip-and-ports, the IP is wrong

**Comment by windghoul** [comment] 2020-12-17 10:12
> ```
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   annotations: null
>   labels:
>     app: istio-ingressgateway
>     install.operator.istio.io/owning-resource: unknown
>     istio: ingressgateway
>     istio.io/rev: default
>     operator.istio.io/component: IngressGateways
>     release: istio
>   name: istio-ingressgateway
>   namespace: istio-system
> spec:
>   ports:
>   - name: status-port
>     port: 15021
>     protocol: TCP
>     targetPort: 15021
>   - name: http2
>     port: 80
>     protocol: TCP
>     targetPort: 8080
>   - name: https
>     port: 443
>     protocol: TCP
>     targetPort: 8443
>   - name: tcp
>     port: 31400
>     protocol: TCP
>     targetPort: 31400
>   - name: tls
>     port: 15443
>     protocol: TCP
>     targetPort: 15443
>   selector:
>     app: istio-ingressgateway
>     istio: ingressgateway
>   type: NodePort
> ```
> 
> ```
> kubectl get service -n istio-system  
> NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                     AGE
> istio-ingressgateway   NodePort    10.233.13.180   <none>        15021:2805/TCP,80:24547/TCP,443:20403/TCP,31400:32200/TCP,15443:21128/TCP   4m3s
> istiod                 ClusterIP   10.233.47.232   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                       4m3s
> ```
> 
> I curl http://10.233.13.180:24547/
> 
> but get no response.
> 
> Any advice?

try to curl 10.233.13.180:80 or check vs & gateway

**Comment by howardjohn** [comment] 2020-12-17 15:43
Closing as this is working as intended, please follow https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#determining-the-ingress-ip-and-ports. Thanks!

**Closed by howardjohn** 2020-12-17 15:43 UTC
Labels: area/environments, kind/need more info
