### ISSUE TITLE
Auto update common-files when build-tools is built

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28436] opened 2020-10-30 18:44 UTC
Its a bit painful to do this manually

**Comment by daixiang0** [comment] 2020-11-02 01:27
Add it as a prow job?

**Comment by ericvn** [comment] 2020-11-03 14:15
We would either have to wait some period of time, say 45 mins, and then look for an image that was updated in the last 45 mins (and hope it was caused by the same PR that tripped the job). If multiple changes went in near each other, as long as the image build wasn't slow and missed, both automator jobs might pick up the same one, but that might not be too bad. I have some code in my release-builder changes which looks for the last image for a given release so that could be used.

**Comment by howardjohn** [comment] 2020-11-03 14:20
can't we do it in the actual job that builds the image as well? do we don't
need a wait?

**Comment by ericvn** [comment] 2021-02-23 20:49
This is a duplicate of https://github.com/istio/test-infra/issues/2469.

**Closed by ericvn** 2021-02-23 20:49 UTC
Labels: area/test and release, kind/enhancement
