### ISSUE TITLE
TestTCPMixerFilterPeriodicalReport flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#8169] opened 2018-08-23 08:17 UTC
**Describe the bug**

TestTCPMixerFilterPeriodicalReport failed in CI https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/8162/istio-unit-tests/12120/

But I can not reproduce in my local env.

**Comment by hzxuzhonghu** [comment] 2018-08-23 08:28
```
I0823 07:22:11.665] === RUN   TestTCPMixerFilterPeriodicalReport
I0823 07:22:11.666] 2018-08-23T07:22:01.558094Z	info	07:22:01 Envoy config: in /home/bootstrap/go/out/linux_amd64/release/config.conf.20115.yaml
I0823 07:22:11.666] 2018-08-23T07:22:01.562340Z	info	07:22:01 Pinging URL:  http://localhost:20115/server_info
I0823 07:22:11.666] 2018-08-23T07:22:01.562420Z	info	07:22:01 HTTP GET http://localhost:20115/server_info
I0823 07:22:11.667] 2018-08-23T07:22:01.563251Z	info	07:22:01 Get http://localhost:20115/server_info: dial tcp [::1]:20115: connect: connection refused
I0823 07:22:11.667] 2018-08-23T07:22:01.563309Z	info	07:22:01 Will wait a second and try again.
I0823 07:22:11.668] [2018-08-23 07:22:01.587][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:125] Caught Bus error, suspect faulting address 0x7fd634e1b028
I0823 07:22:11.668] [2018-08-23 07:22:01.588][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:94] Backtrace thr<0> obj</home/bootstrap/go/bin/envoy> (If unsymbolized, use tools/stack_decode.py):
I0823 07:22:11.669] [2018-08-23 07:22:01.599][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<0> #0 0xc739fe Envoy::BlockMemoryHashSet<>::initialize()
I0823 07:22:11.669] [2018-08-23 07:22:01.609][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<0> #1 0xc6feec Envoy::BlockMemoryHashSet<>::BlockMemoryHashSet()
I0823 07:22:11.670] [2018-08-23 07:22:01.621][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<0> #2 0xc6bfc5 Envoy::Server::HotRestartImpl::HotRestartImpl()
I0823 07:22:11.670] [2018-08-23 07:22:01.632][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<0> #3 0x812fbf Envoy::MainCommonBase::MainCommonBase()
I0823 07:22:11.671] [2018-08-23 07:22:01.643][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<0> #4 0x813ca1 Envoy::MainCommon::MainCommon()
I0823 07:22:11.671] [2018-08-23 07:22:01.654][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<0> #5 0x812061 std::make_unique<>()
I0823 07:22:11.671] [2018-08-23 07:22:01.665][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<0> #6 0x811a6b main
I0823 07:22:11.672] [2018-08-23 07:22:01.665][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<0> obj</lib/x86_64-linux-gnu/libc.so.6>
I0823 07:22:11.672] [2018-08-23 07:22:01.665][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<0> #7 0x7fd63502e82f (unknown)
I0823 07:22:11.672] [2018-08-23 07:22:01.665][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<0> obj</home/bootstrap/go/bin/envoy>
I0823 07:22:11.672] [2018-08-23 07:22:01.676][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<0> #8 0x585078 _start
I0823 07:22:11.673] [2018-08-23 07:22:01.676][16874][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:121] end backtrace thread 0
I0823 07:22:11.673] 2018-08-23T07:22:01.763490Z	info	07:22:01 Pinging URL:  http://localhost:20115/server_info
I0823 07:22:11.673] 2018-08-23T07:22:01.763535Z	info	07:22:01 HTTP GET http://localhost:20115/server_info
I0823 07:22:11.673] 2018-08-23T07:22:01.764341Z	info	07:22:01 Get http://localhost:20115/server_info: dial tcp [::1]:20115: connect: connection refused
```

**Comment by douglas-reid** [comment] 2018-08-23 22:31
@JimmyCYJ can you please take a look at this issue?

**Comment by kyessenov** [comment] 2018-08-23 22:33
Dupe of https://github.com/istio/istio/issues/8133

**Comment by douglas-reid** [comment] 2018-08-23 22:34
Closing in favor of #8133

**Closed by douglas-reid** 2018-08-23 22:34 UTC
Labels: area/test and release
