### ISSUE TITLE
outboundTrafficPolicy : ALLOW_ANY but I can access to external url

### ISSUE THREAD

**Issue by springrain** [istio/istio#13388] opened 2019-04-17 02:21 UTC
**Bug description**
I setup istio version 1.1.3 with default config:
outboundTrafficPolicy:
    mode: ALLOW_ANY
I call wget http://httpbin.org/ in a pod injected sidecar but it return wget: server returned error: HTTP/1.1 404 Not Found

**Expected behavior**
wget success get data from url
**Steps to reproduce the bug**
I cleanup istio 1.1.2 and setup istio version 1.1.3, deploy a pod in injected sidecar namespace and using ssh to this pod and call wget http://httpbin.org/

Described in https://istio.io/about/notes/1.1.3/
Fix ALLOW_ANY so it now allows external traffic if there is already an http service present on a port.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`client version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
citadel version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
egressgateway version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
galley version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
ingressgateway version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
pilot version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
policy version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
sidecar-injector version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
telemetry version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}`

**How was Istio installed?**
kubectl apply -f istio-demo.yaml
**Environment where bug was observed (cloud vendor, OS, etc)**
k8s 1.14.1   centos7.6  kernel5.0.4

**Comment by esnible** [comment] 2019-04-17 13:36
Closing as a duplicate of https://github.com/istio/istio/issues/12952

**Closed by esnible** 2019-04-17 13:36 UTC
