### ISSUE TITLE
Proposal: enable all traffic going outside of mesh allowed by default

### ISSUE THREAD

**Issue by linsun** [istio/istio#11739] opened 2019-02-13 21:12 UTC
When user uses istio initially, they often spend long hours to get their app working simply because they didn't realize/know that we disable all traffic going out of the mesh/k8s by default.   This is a show stopper for moving to run user's microservices to istio without any changes.  Our goal of the istio project has been it is transparent and not there without user noticing he/she is using it while gaining the benefits of the mesh.

Proposed is to allow all outbound traffic to be enabled by default and up to mesh admin to tune this as they get the app running in istio and tighten up the access control from services to outside of the mesh/k8s.  We should at least do this for the demo profile at the very minimum.

**Comment by linsun** [comment] 2019-02-13 21:12
cc @costinm @rshriram @louiscryan @esnible @vadimeisenbergibm @duderino @frankbu

**Comment by linsun** [comment] 2019-02-13 21:16
with the new global option added by @rshriram and @vadimeisenbergibm we could toggle this easily

**Comment by esnible** [comment] 2019-02-13 21:28
I believe it would be a good default for applications to behave as expected unless additional security is requested.

Recently closed bug https://github.com/istio/istio/issues/10330 allowed traffic to go out by default on most ports.  It would be very confusing if users were getting that behavior and then we turned it off as part of the 1.1 upgrade.

**Comment by vadimeisenbergibm** [comment] 2019-02-14 04:22
See this thread https://groups.google.com/forum/#!msg/istio-users/J_Ad-wTLjmY/ErpE6AKqDQAJ

> Security is a concern, but not the primary one I am thinking about in this case. One very nice "ergonomic" that Istio 1.0's hijacking of all network traffic brought to the table for us, with respect to mesh external traffic, was as a control/visibility mechanism.

> For background, we have product development teams creating microservices, but very shortly there will also be SDK customers and professional services groups deploying to UAT and production environments. Even within the development group we could very quickly determine a misconfigured IP/PORT combination (for example, hard coded IPs) as we moved between environments and correct or, if legitimate, create a new ServiceEntry. Now I know we can create mesh external mechanisms to whitelist traffic (and we do) but the "Istio native" ServiceEntry feature was valuable since it acted as a mesh native "catalog" of external services, avoided configuring the egress controller, and was easy to codify into custom service helm charts. With regards to the new 1.1 behavior we will no longer have this and problems look like they will now be detected later in the deployment cycle.

https://groups.google.com/d/msg/istio-users/J_Ad-wTLjmY/ahxgS_raDQAJ 

> Just to let let people know, we are always very happy about the egress control and the ability to block all traffic by default. We have very strict security requirements, one of them being that all outgoing traffic has to be explicitly allowed.

**Comment by linsun** [comment] 2019-02-15 19:55
@vadimeisenbergibm we are not saying this feature isn't useful, of course, this is one of the most important features of istio.  However, we don't want users to stumble on this during day 1 of using istio. 

Per yesterday's discussion in networking WG, people are in favor of making this default for the demo profile.  It seems people are in favor of making this change in the standard profile as well as long as we have an upgrade path.

**Comment by vadimeisenbergibm** [comment] 2019-02-15 20:03
@rshriram wrote here https://groups.google.com/d/msg/istio-users/J_Ad-wTLjmY/QC-6ediuCQAJ

>  We are adding a global flag that will restore the old 1.0 behavior - this will be the default mode. You can change the flag to get the new behavior (allow all) if you wish. 

So should we still change the default behavior in the standard profile?

**Comment by linsun** [comment] 2019-02-15 20:06
didn't expect you are still online @vadimeisenbergibm , thanks :)

Yes, I would propose we definitely change for demo profile, and default profile as well since we are making a bunch of changes in 1.0->1.1 and we can add this to the list of items to be documented.

if you agree, could you submit two PRs?  one for demo profile, one for default?

**Comment by loewenstein** [comment] 2019-02-16 06:45
@linsun is the proposed default really allowing all egress traffic or is it the "allow all - unless there happens to be configuration for the port you are trying to connect to" thing?
While I am in favor of allowing egress by default, the latter version of it is probably worse than blocking all egress because it is going to be more confusing.

**Comment by vadimeisenbergibm** [comment] 2019-02-16 06:54
@linsun @loewenstein The PR that describes allowing all egress traffic by default was merged yesterday. Please take a look https://preliminary.istio.io/docs/tasks/traffic-management/egress/#install-istio-with-access-to-all-external-services-by-default.

> To allow access to any external service on any ports without an HTTP service or a service entry within the mesh, Istio has an installation option. For example, if you don’t register an HTTP service or define a service entry for the 8000 port within the mesh, you can configure the sidecar proxy to pass the request to any external service on that port. If you later create an HTTP service inside the mesh on port 8000 or define a service entry for any host on port 8000, Istio will block all external access to port 8000 since Istio then falls back to the blocking-by-default behavior for that port.

**Comment by loewenstein** [comment] 2019-02-16 10:52
@vadimeisenbergibm @linsun I still think this mode is going to be even more confusing than blocking all egress.
E.g. calling any external http service on 80 and/or 443 is likely to be blocked right.

**Comment by vadimeisenbergibm** [comment] 2019-02-16 11:22
@loewenstein Calling any external service on port 80 will be blocked. (we can hope that external services will be called over TLS only, so this will not be a limitation).
Calling external services on port 443 will be allowed.

The problem is only with existing HTTP services or with any Service Entry that the user defines. So once the user installs Istio and starts testing it, without defining any Service Entry, the issue is only with HTTP services inside the mesh, in particular with port 80.

**Closed** 2019-02-21 20:26 UTC
