### ISSUE TITLE
Prometheus Istio add-on getting evicted

### ISSUE THREAD

**Issue by Siddharthk** [istio/istio#28144] opened 2020-10-21 07:31 UTC
Prometheus pod is getting evicted. The pod has been installed as istio add-on.
```
Labels:         app=prometheus
                pod-template-hash=6896c67497
                release=istio
Annotations:    kubernetes.io/psp: eks.privileged
                sidecar.istio.io/inject: false
Status:         Failed
Reason:         Evicted
**Message:        The node was low on resource: memory. Container prometheus was using 23086800Ki, which exceeds its request of 0. Container istio-proxy was using 69096Ki, which exceeds its request of 0.**
IP:
IPs:            <none>
Controlled By:  ReplicaSet/prometheus-6896c67497
Containers:
  prometheus:
    Image:      docker.io/prom/prometheus:v2.15.1
    Port:       9090/TCP
    Host Port:  0/TCP
    Args:
      --storage.tsdb.retention=6h
      --config.file=/etc/prometheus/prometheus.yml
    Requests:
      cpu:        10m
```

I see that istio sidecar proxy is taking below resources:
```
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      tcpSocket:
        port: 15021
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
```
I think we should have requests==limits for memory and not overcommit it otherwise this will cause random evictions of pods.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Expected behavior

Prometheus pod should be running.

Steps to reproduce the bug:
```
istio-system   prometheus-6896c67497-2w569                                   0/2     Evicted            0          5d10h
istio-system   prometheus-6896c67497-4r8x2                                   0/2     Evicted            0          5d11h
istio-system   prometheus-6896c67497-7n2z8                                   0/2     OOMKilled          1          5d9h
istio-system   prometheus-6896c67497-b2lpn                                   0/2     Evicted            0          5d11h
istio-system   prometheus-6896c67497-czj62                                   0/2     Evicted            0          5d9h
istio-system   prometheus-6896c67497-dcrc2                                   0/2     Evicted            0          5d10h
istio-system   prometheus-6896c67497-dzfs6                                   0/2     Evicted            0          5d10h
istio-system   prometheus-6896c67497-fs2xr                                   0/2     Evicted            0          5d9h
istio-system   prometheus-6896c67497-hbbh4                                   0/2     Evicted            0          5d10h
istio-system   prometheus-6896c67497-hbqw4                                   0/2     Evicted            0          5d10h
istio-system   prometheus-6896c67497-hn2xm                                   0/2     Evicted            0          5d10h
```
Version (include the output of istioctl version --remote and kubectl version and helm version if you used Helm)

client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (78 proxies)

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

How was Istio installed?

Using istioctl

Environment where bug was observed (cloud vendor, OS, etc)

AWK EKS 1.16.8

**Comment by howardjohn** [comment] 2020-10-21 17:53
The telemetry addons are intended for demo use only and not tuned for production. SEe https://istio.io/latest/blog/2020/addon-rework/ and https://preliminary.istio.io/latest/docs/ops/integrations/prometheus/ for more details.

Closing as "won't fix" as this is working as intended

**Closed by howardjohn** 2020-10-21 17:53 UTC

**Comment by Siddharthk** [comment] 2020-10-29 07:10
@howardjohn I debugged this further...looks like Istio telemetry is causing prometheus to go out of memory and thus have cascading effect and bringing down the node where prometheus pod is hosted. 

Sometimes istio telemetry is fluctuating between service name and pod ip thus causing too many services to be scraped by prometehus and ultimately bringing it down. Screenshots below from prometheus and kiali:
![image](https://user-images.githubusercontent.com/718854/97536729-9e5b8280-19e3-11eb-83aa-f409f1353899.png)

![image](https://user-images.githubusercontent.com/718854/97536806-b7fcca00-19e3-11eb-91a6-6fb21e174a28.png)
