### ISSUE TITLE
TestStackdriverRbacTCPDryRun flake

### ISSUE THREAD

**Issue by zirain** [istio/istio#47910] opened 2023-11-17 15:22 UTC
cc @kyessenov @lei-tang

**Comment by kyessenov** [comment] 2023-11-17 23:03
It's not a flake but caused by https://github.com/envoyproxy/envoy/issues/22583.

**Comment by kyessenov** [comment] 2023-11-20 19:40
Should be fixed by https://github.com/envoyproxy/envoy/pull/30807.

**Closed by kyessenov** 2023-11-20 19:40 UTC
Labels: kind/test failure
