### ISSUE TITLE
What is the status Istio on Arm64 platform

### ISSUE THREAD

**Issue by iecedge** [istio/istio#17747] opened 2019-10-10 02:10 UTC
Hi All,
        I am working at Arm64 platform. And i want to enable the Istio on Arm64 platform. Actually, in my private environments, the Istio 1.2.3 has been built and run successfully just like followings (Of cource, some code were modified).  
```
$ kubectl label namespace default istio-injection=enabled --overwrite
$ kubectl get namespace -L istio-injection
NAME           STATUS   AGE     ISTIO-INJECTION
default        Active   3d23h   enabled
istio-system   Active   3d22h   disabled
kube-public    Active   3d23h
kube-system    Active   3d23h
```
But, recently, when i want to upstream my patch, the Istio/proxy module updated. I found that it can not be built on Arm64 (add some new build modules). So i want to ask some questions about status of Istio on Arm64:
1. Are there any Arm64 CI/CD platforms ?
2. Is there any plan to support Arm64 platform ?
3. Which type is used for Istio CI/CD, jenkins, CircleCI or others ?
4. What is your suggestions about it?

**Comment by howardjohn** [comment] 2019-10-10 02:50
For ci we use Prow (basically runs on kubernetes). I don't think it supports arm64 unless GKE does

**Comment by iecedge** [comment] 2019-10-10 04:38
Could i use another CI/CD tools or build another CI lab for supporting Arm64?

**Comment by iecedge** [comment] 2019-10-11 06:46
I have a new idea. Could we use the cross-compiler for Arm64 supporting?

**Comment by howardjohn** [comment] 2019-10-11 15:15
I am not sure about the proxy, but I am pretty sure you can build the
control plane (pilot, etc) on arm64. See this part of our makefile:
https://github.com/istio/istio/blob/ca8448bef9fe1e0fbd004a297a1847fe8e1dfa9f/Makefile.core.mk#L71-L72

**Comment by howardjohn** [comment] 2020-03-20 22:54
dupe of https://github.com/istio/istio/issues/21094

**Closed by howardjohn** 2020-03-20 22:54 UTC
Labels: area/test and release, lifecycle/needs-triage
