### ISSUE TITLE
Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: context deadline exceeded

### ISSUE THREAD

**Issue by weichanghuan** [istio/istio#19916] opened 2020-01-04 04:51 UTC
bug is :Error from server (InternalError): error when creating "samples/bookinfo/networking/virtual-service-all-v1.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error from server (InternalError): error when creating "samples/bookinfo/networking/virtual-service-all-v1.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error from server (InternalError): error when creating "samples/bookinfo/networking/virtual-service-all-v1.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: context deadline exceeded
Error from server (InternalError): error when creating "samples/bookinfo/networking/virtual-service-all-v1.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 10.96.219.230:443: i/o timeout

**Comment by howardjohn** [comment] 2020-01-04 05:05
is galley running? what k8s are you on?

**Comment by weichanghuan** [comment] 2020-01-04 05:10
> is galley running? what k8s are you on?

[root@k8s-mastet istio-1.4.2]# kubectl get po
NAME                              READY   STATUS    RESTARTS   AGE
details-v1-78d9dc6c4-4m26w        2/2     Running   0          12h
productpage-v1-6769d979fd-kspm8   2/2     Running   0          12h
ratings-v1-69967884bb-zrngl       2/2     Running   0          12h
reviews-v1-5c6ff6fff8-k6cq6       2/2     Running   0          12h
reviews-v2-bd779d6cc-274m7        2/2     Running   0          12h
reviews-v3-db6f58444-t77jd        2/2     Running   0          12h
[root@k8s-mastet istio-1.4.2]# kubectl get po -n istio-system
NAME                                      READY   STATUS    RESTARTS   AGE
istio-citadel-65c9f49c76-n5jpj            1/1     Running   0          12h
istio-galley-c5cb9c77d-8k9pm              1/1     Running   0          12h
istio-ingressgateway-656846d489-4l2pk     1/1     Running   0          12h
istio-pilot-568fd746c8-b2hfk              2/2     Running   3          12h
istio-policy-79f475c566-lmbl4             2/2     Running   0          12h
istio-sidecar-injector-59ccc94d59-4xrg4   1/1     Running   0          12h
istio-telemetry-6f699b8967-k8n72          2/2     Running   0          12h
prometheus-c8fdbd64f-8vdvz                1/1     Running   0          12h

**Comment by weichanghuan** [comment] 2020-01-04 05:10
> is galley running? what k8s are you on?

galley is ok ，

**Comment by weichanghuan** [comment] 2020-01-04 05:12
> is galley running? what k8s are you on?

you need k8s info or istio info?

**Comment by weichanghuan** [comment] 2020-01-04 05:13
> is galley running? what k8s are you on?

my k8s on vm

**Comment by weichanghuan** [comment] 2020-01-04 05:14
> is galley running? what k8s are you on?

my k8s on vm ,not on cloud

**Comment by howardjohn** [comment] 2020-01-04 05:20
the error is from API server calling galley. So maybe there are some connectivity issues between those since you have a custom k8s setup

**Comment by weichanghuan** [comment] 2020-01-04 05:27
> the error is from API server calling galley. So maybe there are some connectivity issues between those since you have a custom k8s setup

ok，tks，i am bad

**Comment by phallamen** [comment] 2020-01-30 08:02
do you have solution for this? i also have same issue.

**Comment by Dirk-c-Walter** [comment] 2020-02-21 21:27
looks like a dupe of this issue?
https://github.com/istio/istio/issues/17162

It's seemsthat it is related to reinstalling istio?

**Comment by Stolr** [comment] 2020-03-02 08:15
Same here 

Istio 1.4.5 - Kube 1.17.3 - Fresh install

```
 Internal error occurred: failed calling webhook \"pilot.validation.istio.io\": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 10.109.38.228:443: connect: connection refused
```

Setting 
```
global:
  configValidation: false
```

Does not resolve the issue

Regards

**Comment by yaakov-berkovitch** [comment] 2020-03-19 12:51
> Same here
> 
> Istio 1.4.5 - Kube 1.17.3 - Fresh install
> 
> ```
>  Internal error occurred: failed calling webhook \"pilot.validation.istio.io\": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 10.109.38.228:443: connect: connection refused
> ```
> 
> Setting
> 
> ```
> global:
>   configValidation: false
> ```
> 
> Does not resolve the issue
> 
> Regards

I just tried to install istio 1.5.0 and failed on the same. Did you succeed to handle the failure ?

**Comment by desek** [comment] 2020-03-26 07:56
I just ran into this issue after an uninstall of Istio 1.4.6 and an attempt to reinstall.
I resolved the issue by deleting the validatingwebhookconfigurations named `istio-galley` which is created by the istio-galley component (in other words, not by the helm chart).

**Comment by ijunbin** [comment] 2020-04-08 08:32
i have the same issuce when reinstall istio and the solution of @desek  can work
maybe you should see [this](https://preliminary.istio.io/docs/ops/common-problems/validation/#creating-configuration-fails-with-no-such-hosts-or-no-endpoints-available-errors)

**Comment by yingchi1994** [comment] 2020-06-16 08:05
**SOLUTION is here!** I also encountered the same problem. I checked a lot of solutions on Google, and almost none of them worked. Only one method succeeded, that is, modify the startup parameters of kube-apiserver, add `enable-aggregator-routing=true`, and then the problemIt was successfully solved! If you encounter the same problem, be sure to try this method！（I used kubeadm cluster）

**Comment by bharath0208** [comment] 2020-06-19 22:57
@yingchi1994 Can you explain the steps clearly n what needs to be modified.   I am using an IBM cloud Kubernetes cluster and i am having trouble in installing istio.

`2020-06-19T22:25:51.665595Z	error	installer	failed to create "EnvoyFilter/istio-system/metadata-exchange-1.4": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: context deadline exceeded`

**Closed** 2020-07-31 05:01 UTC
Labels: lifecycle/needs-triage
