### ISSUE TITLE
istio ingressgateway connection refused on port 31380

### ISSUE THREAD

**Issue by ssubramanian123** [istio/istio#9943] opened 2018-11-13 21:53 UTC
**Describe the bug**
Not able to hit ingress gateway svc on port 31380. Getting connection refused error.  I have deployed istio in our k8s 1.10.8 cluster, all the pods are up and running. Gateway svc got deployed with nodeport and the service is exposed with nodeport 31380. When I try to hit the service from the node or from the container getting connection refused error. 
`[centos@--kubernetes-88.88.88.88 ~]$ curl http://88.88.88.88:31380/hello
curl: (7) Failed connect to 88.88.88.88:31380; Connection refused`

**Expected behavior**
It should return hello version.
`[centos@myinstance ~]$ curl http://88.88.88.88:31380/hello
Hello version: v2, instance: helloworld-v2-7dd57c44c4-rhd67
`

**Steps to reproduce the bug**
Istio Deployment steps

curl -L https://git.io/getLatestIstio | sh -

kubectl --kubeconfig=config apply -f istio-1.0.3/install/kubernetes/helm/istio/templates/crds.yaml

helm template istio-1.0.3/install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort > istio.yaml

kubectl --kubeconfig=config create namespace istio-system

kubectl --kubeconfig=config apply -f istio.yaml

**Version**
K8s : 1.10.8
istio 1.0.3

**Installation**
Istio Deployment steps

curl -L https://git.io/getLatestIstio | sh -

kubectl --kubeconfig=config apply -f istio-1.0.3/install/kubernetes/helm/istio/templates/crds.yaml

helm template istio-1.0.3/install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort > istio.yaml

kubectl --kubeconfig=config create namespace istio-system

kubectl --kubeconfig=config apply -f istio.yaml

**Environment**
CentOS

**Cluster state**
AWS kubernetes cluster

**Comment by chinglinwen** [comment] 2018-11-23 03:00
I encounter the same issue.

I found it had worked one time, after I delete the pod to see if it can working again, then it's not working anymore.

For the working case I see the following logs

```

[2018-11-22 06:52:27.094][26][info][config] external/envoy/source/server/listener_manager_impl.cc:908] all dependencies initialized. starting workers
[2018-11-22 06:53:27.095][26][info][main] external/envoy/source/server/drain_manager_impl.cc:63] shutting down parent after drain

//insert comment: here too much gap?

[2018-11-22 09:38:38.362][26][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:500] add/update cluster outbound|3000||grafana.istio-system.svc.cluster.local starting warming
[2018-11-22 09:38:38.363][26][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|3000||grafana.istio-system.svc.cluster.local complete
[2018-11-22 09:38:38.376][26][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_80'
```

It's almost cause three hours to show the listener setup log ( too long ).

For the second time I try, it never show the add/update listener log, and so it's not working for ten hours now. 

For the not working case, the log always stopped at ```shutting down parent after drain```.

Version
K8s : 1.11.3
istio 1.0.3

**Comment by yudar1024** [comment] 2018-12-15 09:13
same issue here

**Comment by yudar1024** [comment] 2018-12-17 10:03
after delete helloworld sample pods. it never work again. even you redeploy it with out any changes

**Comment by karthimohan** [comment] 2018-12-19 22:30
You need to create a Gateway so istio ingress controller can bind to that port 
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

**Comment by tonyjt** [comment] 2018-12-20 14:10
ame issue here

**Comment by lukesiler** [comment] 2018-12-28 19:34
I am seeing same issue here with our own gateway running in minikube.  After deleting ingress gateway pod, it seems to come up just fine.

Failure log tail:

[2018-12-28 17:56:15.656][18][info][main] external/envoy/source/server/server.cc:401] all clusters initialized. initializing init manager
[2018-12-28 17:56:15.769][18][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_443'
[2018-12-28 17:56:15.771][18][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_80'
[2018-12-28 17:56:15.805][18][info][config] external/envoy/source/server/listener_manager_impl.cc:908] all dependencies initialized. starting workers
[2018-12-28 17:57:15.798][18][info][main] external/envoy/source/server/drain_manager_impl.cc:63] shutting down parent after drain

Success log tail:

[2018-12-28 19:26:07.941][18][info][main] external/envoy/source/server/server.cc:401] all clusters initialized. initializing init manager
[2018-12-28 19:26:07.962][18][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_443'
[2018-12-28 19:26:07.965][18][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_80'
[2018-12-28 19:26:07.970][18][info][config] external/envoy/source/server/listener_manager_impl.cc:908] all dependencies initialized. starting workers

Envoy drain manager issue?

**Comment by lukesiler** [comment] 2018-12-28 19:43
Whoops, that drain manager seems to be a red herring as success case exhibits that also after pod reschedule.

[2018-12-28 19:26:07.941][18][info][main] external/envoy/source/server/server.cc:401] all clusters initialized. initializing init manager
[2018-12-28 19:26:07.962][18][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_443'
[2018-12-28 19:26:07.965][18][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_80'
[2018-12-28 19:26:07.970][18][info][config] external/envoy/source/server/listener_manager_impl.cc:908] all dependencies initialized. starting workers
[2018-12-28 19:27:07.971][18][info][main] external/envoy/source/server/drain_manager_impl.cc:63] shutting down parent after drain
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:160] Add a new Referenced for check cache: Absence-keys: destination.port, destination.uid, source.ip, Exact-keys: context.protocol, context.reporter.kind, destination.service, source.namespace, source.uid,
[2018-12-28T19:27:11.665Z] "GET /api/v1/status HTTP/1.1" 401 - 0 15 64 61 "172.17.0.1" "Go-http-client/1.1" "9e7969b7-421f-9d21-a2e2-7081c8c0794f" "192.168.99.100:31390" "172.17.0.19:8443"

**Comment by kbsivacse** [comment] 2019-01-09 06:03
I'm also facing same issue with Istio 1.0.3 running Kubernetes cluster 1.10.0 & minikube 0.25.2 on Windows 10 platform. Any workaround or solution to this?

**Comment by erks** [comment] 2019-01-15 06:15
Same here. Istio 1.0.5 on Kubernetes 1.11.5 (EKS). The workaround so far is to add `livenessProbe` and `readinessProbe` on one of the ports, so that the pod get restarted when it fails.

**Comment by sikka** [comment] 2019-01-15 07:31
@erks did you add `livenessProbe` to `bookinfo-gateway.yaml`? Can you please share the config?

**Comment by erks** [comment] 2019-01-15 09:17
@sikka i did that on the ingress gateway deployment (https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/gateways/templates/deployment.yaml).

**Comment by peter-fe** [comment] 2019-01-28 13:13
Same issue here, seems to be a major flaw in ingress gateway creation.

We currently run 10 clusters with Istio 1.0.4 on k8s 1.10.12.
Just a plain helm install with the Istio provided charts, not thing special regarding ingress.

If we do a scheduled restart of the ingress-gateways, which all where running ok before the recreation of the pods, some of them don't start up correctly.

This also happens when the horizontal pod autoscaler kicks in and creates new pods, some of them do show the same issue and don't except traffic until you restart them (sometimes several times).

The ones that fail are missing the [info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_xxx' entries in the log file and a netstat in the container also don't show up the expected http and https ports. 

**not-working**
`root@istio-ingressgateway-6d5846444-wfvkq:/# netstat -a
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 *:15090                 *:*                     LISTEN     
tcp        0      0 localhost:15000         *:*                     LISTEN     
tcp        0      0 istio-ingressgate:40894 istio-pilot.istio:15010 ESTABLISHED
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         DGRAM                    7282509  @envoy_domain_socket_0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
root@istio-ingressgateway-6d5846444-wfvkq:/# `

**working**
`root@istio-ingressgateway-6b4cf5599-8ssnv:/# netstat -a
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 *:80                    *:*                     LISTEN     
tcp        0      0 *:15090                 *:*                     LISTEN     
tcp        0      0 localhost:15000         *:*                     LISTEN     
tcp        0      0 *:443                   *:*                     LISTEN     
tcp        0      0 istio-ingressgate:32924 istio-pilot.istio:15010 ESTABLISHED
tcp        0      0 istio-ingressgatewa:443 gke-mpcard-cluste:50539 ESTABLISHED
tcp        0      0 istio-ingressgate:56604 10.16.7.4:9091          ESTABLISHED
tcp        0      0 istio-ingressgate:48356 10.16.7.6:9091          ESTABLISHED
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         DGRAM                    7549633  @envoy_domain_socket_0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@`

**Comment by gtseres** [comment] 2019-03-18 13:02
Hello! Is the issue on the Envoy side? If so, is there a bug in the Envoy repo for that?

**Comment by peter-fe** [comment] 2019-03-20 17:00
I was not able to track that down further, some assumption was that it is pilot related and the configure never gets applied to the proxy. But it's also possible it fails in Envoy itself.

**Comment by viharikrishna** [comment] 2019-03-28 17:42
@peter-fe We are facing a similar kind of issue. Did you get a chance to reproduce this?

**Comment by peter-fe** [comment] 2019-03-31 09:03
@viharikrishna, by scaling up the ingressgateway e.g. up to five pods, quite regular, one of them shows the described issue and does not accept traffic.

**Comment by gtseres** [comment] 2019-03-31 16:23
We have also managed to reproduce that with multiple scale outs/ins with 1.0.2, similarly to what @peter-fe described. We could not reproduce it with Istio 1.1.1 though.

**Comment by bitva77** [comment] 2019-04-03 16:32
We're having the same issue with Kubernetes 1.13 and Istio 1.1.1.  NodePort.

kubeadm install on RedHat 7.6.

Istio 1.0.6 works fine.

It is listening on port 31380 (or 80 if I change it) but it does not accept connections.  Using netcat I can verify it's not a firewall issue or anything.  This is something with Istio.

Restarting pods does not fix the issue even temporarily for us.

**Comment by peter-fe** [comment] 2019-04-04 04:54
@bitva77, at least restarting (several times if needed) should give you a funktional pod. If the problem is persistend,  I would assume it's something different.
We an error like this when using named target ports in the K8s service were the port name don't start with the protocol (http_targetportname).
If looking up the sidecar logfile there should be an add service entry with the pod ip and your Port.

**Comment by bitva77** [comment] 2019-04-04 16:16
@peter-fe thanks.  I must be having a different issue.  Istio is listening on port 31380 but I can't connect to it at all so it's not even getting far enough to Istio

```
netstat -an |grep 31380
tcp6       0      0 :::31380                :::*                    LISTEN
```
```
telnet 10.245.2.95 31380
Trying 10.245.2.95...
telnet: connect to address 10.245.2.95: Connection refused
```

Though Istio appears to be the one refusing the connection as outside of Kubernetes, on the server, I can listen and connect on that port (using netcat for example).

Only thing useful out of the gateway logs is this:

```
[2019-04-03 23:35:19.930][13][warning][main] [external/envoy/source/server/server.cc:525] shutting down admin due to child startup
[2019-04-03 23:35:19.930][13][warning][main] [external/envoy/source/server/server.cc:533] terminating parent process
[2019-04-03 23:35:19.933][27][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:102] gRPC config stream closed: 14, no healthy upstream
[2019-04-03 23:35:19.933][27][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:56] Unable to establish new stream
[2019-04-03 23:36:21.054][13][warning][main] [external/envoy/source/server/server.cc:405] caught SIGTERM
2019-04-03T23:36:21.058771Z     info    Epoch 0 exited normally
[2019-04-04 00:08:06.590][27][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:102] gRPC config stream closed: 13
```

I can't tell if this is an issue or not.

I'll start a new thread with this...

**Comment by goyalnikhil02** [comment] 2019-04-10 11:58
curl http://$INGRESS_HOST:$INGRESS_PORT/hello

curl: (7) Failed to connect to 192.168.21.222 port 31380: Connection refused
any solution for this.

**Comment by goyalnikhil02** [comment] 2019-04-11 12:52
follow this link.:https://hackernoon.com/ingress-and-istio-gateway-resource-e5958846c26b

**Comment by arindam-b** [comment] 2019-05-11 22:12
Version: 1.1.15

I am encountering following issue that stops my application and my pod is not able to launch.
I found the following error in the stack drive and the subsequent line says, terminating task executor.

```
[warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

So the application never launches.

As specified in the thread I have delete istio-pilot but the error persists.

Any idea how to fix?

**Comment by peter-fe** [comment] 2019-05-15 05:58
I can confirm what @gtseres mentioned some comments ago, that the original issue is not reproduce able on > Istio 1.1
I would suggest to close this issue, as it gets more and more used to address similar, but not directly related issues.

**Comment by arindam-b** [comment] 2019-05-15 12:44
Yes it is. I am not encountering it with version 1.1.5

**Comment by halradaideh** [comment] 2019-05-27 10:02
same problem as @goyalnikhil02 , connection refused on istio-ingressgateway on port 31380 from all nodes except the one that proxy runs on

Istio version 1.1.5

**Comment by halradaideh** [comment] 2019-05-27 10:23
on 1.1.7 too

**Comment by hanymahajna** [comment] 2019-06-11 14:27
i see the same issue in 1.1.2 and in 1.1.8
What i saw that it listen in tcp6 port so the ELB healthcheck failed
When i changed the healthcheck manually to another port (like 22) the listen in tcp it's working fine
I think the problem happened cause of tcp6 and not tcp (what the elb in aws expect to use)

**Comment by howardjohn** [comment] 2019-10-01 01:51
Sorry we didnt get to resolve this properly, but all issues here are reported on 1.0. Only istio 1.2-1.3 is supported now (see https://istio.io/blog/2019/announcing-1.1-eol/).

Theres been a ton of changes in this area so I would not be surprised if this is resolved. If you do see similar issues on newer versions I would encourage you to open an issues (ideally one that is reproducible, if possible)

**Closed by howardjohn** 2019-10-01 01:51 UTC
Labels: area/networking, community/help wanted, kind/customer issue
